### ISSUE TITLE
I want to add a function to export offline documents to swagger.How do I submit?

### ISSUE THREAD

**Issue by HanJunJun** [domaindrivendev/Swashbuckle.AspNetCore#1003]
![1106680-20190107000621750-840566449](https://user-images.githubusercontent.com/16394348/50805258-8907f680-132c-11e9-86bb-2aba8437663d.gif)

**Comment by domaindrivendev** [comment]
This looks well beyond the scope of what I envision for the project. Have you considered creating a separate add-on library
