### ISSUE TITLE
v5.0-beta: ModelBinder is not supported (.NetCore)

### ISSUE THREAD

**Issue by Alexander-Stulov** [domaindrivendev/Swashbuckle.AspNetCore#1010]
Version 5.0-beta

Can't generate help page if specify ModelBinder, like:
[ModelBinder(typeof(...)), FromHeader(Name = ...)] DateTimeOffset currentDate

Error thrown:
KeyNotFoundException: The given key 'Microsoft.AspNetCore.Mvc.ModelBinding.BindingSource' was not present in the dictionary.

System.Collections.Generic.Dictionary<TKey, TValue>.get_Item(TKey key)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameter(ApiDescription apiDescription, ApiParameterDescription apiParameter, ISchemaRegistry schemaRegistry)
System.Linq.Enumerable+WhereSelectListIterator<TSource, TResult>.ToList()
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)

**Comment by domaindrivendev** [comment]
Fixed with 781ceb36d4bc0eea917af8c7970ef7763a2dca69. Will be released with 5.0.0. Previews of latest master are available via myget.
