### ISSUE TITLE
Vary Schema by Media Type

### ISSUE THREAD

**Issue by KevinDockx** [domaindrivendev/Swashbuckle.AspNetCore#1011]
According to the OpenAPI 3.0 spec, schemas can vary by media type. Eg, a GET for /animals/{animalId} should be able to return something along the lines of:
```
"content": {
"application/vnd.company.cat+json": {
"schema": {
"$ref": "#/components/schemas/Cat"
}
},
"application/vnd.company.dog+json": {
"schema": {
"$ref": "#/components/schemas/Dog"
}
}
```
... and so on.  I don't seem to be able to get this to work (tried Produces and ProducesByType attributes). Is this functionality currently supported by Swashbuckle (I tried searching the issue list but didn't find an issue related to this)?  If not, is it planned?  

Thanks for your time :)

KR,
Kevin.

**Comment by domaindrivendev** [comment]
You're correct in saying that OpenAPI v3 does allow schema's to vary by media type. And, when there's multiple media type formatters (https://docs.microsoft.com/en-us/aspnet/web-api/overview/formats-and-model-binding/media-formatters) configured for your application, Swashbuckle _will_ generate a schema definition for each one.

However, your usecase seems a little different. Unless I'm mistaken, it looks like you're trying to support some form of polymorphic response (i.e. the response is an animal and _could_ be some derivative of that - cat, dog etc.). In my experience, media types are typically used for different representations of the same entity - e.g. JSON representation of a Cat, XML representation of a Cat and so on. I've never seen it used for polymorphism, and so it's unlikely to be a case that I'll be supporting anytime soon.

With said, OpenApi _does_ support polymorphic models (https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) with the use of `oneOf` and `descrimator` properties in the schema. Swashbuckle doesn't currently support this out-of-the-box but that functionality _is_ on the backlog. See #2.

**Comment by KevinDockx** [comment]
Thanks for your reply!  Maybe I should've used a better example :-) I used Cats & Dogs as that's what's being used in the OpenAPI 3 documentation.

Media types are indeed used for diferent representations of the same entity, but it can go beyond just the format.  Most APIs tend to stop at application/json & application/xml, but those aren't very specific: they only tell something about the format, not the actual type.  As web APIs are maturing towards truly RESTful APIs, media types become more important.  One of the basic ideas behind them is that they can represent an actual type, and that's typically achieved with vendor-specific media types.  

Take api/people/{id}, for example.  With an accept header of application/json, you could get back the default representation of one person.  With a vendor-specific media type in the accept header, you can specify the actual type.  Eg: vnd.company.person would return a representation of that person with firstname & lastname fields.  vnd.company.personwithconcatenatedname would return a representation of a person with a concatenated firstname/lastname, and so on.  It's still the same person, it doesn't warrant a new resource URI, but the returned representation is different.

If I'm not mistaken that's the scenario OpenAPI 3 supports with allowing schema variation by media type.  

Hope this clarifies my question :)

**Comment by domaindrivendev** [comment]
Could you point me to the OpenAPI documentation that discusses this approach?

**Comment by KevinDockx** [comment]
Hi,

I base myself on the media types section: https://swagger.io/docs/specification/media-types/ .  If you scroll down on that page to the part "Multiple Media Types", you can see the schema can be defined separately for each media type.  As the same sort of content tag is used for the request body, the other way around is possible as well: if you look at  "Differences From OpenAPI 2.0" on this page: https://swagger.io/docs/specification/describing-request-body/ it states that schemas can vary by media type.   

In fact, with a custom IOperationFilter I was able to get this to work with Swashbuckle :)  Results in: 

```
responses:
        '200':
          description: Returns the requested book
          content:
            application/vnd.marvin.book+json:
              schema:
                $ref: '#/components/schemas/Book'
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
            application/xml:
              schema:
                $ref: '#/components/schemas/Book'
            application/vnd.marvin.bookwithconcatenatedauthorname+json:
              schema:
                $ref: '#/components/schemas/BookWithConcatenatedAuthorName'
```
(output sample)

```
requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookForCreation'
          application/vnd.marvin.bookforcreation+json:
            schema:
              $ref: '#/components/schemas/BookForCreation'
          application/vnd.marvin.bookforcreationwithamountofpages+json:
            schema:
              $ref: '#/components/schemas/BookForCreationWithAmountOfPages'
```
(input sample)

I ran these through the validator you can find at https://editor.swagger.io/, and both are valid when validating against OpenAPI 3.

So my issue is more or less solved via an OperationFilter, yet I think it would be nice if this was supported out of the box.

**Comment by clawrenceks** [comment]
@KevinDockx I have a requirement which is exactly as you describe here and I came across this issue whilst searching for solutions.

Before I start to look at creating my own OperationFilter, I wondered if the one you reference in your comment above is available anywhere? Such as a guthub repo or blog post?

**Comment by hades200082** [comment]
I have exactly this problem too.

I would hope that this issue could be reopened and a solution added that would automatically handle this scenario within Swashbuck OpenAPI generation.

**Comment by mihaidariesoftvision** [comment]
@KevinDockx could you please post a link to your OperationFilter example?

**Comment by KevinDockx** [comment]
@mihaidariesoftvision : there's a sample of that here: https://github.com/KevinDockx/DocumentingAspNetCoreApisWithOpenAPI (or, more specifically: https://github.com/KevinDockx/DocumentingAspNetCoreApisWithOpenAPI/tree/master/Finished%20sample/Library.API/OperationFilters).  The sample targets Swasbhuckle v5 beta, so things might have changed...

**Comment by VincentPaukgyi** [comment]
@KevinDockx
I am using the Swashbuckle.AspNetCore.SwaggerGen, Version=5.5.0.0, and this is the registration method. Schema=context.SchemaRepository.GetOrAdd(typeof(AuthorForCreationWithDateOfDeathDto),string, Func<OpenApiSchema>).

It needs the additional parameter for schemaId and Func. How can I implement it?
Thank you in advance.

**Comment by VincentPaukgyi** [comment]
@KevinDockx 
Your sample project, custom media type for schema variation is not working for input.
![image](https://user-images.githubusercontent.com/13621740/85229358-48f8de80-b40f-11ea-998b-9722a44f8563.png)

**Comment by KevinDockx** [comment]
@VincentPaukgyi: as mentioned in my original post I've used v5 beta, things might have changed since then - apparently, they have.  I haven't looked into a solution for this yet.
