### ISSUE TITLE
Model for generic & enums

### ISSUE THREAD

**Issue by 10der** [domaindrivendev/Swashbuckle.AspNetCore#1012]
Hi!

my model looks like is not accurate

```
[ProducesResponseType(typeof(BaseOperationResult<ProcessWorkInOpCode>), (int)HttpStatusCode.OK))]
```

```
Test.Common.Models.OperationResults.BaseOperationResult`1[[Test.Work.Business.Models.Enums.ProcessWorkInOpCode, Test.Work.Business, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]{
message	string
readOnly: true
operationCode	string
readOnly: true
Enum:
Array [ 3 ]
}
```
why?

Thank you, 
O.

**Comment by domaindrivendev** [comment]
I'm assuming you're referring to the auto-generated `schemaId` for the generic type? If so, the generated id has been simplified as of #1041 and as a result the generic type above would map to a schema Id of `ProcessWorkInOpCodeBaseOperationResult`.
