### ISSUE TITLE
TypeNameHandling.Auto in json DefaultSettings breaks index.html

### ISSUE THREAD

**Issue by Grax32** [domaindrivendev/Swashbuckle.AspNetCore#1013]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/c8d8edbf1a04ccf5662ad961fd373adaf0d12e32/src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs#L109

SerializeToJson inherits DefaultSettings.  Setting TypeNameHandling to Auto in DefaultSettings breaks Swashbuckle's index.html because it changes how the enum list is serialized.

It looks like you could possibly use JsonSerializer.Create to get around inheriting DefaultSettings.

**Comment by domaindrivendev** [comment]
Interested in submitting a PR?

**Comment by Grax32** [comment]
I'll see what I can do.   I made the code changes in my fork, but I haven't executed this code, and I might not be able to test for a few days.

https://github.com/Grax32/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.ReDoc/ReDocMiddleware.cs

**Comment by domaindrivendev** [comment]
Fixed by e623015

**Comment by Grax32** [comment]
Thank you
