### ISSUE TITLE
Change External Dependency of fonts.googleapis.com

### ISSUE THREAD

**Issue by moxixuan** [domaindrivendev/Swashbuckle.AspNetCore#1018]
hi, when it load the ~/swagger/index.html, 
https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700" rel="stylesheet
it doesn't work, i'm in china. I wonder if GFW blocked it lately,Because it work well when use ssr to load it. So how can i change this href ? thanks.

**Comment by moxixuan** [comment]
![d9 _80k29 zpag1b7a2 0](https://user-images.githubusercontent.com/19483437/51603003-73591a80-1f43-11e9-97a4-bf2352078996.png)

**Comment by ttutko** [comment]
I was just about to post an issue for this but not because of being in China. This is marketed as a self contained copy of swagger-ui but these fonts it tries to access are not self contained. Would prefer to have these self contained as it causes significant delay if you are on a network that either isn't connected to the internet or can't resolve googleapis.com like the original poster above.

**Comment by ttutko** [comment]
I would update the issue title to be something like "Remove External Dependency of fonts.googleapis.com"

**Comment by emilssonn** [comment]
A quick/temporary fix is to use your own index.html, https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-indexhtml.

**Comment by moxixuan** [comment]
> 
> 
> I would update the issue title to be something like "Remove External Dependency of fonts.googleapis.com"

Ok,thanks

**Comment by moxixuan** [comment]
> 
> 
> A quick/temporary fix is to use your own index.html, https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-indexhtml.

Thank you, that's exactly what I need.

**Comment by ttutko** [comment]
Wondering why you closed this? I agree you can work around it with a custom index.html but IMO the dependency should still be removed by default.

**Comment by moxixuan** [comment]
> 
> 
> Wondering why you closed this? I agree you can work around it with a custom index.html but IMO the dependency should still be removed by default.

When I got home, I found that I could open fonts.googleapis.com normally, so this is not the reason for GFW, then I consulted my colleague, he said that it can also be accessed normally, then I found the reason, my computer settings The DNS server could not resolve the domain name, so after I reassigned it, everything was fine. As you said, it can work around it with a custom index, this is a good idea, but I think Dependency of fonts.googleapis.com is not a bad idea, because we can change it at any time.
