### ISSUE TITLE
ProducesDefaultResponseType does not generate the description property

### ISSUE THREAD

**Issue by arturek** [domaindrivendev/Swashbuckle.AspNetCore#1023]
Methods marked with ProducesDefaultResponseType produce response specifications without mandatory 'description' property (as reported by http://editor.swagger.io/). The correct output is shown in https://swagger.io/docs/specification/describing-responses/#default. The ProducesResponseType attribute works correctly.

## VERSION: ##
4.0.1 and 5.0.0-beta

## STEPS TO REPRODUCE: ##
add following two attributes to an action method of a controller. 
```
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesDefaultResponseType]
```

## EXPECTED RESULT: ##
The produced YAML should be
```
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ProblemDetails'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ProblemDetails'

```
## ACTUAL RESULT: ##
The generated YAML has no description property for default case.
```
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/ProblemDetails'
        default:
          schema:
            $ref: '#/definitions/ProblemDetails'
```

**Comment by domaindrivendev** [comment]
Fixed with 56f9ed384615ce1721e0964b45c1da20eb97b1c4
