### ISSUE TITLE
Multiple IFormFile upload

### ISSUE THREAD

**Issue by twsl** [domaindrivendev/Swashbuckle.AspNetCore#1029]
[#902](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/902) already adresses this issue, but since master/5.0.0-beta now already should support OpenAPI 3.0 standard, it is time for a bug report.

There is no support for multiple file upload via e.g. `List<IFormFile>`, swagger simply posts 
```
-----------------------------217261477111538
Content-Disposition: form-data; name="files"

[object File],[object File]
-----------------------------217261477111538
```
instead of properly resolving the file objects to multiple files. The ui is fine tho.
See:
* https://swagger.io/docs/specification/describing-request-body/file-upload/
* https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#considerations-for-file-uploads
* https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#special-considerations-for-multipart-content

**Comment by twsI** [comment]
Correct request would look like this
```
-----------------------------217261477111538
Content-Disposition: form-data; name="files"; filename="file.txt"

<context>
-----------------------------217261477111538
Content-Disposition: form-data; name="files"; filename="file.txt"

<context>
-----------------------------217261477111538
```
I am investigating this now

**Comment by domaindrivendev** [comment]
This an open issue with the swagger-ui:
https://github.com/swagger-api/swagger-ui/issues/4600

**Comment by twsI** [comment]
The UI actually isn't a problem at all for me ![ui](https://i.imgur.com/pPQjpJA.png)

**Comment by domaindrivendev** [comment]
It may “look” fine but it’s the UI that submits the request and it’s doing so incorrectly. It’s not sending as multiple parts.

**Comment by crclz** [comment]
I've run into the same issue

**Comment by aladd04** [comment]
I can confirm this is still an issue on the latest RC version (5) with .NET Core 3.1.

**Comment by domaindrivendev** [comment]
As mentioned above, this is an open issue with the [swagger-ui](https://github.com/swagger-api/swagger-ui/issues/4600) and is not specific to Swashbuckle. It won't be resolved in Swashbuckle, until it's resolved in the upstream swagger-ui library.

**Comment by ToMakeSense** [comment]
@domaindrivendev Multiple files uploading can't be achieved by `List<IFormFile>` as parameter, however, it can be achieved  by `IFormCollection formCollection`

> ![image](https://user-images.githubusercontent.com/6244148/83400046-ce9ef500-a434-11ea-8d53-1365d9185b4c.png)

**Comment by ToMakeSense** [comment]
The swagger-ui issue should be fixed in  its latest release [releases/tag/v3.26.0](https://github.com/swagger-api/swagger-ui/releases/tag/v3.26.0)

> ## Bug Fixes
> * OAS3 upload file when array items are type=string format=binary (#6040)

**Comment by domaindrivendev** [comment]
Will include latest version of swagger-ui with next SB release.

**Comment by domaindrivendev** [comment]
See commit 3e87212fab8c10441b592ae81fc263b1ab631acf
