### ISSUE TITLE
FromBody typed parameter is shown as query and divided in subitems

### ISSUE THREAD

**Issue by erikdario** [domaindrivendev/Swashbuckle.AspNetCore#1031]
Hi guys,
this is my Get method in controller. I use from body parameter to get values.
It works fine with all clients.

public Inventario Get([FromBody]FiltroInventario  filtro)
        {
            //SOME CODE
        }

- FiltroInventario is like this (sry for VBNET syntax)

Public Class FiltroInventario   

    Public UtenteCorrente AS String

    Public ListaReparti As List(Of Reparto) = New List(Of Reparto)

    Public ListaDistretti As List(Of Distretto) = New List(Of Distretto)

End Class

As you can see, it seems that swagger broke object in sub arrays as query params.
I only want a raw body param to put my json object

![image](https://user-images.githubusercontent.com/8337060/52206752-84772500-287b-11e9-886a-570085a100bf.png)

**Comment by domaindrivendev** [comment]
I just tried this with the latest version (`5.6.3`) and no repro. Going to close for now, but if you're still experiencing an issue please put together a minimal app (i.e. start from empty proj) that repro's and post to github so I can pull down and troubleshoot.
