### ISSUE TITLE
Moving to net core 2.1 and Microsoft.AspNetCore.App 2.1.1 stops Swashbuckle 4.0.1 displaying IFormFile with upload button

### ISSUE THREAD

**Issue by zakkra** [domaindrivendev/Swashbuckle.AspNetCore#1033]
## VERSION: ##
4.0.1

## STEPS TO REPRODUCE: ##
Open Swashbuckle.AspNetCore solution from 4.0.1 tag. 
Right click the Basic project > Properties > Application and set Target Framework to .Net Core 2.1 (do the same for the integration test project)
Remove all nuget packages from the project references
Add Microsoft.AspNetCore.App 2.1.1 nuget
Run the Basic project
Navigate to  FileUploads and expand post file method

## EXPECTED RESULT: ##
Upload text box with the browse button

## ACTUAL RESULT: ##
Multiple text boxes shown for:

ContentTypestring(query) |  
ContentDispositionstring(query) |  
Headersobject(query) |  
Lengthinteger($int64)(query) |  
Namestring(query) |  
FileNamestring(query)

## ADDITIONAL DETAILS ##
I beleive CancellationToken parameters also stop being handeled properly in this case

**Comment by rdeveen** [comment]
For me it helps to set the compatibility version?
```C#
public void ConfigureServices(IServiceCollection services)
{
        services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
}
```

**Comment by ankitsinghal1302** [comment]
@zakkra Curious if you found a solution for this issue ?

**Comment by zakkra** [comment]
It has been a while, make sure you are using the latest version of swashbuckle thay might have fixed it by now but if not you can use this custom filter:
`
/// <summary>
/// Make IFormFile parameters or objects with properties of IFormFile type treated as files for swagger integration purposes
/// </summary>
    public class SwaggerFormFileOperationFilter : IOperationFilter
    {

        private static readonly ImmutableArray<string> IFormFilePropertyNames = typeof(IFormFile)
            .GetTypeInfo()
            .DeclaredProperties
            .Select(p => p.Name)
            .ToImmutableArray();

        public void Apply(Operation operation, OperationFilterContext context)
        {
            var parameters = operation.Parameters;
            if (parameters == null) return;

            var @params = context.ApiDescription.ActionDescriptor.Parameters;
            if (parameters.Count == @params.Count) return;

            var formFileParams = (from parameter in @params where parameter.ParameterType.IsAssignableFrom(typeof(IFormFile)) select parameter).ToArray();
            var iFormFileType = typeof(IFormFile).GetTypeInfo();
            var containerParams = @params.Select(p => new KeyValuePair<ParameterDescriptor, PropertyInfo[]>(p, p.ParameterType.GetProperties()))
                .Where(pp => pp.Value.Any(p => iFormFileType.IsAssignableFrom(p.PropertyType)))
                .SelectMany(p => p.Value.Select(pp => pp))
                .ToImmutableArray();
            if (!(formFileParams.Any() || containerParams.Any())) return;

            var consumes = operation.Consumes;
            consumes.Clear();

            consumes.Add("application/form-data");

            if (!containerParams.Any())
            {
                FixFileWhenParameter(parameters, formFileParams);
            }
            else
            {
                FixFileWhenProperty(containerParams, parameters, iFormFileType);
            }
        }

        private static void FixFileWhenProperty(ImmutableArray<PropertyInfo> containerParams, IList<IParameter> parameters, TypeInfo iFormFileType)
        {
            var paramsToRemove = new List<IParameter>();
            foreach (var parameter in containerParams)
            {
                var parameterFilter = parameter.Name + ".";
                paramsToRemove.AddRange(from p in parameters where p.Name.StartsWith(parameterFilter) select p);
            }

            paramsToRemove.ForEach(x => parameters.Remove(x));
            foreach (var parameter in containerParams)
            {
                if (iFormFileType.IsAssignableFrom(parameter.PropertyType))
                {
                    var originalParameter = parameters.FirstOrDefault(param => param.Name == parameter.Name);
                    parameters.Remove(originalParameter);
                    parameters.Add(new NonBodyParameter
                    {
                        Name = parameter.Name,
                        Required = originalParameter?.Required ?? false,
                        Type = "file",
                        In = "formData"
                    });
                }
            }
        }

        private static void FixFileWhenParameter(IList<IParameter> parameters, ParameterDescriptor[] formFileParams)
        {
            var nonIFormFileProperties = parameters.Where(p => !(IFormFilePropertyNames.Contains(p.Name) && string.Compare(p.In, "formData", StringComparison.OrdinalIgnoreCase) == 0))
                .ToImmutableArray();

            parameters.Clear();
            foreach (var parameter in nonIFormFileProperties) parameters.Add(parameter);

            foreach (var parameter in formFileParams)
            {
                parameters.Add(new NonBodyParameter
                {
                    Name = parameter.Name,
                    Type = "file",
                    In = "formData"
                });
            }
        }
    }`

**Comment by domaindrivendev** [comment]
Closing as the latest version `5.2.0` fully supports `IFormFile` out-of-the-box, removing the need for a custom filter entirely.
