### ISSUE TITLE
Enums + StringLength attribute - is it a bug to honour both?

### ISSUE THREAD

**Issue by freeranger** [domaindrivendev/Swashbuckle.AspNetCore#1037]
Not sure if this is a "bug" or not.
If I have a model with an enum property and mark it up with a stringlenght attribute:
```     [StringLength(100)]
        public FooEnum Bar{ get; set; }
```
then it appears in the swagger.json as:
```
 "fooEnum":{
   "description":"The foo enum",
   "maxLength":100,
   "minLength":0,
   "enum":["unknown","foo1","foo2"],
   "type":"string"
}
```
Now leaving aside the question of whether or not it makes sense for the C# developer to have put a StringLength attribute on there, does it make sense for the swagger to be generated with min/max lengths given that it is an enum and therefore has a fixed set of values?

This came up when trying to use swagger-codegen to generate a C# client - which tried to treat it as an enum (because it is one) but also tried to generate some validation code because of [StringLength] which means the code does not compile because an enum value doesn't have a length.
I am going to raise the issue with the swagger-codegen people because it should generate valid C#, but it may be that the min/max length properties should never have been generated at all, which is why I am posting here too.

**Comment by domaindrivendev** [comment]
I'm comfortable pushing this one back as a developer responsibilty to use the validation attributes correctly.
