### ISSUE TITLE
Wrongly rounded maximum value in swagger.json for RangeAttribute with lnt64.MaxValue

### ISSUE THREAD

**Issue by thomaslevesque** [domaindrivendev/Swashbuckle.AspNetCore#1038]
I'm using Swashbuckle.AspNetCore 4.0.1

I have a property like this:

```csharp
        [Range(typeof(long), "0", "9223372036854775807")]
        public long Size { get; set; }
```

(note: I can't use `Int64.MaxValue` in the attribute, because it accepts a `double`, not a `long`, and the value is rounded up)

But in the generated swagger.json, the maximum value for this property is 9223372036854776000, which is greater than `Int64.MaxValue`. It's because the value is converted to string, then parsed as Double:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/28e8673e2579b406bc5120b89589aee3b5b79341/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaExtensions.cs#L23

The problem seems to be fixed on master, which uses Decimal instead of Double:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f85d3e663caeda076d81adfde5e5ad90102d1fd/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/OpenApiSchemaExtensions.cs#L22

But I'd rather not use a beta just for this problem... Would you consider releasing a 4.0.2 with this fix?

**Comment by egorshulga** [comment]
Hi @domaindrivendev! I faces the same issue. Could the fix be released as a patch for current stable version? Thanks!

**Comment by egorshulga** [comment]
@domaindrivendev I'd open a PR, but I guess destination branch should not be `master`, cause it is a fix for v4. Should a separate branch be created with the fix, so a minor v4 release would be created from it?

**Comment by domaindrivendev** [comment]
Not sure exactly when but this looks to resolved for some time - @thomaslevesque if you upgrade to the latest version (`5.6.3` at time of writing), your issue should be resolved

**Comment by FontanaVincentCdm** [comment]
This issue still persist in 6.5.0

**Comment by martincostello** [comment]
New issue with a repro please.
