### ISSUE TITLE
Ignore 3rd party libraries with a Filter

### ISSUE THREAD

**Issue by sven5** [domaindrivendev/Swashbuckle.AspNetCore#1044]
Hi,

I already asked this question on [Stackoverflow ](https://stackoverflow.com/questions/54712666/ignore-3rd-party-controller-actions-in-swagger) but didn't get an appropriate answer.
My solutions uses 3rd party components that are exposing Web API endpoints. I have no control about this library so my question is how to set up a filter to ignore this library. I don't want to include this in any doc.

Currently the following exception is thrown:
**NotSupportedException: Ambiguous HTTP method for action - DevExpress.AspNetCore.Reporting.QueryBuilder.QueryBuilderController.Invoke (DevExpress.AspNetCore.Reporting.v18.2). Actions require an explicit HttpMethod binding for Swagger 2.0**

**Edit:** I already tried to use an OperationFilter but was unsuccessful because Apply doesn't get called for the 3rd party lib.

Thanks
Sven

**Comment by domaindrivendev** [comment]
You can configure a custom “DocInclusionPredicate” (see readme) to filter out ApiDescriptions for actions in a given namespace

**Comment by sven5** [comment]
Thank you,

I got it working.

Regards
Sven
