### ISSUE TITLE
client_id and client_secret not posted with oauth application flow

### ISSUE THREAD

**Issue by kspearrin** [domaindrivendev/Swashbuckle.AspNetCore#1053]
<PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />

Startup.cs config

    services.AddSwaggerGen(config =>
    {
        config.SwaggerDoc("v1", new Info { Title = "API", Version = "v1" });

        config.AddSecurityDefinition("oauth2", new OAuth2Scheme
        {
            Type = "oauth2",
            Flow = "application",
            TokenUrl = "http://localhost:33656/connect/token",
            Scopes = new Dictionary<string, string>
            {
                { "api", "APIs" },
            },
        });

        config.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
        {
            { "oauth2", new[] { "api" } }
        });
    });

    //...

    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "API");
    });

1. Visit `swagger/index.html`
2. Click authorize button
3. Provide a client id and secret in the UI.
4. Click authorize button.

When I do this I get "auth errorError: Bad Request, error: invalid_client". This is happening because the `client_id` and `client_secret` are not posted to `/connect/token`. Any idea why?

Screenshot:

![image](https://user-images.githubusercontent.com/1190944/53523618-443a4980-3aab-11e9-8e9f-f14d99b7480d.png)

**Comment by kspearrin** [comment]
I see that it is sending the `client_id` and `client_secret` as as basic authentication with the `Authorization` header.

**Comment by PeterMaco** [comment]
I have the same problem. So what to do with it? There is no solution here posted.
