### ISSUE TITLE
Getting HTTP Error 500.0 - ANCM In-Process Handler Load Failure

### ISSUE THREAD

**Issue by akshayshah2050** [domaindrivendev/Swashbuckle.AspNetCore#1054]
I have created an empty asp.net  core project. (.NET Core 2.2)
I have created a controller and set up swagger (Swashbuckle.AspNetCore Version: 4.0.1) to generate documentation
When i run the solution the code is working fine but when i go to swagger ui url i get the above mentioned error
![swagger error](https://user-images.githubusercontent.com/22302386/53550911-e3b81480-3b5d-11e9-93df-5c47ae9eee83.png)

Please help me

**Comment by javiercampos** [comment]
Same here... it happens only when running on IIS Express in-process of ASP NET Core 2.2 (haven't really tried on full IIS). Works fine if running on Kestrel or non in-process

**Comment by larserikfinholt** [comment]
Same here, but we're not using Swagger. Application runs fine on IIS (2.2.2 inProcess) for about one week, now it suddenly started getting HTTP Error 500.0 - ANCM In-Process Handler Load Failure. A few minutes later the error dissapeared. 
Nothing found in the logs. Sorry for not beeing more helpful with debugging info.

**Comment by TracyGH** [comment]
Ditto.
