### ISSUE TITLE
Adding custom operations does not keep the document sorted

### ISSUE THREAD

**Issue by thzois** [domaindrivendev/Swashbuckle.AspNetCore#1062]
Hello,

I am using a DocumentFilter in order to add two more operations at the documentation with a new tag, related to getting and refreshing an AccessToken. When the documentation is rendered every tag is sorted (I have only 2) except from the ones that I add with the DocumentFilter. Even though they should appear first (their tag is AccessToken) they appear last in the list. 

P.S: I am not using any custom way to sort the operations.

```c#

            services.AddSwaggerGen(c =>
            {
                c.DocumentFilter<AuthorizationEndpoints>(Configuration);

                c.SwaggerDoc("v1", new Info
                {
                    Title = "CloudApi",
                    Version = "v1",
                    Description = "API"
                });

                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                c.IncludeXmlComments(xmlPath);

                // Ignore flagged API calls -> [ApiExplorerSettings(IgnoreApi = true)]
                c.IgnoreObsoleteActions();
            });

```

**Comment by domaindrivendev** [comment]
Document filters are the _final_ hooks in the generation process before serializing to JSON. So, sorting has already been applied. You're best bet would be to resort all operations in the entire document before exiting the document filter.

**Comment by thzois** [comment]
I actually did it but it's not a proper way.
