### ISSUE TITLE
JsonObject(ItemRequired = Required.AllowNull) not recognized

### ISSUE THREAD

**Issue by artfulsage** [domaindrivendev/Swashbuckle.AspNetCore#1064]
Hi. I suppose there is a bug in recognizing required properties of class marked with `[JsonObject(ItemRequired = Required.AllowNull)]` while properties marked with `[JsonRequiredAttribute]` and `[JsonProperty(Required = Required.AllowNull)]` recognized well.

Repro sample:
```cs
public class Program
{
	public static void Main(string[] args)
		=> WebHost.CreateDefaultBuilder(args).UseStartup<Startup>().Build().Run();
}

public class Startup
{
	public Startup(IConfiguration configuration) => Configuration = configuration;

	public IConfiguration Configuration { get; }

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
		services.AddSwaggerGen(c => c.SwaggerDoc("1.0", new Info()));
	}

	public void Configure(IApplicationBuilder app, IHostingEnvironment env)
		=> app.UseSwagger()
			.UseSwaggerUI(c =>
			{
				c.SwaggerEndpoint($"/swagger/1.0/swagger.json", "API");
				c.RoutePrefix = string.Empty;
			})
			.UseMvc();
}

[JsonObject(ItemRequired = Required.AllowNull)]
public class Item
{
	public int? Id { get; set; }
	public string Name { get; set; }
}

public class Item2
{
	[JsonRequired]
	public int? Id { get; set; }

	[JsonProperty(Required = Required.AllowNull)]
	public string Name { get; set; }
}

[Route("api/[controller]")]
[ApiController]
public class ItemsController : ControllerBase
{
	[HttpGet("default-item")]
	public ActionResult<Item> GetDefaultItem() => new Item();

	[HttpGet("default-item2")]
	public ActionResult<Item2> GetDefaultItem2() => new Item2();
}
```
![swagger problem](https://user-images.githubusercontent.com/35620830/53957315-15495680-40ef-11e9-8974-9a649f553d29.png)

**Comment by slahabar** [comment]
I am running into issues with below. 
 [JsonProperty(Required = Required.AllowNull)] 
tags it as required field but only allows non-null values.

**Comment by spfaeffli** [comment]
Currently the value for `JsonProperty.Required` only determines if the value is required - it does not allow you to indicate that a value may or may not be null.
Example:
```
[JsonProperty(Required = Required.AllowNull)]
public string ValAllowNull { get; set; }

[JsonProperty(Required = Required.Always)]
public string ValAlways { get; set; }

[JsonProperty(Required = Required.Default)]
public string ValDefault { get; set; }

[JsonProperty(Required = Required.DisallowNull)]
public string ValDisallowNull { get; set; }

[JsonProperty(Required = Required.Always)]
public int? ValNullable { get; set; }
```
Produces this output:
```
"RequiredTest": {
  "required": [
    "valAllowNull",
    "valAlways",
    "valNullable"
  ],
  "type": "object",
  "properties": {
    "valAllowNull": {
      "type": "string"
    },
    "valAlways": {
      "type": "string"
    },
    "valDefault": {
      "type": "string"
    },
    "valDisallowNull": {
      "type": "string"
    },
    "valNullable": {
      "type": "integer",
      "format": "int32",
      "nullable": true
    }
  },
  "additionalProperties": false
},
```
As you can see, `nullable` is only set for nullable types.
@domaindrivendev : Would you accept a PR that sets the value for `nullable` based on [JsonProperty.Required](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Required.htm)? If so, I would be happy to implement this.

**Comment by domaindrivendev** [comment]
Seems reasonable - a PR would be great!

**Comment by artfulsage** [comment]
Guys what about original issue with `[JsonObject(ItemRequired = Required.AllowNull)]`?

**Comment by IrickNcqa** [comment]
This is a problem for me too.  Optional strings being required?

Nothing like hitting deserialization errors in NSwagStudio auto-generated code because optional strings are null, yet marked as DisallowNull :(

**Comment by domaindrivendev** [comment]
@artfulsage @slahabar @IrickNcqa - thanks to some inspiring work from @spfaeffli, I now think I have all of your issues resolved. This is the last remaining issue preventing me from moving toward an official 5.0.0 release. So, it would be very helpful if you could pull down the latest preview from myget (`5.0.0-rc3-preview-0952` at the time of writing) and confirm everything is now working as expected.

Here's the relevant commit - c89876fbe77f65d25b1e768361a71ba7b9ef4462

**Comment by artfulsage** [comment]
@spfaeffli @domaindrivendev, thanks for update! I'd like to test it, but it seems there are a lot of breaking changes since version 4. Do you have any guide to upgrade?

**Comment by spfaeffli** [comment]
@artfulsage There is no upgrade guide yet  (#1262) - however you could take a look at the [release notes](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases) to see what changed since v4.
