### ISSUE TITLE
Xml comments are being ignored when using ModelMetadataType

### ISSUE THREAD

**Issue by vikasNew** [domaindrivendev/Swashbuckle.AspNetCore#1066]
Hi,

i am using xml comments & EnableAnnotations both but in case of partial classes only Annotations are displayed in swagger document.

My scenario is as below...

i have a Model partial class which contains entities, in this class i have applied xml comments. And i have other partial class with same name which contains ModelMetaData (Required validations). 

Now whats happening is only Annotaions are being displayed in swagger document. xml comments from first partial class not being displayed in generated document.

when i comment the ModelMetaData class then xml commments appeared on document.

please help me how to resolve this. i want to display both xml comments & Annotations on Document.

` public partial class RequesBody
    {
        /// <summary>
        /// Gets / Sets the Name of customer
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets / Sets Address of customer)
        /// </summary>
        public string Address { get; set; }
    }

    [ModelMetadataType(typeof(Metadata))]
    public partial class RequesBody
    {
        private class Metadata
        {
            [Required, MinLength(16), MaxLength(19)]
            public string Name { get; set; }

            [Required, MinLength(1), MaxLength(4)]
            public string Address { get; set; }
        }
    }`

Thanks

**Comment by vikasNew** [comment]
Hello,

Any suggestions on this..??

**Comment by domaindrivendev** [comment]
It’s not currently supported

**Comment by domaindrivendev** [comment]
No intention at this time to support this
