### ISSUE TITLE
Invalid Swagger JSON generated when adding referenced security scheme

### ISSUE THREAD

**Issue by ransagy** [domaindrivendev/Swashbuckle.AspNetCore#1067]
I am trying to add a simple JWT bearer token authentication with the 5.0.0-beta package.
This is what i did according to examples on this repo/issues:

```C#
c.AddSecurityDefinition(BEARER_AUTH, new OpenApiSecurityScheme
{
    In = ParameterLocation.Header,
    Name = HttpRequestHeader.Authorization.ToString(),
    Type = SecuritySchemeType.Http,
    Scheme = BEARER_AUTH.ToLowerInvariant(),
    BearerFormat = "JWT"
});

var openApiReference = new OpenApiReference { Type = ReferenceType.Schema, Id = BEARER_AUTH };
var openApiSecurityScheme = new OpenApiSecurityScheme { Reference = openApiReference };
var securityRequirement = new OpenApiSecurityRequirement { { openApiSecurityScheme, new string[0] } };

c.AddSecurityRequirement(securityRequirement);
```

This results in an invalid Swagger JSON with the error `Parser error on line 318 missed comma between flow collection entries`. Relevant section in the JSON as follows:
```json
...
  "security": [
    {{
        "$ref": "#/components/schemas/Bearer"
      }[ ]
    }
  ]
}
```

**Comment by ac9999** [comment]
Change "Type = ReferenceType.**Schema**" to "Type = ReferenceType.**SecurityScheme**".  
It should work.  

`var openApiReference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = BEARER_AUTH };`

**Comment by ransagy** [comment]
@ac9999 Yeah, That is it, Thanks! Was this documented somewhere?

I'm not sure whether this is still a bug or not, so i'm leaving it open for now. Maybe this needs to be documented, If it isn't.

**Comment by domaindrivendev** [comment]
The use of `ReferenceType.SecurityScheme` is demonstrated in the security scheme example from the [5.0.0 readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README-v5.md#add-security-definitions-and-requirements)

**Comment by ransagy** [comment]
Ah, I missed that readme, then. Thanks for the help and heads up :]
