### ISSUE TITLE
Swashbulcke 5 beta + .NET Core 3 Preview 3 - Error 

### ISSUE THREAD

**Issue by JohnGalt1717** [domaindrivendev/Swashbuckle.AspNetCore#1068]
'Method not found: 'Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware..ctor(Microsoft.AspNetCore.Http.RequestDelegate, Microsoft.AspNetCore.Hosting.IHostingEnvironment, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Builder.StaticFileOptions>, Microsoft.Extensions.Logging.ILoggerFactory)'.'

This code worked fine with Preview 2. It throws on CreateHostBuilder in Program.cs.

It doesn't happen unless the UseSwaggerUI call is enabled.

**Comment by antdid** [comment]
Same problem on preview with version 4 of Swashbuckle.AspNetCore

**Comment by SosoKapianidze** [comment]
I'm having the same issue

**Comment by kashif-imagyn** [comment]
I have the same issue any workarounds?

**Comment by stevie6410** [comment]
Same issue here

**Comment by komlachsv** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/438
And it does not work...

**Comment by xakep139** [comment]
Direct reference to Microsoft.AspNetCore.StaticFiles 2.0.0 doesn't solve the issue.  Any workaround?

**Comment by domaindrivendev** [comment]
This is a dup of #1030. In summary, there's breaking changes in ASP.NET Core 3.0 which need to be accounted for in SB. There's a PR in the works - #1061

**Comment by xakep139** [comment]
@domaindrivendev, #1030 is about `JsonResult`. This issue is about `StaticFiles` dependency. Are these issues connected?

**Comment by domaindrivendev** [comment]
They all fall under the general issue of incompatibility with ASP.NET Core. We know this doesn’t work right now so would like to focus on one issue to get it working, then focus on more specific issue with 3.0 afterwards

**Comment by jackselvam** [comment]
I am using swashbuckle 5.0.0 rc1 + asp.net core preview 3, getting below error

An error occurred while starting the application.
MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware..ctor(Microsoft.AspNetCore.Http.RequestDelegate, Microsoft.AspNetCore.Hosting.IHostingEnvironment, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Builder.StaticFileOptions>, Microsoft.Extensions.Logging.ILoggerFactory)'.
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.CreateStaticFileMiddleware(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options)
MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware..ctor(Microsoft.AspNetCore.Http.RequestDelegate, Microsoft.AspNetCore.Hosting.IHostingEnvironment, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Builder.StaticFileOptions>, Microsoft.Extensions.Logging.ILoggerFactory)'.
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.CreateStaticFileMiddleware(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware..ctor(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options)
Microsoft.Extensions.Internal.ActivatorUtilities+ConstructorMatcher.CreateInstance(IServiceProvider provider)
Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, object[] parameters)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

**Comment by Sonorpearl** [comment]
Still breaks for me...

**Comment by jack0fshad0ws** [comment]
Same here.. 5.0.0-rc3

**Comment by mariohik** [comment]
Looks like it was fixed in version 5.0.0-rc4

**Comment by air-slip** [comment]
Same error for me in 5.0.0-rc4

**Comment by PulaSivaPrasad** [comment]
<img width="1920" alt="swagger error" src="https://user-images.githubusercontent.com/58215717/69626461-b6f24880-106e-11ea-96ac-b8e9cde4987b.png">

i have updated the below things from stable version 4.0.1

Swashbuckle.AspNetCore rc4
Swashbuckle.AspNetCore.Swagger rc4
Swashbuckle.AspNetCore.SwaggerUI rc4

still i'm facing the issue while running the application. all the dll's are skipping loading symbols.

any solution please let me know.

**Comment by ranouf** [comment]
Same for me.

Do you have a solution?

**Comment by PulaSivaPrasad** [comment]
No @ranouf.

after deploying to Azure it is giving the error like 
“failed to load coreclr. Exception message:
Managed server didn't initialize after 120000 ms” 
and “500.37 ANCM Failed to Start Within Startup Time Limit”

I'm not finding the proper solution.
