### ISSUE TITLE
how to manage large description for swaggerDoc

### ISSUE THREAD

**Issue by vikasNew** [domaindrivendev/Swashbuckle.AspNetCore#1069]
Hi 

i want to add large description to my swaggerDoc but it's not a good to put this large text over my c# code. as like below..

`string apiDescription = "Large description goes here."
 c.SwaggerDoc("default", new Info { Title = "API", Version = "default", Description = apiDescription });`

i want to keep my Large description separate from c# code, so there is any way to do this ?

one option i am thinking is that i create a separate xml file and put the large description there An read the text from XML in my c# code.

please suggest me what are the other options..

Thanks in anticipation.

**Comment by domaindrivendev** [comment]
This is a general question and not a bug report or feature request and therefore, as per the [contributing guidelines](CONTRIBUTING.md) should be posted to StackOverflow instead of the SB repo. Thanks

Off the top of my head though, this seems like something you could solve independently of SB.
