### ISSUE TITLE
FromQuery typed parameter rendered without expanded all properties

### ISSUE THREAD

**Issue by augustynski-lukasz** [domaindrivendev/Swashbuckle.AspNetCore#1070]
I have FromQuery with complicated query model used in controller Get.
Some of query model properties are expanded to all subitems and some are not.
The first occurence of some class in query model is expanded but the further one does not.

![image](https://user-images.githubusercontent.com/2602671/54027240-18048400-41a1-11e9-884d-127e69e4ebba.png)

The ImpactArea and Location of the query have the same type defintion.
Generated JSON fragment:
Expanded model:
`   {
            "name": "ImpactArea.Place.Text",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ImpactArea.Place.MatchWholeWord",
            "in": "query",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "ImpactArea.Description.Text",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ImpactArea.Description.MatchWholeWord",
            "in": "query",
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "ImpactArea.BoundingBox.TopLeft.Lon",
            "in": "query",
            "schema": {
              "type": "number",
              "format": "double"
            }
          },
          {
            "name": "ImpactArea.BoundingBox.TopLeft.Lat",
            "in": "query",
            "schema": {
              "type": "number",
              "format": "double"
            }
          },`

And not expanded one.
` {
            "name": "Location.Place",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/sawWorkflow.Application.TextSearchParam"
            }
          },
          {
            "name": "Location.Description",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/sawWorkflow.Application.TextSearchParam"
            }
          },
          {
            "name": "Location.BoundingBox",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/sawWorkflow.Application.BoundingBox"
            }
          },
          {
            "name": "Location.BoundingCircle",
            "in": "query",
            "schema": {
              "$ref": "#/components/schemas/sawWorkflow.Application.BoundingCircle"
            }
          },`

Problem occurs in versions from 3.0

**Comment by domaindrivendev** [comment]
To troubleshoot - I would need to see the model definition. You don't have to provide your exact classes but if you could do some groundwork and figure out a simplest possible repro, that would be very helpful.

**Comment by augustynski-lukasz** [comment]
Here you are: https://github.com/augustynski-lukasz/Issue_1070
Generated MVC .Net Core 2.2 App. THe issue is presented at TestController Get([FromQuery] TestModel model) method.

**Comment by domaindrivendev** [comment]
After further investigation, this appears to be an issue with `ApiExplorer`, the API metadata provider that's shipped with ASP.NET Core, and is heavily used by Swashbuckle. I've submitted a corresponding request to the ASP.NET Core repo - https://github.com/aspnet/AspNetCore/issues/10110

**Comment by domaindrivendev** [comment]
Closing as it appears to be fixed upstream
