### ISSUE TITLE
[suggestion] How about assembly generation?

### ISSUE THREAD

**Issue by ArmanHayots** [domaindrivendev/Swashbuckle.AspNetCore#1075]
If we already have well-formatted JSON file with all documentation, why not to generate assembly for interaction nearly like it done for WCF with WSDL?
For a good start we can retrieve URL address; in more advanced way we can encapsulate `HTTPClient` and perform simple method calls.

**Comment by domaindrivendev** [comment]
Swashbuckle is primarily focused on Swagger/OpenAPI _generation_. Once you have this, there's several existing tools you can leverage to generate clients, and I don't want to re-invent the wheel. For example - [swagger-codegen](https://github.com/swagger-api/swagger-codegen), [AutoRest](https://github.com/Azure/AutoRest), [NSwag](https://github.com/RSuter/NSwag/wiki/SwaggerToCSharpClientGenerator)
