### ISSUE TITLE
Generating duplicate enum values despite having no keys

### ISSUE THREAD

**Issue by rsheasby** [domaindrivendev/Swashbuckle.AspNetCore#1077]
Running version 4.0.1 but the bug goes back to version 1.0.0

Basically, if there's a C# enum with a few definitions with a common value, Swashbuckle will add all the values into the swagger.json despite them being duplicates and despite the fact that the keys(the name of the enum values) don't actually make it into the swagger.json so the duplicate values are entirely unnecessary. Take for example HttpStatusCode:

```
...
IMUsed = 226,
Ambiguous = 300,
MultipleChoices = 300,
Moved = 301,
MovedPermanently = 301,
Found = 302,
Redirect = 302,
RedirectMethod = 303,
SeeOther = 303,
NotModified = 304,
UseProxy = 305,
Unused = 306,
RedirectKeepVerb = 307,
TemporaryRedirect = 307,
PermanentRedirect = 308,
BadRequest = 400,
...
```

Will turn into:

```
"statusCode": {
          "format": "int32",
          "enum": [
            ...,
            226,
            300,
            300,
            301,
            301,
            302,
            302,
            303,
            303,
            304,
            305,
            306,
            307,
            307,
            308,
            400,
            ...
          ],
          "type": "integer"
        },
```

In this case, the duplicate entries are actually causing a compile bug in NSwag's Angular TypeScript generation. Given that swagger files are used for code generation for multiple languages I think it would be worth resolving the unnecessary duplication.

**Comment by domaindrivendev** [comment]
Fixed by 5798c2cb1d9265dd9c8d18c5b97b633fa62cccf0
