### ISSUE TITLE
Asp.net core 3.0 + Swash Buckle 5 rc1 issue

### ISSUE THREAD

**Issue by jackselvam** [domaindrivendev/Swashbuckle.AspNetCore#1088]
I am using swashbuckle 5.0.0 rc1 + asp.net core preview 3, getting below error

An error occurred while starting the application.
MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware..ctor(Microsoft.AspNetCore.Http.RequestDelegate, Microsoft.AspNetCore.Hosting.IHostingEnvironment, Microsoft.Extensions.Options.IOptions1<Microsoft.AspNetCore.Builder.StaticFileOptions>, Microsoft.Extensions.Logging.ILoggerFactory)'. Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.CreateStaticFileMiddleware(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options) MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware..ctor(Microsoft.AspNetCore.Http.RequestDelegate, Microsoft.AspNetCore.Hosting.IHostingEnvironment, Microsoft.Extensions.Options.IOptions1<Microsoft.AspNetCore.Builder.StaticFileOptions>, Microsoft.Extensions.Logging.ILoggerFactory)'.
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.CreateStaticFileMiddleware(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware..ctor(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options)
Microsoft.Extensions.Internal.ActivatorUtilities+ConstructorMatcher.CreateInstance(IServiceProvider provider)
Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, object[] parameters)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass4_0.b__0(RequestDelegate next)
Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

**Comment by domaindrivendev** [comment]
Try `5.0.0-rc2`

**Comment by QuinntyneBrown** [comment]
@domaindrivendev Still doesn't work. Just tried it.

**Comment by QuinntyneBrown** [comment]
@domaindrivendev  For your reference, my repo is here. I will check in the code with the Rc 2 change 
https://github.com/QuinntyneBrown/BookStore/tree/infragistics-tree-grid

**Comment by QuinntyneBrown** [comment]
Sorry, it works! Thanks! Hope it works for @jackselvam as well.

**Comment by jackselvam** [comment]
Yes, it's working for me also

**Comment by FelschR** [comment]
I'm having this error on 5.0-rc4 with the stable .NET Core SDK 3.0.100.

**Comment by denis-pujdak-adm-it** [comment]
I got Swashbuckle.AspNetCore 4.0.1 and I ma ending up with the same error:
```
System.MissingMethodException: 'Method not found: 'Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware..ctor(Microsoft.AspNetCore.Http.RequestDelegate, Microsoft.AspNetCore.Hosting.IHostingEnvironment, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Builder.StaticFileOptions>, Microsoft.Extensions.Logging.ILoggerFactory)'.'
```
Does 4.0.1 support asp.net.core 3.1?

**Comment by vpaulino** [comment]
same error here.  must update to v5.0.0-rc5 ( the latest rc works for me ) and add UseStaticFiles.  

` public void Configure(IApplicationBuilder app)
        {
            app.UseStaticFiles();

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.),
            // specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
            });

            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }`

**Comment by denis-pujdak-adm-it** [comment]
I cannot use 5.0 as there is no implementation of `filterContext.SchemaRegistry.GetOrRegister(type);` in `IDocumentFilter`.
I tried `schemaRepository.GetOrAdd(type, type.Name, () => new OpenApiSchema() { Type = type.Name })` but I could not figure out how to use it. It registers types with no properties.

So I stuck with v4 at the moment. Would be nice to have v4 compatible with .net core 3.1 as v5 of swagger is a big mess so I am not going to use it.

**Comment by kylepope-ge** [comment]
@denis-pujdak-adm-it - I think you might be able to get it to work via this, which will add it to the schemaRepository:
```
context.SchemaGenerator.GenerateSchema(type, context.SchemaRepository);
```

**Comment by domaindrivendev** [comment]
Also worth noting - this is all described under "Breaking Changes" in the 5.0.0-rc5 release notes:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v5.0.0-rc5

**Comment by denis-pujdak-adm-it** [comment]
@domaindrivendev @kylepope-ge Thanks for your help guys. But I ended up with the issue #1452 . Swagger does not generate a schema properly. Very simple example shows it is not working. I got stuck with v4 at the moment.

**Comment by onlifevineesh** [comment]
> Try `5.0.0-rc2`

Thank you so much @domaindrivendev. Been struggling with this issue after I upgraded my asp.net core solution to .net 5.0. Installing "Swashbuckle.AspNetCore -Version 5.0.0-rc2" fixed it. However neither rc3 nor rc4 worked for me!!.
