### ISSUE TITLE
Request Body getting cleared

### ISSUE THREAD

**Issue by jackselvam** [domaindrivendev/Swashbuckle.AspNetCore#1090]
When i click second time in Post/Put Method tab, the request body getting cleared my previously entered values

**Comment by domaindrivendev** [comment]
These sound like gripes with the UI itself rather than the Swagger generation and therefore, as per the issue guidelines, should be submitted to the [swagger-ui](https://github.com/swagger-api/swagger-ui) project instead of Swashbuckle.
