### ISSUE TITLE
No executable found matching command "dotnet-swagger"

### ISSUE THREAD

**Issue by pierre-roudaut-cko** [domaindrivendev/Swashbuckle.AspNetCore#1095]
Hi,

I cannot seem to make `dotnet swagger tofile --help` work. 
Tested on `netcoreapp2.1` and `netcoreapp2.2`

### Reproduction steps:

`dotnet add package Swashbuckle.AspNetCore`
`dotnet add package Swashbuckle.AspNetCore.Cli`

_Api.csproj:_
```
</ItemGroup>
     ....
      <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
     <PackageReference Include="Swashbuckle.AspNetCore.Cli" Version="4.0.1" />
</ItemGroup>`
```
_Startup.cs_
```
            services
                .AddMvcCore()
                .AddApiExplorer()
                .AddSwaggerGen(...)
           ...
            app
               .UseMvc()
               .UseSwagger();
```
The swagger auto-generated documentation is accessible when running the project and navigating to `http://localhost:5000/swagger/v1/swagger.json`.

However, when running the following command:
`dotnet swagger tofile --help`
I get the error: `No executable found matching command "dotnet-swagger"`

Am I missing something? Is there a known issue?
Thank you for your help

**Comment by domaindrivendev** [comment]
Did you follow the steps here - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcorecli

It looks like you may be missing the following snippet in your csproj file:

```xml
<ItemGroup>
  <DotNetCliToolReference Include="Swashbuckle.AspNetCore.Cli" Version="4.0.1" />
</ItemGroup>
```

**Comment by pierre-roudaut-cko** [comment]
My bad, VS kept adding the package as `PackageReference` instead of `DotNetCliToolReference `, changing  it manually int the .csproj solved the issue.
Thanks a lot !
