### ISSUE TITLE
The 2.0+ version of the UI does not have the convenience of the previous UI operation. I don’t know if you have the same view.

### ISSUE THREAD

**Issue by qgxcry** [domaindrivendev/Swashbuckle.AspNetCore#1104]
In addition to lowering the version, is there a better solution?

**Comment by domaindrivendev** [comment]
Can you please provide a little more detail - screen shots etc

**Comment by ChristianSauer** [comment]
In short, it's bulky and a usabillity nightmare. But thats not @domaindrivendev  fault at all. The guys as SwaggerUi dropped that.
@qgxcry  If you do not need the interactive feature, you could try one of the alternative UIs like the **Swashbuckle.AspNetCore.ReDoc** which looks beautiful.
