### ISSUE TITLE
5.0.0-rc2 converts date-time example into local datetime format

### ISSUE THREAD

**Issue by mikolajkowalski** [domaindrivendev/Swashbuckle.AspNetCore#1108]
Till 5.0.0-beta each datetime example was published in a given format.
In 5.0.0-rc2 it is converted into a local format from Windows machine.
How can I prevent it? 
c.MapType or Serialization options does not help.

`///<example>2018-11-05T00:00:00Z</example>
   public DateTime SomeDate
   {
        get;
        set;
    }`

**Comment by domaindrivendev** [comment]
Should be fixed by 8eb279e4272d2f10875b430ce89e5f14d0c82603
