### ISSUE TITLE
Swagger UI sending default client_secret to token endpoint 

### ISSUE THREAD

**Issue by thomaslazar** [domaindrivendev/Swashbuckle.AspNetCore#1109]
We recently updated `Swashbuckle.AspNetCore` from version 3.0.0 to 4.0.1 and it broke the token retrieval. 

We're using ADFS 2019 OAuth2 as authentication provider and have an application group configured that doesn't use a `client_secret`. So now after the update the token retrieval failed because the Swagger UI was sending some default value as `client_secret` query parameter to the token endpoint, which didn't expect it for the given `client_id`. 

We didn't provide a `.OAuthClientSecret(...)` to the `SwaggerUIOptions` before, but now we have to add `.OAuthClientSecret(null)` to force Swagger UI to omit the `client_secret` parameter. 

TBH if you don't provide a client secret it shouldn't try to send a default one. 

The flow is `authorizationCode`.

**Comment by domaindrivendev** [comment]
Thanks for pointing this out. See b1ea8afa315cc6d25460884d5b63f8b051903ffe for the fix.
