### ISSUE TITLE
Is it possible to have more than one swagger paths?

### ISSUE THREAD

**Issue by Tintifax73** [domaindrivendev/Swashbuckle.AspNetCore#1111]
Hi,

I have an aspnet core api running with multiple versions and swashbuckle swagger gen/ui. In the future I will have internal and external consumers of my api. Authentication and the permissions work perfect, but somehow I dont like the fact that the swagger documentation shows internal api-methods like portal admin functions.

Is it somehow possible to generate an f.e. intern and an extern swagger json (set via attributes)? for example: https://.../swagger/v0.1/swagger.json and https://.../swagger/intern/v0.1/swagger.json automatically?

thank you and all the best :)
Thomas

**Comment by domaindrivendev** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#generate-multiple-swagger-documents

The example given cerates documents for different _versions_ of the API but you could use the same approach to split the docs down any axis you'd like.
