### ISSUE TITLE
Ability to hide an Enum field from documentation

### ISSUE THREAD

**Issue by bverb** [domaindrivendev/Swashbuckle.AspNetCore#1112]
Swashbuckle Version: 4.0.1

My API has the following property:

`public UserType Type { get; set; }`

```
public enum UserType
{
      User
      Service
      [ApiInternalValue]
      Internal
}
```
I want to hide the "Internal" field from the swagger documentation without marking it as Obsolete or JsonIgnore. I have another application that needs to use this field, so it must remain public.

I created a Schema filter for the ApiInternalValueAttribute above, but found that it is only able to hide full properties from the document, not fields from within an Enum.

Is this scenario not currently supported?

**Comment by domaindrivendev** [comment]
You could use the MapType config method to craft a specific schema for your enum type. Should be straightforward - set Type = “string” and Enum to the list values you want to include

**Comment by bverb** [comment]
Tried using MapType (note - I had to implement this in a way that would work for multiple Enums)

`public IList<KeyValuePair<Type, List<object>>> EnumMapTypes { get; set; }`

```
                foreach (var customEnum in configuration.EnumMapTypes)
                {
                    options.MapType(customEnum.Key, () => new Schema 
                    { 
                           Type = "string", 
                           Enum = customEnum.Value });
                    }
                 }
```
I verified that the included values are being properly 
added to SchemaRegistryOptions.CustomTypeMappings. 

However, my document still does not reflect that.

**Comment by bverb** [comment]
Interesting...I've identified the problem. MapType does not work on nullable Enums.

**Comment by bverb** [comment]
Closing issue. Simply needed a new MapType for the nullable version of the Enum.
