### ISSUE TITLE
5.0.0-rc2: operationid missing in IOperationFilter?

### ISSUE THREAD

**Issue by KevinDockx** [domaindrivendev/Swashbuckle.AspNetCore#1114]
When creating a custum OperationFilter the Apply method gets an operation (OpenApiOperation) and context (OperationFilterContext).  It seems that in RC2 operation.operationId is always null (in 5.0.0-beta this was filled out as expected).  Is this a bug, or is it expected behavior?  And if it's expected behavior, where from can we get the operationId in a custom OperationFilter?

**Comment by spfaeffli** [comment]
The change was introduced with this [commit](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/6d4beaf859f7a3407de0b06bee14c4b4c9c508a7) - you need to specify the value explicitly or implement your own strategy to resolve the OperationId.

**Comment by domaindrivendev** [comment]
`OperationId` is NOT required by the Swagger/OAI specification and auto-generating them was becoming increasingly problematic for a number of reasons that I won't go into here. Therefore, as of v4.0, Swashbuckle no longer generates them automatically. See the [4.0 release notes](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v4.0.0) for some additional context.

**Comment by domaindrivendev** [comment]
As you're using rc2, you may want to look at the topic in the v5 docs as the behavior will change slightly again with the official v5.0 release:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README-v5.md#assign-explicit-operationids

**Comment by KevinDockx** [comment]
Thanks for the explanation! :)
