### ISSUE TITLE
Truncated swagger.json in AspNetCore 3 distribution release

### ISSUE THREAD

**Issue by DanielS4n** [domaindrivendev/Swashbuckle.AspNetCore#1121]
In debugger (VS 2019) the swagger,json is in the correct format but after distribution (release) the browser report error because miss the initial bracket '{' in the JSON:

```
{    <--- miss start bracket
  "openapi": "3.0.1",
  "info": {
    "title": "EasyDataCore Web API",
    "description": "Web API interface for EasyDataCore",
    "version": "v3"
  },
  "paths": {
 ...
 --> truncated at end
```

**Comment by MiyamuraMiyako** [comment]
Yes, and end of json, document is garbled:
![图片](https://user-images.githubusercontent.com/10345361/55962541-af2e9100-5ca3-11e9-8609-46168dffedb7.png)

![图片](https://user-images.githubusercontent.com/10345361/55962511-9e7e1b00-5ca3-11e9-9c9c-5ab6d5afc5c1.png)

**Comment by domaindrivendev** [comment]
@DanielS4n @MiyamuraMiyako - could you take a quick look at #1105. I believe there were some upstream (AspNetCore) issues that have been resolved in the latest preview (ASP.NET Core Preview 4). Could you please pull down that version of the SDK and let me know if this issue still persists? Thanks

**Comment by MiyamuraMiyako** [comment]
@domaindrivendev I use preview-5, problem sovled.
