### ISSUE TITLE
Add configuration to enable swagger/swaggerui on a specific port only

### ISSUE THREAD

**Issue by EricStG** [domaindrivendev/Swashbuckle.AspNetCore#1122]
I'm looking into restricting access to the generated swagger.json, as well as the swagger ui, to some sort of management port that is publicly available, but is available internally.

It would be great if `SwaggerOptions` and `SwaggerUIOptions` would include a port to filter requests on, similar to the [health checks](https://github.com/aspnet/AspNetCore/blob/107e1862b7a463ad2ae413318288ad8461c1a7e8/src/Middleware/HealthChecks/src/Builder/HealthCheckApplicationBuilderExtensions.cs#L228) in ASP.Net Core

**Comment by mrhockeymonkey** [comment]
@EricStG did you find a work around for this? I'm looking to have the same in that metrics and health will be available on one port whilst swagger and controllers be available on another (that is not exposed publicly). 

+1 for this feature

**Comment by EricStG** [comment]
It's been a while, and I don't remember the exact workaround I used, but in your startup.cs, in `Configure`, you can use `MapWhen` to have a conditional pipeline:

```cs
const int swaggerPort = 6000;
app.MapWhen(context => context.Connection.LocalPort == swaggerPort, app =>
{
    app.UseSwagger();
    app.UseSwaggerUI();
});
```

If you only want swagger (and health checks) on that port, you'll have to configure the rest of your pipeline accordingly

**Comment by TAC911** [comment]
+1 for this one.
Is there any plan to support this natively?

**Comment by martincostello** [comment]
This can be trivially implemented with `MapWhen()` to any arbitrary filter, which is infinitely extensible compared to having baked-in support just for ports. https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1122#issuecomment-1002150373
