### ISSUE TITLE
Is it possible to run dotnet swagger from command line

### ISSUE THREAD

**Issue by tkumark** [domaindrivendev/Swashbuckle.AspNetCore#1125]
Is it possible to run dotnet swagger from command line which is not configured to one specific project?

currently I am running it like 
`dotnet <nugetpackages>\Swashbuckle.AspNetCore.Cli\bin\$(Configuration)\netcoreapp<ver>\dotnet-swagger.dll tofile --host http://localhost --output swagger.json <bin>\<AssemblyName>.dll v1`

but would prefer to use `dotnet swagger` if possible.

**Comment by domaindrivendev** [comment]
For version 5.0.0, this tool will be available as a [Net Core Global Tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools). See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README-v5.md#retrieve-swagger-directly-from-a-startup-assembly for installation details.

I'm working hard to get the official 5.0.0 release done ASAP but in the meantime you can try this out with a preview version available on myget.org:

> dotnet tool install -g Swashbuckle.AspNetCore.Cli --version 5.0.0-rc3-preview-0938

_NOTE: for this to work, you need to have myget.org configured as a Nuget source_

**Comment by syndicatedshannon** [comment]
Link above is now:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#retrieve-swagger-directly-from-a-startup-assembly
