### ISSUE TITLE
How to Generate swagger.json for Polymorphic classes

### ISSUE THREAD

**Issue by MattHartz** [domaindrivendev/Swashbuckle.AspNetCore#1129]
Hi,

Is there any documentation on how to generate swagger.json that includes base/derived types on response models? I see some post for supporting discriminators for POST/PUT apis, but no documentation for GET apis. Is this supposed to be supported out of the box?

Thank you!

**Comment by domaindrivendev** [comment]
It will be supported out-of-the-box with the 5.0.0 release. If you want to try it out, it's available (but not yet documented) in the pre-release version - 5.0.0-rc2. Take a look at the Basic test app for inspiration:

- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v5.0.0-rc2/test/WebSites/Basic/Startup.cs#L63
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v5.0.0-rc2/test/WebSites/Basic/Controllers/PolymorphicTypesController.cs

__NOTE__: You'll need to explicitly opt-in via a config call to `GeneratePolymorphicTypes`.
