### ISSUE TITLE
Execute button is not working

### ISSUE THREAD

**Issue by myesn** [domaindrivendev/Swashbuckle.AspNetCore#1132]
![image](https://user-images.githubusercontent.com/18598579/56412442-bd3d6c80-62b6-11e9-85e5-dcacaefb52c9.png)
![image](https://user-images.githubusercontent.com/18598579/56412807-f1fdf380-62b7-11e9-9eba-86caa5c2e87a.png)
![image](https://user-images.githubusercontent.com/18598579/56412402-8e26fb00-62b6-11e9-86ed-051db1517516.png)
![image](https://user-images.githubusercontent.com/18598579/56412370-72235980-62b6-11e9-8cae-78b146ccd185.png)
![image](https://user-images.githubusercontent.com/18598579/56412830-08a44a80-62b8-11e9-9ccb-689f70a80be3.png)
![image](https://user-images.githubusercontent.com/18598579/56412261-22dd2900-62b6-11e9-9071-4452886820d0.png)

Hi, above is a screenshot of my code, the issue is clicking the execute button does not work.

**Comment by domaindrivendev** [comment]
Looks like you’re using NSwag as opposed to Swashbuckle. Wrong repo?

**Comment by myesn** [comment]
Sorry, I used the wrong library, thank you.
