### ISSUE TITLE
Uses old dependencies

### ISSUE THREAD

**Issue by lonix1** [domaindrivendev/Swashbuckle.AspNetCore#1133]
*2. If your issue is specifically a UI concern, don't submit it here. Post to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui).*

There is a UI bug in firefox where the version field's text is white and cannot be seen. This works on later versions.

So the problem is not really a UI bug, but rather that this nuget doesn't use the latest version of all the dependencies. When will the latest version be released?

**Comment by domaindrivendev** [comment]
I have a number of [critical bugs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/7) to resolve before releasing the stable version of 5.0.0. However, you can go ahead and pull down the latest RC version (5.0.0-rc2) to get most of the changes, including the latest UI versions.
