### ISSUE TITLE
Doesn't work for internal controllers

### ISSUE THREAD

**Issue by lonix1** [domaindrivendev/Swashbuckle.AspNetCore#1134]
It's best practice to keep everything internal, unless otherwise necessary - but if a controller is `internal` instead of `public` then swashbuckle doesn't see it.

So it would be nice to declare swashbuckle as a "friend" assembly so it can see my assembly's  internals:
````cs
[assembly: InternalsVisibleTo("Swagger???")]
````

But I'm not sure of the library's official name?

I also tried `Swashbuckle.AspNetCore` but that's not it.

**Comment by domaindrivendev** [comment]
If you mark a controller internal, not only will it not be surfaced by Swashbuckle, but it won't be discoverable by the MVC framework itself. That is, by default, ASP.NET Core _requires_ controllers to be public.

Unless you've customized the controller selection process in ASP.NET Core the operations won't be exposed full stop. Try testing this independently of Swashbcuke - e.g. with curl or postman.

**Comment by lonix1** [comment]
Yeah you're right... I did some tinkering in the registration process and forgot about it!

Bottom line: controllers must be public.

Sorry to waste your time! :cry:

**Comment by CodyBatt** [comment]
If anyone finds this issue... it IS fairly easy to use internal controllers with Swagger UI. Add the code below somewhere in your project:

```csharp
public class InternalControllerBase : Controller
{
}

public class CustomControllerFeatureProvider : ControllerFeatureProvider
{
    protected override bool IsController(TypeInfo typeInfo)
    {
        var isCustomController = !typeInfo.IsAbstract && typeof(InternalControllerBase).IsAssignableFrom(typeInfo);
        return isCustomController || base.IsController(typeInfo);
    }
}

public static class InternalControllersExtension
{
    public static IMvcBuilder EnableInternalControllers(this IMvcBuilder builder)
    {
        builder.ConfigureApplicationPartManager(manager =>
        {
            manager.FeatureProviders.Add(new CustomControllerFeatureProvider());
        });

        return builder;
    }
}
 ```
 
 Modify internal controllers to be `internal` instead of `public` and derive from `InternalControllerBase` instead of `Controller`.
 
 
 Now call `EnableInternalControllers` in your startup code:
 
```csharp
services.AddControllers().EnableInternalControllers();
``` 
where `services` is `IServiceCollection`. You don't need to make any changes to swagger config for this to work. 

(Tested with .NET 7, AspNetCore 2.21.0)
