### ISSUE TITLE
[EmailAddress] and [Phone] does not set right value in format for generated swagger json

### ISSUE THREAD

**Issue by raanam** [domaindrivendev/Swashbuckle.AspNetCore#1135]
Version - 4.0.1

We used following annotation on model

`[EmailAddress]
public string Email { get; set; }
[Phone] public string Phone {get;set;}`

EmailAddress and Phone annotation are defined in System.ComponentModel.DataAnnotations

But generated swagger JSON reports it as - 
```json
"email": { "type": "string" }, "phone": { "type": "string" }
```
We were expecting it to be like
```json
"email": { "type": "string", "format": "email" }, "phone": { "type": "string", "format": "phone"  }
```

Do we need to specify something more in Attribute to get format information in swagger JSON

**Comment by domaindrivendev** [comment]
Support for `Email` and `Phone` attributes has already been added to the master branch and will be available with the v5 release
