### ISSUE TITLE
Some behaviors may be abnormal

### ISSUE THREAD

**Issue by EzrealJ** [domaindrivendev/Swashbuckle.AspNetCore#1137]
Hello there
My English is not very good. The following text was obtained by the translation software.But I think you can understand what I am expressing.

I found a problem, but I'm not sure if it's a UI issue, or is it designed to be like this.
Concise and concise:
When two actions in my controller have the same method name but different routes, the areas of the UI that belong to two different routes will be expanded at the same time when one of them is clicked.

**Comment by domaindrivendev** [comment]
Use one of the two approaches described here to ensure that the generated `OperationId`s are unique - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#assign-explicit-operationids
