### ISSUE TITLE
Global AuthorizeFilter not picked up as [Authorize]

### ISSUE THREAD

**Issue by Kizmar** [domaindrivendev/Swashbuckle.AspNetCore#1140]
Using: Swashbuckle.AspNetCore Version 4.0.1

I recently updated our Swashbuckle implementation and added an oauth2 scheme with an operation filter. Now when I use Swagger-UI, the endpoints that have an `[Authorize]` attribute show a lock icon in Swagger-UI, and it adds the bearer token to the request headers.

I just noticed that the lock icon and header aren't getting added when we apply a global `AuthorizeFilter` and aren't using `[Authorize]` within the controllers. 

Example:
```
services.AddMvc(config =>
{
    var policy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();

    config.Filters.Add(new AuthorizeFilter(policy));
}
```

I'm not sure if this is a bug, or if my configuration needs to be adjusted for this scenario. I can post more code here, just not sure what would be needed for this.

[EDIT]
We actually do have `[Authorize("scope_name")]` on the controller I've been testing (in addition to the global filter mentioned above). I added `[Authorize]` to one of the endpoints specifically and the lock icon did show up. Looks like the attribute *has* to be on the endpoints in order for the operation filter to see it.

**Comment by lonix1** [comment]
I posted something similar [here](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/93). It's probably easier to get the feature into that library.

If you aren't using that library by the way, it's quite awesome.

**Comment by domaindrivendev** [comment]
Swashbuckle doesn't provide any automatic integration with the `Authorize` attributes or global filters. The recommended approach is to implement this yourself with an operation filter. I would imagine your filter needs to be updated to account for globally configured attributes but this isn't really a Swashbuckle issue.
