### ISSUE TITLE
Fail to load swagger when body modals have same name

### ISSUE THREAD

**Issue by vsarunov** [domaindrivendev/Swashbuckle.AspNetCore#1141]
Bug.

Using .net core 2.0
Swashbuckle version: 4.0.1

When Bodies in the request have the same name fails to load.

Example:
```

 [Route("getData")]
        [HttpPost]
        [ProducesResponseType(typeof(IEnumerable<object>), StatusCodes.Status200OK)]
        public async Task<IActionResult> GetData1([FromBody]SomeObject1.Query requestData)
        {
          ....
        }

[Route("getData2")]
        [HttpPost]
        [ProducesResponseType(typeof(IEnumerable<object>), StatusCodes.Status200OK)]
        public async Task<IActionResult> GetData2([FromBody]SomeObject2.Query requestData)
        {
          ....
        }
```

Both have the same name "Query", however they are nested classes inside other classes which are different. If I comment out one of them or rename to Query2, works fine, with no conflict.

**Comment by lonix1** [comment]
I had the same problem. The fix is this:

````csharp
services.AddSwaggerGen(c => {

  c.CustomSchemaIds(y => y.FullName);
}
````

**Comment by vsarunov** [comment]
> 
> 
> It's not a bug.
> 
> I had the same problem. The fix is this:
> 
> ```cs
> services.AddSwaggerGen(c => {
> 
>   c.CustomSchemaIds(y => y.FullName);
> }
> ```

Yes, figured it out. Thank you for the reply though :)

**Comment by lonix1** [comment]
I was surprised we had the same problem at the same exact time... What are the odds? :smile:
