### ISSUE TITLE
[Feature Request] Simplify response attributes and comments

### ISSUE THREAD

**Issue by lonix1** [domaindrivendev/Swashbuckle.AspNetCore#1142]
To fully describe a response:

````csharp
/// <response code="200">Data retrieved successfully.</response>
[ProducesResponseType(typeof(FooData), 200)]

// and

/// <response code="401">Login failed.</response>
[ProducesResponseType(401)]
````

If there are many types of responses (different error, etc.) then a single action method becomes very ugly / hard to read.

There is also a `SwaggerResponseAttribute` but it doesn't seem to work in the same way - the description is not rendered.

It would be nice if we could use it to replace the above with this:

````csharp
[SwaggerResponse(200, "Data retrieved successfully.", typeof(FooData))]

// and

[SwaggerResponse(401, "Login failed.")]
````

That would halve the size of every action's attribute/doccomment section.

**Comment by domaindrivendev** [comment]
That should work today. But you do need to explicitly enable the Swagger* annotations during setup via a call to “EnableAnnotations”. Maybe this is why it’s not working for you?

**Comment by lonix1** [comment]
THAT WAS IT! :smile: 

Thanks for this fantastic library.
