### ISSUE TITLE
Request args model inheritance

### ISSUE THREAD

**Issue by brunolau** [domaindrivendev/Swashbuckle.AspNetCore#1146]
My code is as following, generated documentation however contains documentation only for properties of "CustomDtoExtended" class, it seems to be unable to resolve comments of the base class, is there something I'm missing?

       public class CustomDtoExtended : CustomDto
        {
            /// <summary>
            /// Some other property
            /// </summary>
            public int OtherProp { get; set; }
        }

        public abstract class CustomDto
        {
            /// <summary>
            /// ID of the Group
            /// </summary>
            public int Id { get; set; }

            /// <summary>
            /// Current Name of the group
            /// </summary>
            public string Name { get; set; }
        }

        /// <summary>
        /// Creates or modifies Group
        /// </summary>
        /// <param name="data">Group data</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult<int>> Post([FromBody]CustomDtoExtended data)
        {

        }

**Comment by domaindrivendev** [comment]
Inheriting of XML comments is not currently supported by Swashbuckle and I've no plans to add this anytime soon.

**Comment by Kshopper93** [comment]
Any news here?

**Comment by domaindrivendev** [comment]
I don't intend on adding this functionality
