### ISSUE TITLE
5.0.0-rc2 schema filter for [FromForm] request bodies?

### ISSUE THREAD

**Issue by bbarry** [domaindrivendev/Swashbuckle.AspNetCore#1148]
I have a controller method:

```csharp
[HttpPost]
public ActionResult Foo([FromForm]MyRequestType request) => Ok();

//...
public class MyRequestType
{
      [BindProperty(Name = "email")]
      [Schema(Format="email")]
      public string Email { get; set; }
}
```

and a schema filter:

```csharp
    public class SchemaAttribute : Attribute
    {
        public string Format { get; set; }
    }
    public class MyFilter : ISchemaFilter
    {
        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
            => Apply(schema, context, null);
        private void Apply(OpenApiSchema schema, SchemaFilterContext context, SchemaAttribute attribute)
        {
            if (attribute == null) { attribute = context.Type.GetCustomAttribute<SchemaAttribute>(); }
            Process(schema, attribute);
            foreach (var property in context.Type.GetProperties())
            {
                var name = property.GetCustomAttribute<BindPropertyAttribute>()?.Name;
                if (name == null) continue;
                if (!schema.Properties.TryGetValue(name, out var schemaProp)) continue;
                var attr = property.GetCustomAttribute<SchemaAttribute>();
                if (attr != null)
                {
                    Apply(schemaProp, new SchemaFilterContext(property.PropertyType,null,null,null), attr);
                }
            }
        }

        private void Process(OpenApiSchema schema, SchemaAttribute attribute)
        {
            if (attribute == null) return;

            if (attribute.Format != null)
            {
                schema.Format = attribute.Format;
            }
        }
    }
```

(code reduced for test case)

expecting:

        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  }
                }
              },
              "encoding": {
                "email": {
                  "style": "form"
                }
              }
            }
          }
        },

actual:

same as above except "format":... missing

**Comment by domaindrivendev** [comment]
Out-of-the-box, Swashbuckle supports attributes from `System.ComponentModel.Annotations` namespace. In your example, you've used a `SchemaAttribute` which doesn't come from the Annotations namespace - where is that attribute coming from, I'm not familiar with it?

If you use the `EmailAddressAttribute` instead you'll get the desired results.

```csharp
public class MyRequestType
{
      [BindProperty(Name = "email")]
      [EmailAddress]
      public string Email { get; set; }
}
```

**Comment by domaindrivendev** [comment]
Sorry - just seeing it's your own attribute with an accompanying schema filter. There must be something wrong with your filter implementation. Have you debugged through it?

**Comment by bbarry** [comment]
Sorry, it is the `[FromForm]` version that isn't working. `[FromBody]` works fine

`SchemaAttribute` is a type I wrote which lets me override whatever I want specifically for this OAS. It has a bunch of other properties that I haven't shown to support things like examples, descriptions, changing the schema type name (there is an accompanying document filter to finish that) and more schema validations than are supported OOB. If I get approval I could maybe put in a PR for the annotations library. All it has is a bunch of properties; the work is in the filter which is much expanded from the one posted here.

**Comment by bbarry** [comment]
Without much testing I am able to trigger schema generation via an operation filter which appears to be working for me:

    internal class FixFromFormSchemaOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var fromFormParameter = context.MethodInfo.GetParameters()
                .FirstOrDefault(p => p.IsDefined(typeof(FromFormAttribute), true));
            if (fromFormParameter == null) return;
            
            foreach (var key in operation.RequestBody.Content.Keys)
            {
                operation.RequestBody.Content[key].Schema =
                    context.SchemaGenerator.GenerateSchema(fromFormParameter.ParameterType, context.SchemaRepository);
            }
        }
    }

I am not sure what the potential drawbacks are of this approach (all of my cases have a single parameter with `[FromForm]` which is a class containing a set of string, enum, and primitive properties).

**Comment by domaindrivendev** [comment]
Due to the way in which form fields are surfaced by ApiExplorer (the API metadata layer that ships with ASP.NET Core), form Schema's need to be treated as a special case in Swashbuckle, and are generated in a slightly different way to to regular payload schemas.

As a result, they are a) always generated inline within the relevent Operation definition rather components.schemas and b) never passed through the schema filters.

If you need to inspect those schemas, look in the relevent Operation definition instead. If you need to modify, use an IOperationFilter instead of an ISchemaFilter.
