### ISSUE TITLE
Ampersand in remarks xml block not rendered correctly

### ISSUE THREAD

**Issue by lonix1** [domaindrivendev/Swashbuckle.AspNetCore#1151]
A POST can be annotated with a sample request like this:

````cs
/// <summary>
/// Creates a TodoItem.
/// </summary>
/// <remarks>
/// Sample request:
///
///     POST /Todo
///     {
///        "id": 1,
///        "name": "Item1"
///     }
/// </remarks>
[HttpPost]
public ActionResult<TodoItem> Create(TodoItem item) { }
````

But what about a GET:

````cs
/// <summary>
/// Gets a TodoItem.
/// </summary>
/// <remarks>
/// Sample request:
///
///     GET /Todo?iscomplete=true&owner=mike         <--- problem is here
/// </remarks>
[HttpGet]
public ActionResult<TodoItem> Get(bool isComplete, string owner) { }
````

The problem is the ampersand - the compiler complains: `warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'owner'.'` So I used `&amp;` or `&#38;` and the compiler is happy, and the xml is generated.

But swashbuckle renders it as `&amp;` not as `&`.

What is the correct syntax? Are there examples anywhere for GETs?

**Comment by tomaspakala** [comment]
I have encountered same problem.

**Comment by lonix1** [comment]
@mvarblow Has a nice [workaround here](https://stackoverflow.com/a/57561054/9971404), until this is fixed.

**Comment by kenbrower** [comment]
Workaround is no longer valid as of the 5.0.0-rc3 release because IOperationFilter is no longer in Swashbuckle.AspNetCore.Swagger namespace.

**Comment by lucianoac** [comment]
Hi, I was looking at this problem and this seem duplicate with  #1265 . Since I was messing around with XmlCommentsTextHelper to make it work with <para> tag, I think it's a good place to decode the xml. My intend is put a simple System.Net.WebUtility.HtmlDecode() in the text processing pipeline. Does anyone have some insight on the possible side effects when calling HtmlDecode? Some unwanted transformations perhaps.

**Comment by domaindrivendev** [comment]
This appears to work fine in the latest version - `5.6.3`

**Comment by Markus1980Wien** [comment]
For summary and description this bug does not occur any more

BUT for the `<example>`-Tag the problem still exists
`/// <summary>`
`///  KeyValuePair List as HTML-FORM-POST-Values (application/x-www-form-urlencoded)`
`/// </summary>`
`/// <example>DOCNAME=Name1&amp;DOCTYPE=invoice"</example>`
