### ISSUE TITLE
improve schema generated for classes derived from DynamicObject

### ISSUE THREAD

**Issue by HeroXXiv** [domaindrivendev/Swashbuckle.AspNetCore#1153]
Original discussion for webapi from [here](https://github.com/domaindrivendev/Swashbuckle/issues/412).

I'm using [`Westwind.Utilities.Expando`](https://github.com/RickStrahl/Westwind.Utilities/blob/7d5d76f3b415f9e43ebd558a467fb9cf8e5de24a/Westwind.Utilities/SupportClasses/Expando.cs) as my base dynamic model which supports both compiletime and runtime properties, and generating openapi document from business logic services directly, so i am able to invoke `SchemaRegistry` with my code.

According to [`SchemaRegistry.CreateInlineSchema`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/28e8673e2579b406bc5120b89589aee3b5b79341/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs#L87), a class derived from `DynamicObject` will results `JsonDynamicContract` but `JsonObjectContract` if marked with `[JsonObject]`. So IMO I can 

1. add `else if (jsonContract is JsonDynamicContract)` check and return a schema just like `CreateObjectSchema` with `AdditionalProperties` as well, or
2. update [`CustomTypeMappings` check logic](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/28e8673e2579b406bc5120b89589aee3b5b79341/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs#L89) with inheritance support, then I can add a mapping of Expando class which works with all derived model classes, or
3. add a `SchemaFilter` to modify the current object schema returned. (may not change any logic in `SchemaRegistry` but need some cross/cycle invokes between filter and registry, such as `CreatePropertySchema` and `referencedTypes`)

**Comment by domaindrivendev** [comment]
#Dup of #1314
