### ISSUE TITLE
How to document Swagger/Swashbuckle parameter descriptions when using [FromQuery]

### ISSUE THREAD

**Issue by rgelb** [domaindrivendev/Swashbuckle.AspNetCore#1158]
In a standard .NET Core 2.2 Api project with Swashbuckle.AspNetCore 5.0.0-rc2:

```csharp
[HttpGet]
public ActionResult GetSomeData([FromQuery] SomeDataRequest request) {
    return File(returnImage(), "image/png");
}
```

The definition of SomeDataRequest 

```csharp

public class SomeDataRequest {
  /// <summary>
  /// Description 1
  /// </summary>
  [Description("description 1")]
  public string foo;

  /// <summary>
  /// Description 2
  /// </summary>
  [Description("description 2")]
  public string bar;
}
```

When I bring up the Swagger UI, it doesn't show any kind of descriptions for the properties of SomeDataRequest.

As you can see I tried the Description attribute and the XML comments. Nothing seems to work.

**Comment by domaindrivendev** [comment]
Have you followed the readme instructions for including XML comments?

**Comment by rgelb** [comment]
@domaindrivendev I found the issue.  `SomeDataRequest` class is in another assembly and therefore was not part of the XML documentation file for the project where Swashbuckle is referenced.  I guess, I'll have to do a post-build step to copy over the xml file.  Thank you!

**Comment by davidkmitrais** [comment]
Hi @rgelb,
Could you explain more about this issue? as I have the same problem and didn't know how to have description for the parameters of class.
Thanks

**Comment by rgelb** [comment]
@davidkmitrais So let's say you have 2 projects.  

api.csproj                 -- this project has Controller actions for your API
entities.csproj           -- this project contains entities that you either pass in or return to/from the API.

You generate the XML documentation file for both, which results in api.xml and entities.xml.  These files get placed in their respective bin/debug directories.  And then the Startup.cs in your Api.cs has Swagger declaration to read the xml documentation:

```csharp
services.AddSwaggerGen(c => {
    c.SwaggerDoc("v1", new Info { Title = "Widgets Images", Version = "v1" });
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    c.IncludeXmlComments(xmlPath);
    ...
```

You can see the problem here, right?  It's only getting api.xml because that it's in the executing directory.  So you need to somehow bring entities.xml to the same directory.  To do, that I defined a post-build step for the api project:

`copy /Y $(ProjectDir)..\entities\bin\$(ConfigurationName)\netstandard2.0\entities.xml $(TargetDir)`

You might have to fudge directory names a little bit if you are not using .net core 2.x

Now after every build, entities.xml will be in the same folder as api.xml.  The last step is to let Swagger know about.  We do this by extending `AddSwaggerGen` code a bit:

```csharp
var entitiesXmlPath = Path.Combine(AppContext.BaseDirectory, "entities.xml");
c.IncludeXmlComments(entitiesXmlPath);
```

I hope this helps.

**Comment by davidkmitrais** [comment]
@rgelb Thank you!. 
Yeah now I could display my entities description for swagger UI.
just little thing that I want to add, that we also could add examples of value by adding "example" on definitions like below:
```
public class SearchTermViewModel
    {
        /// <summary>
        /// First Name of Supplier Contact.
        /// </summary>
        /// <example>John</example>
        public string FirstName { get; set; }

        /// <summary>
        /// Last Name of Supplier Contact.
        /// </summary>
        /// <example>Doe</example>
        public string LastName { get; set; }
}
```

**Comment by utarn** [comment]
@rgelb Thanks!  I just add GenerateDocumentationFile to all of referencing .csproj files without post build setting. Once the main project is compiled, the all the xml files are copied to the same directory as the main project is.

```
  <PropertyGroup>  
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>  
```
