### ISSUE TITLE
Null reference IN TryCreateFor

### ISSUE THREAD

**Issue by mayamoon** [domaindrivendev/Swashbuckle.AspNetCore#1159]
I use a JsonProperty in my dataobject ,I not Add DefaultValue to the Attrribute ,then I can't generate doc to client ,I find the bug in method OpenApiAnyFactory.TryCreateFor

  else if (schema.Type == "string" && value.GetType().IsEnum)
                openApiAny = new OpenApiString(Enum.GetName(value.GetType(), value));

this code do not check when value is null

**Comment by domaindrivendev** [comment]
Can you please provide an exact set of repro steps

**Comment by UltimateForm** [comment]
hi just wanted to say i had similar error to this, although im not sure if for the same cause. In my case I had a  `DefaultValue` attribute (from System.ComponentModel) with `null` for a boolean field(made sense to me because the field was nullable), removing that fixed the problem

**Comment by domaindrivendev** [comment]
Fixed by 5a4b35f0aa7a6a41077d1e3ec2123299b8bff0ad
