### ISSUE TITLE
SwaggerResponse Type =

### ISSUE THREAD

**Issue by mikebollandajw** [domaindrivendev/Swashbuckle.AspNetCore#1163]
ASPNet Core 2.1
Swashbuckle.AspNetCore 3.0.0
Swashbuckle.AspNetCore.Annotations 3.0.0
Swashbuckle.AspNetCore.SwaggerUI 3.0.0

I am getting the exception 

```System.InvalidOperationException: Conflicting schemaIds: Identical schemaIds detected for types```

This only happens if i am decorating my controller method with something like 

```[SwaggerResponse(StatusCodes.Status200OK, Type = typeof(MyNamespace.Company)]```

If i comment it out this attribute then the issue does not occur and swagger will start

I have a library that also has a model of Company which I believe is causing this issue. However, 
I do not wish to use CustomSchemaIds and have full names in the model definitions at the bottom of my swagger page

Why is this swaggerresponse not able to see I only want to use MyNamespace.Company?

**Comment by domaindrivendev** [comment]
Swashbuckle only generates schema's for types that are ultimately surfaced (parameters and responses) somewhere in you're API. If you're receiving this error, then there MUST be another type with the same name, different namespace (possibly the library type you referred to) surfaced somewhere in your API.

SchemaId's need to be unique across you're entire API so it may be coming from some other action. Have you confirmed that the _other_ `Company` type is not exposed anywhere in your API? It could be hidden deep down in a nested object structure.

**Comment by mikebollandajw** [comment]
If that was the case commenting out the swaggreresponse would still give the error

**Comment by domaindrivendev** [comment]
By commenting out the `SwaggerResponseAttribute`, you're no longer surfacing the type `MyNamespace.Company` in your API. So, the _other_ `Company` type (wherever else that's surfaced) will be unique in it's class name, and therefore you would NOT still see the error

**Comment by mikebollandajw** [comment]
I have managed to locate the other area where the item was surfaced as you advised and replaced it with a view model

Returning the response attribute and this no longer throws the exception!

Thank you!
