### ISSUE TITLE
How to show C# MaxLength Data Annotation on FromQuery Parameter properties?

### ISSUE THREAD

**Issue by DatXN** [domaindrivendev/Swashbuckle.AspNetCore#1167]
I have this method which uses FromQuery parameter binding:

```
        [HttpGet()]
        [ApiConventionMethod(typeof(DefaultApiConventions), nameof(DefaultApiConventions.Get))]
        public async Task<ActionResult<List<Order>>> GetOrders([FromQuery] OrdersQueryParameter ordersQueryParameter)
        {
            var data = await _orderHander.GetAsync(ordersQueryParameter);

            #region Pagination Metadata

            var resourcePagingMeta = new ResourcePagingMetadata(data.Item2, ordersQueryParameter.PageNumber, ordersQueryParameter.PageSize);
            var resourceMeta = ResourcePagingHelpers.CreateResourceUri(resourcePagingMeta, ordersQueryParameter, _linkGenerator, HttpContext);
            Response.Headers.Add("X-Pagination", JsonConvert.SerializeObject(resourceMeta));

            #endregion Pagination Metadata
            // Have to return List to allow XML Serialization formatter to work; IEnumerable not work
            return Ok(data.Item1.ToList());
        }
```

I used following data annotaion: Required and MaxLength

```
    public class OrdersQueryParameter : ResourcesQueryParameter
    {
        /// <summary>
        /// Test number
        /// </summary>
        /// <value></value>
        [MaxLength(3)]
        [Required]
        public string Number { get; set; }
        ...
```

But in Swagger UI and schema, the MaxLength is not produced and display (it only show required attribute)

![image](https://user-images.githubusercontent.com/5478040/58898249-5ec43480-8724-11e9-8b29-8ce93ad46a33.png)

So how can I display the MaxLength in Parameter like in the returned data schema?
For example, this is what I want:

![image](https://user-images.githubusercontent.com/5478040/58898308-83201100-8724-11e9-874e-09171fada004.png)

**Comment by domaindrivendev** [comment]
This is a question/feature request for the [swagger-ui folks](https://github.com/swagger-api/swagger-ui) rather than Swashbuckle. I suggest you create a corresponding issue in that repo and link here fore tracking.

**Comment by martincostello** [comment]
Closing as external.
