### ISSUE TITLE
Internal Server Error when using BadRequestObjectResult

### ISSUE THREAD

**Issue by mhsimkin** [domaindrivendev/Swashbuckle.AspNetCore#1168]
Swashbuckle.AspNetCore version 5.0.0-rc2
AspNetCore v3.0.0-preview5

I decorated an API Controller Action with the ProducesResponseTypeAttribute as below:

```        /// <summary>
        /// Get a collection of all available lists for a specific user.
        /// </summary>
        /// <param name="userId">The id of the specific user.</param>
        /// <returns>Returns a collection of <see cref="UserListItem">UserListItem</see>objects that contain the name and id of each list./></returns>
        [ProducesResponseType(200, Type = typeof(IEnumerable<UserListItem>))]
        [ProducesResponseType(400, Type = typeof(BadRequestObjectResult))]
        [HttpGet("{userId}")]
        public ActionResult Get(long userId)
        {
            return Ok(new List<UserListItem> { new UserListItem() { ListId = Guid.NewGuid().ToString("N"), Name = "Test" } });
        }
```

When I attempt to access the swagger document "An unhandled exception occurred while processing the request" is thrown with a KeyNotFoundException.

I know that the **BadObjectRequestResult** type is the cause of the issue, because if I remove it, the exception doesn't occur.

The attached file is the HTML error page provided from /swagger/v1/swagger.json request.

[Internal Server Error.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/3253731/Internal.Server.Error.txt)

**Comment by domaindrivendev** [comment]
I can't repro this on the latest code. There's no official Nuget yet (still working through some bugs before official release) but if you download the [latest preview from my.get.org](https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) things should be working.
