### ISSUE TITLE
Using Custom Classes In Swashbuckle Docs

### ISSUE THREAD

**Issue by StuartFergusonVme** [domaindrivendev/Swashbuckle.AspNetCore#1174]
I am currently using Swashbuckle to document my API successfully for most of my methods.

However one of my api methods is written to take in a base class for request messages and then internally using the dyanmic keyword call a specific private method to handle the specific inherited version:

```
public async Task<IActionResult> PostEvent([FromBody] DomainEvent @event,
                                           CancellationToken cancellationToken)
{
    await this.HandleSpecificDomainEvent((dynamic)domainEvent, cancellationToken);

    return this.Ok();
}

private async Task HandleSpecificDomainEvent(EventType1 domainEvent,
                                             CancellationToken cancellationToken)
{
    // Do something here
}
``` 
This means that when Swashbuckle documents this method it only documents the base DomainEvent class.

Is there a way (either configuration or tagging the inherited classes) that I can get the inherited class definitions to be included in the generated Swagger documentation, without having to put a controller method in for each type.

**Comment by domaindrivendev** [comment]
Which version are you using? If you upgrade to 5.0.0rc2 (currently in pre release phase), you can do this by opting into “polymorphic schema” via the “GeneratePolymorphicSchemas” confit option.

**Comment by StuartFergusonVme** [comment]
Just tried as you suggested but the option is not making any difference :(

Here is my configuration section:

```
services.AddSwaggerGen(c =>
                                   {
                                       c.SwaggerDoc("v1",
                                                    new OpenApiInfo
                                                    {
                                                        Title = "My Test API",
                                                        Version = "v1"
                                                    });
                                       c.SchemaGeneratorOptions.GeneratePolymorphicSchemas = true;
                                   });
```

Is there anything else I need ?

**Comment by domaindrivendev** [comment]
Hmmm - that should work just fine. In fact this is working as expected in the "Basic" sample app in this repo. Try taking a look there to see if there's anything you've missed:

- Controller: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/Basic/Controllers/PolymorphicTypesController.cs
- Startup: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/Basic/Startup.cs#L63

**Comment by domaindrivendev** [comment]
Here's what you should see in the UI:

<img width="502" alt="screenshot" src="https://user-images.githubusercontent.com/1434343/59601737-d454db00-90fc-11e9-902e-746853050020.png">

**Comment by StuartFergusonVme** [comment]
Ok thanks managed to get that working now.
