### ISSUE TITLE
SwaggerUIOptions configured from appsettings.json not honored by `UseSwaggerUI` with configuration callback

### ISSUE THREAD

**Issue by ggirard07** [domaindrivendev/Swashbuckle.AspNetCore#1181]
**Steps to reproduce**
1. Create a new ASP.Net Core WebAPI project and add Swashbuckle.AspNetCore NuGet v4.0.1
2. In the Startup class, configure `SwaggerUIOptions` from appsettings.json
```csharp
public void ConfigureServices(IServiceCollection services)
{
  ...
  services.AddSwaggerGen();
  services.Configure<SwaggerUIOptions>(cfg => Configuration.Bind("SwaggerUI", cfg));
  ...
}
```
3. Also, override SwaggerUI configuration when adding middleware
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
  ...
  app.UseSwagger();
  app.UseSwaggerUI(c =>
  {
    //change anything here, as long as delegate is passed in
  }
  ...
}
```

**Expected behavior**
Configuration defined in `appsettings.json` is used and overridden by the delegate of the call to `UseSwaggerUI`.

**Actual behavior**
Configuration defined in `appsettings.json` are ignored.

**Remarks**
Current behavior is related to [how the `SwaggerUIOptions` instance is currently manually instantiated by `UseSwaggerUI`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs#L20). Dependency injection is bypassed. Instance should be resolved from the registered services instead:
```csharp
app.ApplicationServices.GetService<IOptions<SwaggerUIOptions>>();
```

I am not very familiar with ASP.Net Core middleware, but I can open a PR if this fix looks good to you.

**Comment by domaindrivendev** [comment]
This is supported in the latest code
