### ISSUE TITLE
System.Type is not supported by SwaggerGen

### ISSUE THREAD

**Issue by CodeTherapist** [domaindrivendev/Swashbuckle.AspNetCore#1185]
**This applies for the version 5.0.0-rc2, seems to be fixed in master branch.**

I tried to integrate `Swashbuckle.AspNetCore` accordingly to [Getting started with swashbuckle](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio).

Inside my application I have a model that has a property of type `System.Type`.
Unfortunately, the `Swashbuckle` threw a `System.Collections.Generic.KeyNotFoundException`:

```
   An unhandled exception has occurred while executing the request.
System.Collections.Generic.KeyNotFoundException: The given key 'System.Type' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Swashbuckle.AspNetCore.SwaggerGen.PrimitiveSchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
// [...] ommited for simplicity
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
After my investigation, I found out that Json.NET creates a [JsonStringContract](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonStringContract.cs) for a property of type `System.Type`.

The `JsonStringContract` is inheriting from the `JsonPrimitiveContract` and this let's the `PrimitiveSchemaGenerator` [handle ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/07adbdbf833510bfb050b98da3a037c2f911722b/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGen/PrimitiveSchemaGenerator.cs#L28) `System.Type` as well and throws because the [dictionary ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/07adbdbf833510bfb050b98da3a037c2f911722b/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGen/PrimitiveSchemaGenerator.cs#L91) doesn't contain this type as key.

**Comment by dongshengfengniaowu** [comment]
The same error . Anyone can help?

**Comment by CodeTherapist** [comment]
I fixed it, I can do a PR for it.

**Comment by WarpSpideR** [comment]
I'm coming across this problem too and can confirm that it is fixed in the master! Can we have another release candidate @domaindrivendev?

**Comment by magicbash** [comment]
I have same issue with Microsoft.AspNetCore.Http.PathString.

**Comment by domaindrivendev** [comment]
I believe this is fixed with the latest code (both Type and PathString both default to a string schema). There's no official Nuget yet (still working through some bugs before official release) but if you download the [latest preview from my.get.org](https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) things should be working.

**Comment by Ibro** [comment]
I have similar issue.

> KeyNotFoundException: The given key 'System.Version' was not present in the dictionary.
