### ISSUE TITLE
Enable support for multiple examples

### ISSUE THREAD

**Issue by alxleo** [domaindrivendev/Swashbuckle.AspNetCore#1186]
Swagger UI 3.23.0 was recently released with a feature to support multiple examples. This is one of the longest awaited issues (https://github.com/swagger-api/swagger-ui/issues/2651) and one that is exciting to have available on our projects.

Could you consider adding support for it on the current release?

**Comment by domaindrivendev** [comment]
As of `v5.0.0` Swashbuckle has been shipping with swagger-ui `v3.24.3` or higher.
