### ISSUE TITLE
.NET Core 2.2 and Swagger UI is not Displaying After Publish

### ISSUE THREAD

**Issue by sbrfarhadi** [domaindrivendev/Swashbuckle.AspNetCore#1190]
hi
I use ASP Core 2.2
my config endpoint:
 c.SwaggerEndpoint("/swagger/v1/swagger.json", "my api1");
Swagger works in locals

But Swagger does not show after the project's release (**add in IIS**)
(http://localhost:1404/swagger/index.html error page can’t be found)

but show json in url http://localhost:1404/swagger/v1/swagger.json

Swashbuckle.AspNetCore v4.0.1
Swashbuckle.AspNetCore.Swagger v4.0.1
Swashbuckle.AspNetCore.SwaggerGen v4.0.1
Swashbuckle.AspNetCore.SwaggerUI v4.0.1

**Comment by minhSkoolbo** [comment]
having the same issue here. All the files under /swagger folder are missing
```
/swagger/swagger-ui.css net::ERR_ABORTED 404 (Not Found)
/swagger/swagger-ui-bundle.js net::ERR_ABORTED 404 (Not Found)
/swagger/swagger-ui-standalone-preset.js net::ERR_ABORTED 404 (Not Found)
/swagger/swagger-ui-bundle.js net::ERR_ABORTED 404 (Not Found)
/swagger/swagger-ui-standalone-preset.js 404 (Not Found)
```

It also works fine in local for me. Core 2.2, Swashbuckle.AspNetCore v4.0.1 too.

**Comment by heqiao** [comment]
Same issue. Any solution or work around?

**Comment by knasher** [comment]
I had this issue and it was due to this line in the `UseSwaggerUI` method:
```
c.RoutePrefix = string.Empty;
```
Try removing it if it's there, it worked for me.

**Comment by heqiao** [comment]
I do have `c.RoutePrefix = "api-docs/swagger";` in `UseSwaggerUI`, but removing it doesn't work either, the same error messages @minhSkoolbo posted after publishing.

**Comment by minhSkoolbo** [comment]
Yup, setting correct RoutePrefix fixed my issue.
RoutePrefix was set to string.Empty and it was exactly what caused the problem.
Here's the correct code in my case for your reference.
```
c.SwaggerEndpoint("/swagger/v1/swagger.json", "API V1");
c.RoutePrefix = "swagger";
```

**Comment by heqiao** [comment]
@minhSkoolbo sorry for the late update, my issue was resolved.

```
        private const string RoutePrfix = "MY_CONTEXT_PATH/swagger";
        private const string RouteTemplate = "/swagger/{documentName}/swagger.json";
        private const string SwaggerEndpoint = "/swagger/v1/swagger.json";
        private const string SwaggerTitle = "RFP API";

            app.UseSwagger((c =>
            {
                c.RouteTemplate = RoutePrfix + RouteTemplate;
            }));
            app.UseSwaggerUI(c =>
            {
                c.RoutePrefix = RoutePrfix;
                c.SwaggerEndpoint($"/{RoutePrfix}{SwaggerEndpoint}", SwaggerTitle);
            });
```

**Comment by capdiem** [comment]
it does not work when I install `Swashbuckle.AspNetCore.Swagger`, `Swashbuckle.AspNetCore.SwaggerGen` and `Swashbuckle.AspNetCore.SwaggerUI` separately. However, it works when I install `Swashbuckle.AspNetCore` only.

**Comment by fmarakasov** [comment]
I my case the problem was with the IIS configuration itself: for newly created site, access to *.js and *.json files are not listed in Request Filtering feature. Once I added them, the problem has gone.

**Comment by Vaccano** [comment]
For me it was an issue with the following:

When I host locally, it looks like this:

> https://localhost:44304/swagger/index.html

And the swagger.json file is located at:

> https://localhost:44304/swagger/v1/swagger.json

When I host on IIS it looks like this:

> https://myhost.domain.net/myapplication/swagger/index.html

And the swagger.json file is located at:

> https://myhost.domain.net/myapplication/swagger/v1/swagger.json

But the code is looking for the swagger.json file at :

> https://myhost.domain.net/swagger/v1/swagger.json

(It is using an absolute path instead of a relative one.)

Not sure how to fix this yet...

**Comment by waelalshabani** [comment]
I had this error and fixed it by setting up the swagger middle-ware as follow:
```
app.UseSwaggerUI(c =>
{
       c.RoutePrefix = "v1";
       var basePath = string.IsNullOrWhiteSpace(c.RoutePrefix) ? "." : "..";
       c.SwaggerEndpoint($"{basePath}/swagger/{c.RoutePrefix}/swagger.json", "Name");
});
```
Which is based on this post: https://stackoverflow.com/a/56282125/5830500

**Comment by domaindrivendev** [comment]
Scanning the thread, this issue looks to be resolved. If folks are still seeing related issues, please re-open a new ticket with clear repro steps

**Comment by hkillp** [comment]
> For me it was an issue with the following:
> 
> When I host locally, it looks like this:
> 
> > https://localhost:44304/swagger/index.html
> 
> And the swagger.json file is located at:
> 
> > https://localhost:44304/swagger/v1/swagger.json
> 
> When I host on IIS it looks like this:
> 
> > https://myhost.domain.net/myapplication/swagger/index.html
> 
> And the swagger.json file is located at:
> 
> > https://myhost.domain.net/myapplication/swagger/v1/swagger.json
> 
> But the code is looking for the swagger.json file at :
> 
> > https://myhost.domain.net/swagger/v1/swagger.json
> 
> (It is using an absolute path instead of a relative one.)
> 
> Not sure how to fix this yet...

Adding the relative path to Swagger endpoint would fix it . Ex :  c.SwaggerEndpoint("./swagger/v1/swagger.json", "V1");

**Comment by mahmoodvcs** [comment]
I saw the actual error in the EventViewer. The XML file for XML comments was not in the publish folder. I copied it and it worked.

**Comment by hkilimci** [comment]
For .net core 5, swagger is added automatically on project creating. 

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSwaggerGen(c =>
        {
            c.SwaggerDoc("v1", new OpenApiInfo { Title = "MyProject.Api", Version = "v1" });
        });
    }

However, you need to make sure that two commented lines are out of the if block.

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider svp)
            {
                if (env.IsDevelopment())
                {
                    app.UseDeveloperExceptionPage();
                    //app.UseSwagger();
                    //app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "MyProject.Api v1"));
                }
    
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "MyProject.Api v1"));                 
    
            }

**Comment by ValalSidur** [comment]
Startup.cs change swagger sentence from env.IsDevelopment to outsite 

 if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseSwagger();
            app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "ApiClientes v1"));
            app.UseHttpsRedirection()

**Comment by tcunning** [comment]
I added a IsProduction to resolve the issue:

`
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseStaticFiles();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "MyRvLinkBridge v1"));
            }
            else if (env.IsProduction())
            {
                app.UseDeveloperExceptionPage();
                app.UseStaticFiles();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "MyRvLinkBridge v1"));
            }
`

This was for a test project, so I just used the same code as what was used for Development
