### ISSUE TITLE
 Swagger UI is displaying actual data as Example Values

### ISSUE THREAD

**Issue by CaveDweller92** [domaindrivendev/Swashbuckle.AspNetCore#1192]
I haven't specified any sample/example responses in the code but Swagger UI uses the actual values in the database to create example values. or rather values I have used with Swagger UI.

Screenshots 
![60946602-3e335f80-a30c-11e9-853c-971267e8423e](https://user-images.githubusercontent.com/34083662/61018946-1567a480-a3b6-11e9-84b5-eb54dd5dd2d1.png)

Is it possible to disable this option or Is there a workaround for this so that it won't display actual data?

**Comment by domaindrivendev** [comment]
This isn’t actual data from the database - that would be crazy! It’s canned examples provided by the UI based on the schema “type” and “format” described in the Swagger JSON - in your example “string” and “uuid” respectively

**Comment by HarithK92** [comment]
@domaindrivendev  Is it possible to set the UserId which is a uuid as "uuid" like "string" in other fields?
