### ISSUE TITLE
Header Authorization Parameter in 5.0.0-rc2

### ISSUE THREAD

**Issue by nerig** [domaindrivendev/Swashbuckle.AspNetCore#1197]
This applies for version 5.0.0-rc2
Target framework - netcoreapp3.0

Hello.
I can't get Swagger UI to parse/use the header's Authorization parameter.

When I expand an endpoint on the APIs list it is saying: 

> Could not render this component, see the console.

In the console, the error is:

> swagger-ui-bundle.js:70 TypeError: Cannot read property 'get' of undefined
>     at t.value (swagger-ui-bundle.js:82)
>     at t.render (swagger-ui-bundle.js:70)
>     at s._renderValidatedComponentWithoutOwnerOrContext (swagger-ui-bundle.js:70)
>     at s._renderValidatedComponent (swagger-ui-bundle.js:70)
>     at s._updateRenderedComponent (swagger-ui-bundle.js:70)
>     at s._performComponentUpdate (swagger-ui-bundle.js:70)
>     at s.updateComponent (swagger-ui-bundle.js:70)
>     at s.receiveComponent (swagger-ui-bundle.js:70)
>     at Object.receiveComponent (swagger-ui-bundle.js:13)
>     at Object.updateChildren (swagger-ui-bundle.js:70)

My code:

Startup.ConfigureServices() =>
```
services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo { Title = "MyApp", Version = "v1.0" });
    options.OperationFilter<SwaggerOperationFilter>();
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.Http,
        In = ParameterLocation.Header,
        Name = "Authorization",
        Scheme = "Bearer",
        BearerFormat = "JWT",
        Description = "JWT Authorization header using the Bearer scheme."
    });
    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
            },
            new string[] {}
        }
    });
});
```
Startup.Configure() =>
```
app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/swagger/v1/swagger.json", "MyApp v1.0");
    options.DocExpansion(DocExpansion.List);
});
```

SwaggerOperationFilter class:
```
public class SwaggerOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        var filterPipeline = context.ApiDescription.ActionDescriptor.FilterDescriptors;
        var isAuthorized = filterPipeline.Select(filterInfo => filterInfo.Filter).Any(filter => filter is AuthorizeFilter);
        var allowAnonymous = filterPipeline.Select(filterInfo => filterInfo.Filter).Any(filter => filter is IAllowAnonymousFilter);
        if (isAuthorized && !allowAnonymous)
        {
            var param = new OpenApiParameter();
            param.Name = "Authorization";
            param.In = ParameterLocation.Header;
            param.Description = "Authorization header using the Bearer scheme";
            param.Required = true;
            if (operation.Parameters == null)
                operation.Parameters = new List<OpenApiParameter>();
            operation.Parameters.Add(param);
        }
    }
}
```

Am I missing anything?

Thanks in advance for your help.

**Comment by lhysrc** [comment]
I set a schema to the `Parameter` and it works.
```
param.Schema = new OpenApiSchema
{
       Title = "Bearer",
       Type = "string",
       Format = "jwt-bearer",
}
```
But I don't know what is the correct value for the schema's properties.

**Comment by SledgeHammer01** [comment]
Have you gotten this to work in RC3? I'm having the same issue. The Schema thing didn't fix it.

**Comment by yfer** [comment]
I've had similar problems. 
SwaggerUI do not send Autorization header if you set: 
`Scheme = "Bearer"`
and will send if you set
`Scheme = "bearer"`

But i'm testing with RC4

**Comment by eyiadmin** [comment]
have you solved it? I still have problems now

**Comment by acclaimuser** [comment]
Still an issue with 5.0.0-rc5

**Comment by lnaie** [comment]
I see this happening with dotnet core 2.2 and 3.1 after I migrated to swahsbuckle 5.0. 
My operation filter looks like this:
```
public class ApiHeadersFilter : IOperationFilter
{
    private readonly IAppSettings _appSettings;

    public ApiHeadersFilter(IOptions<AppSettings> appSettings)
    {
        _appSettings = appSettings.Value;
    }

    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        if (operation.Parameters == null)
        {
            operation.Parameters = new List<OpenApiParameter>();
        }

        operation.Parameters.Add(new OpenApiParameter
        {
            Name = "Authorization",
            In = ParameterLocation.Header,
            Description = "Authorization token",
            Required = true,
            Style = ParameterStyle.Simple,
        });

        [...]
    }
}
``` 
The ui looks like this:
![image](https://user-images.githubusercontent.com/1276077/72893138-a2ea6080-3d18-11ea-913b-f975ab0a0588.png)

**Comment by lnaie** [comment]
Ok, I have figure what was breaking the UI. Every defined OpenApiParameter needs the schema property set:
```
Schema = new OpenApiSchema
{
     Type = "string" // or other type
}
```

**Comment by Cantaria** [comment]
I have the same issue with version 5.0.0.. The Header for the token is not set.

When i test my REST-Service in Postman, everything is fine. 

`
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "My REST", Version = "v1" });

                var securityScheme = new OpenApiSecurityScheme
                {
                    In = ParameterLocation.Header,
                    Description = "Please enter the JWT Bearer token in format: Bearer {token}",
                    Name = "Authorization",
                    Type = SecuritySchemeType.ApiKey,
                    Scheme = "Bearer"
                };
                var securityRequirement = new OpenApiSecurityRequirement
                {
                    {securityScheme, new List<string>() }
                };

                c.AddSecurityDefinition("Bearer", securityScheme);
                c.AddSecurityRequirement(securityRequirement);
            });
`

**Comment by ronaldhoek** [comment]
Please take a look at the code I added for another issue: #971 (comment)

It's the code I use to be able to specify a JWT bearer token using version 5.x
Should be adaptable to your case ;)

**Comment by china-live** [comment]
update Bearer to  bearer

**Comment by martincostello** [comment]
Closing as external.

**Comment by eyiadmin** [comment]
你好、我暂时不能回复你的信息、、请电话联系、13548074395、谢谢合作
