### ISSUE TITLE
Don't référence all by default 

### ISSUE THREAD

**Issue by clintnetwork** [domaindrivendev/Swashbuckle.AspNetCore#1206]
Hi,

Maybe you can add an option to don't enable registering all controllers, I've a problem with a markdown processor, please check https://github.com/RickStrahl/Westwind.AspNetCore.Markdown/issues/8

Thank you

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#omit-actions-by-convention

**Comment by clintnetwork** [comment]
Ha interesting :D

And congrats your libs is very cool

**Comment by clintnetwork** [comment]
@domaindrivendev maybe you can add this to the documentation: https://gist.github.com/clintnetwork/5aee1c0f76a1d81ff4e16bd661964616

Cheers
