### ISSUE TITLE
Casting Issue with OpenApiAnyFactory

### ISSUE THREAD

**Issue by StrictlyDPBlaine** [domaindrivendev/Swashbuckle.AspNetCore#1207]
In master right now there is an issue with the OpenApiAnyFactory specifically the private static TryCast method. 

When trying to cast a decimal to double the TryCast method is failing. I created a simple example of the issue below.

```
void Main()
{
    var foo = 4.3m;
    var bar = TryCast<double>(foo, out var doubles);
    // bar is null
}


private static bool TryCast<T>(object value, out T typedValue)
{
    try
    {
        typedValue = (T)value;
        return true;
    }
    catch (InvalidCastException ex)
    {
        typedValue = default(T);
        return false;
    }
}
```
I believe the root issue is the object type casting that happens in the method signature. While (double)4.3m is fine, what I think is being executed is  (double)(object)4.3m which throws an exception.

**Comment by domaindrivendev** [comment]
Thanks for digging into this. Seems like a fix maybe fairly straightforward. Interested in submitting a PR?
