### ISSUE TITLE
SwaggerGen - Parameter 'Explode' value not being serialized correctly

### ISSUE THREAD

**Issue by bmcockman** [domaindrivendev/Swashbuckle.AspNetCore#1212]
Using  v5.0.0-rc2, it's likely this same problem occurs in the stable version too.

As per the swagger parameter specification for [Query Parameters](https://swagger.io/docs/specification/serialization/#query), when the _style_ is set to _form_, the default _explode_ value is _true_. 

When adding a parameter like so:
```
OpenApiParameter param = new OpenApiParameter();
param.name = "Foo";
param.In = ParameterLocation.Query;
param.Style = ParameterStyle.Form;
param.Explode = false;
param.Schema = new OpenApiSchema
{
    Type = "array",
    Items = new OpenApiSchema
    {
        Type = "string"
     }
};
```

This serializes to:
```
"parameters": [
{
	"name": "Foo",
	"in": "query",
	"style": "form",
	"schema": {
		"type": "array",
		"items": {
			"type": "string"
		},
	}
}]
```

The explode property is not serialized therefore, defaults to true based on the style, when it should be false.

**Comment by domaindrivendev** [comment]
This appears to be working correctly in the latest master version, which will be available very soon as `v5.6.0`. That is, when I add the parameter as specfied above, `explode: false` is serialized to the the generated JSON.
