### ISSUE TITLE
ActionResult is part of model

### ISSUE THREAD

**Issue by tornie2** [domaindrivendev/Swashbuckle.AspNetCore#1214]
When a controller method returns ActionResult<T>, the ActionResult object becomes part of the model in the Swagger documentation. This is of course misleading in the Swagger UI, as the ActionResult is not really returned to the client.

My method looks like this:

        [HttpGet]
        public ActionResult<HelloWorldResponse> Get(string callerId)
        {
            var response = new HelloWorldResponse { Greeting = "Hello world" };
            return Ok(response);
        }

This is my output-class

    public class HelloWorldResponse
    {
        public string Greeting { get; set; }
    }

ActionResult is included in the schema

    "/api/HelloWorld": {
      "get": {
        "tags": [
          "HelloWorld"
        ],
        "operationId": "Get",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "callerId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Microsoft.AspNetCore.Mvc.ActionResult`1[[StarterHttpRestHost.Controllers.HelloWorldResponse, StarterHttpRestHost, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"
            }
          }
        }
      }
    },

using version 4.0.1 of SwashBuckle

    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />

**Comment by domaindrivendev** [comment]
Which version of AspNetCore are you using?

**Comment by tornie2** [comment]
I reference Swashbuckle from a netstandard2.0 library

    <TargetFramework>netstandard2.0</TargetFramework>

**Comment by tornie2** [comment]
[Reproduce.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/3464939/Reproduce.zip)

I've made a small project to reproduce the problem.

**Comment by Mhirji** [comment]
@tornie2, have you tries adding the Produces decorator to you method?

**Comment by tornie2** [comment]
Looks like the Produces decorater does fix the problem.

I just didn't think that was necessary?
Shouldn't Swashbuckle be able to derive the schema, when my returntype is ActionResult<Greeting>

**Comment by domaindrivendev** [comment]
Swashbuckle is built on ApiExplorer (part of AspNetCore) and it’s in fact ApiExplorer that has the issue. I believe they resolved as of version 2.1. Try upgrading to that version of AspNetCore and things should work as expected

**Comment by tornie2** [comment]
Upgrading to 2.2 of ApiExplorer fixed the issue.
Thanks a bunch :-)
