### ISSUE TITLE
Http ambiguous when implementing IActionFilter on controller whose inherit ControllerBase

### ISSUE THREAD

**Issue by Davilink** [domaindrivendev/Swashbuckle.AspNetCore#1219]
I tried to do something like this:
```
public class TestController : ControllerBase, IActionFilter {
  public string AcceptLanguage { get; set; }

  [HttpGet]
  public string GetTest()
  {
    return AcceptLanguage;
  }

  public void OnActionExecuting(ActionExecutingContext context)
  {
      AcceptLanguage = AcceptLanguageHelpers.Extract(context.HttpContext.Request);
  }

  public void OnActionExecuted(ActionExecutedContext context)
  {
  }
}
```
But i received this error
![image](https://user-images.githubusercontent.com/1498932/62583640-ff4ae800-b87e-11e9-84e4-1345a9a47a89.png)
![image](https://user-images.githubusercontent.com/1498932/62583642-070a8c80-b87f-11e9-80a7-094e526967cf.png)

I made it work with :
```
public class TestController : Controller {
  public string AcceptLanguage { get; set; }

  [HttpGet]
  public string GetTest()
  {
    return AcceptLanguage;
  }

  protected override void OnActionExecuting(ActionExecutingContext context)
  {
      AcceptLanguage = AcceptLanguageHelpers.Extract(context.HttpContext.Request);
  }

  protected override void OnActionExecuted(ActionExecutedContext context)
  {
  }
}
```
If i add `[ApiExplorerSettings(IgnoreApi = true)]` the problem go away, because swagger exclude this method from the generation.
```
public class TestController : ControllerBase, IActionFilter {
  public string AcceptLanguage { get; set; }

  [HttpGet]
  public string GetTest()
  {
    return AcceptLanguage;
  }

  [ApiExplorerSettings(IgnoreApi = true)]
  public void OnActionExecuting(ActionExecutingContext context)
  {
      AcceptLanguage = AcceptLanguageHelpers.Extract(context.HttpContext.Request);
  }

  [ApiExplorerSettings(IgnoreApi = true)]
  public void OnActionExecuted(ActionExecutedContext context)
  {
  }
}
```

Is that a reason why swagger don't exclude by default these method ?

Is swagger would be able to filter out the method if the class inherit from IActionFilter ?

**Comment by domaindrivendev** [comment]
OK - I don't see anything in that article that suggests having the controller _itself_  implement `IActionFilter`. You typically implement an action filter as a separate component and then inject it into your pipeline via global configuration or attributes.
