### ISSUE TITLE
SwaggerResponseAttribute applied on base controller not visible in derived controller

### ISSUE THREAD

**Issue by leppie** [domaindrivendev/Swashbuckle.AspNetCore#122]
Seems the attributes are not read from a base controller class.

**Comment by leppie** [comment]
This is simple fix: https://github.com/domaindrivendev/Ahoy/blob/master/src/Swashbuckle.SwaggerGen/Generator/ApiDescriptionExtensions.cs#L50

pass `true` instead of `false`

**Comment by leppie** [comment]
See: https://github.com/domaindrivendev/Ahoy/commit/47d2e95ad92da70bda4eb5f68fe3373bf3919969

**Comment by domaindrivendev** [comment]
SwaggerResponseAttribute has been removed in favor of AspNet Core's built-in __ProducesResponseTypeAttribute__. You should use this instead and it should be picked up from base controllers.

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"
