### ISSUE TITLE
Execute button no longer working after adding filter where the last NonBodyParameter has Required set to true

### ISSUE THREAD

**Issue by djangojazz** [domaindrivendev/Swashbuckle.AspNetCore#1222]
This appears to be happening to me when I am running production version 4.0.1 in a Net Core 2.2 app.  I have a List of IParameter I set to implement an IOperationFilter.  The Execute button appears to not work if the final parameter added has a 'Required' set to true.

//If this is the last parameter
operation.Parameters.Add(new NonBodyParameter
                {
                    Name = "Id"
                   Description = "Test"
                    In = "header",
                    //I have not done thorough testing but thus far this disables the execute on the UI generated
                    Required = true,
                    Type = "int",
                });

**Comment by djangojazz** [comment]
The work around for me is to just ensure the last parameter does NOT have the Required option at all.

**Comment by domaindrivendev** [comment]
Hmm ... I've no idea either but because it's UI related, I'm going to close the issue here and suggest you post your issue to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui) instead.

Happy to re-open if you can confirm it's related to this project but right now there's nothing pointing in that direction.

**Comment by oleksiivasylenko** [comment]
Hi @domaindrivendev, I have similar issue, could you please review it.

Problem 1
When data is entered in required field it is still highlighted as required. I found that problem occurs when the name of parameter in attribute "[HttpGet("{id}")]" is the same as the name of parameter in method "Get1(Guid id)".
---- Look at - WeatherForecastController.cs -> 29-30 lines

Problem 2(found while testing problem 1)
When the name in attribute is different from the name in method parameter
EG: [HttpGet("byname/{name}")], Get2(Guid id)
Filed "Id" in swagger UI becomes required when you enter any data in it
---- Look at - WeatherForecastController.cs -> 46-47 lines

ASP NET core 3.0
Swashbuckle.AspNetCore - 5.0.0-rc4

Here is link to git repository with this error
https://github.com/oleksiivasylenko/swaggerUI-required-error.git
Here is the link to video which shows problems
https://youtu.be/LlEi3ycAiY0
