### ISSUE TITLE
Mark property as required without the [Required] attribute

### ISSUE THREAD

**Issue by mattfrear** [domaindrivendev/Swashbuckle.AspNetCore#1224]
I understand that Swashbuckle supports the [Required] attribute on request model properties, i.e.
```csharp
public class ChangeLineNumberViewModel
{
    /// <summary>
    /// The domain user who is changing the line number, i.e. TPWR\\johnd
    /// </summary>
    [Required]
    public string RequestedBy { get; set; }
}
```

However, `[Required]` signals to MVC model binding that the field is Required, and model binding intercepts the requests and gets in the way of my own internal validation which I wish to use (so that I can return a [Problem details](https://tools.ietf.org/html/rfc7807)).

I guess what I'd like is perhaps a `[SwaggerRequired]` attribute I can use instead, so that the property is marked as required in the swagger doc.

**Comment by domaindrivendev** [comment]
A solution for this is now merged to master and queued up for the `v5.3.0` release (due next week). There's now a `SwaggerSchemaAttribute` that can be applied to classes OR properties. When you apply it to a class you can provide a list of corresponding JSON properties to be marked `required`:

```csharp
[SwaggerSchema(Required = new[] { "RequestedBy" })]
public class ChangeLineNumberViewModel
{
    public string RequestedBy { get; set; }
}
```

To use this you'll have to have the `Annotations` package installed and explicitly opted-in as described [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcoreannotations)

**Comment by mattfrear** [comment]
That's great, thank you very much! I'll give it a try during the week.

**Comment by mattfrear** [comment]
It's a pity I have to install all of these packages to my ViewModels project.

![image](https://user-images.githubusercontent.com/169179/78467899-effda080-7765-11ea-8eef-0ed7495daf1f.png)

I'll try move my ViewModels into my Web project, and then try it.

I have the same issue with method parameters. Is there a way to do that?

    public async Task<IActionResult> CancelOrder(int orderId, [Required]string requestedBy)
    {

**Comment by Snazzie** [comment]
@domaindrivendev That solution is not nice to use at all. Should there not be a way to set globally or a swagger variant of `[Required]` that doesnt affect .net model

**Comment by hlovdal** [comment]
@Snazzie, @mattfrear  There is a custom `[SwaggerRequired]` attribute presented in [this answer](https://stackoverflow.com/a/53377173/23118), although I agree this should be something that comes standard and not something that needs custom extra code.

Ideally there should also exist a `[SwaggerOptional]` attribute that does nothing but with some check than you then can configure to blow for anything that does not have one of the two attributes. Any suggestions how to achieve this?
