### ISSUE TITLE
ASP.NET Core 3 Preview 8 - swagger.json 404

### ISSUE THREAD

**Issue by zHaytam** [domaindrivendev/Swashbuckle.AspNetCore#1227]
ConfigureServices:
```csharp
services.AddControllers();

services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("", new Microsoft.OpenApi.Models.OpenApiInfo
    {
        Title = "My API",
        Version = "v1"
    });
});
```

Configure:
```csharp
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseHttpsRedirection();
app.UseRouting();
app.UseAuthorization();

app.UseSwagger();

// Adds swagger UI
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});
```

Swashbuckle version: 5.0.0-rc2  

Problem: `https://localhost:44392/swagger/v1/swagger.json` returns a 404 and the UI says `Fetch error undefined /swagger/v1/swagger.json`.

Am I doing something wrong?

**Comment by zHaytam** [comment]
I'm ashamed... The problem was the empty name in `c.SwaggerDoc`. Weird that it doesn't give any errors :/

**Comment by leosaravia** [comment]
Well... I may be more ashamed than you as my problem was not to map the controllers... so thanks anyway as I could fix my error by seeing your code. 

Code missing: 
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});
