### ISSUE TITLE
Filters for modifying outgoing requests of Swagger UI

### ISSUE THREAD

**Issue by MontyGvMC** [domaindrivendev/Swashbuckle.AspNetCore#1230]
Currently I see no way to influence redirects (or generally any outgoing request) from the Swagger UI.

Sure, we can define how the requests are defined and should look like but it seems once they are defined the UI takes them as defined and from there on they are unchangeable.

What I am talking about are two scenarios:

Redirects:
I have a controller method taking a path (bucket key) and it returns a redirect to a presigned URL. I can define which parameters the method takes, I can define how the reponse looks like and how the method call is authorized. That works pretty well.
The problem starts when the Swagger UI receives the response and starts handling the redirect. It seems not possible (via a filter or anything) to communicate the Swagger UI that the redirect should not hold the authorization header (bearer token) it used on the request resulting in the redirect.
This causes the problem that the bearer token is sent to any server the redirect points to.

Other use case:
In an existing (released) API I recognized a suboptiomal endpoint definition. It's a POST method to a controller expecting content-type "application/json". Since the POST method does not have any arguments (no body, no query parameter, it just takes the data from the token) Swagger UI (correctly) sends an empty body without content-type header. This causes the Swagger UI calls to fail with Unsupported Media Type. The other clients (which send the content-type header) work as expected.

A filter for outgoing requests would allow to let us write some code like:

if request going to different domain then remove a header

if request going to a specific action/url then add a header

**Comment by domaindrivendev** [comment]
I believe the following functionality will give you what you need:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#use-client-side-request-and-response-interceptors

This was only recently merged and isn't available as an official Nuget yet (that's coming real soon). However you can pull down the latest preview build from [myget.org](https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) to try it out.
