### ISSUE TITLE
Fixes to Customize the Action Selection Process documentation

### ISSUE THREAD

**Issue by jstawski** [domaindrivendev/Swashbuckle.AspNetCore#1232]
Hello, thanks for the community for this awesome repo and middleware! I just want to donate my small contribution by changing the documentation on the [Customize the Action Selection Process ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-the-action-selection-process). I know it is just a sample, but might as well... From my testing, `ApiVersion` attribute is only used if the method doesn't have a `MapToApiVersionAttribue`. The documentation only checks for `ApiVersion`. Below is my contribution:

```
c.DocInclusionPredicate((docName, apiDesc) =>
{
    if (!apiDesc.TryGetMethodInfo(out MethodInfo methodInfo)) return false;

    // Get the MapToApiVersion attributes of the action
    var mapApiVersions = methodInfo
        .GetCustomAttributes(true)
        .OfType<MapToApiVersionAttribute>()
        .SelectMany(attr => attr.Versions);

    //if it contains MapToApiVersion attributes, then we should check those as the ApiVersion ones are ignored
    if (mapApiVersions.Any() && mapApiVersions.Any(v => $"v{v.ToString()}" == docName))
                        return true;

    // Get the ApiVersion attributes of the controller
    var versions = methodInfo.DeclaringType
        .GetCustomAttributes(true)
        .OfType<ApiVersionAttribute>()
        .SelectMany(attr => attr.Versions);

    return versions.Any(v => $"v{v.ToString()}" == docName);
});
```
Since i'm not an expert on `Microsoft.AspNetCore.Mvc.Versioning`, this still needs to be confirmed, but I can say that It Works in My Machine.

**Comment by domaindrivendev** [comment]
Looks like the ApiVersioning lib has a well-documented alternative approach for integrating with Swashbuckle:

https://github.com/microsoft/aspnet-api-versioning/wiki/API-Documentation#aspnet-core

So probably this example should be changed to something a little more trivial in general.
