### ISSUE TITLE
OAuth2 Implicit not working with AzureAD id_token

### ISSUE THREAD

**Issue by cjamesrohan** [domaindrivendev/Swashbuckle.AspNetCore#1235]
Looks like the authentication request is hard-coding the response_type of 'token'. We need the ability to send 'id_token token' as the response type in order to get an id_token back from AzureAD and have that id_token passed in the auth header instead of the access_token.

I am using OIDC with Azure v2.0 endpoints for OAuth2. Running on dotnet core 2.2 and Swashbuckle.AspNetCore 4.0.1.

Url showing response_type of token:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=token&client_id=.......

**Comment by krdmllr** [comment]
I ran into the same problem and found two solutions:
1. Update to Swashbuckle 5 which uses a Swagger UI version that supports OIDC
2. A little hack in the current version: You can add the response type directly to the authorization url like this:
```
c.AddSecurityDefinition("oauth2", new OAuth2Scheme 
{
    Type = "oauth2",
    Flow = "implicit",
    AuthorizationUrl = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize**?response_type=token id_token**",
    Scopes = new Dictionary<string, string> 
    {
        {"openid", "oidc standard"}
    }
});
```

**Comment by cjamesrohan** [comment]
Thanks for your reply. Unfortunately, adding the response_type in this manner results in an AzureAD error stating the following: "AADSTS9000411: The request is not properly formatted. The parameter 'response_type' is duplicated."

I was, however, able to use an older method to replace the response_type query param to what I want. This works, but then I can't seem to tell Swagger UI to use the id_token for my authorization, instead of the access_token.

I attempted using Swashbuckle 5.0.0-rc2, which allowed me to configure OIDC. After clicking the Authorize button, the modal that pops up was blank. Maybe I just need to play with that some more. Do you have an example by chance?

**Comment by cjamesrohan** [comment]
With 5.0.0-beta2, i've tried this:
```csharp
c.AddSecurityDefinition("oidc", new OpenApiSecurityScheme
{
    Type = SecuritySchemeType.OpenIdConnect,
    OpenIdConnectUrl = new Uri("https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration")
});
```

From what I understand, scope definitions are not needed here since those are available in the discovery url. I have tried specifying an implicit flow with and without scopes anyway, just in case, same result. Available authorizations modal is empty, so I cannot continue to authorize in Swagger UI.

**Comment by krdmllr** [comment]
Oh, it worked with the oidc implementation I tested https://demo.identityserver.io/

I actually had the same problem with the v5 version. Did you see that there is a dedicated documentation for v5? https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README-v5.md

You could open a new issue to either fix it if it is a bug or improve the documentation.

**Comment by cjamesrohan** [comment]
I reviewed the v5 docs, yes. Nothing specific about the OpenIdConnect security scheme. With your identityserver demo, did you just create your own identity server implementation? Or is that hitting an instance of Azure AD?

**Comment by cjamesrohan** [comment]
I have opened a new ticket specific to the blank modal in v5 rc2 #1241

**Comment by krdmllr** [comment]
>I reviewed the v5 docs, yes. Nothing specific about the OpenIdConnect security scheme. With your identityserver demo, did you just create your own identity server implementation? Or is that hitting an instance of Azure AD?

I used the demo server directly but it should not matter if you use another provider behind your instance since the request is processed by the identity server 4 logic.

**Comment by ahollandusc** [comment]
Looks like using swagger-ui 3.25 may fix this ?https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1525

**Comment by AKlaus** [comment]
Interesting, that a combination of these closed tickets should have solved the problem:

- [Support "x-tokenName" in swagger-ui](https://github.com/swagger-api/swagger-ui/issues/4084);
- [Support "x-tokenName" in Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1128).

But it didn't bring much joy to me.

Even after adding `Extensions = new Dictionary<string, IOpenApiExtension> { {"x-tokenName", new OpenApiString("id_token") } }`, _Swashbuckle_ still sends a request with `response_type=token` instead of `response_type=id_token`.

**Comment by hkosova** [comment]
> Interesting, that a combination of these closed tickets should solve the problem:
> 
> * [Support "x-tokenName" in swagger-ui](https://github.com/swagger-api/swagger-ui/issues/4084);
> * [Support "x-tokenName" in Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1128).
> 
> Though, after adding `Extensions = new Dictionary<string, IOpenApiExtension> { {"x-tokenName", new OpenApiString("id_token") } }`, _Swashbuckle_ still sends a request with `response_type=token` instead of `response_type=id_token`. Not sure if it's an expected behaviour

The issue where `response_type=token` is sent instead of `response_type=id_token` seems to be a Swagger UI limitation/bug. Open an issue in the Swagger UI repo (if not already):
https://github.com/swagger-api/swagger-ui/issues

**Comment by rizchaerul** [comment]
> I was, however, able to use an older method to replace the response_type query param to what I want. This works, but then I can't seem to tell Swagger UI to use the id_token for my authorization, instead of the access_token.

I'm having a problem that require me to replace response_type query param, how did you do it @cjamesrohan ? Thanks.

**Comment by cjamesrohan** [comment]
> > I was, however, able to use an older method to replace the response_type query param to what I want. This works, but then I can't seem to tell Swagger UI to use the id_token for my authorization, instead of the access_token.
> 
> I'm having a problem that require me to replace response_type query param, how did you do it @cjamesrohan ? Thanks.

I never did get it quite right and have since moved to another place where this is no longer a responsibility of mine. Unfortunately, I have not jumped back in to this issue yet I see what else can be done.

**Comment by gsGabriel** [comment]
> > Interesting, that a combination of these closed tickets should solve the problem:
> > 
> > * [Support "x-tokenName" in swagger-ui](https://github.com/swagger-api/swagger-ui/issues/4084);
> > * [Support "x-tokenName" in Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1128).
> > 
> > Though, after adding `Extensions = new Dictionary<string, IOpenApiExtension> { {"x-tokenName", new OpenApiString("id_token") } }`, _Swashbuckle_ still sends a request with `response_type=token` instead of `response_type=id_token`. Not sure if it's an expected behaviour
> 
> The issue where `response_type=token` is sent instead of `response_type=id_token` seems to be a Swagger UI limitation/bug. Open an issue in the Swagger UI repo (if not already): https://github.com/swagger-api/swagger-ui/issues
> 
> upd: This one seems related: [swagger-api/swagger-ui#3906](https://github.com/swagger-api/swagger-ui/issues/3906)

I still have the reported problem even though the mentioned issue has been closed.

How can I send the response_type as "id_token" instead of "token"?

**Comment by pregress** [comment]
@gsGabriel did you check the networking tab of devtools while loading the swagger UI? 
This might be a CORS issue

**Comment by martincostello** [comment]
Closing as external.
