### ISSUE TITLE
How to automatic save "swagger.json" to folder when debug on web API ?

### ISSUE THREAD

**Issue by uthens** [domaindrivendev/Swashbuckle.AspNetCore#1236]
Hi All,
Now i started to used Swagger and Docfx for generate on REST API document.

To related on this issue :
>> 1) dotnet/docfx#5012
>> 2) https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#feedback

Docfx : https://dotnet.github.io/docfx/

How to automatic save swagger.json file to folder for support with Docfx, when i run debug on web APIs project ?
My project to used .NET Core 2.2 on vs 2019

Thanks you

**Comment by BluMichele** [comment]
Any update?
