### ISSUE TITLE
Warn developers about duplicate operationIds

### ISSUE THREAD

**Issue by Alan-Hinton** [domaindrivendev/Swashbuckle.AspNetCore#1238]
With the current method of generating operationIds from ActionNames or RouteNames it is very easy to end up with duplicate operationIds.  The swagger spec says that all operationIds must be unique.  

It would be useful if the generation of the swagger.json threw an error or displayed a warning when there are duplicate operationIds.

**Comment by Lonli-Lokli** [comment]
@domaindrivendev  Not sure if my question related to it, but my scheme (v3) does not have operationId at all. Is it correct for 5.x?

**Comment by martincostello** [comment]
Closing due to age. If you still have this issue in the latest release of Swashbuckle please open a new issue.
