### ISSUE TITLE
Getting correct documentation on swagger UI from SwaggerResponse

### ISSUE THREAD

**Issue by ThomasArdal** [domaindrivendev/Swashbuckle.AspNetCore#1244]
I've recently moved from using Swashbuckle to Swashbuckle.AspNetCore. In the past, I could add code like this to an endpoint:

```csharp
[SwaggerResponse((int)HttpStatusCode.PaymentRequired, "Tried to call the deployment API without deployment tracking enabled."))]
```

Swagger UI would render a nice list of responses with their description:

![image](https://user-images.githubusercontent.com/563206/64335193-a0da6c00-cfda-11e9-9d5a-c98781840789.png)

After moving to Swashbuckle.AspNetCore, when adding the same attribute, I no longer see the response description:

![image](https://user-images.githubusercontent.com/563206/64335287-c7000c00-cfda-11e9-97c3-5d015eb7664c.png)

When looking through the swagger JSON, the descriptions aren't there:

```json
"responses":{  
  "402":{  
    "description":"Client Error",
    "schema":{  
      "$ref":"#/definitions/ProblemDetails"
    }
  }
}
```

Any idea of what could be wrong there?

**Comment by masterjs** [comment]
For me, I get the comments using the documentation. So I add something like this 
```
/// <summary>
/// My endpoint description,...
/// </summary>
/// <remarks>
/// More details if needed
/// </remarks>
/// <param name="paramX">description of this parameter</param>
/// <returns></returns>
/// <response code="200">Returned the data X</response>
/// <response code="400">An error occurred</response>
/// <response code="500">Internal/Service errors</response>
```

This will add the documentation on my Http status code

**Comment by ThomasArdal** [comment]
Thank you that works! TBH I like the strongly typed C# attributes, but comments will do for now.

**Comment by domaindrivendev** [comment]
@ThomasArdal - the attribute-based approach _should_ be working as you expect. However, in the latest version, that functionality is decoupled from the core library and needs to be explicitly enabled as described here - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcoreannotations

**Comment by ThomasArdal** [comment]
@domaindrivendev Thank you so much. I had indeed installed the NuGet package but forgot to call `EnableAnnotations` 🤦
