### ISSUE TITLE
Question/Ask: Please update nuget package, latest rc2 is 6 month old

### ISSUE THREAD

**Issue by yahorsi** [domaindrivendev/Swashbuckle.AspNetCore#1249]
Hi Guys!

Seems latest nuget 5.0.0-rc2 is already half-year old.
Are there reasons you do not update it?

In our project, we're thinking to move to the open api 3.0 and so are interested in updating Swashbuckle to the version that supports 3.0 and it is unfortunately not released yet ((

Thanks for all your great work!

**Comment by domaindrivendev** [comment]
I'm working on it. There's a couple of regressions I'm working through but hoping to have it out this month.
