### ISSUE TITLE
Generated swagger.json is not valid from the Autorest point of view

### ISSUE THREAD

**Issue by yahorsi** [domaindrivendev/Swashbuckle.AspNetCore#1250]
Hi Guys,

The issue we've got is described in the autorest repo, I'll leave link here in case if it is actually Swashbuckle issue.

https://github.com/Azure/autorest/issues/3305

Thanks for any input!

**Comment by domaindrivendev** [comment]
Closing because without confirmation that it's _actually_ a SB issue, it's just noise. If you can confirm it's a SB issue and can provide details to support that, please go-ahead and re-open. Thanks
