### ISSUE TITLE
[Feature Request] Overriding individual Property & Parameter types with [JsonSchema] Attribute

### ISSUE THREAD

**Issue by douglasg14b** [domaindrivendev/Swashbuckle.AspNetCore#1251]
In some cases specific properties need to have their Schema type overriden. I would have thought that SwaggerGen would accept the use of the `[JsonSchema]` attribute from [NJsonSchema](https://github.com/RicoSuter/NJsonSchema/wiki/JsonSchema), but it doesn't seem to affect the generated schema.

**Example 1**:

```cs
    public class TagResponse
    {
        [JsonSchema(JsonObjectType.String)]
        [JsonConverter(typeof(HashIdsConverter))]
        public int? Id { get; set; }
        public string Name { get; set; }
    }
```

Here the `int Id` is converted to and from a `string` in the form of a HashId (ie. Id `5` == `gR8q5b`). I have specified that the `JsonSchema` of the type, yet it still comes out as an `int` in the Swagger models.

**Example 2**:

```cs
        [HttpGet(TagRoutes.Get, Name = "GetTag")]
        [HashIdFilter(TagRoutes.IdParam)]
        public ActionResult<TagResponse> Get([JsonSchema(JsonObjectType.String)] int tagId)
        {
              //Do stuff
        }
```

Here the `id` parameter is an int and I have this action annotated with a filter. This filter transparently converts the `int id` to and from the `string` HashId. Requests are expected to provide a `string Id`, and responses respond with a `string Id`. However, the Swagger UI shows this as requiring an `int` which removes the ability to test this endpoint through Swagger as strings are not accepted to execute a request...

<hr>

Can this library support the use of the [JsonSchema] attribute to override the schema types of individual properties and parameters?

**Comment by domaindrivendev** [comment]
NSwag is a completely separate project and therefore, Swashbuckle _does not_ support attributes that it defines. However, if you read the documentation, you'll find that SB is highly extensible and provides it's own approach to customizing the generated schema for a given type - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#override-schema-for-specific-types

**Comment by douglasg14b** [comment]
Hi @domaindrivendev 

I wasn't aware this was specific to `NSwag`. Would it not be beneficial to allow for attribute-based schema overrides?

That aside:

I've read, and re-read the docs here and can't find what will let me override the types of an endpoint parameters. Maybe I'm just not understanding what part of the `MapType` performs that?

**Comment by wizofaus** [comment]
I know this is closed, but is the ability to override the schema for an individual function parameter still something that's yet to be implemented? If so, I'd be happy to have a go at doing so, as I need it for my current project (the parameter type is "JsonElement" for complex reasons, but I wanted to show as a specific type in the OpenAPI/swagger spec).

**Comment by wizofaus** [comment]
BTW, I figured it out how to add that functionality by picking up the 'cref' parameter from xml comments, just need to add this to the end of `XmlCommentsParameterFilter.ApplyParamTags`:

```
                var cref = paramNode.GetAttribute("cref", "")?.Split(':').Last();
                if (!string.IsNullOrEmpty(cref) && System.Type.GetType(cref) is System.Type type)
                {
                    parameter.Schema = context.SchemaGenerator.GenerateSchema(type, context.SchemaRepository);
                }
```

Obviously could use some error handling etc., but the basic principle works.  I'm not quite sure why the xml file has "T:" pre-pended to whatever type name you put in the `cref` attribute currently, hence the `Split(':').Last()`.
