### ISSUE TITLE
Swaggergen fails for method whose return type is XML

### ISSUE THREAD

**Issue by JJoe2** [domaindrivendev/Swashbuckle.AspNetCore#1256]
I want to document an AspNet Core Web API that has a method that returns XML and have followed the steps here to document my API using SwaggerGen v5.0.0-rc2: https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio

My documentation is generated successfully when I have a method in my API that returns `ActionResult<string>`.  I now want to change the return type to XML, so I changed the method signature to return `ActionResult<XmlElement>`.

When I run the application and navigate to swagger/v1/swagger.json I get an error with the stack trace below.  Is there a way to get Swashbuckle to document an API that returns XML?

NullReferenceException: Object reference not set to an instance of an object.
Swashbuckle.AspNetCore.SwaggerGen.TypeExtensions.IsNullable(Type type)
Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.ArraySchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(Type type, SchemaRepository schemaRespository)
System.Linq.Enumerable.ToDictionary<TSource, TKey, TElement>(IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector, IEqualityComparer<TKey> comparer)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(string statusCode, ApiResponseType apiResponseType, IEnumerable<object> methodAttributes, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, IEnumerable<object> methodAttributes, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by EvgeniyZ** [comment]
@JJoe2 it's not an issue in current master branch, so I guess in future release your problem will be solved
