### ISSUE TITLE
[Bug] Swashbuckle.AspNetCore.ReDoc no longer works on Chrome

### ISSUE THREAD

**Issue by alvaromarithompson** [domaindrivendev/Swashbuckle.AspNetCore#1260]
As posted [here](https://github.com/Redocly/redoc/issues/1036), ReDoc no longer seems to work with the latest version of Chrome, I am unsure if Swashbuckle.AspNetCore.ReDoc is still under development as the last RC was over six months ago, is this something that's likely to be fixed in the future?

**Comment by nathanvv** [comment]
Same here. Running into "Method Promise.prototype.then called on incompatible receiver" issue with the latest chrome.

**Comment by avk2k** [comment]
Same error: 
`Uncaught (in promise) TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at e.then (<anonymous>)`

**Comment by valentinmarinro** [comment]
Same error: TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]

**Comment by gangstatracer** [comment]
@domaindrivendev updated version of ReDoc to 1.22.3, now it work in Chrome 77. Could you please create a branch from [latest v4.x release tag](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/v4.0.1)? Then I would be able to create pull request with ReDoc package bump.

**Comment by holmesjr** [comment]
> @domaindrivendev updated version of ReDoc to 1.22.3, now it work in Chrome 77. Could you please create a branch from [latest v4.x release tag](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/v4.0.1)? Then I would be able to create pull request with ReDoc package bump.

You might have to fork the project.

**Comment by alvaromarithompson** [comment]
Hi guys,

Just a quick update to say that ReDoc is now working again with the release of Chrome 78, so I'm closing this ticket as it's no longer relevant.
