### ISSUE TITLE
DescribeAllEnumsAsStrings is obsolete

### ISSUE THREAD

**Issue by kluhman** [domaindrivendev/Swashbuckle.AspNetCore#1269]
In `Swashbuckle.AspNetCore.SwaggerGen-5.0.0-rc3`, the `DescribeAllEnumsAsStrings` method is marked obsolete and to-be-deprecated because it will automatically be applied if that convention is present in the serializer. However, the functionality is only present if `Newtonsoft.Json` is used as the serializer. If using the new default Json serializer in .NET Core 3, the `StringEnumConverter` is not respected.

**Reproduction Code**
```csharp
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllers()
            .AddJsonOptions(x =>
            {
                x.JsonSerializerOptions.WriteIndented = !Environment.IsProduction();
                x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
            });

            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
                options.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, @"MyApi.xml"));
            });
    }

    ...
}

public enum Result
{
    Success,
    Failed
}
```

![image](https://user-images.githubusercontent.com/12142251/65357911-dfb51800-dbbd-11e9-9d5f-c52860c31eb9.png)

**Edit:** Completely understand that this is obviously not removed from the API yet, and it does work if I add the `DescribeAllEnumsAsStrings()` and ignore the warning. More it's just an observation of functionality being reported obsolete that may be required if using the default serializer and wondering if there is a plan to implement that convention for the new serializer?

**Comment by domaindrivendev** [comment]
Full support for the new default serializer (i.e. `System.Text.Json`) and corresponding configuration options, is in development and will be added in a future minor version, _before_ the above setting is removed

**Comment by PauloVetor** [comment]
I solved it using ShemaFilter like this:
```
public class EnumSchemaFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema model, SchemaFilterContext context)
    {
        if (context.Type.IsEnum)
        {
            model.Enum.Clear();
            Enum.GetNames(context.Type)
                .ToList()
                .ForEach(n => model.Enum.Add(new OpenApiString(n)));
            }
        }
    }
}
```
And in Startup.cs:
```
services.AddSwaggerGen(options =>
{
    options.SchemaFilter<EnumSchemaFilter>();
}

**Comment by ZOXEXIVO** [comment]
@PauloVetor with this filter, Swagger UI show Validation error for all enums

**Comment by PauloVetor** [comment]
Try to add this:
```
...
model.Type = "string";
model.Enum.Clear();
...
```

**Comment by ggonzalez94** [comment]
Seems like this is fixed in version 5.0.0. Am I missing something?

Just added the following code in ConfigureServices, no need to set DescribeAllEnumsAsStrings in Swagger config
```
services.AddControllersWithViews()
                .AddJsonOptions(options => 
                options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
```

And heres the generated schema:
![image](https://user-images.githubusercontent.com/17907743/74534862-1001a800-4f0b-11ea-9e88-a3a78b2c414b.png)

**Comment by mberneti** [comment]
And in the end, I should say this does not work with  `AddNewtonsoftJson` and this config should be in the `AddJsonOptions` method.

**Comment by unchase** [comment]
Try to use [Unchase.Swashbuckle.AspNetCore.Extensions](https://github.com/unchase/Unchase.Swashbuckle.AspNetCore.Extensions) to fix the display of enums.

**Comment by cdiamonds** [comment]
> Seems like this is fixed in version 5.0.0. Am I missing something?
> 
> Just added the following code in ConfigureServices, no need to set DescribeAllEnumsAsStrings in Swagger config
> 
> ```
> services.AddControllersWithViews()
>                 .AddJsonOptions(options => 
>                 options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
> ```
> 
> And heres the generated schema:
> ![image](https://user-images.githubusercontent.com/17907743/74534862-1001a800-4f0b-11ea-9e88-a3a78b2c414b.png)

This solved my roblem. Thanks

**Comment by wizofaus** [comment]
Not working for me with 5.0.0 final release, in fact not even working if I use DescribeAllEnumsAsStrings. Was working fine with 4.0.1.  Using ASP.NET 2.1.

**Comment by domaindrivendev** [comment]
Dup of #1459. TL;DR this version defaults to honoring `System.Text.Json` (as opposed to `Newtonsoft`) serializer behavior. You need to expicitly opt-in to honoring Newtonsoft as described [here in the readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft)

**Comment by domaindrivendev** [comment]
Yes fully supported

**Comment by maulik-modi** [comment]
@domaindrivendev and @saborrie , What is recommended/supported way to do it globally in .NET 5 with System.text.json?

**Comment by ctolkien** [comment]
I cannot get this to work in V6. Some of the `JsonOptions` have changed which may be relevant?

**Comment by Trapov** [comment]
Cannot work this out with JsonOptions as well.

**Comment by shyboylpf** [comment]
It works in my net6 api.
`services.AddControllers()
                .AddJsonOptions(options =>
                {
                    // show enum value in swagger.
                    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
                });`

**Comment by Trapov** [comment]
Okay, if anyone can't make swagger work with your JsonOptions that's only because there are TWO of them  ([Microsoft.AspNetCore.Http.Json], [Microsoft.AspNetCore.Mvc]) and swagger works only with one.
 
 Configure them both with`IServiceCollection.Configure<Http.Json.JsonOptions>()` and `IServiceCollection.Configure<Mvc.JsonOptions>()` and everything should work fine.

**Comment by acp3012** [comment]
> options.SchemaFilter<EnumSchemaFilter>();

Excellent, I was looking for this one and finally got it :) Thank you

**Comment by rm-code** [comment]
Maybe I'm missing something here, but how  would I preserve the original values of the enums?
```csharp
  public enum Art
  {
    Foo = 1,
    Bar = 3,
    Baz = 7
  }
```
Generates
```csharp
  public enum Art
  {
    [System.Runtime.Serialization.EnumMember(Value = @"Foo")]
    Foo = 0,
    [System.Runtime.Serialization.EnumMember(Value = @"Bar")]
    Bar = 1,
    [System.Runtime.Serialization.EnumMember(Value = @"Baz")]
    Baz = 2,
  }
```

Is this possible?

**Comment by mpawelski** [comment]
> Seems like this is fixed in version 5.0.0. Am I missing something?
> 
> Just added the following code in ConfigureServices, no need to set DescribeAllEnumsAsStrings in Swagger config
> 
> ```
> services.AddControllersWithViews()
>                 .AddJsonOptions(options => 
>                 options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
> ```
> 
> And heres the generated schema: ![image](https://user-images.githubusercontent.com/17907743/74534862-1001a800-4f0b-11ea-9e88-a3a78b2c414b.png)

This works. But If I want to just provide converter for conrete type like:
```cs
public class ValidatePhoneNumberResponse
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public ValidatePhoneNumberFormatResult ValidationResult { get; set; }
}
```
Then the swagger docs still is generating number values:
![image](https://user-images.githubusercontent.com/2056282/171162952-0d7e1b1a-72e4-4fcc-9df2-dd434cb50cb4.png)

Luckily, I can configure `JsonStringEnumConverter` globally for my project, but still it seams like a bug that it doesn't recognize configuring types by  `JsonConverterAttribute`

**Comment by flydyk** [comment]
> A solution without fiddling around with JsonStringConverters can be found [here](https://github.com/RicoSuter/NSwag/issues/1234#issuecomment-821805424).
> 
> > A version of the XEnumNamesSchemaFilter for the latest version Swashbuckle:
> > ...
> 
> Explanation why this is needed [here](https://github.com/RicoSuter/NSwag/issues/1234#issuecomment-470519135).

@rm-code Unfortunately doesn't work for me in 6.5.0 version.
Schema filter is doing the thing if I debug it, but the result is still numbers in swagger UI.

**Comment by polferov** [comment]
I had the same issue, so i made nuget package [GitGub](https://github.com/polferov/Polferov.SwaggerEnumsAsStrings) / [NuGet](https://www.nuget.org/packages/Polferov.SwaggerEnumsAsStrings/)

**Comment by vanderlei-dev** [comment]
> > A solution without fiddling around with JsonStringConverters can be found [here](https://github.com/RicoSuter/NSwag/issues/1234#issuecomment-821805424).
> > > A version of the XEnumNamesSchemaFilter for the latest version Swashbuckle:
> > > ...
> > 
> > 
> > Explanation why this is needed [here](https://github.com/RicoSuter/NSwag/issues/1234#issuecomment-470519135).
> 
> @rm-code Unfortunately doesn't work for me in 6.5.0 version. Schema filter is doing the thing if I debug it, but the result is still numbers in swagger UI.

For Swagger 6.5 @rm-code solution needs to be modified a little bit by still works:

In the schema set `Enum`, `Type` and `Format` properties:

```
    public class XEnumNamesSchemaFilter : ISchemaFilter
    {
        private const string Name = "x-enumNames";

        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            var typeInfo = context.Type;
            
            if (typeInfo.IsEnum && !schema.Extensions.ContainsKey(Name))
            {
                var names = Enum.GetNames(context.Type);
                var arr = new OpenApiArray();
                arr.AddRange(names.Select(name => new OpenApiString(name)));
                                
                schema.Enum = arr;
                schema.Type = "string";
                schema.Format = "string";
            }
        }
    }
``` 

For using it there is no change:

```
      services.AddSwaggerGen(c =>
      {
          //...
          c.SchemaFilter<XEnumNamesSchemaFilter>();
          //...
      });
```

**Comment by JhaFrankSzot** [comment]
How do I get newlines into swagger description files

**Comment by rm-code** [comment]
In Net 10 it looks like Swashbuckle picks up the JsonSerializerOptions. This generates a proper enum schema with string values out of the box:

```csharp
builder.Services
  .AddControllers()
  .AddJsonOptions(options =>
  {
    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
  });
```


If you want to continue using the `ISchemaFilter` approach in Net 10, you will have to modify the code slightly:

```csharp
public class EnumStringFilter : ISchemaFilter
{
  public void Apply(IOpenApiSchema schema, SchemaFilterContext context)
  {
    if (schema is not OpenApiSchema apiSchema)
    {
      return;
    }

    Type typeInfo = context.Type;
    if (!typeInfo.IsEnum)
    {
      return;
    }

    apiSchema.Type = JsonSchemaType.String;
    apiSchema.Format = null;

    string[] names = Enum.GetNames(context.Type);
    apiSchema.Enum = names.Select(name => JsonValue.Create(name)).ToList<JsonNode>();
  }
}
```

**Comment by subedi-prashant** [comment]
To make selective enums passed as strings, simply

```
using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum MyEnum
{
    Enum1, 
    Enum2
}
```
