### ISSUE TITLE
How to get model XML Comment Remarks to show?

### ISSUE THREAD

**Issue by CreepyGnome** [domaindrivendev/Swashbuckle.AspNetCore#1270]
I have some detailed <remarks> documentation in my models XML Comment. However, they never show in the generated UI. 

Remarks are supported for the Controllers but they don't seem to be working for the models which are also shown and documented via the same UI the controllers are. Seems odd that remarks would be supported on one and not the other, so I assume I have to enable it or something but cannot find anything about it.

Please advise if possible and how, and if not can we make this into a feature request to show remarks in the model "schema" views?

**Comment by domaindrivendev** [comment]
This is because the underpinning open source technologies - [the Swagger/OpenAPI spec.](https://swagger.io/specification), and the [swagger-ui](https://github.com/swagger-api/swagger-ui), support 2 separate descriptive fields at the `Operation` level _but only_ 1 descriptive field at the `Schema` level.

So, rather than posting your issue here, I think it would be more appropriate to post to one of those projects.

**Comment by domaindrivendev** [comment]
If the Swagger/OpenAPi spec was updated to include a second field at the `Schema` level, for a more detailed description, then I would be happy to map model `remarks` onto that field.

**Comment by CreepyGnome** [comment]
I disagree because couldn't Swashbuckle just put both levels of docs from XML Comments into the single level for the schema? Seems like a sensible workaround.  That is one of the benefits of having things layered around other things, is it allows for things like this. You shouldn't have to be dependent on your dependencies if you can find a way around their lacking of specific functionality.

@domaindrivendev, this is your prerogative to just close this without a conversation about how Swashbuckle can workaround and solve this issue for its users. However, I would argue that Swashbuckle is more agile in making changes that Swagger and the OpenAPI spec and should not be dismissed just because the SPEC doesn't have a special field for the extra data when it does at least have a field it could fit in.

It could be opt-in during startup configuration so only those who want this get it.

**Comment by esbenbach** [comment]
I agree with @CreepyGnome it would be nice to have the options to merge the two sources of documentation into that single field.

**Comment by WebSerGe** [comment]
It is a pity, that it was closed. Indeed, topic starter is right about merging summary and remarks into one fields.

**Comment by magnusbakken** [comment]
In case anybody is interested, I use the following custom schema filter to add remarks to OpenAPI descriptions: https://gist.github.com/magnusbakken/d3329b65ac5d9493bf112d6b8a88705b

I would also prefer it if this was an option in the library.
