### ISSUE TITLE
How to display parameter descriptions of nested custom types？

### ISSUE THREAD

**Issue by 93910676wangd** [domaindrivendev/Swashbuckle.AspNetCore#1272]
Hello, I now use swashbuckle to generate API documents

Now the API's interface is a custom type, and the property type of the custom type is also a custom type.

In the generated document, the description of the custom property（memoFlg） type is not expressed. How can I solve this problem? Thank you

-------------------------------------------------------------------------------
Example: API(controller->action)
[Route("[controller]/[action]")]
    [ApiController]
    public class TestController
    {
        /// <summary>
        /// ***summary
        /// </summary>
        /// <param name="dto">***dto</param>
        /// <returns>***info</returns>
        [HttpPost]
        public ActionResult<Test_Dto> GetData([FromBody]Test_Dto dto)
        {
        }
   }

  public class Test_Dto
    {
        /// <summary>
        /// input mode
        /// </summary>
        public int InputMode { get; set; }
        /// <summary>
        /// memoflg
        /// </summary>
        public CheckBox memoFlg{ get; set; }
}

    public class CheckBox
    {
        /// <summary>
        /// set value
        /// </summary>
        public bool Checked { get; set; }
    }
-----------------swagger.json-------------------------

      "Test_Dto ": {
        "type": "object",
        "properties": {
          "inputMode": {
            "type": "integer",
            "description": "input mode",
            "format": "int32"
          },
          "memoFlg": {
            "$ref": "#/components/schemas/CheckBox"
          },
------------------------------------------------------------

Question：Why memoFlg doesn't have description ???????????

**Comment by 93910676wangd** [comment]
How to set up the following content? Thanks.

-----------------swagger.json-------------------------

  "Test_Dto ": {
    "type": "object",
    "properties": {
      "inputMode": {
        "type": "integer",
        "description": "input mode",
        "format": "int32"
      },
      "memoFlg": {
        allOf:
        - $ref:"#/components/schemas/CheckBox"
        description: :'this is a test'
      },

**Comment by domaindrivendev** [comment]
In your `Startup.cs`, apply the following config setting:

services.AddSwaggerGen(c =>
{
    ...

    c.UseAllOfToExtendReferenceSchemas();
});
