### ISSUE TITLE
Can't build with RC3 in VS2019 / .Net Core 3.0

### ISSUE THREAD

**Issue by SledgeHammer01** [domaindrivendev/Swashbuckle.AspNetCore#1274]
When I try to build my project in VS2019 with .Net Core 3.0 and Swagger 5.0 RC3, I get the following build error. RC2 builds fine.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet "C:\Users\xxx\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\/../tools/dotnet-getdocument.dll" --assembly "C:\Users\xxx\Documents\Visual Studio 2019\Projects\MyProject\bin\Debug\netcoreapp3.0\MyProject.dll" --file-list "obj\MyProject.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v3.0" --output "obj" --project "MyProject" --assets-file "C:\Users\xxx\Documents\Visual Studio 2019\Projects\MyProject\obj\project.assets.json" --platform "AnyCPU" " exited with code 7.	MyProject	C:\Users\xxx\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\Microsoft.Extensions.ApiDescription.Server.targets	41

**Comment by JoJo2406** [comment]
I had a similar issue with net core 2.2 - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1266

try setting the following property in the csproj

```xml
<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
```

**Comment by KarlJorgen** [comment]
I have the same issue after upgrade to RC3 and .Net Core 3.0.
RC2 builds fine

**Comment by domaindrivendev** [comment]
Tracking in #1266

**Comment by SledgeHammer01** [comment]
Jojo's solution worked for me.
