### ISSUE TITLE
Cannot Access Key Vault

### ISSUE THREAD

**Issue by ghost** [domaindrivendev/Swashbuckle.AspNetCore#1276]
I have the same issue mentioned below by another user.
Api documentation generation runs fine locally through Visual Studio. Running the dotnet build command in a terminal window or during an Azure Dev Ops build pipeline results in an error with it trying to access Azure Key Vault.

Do we need to do an Azure Sign-In on a step before the dotnet build command runs for the project?

I used an Key Vault Task in the build step previous to the dotnet build command and it successfully can retrieve the keys so I know I have the key vault permissions correct.

Error from the build pipeline:
dotnet "C:\Users\VssAdministrator\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\/../tools/dotnet-getdocument.dll" --assembly "D:\a\1\s\src\WebApi\Pm9.WebApi.OnTrackServices\bin\Release\netcoreapp2.2\Pm9.WebApi.OnTrackServices.dll" --file-list "obj\Pm9.WebApi.OnTrackServices.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v2.2" --output "obj" --project "Pm9.WebApi.OnTrackServices" --assets-file "D:\a\1\s\src\WebApi\Pm9.WebApi.OnTrackServices\obj\project.assets.json" --platform "AnyCPU" 
  System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/***. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
  Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/***. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. MSI ResponseCode: BadRequest, Response: {"error":"invalid_request","error_description":"Identity not found"}
  Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/***. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Visual Studio Token provider file not found at "C:\Users\VssAdministrator\AppData\Local\.IdentityService\AzureServiceAuth\tokenprovider.json"
  Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/***. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. Process took too long to return the token.

Original Comment Found:

For me, I have a piece of code related to the production environment.

```csharp
.ConfigureAppConfiguration((hostingContext, configBuilder) => {
    if (hostingContext.HostingEnvironment.IsProduction()) {
        var config = configBuilder.Build();
        configBuilder.AddAzureKeyVault(
            $"https://{config["AzureKeyVault:Name"]}.vault.azure.net/",
            new PrefixKeyVaultSecretManager("API"));
    }
})
```

It was executed by `Microsoft.Extensions.ApiDescription.Tool` of course it will results an error, those are runtime variables I don't have during the build.

_Originally posted by @zhangpengchen in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1226#issuecomment-534154059_

**Comment by emilssonn** [comment]
I have the same issue. We use config from key vault even when developing (https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.0#use-managed-identities-for-azure-resources). 

It seems that on each build microsoft.extensions.apidescription.server tries to start the project? Upgrading microsoft.extensions.apidescription.server to 3.0 does not help.
If I remove the key vault configuration provider the project can be built.

**Comment by emilssonn** [comment]
https://github.com/aspnet/AspNetCore/issues/14410 seems to be related.

**Comment by emilssonn** [comment]
Setting <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments> seems to be a workaround. Looks like the problem (or working as intended) is in Microsoft.Extensions.ApiDescription.Server.

Ref: https://github.com/aspnet/AspNetCore/issues/14232

**Comment by kamir008** [comment]
@emilssonn Can you please elaborate where we need to specify the condition <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments> for the workaround to work. I am also facing the same issue.

**Comment by emilssonn** [comment]
@kamir008 I dont know if I had the exact same problem. But to prevent Microsoft.Extensions.ApiDescription.Server from trying to generate open api json on build you set `<OpenApiGenerateDocuments>false</OpenApiGenerateDoc>` in the project file inside the main `<PropertyGroup>`. Updating to the latest rc of swashbuckle might also solve the problem.

**Comment by JakeWierzba** [comment]
> @kamir008 I dont know if I had the exact same problem. But to prevent Microsoft.Extensions.ApiDescription.Server from trying to generate open api json on build you set `<OpenApiGenerateDocuments>false</OpenApiGenerateDoc>` in the project file inside the main `<PropertyGroup>`. Updating to the latest rc of swashbuckle might also solve the problem.

I added that flag to the project file and it allows the build to succeed online and the Swagger Docs still show up.

I'm guessing this would only affect your project if you built something that depended on the Open API Docs.
