### ISSUE TITLE
5.0 RC3 / .Net Core 3.0.100 not passing in authorization header

### ISSUE THREAD

**Issue by SledgeHammer01** [domaindrivendev/Swashbuckle.AspNetCore#1277]
.Net Core 3.0.100
 Swagger 5.0 RC3
•Method in controller has [Authorize] header
•Using documented OAuth2SecurityFilter class
•Lock icon is shown on UI
•UI prompts for Oauth Header

Curl request generated is missing Oauth header. Note -H has no value (worked in 4.0):

curl -X GET "http://localhost:52580/sample/testMethod?APNSampleRequestValue=Sample%20APN%20Request%20Value&SampleComplexRequest.SampleTestBValue=123&SampleComplexRequest.SampleTestAValue=1" -H "accept: application/json"

OAuth2SecurityFilter looks like this... Am I missing something? I don't want the UI to prompt for the client id & secret and call the token, I just want it to pass in the value in the text box as it did in 4.0 and earlier:

			operation.Parameters.Add(new OpenApiParameter()
			{
				Name = "Authorization",
				In = ParameterLocation.Header,
				Description = Properties.Resources.SecurityDescription,
				Required = true,
				Schema = new OpenApiSchema() { Type = "string" }
			});

			operation.Security.Add(new OpenApiSecurityRequirement()
			{
				{
					new OpenApiSecurityScheme()
					{
						Type = SecuritySchemeType.OAuth2,
						In = ParameterLocation.Header,
						Scheme = "Bearer",
						Flows = new OpenApiOAuthFlows()
						{
							ClientCredentials = new OpenApiOAuthFlow()
							{
								Scopes = new Dictionary<string, string>
								{
									{ "readAccess", "Access read operations" },
									{ "writeAccess", "Access write operations" }
								},
								TokenUrl = new Uri("/token", UriKind.Relative)
							}
						}
					},
					new List<string>()
				}
			});
		}

**Comment by domaindrivendev** [comment]
Have you followed these exact steps:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements.

The example from this repo (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/test/WebSites/OAuth2Integration) appears to work just fine.

**Comment by SledgeHammer01** [comment]
Hi,

Yes, I have:

1) In Startup.cs, I added:

				options.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
				{
					Type = SecuritySchemeType.OAuth2,
					Flows = new OpenApiOAuthFlows
					{
						Implicit = new OpenApiOAuthFlow
						{
							AuthorizationUrl = new Uri("/auth-server/connect/authorize", UriKind.Relative),
							Scopes = new Dictionary<string, string>
				{
					{ "readAccess", "Access read operations" },
					{ "writeAccess", "Access write operations" }
				}
						}
					}
				});

2) I created an IOperationFilter with:

				var requiredScopes = context.MethodInfo
							.GetCustomAttributes(true)
							.OfType<AuthorizeAttribute>()
							.Select(attr => attr.Policy)
							.Distinct();

				if (requiredScopes.Any())
				{
					//operation.Responses.Add("401", new OpenApiResponse { Description = "Unauthorized" });
					//operation.Responses.Add("403", new OpenApiResponse { Description = "Forbidden" });


					var oAuthScheme = new OpenApiSecurityScheme
					{
						Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "oauth2" }
					};

					operation.Security = new List<OpenApiSecurityRequirement>
				{
					new OpenApiSecurityRequirement
					{
						[ oAuthScheme ] = requiredScopes.ToList()
					}
				};
				}

I just commented out the response codes because I already have them added in the controller with the Produces attribute.

With this setup, I get the Authorize button at the top (which I don't want because it doesn't really work right -- I realize that's the swagger-ui project), and I get the lock on the appropriate method as desired. I don't get the OAuth Text Box in the method because I removed the OpenApiParameter add call per the docs.

I'm not using implicit flow, I'm trying to use client_credentials flow. My token endpoint is a controller in the same server. It was working in 4.0 and I added the parameter as:

				//operation.Parameters.Add(new OpenApiParameter()
				//{
				//	Name = "Authorization",
				//	In = ParameterLocation.Header,
				//	Description = Properties.Resources.SecurityDescription,
				//	Required = true,
				//	Style = ParameterStyle.Simple,
				//	Schema = new OpenApiSchema()
				//	{
				//		Type = "string"
				//	}
				//});

And it would pass in a -H on the curl line.

I tried downloading the code and building and running that test project (in Chrome), but all I got was a blank page??

Thanks for the help.

**Comment by SledgeHammer01** [comment]
If you ignore the Oauth aspect of this issue... if I just have:

public async Task<IActionResult> TestMethodAsync([FromQuery]SampleRequest request, [FromHeader(Name = "Authorization")]string str)
{
}

That doesn't pass in the header value on the curl string either. It does show the text box for it in the UI though... is that on your end of swagger-ui?

**Comment by domaindrivendev** [comment]
Firstly, this is a [swagger-ui](https://github.com/swagger-api/swagger-ui) issue and not a Swashbuckle issue.

Secondly, it appears to be by design on their side:

> The Authorization header parameter defined in /auth/credentials and /system/info won't be used because OpenAPI Specification says that tools should ignore explicit header parameters named Authorization. The Authorization header should be defined as a security scheme instead

See https://github.com/swagger-api/swagger-ui/issues/5643

**Comment by billkiddo** [comment]
From [https://github.com/swagger-api/swagger-ui/issues/5643](url)

> You need to change your Swashbuckle configuration so that it includes proper securitySchemes and security definitions in the generated JSON file. Please check Swashbuckle documentation or open a ticket with them for support.
