### ISSUE TITLE
Feature Request: Allow serializing just the value

### ISSUE THREAD

**Issue by Vaccano** [domaindrivendev/Swashbuckle.AspNetCore#1279]
I am using 5.0.0-rc3.

I am trying to get Breeze to work with Swashbuckle.  I added an IOperationFilter to add the parameter.  But it gets added in the standard format of `ParamName=ParamValue`.

Breeze adds an extra, unnamed parameter to all its calls (as the first parameter).  This parameter is a URL Encoded Json string.  

When I add this parameter to the list via an IOperationFilter the `ParamName=` part breaks it.  (I have been unable to find anyway to remove that prefix.)

**It would be a nice feature to allow just serializing the value into the parameter so I can use my breeze based service with Swashbuckle.**

So to be clear, here is an example of what I am requesting:

            var breezeJsonParam = new OpenApiParameter();
            breezeJsonParam.Name = "breezeJson";
            breezeJsonParam.In = ParameterLocation.Query;
            breezeJsonParam.Schema = new OpenApiSchema();
            breezeJsonParam.Schema.Type = "string";
            breezeJsonParam.Schema.Default = new OpenApiString("{}");

            // This is the part that would be the feature request
            breezeJsonParam.SerializeJustValue = true;

Then, in the SwaggerUI, if the user enters `{}` as the value, it would be passed to the application as `{}` instead of `breezeJson={}`.

**Comment by domaindrivendev** [comment]
Your query is related to the [Swagger/OpenAPI Spec](https://swagger.io/specification/) and not Swashbuckle. Currently, that spec requires all parameters to have a `name`. So what you're asking would mean non-adherence to the spec, and it would also require an update to the [swagger-ui tool](https://github.com/swagger-api/swagger-ui) (a seperately owned and maintained tool). So, it's not something we would take on within Swashbuckle.

With that said, you could possibly do this on the client-side with a custom "request interceptor":
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#use-client-side-request-and-response-interceptors
