### ISSUE TITLE
Add support for JsonPropertyNameAttribute from System.Text.Json

### ISSUE THREAD

**Issue by tcfialho** [domaindrivendev/Swashbuckle.AspNetCore#1280]
With the new json serializer from Microsoft the [JsonPropertyName] attribute comes to replace the old [JsonProperty]. However, swagger is not taking the value from this new attribute.

**Comment by domaindrivendev** [comment]
Full support for `System.Text.Json` is next up on the backlog (once I get v3.0.0 released) and due to some recent refactorings should be relatively trivial. So, hopefully within the next month

**Comment by quotschmacher** [comment]
hi there - i just came across this and i'm facing the same problem. i wanted to use the [JsonPropertyName] as swagger does not seem to be very case sensitive when dealing with parameters.

any progress here?

**Comment by mangoyoga80** [comment]
I'm also very interested in this feature

**Comment by domaindrivendev** [comment]
Changes are in master. Can preview by downloading latest preview from myget.org. Closing in on the official release
