### ISSUE TITLE
Dotnet command error

### ISSUE THREAD

**Issue by aibarralandeo** [domaindrivendev/Swashbuckle.AspNetCore#1282]
I installed Swashbuckle.AspNetCore version rc3 and receiving this error at launch.  

The command "dotnet "C:\Users\xxxx\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\/../tools/dotnet-getdocument.dll" --assembly "D:\Projects\Test\Test.Hub.API\Test.Hub.Service\Test.Hub.Service.Swagger\bin\Debug\netcoreapp3.0\Test.Hub.Service.Swagger.dll" --file-list "obj\Test.Hub.Service.Swagger.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v3.0" --output "obj" --project "Test.Hub.Service.Swagger" --assets-file "D:\Files\Test\Test.Hub.API\Test.Hub.Service\Test.Hub.Service.Swagger\obj\project.assets.json" --platform "AnyCPU" " exited with code 3

And it's related to Microsoft.Extensions.ApiDescription.Server.targets file, which is part of a Nuget Package you're referencing to in version 0.3.0-preview7.19365.7

The error fires at `CreateHostBuilder(args).Build().Run();` of Main method.

Any idea what can be causing this?

**Comment by aibarralandeo** [comment]
I have to add something else. If I don't clean the solution and, instead, launch the project for the second time, it starts without problems. But if I stop the project and re run, the same error appears, the same solution is applicable.

**Comment by inpicksys** [comment]
@aibarralandeo 
 As in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1226
`<PropertyGroup>
  <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
</PropertyGroup>`
or
 `<PropertyGroup>
  <OpenApiGenerateDocumentsOnBuild>false</OpenApiGenerateDocumentsOnBuild>
</PropertyGroup>`
Help me to fix this issue.

**Comment by inpicksys** [comment]
Remaining issue is updating auth filter, as Swashbuckle changes a lot of instances and api.

**Comment by domaindrivendev** [comment]
Closing as it's a dup. Underlying issue is being tracked #1266
