### ISSUE TITLE
GRPC?

### ISSUE THREAD

**Issue by khteh** [domaindrivendev/Swashbuckle.AspNetCore#1285]
Not a bug but a question. Any plan to support GRPC since it is supported in .Net Core 3.0? There is one for Java: https://github.com/grpc-swagger/grpc-swagger

**Comment by BlowaXD** [comment]
Would be cool, I don't have time to dive into Swashbuckle/Swagger to generate the right things

**Comment by domaindrivendev** [comment]
No plans to add this out-of-the-box, but looks like there's already a MS recommended package to support this:
https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-5.0#enable-swaggeropenapi-support
