### ISSUE TITLE
CLI Not working per instructions.

### ISSUE THREAD

**Issue by nezoic** [domaindrivendev/Swashbuckle.AspNetCore#1288]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcorecli

I don't know if it's me but the CLI never works.
I can install it.
dotnet tool install swashbuckle.aspnetcore.cli --version 5.0.0-rc3

But running - help returns:

dotnet tool run swagger tofile --help
Usage: dotnet tool [options] [command]

Options:
  -h, --help   Show command line help.

Commands:
  install <PACKAGE_ID>     Install a tool for use on the command line.
  uninstall <PACKAGE_ID>   Uninstall a tool from the current development environment.
  update <PACKAGE_ID>      Update a tool to the latest stable version.
  list                     List tools installed in the current development environment.

Also get similar error running the "run" portion, never recognised the command.

**Comment by domaindrivendev** [comment]
Thanks for pointing this out … it seems the docs are incorrect. Once you've installed the tool, you should be able to invoke it as follows (NOTE: the omission of ` tool run `) :

```
dotnet swagger tofile --help
```

I updated the docs [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#retrieve-swagger-directly-from-a-startup-assembly)

**Comment by nezoic** [comment]
That returns something odd.
dotnet swagger tofile --help
dotnet : No executable found matching command "dotnet-swagger"

**Comment by domaindrivendev** [comment]
That doesn’t repro for me. Have you installed as a global Net tool?

**Comment by nezoic** [comment]
Yes, listing the installed packages shows 5.0.0-rc3 installed.
dotnet tool list -g
Package Id                      Version        Commands
-------------------------------------------------------
swashbuckle.aspnetcore.cli      5.0.0-rc3      swagger

**Comment by domaindrivendev** [comment]
Not sure - as I can’t repro there’s not much else I can do to help. You’ll have to dig deeper yourself

**Comment by nezoic** [comment]
Can I ask what version of dotnet you're using? I tried on 2.2.4 and 3.0.

**Comment by domaindrivendev** [comment]
```
C:\Users\Richie\src\NetCore3\NetCore3> dotnet --version
3.0.100

C:\Users\Richie\src\NetCore3\NetCore3> dotnet new tool-manifest
The template "Dotnet local tool manifest file" was created successfully.

C:\Users\Richie\src\NetCore3\NetCore3> dotnet tool install swashbuckle.aspnetcore.cli --version 5.0.0-rc3
You can invoke the tool from this directory using the following commands: 'dotnet tool run swagger' or 'dotnet swagger'.
Tool 'swashbuckle.aspnetcore.cli' (version '5.0.0-rc3') was successfully installed. Entry is added to the manifest file C:\Users\Richie\src\NetCore3\NetCore3\.config\dotnet-tools.json.

C:\Users\Richie\src\NetCore3\NetCore3> dotnet swagger tofile --help
Usage: dotnet swagger tofile [options] [startupassembly] [swaggerdoc]

startupassembly:
  relative path to the application's startup assembly

swaggerdoc:
  name of the swagger doc you want to retrieve, as configured in your startup class

options:
  --output:  relative path where the Swagger will be output, defaults to stdout
  --host:  a specific host to include in the Swagger output
  --basepath:  a specific basePath to inlcude in the Swagger output
  --serializeasv2:  output Swagger in the V2 format rather than V3

C:\Users\Richie\src\NetCore3\NetCore3> dotnet swagger tofile .\bin\Debug\netcoreapp3.0\NetCore3.dll v1
{
  "openapi": "3.0.1",
  "info": {
    "title": "Test API",
    "version": "v1"
  },
  …
```

**Comment by navi-dev** [comment]
I have followed the same but still I am not seeing the output instead an error any idea?
![image](https://user-images.githubusercontent.com/31265301/68855804-0ba7d200-0705-11ea-8360-040f6a43d996.png)

**Comment by navi-dev** [comment]
Okay, so let me tell explain what is happening here. The above error I got because I was using .NET core 2.2 and downgrading to 2.1 worked for me. 

And the one @nezoic raised it is indeed the issue, installing the tool not setting up the path of swagger so you need to do it explicitly though it claims it adding but its not and instead of dotnet-swagger use swagger.

Hope it helps.

**Comment by domaindrivendev** [comment]
Closing in favor of #1699, which captures all of the outstanding compatibility issues. That issue is being addressed as a top priority
