### ISSUE TITLE
Response model is always produced for 4XX response codes

### ISSUE THREAD

**Issue by aussieviking** [domaindrivendev/Swashbuckle.AspNetCore#1292]
**Problem**: Response type model defaults to `ProblemDetails` when response code is in the 4xx range and no response type has been defined.

The `SwaggerResponse` attribute produces an example model even though no type has been specified.

### Example controller method declaration:
```
[HttpPost]
[Route("foobar")]
[SwaggerResponse(200, "foo")]
[SwaggerResponse(400, "bar")]
[SwaggerResponse(500, "foobar")]
public IActionResult Foobar() { return Ok(); }
```

### Expected result:
A swagger document with no response type for either response:
```
"responses": {
    "200": {
        "description": "foo"
    },
    "400": {
        "description": "bar"
    },
    "500": {
        "description": "foobar"
    }
}
```

### Actual result:
A swagger document, where the 400 response references a `ProblemDetails` object:
```
"responses": {
    "200": {
        "description": "foo"
    },
    "400": {
        "description": "bar",
        "schema": {
            "$ref": "#/definitions/ProblemDetails"
        }
    },
    "500": {
        "description": "foobar"
    }
}
```

I have noticed that I can get around this issue by including the following attribute declaration but I would prefer not to have to do that:

`[ProducesErrorResponseType(typeof(void))]`

**Comment by domaindrivendev** [comment]
Which version of Swashbuckle are you using? I can't repro the issue with the latest version - `5.0.0-rc4`

**Comment by wizofaus** [comment]
`ProducesErrorResponseType` doesn't work for me at all with 4.0.1 - is this expected? (can log separately if needed)

**Comment by domaindrivendev** [comment]
@wizofaus please create a separate issue for `ProducesErrorResponseType` not working.

**Comment by domaindrivendev** [comment]
@aussieviking - because the `SwaggerResponse` attribute _extends_ the `ProducesResponseType` attribute, I believe your issue is actually a dup of #1043. Which, is actually due to an upstream issue with ASPNET Core. Closing this one, so we can track in 1 place
