### ISSUE TITLE
[5.0.0-rc4] [.NET CORE 3.0] Swagger does not add Authorization header to request

### ISSUE THREAD

**Issue by harper555** [domaindrivendev/Swashbuckle.AspNetCore#1295]
Hello,

I made a new Web API. I got Swagger and IdentityServer4.AccessTokenValidation set up and running, but Swagger does not seem to add an Authorization header to my request.

Startup.cs -> ConfigureServices method

````
public void ConfigureServices(IServiceCollection services)
		{
			services.AddControllers(c => {
				var policy = ScopePolicy.Create("openid", "api");
				c.Filters.Add(new AuthorizeFilter(policy));
			});

			services
				.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
				.AddIdentityServerAuthentication(options => {
					options.Authority = Configuration["Identity:Identity"];
					options.ApiName = Configuration["Identity:IdentityScope"];
					options.ApiSecret = Configuration["Identity:IdentityScopeSecret"];
					options.SupportedTokens = SupportedTokens.Both;
					options.LegacyAudienceValidation = true;
				});

			services.AddSwaggerGen(c => {
				c.SwaggerDoc("v1", new OpenApiInfo { Title = "Printer API", Version = "v1" });
				c.OperationFilter<SwaggerAuthorizationOperationFilter>();
			});

			RegisterDbContexts(services);
			RegisterServices(services);
		}
````

Startup.cs -> Configure method

````
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
		{
			if (env.IsDevelopment()) {
				app.UseDeveloperExceptionPage();
			}

			app.UseHttpsRedirection();
			app.UseRouting();
			app.UseAuthentication();
			app.UseAuthorization();
			
			var swaggerEndpoint = "/swagger/v1/swagger.json";
			if (Environment.IsStaging()) {
				swaggerEndpoint = "/int/printerapi/swagger/v1/swagger.json";
			}
			if (Environment.IsProduction()) {
				swaggerEndpoint = "/int/printerapi/swagger/v1/swagger.json";
			}

			app.UseSwagger();
			app.UseSwaggerUI(c => {
				c.DocumentTitle = "Printer API";
				c.SwaggerEndpoint(swaggerEndpoint, "Printer API V1");
				c.RoutePrefix = string.Empty;
			});

			app.UseEndpoints(endpoints => {
				endpoints.MapControllers();
			});
		}
````

SwaggerAuthorizationOperationFilter.cs

````
public class SwaggerAuthorizationOperationFilter : IOperationFilter
	{
		public void Apply(OpenApiOperation operation, OperationFilterContext context)
		{
			var filterDescriptors = context.ApiDescription.ActionDescriptor.FilterDescriptors;
			var isAuthorized = filterDescriptors.Select(filterInfo => filterInfo.Filter).Any(filter => filter is AuthorizeFilter);
			var allowAnonymous = filterDescriptors.Select(filterInfo => filterInfo.Filter).Any(filter => filter is IAllowAnonymousFilter);

			if (isAuthorized && !allowAnonymous) {
				if (operation.Parameters == null) {
					operation.Parameters = new List<OpenApiParameter>();
				}

				operation.Parameters.Add(new OpenApiParameter {
					Name = "Authorization",
					In = ParameterLocation.Header,
					Description = "access token",
					Required = true,
					Schema = new OpenApiSchema {
						Type = "string",
						Default = new OpenApiString("Bearer {access token}"),
					}
				});
			}
		}
	}
````

I attached a screenshot of Swagger after I press Execute.

What am I doing wrong?

![swagger](https://user-images.githubusercontent.com/5992169/66203243-80243580-e6b0-11e9-91a7-6f6b28f80f69.png)

Thank you.

**Comment by domaindrivendev** [comment]
As per the [readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements), you need to a) define the security scheme in use (i.e. via `AddSwaggerGen(c => c.AddSecurityDefinition(...` *AND* b) specify which operations the scheme applies to (i.e. via `AddSwaggerGen(c => c.AddSecurityRequirement(…` for _all_ operations or with an operation filter for _per-operation_ requirements). From you configuration, it looks like you've done the latter but not the former.

**Comment by domaindrivendev** [comment]
Dup of #1277

**Comment by domaindrivendev** [comment]
A REMINDER for anyone following this issue or the referenced duplicate …

This is _NOT_ an issue with Swashbuckle! It's a limitation (seemingly by design) of the [swagger-ui](https://github.com/swagger-api/swagger-ui/issues/5643):

> The Authorization header parameter defined in /auth/credentials and /system/info won't be used because OpenAPI Specification says that tools should ignore explicit header parameters named Authorization. The Authorization header should be defined as a security scheme instead.

**Comment by shockey** [comment]
@domaindrivendev, Swagger UI is simply following the explicit instructions of OpenAPI 3.0:

> **If in is "header" and the name field is** "Accept", "Content-Type" or **"Authorization"**, the parameter definition SHALL be ignored.
> 
> [ref](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-10)

Authorization header parameters are quite simply illegal in OpenAPI 3.0, so no tool should be supporting or generating them.

**Comment by abhishekguptalm** [comment]
In HTTP Context string requestUrl = string access_token = httpContext.Request?.Headers["Authorization"].ToString(); any other solution ? to get authorization field

**Comment by DalSoft** [comment]
Simple solution for people who just have a bearer token and not a full oauth2 flow.

Change your OperationFilter so that the OpenApiParameter Header name you are adding is "X-Authorization" instead of  "Authorization". 

Then add this to your Startup.cs:

```cs
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ApplicationDbContext context, TBSCDbContext tbscContext)
{                
   app.Use((httpContext, next) => // For the oauth2-less!
   {
      if (httpContext.Request.Headers["X-Authorization"].Any())
      httpContext.Request.Headers.Add("Authorization", httpContext.Request.Headers["X-Authorization"]);

      return next();
   });
//..
}
```

**Comment by farshid3003** [comment]
I Integrate swagger with firebase and automatically password flow authentication 

https://stackoverflow.com/questions/61540706/configure-swagger-authentication-with-firebase-google-in-net-core/61540707#61540707
