### ISSUE TITLE
[suggest] Controller summary not shown

### ISSUE THREAD

**Issue by fawdlstty** [domaindrivendev/Swashbuckle.AspNetCore#1299]
version: 5.0.0-rc4
![image](https://user-images.githubusercontent.com/7323999/66311347-d4dddf80-e940-11e9-9080-86aacfaf01b1.png)
The effect of this code is as follows:
![image](https://user-images.githubusercontent.com/7323999/66311746-cc39d900-e941-11e9-9940-d8cb92464ca5.png)
However, the controller module summary is not shown. It is recommended to write the controller module summary to the end of the module, looks like:
![image](https://user-images.githubusercontent.com/7323999/66311902-276bcb80-e942-11e9-8f91-ddacd68b8c01.png)

**Comment by domaindrivendev** [comment]
Dup of #1293

**Comment by domaindrivendev** [comment]
TL/DR: Use the overload of `IncludeXmlComments` that accepts an `includeControllerXmlComments` flag.

**Comment by changhuixu** [comment]
Thanks @domaindrivendev. Finally find the solution.

**Comment by lonix1** [comment]
@domaindrivendev Thanks for `includeControllerXmlComments`! Perhaps should be added to the docs as it was very hard to discover. Thanks!
