### ISSUE TITLE
scopeSeperator misspelled

### ISSUE THREAD

**Issue by wizofaus** [domaindrivendev/Swashbuckle.AspNetCore#1302]
scopeSeperator -> scopeSeparator

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/b1ea8afa315cc6d25460884d5b63f8b051903ffe/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIOptions.cs

**Comment by domaindrivendev** [comment]
Good catch - in addition to being misspelt, this was actually making the setting ineffective because the swagger-ui expects the correct spelling `scopeSeparator`.

Fixed by c2f241cc4c34ee21b97aae28f3867aa263093f70
