### ISSUE TITLE
operation.Consumes.Add("multipart/form-data") and NonParameter？

### ISSUE THREAD

**Issue by ghd258** [domaindrivendev/Swashbuckle.AspNetCore#1305]
public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            if (!context.ApiDescription.HttpMethod.Equals("POST", StringComparison.OrdinalIgnoreCase) &&
                !context.ApiDescription.HttpMethod.Equals("PUT", StringComparison.OrdinalIgnoreCase))
            {
                return;
            }
            var fileParameters = context.ApiDescription.ActionDescriptor.Parameters.Where(n => n.ParameterType == typeof(IFormFile)).ToList();
            if(fileParameters.Count==0)
            {
                return;
            }
            operation.Consumes.Add("multipart/form-data");
            foreach (ParameterDescriptor fileParameter in fileParameters)
            {
                var parameter = operation.Parameters.Single(n => n.Name == fileParameter.Name);
                operation.Parameters.Remove(parameter);
                operation.Parameters.Add(new NonBodyParameter
                {
                    Name = parameter.Name,
                    In = "formData",
                    Description = parameter.Description,
                    Required = parameter.Required,
                    Type = "file"
                });
            }
        }

  public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            foreach (var parameter in operation.Parameters.OfType<NonParameter>())
            {
                var description = context.ApiDescription.ParameterDescriptions.FirstOrDefault(p => p.Name == parameter.Name);
                if (description == null)
                    return;
                if (parameter.Description == null)
                {
                    parameter.Description = description.ModelMetadata?.Description;
                }
                if (description.RouteInfo != null)
                {
                    parameter.Required |= !description.RouteInfo.IsOptional;
                    if (parameter.Default == null)
                        parameter.Default = description.RouteInfo.DefaultValue;
                }
            }
        }

**Comment by domaindrivendev** [comment]
I've no idea what your asking here and don't have the time to try infer it from a big snippet of code. If you're still having an issue, please resubmit with more context - concise repro steps, expected behavior, actual behavior. Something along the [following lines](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1329) would be 👌
