### ISSUE TITLE
xml comment documentation "returns" is ignored

### ISSUE THREAD

**Issue by wizofaus** [domaindrivendev/Swashbuckle.AspNetCore#1311]
/// <summary>Quote of the day</summary>
        /// <returns>A random inspiring quote</returns>
        [HttpGet]
        [Route("qotd")]
        [ProducesResponseType(typeof(string), 200)]
        public async Task<IActionResult> QuoteOfTheDay()

The "random inspiring quote" information logically applies to the primitive "string" response returned, but doesn't appear to be part of the swagger output at all:

     "/qotd":{"get":{"tags":["Quote"],"summary":"Quote of the day","operationId":"QuoteOfTheDay","consumes":[],"produces":["application/json"]

The swagger-ui then shows no useful information on what the response is.

UPDATE: I tried changing it to `<response code="200">`, and it worked as expected.  Only figured this from inspecting the code though.

**Comment by domaindrivendev** [comment]
It's documented here - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments
