### ISSUE TITLE
5.0.0-rc2 IDocumentFilter.Apply() context.SchemaGenerator.GenerateSchema() generates empty schema

### ISSUE THREAD

**Issue by remcolam** [domaindrivendev/Swashbuckle.AspNetCore#1312]
I'm trying to add a model to the schemas, using the IDocumentFilter... I had this working in 4, but in 5 the GetOrRegister method doesn't exist, looking at the fields in the conext, I assumed I needed to generate the schema myself, using the generator.

Unfortunately, it is generating an empty schema, am I doing something wrong? Is it a bug? 

IDocumentFilter implementation
```    internal class KnownSubtypesDocumentFilter : global::Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter
    {
        public void Apply(Microsoft.OpenApi.Models.OpenApiDocument swaggerDoc, global::Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext context)
        {
            var schema = context.SchemaGenerator.GenerateSchema(typeof(CoreAPIAccess.Models.Token.NewToken), context.SchemaRepository);
            context.SchemaRepository.Schemas[nameof(CoreAPIAccess.Models.Token.NewToken)] = schema;
        }
    }
```
The relevant model:
```    /// <summary>
    /// Used to request a new token
    /// </summary>
    public class NewToken
    {
        /// <summary>
        /// Datetime at which the request was sent
        /// </summary>
        public DateTime RequestDatetimeUtc { get; set; }
        /// <summary>
        /// The machine name sending the request
        /// </summary>
        public string MachineName { get; set; }
    }
```

Resulting swaggerUI:
![image](https://user-images.githubusercontent.com/11367055/66640387-317b1c00-ec19-11e9-9f65-4c969dcde045.png)

PS Using rc2, because rc4 causes an exception:
```
System.InvalidOperationException: Can't use schemaId "$Attribute" for type "$Sometype+Attribute". The same schemaId is already used for type "$Sometype.Attribute"
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.ReserveIdFor(Type type, String schemaId)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
```

**Comment by domaindrivendev** [comment]
If you implement your filter as follows you should be good:

```csharp
public void Apply(Microsoft.OpenApi.Models.OpenApiDocument swaggerDoc, global::Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext context)
{
    context.SchemaGenerator.GenerateSchema(typeof(CoreAPIAccess.Models.Token.NewToken), context.SchemaRepository);
}
```

The `SchemaGenerator` automatically adds referenced/shared schemas to the `SchemaRepository` that's passed into the `GenerateSchema`. The schemas in the `context.SchemaRepository` are ultimately added to the Swagger document. So, you don't need to add them manually

**Comment by remcolam** [comment]
That got the model in, which helps, but it's missing the descriptions from the xml comments (as can be seen below). Is there a way to get them combined? Or will this never work for models added this way? Maybe if I add swashbuckle documenting attributes?

```
      "NewToken": {
        "type": "object",
        "properties": {
          "requestDatetimeUtc": {
            "type": "string",
            "format": "date-time"
          },
          "machineName": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
```

**Comment by domaindrivendev** [comment]
I believe XML comments should work just fine with this approach. If I get a chance today, I'll see if I can repro with XML comments.

**Comment by domaindrivendev** [comment]
When I incorporate XML comments, they still get outputted with the above approach. So, still no repro on my side.

Might be worth creating a minimal repro project and pushing it to github. Without a repro there's nothing I can do.

**Comment by remcolam** [comment]
I'll verify first that the comments are actually in the xml. Something I should have done before actually.

Unfortunately, this project is a bit am the back burner at the moment, since our core 2.2 project can't seem to run properly on core 3. We getting all those warnings from Roslyn analyzers crashing, probably since not all packages are yet available in core 3. So we might wait until January, core 3.1 will be out for a few months then.

It's fine to close this, I'll check if I can make a smaller repro project and push that somewhere if I'm still having issues.
