### ISSUE TITLE
No operations defined in spec!---v5.0.0-rc4

### ISSUE THREAD

**Issue by ghd258** [domaindrivendev/Swashbuckle.AspNetCore#1315]
No operations defined in spec!

**Comment by tomkerkhove** [comment]
Works fine for me. How did you document your operations?

**Comment by ghd258** [comment]
net core 2.2  normal ； This problem occurred after upgrading to 3.0

  services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v2", new OpenApiInfo
                {
                    Version = "v1.1.0",
                    Title = "iot WebAPI",
                    Description = "后台框架",
                    //TermsOfService = "None",
                    Contact = new OpenApiContact { Name = "Blank", Email = "790048789@qq.com" }
                });


            });

 app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v2/swagger.json", "SimplCommerce API V1");
            });

**Comment by tomkerkhove** [comment]
Looks like you are not providing any XML docs to `IncludeXmlComments` in `AddSwaggerGen`. We always do that so that it knows what we have.

Not sure if this was not required before and if that changed, but if you add that it works for us.

**Comment by ghd258** [comment]
var basePath = Microsoft.DotNet.PlatformAbstractions.ApplicationEnvironment.ApplicationBasePath;
            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v2", new OpenApiInfo
                {
                    Version = "v1.1.0",
                    Title = "iot WebAPI",
                    Description = "后台框架",
                    //TermsOfService = "None",
                    Contact = new OpenApiContact { Name = "Blank", Email = "790048789@qq.com" }
                });

                var xmlPath = Path.Combine(basePath, "IOT.API.xml");
                options.IncludeXmlComments(xmlPath, true);
             
            });

The problem still exists.

**Comment by ghd258** [comment]
![QQ图片20191012172926](https://user-images.githubusercontent.com/4811375/66699036-e561d180-ed15-11e9-9fe8-d076d13eeeb5.png)
![QQ图片20191012172930](https://user-images.githubusercontent.com/4811375/66699039-e72b9500-ed15-11e9-9350-5c7031882800.png)

**Comment by tomkerkhove** [comment]
Is your controller documented?

**Comment by ghd258** [comment]
Is your controller documented?
![QQ图片20191012174708](https://user-images.githubusercontent.com/4811375/66699316-5efabf00-ed18-11e9-8b18-7d9d3ed6f54d.png)

**Comment by tomkerkhove** [comment]
With documentation I'm more referring to XML docs:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments

**Comment by 2693252993** [comment]
I had the same problem


this is my xml

`<?xml version="1.0"?>
<doc>
    <assembly>
        <name>BuTian.Web</name>
    </assembly>
    <members>
        <member name="T:BuTian.Web.Controllers.AccountController">
            <summary>
            user
            </summary>
        </member>
        <member name="M:BuTian.Web.Controllers.AccountController.Delete(System.Int64)">
            <summary>
            Deletes a specific TodoItem.
            </summary>
            <param name="id"></param>        
        </member>
    </members>
</doc>
`

**Comment by ghd258** [comment]
The reason for the error was found. It was caused by the namespace. The same class name in different namespaces would cause the error.

**Comment by ghd258** [comment]
NotSupportedException: HTTP method "POST" & path "v{version}/Qxt/MesProcessCategory/GetList" overloaded by actions - IOT.API.Areas.Qxt.Controllers.Mes.MesProcessCategoryController.GetList (IOT.API),IOT.API.Areas.Qxt.Controllers.Mes.MesProcessCategoryController.GetList (IOT.API). Actions require unique method/path combination for OpenAPI 3.0. Use ConflictingActionsResolver as a workaround


InvalidOperationException: Can't use schemaId "$sort" for type "$QueryModels.sort". The same schemaId is already used for type "$VOCs.FrameworkCore.Web.ServiceRestClient.sort"

**Comment by KEMBL** [comment]
Who has that problem after namespace(s) changes, check ApiExplorerGroupPerVersionConvention and fix namespaces is any

**Comment by TunarPro** [comment]
sasa

**Comment by AmitGee** [comment]
> The reason for the error was found. It was caused by the namespace. The same class name in different namespaces would cause the error.

This was it for me. I wish it were easier to identify & troubleshoot such issues. I had nothing in the log that would point me towards this.

**Comment by sep96** [comment]
Here's a step-by-step approach to troubleshoot:

Check your controller:
```

[ApiController]
[Route("api/[controller]")]
public class YourController : ControllerBase
{
    [HttpGet]
    public IActionResult Get()
    {
        // Implementation
    }
}
```
Verify your Startup.cs (or Program.cs for .NET 6+):

```
services.AddControllers();
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Your API", Version = "v1" });
});
```
Ensure you're calling the necessary methods in Configure:

```
app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Your API v1"));
```
If using .NET 6+ minimal APIs, make sure your endpoints are defined:
`
app.MapControllers();`
Check your project file (.csproj) to ensure XML documentation is generated:

```
<PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <NoWarn>$(NoWarn);1591</NoWarn>
</PropertyGroup>
```
