### ISSUE TITLE
Controller actions returning IAsyncEnumerable<T> are not documented correctly

### ISSUE THREAD

**Issue by MarcusWichelmann** [domaindrivendev/Swashbuckle.AspNetCore#1317]
When an API controller action returns `IAsyncEnumerable<SomeModel>` its result is not documented correctly in the resulting API spec.

For example, this code
```C#
public IAsyncEnumerable<SomeModel> GetSomethingAsync()
{
    return _someService.GetAllAsync();
}
```

results in this schema:
```JSON
...
      "SomeModelIAsyncEnumerable": {
        "type": "object",
        "additionalProperties": false
      },
...
```

As you can see, all information about the model are missing here. I'd expect that API actions that return `IAsyncEnumerable<T>` are documented the same way as when they are when they return `ICollection<T>`.

Version `5.0.0-rc4` with `ASP.Net Core 3.0`

**Comment by rcollette** [comment]
In case anyone finds this still happening, if you are switching from Newtonsoft to System.Text.Json and forget to remove `AddSwaggerGenNewtonsoftSupport()`, you will not get correct type documentation for the generic type specified in `IAsyncEnumerable<>`.
