### ISSUE TITLE
Describing enums as strings in 5.0.0-rc4 works only for Newtonsoft.Json

### ISSUE THREAD

**Issue by mrmartan** [domaindrivendev/Swashbuckle.AspNetCore#1320]
There was some attemtp at fixing enum name generation in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1061 but AFAICT it only works for Newtonsoft.Json and not for System.Text.Json.

Demonstration (the used JSON technology is the only difference, and what you see is the only change in code):
```csharp
services
    .AddMvc(options =>
    {
        options.EnableEndpointRouting = false;
    })
    .AddNewtonsoftJson(options => 
    {
        options.SerializerSettings.Converters.Add(new StringEnumConverter());
    })
```
![image](https://user-images.githubusercontent.com/2376580/66743801-042da880-ee7b-11e9-9ae1-78818fdd147d.png)

```csharp
services
    .AddMvc(options =>
    {
        options.EnableEndpointRouting = false;
    })
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
    })
```
![image](https://user-images.githubusercontent.com/2376580/66743830-19a2d280-ee7b-11e9-8afc-aeacf88e3005.png)

**Comment by domaindrivendev** [comment]
`System.Text.Json` is not fully supported yet … working on it, albeit in my limited free time 😉

**Comment by domaindrivendev** [comment]
Should be addresses by #1378. Preview nugets available on myget, official release coming real soon

**Comment by unchase** [comment]
Try to use [Unchase.Swashbuckle.AspNetCore.Extensions](https://github.com/unchase/Unchase.Swashbuckle.AspNetCore.Extensions) to fix the display of enums.
