### ISSUE TITLE
OpenApiModels doesn't exist

### ISSUE THREAD

**Issue by grosch** [domaindrivendev/Swashbuckle.AspNetCore#1327]
I just installed version 5.0.0-rc4 but there's no OpenApiInfo class found.  Using Visual Studio 2019 and ASP.NET Core 3

**Comment by domaindrivendev** [comment]
100% it's there! Perhaps your missing the `using Microsoft.OpenApi.Models` as described in the [readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#getting-started)?

**Comment by grosch** [comment]
I installed r3 and it compiles now.  Not sure what happened.  However, when I try and run the app (via F5 in VS.NET) then I get this error:

> Error	MSB3073	The command "dotnet "C:\Users\grosch\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\/../tools/dotnet-getdocument.dll" --assembly "C:\Users\grosch\source\repos\LaMP\LaMP\bin\Debug\netcoreapp3.0\LaMP.dll" --file-list "obj\LaMP.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v3.0" --output "obj" --project "LaMP" --assets-file "C:\Users\grosch\source\repos\LaMP\LaMP\obj\project.assets.json" --platform "AnyCPU" " exited with code 7.

Is there something else I'm supposed to do?

**Comment by grosch** [comment]
I'm using ASP.NET Core 3, so there's no Mvc involved here.  I'm guessing that's the issues as I read through your readme file again?

**Comment by domaindrivendev** [comment]
Install rc4 and you should be good

**Comment by grosch** [comment]
Thanks, rc4 definitely fixed that issue.  When I F5 in VS I can now append "/swagger/v1/swagger.json" and see the full output properly.  If I just go to "/swagger" or "/swagger/v1" I get a 404 though.  Did I miss something else?

**Comment by grosch** [comment]
I was missing the UseSwaggerUI call in Configure.  All is working now.  That you so much for your help and patience.
