### ISSUE TITLE
How to add an example for type Array

### ISSUE THREAD

**Issue by phikll12** [domaindrivendev/Swashbuckle.AspNetCore#1330]
`/// <summary>
 /// List Pet Name
 /// </summary>
/// <example>"Dog"</example>
[DataMember(Name="PetName ")]
public List<string> PetName { get; set; }`

**Genarate** 
{
  "PetName ": [
    "string"
  ]
}
**I want** 
{
  "PetName ": [
    "Dog"
  ]
}

**Comment by domaindrivendev** [comment]
You can only use the `<example>` tag for primitive types that can be easily expressed as a string.

For more complex examples, you'll need to do it manually through a custom `ISchemaFilter`. See the following for inspiration: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/Basic/Swagger/ExamplesSchemaFilter.cs
