### ISSUE TITLE
5.0.0-rc4 with Microsoft.AspNetCore.Mvc.Versioning doesn't generate json routes

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [domaindrivendev/Swashbuckle.AspNetCore#1334]
In an asp.net core web api project I had a previously perfectly working Swashbuckle setup with API versioning via attribute (like this:

```
 [ApiVersion("8.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [Produces("application/json")]
    public class AuthController : Controller
    {
...etc...
```
 working with .net core 2.x / Swashbuckle 4.x  project.

It was all working perfectly with my versioned api.

Recently I updated the project to .net core 3.1.100-preview1-014459 and Swashbuckle 5 rc4 and now the generated swagger.json has no routes when there should be dozens, e.g. this is what I get now:

```

{
  "openapi": "3.0.1",
  "info": {
    "title": "XXX API",
    "description": "XXX  API",
    "version": "8.0"
  },
  "paths": { },
  "components": {
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "description": "JWT Authorization header using the Bearer scheme.",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "Bearer": [ ]
    }
  ]
}
```
The instructions in the readme section here:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-the-action-selection-process

Seem to indicate that it will pick up those versioned routes but it does not.  In addition when I put a breakpoint at the top of that code it never hits.  Perhaps `DocInclusionPredicate `is never getting called due to the default one executing?

I have tried just about everything I could find or throw at this to no avail.

As a test I tried removing the Version attribute on all routes and all the versioning related code in my startup.cs and it documented all the routes just fine so it's clearly an issue with versioned routes.

How can this be resolved?

**Comment by domaindrivendev** [comment]
Can you share please share your Swagger configuration from `Startup.cs`.

**Comment by WhatFreshHellIsThis** [comment]
```
  services
                 .AddApiVersioning(options =>
                 {
                     options.AssumeDefaultVersionWhenUnspecified = true;
                     options.DefaultApiVersion = Microsoft.AspNetCore.Mvc.ApiVersion.Parse("8.0");
                     options.ReportApiVersions = true;
                 });

            services.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV");         
            services.AddSwaggerGen(
                           c =>
                           {
                               c.SwaggerDoc("v8", new OpenApiInfo { Title = "XXX API - V8", Version = "v8" });
                               c.DocInclusionPredicate((docName, apiDesc) =>
                                    {
                                        if (!apiDesc.TryGetMethodInfo(out MethodInfo methodInfo)) return false;

                                        var versions = methodInfo.DeclaringType
                                            .GetCustomAttributes(true)
                                            .OfType<ApiVersionAttribute>()
                                            .SelectMany(attr => attr.Versions);

                                        return versions.Any(v => $"v{v.ToString()}" == docName);
                                    });
                           });
```

Yields this:
```

{
  "openapi": "3.0.1",
  "info": {
    "title": "XXX API - V8",
    "version": "v8"
  },
  "paths": { },
  "components": { }
}
```

**Comment by WhatFreshHellIsThis** [comment]
So I just created a fresh webapi test project with all the latest versions of everything  and I *was* able to get Swashbuckle to work correctly with api versioning so it only doesn't work in my upgraded pr-existing project.  I'll figure out what the exact issue is and get it working with my upgraded project and post here once I find it what exactly was wrong to hopefully help others.  For the time being I don't think this is a bug though it may well be a documentation issue here.

**Comment by WhatFreshHellIsThis** [comment]
Found it!  Not what I expected at all: My project I'm upgrading is quite old and it didn't have the 
`[ApiController]`
attribute set on my api controllers, the moment I added that it worked!

So to be clear make sure you put the ApiController attribute on your controller routes, i.e. turn this:

```
ApiVersion("8.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [Produces("application/json")]
    public class AuthController : Controller
    {
....

```

Into this:

```
[ApiController]
ApiVersion("8.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [Produces("application/json")]
    public class AuthController : Controller
    {
```

**Comment by WhatFreshHellIsThis** [comment]
Oh, and just to add, I didn't use the method outlined in the readme for this Swashbuckle project for handling versioned routes 
(here 
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-the-action-selection-process 
it may very well work) but instead used the method outlined on the ApiVersion github site here:
https://github.com/microsoft/aspnet-api-versioning/wiki/Swashbuckle-Integration
