### ISSUE TITLE
Request : Custom paths in SwaggerGen

### ISSUE THREAD

**Issue by flmontpetit** [domaindrivendev/Swashbuckle.AspNetCore#1336]
Context : We have to maintain a legacy API and we can not make any changes to it (at least on the medium-long term). It was ported from WCF to ASP.NET Core and uses attribute routing like this : 

```
[Route("/v1/{action}")]
public class MyLegacyAPI : ControllerBase
```

Methods look like this : 

```
[HttpGet]
public ActionResult<ResultInfo> Login([Required]string username, [Required]string password)
{
    // everybody wants to steal my lucky charms
}
```

MVC routing takes care of resolving actions and parameters for us which is neat. However Swashbuckle only sees one path ("/v1/{action}") and considers every single method to be a duplicate. 

There is a viable workaround, which involves changing the route attribute ahead to simple "/v1/" and annotating every API action like this for example : 

```[HttpGet("Login")]```

However I envision something nifty like this : 

```
services.AddSwaggerGen(options =>
{
    // other options 
    options.CustomPaths(method => method.Name);
});
```

CustomPaths would expect a Func<MethodInfo, string>. It would be hard to guarantee that the entire route can be mapped properly but at least with MethodInfo we have access to DeclaringType and we can scan for Route attributes. This complexity can be handled by the calling application, not Swashbuckle itself. 

Obviously our service doesn't comply with OpenAPI specification in the slightest so it's natural that Swashbuckle requires some tweaking to work properly but we could have a more concise and less opaque solution that way.

**Comment by domaindrivendev** [comment]
If you change your Route definition to use square braces around the `action` route parameter instead of curly ones, I think your issue will be resolved.

```
[Route("/v1/[action]")]
public class MyLegacyAPI : ControllerBas
```

**Comment by domaindrivendev** [comment]
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-5.0#token-replacement-in-route-templates-controller-action-area
