### ISSUE TITLE
Why generated same tags?

### ISSUE THREAD

**Issue by scccboom** [domaindrivendev/Swashbuckle.AspNetCore#1337]
Swashbuckle.AspNetCore: 4.0.1
TargetFramework: netcoreapp2.1

`api/[controller]` and `api/[controller]/{id}` generated tags `[controller]`.
Open Swagger UI. 
Click opblock it's all open.
Inspect element opblock has same id.
This issue report here or swagger-ui.

**Comment by domaindrivendev** [comment]
I don't believe this is an issue with the latest version.
