### ISSUE TITLE
SwaggerUI in combination with Azure API gateway not generating correct url's

### ISSUE THREAD

**Issue by JBastiaan** [domaindrivendev/Swashbuckle.AspNetCore#1338]
Hello,

we have an API hosted in an Azure app service that is exposed through an API gateway. The gateway adds an additional prefix in the url.

For example when calling the app service directly the url would be: 
/api/docs/index.html

Via the gateway it would be
/customername/api/docs/index.html

Now the issue is that the documentation generated by Swashbuckle does not take the /customername/ part into account in the endpoints generated. So all calls done from the SwaggerUI end up in a 404.

I read that Swagger looks at the Pathbase of the Request object to determine the base url. However apparently that is not filled when the request is directed through the API gateway. What are my options here? Is the only option to set the BasePath manually like this?:

` app.UseSwagger(c =>
 {
     c.PreSerializeFilters.Add((swagger, request) => swagger.BasePath = "/customername");
 });`

The only downside i see with this is then the swagger docs will only work when directed through the gateway since it is then hardcoded, and will no longer work when calling the api directly..

**Comment by sjmorgan81** [comment]
I am new to Swashbuckle and Swagger so I might be wrong but I think it might be the [servers](https://swagger.io/specification/#serverObject) object in the generated JSON that you need to override. I think when Swashbuckle is running behind an API gateway it gets confused and so, at least in my case, the servers object wasn't even getting included in the generated JSON.

To fix it in my case I ended up doing:

```cs
if (env.IsProduction())
{
    app.UseSwagger(options => options.PreSerializeFilters.Add((swagger, httpReq) =>
    {
        if (httpReq.Host.Host == "production.example.net")
        {
            swagger.Servers = new List<OpenApiServer> { new OpenApiServer { Url = "/addresses" } };
        }
    }));
}
```

**Comment by domaindrivendev** [comment]
Consolidated into #1953

**Comment by stackdownflow** [comment]
@JBastiaan - Is the your issue fixed ?
