### ISSUE TITLE
Allow attribute to auto-add ProducesResponseType

### ISSUE THREAD

**Issue by grosch** [domaindrivendev/Swashbuckle.AspNetCore#1339]
So I've got a lame-o attribute defined like so:

``` C#
    internal class ModelValidationAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!context.ModelState.IsValid)
                context.Result = new BadRequestObjectResult(context.ModelState);
        }
    }
```

That means that any route which includes the `[ModelValidationAttribute]` needs to also have the `[ProducesResponseType(StatusCodes.Status400BadRequest)]` added to it.  

Would be awesome if there were some way we could tag that so that Swashbuckle knew and just automatically added that for me so I didn't need to remember to put it on every route.

**Comment by domaindrivendev** [comment]
A very simple IOperationFilter (see readme) would do the trick. In fact this is exactly the usecase for adding that extensibility point

**Comment by grosch** [comment]
Thanks.  Gotta read that thing closer.
