### ISSUE TITLE
Subclass with the same name as the base class.

### ISSUE THREAD

**Issue by FurstLevy** [domaindrivendev/Swashbuckle.AspNetCore#1340]
### System Details

- Web Framework version: netcoreapp3.0
- Swashbuckle.AspNetCore version: 5.0.0-rc5

The endpoint receives a ViewModel.
This ViewModel has a property where it is the same name as the base class.

I am attaching two images to make it easier to understand. One is when it works and another not.

![NotWork](https://user-images.githubusercontent.com/7149828/67505084-fa692980-f660-11e9-9436-e77c0c47df54.png)

![Working](https://user-images.githubusercontent.com/7149828/67505092-fe954700-f660-11e9-8b29-ccd5cbb30e86.png)

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-schema-ids
