### ISSUE TITLE
Wrong interpretation of `readOnly` and `writeOnli` concepts in Swagger

### ISSUE THREAD

**Issue by pqnet** [domaindrivendev/Swashbuckle.AspNetCore#1341]
In Swagger specification, `readOnly` and `writeOnly` refer to whether the annotated property is not present when the DTO is used as a parameter (`readOnly`) or as a server response (`writeOnly`). See  https://swagger.io/docs/specification/data-models/data-types/

Swashbuckle incorrectly computes these attributes based on the presence of getters and setters for the property in the C# class.
This causes clients (such as Swagger-UI) to generate incorrect calls, for example when serialising request parameter objects.

The correct approach should be to not derive these properties from readability or writability of the properties in the C# class, but to rely on some custom annotation.

see:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/ad91d72078e1e2276824b38e2483c1d8ab6e5376/src/Swashbuckle.AspNetCore.SwaggerGen/Newtonsoft/NewtonsoftApiModelResolver.cs#L166

**Comment by domaindrivendev** [comment]
I disagree! Swashbuckle is computing these flags according to "serializer behavior". For example, Newtonsoft will de-serialize JSON payload properties into a corresponding C# property if:

- The C# property has a public setter
- OR the declaring type's constructor accepts a parameter with the same name

This is the "serializer behavior" and therefore your application's behavior - i.e. specifically what Swashbuckle is describing. If your DTO has properties that don't meet either of the above requirements, then the value WILL NOT be populated into the C# instance and therefore CANNOT ever be written via your API. Therefore, setting `readOnly` is the correct interpretation.

**Comment by domaindrivendev** [comment]
You mentioned that the current behavior is causing the swagger-ui to generate incorrect calls. Could you provide a concrete example of this? It might help me understand your issue a little better.
