### ISSUE TITLE
SwaggerUI - OAuth - client_credentials: Failed to fetch

### ISSUE THREAD

**Issue by jwefers** [domaindrivendev/Swashbuckle.AspNetCore#1344]
When specifiying an OAuth Policy with client_credentials flow, the token acquiration in the UI fails. SwaggerUI does OPTIONS against the token endpoint, whose response does not set a CORS header.

![image](https://user-images.githubusercontent.com/851823/67664123-4f5db600-f967-11e9-8c0c-d55d51a9c25d.png)

![image](https://user-images.githubusercontent.com/851823/67663758-82537a00-f966-11e9-9704-94dbb3ecc647.png)

`Access to fetch at 'https://login.microsoftonline.com/<mytenant>/oauth2/v2.0/token' from origin 'http://localhost:5000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by hoffe86** [comment]
Same issue on my side.

**Comment by domaindrivendev** [comment]
Technically, I don't think this is an issue with Swashbuckle or the swagger-ui. To support the client credentials flow from _any_ client that's on a different domain to the token endpoint (swagger-ui just happens to be the example here), then the token endpoint would need to support CORS by returning an appropriate `Access-Control-Allow-Origin` header. This isn't an issue with the swagger-ui, it's just how the web works. Maybe the following SO thread will help explain it better and possibly offer up some workarounds:

https://stackoverflow.com/questions/38317973/no-access-control-allow-origin-header-with-microsoft-online-auth

**Comment by hoffe86** [comment]
Not sure if the workaround is working with the token of Azure Active Directory or Azure B2C, which is managed by Microsoft. 

There is an older issue for Swagger UI #swagger-ui/3172, which describes the issue with a solution by replacing redirect page.

**Comment by clericc** [comment]
what about no-cors?
https://developer.mozilla.org/en-US/docs/Web/API/Request/mode

**Comment by Doomblaster** [comment]
Looking at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS and scrolling down to "Simple Request", I'm thinking this could be solved by not sending client_id/client_secret as Authorization header, but put it in the body. Then I think this should satisfy a "Simple Request" and not send the preflight CORS request. Not sure if that is possible to do with just configuration though.

**Comment by Doomblaster** [comment]
`<html>

<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
    <script>
        async function postData(url = '', clientId = '', clientSecret = '') {
            let headers = {
                "Accept": "application/json;charset=utf-8",
                "Content-Type": "application/x-www-form-urlencoded"
            }
            let body = "grant_type=client_credentials&scope=dm.loan&client_id=" + clientId + "&client_secret=" + clientSecret

            let response = await fetch(url, {
                mode: "no-cors",
                method: "post",
                headers: headers,
                body: body
            });
            return response;
        }
        let url = "";
        let clientId = "";
        let clientSecret = "";

        postData(url, clientId, clientSecret);
    </script>
</head>

<body>
</body>

</html>`

seems like the no-cors + putting credentials in body does the trick at least, but then again...this is maybe a 3rd library that is being used?

**Comment by domaindrivendev** [comment]
@jwefers can this be closed?

**Comment by jwefers** [comment]
well if its possible to to client_credentials flow via UI. But i have never tried again - we obtain tokens via cmdline and then paste them into Swagger as "Bearer <token>"

**Comment by jwefers** [comment]
btw thanks for the amazing work you do in general here, dont want to be unthankful here - i could obv spend the time and make a PR at some point ;)

**Comment by k290** [comment]
Just chipping in: Currently it doesn't seem to be possible to get this to work using swashbuckle. The reasoning is well understood. A workaround using Swashbuckle would be valuable.
For now, I'm running client_credentials using commandline or postman and then pasting the token into Swagger

**Comment by Odraio** [comment]
Currently I'm facing the same issue while using the authorization code flow. Does somebody already has a workaround or it the only 'solution' to add the domain to the CORS supported withelist of the token provider?

**Comment by thomaswurtz** [comment]
The workaround suggested in [swagger-api/swagger-ui#6081 (comment)](https://github.com/swagger-api/swagger-ui/issues/6081#issuecomment-848894552) works for me.

I don't have a suitable code snippet to share, but you should be able to put that workaround in a custom javascript file you then use similar to this example:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v5.4.1/test/WebSites/CustomUIConfig/Startup.cs#L74

**Comment by jwr3408** [comment]
Try this .NET package: AspNetCore.Proxy.

Add this code to your program.cs file after app.MapControllers().RequireAuthorization() and before app.Run()

```
  app.UseProxies(proxies =>
    {
        proxies.Map("oauth", proxy => proxy.UseHttp(ConfigSettings.TokenUrl,
            builder => builder.WithShouldAddForwardedHeaders(false)));
    });
```

here is my _flows_ parameter: 
```
 Flows = new OpenApiOAuthFlows()
                    {
                        ClientCredentials = new OpenApiOAuthFlow
                        {
                            TokenUrl = new Uri("/oauth", UriKind.Relative),
                            Scopes = new Dictionary<string, string>()
                        }
                    }
```
