### ISSUE TITLE
I had a problem adding a swagger to the ocelot gateway

### ISSUE THREAD

**Issue by miaoyukai** [domaindrivendev/Swashbuckle.AspNetCore#1345]
![image](https://user-images.githubusercontent.com/38027640/67752167-756d7e00-fa6d-11e9-9537-c01bb300e920.png)
Pictured above,How can I set curl on the swagger to make it look like the following figure？
![27f00cc44ba4c80526748090f8e45b5](https://user-images.githubusercontent.com/38027640/67752687-5de2c500-fa6e-11e9-855d-a5ffb3c66ea9.png)

Thanks

**Comment by domaindrivendev** [comment]
Consolidated into #1953
