### ISSUE TITLE
5.0.0-rc4 Unable to render this definition

### ISSUE THREAD

**Issue by michelmob** [domaindrivendev/Swashbuckle.AspNetCore#1347]
Hi! I'm trying to update my project to use Asp.Net Core 3.0 and 
Swashbuckle.AspNetCore 5.0.0-rc4 but I'm receiving this message:

Parser error on line 8
end of the stream or a document separator is expected

and 

Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

Can you guys help me?

**Comment by Fosol** [comment]
I still see this error in v5.0.0 once I deploy.  Works fine locally though.

**Comment by domaindrivendev** [comment]
Looks like a dup of #1105, which I believe was traced back to an ASP.NET Core Kestrel bug rather than Swashbuckle.
