### ISSUE TITLE
5.0.0-rc4 - an exception for multiple IFileForm controller method parameters

### ISSUE THREAD

**Issue by xhafan** [domaindrivendev/Swashbuckle.AspNetCore#1348]
Swashbuckle.AspNetCore 5.0.0-rc4, with a controller method like this:

```c#
        public async Task<string> Import(
            [FromForm]IFormFile file1,
            [FromForm]IFormFile File2,
            [FromForm]IFormFile file3
        )
```
it throws `An item with the same key has already been added. Key: ContentType'` when accessing `/swagger/v1/swagger.json`

**Comment by jlehto** [comment]
Got this with 5.0.0-rc2 as well.

**Comment by MayGodBlessYouAMen** [comment]
I also encountered the same problem. Is there a way to solve it?

**Comment by MayGodBlessYouAMen** [comment]
There is no error in writing like this：

public class RequestFiles()
{
	public IFormFile File1 {get;set;}
	public IFormFile File2 {get;set;}
	public IFormFile file3 {get;set;}
}

public async Task<string> Import([FromForm]RequestFiles request)
{ 

}

**Comment by nomailme** [comment]
> There is no error in writing like this：
> 
> public class RequestFiles()
> {
> public IFormFile File1 {get;set;}
> public IFormFile File2 {get;set;}
> public IFormFile file3 {get;set;}
> }
> 
> public async Task Import([FromForm]RequestFiles request)
> {
> 
> }

Thank you for this  workaround

**Comment by domaindrivendev** [comment]
There's a couple of interesting things going on here. Firstly, when using `IFormFile`, you don't need to decorate the parameters with `[FromForm]` as the binding source is automatically inferred by ASP.NET Core based on the type. If you look at the official docs, the attribute is never included - https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1.

Furthermore, if you _do_ include the attribute, `ApiExplorer`, the ASP.NET Core component that Swashbuckle is built on top of, seems to get very confused and ends up surfacing `ApiParameterDescription.Name` = "Content-Type" for all three parameters, hence the duplicate key issue you're observing.

So, if you remove the `[FromForm]` attributes, which aren't really meant to be there in the first place, everything should work as expected and Swashbuckle will generate the Swagger output without any issues:

```csharp
public async Task<string> Import(
    IFormFile file1,
    IFormFile File2,
    IFormFile file3
)
```

**Comment by nomailme** [comment]
Indeed, @domaindrivendev. Removing these attributes resolved my issue. Thank you.

**Comment by xhafan** [comment]
Works for me now when I removed `[FromForm]` , and I could also delete me custom `FormFileOperationFilter` I took from https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/193#issuecomment-280695375
