### ISSUE TITLE
Update swagger-ui - Request CURL output XSS issue

### ISSUE THREAD

**Issue by yngndrw-sage** [domaindrivendev/Swashbuckle.AspNetCore#135]
Swashbuckle Ahoy currently uses an old version of swagger-ui which has an XSS issue when displaying the CURL output.

The corrected line can be seen here:
https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/OperationView.js#L777

The [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle/) repository also has this issue so I've [raised a separate issue there](https://github.com/domaindrivendev/Swashbuckle/issues/818).

**Issue Reproduction**
Enter `<script>alert(document.domain);</script>` into a body parameter of an operation and click "Try it out!", the parameter is output without escaping into the CURL output and an alert box is shown.

**Comment by domaindrivendev** [comment]
updated in master to use 2.2.6

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"

**Comment by attritionorg** [comment]
@yngndrw-sage Do you have a reference for the swagger-ui XSS issue, other than the quoted line?

**Comment by yngndrw-sage** [comment]
@attritionorg I seem to have foolishly quoted a specific line number in the head revision, which has now changed - Oops.

Anyway here's the related pull request in swagger-ui where this was fixed:
https://github.com/swagger-api/swagger-ui/pull/1869

... and the associated issue:
https://github.com/swagger-api/swagger-ui/issues/1863

**Comment by attritionorg** [comment]
Ah great, thanks for the links. That is 2016-1000233 for reference =)
