### ISSUE TITLE
swagger generates the same operationId

### ISSUE THREAD

**Issue by eladmotola** [domaindrivendev/Swashbuckle.AspNetCore#1351]
swagger generates a json with the same operationId, which not allowed by the spec - https://swagger.io/specification/v2/

For the following steps:
1. create an empty WebAPI project
2. create a new controller and add another Get function that recieve a paramter like this example:
`public class UserController : ApiController`
`    {`
       ` public string[] Get()`
`        {`
           ` return new string[] { "value1", "value2" };`
        `}`
`        public string Get(int id)`
`        {`
           ` return "value";`
`        }        `
`    }`

swagger generates:
`{{ "swagger": "2.0", "info": { "version": "v1", "title": "WebApplication1" }, "host": "localhost:3873", "schemes": ["http"], "paths": { "/api/User": { "get": { "tags": ["User"], "operationId": "User_Get", "consumes": [], "produces": ["application/json", "text/json", "application/xml", "text/xml"], "responses": { "200": { "description": "OK", "schema": { "type": "array", "items": { "type": "string" } } } } } }, "/api/User/{id}": { "get": { "tags": ["User"], "operationId": "User_Get", "consumes": [], "produces": ["application/json", "text/json", "application/xml", "text/xml"], "parameters": [{ "name": "id", "in": "path", "required": true, "type": "integer", "format": "int32" } ], "responses": { "200": { "description": "OK", "schema": { "type": "string" } } } } } }, "definitions": {} }}`

Im using the latest version

**Comment by domaindrivendev** [comment]
Please see https://github.com/domaindrivendev/Swashbuckle.AspNetCore#assign-explicit-operationids
