### ISSUE TITLE
Version for package `Swashbuckle.AspNetCore.Cli` could not be resolved.

### ISSUE THREAD

**Issue by vikasillumina** [domaindrivendev/Swashbuckle.AspNetCore#1353]
Hi there,

I am trying to use the solution as discussed here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/541
I am trying to use 4.0.1 version:
` <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="4.0.1" />
    <DotNetCliToolReference Include="Swashbuckle.AspNetCore.Cli" Version="4.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="4.0.1" />`

But when I run the command:
` dotnet swagger tofile --help`
I am seeing this error:
`Version for package `Swashbuckle.AspNetCore.Cli` could not be resolved.`

What I am missing?

**Comment by mikeblakeuk** [comment]
Make sure you install the manifest first

> dotnet new tool-manifest

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#using-the-tool-with-the-net-core-30-sdk-or-later
