### ISSUE TITLE
Scope validation failed 

### ISSUE THREAD

**Issue by kinglionsoft** [domaindrivendev/Swashbuckle.AspNetCore#1354]
Scope validation failed  as  Singleton DocumentProvider accesses to Transient SwaggerGenerator: 
```
Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.ApiDescriptions.IDocumentProvider Lifetime: Singleton ImplementationType: Microsoft.Extensions.ApiDescriptions.DocumentProvider': No constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator' can be instantiated using services from the service container and default values.
```
[SwaggerGenServiceCollectionExtensions.cs#L33](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenServiceCollectionExtensions.cs#L33)
``` c#
services.AddTransient<ISwaggerProvider, SwaggerGenerator>();
...
services.TryAddSingleton<IDocumentProvider, DocumentProvider>();
```
* scope validation
[https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.0#scope-validation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.0#scope-validation)

* Swashbuckle.AspNetCore.SwaggerGen: 5.0.0-rc4
* netcoreapp3.0

**Comment by martincostello** [comment]
Closing due to age - please open a new issue if you still have this issue in the latest version of Swashbuckle.
