### ISSUE TITLE
"Could not resolve reference: Not Found" Error

### ISSUE THREAD

**Issue by ziad-akiki** [domaindrivendev/Swashbuckle.AspNetCore#1355]
**Using**:

| Name | Version |
| --- | --- |
| Asp .Net Core | 3.0 |
| Swashbuckle.AspNetCore | 5.0.0-rc4 |
| IIS Express |

I have a `User` model as follows:
```
public class User : BaseModel
{
        public virtual User Manager { get; set; }
        public virtual ICollection<User> Team { get; }

        [Required]
        [StringLength(32)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(32)]
        public string LastName { get; set; }

        //... other basic properties
}
```

I then defined a `UsersController` with a registration method that takes the following object as request body:
```
/// <summary>
/// Registers a new user.
/// </summary>
/// <remarks>
/// Sample request:
/// 
///     POST api/users/register
///     {
///         "email":"test@test.com",
///         "firstName":"Test",
///         "lastName":"Test",
///         "phone":"0011",
///         "password":"password"
///     }
///
/// </remarks>
/// <param name="userParam">A new user to register.</param>
/// <returns>The new user with its new ID.</returns>
/// <response code="200">Returns the newly created user.</response>
/// <response code="400">If the email is already registered with the app.</response>
[AllowAnonymous]
[HttpPost("register")]
[ValidateModel]
[ProducesResponseType(200)]
[ProducesResponseType(400)]
public async Task<IActionResult> Register([FromBody] User userParam) 
{ ... }
```

Now when browsing to the swagger UI I'm getting the following errors _when I try to expand an API route definition_: "Could not resolve reference: Not Found":
![image](https://user-images.githubusercontent.com/40595927/68280261-d99bcd80-007d-11ea-8cea-80697fd986d4.png)

Looking at the `/swagger/v1/swagger.json` I found that it is well referenced:
```
"components": {
    "schemas": {
      "User": {
        "required": [
          "email",
          "firstName",
          "lastName",
          "password",
          "phone"
        ],
        "type": "object",
        "properties": {
          "manager": {
            "$ref": "#/components/schemas/User"
          },
          "team": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/User"
            },
            "nullable": true,
            "readOnly": true
          },
...
```

And this is my `Startup.cs` configuration in case it's needed:
_The Configure Services Part:_
```
services.AddSwaggerGen(options =>
{
	options.SwaggerDoc("v1", new OpenApiInfo
	{
		Title = "Test API",
		Version = "v1",
		Contact = new OpenApiContact
		{
			Name = "Test",
			Email = "test@test.com"
		}
	});

	var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
	var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
	options.IncludeXmlComments(xmlPath);
});
```
_The Configure Part:_
```
if (env.IsDevelopment())
{
	app.UseDeveloperExceptionPage()
		.UseSwagger()
		.UseSwaggerUI(options =>
		{
			options.SwaggerEndpoint("../swagger/v1/swagger.json", "Test API");
		});
}
```

Any solution to this?

**Comment by spaasis** [comment]
Possibly related? #1352

**Comment by domaindrivendev** [comment]
Hmmm this is interesting. As far as I can tell the `swagger.json` that's generated by Swashbuckle looks correct and so, this points to an issue with the [swagger-ui](https://github.com/swagger-api/swagger-ui) as opposed to Swashbuckle itself.

I looked in their issue list and found the following which seems to be related:
https://github.com/swagger-api/swagger-ui/issues/5726

**Comment by kiran-bobade** [comment]
I observed the same issue in my .net core 3.1 API. It was the issue related to **JObject** because I have JObject property in my model. And the solution was


```
    services.AddSwaggerGen(options =>
    {
        // other options
        options.MapType<JObject>(() => new OpenApiSchema { Type = "object" });
    });
```

**Comment by JerrySantana92** [comment]
Remove the .. in your configuration.

Replace this:
options.SwaggerEndpoint("../swagger/v1/swagger.json", "Test API");

By this:
options.SwaggerEndpoint("/swagger/v1/swagger.json", "Test API");
