### ISSUE TITLE
Enums not working with Dictionary<,> when used as key

### ISSUE THREAD

**Issue by phosphene47** [domaindrivendev/Swashbuckle.AspNetCore#1356]
v5.0.0-rc4

When enums are used as the key in Dictionary<,>, it is serialized as an object model with the enum values as field names. However, camelCasing and `EnumMember` attributes do not work on them.

`EnumMember` example (simply omit the attribute for camel casing example):
```csharp
enum Tags {
  [EnumMember(Value = "au")]
  Author
}

class RequestModel {
  public Dictionary<Tags, string[]> Tags { get; set; }
}
```

Produces a schema like this:
```json
"RequestModel": {
  "type": "object",
  "properties": {
    "Tags": {
      "type": "object",
      "properties": {
        "Author": { // notice this line
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Expected schame would be:
```json
"RequestModel": {
  "type": "object",
  "properties": {
    "Tags": {
      "type": "object",
      "properties": {
        "au": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

**Comment by phosphene47** [comment]
A temporary solution is writing a concrete class with fields using `JsonProperty`

```csharp
class TagsDictionary {
  [JsonProperty("au")]
  public string[] Author { get; set; }
}
```

which is cumbersome especially for large enums.

**Comment by quico14** [comment]
Is there any way to avoid having a `List<KeyValuePair<Tags, string[]>>` and having instead a `Dictionary<Tags, string[]>` with the enum Key being well set up in the contract, instead of defining whichever string?

Thanks :)
