### ISSUE TITLE
net::ERR_CONNECTION_RESET when upload file 254Mb

### ISSUE THREAD

**Issue by Marusyk** [domaindrivendev/Swashbuckle.AspNetCore#1357]
Using Swashbuckle.AspNetCore 4.0.1

My action is
```csharp
[HttpPost]
public async Task<IActionResult> Add([FromForm] IFormFile file)
{
	if (file == null)
	{
		throw new BadRequestException(nameof(file), "No file specified");
	}

	using (Stream data = file.OpenReadStream())
	{
		SoundDto sound = await _soundsManager.Add(new SoundAddDto { Name = file.FileName, Data = data});
                return StatusCode((int)HttpStatusCode.Created, sound);
	}
}

```

When I upload a file with size 254Mb I goe the error:

![Screenshot_1](https://user-images.githubusercontent.com/9221694/68301103-e8977580-00a7-11ea-8551-079339a4d5e1.png)

Files with size less than 200 is ok

**Comment by Marusyk** [comment]
any news?

**Comment by domaindrivendev** [comment]
Have you tried uploading from a different tool (e.g. postman, curl etc.)? What makes you think this is an issue with Swashbuckle as opposed to your application?

**Comment by Marusyk** [comment]
Yes, of course I have tried. The problem only when upload with Swashbuckle
