### ISSUE TITLE
Way to set token from UI in new version

### ISSUE THREAD

**Issue by FabioMorcillo** [domaindrivendev/Swashbuckle.AspNetCore#1359]
Hi,

In older version we can set token from UI using:
window.swaggerUi.api.clientAuthorizations.add("key", new SwaggerClient.ApiKeyAuthorization("Authorization", "Bearer " + r.access_token, "header"));

In new version, i changed the index.html:
app.UseSwaggerUI(c =>
            {
                c.IndexStream = () => new FileStream($"{AppDomain.CurrentDomain.BaseDirectory}/wwwroot/index.html", FileMode.Open);
            });

How can we set token from this custom index.html using javascript ?

or

How can we append more inputs in authentication page and make custom authentication ?

**Comment by ronaldhoek** [comment]
Please take a look at the code I added for another issue: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/971#issuecomment-604488724

It's the code I use to be able to specify a JWT beare token.
Should be adaptable to your case ;)

**Comment by domaindrivendev** [comment]
@ronaldhoek's solution seems like it should work for this usecase
