### ISSUE TITLE
ProblemDetails JSON Schema generated in SwaggerUI does not match the ProblemDetails schema returned by ASP.NET Core 3.0

### ISSUE THREAD

**Issue by Kevweir** [domaindrivendev/Swashbuckle.AspNetCore#1360]
SwaggerUI ProblemDetails schema:

type | stringnullable: true
-- | --
title | stringnullable: true
status | integer($int32)nullable: true
detail | stringnullable: true
instance | stringnullable: true
extensions | {...}

ProblemDetails Schema returned by ASP.NET Core 3.0

{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "|1cbf858e-4fa8cb5c015e787e.",
  "errors": {
    "": [
      "A non-empty request body is required."
    ]
  }
}

**Comment by Kevweir** [comment]
To clarify I'm using this version of Swashbuckle.AspNetCore
Install-Package Swashbuckle.AspNetCore -Version 5.0.0-rc4

**Comment by Kevweir** [comment]
Thanks for responding.  For starters the SwaggerUI ProblemDetails has detail, instance and extensions properties that the ASP.NET Core ProblemDetails does not. 
Also the ASP.NET Core ProblemDetails has type, tracid and errors properties that the SwaggerUI ProblemDetails does not.

**Comment by Kevweir** [comment]
Basically the naming conventions only match on the title and status properties.

**Comment by cremor** [comment]
> For starters the SwaggerUI ProblemDetails has detail, instance and extensions properties that the ASP.NET Core ProblemDetails does not.

This is no problem since all those properties are neither marked as required nor marked as not nullable.

> Also the ASP.NET Core ProblemDetails has type, tracid and errors properties that the SwaggerUI ProblemDetails does not.

Swashbuckle does have the "type" property. It's the first row in your table.
About the other properties: Please read my previous answer again. The ProblemDetails RFC allows arbitrary properties. You can have any property you want in the ProblemDetails response and it will still be valid according to the spec.

**Comment by Kevweir** [comment]
Ok thanks for the feedback.  I just had an expectation they match exactly but they clearly do not.  Thanks for the clarification.
