### ISSUE TITLE
Example with null value

### ISSUE THREAD

**Issue by jdeboer-geoplan** [domaindrivendev/Swashbuckle.AspNetCore#1361]
Feature Request:

I think this is a feature request as I don't think there is a way of doing this.

I would like

        /// <summary>
        /// blah blah blah
        /// </summary>
        /// <example>null</example>
        public int? NullableInt{ get; set; }

to produce:

          "nullableInt": {
            "type": "integer",
            "description": "blah blah blah",
            "format": "int32",
            "nullable": true,
            "example": null
          },

At the moment it does not produce an example and the swaggerUI gives it a 0.

I've got round this by implementing an ISchemaFilter based on XmlCommentsSchemaFilter which looks for the word "null" and sets the example to OpenApiNull(), but I wonder if this'd be good to have in the real XmlCommentsSchemaFilter or if I've missed something obvious to avoid having to do this.

**Comment by domaindrivendev** [comment]
Fixed by #2151
