### ISSUE TITLE
The nuget package is not uptodate with the source for .Net Core 3

### ISSUE THREAD

**Issue by Elvin1492** [domaindrivendev/Swashbuckle.AspNetCore#1362]
The nuget package is not uptodate with the source. That's why most of the users getting 

`Lifetime: Transient ImplementationType: Swashbuckle.AspNetCore.SwaggerGen.SchemaRegistryFactory': Failed to compare two elements in the array.use it is an interface`

The main difference is in Microsoft.Extensions.*. (Specially, Microsoft.OpenApo.Models).

I downloaded the source from github, and referenced the *.dll manualy, and everything started to work.

**Comment by domaindrivendev** [comment]
Nuget packages are a snapshot in time, whereas the master branch on GitHub is in constant development and therefore will nearly always be _ahead_ of what's been explicitly published to Nuget. This is a very typical CI/CD approach.

With that said, a git tag is created for every release that goes to Nuget, so if you want to see the source code for a given release, you simply select that tag from the branches drop-down on the project's git page.
