### ISSUE TITLE
System.Text.Json.Serialization.JsonIgnore attribute not used when ignoring properties

### ISSUE THREAD

**Issue by crnd** [domaindrivendev/Swashbuckle.AspNetCore#1363]
Swashbuckle.AspNetCore does not use the `System.Text.Json.Serialization.JsonIgnore` attribute when ignoring response object properties. It seems that only the `Newtonsoft.Json.JsonIgnore` is properly handled when generating the API spec.

With the following simple API the expected result would be that only the property `NotIgnored` would be included in the API spec JSON. However both the `NotIgnored` and `SystemTextJsonIgnore ` properties are present.

```
[Route("[controller]")]
public class TestObjectsController
{
    [HttpGet]
    public ActionResult<TestObject> GetTestObject()
    {
        return new TestObject
        {
            NotIgnored = Guid.NewGuid().ToString(),
            SystemTextJsonIgnore = Guid.NewGuid().ToString(),
            NewtonsoftJsonIgnore = Guid.NewGuid().ToString()
        };
    }
}
```

```
public class TestObject
{
    public string NotIgnored { get; set; }

    [System.Text.Json.Serialization.JsonIgnore]
    public string SystemTextJsonIgnore { get; set; }

    [Newtonsoft.Json.JsonIgnore]
    public string NewtonsoftJsonIgnore { get; set; }
}
```

ASP.NET Core 3.0
Swashbuckle.AspNetCore 5.0.0-rc4
[https://github.com/crnd/swashbuckle-ignore-issue](https://github.com/crnd/swashbuckle-ignore-issue) Sample project to reproduce the issue

**Comment by domaindrivendev** [comment]
Should be addresses by #1378. Preview nugets available on myget, official release coming real soon
