### ISSUE TITLE
PascalCase serialization for ASP.NET 3.0 (Text.Json)

### ISSUE THREAD

**Issue by Msirkovsky** [domaindrivendev/Swashbuckle.AspNetCore#1364]
Hi, thank you for your great work. 
I have upgraded my app to asp.net 3.0(serializer Text.Json ) with this settings:

services.AddControllers().AddJsonOptions(opt => { opt.JsonSerializerOptions.PropertyNamingPolicy = null; });

to achieve PascalCase(classes and properties) for my models.

But when I go to the endpoint /swagger.json I see, that class is PascalCased(Provider) but properties are lower case(id, userId).

Example:
"Provider": {
       "type": "object",
       "properties": {
         "id": {
           "type": "string",
           "format": "uuid"
         },
         "userId": {
           "type": "string",
           "format": "uuid"
         },
...

Thank you

**Comment by domaindrivendev** [comment]
Should be addresses by #1378. Preview nugets available on myget, official release coming real soon
