### ISSUE TITLE
Can't change request header of accpet when request the api that cause the request to fail.

### ISSUE THREAD

**Issue by laggage** [domaindrivendev/Swashbuckle.AspNetCore#1366]
I aming using version: 5.0.0-rc4;
when  implement hateoas, always  need to customsize mimetype; so if request the api, we need to add the custom header of accept.
The picture bellow may better shows what I mean.
![image](https://user-images.githubusercontent.com/38829279/68588456-7ddda400-04c4-11ea-822e-7b39d1fdb831.png)

**Comment by domaindrivendev** [comment]
Short answer is to simply apply the `ProducesAttribute` on the  controller or actions that you'll be exposing this mime type from:

```csharp
[Produces("application/vnd.la.hateos+json")]
public class TagsController
{
…
}
```

Swashubuckle will automatically pick up this attribute and incorporate the specified content types into the generated Swagger/OpenAPI document accordingly. It's worth noting that Swagger/OpenAPI 3.0 does not use the generic `Headers` collection for certain reserved headers (`Content-Type`, `Accept`, `Authorization` etc.) and represents them differently. For example, see [this link](https://swagger.io/docs/specification/describing-request-body/) to understand how content types are incorporated into the Swagger/OpenAPI document format.

**Comment by laggage** [comment]
Thanks for answer! Howerver...
Confused still...
![image](https://user-images.githubusercontent.com/38829279/68591979-f183af00-04cc-11ea-9d8a-62a5583ab70a.png)
In my code, only if the request header has `Accept` -> `application/vnd.la.hateoas+json`, then it will return the resources that I reqeust with swaggerui(Execute button), but I don't know what to do if I want to add `Accept` when I request my api through swagger ui. 
I have tried what you say than add attribute `Produces`, but it wasn't what I wanted;
