### ISSUE TITLE
Incorrect json serialization of examples with OpenApiDouble and OpenApiFloat

### ISSUE THREAD

**Issue by nilshedstrom** [domaindrivendev/Swashbuckle.AspNetCore#1367]
### Bug

Name | Version
-- | --
Asp .Net Core | 3.0
Swashbuckle.AspNetCore | 5.0.0-rc4
IIS Express

I have a schema filter
```    
public class AddSchemaExamples : ISchemaFilter
{
        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            schema.Example = new OpenApiDouble(4.2);
        }
}
```
That is added inside ConfigureServices
```
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
                c.SchemaFilter<AddSchemaExamples>();
            });
```

The example is incorrectly serialized to json as 
`
"example": 4,2
`

The correct serialization would be
`
"example": 4.2
`
The same bug also seems to affect OpenApiFloat

**Comment by nilshedstrom** [comment]
The bug was related to the fact that I was using a culture with NumberFormat.NumberDecimalSeparator="," and that caused issues with parsing/serialization of float and double values because the code depends on the current culture.

I made a fix in #1379 .

**Comment by nilshedstrom** [comment]
I will close this bug since the PR with the fix has been merged to master.

**Comment by royvandertuuk** [comment]
When can we expect a new release candidate with this fix included?
