### ISSUE TITLE
Export as yaml file

### ISSUE THREAD

**Issue by TimmyGilissen** [domaindrivendev/Swashbuckle.AspNetCore#1368]
I have created a pr to export the openapi as a YAML file. 

To automatically deploy it azure we are using an arm template. for that reason, the content has to be in the YAML format.

Can you guys review the pr I created so we go forther with our CD :).

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1358

**Comment by TimmyGilissen** [comment]
I have reverted the commits back to the working version.

There is more work to be done than just updating the swagger middleware by looking at the HTTP headers.

By default, the path is set to export a JSON file, if you want to be able to export a YAML file you need to update the path so the file is exported as a YAML file.

I think a more explicit way is a better approach. When you configure the SwaggerGen you explicitly say you want to work with a YAML setup.

This makes it more clear what you are working with. Instead of using the header notation.

[#1358 ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1358)

**Comment by ShaneZhengNZ** [comment]
@TimmyGilissen Do you know what is the progress for this one? How do we export as a YAML file? Any examples?

**Comment by TimmyGilissen** [comment]
@ShaneZhengNZ here is a small example that I use 

swagger tofile --yaml --host https://mycustomhost --output swagger.yaml {path to the dll file} v1
