### ISSUE TITLE
Multiple files upload as [FromForm] binds to a null value in model

### ISSUE THREAD

**Issue by valentinburk** [domaindrivendev/Swashbuckle.AspNetCore#1369]
In version **5.0.0-rc4** in .**NET Core 3.0** project it is impossible to upload files collection with **Swagger UI** whereas it is still possible to do using **Postman**.

I tried different types of collections:
1. `IFormFile[]`
2. `List<IFormFile>`
3. `IEnumerable<IFormFile>`

Results are all the same.

### Controller class:
```csharp
[Route("api/file")]
public sealed class FileController : ControllerBase
{
	[HttpPost]
	public IActionResult Post([FromForm]RequestModel model)
	{
		return Ok();
	}
}
```

### Model class:
```csharp
public sealed class RequestModel
{
	public IFormFile[] Files { get; set; }
}
```

### Swagger UI

![image](https://user-images.githubusercontent.com/20153112/68776377-03865e80-0641-11ea-9bfe-c48de236ea64.png)

### Result

![image](https://user-images.githubusercontent.com/20153112/68776440-20229680-0641-11ea-9129-4fe18f641fcd.png)

### Same request in Postman

![image](https://user-images.githubusercontent.com/20153112/68776672-8ad3d200-0641-11ea-96ab-4981570a0a58.png)

### Postman result

![image](https://user-images.githubusercontent.com/20153112/68776802-b951ad00-0641-11ea-802d-3895fc2a5c40.png)

**Comment by domaindrivendev** [comment]
Closing as I believe this is a dup of #1029

**Comment by sshrishi** [comment]
![Drop](https://user-images.githubusercontent.com/45084929/85600602-3949e780-b613-11ea-96b8-9c6e90893aa4.jpg)
![photo-1494548162494-384bba4ab999](https://user-images.githubusercontent.com/45084929/85600618-3bac4180-b613-11ea-99a1-40bb05b01a18.jpg)
