### ISSUE TITLE
QueryString select components in SwaggerUI are disabled for boolean parameters

### ISSUE THREAD

**Issue by parekhkb** [domaindrivendev/Swashbuckle.AspNetCore#1370]
We've upgraded to AspNetCore 3.0 and Swashbuckle.AspNetCore 5.0.0-rc4 in our test environments.

We've noticed the following issue. When trying out endpoints, the queryString select components for booleans are disabled. The Select components for enum queryStrings are enabled and work fine, but for booleans they're disabled.

![image](https://user-images.githubusercontent.com/5116394/68816679-0169d300-0634-11ea-90a8-a5d9dd95f1c7.png)

**Comment by domaindrivendev** [comment]
I can't repro this. Have you clicked the "Try it out" button - all fields are disabled until you do that

**Comment by parekhkb** [comment]
Yes that is what I am referring to. 

One thing that might be unique to my setup is that the route takes a composite object from the queryStrings:

```
[HttpGet]
public async Task<ActionResult<PagedList<UserBasicDto>>> QueryUsers(                                                                                [FromQuery] UserQueryStrings queryParams){
...
}

...

public class UserQueryStrings : QueryStringsBase {
        [FromQuery]
        public override bool IncludeTotals
        {
            get => base.IncludeTotals;
            set => base.IncludeTotals = value;
        }
       ...
}
```

**Comment by parekhkb** [comment]
Thanks. Yes I had not clicked "Try it Out", I had thought I had since the Enum drop downs were selectable. 

It's still strange to me that the Enum examples are selectable but the bool examples are not. Either way this is not an issue.
