### ISSUE TITLE
migrate UploadFileFilter from previouse version

### ISSUE THREAD

**Issue by egorowp** [domaindrivendev/Swashbuckle.AspNetCore#1376]
Hello
I use asp.net core 3.0 with Swashbuckle.AspNetCore package to 5.0.0-RC4
How can I implement UploadFileFilter. Previous implementation don't work.
[https://stackoverflow.com/questions/58809344/swashbuckle-aspnetcore-5-0-0-rc4-uploadfilefilter-doesnt-work](https://stackoverflow.com/questions/58809344/swashbuckle-aspnetcore-5-0-0-rc4-uploadfilefilter-doesnt-work)

**Comment by iamzly** [comment]
> 您好，
> 我将Asp.net core 3.0与Swashbuckle.AspNetCore软件包一起使用到5.0.0-RC4，
> 如何实现UploadFileFilter。先前的实现无效。
> https://stackoverflow.com/questions/58809344/swashbuckle-aspnetcore-5-0-0-rc4-uploadfilefilter-doesnt-work

### **添加一个属性文件AddSwaggerFileUploadButtonAttribute.cs**

`using System;

namespace SwashbuckleApplication.WebCommen.Filter
{
    [AttributeUsage(AttributeTargets.Method)]
    public class AddSwaggerFileUploadButtonAttribute : Attribute
    {
    }
}`

### **然后添加过滤器文件AddFileParamTypesOperationFilter.cs**

`using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Collections.Generic;
using System.Linq;

namespace SwashbuckleApplication.WebCommen.Filter
{
    public class AddFileParamTypesOperationFilter : IOperationFilter
    {
        private static readonly string[] fileParameters = new[] { "ContentType", "ContentDisposition", "Headers", "Length", "Name", "FileName" };
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var operationHasFileUploadButton = context.MethodInfo.GetCustomAttributes(true).OfType<AddSwaggerFileUploadButtonAttribute>().Any();

            if (!operationHasFileUploadButton)
            {
                return;
            }
            RemoveExistingFileParameters(operation.Parameters);
            operation.RequestBody = new OpenApiRequestBody()
            {
                Content =
                    {
                        ["multipart/form-data"] = new OpenApiMediaType()
                        {
                            Schema = new OpenApiSchema()
                            {
                                Type = "object",
                                Properties =
                                {
                                    ["file"] = new OpenApiSchema()
                                    {
                                        Description = "Select file", Type = "string", Format = "binary"
                                    }
                                }
                            }
                        }
                    }
            };

        }

        private void RemoveExistingFileParameters(IList<OpenApiParameter> operationParameters)
        {
            foreach (var parameter in operationParameters.Where(p => p.In == 0 && fileParameters.Contains(p.Name)).ToList())
            {
                operationParameters.Remove(parameter);
            }
        }
    }

}
`
### **接着添加代码**

` c.OperationFilter<AddFileParamTypesOperationFilter>();`

### **最后在控制器里使用**

`        [HttpPost]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesDefaultResponseType]
        [AddSwaggerFileUploadButton]
        public IActionResult UploadFile([FromForm]IFormFile file=null)
        {
            return Content("ok");
        }`

**Comment by iamzly** [comment]
> Hello
> I use asp.net core 3.0 with Swashbuckle.AspNetCore package to 5.0.0-RC4
> How can I implement UploadFileFilter. Previous implementation don't work.
> https://stackoverflow.com/questions/58809344/swashbuckle-aspnetcore-5-0-0-rc4-uploadfilefilter-doesnt-work



> Hello
> I use asp.net core 3.0 with Swashbuckle.AspNetCore package to 5.0.0-RC4
> How can I implement UploadFileFilter. Previous implementation don't work.
> https://stackoverflow.com/questions/58809344/swashbuckle-aspnetcore-5-0-0-rc4-uploadfilefilter-doesnt-work

> 您好，
> 我将Asp.net core 3.0与Swashbuckle.AspNetCore软件包一起使用到5.0.0-RC4，
> 如何实现UploadFileFilter。先前的实现无效。
> https://stackoverflow.com/questions/58809344/swashbuckle-aspnetcore-5-0-0-rc4-uploadfilefilter-doesnt-work

### **添加一个属性文件AddSwaggerFileUploadButtonAttribute.cs**

`using System;

namespace SwashbuckleApplication.WebCommen.Filter
{
    [AttributeUsage(AttributeTargets.Method)]
    public class AddSwaggerFileUploadButtonAttribute : Attribute
    {
    }
}`

### **然后添加过滤器文件AddFileParamTypesOperationFilter.cs**

`using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Collections.Generic;
using System.Linq;

namespace SwashbuckleApplication.WebCommen.Filter
{
    public class AddFileParamTypesOperationFilter : IOperationFilter
    {
        private static readonly string[] fileParameters = new[] { "ContentType", "ContentDisposition", "Headers", "Length", "Name", "FileName" };
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var operationHasFileUploadButton = context.MethodInfo.GetCustomAttributes(true).OfType<AddSwaggerFileUploadButtonAttribute>().Any();

            if (!operationHasFileUploadButton)
            {
                return;
            }
            RemoveExistingFileParameters(operation.Parameters);
            operation.RequestBody = new OpenApiRequestBody()
            {
                Content =
                    {
                        ["multipart/form-data"] = new OpenApiMediaType()
                        {
                            Schema = new OpenApiSchema()
                            {
                                Type = "object",
                                Properties =
                                {
                                    ["file"] = new OpenApiSchema()
                                    {
                                        Description = "Select file", Type = "string", Format = "binary"
                                    }
                                }
                            }
                        }
                    }
            };

        }

        private void RemoveExistingFileParameters(IList<OpenApiParameter> operationParameters)
        {
            foreach (var parameter in operationParameters.Where(p => p.In == 0 && fileParameters.Contains(p.Name)).ToList())
            {
                operationParameters.Remove(parameter);
            }
        }
    }

}
`
### **接着添加代码**

` c.OperationFilter<AddFileParamTypesOperationFilter>();`

### **最后在控制器里使用**

`        [HttpPost]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesDefaultResponseType]
        [AddSwaggerFileUploadButton]
        public IActionResult UploadFile([FromForm]IFormFile file=null)
        {
            return Content("ok");
        }`

**Comment by iamzly** [comment]
> Hello
> I use asp.net core 3.0 with Swashbuckle.AspNetCore package to 5.0.0-RC4
> How can I implement UploadFileFilter. Previous implementation don't work.
> https://stackoverflow.com/questions/58809344/swashbuckle-aspnetcore-5-0-0-rc4-uploadfilefilter-doesnt-work

### **添加一个属性文件AddSwaggerFileUploadButtonAttribute.cs**

```
using System;

namespace SwashbuckleApplication.WebCommen.Filter
{
    [AttributeUsage(AttributeTargets.Method)]
    public class AddSwaggerFileUploadButtonAttribute : Attribute
    {
    }
}
```

### **然后添加过滤器文件AddFileParamTypesOperationFilter.cs**

```
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Collections.Generic;
using System.Linq;

namespace SwashbuckleApplication.WebCommen.Filter
{
    public class AddFileParamTypesOperationFilter : IOperationFilter
    {
        private static readonly string[] fileParameters = new[] { "ContentType", "ContentDisposition", "Headers", "Length", "Name", "FileName" };
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var operationHasFileUploadButton = context.MethodInfo.GetCustomAttributes(true).OfType<AddSwaggerFileUploadButtonAttribute>().Any();

            if (!operationHasFileUploadButton)
            {
                return;
            }
            RemoveExistingFileParameters(operation.Parameters);
            operation.RequestBody = new OpenApiRequestBody()
            {
                Content =
                    {
                        ["multipart/form-data"] = new OpenApiMediaType()
                        {
                            Schema = new OpenApiSchema()
                            {
                                Type = "object",
                                Properties =
                                {
                                    ["file"] = new OpenApiSchema()
                                    {
                                        Description = "Select file", Type = "string", Format = "binary"
                                    }
                                }
                            }
                        }
                    }
            };

        }

        private void RemoveExistingFileParameters(IList<OpenApiParameter> operationParameters)
        {
            foreach (var parameter in operationParameters.Where(p => p.In == 0 && fileParameters.Contains(p.Name)).ToList())
            {
                operationParameters.Remove(parameter);
            }
        }
    }

}
```
### **接着添加代码**

``` 
c.OperationFilter<AddFileParamTypesOperationFilter>();
```

### **最后在控制器里使用**

```       
[HttpPost]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesDefaultResponseType]
        [AddSwaggerFileUploadButton]
        public IActionResult UploadFile([FromForm]IFormFile file=null)
        {
            return Content("ok");
        }
```

**Comment by domaindrivendev** [comment]
In 5.0.0-rc4, support for `IFormFile`, `IFormFileCollection`, `FileResult` etc. is supported out-of-the-box so no need for the filter at all.

Also, for best results, I would omit the `[FromForm]` attribute. It's not necessary as ASP.NET Core automatically infers the binding source from the type, and it also causes some problems for `ApiExplorer`, the ASP.NET Core metadata component that Swashbuckle is  built on top of. See #1348 for more details on that.
