### ISSUE TITLE
Empty response objects don't have empty `properties` value anymore

### ISSUE THREAD

**Issue by eimantas** [domaindrivendev/Swashbuckle.AspNetCore#1381]
Context: I have a service that uses swagger and generates OASv2 json output (.net core 2.2, swagger 4.0). On that I wrote my api spec parser that generates client code for my project. There are cases where requests generate an empty response. And definitions for those responses have empty `properties` objects:

```json
"EmptyResponse": {
    "type": "object",
    "properties": {}
},
```

Now I'd like to use the same code generator for another project that runs on .net core 3.0 and swagger 5.0.0-rc4. I serialize the spec as V2 using the code the README.md:

```csharp
app.UseSwagger(c => 
{
    c.SerializeAsV2 = true;
});
```

The problem is that empty response objects, when serialized, do not contain empty `properties`. I'd like to avoid changing the code in my generator so I was wondering if there is any config flag that emits empty json object when the definition doesn't contain any properties.

The .net 3/swagger 5.0.0-rc4 empty response definition looks like this:

```json
"EmptyResponse": {
    "type": "object",
},
```

**Comment by domaindrivendev** [comment]
There's no config flag but I just tested with the latest version (`5.6.3`) and don't see the empty `properties` field being emitted.

**Comment by domaindrivendev** [comment]
There's no config flag for this and the generated swagger is perfectly valid - no plans to support this feature unfortunately.
