### ISSUE TITLE
Protobuf repeated fields not displayed in payload

### ISSUE THREAD

**Issue by EvanTsiatsios** [domaindrivendev/Swashbuckle.AspNetCore#1382]
Hi, our API utilizes protobuf for communication (serialized to JSON and back appropriately). For some weird reason if a protobuf field is listed as repeated it does not show up in the payload tab. Schema and Responses pick it up just fine, it is only missing from the payloads. This occurs for the POST methods. Is this expected behavior? 

Steps to reproduce:

1. Create a protobuf file that utilizes repeated fields.
2. Generate the appropriate class.
3. Create a controller with a public method attributed as POST and add a [FromBody] tag directly expecting a type of your instantiate protobuf class. 
4. Run the swagger server and notice at the payload, it should be missing all repeated fields.

If you need more information please let me know.

**Comment by EvanTsiatsios** [comment]
Temporary workaround that I found:
https://stackoverflow.com/questions/41005730/how-to-configure-swashbuckle-to-ignore-property-on-model

It would be nice if this was addressed by default, but if anyone stumbles upon this, above is the solution I used.

**Comment by MichaelLiss** [comment]
experiencing the same thing - no repeated values

**Comment by Havret** [comment]
The problem is because repeated fields in generated objects do no have getters. As such they are treated as read only and ignored for the schemas of the input contract. You can apply a simple workaround to include them.

```csharp
internal class ProtobufSchemaFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        if (context.Type.IsAssignableTo(typeof(IMessage)))
        {
            foreach (var openApiSchema in schema.Properties)
            {
                if (openApiSchema.Value.Type == "array")
                {
                    openApiSchema.Value.ReadOnly = false;
                }
            }
        }
    }
}
```

And then register custom schema filter.

```csharp
services.AddSwaggerGen(options =>
{
    options.SchemaFilter<ProtobufSchemaFilter>();
});
```

**Comment by ktkk** [comment]
This might be a bit off topic, but I'm also having some problems with protobuf repeated fields in ASP.NET Core actions.
The previous answer actually remedied part of the problem, which is that these fields weren't even showing up in Swagger, so thanks for that. :)

However, my main problem is that I cannot assign these repeated fields from Swagger. If I fill in the array in JSON, my model just recieves an empty RepeatedField property.

Does anyone have an idea how I can fix this? Thanks!

**Comment by Havret** [comment]
Hi @ktkk, if you are using System.Text.Json this package will help with that https://github.com/Havret/Protobuf.System.Text.Json.

**Comment by martincostello** [comment]
Closing as there are workarounds and I do t think we would want to depend on Protobuf packages to implement them in-box.
