### ISSUE TITLE
How to hide client_id and client_secret on Available authorizations dialog?

### ISSUE THREAD

**Issue by patricknolan** [domaindrivendev/Swashbuckle.AspNetCore#1383]
Hi,

I'm allowing customers to access my SaaS API via Swashbuckle. They are required to authenticate using OAuth via the Available authorizations popup. When they click the Authorize button via the popup they are required to authenticate via gmail. However, this shows the Auth0 client_id and client_secret SwashBuckle uses which I need hidden from the end user.

Is there a way for this to be hidden?

I've attached a screenshot to this issue.

![authorizations](https://user-images.githubusercontent.com/21054590/69192020-732fa880-0b6f-11ea-8cd9-77bc539be9f8.png)

**Comment by domaindrivendev** [comment]
This is a question for the [swagger-ui folks](https://github.com/swagger-api/swagger-ui) rather than SB.

**Comment by martincostello** [comment]
Closing as external.
