### ISSUE TITLE
Filter with parameter null on Constructor

### ISSUE THREAD

**Issue by MarcoGix** [domaindrivendev/Swashbuckle.AspNetCore#1384]
Hi,

I found this issue calling a DocumentFilter (probably same on other filters).

	public class TestFilter : IDocumentFilter
	{
		private readonly string _param1;
		private readonly int _param2;

		public TestFilter(string param1, int param2)
		{
			_param1 = param1;
			_param2 = param2;
		}

		public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
		{

		}
	}

When I call it by

	services.ConfigureSwaggerGen(c =>
	{
		c.DocumentFilter<TestFilter>(null, 1);
	});

if I pass the param1 as in the snippet, as null, I receive the following error:
**_"A suitable constructor for type 'XXX.TestFilter' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor."_**

Passing a not null string, everything works fine.

Let me know if you have everything to replicate this issue.

Thanks,
Marco Giannotti

**Comment by martincostello** [comment]
`DocumentFilter<T>` takes an argument of `object[] arguments` and this later calls `ActivatorUtilities.CreateInstance()` to create the instance of `T`.

With your usage, it's looking for a constructor with the signature `(object, int)`, which doesn't exist.

The fix in this case would be to explicitly pass the parameter as a string or cast the null.

```csharp
services.ConfigureSwaggerGen(c =>
{
    c.DocumentFilter<TestFilter>((string)null, 1);
});

// or
services.ConfigureSwaggerGen(c =>
{
    string param1 = null;
    c.DocumentFilter<TestFilter>(param1, 1);
});
```
