### ISSUE TITLE
405 occurs when grpc is enabled

### ISSUE THREAD

**Issue by alefcarlos** [domaindrivendev/Swashbuckle.AspNetCore#1385]
## Versions
Version: 5.0.0-rc4
Redoc Version: 5.0.0-rc4

## Problem

When `services.AddGrpc()` is added in DI Container this error occurs when I access the UI, while others routes is working.

![image](https://user-images.githubusercontent.com/5452336/69267387-cde6f580-0bab-11ea-8aad-7ba17df744d3.png)

**Comment by jpseini** [comment]
@alefcarlos - did you ever manage to resolve this? I am running into the same/similar issue.

As soon as I add Grpc to my solution then my swagger page (swagger/index.html) no longer works and gives me a 405 error. If I remove the MapGrpcService<> call, then the page loads without any issue (even if I keep the AddGrpc() method)

**Comment by alefcarlos** [comment]
@jpseini this isn't possible because of http2. There are 2 solutions:

1 - add grpc server in another port using hosted services
2 - create separated projects for http and grpc server.

I chose the second one.

David Fowler made an example using both in same project: https://github.com/alefcarlos/gRPCSamples/tree/master/KestrelHostedWithinIIS
