### ISSUE TITLE
[FromQuery] list of complex object is null

### ISSUE THREAD

**Issue by egorowp** [domaindrivendev/Swashbuckle.AspNetCore#1391]
Hello. 
Asp.Net core 3. Swashbuckle.AspNetCore 5.0.0-rc4
[FromQuery] list of complex object return null

**Comment by domaindrivendev** [comment]
Closing as there's not nearly enough info. If this is still an issue for you, please provide clear repro steps, sample code, actual vs expected results and then re-open.
