### ISSUE TITLE
Bug with virtual directories and IIS

### ISSUE THREAD

**Issue by ovebastiansen** [domaindrivendev/Swashbuckle.AspNetCore#1392]
Hi,

Using "Swashbuckle.AspNetCore" Version="5.0.0-rc4" and netcoreapp2.2
According to the documentation, and it is working for v4, but it is broken in v5. I am hosting a api on a virtual directory in IIS, and using ./ works locally and with deployed v4 but not deployed v5.

Current config:
app.UseSwagger(config =>
            {
                config.SerializeAsV2 = true;
                config.RouteTemplate = "/docs/{documentName}/swagger.json";
            });
            app.UseSwaggerUI(config =>
            {
                config.SwaggerEndpoint("./v1/swagger.json", "API v1");
                config.RoutePrefix = "docs";
            });

This works locally against
http://localhost:port/docs/index.html
But deployed it does not work.
https://publicaddress/api/docs/index.html

Docs:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio
"If using directories with IIS or a reverse proxy, set the Swagger endpoint to a relative path using the ./ prefix. For example, ./swagger/v1/swagger.json. Using /swagger/v1/swagger.json instructs the app to look for the JSON file at the true root of the URL (plus the route prefix, if used). For example, use http://localhost:<port>/<route_prefix>/swagger/v1/swagger.json instead of http://localhost:<port>/<virtual_directory>/<route_prefix>/swagger/v1/swagger.json."

**Comment by lukos** [comment]
This is broken for me too. 

If I use /swagger or ./swagger then it works locally but not when deployed behind IIS (the swagger UI appears but says it cannot find swagger.json). If I try ../ which someone else suggested, it doesn't work in either place.

At the moment, this makes it unusable for AspNet Core 3.1 running on IIS.

**Comment by idseefeld** [comment]
For the following configuration worked for a virtual directory `api`:
```
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/api/swagger/v1/swagger.json", "Telemed.Identity User API V1");
});
```
Maybe it makes sense to use an `appSetting ` for the path segment. Otherwise debugging in Visual Studio will not work.
KR

**Comment by domaindrivendev** [comment]
To work best virtual dir/reverse proxy environments, you should specify a `SwaggerEndpoint` that's _relative to the Swagger UI page itself. So, if you have ...

`/docs/v1/swagger.json` for the Swagger JSON
`/docs/index.html` for the Swagger UI page

Then, you should set the `SwaggerEndpoint` as follows:

```csharp
c.SwaggerEndpoint("v1/swagger.json", API v1");
```

This works!

**Comment by IsaaacD** [comment]
@domaindrivendev Could you elaborate on your working example please? I'm having issues but I'm not sure what you mean to setup Swagger UI page. This is what I have so far and it's not working with my virtual directory and I'm not sure what to try next:
```
            var basePath = Configuration["AppSettings:VirtualDirectory"];
            app.UseSwagger(c =>
            {
                c.RouteTemplate = basePath + "/swagger/{documentName}/swagger.json";
                c.PreSerializeFilters.Add((swaggerDoc, httpReq) =>
                {
                    swaggerDoc.Servers = new List<OpenApiServer> { new OpenApiServer { Url = $"{httpReq.Scheme}://{httpReq.Host.Value}/{basePath}" } };
                });
            });

            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("swagger/v1/swagger.json", "Corporate Website API V1");                
                c.RoutePrefix = basePath;
                
            });
```

**Comment by domaindrivendev** [comment]
Consolidated into #1953
