### ISSUE TITLE
Unable to filter request models via attribute

### ISSUE THREAD

**Issue by DatBear** [domaindrivendev/Swashbuckle.AspNetCore#1399]
There is no clear way to ignore a complex object within a complex object bound from an API Operation parameter. For example, I have this controller method on an API controller:
```
public async Task<Player> CreatePlayerAccount(ApplicationUserManager userManager, CreatePlayerAccountPost model)
```

and in CreatePlayerAccountPost.cs I have this:
```
public class CreatePlayerAccountPost{
    public string Username { get; set; }
    public string Password { get; set; }
...
    public Facility HomeFacility { get; set; }
}
```

There is no way (that I can find, I've looked everywhere) to not have HomeFacility included in the generated UI / doc. I have tried using [JsonIgnore], [Obsolete], and even a custom attribute. The problem is that the schema filter filters only on response types, and the operation filters offer no way to exclude a complex type via an attribute, they expand the type into its properties before the operation filter gets hit so the whole property can't be ignored at once, every one of the target's properties/child properties/etc. would have to be ignored.

I have tried this Operation Filter Apply() method to get it to ignore properties with JsonIgnore, and then decorated the HomeFacility property with JsonIgnore attribute, but it expands the Facility object before it gets to the filter.
```
public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var parameters = context.ApiDescription.ParameterDescriptions
                //.Where(d => d.Source.Id == "Query")
                .ToList();

            parameters.ForEach(param => {
                var toIgnore = ((DefaultModelMetadata)param.ModelMetadata)?
                    .Attributes.PropertyAttributes
                    ?.Any(x => x is JsonIgnoreAttribute);

                var toRemove = operation.Parameters.SingleOrDefault(p => p.Name == param.Name);

                if(toIgnore ?? false)
                    operation.Parameters.Remove(toRemove);
            });
        }
```

**Comment by ngbrown** [comment]
I was able to ignore parameters this way:

```cs
public class IgnoreParametersOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        if (operation.Parameters.Count == 0)
        {
            return;
        }

        var excludedRootParameters = context.ApiDescription.ActionDescriptor.Parameters.SelectMany(
            pd => pd.ParameterType.GetProperties()
                .Where(CheckForJsonIgnore)
                .Select(p => p.Name));

        var parametersToRemove = excludedRootParameters.SelectMany(paramName => {
                string rootParamName = $"{paramName}.";
                return operation.Parameters.Where(p =>
                    !p.Required && (p.Name == paramName || p.Name.StartsWith(rootParamName)));
            })
            .ToList();

        foreach (OpenApiParameter apiParameter in parametersToRemove)
        {
            operation.Parameters.Remove(apiParameter);
        }
    }

    private static bool CheckForJsonIgnore(PropertyInfo p)
    {
        return p.GetCustomAttribute<JsonIgnoreAttribute>(true) != null
               || (p.DeclaringType?.GetInterfaces().Any(i =>
                       i.GetProperty(p.Name, p.PropertyType)?.GetCustomAttribute<JsonIgnoreAttribute>() != null)
                   ?? false);
    }
}
```

Put `[JsonIgnore]` on the property in the parameter object that you want ignored.

**Comment by domaindrivendev** [comment]
@DatBear custom filters are NOT necessary for this use case. Firstly, I've noticed that your models are not decorated with a source binding attribute (`[FromQuery]`, `[FromBody]` etc.) so Swashbuckle has no way of knowing which parameter type they should be bound to. In this case, it will default to describing them as query parameters, which from the name of the model I'm assuming isn't what you want. Furthermore, `JsonIgnore` will NOT be honored for query parameters because they have nothing to do with JSON. Also, it's not clear to me what your intention is with the `ApplicationUserManager` parameter - is this an actual API parameter too?

Assuming that your intention is for `CreatePlayerAccountPost` to represent the POST body, but with the `HomeFacility` property ignored. Then the following should work for you:

```csharp
public async Task<Player> CreatePlayerAccount([FromBody]CreatePlayerAccountPost model, [BindNever]ApplicationUserManager userManager)
{
    ...
}

public class CreatePlayerAccountPost
{
    ...
    [JsonIgnore]
    public Facility HomeFacility { get; set; }
}
```

**Comment by ngbrown** [comment]
Putting `[BindNever]` on a property that is complex (a class) does not remove it from the documentation.

For example, I have a parameter that is populated in the controller like this:

```cs
        /// <summary>
        /// Get channel by id
        /// </summary>
        [HttpGet("{id:int}")]
        [ProducesResponseType(typeof(Details.Result), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> Index(Domain.Features.Channels.Details.Query query, CancellationToken cancellationToken)
        {
            query.AuthenticatedUser = User;
            Details.Result model = await this.mediator.Send(query, cancellationToken);

            if (model == null) return NotFound();

            return Ok(model);
        }
```

The `Query` class:

```cs
        public class Query : IRequest<Result>
        {
            public int Id { get; set; }

            [BindNever]
            public IPrincipal AuthenticatedUser { get; set; }
        }
```

However, the documentation shows this:

![Screenshot - 2019-12-24_17-39-15](https://user-images.githubusercontent.com/228987/71427298-61f92080-2674-11ea-94c7-543f71b79952.png)

Also, the filter I showed would look at the interface for convenience sake.

Does that make sense?
