### ISSUE TITLE
[Feature Request] Auto Mark Obsolete Properties as Deprecated

### ISSUE THREAD

**Issue by chadsowald** [domaindrivendev/Swashbuckle.AspNetCore#1400]
Swashbuckle 5.x RC adds support for Open API v3, which includes support for marking properties as deprecated.  Can you please add automatic support for marking properties with the [Obsolete] attribute as deprecated in Swagger?  Swashbuckle already automatically does this for operations ([see here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/58d773a97a6041bdb5906c6a87c4ebbf9f90c7cc/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L139)). For now, I've done this with a schema filter like this:

```csharp
/// <summary>
/// Swashbuckle does not yet natively deprecate properties marked with Obsolete like it does operations.  Until then, we need something like this.
/// </summary>
internal class MarkObsoletePropsAsDeprecatedSchemaFilter : ISchemaFilter
{
    public void Apply( OpenApiSchema schema, SchemaFilterContext context )
    {
        var objectContext = context.ApiModel as ApiObject;
        if (objectContext == null)
            return;

        foreach (var prop in objectContext.ApiProperties)
        {
            if (prop.MemberInfo.CustomAttributes.Any( a => a.AttributeType.Name == nameof( ObsoleteAttribute ) ))
            {
                schema.Properties[ prop.ApiName ].Deprecated = true;
            }
        }
    }
}
```

Also, please let me know if there's an easier or existing way that I missed.

**Comment by domaindrivendev** [comment]
Added by a9b46a906b1e301d2ee3beedfb0d294a25bbff84

**Comment by prudnikovsg** [comment]
Hey guys!
And thank you so much for your hard work.

I have a small question.
Please tell me, if I understand correctly, you removed this functionality with this [commit](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/067394c6665fdf1520e1de1d6c7e6d553d94f340), right?
Are you not planning to support marking properties as obsolete at all or is there some other way to enable this functionality now?
