### ISSUE TITLE
if a ProducesResponseType attribute is defined, no documentation for status 200 is produced

### ISSUE THREAD

**Issue by jerchap** [domaindrivendev/Swashbuckle.AspNetCore#1402]
If I create an action, and do not decorate it with ProducesResponseType attributes, Swashbuckle will nicely generate documentation for Status code 200 and provide example & schema for the return type.

If I add a ProducesResponseType attribute a code other than Status200Ok (such as an error code), it no longer generates documentation for Status code 200 and I manually need to add an additional ProducesResponseType attribute for Status200Ok.  Why can it not continue to generate the documentation for Status200Ok by default without requiring the attribute?

**Comment by redoz** [comment]
@jerchap Well, if my endpoint only produces 204 and 404 statuses, I'd need an additional attribute to suppress the automatically generated 200 status-code.

Seems like the current setup provides a happy medium, define nothing and it assumes you'll return a 200, define something and you have to be specific about exactly what you return.

**Comment by jerchap** [comment]
Yes that is true.
