### ISSUE TITLE
Attribute for controller, endpoint, parameter descriptions

### ISSUE THREAD

**Issue by jerchap** [domaindrivendev/Swashbuckle.AspNetCore#1403]
Are there any attributes that can be used to decorate actions, controllers and parameters with so that descriptions for them appear on the swagger ui?  I see there is an option to map to the xml documentation, but I might want content in that documentation that is not intended for publishing to swagger.

**Comment by jerchap** [comment]
found the annotations package

**Comment by acclaimuser** [comment]
SwaggerUI is not respecting the annotations from this package. we can workaround with ProducesResponseType from Microsoft.AspNetCore.Mvc
