### ISSUE TITLE
Is there any way of mapping Flags to array of enums or byte?

### ISSUE THREAD

**Issue by vdurante** [domaindrivendev/Swashbuckle.AspNetCore#1404]
I've been trying to set up an API endpoint that has a `FlagsAttribute` enum as input, but Swashbuckle is mapping it to an Enum, instead of an Array or Bit sequence. Is there any alternative, solution or desire to implement such feature? Thanks.

**Comment by domaindrivendev** [comment]
For this type of customization, I would recommend the `MapType` setting to provide a custom schema for the enum in question.
