### ISSUE TITLE
 Request examples are not generated if serialize as V2

### ISSUE THREAD

**Issue by tmarkovski** [domaindrivendev/Swashbuckle.AspNetCore#1406]
VERSION:
5.0.0-rc4

STEPS TO REPRODUCE:

-  Add Examples filter (https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters)
-  `app.UseSwagger(c => { c.SerializeAsV2 = true; });`

EXPECTED RESULT:

Examples should show in the swagger doc
ACTUAL RESULT:

Examples don't show.
ADDITIONAL DETAILS

It works fine when not using `SerializeAsV2`

**Comment by ashishpathak2111** [comment]
facing same issue, any update on this?

**Comment by domaindrivendev** [comment]
I can't speak for the `Swahbuckle.AspNetCore.Filters` library as it's developed independently but I can confirm that, with `v5.6.0` of Swashbuckle, schema examples set via an `ISchemaFilter` works with and without the `SerializeAsV2` setting.

If you're still experiencing this issue, I would suggest creating an issue in the downstream repo.
