### ISSUE TITLE
New release 

### ISSUE THREAD

**Issue by TimmyGilissen** [domaindrivendev/Swashbuckle.AspNetCore#1408]
Hi,

I was wondering when the next release is planned.

One of the features that I created a pr for is merged to the existing codebase. 

When the new release is availible we can update our build pipeline with the new swashbuckle tool.

Timmy

**Comment by msjonathan** [comment]
Indeed, it would be great to have a estimated release date - currently we are holding back the upgrade to 3.1 until 5.0 is released 👍

**Comment by MuiBienCarlota** [comment]
The only remaining issue before 5.0 is this one.
Can we hope to be very close to a next exit?
I really need for a .Net Core 3.x version!

**Comment by domaindrivendev** [comment]
Finally ... `5.0.0` has just been shipped
