### ISSUE TITLE
Body Parameter upgrading to swashbuckle 5

### ISSUE THREAD

**Issue by white-label-development** [domaindrivendev/Swashbuckle.AspNetCore#1417]
We are upgrading to swashbuckle 5.0.0-rc4 and a previous operation filter from v4 is proving difficult to get working.

the old code is 
```
operation.Parameters.Add(new BodyParameter()); ...etc
```

The new `OpenApiParameter` doesn't accept a location of `Body` so can you advise how we would add a body parameter (it needs to take xml)

**Comment by domaindrivendev** [comment]
In Swagger/OpenAPI specification v3, Body parameters are separated from that collection to a specific field called `requestBody`. So to access this in your operation filter use `operation.RequestBody`
