### ISSUE TITLE
Support providing custom ISwaggerProvider registration

### ISSUE THREAD

**Issue by sverrirs** [domaindrivendev/Swashbuckle.AspNetCore#1423]
I was trying to implement the CustomProvider scenario to implement a SwaggerGenerator that would cache the swagger.json response after first generation.

This provided to be a little bit more involved than expected and I described my workaround in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/356#issuecomment-566449902

It seems though that this scenario can be more easily supported by changing the DI service registration to a `services.TryAddTransient(...)` in this line
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenServiceCollectionExtensions.cs#L29

The line would become
```
services.TryAddTransient<ISwaggerProvider, SwaggerGenerator>();
```

That way the user could register their own implementation of `ISwaggerProvider` with the container before calling the `services.AddSwaggerGen(...)` extension method and no special workaround would be needed.

**Comment by domaindrivendev** [comment]
What's the benefit of adding it _before_ vs after?

**Comment by sverrirs** [comment]
Hi Richard,

The fix in question is to change the SwaggerGen function to perform a `TryAddTransient` internally. That way a user can register their custom implementation with the DI container before calling the SwaggerGen function. What that gives us is greater level of customization since when the SwaggerGen tries to add its built in one the TryAdd... function would detect an already present implementation (the custom one) thus skipping the registration of its built-in (now it always overrides).

**Comment by domaindrivendev** [comment]
I understand the proposed change but unless I'm missing something the only tangible difference is around the positioning of the one-liner in `Startup.cs` to register the alternative `ISwaggerProvider`. That is, without your proposed change, this MUST be after the call to `AddSwaggerGen` whereas with it the line can be before or after. Or am I missing something here?

**Comment by sverrirs** [comment]
Yes, you are correct. However what is needed currently is to replace the already registered instance in the DI container. It is a more complicated function call. :)
