### ISSUE TITLE
Authorization Header not being sent from Swagger UI 5.0.0-rc5

### ISSUE THREAD

**Issue by VictorioBerra** [domaindrivendev/Swashbuckle.AspNetCore#1425]
Tried both the following solutions:

## https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1022

```csharp
                    options.AddSecurityDefinition("basicAuth", new OpenApiSecurityScheme
                    {
                        Type = SecuritySchemeType.Http,
                        Scheme = "Basic", // tried lowercase "basic" too.
                        Description = "Input your username and password to access this API",
                        In = ParameterLocation.Header,
                    });

                    options.AddSecurityRequirement(new OpenApiSecurityRequirement
                    {
                        {
                            new OpenApiSecurityScheme
                            {
                                Reference = new OpenApiReference {
                                    Type = ReferenceType.SecurityScheme,
                                    Id = "basicAuth" }
                            }, new List<string>() }
                    });
```

## https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1171

```csharp
                    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
                    {
                        Description = "JWT Authorization header using the Bearer scheme.",
                        Name = "Authorization",
                        In = ParameterLocation.Header,
                        Scheme = "bearer",
                        Type = SecuritySchemeType.Http,
                        BearerFormat = "JWT"
                    });

                    options.AddSecurityRequirement(new OpenApiSecurityRequirement
                    {
                        {
                            new OpenApiSecurityScheme
                            {
                                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
                            },
                            new List<string>()
                        }
                    });
```

I need basic auth, and I am willing to settle for making the user put the encoded final header in. Ideally, they would be prompted for a username and password and that could automatically be encoded.

**Comment by handsome-b-wonderful** [comment]
I'm also experiencing the same issue where the UI is not adding the authorization header.

I'm using token authentication that is applied conditionally based on attrbiutes of my controller, but with very similar code in an IOperationFilter:


```Csharp

               operation.Parameters.Add(new OpenApiParameter
                {
                    Name = "Authorization",
                    In = ParameterLocation.Header,
                    Description = "[Your Token]",
                    Required = true,
                    Schema = new OpenApiSchema { Type = "string" },
                });

                operation.Responses.Add("401", new OpenApiResponse { Description = "Unauthorized" });
                operation.Responses.Add("403", new OpenApiResponse { Description = "Forbidden" });

                operation.Security = new List<OpenApiSecurityRequirement>
                {
                    new OpenApiSecurityRequirement()
                        {
                             {
                                new OpenApiSecurityScheme
                                {
                                    Description = "Adds token to header",
                                    Name = "Authorization",
                                    Type = SecuritySchemeType.Http,
                                    In = ParameterLocation.Header,
                                    Scheme = "bearer",
                                    Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
                                },
                                new List<string>()
                            }
                    }
                };
```

The UI is generated correctly but the header is not added to the request.

using 5.0.0-rc5

**Comment by gorkemyontem** [comment]
Really need a working example for bearer token.

**Comment by VictorioBerra** [comment]
@gorkemyontem at this point I'm thinking that's not going to happen without a PR.

**Comment by domaindrivendev** [comment]
The following example works for me (including automatic encoding of credentials). It's worth noting that this type of question is related to understanding the Swagger specification, and how to express certain API behaviors with it, as opposed to Swashbuckle itself. When this is the case, I would encourage people to look at the Swagger documents (e.g. [authentication examples](https://swagger.io/docs/specification/authentication/)) instead as they contain many examples which can be easily ported over to Swashbuckle configuration.

A working example for basic Auth (derived from the Swagger docs)

```csharp
c.AddSecurityDefinition("basicAuth", new OpenApiSecurityScheme
{
    Type = SecuritySchemeType.Http
    Scheme = "basic"
});

c.AddSecurityRequirement(new OpenApiSecurityRequirement
{
    {
        new OpenApiSecurityScheme
        {
            Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "basicAuth" }
        },
        new string[]{}
    }
});
```

**Comment by VictorioBerra** [comment]
@domaindrivendev That did not work.

## Click authorize

![image](https://user-images.githubusercontent.com/2934507/71733570-8ccf3b80-2e0f-11ea-8e82-ddb6fdfbc343.png)

## Fill out info and click the authorize button

![image](https://user-images.githubusercontent.com/2934507/71733609-a7091980-2e0f-11ea-8eba-37ad108f791b.png)

## Expand an operation

![image](https://user-images.githubusercontent.com/2934507/71733685-c607ab80-2e0f-11ea-9b34-81bc06de3b14.png)

## Click "Try it out"

![image](https://user-images.githubusercontent.com/2934507/71733727-dae43f00-2e0f-11ea-8ab8-a25868ae5c93.png)

## Click "Execute"

![image](https://user-images.githubusercontent.com/2934507/71733777-f9e2d100-2e0f-11ea-8de3-1de3e14850d1.png)

## 401! And there is no "Authorize" header in the request payload.

![image](https://user-images.githubusercontent.com/2934507/71733905-46c6a780-2e10-11ea-85fc-0d2dfc9cc0f5.png)

> It's worth noting that this type of question is related to understanding the Swagger specification, and how to express certain API behaviors with it, as opposed to Swashbuckle itself

But Swashbuckle needs to understand the Swagger body to make use of it in the UI does it not? How else does the UI know to create Auth headers, and encode parameters?

**Comment by pnavk** [comment]
**Don't use parameters** to accomplish this as it is **no longer supported by Swagger UI**. To get the Authorization header included the curl request you must define it entirely using security schemes. For reference see [this comment ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1295#issuecomment-540143783)

Want to share my configuration that works on 5.0.0-rc5:

**In Startup.cs, add a global _Security Definition_ and operation filter:**
```
services.AddSwaggerGen(opt =>
{
	opt.SwaggerDoc("v1", new OpenApiInfo { Title = "My Api", Version = "v1" });
	opt.AddSecurityDefinition("bearer", new OpenApiSecurityScheme
	{
		Type = SecuritySchemeType.Http,
		BearerFormat = "JWT",
		In = ParameterLocation.Header,
		Scheme = "bearer"
	});
	opt.OperationFilter<AuthenticationRequirementsOperationFilter>();
});
```
In the **AuthenticationRequirementsOperationFilter** add a _Security Requirement_ to the operation by referencing the _Security Definition_ that was added globally:

```
public class AuthenticationRequirementsOperationFilter : IOperationFilter
{
	public void Apply(OpenApiOperation operation, OperationFilterContext context)
	{
		if (operation.Security == null)
			operation.Security = new List<OpenApiSecurityRequirement>();


		var scheme = new OpenApiSecurityScheme { Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "bearer" } };
		operation.Security.Add(new OpenApiSecurityRequirement
		{
			[scheme] = new List<string>()
		});
	}
}
```
**Note:**

- The Id value "bearer" matches what was passed as the first parameter to AddSecurityDefinition in Startup.cs
- This example adds the security requirement to ALL endpoints. Typically, filtering logic will be included to only add the security requirement to endpoints that need it.

The generated UI won't have Authorization fields in each endpoint. There should be open locks on the endpoints that had a security requirement added to them in the OperationFilter and an Authorize button should show up on the top right. Add the token to the header using the Authorize button and the endpoints will show with closed locks. **Note: "Bearer" will be added automatically, so only provide the token when authorizing.**

<img width="493" alt="Screen Shot 2020-01-07 at 11 23 07 PM" src="https://user-images.githubusercontent.com/10317382/71958497-4c701480-31a5-11ea-91da-5b04f153458c.png">

Requests should now include the Authorization header with the provided token. You can verify in the curl:

<img width="1087" alt="Screen Shot 2020-01-07 at 11 24 51 PM" src="https://user-images.githubusercontent.com/10317382/71958708-c99b8980-31a5-11ea-85c9-097945a96b1b.png">

Hope it helps!

**Comment by VictorioBerra** [comment]
@pnavk Thank's you led me to the solution **which was that I had** `options.OperationFilter<SecurityRequirementsOperationFilter>()` **in my startup.cs!** This was overriding anything I did thanks to this https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/master/src/Swashbuckle.AspNetCore.Filters/SecurityRequirementsOperationFilter/SecurityRequirementsOperationFilter.cs#L20

Similar one here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/OAuth2Integration/ResourceServer/Swagger/SecurityRequirementsOperationFilter.cs#L27

All I had to do was add the following to my `AddSwaggerGen` and the problem was solved.

```csharp
options.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
{
    Type = SecuritySchemeType.Http,
    Scheme = "basic"
});
```

The key here being `"oauth2"` since that references the hardcoded `OpenApiScheme.OpenApiReference`.

**Comment by handsome-b-wonderful** [comment]
> 
> 
> Really need a working example for bearer token.

This is working for me under 5.0.0-rc5:

In Startup.cs in ConfigureServices:


```C#
services.AddSwaggerGen(options =>
            {
                options.AddSecurityDefinition("bearer", new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.Http,
                    BearerFormat = "JWT",
                    In = ParameterLocation.Header,
                    Scheme = "bearer"
                });


                // add auth header for [Authorize] endpoints
                options.OperationFilter<AddAuthHeaderOperationFilter>();
```

```
public class AddAuthHeaderOperationFilter : IOperationFilter
    {

        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
               if (operation.Security == null)
                    operation.Security = new List<OpenApiSecurityRequirement>();


                var scheme = new OpenApiSecurityScheme { Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "bearer" } };
                operation.Security.Add(new OpenApiSecurityRequirement
                {
                    [scheme] = new List<string>()
                });
        }
    }
```

__NOTE:__ I filter on 
* controllers that have an `[Authorize]` attribute 
* do not have `[AllowAnonymous]` method attributes.

in `AddAuthHeaderOperationFilter` - code removed for clarity.

**Comment by 11kodykay11** [comment]
For those who are still having trouble with this, here is the code that worked for me after few hours of trial and error.
```
services.AddSwaggerGen(c =>
            {                
                c.AddSecurityDefinition("Basic", new OpenApiSecurityScheme
                {
                    Name = "Basic",
                    Description = "Please enter your username and password",
                    Type = SecuritySchemeType.Http,
                    Scheme = "basic", //This is were it was not working for me. I was using uppercase B
                    In = ParameterLocation.Header
                });

`               c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference {
                                Type = ReferenceType.SecurityScheme,
                                Id = "Basic" }
                        }, new List<string>() 
                    }
                });
        }
```

**Comment by zscao** [comment]
The options below working with Bearer scheme for me:

                c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
                {
                    Description = "JWT Authorization header using the Bearer scheme.",
                    Name = "Authorization",
                    In = ParameterLocation.Header,
                    Type = SecuritySchemeType.ApiKey,
                    Scheme = "bearer"
                });

                c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "Bearer"
                            }
                        }, new List<string>()
                    }
                });

**Comment by davidbuckleyni** [comment]
I am having the same issue for me but for me its addding the token but getting 401 unauthorised from the controller if i remove the dataannotation it works fine.

```
services.AddSwaggerGen(c =>
{

            c.SwaggerDoc("v1", new OpenApiInfo { Title = "App Manager - Running Buddies", Version = "v1" });

            c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme {
                Description = "JWT Authorization header using the Bearer scheme.",
                Name = "Authorization",
                In = ParameterLocation.Header,
                Type = SecuritySchemeType.ApiKey,
                Scheme = "bearer"
            });

            c.AddSecurityRequirement(new OpenApiSecurityRequirement
            {
            {
                new OpenApiSecurityScheme
                {
                    Reference = new OpenApiReference
                    {
                        Type = ReferenceType.SecurityScheme,
                        Id = "Bearer"
                    }
                }, new List<string>()
            }
        });
   });
```
```
        [AllowAnonymous]
        [HttpPost]
        public IActionResult CreateToken([FromBody] LoginModel login) {

            IActionResult response = Unauthorized();
            var user = Authenticate(login);

            if (user != null) {
                var tokenString = BuildToken(login);
                response = Ok(new { token = tokenString });
            }

            return response;

        }


        private string BuildToken(LoginModel login) {
            var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config["JwtToken:SecretKey"]));
            var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);
            JwtSecurityToken token;
            
                token = new JwtSecurityToken(_config["JwtToken:Issuer"],
              _config["JwtToken:Issuer"], expires: DateTime.Now.AddMinutes(30),
              signingCredentials: creds); 
            return new JwtSecurityTokenHandler().WriteToken(token);

        }


        private UserModel Authenticate(LoginModel login) {
            UserModel user = null;
            //var result = await _signInManager.PasswordSignInAsync(, lockoutOnFailure: false);
            if (login.Username == "mario" && login.Password == "secret") {
                user = new UserModel { UserName = "Mario Rossi", Email = "mario.rossi@domain.com" };
            }
            return user;
        }
```

My Bmi Controler

```
namespace AppManagerApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
   [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class BmiInformationsController : ControllerBase
    {
        private readonly AppManagerDBContext _context;

        public BmiInformationsController(AppManagerDBContext context)
        {
            _context = context;
        }

        // GET: api/BmiInformations
        [HttpGet]
        public async Task<ActionResult<IEnumerable<BmiInformation>>> GetBmiInformation()
        {
            return await _context.BmiInformation.ToListAsync();
        }
}```

Please help this is driving me nuts

**Comment by ceemafour** [comment]
I think the issue here (from the [documentation](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-indexhtml) ): 

_NOTE: In addition to defining a scheme, you also need to indicate which operations that scheme is applicable to. You can apply schemes globally (i.e. to ALL operations) through the AddSecurityRequirement method. The example below indicates that the scheme called "oauth2" should be applied to all operations, and that the "readAccess" and "writeAccess" scopes are required. When applying schemes of type other than "oauth2", the array of scopes MUST be empty._

I am using implicit flow for swagger and this solved the issue for me: 

`               c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "oauth2" }
                        },
                        new[] { "scope1", "scope2"  }
                    }
                });
`

**Comment by capcom923** [comment]
I met the same issue before and resolved it.

Now the available Authorization header works fine.

Please check my latest sample using SwashBuckle v5.5.1 and netcore 3.1
https://github.com/capcom923/MySwashBuckleSwaggerWithJwtToken

**Comment by changhuixu** [comment]
@domaindrivendev 
To sum up:
(1) It works out-of-box when use `new OpenApiSecurityScheme  { Type = SecuritySchemeType.ApiKey}`
(2) It works out-of-box when use `Type = SecuritySchemeType.Http` and `Scheme="basic"` , but this is for basic auth, not for JWT
(3) If we use `Type = SecuritySchemeType.Http` for JWT, then we need to have customized `OperationFilter`.

**Comment by iashwini** [comment]
If someone migrating to .net core version 3.1, following are the changes require.

1. Use 'Type = SecuritySchemeType.Http'. Because we need to use bearer authentication, set the scheme type to http.
2. HTTP Authorization scheme to be used in the Authorization header. Scheme = "bearer". This has to be a lower case.
3. Add AddSecurityRequirement(). This enables security globally.

Below is the code how it should look.

`options.AddSecurityDefinition(definition, new OpenApiSecurityScheme
                   {
                       Description = $"desc",
                       Name = "Authorization",
                       In = ParameterLocation.Header,
                       Type = SecuritySchemeType.ApiKey,
                       Scheme = "bearer"
                   });

                   options.AddSecurityRequirement(new OpenApiSecurityRequirement
                    {
                        {
                            new OpenApiSecurityScheme
                            {
                                Reference = new OpenApiReference
                                {
                                    Type = ReferenceType.SecurityScheme,
                                    Id = "Bearer"
                                }
                            }, new List<string>()
                        }
                    });`

**Comment by RahulBavaliya** [comment]
> **Don't use parameters** to accomplish this as it is **no longer supported by Swagger UI**. To get the Authorization header included in the curl request **you must define it entirely using security schemes**. For reference see [this comment ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1295#issuecomment-540143783)
> 
> Want to share my configuration that works on 5.0.0-rc5:
> 
> **In Startup.cs, add a global _Security Definition_ and operation filter:**
> 
> ```
> services.AddSwaggerGen(opt =>
> {
> 	opt.SwaggerDoc("v1", new OpenApiInfo { Title = "My Api", Version = "v1" });
> 	opt.AddSecurityDefinition("bearer", new OpenApiSecurityScheme
> 	{
> 		Type = SecuritySchemeType.Http,
> 		BearerFormat = "JWT",
> 		In = ParameterLocation.Header,
> 		Scheme = "bearer"
> 	});
> 	opt.OperationFilter<AuthenticationRequirementsOperationFilter>();
> });
> ```
> 
> In the **AuthenticationRequirementsOperationFilter** add a _Security Requirement_ to the operation by referencing the _Security Definition_ that was added globally:
> 
> ```
> public class AuthenticationRequirementsOperationFilter : IOperationFilter
> {
> 	public void Apply(OpenApiOperation operation, OperationFilterContext context)
> 	{
> 		if (operation.Security == null)
> 			operation.Security = new List<OpenApiSecurityRequirement>();
> 
> 
> 		var scheme = new OpenApiSecurityScheme { Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "bearer" } };
> 		operation.Security.Add(new OpenApiSecurityRequirement
> 		{
> 			[scheme] = new List<string>()
> 		});
> 	}
> }
> ```
> 
> **Note:**
> 
> * The Id value "bearer" matches what was passed as the first parameter to AddSecurityDefinition in Startup.cs
> * This example adds the security requirement to ALL endpoints. Typically, filtering logic will be included to only add the security requirement to endpoints that need it.
> 
> The generated UI won't have Authorization fields in each endpoint. There should be open locks on the endpoints that had a security requirement added to them in the OperationFilter and an Authorize button should show up on the top right. Add the token to the header using the Authorize button and the endpoints will show with closed locks. **Note: "Bearer" will be added automatically, so only provide the token when authorizing.**
> 
> <img alt="Screen Shot 2020-01-07 at 11 23 07 PM" width="493" src="https://user-images.githubusercontent.com/10317382/71958497-4c701480-31a5-11ea-91da-5b04f153458c.png">
> 
> Requests should now include the Authorization header with the provided token. You can verify in the curl:
> 
> <img alt="Screen Shot 2020-01-07 at 11 24 51 PM" width="1087" src="https://user-images.githubusercontent.com/10317382/71958708-c99b8980-31a5-11ea-85c9-097945a96b1b.png">
> 
> Hope it helps!

Thanks for the solution, it worked for me....!!!

**Comment by douglasg14b** [comment]
Having to define & build this all yourself just to get swagger docs to work is.... kinda asinine?
