### ISSUE TITLE
Attributes not respected when using FromQueryAttribute

### ISSUE THREAD

**Issue by maxkisung** [domaindrivendev/Swashbuckle.AspNetCore#1426]
In 5.0.0-rc5, when I use the FromQueryAttribute in my controller method:
`
public async Task<IActionResult> GetItemFromQuery([FromQuery] ItemRequest itemRequest)
`
, the RequiredAttribute and RangeAttribute are not written to the swagger file.

This works fine in rc5: 
`public async Task<IActionResult> GetItem([Required][Range(0, 9999999)] int itemRequest)
`

In rc4, the Required is respected but Range is not.  

A workaround in rc5 is to use the BindRequiredAttribute with the SwaggerDefaultValues: IOperationFilter, but I don't have a workaround for Range.

Both of these worked in 4.0

Attached project demonstrates rc5 behavior.
[deleteWeb.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/3979811/deleteWeb.zip)

**Comment by domaindrivendev** [comment]
Fixed by a61da693d9bd559e3e3c1ab247ac12c6a0096198
