### ISSUE TITLE
Swagger permanent authorization token

### ISSUE THREAD

**Issue by gaoconggit** [domaindrivendev/Swashbuckle.AspNetCore#1427]
I am developing web api in ASP.NET Core MVC. I wonder if there is a way to make authorization token in swagger persistent, so that the authorization does not need to be done manually every time the application is run. 
It would make testing easier.

**Comment by lankymart** [comment]
Have the same issue, the authorization token is only valid until the swagger-ui is refreshed and then you have to provide the client_id, client_secret and scopes again. I'm guessing this could be done by injecting a JavaScript but not sure, is this something that is planned?

**Comment by domaindrivendev** [comment]
This is a question for the [swagger-ui folks](https://github.com/swagger-api/swagger-ui)
