### ISSUE TITLE
ODataQueryOptions<TEntity> causes ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by jtran96** [domaindrivendev/Swashbuckle.AspNetCore#1428]
I am getting "ArgumentException: An item with the same key has already been added." when one of the data type of an operation parameter is ODataQueryOptions<TEntity>.

Using 
.NET Core 3.1
System.Text.Json
Swashbuckle.AspNetCore 5.0.0-rc5

`public IActionResult Get(ODataQueryOptions<WeatherForecast> queryOptions)`

Stack Trace
`System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
System.Collections.Generic.Dictionary<TKey, TValue>.Add(TKey key, TValue value)
Swashbuckle.AspNetCore.SwaggerGen.JsonObjectHandler.CreateDefinitionSchema(Type type, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase+<>c__DisplayClass4_1.<GenerateSchema>b__0()
Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, string schemaId, Func<OpenApiSchema> factoryMethod)
Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func<OpenApiSchema> factoryMethod)
Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameter(ApiParameterDescription apiParameter, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator+<>c__DisplayClass10_0.<GenerateParameters>b__1(ApiParameterDescription apiParam)
System.Linq.Enumerable+WhereSelectListIterator<TSource, TResult>.ToList()
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameters(ApiDescription apiDescription, SchemaRepository schemaRespository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

The issue occurs because of the below.

`ODataQueryOptions<TEntity>: ODataQueryOptions`
`public ETag<TEntity> IfMatch { get; }`
`public ETag<TEntity> IfNoneMatch { get; }`

`ODataQueryOptions`
`public virtual ETag IfMatch { get; }`
`public virtual ETag IfNoneMatch { get; }`

A possible solution would be to do a check if the key already exists and do either replace of the value or skip?

**Comment by Temppus** [comment]
I found this bug report just now so I closed my reported issue, because it was duplicate.
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1455

**Comment by farshad-dashti** [comment]
Same problem here :(

**Comment by slashersvk** [comment]
Had same problem but from stable version 5.0.0 it no longer throws exception.

**Comment by ToddTaylor** [comment]
I'm seeing the following similar exception:

`System.ArguementException: An item with the same key has already been added.  Key: ifMatch`

Using:
- .NET Core 3.1
- Microsoft.AspNetCore.OData 7.3.0
- Swashbuckle.AspNetCore 5.1.0
- Swashbuckle.AspNetCore.Annotations 5.1.0

Reverting the Swashbuckle NuGet packages back to version 5.0.0 has resolved the issue for now.

**Comment by janoooo** [comment]
I had a similar exception

_System.ArgumentException: An item with the same key has already been added. Key: ifMatch
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerMetadata serializerMetadata, SchemaRepository schemaRepository)
... so on...

I used:
- .NET Core 3.1 webapi only
- OData 7.4.0 beta
- Swashbuckle 5.1

**Fix:**
My app uses Newtonsoft.Json, because OData used it to format a url {$select}. 
Swashbuckle v 5.1 is configured to use System.Text.Json by default.
As you can see in https://github.com/domaindrivendev/Swashbuckle.AspNetCore
_If you're using Newtonsoft, then you'll need to install a separate package and explicitly opt-in to ensure that Newtonsoft settings/attributes are automatically honored by the Swagger generator_
After installing package Swashbuckle.AspNetCore.Newtonsoft and settings explicit opt-in app works correctly

**Comment by jtran96** [comment]
Yea we ended up explicitly use Newtonsoft as well, which forces us to not use System.Text.Json. Solving this issue was good but we aren't sure the side-affect to other components.

**Comment by kakone** [comment]
I sent a PR where I replaced the property.

**Comment by SharpNoiZy** [comment]
Hi,
I have the same issue, but don't how solve the issue until your fix aa7f6ee is released with a new version.

I have this issue with the GeneratePolymorphicSchemas->discriminatorSelector

I try to name the property that descripes the type, but if I do so, I get the exception.

**Comment by gokhanabatay** [comment]
Hi when did you plan to release, we are waiting upgrade.
