### ISSUE TITLE
swaggerDoc.Definitions.Clear() missing in 5.0.0

### ISSUE THREAD

**Issue by shaair** [domaindrivendev/Swashbuckle.AspNetCore#1432]
what is the replacement for swaggerDoc.Definitions.Clear() in 5.0.0

**Comment by domaindrivendev** [comment]
`swaggerDoc.Components.Schemas.Clear();`

Although - I'm curious to know why you would ever want to do this as it would break all of the schema references in your swagger document?

**Comment by shaair** [comment]
Actually with the different clients need must to specified the schema and some time no need to expose.
