### ISSUE TITLE
No possibility of rendering non-property fields in models?

### ISSUE THREAD

**Issue by JustArchi** [domaindrivendev/Swashbuckle.AspNetCore#1438]
Hey, I'm using latest version of Swashbuckle.AspNetCore, 5.0.0-rc5 as of today.

For the last hour I've been looking for a simple switch that would enable rendering of normal, non-property fields in the classes. By default Swashbuckle is looking only for public properties, and I'd like it to work with fields as well.

Unfortunately I didn't find any option for that, neither in the documentation nor the source code. It seems that this option doesn't even exist, even though I'm almost certain that at some point those fields I've used all this time were rendered correctly and disappeared only recently, but maybe I'm wrong so don't quote me on that.

Anyway I'd be happy if Swashbuckle rendered in models everything that JSON serializers normally do, to give user consuming my API complete view of what lies inside request/response that he's going to see. The good starting point would be to render recursively every field and property of the request/response that does not have `[JsonIgnore]` attribute and has either a public getter or `[JsonProperty]` attribute. To the best of my knowledge this is already happening with the properties, but not with the fields, which would be nice.

Ref: https://www.newtonsoft.com/json/help/html/SerializationGuide.htm#Objects

> By default a type's properties are serialized in opt-out mode. What that means is that all public fields and properties with getters are automatically serialized to JSON, and fields and properties that shouldn't be serialized are opted-out by placing JsonIgnoreAttribute on them. To serialize private members, the JsonPropertyAttribute can be placed on private fields and properties.

Of course you could tell me "just use the properties then", but it's not a workaround or solution. Fields are quite common in the code, I might want to serialize some private or internal field to show it to the user, but it gets especially annoying if I have some third-party class from another library to show for user, and I can't since it for some reason decided to use fields and not properties for its body.

Thank you in advance for considering this feature. If there is any existing solution or workaround that would let me tell the swagger generator in Swashbuckle to render fields, I'd also appreciate giving it a try until the feature is added.

**Comment by domaindrivendev** [comment]
Out of the box, this version describes types based on the System.Text.JSON serializer, which does NOT serializer fields. Sounds like you may be using Newtonsoft and not STJ. If so, you’ll need to opt-in to Swashbuckle support for Newtonsoft as described in the release notes

**Comment by JustArchi** [comment]
Yes, I'm using Newtonsoft, sorry for omitting that detail.

> If so, you’ll need to opt-in to Swashbuckle support for Newtonsoft as described in the release notes

God damn, I'm so ashamed of myself right now that I've totally missed this in release notes. Of course everything works fine now after following the doc with `AddSwaggerGenNewtonsoftSupport()`.

Thank you a lot for pushing me on the right track. I apologize for taking your time with my issue, it's entirely my fault that I didn't notice the JSON changes (despite reading the release notes). At the same time I'd like to say double thanks for leaving Newtonsoft as optional opt-in in swagger, it's awesome that you've considered this scenario.

Thanks again 👍
