### ISSUE TITLE
RC5 enums not working correctly

### ISSUE THREAD

**Issue by SledgeHammer01** [domaindrivendev/Swashbuckle.AspNetCore#1440]
This issue is introduced in RC5, RC4 worked correctly.

Consider, the following class:

	public enum GrantType
	{
		client_credentials = 0
	}

	public class TokenCredentials
	{
		[Required]
		public GrantType? grant_type
		{
			get;
			set;
		}

		public string client_id
		{
			get;
			set;
		}

		public string client_secret
		{
			get;
			set;
		}
	}

Controller method:

public async Task<IActionResult> GenerateTokenAsync([FromForm]TokenCredentials tokenCredentials)
{
}

In RC4, Swagger reports grant_type is a string and shows "client_credentials" in the drop down. In RC5, Swagger reports it is an int and shows 0 in the drop down.

Startup.cs is setup with:

			services.AddMvc(options => options.EnableEndpointRouting = false).AddNewtonsoftJson(options =>
			{
				// serialize all enums as strings

				options.SerializerSettings.Converters.Add(new StringEnumConverter());

				// serialize objects based on class hierarchy depth

				options.SerializerSettings.ContractResolver = new ContractResolver();
			});

**Comment by RouR** [comment]
It seems that StringEnumConverter is ignored.

Try to add
```
                    .AddJsonOptions(options =>
                    {
                        options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
                    })

```

**Comment by domaindrivendev** [comment]
If you’re still using Newtonsoft, then you need to explicitly opt-in to Swashbuckle Newtonsoft support (honoring StringEnumConverter etc.) as described in the release notes

**Comment by SledgeHammer01** [comment]
Thanks, that worked. Helps to read release notes once in a while :).

**Comment by ltm0203** [comment]
services.AddMvc(options => options.EnableEndpointRouting = false).AddNewtonsoftJson(options =>
		{
			// serialize all enums as strings

			options.SerializerSettings.Converters.Add(new StringEnumConverter());

			// serialize objects based on class hierarchy depth

			options.SerializerSettings.ContractResolver = new ContractResolver();
		});
