### ISSUE TITLE
Swashbuckle.AspNetCore.Newtonsoft is not strong name signed

### ISSUE THREAD

**Issue by jkeech** [domaindrivendev/Swashbuckle.AspNetCore#1443]
Swashbuckle.AspNetCore.Newtonsoft version 5.0.0-rc5 is not strong-name signed, which is preventing me from using it in my services. Can you publish a version which is signed similar to the other packages? Thanks!

> CSC : error CS8002: Referenced assembly 'Swashbuckle.AspNetCore.Newtonsoft, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by domaindrivendev** [comment]
Fixed by db7e7bcd43bf118fd4c447355f333250958278f4
