### ISSUE TITLE
Grouping everything under a single group, or hiding the section labels?

### ISSUE THREAD

**Issue by ffMathy** [domaindrivendev/Swashbuckle.AspNetCore#1446]
Is it possible to group everything under a single group, or remove grouping altogether?

**Comment by domaindrivendev** [comment]
Under the hood, grouping is driven by operation "tags". By default, operations will be tagged with the controller name and hence are grouped that way. However, you can override this behavior with something along the following lines to achieve a single group. There's no easy way to remove grouping altogether:

```csharp
c.TagActionsBy(api => new[] { "All Operations" });
```
