### ISSUE TITLE
ReDoc including /swagger/v1 in sample API calls

### ISSUE THREAD

**Issue by jeroenheijmans** [domaindrivendev/Swashbuckle.AspNetCore#1454]
First up: thanks for a great set of packages, it all works terrifically well for us!

One thing we started to notice when upgrading to `5.0.0-rc5` (though the problem may have pre-existed) is that the sample requests URL would contain an unexpected base path, when using _ReDoc_ as the UI.

First, a repro! We've started with a fresh ASP.NET Core 3.0 Web API project called `Foo`, and changed only the Startup and NuGet packages. Startup looks like this:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddSwaggerGen(c => { c.SwaggerDoc("v1", new OpenApiInfo { Title = "Foo Api", }); });
    services.AddControllers();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseDeveloperExceptionPage();
    app.UseHttpsRedirection();
    app.UseRouting();
    app.UseAuthorization();
    app.UseSwagger();
    app.UseReDoc(c =>
    {
        c.SpecUrl = "swagger/v1/swagger.json";
        c.RoutePrefix = "";
    });
    app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
}
```

There's a `WeatherForecastController` from Microsoft's template with some routes. When I start the project and navigate to the root, I see ReDoc properly. Nice! But, the sample request box on the right hand site will be like this:

```none
GET /WeatherForecast
https://localhost:44371/swagger/v1/WeatherForecast
```

Screenshot:

![same info as snippet above](https://user-images.githubusercontent.com/1590536/71899465-13f81880-315c-11ea-98db-b10e4c91cb56.png)

This _incorrectly_ includes `/swagger/v1` as part of the URL.

If I change from ReDoc to SwaggerUI by using this instead:

```csharp
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "Foo Api");
    c.RoutePrefix = "";
});
```

And then start things up and execute a test request, it _does not_ show that same behavior:

![screenshot showing SwaggerUI properly using the URI](https://user-images.githubusercontent.com/1590536/71899721-95e84180-315c-11ea-94be-2f96cd7af009.png)

That is, it does _not_ insert `swagger/v1/` anywhere in the URLs.

----

I've tried to fix (work around?) this myself by trying to configure the `RootUrl` with ReDoc, but could not find the right extension point to do this.

Please let me know if I can add any details or help to improve this issue and prevent others from running into this same issue.

**Comment by domaindrivendev** [comment]
> First up: thanks for a great set of packages, it all works terrifically well for us!
Thanks for this. A single comment like this goes a long way.Doc

I was able to repro this issue in my ReDoc sample app so definitely a bug somewhere. However, I believe that the issue is actually with the

**Comment by domaindrivendev** [comment]
> First up: thanks for a great set of packages, it all works terrifically well for us!

Thanks for this. A single comment like this goes a long way to keeping me motivated 👍 

I was able to repro this issue in my ReDoc sample app so definitely a bug somewhere. However, I think the root cause is with the [redoc library itself](https://github.com/Redocly/redoc) as oppsoed to
Swashbuckle, and you may be able to get a resolution quicker by posting there instead.

The [Swagger / OpenAPI](https://swagger.io/specification/#pathsObject) has the following to say about constructing request URL's from the Swagger document:

> The path is appended (no relative URL resolution) to the expanded URL from the Server Object's url field in order to construct the full URL. Path templating is allowed.

If you look at the raw `swagger.json` returned by Swashbuckle, you'll see that the `server` property is actually omitted and therefore should be defaulted to `/` (also as per the spec). So, to construct the sample request URL, the redoc UI should simply append `/products` to `/`. However, it appears to be appending it to the path of the current page instead.

I believe the __swagger-ui__ honors the spec. correctly whereas __redoc__ does not.

**Comment by jeroenheijmans** [comment]
Thx for the prompt response!

If I understood correctly:

- I should report this as a bug upstream in redoc, so when it gets fixed it can be pulled into here
- as a workaround, I should look for a way to get the `server` property set so it does (probably) get picked up

right?

**Comment by domaindrivendev** [comment]
Yeh, I think it would be worth reporting upstream. In the meantime, I think you _may_ be able to workaround the issue by expliciting setting the `server` root url in the returned swagger.json rather than relying on the default. For example, I was able to do this as follows:

```csharp
app.UseSwagger(c =>
{
    c.PreSerializeFilters.Add((swagger, httpRequest) =>
    {
        swagger.Servers.Add(new OpenApiServer
        {
            Url = $"{httpRequest.Scheme}://{httpRequest.Host}"
        });
    });
});
```

**Comment by jeroenheijmans** [comment]
Confirmed that the workaround does the trick both in my Repro and in my actual production application 🎉 😄 

I've [reported the issue upstream in the redoc repo](https://github.com/Redocly/redoc/issues/1151), should they want to fix it.

Thanks a bunch for the support!
