### ISSUE TITLE
Not generating enum values for method parameters

### ISSUE THREAD

**Issue by matthawley** [domaindrivendev/Swashbuckle.AspNetCore#1457]
When I have an enum as path parameter for my controller action, it doesn't output any schema for it. I'm using 5.0-rc5 as SwaggerV2 output.

For instances

```
public enum MyEnum {
  A,
  B
}

[HttpPost, Route("foo/{state}")]
public Task<IActionResult> GetState([FromRoute] MyEnum state) { ... }
```

1. It generates the schema correctly from `MyEnum`
```
"MyEnum": {
   "enum": [
      "A",
      "B"
   ],
   "type": "string"
}
```

2. It does not generate a reference OR include the Enum / Type == "String" in the parameter definition of the path.
```
{
   "in": "path",
   "name": "state",
   "description": "The state for the user.",
   "required": true
}
```

**Comment by domaindrivendev** [comment]
Dup of #1329
