### ISSUE TITLE
Gelato import support

### ISSUE THREAD

**Issue by NinoFloris** [domaindrivendev/Swashbuckle.AspNetCore#146]
So after getting my export, http://gelato.io would not import it due to these issues:
- parameter uses `"in": "modelbinding"` which is unsupported, my suggestion is to look for the attributes `[FromQuery]` `[FromBody]` etc and default to `[FromQuery]` as this is the dotnet core default modelbinding source. Setting "in" to "query" or "body" and a few other ones is accepted.
- Casing issues with route placeholders and parameter names, if these don't match (exact case), say I have a camelCased placeholder `{id}` and a modelbinding object with a PascalCased property `Id` then Gelato does not see the connection between these two and complains about a missing parameter for path. 
- Finally i would like to have some control over the casings of resources inside the path urls as `/resource/{id}/Comments` looks weird, I don't know where this string is created but I would like that lowercased with exception to the placeholders, as is normal.

Edit:
And how do I set the basepath of the output — with of course the paths neatly relative to that — should this not go through the Info object? As Gelato imports all the routes under the same 'resource' by default if their paths don't match the base path that was set in the onboarding.

**Comment by domaindrivendev** [comment]
Can you please try again with the latest version of Swashbuckle.AspNetCore as some of the above issues should be fixed? If I don't hear back in the next couple of days I'm going to close the issue. Thanks
