### ISSUE TITLE
Unable to find service type 'Microsoft.Extensions.ApiDescriptions.IDocumentProvider' in dependency injection container. Update the 'Startup' class to register a document.

### ISSUE THREAD

**Issue by ilcos91** [domaindrivendev/Swashbuckle.AspNetCore#1460]
I'm using the version 5.0.0-rc5 and I got this error after downloading the nuget package and compiling my project. I'm using Ocelot as Gateway of the project.
I'm new on github, if this is the wrong place to ask for this problem I'll delete the issue and post it in the right place.

Thank you in advance

**Comment by domaindrivendev** [comment]
@ilcos91 do you still see this issue with the latest version (`5.6.3` at time of writing)? If not, please close this issue. If you do, please create a minimal app (i.e. start from empty project) that repro's the issue and post to github so I can pull down and troubleshoot.
