### ISSUE TITLE
Generic Types containing Array's Produce Invalid Schema Ids

### ISSUE THREAD

**Issue by matthawley** [domaindrivendev/Swashbuckle.AspNetCore#1461]
When we use a generic class where it's declared type is an array, it'll produce an invalid Schema Id.

For instance

`[ProducesRespons(200, typeof(ServiceResponse<Foo[]>))]`

Will result in the schema id of `Foo[]ServiceResponse`, which is invalid per Swagger documentation because of the brackets. This issue is the result of the following method.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/9abdbf99a271de5decb2bd93c5c614632e750b32/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGeneratorOptions.cs#L38

**Comment by domaindrivendev** [comment]
Good catch 👍. Should be fixed by 7a29c9c2269bde2a624a2461818cb1a7d71ec7e3
