### ISSUE TITLE
502 Showing as ServerError vs BadGateway

### ISSUE THREAD

**Issue by say25** [domaindrivendev/Swashbuckle.AspNetCore#1462]
I was expecting the text for 502 to be BadGateway instead of ServerError not sure if this intended behavior or not.

![image](https://user-images.githubusercontent.com/7467062/72031940-96afcf00-3253-11ea-836f-93406c0aeaf5.png)

**Comment by eliezer325** [comment]
> I was expecting the text for 502 to be BadGateway instead of ServerError not sure if this intended behavior or not.
> 
> ![image](https://user-images.githubusercontent.com/7467062/72031940-96afcf00-3253-11ea-836f-93406c0aeaf5.png)

**Comment by martincostello** [comment]
Fix would be to extend this code with additional status codes:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/cbc1b7aa34c8662c33dd854efef49b66706965ad/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L691

**Comment by say25** [comment]
@martincostello I can take this on
