### ISSUE TITLE
Readonly enum is showing

### ISSUE THREAD

**Issue by IlyaUhlianitsa** [domaindrivendev/Swashbuckle.AspNetCore#1464]
Hello,
I use aspnetcore3.1 and Swashbuckle.AspNetCore 5.0.0-rc3
I need to hide some properties when HTTP GET and show them when HTTP POST, so I inherit `ISchemaFilter` and set `openApiSchema.ReadOnly = true;` for a property. 
It works awesome for value types and strings - properties aren't showing in GET endpoints.
But it doesn't work with enums, unfortunately.

I checked with 5.0.0-rc5 version and it doesn't work. Also, I wouldn't like to migrate to this version because of this bug https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1459

4.0.1 versions for net core 2.0 works fine.

Is it possible to fix this problem in the next rc?
And does someone know the release date for the 5.0.0 version?

**Comment by domaindrivendev** [comment]
If you want the `readOnly` flag to be set mark the property as `private get` or `internal get` in your C# code. No need for a schema filter.

**Comment by IlyaUhlianitsa** [comment]
Unfortunately, it is not what I'm looking for.
`private get` or `internal get` removes the property from HTTP GET and POST endpoints where I use one contract. But I need `readonly` behavior - hide from HTTP GET and show in HTTP POST

See details there please.
![image](https://user-images.githubusercontent.com/14961737/72201323-b1589280-3463-11ea-85f1-cbabb0cf3cab.png)
https://swagger.io/docs/specification/data-models/data-types/

**Comment by domaindrivendev** [comment]
OK I guess I mixed up the wording - my suggestion should have said use `private set` or `internal set`.

**Comment by IlyaUhlianitsa** [comment]
Thanks for your answer!
I can't use `private` because my code should work with the resource in different classes.
I tested `internal set` and `internal get` with value types and strings - it works great! Hides in POST and GET endpoints respectively.
But it doesn't work with enums - they are showing always.

Maybe it is possible to fix as it works in 4.0.1 version?

**Comment by domaindrivendev** [comment]
The issue with enums is because enums (and complex classes) are defined as shared schema definitions that are "referenced" by parameter or property defintions rather than being defined inline with. This means they're shared and therefore can't include contextual metadata like the `readOnly` flag.

However, the latest code includes a solution to this problem and based on initial testing appears to support the behavior you want for both value-typed and enum properties. This will be available with the `5.0.0` release but in the meantime you can try it out by pulling the latest preview from myget.org:

https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore

**Comment by IlyaUhlianitsa** [comment]
I see `5.0.0` version has just released - huge thanks for that @domaindrivendev!
I tested it and this issue could be closed because the bug is fixed.

**Comment by RobKuipers** [comment]
Hi,
Same problem (enums with a getter only, and even explicitly marked with [SwaggerSchema(ReadOnly = true)] showing up in POST examples).
Using Swashbuckle AspNetCore 6.1.4

Shows up as $ref with no further metadata.

Does anyone else experience the same problem?

**Comment by ph-ict** [comment]
@RobKuipers I know it's been a while but just found this issue also in the latest stable 6.3.0

**Comment by melgmry0101b** [comment]
I can confirm @ph-ict 's note that using `internal set` for `Enum` types on version `6.3.1` doesn't annotate the field as `readOnly`

**Comment by ph-ict** [comment]
@domaindrivendev Can we get this issue reopened please?

**Comment by galfar** [comment]
I can confirm with v6.5.0.

In my case I can use a workaround based on https://stackoverflow.com/a/72386179
where I put [SwaggerSchema(ReadOnly = true)] on the enum itself.

```cs
[SwaggerSchema(ReadOnly = true)]  
public enum OfferStatus
{
    New = 0, 
    Archived = 1,
    FirstReminderSent = 2    
}

public record ClientOffer : BaseRecord
{
    [Required]
    public string ClientEmail { get; init; } = default!;
    // ReadOnly is not needed on property itself anymore but I keep it there for a bit more clarity
    [SwaggerSchema(ReadOnly = true)]
    public OfferStatus Status { get; init; } = OfferStatus.New;
}
```

**Comment by sawork** [comment]
Oh god, this problem is still not solved...
