### ISSUE TITLE
SchemaGenerator generating empty schema

### ISSUE THREAD

**Issue by krajek** [domaindrivendev/Swashbuckle.AspNetCore#1466]
Version: 5.0.0rc4 and rc5

Hi, I would like to create an operation filter that for every operation would add a 500 response with specific(ApiErrorResult) type as the content.

However, the schema that the schema generator produces is empty (has no properties).

```
public class InternalServerErrorOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            string statusCodeText = ((int) HttpStatusCode.InternalServerError).ToString();

            if (operation.Responses.ContainsKey(statusCodeText))
            {
                return;
            }
            var errorType = typeof(ApiErrorResult);

            var response = new OpenApiResponse
            {
                Description = "Unexpected error occured",
                Content = new Dictionary<string, OpenApiMediaType>()
                {
                    {
                        "application/json", new OpenApiMediaType()
                        {
                            Schema = context.SchemaRepository.GetOrAdd(
                                errorType,
                                nameof(ApiErrorResult),
                                () =>
                                {
                                    var errorResultSchema = context.SchemaGenerator.GenerateSchema(
                                        errorType,
                                        context.SchemaRepository);

                                    return errorResultSchema;
                                }),

                        }
                    }

                }
            };

            operation.Responses.Add(statusCodeText, response);
        }
    }
```

I found out that if I use the error type in any of `Produces` attribute like this:

```
[ProducesResponseType(typeof(ApiErrorResult), 400)]
```

then the repository already contains the correct schema and everything is fine. How should I use the generator to do the same job `ProducesResponseType` seems to be doing?

**Comment by krajek** [comment]
By the method of trial and error, I ended up with the following working solution:

```
public class InternalServerErrorOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var statusCodeText = ((int) HttpStatusCode.InternalServerError).ToString();
            var errorType = typeof(ApiErrorResult);

            if (operation.Responses.ContainsKey(statusCodeText))
            {
                return;
            }

            if (!context.SchemaRepository.Schemas.TryGetValue(nameof(ApiErrorResult), out var schema))
            {
                schema = context.SchemaGenerator.GenerateSchema(errorType, context.SchemaRepository);
            } 

            var response = new OpenApiResponse
            {
                Description = "Unexpected error occured",
                Content = new Dictionary<string, OpenApiMediaType>()
                {
                    {
                        "application/json", new OpenApiMediaType()
                        {
                            Schema = schema
                        }
                    }

                }
            };

            operation.Responses.Add(statusCodeText, response);
        }
    }
```

The problem was with the `GetOrAdd` method being fed result of `GenerateSchema`. Manually checking the presence of schema solved the problem.

If you think this piece of information is useful enough to be documented, let me know, I am willing to provide a PR for this.

Closing.

**Comment by thomaslevesque** [comment]
@krajek I have the same issue, but your solution doesn't seem to work for me, the schema is still empty.

**Comment by krajek** [comment]
`
/// <summary>
    /// Adds 500 Internal Server Error response to each operation that does not define it explicitly.
    /// </summary>
    public class InternalServerErrorOperationFilter : IOperationFilter
    {
        /// <inheritdoc />
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var statusCodeText = ((int) HttpStatusCode.InternalServerError).ToString();

            if (operation.Responses.ContainsKey(statusCodeText))
            {
                return;
            }

            var errorSchema = context.GetApiErrorResultSchemaRef();

            var response = errorSchema.AsJsonResponse("Internal server error");

            operation.Responses.Add(statusCodeText, response);
        }
    }
`

`
/// <summary>
        /// Makes sure that schema repository contains model for <see cref="ApiErrorResult"/>.
        /// Returns OpenAPI schema as a reference to the schema in repository.
        /// </summary>
        public static OpenApiSchema GetApiErrorResultSchemaRef(this OperationFilterContext self) 
            => self.EnsureSchemaPresentAndGetRef<ApiErrorResult>();
`

`
/// <summary>
        /// Makes sure that schema repository contains model for <typeparamref name="TModel"/>.
        /// Returns OpenAPI schema as a reference to the schema in repository.
        /// </summary>
        /// <typeparam name="TModel">Model type to be represented in schema repository</typeparam>
        /// <param name="self">The operation filter</param>
        /// <returns>The OpenAPI schema for <typeparamref name="TModel"/></returns>
        public static OpenApiSchema EnsureSchemaPresentAndGetRef<TModel>(
            this OperationFilterContext self)
        {
            var type = typeof(TModel);
            if (!self.SchemaRepository.Schemas.TryGetValue(type.Name, out _))
            {
                var refSchema = self.SchemaGenerator.GenerateSchema(type, self.SchemaRepository);
                return refSchema;
            }

            var createdRefSchema = new OpenApiSchema()
            {
                Reference = new OpenApiReference()
                {
                    Id = type.Name,
                    Type = ReferenceType.Schema
                }
            };

            return createdRefSchema;
        }
`

This is the code I use in production. Maybe that will help you.

**Comment by thomaslevesque** [comment]
Thanks @krajek. I eventually managed to make it work, not sure how...
