### ISSUE TITLE
Propertiy names set by JsonPropertyAttributes are ignored whenever its class is used with [FromBody] Post Method

### ISSUE THREAD

**Issue by tvperez76** [domaindrivendev/Swashbuckle.AspNetCore#1467]
Propertiy names set by JsonPropertyAttributes are ignored whenever its class is used with [FromBody] Post Method.  This only appears to happen with v5.0.0-rc5 version of Swashbuckle.AspNetCore library.  All others appear to be working well.

Version v.5.0.0-rc5:
<img width="1196" alt="Swashbuckle AspNetCore v5 0 0-rc5" src="https://user-images.githubusercontent.com/29001635/72166286-cfe45e00-337d-11ea-98d8-716ff97f1366.png">

Version v.5.0.0-rc4:
<img width="1063" alt="Swashbuckle AspNetCore v5 0 0-rc4" src="https://user-images.githubusercontent.com/29001635/72167634-5c901b80-3380-11ea-99ff-3cefc25b04c9.png">

**Comment by domaindrivendev** [comment]
`JsonProperty` is a Newtonsoft attribute which leads me to believe you're still using the Newtonsoft serializer as opposed to the new serializer `System.Text.Json` that ships with ASP.NET Core 3.0. If this is the case, you'll need to install a separate Swashbuckle package and explicitly opt-in to honor the Newtonsoft attributes. See https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft

**Comment by tvperez76** [comment]
That's correct.  However, I am not using ASP.NET Core 3.0, so that's not really an option.

**Comment by domaindrivendev** [comment]
Yes you need to invoke it regardless

**Comment by tvperez76** [comment]
Thank you for the information.  I recommend that this be explicitly stated in the documentation, as to remove any ambiguity as to the applicability of the AddSwaggerGenNewtonsoftSupport() method in non-ASP.NET Core 3.0 hosts.
