### ISSUE TITLE
AdditionalProperties is added to Properties

### ISSUE THREAD

**Issue by runehalfdan** [domaindrivendev/Swashbuckle.AspNetCore#1471]
I have this simple Dto-object (we do schema-mapping manually): 
```
public abstract class MyDto
{
    [JsonExtensionData]
    public Dictionary<string, object> Properties { get; } = new Dictionary<string, object>(StringComparer.Ordinal);
}
```

In JsonObjectHandler (and NewtonsoftObjectHandler), this property is added to the Properties-collection. And its presence triggers AdditionalPropertiesAllowed = true and sets AdditionalProperties-schema. 
As I understand it, the presence of a JsonExtensionData-property should only enable AdditionalProperties, not added it a property

**Comment by domaindrivendev** [comment]
Good catch. Fixed by c47d3b70fc0fcc2d24e0a88789132a358d6ab7c5, including a test for both the STJ and Newtonsoft based-generators.
