### ISSUE TITLE
XML documentation for [FromForm] parameters not generated

### ISSUE THREAD

**Issue by xhafan** [domaindrivendev/Swashbuckle.AspNetCore#1473]
Swashbuckle.AspNetCore 5.0.0-rc5, XML documentation for `[FromForm]` parameters is not generated. When I remove `[FromForm]` attribute from the parameter, it works fine.

Example: 
```c#
/// <summary>
/// Remove tour from a destination. The tour will not be deleted, just removed from the destination.
/// </summary>
/// <param name="uniqueId">Destination unique id</param>
/// <param name="tourUniqueId">Tour unique id</param>
/// <returns></returns>
[Authorize]
[HttpPost("{uniqueId}/[action]")]
public async Task<string> RemoveTour(
    string uniqueId, 
    [FromForm]string tourUniqueId
    )
{
...
}
```

![image](https://user-images.githubusercontent.com/13038902/72342673-532ee800-36cd-11ea-9a97-734b2090272f.png)

This used to work in Swashbuckle.AspNetCore 4.0.1: 
![image](https://user-images.githubusercontent.com/13038902/72343912-4bbd0e00-36d0-11ea-9b31-b66769c1ff6b.png)

**Comment by domaindrivendev** [comment]
This requires a bit of a refactor to how XML comments are incorporated into the Swagger document. Rather than hold up the 5.0.0 release figuring this out, I'm going to punt for this release but will prioritize as a fast follow.

**Comment by tkggusraqk** [comment]
This function is very important and will be very convenient for parameter description
