### ISSUE TITLE
Test UI does not send HTTP GET body 

### ISSUE THREAD

**Issue by HGSandhagen** [domaindrivendev/Swashbuckle.AspNetCore#148]
My web service expect a get request with a body. The generated swagger look correct (see below), the ui shows it with parameter type "body" and even the generated curl statement is correct (and works), but when the request is send from UI, it has no body.

Method definition in controller:
        [HttpGet("testbody/{param}")]
        [SwaggerResponse(System.Net.HttpStatusCode.OK, Type = typeof(IEnumerable<String>))]
        public IActionResult GetTestBody(String param, [FromBody]String properties = null) {

curl: curl -X GET --header 'Content-Type: application/json' --header 'Accept: application/json' -d 'property' 'http://localhost:61240/api/Ldap/testbody/param'

Excerpt from generated swagger.json:

"/api/Ldap/testbody/{param}": {

```
"get": {
    "tags": [
        "Ldap"
    ],
    "operationId": "ApiLdapTestbodyByParamGet",
    "consumes": [
        "application/json",
        "text/json",
        "application/json-patch+json"
    ],
    "produces": [ ],
    "parameters": [
        {
            "name": "param",
            "in": "path",
            "required": true,
            "type": "string"
        },
        {
            "name": "properties",
            "in": "body",
            "required": false,
            "schema": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        }
    ],
    "responses": {
        "200": {
            "description": "OK",
            "schema": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "204": {
            "description": "No Content"
        }
    },
    "deprecated": false
}
```

},

**Comment by joehoppe** [comment]
I am seeing the same thing with 6.0.0-beta901 for posts. The CURL statement works, but the only way to get parameters to be passed from the UI is to mark the parameters as [FromQuery]. Parameters without an attribute, or using [FromBody], the UI does not pass. Verified using Fiddler.

**Comment by domaindrivendev** [comment]
If the generated Swagger is correct but the UI is not behaving as expected, then you would be better off logging this issue with the [swagger-ui](https://github.com/swagger-api/swagger-ui) folks.
