### ISSUE TITLE
An empty enum in a DTO crashes the middleware

### ISSUE THREAD

**Issue by Boiethios** [domaindrivendev/Swashbuckle.AspNetCore#1489]
## VERSION: ##
Version `5.0.0`

## STEPS TO REPRODUCE: ##
Just put any empty `enum` in a DTO:

```cs
public enum FooBar {}

public class MyDto
{
    pulic FooBar fooBar { get; set; }
}

// In the controller:

[HttpGet("")]
[ProducesResponseType(200)]
public ActionResult<MyDto> GetMyDto()
{
    return new MyDto();
}
```

## EXPECTED RESULT: ##
The `swagger.json` is correctly fetched, or a clear error is issued.

## ACTUAL RESULT: ##
The Swashbuckle middleware crashes with an `IndexOutOfRangeException`.

## ADDITIONAL DETAILS ##
I know that an empty doesn't make much sense in a DTO, but IMO there should be an clearer clue of what fails. I put this enum as a placeholder before populating it, and had a hard time figuring why the middleware was crashing.

**Comment by JoasE** [comment]
Having the same problem! Took a while to find out what it was. Had the enum as a placeholder aswell. A more clear exception would be nice, but I think it should just generate valid swagger.
