### ISSUE TITLE
[5.0.0] Dictionary<Enum, T> Does not Respect Enum Naming Conventions

### ISSUE THREAD

**Issue by matthawley** [domaindrivendev/Swashbuckle.AspNetCore#1491]
When generating a schema, a type that exposes a Dictionary where the key is an enum, the name of the key it generates is always what is in code (normally Pascal cased). I feel that this handler should respect the naming conventions of enums.

**Expected:**
```
"ServiceResponse": {
  "required": [ "updates"],
  "type": "object",
  "properties": {
    "updates": {
      "required: [],
      "type": "object",
      "properties": {
        "profile": {
          "format": "int64",
          "type": "integer"
        }
      }
    }
  }
}
```

**Actual:**
```
"ServiceResponse": {
  "required": [ "updates"],
  "type": "object",
  "properties": {
    "updates": {
      "required: [],
      "type": "object",
      "properties": {
        "Profile": {
          "format": "int64",
          "type": "integer"
        }
      }
    }
  }
}
```

**C# Classes:**
```
public enum UpdateTypes {
  Profile
}

public class ServiceResponse {
  public IDictionary<UpdateTypes, long> Updates { get; set; }
}
```

Reference to the code in question:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/e4402e3872462e7e42dc4baa58b7a2a0e0fb3f51/src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDictionaryHandler.cs#L48

Would expect the following code to apply here as well.
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/e4402e3872462e7e42dc4baa58b7a2a0e0fb3f51/src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftEnumHandler.cs#L81

**Comment by matthawley** [comment]
Also, it seems this doesn't take into consideration `EnumMemberAttribute` for the member name either.

**Comment by matthawley** [comment]
Actually, the more I think about it - it's not that it doesn't respect enum naming conventions, it doesn't respect json serialization naming conventions as it's being treated as a property vs. a list of enum values.

**Comment by matthawley** [comment]
Here's a filter I wrote in case anyone else needs it.

```
public void Apply(OpenApiSchema schema, SchemaFilterContext context)
{
    if (schema.Properties.Count == 0)
    {
        return;
    }

    CamelCaseNamingStrategy camelCaseStrategy = new CamelCaseNamingStrategy();
    PropertyInfo[] properties = context.Type.GetProperties();
    foreach (KeyValuePair<string, OpenApiSchema> property in schema.Properties)
    {
        if (property.Value.Type != "object" ||
            property.Value.Properties.Count == 0)
        {
            continue;
        }

        PropertyInfo info = properties.SingleOrDefault(x => x.Name.Equals(property.Key, StringComparison.OrdinalIgnoreCase));
        if (null == info ||
            false == info.PropertyType.IsDictionary(out Type keyType, out Type valueType) ||
            false == keyType.IsEnum)
        {
            continue;
        }

        Dictionary<string, OpenApiSchema> newProperties = new Dictionary<string, OpenApiSchema>();

        foreach (KeyValuePair<string, OpenApiSchema> subProperty in property.Value.Properties)
        {
            newProperties.Add(
                camelCaseStrategy.GetPropertyName(subProperty.Key, false),
                subProperty.Value);
        }

        property.Value.Properties = newProperties;
    }
}
```

**Comment by phosphene47** [comment]
Relevant/duplicate: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1356

**Comment by domaindrivendev** [comment]
Closing - will be tracked in duplicate referenced above.
