### ISSUE TITLE
Hidden property not existant on OpenAPIParamter

### ISSUE THREAD

**Issue by ddeisadzevp** [domaindrivendev/Swashbuckle.AspNetCore#1493]
Wondering if this is a bug or a feature that was left out but swagger `ApiParam(hidden)` does not seem to be existant in `OpenApiParamter.` Is there something similar that this (http://docs.swagger.io/swagger-core/current/apidocs/io/swagger/annotations/ApiParam.html#hidden()) translates to in Swashbuckle.AspNetCore?

**Comment by domaindrivendev** [comment]
Could you please elaborate on your specific use case. For example, why do you want to hide the parameter in question?

**Comment by ddeisadzevp** [comment]
I have a URL parameter on a request that I do not want exposed via swagger.

**Comment by ddeisadzevp** [comment]
Wanted to see if there was anything built-in before I go about writing a custom attribute for the parameter.

**Comment by domaindrivendev** [comment]
I gather it’s a parameter you want to hide. But why? Is it a secret parameter or something. Just trying to understand the use case

**Comment by ddeisadzevp** [comment]
Yes, the use case is : we want to flag a runtime variable but it would confuse consumers of that API if they were to see that flag. E.g. If we are publishing data to prod and we want to have a identifier to switch to staging to run regression tests.

**Comment by domaindrivendev** [comment]
Nothing built-in for this use case, so I would suggest you proceed with a custom attribute
