### ISSUE TITLE
ApiVersionDescriptions without having to get ServiceProvider .NET Core 3

### ISSUE THREAD

**Issue by JohnGalt1717** [domaindrivendev/Swashbuckle.AspNetCore#1497]
As of .NET Core 3 it warns about creating an extra Service Provider in the Startup.cs file. Is there another way to get the ApiVersions that doesn't require that you do this?

IE the old recommended way was:

var provider = serviceProvider.GetRequiredService<IApiVersionDescriptionProvider>();
foreach (var description in provider.ApiVersionDescriptions) {...}

Is there a way to do this without serviceProvider?

**Comment by johankvint** [comment]
I did like this, if someone else have the same problem

```
public void Configure(IApplicationBuilder app, IApiVersionDescriptionProvider provider)
{
    ....
    app.UseSwaggerUI(c =>
    {
        foreach (var description in provider.ApiVersionDescriptions)
        {
            c.SwaggerEndpoint(
                $"/swagger/{description.GroupName}/swagger.json",
                description.GroupName.ToUpperInvariant()
            );
        }
    });
}
```

**Comment by JohnGalt1717** [comment]
@johankvint  That's fine for the Configure Method. But you first have to call AddSwaggerGen and options.SwaggerDoc has to be called for every version. Meaning you have to generate a provider in the ConfigureServices method to do that.

The problem is the ConfigureServices having to have a provider, not the Configure function's injection that creates the endpoint to said document.

**Comment by johankvint** [comment]
Ah sorry missed that. For that I did like this:

```
public class ConfigureSwaggerOptions : IConfigureOptions<SwaggerGenOptions>
{
    readonly IApiVersionDescriptionProvider provider;

    public ConfigureSwaggerOptions(IApiVersionDescriptionProvider provider) =>
    this.provider = provider;

    public void Configure(SwaggerGenOptions options)
    {
        foreach (var description in provider.ApiVersionDescriptions)
        {
            options.SwaggerDoc(description.GroupName, new OpenApiInfo
            {
                Version = description.ApiVersion.ToString(),
                Title = $"API v{description.ApiVersion}",
            });
        }
    }
}
```

and then add it with DI

`services.AddSingleton<IConfigureOptions<SwaggerGenOptions>, ConfigureSwaggerOptions>();`

**Comment by jhancock4d** [comment]
So while that may work, that's a hack. The AddSwaggerGen function needs to take a second param of either the provider or the ApiVersionDescriptions (or some other construct that includes the ApiVersionDescriptions and could contain other stuff later) and just work because as it is now, it's broken in .net core 3.

**Comment by commonsensesoftware** [comment]
@jhancock4d it's actually not a hack. The **IApiVersionDescriptionProvider** is provided by [API Versioning](https://github.com/microsoft/aspnet-api-versioning) and not by Swashbuckle or even ASP.NET. While I would agree the synergy _could_ be better, connecting all the pieces via DI is a common and sensible mechanism. This has been the recommend and provided example (as opposed to creating a temporary provider) for nearly 2 years, which would have been back in the ASP.NET Core 2.2 days. This can definitely be made to work properly in .NET Core 3.0. I hope that helps clarify things.

**Comment by jhancock4d** [comment]
@commonsensesoftware then the samples and examples need to be updated to do this properly instead of the way that they show.

**Comment by commonsensesoftware** [comment]
@jhancock4d if you're referring to the API Versioning samples/examples, they have been updated as described for almost 2 years. You'll want to review [ConfigureSwaggerOptions.cs](https://github.com/microsoft/aspnet-api-versioning/blob/master/samples/aspnetcore/SwaggerSample/ConfigureSwaggerOptions.cs) and [Startup.cs](https://github.com/microsoft/aspnet-api-versioning/blob/master/samples/aspnetcore/SwaggerSample/Startup.cs#L57). I wouldn't expect Swashbuckle to ever include these examples; maybe a link. I hope that helps.
