### ISSUE TITLE
[5.0.0] using Newtonsoft JsonProperty and defining propertyName does NOT generate description

### ISSUE THREAD

**Issue by jlouros** [domaindrivendev/Swashbuckle.AspNetCore#1498]
### Configuration:

1. ASP.Net Core 3.1 web application
2. _Swashbuckle.AspNetCore_ version 5.0.0
3. _Swashbuckle.AspNetCore.Annotations_ version 5.0.0
4. _Swashbuckle.AspNetCore.Newtonsoft_ version 5.0.0
5. setup `Startup.ConfigureServices()` to use Newtonsoft `services.AddSwaggerGenNewtonsoftSupport();`
6. setup to generate XML documentation file

### Issue:

For properties using `Newtonsoft.Json.JsonPropertyAttribute(string propertyName)` (defining _propertyName_ parameter) description is **NOT** generated. See: https://github.com/JamesNK/Newtonsoft.Json/blob/a31156e90a14038872f54eb60ff0e9676ca4a0d8/Src/Newtonsoft.Json/JsonPropertyAttribute.cs#L214-L221

However, is the default .ctor of `Newtonsoft.Json.JsonPropertyAttribute()` is used, the property description is generated as expected.

### Example:

```csharp
public class Entity
{
    /// <summary>
    /// description is generated as expected
    /// </summary>
    public string ThisWorks { get; set; }

    /// <summary>
    /// this also works, description is generated as expected
    /// </summary>
    [Newtonsoft.Json.JsonProperty]
    public string WithDefaultJsonPropertyThisWorks { get; set; }

    /// <summary>
    /// defining propertyName of JsonProperty does NOT generate description
    /// </summary>
    [Newtonsoft.Json.JsonProperty("this-will-not-work")]
    public string ThisWillNotWork { get; set; }
}
```
Swagger v2 output (in OpenAPI 3.0 description is not generated as well)
```json
{
    "swagger": "2.0",
    "info": ...,
    "paths": ...,
    "definitions": {
        "TestEntity": {
            "type": "object",
            "properties": {
                "thisWorks": {
                    "description": "description is generated as expected",
                    "type": "string"
                },
                "withDefaultJsonPropertyThisWorks": {
                    "description": "this also works, description is generated as expected",
                    "type": "string"
                },
                "this-will-not-work": {
                    "type": "string"
                    // BUG: notice missing description
                }
            }
        }
    }
}
```

This is a new issue with version 5.0.0. In the previous version (4.0.1) it was working as expected.

**Comment by jlouros** [comment]
To replicate this issue, please check the following branch: https://github.com/jlouros/Swashbuckle.AspNetCore/tree/json-property-issue

**Comment by pvdberge** [comment]
The same issue occurs when using the System.Runtime.Serialization.DataMember attribute with Name property set instead of the JsonProperty attribute.
```cs
/// <summary>
/// defining Name of DataMember does NOT generate description
/// </summary>
[System.Runtime.Serialization.DataMember(Name = "this-will-not-work")]
public string ThisWillNotWork { get; set; }
```

**Comment by jlouros** [comment]
To be exact, the problem is with this code:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/e4402e3872462e7e42dc4baa58b7a2a0e0fb3f51/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs#L31-L40

local variable `propertyName` is set with the overridden property name defined with `Newtonsoft.Json.JsonProperty`, but `context.Type.GetMember()` uses the property name defined in the class.

**Comment by gbrown-ce** [comment]
I'm still seeing this issue with the latest version.

**Comment by toddschilling** [comment]
> I'm still seeing this issue with the latest version.

Did you use the configuration shown at the beginning of this issue?  Specifically...

* Add reference to Swashbuckle.AspNetCore.Newtonsoft
* Update Startup.ConfigureServices() to call services.AddSwaggerGenNewtonsoftSupport();

**Comment by gbrown-ce** [comment]
Yes I believe we staightened this out. Thanks!
