### ISSUE TITLE
SecurityRequirementsOperationFilter invalid

### ISSUE THREAD

**Issue by nianwu** [domaindrivendev/Swashbuckle.AspNetCore#1507]
when i set [Authorize] on controller class , requiredScopes is empty, so I made the following changes
```C#
// Policy names map to scopes
var requiredScopes = context.MethodInfo
    .GetCustomAttributes(true)
    .OfType<AuthorizeAttribute>()
    // my change
    .Union(context.ApiDescription.ActionDescriptor.EndpointMetadata.OfType<AuthorizeAttribute>())
    // end my change
    .Select(attr => attr.Policy)
    .Distinct();
```

**Comment by wswind** [comment]
> when i set [Authorize] on controller class , requiredScopes is empty, so I made the following changes
> 
> ```cs
> // Policy names map to scopes
> var requiredScopes = context.MethodInfo
>     .GetCustomAttributes(true)
>     .OfType<AuthorizeAttribute>()
>     // my change
>     .Union(context.ApiDescription.ActionDescriptor.EndpointMetadata.OfType<AuthorizeAttribute>())
>     // end my change
>     .Select(attr => attr.Policy)
>     .Distinct();
> ```


This is very helpful, thanks. I think this should  be merged into 
test/WebSites/OAuth2Integration/ResourceServer/Swagger/SecurityRequirementsOperationFilter.cs
