### ISSUE TITLE
How to add my token to the header of my http request?

### ISSUE THREAD

**Issue by zh-wowtv** [domaindrivendev/Swashbuckle.AspNetCore#151]
I know this is a swagger-ui issue (I even can't find index.html in my project). But I don't know where is the code or configuration for swagger-ui in Swashbuckle. What I want is to add a token to every request after I got the token. What should I do? Thanks.

**Comment by LRPalacios** [comment]
Any updates on this? In my case i need to add a custom http header,

**Comment by SimonTouchtech** [comment]
This might be what you're looking for: https://docs.asp.net/en/latest/tutorials/web-api-help-pages-using-swagger.html#customizing-the-ui

**Comment by domaindrivendev** [comment]
@zh-wowtv. Can you elaborate a little more on your requirements?

Swagger has built in support for defining security schemes and specifying security requirements per operation in your API (see http://swagger.io/specification/#securityDefinitionsObject and http://swagger.io/specification/#securityRequirementObject). If you're scheme is one of the supported types (e.g. apiKey, oauth2 etc.), then you can configure it in _Startup.cs_ and the UI will automatically provide authentication capabilities via the "Authorize" button. Check out the example Website which demonstrates this setup for OAuth2:

Alternatively, you can simply add an additional "header" parameter to your operation descriptions. This will cause a corresponding field to be rendered in the UI where you can enter the token value. You can do this with a custom Operation Filter (see readme). Here's an example of what your filter might look like:

    public class AddTokenHeaderParameter : IOperationFilter
    {
        public void Apply(Operation operation, OperationFilterContext context)
        {
            if (operation.parameters == null)
                operation.parameters = new List<Parameter>();

            operation.parameters.Add(new Parameter
                {
                    name = "Token",
                    @in = "header",
                    type = "string",
                    required = true
                });
        }
    }

**Comment by ZeekoZhu** [comment]
add a new class to define your own schema of auth
```
using System.Collections.Generic;
using Swashbuckle.Swagger.Model;
using Swashbuckle.SwaggerGen.Generator;

namespace Hive.Web.Filters
{
    public class AddAuthTokenHeaderParameter : IOperationFilter
    {
        public void Apply(Operation operation, OperationFilterContext context)
        {
            if (operation.Parameters == null)
                operation.Parameters = new List<IParameter>();

            operation.Parameters.Add(new HeaderParameter()
            {
                Name = "AuthToken",
                In = "header",
                Type = "string",
                Required = false
            });

        }
    }

    class HeaderParameter : NonBodyParameter
    {
    }
}
```

add operation filter
```
services.AddSwaggerGen(c =>
            {
                c.SingleApiVersion(new Info()
                {
                    Version = "v1",
                    Title = "title",
                    Description = "Description"
                });
                c.OperationFilter<AddAuthTokenHeaderParameter>();
            });
```

refresh your swagger UI page

**Comment by ZeekoZhu** [comment]
So, is there any way to use a Attribute to make it more easier and flexible? @domaindrivendev

**Comment by domaindrivendev** [comment]
Do you use an attribute to enforce the security requirement in the first place - e.g. AuthorizeAttribute?

Ideally, you're operation filter would add the token if such an attribute were present. This is the SB philosophy - use the implementation to drive living documentation instead of documentation specific attributes that can easily go out of sync with actual behavior

**Comment by ZeekoZhu** [comment]
@domaindrivendev yeah, you are right. So I changed the `Apply` method:
```
public void Apply(Operation operation, OperationFilterContext context)
        {
            if (operation.Parameters == null)
                operation.Parameters = new List<IParameter>();
            var attrs = context.ApiDescription.GetActionAttributes();
            foreach (var attr in attrs)
            {
                if (attr.GetType() == typeof(Auth))
                {
                    operation.Parameters.Add(new HeaderParameter()
                    {
                        Name = "AuthToken",
                        In = "header",
                        Type = "string",
                        Required = false
                    });
                }
            }
        }
```

**Comment by FACAMK** [comment]
I've setup the swagger with the following:
Swagger:
c.BasicAuth("basic").Description("Basic HTTP Authentication");
c.ApiKey("Authorization", "header", "OAuth bearer token");
SwaggerUI:
c.ApiKeySupport("Authorization", "header");

and this Operation is applied:

public class AssignAuthenticationSecurityRequirements : IOperationFilter
        {
            public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
            {
                // Correspond each "Authorize" role to an oauth2 scope
                var scopes = apiDescription.ActionDescriptor.GetFilterPipeline()
                    .Select(filterInfo => filterInfo.Instance)
                    .OfType<AuthorizeAttribute>()
                    .SelectMany(attr => attr.Roles.Split(','))
                    .Distinct();

                if (scopes.Any())
                {
                    if (operation.security == null)
                        operation.security = new List<IDictionary<string, IEnumerable<string>>>();

                    var oAuthRequirements = new Dictionary<string, IEnumerable<string>>
                    {
                        { "basic", scopes },
                        { "apiKey", scopes },
                        { "bearer", scopes }
                    };

                    operation.security.Add(oAuthRequirements);
                }
            }
        }

The basic Auth works fine, but the Token auth doesnt work at all.

Any way to make this work?
.Net Version: 4.6.2
Swagger version: 8.3.10.2

**Comment by awais-ilyas** [comment]
```
public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            if (operation.parameters != null)
            {
                operation.parameters.Add(new Parameter
                {
                    name = "Authorization",
                    @in = "header",
                    description = "access token",
                    required = false,
                    type = "string"
                });
            }
        }
```

I'm unable to add token in HTTP GET request, however I can add token in POST request. Please let me know, what I'm missing?

**Comment by kashish52** [comment]
@awais-ilyas  you are not getting the toke on get request because you are only adding the Authorization to those requests which already have some parameters (if conditions). Since get requests don't have the parameters  you are not getting it in the get request. If you want to add Authorization to GET requests also do something  like this:
```
public void Apply(Swashbuckle.Swagger.Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
	{

            if (operation.parameters == null)
                operation.parameters = new List<Parameter>();
            operation.parameters.Add(new Parameter
            {
                name = "Authorization",
                @in = "header",
                description = "access token",
                required = true,
                type = "string"
            });
        }
```
or take a look at @ZeekoZhu  Answer above
