### ISSUE TITLE
[Feature] Add schema filters using lambda

### ISSUE THREAD

**Issue by kant2002** [domaindrivendev/Swashbuckle.AspNetCore#1514]
I think it can be useful for Swashbuckle to have simplified definition of different kind of filters.
Right for cases like #1488 you have to write very simple class. Same for enum juggling with "x-ms-enum". 

Essentially these classes is just glorified functions. This can be better reflected in the configuration API. 

## Proposed change.

```
class SwaggerGenOptionsExtensions
{
     public void SchemaFilter(Action<OpenApiSchema, SchemaFilterContext> filter);
     public void ParameterFilter(Action<OpenApiParameter, ParameterFilterContext> filter);
     public void OperationFilter(Action<OpenApiOperation, OperationFilterContext> filter);
     public void DocumentFilter(Action<OpenApiDocument, DocumentFilterContext> filter);
}
```

**Comment by domaindrivendev** [comment]
The filters are a little more than glorified functions because they are DI aware. That is, they can be created with dependencies automatically (constructor) injected from your applications DI container, which can be very useful.

Personally, I don't see too much relative value in the change you've proposed. Thanks for the suggestion though.

**Comment by kant2002** [comment]
@domaindrivendev The value as I see it was, to slightly simplify the API around Swashbuckle. Right now I constantly have to augment something to make it work with serialization magic. Most of the time it is simple filters like `ReverseAllOfPropertiesFilter` in the originally mentioned issue. When I build web applications in ASP.NET I split them on separate web application each of them has their own Swashbuckle which used for produce separate client library. After that all that applications merged in one big app, and then I suddenly has to copy all these smallish filters around the applications. Given that nature of all my customisation is just glorified functions, that's why the proposal.
