### ISSUE TITLE
Enum query parameter documented as int values

### ISSUE THREAD

**Issue by mercer** [domaindrivendev/Swashbuckle.AspNetCore#1515]
Swagger api for an endpoint that accepts an enum query is generated as in values.

I'm with Swashbuckle.AspNetCore.SwaggerGen 5.0.0 and netcoreapp2.2

![image](https://user-images.githubusercontent.com/95358/73672947-7ccca500-46b6-11ea-8305-945ead363cec.png)

The enum I use

![image](https://user-images.githubusercontent.com/95358/73672827-4131db00-46b6-11ea-9c3b-aa09d06781a4.png)

My controller

![image](https://user-images.githubusercontent.com/95358/73672878-5c9ce600-46b6-11ea-81a5-707ffb3f4bc0.png)

Generated swagger api

![image](https://user-images.githubusercontent.com/95358/73672908-6cb4c580-46b6-11ea-8168-84d9e9e868cb.png)

Swashbuckle.AspNetCore.SwaggerGen 4.0.0 used to generate proper enum values

![image](https://user-images.githubusercontent.com/95358/73673082-bac9c900-46b6-11ea-91e8-74799f01af0a.png)

**Comment by domaindrivendev** [comment]
Dup of #1459. TL;DR this version defaults to honoring `System.Text.Json` (as opposed to `Newtonsoft`) serializer behavior. You need to expicitly opt-in to honoring Newtonsoft as described [here in the readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft)

**Comment by mercer** [comment]
I'm with `netcoreapp2.2`, does this still apply? https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft talks about netcoreapp3.0

**Comment by mercer** [comment]
It does apply; problem solved

![image](https://user-images.githubusercontent.com/95358/73745591-139f6d00-475c-11ea-9f11-bb5c8111549d.png)
