### ISSUE TITLE
Duplicated entries in custom ApiError with ProducesResponseType annotation

### ISSUE THREAD

**Issue by mercer** [domaindrivendev/Swashbuckle.AspNetCore#1516]
After I annotate my controller with ProducesResponseType I get duplicated statusCodes.

I'm with Swashbuckle.AspNetCore.SwaggerGen 5.0.0 and netcoreapp2.2

![image](https://user-images.githubusercontent.com/95358/73673501-6541ec00-46b7-11ea-9a97-e005b62c9f80.png)

![image](https://user-images.githubusercontent.com/95358/73673433-4ba0a480-46b7-11ea-8e65-ad7796d90764.png)

![image](https://user-images.githubusercontent.com/95358/73673455-522f1c00-46b7-11ea-9581-7d1f96eb1452.png)

**Comment by domaindrivendev** [comment]
You're misinterpreting the Swagger JSON that's being returned. The snippet you're showing IS NOT listing the status codes returned by a given operation, it's describing what a serialized `ApiError` would look like (seing as you specified as the being the type that's returned with a 404 response). As part of that _description_, it's stating that the `ApiError` type has a property on it called `statusCode` and that the value can be any one of the listed values

**Comment by domaindrivendev** [comment]
You may want to read the official [Swagger / Open API specification] for a better understanding of the data that Swashbuckle generates and returns.

**Comment by mercer** [comment]
I'm not the only one misinterpreting that data, https://github.com/OpenAPITools/openapi-generator uses it to generate a bad client.

But thanks for helping me out.

**Comment by mercer** [comment]
AddSwaggerGenNewtonsoftSupport solved the problem for me
