### ISSUE TITLE
CLI Tool for version 5.0.0 not running as post build argument for dotnet 2.1 project

### ISSUE THREAD

**Issue by sorvis** [domaindrivendev/Swashbuckle.AspNetCore#1517]
I'm testing out upgrading our application from using version 4.0.1 to 5.0.0 of the CLI tool. To install I followed the current directions in the readme.md file by using the "dotnet-tools.json" file.

When I run the following command:

`dotnet swagger tofile --output "../../docs/swagger/swagger_v1.json" E:\git\Mock.Service\src\Mock.ServicesHost\bin\Debug\netcoreapp2.1\Mock.ServicesHost.dll "v1"`

I'm seeing this output in response:
`The specified deps.json [E:gitMock.ServicesrcMock.ServicesHostbinDebugnetcoreapp2.1Mock.ServicesHost.deps.json] does not exist`

From the error message it appears that it scrubbed all the slashes from the path to the dll?

**Comment by sorvis** [comment]
Update on this issue I suspect that my path with slashes being removed come in as a result of me trying to run the command in git bash for windows.

The real underlying error I believe is this:

>  Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Loader, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>      at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
>      at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
>      at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
>      at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 106
> 
>   Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Loader, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>      at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
>      at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
>      at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
>      at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 106

Which I appears to be related to the fact that I am running this for a netcoreapp2.1 project not 3.0. I suspect this because of the special including of System.Runtime.Loader in _Swashbuckle.AspNetCore.Cli_ for dotnet 2.1
![image](https://user-images.githubusercontent.com/1037467/73883442-f4730f00-4831-11ea-9fdc-f9b1f5b6e63c.png)

Now I'm suspecting that somehow when I run the command _dotnet swagger_ its picking up the wrong runtime version of the tool from when I ran command to install it.
`dotnet tool install swashbuckle.aspnetcore.cli --version 5.0.0`

**Comment by sorvis** [comment]
We've discovered that version 5.0.0-rc4 of the cli tool fixes this issue (my coworker says rc2 works as well).

**Comment by woeterman94** [comment]
Still having this issue in 5.3.1. It keeps saying that my deps.json does not exist. While the path is correct
