### ISSUE TITLE
Enum in [QueryString] object has invalid format

### ISSUE THREAD

**Issue by WhitWaldo** [domaindrivendev/Swashbuckle.AspNetCore#1520]
We're using Swashbuckle.AspNetCore 5.0.0. In our controller, we have the following method:

`public async Task<ActionResult<List<MyObject>>> ListObjects(Guid objId, [FromQuery]ResourceParameters resourceParameters)`

The ResourceParameters class looks like:

```
public class ResourceParameters {
  public MatchType? FilterByType {get;set;}
}
```

And finally, our MatchType is an enum looking like:

```
[DataContract]
public enum MatchType {
  [EnumMember(Value="all")]
  All,
  [EnumMember(Value="any")]
  Any
}
```

The relevant parameters output of the generated Swagger file looks like:
```
"parameters": [
          {
            "in": "path",
            "name": "objId",
            "required": true,
            "type": "string",
            "format": "uuid"
          },
          {
            "in": "query",
            "name": "FilterByType"
          }
]
```

Now, I've got an ISchemaFilter in place so I can pull the values for enums out of the [EnumMember] attributes I've got on each of them anyway:
```
    public class DescribeEnumMemberValues : ISchemaFilter
    {
        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            if (context.Type.IsEnum)
            {
                schema.Enum.Clear();

                //Retrieve each of the values decorated with an EnumMember attribute
                foreach (var member in context.Type.GetMembers())
                {
                    var memberAttr = member.GetCustomAttributes(typeof(EnumMemberAttribute), false).FirstOrDefault();
                    if (memberAttr != null)
                    {
                        var attr = (EnumMemberAttribute) memberAttr;
                        schema.Enum.Add(new OpenApiString(attr.Value));
                    }
                }
            }
        }
    }
```

So, later on in the Swagger output, the enum will show up under definitions as:
```
    "MatchType": {
      "enum": [
        "all",
        "any"
      ],
      "type": "string"
    },
```

In the case of this controller method, the output Swagger fails to use this definition, so I get the following validation failure at [https://editor.swagger.io/](https://editor.swagger.io/)

> Structural error at paths.//obj/list.get.parameters.1
> should have required property 'type'
> missingProperty: type
> Jump to line 732
> Structural error at paths.//obj/list.head.parameters.1
> should have required property 'type'
> missingProperty: type
> Jump to line 817

Either line just points to a value similar to my Swagger properties in the third code sample above. Why is the type parameter being excluded here?

**Comment by domaindrivendev** [comment]
Dup of #1329. Long story short, use the `UseInlineDefinitionsForEnums`.
