### ISSUE TITLE
[5.0.0] Nuget error with dotnet core

### ISSUE THREAD

**Issue by isetr** [domaindrivendev/Swashbuckle.AspNetCore#1524]
We've been using this package for our project for a while now. Migrating to dotnet core 3.0, we updated to 5.0.0-rc4.

For a while it was working without issues, but for a few days/weeks now NuGet shows an error at every build (the project builds, but the errors are still there):

```
NU1202: Package Swashbuckle.AspNetCore.Cli 5.0.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Swashbuckle.AspNetCore.Cli 5.0.0 supports:
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
  - netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any
NU1212: Invalid project-package combination for Swashbuckle.AspNetCore.Cli 5.0.0. DotnetToolReference project style can only contain references of the DotnetTool type 
```

---

For reproduction I just created a new dotnet core console app with the project file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="5.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Swashbuckle.AspNetCore.Cli" Version="*" />
  </ItemGroup>
</Project>
```

**Comment by isetr** [comment]
Update:

Removing the following lines from the .csproj makes the error disappear:
```
  <ItemGroup>
    <DotNetCliToolReference Include="Swashbuckle.AspNetCore.Cli" Version="*" />
  </ItemGroup>
```

The error is still a problem since it says it works with netcoreapp3.0.

**Comment by domaindrivendev** [comment]
Please have a read through this - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#retrieve-swagger-directly-from-a-startup-assembly

Rather than using DotNetCliToolReference, you now install the CLI as a .NET Core Global Tool.
