### ISSUE TITLE
Redoc Theme

### ISSUE THREAD

**Issue by markdulfer** [domaindrivendev/Swashbuckle.AspNetCore#1527]
Hi,

Not sure if I'm doing something wrong or not, but I'm trying to use custom themeing on a Redoc layout. To get it to work I had to do this:

In C# I'm reading the theme file off disk and adding to the ConfigObject.AdditionalItems (as the doc says to do):
```
var theme = System.IO.File.ReadAllText(ThemeFile);
configObject.AdditionalItems.Add("theme", Newtonsoft.Json.JsonConvert.DeserializeObject(theme));
```

but to actually get it to apply the them, in the index.html file I had to do this:

```
for (var k in configObject.additionalItems) {
   if (configObject.additionalItems.hasOwnProperty(k)) {
      configObject[k] = configObject.additionalItems[k];
}
Redoc.init(swagger, configObject,...);
```

The additional items are where the theme object ends up, but Redoc doesn't read from there. Redoc needs the theme object as a property on the root configObject.

Thanks.

**Comment by domaindrivendev** [comment]
If I'm undestanding your issue correctly - I don't seem to be able to repro it. That is, when I add the following in the C# config:

```csharp
c.AdditionalItems.Add("theme", new object { foo = "bar" });
// using dummy object here but should be sufficient to test this out
```

The "theme" property is correctly added as a property on the root `configObject`.

**Comment by domaindrivendev** [comment]
If you're still seeing this issue with the latest version (`5.6.3` at time of writing), please create a minimal app (i.e. starting from empty proj) that repro's it and post to github so I can pull down and troubleshoot.

**Comment by markdulfer** [comment]
I can no longer reproduce with the latest version.

Thanks for the follow-up.
