### ISSUE TITLE
Newtonsoft SnakeCaseNamingStrategy causes missing XML comments for multiple word property names?

### ISSUE THREAD

**Issue by nootnoot20** [domaindrivendev/Swashbuckle.AspNetCore#1537]
Hi, I'm running into a weird issue with XML comments using Swashbuckle.AspNetCore 5.0.0.

1. Newtonsoft's `NamingStrategy` was set to `SnakeCaseNamingStrategy`.

```
    public void ConfigureContainer(ServiceRegistry services)
    {
        services
            .AddMvc()
            .AddNewtonsoftJson(options =>
            {
                options.SerializerSettings.ContractResolver = new DefaultContractResolver()
                {
                    NamingStrategy = new SnakeCaseNamingStrategy()
                };
            });
    }
```

2. XML comments were included while calling `AddSwaggerGen` and `AddSwaggerGenNewtonsoftSupport` was called.
3. XML comments were added to a model.

```
    public class Address
    {
        /// <summary>
        /// Address 1.
        /// </summary>
        public string Address1 { get; set; }

        /// <summary>
        /// Address 2.
        /// </summary>
        public string Address2 { get; set; }

        /// <summary>
        /// City.
        /// </summary>
        public string City { get; set; }

        /// <summary>
        /// State.
        /// </summary>
        public string State { get; set; }

        /// <summary>
        /// Post Code.
        /// </summary>
        public string PostCode { get; set; }

        /// <summary>
        /// Country.
        /// </summary>
        public string Country { get; set; }
    }
```
4. Any property with multiple words that is changed into snake case by `Newtonsoft` doesn't load the XML comments into the Swagger documentation.
e.g. https://i.stack.imgur.com/thJxV.jpg
`PostCode` becomes `post_code` and loses its XML comments because of the underscore. The XML comments work as expected for properties without underscores and whenever `SnakeCaseNamingStrategy` is disabled.

Have I done something wrong or could this be an issue with Swashbuckle or Newtonsoft?

**Comment by jamarino** [comment]
I ran into the exact same issue today ☹️
