### ISSUE TITLE
Please consider making IOperationFilter.Apply an asychronous operation

### ISSUE THREAD

**Issue by gingters** [domaindrivendev/Swashbuckle.AspNetCore#1538]
Please consider making the method `Apply` of the `IOperationFilter` asynchronous.

I know this will be a breaking change (unless an `IAsynchronousOperationFilter` will be introduced for that), so here is my reasoning.

One thing that needs to be done with an `IOperationFilter` is to check whether the method or controller of the API needs authentication. In ASP.NET Core the concept of Policies has been introduced. So the `AuthorizeAttribute` provides us with a policy name, and nothing more.

We now need to load the policy to check whether it has requirements that require a) a logged in user (it might also accept anonymous users), and b) if there are any scopes required which we should add to the OpenApiSecurityRequirements.

For loading the policies, ASP.NET Core Authorization offers us the `IAuthorizationPolicyProvider` interface with the `Task<AuthorizationPolicy> GetPolicyAsync(string policyName)` method. This can't be called safely from our `IOperationFilter.Apply()` method as it is asynchronous. Calling an asynchronous method from a synchronous context is considered bad practice and might even end up in deadlocks.

To be able to support asynchronous APIs provided by ASP.NET Core in our OperationFilter it would be great if the filter would provide an asynchronous API itself.

**Comment by Akridian** [comment]
Faced same issue.

**Comment by martincostello** [comment]
Closing in favour of #1661 to add async support for filters in general.
