### ISSUE TITLE
servers versioning

### ISSUE THREAD

**Issue by FlorenciaNodar** [domaindrivendev/Swashbuckle.AspNetCore#1540]
I need to use servers and define variables such as the path all from .net core.
Do you have any example of versioning and using servers with version? without the version having the methods.

**Comment by domaindrivendev** [comment]
As per the [contributing guidelines](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/CONTRIBUTING.md), this feels like more of a question that an issue report and therefore should be posted to StackOverflow. Thanks
