### ISSUE TITLE
Upgrade from 4.0 to 5.0 with .NetCore 3.1 Oath2 not working

### ISSUE THREAD

**Issue by jonnymec** [domaindrivendev/Swashbuckle.AspNetCore#1543]
My code before the upgrade was 
`               c.AddSecurityDefinition("implicit", new OAuth2Scheme
                {
                    Type = "oauth2",
                    Flow = "implicit",
                    AuthorizationUrl = $"{identityServerConfiguration.Authority}connect/authorize",
                    Scopes = new Dictionary<string, string>()
                });
                c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
                {
                    {"implicit", new List<string> {identityServerConfiguration.RequiredScopes}}
                });`

After Upgrade:
`                var oauth2scheme = new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.OAuth2,
                    Flows = new OpenApiOAuthFlows
                    {
                        Implicit = new OpenApiOAuthFlow
                        {
                            AuthorizationUrl = new Uri($"{identityServerConfiguration.Authority}connect/authorize"),
                            Scopes = new Dictionary<string, string>()
                        }
                    }
                };
                c.AddSecurityDefinition("oauth2", oauth2scheme);
                c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {oauth2scheme, new List<string>{ identityServerConfiguration.RequiredScopes } }
                });`
It seems like authorizing in the swagger ui works, but all of my API calls now return 401, when they were working just fine with SB 4.0 and .NetCore 2.2.  Is this a bug, or am I missing something?

**Comment by UNOPARATOR** [comment]
Comparing your code "After Upgrade" with a working code from one of my projects, I believe you should change this part of your code:
```c#

Scopes = new Dictionary<string, string>()
```
into this:
```c#
Scopes = new Dictionary<string, string>() { { identityServerConfiguration.RequiredScopes, "NameOfYourApiName" } }
```

**Comment by UNOPARATOR** [comment]
On second look there are other differences too.
So here is my working sample code if you would like to try it out which supports implicit and client credentials: *(some parts are omitted and some renamed according to your sample code)*
```c#
//...
        public void ConfigureServices(IServiceCollection services)
        {
//...
            services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = identityServerConfiguration.Authority;
                    options.ApiName = "NameOfYourApiName";
                    //#if DEBUG
                    options.RequireHttpsMetadata = false;
                    //#else
                    //  options.RequireHttpsMetadata = true;
                    //#endif
                });

            //services.AddAuthorization(options =>
            //{
            //    options.AddPolicy("nameOfPolicy",
            //        policy => policy.RequireRole("nameOfRole"));
            //});

            services.AddSwaggerGen(c =>
            {
                ...
                c.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.OAuth2,
                    Flows = new OpenApiOAuthFlows
                    {
                        Implicit = new OpenApiOAuthFlow
                        {
                            AuthorizationUrl = new Uri($"{identityServerConfiguration.Authority}/connect/authorize"),
                            Scopes = new Dictionary<string, string>
                            {
                                { identityServerConfiguration.RequiredScopes, "NameOfYourApiName" }
                            }
                        },
                        ClientCredentials = new OpenApiOAuthFlow
                        {
                            TokenUrl = new Uri($"{identityServerConfiguration.Authority}/connect/token"),
                            Scopes = new Dictionary<string, string>
                            {
                                { identityServerConfiguration.RequiredScopes, "NameOfYourApiName" }
                            }
                        }
                    }
                });
                c.AddSecurityRequirement(new OpenApiSecurityRequirement {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "oauth2" }
                        },
                        new[] { identityServerConfiguration.RequiredScopes }
                    }
                });
            });
//...
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IdentityServerApiConfiguration identityServerApiConfiguration)
        {
//...
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("./swagger/v1/swagger.json", $"{ApiConfigurationConsts.ApiName} {ApiConfigurationConsts.ApiVersionV1}");
                c.RoutePrefix = string.Empty;
                c.DocumentTitle = ApiConfigurationConsts.ApiName;
                c.EnableFilter();
                c.DefaultModelsExpandDepth(-1); // Hide models in Swagger UI
                c.DisplayRequestDuration();

                c.OAuthClientId(identityServerApiConfiguration.OidcSwaggerUIClientId);
                c.OAuthAppName(ApiConfigurationConsts.ApiName);
            });

            app.UseAuthentication();

            app.UseAuthorization();
//...
        }
//...
```

**Comment by mwwski** [comment]
@UNOPARATOR  awesome! saved me hours of wondering why it does not work!

**Comment by domaindrivendev** [comment]
Closing as this is a usage question (which looks to be answered above) as opposed to a bug or feature request. As per the [contributing guidelines](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/CONTRIBUTING.md) general questions should be posted to STACKOVERFLOW instead of the project issue list
