### ISSUE TITLE
SerializeAsV2 not respected

### ISSUE THREAD

**Issue by santesem-links** [domaindrivendev/Swashbuckle.AspNetCore#1548]
Hi,
I have recently update this package (from NuGet version v5.0.0-RC5) to v5.0.0, and the command  **SerializeAsV2** was not respected.

For example, in the swagger.json the keyword "**allOf**" was added, but this is not compliant with swagger 2.0 specs.

![image](https://user-images.githubusercontent.com/43367666/75863356-9cafcf80-5e00-11ea-9e13-e27731ea9a31.png)

Picture: both with SerializeAsV2 set as true
Left -> generated with 5.0.0 -> OpenApi 3 keyword (wrong)
Right -> generated whit 5.0.0-RC5 ->Swagger 2.0 specs (correct)

How can I generate a swagger.json compliant with swagger 2.0 specs, using the v5.0.0 NuGet of this library?

Thanks

**Comment by domaindrivendev** [comment]
There's an update on the way that will make `allOf` behavior opt-in. This should solve your problem so stay tuned ...

**Comment by domaindrivendev** [comment]
As of 5.1.0, the allOf behavior has been made opt-in. This should resolve your issue.
