### ISSUE TITLE
Unable to shown Enum as string (Regression after 4.0.1 -> 5.0.0)

### ISSUE THREAD

**Issue by marius-jaskunas** [domaindrivendev/Swashbuckle.AspNetCore#1549]
Hello,

Was trying to show Enum as string but on Generation they are set to numbers: 

```
"MyEnum": {
        "enum": [
          1,
          2
        ],
        "type": "integer",
        "format": "int32"
      }
```

Since upgrade `options.DescribeAllEnumsAsStrings();` is obsolete and no longer working.

I tried adding JSON converter, but nothing changed. 

```
.AddJsonOptions(options =>
{
    options.SerializerSettings.Converters.Add(new StringEnumConverter());
```

Am I missing something in configuration or there is some kind of issue?

**Version:**
5.0.0

**Worked fine on:**
4.0.1

**Comment by domaindrivendev** [comment]
Dup of #1459. TL;DR this version defaults to honoring `System.Text.Json` (as opposed to `Newtonsoft`) serializer behavior. You need to expicitly opt-in to honoring Newtonsoft as described [here in the readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft)
