### ISSUE TITLE
Swashbuckle.AspNetCore.Cli should include dotnet-swagger.runtimeconfig.json as content file

### ISSUE THREAD

**Issue by Lonli-Lokli** [domaindrivendev/Swashbuckle.AspNetCore#1554]
I would like to use dotnetswagger as non DotNet tool but as a project, as referenced in wiki.
Actual issue -only dotnet-swagger.dll is copied, dotnet-swagger.runtimeconfig.json is not copied as assets from nuget to output folder.

Open solution and rebuild.

[RuntimeConfigNugetIssue.zip](https://github.com/NuGet/Home/files/4224768/RuntimeConfigNugetIssue.zip)

This file should be included as contentFile as here https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files

**Comment by domaindrivendev** [comment]
I'm still not 100% understanding your issue - is the CLI tool not working for you. If not, can you please provide some details of the error you're receiving?

**Comment by Lonli-Lokli** [comment]
@domaindrivendev I'm trying to use this CLI as non DotNet CLI tool but as a standalone dll.
You can see similar behavior in sample here https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/CliExample/CliExample.csproj

**Comment by domaindrivendev** [comment]
Still, I'm not understanding your exact problem. Using the DLL directly works in the sample app you've referenced. Can't you follow the exact approach it's using?

**Comment by Lonli-Lokli** [comment]
@domaindrivendev 
I think we can close this issue - we've updated our code to the latest version and we are using it as a CLI now.

I was talking that if you will try to use this tool as pure dll then it will.
