### ISSUE TITLE
IFormFile couldn't show as file upload button directly

### ISSUE THREAD

**Issue by Aoi-hosizora** [domaindrivendev/Swashbuckle.AspNetCore#1555]
dotnetcore 3.0
Swashbuckle.AspNetCore : 5.0.0-rc5
Swashbuckle.AspNetCore.SwaggerUI : 5.0.0-rc5
Feature Requests

I used `[FromForm(Name = "file"] IFormFile imageFile` to upload a image (single file), but the swagger generated this as a object. 

I have search some issues and I have a solution following. But I don't want to copy this code anywhere, so I hope that Swashbuckle could support IFormFile render to upload file directly.

```c#
[AttributeUsage(AttributeTargets.Method)]
public class FileUploadAttribute : System.Attribute { }

// options.OperationFilter<FormFileOperationFilter>();

public class FormFileOperationFilter : IOperationFilter {

    private static readonly string[] FileParameters = { "contentType", "contentDisposition", "headers", "length", "name", "fileName" };
    private const string FormData = "multipart/form-data";
    private const string Json = "application/json";

    public void Apply(OpenApiOperation operation, OperationFilterContext context) {
        var attr = context.MethodInfo.GetCustomAttributes(true).OfType<FileUploadAttribute>().Any();
        if (!attr) {
            return;
        }
        var content = operation.RequestBody.Content;

        var jsonProperties = GetProperties(content, Json);
        foreach (var parameter in jsonProperties.Where(p => FileParameters.Contains(p.Key))) {
            jsonProperties.Remove(parameter);
        }
        if (jsonProperties.Count == 0) {
            content.Remove(Json);
        }

        var formDataProperties = GetProperties(content, FormData);
        formDataProperties.Add("file", new OpenApiSchema { Type = "file" });
    }

    private static IDictionary<string, OpenApiSchema> GetProperties(IDictionary<string, OpenApiMediaType> contents, string mediaType) {
        if (!contents.ContainsKey(mediaType)) {
            contents.Add(mediaType, new OpenApiMediaType {
                Schema = new OpenApiSchema {
                    Type = "object",
                    Properties = new Dictionary<string, OpenApiSchema>()
                }
            });
        }
        return contents[mediaType].Schema.Properties;
    }
}
```

![image](https://user-images.githubusercontent.com/31433480/76095029-8bccad00-5ffe-11ea-98b1-4bbaf714e0b4.png)

![image](https://user-images.githubusercontent.com/31433480/76095082-a56df480-5ffe-11ea-891d-e2c341edd6f9.png)

**Comment by domaindrivendev** [comment]
As per the [ASP.NET Core docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1), you're not supposed to decorate `IFormFile` parameters with the `[FromForm]` attribute as the binding source is automatically inferred from the type. In fact, the inferred value is `BindingSource.FormFile` and if you apply the attribute it will be set to `BindingSource.Form` instead, which screws up `ApiExplorer`, the metadata component that ships with ASP.NET Core and is heavily relied on by Swashbuckle.

In your case, I would recommend, removing the attribute entirely and renaming the parameter to `file`. This should give you exactly the result you're looking for without the need to wire up a custom filter.

**Comment by Aoi-hosizora** [comment]
@domaindrivendev I just do that, but the result comes to a string-like textbox, what I want is a choose file button.

![image](https://user-images.githubusercontent.com/31433480/76106389-b4aa6d80-6011-11ea-80b2-a97ce15931c5.png)

```c#
        public async Task<ActionResult<Result<ImageItemDto>>> PostImage(
            [FromRoute] [SwaggerParameter("Group name")]
            string groupName,
            IFormFile file
        ) { ... }
```

**Comment by domaindrivendev** [comment]
Hmmm - are you using the SerializeAsV2 setting by any chance? This used an upstream library (OpenAPI.Net) to convert the V3 spec generated by SB into a V2 document. I’ve observed some issues with this conversion and this may be another one.

**Comment by Aoi-hosizora** [comment]
Oh yes, I'm using Swagger v2.

In v2, file parameter's type is `file`, and has no schema. But in v3, the type is `string` and the schema is `binary`.

![image](https://user-images.githubusercontent.com/31433480/76144383-af552d80-60ba-11ea-8e79-3a450ac480a8.png)

So if I use v2, I have to write a OperationFilter? (I'm more familiar with v2's format)

**Comment by domaindrivendev** [comment]
Do you have a reason to use V2 rather than V3. The latter will work much better, plus no need for the op filer

**Comment by Aoi-hosizora** [comment]
@danielcrenna Thanks :) I will use v3.

The reason is just that I am more familiar with v2. (I wrote a library to generate v2 in golang through parsing comments just like `// @Route xxx [GET]`).
