### ISSUE TITLE
Request: Option to generate a v2 swagger spec?

### ISSUE THREAD

**Issue by curiousdev** [domaindrivendev/Swashbuckle.AspNetCore#1561]
We've got aspnet-3.1 core services using the latest swashbuckle library. We have some consumers who's code-gen tools (triggered during ci builds) need to still generate against a v2 swagger spec file. 

In the bootstrapping middleware for swagger is there an option to produce a swagger spec file, even though we're using the latest libraries?

**Comment by domaindrivendev** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#serialize-swagger-in-the-20-format
