### ISSUE TITLE
Structural error when using UseInlineDefinitionsForEnums

### ISSUE THREAD

**Issue by older** [domaindrivendev/Swashbuckle.AspNetCore#1562]
When using `UseInlineDefinitionsForEnums()` swashbuckle v5.0.0 generates enum definitions inline but inserts `description` property inside `items`:

        "parameters": [
          {
            "in": "query",
            "name": "arrayofenums",
            "description": "Array containing enums",
            "required": true,
            "type": "array",
            "items": {
              "description": "Defines values for TestEnum.",
              "enum": [
                "TestEnumValue1",
                "TestEnumValue2",
                "TestEnumValue3"
              ],
              "type": "string"
            }
          }
        ],

and this is reported as structural error by editor.swagger.io:

    Structural error at paths./test.get.parameters.0.items
    should NOT have additional properties
    additionalProperty: description

Opening this as suggested by @domaindrivendev in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1329#issuecomment-595240341_

**Comment by domaindrivendev** [comment]
@older could you please create a minimal app (i.e. starting from empty project), and using the latest version of SB, that repro's this issue and post to github so I can pull it down and troubleshoot.

**Comment by older** [comment]
@domaindrivendev I cannot reproduce it any more. And I tried both with Swashbuckle.AspNetCore 5.0.0 and 5.6.3. 
Could it be that it was fixed in some upstream dependency? I only have the latest 5.0.102 SDK installed so I tested only with this SDK version.
