### ISSUE TITLE
Keep inheritance information

### ISSUE THREAD

**Issue by tsproesser** [domaindrivendev/Swashbuckle.AspNetCore#1564]
Right now I'm using this library for generating my models (in my case actually interfaces) including its inherited properties. But can someone tell my why the properties get mapped as direct properties of my interface and won't get actually "inherited"? Or is inheritance just not supported by OpenAPI? I'm not sure about this.

**Comment by domaindrivendev** [comment]
Inheritance is supported although it's opt-in via the `GeneratePolymorphicSchemas` setting. It's also well documented at this point - I'll try get that added ASAP (I'm also very open to PR's for doc updates).

**Comment by tsproesser** [comment]
Addin this flag I still can't see any "oneOf" in my swagger.json. Anything else I need to do? I'm using "AddSwaggerGenNewtonsoftSupport", too.

**Comment by domaindrivendev** [comment]
The Newtsonsoft setting shouldn't matter here (although you should be applying that too if you're still using the Newtonsoft serializer vs STJ). Rather than going back and forth over in a thread, perhaps you could create a minimal app that repro's the behavior (or lack of desired behavior) you're observing. If you do this and push it up to github, I can pull down and answer your question a lot quicker.

**Comment by tsproesser** [comment]
I'm a bit busy these days, hoped some one maybe knew a potential issue here. I'll update as soon as I find time, thank you!

**Comment by tsproesser** [comment]
Hey, found the issue now, even though I still havent created a Git - sorry for that. This only works for classes, not for interfaces!

**Comment by tsproesser** [comment]
Any news on this?

**Comment by domaindrivendev** [comment]
No plans to implement this anytime soon. However, you can probably workaround this pretty easily by passing a custom `subTypesResolver` when you call `GeneratePolymorphicSchemas()`. For reference, here's the default implementation:

```csharp
private IEnumerable<Type> DefaultSubTypeResolver(Type baseType)
{
    if (baseType == typeof(object))
        return Enumerable.Empty<Type>();

    return baseType.Assembly.GetTypes().Where(type => type.IsSubclassOf(baseType));
}
```

You should be able to figure out a tweak that would give you the interface support you're looking for. If this works for you, then perhaps you could consider a simple PR to get it into the box?

**Comment by tsproesser** [comment]
> No plans to implement this anytime soon. However, you can probably workaround this pretty easily by passing a custom `subTypesResolver` when you call `GeneratePolymorphicSchemas()`. For reference, here's the default implementation:
> 
> ```cs
> private IEnumerable<Type> DefaultSubTypeResolver(Type baseType)
> {
>     if (baseType == typeof(object))
>         return Enumerable.Empty<Type>();
> 
>     return baseType.Assembly.GetTypes().Where(type => type.IsSubclassOf(baseType));
> }
> ```
> 
> You should be able to figure out a tweak that would give you the interface support you're looking for. If this works for you, then perhaps you could consider a simple PR to get it into the box?

Sure, great idea! I'll let you know if it's done & working.

**Comment by tsproesser** [comment]
Just checking the code a bit and I have a question:

Why are classes searched that inherit from the current type and not the current type's base classes? Guess that's why only the type's own assembly is checked. Otherwise you could only base the BaseTypes cross Assembly

**Comment by tsproesser** [comment]
And: something doesn't work as expected with interfaces. Attached you find a minimum solution to reproduce my error. Interfaces just behave different than classes do, event with matching SubTypeResolver:

[WebApplication1.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/4417513/WebApplication1.zip)

**Comment by domaindrivendev** [comment]
@tsproesser Swashbuckle has been updated to support the "inheritance" use-cases (i.e. Schema A "inherits from" Schema B) and the "polymorphism" use cases (i.e. Schema A "can be one of" Schema B, Schema C etc.) independently via the `UseAllOfForInheritance` and `UseOneOfForPolymorphism` settings respectively.

For the "inheritance" use-case, you simply apply the `UseAllOfForInheritance` setting. However, in the case of interfaces (i.e. `class A : interface B`), this is a "implements" relationship as opposed to an "inherits from" relationship and this still not currently supported by Swashbuckle. So you would have to make your interface an abstract class to get the behavior you're looking for.
