### ISSUE TITLE
Manually added schemas don't show up in the swagger ui

### ISSUE THREAD

**Issue by nikolatomasevicpro** [domaindrivendev/Swashbuckle.AspNetCore#1565]
Hello,

i read the documentation, and i must say it is very detailed, i appreciate that. Thanks to that i saw that i could solve a little problem with adding schemas for the classes invisible to SwaggerGen manually.

I implemented a method for doing just that, but the end result is that they don't show up in the swagger ui. I think they are not added unless swagger sees them being used by an api, but i need to add those regardless.

Here is the GitHub repo of the project i'm testing all that on :
[TestMediatR](https://github.com/nikolatomasevicpro/TestMediatR)

The basic idea is creating one access point for all queries of same type (Identity, Basket...). But that makes swagger generator miss out on all the query classes. So i tried to add them manually, but the result is still the same : the manually added schema does not end in the swagger file.

**Comment by domaindrivendev** [comment]
The `MapType` setting is for providing a custom schema for a specific type. However, that schema will only be inlcuded in the generated Swagger/OpenAPI document if the mapped type is a parameter, property or response in one of your API operations.

If you'd like to manually add a standalone schema, then a [document filter](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#document-filters) would probably be your best bet. Here's an example:

```csharp
internal class AdditionalSchemasDocumentFilter : IDocumentFilter
{
    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        context.SchemaGenerator.GenerateSchema(typeof(SampleQuery), context.SchemaRepository);
    }
}
```

**Comment by nikolatomasevicpro** [comment]
Thanks for the quick answer.
I did make a document filter, however i noticed it is called each time the swagger page is requested. This makes it a little tedious since i'm using reflection to add all the missing information and it takes a bit of time to do that. 

Obviously, the swagger pages son't be heavily used like the API entrypoint, but i was hoping to make it so the types are added only once. Is this possible or is the document filter the only way add types invisibles to swagger generator?

**Comment by domaindrivendev** [comment]
Out-of-the-box, the Swagger is always generated on the fly and the generator makes significant use of reflection itself. I'd be surprised if your extension has a measurable impact to this. Have you been observing performance problems when loading your Swagger page?

With all that said, there are ways to implement caching so that the generation logic, which would include your document filter, only happens once. Some of these are discussed in #356 but the overall gist of it would be adding a custom `ISwaggerProvider` implementation that decorates the default behavior with caching:

```csharp

// Startup.cs
services.AddSwaggerGen(c =>
{
    ...
});

services.Replace(ServiceDescriptor.Transient<ISwaggerProvider, CachingSwaggerProvider>());
```
```csharp
// CachingSwaggerProvider.cs
public class CachingSwaggerProvider : ISwaggerProvider
{
    private static readonly ConcurrentDictionary<string, OpenApiDocument> _cache = new ConcurrentDictionary<string, OpenApiDocument>();

    private readonly SwaggerGenerator _swaggerGenerator;

    public CachingSwaggerProvider(
        IOptions<SwaggerGeneratorOptions> optionsAccessor,
        IApiDescriptionGroupCollectionProvider apiDescriptionsProvider,
        ISchemaGenerator schemaGenerator)
    {
        _swaggerGenerator = new SwaggerGenerator(optionsAccessor.Value, apiDescriptionsProvider, schemaGenerator);
    }

    public OpenApiDocument GetSwagger(string documentName, string host = null, string basePath = null)
    {
        return _cache.GetOrAdd(documentName, (_) => _swaggerGenerator.GetSwagger(documentName, host, basePath));
    }
}
```

**Comment by nikolatomasevicpro** [comment]
I did not observe significant performance problems, though i'm currently testing with only a few classes. The maximum number of classes should be around a few hundred at most so i don't think there will be a huge impact but, as i said, i was simply hoping to reduce the amount of work per page load. Your answer gave me the elements i needed. Thank you.
