### ISSUE TITLE
Redoc: Add ability to inject redoc.standalone.js

### ISSUE THREAD

**Issue by remcolam** [domaindrivendev/Swashbuckle.AspNetCore#1567]
Chrome 80 broke the redoc index menu on the left. This was solved in the redoc.standalone.rc23.js, but until the packages get updated, the only way to get it in is to inject your own html index page, with the correct file in it.

Would it be an option to allow the redoc js be injected separately into the index, just like we can the style sheet?

**Comment by martincostello** [comment]
As far as I'm aware, you can override any of the resources by replacing them with a static file with different content as long as it would have the same path as the resource you're replacing and the static file middleware is registered before Swashbuckle. This is how index.html overriding works.

The next release will also contain the latest version of Redoc, which presumably fixes the original motivating bug.
