### ISSUE TITLE
Xml comments. Wrong numeration on numbered list

### ISSUE THREAD

**Issue by Kolyan4ik95** [domaindrivendev/Swashbuckle.AspNetCore#1568]
Xml comments with numbered list in UI has wrong numeration.
Sample:

``` csharp 
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "MyWebAPIService", Version = "v1" });
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml"; 
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    c.IncludeXmlComments(xmlPath);
});


///<summary>
/// DigitEnum:
/// 0. Zero
/// 1. One
/// 2. Two
/// 3. Three
/// 4. Four
/// 5. Five
///</summary>
public enum DigitEnum
{
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
}

```
Result is here: 
![image](https://user-images.githubusercontent.com/39876997/76737383-b98dc080-6779-11ea-9db4-0b787743bdf8.png)

``` html
<div class="renderedMarkdown"><p>DigitEnum:</p>
<ol>
<li>Zero</li>
<li>One</li>
<li>Two</li>
<li>Three</li>
<li>Four</li>
<li>Five</li>
</ol></div>
```

What I except to see: 
![image](https://user-images.githubusercontent.com/39876997/76737704-55b7c780-677a-11ea-8212-8240d33fd433.png)

``` html
<div class="renderedMarkdown"><p>DigitEnum:</p>
<ol>
<li value="0">Zero</li>
<li value="1">One</li>
<li value="2">Two</li>
<li value="3">Three</li>
<li value="4">Four</li>
<li value="5">Five</li>
</ol></div>
```

**Comment by asrasya-kosha** [comment]
I tested this and the generated manifest xml and swagger.json is populated with correct values but somehow swaggerUI is doing something intelligent over the top to display values starting with 1.

I'll have a look on the UI code (perhaps some js file) which is causing this issue. If anyone has some pointer on which file exactly to look into, please let me know, it will save some time.

**Comment by mattfrear** [comment]
It sounds like this is a swagger-ui issue, so this issue can be closed.
