### ISSUE TITLE
Default Value Attribute more does not work in version 5.1.0

### ISSUE THREAD

**Issue by zavada-sergey** [domaindrivendev/Swashbuckle.AspNetCore#1569]
I have enum (img 1)
![1](https://user-images.githubusercontent.com/23330347/76736516-9f4ee500-676f-11ea-90ab-9ef07dbb0bc9.PNG)

I use this enum in my model along with DefaultValueAttribute (img 2)
![2](https://user-images.githubusercontent.com/23330347/76736629-db824580-676f-11ea-8fdf-cd13be03d9a2.PNG)

I created a DefaultValueSchemaFilter which allows you to use DefaultValueAttribute with Swagger. (img 3)
![3](https://user-images.githubusercontent.com/23330347/76737943-619f8b80-6772-11ea-9901-12785684c772.PNG)

After that I registered mine in SwaggerGen (img 4)
![4](https://user-images.githubusercontent.com/23330347/76738050-8dbb0c80-6772-11ea-98b1-2e5be4670a1c.PNG)

When using version 5.0.0 DefaultValueAttribute works correctly (img 5)
![5](https://user-images.githubusercontent.com/23330347/76738206-e1c5f100-6772-11ea-9f30-c789305edea7.PNG)

But when using version 5.1.0 DefaultValueAttribute works not correctly (img 6)
![6](https://user-images.githubusercontent.com/23330347/76738285-04580a00-6773-11ea-90e6-7bec672edef3.PNG)

How can I fix this problem?

**Comment by domaindrivendev** [comment]
When configuring Swagger in your `Startup.cs`, apply the `UseAllOfToExtendReferenceSchemas` setting. Long story short, this behavior was made implicit in `5.0.0` and while it's helpful for some situations (including your own), it also caused a range of new issues particularly for people that were using code gen tools to generate clients from the generated Swagger/OpenAPI document. So, I made the behavior opt-in only as of `5.1.0`. By opting-in, you should get the behavior you're looking for.
