### ISSUE TITLE
XML comments missing for properties which are Enums or Classes 

### ISSUE THREAD

**Issue by pfaustinopt** [domaindrivendev/Swashbuckle.AspNetCore#1575]
## Version
**Swashbuckle.AspNetCore:** 5.1.0

## Steps to reproduce
Create the following classes
```
public class SomeClass
{
    /// <summary>
    /// AnotherClass comments
    /// </summary>
    public AnotherClass AnotherClass { get; set; }

    /// <summary>
    /// SomeEnum comments
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public SomeEnum SomeEnum { get; set; }
}

public class AnotherClass
{
    /// <summary>
    /// Some property comments
    /// </summary>
    public string Name { get; set; }
}

public enum SomeEnum
{
    A,
    B,
    C
}
```

## Expected behaviour
On version `5.0.0`, the generated JSON is the following:
```
"SomeClass": {
        "type": "object",
        "properties": {
          "anotherClass": {
            "allOf": [
              {
                "$ref": "#/components/schemas/AnotherClass"
              }
            ],
            "description": "AnotherClass comments",
            "nullable": true
          },
          "someEnum": {
            "allOf": [
              {
                "$ref": "#/components/schemas/SomeEnum"
              }
            ],
            "description": "SomeEnum comments"
          }
        },
        "additionalProperties": false
      }
```

This means that the comments `AnotherClass comments` and `SomeEnum comments` show up in the swagger UI:

![2020-03-17 19_10_33-Swagger UI](https://user-images.githubusercontent.com/5471232/76892758-1923c300-6883-11ea-87ba-e2b8c49073a3.png)

## Actual behaviour

On version `5.1.0`, the generated JSON is the following:
```
"SomeClass": {
  "type": "object",
  "properties": {
    "anotherClass": {
      "$ref": "#/components/schemas/AnotherClass"
    },
    "someEnum": {
      "$ref": "#/components/schemas/SomeEnum"
    }
  }
}
```

As you can see, the description field is missing after the update to the new `Swashbuckle.AspNetCore` version.

The swagger UI now shows the following:

![2020-03-17 19_09_17-Swagger UI](https://user-images.githubusercontent.com/5471232/76892899-4cfee880-6883-11ea-94a9-f151868d0881.png)

**Comment by JoFrMueller** [comment]
We stumbled upon this as well after we migrated to .NET Core 3.1 and Swashbuckle.AspNetCore 5.1.0.

Actually it should be not too difficult to introduce some JSON comment output validation to some of the tests in `test/Swashbuckle.AspNetCore.SwaggerGen.Test/XmlComments/` to avoid this issue for future releases. Or am I missing something?

If I can be of any help regarding this issue, please let me know. Would be happy to provide a corresponding pull request after some help regarding _'how tests are structured and implemented in general'_.

**Comment by domaindrivendev** [comment]
When configuring Swagger in your Startup.cs, apply the `UseAllOfToExtendReferenceSchemas` setting. Long story short, this behavior was made implicit in 5.0.0 and while it's helpful for some situations (including your own), it also caused a range of new issues particularly for people that were using code gen tools to generate clients from the generated Swagger/OpenAPI document. So, I made the behavior opt-in only as of 5.1.0. By opting-in, you should get the behavior you're looking for.

**Comment by JoFrMueller** [comment]
Thanks for the clarification. `UseAllOfToExtendReferenceSchemas` works well!

**Comment by pfaustinopt** [comment]
It's working, thank you.

**Comment by pfaustinopt** [comment]
@domaindrivendev one of our teams is using this [tool](https://github.com/OpenAPITools/openapi-generator) to generate the swagger client (swift5 and kotlin-client) and with the previous version `5.0.0` we never had no problems. However, once I've set `UseAllOfToExtendReferenceSchemas`, they started having problems with the gen tool just like you said. 

Any idea why everything worked correctly on version `5.0.0` (which had `UseAllOfToExtendReferenceSchemas` by default)  and now with the version `5.1.0` if I opt-in it is no longer working?

According to what you said, the behaviour should remain the same. If they had success using the gen tool with the version `5.0.0`, they should also be able to generate the client on `5.1.0` with `UseAllOfToExtendReferenceSchemas`.
