### ISSUE TITLE
Response Description Styling looks off

### ISSUE THREAD

**Issue by RichieRunner** [domaindrivendev/Swashbuckle.AspNetCore#1577]
I am on version v5.1.0, and have followed the setup instruction, but am noticing that the Description column in Responses section seems to not be styled correctly.  Am I missing some stylesheet somewhere?
![image](https://user-images.githubusercontent.com/20289967/76992678-d73d6000-6908-11ea-911b-fba23a2fcb52.png)

**Comment by domaindrivendev** [comment]
I see the same so I guess that's just the styling. If you have issues or suggestions around the look and feel of the UI, then you should post those to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui) instead of this one.
