### ISSUE TITLE
Routing Swagger through OData Service route

### ISSUE THREAD

**Issue by kisalay1988** [domaindrivendev/Swashbuckle.AspNetCore#1578]
I have created a .NET Core 3.0 Web API with OData and Swagger. Configured the OData route as below in Configure method of `Startup.cs`

```csharp
app.UseMvc(routeBuilder =>
            {
                routeBuilder.EnableDependencyInjection();
                routeBuilder.Select().OrderBy().Filter().MaxTop(200).Count().SkipToken();
                routeBuilder.ServiceProvider.GetRequiredService<ODataOptions>().UrlKeyDelimiter = Parentheses;
                routeBuilder.MapODataServiceRoute("odata", "odata", GetEdmModel());
            });
```

In my controller the Route is configured as :

```csharp
   [Route("api/[controller]")]
    public class ControlController : ODataController
    {
...
```

1. If I make a call using http://localhost/odata/Control - Data is returned in Odata format as its routed through Odata
2. If I make a call using http://localhost/api/Control - Data is returned an array of my return type object but not in odata format
3. If I change Route attribute value over controller to "odata/[controller]", then no data in Odata format is returned but returned as point 2 above.
4. If I remove the Route attribute from controller, it leads to "No operations defined in spec!" error

Is there a way I can make swagger to route through the mapped odata service route and get the desired output?

**Comment by domaindrivendev** [comment]
Swashbuckle is built on top of `ApiExplorer`, the API metadata provider that's part of ASP.NET Core. That component does not currently support OData controllers and therefore neither does Swashbuckle.

This lack of support is being tracked in the following issue, including a workaround from the `Microsoft.AspNetCore.Mvc.Versioning` library:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/581#issuecomment-759435536
