### ISSUE TITLE
Use constructor to set properties in swagger

### ISSUE THREAD

**Issue by gkhndev** [domaindrivendev/Swashbuckle.AspNetCore#1582]
I am building an API and using swagger to test the endpoints. I have a ProductDTO:

public string ProductName { get; set; }
.
.
.
public Price Price { get; set; }
in this DTO I want to use Price class which is used throughout my code. Price class looks like this:

public class Price
{
    public Price(decimal amount, string currency)
    {
        Amount = amount;
        Currency = currency;
    }

    public decimal Amount { get; private set; }
    public string Currency { get; private set; }
}
But since private setters are used in Price class I cannot set these values using swagger (it has readonly attribute on those). I really like this approach of having private setters and setting values with constructor, which by the way is public. Is there any way I could set values for Price class using swagger and still use private setters on properties?

This case is working in 4.0.1 version but not in the last version

**Comment by domaindrivendev** [comment]
Which serializer are you using - _Newtonsoft_ or _System.Text.Json_? I'm asking because the latter currently only supports publicly settable properties on deserialization. So, given your question, I'm assuming you're using Newtonsoft?

That being the case, then I think this issue is really a dup of #849, which I'm going to prioritize resolving next. If it's OK with you I'm going to close this issue and continue tracking with the original. If you feel this si trully different just let me know and we'll try an iron out the distinction.

**Comment by gkhndev** [comment]
i am not using serializer 

i wan to share example codes 

this code is working 4.0.1 of version it do no need any serializer  so why does not work in the last version

    [DataContract]
    public class AddOfferWithQuotationsCommand : IRequest<int>
    {
        public AddOfferWithQuotationsCommand(List<QuotationItemViewModel> quotations, int tenantId, string tenantName, int customerId, string customerName, 
                                             int offerTypeId, DateTime estimatedStartDateTime, DateTime validityDateTime) : this()
        {
            this._quotations = quotations.Select(x => x.Map<QuotationItemDto>()).ToList();
            this.TenantId = tenantId;
            this.TenantName = tenantName;
            this.CustomerId = customerId;
            this.CustomerName = customerName;
            this.OfferTypeId = offerTypeId;
            this.EstimatedStartDateTime = estimatedStartDateTime;
            this.ValidityDateTime = validityDateTime;
        }

        public AddOfferWithQuotationsCommand()
        {
            this._quotations = new List<QuotationItemDto>();
        }

        [DataMember]
        public int TenantId { get; private set; }

        [DataMember]
        public string TenantName { get; private set; }

        [DataMember]
        public int CustomerId { get; private set; }

        [DataMember]
        public string CustomerName { get; private set; }

        [DataMember]
        public int OfferTypeId { get; private set; }

        [DataMember]
        public DateTime EstimatedStartDateTime { get; private set; }

        [DataMember]
        public DateTime ValidityDateTime { get; private set; }

        [DataMember]
        private readonly List<QuotationItemDto> _quotations;

        public IReadOnlyCollection<QuotationItemDto> Quotations => _quotations;
    }

**Comment by domaindrivendev** [comment]
The "Serializer" is the component in ASP.NET Core that takes the submitted JSON payload and uses it to populate an instance of  `AddOfferWithQuotationsCommand`. It's a critical part of any API built on ASP.NET Core and it's also a key dependency for Swahbuckle as it needs to honor serializer behavior to create an accurate description of JSON payloads (both in and out of your API).

Prior to ASP.NET Core 3.x, _Newtonsoft_ was the default/built-in serializer. From 3.x onwards though, they've switched to a new native serializer _System.Text.Json (STJ)_. However, 3.x applications can still switch back to _Newtonsoft_ if they wish. You should know which serializer your application is configured to use.

**Comment by jwisener** [comment]
This is still not properly working, even after adding the nuget package from the link you provided.

For example: 

You have a class 

```
    public class TestValidationRequest
    {
        [JsonConstructor]
        public TestValidationRequest(string phoneNumber, string email)
        {
            PhoneNumber = new PhoneNumber(phoneNumber);
            Email = new EmailAddress(email);
        }
        public PhoneNumber PhoneNumber { get; }
        public EmailAddress Email { get; }
    }
```

It still shows the api endpoints as requiring these complex objects vs  what is defined via the jsonconstructor attribute.
