### ISSUE TITLE
SwaggerUI shows optional enums as required

### ISSUE THREAD

**Issue by spanevin** [domaindrivendev/Swashbuckle.AspNetCore#1585]
All versions of Swashbuckle.AspNetCore are affected including 5.2.0

```
public enum MyEnum {Val1, Val2}

[HttpGet("{myEnum?}")]
IActionResult Get([FromRoute]MyEnum? myEnum = null)
{
}
```
Swagger UI shows myEnum as required and there is no option to omit a value for it.

I have read all the issues related to nullable/optional enums but haven't found any working solution.

**Comment by domaindrivendev** [comment]
It's nothing to do with being an enum - it's because it's a _path_ parameter.

This issue is actually a dup of #406 and #824. Long story short, the Swagger/OpenAPI specification DOES NOT allow optional route parameters and therefore they're NOT supported by Swashbuckle.

**Comment by spanevin** [comment]
`the Swagger/OpenAPI specification DOES NOT allow optional route parameters and therefore they're NOT supported by Swashbuckle.`
Why it does not allow this when it's supported by webapi/aspnetcore?
Multiple actions with the same route aren't supported as well...
Too many limitations, which make usage of this lib in real applications useless...
