### ISSUE TITLE
Swashbuckle ignores the "AllowAnonymous" attribute of controller operations

### ISSUE THREAD

**Issue by tiwalter** [domaindrivendev/Swashbuckle.AspNetCore#1586]
If i have controller operations with the "AllowAnonymous" attribute (see example below):
```
[AllowAnonymous]
[HttpGet]
public Response ExampleFunction(string exampleInput)
{
   ...
  return retVal
}
```

The operation does still have the auth in the generated Swagger documentation (lock is shown & the auth header will be sent with every request).

I expect, that Swashbuckle does respect this attribute and removes the auth of the endpoint / operation.

Version of Swashbuckle.AspNetCore: **5.1.0**
Version of .NET Core: **3.1.102**

**Comment by domaindrivendev** [comment]
Swashbuckle does not honor _any_ auth metadata out-of-the-box. Instead this behavior has to be explicitly configured as described [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements).

As you _do_ appear to be seeing auth-related behavior, I'm assuming you're application already has this Swashbuckle configuration in place. It's that configuration and related code that will have to be adjusted to solve this issue.

If you could share your Swashbuckle configuration (look for `AddSwaggerGen` in your `Startup.cs`) I might be able to point you in the right direction?

**Comment by tiwalter** [comment]
Thanks for the fast reply @domaindrivendev.

Here is my Swashbuckle configuration:

`
services.AddSwaggerGen(c =>
{

c.SwaggerDoc("v1", new OpenApiInfo
{
    Title = "...",
    Version = "v1",
    Description = "..." +
    Contact = new OpenApiContact
    {
        Name = "...",
        Email = "..",
        Url = new Uri(..")
    }
});

c.AddSecurityDefinition("basic", new OpenApiSecurityScheme
{
    Type = SecuritySchemeType.Http,
    Name = "Authorization",
    Scheme = "basic", 
    Description = "Input your username and password to access this API",
    In = ParameterLocation.Header,
});

c.AddSecurityRequirement(new OpenApiSecurityRequirement
{
    {
        new OpenApiSecurityScheme
        {
            Reference = new OpenApiReference {
                Type = ReferenceType.SecurityScheme,
                Id = "basic" }
        }, new List<string>() }
});

c.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, "XX.WebApi.xml"));
c.ExampleFilters();
`

Do i have to adjust this config to achieve the expected behaviour?

**Comment by domaindrivendev** [comment]
Yes. When you use the `AddSecurityRequirement` method you're adding a "global" requirement (i.e. applicable to _all_ operations). If you want to add security requirements at the operation level, then you'll need to create a custom Operation Filter that inspects your action metadata for the presence of authorization attributes and then sets the `Operation.Security` property accordingly.

The readme has an [example that does this for an OAuth security scheme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements). If you read through that section carefully then you should be able to adjust the example for the "basic" schema in your case. If anything, it should be much simpler than the OAuth one.

**Comment by tiwalter** [comment]
Thanks, you're right!

This implementation works for me:
```
public class BasicAuthOperationsFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        var noAuthRequired = context.ApiDescription.CustomAttributes().Any(attr => attr.GetType() == typeof(AllowAnonymousAttribute));

        if (noAuthRequired) return;

        operation.Security = new List<OpenApiSecurityRequirement>
        {
            new OpenApiSecurityRequirement
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference
                        {
                            Type = ReferenceType.SecurityScheme,
                            Id = "basic"
                        }
                    },
                    new List<string>()
                }
            }
        };
    }
}
```

The only thing you have to do is to filter operations with the "AllowAnonymous" attribute. The `operation.Security` property will be adjusted for them.

**Comment by RavinduL** [comment]
Small extension to @tiwalter's solution that also recognises `AuthorizeAttribute`s on endpoints & controllers.

```csharp
class AuthOperationFilter : IOperationFilter
{
	public void Apply(OpenApiOperation operation, OperationFilterContext ctx)
	{
		if (ctx.ApiDescription.ActionDescriptor is ControllerActionDescriptor descriptor)
		{
			// If not [AllowAnonymous] and [Authorize] on either the endpoint or the controller...
			if (!ctx.ApiDescription.CustomAttributes().Any((a) => a is AllowAnonymousAttribute)
				&& (ctx.ApiDescription.CustomAttributes().Any((a) => a is AuthorizeAttribute)
					|| descriptor.ControllerTypeInfo.GetCustomAttribute<AuthorizeAttribute>() != null))
			{
				operation.Security.Add(new OpenApiSecurityRequirement
				{
					[new OpenApiSecurityScheme
					{
						Reference = new OpenApiReference
						{
							Type = ReferenceType.SecurityScheme,
							Id = ...,
						},
					}] = Array.Empty<string>()
				});
			}
		}
	}
}
```

**Comment by AnthonyMastrean** [comment]
Any idea how you'd evaluate both the default and fallback authorization policy as part of this operation filter?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizationoptions?view=aspnetcore-5.0

**Comment by AdisonCavani** [comment]
Minimal API uses `RequireAuthorization()` method instead of `[Authorize]` attribute.
How can I use `IOperationFilter` filter with MinimalAPI to detect if endpoint requires auth?

**Comment by Davilink** [comment]
> Minimal API uses `RequireAuthorization()` method instead of `[Authorize]` attribute. How can I use `IOperationFilter` filter with MinimalAPI to detect if endpoint requires auth?

This will override the global security by an empty one
```csharp
.WithOpenApi(operation =>
{
    operation.Security.Add(new OpenApiSecurityRequirement());
    return operation;
});
```

**Comment by CesarD** [comment]
How can one detect whether the `.AllowAnonymous()` method has been called for an endpoint if I'm working already with an `OperationFilter`?

**Comment by mathiash98** [comment]
To clarify for people struggling using the OptionFilter:

1. Remove `AddSecurityRequirement ` from `.AddSwaggerGen` and add `AddOperationFilter<OperationFilter>` instead

```CSharp
builder.Services.AddSwaggerGen(c =>
{
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Enter 'Bearer' [space] and then your token in the text input below.",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });

    c.OperationFilter<OpenAPIAuthOperationFilter>();
});
```

```CSharp
using System.Reflection;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

/// <summary>
/// OpenAPI operation filter to apply authentication requirements.
/// This filter checks if the endpoint or controller has [AllowAnonymous] or [Authorize] attributes
/// and applies the appropriate security scheme to the OpenAPI operation.
/// If neither attribute is present, no security scheme is applied.
/// </summary>
class OpenAPIAuthOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext ctx)
    {
        var endpointAttributes = ctx.ApiDescription.CustomAttributes();
        var controllerAttributes = (ctx.ApiDescription.ActionDescriptor as ControllerActionDescriptor)?.ControllerTypeInfo.GetCustomAttributes();

        // If not [AllowAnonymous] and [Authorize] on either the endpoint or the controller...
        if (!endpointAttributes.Any((a) => a is AllowAnonymousAttribute)
            && (endpointAttributes.Any((a) => a is AuthorizeAttribute)
                || controllerAttributes?.Any((a) => a is AuthorizeAttribute) == true))
        {
            operation.Security =
            [
                new() {
                        {
                            new OpenApiSecurityScheme
                            {
                                Reference = new OpenApiReference
                                {
                                    Type = ReferenceType.SecurityScheme,
                                    Id = "Bearer",
                                }
                            }, Array.Empty<string>()
                        }
                    }
            ];
        }
        else
        {
            // If [AllowAnonymous] is present, do not apply any security scheme
            operation.Security = null;
        }
    }
}
```
