### ISSUE TITLE
Constructor is not considered when adding read-only flag to parameters

### ISSUE THREAD

**Issue by bajdka** [domaindrivendev/Swashbuckle.AspNetCore#1587]
Version used: Swashbuckle.AspNetCore **5.2.0**

**Steps to reproduce**
Use request model with properties only with getters (without setters) and constructor that sets the values. Example:
```
{
    public class ApplyFormPostRequest
    {
        public string EmailAddress { get; }
        public string PhoneNumber { get; }

        public ApplyFormPostRequest(
            string emailAddress,
            string phoneNumber
        )
        {
            EmailAddress = emailAddress;
            PhoneNumber = phoneNumber;
        }
    }
}
```

**Actual result:**
```
...
"properties": {
     "emailAddress": {
            "type": "string",
            "nullable": true,
            "readOnly": true
      },
    "phoneNumber": {
            "type": "string",
            "nullable": true,
            "readOnly": true
      }
}
```
- issue doesn't occur when there are direct getters & setters but I would like to avoid that

**Expected result:**
- since there is a constructor, fields _**emailAddress**_ and _**phoneNumber**_ shouldn't be marked as read-only

**Comment by domaindrivendev** [comment]
This is a dup of #849 and is resolved as of `v5.2.1` - assuming you've configured SB to optimize for Newtonsoft serializer behavior as described [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft)
