### ISSUE TITLE
XmlRootAttribute ignored

### ISSUE THREAD

**Issue by Fruchuxs** [domaindrivendev/Swashbuckle.AspNetCore#1596]
Swashbuckle 5.2.1 is ignoring the XmlRootAttribute.

```c#
[XmlRoot("Client")]
class CustomerModel {
}
```

With media type application/xml I get the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomerModel>

</CustomerModel>
```

This is a huge problem for peoples who tries to bind an api.

**Comment by domaindrivendev** [comment]
Will track as part of #1050
