### ISSUE TITLE
Duplicate attributes in default schemas

### ISSUE THREAD

**Issue by DenesIsti** [domaindrivendev/Swashbuckle.AspNetCore#1597]
I have a simple ASP.Net Core project with a simple controller. Nothing special. But when I load it up with swagger ui in the json file in the generated attributes I have a lot of duplicated value, for example: 

TypeAttributesinteger($int32)Enum:
[ **0**, **0**, **0**, 0, 1, 2, 3, 4, 5, 6, 7, 7, 8, 16, 24, 32, 32, 128, 256, 1024, 2048, 4096, 8192, 16384, 65536, 131072, 196608, 196608, 262144, 264192, 1048576, 12582912 ]

If I generate a C# code from this with NSwagStudio I will get a lot of duplicated values, and the code will not compile. 
I wrote a ticket on swaggerUI, and they pointed me this way, saying that this is a library issue.

Is this a bug, or some ASP.Net Core issue?

**Comment by domaindrivendev** [comment]
Please create a minimal app that repro's the issue and post to github where I can pull down and take a look.

**Comment by DenesIsti** [comment]
Thanks for responding, I've created a minimal web-service, and invited you on the github repo. 
Just as an extra info: I have the ErrorResponseModel class that it seems to generate the errors in the swagger.json file, values such as (0 and 256 are duplicated):
"MethodAttributes": {
        "enum": [
          0,
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          16,
          32,
          64,
          128,
          256,
          256, ....

**Comment by domaindrivendev** [comment]
You're `ErrorModel` includes a property of type `Exception` which has an extremely low-level C#-specific structure and is therefore not ideal for serializing to JSON. Swashbuckle is trying to describe what this might look like in a serialized-to-json form and as you can see it's extremely complicated.

Do you really want to expose the full internals of your Excpeptions instances to your API consumers? Aside from the fact that it's not a particularly usable structure for API consumers, I would think it could also be a security concern. If you want to maintain the structure internally (possibly for internal logging etc.) you can keep the property but tell the serializer to ignore it as follows:

```csharp
[JsonIgnore]
public Exception FullException { get; }
```

This will provide a much API contract and corresponding Swagger/OpenAPI description

**Comment by domaindrivendev** [comment]
I've also noticed that you're using some `Newtonsoft` specific annotations. I'm not sure if you're aware of this but as of ASP.NET Core 3.0, 'Newtonsoft` is no longer the default serializer and as far as I can tell you're not explicitly reverting back to `Newtonsoft` in your `Statup.cs`. This means your annotations will essentially have zero effect.

**Comment by DenesIsti** [comment]
Thank you, you are totally right. By removing the Exception type from the serialization the issue is gone.

Also thanks for the headsup on the annotations. We wrote this code last year, using ASP.Net Core 2,  its time to update it.
