### ISSUE TITLE
AddSecurityDefinition does not send header if casing is not all lower

### ISSUE THREAD

**Issue by AroglDarthu** [domaindrivendev/Swashbuckle.AspNetCore#1598]
The `OpenApiSecurityScheme.Scheme` property states: 
*REQUIRED: The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235*

If we go there, we find a link to the allowed schemes: http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml

And here you will see that most of the official name start with a capital letter. For example: *Bearer* or *Basic*.

Personally I don't like to type strings at all, so I tend to borrow the constants from a suitable library. For instance `JwtBearerDefaults.AuthenticationScheme` in `Microsoft.AspNetCore.Authentication.JwtBearer`. The constant defined there is exactly what is should be: **Bearer**.

However, passing this constant to the `OpenApiSecurityScheme.Scheme` property will result in SwaggerUI not sending the header at all...

Now I could argue that depending on *bearer* or *basic* is plain wrong, as the RFC states these should be *Bearer* and *Basic* respectively, but that would cause a major breaking change. 
I propose just ignoring the casing of the Scheme property value. Everybody happy...

There are multiple issues that refer to this exact problem (for example #1022). People tend to just fix the problem by using lowercase. Unfortunately, because we like to use constants as explained above, this problems comes back over and over again and it always takes time to find the cause :-(

**Comment by AroglDarthu** [comment]
The `OpenApiSecurityScheme.Scheme` property states: 
*REQUIRED: The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235*

If we go there, we find a link to the allowed schemes: http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml

And here you will see that most of the official name start with a capital letter. For example: *Bearer* or *Basic*.

Personally I don't like to type strings at all, so I tend to borrow the constants from a suitable library. For instance `Microsoft.AspNetCore.Authentication.JwtBearer.AuthenticationScheme`. The constant defined there is exactly what is should be: **Bearer**.

However, passing this constant to the `OpenApiSecurityScheme.Scheme` property will result in SwaggerUI not sending the header at all...

Now I could argue that depending on *bearer* or *basic* is plain wrong, as the RFC states these should be *Bearer* and *Basic* respectively, but that would cause a major breaking change. 
I propose just ignoring the casing of the Scheme property value. Everybody happy...

There are multiple issues that refer to this exact problem. People tend to just fix the problem by using lowercase. Unfortunately, because we like to use constants as explained above, this problems comes back over and over again and it always takes time to find the cause :-(

**Comment by AroglDarthu** [comment]
#1022

**Comment by domaindrivendev** [comment]
According to the folks who create the Swagger/OpenAPI specification, the value is __case-insensitive__ (see https://github.com/OAI/OpenAPI-Specification/issues/1876). However, as you've pointed out, the swagger-ui appears to only support lowercase. As the swagger-ui is an independent, upstream project the fix would have to happen there. I'll keep this one open for tracking but you should create an issue in [the swagger-ui repo](https://github.com/swagger-api/swagger-ui) if one doesn't already exist.

**Comment by AroglDarthu** [comment]
OK. Thanks, I didn't realize these were separate repos :-(

**Comment by china-live** [comment]
Custom "authentication:00000000" used by a lot of old APIs，How to test？
