### ISSUE TITLE
Easier way to support camelCase for objects marked as [FromQuery]

### ISSUE THREAD

**Issue by greghroberts** [domaindrivendev/Swashbuckle.AspNetCore#160]
If you have a complex object that you are mapping with [FromQuery] then there doesn't seem to be a great way to make those follow camelCase convention unless you put [FromQuery(Name="camelCase"] on each property. Seems like a simple convention could be configured or an option on FromQuery, but this is usually an app setting, not something you decide to do for each API.

Let me know if there is a better way to support this.  I'd be happy to help if there is obvious place for this to go.

**Comment by khellinxdigipolis** [comment]
Is there a widely accepted convention for this?
Although Microsoft suggests using camelCase for query parameters (https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md), I'm not sure Microsoft should be the only reference.

At the company where I'm currently empoyed, convention is to use lowercase (eg: pagesize) but I've seen other uses (eg: Facebook uses snake_case if I'm not mistaken).

I've forked your repo and I am adding an option QueryParametersCapitalization to SchemaRegistryOptions of enum type CapitalizationType:
`    public enum CapitalizationType
    {
        None,
        CamelCase,
        PascalCase,
        SnakeCase,
        KebabCase
    }`

The generator then converts the query parameter names.
Ofcourse, model binding would also need its custom implementation but that's outside of Swashbuckle's scope.

What's your opinion on the above?
Thanks!

**Comment by domaindrivendev** [comment]
See d8ba4d35c17afa3f1d06884b9653a89ea746fe3c

**Comment by greghroberts** [comment]
@domaindrivendev be great to publish a new package for this.

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"

**Comment by ozonni** [comment]
Still not available in latest [nuget package](https://www.nuget.org/packages/Swashbuckle.AspNetCore/1.0.0-rc1)

**Comment by RamunasAdamonis** [comment]
The hack to put `[FromQuery(Name="camelCase"]` does not work with .Net Core 2.2. Is there another solution for this?

**Comment by domaindrivendev** [comment]
@RamunasAdamonis please provide a code example that repro's your issue. I just tested in a .Net Core 2.2 project and both the `[FromQuery]` annotation AND the global config setting `DescribeAllParametersInCamelCase` work exactly as expected.

**Comment by RamunasAdamonis** [comment]
@domaindrivendev I was not using `DescribeAllParametersInCamelCase` option. It works as expected now. Thank you for highlighting this.
