### ISSUE TITLE
How to force date instead of datetime in Swagger

### ISSUE THREAD

**Issue by mvdiemen** [domaindrivendev/Swashbuckle.AspNetCore#1609]
Hello,

We have a model with datetime, but for some of them we want to force them to be shown as a data in the produced swagger file. I've found this link, but after four years I can imagine that this could be easier. https://github.com/domaindrivendev/Swashbuckle/issues/741

Thanks in advance

**Comment by domaindrivendev** [comment]
If you need to do this globally (i.e. for all properties of type `DateTime`) then the following is still the best approach:

```csharp
c.MapType<DateTime>(() => new OpenApiSchema { Type = "string", Format = "date" });
```

If you need to do it on a per-property basis, then I've just pushed and released a simple change that let's you do this via the `SwaggerSchemaAttribute` (see https://github.com/domaindrivendev/Swashbuckle.AspNetCore#enrich-schema-metadata). To use this approach you'll need `v5.3.1` or higher.

**Comment by WoMayr** [comment]
Is there a way to force the "date" format for query parameters?

The `SwaggerParameterAttribute` does not support the format property.

**Comment by domaindrivendev** [comment]
Decorate your parameter with a SwaggerSchemaAttribute

**Comment by WoMayr** [comment]
It doesn't allow me to do that, as SwaggerSchemaAttribute is not marked to be used on Parameters
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Annotations/SwaggerSchemaAttribute.cs#L5

**Comment by domaindrivendev** [comment]
@WoMayr - see referenced PR to get this added in

**Comment by arisliang** [comment]
Even after specify `[SwaggerSchema(Format = "date")]` on the property, the format still show as 'date-time'

**Comment by sebasijan** [comment]
As mentioned by @arisliang , the `SwaggerSchema` attribute does not affect how the date is appeared when I addd it like this

    [SwaggerSchema(Format = "date")]

**Comment by sebasijan** [comment]
Got it working by adding this to my configuraion

    c.EnableAnnotations();

**Comment by adamjones1** [comment]
Is there a solution for this for apps not on ASP.Net Core but just ASP.Net Web API instead?

**Comment by ardalis** [comment]
The attribute is working but the global MapType using this syntax is not:

```csharp
c.MapType<DateTime>(() => new OpenApiSchema { Type = "string", Format = "date-time" });
```

Instead the generated json just includes "type" : "string" and no "format". (whereas using the attribute produces the expected "format":"date-time")
