### ISSUE TITLE
using multiple IncludeXmlComments, but solution is concidering only last file.

### ISSUE THREAD

**Issue by AlmasHasnain** [domaindrivendev/Swashbuckle.AspNetCore#1610]
Hi,

We are using below specifications:
- .Net Framework 4.7.2
- Swashbuckle.Core V 5.6.0

All the code has been done with reference to link "https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments" and "https://github.com/domaindrivendev/Swashbuckle/blob/5489aca0d2dd7946f5569341f621f581720d4634/Swashbuckle.Dummy.Core/App_Start/SwaggerConfig.cs#L261".

In our solution we are having multiple projects. There are 2 projects in which controllers are defined and we are showing comments inserted in these projects in swagger. The main project which is the default project is different from these 2 projects.

As per the guidelines we have defined the name in build section and enabled XML Documentation File. We have also added the reference of these xml in bin of main project and set the properties to updated the files every time the solution is built. 

To include multiple comments file we are using "c.IncludeXmlComments(filename)" method twice with specific file names.

[Reference.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/4423597/Reference.txt)

**Issue:**
Comments from both of these files are getting included and are visible in swagger, when code is executed on localhost. But when we commit the solution in PR environment only a few of comments appear. On analysis our judgement is in PR environment the comments provided by 2nd file "Api2.xml" is getting included. Its appearing as if the comments which are provided in 1st file (execution of code order) is over written by 2nd file and hence none of the comments of 1st file is appearing. 

I will be really grateful if you can help us with the issue. Please let us know in case any other information is required from our end.

Regards,
Almas Hasnain

**Comment by domaindrivendev** [comment]
`Swashbuckle.Core` an old version of Swashbuckle that's targeted to WebApi as opposed to ASP.NET Core. There's a separate github project for it ([see here](https://github.com/domaindrivendev/Swashbuckle)) and this issue should be posted there instead.

With that said, it's an old stack and development on it has pretty much come to a halt in favor of the ASP.NET Core specific project.
