### ISSUE TITLE
Link to Swagger doc broken in reverse-proxy scenario

### ISSUE THREAD

**Issue by TaffarelJr** [domaindrivendev/Swashbuckle.AspNetCore#1624]
My app was originally set up this way:
```csharp
app.UseRouting();
app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/swagger/v1/swagger.json", "My API v1");
});
```

However I need to deploy it in a reverse-proxy scenario for production. So I modified the code as suggested in #1253:
```csharp
app.UsePathBase("/some/root/path");
app.UseRouting();
app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("v1/swagger.json", "My API v1");
});
```

Now the Swagger UI is accessible from both
- `/swagger`
- `/some/root/path/swagger`

... and the Swagger doc is accessible from both
- `/swagger/v1/swagger.json`
- `/some/root/path/swagger/v1/swagger.json`

Which is perfect.
However, looking at the Swagger UI, the link to the Swagger doc is broken. Here's the markup being generated:
```html
<a target="_blank" href="about:blank" rel="noopener noreferrer" class="link">
    <span class="url">
        <!-- react-text: 72 -->
        <!-- /react-text -->
        <!-- react-text: 73 -->
        "v1/swagger.json"
        <!-- /react-text -->
        <!-- react-text: 74 -->
        <!-- /react-text -->
    </span>
</a>
```

Obviously, clicking on it brings up an empty about:blank page instead of the expected swagger.json.

I wasn't sure if this issue belonged over at swagger-ui instead; but since I'm following #1253, I thought I'd post here first.

- .NET Core 3.1 application
- Swashbuckle.AspNetCore 5.3.1

**Comment by domaindrivendev** [comment]
This is indeed an [upstream issue](https://github.com/swagger-api/swagger-ui/issues/4107) with the swagger-ui library.

However, the latest version of Swashbuckle (`v5.3.2`) contains a workaround to address the issue in lieu of an upstream-fix. Please pull that down and let me know if that works?

**Comment by takato1314** [comment]
Hi. I just upgrade from v5.3.1 to v5.3.3 just now and confirms that the current workaround is working.

**Comment by diogonborges** [comment]
> 
> 
> Hi. I just upgrade from v5.3.1 to v5.3.3 just now and confirms that the current workaround is working.

Which workaround @takato1314 ?

**Comment by takato1314** [comment]
> This is indeed an [upstream issue](https://github.com/swagger-api/swagger-ui/issues/4107) with the swagger-ui library.
> 
> However, the latest version of Swashbuckle (`v5.3.2`) contains a workaround to address the issue in lieu of an upstream-fix. Please pull that down and let me know if that works?

I was referring to this workaround that @domaindrivendev mentioned. Basically i got the same problem as the the author while using v5.3.1 and after upgrading it to the latest (v5.3.3), then the same problem was resolved on my side.

**Comment by TaffarelJr** [comment]
Sorry, I got pulled away onto other things for a while. I brought down the latest library (5.4.1) and it's working for me too. Thanks for your help!
