### ISSUE TITLE
Polymorphic response: the base type is missing from the list

### ISSUE THREAD

**Issue by xlegalles** [domaindrivendev/Swashbuckle.AspNetCore#1626]
I'm using v5.2.1

I have a simple use case with a response `[ProducesResponseType(typeof(ParamDto[]), (int)HttpStatusCode.OK)]`

`ParamDto `is _not_ abstract and have several subtypes. 

**Actual result:**
When looking at the generated swagger file, I get:
```
"schema": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "$ref": "#/components/schemas/DoubleParamDto"
                      },
                      {
                        "$ref": "#/components/schemas/EnumParamDto"
                      },
                      {
                        "$ref": "#/components/schemas/IntegerParamDto"
                      }
                    ]
                  }
                }
```
**Expected result:**
`"$ref": "#/components/schemas/ParamDto"` should be part of the list

**Comment by xlegalles** [comment]
Tried annotations and this:
`[SwaggerSubTypes(typeof(ParamDto), typeof(DoubleParamDto), typeof(EnumParamDto), typeof(IntegerParamDto))]
`
Got a StackOverFlowException!

Note that `c.SchemaGeneratorOptions.GeneratePolymorphicSchemas `is false
and I just use `c.EnableAnnotations(enableSubTypeAnnotations:true);`

Tried to update the list of OneOf from SchemaFilter and same: StackOverFlowException!
Knowing that there is already a ticket [related to a specific type resolver](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1433), I don't know if I have many workarounds left.

**Comment by xlegalles** [comment]
Next step: I tried to add a fake parent type to get all the hierarchy. So to summarize

- DoubleParamDto :: ParamDto :: SwaggerParamDto
- EnumParamDto :: ParamDto :: SwaggerParamDto
- IntegreParamDto :: ParamDto :: SwaggerParamDto

With `[ProducesResponseType(typeof(SwaggerParamDto[]), (int)HttpStatusCode.OK)]`

And I get this crazy schema!

```
"oneOf": [
                      {
                        "$ref": "#/components/schemas/DoubleParamDto"
                      },
                      {
                        "$ref": "#/components/schemas/EnumParamDto"
                      },
                      {
                        "$ref": "#/components/schemas/IntegerParamDto"
                      },
                      {
                        "oneOf": [
                          {
                            "$ref": "#/components/schemas/DoubleParamDto"
                          },
                          {
                            "$ref": "#/components/schemas/EnumParamDto"
                          },
                          {
                            "$ref": "#/components/schemas/IntegerParamDto"
                          }
                        ]
                      }
                    ]
```

**Comment by domaindrivendev** [comment]
This is a dup of #1433. The issue is being tracked there so no need for a second issue
