### ISSUE TITLE
Unknown Type: ınteger problem

### ISSUE THREAD

**Issue by SarperMUTLUBAY** [domaindrivendev/Swashbuckle.AspNetCore#1627]
I upgraded Swashbuckle.AspNetCore to 5.3.1 and then I realized that the values that used to be "integer" are now "ınteger". It see (ı)nteger type not (i)nteger and i can no longer send integer parameters api.

![image](https://user-images.githubusercontent.com/10811371/79536801-8fd1fd00-8089-11ea-948f-ce7cdca43abb.png)

![image](https://user-images.githubusercontent.com/10811371/79536820-9c565580-8089-11ea-967e-7e7f27680217.png)

**Comment by domaindrivendev** [comment]
Weird ... although I'm unable to repro this issue on my side. Could you please create a minimal project that repro's the issue and post to github so I can pull down to investigate further?

**Comment by SarperMUTLUBAY** [comment]
I created and shared the repository url at the bottom. 

https://github.com/SarperMUTLUBAY/SwaggerUIBug

![image](https://user-images.githubusercontent.com/10811371/79691620-6374d700-8269-11ea-94cc-60e91389403d.png)

![image](https://user-images.githubusercontent.com/10811371/79691625-712a5c80-8269-11ea-80e9-8e1ca72574f9.png)

**Comment by domaindrivendev** [comment]
@SarperMUTLUBAY thanks for putting together the sample application. Unfortunately though, your issue does not repro for me, even when I spin up your sample application:
![screenshot](https://user-images.githubusercontent.com/1434343/79734209-3f0f0e00-82ee-11ea-8033-be76339d83fc.png)

So, there's some weird, environment-specific bug going on, and I'm suspecting it's more likely to be an issue with the [swagger-ui project](https://github.com/swagger-api/swagger-ui) rather than Swashbuckle itself. Perhaps a browser compatability issue - could you ket me know which browser you're using?

**Comment by domaindrivendev** [comment]
Additionally, in your repro environment, could you please navigate to the Swagger/OpenAPI JSON endpoint (e.g. http://localhost:5000/swagger/v1/swagger.json) and confirm that the word "integer" is displayed correctly wherever it's used in the JSON?

**Comment by SarperMUTLUBAY** [comment]
i will check and share result asap.

**Comment by developeravci** [comment]
Sorunu Culture ayarlarını set ederek aşabilirsin. Startup configure metodu içerisinde;

`
            var cultureInfo = new CultureInfo("en-US");
            CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
            CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
`
Culture ayarlarını en-US olarak set edersen sorunun çözülür.

**Comment by SarperMUTLUBAY** [comment]
@developeravci yanıt için teşekkürler hocam aklımda bulunduracağım ancak önceki versiyonlarda olmayan bir sorun geldiğinden swagger tarafı hallederse daha iyi olacaktır. Bilgisayarım tamamen ingilizce ve serverlar da ingilizce olduğu halde bu problemi yaşıyorum. Versiyon güncellemesi öncesinde yoktu.

**Comment by developeravci** [comment]
@SarperMUTLUBAY Rica ederim. Bence de swagger tarafı halletmeli.

**Comment by domaindrivendev** [comment]
@SarperMUTLUBAY - were you able to check what the raw Swagger/OpenAPI that's being returned by Swashbuckle looks like?

It's looking like this is some kind of localization issue, but I'm not sure exactly where the issue lies. When Swashbuckle serializes it's `OpenApiDocument` to JSON, it uses a culture invariant `StringWriter` so I would expect the JSON to be OK:

```csharp
private async Task RespondWithSwaggerJson(HttpResponse response, OpenApiDocument swagger)
{
    response.StatusCode = 200;
    response.ContentType = "application/json;charset=utf-8";

    using (var textWriter = new StringWriter(CultureInfo.InvariantCulture))
    {
        var jsonWriter = new OpenApiJsonWriter(textWriter);
        if (_options.SerializeAsV2) swagger.SerializeAsV2(jsonWriter); else swagger.SerializeAsV3(jsonWriter);

        await response.WriteAsync(textWriter.ToString(), new UTF8Encoding(false));
    }
}
```

**Comment by developeravci** [comment]
Not Set CultureInfo > swagger.json ;

![11](https://user-images.githubusercontent.com/36299664/79763669-0b070d80-832d-11ea-9f45-d136d0ce36ef.png)

Set CultureInfo > swagger.json ;

```CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;```

![22](https://user-images.githubusercontent.com/36299664/79763804-3689f800-832d-11ea-8eb0-e1196f2ec763.png)

**Comment by SarperMUTLUBAY** [comment]
@domaindrivendev I checked and it looks the same

![image](https://user-images.githubusercontent.com/10811371/79800193-75877000-8364-11ea-885d-719bdb644279.png)

**Comment by domaindrivendev** [comment]
@SarperMUTLUBAY, @developeravci - thanks for your help in getting to the bottom of this. It turns out there was a bug in the Swashbuckle code that was causing this.

I've [merged a fix](6d4d5f40e00acdd8ac52cc833c6ef4d78e959ef5) and am pushing out a new patch release (`v5.3.3`) right now.

**Comment by developeravci** [comment]
@developeravci 
yes, bug has fixed. thank you.

**Comment by developeravci** [comment]
@domaindrivendev 
yes, bug has fixed. thank you.
