### ISSUE TITLE
camelCase properties on a complex type model

### ISSUE THREAD

**Issue by stevejgordon** [domaindrivendev/Swashbuckle.AspNetCore#163]
I have a model such as:

```
/// <summary>
/// Represents the properties required to support user authentication
/// </summary>
public class LoginInputModel
{
    /// <summary>
    /// The email address (used as username) for the user attempting to login
    /// </summary>
    [Required]
    public string Email { get; set; }

    /// <summary>
    /// The password of the user attempting to login
    /// </summary>
    [Required]
    public string Password { get; set; }
}
```

On my login action I have something like:

```
[HttpPost("[action]"), AllowAnonymous]
[Produces("application/json", Type = typeof(GenerateJwtResult))]
[SwaggerResponse(System.Net.HttpStatusCode.OK, Type = typeof(GenerateJwtResult))]
public async Task<IActionResult> Login([FromForm] LoginInputModel model)
{
  ...
}
```

I was hoping in the swagger UI it would show the properties email and password in camelCase but this doesn't seem to be the case. Is this possible to configure?

I've added this in my services method 

```
AddMvc().AddJsonOptions(options =>
{
    options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
});

```

and then 

```
// Register Swagger
services.AddSwaggerGen();
services.ConfigureSwaggerGen(options =>
{
    options.SingleApiVersion(new Info
    {
        Version = "v1",
        Title = "API",
        Description = "An API"
    });
    options.DescribeAllEnumsAsStrings();
});
```

Most things show as camelCase for the output models but the input one still seems to be pascal.

![image](https://cloud.githubusercontent.com/assets/3669103/17929231/0b060ffa-69f7-11e6-8b9c-8dd8bd95bae2.png)

**Comment by SimonTouchtech** [comment]
Well, you're using FromForm, which means the input is explicitly not JSON, so any JSON options you set will not (or at least should not) impact form input. 

I am unsure how ASP.NET model binding for form input works but it's either case sensitive or not. If it is, the Swagger document created is correct and camelCase wouldn't work. If it is not the name ASP.NET provides to SwaggerGen will still be the original as ASP.NET does not know of your intention to camel-case the parameter names. 

What you're asking for is basically either an option in SwaggerGen or ASP.NET to ensure camelCase for form input. I don't think there is such an option today (but I could be wrong).

As a side note, if you want the strings for your enums to be camelCase as well you should add `options.DescribeStringEnumsInCamelCase();` after `options.DescribeAllEnumsAsStrings();`.

**Comment by SimonTouchtech** [comment]
Related to issue #160, which basically asks for the same thing (camelCase support), but for FromQuery.

**Comment by stevejgordon** [comment]
@SimonTouchtech - Many thanks for taking the time to reply. Your comment makes sense based on the FromForm usage. The link to issue 160 helped as I'm using the FromForm(Name="") attribute on my properties now which seems to work for my needs. Would still be nice if the properties could be camelCased automatically for the generated swagger.

**Comment by khellinxdigipolis** [comment]
Is there a widely accepted convention for this?
Although Microsoft suggests using camelCase for query parameters (https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md), I'm not sure Microsoft should be the only reference.

At the company where I'm currently empoyed, convention is to use lowercase (eg: pagesize) but I've seen other uses (eg: Facebook uses snake_case if I'm not mistaken).

I've forked your repo and I am adding an option QueryParametersCapitalization to SchemaRegistryOptions of enum type CapitalizationType:
`    public enum CapitalizationType
    {
        None,
        CamelCase,
        PascalCase,
        SnakeCase,
        KebabCase
    }`

The generator then converts the query parameter names.
Ofcourse, model binding would also need its custom implementation but that's outside of Swashbuckle's scope.

**Comment by domaindrivendev** [comment]
See d8ba4d35c17afa3f1d06884b9653a89ea746fe3c

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"

**Comment by RamunasAdamonis** [comment]
Is there a way to do this in .Net Core 2.2?

**Comment by Dissimilis** [comment]
> Is there a way to do this in .Net Core 2.2?

For everyone who might be looking, this does the trick:

```
services.AddSwaggerGen(c =>
{
   c.DescribeAllParametersInCamelCase();
}
```
