### ISSUE TITLE
Clearing SecuritySchemes/SecurityRequirements from a DocumentFilter permanently removes them

### ISSUE THREAD

**Issue by mix4242** [domaindrivendev/Swashbuckle.AspNetCore#1632]
**Bug report**

- Swashbuckle: 5.3.2
- .NET Core: 3.1.200

I have a Document Filter that suppresses Paths and Schemas when requested by unauthenticated/unauthorized users. It works great.

I now wanted to further remove the `components.securitySchemes` and `security` sections of the generated Swagger JSON.

My code inside the Document Filter:
```
public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
{
   (...)

   if (!isAuthenticated)
   {
      // Work fine
      swaggerDoc.Paths.Clear();
      swaggerDoc.Components.Schemas.Clear();

      // Added new
      swaggerDoc.Components.SecuritySchemes.Clear();
      swaggerDoc.SecurityRequirements.Clear();

      return;
   }

   (...)
}
```

However when I add the new lines to suppress the security content of the JSON, after the first request by an unauthenticated user, when it correctly suppresses all info I want, all further requests by legitimate, authenticated users result in both `components.securitySchemes` and `security` sections being always missing. It seems the `Clear`s are doing a permanent job of clearing those details :/

Please see screens: 
First, authenticated request:
![Screenshot 2020-04-21 at 12 37 28](https://user-images.githubusercontent.com/5556295/79861885-0c881280-83cd-11ea-8548-a84ef7c20ddb.png)

Unauthenticated:
![Screenshot 2020-04-21 at 12 38 07](https://user-images.githubusercontent.com/5556295/79861915-1a3d9800-83cd-11ea-9441-c601e0ef865b.png)

All subsequent authenticated:
![Screenshot 2020-04-21 at 12 39 48](https://user-images.githubusercontent.com/5556295/79861986-3b05ed80-83cd-11ea-8d1f-bcbf23f9abb8.png)

Please let me know if I am doing anything incorrectly. 
Thanks :)

**Comment by domaindrivendev** [comment]
Off the top of my head I can't think of anything that would cause this. Could you please create a minimal application that repros the issue and post to github so I can pull down and troubleshoot further?

**Comment by mix4242** [comment]
Thanks for the prompt response!

Here it the test repo: [https://github.com/mix4242/Swashbuckle.AspNetCore_issues_1632_test_repo](url)

I have created a new .NET Core Web App in Rider and the only code changes I have made are in `Startup.cs`. I also added Swashbuckle.AspNetCore: 5.3.3 & Swashbuckle.AspNetCore.Newtonsoft: 5.3.3.

I 'use' Swagger and SwaggerUI and I add Swagger Gen with a SecurityRequirement and a SecurityDefinition, and a Document filter, `SuppressContentDocumentFilter` defined in the same file. 

The document filter simply looks for a presence of any query string in the request and if present suppresses the content of the JSON.

The first time I navigate to `https://localhost:5001/api-docs/v1/docs.json` all is well, paths/schemas and both `security` and `components.securitySchemes` are present and accounted for.

When I then head to `/api-docs/v1/docs.json?suppress`, all is correctly removed as I would expect. 

However on going back to `/api-docs/v1/docs.json` (by changing URL, back button will fetch from cache) the paths/schemas are once more present but the `security` and `components.securitySchemes` sections no longer exist - as per original post.

Thank you for your help

**Comment by domaindrivendev** [comment]
Thanks for posting that - always makese it much easier to resolve. If you update your filter implementation as follows, you should be good:

```csharp
public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
{
    if (this._httpContextAccessor.HttpContext.Request.QueryString.HasValue)
    {
        swaggerDoc.Paths = new OpenApiPaths();
        swaggerDoc.Components.Schemas = new Dictionary<string, OpenApiSchema>();

        swaggerDoc.Components.SecuritySchemes = new Dictionary<string, OpenApiSecurityScheme>();
        swaggerDoc.SecurityRequirements = new List<OpenApiSecurityRequirement>();
        return;
    }
}
```

To explain, The security schemes and requirements are assigned to the generated Swagger/OpenAPI document directly from the `SwaggerGeneratorOptions` instance which is a singleton instance that's injected via the ASP.NET Core "Options" API. So, when you apply the `Clear` method, you're updating the underlying state of that singleton instance.

This is definitely a bit of an unexpected gotcha and I'll look into a SB change to prevent it, but in the meantime the filter update should work for you.

**Comment by domaindrivendev** [comment]
Just pushed 0e9f7c4542e2084693d10043a36424f343762e05 to prevent people getting caught out by this in future.

**Comment by mix4242** [comment]
Amazing! Thank you very much 😄
