### ISSUE TITLE
Class as a member no longer nullable (5.0.0+)

### ISSUE THREAD

**Issue by HolopaMir** [domaindrivendev/Swashbuckle.AspNetCore#1633]
Repro: https://github.com/Enegia/SwaggerClassAsAMemberBugRepro/tree/master/SwaggerClassAsAMemberBugRepro/SwaggerClassAsAMemberBugRepro

Behaviour:
```
public class Example {
  [JsonProperty(Required = Required.Default)]
  public SubClass SubClassThatIsNull {get; set;}
}
```
That used to generate as a nullable property in 5.0.0:
```
"properties": {
              "SubClassThatIsNull": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/SubClass"
                  }
                ],
                "nullable": true
              }
}
```

But now (5.3.3) class is defined in json as:
```
"properties": {
              "SubClassThatIsNull": {
                "$ref": "#/components/schemas/SubClass"
              }
}
```

When we are generating client from that, we are unable generate SubClassThatIsNull as a nullable property.

Is there some new alternative way to make Sub class nullable?

**Comment by domaindrivendev** [comment]
This is essentially a dup of #1589. Long story short, apply the `UseAllOfToExtendReferenceSchemas` setting to get the behavior you're expecting.
