### ISSUE TITLE
Regression of duplicate enum values

### ISSUE THREAD

**Issue by Fnatte** [domaindrivendev/Swashbuckle.AspNetCore#1636]
Hi,

I think there has been a regression of #1077. I have found duplicate enum values in swagger.json that causes generated models to not compile. In fact, the example in #1077 with HttpStatusCode is the exact same use case that I'm struggling with.

See the fix in commit 5798c2cb1d9265dd9c8d18c5b97b633fa62cccf0. That `Distinct()` call is missing in current implementations:
* https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/316ddd0fe6768f470c274a0e93c789b65cf658b9/src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs#L143-L144
* https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/316ddd0fe6768f470c274a0e93c789b65cf658b9/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs#L77

#1605 may be related, but I don't understand that issue.

So to clarify the issue here, when generating swagger.json for e.g. HttpStatusCode the output enum will contain duplications of 301 because HttpStatusCode defines Moved and MovedPermanently as 301. I believe that duplicates should be removed with `Distinct()` as it was before.

Thanks,
Matteus H

**Comment by domaindrivendev** [comment]
Fixed by 830e2cbfd14098fa1b79df4e532eb53c9c81e895
