### ISSUE TITLE
Will Swachbuckle.AspNetCore.Cli support netcore3.1?

### ISSUE THREAD

**Issue by JennelleMaierPie** [domaindrivendev/Swashbuckle.AspNetCore#1644]
I'd like to use the Cli with a netcore3.1 project.  I'm getting this error when I try to install the package: Package Swashbuckle.AspNetCore.Cli 5.4.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Swashbuckle.AspNetCore.Cli 5.4.0 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any.

Are there plans to support netcore3.1 in the future?

**Comment by domaindrivendev** [comment]
100% it needs to be supported. In fact - I think the lack of support is an (unexpected) regression introduced by https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1637

**Comment by domaindrivendev** [comment]
Investigating ...

**Comment by domaindrivendev** [comment]
No repro for me. Did you follow the installation steps [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#retrieve-swagger-directly-from-a-startup-assembly)?

Worth noting that this tool is installed as a .NET CLI tool and NOT as a `PackageReference` in your project

**Comment by JennelleMaierPie** [comment]
You're quite right, sorry for not following the documentation.  I've got it installed now.
