### ISSUE TITLE
After upgrading to 5.4.0 when using Newtonsoft serialization [JsonRequired] fields are marked as nullable

### ISSUE THREAD

**Issue by RedwoodForest** [domaindrivendev/Swashbuckle.AspNetCore#1645]
After upgrading from 4.x to 5.4.0 (including enabling Newtonsoft serializer support) model object fields marked with ```[JsonRequired]``` are marked as nullable in the swagger.json (and shown as nullable in the UI).

[JsonProperty(Required = Required.Always)]``` works as expected (these fields are not marked as nullable).

Code:
```
public class TestDto {
    [JsonRequired]
    public String jsonRequired;
  
    [JsonProperty(Required = Required.Always)]
    public String jsonProperty;
}
```

swagger.json:
```
"jsonRequired": {
  "type": "string",
  "nullable": true
},
"jsonProperty": {
  "type": "string"
}
```

For now I've worked around this issue by converting all our models to use the JsonProperty approach.

**Comment by domaindrivendev** [comment]
This is indeed a regression that was introduced in the 5.x line. I just pushed c4dcb1b82ed311c5e5f7890157f392a00002d911 to fix it. Preparing a `v5.4.1` patch release now ...

**Comment by RedwoodForest** [comment]
Thanks!
