### ISSUE TITLE
After upgrading to 5.4.1 when explicitly mapping a struct type the mapping it not used for the nullable version

### ISSUE THREAD

**Issue by RedwoodForest** [domaindrivendev/Swashbuckle.AspNetCore#1648]
In 4.x if you explicitly specified a mapping for a struct type it would also be used for the nullable version of the struct. In 5.4.1 you have to explicitly map the nullable version as well. Is this change intentional?

In our API we use NodaTime.Serialization.JsonNet.Extensions.ConfigureForNodaTime to add support for (de)serializing NodaTime types (like Instant) in DTOs. For example Instant is serialized to a String like `2013-07-26T16:45:20.1234567Z`. Because of this we need to explicitly map these types in Swashbuckle so that it knows about this as well:

```
swaggerGenOptions.MapType(
    typeof(Instant),
    () => new OpenApiSchema {
        Type = "string"
    });
```

And here's an example DTO:
```
public class TestDto {
        public Instant instant;
        public Instant? nullableInstant;
}
```

In 4.x they would both be mapped as a string in swagger.json but in 5.x only the non-nullable one is:
```
"instant": {
  "type": "string"
},
"nullableInstant": {
  "nullable": true
}
```

Adding a mapping for `Instant?` works as expected.

Was this change intentional?

**Comment by thomaslevesque** [comment]
I just hit this problem as well. It's probably easy to fix, I'll try to send a PR.

**Comment by domaindrivendev** [comment]
Yes - this change was intentional, and to that point probably should be mentioned as a breaking change in the 5.0.0 release notes (I will update this). The purpose of `MapType` is to support custom C# Type to Schema mappings. As `Nullable<T>` and `T` are different types, they're should be separate mappings for each.

**Comment by thomaslevesque** [comment]
@domaindrivendev thanks for your answer.

Is there any scenario where it would be useful to have different schema for `T` and `Nullable<T>`?

In 99% of cases, people would probably want `Nullable<T>` to have the same schema as `T` (except for the `nullable` attribute of course). In the 1% where they don't, they can always explicitly specify a schema for `Nullable<T>`. So I think it would make sense to cater to the 99% by default, while allowing the 1% to override if necessary.

What do you think?

**Comment by RedwoodForest** [comment]
I found the old behavior much more intuitive. If nothing else maybe there could be an extension method or option to automatically map nullable structs as well?

In case it's helpful to future readers this is how we're mapping the nullable versions without having to explicitly specify them:
```
// Based on the list of serializable types from https://nodatime.org/1.2.x/userguide/serialization
var nodaTimeTypesSerializedAsString = new [] { 
    typeof(Instant),
    typeof(OffsetDateTime),
    typeof(ZonedDateTime),
    typeof(LocalDateTime),
    typeof(LocalDate),
    typeof(LocalTime),
    typeof(Offset),
    typeof(Interval),
    typeof(Duration),
};

// As of version 5.x the nullable versions of types need to be explicitly specified too.
// https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1648
nodaTimeTypesSerializedAsString = nodaTimeTypesSerializedAsString
    .Concat(nodaTimeTypesSerializedAsString.Select(x => typeof(Nullable<>).MakeGenericType(x)))
    .ToArray();

foreach (var type in nodaTimeTypesSerializedAsString) {
    // https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#override-schema-for-specific-types
    swaggerGenOptions.MapType(
        type,
        () => new OpenApiSchema {
            Type = "string"
        });
}
```

**Comment by the-claw** [comment]
> Yes - this change was intentional, and to that point probably should be mentioned as a breaking change in the 5.0.0 release notes (I will update this). The purpose of `MapType` is to support custom C# Type to Schema mappings. As `Nullable<T>` and `T` are different types, I felt it more appropriate to require separate mappings for each.

This behaviour conflicts with #1551 (support for open generics in MapType()): due to this change I cannot register a type map for Nullable<MyOpenGeneric<>>, as the language will not allow open generics to be nested in this way. The behaviour described by @thomaslevesque would definitely be preferred.

**Comment by cm-sdpick** [comment]
Any update on this? It's been over a year and we're still blocked on upgrading due to it.

**Comment by the-claw** [comment]
Any update on this? It's been over a year and we're still blocked on upgrading due to this issue. Thanks.

**Comment by martincostello** [comment]
Closing as this was answered as being an intentional change.
