### ISSUE TITLE
Example in comments not displayed for DateTimeOffset.

### ISSUE THREAD

**Issue by simonvane** [domaindrivendev/Swashbuckle.AspNetCore#1649]
I am using  Swashbuckle.AspNetCore 5.4.1 / Swashbuckle.AspNetCore.Newtonsoft 5.4.1.

I have a DTO as follows:
```
public class MermbershipDto
{
    /// <summary>
    /// The date and time when the Membership was created.
    /// </summary>
    /// <example>2019-06-17T15:35:06.216Z</example>
    public DateTimeOffset Created { get; set; }
}
```
And the example value is displayed as follows:
```
{
  "created": "17/06/2019 15:35:06 +00:00"
}
```
This ignores the example in the comments. This is problematic for us because the displayed format is not a format we accept.

- Is it intended that the example comment is ignored in this case?
- Is there a workaround?

**Comment by vbjay** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1655#issuecomment-624383406
