### ISSUE TITLE
 [5.2.1] [.NET CORE 3.1] IncludeXmlComments throws null reference

### ISSUE THREAD

**Issue by rvarna** [domaindrivendev/Swashbuckle.AspNetCore#1652]
This issue is similar to https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1521
I tried posting on it but the issue was already closed and didn't get a response.

When including xml comments for swagger generation, we get a stack trace on navigating to the swagger json file (works if we remove xml comments). This was working earlier when we were on Swashbuckle.Core 5.6.0 and .net 4.6.2 and we are trying to migrate over to .net core.

Configuration:
```
services.AddSwaggerGen(c =>
                {
                    //c.Schemes(new[] { "https" });
                    c.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo()
                    {
                        Title = "My Title",
                        Version = "v1",
                        Description = "My API"
                    });
                    c.IncludeXmlComments("Api.xml");
                    c.DescribeAllEnumsAsStrings();
                });
```

I have verified that the Api.xml exists. I have also tried the following variant:
```
var xmlFile = $"Api.xml"; 
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    c.IncludeXmlComments(xmlPath);
```
The result is the same stack trace.

The stack trace:
```
{"error":"System.ArgumentException: The argument 'name' is null, empty or consists only of white-space. (Parameter 'name')\r\n   at   
Microsoft.OpenApi.Writers.OpenApiWriterExtensions.CheckArguments(IOpenApiWriter writer, String name)\r\n   at Microsoft.OpenApi.Writers.OpenApiWriterExtensions.CheckArguments[T](IOpenApiWriter writer, String name, Action`2 action)\r\n   at   
Microsoft.OpenApi.Writers.OpenApiWriterExtensions.WriteRequiredObject[T](IOpenApiWriter writer, String name, T value, Action`2 action)\r\n   at  

 Microsoft.OpenApi.Models.OpenApiExtensibleDictionary`1.SerializeAsV3(IOpenApiWriter writer)\r\n   at Microsoft.OpenApi.Models.OpenApiOperation.<>c.<SerializeAsV3>b__53_4(IOpenApiWriter w, OpenApiResponses r)\r\n   at 
  Microsoft.OpenApi.Writers.OpenApiWriterExtensions.WriteRequiredObject[T](IOpenApiWriter writer, String name, T value, Action`2 action)\r\n   at 
  Microsoft.OpenApi.Models.OpenApiOperation.SerializeAsV3(IOpenApiWriter writer)\r\n   at Microsoft.OpenApi.Models.OpenApiPathItem.<>c.<SerializeAsV3>b__25_2(IOpenApiWriter w, OpenApiOperation o)\r\n   at 
  Microsoft.OpenApi.Writers.OpenApiWriterExtensions.WriteRequiredObject[T](IOpenApiWriter writer, String name, T value, Action`2 action)\r\n   at 
  Microsoft.OpenApi.Writers.OpenApiWriterExtensions.WriteOptionalObject[T](IOpenApiWriter writer, String name, T value, Action`2 action)\r\n   at 
  Microsoft.OpenApi.Models.OpenApiPathItem.SerializeAsV3(IOpenApiWriter writer)\r\n   at Microsoft.OpenApi.Models.OpenApiExtensibleDictionary`1.<>c.<SerializeAsV3>b__4_0(IOpenApiWriter w, T p)\r\n   at 
  Microsoft.OpenApi.Writers.OpenApiWriterExtensions.WriteRequiredObject[T](IOpenApiWriter writer, String name, T value, Action`2 action)\r\n   at 
  Microsoft.OpenApi.Models.OpenApiExtensibleDictionary`1.SerializeAsV3(IOpenApiWriter writer)\r\n   at Microsoft.OpenApi.Models.OpenApiDocument.<>c.<SerializeAsV3>b__32_2(IOpenApiWriter w, OpenApiPaths p)\r\n   at 
  Microsoft.OpenApi.Writers.OpenApiWriterExtensions.WriteRequiredObject[T](IOpenApiWriter writer, String name, T value, Action`2 action)\r\n   at 
  Microsoft.OpenApi.Models.OpenApiDocument.SerializeAsV3(IOpenApiWriter writer)\r\n   at 
  Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.RespondWithSwaggerJson(HttpResponse response, OpenApiDocument swagger)\r\n   at 
  Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at 
  
```

We do have a lot of CS1591 errors (Missing XML comment for publicly visible type or member) that we see during xml generation. However, it has never been a problem before. The stacktrace and error message aren't helpful. Is there a better way to debug this?

**Comment by domaindrivendev** [comment]
The NRE exception is occurring in a [separate library](https://github.com/microsoft/OpenAPI.NET) that's leveraged but not maintained by SB. So, to resolve this, I would need to lean on you to dig deeper.

There's obviously something in the `OpenApiDocument1`, which is generated by Swashbuckle, that the library doesn't like when it tries to serialize to JSON. But, as you said, the stack trace doesn't give us much to work with.

If you could create a minimal project (i.e. start from scratch and add operations until you get a repro) that repro's the issue and then post it to github, then I could pull it down and take a look. Alternatively, you could pull down the source for the aforementioned third-party library - add it as a reference to your app, and then debug the NRE to figure out what's going on?

**Comment by rvarna** [comment]
@domaindrivendev , Thank you for the response. We are a full fledged service and have lot of controllers and methods, but I agree with the proposed debugging steps. I will try out a semi-binary search by adding /removing methods to see which ones trigger this and see how it goes.

**Comment by rvarna** [comment]
So, it turns out our issue wasn't far off from https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1521 either. We had a typo in one file, in one xml comment
<response **codde**="200">OK</response>

Fixing that resolved the issue. I will close this topic

**Comment by dylangmiles** [comment]
> So, it turns out our issue wasn't far off from #1521 either. We had a typo in one file, in one xml comment <response **codde**="200">OK
> 
> Fixing that resolved the issue. I will close this topic

I had `<response Code="200">foo</response>` which cause the same issue. Changing to `<response code="200">foo</response>` fixed it for me.
