### ISSUE TITLE
MultiFile upload UI does not send files to controller.

### ISSUE THREAD

**Issue by kailasdp2000** [domaindrivendev/Swashbuckle.AspNetCore#1653]
Using Swashbuckle.AspNetCore 4.0.1 installed with nugetpackage manager in a WebAPI solution.
OS - Windows 10
Browser - Chrome - Version 81.0.4044.129 (Official Build) (64-bit)

**I intend to implement user friendly interface for multi-file upload.**

**Issue description -**
In solution, IOperationFilter is implemented, it checks:
```
param.ParameterType == typeof(IFormFile[]) && param.ParameterType.IsArray
```
If so, then a new parameter is constructed in below fashion:
```

                var newParameter = new NonBodyParameter
                {
                    Type = "array",
                    In = "formData",
                    Description = oldParameter.Description,
                    Name = oldParameter.Name,
                    Required = oldParameter.Required,
                    CollectionFormat = "multi"
                };

                PartialSchema partialSchema = new PartialSchema { Type = "file", Format = "binary", CollectionFormat = "form-data" };
                newParameter.Items = partialSchema;

                operation.Parameters.Add(newParameter);
                operation.Consumes.Add("multipart/form-data");
```
Controller signature:
```
MyController(string branch, [Required] IFormFile[] templateFiles)
```

With these changes, I get multifile UI and I am able to select multiple files.
But, when the request is received by the controller, templateFiles does not contain any files.

However, when tried from Postman (with Body provided as form-data) it works well.
This seems to be very much similar to the issue mentioned below.
https://github.com/swagger-api/swagger-ui/issues/2617#issuecomment-495192035

**Comment by domaindrivendev** [comment]
Dup of #1029, which is now resolved
