### ISSUE TITLE
C# DatetimeOffset not using correct Format in examples

### ISSUE THREAD

**Issue by vbjay** [domaindrivendev/Swashbuckle.AspNetCore#1655]
PackageReference Include="Swashbuckle.AspNetCore" Version="5.2.1" 

See #375 and #1649 for similar issues
The model I am using
```c#
 public class DeliverBetween : IValidatableObject
    {
        /// <summary>
        /// Expected time delivery should be completed by.  Can be in any format that can be parsed by <see cref="DateTimeOffset"/>
        /// </summary>
        /// <example>2049-01-01 15:00:00Z</example>
        [Required]
        public DateTimeOffset End { get; set; }

        /// <summary>
        /// Expected time delivery should start.  Can be in any format that can be parsed by <see cref="DateTimeOffset"/>
        /// </summary>
        /// <example>2049-01-01 17:00:00Z</example>
        [Required]
        public DateTimeOffset Start { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Start >= End)
                yield return new ValidationResult($"{nameof(Start)} must be before {nameof(End)}.", new string[] { nameof(Start) });
        }
    }
```
schema generated

```json
 "DeliverBetween": {
        "required": [
          "end",
          "start"
        ],
        "type": "object",
        "properties": {
          "end": {
            "type": "string",
            "description": "Expected time delivery should be completed by.  Can be in any format that can be parsed by System.DateTimeOffset",
            "format": "date-time",
            "example": "1/1/2049 3:00:00 PM +00:00"
          },
          "start": {
            "type": "string",
            "description": "Expected time delivery should start.  Can be in any format that can be parsed by System.DateTimeOffset",
            "format": "date-time",
            "example": "1/1/2049 5:00:00 PM +00:00"
          }
        }
```

![image](https://user-images.githubusercontent.com/3629489/81125478-3f222700-8f06-11ea-8f6e-6fffe2fd79fd.png)

I would like to be able to specify the format the example is generated in.  Iit to be in like https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.universalsortabledatetimepattern?view=netcore-3.1 or even better 8601 format with a Z.  Why is it that my response created at is in a different format( actually the one I want for all datetimeoffsets).

![image](https://user-images.githubusercontent.com/3629489/81126585-b86f4900-8f09-11ea-8e58-14e18bab304c.png)

response createdAt schema

```json
 "OrderResponse": {
        "type": "object",
        "properties": {
          "createdAt": {
            "type": "string",
            "description": "When the order was created",
            "format": "date-time"
          }
```

Order request  created at property

```c#
  public class OrderResponse
    {
        /// <summary>
        /// When the order was created
        /// </summary>
        public DateTimeOffset CreatedAt { get; set; }
    }
```

**Comment by vbjay** [comment]
Reading https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier 

I see 

> The "O" or "o" standard format specifier (and the "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK" custom format string) takes advantage of the three ways that ISO 8601 represents time zone information to preserve the Kind property of DateTime values:
The time zone component of DateTimeKind.Local date and time values is an offset from UTC (for example, +01:00, -07:00). **All DateTimeOffset values are also represented in this format.**
The time zone component of DateTimeKind.Utc date and time values uses "Z" (which stands for zero offset) to represent UTC.
DateTimeKind.Unspecified date and time values have no time zone information.

I can do this to force Z format

```c#
string value= DateTimeOffset.Parse(@"2049-1-1 1:00pm -04:00").UtcDateTime.ToString("o");
```
which results in 
2049-01-01T17:00:00.0000000Z

**Comment by domaindrivendev** [comment]
Dup of #1649
