### ISSUE TITLE
Swashbuckle.AspNetCore.Cli won't install under netcoreapp3.1

### ISSUE THREAD

**Issue by RManesiya** [domaindrivendev/Swashbuckle.AspNetCore#1656]
Thanks for contributing to Swashbuckle.AspNetCore! As per the [contributing guidelines](CONTRIBUTING.md), please adhere to the following rules of thumb before submitting your issue:

I get the following message when attempting to upgrade to Swashbuckle.AspNetCore.Cli, and I understand the error. When should we expect the support for .NET Core 3.1?

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	NU1202	Package Swashbuckle.AspNetCore.Cli 5.4.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Swashbuckle.AspNetCore.Cli 5.4.1 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / 

1. If it's not a bug report, feature request or PR, don't submit it here. Post to Stackoverflow instead.
2. If your issue is specifically a UI concern, don't submit it here. Post to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui).
3. For bug reports, specify the version your using and provide clear repro steps.

**Comment by domaindrivendev** [comment]
The CLI component is needs to be installed as a .NET Tool as opposed to a project reference. If you follow the [installation steps from the readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#retrieve-swagger-directly-from-a-startup-assembly), it should work against an app targeting `netcoreapp3.1` without issue. I've verified this myself locally. Please try that if you haven't done so already and let me know how it goes.

**Comment by RManesiya** [comment]
I followed the [steps located](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#retrieve-swagger-directly-from-a-startup-assembly) here.

After installing the tool I issued the following command and got an error:

`dotnet swagger tofile --output MyProject\wwwroot .\ MyProject\bin\Debug\netcoreapp3.1\MyProject.dll V1`

I checked the file location and the `C:\Users\[USERNAME]\.nuget\packages\swashbuckle.aspnetcore.cli\5.4.1\tools\netcoreapp2.1\any\dotnet-swagger.dll` does exists.

```
dotnet : Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\Users\RManesiya\.nuget\packages\swashbuckle.aspnetcore.cli\5.4.1\tools\netcoreapp2.1\any\dotnet-swagger.dll'. The located assembly's manifest definition does 
not match the assembly reference. (0x80131040)
At line:1 char:1
+ dotnet swagger tofile --output MyProject\wwwroot .\MyPro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...e. (0x80131040):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
File name: 'C:\Users\[USERNAME]\.nuget\packages\swashbuckle.aspnetcore.cli\5.4.1\tools\netcoreapp2.1\any\dotnet-swagger.dll'

```

**Comment by hiyangw** [comment]
Same issue here and same steps as @RManesiya

**Comment by hiyangw** [comment]
> I followed the [steps located](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#retrieve-swagger-directly-from-a-startup-assembly) here.
> 
> After installing the tool I issued the following command and got an error:
> 
> `dotnet swagger tofile --output MyProject\wwwroot .\ MyProject\bin\Debug\netcoreapp3.1\MyProject.dll V1`
> 
> I checked the file location and the `C:\Users\[USERNAME]\.nuget\packages\swashbuckle.aspnetcore.cli\5.4.1\tools\netcoreapp2.1\any\dotnet-swagger.dll` does exists.
> 
> ```
> dotnet : Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\Users\RManesiya\.nuget\packages\swashbuckle.aspnetcore.cli\5.4.1\tools\netcoreapp2.1\any\dotnet-swagger.dll'. The located assembly's manifest definition does 
> not match the assembly reference. (0x80131040)
> At line:1 char:1
> + dotnet swagger tofile --output MyProject\wwwroot .\MyPro ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (Unhandled excep...e. (0x80131040):String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
> File name: 'C:\Users\[USERNAME]\.nuget\packages\swashbuckle.aspnetcore.cli\5.4.1\tools\netcoreapp2.1\any\dotnet-swagger.dll'
> ```
Same issue here and same steps as @RManesiya

**Comment by hiyangw** [comment]
> > I followed the [steps located](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#retrieve-swagger-directly-from-a-startup-assembly) here.
> > After installing the tool I issued the following command and got an error:
> > `dotnet swagger tofile --output MyProject\wwwroot .\ MyProject\bin\Debug\netcoreapp3.1\MyProject.dll V1`
> > I checked the file location and the `C:\Users\[USERNAME]\.nuget\packages\swashbuckle.aspnetcore.cli\5.4.1\tools\netcoreapp2.1\any\dotnet-swagger.dll` does exists.
> > ```
> > dotnet : Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\Users\RManesiya\.nuget\packages\swashbuckle.aspnetcore.cli\5.4.1\tools\netcoreapp2.1\any\dotnet-swagger.dll'. The located assembly's manifest definition does 
> > not match the assembly reference. (0x80131040)
> > At line:1 char:1
> > + dotnet swagger tofile --output MyProject\wwwroot .\MyPro ...
> > + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> >     + CategoryInfo          : NotSpecified: (Unhandled excep...e. (0x80131040):String) [], RemoteException
> >     + FullyQualifiedErrorId : NativeCommandError
> >  
> > File name: 'C:\Users\[USERNAME]\.nuget\packages\swashbuckle.aspnetcore.cli\5.4.1\tools\netcoreapp2.1\any\dotnet-swagger.dll'
> > ```
> 
> Same issue here and same steps as @RManesiya

Please upgrade your Swagger libraries to latest version or 5.4.1 which same as your CLI. I can successfully generate swagger.json after upgrade. Have good luck 😉 
![Screen Shot 2020-05-19 at 1 58 36 PM](https://user-images.githubusercontent.com/12105435/82276285-ef992c00-99d8-11ea-920c-bf165646bbce.png)

**Comment by domaindrivendev** [comment]
Closing in favor of #1699, which captures all of the outstanding compatibility issues. That issue is being addressed as a top priority
