### ISSUE TITLE
When using a Named FromQueryAttribute the generator is not respecting nested classes

### ISSUE THREAD

**Issue by arielmoraes** [domaindrivendev/Swashbuckle.AspNetCore#1658]
Considering the following example:

```csharp
public IActionResult Get([FromQuery] Filter filter)
{
    return Ok();
}

public class Filter
{
    [FromQuery(Name = "sf")]
    [SwaggerParameter("Sub Filter")]
    public SubFilter SubFilter { get; set; }
}

public class SubFilter
{
    [FromQuery(Name = "a")]
    [SwaggerParameter("The Alias to filter")]
    public string Alias { get; set; }
}
```

When calling the Get action we should pass a query string parameter named `sf.a` to set the Alias property, but the generator doesn't seem to navigate correctly through all nested named FromQuery attributes, thus generating a json with a parameter named `a`.

A workaround we found is to inherit the current `AnnotationsParameterFilter` and `SwaggerParameter` by adding a custom Name to it.

.net Core version: 2.2
Swashbuckle version: 5.3.3

**Comment by domaindrivendev** [comment]
This is a dup of #1833
