### ISSUE TITLE
Swashbuckle.AspNetCore.*- Update Microsoft.* references to v3.1.x LTS version so PreEmptive Dotfuscator does not require 2 .NET Core SDKs

### ISSUE THREAD

**Issue by DanielCaspers** [domaindrivendev/Swashbuckle.AspNetCore#1664]
**Request Type**: Update dependencies
**Affected Packages**: 
- Swashbuckle.AspNetCore.Annotations
- Swashbuckle.AspNetCore.Cli
- Swashbuckle.AspNetCore.Newtonsoft
- Swashbuckle.AspNetCore.Swagger
- Swashbuckle.AspNetCore.SwaggerGen
- Swashbuckle.AspNetCore.SwaggerUI

**Affected Package Version**: v5.4.1

**Problem Description**: I am building a .NET Core 3.1 LTS application which is obfuscated using PreEmptive Dotfuscator. When running Dotfuscator on only my assemblies, it was unable to rebuild my application because of the reference within Swashbuckle.AspNetCore.Annotations to .NET Core 3.0. Thus, it failed to obfuscate the app. 

Dotfuscator returned the following error:
```
Couldn't load external type because its assembly can't be found: Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute,Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
 
=== Pre-bind state information ===
C:\Users\<username>\<my-app>\Swashbuckle.AspNetCore.Annotations.dll
LOG: DisplayName = Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```

Using JetBrains dotPeek, I was able to confirm that the issue was in fact related to references to .NET Core 3.0 packages, and has not yet been updated to point at .NET Core 3.1 LTS packages.

![image](https://user-images.githubusercontent.com/6056563/81606362-8f7f0600-9398-11ea-9218-8ef107ecf0b3.png)

**Workaround**: This problem can easily be mitigated by installing both .NET Core 3.0 and .NET Core 3.1 SDKs side-by-side on affected build environments so the necessary references can be resolved.

**Request**: Update the references in Swashbuckle.AspNetCore.* to reference .NET Core 3.1 LTS so that only 1 version of .NET Core SDK is required in CI build environments. 

I realize this is likely a breaking change for .NET Core 3.0 clients, but it would definitely be a help to others building enterprise-grade apps. 

Thank you for your hard work and excellent library :)

**Comment by martincostello** [comment]
Closing due to age - please open a new issue if you still have issues in the latest version.

**Comment by DanielCaspers** [comment]
No longer relevant to me. Thank you!
