### ISSUE TITLE
Custom Swagger Ui or Inject javascript

### ISSUE THREAD

**Issue by bereanu99** [domaindrivendev/Swashbuckle.AspNetCore#1665]
Hello! 
I am trying to inject custom javascript in to swagger UI or a custom html in order to achieve a custom auth based on the clients tenant.
1. Trying to inject c.InjectJavascript("swagger-custom.js"); i get Failed to load resource (my swagger-custom.js is on the same lvl as program.cs
2.trying to inject c.IndexStream = () => GetType().GetTypeInfo().Assembly.GetManifestResourceStream("Namespace.Swagger.swagger-custom.html"); i am getting {"status":500,"errors":[{"Message":"Value cannot be null.

Any posible fixes?

**Comment by domaindrivendev** [comment]
Both of these approaches are supported and work, so you must be missing something.

For injecting custom JS/CSS, take a look at the following sample app:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/v5.4.1/test/WebSites/CustomUIConfig

For injecting a custom index, take a look at:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/v5.4.1/test/WebSites/CustomUIIndex 

If you're using the `IndexStream` approach, make sure you've set the file's "Build Action" to "Embedded Resource"

**Comment by bereanu99** [comment]
Thanks, it works what I am trying to achieve is that customize the auth url based on the tenant name(client) and that applies to modify swagger.json immediately before the swagger is Generated.

**Comment by ellenkuipers** [comment]
> Thanks, it works what I am trying to achieve is that customize the auth url based on the tenant name(client) and that applies to modify swagger.json immediately before the swagger is Generated.

I'm looking for the same. Any ideas?
