### ISSUE TITLE
After upgrade from 5.2.1 to 5.4.1 can't display the text box in the header with the "Explore" button

### ISSUE THREAD

**Issue by vbulcan** [domaindrivendev/Swashbuckle.AspNetCore#1666]
Thanks for contributing to Swashbuckle.AspNetCore! As per the [contributing guidelines](CONTRIBUTING.md), please adhere to the following rules of thumb before submitting your issue:

1. If it's not a bug report, feature request or PR, don't submit it here. Post to Stackoverflow instead.
2. If your issue is specifically a UI concern, don't submit it here. Post to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui).
3. For bug reports, specify the version your using and provide clear repro steps.

**Comment by vbulcan** [comment]
Hello,

while using version 5.2.1 I was able to skip the configuration of the SwaggerEndpoint in UseSwaggerUI method and this way the swagger was displaying a text box with "Explore" button.

After upgrading to 5.4.1 the skipping of the configuration of the SwaggerEndpoint is resulting in blank screen.

Could you please tell me how to visualize the text box in the header with the "Explore" button with the new version.

Thank you !

**Comment by martincostello** [comment]
Closing due to age and on the assumption that the latest version of Swagger UI has resolved this problem.
