### ISSUE TITLE
Dictionary<TEnum, T> can't be used in DTOs even with custom JSON converter

### ISSUE THREAD

**Issue by devdeer-stephan** [domaindrivendev/Swashbuckle.AspNetCore#1667]
# Request Type:
Bug
# Affected Packages:
* Swashbuckle.AspNetCore.SwaggerGen
# Affected Version:
5.4.1
# Problem Description:
I have a controller method that expects a `Dictionary<MyEnum, int>` (I've tried with either that as a parameter as well as a DTO containing the `Dictionary`). `System.Text.Json` [doesn't support that by default](https://github.com/dotnet/runtime/issues/30524), so I built my own JSON converter following [the microsoft docs for that](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to#sample-factory-pattern-converter).
Then I tried both registering the Converter(-Factory) with the `IMvcBuilder` as well as using the annotation in my DTO. Neither allowed me to run SwaggerGen.

[Looking at the code](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs#L48) quickly explained why:
```c#
if (underlyingType.IsDictionary(out Type keyType, out Type valueType))
{
    if (keyType.IsEnum)
        throw new NotSupportedException(
            $"Schema cannot be generated for type {underlyingType} as it's not supported by the System.Text.Json serializer");
```

# Request
Look for available converters that are able to (de-)serialize the dictionary before throwing an exception.

**Comment by domaindrivendev** [comment]
Unfortunately, what you're requesting is not possible for Swashbuckle. There's no problem detecting custom converters for a given type, but without prior knowledge of the converter, there's no way of predicting the shape of the JSON it will produce. The only possible way would be for SB to actually execute the converter and this is not something I'm not willing to pursue - executing application code is too intrusive and introduces a ton of security risks.

**Comment by domaindrivendev** [comment]
For your situation, I recommend hooking into one of the Swashbuckle extensibility points. The  `MapType` setting should get you what you want. For example:

```csharp
services.AddSwaggerGen(c =>
{
    ...

    c.MapType<Dictionary<MyEnum, int>>(() =>
        new OpenApiSchema
        {
            Type = "object",
            Properties = typeof(MyEnum).GetEnumNames().ToDictionary(
                name => name,
                name => new OpenApiSchema { Type = "integer", Format = "int32" })
        });
});
```

**Comment by devdeer-stephan** [comment]
Thank  you, your suggestion worked.
Though I don't really understand the reason for SB not to execute a custom converter. If I as a developer decide to introduce a custom JSON converter I expose my application to the risk anyway, so I am probably sure I want to use that converter. SB not executing that converter seems only inconvenient, as I will probably execute it somewhere else in my code anyway. Are there additional risks that come specifically with SB executing foreign code?
