### ISSUE TITLE
How to remove the Inherited class

### ISSUE THREAD

**Issue by xts-velkumars** [domaindrivendev/Swashbuckle.AspNetCore#1672]
Hi Team, 

I would like to removed Inherited class from my command object. After i updated to latest version its broken

 public class RemoveDefinitionsDocumentFilter : IDocumentFilter
        {
            public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
            {
                swaggerDoc.Definitions.Remove("IResult");
                swaggerDoc.Definitions.Remove("ILoggedOnUserProvider");
                swaggerDoc.Definitions.Remove("Command");
            }
        }

New Version, I cant use SwaggerDocument swaggerDoc,

**Comment by remcolam** [comment]
So the new Apply function signature is: `public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)`
I can see it doesn't contain a definitions member, so you should probably dig into it's structure deeper. I would suggest placing a breakpoint and then inspecting the object in the debugger.

Additionally, I think you want to hide some schemas, the DocumentFilterContext contains the schema repository, which contains a dictionary called Schema's, I think you need to remove them from there.

Seems like it's something you can try, don't know if it will work though

**Comment by domaindrivendev** [comment]
As of `5.0.0`, the object model has changed to reflect Swagger/OpenAPi v3 as opposed to v2. This is described in the "Breaking Changes" of the release notes:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v5.0.0
