### ISSUE TITLE
How do I get my project to generate `deps.json` files on compile?

### ISSUE THREAD

**Issue by ffMathy** [domaindrivendev/Swashbuckle.AspNetCore#1673]
I get the following error:

> The specified deps.json [MyProject/bin/Debug/MyProject.deps.json] does not exist

When running the CLI: 
`dotnet swagger tofile --output ./bin/swagger.json MyProject/bin/Debug/MyProject.dll V1`

Is the CLI still fully functional for later versions of .NET Core? If so, how can I make C# produce the `.deps.json` file for this to work?

**Comment by domaindrivendev** [comment]
I believe the error in this case may be misleading. I think the DLL path you're providing is invalid - it's missing the framework folder. If you update it as follows the following, I believe your issue will be resolved:

```
dotnet swagger tofile --output ./bin/swagger.json MyProject/bin/Debug/($TargetFramework)/MyProject.dll V1
```

Where `$(TargetFramework)` is the framework your app is targetting (e.g. `netcoreapp2.1`, `netcoreapp3.1` etc.).

The Swashbuckle code currently looks for the corresponding `.deps.json` first, hence why your seeing the error. I'll make an update to provide a better error message in this case.

**Comment by ffMathy** [comment]
No, in my case, that is the actual build folder. If the file is not found, I get another error.

If I actually go to the folder that has my binaries (which is the one provided), there is no `.deps` file at all next to them.

**Comment by domaindrivendev** [comment]
Then I'm at a loss. If your build isn't outputting to a framework-specific folder then you have something non-standard in your setup. As far as I'm aware, the deps.json file is 100% required for dotnet and I don't know of any use-cases where it wouldn't be emitted from a build.

If you create a minimal application (i.e. start from a blank project) that repro's your issue and post it to github, then I'll pull down and take a look. Otherwise, there's not much else I can do without a repro.

**Comment by jpl2nd** [comment]
I'm having the same issue: 

 swagger tofile --output ".\publish\swagger.json" "\bin\Debug\net6.0\SampleAPI.dll" "v1"
 
 The specified deps.json [\bin\Debug\net6.0\SampleAPI.deps.json] does not exist

**Comment by StingyJack** [comment]
@domaindrivendev would someone running this tool on an asp.net framework 4.x web api project get this deps.json error?

**Comment by martincostello** [comment]
I wouldn't have thought so, that's a .NET (Core) thing.

**Comment by StingyJack** [comment]
I get the same error when running the tool against a netfx project.
