### ISSUE TITLE
Swagger is not working when adding Odata as part of the parameters of an ActionMethod

### ISSUE THREAD

**Issue by zinov** [domaindrivendev/Swashbuckle.AspNetCore#1675]
I have a problem with swagger documentation when I have ODataQueryOptions(I am using Non-edm approach to implement odata options, dotnet core 3.1, Swashbuckle.Aspnetcore 5.3.3, Microsoft.Aspnetcore.odata 7.4.0). 
When I click the method that has OdataQueryOptions as a parameter, the swagger UI page got stuck and crash. If I remove the OdataQueryOptions the swagger UI is working as expected. Here is some code example repo
[ExampleApi in Github](https://github.com/ocean8028/ExampleApi)

**Comment by NetTecture** [comment]
May I ask how you get Swagger working at all? I have no methods showing up at all and it seems that when using endpoint routing the api explorer is not exposing the routes (yet).

**Comment by zinov** [comment]
yes, please lunch the application and you will see the swagger up and running, by default the page opens the swagger. Please see as well on the Startup the  services.AddSwaggerGen on the ConfigureServices and on the Configure how we use  app.UseSwagger and app.UseSwaggerUI. 
Now if you go to the Controllers and you uncomment the OdataQueryOptions parameter on this method the SwaggerUI doesn't work.

 `public IActionResult Get(ODataQueryOptions<WeatherForecast> options)`

Below is a screenshot of what is happening, the page keeps loading forever.
![1](https://user-images.githubusercontent.com/1099892/83099256-d8160f00-a07a-11ea-9ffe-bd194e53679e.png)

**Comment by domaindrivendev** [comment]
Swashbuckle is built on top of `ApiExplorer`, the API metadata provider that's part of ASP.NET Core. That component does not currently support OData controllers and therefore neither does Swashbuckle.

This lack of support is being tracked in the following issue, including a workaround from the `Microsoft.AspNetCore.Mvc.Versioning` library:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/581#issuecomment-759435536
