### ISSUE TITLE
Package 5.4.1 is not completely compatible with swagger doc 2.0

### ISSUE THREAD

**Issue by CodeWithCare** [domaindrivendev/Swashbuckle.AspNetCore#1679]
We are using SwashBuckle 5.0 and trying to produce a `swagger doc 2.0`. And apparently it does produce swagger.json which is not 100% compliant with swagger 2.0 specs. The problem is specifically around how it does enlists the enums:

    name: prop-name
    description: something
    type: array
    items:
        $ref: '#/definitions/mytype'

where it should had been :

    name: prop-name
    description: something
    type: array
    items:
      type: string
      enum:
        - Item1

For it to be 100% swagger 2.0 spec.So jus tto summarize, SwashBuckle has produced a swagger.json for us which is not 100% swagger 2.0 complaint. We are enforcing our configuration to use V2 by spefically saying `SerializeAsV2 = true` 

We also considered upgrading to OAS 3.0 and decided against to for now since all of the clients have to change and it is a big effort. So we are back to trying to figure out how can have have SwashBuckle produce a swagger.json that is 100% swagger 2.0 complaint? I just want to see if there is not a configuration that we need to change before I file a bug against SwashBuckle team.

Any suggestions?

**Comment by domaindrivendev** [comment]
Swagger 2.0 supports both inline AND referenced schema definitions. So, it’s not clear to me how the first example is non-compliant. Could you please be more specific, referring to the spec if possible, about why your first example is invalid?

With all that said, if you want to force inline definitions for enums you can force this behavior with a setting. Can’t remember exact name but it’s something like “UseInlineDefinitionsForEnums”

**Comment by CodeWithCare** [comment]
Thank you for your answer @domaindrivendev. The suggested option `c.UseInlineDefinitionsForEnums();`  does switch to inline descriptions. Now, back to your original question `How do I think the first example is non-compliant`

Two points:

1. Swagger editor throws error when I try to load the doc with $ref to describe enums the errors look like below:

<img width="935" alt="Screen Shot 2020-05-25 at 12 24 09 PM" src="https://user-images.githubusercontent.com/31261551/82839004-d41f9c80-9e82-11ea-88d0-c2f97c16921d.png">


2. We are using `swagger-gen` That creates the client code for our Go client and that one also throws the same error when trying to generate the client code. Now, if there is a flag that we can pass when trying to generate the client, hence, stopping us from generating the client for this swagger.json.

**Comment by CodeWithCare** [comment]
I am closing it because your comments were very helpful and we do not have the issue anymore.
