### ISSUE TITLE
XML Comments with nuget packages

### ISSUE THREAD

**Issue by JuanZamudioGBM** [domaindrivendev/Swashbuckle.AspNetCore#1680]
Hi, I'm using VS 16.6.0 with asp.net core 3.1 and Swashbuckle.AspNetCore.Swagger 5.4.1 (SwaggerGen and SwaggerUI also in 5.4.1)

I added the steps to include the xml comments in the documentation, I also have some generic models  in a nuget package, I modified the csproj of the API so the xml from the package is copied to the output directory during build and publish.

In the browser I xcan see examples of the models included in the solution, but the models in the nuget package have the default values, like this:

```
{
  "error": {
    "code": "string",
    "details": [
      null
    ],
    "event_id": 0,
    "inner_error": {
      "code": "string"
    },
    "message": "string",
    "target": "string"
  }
}
```
In the schema definition I can see my comments from the xml file so the file is being loaded by Swashbuckle, is there a way to add examples to this generic models in a package?

Also is there a setting so the examples are added to the swagger.json file? I can only see the examples in the UI.

Thanks a lot.

**Comment by korifeich** [comment]
@JuanZamudioGBM HI,

Have you added path to file with xml comments from NuGet package you are using, according to point 5 in documentation:

### Include Descriptions from XML Comments ###

```
c.IncludeXmlComments(filePath);
```
_NOTE: *. you can invoke the IncludeXmlComments method multiple times and they will all be merged into the outputted Swagger JSON._

**Comment by snowchenlei** [comment]
@korifeich project references a third-party nuget, how is it configured? 
I don't have xml file. But nuget contains documentation.

**Comment by korifeich** [comment]
@snowchenlei Can you send me nuget package name?

Usually you need to do the following:
- Check if xml file is included in NuGet package itself
- Check if this xml file is copied to your output folder (build or publish)
- Add this xml file following the swashbuckle documentation

**Comment by snowchenlei** [comment]
@korifeich My nuget.It has not been published to the public network.
installing nuget can import the xml file?
`my nuget` project properties setting: 

- build -> output -> xml document file(checked)

- build -> output -> generate serialization assembly(auto)

- xml file copy to output(yes)
now,I installed my nuget in `demo` project. but `my nuget` xml file was not found in `demo` project .
