### ISSUE TITLE
Error running `dotnet swagger` if the input dll was compiled as x86

### ISSUE THREAD

**Issue by phil-allen-msft** [domaindrivendev/Swashbuckle.AspNetCore#1682]
1. Boot Visual Studio 2019
2. File -&gt; New -&gt; Project -&gt; Asp.NET Core WebApplication
3. Choose .NET Core 3.1 and the API template
4. Click Create
5. Get to a command prompt with the context of the created solution. "Menu Bar -&gt; Tools -&gt; Nuget Package Manager -&gt; Package Manager Console" is one such way
6. `Install-Package Swashbuckle.AspNetCore`
7. `dotnet new tool-manifest`
8. `dotnet tool install swashbuckle.aspnetcore`
8a. Version 5.4.1 is installed

9. Add the following code to Startup.cs:
            services.AddSwaggerGen(config =&gt;
            {
                config.SwaggerDoc("v1",
                new OpenApiInfo
                {
                    Title = "MyApi",
                    Version = "v1"
                });
            });
10. `dotnet build "<Path to project root>"`
11. `dotnet swagger tofile --serializeasv2 "<PathToBinary>" v1`

SUCCEEDS

12. Add the following to a property group in the csproj:
    &lt;PlatformTarget&gt;x86&lt;/PlatformTarget&gt;

13. `dotnet build "<Path to project root>"`
14. `dotnet swagger tofile --serializeasv2 "<PathToBinary>" v1`

RESULT:
dotnet : Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'WebApplication66, Version=1.0.0.0, 
Culture=neutral, PublicKeyToken=null'.
At line:1 char:1
dotnet swagger tofile --serializeasv2 "&lt;PathOnLocalMachine&gt; ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : NotSpecified: (Unhandled excep...KeyToken=null'.:String) [], RemoteException
    FullyQualifiedErrorId : NativeCommandError
 
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, 
ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Swashbuckle.AspNetCore.Cli.Program.&lt;&gt;c.&lt;Main&gt;b__0_3(IDictionary`2 namedArgs) in 
C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 69
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in 
C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in 
C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 108
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

EXPECT:
The same generated output as in step 11.

NOTE:
If instead of using TargetPlatform, one uses the RuntimeIdentifier
&lt;RuntimeIdentifier&gt;win-x86&lt;/RuntimeIdentifier&gt;
it all works.

**Comment by domaindrivendev** [comment]
Closing in favor of #1699, which captures all of the outstanding compatibility issues. That issue is being addressed as a top priority
