### ISSUE TITLE
Missing operationId in V2

### ISSUE THREAD

**Issue by mcm-ham** [domaindrivendev/Swashbuckle.AspNetCore#1684]
I just upgraded from 4.0.1 (was working) to 5.3.1 (seeing error). I'm using the CLI with the following command:
> dotnet swagger tofile --serializeasv2 --output restapi/v1/identity.json restapi/out/WebApi.dll identity

I'm using docfx to generate a website from swagger json: https://dotnet.github.io/docfx/tutorial/intro_rest_api_documentation.html

But seeing now seeing this error in docfx:
> {"message":"Unable to load file 'restapi/v1/identity.json' via processor 'RestApiDocumentProcessor': operationId should exist in operation 'post' of path '/api/identity/orders/validate' for swagger file 'restapi/v1/identity.json'","source":"BuildCommand.BuildCore.Build Document.Load.RestApiDocumentProcessor","file":"restapi/v1/identity.json","date_time":"2020-05-28T03:05:34.795557Z","message_severity":"error","code":"InvalidInputFile","correlation_id":"7D610FEE-375A-41B2-A3AC-57FDB33C2824.1.182.1.76.5.4"}

Is this due to an issue with https://github.com/microsoft/OpenAPI.NET and should file bug there?

**Comment by iamwyza** [comment]
I got bit by this today as well and literally came here to report the same issue.  The way I understand it, the v2 rendering is actually v3, reverse rendered to v2.  So I'm wondering if operationid is getting dropped in the v3 or something.

**Comment by iamwyza** [comment]
Actually, I just followed these directions and it fixed it for me: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcoreswaggergen

**Comment by mcm-ham** [comment]
Thanks iamwyza for the pointer, fixed it for me too.
