### ISSUE TITLE
Support for Nullable Reference Types

### ISSUE THREAD

**Issue by Compusa** [domaindrivendev/Swashbuckle.AspNetCore#1686]
Are there any plans to add support for Nullable Reference Types? It would be nice, and with NRT we would no longer need to annotate required properties with the `[Required]` attribute.

**Comment by alesdvorakcz** [comment]
I am also looking for a way how to set all non-nullable properties in schemas required by default. Is there any other way except manually adding Required attribute everywhere?

**Comment by esbenbach** [comment]
Creating a pull request ;)

**Comment by FelschR** [comment]
@alesdvorakcz 
I agree, it would be nice if Swashbuckle behaves the same as the ASP.NET Core validation system:

> The validation system in .NET Core 3.0 and later treats non-nullable parameters or bound properties as if they had a [Required] attribute.

— https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#required-attribute

**Comment by Lonli-Lokli** [comment]
Waiting for the same. With Nullable feature enabled it's still required to add Required attribute.

**Comment by esbenbach** [comment]
@domaindrivendev I would be willing to give it a try if you think you would accept a PR for it.
Presumably there would be a need to "opt-out" like there is with the validation in aspnetcore.

Also, i expect the Nullable type detection would more or less be equivalent to what is done in the asp.net core repo:
https://github.com/dotnet/aspnetcore/blob/0517745c08d1bc85009f1ca41a41d77176eeea60/src/Mvc/Mvc.DataAnnotations/src/DataAnnotationsMetadataProvider.cs#L357

Which is not exactly pretty - but I doubt I can come up with something better.
Would that approach be acceptable?

**Comment by domaindrivendev** [comment]
@esbenbach - sounds reasonable. I'll keep an eye out for your PR and will try my best to provide prompt feedback

**Comment by eluchsinger** [comment]
Any news here?

**Comment by esbenbach** [comment]
Unfortunately no - due to Covid19, lots of stuff has prevented me from looking into this, and the timeframe is pretty grim. Someone else should feel free to give it a try :)

**Comment by coder925** [comment]
> ... with NRT we would no longer need to annotate required properties with the [Required] attribute

@Compusa , were you able to remove `[Required]` attributes from your properties?

When I add `setupAction.SupportNonNullableReferenceTypes();` it correctly removes `"nullable": true` from the swagger property, but it is still not listed as **_required_**.

Do you still need to mark all properties with `[Required]`? Is there another feature request issue to also make them required by default?

**Comment by JoelHutters** [comment]
> > ... with NRT we would no longer need to annotate required properties with the [Required] attribute
> 
> 
> 
> @Compusa , were you able to remove `[Required]` attributes from your properties?
> 
> 
> 
> When I add `setupAction.SupportNonNullableReferenceTypes();` it correctly removes `"nullable": true` from the swagger property, but it is still not listed as **_required_**.
> 
> 
> 
> Do you still need to mark all properties with `[Required]`? Is there another feature request issue to also make them required by default?

I haven't been able to this yet unfortunately.

**Comment by hannahchan** [comment]
I just tested this out and it looks like my fields are correctly marked as nullable or not nullable. Non-nullable fields are not marked as required unless I annotate with `[Required]`.

I currently believe this should be the correct behaviour as `nullable` and `required` in the JSON schema standard are two different things. The first is basically a promise that says that if a key is present in a JSON document, the value will or will not be null. The second one is basically a promise that it will be in the JSON document.

**Comment by coder925** [comment]
@hannahchan , thank you for verifying that this issue only affects `nullable`.

I have posted a new issue https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2036 regarding optionally treating all non-nullable types as `required`.

**Comment by Lonli-Lokli** [comment]
I have  `<Nullable>enable</Nullable>` and contract defined as `public record DocumentContract(string Author, string Id);`, so was expecting to get either required or nullabl: false, but schema look like this
```
"DocumentContract": {
        "type": "object",
        "properties": {
          "author": {
            "type": "string",
            "nullable": true
          },
          "id": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
```

Has this been reported?

**Comment by Lazzaretti** [comment]
> I have `<Nullable>enable</Nullable>` and contract defined as `public record DocumentContract(string Author, string Id);`, so was expecting to get either required or nullabl: false, but schema look like this
> 
> ```
> "DocumentContract": {
>         "type": "object",
>         "properties": {
>           "author": {
>             "type": "string",
>             "nullable": true
>           },
>           "id": {
>             "type": "string",
>             "nullable": true
>           }
>         },
>         "additionalProperties": false
>       },
> ```
> 
> Has this been reported?

@Lonli-Lokli you also need to set `SupportNonNullableReferenceTypes()`. With that change I get `nullable: false`

**Comment by MatteoSp** [comment]
> @Lonli-Lokli you also need to set `SupportNonNullableReferenceTypes()`. With that change I get `nullable: false`

I would suggest to enable that by default (when nullable ref. types are enabled) on the next major version.
