### ISSUE TITLE
Namespace reverses the order of doc

### ISSUE THREAD

**Issue by tytannial** [domaindrivendev/Swashbuckle.AspNetCore#1692]
The different namespaces are reversing order, but controllers in every namespace order is correct. How to make all apis sorted by alphabet.
![QQ截图20200603105119](https://user-images.githubusercontent.com/11215623/83590722-f901c700-a588-11ea-9ede-ccdab0a2b80f.png)

**Comment by domaindrivendev** [comment]
Out-of-the-box, the APIs should be sorted by controller name, independent of namespaces. I was able to create a setup similar to what you've shown and confirmed this is the case. So, I can't repro your issue.

Swashbuckle does expose settings to customize this behavior - is it possible you're using these? Could you post your Swagger config from your `Startup.cs`?

**Comment by tytannial** [comment]
https://github.com/zhontai/Admin.Core/blob/master/Admin.Core/Startup.cs
:)

**Comment by martincostello** [comment]
Closing due to age and the link now 404ing.
