### ISSUE TITLE
Expanding an operation expands all operations in  the same controller

### ISSUE THREAD

**Issue by rcollette** [domaindrivendev/Swashbuckle.AspNetCore#1695]
This is a UI issue that is not duplicated at the Swagger UI live demo site.

I have a controller with multiple methods.
When I expand one of the method in the controller, all methods in that controller expand.

**Comment by domaindrivendev** [comment]
I recall this being a bug in older versions of the [swagger-ui](https://github.com/swagger-api/swagger-ui) that was fixed a while back. Which version of Swashbuckle are you using - is it possible it's an old one that contains the errant version of the swagger-ui?

**Comment by rcollette** [comment]
I'm using swashbuckle 5.4.1

**Comment by domaindrivendev** [comment]
I don't have a repro with that verison. Could you please put together a minimal app (i.e. start from a blank project) that repro's your issue, and post it to github? That way, I can pull it down and will have a repro to work with.

**Comment by rcollette** [comment]
We use a dotnet template for generating new micro services that includes Swashbuckle. This is a project generated from that template.

https://github.com/rcollette/swashbuckle-issue-example

**Comment by domaindrivendev** [comment]
This is not a minimal repro - it has a ton of additional config, and it's hanging for me on startup. So, not very helpful I'm afraid. Could you possibly take the time to craft a "minimal" repro that will run anywhere?

**Comment by domaindrivendev** [comment]
Just noticed the following Swashbuckle customization in your `Startup.cs` that is likely the culprit:

```csharp
                    c.CustomOperationIds(
                        apiDesc =>
                            apiDesc.TryGetMethodInfo(out MethodInfo methodInfo)
                                ? methodInfo.Name
                                : null);
```

As per the Swagger / OpenAPI spec., `operationId` MUST be unique but the will result in duplicated values for actions that have the same name. This ID duplication is likely causing the UI behavior you're observing.

As noted in the Swashbuckle readme, if you're using the above customization, then you need to ensure that the provided naming strategy results in unique OperationIds.

> NOTE: With either approach, API authors are responsible for ensuring the uniqueness of operationIds across all Operations

**Comment by rcollette** [comment]
Ah.  Sorry I didn't catch that.  I've been using this for so long now that note may not have been there at the time I implemented it, or perhaps I picked up the code from a different source.

```
add operation id GetInfo
add operation id Log
add operation id Get
add operation id Post
add operation id Get
add operation id Put
add operation id Delete
```

I don't even recall why I added it in the first place unless it was necessary to make the xml documentation work.

This 

```
c.CustomOperationIds(
  apiDesc => apiDesc.TryGetMethodInfo(out MethodInfo methodInfo)
  ? methodInfo.DeclaringType + "." + methodInfo.Name + "(" +
  string.Join(",", methodInfo.GetParameters().Select(p => p.ParameterType)) + ")"
  : null);
```
Fixes the problem but starts to make me wonder about the fact that code structure is getting exposed potentially to the outside world.

```
add operation id The.Solution.Name.Web.Controllers.InfoController.GetInfo()
add operation id The.Solution.Name.Web.Controllers.LoggingTestController.Log()
add operation id The.Solution.Name.Web.Controllers.ValuesController.Get()
add operation id The.Solution.Name.Web.Controllers.ValuesController.Post(The.Solution.Name.Repository.ValueModel)
add operation id The.Solution.Name.Web.Controllers.ValuesController.Get(System.Int32)
add operation id The.Solution.Name.Web.Controllers.ValuesController.Put(System.Int32,The.Solution.Name.Repository.ValueModel)
add operation id The.Solution.Name.Web.Controllers.ValuesController.Delete(System.Int32)

```

Closing the issue since it is not a bug and thank you for the assistance.

**Comment by domaindrivendev** [comment]
If you omit the call to “CustomOperationIds” then the generated doc won’t contain any operationId values at all, which is perfectly valid from a spec perspective. Furthermore the UI will handle that just fine.

If you don’t have a good reason to include them (e.g. client generators), you may be better off just doing that.
