### ISSUE TITLE
Typescript generator ignoring generateDefaultValues

### ISSUE THREAD

**Issue by paul-cf** [domaindrivendev/Swashbuckle.AspNetCore#1697]
Hi, updated to 5.4.1 (from 4.0.1) and now when generating typescript the DTOs are being 'new'd in init when previously they were '<any>undefined'?

PREV....
 ```
   init(data?: any) {
        if (data) {
            this.user = data["user"] ? UserLoginInfoDto.fromJS(data["user"]) : <any>undefined;
        }
    }
```

NOW....
  ```
  init(data?: any) {
        if (data) {
            this.user = data["user"] ? UserLoginInfoDto.fromJS(data["user"]) : new UserLoginInfoDto();
        }
    }
```
....

 And relevant part of service.config.nswag file:

```
{
  "runtime": "Default",
  "swaggerGenerator": {
    "fromSwagger": {
      "url": "http://localhost:22742/swagger/v1/swagger.json",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}ServiceProxy",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 3.9,
      "template": "Angular",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "useSingletonProvider": false,
      "injectionTokenType": "InjectionToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "MomentJS",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "wrapDtoExceptions": false,
      "wrapResponses": false,
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromPathSegments",
      "markOptionalProperties": false,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "extensionCode": "service.extensions.ts",
      "generateDefaultValues": false,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "output": "../src/app/shared/service-proxies/service-proxies.ts"
    },


```

**Comment by domaindrivendev** [comment]
As mentioned in the [5.0.0 release notes](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v5.0.0) the major version increment introduces Swagger / OpenAPI v3 as the default JSON format generated by Swashbuckle. The new structure is significantly different to the v2 format and may be impacting downstream tools like NSwag (which is completely independent of Swashbuckle).

If you want Swashbucke to continue emitting the v2 Swagger / OpenAPI format, you can apply the `SerializeAsV2` setting when configuring the Swagger middleware (see `UseSwagger(...)`).

With that said, support for this option is limited at this point. Ideally, you would stick with the newer format and try to figure out specifically what part of it is NSwag having trouble with. Unfortunateley though, this isn't something I can help with as NSwag is a completely separate project.

**Comment by paul-cf** [comment]
Thanks for response.

Tbh, new to this side of the project and wasn't aware of all the moving parts - turns out i also had to update the nswag package in the angular app.
