### ISSUE TITLE
Multipul file Upload is not working on Asp.net core with openApi new release!!

### ISSUE THREAD

**Issue by sumankumarsahu** [domaindrivendev/Swashbuckle.AspNetCore#1704]
I am sharing some code.

[HttpPost("fileUploads")]
        public IActionResult Index([FromForm] FileUploadRequest fileUploadRequest)
        {
            var outPut = _fileUploader.ExtractFilesAndScan(fileUploadRequest);
            return Ok(new
            {
                outPut.FilesUploaded,
                outPut.FilesScanned,
                ScanResult = outPut.ScanResult.ToString(),
                outPut.Messages
            });
        }

public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            if (operation.Tags.All(p => p.Name != "FileUploads")) return;

            var fileParameter = operation.Parameters.FirstOrDefault(x => x.Name == "file");
            if (fileParameter != null)
                operation.Parameters.Remove(fileParameter);

            var uploadFileMediaType = new OpenApiMediaType()
            {
                Schema = new OpenApiSchema()
                {
                    Type = "object",
                    Properties =
                    {
                        ["Files"] = new OpenApiSchema()
                        {
                            Description = "Upload File",
                            Type = "file",
                            Format = "formData",
                            MultipleOf = 10
                        }
                    },
                    Required = new HashSet<string>() { "Files" }
                }
            };

            operation.RequestBody = new OpenApiRequestBody
            {
                Content = { ["multipart/form-data"] = uploadFileMediaType }
            };
        }

still Gettingf Issue not able to find any value in controller request.

**Comment by domaindrivendev** [comment]
In the latest version, file uploads are supported out-of-the-box - no need for an operation filter:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#handle-forms-and-file-uploads
