### ISSUE TITLE
Endpoint routing: return `IEndpointConventionBuilder` instead of `IEndpointRouteBuilder`

### ISSUE THREAD

**Issue by eric-b** [domaindrivendev/Swashbuckle.AspNetCore#1705]
I have 2 remarks/questions regarding recently added method `MapSwagger()`: 

1. `MapSwagger()` should return `IEndpointConventionBuilder`

2. `MapSwagger()` could be simplified and more consistent with *UseSwagger()*.

Current usage is like this:

    public void Configure(IApplicationBuilder app)
    {
        // [...]
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
            endpoints.MapSwagger("swagger/{documentName}/swagger.json");
        });
    }   

Because `MapSwagger()` returns `IEndpointRouteBuilder`, this limits some conventions, for example, we currently cannot do this:

            endpoints
                .MapSwagger("swagger/{documentName}/swagger.json")
                .RequireAuthorization();

To make this possible, [MapSwagger](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8fdcfd95c32181c8515735475ff3b80dad1f70d5/src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerBuilderExtensions.cs#L42) should return `IEndpointConventionBuilder`:

        public static IEndpointConventionBuilder MapSwagger(
            this IEndpointRouteBuilder endpoints,
            string pattern = "/swagger/{documentName}/swagger.json",
            Action<SwaggerEndpointOptions> setupAction = null)
        {
            // [...]
            return endpoints.MapGet(pattern, pipeline);
        }

I can make a PR but I'm not sure of naming of new method (because it would be a breaking change with current method). 

---

Regarding my second point, it's about consistency:

*MapSwagger()* internally calls [UseSwagger()](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8fdcfd95c32181c8515735475ff3b80dad1f70d5/src/Swashbuckle.AspNetCore.Swagger/DependencyInjection/SwaggerBuilderExtensions.cs#L23).

*UseSwagger()* allows two ways for configuring `SwaggerOptions`: either from conventional options configuration with `IServiceProvider`, either with a lambda action passed as argument.

But current implementation of `MapSwagger` always passes a lambda action argument with default values. Unless I missed something, previously configured `SwaggerOptions` in DI will not be used if we call *MapSwagger()*. I find options in DI way more powerful because we can access its values from any other DI method (when configuring other components). On the contrary, values set on endpoint mapping are not accessible from *ConfigureServices()* stage.

**Comment by alrz** [comment]
>  we currently cannot do this:
> ```cs
>        endpoints
>             .MapSwagger("swagger/{documentName}/swagger.json")
>             .RequireAuthorization();
> ```

I just hit this. I think that was the whole point of endpoint routing?

**Comment by APIWT** [comment]
I am going to link this here just in case it helps someone else: https://github.com/dotnet/aspnetcore/issues/24252

**Comment by herecydev** [comment]
Is this going anywhere? Do you want a PR to fix this?

**Comment by ylabade** [comment]
Any news about this issue ?
