### ISSUE TITLE
Wrap thrown system exceptions to provide useful information

### ISSUE THREAD

**Issue by JonasZ95** [domaindrivendev/Swashbuckle.AspNetCore#1711]
Version: Swashbuckle.AspNetCore Version="5.4.1"

The bug(for me It's a bug) I'm talking about is that when GenSwagger is called and an exception is thrown while the core library is trying to do some reflection you get exceptions like: 
` System.Reflection.AmbiguousMatchException: Ambiguous match found.` with zero information which controller or operation caused this exception.

The problem is that It's quite hard to actually break when the exception is thrown and getting any information why It happens. So I would propose we wrap any exception which happens during GetSwagger to actually contain information in which controller and which operation the exception happened. I could also create a pull request implementing this but I'm not sure what kind of information the wrapped exception should contain.

**Comment by domaindrivendev** [comment]
Seems reasonable. Adding the related `ApiDescription`, which identifies the controller and action , among other things, would be a good start. With this in mind, I think the method `SwaggerGenerator.GenerateOperation` would be the appropriate place to put the try/catch/wrap/rethrow logic. Happy to accept a PR for this.

**Comment by domaindrivendev** [comment]
See 61b2fb28928ca211c9655fc212f086ee788f00c9
