### ISSUE TITLE
swashbuckle.Aspnetcore cli not able to recognize private nuget feed reference and failed to resolve, not generating swagger.json file

### ISSUE THREAD

**Issue by SSanjeevi** [domaindrivendev/Swashbuckle.AspNetCore#1715]
### swashbuckle.Aspnetcore cli not able to recognize private nuget feed reference and failed to resolve, not generating swagger.json file

**CLI Command:**

`dotnet swagger _tofile projfolder\bin\Debug\netcoreapp3.1\myassembly.dll "v1 1.0.xml"`

**Following error occurs on above command:**
```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'mycommon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

The mycommon assembly is referred using _private feed_ **Nuget**.
Also placed the _Nuget.config_ file in the project folder.

Is there any way to pass Nuget.config file to this tool?

Version used command for info on version:
`dotnet tool install --version 5.5.0 Swashbuckle.AspNetCore.Cli`

**Comment by talksinmath** [comment]
+1 , can't use it as of now because of the private feed issue

**Comment by BlackRider97** [comment]
+1

**Comment by talksinmath** [comment]
Any news on this?

**Comment by domaindrivendev** [comment]
I'm not familiar with this scenario and so could do with some help troubleshooting. Would someone on this thread be willing to dig a bit deeper with their own investigation?

**Comment by talksinmath** [comment]
Yes, I'd be happy to help.

A short description: I have a project with two nuget feeds, one of them is a private one which hold company internal artifacts. The private feed also needs authentication.

When running the cli tool, I get the error described above.

**Comment by AjaySewradj** [comment]
I had the same issue with my private NuGet feed. The following command fixed it for me:

```
dotnet tool restore --ignore-failed-sources
```

Just make sure that there is one package source that does work (the regular NuGet.org feed for example)

**Comment by martincostello** [comment]
I'm not sure how this can be a Swashbuckle issue as it runs your code, which you own the build for, so your binaries should be in your build output.
