### ISSUE TITLE
Disable Validator

### ISSUE THREAD

**Issue by Padagi** [domaindrivendev/Swashbuckle.AspNetCore#172]
Is there currently any way to disable the "Error {...}" validation indicator when the API is not visible to the public internet (e.g. is an internal API)?

![image](https://cloud.githubusercontent.com/assets/17285914/18356699/ab529116-75a2-11e6-9623-791017c3e38a.png)

Error message is "{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://[internalurladdress]/swagger/v1/swagger.json"}]}" as expected because the validator at online.swagger.io cannot reach the internal address.

Previous version of Swashbuckle offered configuration to change or disable the validator as shown below, however I do not see options for configuration in the .Net Core packaged version:

```
httpConfiguration
    .EnableSwagger(c => c.SingleApiVersion("v1", "A title for your API"))
    .EnableSwaggerUi(c =>
        {
            c.InjectStylesheet(containingAssembly, "Swashbuckle.Dummy.SwaggerExtensions.testStyles1.css");
            c.InjectJavaScript(containingAssembly, "Swashbuckle.Dummy.SwaggerExtensions.testScript1.js");
            c.BooleanValues(new[] { "0", "1" });
            **_c.SetValidatorUrl("http://localhost/validator");
            c.DisableValidator();_**
            c.DocExpansion(DocExpansion.List);
            c.SupportedSubmitMethods("GET", "HEAD")
        });
```

I'm using "Swashbuckle": "6.0.0-beta902" .

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"

**Comment by freeranger** [comment]
@domaindrivendev I'm looking for the "DisableValidator" method and I can't find it - it seems not to have made the transition from Swashbuckle 6 to AspNetCore 1.x.....

**Comment by daniel-cohen** [comment]
For anyone else looking for a specific answer, setting "ValidatorUrl" to null seems to disable to validator in 
```
app.UseSwaggerUI3(c =>
            {
                // Core
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "V1");
                c.ValidatorUrl(null);
            });
```
