### ISSUE TITLE
Inconsistent title generation between runtime and CLI

### ISSUE THREAD

**Issue by bradygaster** [domaindrivendev/Swashbuckle.AspNetCore#1721]
Thanks for contributing to Swashbuckle.AspNetCore! As per the [contributing guidelines](CONTRIBUTING.md), please adhere to the following rules of thumb before submitting your issue:

When I use the most-basic code [thanks again!] like this to generate my Swagger, without any parameters: 

```
public void ConfigureServices(IServiceCollection services)
{
     services.AddControllers();
     services.AddSwaggerGen();
}
```

There's a variance between how `Swashbuckle.AspNetCore` and `Swashbuckle.AspNetCore.Cli` outputs the API's `title` per my expectations, with the name of the app. 

```
title: "WhoAmI"
```

When I use the CLI, however, the `title` is emitted as the full assembly name. 

```
"title": "WhoAmI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
```

When this OAS is ingested into many API Management products, the special characters cause some issues, such as downstream export into Power Platform from Azure API Management (adding @miaojiang for visibility). Ideally, the CLI would just omit `WhoAmI` in the above example, just like the runtime generation works.

**Comment by domaindrivendev** [comment]
Simple enough fix - will push out hotfix relese in the morning

**Comment by bradygaster** [comment]
That’s fantastic. Thanks mate.

**Comment by bradygaster** [comment]
thanks again @domaindrivendev - works like a champ. we should sync up soon and talk about progress and next steps.
