### ISSUE TITLE
Hiding Input Parameters or Optional Route Parameters

### ISSUE THREAD

**Issue by ardalis** [domaindrivendev/Swashbuckle.AspNetCore#1723]
I've reviewed StackOverflow and spent several hours on this already trying a number of approaches, none of which have ultimately worked.

I have a pretty simple setup:
1. I have a BaseRequest class that includes a CorrelationId which is set to a Guid. This is passed throughout the request (and response) so that logs etc. can all be attributed to this request. The class looks like this:

```csharp
    public abstract class BaseRequest
    {
        /// <summary>
        /// Unique Identifier used by logging
        /// </summary>
        [IgnoreDataMember]
        [System.Text.Json.Serialization.JsonIgnore]
        public Guid CorrelationId { get; }

        public BaseRequest()
        {
            CorrelationId = Guid.NewGuid();
        }
    }
```

I have a Delete endpoint which looks like this:
```csharp
        [HttpDelete("api/catalog-items/{CatalogItemId}")]
        [SwaggerOperation(
            Summary = "Deletes a Catalog Item",
            Description = "Deletes a Catalog Item",
            OperationId = "catalog-items.Delete",
            Tags = new[] { "CatalogItemEndpoints" })
        ]
        public override async Task<ActionResult<DeleteCatalogItemResponse>> HandleAsync([FromRoute]DeleteCatalogItemRequest request)
        {
        }
```

And the DeleteCatalogItemRequest:

```csharp
public class DeleteCatalogItemRequest : BaseRequest 
{
    public int CatalogItemId { get; set; }
}
```

What I want is for this this to be true:
1. CatalogItemId is required on the route
2. No body is expected on the request

Any of these could also be true:
1. CorrelationId is completely ignored.
2. CorrelationId is optionally added to the querystring
3. CorrelationId is optionally added to the route

What I am seeing:

With the code above, the [FromRoute] attribute on action method's request argument is generating this:
```json
"parameters": [
          {
            "name": "CatalogItemId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "CorrelationId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
```

Note that it's requiring CorrelationId despite every attempt I've made to exclude it.

If I discard the [FromRoute] attribute, I get this instead - it wants the whole DeleteCatalogItemRequest object as the body:

```json
"parameters": [
          {
            "name": "CatalogItemId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteCatalogItemRequest"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteCatalogItemRequest"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/DeleteCatalogItemRequest"
              }
            }
          }
        },
```

I can just add `[FromRoute]` to the `CatalogItemId` property of the request but that does nothing different.

Any ideas appreciated. I'd like to keep the CorrelationId on the request because it's very helpful for diagnosing issues, especially across multiple services in a microservices environment. I can add it somewhere else using a filter or something but it's most convenient on the BaseRequest and BaseResponse types we're using currently. I don't want my DELETE endpoints to expect request bodies, though, so I just need a way to have a single route/path parameter mapped to a request object that may have additional properties (which might come FromQuery or not at all).

**Comment by domaindrivendev** [comment]
> CorrelationId is optionally added to the querystring
> CorrelationId is optionally added to the route

Forget about Swashbuckle, your API itself won't actually support this behavior with the setup you've described. When you decorate a complex parameter with `[FromRoute]`, then you're implicitly binding all contained properties to the route only. This means that ASP.NET Core won't populate the values if they're passed in the query instead. Furthermore, the route approach won't work either because route-bound parameters/properties MUST be defined as a parameter in the route template, but in your example (i.e. `api/catalog-items/{CatalogItemId}`), `CorrelationId` is not defined. To illustrate both of these issues, try hitting your APi with the following via something like CURL or Postman:

```
DELETE /api/catalog-items/123?CorrelationId=e1dcb5a5-809c-4bb9-9ab2-d522541dde18
```
In this case, the CorrelationId property WILL NOT be populated with the provided value.

```
DELETE /api/catalog-items/123/e1dcb5a5-809c-4bb9-9ab2-d522541dde18
```
In this case, you're API will return a 404 because there is no matching route template

To get around this, you can simply  decorate the `CorrelationId` property with an explicit `[FromQuery]` binding:

```csharp
public abstract class BaseRequest
{
    [FromQuery]
    public Guid CorrelationId { get; set; }
}
```

This way, you can allow the property to be optionally set via query string. Furthermore, Swashbuckle will follow suit by describing the parameter as an optional query string parameter.

**Comment by ardalis** [comment]
I believe I tried adding FromQuery to CorrelationId without success, but perhaps that was a combination I missed.

What I managed to get to work was this:

```csharp
public abstract class BaseMessage
{
    protected Guid _correlationId = Guid.NewGuid();
    public Guid CorrelationId() => _correlationId;
}
public abstract class BaseRequest : BaseMessage 
{
}
public abstract class BaseResponse : BaseMessage
{
    public BaseResponse(Guid correlationId) : base()
    {
        base._correlationId = correlationId;
    }

    public BaseResponse()
    {
    }
}
```

Then for instance the delete endpoint looks like this:
```csharp
        [HttpDelete("api/catalog-items/{CatalogItemId}")]
        [SwaggerOperation(
            Summary = "Deletes a Catalog Item",
            Description = "Deletes a Catalog Item",
            OperationId = "catalog-items.Delete",
            Tags = new[] { "CatalogItemEndpoints" })
        ]
        public override async Task<ActionResult<DeleteCatalogItemResponse>> HandleAsync([FromRoute]DeleteCatalogItemRequest request)
        {
            var response = new DeleteCatalogItemResponse(request.CorrelationId());
            // more stuff
        }
```

And the swagger.json:

```json
"/api/catalog-items/{CatalogItemId}": {
      "delete": {
        "tags": [
          "CatalogItemEndpoints"
        ],
        "summary": "Deletes a Catalog Item",
        "description": "Deletes a Catalog Item",
        "operationId": "catalog-items.Delete",
        "parameters": [
          {
            "name": "CatalogItemId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteCatalogItemResponse"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteCatalogItemResponse"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteCatalogItemResponse"
                }
              }
            }
          }
        }
```

I'm OK (for now) with CorrelationId not being settable from the API itself as I'm fine to generate it within the initial request. If I decide I have to have it sent from the client as an optional querystring I'll see if I can get your solution to work.

Thanks!
