### ISSUE TITLE
Support "scopes" configuration for ui.initOAuth

### ISSUE THREAD

**Issue by logankp** [domaindrivendev/Swashbuckle.AspNetCore#1725]
Swagger UI recently added support for specifying scopes to be selected by default on the authorization modal. Please expose this setting in `OAuthConfigObject`.

SwaggerUI version 3.26.1 adds support for this. See https://github.com/swagger-api/swagger-ui/pull/6037.

**Comment by Vaccano** [comment]
I was about to try to make a pull request for this!  Looks like it is done an awaiting being pulled in.  Looking forward to this feature once it is in Swashbuckle!
