### ISSUE TITLE
ProducesResponseTypeAttribute not as functional as SwaggerResponseAttribute

### ISSUE THREAD

**Issue by tillig** [domaindrivendev/Swashbuckle.AspNetCore#173]
With the removal of `SwaggerResponseAttribute` in favor of the base MVC `ProducesResponseTypeAttribute` some ability to annotate the API seems to have disappeared (please do correct me if I'm wrong).
- **All responses require a type.** The `ProducesResponseTypeAttribute` allows you to specify a response code but you also must _also_ specify a non-null `System.Type` that goes with the response. What sort of type comes back with a 404? (It looks like @domaindrivendev [has already filed an issue on this](https://github.com/aspnet/Mvc/issues/4863), but there isn't a corresponding discussion here, so it may be worth talking about from a workaround perspective.)
- **There is no per-response description.** The `ApiExplorer.ApiResponseType` object has a status code and type associated, but no plaintext description. The current generator code [maps the description to hardcoded strings](https://github.com/domaindrivendev/Ahoy/blob/d871059b1898b97c9ab9d31ecc40ab15d183d119/src/Swashbuckle.SwaggerGen/Generator/SwaggerGenerator.cs#L216) but there's no great way to get that info back in there.

My current workaround is basically to replicate the original `SwaggerResponseAttribute` and put my own operation filter in place to get the full, richer set of data back in there.

I'm curious if there is a plan longer-term to put more metadata markup ability back into Swashbuckle or if this will always be a custom extension. If you don't want it in the main Swashbuckle packages, perhaps a new package `Swashbuckle.Metadata` or something with the attributes put back?

**Comment by vas6ili** [comment]
@tillig You can use a custom tag `<response code="200">description here</response>` in XML docs to add a description to each response type ([this example in one of the test websites](https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/Basic/Controllers/ResponseTypeAnnotationsController.cs)). While there are

**Comment by domaindrivendev** [comment]
You can also use typeof(void) for responses that don't contain a payload

**Comment by tillig** [comment]
Using XML docs doesn't seem to work in ASP.NET Core if you have a modular application where some of your REST API controllers are in separate assemblies. The XML docs don't appear to get copied to the build output / package directory.

`typeof(void)` is a trick I didn't think of to handle the type. Still doesn't take care of the per-response description, but it's a step closer.

**Comment by vas6ili** [comment]
@tillig That is strange. I have request/response models and controllers in separate assemblies and it seems to work just fine.

**Comment by tillig** [comment]
@vas6ili Are the assemblies in the same solution or are they packages pulled down from, say, an internal NuGet server? My situation is the latter. The dotnet CLI tooling has never copied the XML doc from external packages into the build output location that I'm aware of. If you've found a way to force that, I'd be interested.

Regardless, I'm more interested in solving this problem with metadata that I can separate from developer doc. XML doc typically has other artifacts like "see" links that reference things that don't make sense from an outside consumer perspective. We're trying to keep XML doc for the folks working on the actual REST controllers in Visual Studio (eg, Intellisense items) and have very specific doc for API consumers using different phrasing that is clearer for that audience. Our experience had been that it is too hard to consistently write a single set of docs that works for both audiences.

**Comment by domaindrivendev** [comment]
@tillig - I totally get your point regarding the overloaded use of XML comments. As you mentioned, the typical audience is internal developers within the context of C#. This is very different from an external audience in the context of HTTP and JSON described through Swagger. Since SB's inception, I've been aware of this fact and for some time I seriously contemplated removing the XML Comment support altogether. However ...

Overtime, it's become apparent to me that most users rely heavily on this feature and really really like it. From a practical standpoint, it's much easier to write human-readable descriptions within XML comment blocks as opposed to string parameters on an attribute. So, I've decided to go with it as the de facto approach for human readable descriptions. For those who favor attributes over XML comments, it's fairly trivial to create a custom attribute / operation filter pair themselves.

Another alternative that I would certainly consider, albeit a couple of milestones down the road, is a set of custom XML tags that are specifically for descriptions at the API layer. This might yield the best of both worlds - the convenience of documenting via inline comments and the ability to distinguish between internal and external comments. Would be interested to get your thoughts?

**Comment by tillig** [comment]
My thoughts are that I'd like to keep the two things separate. The previous attribute system worked well. It kept the XML API well separated from the Swagger docs. It didn't cause devs who may be newer to doc writing to forget the difference in audience between the two things. It was testable. You could write custom FxCop rules or Roslyn analyzers for it. They were always available even if the app was distributed without PDB/XML files.

Going to a mixture of attribute and XML doc just creates confusion. I get that's probably fine in small teams or teams of folks who work tightly together, but in large distributed enterprise teams, it sounds like a situation that could become "standards whack-a-mole," trying to enforce a combination of things that have a high potential to be far less easy to automate checks against.

Sorry, I'm pretty passionate about my doc. I don't mean to sound demanding. If the answer is "roll your own because XML is the way now," it'll be disappointing... And I guess I'll roll my own because XML comments, even custom XML tags, won't work for me.

I might even go so far as to suggest a way to tie the attributes to RESX files for localization capability, sort of how DataAnnotations validation messages can be localized. That's a "futures" sort of thing, but not really something available in plain XML doc.

**Comment by domaindrivendev** [comment]
Your arguments make sense and you have me pretty much convinced that I should add the SwaggerResponse attributes back.

I'm keen to get the 6.0.0 stable release out in the coming days so it will be the following milestone. As always, help by way of a PR would always be appreciated.

**Comment by tillig** [comment]
Excellent. I'd be happy to help. Let me see what I can cook up. May be really next week as I'm on PTO this week.

**Comment by tillig** [comment]
Posted a PR for this. Sorry for the delay. Feedback welcome.

**Comment by domaindrivendev** [comment]
As per your PR, SwaggerResponseAttribute re-added and available in the latest version - Swashbuckle.AspNetCore.1.0.0-rc1 (NOTE: the package name change).
