### ISSUE TITLE
No operations in swagger when using MapRoute without Route attributes

### ISSUE THREAD

**Issue by bpiec** [domaindrivendev/Swashbuckle.AspNetCore#1730]
I am targeting .NET Core 2.1 and I don't want to use the `Route` attributes but use the default route. Here's my `Startup` code:

```csharp
public class Startup
{
	public Startup(IConfiguration configuration)
	{
		Configuration = configuration;
	}

	public IConfiguration Configuration { get; }

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

		services.AddSwaggerGen(c =>
		{
			c.SwaggerDoc("v1", new OpenApiInfo { Title = "API V1", Version = "v1" });
		});
	}

	public void Configure(IApplicationBuilder app, IHostingEnvironment env)
	{
		app.UseSwagger();

		app.UseMvc(routes =>
		{
			routes.MapRoute(
				name: "default",
				template: "api/{controller}/{action}");
		});
	}
}
```

The controller is simple:

```csharp
public class ValuesController : ControllerBase
{
	[HttpGet]
	public ActionResult<IEnumerable<string>> Get()
	{
		return new[] { "value1", "value2" };
	}
}
```

I can go to `https://myurl/api/values/get` and it works (returns an array). However when I open `swagger.json` there are no operations defined:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": { },
  "components": { }
}
```

I believe this is a bug. I am using Swashbuckle 5.5.1.

**Comment by chsakell** [comment]
Original package doesn't support conventional based routes. 

You can try [Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting](https://github.com/chsakell/Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting) if your application targets ASP.NET Core 2.2 or 3.X.

**Comment by domaindrivendev** [comment]
@chsakell is correct - this feature is not supported nor will it be supported
