### ISSUE TITLE
How to set the HTTP schema selection box

### ISSUE THREAD

**Issue by stulzq** [domaindrivendev/Swashbuckle.AspNetCore#1731]
![image](https://user-images.githubusercontent.com/13200155/86346928-304ebb00-bc90-11ea-9312-21fbab978fa2.png)

**Comment by stulzq** [comment]
I tried some settings, but it seemed wrong. Is there an option to do this

**Comment by qgaye** [comment]
same question, did you solve it

**Comment by domaindrivendev** [comment]
In the latest version of the code, this is automatically set according to the URL that the Swagger JSON is consumed from. For example, if you're app is hosted at `https://<your-host>`, and the Swagger JSON is provided at `https://<your-host>/swagger/v1/swagger.json`, then the schemes drop down will have the value `HTTPS`.

Additionally, you customize these values by modifying the `document.Servers` array in a custom a document filter (see readme).

**Comment by stulzq** [comment]
Thank you .
