### ISSUE TITLE
Swashbuckle.AspNetCore.Cli "servers" part no appearing in swagger.json

### ISSUE THREAD

**Issue by woeterman94** [domaindrivendev/Swashbuckle.AspNetCore#1732]
In my startup I have

```
			app.UseSwagger(c =>
			{
				c.PreSerializeFilters.Add((swagger, httpReq) =>
				{
					// api gateway
					swagger.Servers = new List<OpenApiServer> { new OpenApiServer { Url = "__API-SCHEME__://__API-URL__" } }; // pipelines variables
				});
			});
```

When I run my application and visit /swagger.json I see the server array in my json

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "MY API",
    "version": "v1"
  },
  "servers": [
    {
      "url": "__API-SCHEME__://__API-URL__"
    }
  ],
```

However when using the CLI tool (dotnet swagger tofile --output swagger.json $(OutputPath)\$(AssemblyName).dll v1 )
The servers part is missing from my json.

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "my API",
    "version": "v1"
  },
  "paths": {
    "/api/v{version}/something/something": {
      "get": {
        "tags": [
          "test"
        ],
```
Am I doing something wrong?

**Comment by hctv19** [comment]
We're having basically the same issue - code that is set up to modify the generated OpenAPI doc within the app.UseSwagger() method isn't being executed when we generate the document using the CLI

**Comment by domaindrivendev** [comment]
`PreSerializeFilters` is a setting specifically for the Swagger _middleware_ - i.e. the Swashbuckle component that serves up the generated Swagger as a JSON endpoint. It's meant for the use-case where you want to enrich the generated Swagger doc with incoming request context. For example, assigning the server metadata base on "X-Forwarded-*" headers in the request.

It's not applicable when using the CLI tool. If you want a solution that works in the CLI case, use an `IDocumentFilter` (see readme) instead.
