### ISSUE TITLE
No TryGetMethodInfo in ApiDescription on CustomOperationIds method

### ISSUE THREAD

**Issue by Yukimir** [domaindrivendev/Swashbuckle.AspNetCore#1733]
From document [(https://github.com/domaindrivendev/Swashbuckle.AspNetCore#assign-explicit-operationids)]
in Option 2)
```
    c.CustomOperationIds(apiDesc =>
    {
        return apiDesc.TryGetMethodInfo(out MethodInfo methodInfo) ? methodInfo.Name : null;
    });
```
but there is no TryGetMethodInfo method in apiDesc.
And there is no way to get method info.

**Comment by eLarocque** [comment]
Same here. Does anyone have info on why this could be? Is there a new undocumented way to getting this functionality?

**Comment by eLarocque** [comment]
I think I was able to get similar information using:
```
c.CustomOperationIds(apiDesc =>
{
    var versions = apiDesc.ActionDescriptor.EndpointMetadata.Where(p => p.GetType() == typeof(ApiVersionAttribute)).SelectMany(attr => (attr as ApiVersionAttribute).Versions).ToList();

return versions.Any(v => $"{v.ToString()}" == docName);
});
```

**Comment by domaindrivendev** [comment]
You need to import the following namespace:

```csharp
using Swashbuckle.AspNetCore.SwaggerGen;
```
