### ISSUE TITLE
Models which are Required and have no setter are not marked as readonly

### ISSUE THREAD

**Issue by freeranger** [domaindrivendev/Swashbuckle.AspNetCore#1734]
I am upgrading from 3.0 to 5.4.1 and still serialising as V2 Swagger.
I have a model like this:
```
    internal class FooModel
    {
        /// <summary>
        /// The name of the Foo
        /// </summary>
        [Required]
        public string Name { get; }

        public FooModel(string name)
        {
            Name = name;
        }
    }       
```

In v3 of swashbuckle this would be rendered as:
```
"FooModel": {
	"required": [
		"name"
	],
	"type": "object",
	"properties": {
		"name": {
			"description": "The name of the Foo",
			"type": "string",
			"readOnly": true
		}
	}
}```
but in 5.4.1, still serialising as v2 swagger, I get:
```
    "FooModel": {
      "required": [
        "name"
      ],
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the Foo",
          "type": "string"
        }
      }
    },
```
So it has lost the readonly aspect.

If i serialise as OpenAPI v3 then it reappears:
```
      "FooModel": {
        "required": [
          "name"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the Foo",
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
```

**Comment by domaindrivendev** [comment]
Swashbuckle uses an external library [OpenAPI.NET](https://github.com/microsoft/OpenAPI.NET) for the serialization back to V2 feature. Given that the v3 version is as expected, this must be an issue in that external library and should be posted there instead.

With that said, The `[Required]` attribute is for validating _input_ data so why would you ever want to mark a read only property with it. For context, `readOnly` in Swagger / OpenAPI indicates that a property can be returned in a response payload but should not be provided as part of an incoming payload.

**Comment by martincostello** [comment]
Closing as external.
