### ISSUE TITLE
Translation language file doesn't work

### ISSUE THREAD

**Issue by fenomeno83** [domaindrivendev/Swashbuckle.AspNetCore#1739]
Hi. I need to translate swagger ui in italian.

I've swashbucle 5.1 in .net core 3.1 project.

I've download translator.js and it.js from here
https://github.com/swagger-api/swagger-ui/tree/1f2a5d7dd74131f0e9886b0f137ac20165aa90d2/dist/lang

Then I've create a wwwroot folder in my project (because missing and need to put static files)

Then I've enabled static files in startup

    app.UseStaticFiles();

I've put the 2 files inside wwwroot folder and addes in startup

           app.UseSwaggerUI(c =>
            {
                
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Public API");

                c.HeadContent = "<script src='./translator.js'></script><script src='./it.js'></script>";

                c.RoutePrefix = string.Empty;
            });

When i start application, index,html has included script and they are correctly downloaded
Here the head part of generated index.html

      
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Swagger UI</title>
      <link rel="stylesheet" type="text/css" href="./swagger-ui.css">
      <link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
      <link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" />
      <style>

        html {
            box-sizing: border-box;
            overflow: -moz-scrollbars-vertical;
            overflow-y: scroll;
        }

        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }

        body {
            margin: 0;
            background: #fafafa;
        }
    </style>
    <script src='./translator.js'></script><script src='./it.js'></script>
</head>

But page is not translated.

Can you help me?

**Comment by fenomeno83** [comment]
I've created a my custom solution

https://github.com/fenomeno83/SwaggerGlobalization

**Comment by domaindrivendev** [comment]
This issue should be posted to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui) instead of SB
