### ISSUE TITLE
Feature request - include execution time in the swagger UI, around response output view

### ISSUE THREAD

**Issue by aravindk777** [domaindrivendev/Swashbuckle.AspNetCore#1740]
how good it would be, to include some options to show the response time, execution time for the route? It can be made as configurable if needed to include in the swagger UI. This is just to see the processing/execution time only on the swagger and doesnt need to modify anywhere on the actual api request and response outputs. 

More of an output element on the swagger UI only. Right now, if i want to capture the time taken to execute a route/endpoint, i use logging to log such information. But if its just more of an easy attribute and only needed to know from the UI, why would i want to log the time taken attr (may be useful on the logs for the apps but not at all the times to be in the logs, right..)

**Comment by domaindrivendev** [comment]
This is already possible:

```csharp
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("v1/swagger.json", "V1 Docs");

    c.DisplayRequestDuration();
});
```

**Comment by freeranger** [comment]
Awesome, just added that to mine - thanks DDD!

**Comment by abdelgrib** [comment]
For other versions 

`c.AdditionalSettings.Add("displayRequestDuration ", true)`
