### ISSUE TITLE
XmlComments for references schemas are not generated

### ISSUE THREAD

**Issue by freeranger** [domaindrivendev/Swashbuckle.AspNetCore#1741]
I am upgrading from Swashbuckle 3.0 to 5.4.1 and noticed an issue with xml comments for properties referencing another schema.

Using your demo Basic project if I add this type:
``` csharp
 /// <summary>
 /// Product Container Summary
 /// </summary>
 public class ProductContainer
 {
     /// <summary>
     /// Contained Product Summary
     /// </summary>
     public Product ContainedProduct { get; set; }
 }
```

And change your CrudActionControllers Create method to:
``` csharp
  [HttpPost]
  public ProductContainer Create([FromBody, Required] ProductContainer product)
  {
      return product;
  }
```
Then the definition in the generated swagger using 3.0 looks like this:
``` json
  "ProductContainer": {
    "description": "Product Container Summary",
    "type": "object",
    "properties": {
      "ContainedProduct": {
        "$ref": "#/definitions/Product",
        "description": "Contained Product Summary"
      }
    }
  },
```
but using 5.4.1 looks like this:
``` json
  "ProductContainer": {
    "type": "object",
    "properties": {
      "containedProduct": {
        "$ref": "#/components/schemas/Product"
      }
    },
    "additionalProperties": false,
    "description": "Product Container Summary"
  },
```
You can see that it has lost the description of ContainedProduct from the ProductContainer class

**Comment by domaindrivendev** [comment]
Long story short, the older version was generating invalid Swagger / OpenAPI JSON, because "reference" schemas should only include the `$ref` field and no others.

So, with this constraint, how would one provide a description for a property schema that references another schema? Well, the recommended approach is to use the `allOf` keyword to extend the type-specific schema with additional property-specific metadata (e.g. the property description) as follows:

```
"properties": {
  "containedProduct": {
    "allOf": [
      { "$ref": "#/components/schemas/Product" }
    ],
    "description": "Contained Product Summary"
  }
}
```

This way, the property description can be included in addition to the type-specific metadata in the referenced schema. However, it does alter the structure of the generated Swagger / OpenAPI and is therefore supported by Swashbuckle as _opt_-in behavior via the `UseAllOfToExtendReferencedSchemas` setting.

**Comment by freeranger** [comment]
Hi

Thanks for the explanation - seems a bit of a strange limitation to have in the spec.
In my use case I have this notion of what an "identifier" looks like, so there is a generic description of this on the Identifier class, but in the specific uses of same I want to be able to describe it as "Identifies the Product" or whatever.   I can't imagine this is an unusual requirements...

The funny thing is that swagger-codegen totally respected the description attribute so if it was incorrect to do so, at least everyone was consistent ;)  
I can't see anything in the 2.0 spec that states no other props are allowed (where I can see that in the 3.0 spec) perhaps they weren't strong on that, or just didn't articulate it, or maybe I'm just blind and can't see it...

I see what you mean about {{UseAllOfToExtendReferenceSchemas}} changing the structure of the generated json - I don't think I can go with that unfortunately :/

What I am doing is upgrading a shared library so it can be used with new .NET Core 3.1 apps with OpenAPI3.0 output produced as well as existing .NET Framework apps which output swagger 2.0.   The latter I do not want to introduce any breaking changes but I am struggling a bit to keep the output the same, as in this case.
It would be nice if there was a compatibility option to keep producing things the old way, even if it wasn't quite to spec, but I can understand you might not want to do that.

Is there any way I can force the old behaviour?   Like some kind of "last chance to fiddle with things" hook into the pipeline?

Thanks

**Comment by domaindrivendev** [comment]
@freeranger - unfortunately there is no way to force the old way because it's incorrect. I'm going to close this issue as I don't believe any further action can be feasibly made on the Swashbuckle side.
