### ISSUE TITLE
AddServer in ASP.NET Core and Swagger UI

### ISSUE THREAD

**Issue by ameyasubhedar** [domaindrivendev/Swashbuckle.AspNetCore#1746]
As per the [documentation ](https://swagger.io/docs/specification/api-host-and-base-path/) of the Swagger Open Api 3.0... we have to specify the server to describe the base url of the Swagger API.

In My ConfigureServices I added the following 

```
// Add server
c.AddServer(new OpenApiServer()
{
     Url = "https://api.example.com/v1"
});
```

But if I add this I get the TypeError: Failed to fetch error.

If I do not specify any server the API works and pics up the BaseUrl correctly ?

What is the correct way to specify server in the asp.net core - swagger ui and do we need to specify it at-all ?

**Comment by domaindrivendev** [comment]
If you don't specify the server, then Swashbuckle will infer it from the request made to retrieve the Swagger JSON.

For example, if you're API is hosted at `https://<your-api-host>` and you're using SB to expose Swagger JSON at `https//<your-api-host>/swagger/v1/json`, then the server array will be automatically be populated with `https://<your-api-host>`. In most case this works well and is perfectly sufficient.

However, if you want to list additional hosts for your API (e.g. test environments etc.) then you could use the `AddServer` setting to add them.

**Comment by xiting121** [comment]
When I try to add below code to services.AddSwaggerGen, I got SwaggerGens does not contain a definition for AddServer   
 c.AddServer(new OpenApiServer()
                {
                    Url = "http://myapi.com/development/v1"
                });
When I run my api  locally (debug with localhost), no server array, after publish to DEV server, I saw server array, is this the default behavior?

**Comment by obarlik-defacto** [comment]
This worked for me

            services.AddOptions<OpenApiDocumentMiddlewareSettings>()
                .Configure<IConfiguration>((settings, config) =>
                {
                    settings.PostProcess = (doc, req) =>
                    {
                        doc.Info.Title = GetAppNameDisplay(appName);
                        doc.Info.Version = "v1";

                        if (!Debugger.IsAttached && !EnvironmentHelper.IsUnitTesting)
                        {
                            BaseUrlProvider bup = req.HttpContext.RequestServices.GetRequiredService<BaseUrlProvider>();

                            doc.Servers.Clear();
                            doc.Servers.Add(new OpenApiServer
                            {
                                Url = bup.BaseUrl,
                                Description = "API Server"
                            });
                        }
                    };
                });
