### ISSUE TITLE
Should MaxLengthAttribute on collection result in maxItems property instead of maxLength property?

### ISSUE THREAD

**Issue by OldrichDlouhy** [domaindrivendev/Swashbuckle.AspNetCore#1747]
Swashbuckle always generates the `maxLength` property for fields marked with `MaxLengthAttribute`, regardless whether it is used on string or on collection.

I am not sure whether it is correct as according to https://swagger.io/specification/ the following properties are taken directly from the JSON Schema definition and follow the same specifications:
* maxLength
* minLength
* maxItems
* minItems

According to the JSON Schem definition, the `maxLength` and `minLength` govern strings (https://json-schema.org/understanding-json-schema/reference/string.html), while `maxItems` and `minItems` govern arrays (https://json-schema.org/understanding-json-schema/reference/array.html#length).

Should Swashbuckle generate the `maxItems` and `minItems` properties when the corresponding attribute is used on collection property?

**Comment by skillful-alex** [comment]
I faced the same problem.
And a question about min/maxItems on stackoverflow [how-to-set-maxlengthattribute-for-ienumerable-which-is-returned-from-metod-for](https://stackoverflow.com/questions/63392286/how-to-set-maxlengthattribute-for-ienumerable-which-is-returned-from-metod-for)

**Comment by domaindrivendev** [comment]
Fixed by 341751b

**Comment by ELTemi** [comment]
@domaindrivendev when will the 5.6.0 version be available in nuget? Thanks

**Comment by domaindrivendev** [comment]
@ELTemi  v5.6.0 now pushed to Nuget. Pull it down and let me know how it goes
