### ISSUE TITLE
OAuth2 client-credentials flow - unable to set clientid and secret key for authentication

### ISSUE THREAD

**Issue by Petteroe** [domaindrivendev/Swashbuckle.AspNetCore#175]
I am using 6.0.0-beta902 of Swashbuckle SwaggerGen and SwaggerUi (because rc1-final is not compatible with net461)

I am using OAuth2 client-credentials flow to authenticate calling clients, and the support for this in Swashbuckle looks promising. Right up to the point where you actually want it to work. I get an Authorize button in the top bar of the UI, but when I select the scope and click the authorize button I don't get anywhere. 

I tried to hack the javascript according to this issue: Allow to set values in initOAuth #75, but that killed the entire UI. 

Can you please provide a way to set these values?

Thanks,
Morten

**Comment by ChrisRichner** [comment]
+1

**Comment by robert53** [comment]
+2

**Comment by ThinkAboutGitHub** [comment]
+3

**Comment by jaymcguinness** [comment]
+4

**Comment by carlos8k** [comment]
+5

**Comment by domaindrivendev** [comment]
The code changes for this are pushed and available as a preview package (see https://www.myget.org/gallery/domaindrivendev). See the following for an example:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/SecuritySchemes/Startup.cs#L64

Will be available as a stable release very shortly

**Comment by ChrisRichner** [comment]
I could not test it because the package refuses to run against net46 ,(

What do I miss?

**Comment by alzuma** [comment]
+6

**Comment by thangchung** [comment]
+7

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"
