### ISSUE TITLE
SwaggerGen incorrectly combines multiple instances of ProducesAttribute

### ISSUE THREAD

**Issue by wjrogers** [domaindrivendev/Swashbuckle.AspNetCore#1752]
`ProducesAttribute` has `AllowMultiple = false`, so the attribute cannot be specified more than once. However, it can be inherited (by a method from the controller class, or by the controller class from a base class). When inherited, the last-applied instance wins. ASP.NET Core does not combine the content-types from multiple instances.

However, SwaggerGen does:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/b7cf75e7905050305b115dd96640ddd6e74c7ac9/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L418-L422

This results in a swagger document that lists response content-types that the operation does not actually support. The ApiExplorer metadata is correct, but SwaggerGen does not use it because it checks `ProducesAttribute` first.

Here is an example filter that demonstrates the problem by removing unsupported response formats from the operation:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Example.Filters
{
    public class ProducesOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            foreach (var responseType in context.ApiDescription.SupportedResponseTypes)
            {
                // based on internals of SwaggerGenerator
                // https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/b7cf75e7905050305b115dd96640ddd6e74c7ac9/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L383-L387
                var responseKey = responseType.IsDefaultResponse ? "default" : responseType.StatusCode.ToString();
                var response = operation.Responses[responseKey];

                // remove media types not supported by the API
                foreach (var contentType in response.Content.Keys)
                {
                    if (!responseType.ApiResponseFormats.Any(x => x.MediaType == contentType))
                        response.Content.Remove(contentType);
                }
            }
        }
    }
}
```

Could SwaggerGen simply remove the lines I've quoted above and rely on ApiExplorer's metadata? Or is there a (version compatibility?) reason to keep the explicit `ProducesAttribute` check?

Versions:
- Swashbuckle.AspNetCore 5.5.1
- ASP.NET Core 3.1
- Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer 4.1.1

**Comment by domaindrivendev** [comment]
IIRC there was definitely scenarios where the API explorer metadata did not reflect what was specified by explicit `Produces/Consumers` attributes and that's why the logic you referenced was added. I'll have to dig a little deeper to uncover those scenarios, and understand if they're still applicable.

**Comment by DaleyKD** [comment]
Holy cow.  This whole time, because of Swagger, I thought that ASP .NET DID combine them.  Just found out today that I've been getting sporadic 406s because I didn't include the `[Produces(MediaTypeNames.Application.Json, "application/problem+json")]` with `[Produces(MediaTypeNames.Application.Octet)]`
