### ISSUE TITLE
How to generate a response example based on a header type?

### ISSUE THREAD

**Issue by zinov** [domaindrivendev/Swashbuckle.AspNetCore#1754]
I have 2 Action methods on my API that are decorated with a GET attribute for the same route. Based on the Accept header value I pass I can target one or the other. Now, with Swashbuckle you bind your response example to a specific status code, which in my case is 200 for both but the response model should be different for each of them, is there a way to implement a response example not using the XML doc approach?

**Comment by flamaniac** [comment]
Ehhh my stupid mistake. Properties don;t have setters. I added init and it Swagger is showing properties now. Sorry for bother,

**Comment by domaindrivendev** [comment]
Dup of #1691
