### ISSUE TITLE
Unable to change group order with `OrderActionsBy` when only some group have description 

### ISSUE THREAD

**Issue by yyjdelete** [domaindrivendev/Swashbuckle.AspNetCore#1757]
Swashbuckle.AspNetCore 5.5.1

When `IncludeXmlComments(..., includeControllerXmlComments: true)` is used, but only some controllers have comments, it's unable to change the order of groups with `OrderActionsBy`(the ones with description is always the first)

Seems `Swashbuckle.AspNetCore` only gen tags with Description in OpenApiDocument.Tags, and according to https://swagger.io/specification/#fixed-fields,`The tags that are not declared MAY be organized randomly or based on the tools' logic.`

Is there an options to force `Swashbuckle.AspNetCore` generate all tags?

**Comment by yingxinj** [comment]
I have just opened a PR #2565 that would fix this issue by adding all Controller tags to the root tags object, not just tags with description, please let me know if it is helpful :) the root tags are then sorted by name as a sensible default, but having the tags object be a complete list means that you can sort them in other ways if preferred.

**Comment by martincostello** [comment]
#2565
