### ISSUE TITLE
Namespace name 'SwaggerRequestParameter' could not be found

### ISSUE THREAD

**Issue by kuntalbose** [domaindrivendev/Swashbuckle.AspNetCore#1758]
I am trying to implement [Enrich RequestBody Metadata](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#enrich-requestbody-metadata)  described in documentation .But Visual studio showing bellow error.

![image](https://user-images.githubusercontent.com/7402233/88689715-76c0f980-d118-11ea-9efd-592ca20b4812.png)

I include bellow packages in my project 

 ```
<PackageReference Include="Swashbuckle.AspNetCore" Version="5.5.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="5.5.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="5.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="5.5.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.ReDoc" Version="5.5.1" />
```
Am I doing any thing wrong?

**Comment by domaindrivendev** [comment]
As stated in the docs you referenced, the attribute name is `SwaggerRequestBody` not `SwaggerRequestParameter`
