### ISSUE TITLE
Problem Documenting Required Properties

### ISSUE THREAD

**Issue by daymar23** [domaindrivendev/Swashbuckle.AspNetCore#1759]
Hello!!

I am trying to create more documentation in some APIs,

I want to change the optional field to a required field.
![image](https://user-images.githubusercontent.com/68713491/88691246-db00a080-d0b9-11ea-8e54-0f17484cd765.png)

But when I add the DataAnnotations [Required] in a property, swagger returns me a 500 error.
![image](https://user-images.githubusercontent.com/68713491/88691307-f075ca80-d0b9-11ea-8024-bfa85b901123.png)

![image](https://user-images.githubusercontent.com/68713491/88691353-ff5c7d00-d0b9-11ea-9a65-9d8deb052377.png)

I read from a lot of documentation and this is supposed to work, but it'snot working.

**Comment by domaindrivendev** [comment]
Try navigating to the Swagger JSON page directly - if you’re using the default route config for Swashbuckle I think you’ll find this at at /v2/swagger/v1/swagger.json. If something is going wrong with the Swagger generation the full stack trace should be visible there

**Comment by daymar23** [comment]
There is not a swagger.json file. 
![image](https://user-images.githubusercontent.com/68713491/88720399-08f9db00-d0e2-11ea-8a90-643add9495d9.png)

**Comment by domaindrivendev** [comment]
Navigate to the url in the white box at the top of the swagger page - that’s the swagger.json page

**Comment by domaindrivendev** [comment]
By “navigate”, I mean type it into your browser address bar

**Comment by daymar23** [comment]
Sorry. I am new with swagger and I thought you were referring to the swagger browser. 

This is the error: 
![image](https://user-images.githubusercontent.com/68713491/88813751-8bcc7580-d176-11ea-9204-02ee3c516ea3.png)

**Comment by daymar23** [comment]
I already checked that issue and added the Microsoft.Web.Infrastrure package and right now a have this error: 

message="Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified." source="mscorlib"

I added the System.ComponentModel.Annotations library but I have the same error.

**Comment by daymar23** [comment]
I changed the System.ComponentModel.Annotations version from 4.7.0 to 4.4.1 and this fixed my problem.
Thanks for your help.
