### ISSUE TITLE
SerializeAsV2 - Request body parameter name is not respected and is set to `body`

### ISSUE THREAD

**Issue by amrElroumy** [domaindrivendev/Swashbuckle.AspNetCore#1770]
**Swashbuckle.AspNetCore version:**  5.5.1

I'm currently using Autorest to generate the client from the generated swagger.json file. 

Unfortunately, the generated client has non-friendly parameter name `body`. The ask is to support overriding the parameter name or at least support the [`x-ms-client-name` Autorest extension](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-client-name). 

I tried using operation filters to modify the request body schema and adding `name` property or the `x-ms-client-name` extension, but they are not respected when serializing to V2.

Startup.cs:
```csharp
app.UseSwagger(
    swaggerOptions =>
    {
        swaggerOptions.SerializeAsV2 = true;
        swaggerOptions.RouteTemplate = "/swagger/{documentName}/swagger.json";
    });
app.UseStaticFiles();
```

Controller action:
```csharp
/// <summary>
/// Creates a resource.
/// </summary>
/// <param name="createResourceRequest">Details of the resource to create.</param>
/// <response code="201">Resource created.</response>
[HttpPost(Name = "CreateResource")]
[ProducesResponseType(typeof(CreateResourceResponse), StatusCodes.Status201Created)]
public async Task<ActionResult> CreateResourceAsync([FromBody, BindRequired] CreateResourceRequest createRresourceRequest)
{
    // action logic
}
```

The generated OpenApi spec would have the following definition for the request body parameter:
```json
"parameters": [
  {
    "in": "body",
    "name": "body", // parameter name is always set to `body`
    "description": "Details of the resource to create.",
    "required": true,
    "schema": {
      "$ref": "#/definitions/CreateResourceRequest"
    }
  }
],
```

**Comment by rvarna** [comment]
Facing a similar issue and I think this is breaking our Autorest generation as well (since the datamodel classes get wiped out). Let me know if you figure out a way. I have been looking at schema generator options and filters to see if there is a way to force this.

**Comment by ravarnamsft** [comment]
Turns out the Autorest generation for us was broken due to a different set of issues and the parameter name not being honored doesn't seem to actually affect the usage of the generated code.

**Comment by devmedvedev** [comment]
Hello! 
Our company uses Swagger to generate OpenAPI schemas for use in Microsoft Power Automate and using parameter name for body parameters **is critical**. I tried to give a name but couldn't find a way

Please, if you know a way, tell me.
Thanks!

**Comment by domaindrivendev** [comment]
Dup of #1478
