### ISSUE TITLE
Description not showing for properties with User Defined Types (Classes)

### ISSUE THREAD

**Issue by vineetbindal** [domaindrivendev/Swashbuckle.AspNetCore#1771]
Please see this [StackOverFlow](https://stackoverflow.com/questions/63279361/swashbuckle-description-doesnt-show-up-for-properties-with-user-defined-types) post.

versions used:     
Swashbuckle.AspNetCore Version=5.5.0
Swashbuckle.AspNetCore.Newtonsoft Version=5.4.1

I have been trying to debug this issue and more investigation point to [SchemaGenerator ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/7a921e0d4b53a573c735cec8070c611b40871bfd/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs#L365). Setting up the flag `UseAllOfToExtendReferenceSchemas` results in this schema 
```

"application/json": {
  "schema": {
    "allOf": [
      {
        "$ref": "#/components/schemas/Metadata.ServiceCreationrequest"
      }
    ],
    "description": "Instance Creation Request.",
    "nullable": true
  }  
}


```
The introduction of `allOf` looks unnecessary here. it should look like 
```

"application/json": {
  "schema": {
      {
        "$ref": "#/components/schemas/Metadata.ServiceCreationrequest"
      },
    "description": "Instance Creation Request.",
    "nullable": true
  }  
}
``` 

Once I figured out what was causing the issue: I stumbled upon this: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1741
It seems like unnecessary to introduce `allOf` in all cases.

**Comment by domaindrivendev** [comment]
Incorrect! As per the JSON Schema specification, the $ref keyword _cannot_ be combined with other keywords in a schema. So to enrich a shared/referenced schema with additional metadata (e.g. in the case of a "property" schema), you _must_ use the `allOf` construct.
