### ISSUE TITLE
Using OperationFilter don't allow to add "Authorization" header as parameter

### ISSUE THREAD

**Issue by manish-panwar** [domaindrivendev/Swashbuckle.AspNetCore#1773]
We don't use `[Authorize]` attribute on out Controllers, and auth is enforced via a middleware. Now on GUI we want to allow passing the authorization header using [Operation Filter example](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/master/src/Swashbuckle.AspNetCore.Filters/AddHeaderOperationFilter.cs), it allows us to pass any custom header but if we try to use it for "Authorization" header, it don't pass the header value in request. Are there any specific reason that Authorization header can't be configured this way?

Since we don't use `[Authorize]` attribute in our controllers, we can't use [SecurityRequirementsOperationFilter](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#how-to-use---security-requirements-filter).

**Comment by joabealexandre** [comment]
@manish-panwar 
@pnavk described an solution that solved my problem. OpenAPI 3.0 ignore the name "Authorization" if it is declared on header.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1425#issuecomment-571926368
