### ISSUE TITLE
JsonElements are not shown properly in example values

### ISSUE THREAD

**Issue by huideaki** [domaindrivendev/Swashbuckle.AspNetCore#1775]
Issue is happening in 5.5.1 with jsonElement, The schema seems to properly see the JsonElement properties but will not add them in the example value.

My guess this is a side effect of #1709. The schema was update to show JsonElement as being any json which is valid.
The problem happens that the jsonElement is properly shown in the schema but will not be shown in the example value view.

Properties is my JsonElement property.

Schema
```
    "schemas": {
      "Vendor": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "buildingId": {
            "type": "string",
            "format": "uuid"
          },
          "properties": {
            "nullable": true
          }
        },
        "additionalProperties": false
      }
}
```

Example Value
```
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "buildingId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}
```

**Comment by domaindrivendev** [comment]
This is more of a Swagger UI than a Swashbuckle issue but IMO the behavior here is perfectly reasonable. If, by definition, a `JsonElement` can be literally anything, how can the UI possibly come up with a meaningful example?

If you want to display a better example, you'll need to explicitly provide one. This can be done with a "Schema Filter" (see readme). Something along the following lines should work:

```csharp
// Startup.cs
services.AddSwaggerGen(c =>
{
    c.SchemaFilter<ExamplesSchemaFilter>();
});

// ExamplesSchemaFilter.cs
public class ExamplesSchemaFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        if (context.Type == typeof(Vendor))
        {
            schema.Example = new OpenApiObject
            {
                ["id"] = new OpenApiString(Guid.NewGuid().ToString()),
                ["properties"] = new OpenApiString("foobar")
            };
        }
    }
}
```

**Comment by t-ricci-delta** [comment]
> This is more of a Swagger UI than a Swashbuckle issue but IMO the behavior here is perfectly reasonable. If, by definition, a `JsonElement` can be literally anything, how can the UI possibly come up with a meaningful example?
> 
> If you want to display a better example, you'll need to explicitly provide one. This can be done with a "Schema Filter" (see readme). Something along the following lines should work:
> 
> ```cs
> // Startup.cs
> services.AddSwaggerGen(c =>
> {
>     c.SchemaFilter<ExamplesSchemaFilter>();
> });
> 
> // ExamplesSchemaFilter.cs
> public class ExamplesSchemaFilter : ISchemaFilter
> {
>     public void Apply(OpenApiSchema schema, SchemaFilterContext context)
>     {
>         if (context.Type == typeof(Vendor))
>         {
>             schema.Example = new OpenApiObject
>             {
>                 ["id"] = new OpenApiString(Guid.NewGuid().ToString()),
>                 ["properties"] = new OpenApiString("foobar")
>             };
>         }
>     }
> }
> ```

@domaindrivendev but still won't be type "string", could be represented as any/object instead?
In my case JsonElement will be shown as "string" in the Swagger UI and is never actually a string

**Comment by danirzv** [comment]
if you use `schema.Example = new OpenApiObject();` too, it will show example as string instead of object
