### ISSUE TITLE
Suggestion: create GitHub swashbuckle organisation, consolidate main and community projects under it

### ISSUE THREAD

**Issue by IanKemp** [domaindrivendev/Swashbuckle.AspNetCore#1776]
Currently we have domaindrivendev/Swashbuckle and and domaindrivendev/Swashbuckle.AspNetCore as the main repos, with [Community Packages](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#community-packages) off living in their own repos. This creates a rather fragmented user experience and hinders discovery of potentially useful Swashbuckle packages over and above the ones listed in the README.

It makes sense to me to create a new [GitHub organisation](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-organizations) called `swashbuckle`, and allow both the "official" @domandrivendev packages, as well as the community ones, to be repos within that org. You would have something like swashbuckle/aspnetmvc (currently domaindrivendev/Swashbuckle), swashbuckle/aspnetcore (domaindrivendev/Swashbuckle.AspNetCore), swashbuckle/aspnetcore-filters (mattfrear/Swashbuckle.AspNetCore.Filters), etc. - with the current Community Package maintainers having full control over their specific repos. Basically, a one-stop shop for anyone to come to for everything Swashbuckle-related.

Anyone with a useful new Swashbuckle package could then apply to the swashbuckle org (essentially @domaindrivendev) for inclusion, if granted this would effectively "bless" their package.

I don't know about the logistics behind this, or whether you (@domaindrivendev) would even be interested in such an endeavour. Just throwing it out there in case it has merit.

**Comment by domaindrivendev** [comment]
@IanKemp I like this idea but when I last looked into it, I was unable to create an org called `Swashbuckle` because there's a github user out there with the same name 😭 

I was so dissapointed by this at the time that I just stopped looking into it any further - there really isn't any other name I'd like for the org 😉 

Soon I'll get over it though and start thinking about an alternative name ...

**Comment by martincostello** [comment]
#2778
