### ISSUE TITLE
Delist Swashbuckle.AspNetCore.AzureFunctions from Community Packages

### ISSUE THREAD

**Issue by IanKemp** [domaindrivendev/Swashbuckle.AspNetCore#1777]
As per https://github.com/bherila/Swashbuckle.AspNetCore.AzureFunctions/issues/8 the source has been removed from its repo over 2 months ago, and the owner hasn't responded as to what's going on in nearly a month. Until or unless some more clarity is provided, this package probably shouldn't be linked to in the README.

**Comment by domaindrivendev** [comment]
Done

**Comment by PehrGit** [comment]
I think the code was moved to a fork of the Swashbuckle.AspNetCore by the same author:

https://github.com/bherila/Swashbuckle.AspNetCore/tree/master/src/Swashbuckle.AspNetCore.AzureFunctions
