### ISSUE TITLE
App running at subpath but httpContext.Request.PathBase is not taken into account

### ISSUE THREAD

**Issue by abdusco** [domaindrivendev/Swashbuckle.AspNetCore#1779]
When running an app from a subpath, swagger ui middleware tries to redirect to index.html at root instead of subpath.

Here I have an app running at `/subapp`
```c#
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.Map("/subapp", app =>
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        
        app.UseRouting();
        app.UseSwagger(options => options.RouteTemplate = "docs/{documentName}.json");
        app.UseSwaggerUI(options =>
        {
            options.SwaggerEndpoint("docs/api.json", "api");
            options.RoutePrefix = "";
        });

        app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
    });
}
```

when I go to `localhost:5000/subapp` swagger tries to redirects me to `index.html` 

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/939ad54164af5820f93a926083d322899c09049f/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs#L57-L61

But the url resolves to nothing because swagger only responds to `/subapp/index.html`.

The solution is to prefix `relativeRedirectPath` with `httpContext.Request.PathBase`

**Comment by domaindrivendev** [comment]
Reverted the merge as it introduced a regression. Have a broader plan to resolve this issue but needs to wait for next _major_ release
