### ISSUE TITLE
Suggestion: support schema object "Title" property through existing SwaggerSchemaAttribute

### ISSUE THREAD

**Issue by MarkLeMerise** [domaindrivendev/Swashbuckle.AspNetCore#1783]
Forgive me if I missed this somewhere, but I crawled through the docs, and even the code to see if there was some attribute or code for setting the `title` property of a schema object ([as specified by the Open API spec](http://spec.openapis.org/oas/v3.0.3#properties)), but it looks like this is not currently supported, except through a custom filter (which is what I'm using right now).

From what I can tell, this feature would be a trivial update to the `AnnotationsSchemaFilter`, however I wasn't sure if excluding `title` was a design decision or has deeper ramifications.

Would it make sense for the `SwaggerSchemaAttribute` to be enhanced with a `title` parameter?

**Comment by domaindrivendev** [comment]
See cb63055

**Comment by MarkLeMerise** [comment]
Thanks for adding this! Much appreciated.
