### ISSUE TITLE
Support Swagger-UI version >= 3.27.0

### ISSUE THREAD

**Issue by BillLudwig** [domaindrivendev/Swashbuckle.AspNetCore#1784]
Thanks for all the hard work that goes into this project. I know that support for Swagger-UI 3.26.0 was just recently added but our team is wanting to take advantage of the click-to-copy feature that was added in 3.27.0.

Thanks again.

**Comment by domaindrivendev** [comment]
See 049b34b80ad91ea050da01d8545ce78dbf02a87f
