### ISSUE TITLE
Can't create readonly enum

### ISSUE THREAD

**Issue by paulshealy1** [domaindrivendev/Swashbuckle.AspNetCore#1788]
I'm using Swashbuckle 5.5.1, and I want a enum to be generated as a readonly property. Our code looks like this:

    [JsonConverter(typeof(StringEnumConverter))]
    public enum MyEnum
    {
        Value1, Value2, Value3
    }

    public class MyClass
    {
        [ReadOnly(true)]
        public MyEnum MyEnumProperty { get; }

        [ReadOnly(true)]
        public int MyIntProperty { get; }
    }

`MyClass` is returned from an operation. 

`MyIntProperty` is correctly generated as a readonly property in the swagger, but `MyEnum` is not. What do we need to do to fix this?

**Comment by paulshealy1** [comment]
Looking at this some more, we are generating our swaggers in v2 compatibility mode, and I think that is part of the problem. The output looks fine in v3 mode.

**Comment by domaindrivendev** [comment]
Going to close this unless you have more info to provide. One thing that might help if you're using the v2 compat setting, is to apply the `UseInlineDefinitionsForEnums` setting.
