### ISSUE TITLE
OpenApiGenerateDocuments works in VS2019, but not with dotnet build

### ISSUE THREAD

**Issue by ramondeklein** [domaindrivendev/Swashbuckle.AspNetCore#1790]
I have enabled `<OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>` in my CSPROJ file and it works great when I build from Visual Studio 2019. When I build the same project (or solution) using `dotnet build` then it doesn't generate the OpenAPI files. I am using **Swashbuckle.AspNetCore (5.5.1)** and **Microsoft.Extensions.ApiDescription.Server (3.1.7)**.

**Comment by domaindrivendev** [comment]
Please create a minimal project that repro's this issue and push to github so I can pull down and invesitgate

**Comment by blemasle** [comment]
@ramondeklein I didn't investigate further, but setting `<OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>` on the projet did the trick for me.
