### ISSUE TITLE
Default Servers array or concise way to specify it?

### ISSUE THREAD

**Issue by tlmii** [domaindrivendev/Swashbuckle.AspNetCore#1807]
When using [HttpRepl](https://github.com/dotnet/httprepl), it's helpful if the Servers array is populated so that once we find the OpenAPI description, we immediately know for sure what the root address should be.

Unless I'm missing something, it looks like the Servers array is not populated by default when using Swashbuckle, and the standard (only?) way to have the Servers array populated automatically is to do something like this in `ConfigureServces`:
```C#
app.UseSwagger(c =>
{
    c.PreSerializeFilters.Add((swaggerDoc, httpReq) =>
    {
        swaggerDoc.Servers = new List<OpenApiServer> { new OpenApiServer { Url = $"{httpReq.Scheme}://{httpReq.Host.Value}" } };
    });
});
```
It would be nice, from a default experience perspective, if one of the following things happened. Either
1. The above was what happened by default under the hood in Swashbuckle (allowing it to be overridden/changed, obviously), or
2. There was a more concise way (an extension method, perhaps) that could be made part of a default template (like `dotnet ew webapi`).

For the second one (since I assume that's the more likely change to happen), I'm thinking of adding something like this to SwaggerBuilderExtensions:

```C#
public static void AddCurrentServer(this SwaggerOptions swaggerOptions)
{
    swaggerOptions.PreSerializeFilters.Add((swaggerDoc, httpReq) =>
    {
        swaggerDoc.Servers = new List<OpenApiServer> { new OpenApiServer { Url = $"{httpReq.Scheme}://{httpReq.Host.Value}" } };
    });
}

```

which means the default template would only need:
```C#
app.UseSwagger(c => c.AddCurrentServer());
```
Instead of the first code example above.

For a little more background: HttpRepl needs to either have the root url for the API specified in the OpenAPI description, or have it passed to us directly. It's difficult to have the latter happen for default templates since the port number is dynamic, etc. I would imagine other tools would benefit from having the Servers array populated by default (or easily) as well. 

cc @bradygaster since we were discussing this.

**Comment by bradygaster** [comment]
@domaindrivendev - any thoughts on this as a default?

**Comment by domaindrivendev** [comment]
Actually this used to be the default but it caused a lot of issues for API's hosted behind a reverse proxy because the server returned will be the back-end server and not the proxy server that the Swagger consumer (e.g. swagger-ui, HttpRepl etc.) needs to communicate with. By leaving it un-populated, the swagger-ui will assume the server that it's retrieving the OAI document from, which ends up working well for much more cases, including many reverse proxy configurations. Shouldn't the HttpRepl tool be doing the same?

**Comment by domaindrivendev** [comment]
With that said, if it simplifies your templates, I'm OK with adding the proposed extension method.

**Comment by domaindrivendev** [comment]
@tlmii, @bradygaster some new sh*t has come to light here for the old Duder (see #1814), which would allow me to support the default you're requesting out-of-the-box while also providing a clean solution for folks trying to run SB in a reverse proxy environment.

**Comment by tlmii** [comment]
> Shouldn't the HttpRepl tool be doing the same?
We're kind of working in reverse. In a lot of cases (including the default F5 experience in VS) we aren't given the OpenAPI description url - just a "root" url and we try to infer the base url and OpenAPI description url from that. Post-.NET 5 RC1, that "root" url we are given is `https://localhost:XXXXX/swagger`, and since we can't get the base url from the description, we just use the "root" url given to us as the base. Which doesn't work. We recently special cased `/swagger` specifically (https://github.com/dotnet/HttpRepl/pull/386) so that we trim that when setting the base. That works, but we just figured it would be nice if the servers array told us for sure and we didn't have to rely on hacks like that. 

From #1814:
> Instead, populate the servers metadata by default, using HttpRequest.Scheme, HttpRequest.Host

That sounds like option 1 above is more of a possibility than I expected. Sounds great!

**Comment by bradygaster** [comment]
love the collaboration. if you need any support from me on this let me know. as always, I can be your test customer so ping me when you want me to give it a spin.

**Comment by bradygaster** [comment]
@domaindrivendev is this still in "waiting for response" status? If you need anything from us, let @tlmii or I know how we can help push this along. Thanks so much.
