### ISSUE TITLE
Return IServiceCollection from AddSwaggerGen to enable chaining

### ISSUE THREAD

**Issue by alexlukelevy** [domaindrivendev/Swashbuckle.AspNetCore#181]
I wondered whether you would be happy to return the `IServiceCollection` from `SwaggerGenServiceCollectionExtensions.AddSwaggerGen` to allow for the chaining of calls. This would bring it in line with the other [Microsoft DI extensions](https://github.com/aspnet/DependencyInjection/blob/master/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceCollectionServiceExtensions.cs).

Example

```
services
    .AddSwaggerGen()
    .AddSingleton(foo);
```

I have created a [PR](https://github.com/domaindrivendev/Ahoy/pull/180) if you are interested - happy to make further changes if required.

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"
