### ISSUE TITLE
How to obtain the Value of the Example Value in SwaggerUI Responses

### ISSUE THREAD

**Issue by AjuPrince** [domaindrivendev/Swashbuckle.AspNetCore#1811]
![image](https://user-images.githubusercontent.com/16829343/93054104-70bcb300-f69b-11ea-8912-758ecc5ff6ca.png)
How to obtain the Value of the Example Value in SwaggerUI Responses in OpenApiDocument?? ?

**Comment by AjuPrince** [comment]
How to obtain the Exampl E Value in SwaggerUI Responses in OpenApiDocument?

**Comment by domaindrivendev** [comment]
In a Swagger / OpenAPI document, response examples are specified as described by the [specification](https://swagger.io/specification/#responses-object).

By default, Swashbuckle _does not_ populate response examples and so the value you're seeing in the UI is being automatically generated by the UI itself based on the response `schema` that's generated by Swashbuckle and consumed by the Swagger UI.

If you want to set these values programatically on the `OpenApiDocument` type that's used by Swashbuckle, I would suggest wiring up an `IOperationFilter` (see readme) and assigning desired examples for each media type as follows:

```csharp
operation.Responses["200"]
    .Content["application/json"]
        .Example = new OpenApiObject
        {
            [ "message" ] = new OpenApiString("foo"),
            [ "code" ] = new OpenApiInteger(1234)
        };
```
