### ISSUE TITLE
Support using two headers for authentication

### ISSUE THREAD

**Issue by Vaccano** [domaindrivendev/Swashbuckle.AspNetCore#1812]
My company uses two separate headers to authenticate calls.  One for the application and one for the user.  

The first (application) is expected as a normal Access Token passed in as bearer authorization.

The second is a ID_Token that is returned with the access token.  It has a custom header that it must be passed in as.

I would like to suggest that you expand your OAuth 2 support to allow taking both of these values from the AuthCode Authorization flow and passing them in to the call.  (One as bearer and another as a header.)

**Comment by eric-b** [comment]
I think this issue should be posted in [swagger-ui](https://github.com/swagger-api/swagger-ui). The frontend part of Swashbuckle is just a wrapper on vanilla Swagger UI.

**Comment by Vaccano** [comment]
Closing as this is too vague for Swashbuckle to implement as is.  I will create another, more specific issue later.
