### ISSUE TITLE
Incorrectly generated Url

### ISSUE THREAD

**Issue by ziga34** [domaindrivendev/Swashbuckle.AspNetCore#1816]
Hello,

Swashbuckle.AspNetCore version 5.6.0 (issue is not present in 5.5.1)

When API is hosted behind Load Balancer Swagger UI generates incorrect Url.
Instead service url (http://cm-mars-prod:12797/api/ping) it generates url with my IP and port:
![image](https://user-images.githubusercontent.com/30434403/93305695-88b14580-f807-11ea-9590-85ffcd61c720.png)
![image](https://user-images.githubusercontent.com/30434403/93305781-ae3e4f00-f807-11ea-9534-019bf8ef6b1c.png)

In dev environment, which is not behind LB, all is OK:
![image](https://user-images.githubusercontent.com/30434403/93305922-daf26680-f807-11ea-8eba-93653ee240ce.png)

**Comment by NatMarchand** [comment]
Same issue #1814

**Comment by domaindrivendev** [comment]
This is due to logic introduced with `v5.6.0` that is using the `X-Forwarded-For` header. I'm about to release a hotfix (`v5.6.1`) that should resolve this issue. Please track in the referenced duplicate.
