### ISSUE TITLE
Response performance

### ISSUE THREAD

**Issue by ziga34** [domaindrivendev/Swashbuckle.AspNetCore#1818]
Hi,

Version 5.6.1 (no issue with 5.5.1)

JSON response with ~10MB size is not processed neither via Chrome neither via FF browsers - both pops up question "Stop or Wait"

Not related to performance but we host same API on syst, acc and prod envs:
On some envs FF generates view:
![image](https://user-images.githubusercontent.com/30434403/93328090-eeabc600-f823-11ea-9d7a-df0d4df6799f.png)
This one is preffered.

On others:
![image](https://user-images.githubusercontent.com/30434403/93328143-03885980-f824-11ea-8e5e-e624fb2ce86f.png)

**Comment by domaindrivendev** [comment]
There's no way Swashbuckle can be affecting the actual performance of your endpoints. So, I'm guessing this is likely an issue with the updated version of [swagger-ui](https://github.com/swagger-api/swagger-ui) that comes with Swashbuckle `5.6.1`.

To confirm this, you could try using the previous version for the `SwaggerUI` package only. For example, something like the following in your `Startup.cs`:

```
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="5.6.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="5.6.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="5.5.1" />
  </ItemGroup>
```

If the error goes away with this set of packages then that indicates an issue with the latest version of `swagger-ui`, specifically `3.32.5`. With that being the case, I would recommend posting an issue to that repo instead
