### ISSUE TITLE
Provide a way to declare Nullable response types in SwakshBuckle (generating clients in NSwagStudio)

### ISSUE THREAD

**Issue by harshan007** [domaindrivendev/Swashbuckle.AspNetCore#1821]
The details are actually posted in following stackoverflow as well but reposting here due to lack of response, please let me know if you need more information. 
https://stackoverflow.com/questions/63851223/how-to-declare-nullable-response-types-in-swakshbuckle-generating-clients-in-ns

We use SwashBuckle to configure our AspNet Core (Service fabric) project to generate Swagger json and UI. Then we use NSwagStudio to generate typescript and C# clients out of nswag.json template with swagger generated by Swashbuckle.

Recently there has been changes in latest version of NSwagStudio that generates clients with null checks added to response objects. We have existing Controllers returning null responses so the clients have stopped working.

Our sample controller endpoint declaration:

```
[HttpPost]
[ODataRoute]
[Produces("application/json")]
[ProducesResponseType(typeof(IActionResult), Status200OK)]
public Task PostXXX() => ...;
```
Our generated client (before)

```
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.6.2.0 (NJsonSchema v10.1.23.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

var status_ = ((int)response_.StatusCode).ToString();
if (status_ == "200") 
{
      var objectResponse_ = await ReadObjectResponseAsync<IActionResult>(response_, headers_).ConfigureAwait(false);
      return objectResponse_.Object;
}
```
Our generated client (after)

```
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.7.0.0 (NJsonSchema v10.1.24.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

 var status_ = (int)response_.StatusCode;
if (status_ == 200)
{
     var objectResponse_ = await ReadObjectResponseAsync<Void>(response_, headers_).ConfigureAwait(false);
     if (objectResponse_.Object == null)
     {
            throw new Exception("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
     }
     return objectResponse_.Object;
} 

```

The question is how do we tell SwashBuckle to mark that this controller endpoint can return nullable response? In other words, am looking for something similar to what's available in NSwag here in Swashbuckle world: https://github.com/RicoSuter/NSwag/wiki/AspNetCoreOpenApiDocumentGenerator#response-nullability

More details in this github issue is posted to NSwag https://github.com/RicoSuter/NSwag/issues/3011 

Please let me know if you need more information.

**Comment by harshan007** [comment]
Any updates on this please?

**Comment by harshan007** [comment]
@domaindrivendev Can you kindly have a look at this please

**Comment by domaindrivendev** [comment]
I can't really speak for how NSwag interprets an OpenAPI document but in my mind, it really doesn't make sense to mark a _response_ schema as being `nullable`. For a scenario where an endpoint may or may not return content, I would expect it to return a 200 status with content and a 204 status without content. In fact, I believe this is exactly what ASP.NET Core does if you return `Ok(null)`.

So rather than documenting this as a `200` response that's nullable, it should be documented as two separate response codes - 200 with a schema, and 204 without a schema. This can be done as follows:

```csharp
[HttpGet]
[ProducesResponseType(200, Type = typeof(SomeDto))]
[ProducesResponseType(204)]
public IActionResult Get()
```

Now, whether or not NSwag supports this is another question entirely.

**Comment by domaindrivendev** [comment]
Closing as I think the approach I described above should be used rather than specifying nulable response schema's in the OpenAPI document

**Comment by JanEggers** [comment]
for anyone wondering I fixed it like this:

```csharp
public class NullableOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            foreach (var response in operation.Responses)
            {
                if (response.Key != "204")
                {
                    continue;
                }

                if (response.Value.Content == null)
                {
                    continue;
                }

                if (!response.Value.Content.TryGetValue("application/json", out var json))
                {
                    continue;
                }

                context.SchemaRepository.Schemas[json.Schema.Reference.Id].Nullable = true;
            }
        }
    }
```

with that code a spec is generated that nswag can use to accept null

**Comment by IanKemp** [comment]
Sadly @JanEggers' solution no longer seems to work - while the type does end up annotated as `"nullable": true` in `swagger.json`, NSwag still generates the `Response was null which was not expected` exception throwing.
