### ISSUE TITLE
Generation of parameters does not take serializer attributes into account.

### ISSUE THREAD

**Issue by mathis-m** [domaindrivendev/Swashbuckle.AspNetCore#1825]
# Bug Report

Generation of parameters does not take serializer attributes(e.g. JsonIgnore) into account.
Related issue: #1748

Steps to reproduce:
`ValuesController.cs`:
```csharp
private static List<string> _values = new List<string> { "value1", "value2" };

[HttpDelete]
public void Delete([FromQuery] MatchQuery deleteQuery)
{
    var regex = new Regex(deleteQuery.RegexMatch);
    _values.RemoveAll(x => regex.IsMatch(x));
}
``` 
`SampleQuery.cs`:
```csharp
public class MatchQuery
{
    [JsonPropertyName("regex")]
    public string RegexMatch { get; set; }
    [JsonIgnore]
    public string BeginWith { get; set; }
}
``` 
Render:
![image](https://user-images.githubusercontent.com/11584315/93668569-67fa2180-fa8d-11ea-825f-e9c459672a3f.png)

I have analyzed the problem and tracked it down to the [parameter generation code](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/60cd697d36771f76a1d16592228fa231a169285f/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L170-L229).

The problem here is that the schema generator is only used for generation of each property of the Query Class not on the Query Class itself like it would have happened for Body parameters.

@domaindrivendev I would like to create a PR for this. Any ideas on how to solve this.
Why not create a schema for the Query Class via schema generator and then create for each property of the generated schema an OpenApiParameter.

**Comment by domaindrivendev** [comment]
This is actually a dup of #1748. See my [comments in that issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1748#issuecomment-762281795) for a resolution.
