### ISSUE TITLE
Redirect to index.html broken in v5.6.1.

### ISSUE THREAD

**Issue by CoreCompetency** [domaindrivendev/Swashbuckle.AspNetCore#1828]
Updating to v5.6.1 from v5.5.1 exhibits these broken changes:

1. Navigating to /app/swagger redirects to /app/app/swagger/index.html.
2. Navigating to /app/swagger/ redirects to /app/swagger/app/index.html.

Going directly to /app/swagger/index.html still works.

Reverting to v5.5.1 restores functionality, so it appears to be an issue in v5.6.1.

EDIT:  Fixed version numbers.

**Comment by scott-fisher-iii** [comment]
We just updated 3 of our projects to use v5.6.1 (not 2.6.1 as the bug states) and are seeing this behavior too.
We were using v5.6.0, v5.5.1, and v5.1.0 in the projects and didn't notice the problem until updating to v5.6.1 last week.

**Comment by redoz** [comment]
I also see this with the ReDoc package after upgrading to 5.6.1 (was on 5.5.x before).

**Comment by domaindrivendev** [comment]
Fixed by reverting the regression (see https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/31c561dc0381412e817a78ce9bc1ff86ade4e6f8)

Hotfix `v5.6.2` is building as we speak ...
