### ISSUE TITLE
path: 'lib/netstandard2.0/Swashbuckle.AspNetCore.dll' not found

### ISSUE THREAD

**Issue by dharmeshsharma** [domaindrivendev/Swashbuckle.AspNetCore#1830]
1. Upgrade lower version to Latest 5.6.1 with .net core 2.2

2. Publish and getting error 

Error:

  An assembly specified in the application dependencies manifest (CoreApi.deps.json) was not found:

    package: 'Swashbuckle.AspNetCore', version: '4.0.1'

    path: 'lib/netstandard2.0/Swashbuckle.AspNetCore.dll'

this is same as pervious version and i didn't find any solution in previous  issues.

and why its showing Version '4.0.1'

**Comment by domaindrivendev** [comment]
I've no idea what's going on here - it seems very specific to your own setup. I'm going to close for now but if you're still experiencing issues please create a minimal app (i.e. starting from an empty project) that repro's the issue and post to github so I can pull down and troubleshoot.
