### ISSUE TITLE
When multiple routes are present, required parameters are incorrectly added to routes where they are not present.

### ISSUE THREAD

**Issue by frankracis-work** [domaindrivendev/Swashbuckle.AspNetCore#1834]
Here is an example controller:
```
[ApiController]
[Route("/demo")]
public class DemoController : ControllerBase
{
		[HttpGet]
		[Route("abc")]
		[Route("def/{id}")]
		public string Get(int id = 1)
		{
				return "You asked for " + id;
		}
}
```
The relevant generated JSON looks like this:
```
{
    "/demo/abc": {
        "get": {
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "schema": {
                        "type": "integer",
                        "format": "int32",
                        "default": 1
                    }
                }
            ]
        }
    },
    "/demo/def/{id}": {
        "get": {
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "schema": {
                        "type": "integer",
                        "format": "int32",
                        "default": 1
                    }
                }
            ]
        }
    }
}
```
The `abc` operation is showing that the `id` parameter is required in the path, yet there is nowhere in the path for it to be placed.   This doesn't make any logical sense, since it's impossible to fulfill the requirement.   The `abc` operation should not have any parameters.

I know there has been discussion about optional parameters in other tickets.   While the C# method does have an optional parameter, the routes do not, and that's all OpenAPI cares about.  There are two operations:  `abc` has no parameters, `def/{id}` has a single required parameter.

**Comment by domaindrivendev** [comment]
This looks like an upstream issue with ASP.NET Core, specifically it's `ApiExplorer` component. I've created the following issue in that repo:

https://github.com/dotnet/aspnetcore/issues/26234

**Comment by martincostello** [comment]
Closing as external.
