### ISSUE TITLE
swagger.json cannot be loaded behind reverse proxy with rewrite

### ISSUE THREAD

**Issue by kamilzzz** [domaindrivendev/Swashbuckle.AspNetCore#1837]
I have an application deployed behind a reverse proxy (ingress-nginx) with path rewriting. Swagger's index.html is loaded successfully but then it fails to fetch swagger.json.

`https://sample-proxy.com/service-a/` is rewrited to / so the backend app sees / as a base request path.

Now when I request `https://sample-proxy.com/service-a/swagger` the index.html is fetched successfully but there is a problem with swagger.json. When I look at the index.html content I can see that url for the swagger.json is `/swagger/api/swagger.json` but it tries to fetch it using `https://sample-proxy.com/swagger/api/swagger.json` and not `https://sample-proxy.com/service-a/swagger/api/swagger.json`.

I can manually fetch swagger.json using full address `https://sample-proxy.com/service-a/swagger/api/swagger.json`.

ASP.NET Core setup:

```csharp
app.UseForwardedHeaders();
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    var name = GetType().Assembly.GetName().Name;
    c.SwaggerEndpoint($"/swagger/{name}/swagger.json", name);
});
```

`<PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />`

Forwarded headers:
```
[X-Forwarded-For] = <ip-address>
[X-Forwarded-Proto] = https
[X-Forwarded-Host] = sample-proxy.com
[X-Forwarded-Port] = 443
[X-Forwarded-Prefix] = /service-a
```

**Comment by kamilzzz** [comment]
Nevermind, just found out that I should use relative path.
```chsarp
c.SwaggerEndpoint($"{name}/swagger.json", name);
```

**Comment by V4A001** [comment]
I do not understand you add the name of the assembly. For me that did not work at all.
