### ISSUE TITLE
Encoding problem with unicode enum values

### ISSUE THREAD

**Issue by anranruye** [domaindrivendev/Swashbuckle.AspNetCore#1839]
Swashbuckle.AspNetCore Version: 5.6.3
ASP.NET Core Version: 3.1
Serializer: STJ

When document enum values as string, unicode characters are encoded twice.

The sample enum type

```
    public enum CloseOpen
    {
        关 = 0, // Close
        开 = 1  // Open
    }
```

result in a schema in the swagger.json like 

```

"components": {
    "schemas": {

...

      "CloseOpen": {
        "enum": [
          "\\u5173",
          "\\u5F00"
        ],
        "type": "string"
      },

...

    }
  }

```

One '\\' character is redundant.

Swagger UI View:
![image](https://user-images.githubusercontent.com/54608128/94366918-b5b9fe00-010d-11eb-8e1b-ecc445a45ea1.png)

**Comment by anranruye** [comment]
I use a SchemaFilter to rewrite enum schemas, which works well.But I suppose there might be some built-in workaround.

**Comment by domaindrivendev** [comment]
I can't repro this issue - could you please create a minimal app (i.e. starting from an empty project) that repro's and then post to github so I can pull it down and troubleshoot.. Thx

**Comment by domaindrivendev** [comment]
![screenshot](https://user-images.githubusercontent.com/1434343/104924754-caa8ee80-5995-11eb-9348-018163f3d790.png)

**Comment by anranruye** [comment]
@domaindrivendev look at this repo: https://github.com/anranruye/SwaggerEncodingProblem

**Comment by domaindrivendev** [comment]
@anranruye I pulled that down and was able to repro. Then, I upgraded SB to `6.0.5` and the issue was resolved. The latest SB has a newer version of the swagger-ui and so I have to assume something was fixed in that library.
