### ISSUE TITLE
Schemas in output are not sorted (even though methods and method groups are)

### ISSUE THREAD

**Issue by MikeBeaton** [domaindrivendev/Swashbuckle.AspNetCore#1844]
This is a very minor issue, but I thought I would flag it up. Sincere apologies if I've missed a way to configure this which exists already.

I have an API which exposes around 90 referenced schemas. When using Swagger UI it is difficult to find a given schema because these are not sorted by name at the end of the document, but rather they are just listed (presumably) in the order they were encountered when generating the Swagger info.

I think this is not a UI issue as such, because Swagger UI displays the schemas in the order they appear in the JSON, and the order in the JSON is controlled by SwaggerGen. As an additional relevant point, method groups and the method names within the groups _are_ sorted in the JSON.

In case it helps anyone else coming across this, you can correct it with the following (not particularly neat, but functional) filter:

```csharp
app.UseSwagger(c =>
{
    c.PreSerializeFilters.Add((swagger, _) =>
    {
        if (swagger.Components != null && swagger.Components.Schemas != null)
        {
            var replacement = new Dictionary<string, OpenApiSchema>();
            foreach (var kv in swagger.Components.Schemas.OrderBy(p => p.Key))
            {
                replacement.Add(kv.Key, kv.Value);
            }
            swagger.Components.Schemas = replacement;
        }
    });
})
```

I think it would be much more convenient if this was the default behaviour. Since method groups and methods are already sorted, I would imagine that (almost?) any user would prefer a sorted output for schemas too (especially because the sorting of all of them gets directly reflected in the UI).

One easy fix to make this the default behaviour is to inline the above filter code directly into `SwaggerMiddleware.Invoke` just before calling any user preserialize filters (though there might be a more preferred way?). If that's considered worth doing (and as I say, if I'm not being very stupid and missing a pre-existing way to do this quickly, rather than by hand with a filter as above) then I'd be more than happy to provide a PR with that.

**Comment by domaindrivendev** [comment]
Done - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/993fb8540e234a7ee52ef81c4ba2424e800be7e3

**Comment by MikeBeaton** [comment]
> `public IDictionary<string, OpenApiSchema> Schemas { get; private set; } = new SortedDictionary<string, OpenApiSchema>();`

Yeah, okay, that's simpler! 😂 Thank you.
