### ISSUE TITLE
Array types with <example> tag not working

### ISSUE THREAD

**Issue by exile69000** [domaindrivendev/Swashbuckle.AspNetCore#1846]
Hi,

I am using the summary and example tags for the swagger documentation.
I have a problem with the <example> tag, it's not recognized by swagger when I use array :

Example : 

```c#
[DataContract]
    public class HeaderResponse
    {
        /// <summary>
        /// Statut code
        /// </summary>
        ///<example>400</example>
        [DataMember]
        public int StatusCode { get; set; }
        /// <summary>
        /// Title
        /// </summary>
        /// <example>Erreur sur methode1</example>
        [DataMember]
        public string Title { get; set; }
        /// <summary>
        /// List of errors 
        /// </summary>
        ///<example>["entry1", "entry2", "entry3"]</example>
        [DataMember]
        public List<string> ErrorList { get; } = new List<string>();
}
```
On swagger documentation, array is not interpreted :

![image](https://user-images.githubusercontent.com/72208464/94818341-4dfdfe80-03fe-11eb-845b-04c2b4888d3f.png)

I found others solutions by using ISchemaFilter like this :

```c#
 public class SwaggerExcludeFilter : ISchemaFilter
    {
        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            switch (context.Type.Name)
            {
                case "HeaderResponse":
                    foreach (var property in schema.Properties)
                    {
                        if (property.Value.Type == "array")
                        {
                            var array = new OpenApiArray();
                            array.Add(new OpenApiString("item1"));
                            array.Add(new OpenApiString("item2"));
                            array.Add(new OpenApiString("item3"));

                            property.Value.Example = array;
                        }
                    }
                    break;
            }
        }
    }
```

Is there no other way than to use ISchemaFilter to handle <example> tags of type array?

**Comment by domaindrivendev** [comment]
With the above merge, the example is now treated as literal JSON. This means null values and even array values can be provided. Here's some examples:

Boolean
```xml
<example>true</example>
```
String
```xml
<example>"foobar"</example>
```
Number
```xml
<example>123</example>
```
Null
```xml
<example>null</example>
```
Array
```xml
<example>[ 1, 2, 3 ]</example>
```

__NOTE:__ This does however mean that string values MUST include the enclosing double quotes to be correctly interpreted and added to the generated Swagger / OpenAPi document. This is a breakiing change and will be communicated with the 6.0.0 release notes.

In lieue of that release, you can test out this functionlity by downloding the latest 6.0.0 preview from Myget.org

**Comment by nicostubi** [comment]
Hi @domaindrivendev 

Do you have a release date for the v6?

Just to know more or less, if it's worth working on master in the meantime.

BR,
Nicolas

**Comment by manandre** [comment]
Hi @domaindrivendev, I have tested this functionality with latest 6.0.0 preview and I discovered that I had also to include double quote for examples of method parameters and so to escape them using '\&quot;' like this:
```xml
/// <param name="settingId" example="&quot;IncludedProperties&quot;">Identifier of the setting</param>
```
Is it expected? If yes, is there a way to avoid it?

**Comment by manandre** [comment]
I have just found a "nicer" escaping:
```cs
/// <param name="settingId" example='"IncludedProperties"'>Identifier of the setting</param>
```
It could be added to the release note to help people who are not "escaping expert" 😋

**Comment by djfoxer** [comment]
Hi. 
How to add dictinary example values in `<example>` tags?

Something like this:
`<example>{"Key":""}</example>`
for Dictionary<string, byte[]> desn't work 😞

**Comment by TAGC** [comment]
@domaindrivendev Are example tags supported for nested arrays in any way as well? I've updated to version 6.1.2 and I've got the examples showing up for flat arrays but I'm not sure if it's possible to do it for nested arrays as well:

```cs
public class UnitCommissionTableTemplateWriteModel
{
    /// <example>[0,3,6]</example>
    public int[] ScoreThresholds { get; init; }

    /// <example>[0,10,20]</example>
    public int[] UnitSaleThresholds { get; init; }

    /// <example>[[10,20,30],[40,50,60],[70,80,90]</example>
    public decimal[][] Commissions { get; init; }
}
```
