### ISSUE TITLE
Correct replacement of <typeparamref name="T"/>

### ISSUE THREAD

**Issue by logicz** [domaindrivendev/Swashbuckle.AspNetCore#1862]
I have the following definition of a method in generic base controller

```
public class ControllerBase<T, S> : ControllerBase 
        where T : Entity
        where S : IService<T>
{
        /// <summary>
        /// Updates existing <typeparamref name="T"/>
        /// </summary>
        /// <param name="id">Entity id</param>
        /// <param name="value">Entity detailes</param>
        [HttpPut("{id}")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async ValueTask<ActionResult> Put(string id, [FromBody] T value)
        {
        }
}
```

When I look the hint to it, I see T as a link and can navigate to class definition in VS2019

Then I inherit it in the implementation controller, that I use for WebAPI and want swagger replace template type to the  certain implementation type to show it's name in swagger UI.

e.g. I implement controller as

`public class EmployeesController : ControllerBase<Employee, IEmployeeService>{}`

so I want to see
`Updates existing Employee`
in the UI

**Comment by domaindrivendev** [comment]
Swashbuckle only supports a basic subset of the XML comments, specifically the ones described [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments)
