### ISSUE TITLE
HTML Description broken when upgrading from 5.5.1 to 5.6.3

### ISSUE THREAD

**Issue by boris-meerovich-sp** [domaindrivendev/Swashbuckle.AspNetCore#1865]
Hi,
Recently, I've upgraded from version 5.5.1 to 5.6.3.
After the upgrade, my API description (HTML) was broken. Looks like you start to clean some styles.
Please note that the HTML is auto-generated.

Here is an example of the description field:

```
c.SwaggerDoc("v1", new OpenApiInfo {
                    Title = "API DOCUMENTATION", 
                    Version = "v1",
                   Description = "<h1> Test </h1>"+
                                 "<h4 style=\"margin - top: 30px; \">Get Token - Sample Request</h4>"+
                                 "<pre style=\"margin:20px 0; font - family: Monaco, Menlo, Consolas, Courier New, monospace; white - space: pre - wrap; display: block; padding: 9.5px; font - size: 13px; line - height: 1.428571429; color: #333333; word-break: break-all; word-wrap: break-word; background-color: #f5f5f5; border: 1px solid #cccccc; border-radius: 4px;\">“curl -X POST http://site.com -H 'content-type: application/x-www-form-urlencoded' -d 'grant_type=client_credentials&client_id=6779ef20e75817b79602&client_secret=mY5zM5nh7MR8gpj5yG9iIQ%3D%3D'”</pre>"
                  
                });

```
In version 5.5.1 it looks like:
![image](https://user-images.githubusercontent.com/16177113/96107856-967ce800-0ee5-11eb-8405-baa3fe390503.png)

From dev tools you can see all styles:
![image](https://user-images.githubusercontent.com/16177113/96108441-3dfa1a80-0ee6-11eb-8195-8f68a2aa5d75.png)

After updrage to 5.6.3 it looks like:
![image](https://user-images.githubusercontent.com/16177113/96108009-c62bf000-0ee5-11eb-8579-0dd008beb15b.png)

From dev tools looks like there are no more styles:
![image](https://user-images.githubusercontent.com/16177113/96108172-f3789e00-0ee5-11eb-91fd-f620640b3a1d.png)

Please, advise.
Thanks

**Comment by domaindrivendev** [comment]
This looks like a question for the [swagger-ui](https://github.com/swagger-api/swagger-ui) folks rather than Swashbuckle, and so I suggest you create an issue there instead. Here's the related swagger-ui versions in use by Swashbuckle:

Swashbuckle `5.5.1` => swagger-ui `3.26.0`
Swashbuckle `5.6.3` => swagger-ui `3.32.5`

**Comment by boris-meerovich-sp** [comment]
Issue [opened](https://github.com/swagger-api/swagger-ui/issues/6846#issue-788341168)

**Comment by domaindrivendev** [comment]
As Swashbuckle is a downstream project, I think you should frame the issue in terms of swagger-ui rather than Swashbuckle - IMO that will increase the likelihood of it being addressed.

For example provide the generated Swagger JSON and screenshots of the UI instead of SB specific configuration etc
