### ISSUE TITLE
upgrade the swagger-ui3.1.6  to swagger-ui 3.2.23

### ISSUE THREAD

**Issue by rakeshverma0701** [domaindrivendev/Swashbuckle.AspNetCore#1867]
Is there a document which helps how to upgrade the swagger-ui3.1.6 ?
I am new to the swagger
Our project is using the swagger-ui 3.1.6 and needed to be upgraded it to swagger-ui 3.2.23 as the swagger-ui 3.1.6 is vulnerable as per the blackduck?
Could you please help me to upgrade or give some information how I can upgrade.

I see the version defined in the swagger-ui-bundle.js with the below details
 x = {
                PACKAGE_VERSION: "3.1.6",
                GIT_COMMIT: "g786cd47",
                GIT_DIRTY: !0,
                HOSTNAME: "WM-5020",
                BUILD_TIME: "Sat, 19 Aug 2017 01:37:07 GMT"
            },

**Comment by domaindrivendev** [comment]
Swashbuckle ships with an embedded, specific version of the SwaggerUI. So, to upgrade the swagger-ui, you need to upgrade the `Swashbuckle.AspNetCore.SwaggerUI` package. The current version of this package ships with `v3.32.5` of the swagger-ui.
