### ISSUE TITLE
SwaggerSchemaAttribute add AttributeTargets.Enum Attribute Value

### ISSUE THREAD

**Issue by wyp315360007** [domaindrivendev/Swashbuckle.AspNetCore#1869]
SwaggerSchemaAttribute add AttributeTargets.Enum attribute in Swashbuckle.AspNetCore.Annotations packages

[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Property | AttributeTargets.Parameter | **AttributeTargets.Enum**, AllowMultiple = false)]
    public class SwaggerSchemaAttribute : Attribute

**Comment by domaindrivendev** [comment]
See dd5450790652488a2bcaabbb53adca283352f134
