### ISSUE TITLE
Multi-targeting project build failed when including Swashbuckle.AspNetCore 5.6.3 

### ISSUE THREAD

**Issue by liGetStart** [domaindrivendev/Swashbuckle.AspNetCore#1876]
We need our project to support both .netCore2.2 and .netCore 3.1. In .netCore2.2, we include Swashbuckle.AspnetCore 4.0.1 and In .netCore 3.1, we include Swashbuckle.AspnetCore 5.6.3. When building the project, get "**MSB4057 The target "GenerateOpenApiDocuments" does not exist in the project.**"

If we remove multi-targeting, just support .netCore3.1 (ie. Set <TargetFramework>netcoreapp3.1</TargetFramework>), and include Swashbuckle.AspnetCore 5.6.3, then it builds without error.

This error can be reproduced by creating an empty .netCore 3.1 console project with .csproj like below:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.2;netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp2.2'">
    <DefineConstants>NETCORE22</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <DefineConstants>NETCORE31</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.2'">
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="4.5.5" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="6.0.0" />
  </ItemGroup>
</Project>
```

Is there a way to walk around this error?

Thank you

**Comment by eric-b** [comment]
I had same issue. Seems to be a regression in recent versions. There are multiple workarounds listed in https://github.com/domaindrivendev/Swashbuckle.WebApi/issues/1358

For example in csproj:

```
<PropertyGroup>
<OpenApiGeneratorDocumentsOnBuild>false</OpenApiGeneratorDocumentsOnBuild>
</PropertyGroup>
```

**Comment by liGetStart** [comment]
Thanks, @eric-b ! the above solution works. I close this ticket since it is a duplicate of https://github.com/domaindrivendev/Swashbuckle.WebApi/issues/1358

**Comment by thohng** [comment]
> For example in csproj:
> 
> ```
> <PropertyGroup>
> <OpenApiGeneratorDocumentsOnBuild>false</OpenApiGeneratorDocumentsOnBuild>
> </PropertyGroup>
> ```

Experienced that the property name ~OpenApiGeneratorDocumentsOnBuild~ is incorrect, it should be `OpenApiGenerateDocumentsOnBuild` instead.

https://github.com/dotnet/aspnetcore/blob/main/src/Tools/Extensions.ApiDescription.Server/src/build/Microsoft.Extensions.ApiDescription.Server.props#L26

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/9668549/a437eccb-00c1-4758-85b8-d5e07e7791a5)

**Comment by eric-b** [comment]
> Experienced that the property name ~OpenApiGeneratorDocumentsOnBuild~ is incorrect, it should be `OpenApiGenerateDocumentsOnBuild` instead.

You’re right, thanks for clarifying.
