### ISSUE TITLE
Get api with enum parameter don't show up in swagger.json 

### ISSUE THREAD

**Issue by priyankajayaswal1** [domaindrivendev/Swashbuckle.AspNetCore#1879]
Version of swashbuckle: Swashbuckle.AspNetCore" Version="5.5.0
Using .Net Core 3.1

Defined the api as:
```
public async Task<ActionResult<EntityResponse>> GetAsync(
            [FromQuery][Required] Provider provider)
```

where `Provider` is an enum.

```
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Provider
    {
        ProviderDummy,
        ProviderData,
    }
```

The created swagger json look like:
![image](https://user-images.githubusercontent.com/7633366/97112237-26ead200-1709-11eb-8b5c-2eee0adae1ac.png)
I updated provider from string to enum then type declaration for string completely goes away.

Any suggestions how may I get it working?

**Comment by domaindrivendev** [comment]
Please create a "minimal project" (ideally starting from an empty project) that repro's your issue and post it to github. That way, I can pull it down and have a ready made repro to work troubleshoot from. Thanks

**Comment by buvinghausen** [comment]
Richard,

I will try to get up a sample repository for you later on today.  I've noticed that enum parameters ignore the XML docs entirely too. I can change it to a string and everything shows up given the exact same comment. My guess is these two things are related.

**Comment by priyankajayaswal1** [comment]
@domaindrivendev here is the link of a dummy swagger project with enum used in query parameter. https://github.com/priyankajayaswal1/SwaggerDummy
The generated swagger doesn't have any type. This is what I was telling. Let me know if you need any other information here.

**Comment by priyankajayaswal1** [comment]
Reminder

**Comment by priyankajayaswal1** [comment]
@domaindrivendev just to bring this to your notice once again You may remove the "Waiting for author" label.

**Comment by domaindrivendev** [comment]
Dup of #1329. Long story short, I think you can resolve this by using the `UseInlineDefinitionsForEnums` config setting.
