### ISSUE TITLE
Polymorphism support breaks when using dynamic assemblies (OData)

### ISSUE THREAD

**Issue by cfauchere** [domaindrivendev/Swashbuckle.AspNetCore#1881]
Hello, 
I am trying to use Swashbuckle with OData and polymorphism. Things work great until I switch to dynamic assemblies.
I have attached some code sample to repro. 
[Swagger.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/5440231/Swagger.zip)

Without dynamic assembly it works fine. I get what I expect:
![image](https://user-images.githubusercontent.com/12868340/97203399-fc812f00-1771-11eb-82b2-2e9b1513ea0f.png)

However I lose polymorphism when I start using dynamic assembly which happens when using the _Ignore()_ method (check ModelConfiguration.cs)
`// TODO: uncomment to see problems`
`// animal.Ignore(x => x.NotImportant);`

![image](https://user-images.githubusercontent.com/12868340/97203353-ea9f8c00-1771-11eb-9113-732dfdfcdb95.png)

**Comment by domaindrivendev** [comment]
I'm not overly familiar with dynamic assemblies but would point you to the following section in the docs as I think it may be relevent here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#detecting-subtypes

By default, Swashbuckle it will _only_ pick up subtypes for polymorphism that are defined in the same assembly as the base type. So, perhaps you could customize the selection strategy (i.e. `SelectSubTypesUsing(...)`) to account for your "dynamically" generated subtypes.
