### ISSUE TITLE
Failed to generate swagger.json

### ISSUE THREAD

**Issue by bnjmaurer** [domaindrivendev/Swashbuckle.AspNetCore#1883]
Hi,

I am trying to publish a very simple API to Azure following this [doc](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-3.1). When hitting publish I am getting this error: Failed to generate the swagger file. Error dotnet swagger tofile --serializeasv2 --output "C:[...]\bin\Release\netcoreapp3.1\swagger.json" "C:[...]\bin\Release\netcoreapp3.1\myapiname.API.dll" v1. Verify that the Startup.cs file of your application calls AddSwaggerGen from ConfigureServices to generate the Swagger file.

The swagger.json file is indeed missing. I tried to simplify as much as possible and publish again but I get the same error.

It's an ASP .NET Core 3.1 project, Swashbuckle.AspNetCore 5.6.3 is installed.

Startup.cs:

        public void ConfigureServices(IServiceCollection services)
        {            
            services.AddControllers();           
            services.AddSwaggerGen();            
        }
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseSwagger();

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });            
        }

        
My only controller:

[ApiController]    
    public class MyOwnController : ControllerBase
    {        
        [HttpGet]
        [Route("\")]
        public string Get()
        {            
            return "test";
        }
    }

    
Thanks for your help!

**Comment by bizinbarefeet** [comment]
Mw too!

**Comment by seenals** [comment]
Me also facing the same issue. Any resolution for this?

**Comment by bnjmaurer** [comment]
I just recreated my project from scratch and copied the code. Works now for some reason. Only difference is the path of the project is shorter and doesn't contain any space. So I don't know what went wrong.

**Comment by domaindrivendev** [comment]
As the original poster has resolved their issue, I'm going to close this ticket. If anyone else in this thread is still having the same issue, please create a minimal application (i.e. starting from blank project) that repro's the issue and post to github so I can pull it down and troubleshoot.
