### ISSUE TITLE
5.5.1 to >5.6.0 broke setting the type for the Operation class in JsonPatchDocument

### ISSUE THREAD

**Issue by ezuidema** [domaindrivendev/Swashbuckle.AspNetCore#1890]
I tested generating the Swagger file using the CLI, because I couldn't explain the difference in how the `Operation` class for JsonPatchDocument was generated in one project vs another project.

I did some more research and found out it breaks when updating from 5.5.1 to a higher version. This in turn explained the difference between the two API projects.

### What breaks

**The JSON for 5.5.1:**
```
      "Operation": {
        "type": "object",
        "properties": {
          "value": {
            "type": "object",
            "additionalProperties": false,
            "nullable": true
          },
          "path": {
            "type": "string",
            "nullable": true
          },
          "op": {
            "type": "string",
            "nullable": true
          },
          "from": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
```

**And for 5.6.0**
```
"Operation": {
        "type": "object",
        "properties": {
          "value": {
            "nullable": true
          },
          "path": {
            "type": "string",
            "nullable": true
          },
          "op": {
            "type": "string",
            "nullable": true
          },
          "from": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
```

The latter is **missing** the type in for the `value` property. Which in turn is causing the generator for angular to break. From the look at the specs it was not completely clear to me if the `type` is a required property or not!?

### Additional info

The property in the `Operation` class from Microsoft is:

```
[JsonProperty("value")]
public object value { get; set; }
```

https://github.com/aspnet/JsonPatch/blob/master/src/Microsoft.AspNetCore.JsonPatch/Operations/Operation.cs#L13

**Comment by domaindrivendev** [comment]
I would contend that the Swagger / OpenAPI generated by  5.6.0 is a more accurate reflection of your API behavior, and that the angular generator is the tool at fault by not honoring it.

According to the JsonSchema specification, it's perfectly valid to have an "empty" schema - i.e. with the `type` field omitted. See https://json-schema.org/understanding-json-schema/basics.html:

> In JSON Schema, an empty object is a completely valid schema that will accept any valid JSON

The schema that you're seeing for the `value` property is for all intents and purposes an "empty" schema (the `nullable` keyword is a Swagger/OpenAPI specific add-on). Given that the underlying property in the corresponding C# model is of type `object`, which can literally be assigned any value, then the "empty schema" is actually the most appropriate description and `type="object"` is actually incorrect becuse the serialized JSON could in fact be be a number, string, boolean, array etc.

**Comment by domaindrivendev** [comment]
With that said, I think you can easily replicate the old behavior, and thus satisfy your angular generator, with the `MapType` setting:

```csharp
c.MapType<object>(() => new OpenApiSchema { Type = "object", Nullable = true });
```
