### ISSUE TITLE
Caution: Swashbuckle.AspNetCore.SwaggerGen 5.6.3 does not work with Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer v4.2.0!

### ISSUE THREAD

**Issue by JaronrH** [domaindrivendev/Swashbuckle.AspNetCore#1891]
I wanted to save someone else the time and report that Swashbuckle.AspNetCore.SwaggerGen does not work with the newly release Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer v4.2.0!  I haven't been able to track down the exact issue yet but, with v4.2.0, the swagger document does not have any API's defined in it.  Rolling back to 4.1.1 fixes the problem.  (ASP.NET Core 3.1 Web API project.)

**Comment by falvarez1** [comment]
I'm seeing similar issues with using the attribute ApiExplorerSettings with a GroupName.  I'm using the GroupName as a Tag in Swashbuckle, but with this newer update the generated Swagger document doesn't include the endpoints if I have a custom GroupName rather than using the version ID in the GroupName.

Here's what my IOperationFilter looks like for creating the Tag based on the ApiExplorerSettings GroupName

```csharp
public class TagByApiExplorerSettingsOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var apiGroupNames = context.GetControllerAndActionAttributesOfType<ApiExplorerSettingsAttribute>()
                .Where(x => !x.IgnoreApi)
                .Select(x => x.GroupName)
                .ToList();

            if (apiGroupNames.Count == 0)
                return;


            var tags = operation.Tags?.Select(x => x).ToList() ?? new List<OpenApiTag>();

            if (context.ApiDescription.ActionDescriptor is ControllerActionDescriptor controllerDescriptor)
                tags.Remove(tags.Find(p => p.Name == controllerDescriptor.ControllerName));

            foreach (var apiGroupName in apiGroupNames)
                if (!tags.Exists(p => p.Name == apiGroupName))
                    tags.Add(new OpenApiTag { Name = apiGroupName });

            operation.Tags = tags;
        }
    }
```

And the controller would look like this:
```csharp
    [ApiController]
    [ApiExplorerSettings(GroupName = @"This is the custom Tag")]
    [ApiVersion("1.0")]
    [Route("v{api-version:apiVersion}/[controller]")]
    public class WeatherForecastController : ControllerBase
    { ...}
```

**Comment by Abdruggi** [comment]
In older aspnet core version it was necessary to write a custom IOperationFilter like the example above. I newer versions a custom tag selecter did the trick.

```
options.SwaggerGeneratorOptions.TagsSelector = TagsSelectors.ApiExplorerSettingsTagsSelector;
```

After upgrading to .Net 5.0, the tag selector gets never called and therefore swagger doesn't pick up the controllers.

Any ides how to accomplish the same behavior with the newest version?

**Comment by domaindrivendev** [comment]
There seems to be multiple unrelated issues being discussed here. I'm going to close for now and if anyone is still experiencing their issue, please create a new issue with as much detail as possible.
