### ISSUE TITLE
Schema generation on expression-bodied properties causing rapid memory growth, until crash

### ISSUE THREAD

**Issue by dncnkrs** [domaindrivendev/Swashbuckle.AspNetCore#1894]
## Framework details

- ASP.NET Core 5.0.100-rc.2.20479.15
- Swashbuckle.AspNetCore 5.5.1

## Obvious symptoms

After starting the app under IIS Express, swagger opens but is stuck in a loading state. If I attempt to access swagger.json, the request holds indefinitely. Under task manager, I can see IIS Express rapidly consuming all available memory. When I first noticed this, it was on 16 GB!

## Diagnostic method

I isolated Swagger through elimination - if I commented out swagger, I didn't get the bug.

I ran the app in JetBrains Rider, and froze the process after it'd consumed about 2GB of RAM. I noticed an unusually long callstack, which was creating the swagger documentation. [1]

Digging deeper, this method was evaluating the parameters for an API endpoint. 

Following this callstack, I found that the `ApiParameterContext` had 2107268 members, [2] which seemed high. The first 3 were expected properties for the parameter, but the other 2107265 were not. [3] 

## Root cause

The parameter in question is a collection of filter query parameters.

```cs
public class QueryParameters
{
    public List<string> Name { get; set; } = new List<string>();

    // ...

    public Expression<Func<Thing, bool>> Filter => BuildFilter(Expression.Property(typeof(Thing));

    private Expression<Func<Thing, bool>> BuildFilter(ParameterExpression param) 
    {
      // ...
    }
}
```

The program is continuing to traverse the property tree for the `Filter` property. As the expression type is either massive or recursive (or both), this evaluation doesn't terminate within a reasonable timeframe.

The rules for determining a property is a leaf node don't cover this case:
- The property is a collection,
- The property is a simple type,
- The type has no properties.

To fix this issue, there should be a way to prevent evaluation of these properties. 

[1]
![Thread](https://user-images.githubusercontent.com/15052417/98662118-3a1fb380-233f-11eb-95bc-6581d210b9be.jpg)

[2]
![image](https://user-images.githubusercontent.com/15052417/98662588-ea8db780-233f-11eb-9399-a086b87b2eeb.png)

[3]
![ApiParameterDescriptions](https://user-images.githubusercontent.com/15052417/98662769-2b85cc00-2340-11eb-9083-358e4a5c57e2.jpg)

**Comment by dncnkrs** [comment]
A few more comments on solutions:

I can work around this by converting my `Filter` property into a method. This isn't ideal, and I'd rather not be engineering around a development dependency. 

There don't appear to be any simple ways to determine if a property is expression bodied.

Checking `IsReadOnly` isn't an option, because read-only binding models are common.

An option could be `IsBindingAllowed`. Programmers can control this on properties with the `BindNever` attribute. I think this would be a good solution from an API perspective, because such properties probably shouldn't be in Swagger anyway.

**Comment by domaindrivendev** [comment]
Technically, this is an issue with `ApiExplorer`, the metadata component that ships with ASP.NET Core, as opposed to Swashbuckle. It within this component, not Swashbuckle, where the over eager evaluation and rapid memory growth occurs. In fact, it's possible to repro this issue without using Swahbuckle at all. For example, if you add the following controller and invoke the action method, which bypasses Swagger/Swashbuckle and inspects the `ApiExplorer` component directly, you'll observe the same issue.

```csharp
[Route("[controller]")]
public class ApiDescriptionsController : ControllerBase
{
    private readonly IApiDescriptionGroupCollectionProvider _apiDescriptionGroupCollectionProvider;

    public ApiDescriptionsController(IApiDescriptionGroupCollectionProvider apiDescriptionGroupCollectionProvider) =>
        _apiDescriptionGroupCollectionProvider = apiDescriptionGroupCollectionProvider;

    [HttpGet]
    public IActionResult GetApiDescriptions()
    {
        var apiMetadata = _apiDescriptionGroupCollectionProvider.ApiDescriptionGroups.Items
            .SelectMany(group => group.Items)
            .Select(apiDescription =>
            {
                return new
                {
                    apiDescription.HttpMethod,
                    apiDescription.RelativePath,
                    ParameterNames = apiDescription.ParameterDescriptions
                        .Select(parameterDescription => parameterDescription.Name)
                };
            });


        return Ok(apiMetadata);
    }
}
```

**Comment by domaindrivendev** [comment]
Actually, I would have 100% expected the `[BindNever]` attribute to prevent the evaluation and solve this issue until I tried it myself, and was surprised to see the issue still occur. It seems that ASP.NET Core honors that attribute during _actual_ model binding but fails to honor it during API metadata evaluation.

As Swashbuckle relies heavily on `ApiExplorer`, there's no way to fix the issue without an upstream fix in the ASP.NET Core repo. Could you please submit an issue to that repro?

**Comment by dncnkrs** [comment]
Sure thing. Thanks for looking at it.

What is the upstream repo? 

It looks like the `ApiExplorer` is being built from the old `aspnet/Mvc` repo, which is now archived.

Here's the package: https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.ApiExplorer/

And the linked repo: https://github.com/aspnet/Mvc

**Comment by domaindrivendev** [comment]
The latest implementation of `ApiExplorer` can be found in the following repo:
https://github.com/dotnet/aspnetcore

**Comment by domaindrivendev** [comment]
Please link the upstream issue here for tracking. Thx

**Comment by martincostello** [comment]
Closing as external.
