### ISSUE TITLE
JsonConverter applied to an enum property is not respected

### ISSUE THREAD

**Issue by sherlock1982** [domaindrivendev/Swashbuckle.AspNetCore#1897]
I'm using Swashbuckle.AspNetCore and Swashbuckle.AspNetCore.Newtonsoft 5.6.3.
Consider the following example:

    public enum LicenseInfoReceivingStatus
    {
        Success,
        OtherError,
    }
    
    public class LicenseFqdnInfo
    {
        [JsonConverter(typeof(StringEnumConverter))]
        public LicenseInfoReceivingStatus Status { get; set; }
    }

In this case Newtonsoft.Json will serialize this enum as string.
Swashbuckle current behavior:
In schema it will be reported as int enum

Swashbuckle expected behavior:
In schema to be reported as string enum

As a workaround i can apply `[JsonConverter(typeof(StringEnumConverter))]` to a type itself but this is not correct in all cases.
Another workaround will be to `DescribeAllEnumsAsStrings()` and this is also not always correct.

**Comment by Harvzor** [comment]
Looks like this may be a duplicate of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1459?

You're halfway there by installing `Swashbuckle.AspNetCore.Newtonsoft`.

You also need to add this line in your startup:

```
services.AddSwaggerGenNewtonsoftSupport();
```

Check the docs here for more details:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft
