### ISSUE TITLE
Default enum value does not honor NamingStrategy or JsonNamingPolicy when SerializeAsV2

### ISSUE THREAD

**Issue by scharnyw** [domaindrivendev/Swashbuckle.AspNetCore#1900]
### Version
Swashbuckle.AspNetCore 5.6.3 on ASP.NET Core 3.1

### Minimal reproducible sample

- Create a controller action:

      [HttpGet]
      public IActionResult Get([FromQuery] MyEnum value = MyEnum.Value1)
      {
          return Ok();
      }

- The enum declaration:

      [JsonConverter(typeof(StringEnumConverter), typeof(CamelCaseNamingStrategy))]
      public enum MyEnum
      {
          Value1,
          Value2
      }

- Add to `ConfigureServices` in `Startup.cs`:

      services.AddControllers().AddNewtonsoftJson();
      services.AddSwaggerGen(options =>
      {
          options.SwaggerDoc("v1", new OpenApiInfo { Title = "Swagger", Version = "v1" });
          options.UseInlineDefinitionsForEnums();
      });
      services.AddSwaggerGenNewtonsoftSupport();

- And to `Configure` in `Startup.cs`:

      app.UseSwagger(options => options.SerializeAsV2 = true);

`UseInlineDefinitionsForEnums()` is necessary in `ConfigureServices` because enum refs is not supported by the Swagger 2.0 standard, and it is the workaround suggested in #1329 when SerializeAsV2.

This produces the following Swagger JSON:

    {
      "swagger": "2.0",
      "info": {
        "title": "Swagger",
        "version": "v1"
      },
      "paths": {
        "/WeatherForecast": {
          "get": {
            "tags": [
              "WeatherForecast"
            ],
            "parameters": [
              {
                "in": "query",
                "name": "value",
                "type": "string",
                "default": "Value1",
                "enum": [
                  "value1",
                  "value2"
                ]
              }
            ],
            "responses": {
              "200": {
                "description": "Success"
              }
            }
          }
        }
      }
    }

This produces a `Semantic error: Default values must be present in enum` on editor.swagger.io because the default value is formatted in PascalCase as opposed to the enum values which are all formatted in camelCase.

### Expected behavior
The default enum value should honor `JsonConverterAttribute` in the same way as the enum definitions.

**Comment by scharnyw** [comment]
On a sidenote, the same issue is observed when using `System.Text.Json`. The difference being that for STJ, the `JsonNamingPolicy` is configured globally in `ConfigureServices`:

      services.AddControllers().AddJsonOptions(c =>
                      c.JsonSerializerOptions.Converters.Insert(0, new JsonStringEnumConverter(JsonNamingPolicy.CamelCase)));

The issue is again observed that all the enum values are in camelCase, but the default value is in PascalCase.

**Comment by domaindrivendev** [comment]
I believe this was fixed by #1866 

It will be available in the upcoming `v6.0.0` release but in the meantime you can try it out and confirm by pulling down the latest preview build from [myget.org](https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore)
