### ISSUE TITLE
Resolver error - Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Rutix** [domaindrivendev/Swashbuckle.AspNetCore#1905]
When using the options.UseAllOfForInheritance(); and you click around in the UI you will get the error at the top: 
`Resolver error - Cannot read property '0' of undefined`

This has to do with swashbuckle using an older version of the npm package swagger-ui-dist. I will submit a PR to update to the most recent one.

**Comment by domaindrivendev** [comment]
swagger-ui version in SB master now at `v3.39.0`
