### ISSUE TITLE
Authorize content doesn't get update after selected definition changed

### ISSUE THREAD

**Issue by lonverce** [domaindrivendev/Swashbuckle.AspNetCore#1908]
Now I have a WebAPI application which has a lots of SwaggerEndpoint, I configured it as below shown

```csharp
app.UseSwaggerUI(options =>
 {
       foreach ((string key, ApiDocSchema schema) in m_docOptions.Schemas)
       {
             options.SwaggerEndpoint($"/swagger/{key}/swagger.json", schema.Title);
       }
 });
```

Every OpenApiDocument for SwaggerEndpoint has a different OpenApiSecurityScheme ( oauth ).

Now in swagger ui page, I can switch documents by the top-right dropdown list. [ select a definitions ].

And then I can execute OAuth-authorize-flow by the [Authorize] button which would pop up a window.

But I found that the content of The Popup window didn't get updated after I switch another document definition. I had to manually refresh the whole page by Ctrl+F5. It seems like a Bug.

The first time I visit the page with default document definition.

![image](https://user-images.githubusercontent.com/29081995/100302326-0e562c00-2fd5-11eb-9735-57d342717ee7.png)

And then I switch definition and click Authorize again. But those scopes is still same.
![image](https://user-images.githubusercontent.com/29081995/100302524-802e7580-2fd5-11eb-9d20-841eacd9242a.png)

Now I click refresh, and click Authorize again, it is updated.
![image](https://user-images.githubusercontent.com/29081995/100302679-ca175b80-2fd5-11eb-9bc7-55d1346a7f25.png)

**Comment by domaindrivendev** [comment]
I think this is a an issue for the swagger-ui folks as opposed to Swashbuckle itself. Please post it to https://github.com/swagger-api/swagger-ui

**Comment by martincostello** [comment]
Closing as external.
