### ISSUE TITLE
SwaggerUI loops indefinitely eating all RAM when using an ODataController for an entity with a property of type NetTopologySuite.Geometries.Point (NetTopologySuite package)

### ISSUE THREAD

**Issue by fededim** [domaindrivendev/Swashbuckle.AspNetCore#1910]
Hi,

I am attaching a simple Visual Studio 2019, .NET 5 solution which implements an ODataController exposing GET, PATCH and DELETE methods for a simple entity called WeatherForecastWithPoint [according to microsoft guidelines for odata controllers](https://docs.microsoft.com/en-GB/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/create-an-odata-v4-endpoint).

If you do not implement the PUT method (it is commented),  SwaggerUI (e.g. browsing to /swagger/index.html) works fine. If you instead uncomment (row 46-55 of WeatherForecastWithPointsController.cs) the PUT method with this signature 

```
        [HttpPut]
        public async Task<IActionResult> Put([FromODataUri] Int64 key, WeatherForecastWithPoint c)
```

**browsing to SwaggerUI loops indefinitely eating all ram.** 

**After some tests I tracked the problem down to a property defined inside WeatherForecastWithPoint class of type NetTopologySuite.Geometries.Point (serialization of this property is also troublesome, I am using a custom JsonConverter)**. Unluckily this type is recommended by Microsoft for dealing with [spatial data in EF Core](https://docs.microsoft.com/en-GB/ef/core/modeling/spatial).

The problem also happens when using standard controllers (e.g. ControllerBase).

Could you please do a check and suggest a workaround ?

[TestSwaggerNTS.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/5607495/TestSwaggerNTS.zip)

**Comment by domaindrivendev** [comment]
Dup of #1864
