### ISSUE TITLE
rapidoc integration

### ISSUE THREAD

**Issue by MithrilMan** [domaindrivendev/Swashbuckle.AspNetCore#1913]
I see there is an integration for ReDoc.
Googling around I found another promising UI called RapiDoc https://github.com/mrin9/RapiDoc that has a MIT license
Why not having an embedded version of it like for ReDoc? Its UI seems quite good and has a built in "try me" feature.

**Comment by Eneuman** [comment]
If you are using asp.net core you can use this as a quick workaround. Add the following code to your startup.cs:
(You might want to add a check if you running in production or not)

```
      // RapiDoc
      app.MapWhen(x => !x.Request.Path.Value.StartsWith("/rapidoc"), builder =>
      {
        app.Run(async context =>
        {
          context.Response.ContentType = "text/html";

          var sb = new System.Text.StringBuilder();
          sb.AppendLine("<!doctype html>");
          sb.AppendLine("<html>");
          sb.AppendLine("<head>");
          sb.AppendLine("  <meta charset=\"utf-8\">");
          sb.AppendLine("  <script type=\"module\" src=\"https://unpkg.com/rapidoc/dist/rapidoc-min.js\"></script>");
          sb.AppendLine("</head>");
          sb.AppendLine("<body>");
          sb.AppendLine("  <rapi-doc spec-url=\"/swagger/v1/swagger.json\"> </rapi-doc>");
          sb.AppendLine("</body> ");
          sb.AppendLine("</html>");

          await context.Response.WriteAsync(sb.ToString());
        });
      });
```

**Comment by domaindrivendev** [comment]
No plans to add this out-of-the-box but I would encourage creation of this as a separate "add-on" project. Happy to link to it in the docs here if needed.
