### ISSUE TITLE
Reverse Proxy feature not working properly with version 5.6.3

### ISSUE THREAD

**Issue by fabiomaistro** [domaindrivendev/Swashbuckle.AspNetCore#1916]
I'm hosting my ASP .NET Core 3.1 application in IIS under a virtual directory:
![image](https://user-images.githubusercontent.com/21156129/100923743-f2c0b900-34df-11eb-8cdf-581120274f59.png)

This is my swagger configuration (using package version 5.6.3):
```` cs
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Insphire CRM Connector", Version = "v1" });

    // omissis... 
    // security-related code
});

app.UseSwagger();
app.UseSwaggerUI(c =>
 {
    c.SwaggerEndpoint("v1/swagger.json", "Insphire CRM Connector API V1");
});
````

If I browse to `http://< my hosted website>/InsphireCRMConnectorWebApi/swagger/index.html` I can properly see the swagger UI and I can use the `Try it out` without any issue.
However, this same website is put under a proxy being built using [Microsoft.ReverseProxy](https://github.com/microsoft/reverse-proxy). 
When I try to connect to swagger UI from the proxy (the url looks like this: `https://<my proxy url>/swagger/index.html`), this is what I get:
![image](https://user-images.githubusercontent.com/21156129/100924820-67e0be00-34e1-11eb-9762-02b03ffa0ab2.png)

I also tried several other configurations using an older package version (that was not natively supporting proxies): in that case I managed to see the swagger UI but the `try it out` was adding the extra virtual directory that I don't need in the proxy.

Is there something I'm missing in the configuration or is it just not supported?

**Comment by sbebrys** [comment]
Did You tray swagger version 5.5.1? Your problem could be related to #1907

**Comment by fabiomaistro** [comment]
@sbebrys Sorry, but I'm not sure I understand your suggestion. Should I downgrade and handle the redirect headers manually?
If so how? As I said I already tried previously, I managed to make it work for the main UI page, but when I was using the `try it out` it was adding the extra virtual directory...

**Comment by domaindrivendev** [comment]
@fabiomaistro - typically the issues in reverse proxy environments are related to URL construction but based on the configuration you shared I think `https://<my proxy url>/swagger/v1/swagger.json` is the correct URL for the UI to retrieve the Swagger JSON from. However, it is returning an Internal Server Error so perhaps there's some other issue going on in your proxy environment. Could you please navigate directly to the Swagger JSON url (i.e. bypass the UI) and share the error response you're seeing - it might give a little more info into what the problem is.

**Comment by ericbl** [comment]
This is also the issue I had.
I gave more details on #1952

**Comment by domaindrivendev** [comment]
Consolidated into #1953
