### ISSUE TITLE
'[ReadOnly(true)]' attribute ignored when generating json schema validations

### ISSUE THREAD

**Issue by julealgon** [domaindrivendev/Swashbuckle.AspNetCore#1917]
I wanted to mark a few properties in my model as `readonly`, so that they didn't appear when performing a POST, but appeared when receiving responses back (either on the POST response, or a GET call).

However, annotating the properties with `[ReadOnly(true)]` didn't seem to produce any results: I was still getting no `readonly` identifier on the json schema.

Example:
```csharp
    public class Consumer
    {
        [ReadOnly(true)]
        public Guid Id { get; set; }
   
        [ReadOnly(true)]
        public Guid ApiKey { get; set; }

        ...
    }
```

The only way for `readonly` to appear in my case was by making the `set` on both properties `internal` instead of `public`.
```csharp
    public class Consumer
    {
        public Guid Id { get; internal set; }
   
        public Guid ApiKey { get; internal set; }

        ...
    }
```

This was less than ideal as it required further changes in my case, to the EDMModel, to make these properties available again (I'm using OData).

Is the `[ReadOnly]` attribute not supposed to work with Swashbuckle? If that's the case, can support be added for it?

- Swashbuckle.AspNetCore v5.6.3

**Comment by domaindrivendev** [comment]
See #1954
