### ISSUE TITLE
Swashbuckle.AspNetCore.Cli 5.6.0+ failing to run

### ISSUE THREAD

**Issue by overbit** [domaindrivendev/Swashbuckle.AspNetCore#1919]
Since the release of version 5.6.0 I'm not able to run the following command. It works with versions 5.5.0/5.5.1
`dotnet swagger tofile --output swagger.json MyApp.dll v1`

The target dll is an .NET Core 3.1 app running with the latest Swashbuckle.AspNetCore nuget packages.

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.OpenApi, Version=1.2.3.0, Culture=neutral, PublicKeyToken=3f5743946376f042'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.OpenApi, Version=1.2.3.0, Culture=neutral, PublicKeyToken=3f5743946376f042'
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111
```

**Comment by tameyer1** [comment]
I have the same issue. Trying to generate the swagger.json file during Azure DevOps build of a core 3.1 API.
The DevOps task contains:
          dotnet new tool-manifest
          dotnet tool install --version 5.6.3 Swashbuckle.AspNetCore.Cli
          dotnet swagger tofile --output .\MyStuff.Api\bin\Release\netcoreapp3.1\swagger.json .\MyStuff.Api\bin\Release\netcoreapp3.1\MyStuff.Api.dll v1

**Comment by domaindrivendev** [comment]
I believe this _may_ be resolved with latest master. Could you try pulling down the preview Nuget from [myget.org](https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) and let me know if it works?

**Comment by tameyer1** [comment]
My issue is resolved.  The build was pulling in an older version of swashbuckle.  For future reference, here is how I am creating a swagger.json in Azure DevOps and then publishing it to Azure API Manager.

This is a core 3.1 API using swashbuckle 5.6.3.
The YML build contains a cmdline step to create the swagger.json file in the build artifact
          mkdir $(build.artifactstagingdirectory)\swagger
          dotnet new tool-manifest
          dotnet tool install --version 5.6.3 Swashbuckle.AspNetCore.Cli
          dotnet swagger tofile --output $(build.artifactstagingdirectory)\swagger\swagger.json .\MyComponent.API\bin\Release\netcoreapp3.1\MyComponent.Api.dll v1

You should now have a swagger.json file in your build artifact
The Release pipeline uses the DevOps extension stephane-eyskens.apim 
In the Create\Update API step, we set the Definition Location to Build Artifact and the definition artifact step to reference the swagger.json from the build artifact.

One other item to note, the API had references to the identity endpoint to use in the OpenApiOAuthFlows in its startup.
For some reason the build step for the swagger.json generation from the swashbuckle cli run in DevOps did not like 
AuthorizationUrl = new Uri($"{identityUrl}/connect/authorize", UriKind.Absolute)  building an absolute uri and would only except a relative one.
