### ISSUE TITLE
Schema Metadata for C# 9 Records

### ISSUE THREAD

**Issue by RehanSaeed** [domaindrivendev/Swashbuckle.AspNetCore#1920]
## C# 9 Positional Records & XML Comments

We can't use positional records with XML comments because there is no way to provide comments for the properties. There is a Roslyn bug open for this at https://github.com/dotnet/roslyn/issues/44571. This would be the ideal solution.

## C# 9 Records & XML Comments

We can create `init` properties instead and comment them as usual. This works.

```cs
/// <summary>A product.</summary>
public record Product
{
    /// <summary>Gets or sets the unique identifier.</summary>
    public int Id { get; init; }
}
```

## C# 9 Positional Records & Swagger Annotations

Using the `[SwaggerSchema]` attribute in a positional record doesn't seem to work. Please can support for this be added?

```cs
public record Product([SwaggerSchema("The product identifier")] int Id);
```

**Comment by GoodeUser** [comment]
@RehanSaeed You should be able to target the backing property by doing something like this:
```cs
public record Product([property: SwaggerSchema("The product identifier")] int Id);
```
The corresponding documentation for Positional Record Members can be found here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/records#positional-record-members

**Comment by reinux** [comment]
> @RehanSaeed You should be able to target the backing property by doing something like this:
> 
> ```cs
> public record Product([property: SwaggerSchema("The product identifier")] int Id);
> ```
> 
> The corresponding documentation for Positional Record Members can be found here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/records#positional-record-members

This compiles, but it doesn't appear to be picked up by Swashbuckle.

The problem has also been stuck on the C# side since April. https://github.com/dotnet/roslyn/issues/52663

**Comment by bizzzd** [comment]
I believe you can use the "param" tag e.g.

`
///<param name="Pid">The product identifier</param>
public record ActiveSessionsPostInput(Guid Pid, Guid Cid, string SessionId) { }
`

Hope this helps

**Comment by andy-g** [comment]
From my understanding, the issue with XML comments for record properties has been resolved with dotnet 6.

I'm able to compile either of these options:
```c#
/// <summary>A product.</summary>
public record Product
{
    /// <summary>Gets or sets the unique identifier.</summary>
    public int Id { get; init; }
}

/// <summary>A product.</summary>
/// <param name = "Id">Gets or sets the unique identifier.</param>
public record Product2
(
    int Id
);
```

Now that this is supported in a released version of the language, is it possible to support this in Swashbuckle too, to handle both xml comments like this, as well as additional data annotations as outlined in https://github.com/dotnet/AspNetCore.Docs/issues/24858?

There quite a lot of excitement around using records as immutable DTO's etc, which is generally very useful for API requests & responses, but it's quite confusing when the results on the swaggger / redoc output is inconsistent depending on whether a class or record type is used.

Thanks so much.

**Comment by voroninp** [comment]
@GoodeUser , targeting parameter:
```
public record Product([property: Required] string Id);
```
does not work.
 Framework throws, because for positional records validation attributes must be applied to constructor parameters. However, Swashbuckle does not recognize nullability of reference types or attribute applied to constructor parameter.

**Comment by MJLHThomassenHadrian** [comment]
Any updates on this?

**Comment by barruka** [comment]
I believe it's crucial for the developer community to have this issue resolved, especially since the necessary code to fix it is already available. Documentation is incredibly important when building an API, and it's been three years since the release of .NET 5 with record types. In my opinion, prioritizing the resolution and merging of this issue might be more important than adding new features.
