### ISSUE TITLE
Object type Parameters not showing on swagger page

### ISSUE THREAD

**Issue by EllinaExt** [domaindrivendev/Swashbuckle.AspNetCore#1921]
I have the following contract, used as the request body

public class Vehicle 
{
public object id {get;set;}
}
Public class Car:Vehicle
{
public string Name {get;set;}
}

With 5.6.3 version of Swashbuckle.AspNetCore and Swashbuckle.AspNetCore.swagger
Below Json is generating 
"Car": {
        "type": "object",
        "properties": {
          "Name": {
            "type": "string",
            "description": "Model Name",
            "nullable": true
          },
          **"id": {
            "description": "Unique identifier for the Vehicle.",
            "nullable": true
          }**
        },
        "additionalProperties": false,
        "description": "desciption text"
      }
However with 5.3.3 version  of Swashbuckle.AspNetCore and Swashbuckle.AspNetCore.swagger
"id": {
            "type": "object",
            "description": "Unique identifier for the Vehicle.",
            "nullable": true
          }
with which swagger page shows Id property on request body correctly.

Same case with JsonPatchDocument.Value which doesnt show up on swagger page with 5.6.3 version of Swashbuckle.AspNetCore and Swashbuckle.AspNetCore.swagger.

Please let me know, how can I fix this issue ?

**Comment by domaindrivendev** [comment]
I need more information to fully understand this issue. Please create minimal app (i.e. starting from empty project) that repo's the issue and post to github where I can pull it down and troubleshoot?

**Comment by Jabberrwocky** [comment]
I am running into this same issue. Here is what I am finding:

* Our app is running on Swashbuckle.AspNetCore 5.5.1.
* We upgraded from 5.5.1 to 5.6.1 (or greater).
* Our autogenerated swagger.json file used output properties defined as objects like this:

```
"furColor": {
   "type": "object",
  "additionalProperties": false,
  "nullable": true
}
```

Now the same property is outputted to the swagger.json file like this:

```
"furColor": {
  "nullable": true
}
```

In my C# code the FurColor property is defined like this:

`public object FurColor { get; set; }`

Is this a bug?

The main reason I care is that we use openapi-generator (https://openapi-generator.tech/) and this change to the swagger.json output is breaking the openapi-generator generated code.

Thank you for your time.

**Comment by tanukus** [comment]
ASP.NET Core 3.1.11
Swashbuckle.AspNetCore 5.6.3

Similar issue:

` public class SearchFilter
    {
        public FilterOperator Operator { get; set; }
        public string PropertyName { get; set; }
        public object PropertyValue { get; set; }
        public bool IsCaseSensitive { get; set; } = false;
    }`

shows as this in SwaggerUI:
`{
      "operator": "EqualTo",
      "propertyName": "string",
      "isCaseSensitive": true
    }`

**Comment by domaindrivendev** [comment]
This is essentially a dup of #1890. See my comments at the bottom of that issue for an explanation of this behavior (as it's by design) and a workaround if you need to revert to the old behavior

**Comment by domaindrivendev** [comment]
@tanukus your issue looks like something different - could you please create a separate issue for it. With that said, I can't repro with the example you gave ... if you do create an issue, please also create a minimal app (i.e. starting from an empty project) that does repro it and post to github where I can pull down and troubleshoot.

**Comment by Jabberrwocky** [comment]
Thank you for taking the time to respond. Will check out that solution.
