### ISSUE TITLE
Default checked "Send empty value" checkbox for [FromForm] parameter sends null value in a collection

### ISSUE THREAD

**Issue by xhafan** [domaindrivendev/Swashbuckle.AspNetCore#1926]
For this action method:
```C#
        public async Task<string> SetPrivateContent(
            [FromForm] string[] tourUniqueIds
        )
```
it generates by default checked `Send empty value` checkbox:

![image](https://user-images.githubusercontent.com/13038902/101919561-01d3f500-3bcb-11eb-8736-99293bc8716d.png)

When I execute it without any `tourUniqueIds` specified, it sends `null` value in the `tourUniqueId` collection:

![image](https://user-images.githubusercontent.com/13038902/101920085-a81ffa80-3bcb-11eb-8599-22aa2cbe53ed.png)

I have to manually uncheck the checkbox to send empty `tourUniqueIds` collection. I discovered that when I change `FromForm` to `FromQuery`, it all works fine as there is no `Send empty value` checkbox:

![image](https://user-images.githubusercontent.com/13038902/101920673-617ed000-3bcc-11eb-8990-22fe8e7914e0.png)

So I would imagine, if there is no `Send empty value` checkbox for `FromForm` parameters, or if it's unchecked by default, it would be more reasonable behaviour, at least for collections. Our tester using swagger struggled with it, as the collection is optional, and he was justifiably annoyed by having to uncheck it every time to execute it with empty `tourUniqueIds` collection.

**Comment by domaindrivendev** [comment]
I understand your reasoning here - the behavior certainly seems a little unintuitive. However, this is a [swagger-ui](https://github.com/swagger-api/swagger-ui/) (upstream dependency of Swashbuckle) as opposed to an issue with Swashbuckle itself. So, I would suggest you create an issue in that repo instead.

I did a quick browse to see if there's anything there already and found the following - it doesn't quite solve your problem but it's requesting a config option to unset the checkbox by default:

https://github.com/swagger-api/swagger-ui/issues/6505
