### ISSUE TITLE
Schema attribute when using model binding during GET

### ISSUE THREAD

**Issue by theezak** [domaindrivendev/Swashbuckle.AspNetCore#1927]
Using 5.5.1. With a parameter

<code>
 public class ParameterClass
    {
        [FromQuery]
        public string? Id { get; set; }

        [FromQuery]
        [SwaggerSchema(Format = "date")]
        public DateTime? DateFrom { get; set; }
    }
</code>
used like this
<code>
  public async Task<IActionResult> Get([FromQuery] ParameterClass parameters)
</code>
The schema attribute does not appear to get picked up.

**Comment by domaindrivendev** [comment]
Simple fix - c8171a1. Will be available as part of the `6.0;0` release but can you can try it out by pulling down a preview build from [myget.org](https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore)
