### ISSUE TITLE
API Key Not added to header

### ISSUE THREAD

**Issue by JasonDWilson** [domaindrivendev/Swashbuckle.AspNetCore#1930]
This was pretty easy to configure in older versions of Swashbuckle.  I need to have Swagger UI send an API key in X-API-KEY in the header.

I've add the following to **ConfigureServices** --> **AddSwaggerGen**:
```csharp
                    c.AddSecurityDefinition(API_KEY_NAME, new OpenApiSecurityScheme
                    {
                        Description = "Api key needed to access the endpoints. X-Api-Key: My_API_Key",
                        In = ParameterLocation.Header,
                        Name = API_KEY_NAME,
                        Type = SecuritySchemeType.ApiKey
                    });
```
_note: APKY_KEY_NAME is a constant containing X-API-KEY_

The Authorize button shows up in the UI as expected
![image](https://user-images.githubusercontent.com/57236874/102271449-0d822d00-3ee5-11eb-86b7-8245d3242684.png)
![image](https://user-images.githubusercontent.com/57236874/102271474-15da6800-3ee5-11eb-9ed2-171640b25214.png)

But the header doesnt get added to the curl command or the request:
![image](https://user-images.githubusercontent.com/57236874/102271643-46220680-3ee5-11eb-936b-201a6ca4e178.png)

I'm sure I missing something, but since all of the docs really seem to focus on bearer and OAuth authentication, I can't really seem to figure out what it is.

**Comment by q00Dree** [comment]
How did you solve this?

**Comment by dwimbley** [comment]
@q00Dree Had this issue and this is how i solved it, might work for you or someone else who stumbles across this.

The issue was the name here

    options.AddSecurityDefinition("Your Api Key Name Here", new OpenApiSecurityScheme()

Needs to be the same as the Id used in the Security Scheme here (Id = "Your Api Key Name Here"

        var key = new OpenApiSecurityScheme()
        {
            Reference = new OpenApiReference
            {
                Type = ReferenceType.SecurityScheme,
                Id = "Your Api Key Name Here"
            },

The name from security definition and the reference have to match.

Full AddSwaggerGen method call

    builder.Services.AddSwaggerGen(options =>
    {
        options.SwaggerDoc("v1", new OpenApiInfo()
        {
            Title = "My Applications API", Version = "v1"
        });

        options.AddSecurityDefinition("Your Api Key Name Here", new OpenApiSecurityScheme()
        {
            In = ParameterLocation.Header,
            Name = "x-custom-api-key", 
            Type = SecuritySchemeType.ApiKey, 
            Description = "Issued API Key"
        });

        var key = new OpenApiSecurityScheme()
        {
            Reference = new OpenApiReference
            {
                Type = ReferenceType.SecurityScheme,
                Id = "Your Api Key Name Here"
            },
            In = ParameterLocation.Header
        };
        var requirement = new OpenApiSecurityRequirement
        {
            { key, new List<string>(){ } }
        };

        options.AddSecurityRequirement(requirement);

        var xmlFilename = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
        options.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, xmlFilename));

    });
