### ISSUE TITLE
Unable to render this definition.The provided definition does not specify a valid version field

### ISSUE THREAD

**Issue by Parweiz** [domaindrivendev/Swashbuckle.AspNetCore#1931]
- Swashbuckle.AspNetCore: v5.6.3
- Swagger/OpenAPI version: OpenAPI 3.0.1

### The code

```csharp
public void ConfigureServices(IServiceCollection services)
{
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Version = "v1",
                    Title = "ParkShare API",
                    Description = "BackEnd GET/POST/PATCH/DELETE"

                });

                c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
                {
                    Name = "Authorization",
                    Type = SecuritySchemeType.ApiKey,
                    Scheme = "Bearer",
                    BearerFormat = "JWT",
                    In = ParameterLocation.Header,
                    Description = "JWT Authorization header using the Bearer scheme."
                });


                c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "Bearer"
                            }
                        },
                        new string[] {}
                    }
                });

            });
}

 public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
 {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.) specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");

            });

            app.UseHttpsRedirection();
            app.UseRouting();

            // global cors policy
            app.UseCors(x => x
                .AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                );

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
}
```

### The bug / issue

I deployed my .NET Core application to a Windows server and I have now an issue with opening Swagger with the public ip-address. I get this following error:

```
Unable to render this definition
The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).
```

It's quite odd for me, because as you can see in the beginning of the [Swagger.json file](http://18.193.85.66/Test/API/swagger/v1/swagger.json) then OpenAPI version field is already set to a valid version (3.0.1). I can even copy-paste the json-file into [Editor Swagger](https://editor.swagger.io/) and see the endpoints through that site.

Bonus-info: I don't have this kind of problem, when I run it through localhost. The swagger.json from localhost contains still same openapi version (3.0.1)

Many thanks.

**Comment by domaindrivendev** [comment]
@Parweiz where are you seeing the above error? I navigated to your swagger-ui page (here http://18.193.85.66/Test/API/swagger/index.html) and it appears to render correctly for me.

**Comment by Parweiz** [comment]
Hello! I've found already a solution to it! It was just a noob mistake, which is about swagger.json not being able to load the "TEST/API" part. Therefore, it could not run it, but I have found a solution to the problem.

The way i figured it out was just by examine the swagger website and then go to "Network" section. If you then press on "swagger.json", then you would see the request url. The issue was here that the request url was saying "{Servers public id address}/swagger/swagger.json". In other words...It basically had hard time loading "TEST/API" part.

**Comment by lexiscode** [comment]
> Hello! I've found already a solution for it! It was just a noob mistake, which is about swagger.json not being able to load the "TEST/API" part. Therefore, it could not load the page, but I have found a solution to the problem.
> 
> The way i figured it out was just by examine the swagger website and then go to "Network" section. If you then press on "swagger.json", then you would see the request url. The issue was here that the request url was saying "{Servers public id address}/swagger/swagger.json". In other words...It basically had hard time loading "TEST/API" before "swagger/swagger.json".

pls where is the swagger.json file located??

**Comment by GearTheWorld** [comment]
Why sudently without any change of code we get this issue ?

Tje swagger.json is autogenerated so it's not something we can modify.  There must be something else please advise !

**Comment by martincostello** [comment]
My guess, given this is a closed 4 year old issue, is that it's probably https://github.com/swagger-api/swagger-ui/pull/10247, which happens when you use swagger-ui less than 5.19.0 with Microsoft.OpenApi 1.6.23.

See what versions of everything you're using, and whether the combination of Swashbuckle.AspNetCore, swagger-ui and Microsoft.OpenApi create the situation where the OpenAPI document cannot be rendered in swagger-ui.

If it's not that, create a new issue with appropriate levels of detail to be able to investigate the issue (or offer a resolution) without me having to offer educated guesses.
