### ISSUE TITLE
Is possible using static swagger json file?

### ISSUE THREAD

**Issue by TutoDS** [domaindrivendev/Swashbuckle.AspNetCore#1933]
Hi.
Is possible using static swagger json file?
Example, create manually swagger documentation on JSON file and load this file and not the documentation generated by comments

**Comment by domaindrivendev** [comment]
Yes - just add your static file to the following path under your project root `wwwroot/swagger/v1/swagger.json`, and ensure ASP.NET Core's static file middleware is enabled (i.e. `UseStaticFiles()`) in your `Startup.cs`. Then, just wire up the `SwaggerUI` middleware and configure to use the static Swagger endpoint. No need for any of the other Swashbuckle components just `UseSwaggerUI`.

See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/master/test/WebSites/CliExample for an example that does exactly this.
