### ISSUE TITLE
[Feature Request] Add remarks to parameters

### ISSUE THREAD

**Issue by pdevito3** [domaindrivendev/Swashbuckle.AspNetCore#1937]
I'd like to be able to add remarks to complex parameters for my endpoints, but currently, only the summary will show up. Unless I'm missing a particular setting?

**Comment by domaindrivendev** [comment]
Unlike it's `Operation` object, the Swagger/OpenAPI `Parameter` object only supports a _single_ `description` field for entering descriptive text. For simplicity, I'd like to maintain a 1:1 mapping between XML Comments tag and Swagger/OpenAPI field as opposed to combining/formatting multiple tags into the one field. So, your request is not something I plan on adding to SB at this point.

**Comment by 304NotModified** [comment]
I also really like this feature. But luckily, it could be added with a `IParameterFilter` ! (nice!)

See the code posted here:  https://stackoverflow.com/questions/60447302/how-to-show-remarks-in-swagger-documentation/73057660#73057660
