### ISSUE TITLE
 Parameters are misplaced for polymorphic types

### ISSUE THREAD

**Issue by bandolir** [domaindrivendev/Swashbuckle.AspNetCore#1942]
This issue: 
[Parameters are misplaced for polymorphic types](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1544#issue-572648686)
is again exist in v5.6.0

The [GenerateObjectSchema](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/90a6382eab701ced8ed6bf4a2c60ed760fd232db/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs#L314) method does not add object to the AllOf.

**Comment by domaindrivendev** [comment]
On further reflection, the structure generated by Swashbuckle is perfectly valid. That is, the `allOf` field can be combined with other schema fields outside of the `allOf` collection.

With the current design, this approach is easier to implement within the `SchemaGenerator` then what's being suggested by the OP, and given that there's nothing wrong with the structure, I don't believe this to be a valid issue.

**Comment by bandolir** [comment]
In this case all of the client generator tool should support this kind of format which is a bit against the OpenAPI specification. I've just met with one client generator, ng-openapi-gen, which is currently does not support it and never will.

**Comment by domaindrivendev** [comment]
It’s not against the spec at all. The format that’s currently generated IS perfectly valid Swagger/OpenAPI, it passes all official spec validators and works with many tools I’m aware of. Ng-openapi-gen is at fault here and that’s where the issue should be posted.

**Comment by bandolir** [comment]
I'm fine with that. Thanks!

**Comment by jamesfera** [comment]
```
class DocumentFilter : IDocumentFilter
{
    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        foreach (var schemaEntry in swaggerDoc.Components.Schemas)
        {
            var key = schemaEntry.Key;
            var schema = schemaEntry.Value;

            if (schema.AllOf.Any())
            {
                var baseProperties = schema.Properties.ToDictionary(p => p.Key, p => p.Value);

                schema.Properties = null;

                schema.AllOf.Add(new OpenApiSchema()
                {
                    Type = "object",
                    Properties = baseProperties
                });
            }
        }
    }
}
```
