### ISSUE TITLE
Examples do not work if the class is in a project outside of the API.

### ISSUE THREAD

**Issue by tjmcdonough** [domaindrivendev/Swashbuckle.AspNetCore#1944]
Framework: .NET 5
Swashbuckle.AspNetCore Version: 5.6.3
I am decorating the properties of a request class with examples like the below

`/// <summary>`
`/// The name.`
`/// </summary>`
`/// <example>Name</example>`
`[Required]`
`public string? Name { get; set; } = string.Empty;` 

but the XML output is only picking up classes that are within the API project. Am I missing some configuration? I have a separate .Api.Contracts class library where all request objects are stored but the examples do not work. I have included the GenerateDocumentationFile property in the project file.

**Comment by SOHODeveloper** [comment]
Have you included the IncludeXMLComments for the assembly that contains the Api.Contracts

Something like this
        config.IncludeXmlComments(System.IO.Path.Combine(AppContext.BaseDirectory,
          $"{Assembly.GetExecutingAssembly().GetName().Name}.xml"));
        config.IncludeXmlComments(System.IO.Path.Combine(AppContext.BaseDirectory,
          $"{Assembly.GetAssembly(typeof(Api.Models.ResponseSuccessFailure)).GetName().Name}.xml"));

Where Api.Models.ResponseSuccessFailure is a class in the assembly.

**Comment by tjmcdonough** [comment]
Thank you so much. This has fixed my problem.
