### ISSUE TITLE
[Meta] Repo neglect/propose additional contributors

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [domaindrivendev/Swashbuckle.AspNetCore#1946]
I think it would be a good idea to have more people available so that every issue and PR isn't dependent on a single person. It looks like @domaindrivendev hasn't commented on anything since November. There are 40 open PRs, many with pings from the creators and others who want the proposed changes. The last open PR with comments from @domaindrivendev was opened in September and the last merged PR was in November. My work is being held up by my open PR and it looks like there are several others in the same position with other PRs. Would you be willing to give rights to others to review and merge?

**Comment by domaindrivendev** [comment]
Absolutely a reasonable ask and something I've been wanting to support for some time. Like many I'm sure during these times, the last few months have been exceptionally hectic for me (both personally and within the job that actually pays the bills), hence the apparent unresponsiveness around PR's.

To create a "core" team around this project, that is setup for success, requires some ground work in itself. I need to provide dev guidelines, design goals, roadmaps etc. As I'm sure you understand, I don't want every single PR merged, increasing code complexity, just to support some edge cases that fall outside the goals that this project was set out to achieve. Furthermore, I would like to find contributors that understand and appreciate these underlying goals, and that I can trust to maintain the quality and direction of the project.

If you or anyone else has experience or ideas on how efficient ways to recruit and ramp-up a core team, please let me know and I'll be happy to make it happen.

In the meantime, I'll block of time over the next few days to take a somewhat "ruthless" pass over the outstanding PRs

**Comment by Blackbaud-ChristiSchneider** [comment]
Yep, that's super reasonable! I'm glad you're still around and haven't abandoned the project completely as we love using it. I think life has been pretty hectic for everyone lately so definitely understand :P 

Maybe Microsoft would be willing to help since this project is integrated into some of their templates and their documentation. I'm happy to volunteer to be a code reviewer as well but I haven't contributed much so don't know if I'm the best choice. Having a road map would be great because it would help new reviewers determine if PRs should be accepted.

**Comment by martincostello** [comment]
#2778
