### ISSUE TITLE
Swagger.SwaggerMiddleware.GetHostOrNullFromRequest throws exception

### ISSUE THREAD

**Issue by ericbl** [domaindrivendev/Swashbuckle.AspNetCore#1952]
Thanks for providing the Swashbuckle that allow me to generate SwaggerUI in my .NET Core 3.1 WebApis.

Recently, I upgraded from 5.5.1 to 5.6.3 and since then, my app logs the following:

`ERROR Server.Kestrel - Connection id "xxxxxxxxxx", Request id "xxxxxxxxxx:00000001": An unhandled exception was thrown by the application.
System.ArgumentException: Invalid URI: The URI scheme is not valid. (Parameter 'value')
   at System.UriBuilder.set_Scheme(String value)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.GetHostOrNullFromRequest(HttpRequest request)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
`

Looking at the source code of Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware, I see the GetHostOrNullFromRequest() method was introduced in the 5.6.x versions.

The 5.6.3 code is as follow:

```
private string GetHostOrNullFromRequest(HttpRequest request)
        {
            if (!request.Headers.TryGetValue("X-Forwarded-Host", out StringValues forwardedHost))
                return null;

            var hostBuilder = new UriBuilder($"http://{forwardedHost[0]}");

            if (request.Headers.TryGetValue("X-Forwarded-Proto", out StringValues forwardedProto))
                hostBuilder.Scheme = forwardedProto[0];

            if (request.Headers.TryGetValue("X-Forwarded-Port", out StringValues forwardedPort))
                hostBuilder.Port = int.Parse(forwardedPort[0]);

            return hostBuilder.Uri.ToString().Trim('/');
        }
```

This method is quite dangerous since you don't know what forwardedHost[0] could contain!
IMHO, some checks should be added to ensure the data is what you expect here!

In my exemple, the SwaggerUI page is generated correctly when called 'locally' but we have also a tunneling feature that is setting those headers, and thus crashing my app. The Headers are set from that component:
https://github.com/http-party/node-http-proxy/blob/master/lib/http-proxy/passes/web-incoming.js
Looking at our logs, the headers are kind of ok, e.g. 
- x-forwarded-proto: https,https

Anyway, it does not matter much how the headers are set, but before ready them, the GetHostOrNullFromRequest method should be a bit more robust.
For instance, a try/catch over the code returning null in the catch would already avoid the exception.

What do you think here?

**Comment by ericbl** [comment]
I just see the version on master restored the code of 5.5.1, ditching the whole GetHostOrNullFromRequest from 5.6.x!

**Comment by domaindrivendev** [comment]
Consolidated into #1953
