### ISSUE TITLE
Support and Guidance for Reverse Proxy / Virtual Dir Environments

### ISSUE THREAD

**Issue by domaindrivendev** [domaindrivendev/Swashbuckle.AspNetCore#1953]
Over the last couple of Swashbuckle versions, there's been some flux in both the code/implementation and guidance for supporting Swagger pages behind a reverse proxy and/or virtual directory. As a result, there's a number of overlapping open issues, and I'd like to consolidate them here by describing the go forward support and guidance that will be in place as of Swashbuckle `v6.0.0`.

For that version, I'm backing out the recently added logic to automatically honor `X-Forwarded-*` headers, and will update the code to _always_ populate the `servers` metadata using `HttpRequest.Schema`, `HttpRequest.Host` and `HttpRequest.PathBase` from the incoming request. That is, the request to retrieve the Swagger JSON - `http://<your-host>/swagger/v1/swagger.json`). This will result in the swagger-ui having correct server URL's for it's "Try it Out" functionality under all scenarios _except_ for when the app is hosted behind a reverse proxy.

To support the reverse proxy scenario, I will provide guidance in the docs that directs developers to ASP.NET Core's [UseForwardedHeaders middleware](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1). This is MS's recommended approach for apps behind a proxy to ensure that redirects, authentication, link generation, policy evaluation, and client geolocation is all processed correctly. Furthermore, if configured _before_ the Swagger middleware, it will ensure that the _servers_ metadata is also generated correctly.

The list below includes all related open issues and how they can be resolved with the above approach:

- #903, #1392 Lack of guidance around configuring swagger-ui middleware for reverse proxy environments
_To resolve: update docs with guidance, including `UseForwardedHeaders` middleware & "page-relative" URLs for `SwaggerUI` config_

- #1907 Using backend instead of proxy protocol due to fragile logic to honor `X-Forwarded-*` headers
_Resolved: backed out fragile logic in favor of guidance to use ASP.NET Core's `UseForwardedHeaders` middleware_

- #1916, #1952 Internal Server Error due to fragile logic to honor `X-Forwarded-*` headers
_Resolved: backed out fragile logic in favor of guidance to use ASP.NET Core's `UseForwardedHeaders` middleware_
   
- #1338, #1345 Proxy path includes prefix (e.g. `/customername`) but backend doesn't
- _To resolve: update docs with guidance for this scenario. NOTE: `UseForwardedHeaders` middleware doesn't currently handle this.

**Comment by ericbl** [comment]
Hi and thanks for the cleaning!
Do you plan to release a 5.6.4 or 5.7.0 WITHOUT  the "recently added logic to automatically honor X-Forwarded-* headers", before the complete implementation of 6.0 ?
Or do you recommend to use the 5.5.1 instead?

**Comment by domaindrivendev** [comment]
See c35dbc86e37648d12e3726b34d5fdbc059fbe039

**Comment by EricSch** [comment]
Could you clarify what is need to configure Swagger to use it with IIS with or without virtual dir (no proxy), that it works in both environments? Does it mean the same configuration is needed like with a proxy? (using ForwardedHeadersMiddleware)
Sorry for asking but didn't find it for this specific case.
Thank you
