### ISSUE TITLE
Suggestion: Convert Readme.md to separate documentation site

### ISSUE THREAD

**Issue by MNF** [domaindrivendev/Swashbuckle.AspNetCore#1962]
The current https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md file is quite big. 
Will you consider to create a separate documentation site and Convert Readme.md to it?

One of many options is to create docs folder and use  [Read the doc](https://readthedocs.org/)s to host the documentation (e.g. see https://github.com/IdentityServer/IdentityServer4/tree/main/docs)

**Comment by domaindrivendev** [comment]
Dup of #424, and it’s relatively high on the list of priorities
