### ISSUE TITLE
OAuth2 ClientCredentials not working in SwaggerUI

### ISSUE THREAD

**Issue by steelmaker** [domaindrivendev/Swashbuckle.AspNetCore#1964]
Hello guys

I want use ClienCredentials flow for auth in my web api, but not working, server return 400 Bad Request

in Postman works currectly:

```
POST http://localhost:5050/connect/token
Content-Type: application/x-www-form-urlencoded
BODY:
client_id=my_client_id
client_secret=my_client_secret
grant_type=client_credentials
```

I have application with Identity Server 4 like https://github.com/IdentityServer/IdentityServer4/tree/main/samples/Quickstarts/1_ClientCredentials/src/IdentityServer

and I have client asp.net core 3.1 application with Swashbuckle.AspNetCore 5.6.3

```
options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
{
    Name = "Authorization",
    Type = SecuritySchemeType.OAuth2,
    Scheme = "Bearer",
    BearerFormat = "JWT",
    In = ParameterLocation.Header
    Flows = new OpenApiOAuthFlows
    {
        ClientCredentials = new OpenApiOAuthFlow
        {
            TokenUrl = new Uri("http://localhost:5050/connect/token")
        },
    }
});

options.AddSecurityRequirement(new OpenApiSecurityRequirement
{
    {
        new OpenApiSecurityScheme
        {
            Reference = new OpenApiReference
            {
                Type = ReferenceType.SecurityScheme,
                Id = "Bearer"
            },
            Name = "Bearer"
        },
        new string[] {}
    }
});
```

I think I'm not alone
https://stackoverflow.com/questions/63341836/bearer-token-doesnot-pass-on-swagger

**Comment by domaindrivendev** [comment]
This functionality def works do must be something in your setup. Please create a minimal app (i.e. start from empty project) that repro's the issue and post to github so I can pull down and troubleshoot.

**Comment by domaindrivendev** [comment]
Hold off on that - at a quick glance you're Swagger OAuth config looks wrong to me - let me try something and get back to you

**Comment by steelmaker** [comment]
same project: https://github.com/ionepaul/dotnet-api-with-identity-server

I resolved by add cors configuration on IdentityServer side

```
app.UseCors(b =>
{
  b.AllowAnyOrigin()
   .AllowAnyMethod()
   .AllowAnyHeader();
});
```

**Comment by domaindrivendev** [comment]
can the issue be closed then?

**Comment by steelmaker** [comment]
yeap, thx :)
