### ISSUE TITLE
Swagger Schema Descriptions not displaying in JSON

### ISSUE THREAD

**Issue by lynncassidy** [domaindrivendev/Swashbuckle.AspNetCore#1965]
Swashbuckle.AspNetCore Version=5.6.3 
Visual Studio 2019 Community Edition

I'm attempting to add a schema description for these API properties. I've been following along with https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments which states: "NOTE: You can also provide Swagger Schema descriptions by annotating your API models and their properties with summary tags."

namespace Names.Application.Dto
{
    public class SearchCriteriaDto
    {
        /// <description>
        /// A new description
        /// </description>
        public string FullName { get; set; }
        public string FirstName { get; set; }
    }
}

As you can see the description does not display in the JSON file when generated: 
![image](https://user-images.githubusercontent.com/37216450/105169160-0b7a4200-5b13-11eb-88bd-025808749dcf.png)

Am I missing something or should I be using a different Swashbuckle version? Thanks

**Comment by domaindrivendev** [comment]
This functionality def works do must be something in your setup. Please create a minimal app (i.e. start from empty project) that repro's the issue and post to github so I can pull down and troubleshoot.

I assume you're enabling XML comments via the `IncludeXmlComments` setting?

**Comment by lynncassidy** [comment]
Hi thanks for your reply. We did solve this one but it was due to an XML file not generating so comments and descriptions did not appear. Once both XML files generated this worked fine. 

Thanks
