### ISSUE TITLE
[SwaggerSchema("The date it was created", Format = "date")] in README not working

### ISSUE THREAD

**Issue by arisliang** [domaindrivendev/Swashbuckle.AspNetCore#1966]
I've added `[SwaggerSchema("The date it was created", Format = "date")]` to a property, and enabled the annotation `c.EnableAnnotations();`. But it doesn't seem to work. When applyin a schema filter to the class level, I don't get the enriched information from SwaggerSchema attribute.

v5.6.3

**Comment by domaindrivendev** [comment]
Please create a minimal app (i.e. starting from an empty project) that repro's the issue and post to github so I can pull down and troubleshoot

**Comment by arisliang** [comment]
Created a minimal example at https://github.com/arisliang/SwaggerSchemaExample, SwaggerSchema attribute is at https://github.com/arisliang/SwaggerSchemaExample/blob/9ffc049125813ae9b3e63ab8a7f2b419c7febae0/SwaggerSchemaExample/WeatherForecastGet.cs#L15

**Comment by arisliang** [comment]
I'm able to get needed information from SchemaFilterContext now.

**Comment by sebasijan** [comment]
Hey @arisliang did you ever get this attribute working? I specified "date" format but it appears as `2021-05-26T13:38:40.441Z`
