### ISSUE TITLE
Swagger is unable to create swagger.json if multiple (nested) classes have same name.

### ISSUE THREAD

**Issue by terryaney** [domaindrivendev/Swashbuckle.AspNetCore#1972]
Swashbuckle.AspNetCore 5.6.3
Swashbuckle.AspNetCore.Annotations 5.6.3

In my real code, I'm using a MediatR pattern to build my end points and therefore am creating nested return types and often they are same name.  When this happens, Swagger displays:

> Failed to load API definition.

Here is a sample file with two controllers/endpoints.  I'm not using MediatR but the same problem exists.  If I rename one of the sub `CalcEngine` classes to `CalcEngine2` everything works fine.

```
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System;

namespace Endpoints.CalcEngines
{
	[ApiController]
	public class List : ControllerBase
	{
		[HttpGet( "/calc-engines" )]
		[SwaggerOperation(
			Summary = "List all CalcEngines",
			Description = "List all CalcEngines",
			OperationId = "CalcEngines.List",
			Tags = new[] { "CalcEngines" } )
		]
		public CalcEngine[] Execute() =>
			new[]
			{
				new CalcEngine { Name = "CE1.xlsm", DateUploaded = DateTime.Now.AddDays( -2 ) },
				new CalcEngine { Name = "CE2.xlsm", DateUploaded = DateTime.Now.AddDays( -1 ) }
			};


		public record CalcEngine
		{
			public string Name { get; init; }
			public DateTime DateUploaded { get; init; }
		}
	}

	[ApiController]
	public class Get : ControllerBase
	{
		[HttpGet( "/calc-engines/{name}" )]
		[SwaggerOperation(
			Summary = "Get CE Info",
			Description = "Get all CE info",
			OperationId = "CalcEngines.Get",
			Tags = new[] { "CalcEngines" } )
		]
		public CalcEngine[] Execute( string name, bool? allVersions ) =>
			new[]
			{
				new CalcEngine { Name = $"{name}.xlsm", Versions = new [] { new CalcEngine.VersionInfo { DateUploaded = DateTime.Now.AddDays( -2 ), Version = "1" } } },
				new CalcEngine { Name = $"{name}_Test.xlsm", Versions = new[] { new CalcEngine.VersionInfo { DateUploaded = DateTime.Now.AddDays( -1 ), Version = "2" } } }
			};

		public record CalcEngine
		{
			public string Name { get; init; }
			public VersionInfo[] Versions { get; init; }

			public record VersionInfo
			{
				public string Version { get; init; }
				public DateTime DateUploaded { get; init; }
			}
		}
	}
}
```

Is there a way to get around this or am I required to use different class names even though `Get.CalcEngine` and `List.CalcEngine` are different?

**Comment by domaindrivendev** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-schema-ids

**Comment by terryaney** [comment]
Thanks.  I will use this.

**Comment by terryaney** [comment]
@domaindrivendev  Before I use this code/pattern to fix things.  How come I can not see/find the exception?  I don't see anything in my Output-Debug.  I have Exception Settings to stop on all Common Language Exception and it doesn't stop.  I wish I could see 

> Swashbuckle will raise an exception due to "Conflicting schemaIds"

Any idea why I don't see any trace of this exception?

**Comment by domaindrivendev** [comment]
@terryaney to view exceptions, I typically enable ASP.NET Core's developer exception page (i.e. `app.UseDeveloperExceptionPage()`) and then navigate to the Swagger/OpenAPI endpoint that's returning the error:

![screenshot](https://user-images.githubusercontent.com/1434343/107037814-88641780-67b3-11eb-9f6e-bcb241b68376.png)
