### ISSUE TITLE
ISchemaFilter.Apply not called for reference schemas

### ISSUE THREAD

**Issue by maurei** [domaindrivendev/Swashbuckle.AspNetCore#1974]
I'm writing a Swashbuckle integration for [JsonApiDotnetCore](www.jsonapi.net) (JADNC). Using a `IDocumentFilter` I iterate through `OpenApiDocument.Components.Schema` and manipulate every root schema as well as every nested property schema in `OpenApiDocument.Properties` according to the needs of a developer that uses JADNC. 

In order to reliably match every property schema to the actual model property it represents, I want to perform lookup of the `MemberInfo` associated with the property schema. These `MemberInfo`s are not exposed in the document filter by default, so I inject them in my document filter using a custom cache in which these `MemberInfo`s are stored during the execution of my `ISchemaFilter`. The mechanism is as follows:

```c#
public class JsonApiSchemaFilter : ISchemaFilter
{
    private readonly ISchemaMetadataCache _schemaMetadataCache;

    public JsonApiSchemaFilter(ISchemaMetadataCache schemaMetadataCache)
    {
        _schemaMetadataCache = schemaMetadataCache;
    }

    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        // SchemaFilterContext.MemberInfo associated to the schema is what I need in my DocumentFilter
        _schemaMetadataCache.Set(schema, context)
    }
}

public class JsonApiDocumentFilter : IDocumentFilter
{
    private readonly ISchemaMetadataCache _schemaMetadataCache;

    public JsonApiDocumentFilter(ISchemaMetadataCache schemaMetadataCache)
    {
        _schemaMetadataCache = schemaMetadataCache;
    }

    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        foreach (var (rootKey, rootSchema) in swaggerDoc.Components.Schemas)
        {
            foreach (var (propertyKey, propertySchema) in rootSchema)
            {
                SchemaFilterContext metadata = _schemaMetadataCache.Get(propertySchema);
                DoAllSortsOfCustomStuff(rootSchema, key, propertySchema, metadata.MemberInfo) 
            }
        }
    }
}
```

The issue I have is that schemas for which `OpenApiSchema.Reference` is non-null, the `ISchemaFilter.Apply` method is never called. [This snippit is responsible for this](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/fd0b60d37a6a9e36beff0ff802896db92d381d72/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs#L47). Can this be changed so that reference schemas are also exposed in this hook? By not calling this hook for these reference schemas, valuable metadata that I need and that normally would be exposed in `SchemaFilterContext` is  inaccessible.

Let me make a case why I need this. In JADNC annotating fields with `ResourceFieldAttribute`s (eg `[HasOne] `or `[Attr]`) determines if a relationship or property is exposed to the client.

```c#
public class Article : Identifiable
{
    [HasOne]
    public User Author { get; set; }

    public User Approver { get; set; }
}

public class User : Identifiable
{
    [Attr]
    public string Name { get; set; }

    public string Password { get; set; }
}
```
So in this case, we have these two property/reference schemas and their associated model property:
- `OpenApiDocument.Components.Schemas["Article"]["author"]` -> `Article.Author`
- `OpenApiDocument.Components.Schemas["Article"]["approver"]`  -> `Article.Approver`

and I want to remove the latter schema because its associated property is not exposed.

For this I want to perform a look-up of the `MemberInfo`s associated to these schemas to check if the JADNC attributes are present, but thats not possible because `ISchemaFilter.Apply` was never called with these two reference schemas, (unlike `["User"]["Name"]` and `["User"]["Password"]` for which the schema filters ***are*** called), and so there was no way getting this data off `SchemaFilterContext.MemberInfo`.

I can only retrieve the metadata of the `OpenApiDocument` instance to which these two reference schemas are pointing with this mechanism, because for this schema the schema filter is called, but of course in execution no member info metadata I need is available.

Note that I don't want to rely on comparing the serialized property keys with names of my model properties [as described in your SO answer here](https://stackoverflow.com/a/48454933/4441216) because I don't think it is very robust: it breaks when a developer uses a custom `NamingStrategy`. The only reliable work-around I could come up with is injecting `ISerializerDataContractResolver` in the document filter (which non-trivial because it introduces a circular dependency), confidently reproducing the serialization process by getting a `DataContract.ObjectProperties` for the type I'm trying to do the matching, and comparing its entries with the entries in `OpenApiDocument.Components.Schemas["Article"]`. But I believe I shouldn't have to rely on Swashbuckle's internal serializer for my goal.

**Comment by domaindrivendev** [comment]
What changes are you making to the schema's - is there any reason why you don't just do this with the schema filter instead of the document filter?

**Comment by domaindrivendev** [comment]
I took a quick look at your repo and see you're implementing custom input and output formatters. Does this mean your library provides it's own serialization independently of Newtonsoft/STJ? If so, then you should be implementing and injecting a custom implementation of `ISerializerDataContractResolver` as that's the abstraction that encapsulates serializer-specific behavior. For example, take a look at the Newtonsoft specific implementation here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v5.6.3/src/Swashbuckle.AspNetCore.Newtonsoft/SchemaGenerator/NewtonsoftDataContractResolver.cs

**Comment by maurei** [comment]
Thanks a lot for your quick reply!

We use Newtonsoft serializer but do a non-trivial transformation before that: we turn eg `Article` from the example above  into a JSON payload that looks like [this example](https://www.jsonapi.net/request-examples/index.html#get-by-id) (see [JSON:API specification](www.jsonapi.org)). This transformation  cannot be done by Newtonsoft alone, so we first transform a model into a [ResourceObject](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/JsonApiDotNetCore/Serialization/Objects/ResourceObject.cs/#L6) which is then serialized by Newtonsoft.

I was hoping to just rely on `NewtonsoftDataContractResolver` because it does a perfect job for a large majority of the types. Just for our own models we'd need to remove some entries in data contract and rename some others, but the Newtonsoft implementation is not extensible so we'd end up copy-pasting most of the code to achieve this (or relying on some reflective black magic which I would also prefer to avoid).

But bottom line: I agree that it would be better to have correct `DataContract`s from the start than changing everything after it has been generated, probably even if end up having to copy source code. But this is independent of what I believe is an inconsistency:  `IFilterSchema.Apply` only being fired for a subset of `OpenApiSchema`s, which is the set where `OpenApiSchema.Reference` is null. As a result I will still run into problems that cannot be resolved by implementing a custom `ISerializerDataContractResolver`.

For example, we need to complement the `OpenApiSchema.Description` of a reference schema to display the [includability](https://www.jsonapi.net/usage/resources/relationships.html#includibility) of a relationship (in JADNC the ability of side-loading a specific relationship can be switched on and off).

```c#
public class TodoItem : Identifiable
{
    [HasOne(CanInclude: false)]
    public Person Owner { get; set; }
}
```

For this I would still need to retrieve the `MemberInfo` associated to the reference schema at `OpenApiDocument.Components.Schemas["TodoItem"]["owner"]`, which is currently not possible because it is not exposed to the schema filter.

> is there any reason why you don't just do this with the schema filter instead of the document filter?

Given that `SchemaFilterContext.SchemaRepository.Schemas` is the same object reference as `OpenApiDocument.Components.Schemas`, probably all of this could be achieved in just the schema filter alone, but I think this is a internal detail one shouldn't rely on. Also I think it is a lot more predictable to loop through the schemas in the component myself than having to figure out on and depend on the order of execution of schema filters.

**Comment by domaindrivendev** [comment]
Applying a flter to an `OpenApiSchema` instance with a non-null `Reference` value is non-sensical  because such an instance isn't actually a schema - it's a _reference_ to a schema. That is, it represents a [JSON Reference](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3) and assigning any values other than the `Reference` is meaningless, as stated in the spec:

> Any members other than "$ref" in a JSON Reference object SHALL be
   ignored.

What is possible within the bounds of the spec, is to create an _actual_ schema that "extends" the referenced schema with additional metadata such as `description` etc, as per the following example adapted from [a post on SO](https://stackoverflow.com/questions/33565090/json-schema-property-description-and-ref-usage):

```json
{
    "allOf": [{ "$ref": "#/components/schemas/Article" }],
    "description": "Some description"
}
```

By default, Swashbuckle does not apply this structure to schema's derived from a `MemberInfo`, but you can enable it with the `UseAllOfToExtendReferenceSchemas` setting. In this case, generated property schemas will be an _actual_ schema (as opposed to a _reference_ to a schema) and will therefore be available for modification within a filter.

This setting may help with your filter-based approach but I strongly believe filters are the wrong approach for your use case and you should be focussing on a custom implementation of `ISerializerDataContractResolver`. Re your concern about duplicating code here, this can be easily addressed in a very clean way by using a simple "decorator" pattern. I'll post an example shortly.

**Comment by domaindrivendev** [comment]
```csharp
// Startup.cs
services.AddSwaggerGen(c =>
{
    ...
});
services.Replace(ServiceDescriptor.Transient<ISerializerDataContractResolver, JsonApiDataContractResolver>());
```
```csharp

// JsonApiDataContractResolver.cs
public class JsonApiDataContractResolver : ISerializerDataContractResolver
{
    private readonly NewtonsoftDataContractResolver _newtonsoftDataContractResolver;

    public JsonApiDataContractResolver(SchemaGeneratorOptions generatorOptions, IOptions<MvcNewtonsoftJsonOptions> newtonsoftJsonOptions)
    {
        _newtonsoftDataContractResolver = new NewtonsoftDataContractResolver(generatorOptions, newtonsoftJsonOptions.Value.SerializerSettings);
    }

    public DataContract GetDataContractForType(Type type)
    {
        var newtonsoftDataContract = _newtonsoftDataContractResolver.GetDataContractForType(type);

        if (newtonsoftDataContract.DataType == DataType.Object)
        {
            return DataContract.ForObject(
                underlyingType: newtonsoftDataContract.UnderlyingType,
                properties: newtonsoftDataContract.ObjectProperties
                    .Where(p => // your custom predicate based on p.MemberInfo),
                extensionDataType: newtonsoftDataContract.ObjectExtensionDataType,
                typeNameProperty: newtonsoftDataContract.ObjectTypeNameProperty,
                typeNameValue: newtonsoftDataContract.ObjectTypeNameValue);
        }

        return newtonsoftDataContract;
    }
}
```

**Comment by maurei** [comment]
Thanks for the thorough response! Your advise on to use `allOf` solves my problem. Also, your code sample is along the lines of what I had come up with. There is a bit more duplication involved though than in your example because some properties need to be renamed ([to support custom names](https://www.jsonapi.net/usage/resources/attributes.html#name), and there are no public setters so I need to reinstantiate `DataProperty`s, but it's manageable! Thanks a lot for your time.
