### ISSUE TITLE
How to add a header to the authorization request

### ISSUE THREAD

**Issue by ShaunHavelaar91** [domaindrivendev/Swashbuckle.AspNetCore#1975]
How do you include custom headers when requesting an access token from swagger.

I need to include a custom header` X-ACCOUNT-ID`, it would be great to add the value of the header as you can with the client_id within the authorization requests but for now, I wouldn't mind adding it from config.

**Comment by domaindrivendev** [comment]
This sounds like more of a question for the [swagger-ui folks](https://github.com/swagger-api/swagger-ui) rather than Swashbuckle. Please direct your question to that repo instead.
