### ISSUE TITLE
Generic base classes

### ISSUE THREAD

**Issue by qsdfplkj** [domaindrivendev/Swashbuckle.AspNetCore#1981]
When I have 

    public class Base
    {
        public int BaseProperty { get; set; }
    }

    public class Generic<T> : Base
    {
        public T GenericProperty { get; set; }
    }

    public class Final : Generic<int>
    {
        public int FinalProperty { get; set; }
    }

The generated swagger.json doesn't have a reference to Base.  After enabling 'UseAllOfForInheritance' it still doesn't work? When I takeout either the Base class or Generic in both cases it works fine. But the combined case as presented above doesn't work.

Now when I use NSwag studio to generate a client the Final class no longer derives from the base class.

**Comment by MikeFH** [comment]
I would like to work on that if it's ok.
