### ISSUE TITLE
Nested arrays generating incorrect nested generics

### ISSUE THREAD

**Issue by SartriX** [domaindrivendev/Swashbuckle.AspNetCore#1986]
using Nswag.ApiDescriptionClient 13.10.1 on .Net Core 5.0.2
I'm having several issues generating a client from the public openApi: https://bag.basisregistraties.overheid.nl/api/v1
One issue is: Within it are several polygon objects which contain nested arrays, and these nested arrays are causing compile errors.

This is one of the schema objects defined in the yml spec:
```
    Polygon:
      description: "GeoJSON polygon geometry"
      type: "object"
      allOf:
      - $ref: "#/components/schemas/Geometry"
      - required:
        - "coordinates"
        type: "object"
        properties:
          coordinates:
            type: "array"
            items:
              type: "array"
              items:
                $ref: "#/components/schemas/Point2D"
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.1.6"
```
resulting in:
```
        [Newtonsoft.Json.JsonProperty("coordinates", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<System.Collections.Generic.ICollection<Point2D>> Coordinates { get; set; } = new System.Collections.ObjectModel.Collection<System.Collections.ObjectModel.Collection<Point2D>>();
```
Interface<Interface> = Concrete<Concrete> does not compile. It would need to be Interface<Interface> = Concrete<Interface>

The correct generation would be:
```
public System.Collections.Generic.ICollection<System.Collections.Generic.ICollection<Point2D>> Coordinates { get; set; } = new System.Collections.ObjectModel.Collection<System.Collections.Generic.ICollection<Point2D>>();
```

**Comment by domaindrivendev** [comment]
I cannot speak for NSwag or the errors it produces as it's a completely separate project. If there's something in the Swagger/OpenAPI JSON, which is generated by Swashbuckle, that looks incorrect to you please start by running it through a validator (e.g. https://editor.swagger.io/). If it's showing errors then please post them here and I'd be happy to investigate further.

**Comment by SartriX** [comment]
Terribly sorry. Clicked a ref link on their issuetracker and didn't notice it took me here. My bad!
