### ISSUE TITLE
Missing generated class or incorrect reference

### ISSUE THREAD

**Issue by SartriX** [domaindrivendev/Swashbuckle.AspNetCore#1987]
using Nswag.ApiDescriptionClient 13.10.1 on .Net Core 5.0.2
I'm having several issues generating a client from the public openApi: https://bag.basisregistraties.overheid.nl/api/v1
One issue is:

The generated c# contains quite a few references to one schema class which is not included in the generation.
As example, the following yml:
```
    Intersects:
      type: "object"
      description: "'overlapt' en 'raakt' vallen hieronder"
      properties:
        intersects:
          $ref: "#/components/schemas/GeoJSONGeometry"
```
generates
```
        [Newtonsoft.Json.JsonProperty("geometrie", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public Intersects1 Geometrie { get; set; } = new Intersects1();
```
which results in a compile error as the class Intersects1 is nowhere to be found.

For completeness, the entire yml (which is public domain) and .cs are attached: [bag.v1.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/5917516/bag.v1.zip)

**Comment by domaindrivendev** [comment]
I cannot speak for NSwag or the errors it produces as it's a completely separate project. If there's something in the Swagger/OpenAPI JSON, which is generated by Swashbuckle, that looks incorrect to you please start by running it through a validator (e.g. https://editor.swagger.io/). If it's showing errors then please post them here and I'd be happy to investigate further.

**Comment by SartriX** [comment]
Terribly sorry. Clicked a ref link on their issuetracker and didn't notice it took me here. My bad!
