### ISSUE TITLE
Swagger doesn't describe request  DTOs when they are from diffrent project/assembly

### ISSUE THREAD

**Issue by flamaniac** [domaindrivendev/Swashbuckle.AspNetCore#1989]
1. DTO for the request is in the different project then WebApi project ( main project with controllers, Startup class, and Swagger setup)
2. Swagger is not showing request properties if DTO class is different project.  

-  When I move request dto to the main project Swagger is showing request DTO properties in the "example" section in the SwaggerUI. Request model in only described at the bottom of the page in Schema section
![MissingrequestBody1](https://user-images.githubusercontent.com/6348462/106750394-14e1cf00-6628-11eb-9ec8-3c1c4dbd9ed3.png)
![MissingrequestBody2](https://user-images.githubusercontent.com/6348462/106750407-1a3f1980-6628-11eb-8326-a93cd1f37ca9.png)

**Comment by domaindrivendev** [comment]
The properties are readonly and are therefore omitted by the swagger-us in the context of a requestBody

**Comment by flamaniac** [comment]
Ehhh my stupid mistake. Properties don;t have setters. I added init and it Swagger is showing properties now. Sorry for bother,
