### ISSUE TITLE
Schemas view

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [domaindrivendev/Swashbuckle.AspNetCore#1991]
Is it possible to somehow change the display of models in this section. I would like there to be an example json value

![image](https://user-images.githubusercontent.com/29563929/107001985-a291fb80-679b-11eb-9eaf-b76f37861315.png)

**Comment by AgPeHaJIuH1** [comment]
For example, here's how
![image](https://user-images.githubusercontent.com/29563929/107002095-ca815f00-679b-11eb-8b87-f1b1e945522a.png)

**Comment by domaindrivendev** [comment]
This is a question for the [swagger-ui folks](https://github.com/swagger-api/swagger-ui) and should be posted in that repo rather than SB
