### ISSUE TITLE
MissingMethodException Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware..ctor

### ISSUE THREAD

**Issue by alexrosenfeld10** [domaindrivendev/Swashbuckle.AspNetCore#1998]
I'm getting the below issue running on .NET 5 and SwashBuckle 6.0.2... Bafflingly, I only get this issue running inside a Docker container. When I run natively on my machine everything works fine and there's no problem whatsoever.

```
Unhandled exception. System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware..ctor(Microsoft.AspNetCore.Http.RequestDelegate, Microsoft.AspNetCore.Hosting.IHostingEnvironment, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Builder.StaticFileOptions>, Microsoft.Extensions.Logging.ILoggerFactory)'.
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.CreateStaticFileMiddleware(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware..ctor(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at <Program>$.<<Main>$>d__0.MoveNext() in /src/My.App/Program.cs:line 5
--- End of stack trace from previous location ---
   at <Program>$.<Main>(String[] args)
```

The Dockerfile is (more or less):

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
... build some stuff ...

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS runtime
... set up some more stuff ...

EXPOSE 5001
ENTRYPOINT ["dotnet", "My.App.dll"]
```

I'm not sure if you'll be able to help with this issue, but I'm hoping so as I'm kind of at a loss.

**Comment by alexrosenfeld10** [comment]
@domaindrivendev I have a suspicion that this is caused by https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs#L18-L20 . I'm running `NET5` which isn't included in that condition

**Comment by alexrosenfeld10** [comment]
I'd imagine we'd want the other similar conditions around the codebases to be updated too?

**Comment by domaindrivendev** [comment]
Those are _compile-time_ conditionals as opposed to runtime. Currently, the SB build process creates binaries targeting `netstandard2.0` and `netcoreapp3.0`. This doesn't mean they are the only frameworks the app will run on.

For example, the `netcoreapp3.0` binaries should work no problem with a NET5 runtime. In fact, I have many `net5.0` apps running with the current binaries without issue, and it seems you were able to do the same in your non-docker scenario. TBH, I'm at a loss as to why you would be getting the error you're seeing within a container vs on your local machine when in both cases you're running the app on NET5.

I'm wondering if something in your docker scenario is somehow causing the app to fallback to using the `netstandard2.1` binaries as opposed to the `netcoreapp3.0`. I've no idea why that would be happening but I do think it would result in the error you're seeing.

**Comment by alexrosenfeld10** [comment]
@domaindrivendev thanks for the detailed response. I'm at a loss too, for now I've just disabled swagger in my app so I'm not blocked.

If you could be so kind to take a look, here is more of my dockerfile:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

COPY . /
WORKDIR /

# Install dependencies
RUN dotnet restore --configfile src/NuGet.Config my-app.sln

# Test
RUN dotnet test --no-restore --logger:trx my-app.sln

# Create dotnet artifacts, output to /app
RUN dotnet publish --no-restore --configuration Release --output /app my-app.sln

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS runtime

# New Relic environment variables
# (omitted)

# Set up the app to run
WORKDIR /app
COPY --from=build /app .

EXPOSE 5001
ENTRYPOINT ["dotnet", "My.App.dll"]
```

I don't see anything obvious, unfortunately. I've even looked at the `deps.json` files inside the image and they indicate that the dependency was compiled for `netcoreapp3.0`:


```
      "Swashbuckle.AspNetCore.Swagger/6.0.2": {
        "dependencies": {
          "Microsoft.OpenApi": "1.2.3"
        },
        "runtime": {
          "lib/netcoreapp3.0/Swashbuckle.AspNetCore.Swagger.dll": {
            "assemblyVersion": "6.0.2.0",
            "fileVersion": "6.0.2.0"
          }
        },
        "compile": {
          "lib/netcoreapp3.0/Swashbuckle.AspNetCore.Swagger.dll": {}
        }
      },
      "Swashbuckle.AspNetCore.SwaggerGen/6.0.2": {
        "dependencies": {
          "Swashbuckle.AspNetCore.Swagger": "6.0.2"
        },
        "runtime": {
          "lib/netcoreapp3.0/Swashbuckle.AspNetCore.SwaggerGen.dll": {
            "assemblyVersion": "6.0.2.0",
            "fileVersion": "6.0.2.0"
          }
        },
        "compile": {
          "lib/netcoreapp3.0/Swashbuckle.AspNetCore.SwaggerGen.dll": {}
        }
      },
      "Swashbuckle.AspNetCore.SwaggerUI/6.0.2": {
        "runtime": {
          "lib/netcoreapp3.0/Swashbuckle.AspNetCore.SwaggerUI.dll": {
            "assemblyVersion": "6.0.2.0",
            "fileVersion": "6.0.2.0"
          }
        },
        "compile": {
          "lib/netcoreapp3.0/Swashbuckle.AspNetCore.SwaggerUI.dll": {}
        }
      },
```

**Comment by domaindrivendev** [comment]
With all that said, it's fairly easy to add an explicit `net5.0` target to the build process for all of the SB packages, and that will ensure that an app using `net5.0` _or above_ will always use the `net5.0` binaries. I've created a preview build (`6.0.4-preview-1567`) for this that you can pull down from [myget.org](https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) and try out. If this solves your issue, I think I'd be OK to go down this route.

**Comment by alexrosenfeld10** [comment]
Thanks I'll check this out as soon as I can. It will be a bit tricky to plug in coming from the other source, but I'll see what I can do..

**Comment by alexrosenfeld10** [comment]
@domaindrivendev  I noticed some new commits, is 1567 still the build to test? I'm working on this now.

**Comment by alexrosenfeld10** [comment]
@domaindrivendev this seems to have fixed my issue!

**Comment by trevor-the-developer** [comment]
For anyone in 2026 having issues with .NET 10 (Web and Minimal API) using Swashbuckle.AspNetCore I had to downgrade to 5.6.3 to resolve my  error 

```
Method Not Found:  'Void Swashbuckle.AspNetCore.Swagger.SwaggerOptions.set_SerializeAsV2(Boolean)'.
Program+<>c.<<Main>$>b__0_8(SwaggerOptions c)

MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.Swagger.SwaggerOptions.set_SerializeAsV2(Boolean)'.
Program+<>c.<<Main>$>b__0_8(SwaggerOptions c) in Program.cs
Program+<>c.<<Main>$>b__0_8(SwaggerOptions c) in Program.cs
Microsoft.AspNetCore.Builder.SwaggerBuilderExtensions.UseSwagger(IApplicationBuilder app, Action<SwaggerOptions> setupAction)
Program.<Main>$(string[] args) in Program.cs
```
