### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by herme063** [domaindrivendev/Swashbuckle.AspNetCore#1999]
I am following the "Getting Started" guide, but I get the following exception when I run the application:

    System.MissingMethodException
      HResult=0x80131513
      Message=Method not found: 'System.Collections.Generic.List`1<System.Action`2<Swashbuckle.AspNetCore.Swagger.SwaggerDocument,Microsoft.AspNetCore.Http.HttpRequest>> Swashbuckle.AspNetCore.Swagger.SwaggerOptions.get_PreSerializeFilters()'.

It was thrown from the application builder UseSwagger().

I did disabled OpenApi document generate as it was causing the build to fail:

	<PropertyGroup>
		<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
	</PropertyGroup>

I have no clue if it is related or not.

Thank you,

**Comment by domaindrivendev** [comment]
I can't explain why this is happening. Please create a minimal app (i.e. start from empty project) taht repro's the issue and post to github where I can pull down and troubleshoot.. Thx

**Comment by herme063** [comment]
We are using an in house framework and it turns out they reference version 4.0.1. I was not aware of it so I just added the latest version at our end. Once I matched the version it was working fine.
