### ISSUE TITLE
Support for allOf when describing polymorphic types

### ISSUE THREAD

**Issue by domaindrivendev** [domaindrivendev/Swashbuckle.AspNetCore#2]

**Comment by kevbry** [comment]
I believe this could be done right now, though a fairly simple change to SchemaRegistry could make the implementation a bit cleaner. I built a test implementation using a SchemaFilter and an attribute on child classes to specify which type Swashbuckle should use as the "parent". The filter sets up the "allOf" array on the child schema to contain a reference to the parent, then removes any properties defined by the parent from the child schema. 

The only issue I've run into is that there doesn't seem to be an easy way to get the fully inflated Schema instance for a given type in a filter, as GetOrRegister only returns reference schemas. I'd need the full schema of the parent to figure out which properties of the child schema were actually defined in the parent. SchemaRegistry.Definitions contains the full schemas and is public, but the SchemaIdManager used to generate the indexes into it is private. I was thinking of adding a method to SchemaRegistry to fetch the fully inflated Schema from SchemaRegistry.Definitions, given a Type. Does that seem reasonable? 

Could also include ability to set the "discriminator" property of the parent, but I didn't bother with that now as the tool support for discriminator seems very limited.

Attribute (place on child class, specifying parent):
``` csharp
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class SwaggerSubtypeOfAttribute : Attribute
    {
        public Type Parent { get; set; }
    

        public SwaggerSubtypeOfAttribute(Type parent)
        {
            this.Parent = parent;
        }
    }
```

Filter:
``` csharp
    public class SwaggerSubtypeOfAttributeFilter : ISchemaFilter
    {
        public void Apply(Schema model, SchemaFilterContext context)
        {
            var subTypeAttrib = context
                .SystemType
                .GetTypeInfo()
                .GetCustomAttribute<SwaggerSubtypeOfAttribute>();

            if(subTypeAttrib != null)
            {
                if (model.AllOf == null)
                {
                    model.AllOf = new List<Schema>();
                }
                
                var schemaRef = context.SchemaRegistry.GetOrRegister(subTypeAttrib.Parent);
                model.AllOf.Add(schemaRef);

                //Replace with a better method of getting full schema given a type
                var actualSchema = context
                    .SchemaRegistry
                    .Definitions[schemaRef.Ref.Replace("#/definitions/","")];

                //Remove any properties defined by the parent from the child
                foreach (string propName in actualSchema.Properties.Keys)
                {
                    model.Properties.Remove(propName);
                }
                
                //Move the remaining properties to the "allOf" set
                model.AllOf.Add(new Schema()
                {
                    Properties = model.Properties                    
                });
                model.Properties = new Dictionary<string,Schema>();
            }
        }
    }
```

**Comment by TsengSR** [comment]
@kevbry wouldn't it be better using an existing attribute for that kind of stuff, such as `[KnowType(typeof(ChildType))]`?

**Comment by keycad** [comment]
this enhancement would be really useful, my vote for it

**Comment by domaindrivendev** [comment]
With OpenAPI v3 support now added (see #952), we're in a better position to improve the support for polymorphic types. So, I'll be looking at this as a priority. Stay tuned ...

**Comment by keycad** [comment]
Hi @domaindrivendev , how is this going? any progress? Our team really needs this feature, so we were waiting to see if we could use your solution since it's a priority, but if it's gonna take long maybe we'd need to work on it by ourselves. Any feedback on this will be highly appreciated, thanks!

**Comment by domaindrivendev** [comment]
@keycad - I'm currently working on it as part of a long overdue re-factor of the Schema generation logic. It's a significant refactor hence why it's taking a long time. But, as I said, it's in work and I'm chipping away whenever I get a chance. I'm super busy with the paying job 😄 at the moment and so my time for this is a little unpredictable but I'm aiming to have it finished in weeks rather than months if that helps.

**Comment by keycad** [comment]
ok, after all paying job is higher priority ;) . We'll try to wait a few weeks more if it's possible, thanks for the update!

**Comment by domaindrivendev** [comment]
Polymorphic schema support was added with #1041 (preview packages available on myget.org). It's opt-in via the following config method:

```csharp

services.AddSwaggerGen(c =>
{
    ...

    c.GeneratePolymorphicSchemas();
}
```

When generating the schema for an abstract/base model, this will look for any subtypes in the same assembly and add a corresponding schema for each one  to the `oneOf` collection. This allows you to use abstract/base classes in your contract but also list the known subtypes in your documentation.

If neccessary, you can override the default sub type detection (i.e. assembly scoped) by passing a custom strategy to the above config method.

If you're using the `Annotations` package, you'll need to decorate the abstract/base class with one or more `SwaggerSubType` attributes for each subtype you'd like to include in the docs.
