### ISSUE TITLE
Use Swashbuckle behind a reverse proxy

### ISSUE THREAD

**Issue by angelaki** [domaindrivendev/Swashbuckle.AspNetCore#2003]
Hey folks!

Sorry, I'm afraid I'm totally wrong here asking questions about swashbuckle - but I just can't get the redirects work correctly behind a reverse proxy (stripping the prefix /api) and don't know where else to ask.

Them calling `my.site.com/api/swagger/index.html` everything is working fine. But calling `my.site.com/api/swagger/` redirects me to `my.site.com/swagger/index.html` (the /api is missing). I'm adding the following headers right now:

```
X-Forwarded-Host my.site.com
X-Forwarded-Prefix /api
X-Forwarded-Proto https
```

Shouldn't it work this way? I thought swashbuckle handles these headers?

**Comment by domaindrivendev** [comment]
Which version of SB are you using? Prior to `6.0.0`, it attempted to handle those headers itself but the implementation was fundamentally flawed and although it may have been working for you, it was also causing a lot of issues for others (see #1953 for a summary). Ensuring applications work correctly behind a proxy (e.g. for link generation, redirects etc.) is an application-level concern as opposed to just Swashbuckle, and so should be addressed independently, as described in the Forwarded Header docs, rather than within Swashbuckle code.

So, as of `6.0.0`, I've removed this responsibility from Swashbuckle as described in the 6.0.0 release notes in favor of guidance to use the Forwarded Headers Middleware to solve the problem. Please read through the following section of the SB readme, in particular the part for proxies that change the request path, there should be enough info there to solve your issue:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#working-with-reverse-proxies-and-load-balancers

**Comment by angelaki** [comment]
Thank you so much! Upgraded to 6 lately so this caused the issue! Didn't see the breaking change!

**Comment by angelaki** [comment]
Me again! Seams like `X-Forwarded-Proto, https` doesn't get respected. Redirects work now, but I still need to set the servers manually since the recoginzed server is added as http. This is what my Configure looks like:

```
if (_settings.UseForwardedHeaders)
{
    paramApplicationBuilder.UseForwardedHeaders(new ForwardedHeadersOptions
    {
        ForwardedHeaders = ForwardedHeaders.All
    });

    paramApplicationBuilder.Use((context, next) =>
    {
        if (context.Request.Headers.TryGetValue("X-Forwarded-Prefix", out var value))
        { context.Request.PathBase = value.First(); }

        return next();
    });
}
```

X-Forwarded-Proto should get managed by `UseForwardedHeaders`, isn't it? Problem of swashbuckle 6.0.2 or Dotnet 5.0?

**Comment by ttkoma** [comment]
> Me again! Seams like `X-Forwarded-Proto, https` doesn't get respected. Redirects work now, but I still need to set the servers manually since the recoginzed server is added as http. This is what my Configure looks like:
> 
> ```
> if (_settings.UseForwardedHeaders)
> {
>     paramApplicationBuilder.UseForwardedHeaders(new ForwardedHeadersOptions
>     {
>         ForwardedHeaders = ForwardedHeaders.All
>     });
> 
>     paramApplicationBuilder.Use((context, next) =>
>     {
>         if (context.Request.Headers.TryGetValue("X-Forwarded-Prefix", out var value))
>         { context.Request.PathBase = value.First(); }
> 
>         return next();
>     });
> }
> ```
> 
> X-Forwarded-Proto should get managed by `UseForwardedHeaders`, isn't it? Problem of swashbuckle 6.0.2 or Dotnet 5.0?

Please check this:

paramApplicationBuilder.UseForwardedHeaders(new ForwardedHeadersOptions
 {
        ForwardedHeaders = ForwardedHeaders.All,
        `KnownNetworks = { }`,
        `KnownProxies = { }`
  });


And check our appsettings.json 
{
...,
 `"AllowedHosts": "*"`,
...
}

**Comment by angelaki** [comment]
> > Me again! Seams like `X-Forwarded-Proto, https` doesn't get respected. Redirects work now, but I still need to set the servers manually since the recoginzed server is added as http. This is what my Configure looks like:
> > ```
> > if (_settings.UseForwardedHeaders)
> > {
> >     paramApplicationBuilder.UseForwardedHeaders(new ForwardedHeadersOptions
> >     {
> >         ForwardedHeaders = ForwardedHeaders.All
> >     });
> > 
> >     paramApplicationBuilder.Use((context, next) =>
> >     {
> >         if (context.Request.Headers.TryGetValue("X-Forwarded-Prefix", out var value))
> >         { context.Request.PathBase = value.First(); }
> > 
> >         return next();
> >     });
> > }
> > ```
> > 
> > 
> > X-Forwarded-Proto should get managed by `UseForwardedHeaders`, isn't it? Problem of swashbuckle 6.0.2 or Dotnet 5.0?
> 
> @angelaki, Please check this:
> 
> paramApplicationBuilder.UseForwardedHeaders(new ForwardedHeadersOptions
> {
> ForwardedHeaders = ForwardedHeaders.All,
> `KnownNetworks = { }`,
> `KnownProxies = { }`
> });
> 
> And you can enable more log for middleware
> `"Logging:LogLevel:Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware": "Debug"`

Needed to clear the Networks / Proxies! Thank you!

**Comment by pgiacomo69** [comment]
I'm using apache 2.4 as reverse proxy,  using "/Api"  as prefix for my application. Swagger UI works almost as expected, but whenI use "Try it out" from there, the prefix is missing in Api call.

**Comment by domaindrivendev** [comment]
Could you create a minimal app that repros (ie starting from empty project) and post to GitHub so I can pull down and troubleshoot. I can mimic the proxy behaviour using docker

**Comment by pgiacomo69** [comment]
Sorry, I didn't had the time to create the project.
 The Asp.Net core App is hosted in  a IIS application (http://127.0.0.1:8082) . I need to show it to the world as "https://mysite.xyz/Api" This is how the app is proxied in Apache Config:
 
  <LocationMatch "/Api">
      ProxyPass http://127.0.0.1:8082
      ProxyPassReverse http://127.0.0.1:8082
      RequestHeader set X-Forwarded-Prefix "/Api"
   </LocationMatch>
  
   
   Removing leading slashes in paths, following your guide in readme.md help generating the swagger homepage almost correctly, but the "/Api" prefix is not inserted, so the "Try it out" does not work.
    I solved adding this in UseSwagger:

options.PreSerializeFilters.Add((swagger, httpReq) =>
                {
                    if (httpReq.Headers.TryGetValue("X-Forwarded-Prefix", out var value))
                        {
                        swagger.Servers = new List<OpenApiServer> { new OpenApiServer { Url = value } };
                    }
                });
Now, in generated JSon a new line is present:

"basePath": "/Api"

and trying the Api from swagger page works correctly.
Thank you Anyway, if you still need the example project, I will send it as soon as I can.
Bye

**Comment by gbenthomas** [comment]
> I'm using apache 2.4 as reverse proxy, Swashbukle 6.1.4, net 5.0. Using "/Api" as prefix for my application. Swagger UI works almost as expected, but whenI use "Try it out" from there, the prefix is missing in Api call.
> https://github.com/domaindrivendev/Swashbuckle.AspNetCore#working-with-reverse-proxies-and-load-balancers is missing from readme, i found, and followed, https://github.com/domaindrivendev/Swashbuckle.AspNetCore#working-with-virtual-directories-and-reverse-proxies

I had the same issue with v6.1.4. Here's a reproduction: https://github.com/gbenthomas/swashbuckle-reverse-proxy-issue. I tested this with v5.6.3 and it worked properly. Let me know if you need any more info. Thanks!

**Comment by gbenthomas** [comment]
Hi @domaindrivendev, did you get a chance to check out the reproduction?
