### ISSUE TITLE
MapType no longer gets called for nullable structs

### ISSUE THREAD

**Issue by magnusbakken** [domaindrivendev/Swashbuckle.AspNetCore#2005]
I'm currently relying on custom mapping of nullable structs using the following helper method:

    public static void MapNullablePrimitiveTypes(this SwaggerGenOptions c)
    {
        static OpenApiSchema Schema(string type, string? format = null)
        {
            var schema = new OpenApiSchema() { Type = type, Format = format, Nullable = true };
            schema.Extensions.Add("x-nullable", new OpenApiBoolean(true));
            return schema;
        }

        c.MapType<int?>(() => Schema("integer", "int32"));
        c.MapType<long?>(() => Schema("integer", "int64"));
        c.MapType<float?>(() => Schema("number", "float"));
        c.MapType<double?>(() => Schema("number", "double"));
        c.MapType<byte?>(() => Schema("string", "byte"));
        c.MapType<bool?>(() => Schema("boolean"));
        c.MapType<DateTime?>(() => Schema("string", "date-time"));
    }

With this code in Startup.cs:

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllers();
        services.AddSwaggerGen(c =>
        {
            c.MapNullablePrimitiveTypes();
            c.SwaggerDoc("v1", new OpenApiInfo { Title = "NullableStructs", Version = "v1" });
        });
    }

Setting Nullable = true may not be needed anymore, but it's still necessary for me to set the x-nullable attribute on these types because of some dependencies during client code generation later. However, my custom type map no longer gets used in Swashbuckle 6.

For instance, with this simple controller method, the Schema function gets called in 5.x but not in 6.x:

    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        [HttpGet]
        public IActionResult Test([FromQuery] int? id)
        {
            return NoContent();
        }
    }

I can see that the MapType callback gets called for some other types, but not for the nullable structs. I haven't investigated the exact details, but I don't see why MapType shouldn't work for these types anymore.

**Comment by domaindrivendev** [comment]
The handling of nullable types has changed a little, and as a result it shouldn't be neccessary to provide explicit mappings for `Nullable` types. You can just provide the mapping for the _inner_ type, and SB will automatically assign the `Nullable` flag if neccessary.

For the `x-nullable` extension, I think you really want to _enrich_ a schema rather than providing an explicit mapping for it from scratch. In this situation, wiring up an `ISchemaFilter` (see readme) is a better choice. So, I would suggest you remove the `MapType` calls and instead wire up the following schema filter:

```csharp
public class ExtensionsSchemaFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        if (Nullable.GetUnderlyingType(context.Type) != null)
        {
            schema.Extensions.Add("x-nullable", new OpenApiBoolean(true));
        }
    }
}
```

**Comment by magnusbakken** [comment]
Sounds good! I'll close this.

**Comment by esbenbach** [comment]
@domaindrivendev You should consider adding this to the list of breaking changes (or known Issues if you plan to change the behaviour back). Just a thought.

**Comment by domaindrivendev** [comment]
Yep it should have been there - will add it.
