### ISSUE TITLE
Swashbuckle.AspNetCore.Cli 6.0.4 does not work for .NET Core 3.1 projects

### ISSUE THREAD

**Issue by older** [domaindrivendev/Swashbuckle.AspNetCore#2006]
Running `dotnet swagger tofile` does not work any more after upgrading to Swashbuckle.AspNetCore.Cli 6.x. The following exception is thrown:
`Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)       File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`
Downgrading Swashbuckle.AspNetCore.Cli to 5.6.3 fixes the issue.

Steps to reproduce:

    mkdir SwashbuckleCli6NetCore31
    cd SwashbuckleCli6NetCore31
    dotnet new webapi -f netcoreapp3.1
    dotnet add package Swashbuckle.AspNetCore
    dotnet new tool-manifest
    dotnet tool install swashbuckle.aspnetcore.cli
    
    ## Edit Startup.cs to add OpenAPI document generation
    
    dotnet build
    dotnet swagger tofile --output openapi-v3.json "bin\Debug\netcoreapp3.1\SwashbuckleCli6NetCore31.dll " v1
    
Repro project [is attached](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/5965331/SwashbuckleCli6NetCore31.zip).

**Comment by domaindrivendev** [comment]
What version of the SDK (e.g. `dotnet`) are you using. It needs to be compatible with your app. From the readme ...
>⚠️ The tool needs to load your Startup DLL and it's dependencies at runtime. Therefore, you should use a version of the dotnet SDK that is compatible with your application. For example, if your app targets netcoreapp2.1, then you should use version 2.1 of the SDK to run the CLI tool. If it targetes netcoreapp3.0, then you should use version 3.0 of the SDK and so on.

**Comment by domaindrivendev** [comment]
I just pulled down your example, and ran using a `3*` version of the SDK and it worked without any issue.

**Comment by older** [comment]
Ah, that explains it, thanks. It was working fine with 5.6.3 so I was expecting it to work after update to 6.x.

**Comment by robertkety** [comment]
Does this mean that .Net Core 3.1 is unsupported at the latest version? If so, what version should we be using?

**Comment by older** [comment]
@robertkety It is supported, but starting from 6.x you no longer can run CLI with .NET 5.0 SDK, you actually need .NET Core 3.1 SDK installed and make sure it is used when you run CLI. I used the following `global.json` in my project for that:

```json
{
  "sdk": {
    "version": "3.1.406",
    "rollForward": "latestPatch"
  }
}

```
