### ISSUE TITLE
Is it possible to hide endpoints in Swagger based on IP Address?

### ISSUE THREAD

**Issue by sprudel79** [domaindrivendev/Swashbuckle.AspNetCore#2007]
I have a setup that requires that certain endpoints of the generated Swagger.json are hidden based on the requester's IP address.
The best place for that logic would be in my opinion a DocumentFilter that is applied during AddSwaggerGen() processing and called each time the swagger.json is created. 
My problem is that it is not possible to add DocumentFilters that require the injection of external dependencies via constructor. As I am aware I can add a new DocumentFilter like
`options.DocumentFilter<CustomSwaggerDocFilter>();`
to the process and I could also pass statically parameters to that filter that will be forwarded to the constructor.
Does it therefore make sense to create a feature request for this or is there a better way to achieve my objective?
Thanks in advance!

**Comment by domaindrivendev** [comment]
From the [readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#extend-generator-with-operation-schema--document-filters):

> NOTE: Filter pipelines are DI-aware. That is, you can create filters with constructor parameters and if the parameter types are registered with the DI framework, they'll be automatically injected when the filters are instantiated.

So, you can register the filter as you've done above, and if it has a constructor with parameters, they will automatically be retreived from DI at the time of instantiation. With that said, I'm not sure if you can inject something within the request scope - I'd be interested to know if you try this out.

Regardless, if you want to modify the doc with request context, you can do it with a `PreSerializeFilter` as described in the readme:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#modify-swagger-with-request-context
