### ISSUE TITLE
Nullable Query Pameters no longer nullable

### ISSUE THREAD

**Issue by crobibero** [domaindrivendev/Swashbuckle.AspNetCore#2009]
Nullable query parameters are no longer set as `nullable: true` as of Swashbuckle.AspNetCore 6.0.4, works in 5.6.3

Sample project: https://github.com/crobibero/SwaggerTest

Generated spec:

Swashbuckle.AspNetCore v5.6.3
[swagger.5.6.3.json.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/5968535/swagger.5.6.3.json.txt)

Swashbuckle.AspNetCore v6.0.4
[swagger.6.0.4.json.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/5968534/swagger.6.0.4.json.txt)

Swashbuckle.AspNetCore v6.0.4 with `c.SupportNonNullableReferenceTypes();`
[swagger.6.0.4-support-nullable-reference.json.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/5968536/swagger.6.0.4-support-nullable-reference.json.txt)

**Comment by domaindrivendev** [comment]
This is by design - it's not possible to send the value `null` in a query string parameter. For example, if you have a string parameter called foo and you send it in the query string as:

`someurl?foo=null` ...

then the ASP.NET Core model binder will populate the parameter with a string value of `"null"` instead of `null`.

From your API perspective, what are you trying to articulate in the documentation with `nullable: true` for a query parameter?

**Comment by crobibero** [comment]
I'm trying to say that the query parameter isn't required, so we can use `required: true` in place of the parameter not being nullable.

Another issue we ran into is that enums are now being displayed as their integer value, instead of the string value, even when `[Display(Name = "")]` is set. I've updated the sample project to demonstrate this.

**Comment by kevinharing** [comment]
@crobibero Regarding your last issue, update to 6.05 and it should be fixed. See #2010 for more info.

**Comment by crobibero** [comment]
Confirmed fixed, thank you!

**Comment by plachor** [comment]
> `someurl?foo=null` ...
> then the ASP.NET Core model binder will populate the parameter with a string value of `"null"` instead of `null`.

@domaindrivendev  instead you call `someurl` without query-argument (you omit one that you wish `default` for) and than it is null

**Comment by domaindrivendev** [comment]
I’m if you can “omit” the parameter entirely, then from an OpenAPI perspective it should be described as “required: false” as opposed to “nullable: true”. When your talking in  the world of OpenAPI (as opposed to csharp), these mean different things - “nullable:true” means that the explicit value null can be submitted, which in the case of query parameters is NOT true

**Comment by domaindrivendev** [comment]
Many people, and unfortunately some client generators too, get tripped up on this subtle semantic difference

**Comment by plachor** [comment]
Thanks for quick response and clarification.
