### ISSUE TITLE
Conditional compilation flag NETCOREAPP3_0 is not sufficient anymore when explicitly targeting net5.0

### ISSUE THREAD

**Issue by kevinharing** [domaindrivendev/Swashbuckle.AspNetCore#2010]
In version 6.0.4 of Swashbuckle.AspNetCore net5.0 is targeted explicitly. Because of this the conditional compilation flag NETCOREAPP3_0 is not sufficient anymore to differentiate between compilation paths.

For example look [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/9bfbcefde1b3ed3c075a9154f39e63e8dca82817/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenServiceCollectionExtensions.cs#L56).

I stumbled upon this because my swagger.json is unit tested. My properties inside the swagger suddenly became PascalCase, where they were snake_case previously. This is what led me to the discovery that JsonOptions is most likely no longer used.

Relevant github issues/PRs:

- https://github.com/dotnet/sdk/issues/13377
- https://github.com/dotnet/sdk/pull/14798
- https://github.com/dotnet/sdk/issues/14540#issuecomment-747448407

After looking at the comment in the last link, it looks to me that, in order to support all (future and past) SDKs, the flag needs to become:

`#if NETCOREAPP3_0 || NETCOREAPP3_1 || NET5_0 || NETCOREAPP3_0_OR_GREATER`

**Comment by domaindrivendev** [comment]
Good catch - I could have sworn I’d updated that compiler conditional but must have somehow missed it. Will try get a fix out later today.

**Comment by domaindrivendev** [comment]
FYI, I think it just needs to be (!NETSTANDARD2_0) as I’ve done in all other places (just missed this one).

**Comment by kevinharing** [comment]
Thanks for the quick reply! Just to be sure, there are [more places this is still used](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/search?q=NETCOREAPP3_0).

**Comment by domaindrivendev** [comment]
@kevinharing  could you pull down the latest `6.0.5` preview from [myget.org](https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) and let me know if it resolves your issue.

**Comment by kevinharing** [comment]
@domaindrivendev I’ll have a look at it on Monday and will let you know. However, I see in the referenced issue that is has been solved.

**Comment by domaindrivendev** [comment]
Fixed by 1172b62d45c22f0bf992a6a5b5d80c8a6445f476. Just kicked off the pipeline for the `6.0.5` release so should be available on Nuget.org shortly.

**Comment by kevinharing** [comment]
@domaindrivendev It indeed fixed the issue, thanks!
