### ISSUE TITLE
swagger.json changed property names from camelCase to PascalCase, breaking clients generating proxies.

### ISSUE THREAD

**Issue by mliesmons** [domaindrivendev/Swashbuckle.AspNetCore#2011]
Hi,

/swagger.json version 6.0.2 returns properties as camelCase, from version 6.0.3 onwards property names became PascalCase.
Is this by design or will the output return to the 6.0.2 camelCase format?

**6.0.2**
  "Asset": {
        "required": [
          "**id**"
        ],
        "type": "object",
        "properties": {
          "**clientStamped**": {
            "type": "boolean"
          },

**6.0.3**
"Asset": {
        "required": [
          "**Id**"
        ],
        "type": "object",
        "properties": {
          "**ClientStamped**": {
            "type": "boolean"
          }

**Comment by domaindrivendev** [comment]
I think this is due to a bug introduced by `6.0.3` and identified by #2010. Will get a hotfix out today

**Comment by domaindrivendev** [comment]
@mliesmons could you pull down the latest `6.0.5` preview from [myget.org](https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) and let me know if it resolves your issue.

**Comment by mliesmons** [comment]
Like a charm, tnx.

**Comment by domaindrivendev** [comment]
Fixed by 1172b62d45c22f0bf992a6a5b5d80c8a6445f476. Just kicked off the pipeline for the `6.0.5` release so should be available on Nuget.org shortly.
