### ISSUE TITLE
IFormFile having incorrect Type in swagger.json (expected "file") 

### ISSUE THREAD

**Issue by PranjaliSoni** [domaindrivendev/Swashbuckle.AspNetCore#2012]
Im trying to use IFormFile for uploading file in Asp.NetCore  in the following manner with multipart/form-data :

**I'm Using swashbuckle version "5.5.0"**
```
[HttpPut("Id")]
        **[Consumes("multipart/form-data")]**
        public async Task<ActionResult<Attachment>> CreateAttachmentAsync(
            **IFormFile file**)
{
...
....
...
}
```

The swagger.json generated have **type** of the file as **"string"** :

```
{
            "in": "formData",
            "name": "file",
            "description": "File of size upto 5mb.",
            "type": "string",
            "format": "binary"
          },
```

where it should have been **"file"** which we need for generating the correct Clients with autorest

```
{
            "in": "formData",
            "name": "file",
            "description": "File of size upto 5mb.",
            "type": "file",
            "format": "binary"
          },
```
I have to explicitly **write an operation filter to set the type of all the IFormFile Parameter.** Kindly suggest the correct approach.

**Comment by domaindrivendev** [comment]
Looks to be a dup of #1769
