### ISSUE TITLE
Redoc 6.0 multiple app.UseRedoc no longer working

### ISSUE THREAD

**Issue by AsierVillanueva** [domaindrivendev/Swashbuckle.AspNetCore#2013]
I'm using multiple app.UseRedoc calls to generate multiple documentation paths with diferent swagger specs.
It works until version 5.63, but in 6.0.0 no longer works. Only the last UseRedoc call is applied.

This same issue happened on change to version 5.0.0:
#1559

**Comment by domaindrivendev** [comment]
Dup of #1996
