### ISSUE TITLE
/virtual_directory/swagger error

### ISSUE THREAD

**Issue by jjxtra** [domaindrivendev/Swashbuckle.AspNetCore#2014]
Put a swagger enabled website in an iis virtual directory. Attempt to go to http(s)://yourdomain.com/virtual_directory/swagger.

Almost all the resources are served up properly, except for swagger.json, which seems to ignore the virtual directory and uses http(s)://yourdomain.com/swagger/v1/swagger.json.

All resources served up from swagger nuget should honor the root path in the request and use it as a prefix.

**Comment by domaindrivendev** [comment]
Does your SwaggerUI config look something like this?

```csharp
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "API Docs V1");
});
```

NOTE: the provided URL is a relative URL with a leading `/`. This means the browser will construct the full URL by appending the provided path to the _root_ of the current page (in this case the swagger-ui page). So, you end up with this:

- `http(s)//yourdomain.com` + `/swagger/v1/swagger.json`.

To workaround this, you should provide a _page-relative_ URL in your config:

```csharp
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("v1/swagger.json", "API Docs V1");
});
```

This way, the browser will construct the full URL by appending the provided path to the _folder_ of the current page. So, you end up with the correct URL:

- `http(s)//yourdomain.com/virtual_directory/swagger/` + `v1/swagger.json`

**Comment by jjxtra** [comment]
That did it. Thanks!
