### ISSUE TITLE
Swagger UI Version misunderstanding

### ISSUE THREAD

**Issue by AShtifanovBK** [domaindrivendev/Swashbuckle.AspNetCore#2015]
Hello

I have a small question about the swagger UI version.
I'm trying to configure an openId connect discovery, the [swagger.io](https://swagger.io/docs/specification/authentication/openid-connect-discovery/) documentation says, that it works starting from swagger UI 3.38.0:
![image](https://user-images.githubusercontent.com/78349136/107924797-d4614a00-6f73-11eb-91a6-3d711257df77.png)

In this repository, the [compatibility ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#compatibility)section says that (for the 6.0.5 version) swagger UI 3.42.0 is supported:
![image](https://user-images.githubusercontent.com/78349136/107924902-fa86ea00-6f73-11eb-81e0-5fdf46038d50.png)

But which version is actually used? If i run in the browser console `versions`, it gives me 3.32.5 back:
![image](https://user-images.githubusercontent.com/78349136/107924993-1ee2c680-6f74-11eb-93b6-e45dffa8df1f.png)

The question is.. does the OpenId Discovery work with the actual version (6.0.5), or should i wait till the swaggerUI version is updated in this project?

Thanks!

**Comment by domaindrivendev** [comment]
Your browser must be serving up cached assets or something because SB `6.0.5` definitely ships with version `3.42.0` of the swagger-ui. I've just created a test app and performed your steps above to confirm this.

**Comment by AShtifanovBK** [comment]
Yeah, it should have been my mistake somewhere :) Will check it. 
Thank you for you time and answer!
