### ISSUE TITLE
6.0.5 subclass non-nullable strings shown as nullable

### ISSUE THREAD

**Issue by spaasis** [domaindrivendev/Swashbuckle.AspNetCore#2017]
Hi,

Great that the nullable reference types support is coming along! I tested it and found an issue that was a bit confusing.
When SupportNonNullableReferenceTypes is enabled:

```
public class TopLevelClass{
    public string TopNonNullableString { get; set; } = null!;
    public string? TopNullableString {get; set; }


    public class SubClass{
        public string SubNonNullableString { get; set; } = null!;
        public string? SubNullableString {get; set; }
    }
}
```

For the `TopLevelClass` the properties' nullable context is shown correctly, but for `SubClass` both are shown as nullable.
Now if I move the `SubClass` to be on the top level, the nullable context is shown correctly.

I'm on version 6.0.5

**Comment by Eneuman** [comment]
I have tracked down this bug and will submit a PR tomorrow.
