### ISSUE TITLE
SupportNonNullableReferenceTypes not working for query parameters

### ISSUE THREAD

**Issue by Eneuman** [domaindrivendev/Swashbuckle.AspNetCore#2019]
Using v6.0.5 with .net Core 5 with non nullable reference types enabled.

It looks like c.SupportNonNullableReferenceTypes(); is not working for querystring parameters.

In a controller method I have the following parameter defined:
```
    [SwaggerOperation(OperationId = "GetGrid")]
    public async Task<ActionResult<ViewModels.Result>> GetGridAsync(string sorteringskolumn)
```

This generates the following json:
```
            "name": "sorteringsordning",
            "in": "query",
            "schema": {
              "type": "string"
            }
```

If I try and call this method without the parameter, the .Net Core Model Validation will give me back a HTTP 400 Bad Request and tell me that "sorteringskolumn" is required.

The problem here is that when generating a client from the above json, the client will not understand that the parameter is required since normaly, a string query parameter cannot be null and is by default "", but since non nullable reference type is enabled, the model validation behavior changes.

I think when using `c.SupportNonNullableReferenceTypes ()` a more correct representation would be:

            "name": "sorteringsordning",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }

The workaround is to add a [Required] infront of the parameter name in the controller, but this is awkvard since [Required] is not used when using non nullable reference types.

**Comment by domaindrivendev** [comment]
Def a missing feature - specifically SB doesn't currently support "implicit required for non nullable reference types". Off the top my head, there's the hack approach and the much cleaner approach that ties in with some broader refactors that I want to make. Flagging as p1 for now.

**Comment by domaindrivendev** [comment]
With that said, it does look like ASP.NET Core currently honors this feature on the `ModelMetadata.IsRequired` property and so you could create a fairly simple `IParameterFilter` to workaround the issue for now:

```csharp
// Startup.cs
services.AddSwaggerGen(c =>
{
    ...
    c.ParameterFilter<ImplicitRequiredParameterFilter>();
});
```

```csharp
// ImplicitRequiredParameterFilter
public class ImplicitRequiredParameterFilter : IParameterFilter
{
    public void Apply(OpenApiParameter parameter, ParameterFilterContext context)
    {
        parameter.Required = context.ApiParameterDescription.ModelMetadata.IsRequired;
    }
}
```

**Comment by Eneuman** [comment]
Thank you for the workaround, it works great!

**Comment by Eneuman** [comment]
Now that we dont need to decorate the strings with `[Required]`, we just need to get rid of the need to decorate the reference types with `[BindRequired]`.

Since I have enabled non nullable referencetypes in my project, VS also wants me to explicit tell if a reference type is supposed to be null by adding a ? at the end of the declaration. As I understand it, this doesn't actually change the IL code, its more like static analysis of the code.

Like this:

```
[SwaggerOperation(OperationId = "GetGrid")]
public async Task<ActionResult<ViewModels.Grid>> GetGridAsync(MyComplexClass myType, string userId, [BindRequired] int articleId, int? orgId, int? personalId)

```

Is there any way to also remove the need for [BindRequired] ?
(Note that `myType` will is treated as it had [FromBody])

**Comment by martincostello** [comment]
To make issue tracking a bit less overwhelming for the new maintainers (see #2778), I've created a new tracking issue to roll-up various nullability issues here: #2793.

We'll refer back to this issue from there and include it as part of resolving that issue, but I'm going to close this one to help prune the backlog.
