### ISSUE TITLE
Registering types not exposed by API is broken on version 6

### ISSUE THREAD

**Issue by KostblLb** [domaindrivendev/Swashbuckle.AspNetCore#2020]
Hello! We've recently moved our project to .net 5 and updated Swashbuckle dependency from ver. 5 to 6.0.2. We had some types that were not exposed by our API  that we wanted in swagger.json, like exceptions thrown from controllers, so we had this IDocumentFilter implementation:
```
  public class SwaggerAddCustomTypesFilter : IDocumentFilter
  {
      public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
      {
          context.SchemaGenerator.GenerateSchema(typeof(EventPublisherMethods), context.SchemaRepository);
          context.SchemaGenerator.GenerateSchema(typeof(ValidationExceptionResult), context.SchemaRepository);
      }
  }
```

As of version 6.0.2, this no longer works: schemas are generated and can be seen in context.SchemaRepository.Schemas, but they are not added to actual swaggerDoc. So in order to fix this, I just added the following line at the end of Apply method: 
```
    swaggerDoc.Components.Schemas = context.SchemaRepository.Schemas;
```
and it kinda works.

Is this the indended behavior now or is it a bug?

**Comment by domaindrivendev** [comment]
Please try `6.0.7` - I believe this issue was fixed by 224a0843bf5faa180ebd9a93d05e35f53c76a5ee, and pushed out with that version.
