### ISSUE TITLE
Element defined as type = "string", format = "binary" gets passed always as the last element in a multipart/form-data?

### ISSUE THREAD

**Issue by SpiritBob** [domaindrivendev/Swashbuckle.AspNetCore#2024]
As per OpenAPI 3.0 specifications, there is no longer a type "file", but instead, we should define files using the type `string` and a format either `binary`, or `byte`. (Source: https://swagger.io/docs/specification/data-models/data-types/)

When using an operation filter, if we define a multipart/form-data content, which includes several properties, one of which is a file, if that file is defined in any order, using the legacy 2.0 approach - it gets fed in the order of which it was defined when reading the underlying form data stream. (expected result)

But when it is defined in the new 3.0 convention, for some reason, the data to the server is passed in a way that it is **always** the last element in the multipart/form-data, regardless in what order the file was defined.

If we had a single file, and 3 other properties of type integer, the file would always be the last one to be read in the multipart/form-data request.

Is this a feature? If so, why the subtle differences?

**Comment by domaindrivendev** [comment]
In the OpenAPI/Swagger JSON that Swashbuckle generates, the properties are listed in the order they're defined. So, the change to the order is happening on submission as part of the [swagger-ui tool's "Try it out" functionality](https://github.com/swagger-api/swagger-ui). Therefore, this issue should be submitted to that repo instead of Swashbuckle.

**Comment by SpiritBob** [comment]
@domaindrivendev Got it, will contact them and keep everyone updated.

**Comment by SpiritBob** [comment]
Fixed in https://github.com/swagger-api/swagger-ui/issues/6979?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE2MTIyNDQ3OTI6NjY5NTczMQ%3D%3D#event-4438527544
