### ISSUE TITLE
Not nullable properties in Response are not marked as required 

### ISSUE THREAD

**Issue by rallets** [domaindrivendev/Swashbuckle.AspNetCore#2025]
Hi all, I'm using the latest version 6.0.7 in .net core 5 to generate the swagger json definitions, used by [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator) to generate Typescript-fetch model definitions.

My problem is that openapi-generator is marking all my properties as optional, example
```
export interface AccessRequestResponse {
    accessRequestId?: number;
    [...]
}
```
because in the swagger definition that property is not "required".
The .net core model:
```
public class AccessRequestResponse {
    public long AccessRequestId { get; set; }
    [...]
}
```
The json definition:
```
"AccessRequestResponse": {
    "type": "object",
    "properties": {
      "accessRequestId": {
        "type": "integer",
        "format": "int64"
      },
      [...]
    },
    "additionalProperties": false
},
```
As you can see it's missing the `required` attribute.
I looked in all the issues but haven't found anything related to this (only on Requests).
I found only some (pretty old) SO threads like [this one](https://stackoverflow.com/questions/46576234/swashbuckle-make-non-nullable-properties-required) that suggest a custom `ISchemaFilter`. 
As I think this could be useful in many projects, I was looking for an opinionated implementation directly in Swashbuckle.AspNetCore, as custom filters could not be accepted in some contexts.

I would appreciate hearing your opinion on this.

**Comment by domaindrivendev** [comment]
The difficulty here is that Swashbuckle currently creates a single schema per user-defined type and then that schema is re-used (via the `$ref` keyword) in different contexts - e.g. requests and/or responses. While it's valid to say that a non-nullable property will always be serialized to a _response_ and therefore could be implicitly marked `required`, the same is not true for the reverse case. That is, if the same type is also being used for a request, then a non-nullable property is not neccesarily required. If it's not provided in the request, then the property will have a default value but the request won't neccesarily fail.

So, SB can't mark non-nullable properties as required because it doesn't neccesarily know that the user defined type is only used for responses. That's not to say it shouldn't be able to make this distinction, it just currently doesn't and doing so would be non-trivial IMO.

**Comment by rallets** [comment]
Thanks @domaindrivendev for the quick answer, I understand now the problem better. IMHO I think this could slow down the SB usage in many frontend applications that rely on typescript and asp.net core. 
As example, in my case, all the response models are "wrong" and I need to add a wrapper around them to reflect the "real" model, or apply the `[Required]` attribute to all of them (that for me is a duplicated information that must be kept in sync, driving to human errors).
So I need to figure out a different way to obtain that. I'm wondering if exists a flag that make possible to remove the usage of `$ref` (that I see here as an optimization) and generate the schema for each model (that, we agree, makes a slower and bigger json).

**Comment by domaindrivendev** [comment]
The OpenAPI specification (or more specifically JSON Schema) does provide an approach for essentially "extending" a referenced schema using the `allOf` keyword, and you could conceivably leverage this to apply an additional `required` list, but only in the context of responses. For example, you could keep your request schemas as they are, but structure all of your response schemas as follows:

```yaml
paths:
  /test:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  -
                    $ref: "#/components/schemas/AccessRequestResponse"
                  -
                    required:
                      - accessRequestId
```

To do this with Swashbuckle, you could wire up a relatively straightforward operation filter. The following example makese _all_ properties in a response required implicitly but you could probably adjust to your specific needs fairly easily. 

```csharp
public class TweakResponseSchemasOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        foreach (var response in operation.Responses.Values)
        {
            foreach (var responseMediaType in response.Content.Values)
            {
                if (responseMediaType.Schema.Reference == null) continue;

                var definitionSchema = context.SchemaRepository.Schemas[responseMediaType.Schema.Reference.Id];

                // Instead of referencing it directly, "extend" the definition schema, overriding the required list
                // for this context only
                responseMediaType.Schema = new OpenApiSchema
                {
                    AllOf = new List<OpenApiSchema>
                    {
                        responseMediaType.Schema,
                        new OpenApiSchema { Required = new SortedSet<string>(definitionSchema.Properties.Keys) }
                    }
                };
            }
        }
    }
}
```

**Comment by rallets** [comment]
@domaindrivendev thank you for your reply, I was hoping in something baked in SB, so that was easier approved by team members.

**Comment by laliconfigcat** [comment]
I just run into the same issue recently and unfortunately the proposed solution did not work for me as that solution is only fixing the top-level properties. We have nested models and arrays in our models. 
Unfortunately, sometimes the request and response models are mixed too so simply modifying all response models' references in the schema didn't work for me.

I finally came up with another approach. It is an `IOperationFilter` too, but it is duplicating all response schemas with a new name (with a postfix) and adding the required attributes on the new schema and it is doing it recursively (nested models, arrays too).

```
public class TweakResponseSchemasOperationFilter : IOperationFilter
{
    private const string ResponseModelPostfix = "Response";

    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        // We are iterating through the operation responses' content values to fix all response schemas.
        // Based on the proposed solution: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2025#issuecomment-783758999
        foreach (var responseMediaType in operation.Responses.Values.SelectMany(response => response.Content.Values))
        {
            FixupResponseSchema(context, responseMediaType.Schema);
        }
    }

    private static void FixupResponseSchema(OperationFilterContext context, OpenApiSchema schema)
    {
        // If the current schema is a Reference, we duplicate it and fix the required attributes.
        if (schema.Reference != null)
        {
            schema.Reference.Id = FixupResponseReference(context, schema.Reference);
        }
        // If the current schema is an array, we try fixing up the array's schema.
        else if (schema.Items != null)
        {
            FixupResponseSchema(context, schema.Items);
        }
    }

    private static string FixupResponseReference(OperationFilterContext context, OpenApiReference reference)
    {
        // We generate a new reference ID for the duplicated reference.
        var newReferenceId = reference.Id + ResponseModelPostfix;

        // We want to reuse the already duplicated schemas, so if the SchemaRepository contains the new reference id, we simply return it.
        // There is a slight issue with this, this logic can break if there are 2 models in the API with the names "MyModel" and $"MyModel{ResponseModelPostfix}". 
        // Be careful to use a ResponseModelPostfix that will not cause issues like this.
        if (context.SchemaRepository.Schemas.ContainsKey(newReferenceId))
        {
            return newReferenceId;
        }

        // Looking up the schema based on the current reference Id so we can clone it.
        var definitionSchema = context.SchemaRepository.Schemas[reference.Id];
        var clonedSchema = new OpenApiSchema(definitionSchema);

        // Adding the required attributes to the cloned schema. 
        clonedSchema.Required = new SortedSet<string>(clonedSchema.Properties.Keys);

        // Adding the cloned and fixed schema with the new reference id to the repository.
        context.SchemaRepository.AddDefinition(newReferenceId, clonedSchema);

        // Iterate through all properties of the schema, and fix up the schemas recursively.
        foreach (var property in clonedSchema.Properties.Values)
        {
            FixupResponseSchema(context, property);
        }

        return newReferenceId;
    }
}
```
