### ISSUE TITLE
Using Utf8Json as InputFormatters/OutputFormatters

### ISSUE THREAD

**Issue by darkurse** [domaindrivendev/Swashbuckle.AspNetCore#2027]
Hi @domaindrivendev,

Since I don't know how to reopen an old thread properly ( #1815 ) , I hope you don't mind I re-open one here refering back to the original issue opened by @Sliverb back then. 

Same as him, I am also using Utf8Json serializer as input/output formatters to exchange data on my server. And by doing so, it seems that any JSON data serialized on the body of the request doesn't get 'discovered' by swashbuckle/ApiExplorer.

To show you what happens I have re-create a minimal app for your convenience there : https://github.com/darkurse/SwashbuckleWithUtf8JsonTest

If I use the default serializer it all works, if I specify the Utf8Json serializer it doesn't work anymore.. All depends on the following lines ( Note that `Utf8JsonOutputFormatter`, `Utf8JsonInputFormatter`, `Utf8JsonContractResolver` are classes on the minimal app project ):

     services
                .AddMvcCore()
                .AddApiExplorer()
                // note: If I comment out the AddMvcOptions section, I will see the body populated as expected
                .AddMvcOptions(option => 
                {
                    option.OutputFormatters.Clear();
                    option.OutputFormatters.Add(new Utf8JsonOutputFormatter(Utf8JsonContractResolver.Instance));

                    option.InputFormatters.Clear();
                    option.InputFormatters.Add(new Utf8JsonInputFormatter(Utf8JsonContractResolver.Instance));
                });

**With the Mvc Options** set , we get an empty body :
![with](https://user-images.githubusercontent.com/1208226/108679491-e9e2f080-74ec-11eb-9fc7-2ae8d0fc77d6.png)

**Without the Mvc Options** set , we get the proper body documented :
![without](https://user-images.githubusercontent.com/1208226/108679499-ee0f0e00-74ec-11eb-9b5f-023477922a49.png)

I'm afraid there would be the same work to do as the one you made to be backward compatible with NewtonSoft.. But I don't know how and where to start to make such a mapping..

Any ideas, pointers, help is welcome.

Thank you in advance,
Julien

**Comment by darkurse** [comment]
[Update] I have created the mirrored the idea of the project `Swashbuckle.AspNetCore.Newtonsoft` and created a project `Swashbuckle.AspNetCore.Utf8Json` ( disclaimer : This is a TEST project, so nothing is polished ).

It seems that I can now view the schema on the swagger UI .. but the POST parameters are still not working. I don't know what I am doing wrong at this point. Any pointers would be appreciated.

**Comment by darkurse** [comment]
[Update] I have mirrored the idea of the project `Swashbuckle.AspNetCore.Newtonsoft` and created a project `Swashbuckle.AspNetCore.Utf8Json` hoping that it help in viewing the POST parameters in the swagger UI, unfortunately it didn't change anything.

I am wondering now if this is because `Utf8JsonOutputFormatter` and `Utf8JsonInputFormatter` have both something to do with the **ApiExplorer**.

**Comment by domaindrivendev** [comment]
@darkurse - what you've done is exactly what I would have recommended - the `ISerializerDataContractResolver` abstraction is intended to encapsulate serializer-specific behavior, and so an implementation needs to be created for any new serializer that we want SB to support.

However, the fact that you're seeing no schema defintion with the `Utf8` formatters configured also makese me think this is somehow related to `ApiExplorer`.

**Comment by darkurse** [comment]
@domaindrivendev , thank you for your precious feedback. 

Maybe the ApiExplorer is not the (only) one to blame for this because I noticed another thing.. I remembered that Swashbuckle also reads the generated xml documentation file via the `o.IncludeXmlComments(xmlPath);` .. So I went to look at this xml file and this is what I noticed ( my apologize :

    [...]
        <member name="M:SwashbuckleWithUtf8JsonTest.Controllers.WeatherForecastController.Set(SwashbuckleWithUtf8JsonTest.WeatherForecast)">
            <summary>
            Setting le forecast
            </summary>
            <param name="p">Le parameter</param>
        </member>
        <member name="T:SwashbuckleWithUtf8JsonTest.WeatherForecast">
            <summary>
            Le forecast class
            </summary>
        </member>
    [...]

The `p` parameter represents the body parameter of my controller's entry point

        [HttpPost]
        public void Set([FromBody]WeatherForecast p)

It seems that the `$ref` is missing in the generated XML.. Is OpenApi used to generate this file ? Or is it going through another process ?

In any case, if I bypass the GenerateXML section altogether, it doesn't help either. So issue seems multifold.

**Comment by domaindrivendev** [comment]
OK - I was very curious about this so ended up digging into the ASP.NET Core code, specifically around `ApiExplorer` and came across the following snippet:

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Mvc/Mvc.ApiExplorer/src/DefaultApiDescriptionProvider.cs#L411
```csharp
if (formatter is IApiRequestFormatMetadataProvider requestFormatMetadataProvider)
{
    var supportedTypes = requestFormatMetadataProvider.GetSupportedContentTypes(contentType, type);
```

This tipped me off to the fact that custom input and output formatters needs to implement `IApiRequestFormatMetadataProvider`  and `IApiResponseTypeMetadataProvider` respectively to play nicely with ApiExplorer, and thus Swashbuckle.

I guess the intention is that you use the abstract implementations (`InputFormatter` and `OutputFormatter`) rather than interfaces directly, as these include some of this for you already. However, the additional interfaces you need to implement are very simple and so you could go with either approach. I tested this out with your sample app and it worked perfectly.

**Comment by darkurse** [comment]
Well done ! 

I think I went completely off track this morning with my "generated xml documentation" idea.. Playing with the code again, I saw that I made wrong assumptions.

I have now done as suggested and voila : !
![image](https://user-images.githubusercontent.com/1208226/108848700-98685d80-75e1-11eb-8976-77a01ea9ab22.png)

Thank you so much for your time, much appreciated 👍

**Comment by AlexanderTorresSSA** [comment]
@darkurse  any chance you have a sample repo that covers what you did?  I am experiencing the same exact issue.

**Comment by AlexanderTorresSSA** [comment]
@darkurse  disregard, I found https://github.com/neuecc/Utf8Json/tree/master/src/Utf8Json.AspNetCoreMvcFormatter. Hope that helps anyone else. 

Then it's a matter of doing what was already shared:

``
  services.AddControllers(option =>
            {
                option.OutputFormatters.Clear();
                option.OutputFormatters.Add(new JsonOutputFormatter(StandardResolver.Default));
                option.InputFormatters.Clear();
                option.InputFormatters.Add(new JsonInputFormatter());
            });

``

**Comment by darkurse** [comment]
I'm glad you found it yourself.. As written in my `unclear` addendum, I have [cloned the current project](https://github.com/darkurse/SwashbuckleWithUtf8JsonTest) and made the changes to make it work for me.

Sorry that I couldn't help you out earlier. I just couldn't find the time :/
