### ISSUE TITLE
Korean broken issues.

### ISSUE THREAD

**Issue by msshim-dev** [domaindrivendev/Swashbuckle.AspNetCore#2030]
using OpenApiInfo.

example

```
c.SwaggerDoc("v1", new OpenApiInfo
				{
					Version = "v1",
					Title = "Innofit testAPI V 0.0.0.1.",
					Description = "Innofit Backend API Documents.",
					TermsOfService = new Uri("https://"),
					License = new OpenApiLicense
					{
						Name = "한글(korean)",
						Url = new Uri("i"),
					}
				});
```

korean broken. swagger ui.

How do i do it

**Comment by cupsos** [comment]
![image](https://user-images.githubusercontent.com/24942851/110900774-a4288380-8346-11eb-9887-300ce2f6f2be.png)  
TFM net5.0, Swashbuckle.AspNetCore 6.1.0  
I can not reproduce your issue.  Please give more detail information, version, browser or soruce code.

**Comment by msshim-dev** [comment]
The local machine is fine. However, it appears when I build it as a release and deploy it on Ubuntu 20.04.

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.

As I don't speak Korean, it isn't clear to me what is broken.
