### ISSUE TITLE
FileResult action return type not generating a string/binary schema

### ISSUE THREAD

**Issue by Velorien** [domaindrivendev/Swashbuckle.AspNetCore#2032]
Hello, it seems that I've stumbled upon an inconsistency in the generator.

Consider the following controller action signatures:
```
ActionResult<FileResult> DownloadThatGeneratesAGoodSchema();
FileResult DownloadThatDoesNot();
```

The schema information generated for the first one describes the type as `string` with format `binary`, whereas for the second one there is no content schema whatsoever. This seems to be a bug because for the following code, both actions produce type `integer`, format `int64`:

```
ActionResult<long> ALongNumber();
long AlsoALongNumber();
```

Additionally, `ActionResult<FileResult>` is not a valid type as attempting to use it results in an `System.ArgumentException: Invalid type parameter 'Microsoft.AspNetCore.Mvc.FileResult' specified for 'ActionResult<T>'.`

This behaviour is present in both Swashbuckle.AspNetCore 5.6.3 (.NET 5 default) and 6.0.7 (latest at the time of writing this).

**Comment by domaindrivendev** [comment]
This looks like an upstream issue with ASP.NET Core, specifically with it's `ApiExplorer` component that Swashbuckle builds on top of. In this case, for some reason it's not surfacing any `SupportedResponseTypes` for an action that returns `FileResult`:

![screenshot](https://user-images.githubusercontent.com/1434343/109067269-334a6000-76e6-11eb-9902-6e12af4d7008.png)

**Comment by Velorien** [comment]
Ahh, that makes sense. If my very brief investigation is correct, `IActionResult` falls under the condition of being assignable from `FileResult` and the latter has no generic parameter, so  [this very line](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.ApiExplorer/src/ApiResponseTypeProvider.cs#L233) in `Microsoft.AspNetCore.MVC.ApiExplorer.ApiResponseTypeProvider` causes this behavior.

**Comment by Velorien** [comment]
Fyi, I've opened an issue to track this bug https://github.com/dotnet/aspnetcore/issues/30465

**Comment by SpiritBob** [comment]
@Velorien this would break for any `ActionResult` type, and I think it's with good grounds. Using the generic `ActionResult` class is for wrapping a type that's not an `ActionResult`, rather than attempt wrapping an `ActionResult` within an `ActionResult`. That makes no sense.

You should simply return a `FileResult` in your case.

**Comment by Velorien** [comment]
@SpiritBob I'm not suggesting that the `ActionResult<OtherActionResult>` construct should be viable - I agree that it's nonsensical. What I'm pointing out is that `ActionResult<FileResult>` while causing a runtime error, makes the ApiExplorer module recognise the method as returning a stream of data, but plain `FileResult` doesn't. You mention `JsonResult` as a type that would cause this behaviour too - and rightfully so. From the ApiExplorer's perspective, what's the correct schema that would be applied there? An object? An array? Both are valid JSON responses but if your goal is to generate an OpenApi description, you have no way of knowing what the end result is going to be.

The `ActionResult<long>` vs `long` example was provided for contrast but I'm inclined to agree that it wasn't the clearest one possible ;)

**Comment by angelaki** [comment]
Just hit that issue - any news on this?

**Comment by jeffward01** [comment]
**Works**
```csharp

 MinioClient? minioClient = _getMinioClient();

        // Confirm that the object exists before trying to download it
        StatObjectArgs? statObjectArgs = new StatObjectArgs().WithBucket(this._hardCodedBucketName)
            .WithObject(this._hardCodedObjectName);

        await minioClient.StatObjectAsync(statObjectArgs, cancellationToken);
        FileStreamResult response = null!;

        GetObjectArgs? getObjectArgs = new GetObjectArgs().WithBucket(this._hardCodedBucketName)
            .WithObject(this._hardCodedObjectName)
            .WithCallbackStream(
                stream =>
                {
                    // Load response with file stream
                    response = this.File(stream, _getContentType(), this._hardCodedDownloadedFile.Name);
                });
        await minioClient.GetObjectAsync(getObjectArgs, cancellationToken);

        return response;

```

**Broken**
```csharp
 MinioClient? minioClient = _getMinioClient();

        // Confirm that the object exists before trying to download it
        StatObjectArgs? statObjectArgs = new StatObjectArgs().WithBucket(this._hardCodedBucketName)
            .WithObject(this._hardCodedObjectName);

        await minioClient.StatObjectAsync(statObjectArgs, cancellationToken);
        FileStreamResult response = null!;

        GetObjectArgs? getObjectArgs = new GetObjectArgs().WithBucket(this._hardCodedBucketName)
            .WithObject(this._hardCodedObjectName)
            .WithCallbackStream(
                stream =>
                {
                    // Load response with file stream
                    response = this.File(stream, _getContentType(), this._hardCodedDownloadedFile.Name);
                });
        await minioClient.GetObjectAsync(getObjectArgs, cancellationToken);

        return this.Ok(response);
```

---

Expected: I would expect `this.Ok(response)` to have success.

It appears to be a bug, or a stream disposed issue.
