### ISSUE TITLE
Swagger does not show a file upload button for a IFormFile

### ISSUE THREAD

**Issue by johnpage-agixis** [domaindrivendev/Swashbuckle.AspNetCore#2041]
I have imitated many examples and read many suggestions but I cannot get swagger to show a file input button for an input of type IFormFile.

See here for a minimal example...
[https://github.com/johnpage-agixis/SwaggerUploadFileExample](https://github.com/johnpage-agixis/SwaggerUploadFileExample)

Targetting dotnet 3.1
Swashbuckle.AspNetCore is version 6.0.7

My controller method looks like this.
```
/// <summary>
/// File upload
/// </summary>
/// <param name="file"></param>
/// <returns></returns>
[HttpPost]
[Route("test/")]
public ActionResult Upload(IFormFile file)
{
    return Ok($"{file.FileName} is {file.Length} bytes long");
}
```

All I see is this 
![image](https://user-images.githubusercontent.com/62235266/109696932-e48d4200-7b8d-11eb-8a7e-12b60ebc955f.png)

What am I doing wrong?

**Comment by domaindrivendev** [comment]
Click the "Try it out' button to enable input fields and you'll see the upload button appear. This is obvious to me as I've been using this UI for a long time but perhaps you feel it's a bit unituitive. If so, please direct that feedback to the [swagger-ui project](https://github.com/swagger-api/swagger-ui) and not Swashbuckle. Thanks

**Comment by johnpage-agixis** [comment]
Silly me. Thanks a lot!

**Comment by sharpSteff** [comment]
@johnpage-agixis stumbled over the same issue
