### ISSUE TITLE
Combine multiple swagger docs

### ISSUE THREAD

**Issue by ponsakthi** [domaindrivendev/Swashbuckle.AspNetCore#2043]
Is there a way to combine multiple swagger documents to a single one?

**Update:**
In a microservice architecture where APIs are hosted on multiple different microservices, we are thinking of an approach to host a single microservice called swagger aggregator, which can collect swagger jsons from multiple microservices by invoking their swagger endpoints, stitch them together to look like a single swagger UI .

Eg: Customer API service, Product API service, Purchase Order API service are individual microservices that have their own swagger json. We would like to build documentation API service that can invoke other 3 microservice endpoints to get their swagger json, stitch it up and build a single swagger json . For API developers, the landing page would be the one exposed by Documentation API service.

**Comment by domaindrivendev** [comment]
It's very difficult to address one-liner issues like this. If you want me or others to invest our personal time into solving it, then please  follow suit by investing some of your own time into clearly articulating what you're trying to do (background, code samples etc.)

**Comment by ponsakthi** [comment]
> It's very difficult to address one-liner issues like this. If you want me or others to invest our personal time into solving it, then please follow suit by investing some of your own time into clearly articulating what you're trying to do (background, code samples etc.)

Sorry. Updated original question with more information

**Comment by joacar** [comment]
Waking up this old thread, but how do I merge multiple with the generated? I.e. can I combine `AddSwaggerGen` with a custom `ISwaggerProvider`?

Thanks

**Comment by martincostello** [comment]
Closing this as resolved by https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2043#issuecomment-803026576.
