### ISSUE TITLE
No Request Example with SerializeAsV2 Enabled

### ISSUE THREAD

**Issue by mattrhoden** [domaindrivendev/Swashbuckle.AspNetCore#2044]
Hi,

We are trying to maintain backwards compatibility for the time being and noticed that request examples don't seem to be supported when setting `SerializeAsV2 = true`.  

To reproduce you can run this sample project that I have setup: https://github.com/mattrhoden/v2-bug-example

Here is with `SerializeAsV2 = true`

![image](https://user-images.githubusercontent.com/51673098/109844883-8f4b4200-7c1a-11eb-9e35-1d29740d03d3.png)

Here is with `SerializeAsV2 = false`

![image](https://user-images.githubusercontent.com/51673098/109844976-a7bb5c80-7c1a-11eb-91c1-eec05eef4ee0.png)

I found a related [bug](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/115) and have tried updating my ConfigureServices with `services.Configure<SwaggerOptions>(c => c.SerializeAsV2 = true);` and removing 

```
app.UseSwagger(c =>
{
    c.SerializeAsV2 = true;
    ...
```

That doesn't seem to work either. That example is in another branch called [configure-service-example](https://github.com/mattrhoden/v2-bug-example/tree/configure-service-example).

Thanks for your help.

**Comment by domaindrivendev** [comment]
This is actually due to a downstream issue in the Swashbuckle.AspNetCore.Filters library - https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/115, which appears to be fixed now.
