### ISSUE TITLE
Support non-root / app relative paths

### ISSUE THREAD

**Issue by brgrz** [domaindrivendev/Swashbuckle.AspNetCore#2046]
The issue https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1253 was about supporting non-root paths and it was supposedly resolved but not quite.

The issue is very simple.

Just change the URL templates to not use the leading slash, for example from this 

```
			app.UseSwagger(c =>
			{
				c.RouteTemplate = "/api/{documentName}/swagger/swagger.json";
			});

			app.UseSwaggerUI(c =>
			{
				c.SwaggerEndpoint($"/api/{_apiVersion}/swagger/swagger.json", $"{_apiTitle} {_apiVersion}");
			});
```

to this

```
app.UseSwagger(c =>
			{
				c.RouteTemplate = "api/{documentName}/swagger/swagger.json";
			});

			app.UseSwaggerUI(c =>
			{
				c.SwaggerEndpoint($"api/{_apiVersion}/swagger/swagger.json", $"{_apiTitle} {_apiVersion}");
			});
```

and you will see the request for swagger.json fails (fetch error). Fails locally with IIS Express too and it fails in certain scenarios on the server like when used inside an IIS sub app.

Hopefully that is enough info for reproduction.

**Comment by domaindrivendev** [comment]
The URL that you pass to `SwaggerEndpoint` is what the swagger-ui, a client-side application, uses to retrieve your API metadata. In omitting the leading slash, you're telling the swagger-ui that the path is relative to _itself_ (nothing to do with SB by the way ... just how the internet works). So, assuming the default `RoutePrefix = "swagger"` for the SwaggerUI middleware, you're telling it that the Swagger endpoint is available at `swagger/api/{_apiVersion}/swagger/swagger.json`, which clearly isn't correct. If you want to use _page-relative_ paths (i.e. without the leading slash) then you need to ensure the value is relative to the URL at which the swagger-ui is served. So, something along the following lines should work:

```csharp
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("../api/v1/swagger/swagger.json", "V1 Docs");
});
```

**Comment by brgrz** [comment]
I understand that but I wasn't only changing the path to `SwaggerEndpoint()` as you can see from the example I also told Swashbuckle `c.RouteTemplate = "api/{documentName}/swagger/swagger.json"`. It makes sense to me that when both route templates use the leading slash AND work they will also work when they lose the leading slash. 

Otherwise I do not know what the `UseSwagger()` `RouteTemplate` is for?

**Comment by domaindrivendev** [comment]
The `RouteTemplate` setting within `UseSwagger` is for specifying the route that your app will expose the Swagger JSON for a given `{documentName}` at. Think attribute routing, but for the Swagger JSON endpoint that's provided by the `UseSwagger` middleware.

The value that you pass to `SwaggerEndpoint` within `UseSwaggerUI` is the URL that you're telling the swagger-ui it can retrieve the Swagger JSON that it needs. In a typical Swashbuckle install, this should _correspond_ to the Swagger JSON you're exposing, and thus the `RouteTemplate` specified above, although this doesn't have to be the case (for example, if you're using the SwaggerUI on it's own and retrieving the Swagger JSON from elsewhere).

So, you're correct in saying they should match up, but when thinking about leading slashes etc, you need to account for the fact that `UseSwagger => RouteTemplate` is from the perspective of the _server_ and `UseSwaggerUI => SwaggerEndpoint` is from the perspective of the client-side code running in your browser. I'm not sure what else I can say here to explain further. If it still doesn't solve your problem, then we should take a step back out of implementation detail and have you explain exactly what you're trying to achieve with your docs that's not working for you.

**Comment by brgrz** [comment]
I updated to 6.1.0 because I saw you were changing parts of code that handle relative paths and deal exactly with the kind of issues I was having 3 days ago.

As it stands now with the following setup

```
			app.UseSwagger(c =>
			{
				c.RouteTemplate = "swagger/{documentName}/swagger.json";
			});

			app.UseSwaggerUI(c =>
			{
				c.SwaggerEndpoint($"{_apiVersion}/swagger.json", $"{_apiTitle} {_apiVersion}");
			});
```

it seems to work fine in a virtual application use case. I also tried playing around with RoutePrefix and again got mixed/unpredictable results so I quickly stopped with the code that now works both locally and in production. I think setting the paths remains somewhat unintuitive (illogical?) but I guess we can't have it all, right? ;) 

thank you

**Comment by rnarayana** [comment]
FWIW, this works for me:

```
public static IApplicationBuilder EnableSwagger(this WebApplication app)
    => app.UseSwagger(options =>
    {
        options.RouteTemplate = "abc/{documentName}/swagger.json"; //DO not replace {documentName}, see RouteTemplate documentation
    }).UseSwaggerUI(options =>
    {
        options.SwaggerEndpoint("v1/swagger.json", "v1");
        options.RoutePrefix = "abc";
    });
```

**Comment by Timovzl** [comment]
> FWIW, this works for me

+1

On top of this, my **controller routes also needed to be relative**. For example, a controller might have `Route("api/Orders/[action]")`, and the application might end up running under `host/whatever` instead of just `host`. The Swagger page would use `host/api/Orders/action`, but I needed `host/whatever/api/Orders/action`.

To also get relative behavior for determining routes to controller methods, I extended the solution as follows:

```cs
List<OpenApiServer>? cachedServerRepresentation = null;
app.UseSwagger(swagger => 
{
    swagger.RouteTemplate = "api/{DocumentName}/swagger.json";
    swagger.PreSerializeFilters.Add((swaggerDoc, httpRequest) =>
    {
        // Determine controller URLs dynamically, as we might not be running directly under the root
        swaggerDoc.Servers = cachedServerRepresentation ??=
        [
            // Strip '/api/V1/index.html' before adding e.g. '/api/Controller/action'
            new OpenApiServer() { Url = new Uri($"{httpRequest.Scheme}://{httpRequest.Host}{httpRequest.Path}/../../..").AbsoluteUri },
        ];
    });
});
app.UseSwaggerUI(swagger =>
{
    swagger.RoutePrefix = "api";
    swagger.SwaggerEndpoint("V1/swagger.json", "My Demo API");
});
```

Now everything is relative. 🙂

To also account for a proxy that uses a path prefix the application does not know about, I changed it to this:

```cs
List<OpenApiServer>? cachedServerRepresentation = null;
app.UseSwagger(swagger =>
{
    swagger.RouteTemplate = "api/{DocumentName}/swagger.json";
    swagger.PreSerializeFilters.Add((swaggerDoc, httpRequest) =>
    {
        // If behind a proxy, include the proxy's original path prefix when making API calls
        if (!environment.IsDevelopment() && httpRequest.Headers["X-Forwarded-Path"] is [string relativePath, ..])
        {
            // We receive something like "/ProxyPathPrefix/api/V1/swagger.json", so strip off "/api/V1/swagger.json" to extract the path prefix
            if (cachedServerRepresentation is null)
            {
                relativePath = $"{relativePath}/../../..";
                cachedServerRepresentation = [new OpenApiServer() { Url = relativePath }];
                app.Services.GetRequiredService<ILogger<SwaggerEndpointOptions>>().LogInformation("Set Swagger path prefix to {PathPrefix}", relativePath);
            }
            swaggerDoc.Servers = cachedServerRepresentation;
        }
    });
});
app.UseSwaggerUI(swagger =>
{
    swagger.RoutePrefix = "api";
    swagger.SwaggerEndpoint("V1/swagger.json", "My Demo API");
});
```

If you have `X-Forwarded-Prefix` available (which I do not), it is simpler to use that instead of navigating up (`/.../../..`) from `X-Forwarded-Path`.

Furthermore, if the proxy sends a different `X-Forwarded-Proto` and `X-Forwarded-Host`, those may be relevant to include as well.
