### ISSUE TITLE
Enabled AuthUsePkce for SwaggerUI but the server returns pkce_missing_challenge

### ISSUE THREAD

**Issue by babakdevoteam** [domaindrivendev/Swashbuckle.AspNetCore#2047]
I have already asked this in [stackoverflow](https://stackoverflow.com/questions/66438535/enabled-authusepkce-for-swaggerui-but-the-server-returns-pkce-missing-challenge), but did not get any response. 

I am using version v5.0.0 of Swashbuckle in my asp net core 3.1 app :

```
options.AddSecurityDefinition("OAuth2", new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.OAuth2,

            Flows = new OpenApiOAuthFlows
            {
                AuthorizationCode = new OpenApiOAuthFlow
                {
                    AuthorizationUrl = new Uri("https://my.okta.com/oauth2/v1/authorize"),
                    TokenUrl = new Uri("https://my.okta.com/oauth2/v1/token"),
                    Scopes = new Dictionary<string, string>
                        {
                        { "openid", "desc" }
                        },
                }
            },
            Description = "Balea Server OpenId Security Scheme"
        });
```

```
app.UseSwaggerUI(options =>
            {
            options.RoutePrefix = "docs";
          
            options.OAuthScopeSeparator(",");
            options.OAuthUsePkce();
            });
```

But the Auth server returns error :

pkce_missing_challenge

Here is the request log that Auth server receives :

/oauth2/v1/authorize?response_type=code&client_id=xxxxxxxxxxxxx&redirect_uri=https%3A%2F%2Flocalhost%3A8002%2Fdocs%2Foauth2-redirect.html&scope=openid&state=VHVlIE1hciAwMiAyMDIxIDExOjIyOjM3IEdNVCswMDAwIChXZXN0ZXJuIEV1cm9wZWFuIFN0YW5kYXJkIFRpbWUp

And when I inspect "v1/swagger.json" I do not see "usePkceWithAuthorizationCodeGrant" there.

**Comment by domaindrivendev** [comment]
I can't repro this issue in my OAuth2 test project, which targets `v6.1.0`. So, you'll need to create a minimal project that repro's and post to github where I can pull down and troubleshoot. Also, `usePkceWithAuthorizationCodeGrant` is a swagger-ui setting so you would see it in the HTML source of `/swagger/index.html` not in `v1/swagger.json`.

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
