### ISSUE TITLE
Is there a OrderActionGroupsBy equivalent in Swashbuckle.AspNetCore?

### ISSUE THREAD

**Issue by shaazsiddiqui** [domaindrivendev/Swashbuckle.AspNetCore#2051]
Just wondering if there is a OrderActionGroupsBy equivalent in AspNetCore so that groups can be custom ordered? Can documentFilter/operationFile be used to achieve this?

**Comment by martincostello** [comment]
Closing this out due to age - if you're still experiencing this problem with the latest version of Swashbuckle please open a new issue.
