### ISSUE TITLE
Raw file upload

### ISSUE THREAD

**Issue by Yuri6037** [domaindrivendev/Swashbuckle.AspNetCore#2055]
In one of my project, I need a custom IFormFile that allows uploads without forms, that is allow JavaScript to directly inject binary data to the server and let the server apply data verification and processing. This is especially useful for electron based clients.

The problem is Swagger is absolutely unable to understand this system.

Here is how it's setup:
- Each controller action function that deals with those raw files have a special [RawContent] attribute.
- The core Server module provides a special model binder in order to treat this RawContent as a direct byte block or Stream.

Here is my attempt at getting Swagger to display a file upload for these cases:
```C#
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
            foreach (var p in context.MethodInfo.GetParameters())
            {
                if (TypeUtils.GetAttribute<RawContent>(p) == null) //This is a utility function used to get a particular attribute a reflection object, consider this utility as working
                    continue;
                foreach (var op in operation.Parameters.Where(op => op.Name == p.Name).ToList())
                {
                    operation.Parameters.Remove(op);
                }
                if (operation.RequestBody == null)
                    operation.RequestBody = new OpenApiRequestBody();
                operation.RequestBody.Content.Add("application/octet-stream", new OpenApiMediaType
                {
                    Schema = new OpenApiSchema
                    {
                        Type = "object",
                        Properties =
                        {
                            ["Files"] = new OpenApiSchema
                            {
                                Description = "Upload file",
                                Type = "file",
                                Format = "binary"
                            }
                        },
                        Required = { "Files" }
                    }
                });
            }
    }
```

The current result of this is that at least the UI shows a request body instead of a broken query parameter, but shows a bad message: `Example values are not available for application/octet-stream media types.`. I expect it to show a file upload button. I know this is possible as I tested it with help of AXIOS under both Chrome and FireFox. You can just leave a dom File object as request body to AXIOS and just match the Content-Type of this request to the dom File.type.

**Comment by SpiritBob** [comment]
@Yuri6037 why are you even implementing all of that, when ASP.NET Core fully supports `application/octet-stream` content type?

Just access `HttpRequest.Body` and there's your stream with your raw bytes.

**Comment by Yuri6037** [comment]
The reason why I have this implementation is only for simplicity and to avoid errors when writing code that cannot directly manipulate streams but instead byte[].

I know there could be any number of file. In my case there will be a single file.

I'm not asking for swagger to implement it for application/octet-stream. I'm asking for swagger to allow an API that I can implement in order to let swagger know that it needs to activate a file upload button and let swagger know that it must not write any header but instead should write the raw content.

**Comment by SpiritBob** [comment]
@Yuri6037 It actually already supports that. I've edited my previous comment as I was talking non-sense at certain parts.

**Comment by Yuri6037** [comment]
As I expected this has absolutelly no effect. It still just says "Example values are not available for application/octet-stream media types.".

I tried both with "string" and "file" but still same message. It seem that if the request body has a content type of application/octet-stream then eveything is disabled. I'm using v6.1.0 with .NET Core 3.1

**Comment by SpiritBob** [comment]
> As I expected this has absolutelly no effect. It still just says "Example values are not available for application/octet-stream media types.".
> 
> I tried both with "string" and "file" but still same message. It seem that if the request body has a content type of application/octet-stream then eveything is disabled. I'm using v6.1.0 with .NET Core 3.1
I'm sorry for confusing you, but the message says it all. You can't have examples for a stream. What would that look like?

The error is being propagated by swagger-ui, so perhaps you should address this issue to them if you feel it's wrong?

When you click "Try it out", you'll see the button "Upload file", you'll be able to select your file, and then successfully make the request. If you need to explain what the user would need to write in the body, you can do that via the `Description` property.

**Comment by SpiritBob** [comment]
@Yuri6037 to further improve on the above, your original code wanted to make the body required, to do that you'd do the following:
```
operation.RequestBody.Required = true;
````

And if the idea behind an example would be to explain what a user would have to do, you can always set a description via `operation.RequestBody.Description`, but it doesn't seem to have any effect on this particular case. Someone else should explain why that is so.

**Comment by Yuri6037** [comment]
Thank a lot. I though it would show the file upload all the time. I think it could be better if swagger had a way to show a message that informs the use that after clicking Try it out he can upload a file.

**Comment by domaindrivendev** [comment]
@Yuri6037 - if anything, it sounds like this may be a potenial issue/suggestion for the swagger-ui project rather than Swashbuckle? Can we close this issue?

**Comment by Yuri6037** [comment]
I don't know I though it was an issue on the Swashbuckle implementation.

Anyway, the original problem of this issue is fixed, I'll close it.
