### ISSUE TITLE
[Question] How to change Locked Icon?

### ISSUE THREAD

**Issue by imclint21** [domaindrivendev/Swashbuckle.AspNetCore#2058]
Hi,

I tried all to change icon, using `[Authorize]` attribute, creating custom `IOperationFilter` etc, how is it possible to configure this?

![](https://user-images.githubusercontent.com/5221349/111012738-b1c12600-83a5-11eb-9b83-1bfab79db42b.png)

Best regards

**Comment by MarkLeMerise** [comment]
I'm not sue I understand if you're trying to 1) customize the literal lock icon graphic which shows up on the page, or 2) customize which operations require authorization. I suspect it's 2), but in case it's 1), you can [inject custom CSS](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#inject-custom-css) or provide your [own HTML template](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-indexhtml).

If it's indeed 2), I would recommend reading up on [the section on adding a security definition](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements). Specifically, there is a code sample showing how `[AuthorizeAttribute]` can be used to mark specific operations as authorized, meaning the lock icon will show up just on those operations.

**Comment by spaasis** [comment]
If you're concerned that the locked/unlocked is rendered "the wrong way around", check out this issue on swagger-ui https://github.com/swagger-api/swagger-ui/issues/4402
