### ISSUE TITLE
Version 6.0 and above can get the Summary comment of Action, but cannot get the content in the parameter comment param of Action

### ISSUE THREAD

**Issue by qcjxberin** [domaindrivendev/Swashbuckle.AspNetCore#2060]
Version 6.0 and above can get the Summary comment of Action, but cannot get the content in the parameter comment param of Action

**Comment by domaindrivendev** [comment]
Please provide detailed repro steps (including code samples) or better still, create a minimal application (i.e. start from empty project) that repro's the isse and post to github where I can pull down and troubleshoot.

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
