### ISSUE TITLE
[FromForm] param description not display.

### ISSUE THREAD

**Issue by msshim-dev** [domaindrivendev/Swashbuckle.AspNetCore#2062]
![1](https://user-images.githubusercontent.com/78785087/111398960-afddc680-8707-11eb-9c4e-4c53b4d8d0f5.PNG)
![2](https://user-images.githubusercontent.com/78785087/111398966-b409e400-8707-11eb-8ffd-3df11735a1b7.PNG)

Request Body parameters description not display.

**Comment by thiagoknop3** [comment]
Up

**Comment by bitilly** [comment]
i have same problem with version 6.x.x,
i solve it when downgrade to 5.6.3

**Comment by thiagoknop3** [comment]
I did the same , downgrade to 5.6.3 :(

**Comment by msshim-dev** [comment]
OMG...... Why the version goes up but the function goes down...

**Comment by datlam162** [comment]
I did the same, downgraded to 5.6.3, is there any updates on this?

**Comment by bbhxwl** [comment]
I also have this problem. Can I fix the latest version of the bug?

**Comment by bitilly** [comment]
sorry，i have no idea.



***@***.***
 
From: bbhxwl
Date: 2022-01-13 13:14
To: domaindrivendev/Swashbuckle.AspNetCore
CC: bitilly; Comment
Subject: Re: [domaindrivendev/Swashbuckle.AspNetCore] [FromForm] param description not display. (#2062)
I also have this problem. Can I fix the latest version of the bug?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DominicSaladin** [comment]
This still happens in version 6.4.0... Am I doing something wrong or is still not fixed?

**Comment by GrononS** [comment]
I am using version 6.5.0 and this is still a problem. I even installed Swashbuckle.AspNetCore.Annotations alongside this and it still doesn't work.

Please fix, this is a big oversight for me and is making my documentation pretty much useless since I use [FromForm] everywhere :(

**Comment by alexminza** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2519

**Comment by martincostello** [comment]
#3076
