### ISSUE TITLE
Bind document to an URL

### ISSUE THREAD

**Issue by Andrej997** [domaindrivendev/Swashbuckle.AspNetCore#2064]
Hi all,

Can I bind an url to a document? I want to publish my swagger api with 2 different DNS, i.e. 
myswagger.user.com and 
myswagger.admin.com 
I have 2 documents, one for users endpoint and one for admin endpoints.
How can I set to open users document (with user endpoints) when client enters myswagger.user.com and when client enters myswagger.admin.com to display admins document (with admin endpoints)?

Can you please help me with this..

Kind Regards,
Andrej

**Comment by domaindrivendev** [comment]
This can be accomplished relatively easily by leveraging ASP.NET Core's [URL Rewrite Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-5.0#regex-examples). Specifically, you would configure a custom rule that rewrites the `HttpContext.Request.Path` to a route that will be matched by the Swagger middleware.

- `myswagger.{documentName}.com` => `/swagger/{documentName}/swagger.json`

Here's a quick example I threw together and was able to get working for me:

```csharp
// Startup.cs
public void ConfigureServices(IServiceCollection services)
{
    ...

    services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("admin", new OpenApiInfo { Title = "Admin API", Version = "v1" });
        c.SwaggerDoc("public", new OpenApiInfo { Title = "Public API", Version = "v1" });
    });
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    var rewriteOptions = new RewriteOptions().Add(new SwaggerEndpointRewriteRule());
    app.UseRewriter(rewriteOptions);

    app.UseSwagger();

    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("http://myswagger.admin.com", "Admin API Docs");
        c.SwaggerEndpoint("http://myswagger.public.com", "Public API Docs");
    });

    ...
}
```

```csharp
// SwaggerEndpointRewriteRule.cs
public class SwaggerEndpointRewriteRule : IRule
{
    public void ApplyRule(RewriteContext context)
    {
        var request = context.HttpContext.Request;

        if (request.Host.Value.StartsWith("myswagger.") && request.Path.Value == "/")
        {
            var documentName = request.Host.Value.Split('.')[1];

            request.Path = $"/swagger/{documentName}/swagger.json";
        }

        context.Result = RuleResult.ContinueRules;
    }
}
```

**Comment by Andrej997** [comment]
Dear @domaindrivendev 

Thank you for the quick response, but this does not open the swagger ui with endpoints, it opens the page with json model of the document.
Is there a way to open the document ui?

**Comment by domaindrivendev** [comment]
To create per-document versions of the UI, you can wire up multiple instances of the swagger-ui middleware as follows:

```csharp
app.UseSwaggerUI(c =>
{
    c.RoutePrefix = "swagger/admin";
    c.SwaggerEndpoint("/swagger/admin/swagger.json", "Admin API Docs");
});

app.UseSwaggerUI(c =>
{
    c.RoutePrefix = "swagger/public";
    c.SwaggerEndpoint("/swagger/public/swagger.json", "Public API Docs");
});
```

Now, you will have a dedicated path for the admin docs and the public docs - `/swagger/admin` and `/swagger/public` respectively. This may be enough to suit your needs. However, it sounds like you also want to use subdomains instead of paths to distinguish between the two API sections. Again, I would refer you to the URL Rewrite middleware for this. Here's a basic example that I was able to get working:

```csharp
public void ApplyRule(RewriteContext context)
{
    var request = context.HttpContext.Request;

    // Need to perform the rewrite for all the swagger-ui assets
    var swaggerUIPattern = new Regex(@"^/(.+\.(?:html|js|css))?$");

    if (request.Host.Value.StartsWith("myswagger.") && swaggerUIPattern.IsMatch(request.Path))
    {
        var documentName = request.Host.Value.Split('.')[1];

        request.Path = swaggerUIPattern.Replace(request.Path, $"/swagger/{documentName}/$1");
    }

    context.Result = RuleResult.ContinueRules;
}
```

**Comment by Andrej997** [comment]
Dear @domaindrivendev I wanted to achieve when I enter 
https://myswagger.user.com/index.html that it opens swagger ui with user document (with user endpoints) and when I enter
https://myswagger.admin.com/index.html that it opens swagger ui with admin document (with admin endpoints)

**Comment by domaindrivendev** [comment]
Yes, I understand the requirement. I believe I've given you more than enough information to accomplish this.
