### ISSUE TITLE
nullable attributes disappeared from OpenAPI contract after updating to 6.0.7 from 5.6.3 

### ISSUE THREAD

**Issue by dmytribaglai** [domaindrivendev/Swashbuckle.AspNetCore#2065]
Here is what has been generated on 5.6.3:

> "/api/beta/contact": {
>       "get": {
>         "tags": [
>           "Contact"
>         ],
>         "operationId": "get_contact",
>         "parameters": [
>           {
>             "name": "ContactId",
>             "in": "query",
>             "schema": {
>               "type": "string",
>               **"nullable": true**
>             }
>           },

And after an upgrade to 6.0.7:

> "/api/beta/contact": {
>       "get": {
>         "tags": [
>           "Contact"
>         ],
>         "operationId": "get_contact",
>         "parameters": [
>           {
>             "name": "ContactId",
>             "in": "query",
>             "schema": {
>               "type": "string"
>             }
>           },

Nothing else has been changed, just the Swashbuckle version. Any ideas why this might be happening?

**Comment by domaindrivendev** [comment]
The previous behavior was wrong - the new behavior (as of `6.0.0`) is correct . We're getting deep into the semantics of the OpenAPI specification here, but by stating that the `ContactId` _query_ parameter is `nullable: true` means (categorically) that the following is a valid way to call the endpoint: 

`GET /api/beta/contact?ContactId=null`

Now, in a typical ASP.NET Core app, this will cause model binding to populate the corresponding C# parameter/property with a literal _string_ value of `"null"` as opposed to the `null` value. So, for an ASP.NET app, the `nullable` keyword is non-sensical for query parameters and so Swashbuckle no longer emits it in that case.

So, based on your question, I think you may be misunderstanding the meaning of `nullable:true`. As stated in the [OpenAPI docs](https://swagger.io/docs/specification/describing-parameters/) it is NOT the same thing as optional (i.e. omitting it from the URL entirely) and it is NOT the same thing as empty-valued (e.g. `/api/beta/contact?ContactId`):

> Note: nullable is not the same as an optional parameter or an empty-valued parameter. nullable means the parameter value can be null. Specific implementations may choose to map an absent or empty-valued parameter to null, but strictly speaking these are not the same thing.

**Comment by dorthl** [comment]
So how should we mark that a certain query parameter can not be passed?

**Comment by dorthl** [comment]
@domaindrivendev
