### ISSUE TITLE
Swagger UI is sending request as `http` instead of `https` after upgrading `Swashbuckle.AspNetCore` nuget package to 5.6.0

### ISSUE THREAD

**Issue by PreetiSinghal1989** [domaindrivendev/Swashbuckle.AspNetCore#2069]
Hi,

I'm experiencing this issue after I upgraded the `Swashbuckle.AspNetCore` nuget package to `5.6.0` from `5.5.0`. Swagger UI seems to be sending the request over `http` protocol instead of `https`, although the swagger page itself is hosted on `https`.

![image](https://user-images.githubusercontent.com/21296584/112399223-7ab71280-8ccb-11eb-96a2-099be28398b6.png)

It throws `TypeError: Failed to fetch`.

The difference that I noticed on swagger page before and after upgrading the package is as below:

Before:
![image](https://user-images.githubusercontent.com/21296584/112399539-07fa6700-8ccc-11eb-94bb-8f8c7ff24e83.png)

After:
![image](https://user-images.githubusercontent.com/21296584/112399502-f0bb7980-8ccb-11eb-9020-9d9d5e3f68e5.png)

Before upgrading the package, it didn't have the `servers` array in the response which, I believe, might be related to the change that was released in 5.6.0:

```
Better support for reverse proxy environments, incl. assigning servers metadata based on the presence of common reverse proxy headers
```
Also, notice that the server url has the `http` scheme instead of `https`. Please let me know if there is any other information needed.

**Comment by jhoward321** [comment]
I've been seeing the same issue, it's throwing CORs errors on the console

**Comment by pankti11** [comment]
I am seeing the same issue after updating

**Comment by alexrosenfeld10** [comment]
Same issue here

**Comment by pankti11** [comment]
By updating the version to 6.1.1 resolved the issue for me.

**Comment by alexrosenfeld10** [comment]
I have the same issue on 6.1.1

**Comment by alexrosenfeld10** [comment]
I just added a 

```csharp
                options.PreSerializeFilters.Add((document, request) =>
                {
                    var scheme = request.Host.Host.StartsWith("localhost", StringComparison.OrdinalIgnoreCase)
                        ? "http"
                        : "https";
                    document.Servers = new[]
                    {
                        new OpenApiServer
                        {
                            Url = $"{scheme}://{request.Host}"
                        }
                    };
                });
```
to get around the issue

**Comment by foolnidiot** [comment]
Encountered the same issue on v6.2.1

**Comment by martincostello** [comment]
Closing this out due to age - if you're still experiencing this problem with the latest version of Swashbuckle please open a new issue.
