### ISSUE TITLE
OIDC SecurityDefinition does not work well with OAuthUsePkce

### ISSUE THREAD

**Issue by lordldx** [domaindrivendev/Swashbuckle.AspNetCore#2072]
I have my .NET 5 API app configured as follows:

In my ConfigureServices:
```
services.AddSwaggerGen(c => {
  c.SwaggerDoc("v1", new OpenApiInfo { Title = "MyApp", Version = "v1" });
  c.AddSecurityDefinition("OIDC", new OpenApiSecurityScheme
  {
    Type = SecurityScheme.OpenIdConnect,
    OpenIdConnectUrl = new Uri("<url-to-a-.well-known/openid-configuration>")
  });
});
```

In my Configure:
```
app.UseSwaggerUI(c =>
                {
                    c.SwaggerEndpoint("/swagger/v1/swagger.json", "MyApp v1");
                    c.OAuthUsePkce();
                });
```

If I then run my app, go to the swaggerui and try to authorize, I get **AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.**

When I use SecurityScheme.OAuth2, and I manually configure the definition, then I don't have this issue.
Since OIDC is just a usability layer on top of oauth2, I guess that `OAuthUsePkce()` should work with oidc out of the box as well.

**Comment by lordldx** [comment]
Looks like this was already fixed in swagger-ui: https://github.com/swagger-api/swagger-ui/commit/5e69d3c4f2a3b95bbb3b15d3151fc7d630b1164c

Perhaps just updating to a newer swagger-ui will fix this?
I'm assuming no breaking changes here...

**Comment by stjimmy54** [comment]
> Perhaps just updating to a newer swagger-ui will fix this?

I think so too. 

Update swagger-ui please.

**Comment by domaindrivendev** [comment]
Releaed with `6.1.2`
