### ISSUE TITLE
I want to be able to load the API document on the Action of the controller.

### ISSUE THREAD

**Issue by ShuiFan0** [domaindrivendev/Swashbuckle.AspNetCore#2073]
I want to be able to load the API document on the Action of the controller.

Because my program is lazy to load, I have no idea how much API it will eventually load at startup.

So I want to be able to generate the Swagger page on the Action of the controller based on the input parameters and load the API document that I generated at the specified path.

Please tell me how I can do it. And the extent to which Swagger supports lazy loading.

**Comment by domaindrivendev** [comment]
I don't understand what you're asking for here. Could you please try articulate it more clearly - perhaps some screenshots or code samples would help?

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.

**Comment by ShuiFan0** [comment]
> 请提供[ 可再现的最小例子](https://stackoverflow.com/help/minimal-reproducible-example) 作为一个GUUUB存储库,它演示了您正在经历的问题,因此我们可以进一步研究这个问题。

in c# .net core 8.0, for webSocket action use this 
```
[Route("[action]")]
```
this will throw a error for api doc.
I want to ignore the webSocket action for api doc.

**Comment by ShuiFan0** [comment]
> Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.

I'm sorry。I've forgotten what I want because it's been so long.
I thought it was my latest problem.

**Comment by martincostello** [comment]
> I want to ignore the webSocket action for api doc.

[Hide the action like this](https://stackoverflow.com/a/41624105).
