### ISSUE TITLE
OAuth2 redirect breaks in UI hosted by URL without index.html in path

### ISSUE THREAD

**Issue by whyleee** [domaindrivendev/Swashbuckle.AspNetCore#2076]
We use URL rewriting to host Swagger UI by root URL "/" instead of "/index.html" to fix load balancer pings, because the load balancer can't follow 301-s to "/index.html" and it's a problem for us to ping another URL there.

```cs
app.UseRewriter(new RewriteOptions().AddRewrite("^$", "/index.html", skipRemainingRules: true));
```

This breaks OAuth2 redirect URL, because in Swashbuckle custom UI [index.html](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerUI/index.html) file the code expects UI is always hosted by URL ending with "/index.html":

```js
// If oauth2RedirectUrl isn't specified, use the built-in default
if (!configObject.hasOwnProperty("oauth2RedirectUrl"))
    configObject.oauth2RedirectUrl = window.location.href.replace("index.html", "oauth2-redirect.html").split('#')[0];
```

Steps to reproduce:

1. Install latest `Swashbuckle.AspNetCore` version
2. Configure Swagger and Swagger UI with OAuth2 in Startup
3. Add server-side URL rewrite from "/" to "/index.html"
4. Open Swagger UI and try to Authorize

**Expected**: after successful sign-in, user is redirected back to Swagger UI with authenticated state

**Actual**: after successful sign-in, user is redirected back to Swagger UI without authentication

I'm going to push a PR with the fix shortly.

Current workaround:

1. Create custom "index.html" file based on Swashbuckle [index.html](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerUI/index.html)
2. Make a fix in your file
   ```js
   configObject.oauth2RedirectUrl = (window.location.href.replace("index.html", "") + "oauth2-redirect.html").split('#')[0];
   ```
3. Load it in Swagger UI middleware options:

   ```cs
   var assembly = GetType().Assembly;
   
   app.UseSwaggerUI(c =>
   {
       c.IndexStream = () => assembly.GetManifestResourceStream("index.html");
   });
   ```

**Comment by domaindrivendev** [comment]
I believe this is already fixed by #2128
