### ISSUE TITLE
Migrate Appveyor to a GitHub Actions pipeline

### ISSUE THREAD

**Issue by aleks-ivanov** [domaindrivendev/Swashbuckle.AspNetCore#2084]
Migrate the Appveyor implementation to a single GitHub Actions pipeline for all the required automated processes with the addition of other native GitHub goodies like automated GH release, secure token vault etc.

We can start working on this promptly, just please let us know if you are interested in the implementation of the idea 🙂

Check out quick video presentations of our latest DevOps contributions to the [Notepads](https://www.youtube.com/watch?v=StzaanSf99k) and [MimeKit](https://www.youtube.com/watch?v=jtiaXUkHEl8) projects, to get an idea of what we would like to contribute to Swashbuckle.AspNetCore.

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by martincostello** [comment]
#2775
