### ISSUE TITLE
SwaggerIgnore attribute for ignoring specific properties

### ISSUE THREAD

**Issue by korggy** [domaindrivendev/Swashbuckle.AspNetCore#2085]
I would like to request a [SwaggerIgnore] attribute for ignoring specific properties in the schema.

I found a StackOverflow discussion here, but it's not exactly what I'm looking for:
https://stackoverflow.com/questions/41005730/how-to-configure-swashbuckle-to-ignore-property-on-model

The current approach is to use JsonIgnore, but this also removes the property from serialization. I still want to be serialize the value but remove it from documentation, i.e. in the case that I have an "internal only" property that is used by our own team in special cases but not available to 3rd parties.

The other approach discussed in the StackOverflow post is to write a custom schema filter and register it during startup, but this seems overly complex.

As an alternative, perhaps this could be added as [SwaggerSchema(Ignore = true)] ?

**Comment by Reapism** [comment]
If you are using .NET 5, or latest aspnet swashbuckle (6.1.4), the documentation says if you are using System.Text,Json, Swagger will honor the options of the serializer. However, if you use Newtonsoft.Json, you have to an extension method in your swagger configuration

`dotnet add package --version 5.3.1 Swashbuckle.AspNetCore.Newtonsoft`

`services.AddSwaggerGenNewtonsoftSupport(); // explicit opt-in - needs tobe placed after AddSwaggerGen();`

### This does not seem to be working in latest swashbuckle asp.net core

**However**, for the record, I am using `System.Text.Json` and using the `[JsonIgnore]` attribute and Swagger doesn't seem to honor it.

.NET5,  Latest aspnet swashbuckle (6.1.4)

Code piece:
```
public sealed class AdministratorRegistrationRequest : RegistrationRequest, IRequest<ApiResponse<RegistrationResponse>>
{
    [JsonIgnore]
    public override string UserType { get; protected set; } = UserTypeConstants.Administrator;
}
```

Swagger generates with the parameter.

![image](https://user-images.githubusercontent.com/1627999/118072705-6b258300-b378-11eb-8391-6103e715fc7d.png)

**Comment by TomasSobotaT** [comment]
P0p

**Comment by martincostello** [comment]
#2610
