### ISSUE TITLE
Swagger-UI download link returns incorrect characters when Content-Type is "text/plain; charset=iso-8859-1"

### ISSUE THREAD

**Issue by adolfsson** [domaindrivendev/Swashbuckle.AspNetCore#2087]
I have created an API operation which, among other file formats, returns plain text files with ISO-8859-1 (latin-1) encoding. A direct link to the API operation correctly downloads the file through the browser with the correct encoding, but clicking the "Download file" link in the Swashbuckle Swagger UI will return the file with some incorrect characters (hex EF BF BD). 

The problem probably occurs because the Swagger-UI somewhere internally assumes that the encoding is UTF-8, please see  https://stackoverflow.com/questions/6543548/whats-going-on-with-this-byte-array

When I click the "Download file" link, the Content-Type header of the response is correctly set to "text/plain; charset=iso-8859-1", but the body data has been mangled.

The controller code is below. The mimeType variable has the value "text/plain; charset=iso-8859-1" when the error occurs.

This leads to problems with characters like åäöÅÄÖ. All of them are replaced with three bytes, hex EF BF BD.

The binary files downloaded through the same operation, PDFs and Excel files, are working fine.

````
        [HttpGet]
        [Produces("text/plain; charset=iso-8859-1", Constants.MimeTypeApplicationPDF, Constants.MimeTypeModernExcel, Constants.MimeTypeApplicationJson)]
        [ProducesResponseType(typeof(FileContentResult), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(ODataErrorResponse), StatusCodes.Status404NotFound)]
        [ProducesResponseType(typeof(ODataErrorResponse), StatusCodes.Status500InternalServerError)]
        public IActionResult GetById(Guid id)
        {
            string mimeType;
            string fileName;
            byte[] binaryFileContents = _binaryFileService.Get(id, out mimeType, out fileName);
            if(binaryFileContents == null)
            {
                var target = $"{id}";
                return NotFound(ODataErrorHelper.CreateNotFoundError(target));
            }

            return File(binaryFileContents, mimeType, fileName);
        }
````

The difference between using the "Download file" link and downloading the file through the "Request URL" is visible in the lower right corner of this image, please notice the "encoding" of the character "Ö". 

![image](https://user-images.githubusercontent.com/16435892/114433279-ea7d3680-9bc1-11eb-970d-26ce2b2403fb.png)

Version: Swashbuckle.AspNetCore 6.1.2

**Comment by rfelgent** [comment]
same problem here when handling "application/xml" files having encoding ISO-8859-1 

my current work around is to set "content-type: application/octet-stream" and "content-encoding:ISO-8859-1". The swagger-ui download link is not corrupted anymore
