### ISSUE TITLE
Question: RequestSnippetsEnabled Option Exposed?

### ISSUE THREAD

**Issue by KayakFisher205** [domaindrivendev/Swashbuckle.AspNetCore#2093]
I noticed the CURL command changed and according to the group at swagger-api, it was changed to BASH style. They said if the requestSnippetsEnabled option was exposed, I could enable the Windows specific cURL command.

**Comment by domaindrivendev** [comment]
While the SwaggerUI middleware doesn't currently have a _top-level_ config method for this, it does have a mechanism to add any config items you like. For example, I was able to enable the request snippets plugin as follows:

```csharp
app.UseSwaggerUI(c =>
{
    c.ConfigObject.AdditionalItems.Add("requestSnippetsEnabled", true);
});
```

Might be worth playing around with this technique to get the behavior you're looking for. Also, if you get it figured out, you could possibly submit an MR to add support for this on the top-level / strongly-typed config options 😉

**Comment by KayakFisher205** [comment]
Thanks. I tested this code and it works. Be nice to be able to move the tabs or hide them. However, thats beyond my skill haha.
Thanks for the help.
