### ISSUE TITLE
Multiple Versions in same document (I.E no grouping)

### ISSUE THREAD

**Issue by VisualBean** [domaindrivendev/Swashbuckle.AspNetCore#2098]
All examples I have seen so far, go the direction of having 1 OpenAPI spec, per supported Version.
I would like to simply support multiple versions in the same OpenAPI spec. - I however cannot seem to get this to work (most likely due to routing issues).
I am currently supporting multiple versions with multiple version strategies.
Header and Route based versioning supported.

Pre net core I would do a route factory and a route constraint, this has since changed and I am at a loss on how to solve this.

my routing attributes are pretty standard and looks like this
```csharp
    [Route("api/[controller]")]
    [Route("api/v{version:apiVersion}/[controller]")]
```
The problem is the spec generation due to routing clashes.

- what hooks do I have now to control the generation - It seems OperationFilters are not hit till after the fact? 

(haven't looked much into this complexity since pre-core 🙂

**Comment by martincostello** [comment]
Closing this out due to age - if you're still experiencing this problem with the latest version of Swashbuckle please open a new issue.
