### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by HristoYankovTR** [domaindrivendev/Swashbuckle.AspNetCore#2099]
![image](https://user-images.githubusercontent.com/80719600/115608295-b5e93900-a2ab-11eb-8def-acd1be41c2fe.png)

The documentation should make it clear that the class needs to be `static` as well. Otherwise this doesn't work.

**Comment by domaindrivendev** [comment]
The method needs to be static not the class and that’s explicitly called out in the docs 🤔

**Comment by HristoYankovTR** [comment]
`Debugger.Launch();` in the method does not kick off a debugger, unless the class is `static` itself, leading me to believe that method is not invoked at all, unless the class is `static`.

**Comment by domaindrivendev** [comment]
As confirmed by a “working” example:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8090cf8f2c9f46e7a35119ba5d6fe170b7985a5e/test/WebSites/CliExampleWithFactory/SwaggerHostFactory.cs
