### ISSUE TITLE
Swagger UI doesn't show string type's description.

### ISSUE THREAD

**Issue by ndthanhdev** [domaindrivendev/Swashbuckle.AspNetCore#210]
I expected "event was added" but actuality is "string"

![image](https://cloud.githubusercontent.com/assets/16331812/19846649/bf0398e0-9f73-11e6-8f67-2cc1057f03d4.png)

![image](https://cloud.githubusercontent.com/assets/16331812/19846525/ade123a8-9f72-11e6-893a-96e27919778e.png)

**Comment by domaindrivendev** [comment]
This is really an issue for [swagger-ui](https://github.com/swagger-api/swagger-ui) and not Swashbuckle. I'm happy to keep this issue so that we can track it, but if you want to get it resolved any time soon you'll need to create an issue in that repo

**Comment by domaindrivendev** [comment]
Fixed as of release 2.0.0, which includes swagger-ui 3.x.
