### ISSUE TITLE
Using post-build command "dotnet swagger tofile..." fails trying to perform http request

### ISSUE THREAD

**Issue by nobba75** [domaindrivendev/Swashbuckle.AspNetCore#2103]
Version 6.1.3.

Have used the post build step successfully for some time. 
Now trying to add IdentityServer4 support and more specifically set the token validation parameters. For this I need to contact the identity server instance to get the signing keys.

However, when the Swashbuckle swagger command runs it seems to "execute" the signing keys retrieval, which obviously fails since it isn't, and shouldn't have to be, available during build.

Feels like I have misunderstood something regarding what the document generation actually does. Anyway I don't understand how I can avoid the generation from trying to contact IdSrv4 during build. Does someone have an explanation and/or a solution?

**Comment by martincostello** [comment]
Closing this out due to age - if you're still experiencing this problem with the latest version of Swashbuckle please open a new issue.
