### ISSUE TITLE
"no operations defined in spec" in .net 5.0

### ISSUE THREAD

**Issue by JoAlnilam** [domaindrivendev/Swashbuckle.AspNetCore#2108]
Hi I am using version 6.1.3 with .net core 5.0 web api project. I keep getting "<b>no operations defined in spec</b>" although my controllers are correctly constructed. So generator doesn't discover api in the dll. Could it be 5.0 combability issue?
Here is a set I have: 
<code>

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddRouting(options => options.LowercaseUrls = true);

        services.AddApiVersioning(options =>
        {
            options.ReportApiVersions = true;
            options.ApiVersionReader = new UrlSegmentApiVersionReader();
        });

        services.AddControllers();

        services.AddApiVersioning();

        services.AddMvcCore().AddApiExplorer();

        services.AddSwaggerGen(c =>
        {
            c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
        });
    }

 public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
 {
        
        app.UseForwardedHeaders(new ForwardedHeadersOptions { ForwardedHeaders = ForwardedHeaders.All });

        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseMiddleware(typeof(ExceptionsHandlingMiddleware));

        app.UseHealthChecks("/health");

        app.UseHttpsRedirection();

        app.UseCors(policy => policy.AllowAnyOrigin().AllowAnyHeader());

        app.UseSwagger();

        app.UseSwaggerUI(c =>
        {
            c.SwaggerEndpoint("v1/swagger.json", "My REST API");
        });

        app.UseRouting();

        app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
    }

</code>

<code>

    [ApiController]
    [Route("api/[controller]")]
    public class ModelsController : ControllerBase
    {

</code>

**Comment by domaindrivendev** [comment]
I suspect this may be related to interplay between ApiVersioning and Swashbuckle. IIRC, there’s some specific steps you have to apply (documented on the ApiVersioning repo) to get the two to work well together.

**Comment by domaindrivendev** [comment]
Please take a look there and if that doesn’t help, create a sample app that repro’s and post to GitHub so I can pull down and troubleshoot?

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.

**Comment by sep96** [comment]
Here's a step-by-step approach to troubleshoot:

Check your controller:
```

[ApiController]
[Route("api/[controller]")]
public class YourController : ControllerBase
{
    [HttpGet]
    public IActionResult Get()
    {
        // Implementation
    }
}
```
Verify your Startup.cs (or Program.cs for .NET 6+):

```
services.AddControllers();
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Your API", Version = "v1" });
});
```
Ensure you're calling the necessary methods in Configure:

```
app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Your API v1"));
```
If using .NET 6+ minimal APIs, make sure your endpoints are defined:
`
app.MapControllers();`
Check your project file (.csproj) to ensure XML documentation is generated:

```
<PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <NoWarn>$(NoWarn);1591</NoWarn>
</PropertyGroup>
```
