### ISSUE TITLE
Nullable enum does not generate nullable property when using StringEnumConverter

### ISSUE THREAD

**Issue by tomhreb** [domaindrivendev/Swashbuckle.AspNetCore#2110]
Hello,
I'm using Swashbuckle.AspNetCore.Annotations version 6.1.3 in netcoreapp3.1.
I have `ConfigureServices` as follows:
```            
services.AddControllers()
  .AddNewtonsoftJson(options =>
  {
      serializerSettings.NullValueHandling = NullValueHandling.Ignore;
      options.SerializerSettings.Converters.Add(new StringEnumConverter());
  });

services.AddSwaggerGen(c => { .... })
  .AddSwaggerGenNewtonsoftSupport();
```

I have following `Response` class and `ResponseType` enum:
```
enum ResponseType{ A, B, C }

class Response
{
    public ResponseType? Type { get; set; }
}
```

In generated swagger.json, the `Type` property is not marked as nullable.
```
"Type": {
  "$ref": "#/components/schemas/ResponseType"
}

"ResponseType": {
    "enum": [ "A", "B", "C" ],
    "type": "string"
}
```

**Comment by Eneuman** [comment]
Try add the option "c.UseAllOfToExtendReferenceSchemas();" and see if that fixes it?

Refs cannot be marked as nullable so this might be a workaround.

**Comment by kipusoep** [comment]
UseAllOfToExtendReferenceSchemas did not work for me :-(

**Comment by martincostello** [comment]
To make issue tracking a bit less overwhelming for the new maintainers (see #2778), I've created a new tracking issue to roll-up various nullability issues here: #2793.

We'll refer back to this issue from there and include it as part of resolving that issue, but I'm going to close this one to help prune the backlog.
