### ISSUE TITLE
Cannot resolve symbol 'EnableAnnotations' in 7.0.3

### ISSUE THREAD

**Issue by tjmcdonough** [domaindrivendev/Swashbuckle.AspNetCore#2111]
Your latest release in GitHub is 6.1.0 but in NuGet is 7.0.3. Has the static method EnableAnnotations() for SwaggerGenOptions been deleted?

**Comment by domaindrivendev** [comment]
No - that method has not been removed. Also, I'm not sure what packages you're looking at but the latest version in Nuget is `6.1.3`. The corresponding github tag hadn't been published as a release but I just did that now so both should match. 

![screenshot](https://user-images.githubusercontent.com/1434343/116451950-0dac1500-a855-11eb-9c2d-df513fc58254.png)
