### ISSUE TITLE
Nullable property of a complex type

### ISSUE THREAD

**Issue by coder925** [domaindrivendev/Swashbuckle.AspNetCore#2116]
I have a feature request that a property of a complex type should be marked as nullable when using `c.SupportNonNullableReferenceTypes()`.

The following class:
```CSharp
public class Person
{
    public string Name { get; set; } = string.Empty;
    public string? Title { get; set; }
    public Address? Address { get; set; }
}
```
generates this specification:
```JSON
"Person": {
    "type": "object",
    "properties": {
        "name": {
           "type": "string"
        },
        "title": {
           "type": "string",
           "nullable": true
        },
        "address": {
           "$ref": "#/components/schemas/Address"
        }
    },
    "additionalProperties": false
}
```

The two _primitive types_ (`Name` and `Title`) are correctly defined in regard to nullable. However, the one _complex type_ (`Address`) is not correctly defined as nullable from what I can tell.

For my client generation to Typescript I'm using [openapi-generator](https://github.com/OpenAPITools/openapi-generator). It will currently generate the Address property as non-nullable. I'm not aware of any known workaround.

**Version**: `<PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.4" />`
**Sample project**: [openapigenerator-complextype](https://github.com/coder925/openapigenerator-complextype/tree/main/server-dotnet)

**Comment by Eneuman** [comment]
@coder925 I thinks this works today, but you need to add the option "c.UseAllOfToExtendReferenceSchemas();" since references cannot be marked as null if I'm not misstaken.

**Comment by coder925** [comment]
Thank you @Eneuman ! I was not aware of that option. I wish `UseAllOfToExtendReferenceSchemas()` had been mentioned anywhere in the [docs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md) .

It now works perfectly in my sample! In my real-world project I get some additional warnings in the openapi-generator. I will try to dig into these:
- ```
  [main] WARN  o.o.codegen.DefaultCodegen - The following schema has undefined (null) baseType. It could be due to form parameter defined in OpenAPI v2 spec with incorrect consumes. A correct 'consumes' for form parameters should be 'application/x-www-form-urlencoded' or 'multipart/?' ```
- ```
  [main] WARN  o.o.codegen.DefaultCodegen - schema: class ComposedSchema {
    class Schema {
        type: null
        format: null
        $ref: null
        description: The most essential details of the sales order.
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        not: null
        properties: null
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }
    allOf: [class Schema {
        type: null
        format: null
        $ref: #/components/schemas/SalesOrder
        description: null
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        not: null
        properties: null
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }]
    anyOf: null
    oneOf: null
  } 
  ```
- ```
  [main] WARN  o.o.codegen.DefaultCodegen - codegenModel is null. Default to UNKNOWN_BASE_TYPE
  ```

**Comment by coder925** [comment]
After enabling `c.SupportNonNullableReferenceTypes()`, the _requestBody_ schema will change even if it is non-nullable.

From:
```
"post": { "requestBody": { "content": { "application/json": {
  "schema": {
    "$ref": "#/components/schemas/Person"
  }

```

To:
```
"post": { "requestBody": { "content": { "application/json": {
  "schema": {
    "allOf": [ {
      "$ref": "#/components/schemas/Person"
     }]
```

This is the reason I receive warnings/errors by the _typescript-angular_   [openapi-generator](https://github.com/OpenAPITools/openapi-generator).

Is this a correct specification syntax? If so, I guess this is an issue of the client generator.
