### ISSUE TITLE
dotnet swagger tofile fails if any parameters contain spaces (even if quoted)

### ISSUE THREAD

**Issue by phil-allen-msft** [domaindrivendev/Swashbuckle.AspNetCore#2117]
Version 5.6.3 -> 6.1.4

1) Create a .NET Core 3.1 project that correctly references and uses Swashbuckle.AspNetCore.
2) Install the Swashbuckle.AspNetCore.Cli tool in the project
3) Run the tool as `dotnet swagger tofile --serializeasv2 --output "Path With\Space To\swagger.json" "Path With\Space To\SwashbuckeUsingBinary.dll" v1`

RESULT:
Usage: dotnet swagger _tofile [options] [startupassembly] [swaggerdoc]

startupassembly:
  

swaggerdoc:
  

options:
  --output:  
  --host:  
  --basepath:  
  --serializeasv2:  
  --yaml:  

NOTE:
The options output doesn't have any helpful display text; the "tofile" command runner has helpful display text on each option, but the "_tofile" command runner does not.  "_tofile" is running because "tofile" calls "_tofile" (for runtime configuration reasons) by invoking a new process using "dotnet exec", but it seems that the parameters enclosed by meaningful double-quotes for "tofile" aren't re-enclosed with meaningful double-quotes for "_tofile", so "_tofile" sees that there are far too many arguments, runs "PrintUsage", and returns.

EXPECT:
Swagger to be generated at "Path With\Space To\Swagger.json".

**Comment by domaindrivendev** [comment]
If you can submit a PR for this fix, I’d be happy to put out a patch release

**Comment by zsharp-gls** [comment]
Is there a timeline on when this patch will be released?

**Comment by bradygaster** [comment]
@domaindrivendev - did some analysis of a few of the failure cases we're seeing and it'd be great if #2125 could get released, as the fix from @phil-allen-msft resolves what looks like a large source of errors. Thanks for the consideration on this!

**Comment by domaindrivendev** [comment]
Released with `v6.1.5`
