### ISSUE TITLE
Ability to change the operations order

### ISSUE THREAD

**Issue by ekjuanrejon** [domaindrivendev/Swashbuckle.AspNetCore#2122]
Hello

I have a controller with 3 actions and each of them. I would like to change the order in which the swagger.json is generated. What is the best way of doing it?

Thanks

**Comment by wu-yafeng** [comment]
Configure `SortKeySelector` at your ``Startup.ConfigureServices(IServiceCollection services)``

``` csharp
services.AddSwaggerGen(options=>{
   options.SwaggerGeneratorOptions.SortKeySelector = descriptor => descriptor.ActionDescriptor.AttributeRouteInfo?.Order?.ToString() ?? descriptor.ActionDescriptor.DisplayName;
})
```
Mark route attribute such as `HttpGetAttribute` on your Controller Action.

``` csharp
[HttpGet(Order = 2)]
```
