### ISSUE TITLE
one time donation button?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [domaindrivendev/Swashbuckle.AspNetCore#2123]
i use this tool each day, so I  do not want continuous sponsors. can I do one time donation?

**Comment by domaindrivendev** [comment]
First of all - thank you so much for considering this. I put so many personal hours into this and still receive plenty of complaints about regression bugs, unavailable features etc. But, when I see people out there who truly appreciate the effort involved it makes it all worthwhile 💪

Regarding a one time donation, I’ve seen people workaround by creating a continuous and then cancelling after the first payment. I don’t know if there’s a simpler way - would be a good question for GitHub

**Comment by dzmitry-lahoda** [comment]
will wait ms to unblock me. that is silly, when I add a card to any app market, and got charged right away, but making so with github did not update my details for 5+ minutes. will wait.
![image](https://user-images.githubusercontent.com/757125/119768327-1e39c480-bec1-11eb-9256-3432829cb8bc.png)
and I cannot donate 40 USD, only 20 USD. so will have to wait for a month to disable it. 

i think donation  button should TOP in readme with several options to do so.

**Comment by martincostello** [comment]
See https://github.com/sponsors/domaindrivendev.
