### ISSUE TITLE
Swashbuckle.AspNetCore.Annotations can't be added to class library if class library is used in Blazor WebAssembly project

### ISSUE THREAD

**Issue by LockTar** [domaindrivendev/Swashbuckle.AspNetCore#2126]
Hi,

I have a simple C# Class Library with a class inside.
That class library is referenced from a ASP .NET Core 5 application for creating API's. That works fine.

I also want to use this class library from a Blazor webassembly project. When I add the reference to the blazor project, I get the following error message: 
`The project references the ASP.NET Core shared framework, which is not supported by Blazor WebAssembly apps. Remove the framework reference if directly referenced, or the package reference that adds the framework reference.`
This error message belongs to:
```
<Target Name="_FailIfReferencingAspNetCoreApp" BeforeTargets="ResolveRuntimePackAssets">
    <Error
      Code="BLAZORSDK1001"
      Text="The project references the ASP.NET Core shared framework, which is not supported by Blazor WebAssembly apps. Remove the framework reference if directly referenced, or the package reference that adds the framework reference."
      Condition="'@(FrameworkReference->WithMetadataValue('Identity', 'Microsoft.AspNetCore.App')->Count())' != '0'" />
  </Target>
```

When I remove the Nuget package `Swashbuckle.AspNetCore.Annotations` from my class library it all builds fine again.

I'm using the latest packages, frameworks etc. So:
.NET 5.0

- .NET 5.0 Blazor webassembly project with all packages to latest version
- .NET 5.0 Class library with `Swashbuckle.AspNetCore.Annotations` version `6.1.4`

Thanks

**Comment by xisimao** [comment]
hi ,i have the same problem，have you fix it?

**Comment by martincostello** [comment]
Swashbuckle depends on types that don't support Blazor, so by extension neither does Swashbuckle.
