### ISSUE TITLE
Upgrade swagger-ui and release date

### ISSUE THREAD

**Issue by WinniX** [domaindrivendev/Swashbuckle.AspNetCore#2127]
Hi Team,

May I ask a question about the next release date? The thing is that `swagger-ui` had an [issue](https://github.com/swagger-api/swagger-ui/pull/7206/files), that prevents a form from being submitted in some cases. It's already fixed, but we are waiting now for the `Swashbuckle` to pick up the new version of `swagger-ui` package.  

Could you give us a hint when we can expect the next release? 
Thank you in advance!

- Eugene

**Comment by martincostello** [comment]
There's been several releases since this issue was opened, and there'll be another in the near future.
