### ISSUE TITLE
Property of reference type(another Dto class) decorated with SwaggerSchemaAttribute, doesn't have nullable and description annotations

### ISSUE THREAD

**Issue by AlexanderPanov** [domaindrivendev/Swashbuckle.AspNetCore#2129]
Swashbuckle.AspNetCore Version: 6.1.4(currently latest stable)
Currently I think the issue is not specifically a UI concern.

Description:

I have properties on Dto classes returning another Dto. For them I don't see the annotations for 'nullable: true/false' and a description, provided in the SwaggerSchemaAttribute.
The behavior is different for properties which:
	1. Have a type of a List of the same other Dto(are array fields)
	2. Have type of string or a value type like number fields

Example Dto definition:
```
using Swashbuckle.AspNetCore.Annotations;
using System.Collections.Generic;

namespace Exposure.Model.Dto
{
	  [SwaggerSchema("This is a Sample Dto")]
	  public class SampleDto
	  {
	      [SwaggerSchema("This is single string property")]
	      public string SingleStringProperty { get; set; }

	      [SwaggerSchema("This is List string property")]
	      public List<string> ListStringProperty { get; set; }

	      [SwaggerSchema("This is single Dto property")]
	      public SecondSampleDto SingleDtoProperty { get; set; }

	      [SwaggerSchema("This is List Dto property")]
	      public List<SecondSampleDto> ListDtoProperty { get; set; }
	  }

	  [SwaggerSchema("This is a Second Sample Dto")]
	  public class SecondSampleDto
	  {
	      [SwaggerSchema("This is second single string property")]
	      public string SecondSingleStringProperty { get; set; }
	  }
}
```

Resulting swagger schema on the swagger page:
![image](https://user-images.githubusercontent.com/16353230/120235401-e5368280-c227-11eb-9669-74aa4efd6545.png)

**Comment by psaxton** [comment]
I'm having this same issue, even without using the SwaggerSchema attributes.

**Comment by Eneuman** [comment]
The OpenAPI specification has some issues regarding how nullabillity in complex types can be described.
Sometimes it nessecary to use "AllOf" to extend the schema so nullabillity can be described.

This can be done by using the c.UseAllOfToExtendReferenceSchemas(); options.
Try this and let me know if it fixes it

You can read more about this here: https://github.com/OAI/OpenAPI-Specification/issues/1368

**Comment by AlexanderPanov** [comment]
Hi @Eneuman,
thanks for your reply.
I tested and it is a way to enable nullable and description annotations on reference type properties.

I consider this answer a resolution to the issue.

Regards,
Alex

**Comment by mark-zhou** [comment]
I tried UseAllOfToExtendReferenceSchemas option but it's causing blank request object type names. Not sure if that's intended behavior but not a desirable side effect.

**Comment by Eneuman** [comment]
@mark-zhou Can show me a example of your code and the json it produces?

**Comment by mark-zhou** [comment]
Code is nothing special:

       public class Person
       {
              public string Name { get; set; }
              public int Age { get; set; }
       }

       [HttpPost("/abc")]
       public void Test([Required] Person person)
       { ...
       }

It generates an additional allOf in the json:

            "text/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Person"
                  }
                ]
              }
            }

This changes the UI, causing it to lose the Person tag in the schema view.

***@***.***D77E12.07E861E0]

But the real showstopper for me is that it causes OpenApi generator to emit UNKNOWN type name.

**Comment by mark-zhou** [comment]
Code is nothing special:

       public class Person
       {
              public string Name { get; set; }
              public int Age { get; set; }
       }

       [HttpPost("/abc")]
       public void Test([Required] Person person)
       { ...
       }

It generates an additional allOf in the json:

            "text/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Person"
                  }
                ]
              }
            }

This changes the UI, causing it to lose the Person tag in the schema view.

![image](https://user-images.githubusercontent.com/14211147/126524634-cad3c206-e82c-47c6-a7aa-a9427714add1.png)

But the real showstopper for me is that it causes OpenApi generator to emit UNKNOWN type name.

**Comment by mark-zhou** [comment]
FYI, my current workaround to this problem is manually setting the Nullable flag using a filer:

	foreach (var prop in schema.Properties)
	{
		if (prop.Key == "OptionalFieldA")
		{
			prop.Value.Nullable = true;
		}
	}

OptionalFieldA is already declared as a nullable type. So ideally I shouldn't need to do that.

**Comment by Eneuman** [comment]
Can you also attach the generated json for the ref type?


Mvh

Per Bornsjö



___________________________________
[links_loggo]

Per Bornsjö

LINKS GOT AB
BOX 13103<x-apple-data-detectors://0/1>
S-402 52 GÖTEBORG<x-apple-data-detectors://0/1>
MOB: 070-5888337<tel:070-5888337>

***@***.******@***.***> • www.links.se<http://www.links.se/>

This e-mail is confidential and may contain

________________________________
Från: mark-zhou ***@***.***>
Skickat: Wednesday, July 21, 2021 6:34:39 PM
Till: domaindrivendev/Swashbuckle.AspNetCore ***@***.***>
Kopia: Per Bornsjö ***@***.***>; Mention ***@***.***>
Ämne: Re: [domaindrivendev/Swashbuckle.AspNetCore] Property of reference type(another Dto class) decorated with SwaggerSchemaAttribute, doesn't have nullable and description annotations (#2129)


FYI, my current workaround to this problem is manually setting the Nullable flag using a filer:

foreach (var prop in schema.Properties)
{
        if (prop.Key == "OptionalFieldA")
        {
                prop.Value.Nullable = true;
        }
}


OptionalFieldA is already declared as a nullable type. So ideally I shouldn't need to do that.

**Comment by Eneuman** [comment]
Can you also please attach the generated json for the person ref type?

**Comment by mark-zhou** [comment]
{
  "openapi": "3.0.1",
  "info": {
    "title": "WebApplication3",
    "version": "v1"
  },
  "paths": {
    "/abc": {
      "post": {
        "tags": [
          "WeatherForecast"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Person"
                  }
                ]
              }
            },
            "text/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Person"
                  }
                ]
              }
            },
            "application/*+json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/Person"
                  }
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Person": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "age": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      }
    }
  }
}

**Comment by Eneuman** [comment]
The JSON looks fine to me.

Are you running into this issue https://github.com/OpenAPITools/openapi-generator/issues/6815 ?
