### ISSUE TITLE
Ignoring property on method request object (body) when same property name is present as parameter

### ISSUE THREAD

**Issue by anibal-acosta** [domaindrivendev/Swashbuckle.AspNetCore#2131]
Hello, This is my example escenario.
Model:
```
class personData
{
   public String id {get;set;}
   public String name {get;set;}
   public String email {get;set;}
}
```

I have two method (get for list and post for create/update)

```
[HttpGet]
public List<personData> Get();

[HttpPost("id")]
public personData Post(String id, personData data);

```
when documentation is generated "id" property is present in both operation as result but also present in the Post as data property of personData object. I don't want to include the "id" property in this case because the id is part of the URL (method parameter)

So, maybe some kind of attribute can to tell the builder to ignore if the same property name and datatype is present as parameter of the method. In this case the property "id" is present and also is present in the request object personData, so docu builder will not document the id for the request personData object.

I write this to ask if possible but in the middle I change to write like suggestion also

**Comment by martincostello** [comment]
I would suggest trying `[FromBody]` with the data parameter and see if that fixes it. If you're still having issues please open a new issue and we'll look into it.
