### ISSUE TITLE
Runtime error when adding Swashbuckle.aspnetcore and Swashbuckle.AspNetCore.Filters

### ISSUE THREAD

**Issue by Ankhimes** [domaindrivendev/Swashbuckle.AspNetCore#2132]
I am trying to add documentation (**example**) for Swagger RequestBody but facing issues with both XML commenting approach and using SwaggerRequestExample attribute
Below is the version of nuget packages used

asp.net core= 3.1 
Swashbuckle.AspNetCore = 6.1.4
 Swashbuckle.AspNetCore.Filters = 7.0.2

ERROR after adding  Swashbuckle.AspNetCore

**[2021-06-04T05:49:34.591Z] Executed 'Swagger' (Failed, Id=de288bf2-5954-45ab-be31-af370cb86cb0, Duration=456ms)
[2021-06-04T05:49:34.593Z] System.Private.CoreLib: Exception while executing function: Swagger. Swashbuckle.AspNetCore.SwaggerGen: Failed to generate Operation for action - . See inner exception. AzureFunctions.Extensions.Swashbuckle: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository..ctor()'.**

Runtime Error after adding  Swashbuckle.AspNetCore.Filters
System.MissingMethodException: 'Method not found: 'Void Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter..ctor(System.Text.Json.JsonSerializerOptions)'.'

Please let me know if this is a known issue and what is the workaround for the same

**Comment by Ankhimes** [comment]
Any suggestions or workaround ?

**Comment by martincostello** [comment]
Please open a new issue if you're still having issues trying to use the latest version of Swashbuckle with Azure Functions.
