### ISSUE TITLE
Migrating Swagger ASPNET.Core from 4.x to latest

### ISSUE THREAD

**Issue by mp-assco** [domaindrivendev/Swashbuckle.AspNetCore#2138]
I have been given a project to update and I'm gotten a bit stuck in migrating from 4.x to the latest version. 

The first issue is the Going from `Operation` to `OpenApiOperation` it no longer has `Produces` and I cannot find anywhere that has a solution for this and I cannot find documentation for the breaking changes. It seems like you're supposed to use labels instead, but I do not know how to get the same functionality.

```
    public class ApiVersionOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var actionApiVersionModel = context.ApiDescription.ActionDescriptor?.GetApiVersion();
            if (actionApiVersionModel == null)
            {
                return;
            }

            if (actionApiVersionModel.DeclaredApiVersions.Any())
            {
                operation.Produces = operation.Produces.SelectMany(p => actionApiVersionModel.DeclaredApiVersions.Select(version => $"{p};v={version}")).ToList();
            }
            else
            {
                operation.Produces = operation.Produces.SelectMany(p => actionApiVersionModel.ImplementedApiVersions.OrderByDescending(v => v).Select(version => $"{p};v={version}")).ToList();
            }
        }
    }
```

The next is concerning the `SwaggerDocument.Security` which I cannot find anything about whatsoever on the internet.

```
public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
{
    swaggerDoc.Security = new List<IDictionary<string, IEnumerable<string>>>()
    {
        new Dictionary<string, IEnumerable<string>>()
        {
            { "Bearer", Array.Empty<string>() }
        }
    };
}

```
Anyone know how you're supposed to migrate `Security` from `SwaggerDocument` 4.x to the latest `OpenApiDocument`?

**Comment by Tropico80** [comment]
Hello

Did you have any more information about your second post or find a workaround ?
I currently dealing with the same situation.

Best regards

**Comment by martincostello** [comment]
Please open a new issue if you're still trying to do this.
