### ISSUE TITLE
Custom operation IDs for single document, and not the other

### ISSUE THREAD

**Issue by ffMathy** [domaindrivendev/Swashbuckle.AspNetCore#2139]
I have two Swagger documents:

```csharp
options.SwaggerDoc("v1", new OpenApiInfo
{
    Title = "V1",
    Version = "v1"
});
options.SwaggerDoc("v2", new OpenApiInfo
{
    Title = "V2",
    Version = "v2"
});
```

I'd like to apply a `CustomOperationIds` to one of them, and another type to the other, so that the operation IDs of V2 are different than V1.

Is this possible?

**Comment by martincostello** [comment]
I _believe_ this is possible using a schema filter.
