### ISSUE TITLE
SwaggerSchema attribute description is ignored on complex-typed members

### ISSUE THREAD

**Issue by tyler-boyd** [domaindrivendev/Swashbuckle.AspNetCore#2141]
Hi,

I'm using v6.0.1 of SwashBuckle. Here's a minimal example of what I'm talking about:

```cs
public class Foo {
  [SwaggerSchema("This is a special kind of bar")]
  public Bar Bar { get; set; }

  [SwaggerSchema("Descriptions on simple types do work")]
  public int SomeNumber { get; set; }
}

public class Bar {
   // omitted 
}
```

The generated swagger doesn't contain the "This is a special kind of bar" description on the Foo's Bar field. Am I doing something wrong or is this a bug in the library?

**Comment by officeSpacePirate** [comment]
I'm experiencing the same thing. This applies to using either the SwaggerSchemaAttribute or the `summary` code comment.

**Comment by privjimmie** [comment]
I'm also experience the same issue with the SwaggerSchema attribute

Examples on my model

```
[SwaggerSchema(ReadOnly = true, Description = "forward test desc")]
public string forward_to_email { get; set; }

[SwaggerSchema(ReadOnly = true, Description = "type test desc")]
public _DTO_enums.group_type type { get; set; }
```

and produced json

![image](https://user-images.githubusercontent.com/52044898/173842479-9704c907-18b4-4c91-a948-fc8f167f2e16.png)

I also tried setting it as a SchemaFilter, like this (not exactly, but you get the point), and still not affecting the output

```
public class ReadOnlyFilter : ISchemaFilter
    {
        public void Apply(OpenApiSchema model, SchemaFilterContext context)
        {
            ...
            foreach (var prop in model.Properties)
            {
                prop.Value.ReadOnly = true;
            }
            ...
        } 
    }
```

**Comment by mikeMoreno** [comment]
Support for sibling keywords alongside a `$ref` was added in OpenAPI 3.1.

Swashbuckle currently only supports up to OpenAPI 3.0.

---
Relevant links:

The issue in OpenAPI is mentioned: https://github.com/OAI/OpenAPI-Specification/issues/1514

Swashbuckle's plans to support OpenAPI 3.1: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2349

A comment on the OpenAPI.NET project that mentions support for this explicitly: https://github.com/microsoft/OpenAPI.NET/issues/795#issuecomment-1232410465
