### ISSUE TITLE
Is it possible to use Swashbuckle without the FromBody, FromRoute annotations?

### ISSUE THREAD

**Issue by pauloortins** [domaindrivendev/Swashbuckle.AspNetCore#2142]
On my scenario we are using the ApiController that does the binding interference so we don`t use the FromBody attributes. Is it possible to use swashbuckle without specify a binding annotation? 

Use FromBody breaks our bindings. Is there another parameter like [SwaggerBody] or is there a way to create a filter to do that?

**Comment by martincostello** [comment]
I'm not aware of another attribute, but you should be able to change things with an operation filter.
