### ISSUE TITLE
XML Examples

### ISSUE THREAD

**Issue by thisisausername99** [domaindrivendev/Swashbuckle.AspNetCore#2149]
I am porting an old API to .NET Core and to not introduce breaking changes, we want to support XML as well as JSON.

I have found some undesired behaviors that I would imagine working out of the box. I have therefore created a very simple example and have questions I would be delighted if someone can, at least, point me in the right direction to answer.

Consider the following very simple code:

``` 
[HttpPost]
[Route("api/test")]
public IActionResult post([FromBody] Test test)
{
   return Ok();
}

[DataContract(Namespace ="", Name ="MyTestClass")]
public class Test
{
   public Test()
   {
      MyString = new List<string>();
   }
   [DataMember]
   public List<string> MyString { get; set; }
}
```
    
I am using a XmlDataContractSerializer for he XML part.

```
 public void ConfigureServices(IServiceCollection services)
      {
         services.AddControllers().
         AddXmlDataContractSerializerFormatters();
         services.AddSwaggerGen();
      }
```

The following example are generated 

```
<Test>
  <myString>string</myString>
</Test>       
```

The annotation [DataContract(Namespace ="", Name ="MyTestClass")] is ignored. I feel like I'm missing something because this must surely work out of the box?

The list of strings is a non-starter and gets translated into a single string. I have seen ISchemaFilters that supposedly handle this, but they either don't work as intended or creates compounded errors on wrapped strings (double top-level names). Also MyString is now starting with a lower case in the example

I feel like I am missing something obvious here. 

The JSON part is working admirably, but it seems like the XML support is off.  

Any help would be much appreciated.

**Comment by askids** [comment]
@thisisausername99 were you able to figure out how to get this to work?
