### ISSUE TITLE
ODataQueryOptions in .NET 5 using Microsoft.AspNetCore.OData

### ISSUE THREAD

**Issue by HuntJason** [domaindrivendev/Swashbuckle.AspNetCore#2159]
When I add the ODataQueryOpations parameter into an endpoint in my .NET 5 WebAPI that uses Microsoft.AspNetCore.OData 8.0.1, Swashbuckle generates oddly in the options section compared with what is expected.

[WebApplication1.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/6792823/WebApplication1.zip)

![Expected](https://user-images.githubusercontent.com/112656/125110740-3432cb80-e0a2-11eb-9240-1ca59e5a5cdd.png)
![Actual](https://user-images.githubusercontent.com/112656/125110747-37c65280-e0a2-11eb-8c97-fccbe51de5c0.png)

**Comment by HuntJason** [comment]
It appears as this is an issue with the UI component only as the values appear to be generating properly in the generated (NSwag Studio) client.

**Comment by martincostello** [comment]
Looks like the response generator is trying to render `HttpContext` as a JSON object.

Can you replicate this in the latest release?
