### ISSUE TITLE
On empty Accept-Language header, getting response of unexpected culture.

### ISSUE THREAD

**Issue by ghost** [domaindrivendev/Swashbuckle.AspNetCore#2161]
Hi. I have noticed a weird behavior that might be a bug. You can find a test project [here](https://github.com/RaamGeneral/Test) for a while.

I created a new ASP.NET Core Web API solution and updated the default Swashbuckle package (to version 6.1.4). Then I added a little bit of code to support localization:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("v1", new OpenApiInfo { Title = "test", Version = "v1" });
        c.OperationFilter<AcceptLanguageHeaderOperationFilter>();
    });
    services.AddLocalization(options => options.ResourcesPath = "Resources");
}
```

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    var supportedCultures = new[] {"it", "en"};
    var localizationOptions = new RequestLocalizationOptions().SetDefaultCulture(supportedCultures[0])
        .AddSupportedCultures(supportedCultures)
        .AddSupportedUICultures(supportedCultures);
    localizationOptions.RequestCultureProviders = new List<IRequestCultureProvider>
    {
        new AcceptLanguageHeaderRequestCultureProvider()
    };
    app.UseRequestLocalization(localizationOptions);
    
    [...]
}
```

```csharp
public class AcceptLanguageHeaderOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        if (operation.Parameters == null)
        {
            operation.Parameters = new List<OpenApiParameter>();
        }

        operation.Parameters.Add(new OpenApiParameter
        {
            Name = "Accept-Language",
            In = ParameterLocation.Header,
            Schema = new OpenApiSchema
            {
                Type = "string"
            }
        });
    }
}
```

When I make a request from swagger ui* without any Accept-Language I receive an English response when I actually expect an italian value. To be sure it was not a mistake by my side, I imported the curl command from the swagger ui into Postman and executed the request, getting an Italian response.

\* I'm not sure if this issue belongs here or in [swagger-ui](https://github.com/swagger-api/swagger-ui)

This is the first time I open a issue. I'm still not sure, but getting a different result by the curl command executed in Postman convinced me to share this experience.

**Comment by ronnyek** [comment]
When talking about pure .net localization using strignlocalizer, I've seen stuff like that when I either had resx files named incorrectly, or had a rootnamespace in the project that had a `-` in it.

**Comment by ktkk** [comment]
Hi, I'm running into a similar issue.
I have some middleware that reads the Accept-Language header and sends it along to the database for localised queries.

When I leave the `Accept-Language` header parameter (added with a custom OperationFilter) empty, Swashbuckle actually sends the default header my browser would normally send: `Accept-Language: en,nl;q=0.9,en-GB;q=0.8,en-US;q=0.7`.
It also sends a default `Accept` and `Accept-Encoding` headers, as can be seen in the network tab in the browser.

I have tried using a request interceptor, like this:
```csharp
options.UseRequestInterceptor(@"request => {
    if (request.headers['Accept-Language']?.length > 2) request.headers['Accept-Language'] = undefined;
    return request;
}");
```
Unfortunately without success. It seems these headers are added after the interceptor was called perhaps?

**Comment by martincostello** [comment]
I'm going to close this on the basis that it looks like it's a swagger-ui or browser issue and the OP has deleted their GitHub account.

Please open a new issue with a repro if you're still experiencing this and we can look into it further.
