### ISSUE TITLE
Any Plan of Getting rid of newtonsoft and just utlizing System.Text.Json

### ISSUE THREAD

**Issue by KamranShahid** [domaindrivendev/Swashbuckle.AspNetCore#2163]
Is there any Plan of Getting rid of newtonsoft and just utilizing System.Text.Json? It could be great if we can avoid this dependency. multiple third party libraries have get rid of it's dependency now

**Comment by runehalfdan** [comment]
As far as I can tell, using Newtonsoft is completely optional. Since we in my company use it, I haven't verified that it works well without, though.

**Comment by domaindrivendev** [comment]
@KamranShahid - which version of SB are you using? As of `5.0.0`, the core packages have _no dependency_ on `Newtonsoft` and will honour serialisation behaviour of `System.Text.Json` be default.
