### ISSUE TITLE
swagger can't create swagger.json file when i use same parameter name in two action in same controller

### ISSUE THREAD

**Issue by Alirexaa** [domaindrivendev/Swashbuckle.AspNetCore#2167]
when i use same parameter name in two action in same controller , swagger can't create swagger.json file and following error occurred 
`Can't use schemaId "$Request" for type "$Application.Brands.UpdateBrand+Request". The same schemaId is already used for type "$Application.Brands.CreateBrand+Request"`

and these are  my actions in same controller :

  `  
     [HttpPost(nameof(Create))] 
          public async Task<IActionResult> Create([FromBody] CreateBrand.Request request, [FromServices] CreateBrand createBrand, CancellationToken cancellationToken)
          => Ok(await createBrand.Do(request, cancellationToken));                                                                                                                            
 `

`
       [HttpPut(nameof(Update))]
        public async Task<IActionResult> Update([FromBody] UpdateBrand.Request request, [FromServices] UpdateBrand updateBrand, CancellationToken cancellationToken)
            => Ok(await updateBrand.Do(request, cancellationToken));`

**Comment by SeyedMHM** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1607#issuecomment-607170559

**Comment by SeyedMHM** [comment]
Read here maybe it will help you
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1431#issuecomment-578418266

**Comment by domaindrivendev** [comment]
As per the SO post and issue referenced above, you need to configure a custom strategy for schema Ids because the default strategy uses the class name alone, resutling in non-unique IDs for your use case.
