### ISSUE TITLE
cdata with url not decode 

### ISSUE THREAD

**Issue by rozbo** [domaindrivendev/Swashbuckle.AspNetCore#2171]
if you want to provide a example, and the example value is a url, story will start.
if u use the raw url in xml,  can let xml invaild.
```c#
        /// <summary>
        /// url
        /// </summary>
        /// <example>https://test.com/a?b=1&c=2</example>
        public string Url { get; set; }
```
cause the xml ask the `&` must escape to `&amp` , coincidentally, in most cases, the url always contains `&`.
so u must use the cdata to auto escape like this
```c#
        /// <summary>
        /// url
        /// </summary>
        /// <example><![CDATA[https://test.com/a?b=1&c=2]]></example>
        public string Url { get; set; }
```
and then, the ui can't decode `&amp` back to `&` , so the url is invaild too.
is there a way to show right url in example ?

**Comment by rozbo** [comment]
well, finally I found a solution to this problem
it it caused by https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/a66864f65bac06ad326b4f2ec8fddcc91012a4e8/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs#L52
the `innerXml` will get the xml string , and means never unescaped.
so we nedd `innerText`, but, `XPathNavigator` does not has the `innerText`, I found a `ToString()` method in doc https://docs.microsoft.com/en-us/dotnet/api/system.xml.xpath.xpathnavigator.tostring?view=net-5.0
and it said it is eq to `innerText`.

so, will u fix it by change all `innerXml` to `ToString()` ?

**Comment by domaindrivendev** [comment]
@rozbo - could you create a PR for this change?

**Comment by rozbo** [comment]
Yes， I will do it ASAP

**Comment by rozbo** [comment]
#2184 
all test are passed
