### ISSUE TITLE
load slow

### ISSUE THREAD

**Issue by zhanghaiboshiwo** [domaindrivendev/Swashbuckle.AspNetCore#2177]
When I reached 500 interfaces, the Swagger document was slow to respond and sometimes timed out

**Comment by zhanghaiboshiwo** [comment]
![E3E15184-6430-4e59-8DF7-F5899928C63B](https://user-images.githubusercontent.com/43592384/127878291-f5447049-54dc-41ac-a980-194a514be4b8.png)

**Comment by zhanghaiboshiwo** [comment]
![E3E15184-6430-4e59-8DF7-F5899928C63B](https://user-images.githubusercontent.com/43592384/127878472-208319bf-309c-4449-9095-fb82c600aa55.png)

**Comment by zhanghaiboshiwo** [comment]
Why wasn't there a caching mechanism here? What was the reason?

**Comment by domaindrivendev** [comment]
Dup of #1970
