### ISSUE TITLE
nullable  param mark as Required

### ISSUE THREAD

**Issue by gitlsl** [domaindrivendev/Swashbuckle.AspNetCore#2179]
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.1.5" />

step:
1. create webapi template , add Swashbuckle 
2. add `#nullable enable` on Controller file
3.        [HttpGet("test/{layer?}")]
        public string test(string? layer)
        {
              return layer ??"12344";
        }
       on  swagger  ui,   layer   mark as Required? 
4.   [HttpGet("test/{layer?}")]
        public string test([SwaggerParameter(Required = false)] string? layer)
        {
  return layer ??"12344";
        }
  change to this,     mark as Required   too

q:   is this a bug or I miss something  what should I do to make it as nullable

**Comment by gitlsl** [comment]
after some search , I add  ` c.EnableAnnotations();` in ConfigureServices , now it is not Required 
but get another question
I have no input on  layer param,   but  swagger will pass  `,` to server ,  it will request url  `http://localhost:5000/GeoJson/test/,`  ?

**Comment by domaindrivendev** [comment]
Dup of #406. TL/DR: Swashbuckle does not currently support "optional" path parameters because the OpenAPI specification does not support optional path parameters.
