### ISSUE TITLE
EnableTryItOutByDefault not working with RoutePrefix

### ISSUE THREAD

**Issue by r-bennett** [domaindrivendev/Swashbuckle.AspNetCore#2180]
I'm trying to use `EnableTryItOutByDefault ` from https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2113 but it's not working when I use it in conjunction with `RoutePrefix` and `SwaggerEndpoint` (which I use to have swagger served as the root page rather than at `/swagger`)

e.g.
```
app.UseSwaggerUI(
    options =>
    {
        options.EnableTryItOutByDefault();
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "MyApp");
        options.RoutePrefix = string.Empty;
    });
```
When I say "not working" I mean it has no effect, I still have to click Try It Out to use an endpoint.

Both of the following works fine (although with swagger at `/swagger` rather than `/`):
```
app.UseSwaggerUI(
    options =>
    {
        options.EnableTryItOutByDefault();
    });
```
or the redundant
```
app.UseSwaggerUI(
    options =>
    {
        options.EnableTryItOutByDefault();
        options.RoutePrefix = "swagger";
    });
```

This is with Swashbuckle.AspNetCore.SwaggerUi 6.1.5 running on net5.0

**Comment by domaindrivendev** [comment]
I'm unable to repro this issue. Could you please create a minimal app (i.e. starting from empty project) that repro's the issue and post to Github so I can pull down and troubleshoot.

**Comment by r-bennett** [comment]
I'm also unable to repro this myself now, even in the same full application I was seeing it in before. Not quite sure what happened there, but all seems good to me now. Thanks for taking a look

**Comment by r-bennett** [comment]
I suspect this was browser-caching related - just rolled out the change to my production instance, but it only started working as expected after a hard refresh (ctrl + f5)
