### ISSUE TITLE
[Feature] Generate Swagger file at postbuild without running the app

### ISSUE THREAD

**Issue by jackalsin** [domaindrivendev/Swashbuckle.AspNetCore#2181]
Similar to the feature request [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/541). Can you add support to generate the swagger json without <c>Startup</c> class? Sometimes, we use unity container rather than using `Startup` class

```cs
builder ??= WebHost.CreateDefaultBuilder();
            return builder
                .UseUnityServiceProvider(this.Container)
```

**Comment by Eneuman** [comment]
Do you men generating the json file when you build the project?

**Comment by jackalsin** [comment]
Yes. Sorry, I don’t see your reply on Github Issues.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by DanielHabenicht** [comment]
I think this can be closed as it possible with the CLI, see https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/872#issuecomment-1025662941
