### ISSUE TITLE
Change default tags selector to respect new ITagsMetadata in ASP.NET Core 6

### ISSUE THREAD

**Issue by DamianEdwards** [domaindrivendev/Swashbuckle.AspNetCore#2192]
ASP.NET Core 6 is considering [introducing `ITagsMetadata`](https://github.com/dotnet/aspnetcore/issues/35310) to allow endpoints to describe tags in their metadata. Swashbuckle should update its [default tags selector](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/cf7c50b70390a296f748d9a1f894823e2d9c7280/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs#L80) to respect this metadata if it's present in the `ApiDescription.ActionDescriptor` when populating the tags for an API.

**Comment by JamborJan** [comment]
Is this fully resolved? Is it possible that it is broken again in version 6.2.3? See: https://stackoverflow.com/questions/69861755/why-the-swagger-doesnt-open-in-net-6#

Maybe the latest Swashbuckle version 6.2.3 is broken and not working with net6.0. Scenarios I tested:
- net5.0 and Swashbuckle 6.2.3 = working
- net6.0 and Swashbuckle 6.2.3 = NOT working
- net6.0 and Swashbuckle 6.2.2 = working;

Thanks for your help.

**Comment by DamianEdwards** [comment]
@JamborJan can you share the result of running `dotnet --info` at the command line on a machine that this repros on? Also can you reproduce this in a brand new ASP.NET Core web API project, e.g.
``` console
> dotnet new webapi -o NewWebApi
> cd NewWebApi
NewWebApi> dotnet run
```

**Comment by JamborJan** [comment]
Hi @DamianEdwards thanks for your prompt feedback and your help. It was my fault, the locally running SDK was not up to date. While the whole project was using new net6.0 stuff the local SDK on that one machine was still net5.0. After fixing that all is as expected.

**Comment by nameofSEOKWONHONG** [comment]
In my case, only .net6-rc was installed.
After installing .NET 6, it worked normally.
swagger : 6.2.3

**Comment by DamianEdwards** [comment]
Seems this is done now.
