### ISSUE TITLE
[BUG] Authorization is lost when switching definitions (version> 6.1.1)

### ISSUE THREAD

**Issue by 2A5F** [domaindrivendev/Swashbuckle.AspNetCore#2197]
Authorization is lost when switching definitions 
version> 6.1.1

**Comment by domaindrivendev** [comment]
This is almost certainly specific to the swagger-ui (as opposed to Swashbuckle) and therefore should be directed to the [swagger-ui project](https://github.com/swagger-api/swagger-ui) instead.

With that said though, it seems like _correct_ behavior to me. In the OpenAPI specification, authorization schemes are defined at the document level. Therefore, when you switch documents, it makes 100% sense to me that authorization against schemes defined in the previous document, would _not persist_ for the next document.
