### ISSUE TITLE
V4 to V6 -  SchemaFilterContext.JsonContract Removed

### ISSUE THREAD

**Issue by msM365Dev** [domaindrivendev/Swashbuckle.AspNetCore#2203]
Hello,

We're trying to transition some complex extensions from V4 to V6 and struggling with the deperecation of the SchemaFilterContext.JsonContract property:

**Current code:**
if (context.JsonContract is JsonObjectContract objectContract)
{
    model.Properties.ExtendProperties(objectContract.Properties);
}

We cannot find any documentation or guidance anywhere detailing how to work with the revised SchemaFilterContext object to obtain the properties collection relevant to the current context.

Any pointers would be hugely appreciated.

Thanks in advance

**Comment by izzybabcock** [comment]
Same here

**Comment by gabrielrainha** [comment]
Yeah, still trying to figure that out myself...
