### ISSUE TITLE
[SwaggerParameter(Required = false)] Won't have any effect

### ISSUE THREAD

**Issue by AEZ314** [domaindrivendev/Swashbuckle.AspNetCore#2208]
```
[Post]
IActionResult Post([SwaggerParameter(Required = false)] int? value = null)
{ ... }
```

The generated specification Json is no different than when SwaggerParameter omitted. As a consequence the auto generated client is going to throw an exception if a null value is passed for int? value.

Is it just me not knowing how to use this library or is it something else?

Pardon me if I'm missing something obvious, there isn't much documentation/examples on the usage of this attribute. All I want is the generated code to accept null values for int? value.

**Comment by liesahead** [comment]
Up

**Comment by martincostello** [comment]
I don't understand the issue here - you say it isn't required, and the docs are the same with and without it and it breaks if no value is supplied, but you've said it's not required so null should work.
