### ISSUE TITLE
Bug: readOnly is set to true on Schema but this is not reflected in Swagger file

### ISSUE THREAD

**Issue by wyatt-troia-msft** [domaindrivendev/Swashbuckle.AspNetCore#2227]
Version: 6.1.4

I have some model properties annotated with `[SwaggerSchema(ReadOnly = true)]`. When I debug and inspect the `OpenAPISchema` property corresponding to one of these model properties, its `readOnly` property is set to `true`, as expected. Yet these properties are not marked as readOnly in the produced Swagger file (the `readOnly` key doesn't appear at all for them). 

I am using NewtonSoft as my serializer and have followed [the instructions for handling this in the README](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft).

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
