### ISSUE TITLE
Property's xml documentation not used when the property references a custom C# type

### ISSUE THREAD

**Issue by kichalla** [domaindrivendev/Swashbuckle.AspNetCore#2228]
**Version of Swashbuckle.AspNetCore**: 6.1.5

**Issue**: Following StackOverlfow (not filed by me) issue describes the same issue that I am seeing in my scenario too.
https://stackoverflow.com/questions/65238148/asp-net-core-generated-swagger-descriptions-missing-on-object-attributes

**Expected**: The documentation for `ExampleValue2` property should be present in the generated swagger document. i.e `"description": "ExampleValue description."` should be present.
**Actual**: This information is currently missing.

**Comment by mjanas** [comment]
See https://github.com/OAI/OpenAPI-Specification/issues/1514 - the OpenApi spec does not allow sibling elements for $ref.

A workaround is to use the `allOf` operator. 

```cs
var schemaGenerator = new SchemaGenerator(
    new SchemaGeneratorOptions
    {
         UseAllOfToExtendReferenceSchemas = true,
    }, ...);
```
