### ISSUE TITLE
Disable validator on aspnet5+fullfw?

### ISSUE THREAD

**Issue by andrasg** [domaindrivendev/Swashbuckle.AspNetCore#223]
Is there any way to disable the validator on aspnet5 over the full framework? The latest package I can get is 6.0.0-beta902 which won't allow the Action overload of app.UseSwaggerUi().

**Comment by domaindrivendev** [comment]
This level of configuration will be available in the upcoming, stable 6.0.0 release as can be seen in the example website for custom UI config:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/CustomUiConfig/Startup.cs#L30

If you can't wait until then, it's also available with the preview packages now available on MyGet

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"
