### ISSUE TITLE
Swashbuckle is ignoring provided NewtonsoftDataContractResolver

### ISSUE THREAD

**Issue by kgaska** [domaindrivendev/Swashbuckle.AspNetCore#2230]
Hi,

I'm using NewtonsoftJsonSerializer with JsonApiSerializerSettings. I was trying to force Swashbuckle to generate documentation using JsonApi format:
- installed Swashbuckle.AspNetCore.Newtonsoft package
- used services.AddSwaggerGenNewtonsoftSupport();
- in AddNewtonsoftJson method configured SerializerSettings.ContractResolver to JsonApiContractResolver

however documentation is still generated using standard JSON notation. I have double checked and at the end of services registration I've built ServiceProvider and got ISerializerDataContractResolver instance manually which appeared to be correctly configured to NewtonsoftDataContractResolver with all the settings, JsonApiContractResolver and so on, but documentation is still generated wrong - input/output schemas are in standard json notation instead.

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
