### ISSUE TITLE
Error on Swagger for relative paths with colon character

### ISSUE THREAD

**Issue by PS99999** [domaindrivendev/Swashbuckle.AspNetCore#2239]
I have an API endpoint (.net core 3.1), with the following signature:

```
[HttpGet("{divisionName}/things:count", Name = "GetNumberOfThings")]
public async Task<IActionResult> GetNumberOfThings([FromRoute] [Required] string divisionName, [FromQuery] [Required] string groupBy)
```

When I try to go to the Swagger page, I get the following error:
![image](https://user-images.githubusercontent.com/91678944/135470446-409310d7-6972-4573-a92e-3270f98e7236.png)

The endpoint is working as expected, it is just when I try to access the Swagger.
Previously the Swagger was working, it was only when I updated Swashbuckle.AspNetCore to version 6.2.2.

I think it has to do with that new internal method 'RelativePathSansParameterConstraints', which is looking for a '}' after the ':'.

Can you please have a look?
 
Many thanks in advance.

**Comment by tomkerkhove** [comment]
Happy to contribute this feature if we can flesh it out @domaindrivendev
