### ISSUE TITLE
[BUG] Wrong parameter with odata functions

### ISSUE THREAD

**Issue by mferraricloudsurfers** [domaindrivendev/Swashbuckle.AspNetCore#2243]
Using Swashbuckle.AspNetCore.Annotations **v6.2.2** odata function parameters are truncated like this example:

![image](https://user-images.githubusercontent.com/38034428/135851850-f9c9053d-2f2a-4c31-bbe2-c00ba06348f3.png)

with version 6.2.1 works correctly

![image](https://user-images.githubusercontent.com/38034428/135852010-8e564e7f-ef79-4daf-a22f-6a064975f5d3.png)

**Comment by domaindrivendev** [comment]
Closing in favor of #2310
