### ISSUE TITLE
AddSwaggerGen in DotNet core is not called

### ISSUE THREAD

**Issue by mairo2** [domaindrivendev/Swashbuckle.AspNetCore#2249]
Hi there!
I am trying to update my swagger documentation with security options. In startup.cs the ConfigureServices(IServiceCollection service) is not called in .NetCore which means that my written code in it will not run.
 ```
services.AddSwaggerGen(options =>{
    options.AddSecurityDefinition("oauth2", new ApiKeyScheme
    {
        Description = "Standard Authorization header using the Bearer scheme. Example: \"bearer {token}\"",
        In = "header",
        Name = "Authorization",
        Type = "apiKey"
    });
```

Now I am cecking if there are other options or packages which can help me on this issue.
The thing is that there are alot of solutions for this issue for ASP.Net core but not for .Net Core.
Note: I am using netcorapp3.1 by the way.

**Comment by ruslanmogilevskiy** [comment]
Show how you build your app`s host (IHostBuilder) or better whole Program.cs (usually it there).

**Comment by 23Rohan** [comment]
Do you believe if I say I don't have those two in my project? No Program.cs and no IHostBuilder is found in the project. The only function I have in startup.cs is Configure(IFunctionHostBuilder) if it is the same.

**Comment by 23Rohan** [comment]
`[assembly: FunctionsStartup(typeof(Public.Startup))] 
public class Startup : FunctionsStartup 
{
      public override void Configure(IFunctionsHostBuilder builder)
      {
         builder.Services.AddSwaggerGen(c => 
              { c.SwaggerDoc("v1.0", new OpenApiInfo { 
                   Title = "API v1.0", Version = "1.0.1" 
               }); 
               c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme { 
                    Name = "Bearer Authorization",
                    Description = "JWT Authorization using the Bearer scheme",
                    In = ParameterLocation.Header, Type = SecuritySchemeType.ApiKey, Scheme = "Bearer",
               }); 
               c.AddSecurityRequirement(new OpenApiSecurityRequirement() 
                    { { new OpenApiSecurityScheme {
                         Reference = new OpenApiReference 
                             { Type = ReferenceType.SecurityScheme,
                                Id = "Bearer", 
                             },
                             Scheme = "oauth2",
                             Name = "Bearer",
                             In = ParameterLocation.Header, },
                            new List<string>() 
                         }, 
                  });
                 var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml"; 
                 var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile); c.IncludeXmlComments(xmlPath); 
            }); 
      }
}`

**Comment by ruslanmogilevskiy** [comment]
Firstly you wrote that the ConfigureServices method was not called, but passed an Azure's startup code.
Anyway, does your Configure method get called at all? Seems not, so it could be not a Swashbuckle's problem.

**Comment by FilipaAlves** [comment]
Any news about this? @mairo2 
I am facing the same problem.
