### ISSUE TITLE
XML example in Swagger UI does not correctly conform to the required XML schema

### ISSUE THREAD

**Issue by danroth27** [domaindrivendev/Swashbuckle.AspNetCore#225]
Create a simple Web API with ASP.NET Core that takes a simple type from the body:

```c#
        [Produces(typeof(Value))]
        [HttpPost]
        public IActionResult PostValue([FromBody] Value value)
        {
            return CreatedAtAction("GetValue", new { id = value.Id }, value);
        }
```

```c#
    public class Value
    {
        public int Id { get; set; }
        public string Text { get; set; }
    }
```

Enable the XML formatters:

```c#
   services.AddMvc()
       .AddXmlDataContractSerializerFormatters();
```

Browse to the Swagger UI endpoint. The example for the `value` parameter suggests the following:

```xml
<?xml version="1.0"?>
<Value>
  <id>1</id>
  <text>string</text>
</Value>
```

But this example won't deserialize correctly using the `DataContractSerializer`. You will get a null value. Instead the correct example should be:

```xml
<Value xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/WebApplication11.Controllers">
  <Id>0</Id>
  <Text>string</Text>
</Value>
```

@rynowak @eilon I'm not sure if this is an issue with the ApiExplorer or with the Swagger generation logic.

**Comment by domaindrivendev** [comment]
Support for XML descriptions need some work. @rynowak - any ideas how I could infer the namespace for a given type so I can set the [XML metadata](http://swagger.io/specification/#xmlObject) on the corresponding schema?

**Comment by danroth27** [comment]
Both the [DataContractSerializer](https://blogs.msdn.microsoft.com/youssefm/2009/04/29/using-xml-schema-import-and-export-for-datacontractserializer/) and the [XmlSerializer](https://blogs.msdn.microsoft.com/youssefm/2010/05/13/using-xml-schema-import-and-export-for-xmlserializer/) provide companion APIs for generating the XML Schema for a given CLR type. I think you could then do a translation from XML Schema to the schema language that Swagger uses.

**Comment by IUnknownPtr** [comment]
Anyone knows how this can be accomplished? We need XML namespaces in the Swagger generated examples.

**Comment by domaindrivendev** [comment]
Will track as part of #1050
