### ISSUE TITLE
MapType should check for inheritance

### ISSUE THREAD

**Issue by vanillajonathan** [domaindrivendev/Swashbuckle.AspNetCore#2250]
The `MapType` extension method should check for inheritance of the type. This way you could reduce configuration.

Instead of:
```cs
options.MapType<Cat>(() => new OpenApiSchema { Type = "string", Format = "uuid" });
options.MapType<Dog>(() => new OpenApiSchema { Type = "string", Format = "uuid" });
// ...
options.MapType<Zebra>(() => new OpenApiSchema { Type = "string", Format = "uuid" });
```

the configuration could be just:
```cs
options.MapType<Animal>(() => new OpenApiSchema { Type = "string", Format = "uuid" });
```

If the classes `Cat`, `Dog`, ..., `Zebra` all inherited from the class `Animal`.

**Comment by domaindrivendev** [comment]
While I can see some minor convenience in the example you gave, I think the new behavior is somewhat unintuitive. `MapType` was introduced for providing an explicit mapping between type and schema. If the various types in an inheritance hierarchy ultimately serialize/deserialze to the same thing (i.e what's represented by the schema), then why use an inheritance hierarchy for your API types/models in the first place?

**Comment by domaindrivendev** [comment]
Appreciate the contribution, but the IMO the value-add isn't compelling enough to change the behavior and potentially cause issues for existing users of `MapType`.

**Comment by vanillajonathan** [comment]
We inherit from an abstract base class in order to avoid "primitive obsession".
So we have a strongly-typed data types for identifiers (such as `UserId`, `PostId`, etc) that wrap `Guid`. We get ASP.NET Core to model bind these properties using a [custom JSON converter](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-6-0) and EF Core to [value convert](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions?tabs=data-annotations) these properties.

I doubt this would cause any issues for existing users of `MapType` since this just fallback to using the abstract type if the concrete type isn't found.
