### ISSUE TITLE
Regression in generated schemas 6.2.3 - 6.2.1

### ISSUE THREAD

**Issue by bgelens** [domaindrivendev/Swashbuckle.AspNetCore#2253]
The schema generated has changed in 6.2.3 compared to 6.2.1

6.2.1:
![image](https://user-images.githubusercontent.com/10071039/138296571-bfdb245f-0b84-4557-912c-572fd8989eb1.png)

6.2.2
![image](https://user-images.githubusercontent.com/10071039/138296607-20064f6f-7d0c-4e76-abf9-9f34ddf98c40.png)

Using a dto class in a post method:

```csharp
public class Customer
{
  public Customer() { }

  public Customer(int customerId, DateTime dateTimeCreated)
  {
    CustomerId = customerId;
    DateTimeCreated = dateTimeCreated;
  }

  public int CustomerId { get; }
  public string CompanyName { get; set; }
  public string BillingCustomerId { get; set; }
  public bool Active { get; set; }
  public DateTime DateTimeCreated { get; }
}
```

I'm on dotnet 5

**Comment by ramondeklein** [comment]
I also noticed some breaking changes with v6.2.2. Variables that were exported with `"readOnly": true` in v6.2.1 don't have this line in v6.2.2 anymore. The problem seems to be in `Swashbuckle.AspNetCore.SwaggerGen` sinve v6.2.2.

**Comment by ramondeklein** [comment]
I checked the differences between v6.2.2 and v6.2.1 and I guess commit https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/5b30e37ad28e24e9f3dfd0494f452476d1eeb361 is the source of these issues. Support for `System.Text.Json` broke existing `Newtonsoft.Json` code.

**Comment by chrisbbe** [comment]
I have the same issue, where `"readOnly": true` in 6.2.1 is removed in 6.2.3, I'm using `System.Text.Json`.

**Comment by ramondeklein** [comment]
@chrisbbe Do you have a constructor that accepts the property value? From the code it seems that this is changed too (see the commit in my previous comment).

**Comment by chrisbbe** [comment]
@ramondeklein Right, even a private constructor. Asked the commit author why here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2219#issuecomment-977275104

**Comment by ramondeklein** [comment]
@domaindrivendev Could you please comment on this? It's a pretty severe breaking change that prevents upgrading to 6.2.2+.

**Comment by domaindrivendev** [comment]
As of net5.0, STJ supports [deserialization of mutable types](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-5-0). This means if you have the following DTO:

```csharp
public class Customer
{
    public Customer(int customerId, DateTime dateTimeCreated)
    {
        CustomerId = customerId;
        DateTimeCreated = dateTimeCreated;
    }
    
    public int CustomerId { get; }
    public DateTime DateTimeCreated { get; }
}
```

And, you submit the following payload to an action that accepts this type:

```json
{
  "customerId": 999,
  "dateTimeCreated":  "2021-01-01"
}
```

Then, STJ _will_ assign the submitted values to the deserialized customer instance. Therefore, while the fields may be "read only" within your C# code, they are definitively NOT `readOnly` from an external API perspective, which is what Swashbuckle is documenting.

But, with all that said ... Swashbuckle isn't quite interpreting the STJ behavior correctly (see next comment) and that needs to be fixed. But, before I do that, I want to make sure the rationale at least for the example I provided makes sense?

**Comment by domaindrivendev** [comment]
As I mentioned above, while I believe the general rationale makese sense, the new Swashbuckle behavior still needs to be tweaked. After digging deeper into the STJ docs, it seems that if there's multiple constructors, then only one can be used for setting immutable properties. And, in your example, this would be the parameterless constructor, meaning that the `customerId` and `dateTimeCreated` should in fact be documented as `readOnly = true`.

I'll try get a fix out for this over the next day or so.

**Comment by ramondeklein** [comment]
@domaindrivendev If you have a test-version, then I'll be happy to check if it fixes the issues with my code.
