### ISSUE TITLE
Failed to load API definition. Fetch error. Not Found /swagger/v1/swagger.json

### ISSUE THREAD

**Issue by Exagram** [domaindrivendev/Swashbuckle.AspNetCore#2264]
Thanks for contributing to Swashbuckle.AspNetCore! As per the [contributing guidelines](CONTRIBUTING.md), please adhere to the following rules of thumb before submitting your issue:

1. If it's not a bug report, feature request or PR, don't submit it here. Post to Stackoverflow instead.
2. If your issue is specifically a UI concern, don't submit it here. Post to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui).
3. For bug reports, specify the version you're using and provide clear repro steps.

Swashbuckle Version 6.2.3.

Steps:
- In Visual Studio debug the project.
- Navigate to localhost:12345/swagger
- Observe "LOADING" for a few minutes
- After a few minutes observe: Failed to load API definition. Fetch Error. Not Found /swagger/v1/swagger.json

startup.cs
```c#
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Version = "v1",
                    Title = "...",
                    Description = "...",
                    Contact = new OpenApiContact
                    {
                        Name = "...",
                        Email = "...@...com",
                        Url = new Uri("https://...")
                    }
                });

                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                c.IncludeXmlComments(xmlPath);
            });

...

                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c =>
                {
                    c.SwaggerEndpoint("/swagger/v1/swagger.json", "...");
                });
```

**Comment by Luigi6821** [comment]
Hi @MrNkosiNgcobo,
I have exactly same issue and didn't find any solution.
Someone can help us?

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
