### ISSUE TITLE
Include Descriptions from XML Comments For Minimal Api Not work

### ISSUE THREAD

**Issue by MayueCif** [domaindrivendev/Swashbuckle.AspNetCore#2267]
I Create a .Net 6 Minimal Api Project ,But comment not display in swagger html。
The partten of this：https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments

Code:
`app.MapGet("Test", Handler.Test).WithName("Test");`
`public static class Handler
 {
        /// <summary>
        /// Test Comment
        /// </summary>
        public static string Test()
        {
            return "Test Comment";
        }
 }`

generate xml document is right。Isn't it supported yet? For Minimal Api.

**Comment by adrianstovall71** [comment]
I see the same thing.  Playing with Microsoft's "ToDo" examples for .Net Core and I see the xml comments for the ToDoItemDTO type show up in the documentation, but not for the app.MapGet entries.  

Seems like classes  *do* get comments added to their documentation.

Methods - the things mapped to http verbs - have documentation generated, but without the comments associated with them.

**Comment by MayueCif** [comment]
> I see the same thing. Playing with Microsoft's "ToDo" examples for .Net Core and I see the xml comments for the ToDoItemDTO type show up in the documentation, but not for the app.MapGet entries.
> 
> Seems like classes _do_ get comments added to their documentation.
> 
> Methods - the things mapped to http verbs - have documentation generated, but without the comments associated with them.

yes ,it not work for minimal api.present i can`t find solution seems.

**Comment by farlop** [comment]
Maybe this workaround can help: https://github.com/dotnet/aspnetcore/issues/37906#issuecomment-954494599

**Comment by captainsafia** [comment]
Hi folks! Yes, this isn't supported yet. We've actually got an issue tracking adding support for this over on the aspnetcore repo (https://github.com/dotnet/aspnetcore/issues/39927). If you'd like to see this happen, give it a thumbs-up and it'll help us with prioritization.

**Comment by feO2x** [comment]
I was able to get it running by using a structure like the following with Swashbuckle.AspNetCore 6.3.0:

```csharp
namespace MyAwesomeWebApi;

public static class GetContactsEndpoint
{
    public static WebApplication MapGetContactsEndpoint(this WebApplication app)
    {
        app.MapGet("/api/contacts", GetContacts)
           .Produces<ContactsListDto>()
           .Produces(StatusCodes.Status400BadRequest)
           .Produces(StatusCodes.Status500InternalServerError);
        return app;
    }

    /// <summary>
    /// Gets the contacts as a paged result.
    /// </summary>
    /// <param name="skip">The number of contacts to skip (optional). Default value is 0. Must be greater than or equal to 0.</param>
    /// <param name="take">The number of contacts to take (optional). Default value is 30. Must be between 1 and 100.</param>
    /// <param name="searchTerm">The search term (optional). White space at the front and back will be trimmed automatically. Contacts whose name start with the search term will be found.</param>
    /// <response code="400">Bad Request: the paging parameters are invalid.</response>
    public static async Task<IResult> GetContacts(int skip = 0, int take = 30, string? searchTerm = null)
    {
         if (skip < 0 || take is <= 0 or take > 100)
             return Result.BadRequest();

         // Open a database session here, load the paged contacts and return them
         return Result.Ok(contactListDto);
    }
}
```

You can then map this endpoint in Program.cs like so

```csharp
app.MapGetContactsEndpoint();
```

**Comment by ch-lee** [comment]
This worked!

On top of configuring Swashbuckle, I needed to add this extra part:

```csharp
builder.Services.AddSwaggerGen(opts =>
{
    var xmlFilename = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    opts.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, xmlFilename));
});
```

**Comment by LeoJHarris** [comment]
@ch-lee I can confirm this worked:

In my case I still need to add this to the `csproj` file:

<GenerateDocumentationFile>true</GenerateDocumentationFile>

https://stackoverflow.com/questions/69790435/swagger-asp-net-core-minimal-api-include-xml-comments-files

**Comment by Hoopou** [comment]
> @ch-lee I can confirm this worked:
> 
> In my case I still need to add this to the `csproj` file:
> 
> ```
> <GenerateDocumentationFile>true</GenerateDocumentationFile>
> ```
> 
> https://stackoverflow.com/questions/69790435/swagger-asp-net-core-minimal-api-include-xml-comments-files

I just created a blank api in .net 6 and I needed to add it too!, Thanks

**Comment by dnperfors** [comment]
On .NET 7 I was able to get this working, just as @feO2x describes, however examples on <param> elements don't work. All descriptions are correctly shown.

**Comment by dotnetshadow** [comment]
Has anyone got this to work with a non static class? What happens if you need to use dependency injection in your class?

**Comment by dotnetshadow** [comment]
Does this still work if you don't use statics?

If you use instance base, it doesn't look like it generates it correctly, am I missing something?
`app.MapPost("/do-something", (int foo, string bar, FooHandler handler) =>
    handler.Process(foo, bar));`

**Comment by martincostello** [comment]
> we should just use (where xml comment do indeed work)

Yes.

> And the static method can handle the dependency injection stuff?

Yes.
