### ISSUE TITLE
Response type is ignored when add Filters

### ISSUE THREAD

**Issue by Merynek** [domaindrivendev/Swashbuckle.AspNetCore#2269]
In startup.cs I add filter for all Error response, bcs I return own error object (ErrorResponse) by throw exception and in middleware I return this code in response. But these errors are not as a return type in controllers methods so I have to add filter to all responses. It works and in swagger.json are these responses but without response type (200) there are only error responses.

```
services.AddMvc(options =>  {
                options.EnableEndpointRouting = false;
                options.Filters.Add(new Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute(typeof(ErrorResponse), (int)HttpStatusCode.BadRequest));
                options.Filters.Add(new Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute(typeof(ErrorResponse), (int)HttpStatusCode.Unauthorized));
                options.Filters.Add(new Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute(typeof(ErrorResponse), (int)HttpStatusCode.NotFound));
                options.Filters.Add(new Microsoft.AspNetCore.Mvc.ProducesResponseTypeAttribute(typeof(ErrorResponse), (int)HttpStatusCode.InternalServerError));
            })
```

![image](https://user-images.githubusercontent.com/6883795/141262370-6e8b4d55-f861-47a3-b98f-6ff8880d69b3.png)

Here is example one of my method with return type but it doesnt display in swagger.
```
public async Task<ActionResult<HorseEntity>> GetHorseById(int id) 
```

Does anybody know how can I preserve default return type from controllers methods? Thank you. :-)

**Comment by guzzit** [comment]
Hi, is this still an issue? You could add the ProducesResponseType attribute on top of the specific method in the controller.

`
[ProducesResponseType(StatusCodes.Status200OK, Type = typeof(ErrorResponse))]
public async Task<ActionResult<HorseEntity>> GetHorseById(int id) 
 `

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
