### ISSUE TITLE
Use bootstrap in index.html

### ISSUE THREAD

**Issue by Gillardo** [domaindrivendev/Swashbuckle.AspNetCore#227]
Is there a way i can use bootstrap on the generated index.html file, or inject a style sheet and change the css used??

**Comment by Gillardo** [comment]
Also, this URL on the readme file is not pointing to anything??  But it is referenced on microsoft??

https://github.com/domaindrivendev/Ahoy/tree/master/test/WebSites/CustomizedUi/wwwroot/swagger/ui

**Comment by Gillardo** [comment]
Also, is a new version going to be released soon as the code in the samples, does not match what is available in version beta902.  For example, .UseSwaggerUi extension method only accepts 2 parameters, but in the master branch it accepts Options

**Comment by alzuma** [comment]
Just put index.html in wwwroot\swagger\ui and alter it as you wish.

**Comment by Gillardo** [comment]
This does not work.  I have put a custom index.html into wwwroot/swagger/ui folder and it is not being shown

**Comment by alzuma** [comment]
app.UseStaticFiles(); is present int Startup.cs?

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
     app.UseStaticFiles();

     app.UseSwagger();
     app.UseSwaggerUi();

     app.UseMvc();
}
```

reference https://auth0.com/forum/t/webapi-authentication-with-swagger/1803/7

**Comment by alzuma** [comment]
What is the request path of original index.html, when you look in dev mode (F12)
it should be http://locolhost:<port>/swagger/ui/index.html if so, it should work, if no change folder path according what you see. Remember to clear cache, it may be still in cache.

**Comment by Gillardo** [comment]
I have changed the path, so that i need to request http://localhost:5000/api/v1/index.html which is specified in the base route property.  I am guessing i need to copy the index.html page to this folder instead??

**Comment by alzuma** [comment]
Yep, then copy index.html into wwwroot/api/v1/
