### ISSUE TITLE
Removing a property of schema in a DocumentFilter has stopped working fine.

### ISSUE THREAD

**Issue by vicentt** [domaindrivendev/Swashbuckle.AspNetCore#2275]
I just upgraded a project to AspNet Core 3.1 and Swashbuckle to 6.2.3

In both, the previous and current version, I have a DocumentFilter that removes certain properties of some models that I don't want to show in the model declaration or in the responses returned by the interface.

Before updating, this was working fine.
Now the properties are omitted in the models but they are still in the response body returned by the web app

```
public class DocumentFilter : IDocumentFilter 
    {
        public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
        {
            if (swaggerDoc.Components.Schemas["ContentParameters"].Properties.ContainsKey("client_id"))
                swaggerDoc.Components.Schemas["ContentParameters"].Properties.Remove("client_id");
        }
    }
```
Here the prop is omit
![Captura de pantalla 2021-11-18 140429](https://user-images.githubusercontent.com/7046127/142421309-a1dd0443-cb02-49e3-8747-97b277ef3ba6.png)

But here still appearing
![Captura de pantalla 2021-11-18 140929](https://user-images.githubusercontent.com/7046127/142421326-2435a2b5-3523-4c28-95e7-c295e8a8a21d.png)

I insist that in previous versions, the code above, removes the property of both sites.
am I doing something wrong?
Is there any way to edit the return of response body?

Thanks in advance.

**Comment by saeb-panahifar** [comment]
Would you like to use `client_id `in your API response and not show in Swagger?

**Comment by vicentt** [comment]
Maybe i have conditional models that depends of something like the authorization data such the role or something like that. 
If you are identified with an account with certain privileges you can see certain fields. 
If I have something like this in my api It would be desirable for me that OpenApi could represent it.

**Comment by saeb-panahifar** [comment]
Swagger generates a response body schema based on the response body model. Removing property from a schema doesn't mean that removing the property from the response object. However, in your scenario, you can leave `client_id` or other properties like that as is. and add the below code in ConfigurationServices: 

 ```csharp
services.AddControllers().AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault;
            });
 ```
And also set null for those types of properties, If the account does not have privileges.

**Comment by vicentt** [comment]
This has worked. 
When migrating the null handling configuration in the json's had changed.

Swashbuckle had nothing to do there.

Thank you very much for your help
