### ISSUE TITLE
RangeError: Maximum call stack size exceeded (version 6.2.3)

### ISSUE THREAD

**Issue by boda3369** [domaindrivendev/Swashbuckle.AspNetCore#2276]
Hello, swagger-ui is giving RangeError: Maximum call stack size exceeded when trying to see operation details with this complex swagger:

{
  "openapi": "3.0.1",
  "info": {
    "title": "Test API",
    "description": ".NET Core 3.1",
    "version": "v1"
  },
  "paths": {
    "/api/Policies/PolicyDetail": {
      "post": {
        "tags": [
          "Policies"
        ],
        "parameters": [
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GetPolicyDetailInputData"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/GetPolicyDetailInputData"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetPolicyDetailOutputData"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/GetPolicyDetailOutputData"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "GetPolicyDetailInputData": {
        "type": "object",
        "properties": {
          "policyNumber": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": ""
      },
      "GetPolicyDetailOutputData": {
        "type": "object",
        "properties": {
          "insuredPerson": {
            "oneOf": [
              {
                "$ref": "#/components/schemas/InsuredPersonElement"
              }
            ],
            "nullable": true
          }
        }
      },
      "InsuredPersonElement": {
        "type": "object",

        "properties": {
          "coverages": {
            "type": "array",
            "items": {
              "oneOf": [

                {
                  "$ref": "#/components/schemas/OtherCoverageElement"
                }
              ]
            },
            "nullable": true
          }
        }
      },
      "CoverageElement": {
        "type": "object",
        "properties": {
        }
      },
      "OtherCoverageElement": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/CoverageElement"
          }
        ],
        "properties": {
          "warranties": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "$ref": "#/components/schemas/OtherCoverageElement"
                }
              ]
            },
            "nullable": true
          }
        }
      }
    }
  }
}

Can you please help?

**Comment by msalmankarim** [comment]
+1 Getting the same issue

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/11595290/42ba67af-7402-4e4c-9507-6fc28c7373bb)

I have seen that whenever there are recursive objects in the schema, swagger-ui gives this error.

**Comment by msalmankarim** [comment]
It is fixed in swagger-ui but not sure if the updated version is being used by Swashbuckle

https://github.com/swagger-api/swagger-ui/releases/tag/v5.0.0-alpha.6

**Comment by martincostello** [comment]
I'm closing this as external, but we have #2789 to track upgrading the version we ship with.
