### ISSUE TITLE
there is a controller name bug

### ISSUE THREAD

**Issue by junshangshui** [domaindrivendev/Swashbuckle.AspNetCore#2277]
![ed139ab4a1a98eff4242cf46bfd3b61](https://user-images.githubusercontent.com/40519621/142761016-196fb4f0-d5b8-4a7a-8c2a-d3271521692d.png)

**Comment by junshangshui** [comment]
Swashbuckle.AspNetCore 6.2.3 and .net6.0

**Comment by zhanghaomars** [comment]
@junshangshui 这边有没有遇到部署时通过nginx转发后 Servers /s1这里无法显示 并且在swagger中通过接口调用时url没有把/s1/这个路径加上？

**Comment by junshangshui** [comment]
> 

有

**Comment by junshangshui** [comment]
> @junshangshui这边有没有遇到部署时通过nginx转发后 Servers /s1这里无法显示 并且在swagger中通过接口调用时url没有把/s1/这个路径加上？

有的
