### ISSUE TITLE
.NET 6 application: I do not see the parameter 

### ISSUE THREAD

**Issue by ZedZipDev** [domaindrivendev/Swashbuckle.AspNetCore#2291]
I have a .NET 6 minimal api application. When I use method with int type parameter like

```
app.MapGet("/calc/{sum1}", (int sum1) =>
{
    var msg = String.Format($"Hey {sum1}");
    Log.Information("/calc/{0} response: {1}", sum1, msg);
    return msg;
})
.WithName("Calc");
```
then Swagger page shows me this method with **parameter** and I can try it out. 
But if I use method like this

```
app.MapGet("/calc3/{prod1}", (Product prod1, CalcSvc calcSvc) =>
{
    var msg = String.Format($"Hey {prod1}");
    Log.Information("/calc3/{0} response: {1}", prod1, msg);
    return msg;
})
.WithName("Calc3");
//.....
class Product
{
    // These are public fields, not properties.
    public int Id;
    public string? Name;
}
```
then Swagger page show the method but it does not show **parameter** and I cannot try it out

What is incorrect?

**Comment by ahamdan-ow** [comment]
Were you able to solve it? Am facing similar issue.

**Comment by martincostello** [comment]
Try decorating the parameter object with `[AsParameters]`.
