### ISSUE TITLE
Swashbuckle generates excluded endpoints Schemas (unreferenced schema)

### ISSUE THREAD

**Issue by AmirSasson** [domaindrivendev/Swashbuckle.AspNetCore#2292]
When using Aspnet core `ApiVersion`, some of my Controllers are Excluded when generating a Swagger Document on a specific version., simply by using [DocInclusionPredicate](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/21391c2ea7dcb407784689ad861560623169673f/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs#L33).
unfortunately Swashbuckle still generates all the excluded Controllers Schemas.
the expected result is not even bother to create them.
currently, i has to implement a "Tree Shake" of definitions (document filter) that removes unreferenced definitions, But the expected result is to exlude these schamas on earlier phases as they are no references by any rendered operation. 

more over sometimes, the controller with [ApiVersion] X, has conflict in schemas on controller with [ApiVersion] Y. for example Request Body class is the same name with different Namespace. which make things more complicated.
by excluding these schemas (that are not use) on earlier phase, it would fix the entire problem

**Comment by domaindrivendev** [comment]
Hmmm this shouldn’t be the case as the DocInclusionPredicate does the filtering at a very early stage before Schemas are generated. Could you please create a simple app from scratch that repro’s the issue and post to GitHub where I can pull down and troubleshoot?

**Comment by AmirSasson** [comment]
you are right, i doubled check now, seems like the problem is else where.
i will get to the bottom of it and close this Issue if necessary

**Comment by AmirSasson** [comment]
false alarm, sorry
the source of the problem was when i customize the registration of polymorphism
