### ISSUE TITLE
Change name of model classes

### ISSUE THREAD

**Issue by ultravelocity** [domaindrivendev/Swashbuckle.AspNetCore#230]
Is there a way to change the name of the models in the Swagger definition? Our classes end in "DTO" and we would prefer to strip that from the documentation.

**Comment by DalSoft** [comment]
You can do by implementing a IOperationFilter and removing DTO

**Comment by domaindrivendev** [comment]
Or easier still, you can provide your own schema Id strategy with a call to _CustomSchemaIds_ as described here - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-schema-ids

**Comment by divyang-desai** [comment]
sdsd
![bitmoji](https://render.bitstrips.com/v2/cpanel/732eaa6e-2db0-48dc-b8d8-4484ec74e70f-7b25a5d6-4951-453a-bb29-761f2a3b3df6-v1.png?transparent=1&palette=1&width=246)
