### ISSUE TITLE
The objects list is not displayed correctly

### ISSUE THREAD

**Issue by gerardgsl** [domaindrivendev/Swashbuckle.AspNetCore#2302]
Hi! I am doing a controller that has to receive an object. This object has a list of objects of type < ShippingAddressDTO>.
My problem is that swagger does not show the object type of the list. Even knowing the object type and introducing the fields in swagger, it arrives as null in the controller.

![image (1)](https://user-images.githubusercontent.com/32109972/147348396-90c6b857-3472-4138-81ac-52b652665227.png)
![image (2)](https://user-images.githubusercontent.com/32109972/147348399-c4a5a6d6-56d4-4cef-99f9-dcdf1399fb30.png)

I use the following libraries for the code:

Swashbuckle.AspNetCore.Annotations Version="5.6.3"
Swashbuckle.AspNetCore.SwaggerGen Version="5.6.3"
Swashbuckle.AspNetCore.SwaggerUI Version="5.6.3"

Swashbuckle.AspNetCore.Filters Version="6.0.0"
Microsoft.AspNetCore.Authorization;
Microsoft.AspNetCore.Mvc;
Microsoft.AspNetCore.Mvc.ModelBinding;

I have deleted the unnecessary code. Here is the swagger file.

`{
  "openapi": "3.0.1",
  "info": {
    "title": "Distrib WebAPI",
    "description": "Welcome to Distrib WebAPI. Please check Authentication paragraph at the end of the document to know how to authenticate against the API before using it.You can switch between definitions at the top of documentation to watch the API methods corresponding to the version of the API you are using",
    "version": "v1.8.0.0-ECommerce"
  },
  "servers": [
    {
      "url": "/pccom"
    }
  ],
  "paths": {
    "/PCCOM.Distrib.Clients.ECommerce/Clients": {
      "post": {
        "tags": [
          "Clients"
        ],
        "summary": "Creates a new B2B or B2C client",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "required": [
                  "ShippingAddresses"
                ],
                "type": "object",
                "properties": {
                  "Role": {
                    "$ref": "#/components/schemas/PCCOM.Distrib.Core.DTOs.RoleType"
                  },
                  "PDFDocument": {
                    "type": "string",
                    "format": "binary",
                    "nullable": true
                  },
                  "ShippingAddresses": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/PCCOM.Distrib.Clients.DTOs.v1_6.ShippingAddDTO"
                    }
                  }
                }
              },
              "encoding": {
                "Role": {
                  "style": "form"
                },
                "PDFDocument": {
                  "style": "form"
                },
                "ShippingAddresses": {
                  "style": "form"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Creates a new client",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "400": {
            "description": "Invalid model submitted"
          },
          "401": {
            "description": "User not successfully authenticated"
          },
          "403": {
            "description": "User without client creation permission"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PCCOM.Distrib.Core.DTOs.RoleType": {
        "enum": [
          1,
          2
        ],
        "type": "integer",
        "format": "int32"
      },
      "PCCOM.Distrib.Clients.DTOs.v1_6.ShippingAddDTO": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string",
            "nullable": true
          },
          "phoneNumber": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "apiKey",
        "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "Bearer": []
    }
  ]
}`

**Comment by martincostello** [comment]
As far as I'm aware, this is a SwaggerUI issue - it will only pre-populate the forms in the UI if you provide an example payload.
