### ISSUE TITLE
Constraint doesn't work in HTTP methods

### ISSUE THREAD

**Issue by VladislavMorozovIDT** [domaindrivendev/Swashbuckle.AspNetCore#2304]
The issue relates with constraints in GET.
.NET - 6 version
Swashbuckle.AspNetCore - 6.2.3 version
![image](https://user-images.githubusercontent.com/87074340/147666115-1ab89f20-d4c6-4226-8b40-ccd66809bd7d.png)
![image](https://user-images.githubusercontent.com/87074340/147666126-fb5c2001-cd11-43fb-8af9-d2b4923c966f.png)
Solution was attached.
[SwaggerIssue.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/7789004/SwaggerIssue.zip)

**Comment by chrisoverzero** [comment]
I believe this has been resolved by #2610.
