### ISSUE TITLE
The fromform multiparameter has no comments,

### ISSUE THREAD

**Issue by bbhxwl** [domaindrivendev/Swashbuckle.AspNetCore#2308]
![image](https://user-images.githubusercontent.com/26525599/148911137-526e199b-f94d-47c6-bb14-878088985117.png)
If you delete fromform, you can have comments. I don't know why? I want post to receive two parameters. If fromform is not written, the parameters are received by URL

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
