### ISSUE TITLE
If I have multiple APIs and want to give them to different people, how can I distinguish them?

### ISSUE THREAD

**Issue by bbhxwl** [domaindrivendev/Swashbuckle.AspNetCore#2311]
How can I make different people see different APIs? Instead of him seeing me all?

 /swagger/index.html
 /swagger/index2.html
  /swagger/index3.html

**Comment by martincostello** [comment]
There's not enough information here to offer a more specific answer, but you're probably going to need to implement custom behaviour on your endpoint metadata (e.g. attributes and/or schema filters) to show/hide things based on the user associated with the current HTTP request.
