### ISSUE TITLE
GetType() not available in .net6

### ISSUE THREAD

**Issue by ranouf** [domaindrivendev/Swashbuckle.AspNetCore#2317]
Hi,

I'm trying .net 6. I noticed that GetType() is not available anymore with the new way to configuration the API in program.cs:

```
app.UseSwaggerUI(c =>
{
    c.RoutePrefix = "api-endpoints";
    c.SwaggerEndpoint("v1/swagger.json", $"{Constants.Project.Name} V1");
    c.IndexStream = () => GetType().GetTypeInfo().Assembly.GetManifestResourceStream($"{Constants.Project.Name}.Servers.API.Assets.SwaggerIndex.html");
});
```

![image](https://user-images.githubusercontent.com/1764519/150427175-d988b335-2017-4d41-924a-804021990076.png)

It could be interesting to update the documentation too here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore

What is the new way to configure the indexStream with .net 6?

**Comment by ranouf** [comment]
The solution is:

```
app.UseSwaggerUI(c =>
{
    c.RoutePrefix = "api-endpoints";
    c.SwaggerEndpoint("v1/swagger.json", $"{Constants.Project.Name} V1");
    c.IndexStream = () => **app.**GetType().GetTypeInfo().Assembly.GetManifestResourceStream($"{Constants.Project.Name}.Servers.API.Assets.SwaggerIndex.html");
});
```

**Comment by ranouf** [comment]
Which results to this error:

> An unhandled exception occurred while processing the request.
> ArgumentNullException: Value cannot be null. (Parameter 'stream')

The file is correctly added as an embedded ressource in the csproj:

		```
<EmbeddedResource Include="Assets\SwaggerIndex.html" />
		<EmbeddedResource Include="Assets\HealthChecks.css">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
```

And the file in solution:
![image](https://user-images.githubusercontent.com/1764519/150450376-95cb8155-6d26-4ddc-a49f-44fc66ff3c70.png)

**Comment by reburger** [comment]
Wow, first time I've ever been able to contribute anything.  @ranouf, I don't know if it's the RIGHT WAY, but I got this to work with the following syntax:

                c.IndexStream = () => **MethodBase.GetCurrentMethod().DeclaringType.**Assembly.GetManifestResourceStream($"{FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileDescription}.wwwroot.SwaggerCustomIndex.html");

**Comment by martincostello** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2318#issuecomment-2088013623
