### ISSUE TITLE
How to support binary and json on same endpoint

### ISSUE THREAD

**Issue by semsitivity** [domaindrivendev/Swashbuckle.AspNetCore#2328]
Hi,
I have an endpoint (same path) which must support a byte[]=application/octet-stream or a json=application/json.
The reason is that clients can eventually use compression for their payload.

Both definition I have are correct and works alone, but I have a conflict when declaring them at the same time.
Is there a way to make that working ?

**Comment by domaindrivendev** [comment]
Can you create a sample app to demonstrate your problem and push to GitHub so I can pull down and see what’s possible

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
