### ISSUE TITLE
Unsigned values (uint, ulong) are coerced to signed values (int, long)

### ISSUE THREAD

**Issue by KennethRMason** [domaindrivendev/Swashbuckle.AspNetCore#233]
I have some POCOs that I'm returning out of methods that make use of unsigned fields.  In the `swagger.json`, I'm observing there's no indication that the field is unsigned, and it manifests as a ordinary / signed field.  For example:
```
public class Foo {
        public uint Bar { get; set; }
}
```
Results in this field in `swagger.json`:
```
"bar": {
    "format": "int32",
     "type": "integer"
},
```

As a result, when we consume the `swagger.json` from our fork of Swagger Codegen, the resulting client POCOs contain `int`s rather than `uint`s.

Please correct the `swagger.json` generator to emit an accurate value for the `format` field for unsigned fields.  We happen to be using `uint` and `ulong`, but this seems like something that should be dealt with for all unsigned types.

Swagger Codegen needs an update to cope with unsigned values, too.  We will be updating our fork for the new formats once this problem has been corrected.

**Comment by Igmat** [comment]
As you can see [here](http://swagger.io/specification/#dataTypeFormat) there are no predefined unsigned formats in Swagger. So Swachbuckle should not produce them, because it could create inconsistence with existing swagger tooling.
But you are able to workaround it with `ISchemaFilter` I suppose.
