### ISSUE TITLE
Migrating application [webapi] from .Net core 2.0 to dot6.0 : SchemaFilter causing exception 

### ISSUE THREAD

**Issue by AJEETX** [domaindrivendev/Swashbuckle.AspNetCore#2330]
Within Startup.cs 

             public void ConfigureServices(IServiceCollection services)
             {
                    services.AddSwaggerGen(c =>
                    {
                            c.SwaggerDoc("v1", new OpenApiInfo { Title = "IPM API", Version = "v1" });
	                     // other code
                          c.SchemaFilter<DataContractSchemaFilter>();
                     });
                }
              public void Configure((...)
              {
                     app.UseMvc();

            app.UseSwagger(c =>
            {
                  c.RouteTemplate = "api/swagger/{documentname}/swagger.json";
            });

            app.UseSwaggerUI(c =>
           {
                c.SwaggerEndpoint("v1/swagger.json", "IPM API V1");
                c.RoutePrefix = "api/swagger";
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
             });
    }`
And below is the SchemaFilter Implementation

             public class DataContractSchemaFilter : ISchemaFilter
            {
             public void Apply(OpenApiSchema schema, SchemaFilterContext context)
             {
                   foreach (var property in context.Type.GetProperties())
                   {
                           var name = property.GetCustomAttribute<DataMemberAttribute>()?.Name;
                          if (name == null)
                           {
                                  continue;
                               }

                       if (!schema.Properties.ContainsKey(name))
                           {
                           schema.Properties[name] = schema.Properties[property.Name];
                            schema.Properties.Remove(property.Name);
                           continue;
                           }
                         }
                     }
               }

And the error in the log is

`{"EventId":13,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Server.Kestrel","Message":"Connection id \u00220HMF6K7UVOCD8\u0022, Request id \u00220HMF6K7UVOCD8:00000003\u0022: An unhandled exception was thrown by 
the application.","Exception":"Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - xxxservice.Ranging.Controllers.PlanRangeController.PostNewGroupDefaultParameters (xxxservice). See inner exception  ---\u003E Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - System.Collections.Generic.IEnumerable\u00601[Ranging.Models.PlanRangeParameters]. See inner exception  ---\u003E 
System.Collections.Generic.KeyNotFoundException: The given key \u0027OnRange\u0027 was not present in the dictionary.    at System.Collections.Generic.Dictionary\u00602.get_Item(TKey key)    at xxxservice.Utils.DataContractSchemaFilter.Apply(OpenApiSchema schema, SchemaFilterContext context) in C:\\Users\\atiwari\\source\\repos\\ipm-service\\xxxservice\\Utils\\DataContractSchemaFilter.cs:line 22    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.ApplyFilters(OpenApiSchema schema, Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func\u00601 definitionFactory)    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type modelType, SchemaRepository schemaRepository)    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateArraySchema(DataContract dataContract, SchemaRepository schemaRepository)    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.\u003C\u003Ec__DisplayClass10_0.\u003CGenerateConcreteSchema\u003Eb__1()    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForParameter(Type modelType, SchemaRepository schemaRepository, ParameterInfo parameterInfo)    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo)    --- End of inner exception stack trace ---    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo)    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBodyFromBodyParameter(ApiDescription apiDescription, SchemaRepository schemaRepository, ApiParameterDescription bodyParameter)    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBody(ApiDescription apiDescription, SchemaRepository schemaRepository)  
  at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)    --- End of inner exception stack trace ---    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable\u00601 apiDescriptions, SchemaRepository schemaRepository)    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable\u00601 apiDescriptions, SchemaRepository schemaRepository)    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)    
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Serilog.Enrichers.AspNetCore.HttpContext.SerilogLogContextMiddleware.InvokeAsync(HttpContext context)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication\u00601 application)","State":{"Message":"Connection id \u00220HMF6K7UVOCD8\u0022, Request id 
\u00220HMF6K7UVOCD8:00000003\u0022: An unhandled exception was thrown by the application.","ConnectionId":"0HMF6K7UVOCD8","TraceIdentifier":"0HMF6K7UVOCD8:00000003","{OriginalFormat}":"Connection id \u0022{ConnectionId}\u0022, Request id \u0022{TraceIdentifier}\u0022: An unhandled exception was thrown by the application."}}
xxxservice      | [23:16:08 ERR RequestId: 0HMF6K7UVOCD8:00000003] Connection id "0HMF6K7UVOCD8", Request id "0HMF6K7UVOCD8:00000003": An unhandled exception was thrown by the application.
xxxservice      | Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - xxxservice.Ranging.Controllers.PlanRangeController.PostNewGroupDefaultParameters (xxxservice). 
See inner exception
xxxservice      |  ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - System.Collections.Generic.IEnumerable`1[Ranging.Models.PlanRangeParameters]. See inner exception
xxxservice      |  ---> System.Collections.Generic.KeyNotFoundException: The given key 'OnRange' was not present 
in the dictionary.
xxxservice      |    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
xxxservice      |    at xxxservice.Utils.DataContractSchemaFilter.Apply(OpenApiSchema schema, SchemaFilterContext context) in C:\Users\atiwari\source\repos\ipm-service\xxxservice\Utils\DataContractSchemaFilter.cs:line 22
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.ApplyFilters(OpenApiSchema schema, Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type modelType, SchemaRepository schemaRepository)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateArraySchema(DataContract dataContract, SchemaRepository schemaRepository)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass10_0.<GenerateConcreteSchema>b__1()
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForParameter(Type modelType, SchemaRepository schemaRepository, ParameterInfo parameterInfo)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo)
xxxservice      |    --- End of inner exception stack trace ---
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBodyFromBodyParameter(ApiDescription apiDescription, SchemaRepository schemaRepository, ApiParameterDescription bodyParameter)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBody(ApiDescription apiDescription, SchemaRepository schemaRepository)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
xxxservice      |    --- End of inner exception stack trace ---
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
xxxservice      |    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
xxxservice      |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
xxxservice      |    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
xxxservice      |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) 
xxxservice      |    at Serilog.Enrichers.AspNetCore.HttpContext.SerilogLogContextMiddleware.InvokeAsync(HttpContext context)
xxxservice      |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

swagger nuget packages installed are 

                 <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
                 <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.2.3" />
Pls advise.

**Comment by domaindrivendev** [comment]
This is your code throwing the exception - surely you can debug it and troubleshoot yourself???

From a quick glance though, it looks like you're assuming that property names in the generated schema will always be the same as the underlying C# property name. But in reality, they can often be different - e.g. if the serializer is configured to output property names in _cameCase_ or if explicit json property names are applied via serializer attributes. My guess is you need to update your code to account for this.
