### ISSUE TITLE
The opblock-summary-control (button) flex layout not showing correctly

### ISSUE THREAD

**Issue by JerseyTechGuy** [domaindrivendev/Swashbuckle.AspNetCore#2332]
It appears that starting in Swashbuckle.AspNetCore version 6.2.1 there is a problem with the flex layout for the opblock-summary-control (button).  It is showing part of the text in a single column (vertically). This was working fine in 6.1.5.

![image](https://user-images.githubusercontent.com/6929343/152822299-96b55ea2-68b3-425e-8608-07a64e8fa728.png)

**Comment by mmatlock-tminus** [comment]
Seeing the same issue in 6.3.1

**Comment by Yann577** [comment]
Has anyone found a workaround ?
