### ISSUE TITLE
Access DataContract and CLR Type in Open Generic Mapping

### ISSUE THREAD

**Issue by Danielku15** [domaindrivendev/Swashbuckle.AspNetCore#2333]
In https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1599 and https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1600 there was support for open generics added. 

Unfortunately we can only register a simple `Func<OpenApiSchema>` and therefore we cannot access any details of the actual type being mapped. This is problematic if you have complex models where the generic type argument is used internally to encode some aspects. 

Some usecases: 
- A `Delta<TEntity>` object which has all properties of TEntity but as not required
- A `QueryResult<TEntity>` object which serializes as some custom object holding an array of `TEntity` inside the object. 

I have custom `JsonConverter`s for these classes because their serialization involves some complex logic. 

It would be great if we can have an overload like this: 
```cs
public interface ISchemaFactory
{
  OpenApiSchema CreateSchema(Type type, DataContract dataContract);
}
//  SwaggerGenOptionsExtensions
public static void MapType<TMappedType, TSchemaFactory>(this SwaggerGenOptions swaggerGenOptions) where TSchemaFactory : ISchemaFactory
{
}
```

Where `type` is the concrete type for which a schema is generated allowing access to the type arguments and `dataContract` is the related data contract which the `SchemaGenerator` acquired. The registration of the factory as type instead of instances should allow usage of injected service in the schema factory. 

That's the simple proposal, a more advanced version could try to use the Microsoft DI infrastructure directly. Instead of registering the factories on the `SwaggerGenOptions` we would register them in the DI container as transient services. 

My current workaround is to use SchemaFilters but this is not nice because a lot of types are potentially added to the overall schema which I have to clean again.

**Comment by domaindrivendev** [comment]
If you need to tweak the generated schemas to account for serializer customizations in your app (e.g. via `JsonConverter`), and the basic `MapType(Func<OpenApiSchema>)` approach doesn't meet your needs, then you can create and register a `SchemaGenerator` "decorator". Here's a very basic example to give you the general idea:

```csharp
// Startup.cs
services.Replace(ServiceDescriptor.Transient<ISchemaGenerator, CustomSchemaGenerator>());
```

```csharp
internal class CustomSchemaGenerator : ISchemaGenerator
{
    private readonly SchemaGenerator _schemaGenerator;

    public CustomSchemaGenerator(IOptions<SchemaGeneratorOptions> optionsAccessor, ISerializerDataContractResolver dataContractResolver)
    {
        _schemaGenerator = new SchemaGenerator(optionsAccessor.Value, dataContractResolver);
    }

    public OpenApiSchema GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo = null, ParameterInfo parameterInfo = null)
    {
        if (modelType.IsConstructedGenericType && modelType.GetGenericTypeDefinition() == typeof(Delta<>))
        {
            var entityType = modelType.GenericTypeArguments[0];
            var entitySchema = _schemaGenerator.GenerateSchema(entityType, schemaRepository, memberInfo, parameterInfo);
            return entitySchema;
        }

        return _schemaGenerator.GenerateSchema(modelType, schemaRepository, memberInfo, parameterInfo);
    }
}
```

**Comment by Danielku15** [comment]
This solution only properly works well if you are the owner of the final service collection / application. 😞  I am within a library and want to register some custom types this library ships within Swashbuckle. Replacing the whole `ISchemaGenerator` has the negative implication that any `ISchemaGenerator` the people have in their actual application code would be overwritten which is usually not in their interest.
