### ISSUE TITLE
:path fails to match routes with model binding

### ISSUE THREAD

**Issue by gpgpublickey** [domaindrivendev/Swashbuckle.AspNetCore#2343]
Hi, I'm experiencing an issue related to endpoint's routes, let me explain with a basic example:
Assuming the route:
`[HttpGet("/something/myResource/{identifierNumber}")] public string GetClient([FromRoute] ClientRequest request)`

Where ClientRequest class is:
```
    public class Client
    {
        public int IdentifierNumber { get; set; }
    }
```
If you use any other client than swagger UI to make the request call, it will work correctly, but from swagger UI it will fail to bind the parameters in the **:path** header showing something like:
![image](https://user-images.githubusercontent.com/7245667/153230963-78176618-efec-47a3-a746-3bb033fa089e.png)

Looks like something is wrong between Swashbuckle and model binder with different casing conventions, as workaround I can replace {identifierNumber} by {IdentifierNumber} but this smells like a bug for me.

If you reproduce this case you will be able to see the issue.
My Swashbuckle version: latest
Working with Net5

**Comment by schallm** [comment]
If it helps, here is my example controller class:

```c#
	[Route("api/user-summary")]
	[ApiController]
	public class UserSummaryController : ControllerBase {

		[HttpGet("{Agency}/{FirstName}", Name = "GetSummary")]
		public SummaryResponse Get([FromRoute] SummaryRequest request) {
			// do work with request object
			return new SummaryResponse {
				Agency = request.Agency,
				FirstName = request.FirstName
			};
		}

		public class SummaryRequest {

			[FromRoute]
			public string Agency { get; set; }

			[FromRoute]
			[RegularExpression(@"^.{1,40}$", ErrorMessage = "Characters not allowed.")]
			public string FirstName { get; set; }

		}

		public class SummaryResponse {

			public string? Agency { get; set; }

			public string? FirstName { get; set; }

			// other properties

		}

	}
```

**Comment by gpgpublickey** [comment]
No news regarding the issue is stills there.

**Comment by domaindrivendev** [comment]
The problem here is the difference in casing between the property name (`IdentifierNumber` from @gpgpublickey's example) and the corresponding route parameter in the route template (`{identifierNumber}`). So, to quickly resolve you can use the uppercase name in the route template OR force Swashbuckle to use pascal casing for _all_ parameter names with the `DescribeAllParametersInCamelCase()` config setting.
