### ISSUE TITLE
[Feature Request] Add PostSerialization filter

### ISSUE THREAD

**Issue by Vampire2008** [domaindrivendev/Swashbuckle.AspNetCore#2344]
Hello!
Can you add PostSerialization filter to modify resulting JSON or YAML?
Some options cannot be modified before generating due limitation of OpenAPI.NET.
For example I have to clear `path/{path}/produces` array on OpenAPI v2. Currently it generated from `OpenApiOperation.Responses` where MIME type required.

Currenty I can do it only by writing my own middeware to return JSON instead of using your.

**Comment by martincostello** [comment]
Support for this use case was implemented by #2677.
