### ISSUE TITLE
Annotating via XML comments breaks API1000 analyser

### ISSUE THREAD

**Issue by lonix1** [domaindrivendev/Swashbuckle.AspNetCore#2347]
The library recommends to avoid attributes and [do this instead](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments):
````cs
/// <response code="200">Success.</response>
````

However that triggers `API1000` analyser:
> Action method returns undeclared status code '201'

So the analyser doesn't consider the xml comments.

Is there a way to overcome this issue without disabling the analyser? Maybe there are Swashbuckle-specific analysers we can use instead?

**Comment by martincostello** [comment]
The two approaches conflict with each other. You'll either need to use attributes or suppress the analyser warnings.
