### ISSUE TITLE
Is it possible to set the "host" attribute seen in swagger.json?

### ISSUE THREAD

**Issue by jmasongit** [domaindrivendev/Swashbuckle.AspNetCore#235]
Is it currently possible to configure the "host" attribute seen in swagger.json?

I found the test website used this, but I did not have any success getting the host to appear in swagger.json:
```
app.UseSwagger(documentFilter: (swaggerDoc, httpRequest) =>
            {
                swaggerDoc.Host = httpRequest.Host.Value;
            });
```

Though, perhaps I'm missing some other dependency of this which needs to be set. Thank you

**Comment by domaindrivendev** [comment]
Although the semantics have changed with the latest version (PLEASE NOTE the package rename to Swashbuckle.AspNetCore.1.0.0-rc1), this general approach should work as described here in the readme - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#modify-swagger-with-request-context.
