### ISSUE TITLE
OpenApiGenerateDocumentsOnBuild not working with .net 6 minimal api ?

### ISSUE THREAD

**Issue by GMouron** [domaindrivendev/Swashbuckle.AspNetCore#2350]
Hello,

I am trying to generate the swagger docs on build with `<OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>` but I experience the following error :
`No method 'BuildWebHost', 'CreateHostBuilder' or 'CreateWebHostBuilder' found in type 'Program' with expected signatures.` 
Version used : 6.2.3
You can find a minimum repro here :
https://github.com/LuccaSA/minmal-api-samples/pull/2
This repo is a fork of https://github.com/Minimal-APIs/samples made by a microsoftie where they describe how to add open api support (https://minimal-apis.github.io/quickstart/openapi.html)
In the first PR (https://github.com/LuccaSA/minmal-api-samples/pull/1), I added the nuget and the necessary code following the  tutorial, and it does indeed work at runtime.

When I inspect the dll, those methods do not exist, so this is "right".
(Note : I experienced the same problem on an internal project also setup as minmal api)

If it's not fixable, would there be a workaround possible ? The doc should probably be updated to mention this case (I could take care of that) ?

Thank you.

**Comment by crhairr** [comment]
I'm seeing the same problem with .NET 6.0 minimal APIs. My guess is that this is caused by [this](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blame/master/src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.csproj#L11) line and declared as a dependency [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blame/master/src/Swashbuckle.AspNetCore/Swashbuckle.AspNetCore.csproj#L27). It appears that Microsoft.Extension.ApiDescription.Server version 3.0.0 doesn't support minimal apis. I manually installed 6.0.2 and ran the included `dotnet-getdocument` tool on my web api assembly, and correctly generated the expected json output file.

**Comment by GMouron** [comment]
Yes, it solved my problem !
I know have a different problem, there is no endpoint listed in the file but I don't think it's linked

**Comment by agilenut** [comment]
Same problem.

Also, I'd like to have a better way to override the host. I know that we can use SwaggerHostFactory or SwaggerWebHostFactory but, now with minimal apis, there's no Startup.cs, and I'd rather not add it. So, I can't use the web host builder to add everything. Ideally, I could use the existing Program.cs but override a couple of things like the app configuration block and logging setup.

**Comment by nielsheeren** [comment]
> We experienced the same problem when switching our "controller"-based APIs to the minimal-API approach. While NSwag and SwashBuckle can generate the swagger.json just fine. `dotnet-getdocument` always produces an empty document. Did any of you already solve this problem?

I had had the same problem and had to fix it by manually setting the `ApplicationName `in `WebApplicationOptions` like this:

```c#
public class SwaggerHostFactory
{
    public static IHost CreateHost()
    {
        var options = new WebApplicationOptions() { ApplicationName = typeof(Program).Assembly.FullName };
        var builder = WebApplication.CreateBuilder(options);
        ...
       }
}
```

**Comment by martincostello** [comment]
Duplicate of #2290.
