### ISSUE TITLE
System.MissingMethodException: Method not found: 'Microsoft.OpenApi.Models.OpenApiSchema

### ISSUE THREAD

**Issue by yarex007pobox** [domaindrivendev/Swashbuckle.AspNetCore#2369]
Getting exception after upgrade from Swashbuckle.AspNetCore" Version="6.2.3"  to 6.3.0

Exception is thrown here: - when foreach hits first filter. I even tried to enforce context.Services.AddTransient<ISchemaGenerator, SchemaGenerator>(); but it did not help.
```

var filterContext = new OperationFilterContext(apiDescription, _schemaGenerator, schemaRepository, methodInfo);
                foreach (var filter in _options.OperationFilters)
                {
                    filter.Apply(operation, filterContext);
                }

                return operation;
            }
            catch (Exception ex)
```

I am using ExampleFilters() to show examples 

> 
> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - Volo.Abp.AspNetCore.Mvc.ApiExploring.AbpApiDefinitionController.Get (Volo.Abp.AspNetCore.Mvc). See inner exception
>  ---> System.MissingMethodException: Method not found: 'Microsoft.OpenApi.Models.OpenApiSchema Swashbuckle.AspNetCore.SwaggerGen.ISchemaGenerator.GenerateSchema(System.Type, Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository, System.Reflection.MemberInfo, System.Reflection.ParameterInfo)'.
>    at Ori.Common.Swagger.Filters.DefaultResponseOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
>    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 137
>    --- End of inner exception stack trace ---
>    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 158
>    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 127
>    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 87
>    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 42
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Swagger\SwaggerMiddleware.cs:line 42
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Ori.Common.TenantSupport.AspNetCore.TenantSupportMiddleware.Invoke(HttpContext httpContext, ITenantResolver tenantResolver, ITenantProvider tenantProvider)
>    at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.AspNetCore\Volo\Abp\AspNetCore\Tracing\AbpCorrelationIdMiddleware.cs:line 27
>    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
>    at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by Freakazoid182** [comment]
What fixed this for me was do a clean -> rebuild of the project.

**Comment by yarex007pobox** [comment]
Nope, that did not help.
 
______________________________________________________________
> Od: "Freakazoid182" ***@***.***>
> Komu: "domaindrivendev/Swashbuckle.AspNetCore" ***@***.***>
> Dátum: 13.04.2022 11:19
> Predmet: Re: [domaindrivendev/Swashbuckle.AspNetCore] System.MissingMethodException: Method not found: 'Microsoft.OpenApi.Models.OpenApiSchema (Issue #2369)
>
> CC: ***@***.***>
 
What fixed this for me was do a clean -> rebuild of the project.

**Comment by mjolka** [comment]
There was a [breaking change in Swashbuckle.AspNetCore.SwaggerGen 6.3.0](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/eaf3bc8ea86916a86862c990ea3e954e7e33111d#diff-c46727841a546aa50b440ab58346c751cc554e3dcc0383df7da7920523e641b6), where a new parameter was added to `ISchemaGenerator.GenerateSchema`.

In my case, the error came about due to using  Swashbuckle.AspNetCore.Annotations 6.2.3 which has a dependency on Swashbuckle.AspNetCore.SwaggerGen >= 6.2.3, but is not compatible with 6.3.0. Upgrading Swashbuckle.AspNetCore.Annotations to 6.3.0 resolved the issue.

**Comment by corfor** [comment]
downgrading to before 6.3 worked for me:
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.*" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.2.*" />
