### ISSUE TITLE
[Feature Request][OAuth] Allow set clientId and client secret separately for each auth flow

### ISSUE THREAD

**Issue by Anakael** [domaindrivendev/Swashbuckle.AspNetCore#2376]
Setup:
I have two enabled authFlows in application:
1) AuthorizationCode. with enabled clientId 'client1' and without client secret.
2) ClientCredentials. with enabled clientId 'client2' and with client secret.

Using following code sets default values for all auth flows in Ui.

```cs
app.UseSwaggerUI(c =>
  {
      c.OAuthClientId(authenticationSettings.ClientId);
      c.OAuthClientSecret(authenticationSettings.ClientSecret);
});
```

But I want to be able to set default clientId and client secret for both auth flows separatery.

**Comment by domaindrivendev** [comment]
This feature request should be submitted to the [swagger-ui](https://github.com/swagger-api/swagger-ui) repo instead of Swashbuckle
