### ISSUE TITLE
Actions that capture route values with nested type throw an error when you click to view their documentation details

### ISSUE THREAD

**Issue by jonsagara** [domaindrivendev/Swashbuckle.AspNetCore#2380]
After I upgraded from `6.2.3` to `6.3.0`, I noticed that clicking on an action to view its documentation details had started throwing errors. It appears to be related to my using properties in nested classes to capture route values. I never saw these errors in `6.2.3`.

For example, this does not throw an error:

```csharp
[HttpGet("GetNonNested/{id}")]
public async Task<IActionResult> GetNonNested(int id)
{
    await Task.CompletedTask;

    return Ok(new { message = "this is a non-nested class test" });
}
```

However, this does:

```csharp
[HttpGet("GetNested/{id}")]
public async Task<IActionResult> GetNested(NestedActionModel.Query query)
{
    await Task.CompletedTask;

    return Ok(new { message = "this is a nested class test" });
}
```

`NestedActionModel` is defined as:

```csharp
/// <summary>
/// XML documentation for top-level NestedActionModel class.
/// </summary>
public class NestedActionModel
{
    /// <summary>
    /// XML documentation for nested NestedActionModel.Query class.
    /// </summary>
    public class Query
    {
        /// <summary>
        /// Id property used in the getter.
        /// </summary>
        public int Id { get; set; }
    }
}
```

I have created a reproduction with detailed steps in this repository:

https://github.com/jonsagara/SwashbuckleAspNetCoreRepro

Thank you,

Jon

**Comment by jonsagara** [comment]
Here you go: https://github.com/jonsagara/SwashbuckleAspNetCoreRepro

**Comment by horseyhorsey** [comment]
> After I upgraded from `6.2.3` to `6.3.0`, I noticed that clicking on an action to view its documentation details had started throwing errors. It appears to be related to my using properties in nested classes to capture route values. I never saw these errors in `6.2.3`.

This also fails in `6.2.3`. I've come across this issue wanting to add to existing codebase that uses nested CQRS for api.

**Comment by horseyhorsey** [comment]
> Here you go: https://github.com/jonsagara/SwashbuckleAspNetCoreRepro

I can see now by looking at your repo that I have a different issue with nested where it won't generate at all. 

"errors":"Failed to generate Operation for action - API.Controllers.MyController.Create (API). See inner exception"

I must say when I came across this, it's different to how I would do CQRS usually, from a single class model and not using a Query or Command as a parameter, it does make the actions cleaner though.

**Comment by jonsagara** [comment]
The newly updated README documents a workaround for nested types:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2703

Replace the `+` nested type separator with `.`:

```csharp
builder.Services.AddSwaggerGen(c =>
{
    c.CustomSchemaIds(type => type.FullName.Replace("+", "."));
});
```

I tested this in [my reproduction project](https://github.com/jonsagara/SwashbuckleAspNetCoreRepro), and it worked, so I will mark this as closed.
