### ISSUE TITLE
Content-type specified in `ProducesResponseTypeAttribute` is not in generated openapi document

### ISSUE THREAD

**Issue by magiino** [domaindrivendev/Swashbuckle.AspNetCore#2386]
I'm using:
- .NET 6
- Swahbuckle.AspNetCore 6.3.0

I wonder how can I add to open api information about `content-type` which is different for each response.
- response  200 - content-type: application/zip
- response 500 - content-type: application/json

### I have prepared example:
1. See following action in controller and its open api document. `content-type` is documented with `ProducesResponseTypeAttribute`.

```
/// <summary>
/// Gets zip file.
/// </summary>
/// <response code="200">Zip file.</response>
/// <response code="500">Detailed internal server error.</response>
[ProducesResponseType(typeof(FileContentResult), StatusCodes.Status200OK, MediaTypeNames.Application.Zip)]
[ProducesResponseType(typeof(WebApiError), StatusCodes.Status500InternalServerError, MediaTypeNames.Application.Json)]
[HttpGet("zipfile")]
public ActionResult GetZipFile()
{
    try
    {
        var (zip, fileName) = service.GetZip();
        return File(zip, MediaTypeNames.Application.Zip, fileName);
    }
    catch (Exception ex)
    {
        return StatusCode(500, new WebApiError("test", "Test"));
    }
}
```

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "Test Web API",
    "description": "",
    "version": "0.1.0"
  },
  "paths": {
    "/diagnostic/zipfile": {
      "get": {
        "tags": [
          "Diagnostic"
        ],
        "summary": "Gets zip file.",
        "operationId": "GetZipFile",
        "responses": {
          "200": {
            "description": "Zip file."
          },
          "500": {
            "description": "Detailed internal server error."
          }
        }
      }
    },
```
As you can see there are missing response details for 200 and 500 code in open api document.
Is this bug, can someone explain why is this not working?

2. If I add `ProducesAttribute` the responses are documented, but both repsonses have both `content-type`s (which is wrong).

```
/// <summary>
/// Gets zip file.
/// </summary>
/// <response code="200">Zip file.</response>
/// <response code="500">Detailed internal server error.</response>
[ProducesResponseType(typeof(FileContentResult), StatusCodes.Status200OK)]
[ProducesResponseType(typeof(WebApiError), StatusCodes.Status500InternalServerError)]
[Produces(MediaTypeNames.Application.Zip, MediaTypeNames.Application.Json)]
[HttpGet("zipfile")]
public ActionResult GetZipFile()
{
    try
    {
        var (zip, fileName) = service.GetZip();
        return File(zip, MediaTypeNames.Application.Zip, fileName);
    }
    catch (Exception ex)
    {
        return StatusCode(500, new WebApiError("test", "Test"));
    }
}
```
```
{
  "openapi": "3.0.1",
  "info": {
    "title": "Test Web API",
    "description": "",
    "version": "0.1.0"
  },
  "paths": {
    "/diagnostic/zipfile": {
      "get": {
        "tags": [
          "Diagnostic"
        ],
        "summary": "Gets zip file.",
        "operationId": "GetZipFile",
        "responses": {
          "200": {
            "description": "Zip file.",
            "content": {
              "application/zip": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              }
            }
          },
          "500": {
            "description": "Detailed internal server error.",
            "content": {
              "application/zip": {
                "schema": {
                  "$ref": "#/components/schemas/WebApiError"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WebApiError"
                }
              }
            }
          }
        }
      }
    },
```

**Can someone explain how can I document `content-type` for each response separately? Did someone solve this already?**

**Comment by Silverdark** [comment]
I have the same issue.

For me, the workaround is to use `SwaggerResponse` for the status codes, where I want to provide a different content type as the default one specified on controller level.

Example:
With the following `ProducesResponseType`
```
[ProducesResponseType(typeof(FileContentResult), StatusCodes.Status200OK, "image/jpeg", "application/octet-stream")]
```
I get following result:

```json
"200": {
  "description": "Description."
},
```

When I use `SwaggeResponse` instead
```
[SwaggerResponse(200, "Description.", typeof(FileContentResult), "image/jpeg", "application/octet-stream")]
```

I get the correct generated response:
```json
"200": {
  "description": "Description.",
  "content": {
    "image/jpeg": {
      "schema": {
        "type": "string",
        "format": "binary"
      }
    },
    "application/octet-stream": {
      "schema": {
        "type": "string",
        "format": "binary"
      }
    }
  }
},
```

**Comment by magiino** [comment]
@Silverdark 

Hi, you can get the same result without using swagger annotations nuget.  
Apply this attribute to method.
```
[Produces("image/jpeg", "application/octet-stream")]
```
The disadvantage is that if method defines also 4xx, 5xx status codes the content types will apply also to these status codes, not only for 2xx status code.

You can also replace string values with constants defined in
`System.Net.MediaTypeNames`

I will for now use `SwaggerResponse` to specify different content type for 2xx and 4xx or 5xx statsu codes.

**Comment by jsuprock-netspi** [comment]
@Silverdark @magiino, regarding the following statement
> _For me, the workaround is to use SwaggerResponse for the status codes, where I want to provide a different content type as the default one specified on controller level._
I'm still getting all of the content types for each response code, even though they were separated using `SwaggerResponse`. **e.g.**
```
        /// <response code="200">Returns the exported content in CSV format.</response>
        /// <response code="400">The input provided was problematic.</response>
        /// <response code="401">Authorization failed.</response>
        /// <response code="404">The specified operation was not found.</response>
        /// <response code="429">The maximum number of requests has been exceed.</response>
        /// <response code="500">There was a problem processing the request with the server.</response>
        [HttpGet("exports/csv")]
        [SwaggerResponse(StatusCodes.Status200OK, "OK", typeof(FileStreamResult), "text/csv")]
        [SwaggerResponse(StatusCodes.Status400BadRequest, "Bad Request", typeof(ErrorResponse), "application/json")]
        [SwaggerResponse(StatusCodes.Status401Unauthorized, "Unauthorized", typeof(ErrorResponse), "application/json")]
        [SwaggerResponse(StatusCodes.Status429TooManyRequests, "Too Many Requests", typeof(ErrorResponse), "application/json")]
        [SwaggerResponse(StatusCodes.Status404NotFound, "Not Found", typeof(NotFoundResult), "application/json")]
        [SwaggerResponse(StatusCodes.Status500InternalServerError, "Internal Server Error", typeof(ErrorResponse), "application/json")]
```
yields
```
      "responses": {
          "200": {
            "description": "Returns the exported content in CSV format.",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              }
            }
          },
          "400": {
            "description": "The input provided was problematic.",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              }
            }
          },
          "401": {
            "description": "Authorization failed.",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              }
            }
          },
          "429": {
            "description": "The maximum number of requests has been exceed.",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              }
            }
          },
          "404": {
            "description": "The specified operation was not found.",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Microsoft.AspNetCore.Mvc.NotFoundResult"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Microsoft.AspNetCore.Mvc.NotFoundResult"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Microsoft.AspNetCore.Mvc.NotFoundResult"
                }
              }
            }
          },
          "500": {
            "description": "There was a problem processing the request with the server.",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/(REDACTED)"
                }
              }
            }
          }
        }
```

**Comment by m1t0z** [comment]
> @Silverdark @magiino, regarding the following statement
> 
> > _For me, the workaround is to use SwaggerResponse for the status codes, where I want to provide a different content type as the default one specified on controller level._
> 
> I'm still getting all of the content types for each response code, even though they were separated using **`SwaggerResponse`**. **e.g.**
> 
> ```
>         /// <response code="200">Returns the exported content in CSV format.</response>
>         /// <response code="400">The input provided was problematic.</response>
>         /// <response code="401">Authorization failed.</response>
>         /// <response code="404">The specified operation was not found.</response>
>         /// <response code="429">The maximum number of requests has been exceed.</response>
>         /// <response code="500">There was a problem processing the request with the server.</response>
>         [HttpGet("exports/csv")]
>         [SwaggerResponse(StatusCodes.Status200OK, "OK", typeof(FileStreamResult), "text/csv")]
>         [SwaggerResponse(StatusCodes.Status400BadRequest, "Bad Request", typeof(ErrorResponse), "application/json")]
>         [SwaggerResponse(StatusCodes.Status401Unauthorized, "Unauthorized", typeof(ErrorResponse), "application/json")]
>         [SwaggerResponse(StatusCodes.Status429TooManyRequests, "Too Many Requests", typeof(ErrorResponse), "application/json")]
>         [SwaggerResponse(StatusCodes.Status404NotFound, "Not Found", typeof(NotFoundResult), "application/json")]
>         [SwaggerResponse(StatusCodes.Status500InternalServerError, "Internal Server Error", typeof(ErrorResponse), "application/json")]
> ```
> 
> yields
> 
> ```
>       "responses": {
>           "200": {
>             "description": "Returns the exported content in CSV format.",
>             "content": {
>               "text/plain": {
>                 "schema": {
>                   "type": "string",
>                   "format": "binary"
>                 }
>               },
>               "application/json": {
>                 "schema": {
>                   "type": "string",
>                   "format": "binary"
>                 }
>               },
>               "text/json": {
>                 "schema": {
>                   "type": "string",
>                   "format": "binary"
>                 }
>               }
>             }
>           },
>           "400": {
>             "description": "The input provided was problematic.",
>             "content": {
>               "text/plain": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               },
>               "application/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               },
>               "text/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               }
>             }
>           },
>           "401": {
>             "description": "Authorization failed.",
>             "content": {
>               "text/plain": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               },
>               "application/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               },
>               "text/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               }
>             }
>           },
>           "429": {
>             "description": "The maximum number of requests has been exceed.",
>             "content": {
>               "text/plain": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               },
>               "application/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               },
>               "text/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               }
>             }
>           },
>           "404": {
>             "description": "The specified operation was not found.",
>             "content": {
>               "text/plain": {
>                 "schema": {
>                   "$ref": "#/components/schemas/Microsoft.AspNetCore.Mvc.NotFoundResult"
>                 }
>               },
>               "application/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/Microsoft.AspNetCore.Mvc.NotFoundResult"
>                 }
>               },
>               "text/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/Microsoft.AspNetCore.Mvc.NotFoundResult"
>                 }
>               }
>             }
>           },
>           "500": {
>             "description": "There was a problem processing the request with the server.",
>             "content": {
>               "text/plain": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               },
>               "application/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               },
>               "text/json": {
>                 "schema": {
>                   "$ref": "#/components/schemas/(REDACTED)"
>                 }
>               }
>             }
>           }
>         }
> ```
> 
> Do you have any idea how to fix this?

Hi, John!

I had a very similar issue and it occurred that i simply forgot to enable annotations while configuring the swagger :)

```
services.AddSwaggerGen(c =>
{
   c.EnableAnnotations();
});
```

Hope it will help you too!

**Comment by martinlingstuyl** [comment]
Using .NET 8 and Swahbuckle.AspNetCore 6.5.0

I'm running into the same issue.
- If I use `ProducesResponseTypeAttribute`, I cannot use the contentType parameter, as the the generated json file will not include the response type AND the media type.
- If I use `SwaggerResponseAttribute` (with the nuget package `Swashbuckle.AspNetCore.Annotations`) setting the contentType does not break the response type, but it still doesn't show the expected media types in the dropdown. Setting `.EnableAnnotations()` does not help on my end.
