### ISSUE TITLE
Is there a good way to have the swagger ui allow for any header to be submitted?

### ISSUE THREAD

**Issue by sjd2021** [domaindrivendev/Swashbuckle.AspNetCore#2391]
I have a large enterprise API where there are many different headers that are used for different purposes. For some common ones, I have added filters, attributes, etc. to show them on the affected endpoints. We also call into some internal applications and forward all the headers that we received in our api to the others. However, I'd like a header section where someone could specify that they want header key x to be set to header value y without my api knowing or caring what it is.

**Comment by martincostello** [comment]
Use a schema filter to extend the documentation as appropriate for your use case.
