### ISSUE TITLE
Property attribute to restrict method availability

### ISSUE THREAD

**Issue by anibal-acosta** [domaindrivendev/Swashbuckle.AspNetCore#2393]
Hello, I have a simple class for example: Person
The Person class has 3 properties "id","name" and "age"

Now I have a api for list and for create Person .
Both accepts the Person object as parameter but the "id" property apply only for method GET.

So, maybe you can add a attibute to property indicating an array of method allowd for this property, something like this.

`public class Person
{
   [ApiMethod(GET)]
   public String id {get;set;}
   public String name {get;set;}
   public Int32 age {get;set;}
}`

**Comment by martincostello** [comment]
We have no plans to support this use case - if your endpoints accept/return different models, then use different model types.
