### ISSUE TITLE
Strange endpoints with API specification being created

### ISSUE THREAD

**Issue by BrunoFreitasgit** [domaindrivendev/Swashbuckle.AspNetCore#2400]
Hi,

We've noticed the creation of some endpoints when using Swashbuckle.

Just wondering if these are from Swashbuckle code generation, or it's out of this library scope? All of these endpoints return the same as "..swagger/v1/swagger.json"

![image](https://user-images.githubusercontent.com/17299848/162935722-8a7f4b8d-5dcf-4cf8-9e4f-033d39d77402.png)

If so, is there any way to remove them?

**Comment by domaindrivendev** [comment]
I have no idea whats causing this - nothing in the code generates these explicitly and I’m not able to repro this in my own app. Could you please create a simple app (ideally starting from empty project) that repro’s this, and then post it to gihub so I can pull down and troubleshoot

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.

**Comment by martincostello** [comment]
Possible this was fixed by #2418.
