### ISSUE TITLE
Wrong data type generated in OpenApi specfication file Long

### ISSUE THREAD

**Issue by rubenramosDev** [domaindrivendev/Swashbuckle.AspNetCore#2401]
I'm developing an API with .NET Core 2.2 and with .NET 5.

This is my controller, I'm waiting to receive an Id. I'm adding :long
``[HttpGet("{id:long}")]``

But when I generate OpenApi specification file I got this:
`` 
"schema": {
              "type": "number",
              "format": "int64"
            }
``

Problem is accordingly to OpenAPI specfication this "type" : number is not recognized. It should be 

`` 
"schema": {
              "type": "integer",
              "format": "int64"
            }
``

I tried with version 4.0.1 and 6.3.0

[https://swagger.io/docs/specification/data-models/data-types/#numbers](OpenApi Data Types)

**Comment by vovakuznetsov** [comment]
Duplicated https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2387
Already solved https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2397
