### ISSUE TITLE
Add description to response status code

### ISSUE THREAD

**Issue by mu88** [domaindrivendev/Swashbuckle.AspNetCore#2402]
Hey 👋🏻

When using the `ProducesResponseTypeAttribute`, the generated OpenAPI doc does only contain a very basic description (_Success_, etc.). When describing something more elaborate, XML documentation comments have to be used, e. g. `/// <response code="200">describe something important</response>`. But the value for the `code` attribute only accepts pure numbers, not enums - I cannot write `/// <response code="HttpStatusCode.Success">describe something important</response>`. This makes refactoring harder to accomplish.

Therefore it would be great to have a property like `Description` on the `ProducesResponseTypeAttribute`. This property could be picked up by Swashbuckle/OpenAPI.

The result would look like this: `[ProducesResponseType(HttpStatusCode.Ok, "describe something important")]`

I've already placed this question in the corresponding Microsoft repo ([see here](https://github.com/dotnet/aspnetcore/issues/40836)), but they recommended to file an issue here instead.

**Comment by akamud** [comment]
I would like to have this too. In our project we have more than one reason to return `422` for example. A description could be useful.

**Comment by mu88** [comment]
If you could give me a little guidance of how/where to start, I'd be happy to provide a PR

**Comment by martincostello** [comment]
The [`[SwaggerResponse]`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Annotations/SwaggerResponseAttribute.cs) attribute already provides this functionality.

```csharp
using Microsoft.AspNetCore.Http;

[SwaggerResponse(StatusCodes.Status200OK, "describe something important")]
public IActionResult Get()
{
    return Json("hellow);
}
```
