### ISSUE TITLE
IncludeXmlComments changes the sort order of operations

### ISSUE THREAD

**Issue by overdunne** [domaindrivendev/Swashbuckle.AspNetCore#2403]
Adding the IncludeXmlComments directive changes the sort order of operations.

Comment out this line sorts as expected:

        options.IncludeXmlComments(fi.FullName, true);

The Json file is in the expected order but the UI is not.

Json:

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "WebApi",
    "version": "1.0"
  },
  "paths": {
    "/Message": {
      "get": {
        "tags": [
          "Message"
        ],
        "operationId": "SayHello",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/WeatherForecast": {
      "get": {
        "tags": [
          "WeatherForecast"
        ],
        "operationId": "GetWeatherForecast",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "summary": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  },
  "tags": [
    {
      "name": "WeatherForecast",
      "description": "Gives a weather forecast."
    }
  ]
}
```

Swagger UI:

![image](https://user-images.githubusercontent.com/55284204/163809252-048056f8-6866-4b6e-b98c-769b1593224d.png)

**Comment by overdunne** [comment]
[WebApi.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/8505689/WebApi.zip)

**Comment by martincostello** [comment]
If this was changed, how would you want it to be ordered? How is the ordering you think is correct currently defined?

If the order happens to be the order of declaration in the code, as far as I'm aware, the order members are found by reflection isn't deterministic, so if that's the case and you consider it "correct", then that would be a happy accident rather than by design.

If the order without the documentation is defined by us in code, then it makes sense to have the XML maintain the order (if possible).

**Comment by overdunne** [comment]
I would think lexicographical ordering by route, regardless of description.

**Comment by martincostello** [comment]
Having re-read the description, am I correct that Swashbuckle is rendering the JSON in the order you want, but that the UI is not rendering them in that same order?

If that's the case, then that's going to be an issue with swagger-ui itself, which we just repackage. Either you would need to influence the ordering by configuring it to do what you want in the options passed to the JavaScript (if that's possible), or raise an issue with them to add support for that. If they do support that, but we're on an old version missing that feature, then there's a PR open to update our version to the latest version of swagger-ui.

**Comment by overdunne** [comment]
Yes the json is in the expected order, will look to underlying swagger-ui.
