### ISSUE TITLE
[BUG] 在Swashbuckle.AspNetCore.SwaggerGen.dll 6.3.0 的组件中存在空指针引用错误

### ISSUE THREAD

**Issue by NoEndToLearn** [domaindrivendev/Swashbuckle.AspNetCore#2405]
一、错误详情
{
	"StackTrace": "   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Nebula.AspnetCore.SpacerModule.InvokeAsync(HttpContext httpContext)",
	"Message": "Failed to generate Operation for action - Uranus.TxApp.Controllers.alert.InterceptorController.Interceptor (Uranus.TxApp). See inner exception",
	"Data": {},
	"InnerException": {
		"StackTrace": "   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(ModelMetadata modelMetadata, SchemaRepository schemaRespository)\r\n   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(ApiDescription apiDescription, SchemaRepository schemaRepository, String statusCode, ApiResponseType apiResponseType)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, SchemaRepository schemaRepository)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)",
		"Message": "Failed to generate schema for type - Uranus.Data.TxApp.DTO.AlertDetail.InterceptorDto. See inner exception",
		"Data": {},
		"InnerException": {
			"ClassName": "System.NullReferenceException",
			"Message": "Object reference not set to an instance of an object.",
			"Data": null,
			"InnerException": null,
			"HelpURL": null,
			"StackTraceString": "   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForMember(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, DataProperty dataProperty)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateObjectSchema(DataContract dataContract, SchemaRepository schemaRepository)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type modelType, SchemaRepository schemaRepository)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)",
			"RemoteStackTraceString": null,
			"RemoteStackIndex": 0,
			"ExceptionMethod": null,
			"HResult": -2147467261,
			"Source": "Swashbuckle.AspNetCore.SwaggerGen",
			"WatsonBuckets": null
		},
		"Source": "Swashbuckle.AspNetCore.SwaggerGen",
		"HResult": -2146233088
	},
	"Source": "Swashbuckle.AspNetCore.SwaggerGen",
	"HResult": -2146233088
}

二、运行环境
1、 Windows 11 专业版 、.net 5.0 、Microsoft Visual Studio Enterprise 2019 16.11.11
2、Swagger组件Microsoft.Extensions.ApiDescription.Server 6.3.0 、Swashbuckle.AspNetCore.Swagger 6.3.0、Swashbuckle.AspNetCore.SwaggerGen 6.3.0、Swashbuckle.AspNetCore.SwaggerUI 6.1.5、Swashbuckle.AspNetCore.Newtonsoft 6.3.0

三、重现该问题方法
1、使用Visual Studio Enterprise 2019 通过默认模板创建ASP.NET Core WEB API项目
2、将Swashbuckle.AspNetCore 升级到最新稳定版本 6.3.0
3、添加 对组件Swashbuckle.AspNetCore.Newtonsoft 6.3.0 的引用
4、以下附件为问题重现的demo
[WebApiTest.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/8509245/WebApiTest.zip)

四、具体错误位置
![20220419102034](https://user-images.githubusercontent.com/23007136/163907267-8aa9a23b-2bdc-4784-a0be-356cd16fdd17.png)

**Comment by vovakuznetsov** [comment]
Duplicate #https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2368
MR #https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2373
