### ISSUE TITLE
myget 6.0.0-preview-9 disappeared

### ISSUE THREAD

**Issue by moander** [domaindrivendev/Swashbuckle.AspNetCore#241]
> warning NU1007: Dependency specified was Swashbuckle.SwaggerGen >= 6.0.0-preview-9 but ended up with Swashbuckle.SwaggerGen 6.0.0-rc1-final

The repo seems empty so NuGet chooses rc1-final instead :/

```
nuget list -source https://www.myget.org/F/domaindrivendev/api/v3/index.json
No packages found.
```

**Comment by parys** [comment]
I think you can use version 6.0.0-preview-0044 from the same source. VS offers you(on warning) wrong version. Nuget manager offers now versions from 6.0.0-preview-0021 to 6.0.0-preview-0044.

**Comment by xperiandri** [comment]
@domaindrivendev, could you add migration steps for those who used `Swasbuckle 6.0.0-beta902` or earlier from feed `https://www.myget.org/F/swashbuckle/api/v3/index.json`

Because simple switch of package to `Swashbucke.AspNetCore 1.0.0-rc1` does not work...

**Comment by domaindrivendev** [comment]
@xperiandri - although we're getting real close to a stable release (now moved from beta to release candidate 1), this project is still in a pre-release world and that's going to involve breaking changes. I don't have the time to document migration steps with every beta/pre-release version. The rc1 docs took a lot of time to put together and include enough detail, IMO, for early adopters to figure out how to migrate.

However, being an open source project - if you've got spare time to put together some migration steps, that would be a well received contribution.
