### ISSUE TITLE
Override [FromBody] request type

### ISSUE THREAD

**Issue by maganuk** [domaindrivendev/Swashbuckle.AspNetCore#2410]
I have a model list this:

    public class TestClient
    {
       public Optional<string> TestProp { get; set; }
    }

my json converter converts the value from `string` to `Optional<string>`

For the swagger request I want the request to body to take in a `string` instead of an `Optional<string>`

I can't figure out how to use the ISchemaFilter to do this. The only other way I can think of doing this is to have a separate class representing the swagger request schema. I have defined a class as such:

    public class TestClientSwagger
    {
      /// <summary>
      /// This is a test
      /// </summary>
      public string TestProp { get; set; }
    }

My controller method is: 

    public async Task<IActionResult> PatchClient([FromBody] TestClient client)
    {
      return Ok();
    }

How can I override the request schema to pick up the `TestClientSwagger` schema?

I have tried the following which does not seem to work:

` [Consumes(typeof(TestClientSwagger), MediaTypeNames.Application.Json)]`

Thanks

**Comment by thewrath** [comment]
Personally, I haven't found an "Out of the box" feature to do this.
However, you can use a custom `IOperationFilter` :
```
public class SwaggerRequestTypeOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        var attribute = context.MethodInfo.GetCustomAttribute<SwaggerRequestTypeAttribute>();

        if (attribute is null) return;
        
        // Maybe you don't need this line 
        if (operation.RequestBody.Content.TryGetValue(MediaTypeNames.Application.Json, out var jsonRequest))
        {
            jsonRequest.Schema = context.SchemaGenerator.GenerateSchema(attribute.RequestType, context.SchemaRepository);
        }
    }
}
```

In my case i use a custom attribute `SwaggerRequestType` to know the type of the request, you can use `Consumes` attribute if you want; in the controller : 

```
    [HttpPost]
    [SwaggerRequestType(requestType: typeof(Report))]
    public IActionResult PostReport([JsonSchema("report")] JsonDocument document)
```

**Comment by martincostello** [comment]
A filter is the answer here.
