### ISSUE TITLE
EmailAttribute  for array in Form

### ISSUE THREAD

**Issue by sdecri** [domaindrivendev/Swashbuckle.AspNetCore#2411]
In my aspnet core web api application I have an API with a Form input. In this form I want to include a field that is an array of string where each element must be an email. To validate a form field as an email I can use the [EmailAddress](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.emailaddressattribute?view=net-6.0) Attribute. So I tried to use it on my string[] property. Unfortunately it seems that this attribute is not handled correctly with array.
If I try to run the swagger-ui of my project, I can't specify an array in the "Try it out" section.
The API is like the following:
```
[HttpPost("send-email")]
  public IActionResult SendEmailAsync([FromForm] SendEmailRequest req)
  {
  
    _logger.LogInformation(req.ToJson());
    return Ok();
  }
```
And the model is defined as follows:
```
  public class SendEmailRequest
  {
    protected const int MAX_RECIPIENTS = 10000;

    [EmailAddress]
    public string from { get; set; }

    [Required]
    [MaxLength(MAX_RECIPIENTS)]
    [EmailAddress]
    public string[] recipients { get; set; }

  }
```
In the model there are two properties:
* from: this is a string that must be validated as an email,
* recipients: this is a list of string where each element must be validated as an email.
When I run the swagger-ui, the "recipients" field is not recognized as an array in the "Try it out" section:
![image](https://user-images.githubusercontent.com/2937576/166928332-73bf5755-b2c2-40f6-a885-931b33ce269c.png)

The "recipients" property in the generated swagger json is the following:
```
"recipients": {
  "maxItems": 10000,
  "type": "array",
  "items": {
    "type": "string"
  },
  "format": "email"
},
```

I suspect that the "format" property should be included in the "items" section in the following way:
```
"recipients": {
  "maxItems": 10000,
  "type": "array",
  "items": {
    "type": "string",
    "format": "email"
  },
},
```
I tried this version of the json in the online [swagger editor](https://editor.swagger.io/) and the result is correct:
![image](https://user-images.githubusercontent.com/2937576/166930128-1893a87d-ffa4-43ab-8c83-0f02c6643189.png)

In this way is possible to add elements of the "recipients" array.

The source code of this example is available at: https://github.com/sdecri/SwashbucklerEmailAttribute 

The varsion related to the current issue is: 6.2.3.

**Comment by niteshsinghal85** [comment]
Hi @sdecri,

It worked if you remove the EmailAddress attribute from recipients array.

![image](https://user-images.githubusercontent.com/40641126/173012364-a762ee05-9de4-4ca1-b04d-134a65da4882.png)

swagger ui after changes.

![image](https://user-images.githubusercontent.com/40641126/173013449-e60c6db4-5479-454e-b4d5-00b4a51966c0.png)


you can verify recipients list in controller.

![image](https://user-images.githubusercontent.com/40641126/173013289-460000ac-21db-4dd0-95ee-2c706abbaf0d.png)

I think EmailAddress attribute accepts only string and you need to implement custom attribute validator to validate the recipients list.

**Comment by domaindrivendev** [comment]
As pointed out by @niteshsinghal85, the EmailAddressAttribute is not meant to be used with a strong array property and by design Swashbuckle only supports correct use of data annotation attributes.
