### ISSUE TITLE
Cannot have multiple response types for same status code

### ISSUE THREAD

**Issue by vanillajonathan** [domaindrivendev/Swashbuckle.AspNetCore#2413]
It is not possible to have the multiple response types for the same status code. The last declared `ProducesResponseType` gets used.

```cs
[HttpGet]
[ProducesResponseType(typeof(Foo), 200)]
[ProducesResponseType(typeof(Bar), 200)]
public IActionResult Get(bool foo)
{
    if (foo)
    {
        return Ok(new Foo());
    }

    return Ok(new Bar());
}
```

swagger.json
```json
"/api/Example": {
  "get": {
    // ...
    "responses": {
      "200": {
        "description": "Success",
        "content": {
          "text/plain": {
            "schema": {
              "$ref": "#/components/schemas/Bar"
            }
          },
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Bar"
            }
          },
          "text/json": {
            "schema": {
              "$ref": "#/components/schemas/Bar"
            }
          }
        }
      }
    }
  }
}
```

**Comment by domaindrivendev** [comment]
This is not a bug it’s a limitation of the open api specification, which SB is built on. Specifically you can only have one response object per response code. See https://spec.openapis.org/oas/v3.1.0#responses-object

**Comment by vanillajonathan** [comment]
Thank you for the clarification.

**Comment by Kilowhisky** [comment]
Digging up this old issue. This has actually been added to the spec using the `oneOf` operator. 

https://spec.openapis.org/oas/v3.1.0#discriminator-object

Because of this, i believe this issue should be reopened.

**Comment by vanillajonathan** [comment]
@domaindrivendev Re-open this issue?

**Comment by nithinbandaru1** [comment]
is this not being re-opened?
