### ISSUE TITLE
Filter endpoints for admin and users

### ISSUE THREAD

**Issue by anahit-aleksanyan** [domaindrivendev/Swashbuckle.AspNetCore#2417]
Hello.

How can I add a filter to swagger that will filter my endpoints based on roles.

For example, if I only want to see the endpoints for the **admin**. Either endpoint for **users**, or for **both** of them.

We only have this option for versions, I need something similar for roles. (**see Attachment**)

Thank you.
![Screenshot (562)_LI](https://user-images.githubusercontent.com/97456998/168855139-1cd39541-73bf-46c0-aea9-0eaf8e5c01da.jpg)

**Comment by niteshsinghal85** [comment]
Hi, 
checkout my blog on medium which tries to solve the same problem.
hope it would be helpful.
https://medium.com/@niteshsinghal85/api-filtering-on-swaggerui-by-role-in-net-core-6006b9bb98c4
