### ISSUE TITLE
swagger.json not generated with respect to base route

### ISSUE THREAD

**Issue by sparksterz** [domaindrivendev/Swashbuckle.AspNetCore#242]
I'm trying to deploy a small API in a scenario where we access resources via a reverse proxy with essentially a virtual path reference to the deployed service and I'm having issues. 

I'm currently using 6.0.0-preview-0035 on a .Net Core 1.1 MVC project with the following configuration:
```
app.UseSwaggerUi(c =>
{
         c.BaseRoute = env.ApplicationName + "/help";
});
```
This allows for the swagger index to point to `/ApplicationName/help/index.html` and that loads the page and content fine with the exception of it missing a swagger.json file, but that's expected I didn't give it a location.

I then try to add the following inside my lambda block:
```
c.SwaggerEndpoint("/" + c.BaseRoute + "/swagger/v1/swagger.json", "V1 Docs");
```
This generates an error message stating:
> Can't read swagger JSON from http://localhost:50212/ApplicationName/help/swagger/v1/swagger.json

Which confuses me a bit as all the other swagger resources for css, js, pngs all load using `~/ApplicationName/help` as the base URI. I then try to do some digging and found if I try to hit `~/swagger/v1/swagger.json` I get a 500 error with the following trace:
```
Swashbuckle.Swagger.Model.UnknownSwaggerDocument: Unknown Swagger document - v1
   at Swashbuckle.SwaggerGen.Generator.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.Swagger.Application.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 13.6516ms 500
```
Any other request I formed in order to try and access swagger.json returned me a 404 with the exception of that request `http://localhost:50212/swagger/v1/swagger.json` which leads me to believe it's failing to be generated properly.

I noticed this pull request which might be aimed at this specific problem dating from quite a while back: https://github.com/domaindrivendev/Ahoy/pull/106 Though I'm not positive if I'm having the same issue. Is there something I should try? Or a specific workflow I should do instead in this case?

**Comment by sparksterz** [comment]
This actually had to do with my routing...if I followed the virtual directory sample here:
https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/VirtualDirectory/Startup.cs

Things would not work due to the app.map call I assume not properly routing the swagger requests. The regular calls in my controllers would work fine however. The solution I ended up requiring can be seen here:

http://www.strathweb.com/2016/06/global-route-prefix-with-asp-net-core-mvc-revisited/

It might be worth updating the sample app to use this logic, or there may be some simpler path to solving the problem.

**Comment by chadwackerman** [comment]
One of them is a route the other is a path. Something like:

```
app.UseSwagger("docs/{documentName}/swagger.json");
app.UseSwaggerUi(c => {
        c.SwaggerEndpoint("/docs/v1/swagger.json", "V1 Documentation");
}
```

**Comment by domaindrivendev** [comment]
As pointed out by @chadwackerman, you provide _UseSwagger_ with a "route" and _SwaggerEndpoint_ with a URL (can be fully qualified or relative to the current host). The latter is a URL because it's really client-side configuration, i.e. the remote Swagger URL that powers the swagger-ui, whereas the notion of a "route" is a purely server-side concept.
