### ISSUE TITLE
UI XSS injection to takeover accounts

### ISSUE THREAD

**Issue by mmalyska** [domaindrivendev/Swashbuckle.AspNetCore#2420]
We need to update `swagger-ui` to version `> 4.13` to mitigate this attack.
It is quite severe in my opinion.
More information about this can be found in https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers/

**Comment by IkramShah65** [comment]
Hi @mmalyska 

What's the solution for this issue?

I upgraded Swashbuckle.AspNetCore to latest Version=6.4.0 but still facing the issue

**Comment by badhriongit** [comment]
hey im on Swashbuckle.AspNetCore Version=6.5.0 , in what version is the xss found in https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers/ , fixed. Thanks
