### ISSUE TITLE
Hacking Swagger-UI - from XSS to account takeovers

### ISSUE THREAD

**Issue by shuta85** [domaindrivendev/Swashbuckle.AspNetCore#2424]
Hi 
Do you have plan to upgrade swagger-UI to fix the XSS vulnerability?

[https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers/](https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers/)

Thanks

**Comment by gtd92** [comment]
> Hi @shuta85
> 
> What's the solution for this issue?
> 
> Things I tried
> 
> 1. I upgraded Swashbuckle.AspNetCore to latest Version=6.4.0
> 2. I removed Swashbuckle.AspNetCore and installed latest versions of Swashbuckle.AspNetCore.Swagger , Swashbuckle.AspNetCore.SwaggerGen and Swashbuckle.AspNetCore.SwaggerUI
> 
> Still facing the issue on localhost and using it in .NET core 3.1
> 
> Steps to reproduce: Open link https://{yourwebsitelink}/swagger/index.html?configUrl=https://raw.githubusercontent.com/harshbanshpal/testing/main/test.json

I'm having the same issue. Can anything be done from our side?

**Comment by hbahrini** [comment]
Hi,

Any plan to fix this issue ?
