### ISSUE TITLE
Why can't he support apicontroller but controllerbase

### ISSUE THREAD

**Issue by weiyan2012** [domaindrivendev/Swashbuckle.AspNetCore#2425]
Why can't he support apicontroller but controllerbase
![image](https://user-images.githubusercontent.com/1393860/170477948-1ed44685-09e9-44bb-b945-05a2027f2d8f.png)

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
