### ISSUE TITLE
Unwanted $count query always appears in Swagger doc

### ISSUE THREAD

**Issue by kjkrum** [domaindrivendev/Swashbuckle.AspNetCore#2431]
I created a new ASP.NET Core Web API project using Microsoft.AspNetCore.OData 8.0.10 (the latest) and Swashbuckle.AspNetCore 6.2.3 (the template default) and 6.3.1 (the latest). My intended API works, but the Swagger doc contains an unintended `$count` query.

I created a [minimal repro](https://github.com/kjkrum/ODataTest). Note my [failed attempts](https://github.com/kjkrum/ODataTest/commit/1848fde8f4d97037684fd2e76576c9d752a3ed31) to suppress the query.

Am I missing something?

**Comment by kjkrum** [comment]
![UsersCount](https://user-images.githubusercontent.com/1007080/171502586-abad8aa8-2a49-4a02-a5d9-019f45bc073b.png)

**Comment by kjkrum** [comment]
I used the technique of [cloning Swashbuckle.AspNetCore locally](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1166#issuecomment-497933444) and inspecting the injected `IApiDescriptionGroupCollectionProvider`. The unexpected $count path exists there, so the problem is either upstream in Microsoft.AspNetCore.OData or downstream in my project.

**Comment by veraosipchuk** [comment]
hi @kjkrum could you please share how you solved this problem?

**Comment by kjkrum** [comment]
@veraosipchuk I didn't. I think it's a bug that Swashbuckle generates the `$count` path if the entity isn't countable. But I abandoned OData entirely because [property validation is horrendously broken](https://github.com/OData/AspNetCoreOData/issues/619#issuecomment-1156670183).

**Comment by mguinness** [comment]
The [EnableDollarCountRouting](https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs#L41-L44) option is now available to prevent it from showing.
