### ISSUE TITLE
Whenever my program runs, swigger automatically refreshes the page. Then the api parameters are lost, which is very inconvenient. How to make it not refresh automatically?

### ISSUE THREAD

**Issue by 22140505** [domaindrivendev/Swashbuckle.AspNetCore#2435]
Whenever my program runs, swigger automatically refreshes the page. Then the api parameters are lost, which is very inconvenient. How to make it not refresh automatically?

**Comment by martincostello** [comment]
Disable hot reload in Visual Studio.
