### ISSUE TITLE
MessyCode generate in swagger.json

### ISSUE THREAD

**Issue by itachijames** [domaindrivendev/Swashbuckle.AspNetCore#2445]
I find my app working on linux, the generate file `swagger.json` doesn't generate "so well". 
The code is simple, which i use some chinese character to describe the `OpanApiInfo`
```
builder.Services.AddSwaggerGen(option =>
{
    option.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo
    {
        Version = "v1",
        Title = "配置工具API",
        Description = "AI人员出清配置工具API文档"
    });
    option.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml")
});
```
swagger.json like this (only take the first part) :
```
{
  "openapi": "3.0.1",
  "info": {
    "title": "���ù���API",
    "description": "AI��Ա�������ù���API�ĵ�",
    "version": "v1"
  },
}
```
Thr messycode trouble me for quite a while, it cause Swagger-UI webpage render the same error.
And i fond the same code work well in Windows 10, messycode doesn't show up.  
Is't OS miss some Font? or some Encoding have to set?

Env:
```
Ubuntu 20.04.4 LTS
.Net 6
Swashbuckle.AspNetCore Ver6.3.1
```

**Comment by schurlinga** [comment]
I have the same issue with umlauts, generating the swagger.json within an azure pipeline hosted linux agent (Ubuntu 22.04.3 LTS, .NET 6.0)

Where you able to solve this issue?
