### ISSUE TITLE
Question - v6.0.0 NuGet release date

### ISSUE THREAD

**Issue by poveilleux** [domaindrivendev/Swashbuckle.AspNetCore#245]
Hi,

I was looking for a newer version of the NuGet package for Swashbuckle (I have 6.0.0-beta902) but I didn't find it. I saw in your milestones that it was supposed to be released on November 23. When are you planning to release the 6.0.0 NuGet package?

Thank you.

**Comment by Gillardo** [comment]
Any news on latest release?

**Comment by chadwackerman** [comment]
There's a package on myget.org. Add it to your feeds. https://www.myget.org/gallery/domaindrivendev

I'm running the latest build that way; works fine.

**Comment by poveilleux** [comment]
@chadwackerman I know about that preview release, but I want to run the 6.0.0 release on NuGet main feed.

**Comment by chadwackerman** [comment]
And people in Hell want root beer slush puppies. It's not released yet. Click the plus sign, paste the url, you're done.

**Comment by chadwackerman** [comment]
Don't we all. Until that's released a newer build is available at myget where you can get a head start dealing with the latest round of pointlessly renamed method calls.

**Comment by domaindrivendev** [comment]
Hang tight all - I'm extremely close

**Comment by poveilleux** [comment]
@chadwackerman I started with the preview for one of our microservices but I don't want to do them all over again when the "real" release is out, hence asking for a timetable. @domaindrivendev: I'm glad to read that!

**Comment by danzel** [comment]
Seems 1.0.0-rc1 was released a day or two ago.

**Comment by domaindrivendev** [comment]
NOTE: Renamed from Swashbuckle.6.0.0-* to Swashbuckle.AspNetCore.1.0.0-*. Just released 1.0.0-rc1 and aiming to release the full stable version end of Jan.
