### ISSUE TITLE
Swashbuckle.AspNetCore  .Net 6 not available

### ISSUE THREAD

**Issue by EvegeniyNekrasov** [domaindrivendev/Swashbuckle.AspNetCore#2458]
Hello! I'am new in dotnet. I have a problem with the package. 
It's show a Swashbuckle.AspNetCore Not available in the Manage NuGet Packages and i get an NU1101 error.

Any help please?
Thank you

**Comment by DanielThyselius** [comment]
I don't think the problem lies in this package but rather in the IDE or something with your setup,
Try installing it from the CLI by running this command in the project root folder.
`dotnet add package Swashbuckle.AspNetCore.Cli`
