### ISSUE TITLE
Getting Alert: CST-E has determined that this component is not generally safe to use. in Swashbuckle.AspNetCore 5.5.0.

### ISSUE THREAD

**Issue by shrutigithub** [domaindrivendev/Swashbuckle.AspNetCore#2462]
Can you please let me know in which version is the vulnerability "CST-E has determined that this component is not generally safe to use." resolved? 
We are currently using Swashbuckle.AspNetCore 5.5.0.

**Comment by martincostello** [comment]
If you still get this error with the latest version, please open a new issue and tell us why the tool thinks this.
