### ISSUE TITLE
Missing #/definitions/HttpError in Swashbuckle implementation

### ISSUE THREAD

**Issue by sourabhagrawal23** [domaindrivendev/Swashbuckle.AspNetCore#2466]
Hi,
I am working on a code base that is generating a swagger document correctly.

All of the endpoints have HTTP responses which is referencing #/definitions/HttpError. However, HTTPError is missing from my swagger JSON documentation in the "definitions" section.

**Expected**: HTTPError should be present in the "definitions" element of the JSON doc.

**Actual**: HTTPError is missing in the "definitions" element of the JSON doc.

Example:

"/User": {
"get": {
"tags": [
"user"
],
"summary": "Get the user information",
"description": "User",
"operationId": "User_Get_GET",
"consumes": [],
"produces": [
"application/json",
"text/json",
"text/html",
"application/octet-stream",
"application/xml",
"text/xml"
],
"responses": {
"200": {
"description": "Successfully returns the system information",
"schema": {
"$ref": "#/definitions/SystemInfoDto"
}
},
"403": {
"description": "Unauthorized",
"schema": {
"$ref": "#/definitions/HttpError"
}
},
"404": {
"description": "Not Found",
"schema": {
"$ref": "#/definitions/HttpError"
}
},
"409": {
"description": "Another user has modified this record, please re-retrieve and try again",
"schema": {
"$ref": "#/definitions/HttpError"
}
}
}
}
}

**Comment by zhuhuanzi** [comment]
me too

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
