### ISSUE TITLE
jQuery.fx.off = true;

### ISSUE THREAD

**Issue by chadwackerman** [domaindrivendev/Swashbuckle.AspNetCore#247]
SwaggerUI feels like Adobe Flash demos circa 2003.

**Comment by domaindrivendev** [comment]
@chadwackerman - can you elaborate here a little?

It's also worth noting that Swashbuckle is a server-side Swagger generator that bundles in an embedded version of the awesome (swagger-ui)[https://github.com/swagger-api/swagger-ui] tool for convenience. If you have an issue with the UI, you'd be better off logging it over at that repo.
