### ISSUE TITLE
Cannot offer both AuthorizationCode PKCE and Client Credentials

### ISSUE THREAD

**Issue by sprudel79** [domaindrivendev/Swashbuckle.AspNetCore#2470]
Hi everyone,
I am using latest Swashbuckle version 6.4.0. For my service which is using IdentityServer as IDP I would like to offer both authorization code with PKCE based authentication as well as client credentials in Swagger.
I should say that both auth options work perfectly when I enable them individually.
As I am aware to make PKCE working I need to call this here:

``` csharp
app.UseSwaggerUI(
                options =>
                {
                    options.OAuthUsePkce();                                                                  
                });
```

Now I would like to offer client credentials authorization as well, but when the call to OAuthUsePkce is there, the "client_secret" field which is required for client credentials disappears:

![image](https://user-images.githubusercontent.com/10754010/181296271-c4787771-8779-4a04-98d5-705fd3c64aac.png)

How can I bring back the client_secret field without having to disable PKCE?

Thanks in advance.

**Comment by tiagofe** [comment]
We have exactly the same problem. 😢 Due to that, we can´t update any more to the latest versions. Please... is it possible to correct this?

**Comment by shamnani-kamlesh** [comment]
Same issue - seems its fixed in this PR - https://github.com/swagger-api/swagger-ui/pull/8146

**Comment by Pilchard123** [comment]
Better still - it's also fixed for the auth code flow in swagger-api/swagger-ui#8268

**Comment by domaindrivendev** [comment]
Happy to upgrade the related swagger-ui bits once the above changes have been released there. Feel free to ping me with a reminder when that happens

**Comment by Pilchard123** [comment]
@domaindrivendev It appears to already have been released in [4.15.3](https://github.com/swagger-api/swagger-ui/releases/tag/v4.15.3).

**Comment by sprudel79** [comment]
Thanks everyone involved, I will check the changes soon and will comment here the status.

**Comment by sprudel79** [comment]
Hi everyone, the latest Swashbuckle.AspNetCore version relies on swagger-ui-dist 4.14.0 which of course doesn't include the fix from 4.15.3. 
Is it possible to create a new release with the updated swagger-ui-dist version?
Thank you.

**Comment by markwalsh-liverpool** [comment]
We need a new distribution as @sprudel79 mentions.

**Comment by sprudel79** [comment]
There was just a recent update a few days back. I have upgraded my local setup and have tested the issue.
First of all the latest Swashbuckle.AspNetCore version (6.5.0) uses now swagger-ui-dist 4.15.5.
When I run my updated setup locally I can see finally the client_secret field for the clientCredentials flow.
Thanks for fixing the issue!

**Comment by aherrick** [comment]
@sprudel79 it appears i have the opposite problem? I am using PKCE auth and do not want the client_secret field shown. after upgrading to 6.5.0 it now shows. is there a way to force it to be hidden?

**Comment by sprudel79** [comment]
Here we go @markwalsh-liverpool, I can share a code snippet (which should show the idea) of the Swagger usage with both PKCE and ClientCredentials: 

```
public virtual void ConfigureServices(IServiceCollection services)
{
    ...
    _ = services.AddSwaggerGen(options =>
    {
        ...
      
        var flows = new OpenApiOAuthFlows();

        flows.AuthorizationCode = new OpenApiOAuthFlow
        {
            AuthorizationUrl = new Uri(baseUrlIdentityServer + "/connect/authorize"),
            TokenUrl = new Uri(baseUrlIdentityServer + "/connect/token"),
            Scopes = new Dictionary<string, string>
            {
                { "MyAPI", string.Empty },
                { "openid", string.Empty },
                { "email", string.Empty },
                { "profile",string.Empty}
            }
        };

        flows.ClientCredentials = new OpenApiOAuthFlow
        {
            TokenUrl = new Uri(baseUrlIdentityServer + "/connect/token"),
            Scopes = new Dictionary<string, string>
            {
                { "MyAPI", string.Empty }
            }
        };

        options.AddSecurityDefinition("IdentityServer", new OpenApiSecurityScheme
        {
            Reference = new OpenApiReference
            {
                Type = ReferenceType.SecurityScheme,
                Id = "IdentityServer"
            },
            In = ParameterLocation.Header,
            Name = "Bearer",
            Scheme = "oauth2",
            Type = SecuritySchemeType.OAuth2,
            Flows = flows
        });

        options.AddSecurityRequirement(new OpenApiSecurityRequirement
        {
            {
                new OpenApiSecurityScheme
                {
                    Reference=new OpenApiReference{Type=ReferenceType.SecurityScheme,Id="IdentityServer"},
                    Scheme="oauth2",
                    Name="Bearer",
                    In=ParameterLocation.Header
                },
                new List<string>{"openid","email","profile","MyAPI"}
            }
        });
        
        ...
    });

    ...
}

public virtual void Configure(IApplicationBuilder app, IHostApplicationLifetime applicationLifetime)
{
    ...
    _ = app.UseSwagger(o =>
    {
    });

    if (ServiceOptions.Swagger.UseSwaggerUI)
    {
        var apiVersionDescriptionProvider = app.ApplicationServices.GetRequiredService<IApiVersionDescriptionProvider>();
        
        _ = app.UseSwaggerUI(options =>
        {
            options.OAuthUsePkce();

            foreach (var description in apiVersionDescriptionProvider.ApiVersionDescriptions)
            {
                options.SwaggerEndpoint($"{baseUrlMyAPI}/swagger/{description.GroupName}/swagger.json", description.GroupName.ToUpperInvariant());
            }
        });
    }
    ...
}
```

**Comment by sq735** [comment]
> There was just a recent update a few days back. I have upgraded my local setup and have tested the issue. First of all the latest Swashbuckle.AspNetCore version (6.5.0) uses now swagger-ui-dist 4.15.5. When I run my updated setup locally I can see finally the client_secret field for the clientCredentials flow. Thanks for fixing the issue!

Updated the version to "6.5.0" the problem is present. Any help please.
