### ISSUE TITLE
Swagger JSON and UI generated without content type when Results.Ok is used

### ISSUE THREAD

**Issue by udayakumarlm** [domaindrivendev/Swashbuckle.AspNetCore#2481]
When you define API end points like following both are same in functionality,

```
        app.MapPost("/todoitems", async (FileModel file) =>
        {
            **return file;**
        });
        app.MapPost("/todoitemsnew", async (FileModel file) =>
        {
            **return Results.Ok(file);**
        });
```
Both APIs should generate same UI and JSON output, but the point with Results.Ok is generated as no return content end point. 

When a return object is used then the generated UI is like this (when  **return file;** used) 
![image](https://user-images.githubusercontent.com/32355925/185384265-1c455891-892d-462e-8028-b47b4f3b83c8.png)

When a Results.Ok is used the generated UI is like this (when  return **Results.Ok(file);** used) 
![image](https://user-images.githubusercontent.com/32355925/185384578-d16693e1-83fa-458d-8545-a6deb19e5ad0.png)

JSON generated is also missing content type.

When a return object is used then the JSON is like this (when  **return file;** used) 
'"responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FileModel"
                }
              }
            }
          } '

When a Results.Ok is used the JSON is like this (when  return **Results.Ok(file);** used) 

`"responses": {
          "200": {
            "description": "Success"
          }
        }`

**Is it by design ? Not found information on the same in the documentation.**

**Comment by niteshsinghal85** [comment]
Return type for both API is different, that's why the generated response is different.
for Result.Ok(file), you need to tell what kind of response you are expecting

**Comment by udayakumarlm** [comment]
Expected output should have been same for both as both represent the same thing. Both return 200 OK with file as body of the response. 

I found a way to solve my problem by using Produces() method to document the output like following 

```
   app.MapPost("/todoitemsnew", async (FileModel file) =>
        {
            return Results.Ok(file);
        }).Produces<FileModel>(StatusCodes.Status200OK) ;
```

Not sure if this is a bug or actual behavior.

**Comment by martincostello** [comment]
When `Results.Ok()` is used it returns and `IResult`, so all type information is lost meaning there's no way for us to know what you return.

The solutions to this are to use `[Produces]` or use the `TypedResults.Ok<T>()` method added in .NET 7. Both of these approaches allow Swashbuckle to infer the response type to add to the schema.
