### ISSUE TITLE
FromQuery.Name is not respected for complex objects

### ISSUE THREAD

**Issue by IvMisticos** [domaindrivendev/Swashbuckle.AspNetCore#2483]
It seems like `[FromQuery(Name = "xyz")]` is not respected for complex objects, such as classes in the following example:
```cs
public class MyParameter {
    public string Input { get; set; }
}

public async Task<IActionResult> GetTest([FromQuery(Name = "parameter")] MyParameter param) {
    // TODO
}
```
The documentation generated only shows it as `Input`, not `parameter.Input`, which is not correct and will not work with ASP.NET.

**Comment by timaiv** [comment]
Also problem with `[FromQuery(Name = "")]`
I use this to share same properties between similar requests.

https://stackoverflow.com/questions/75683726/how-to-use-fromquery-with-nested-models/75684248#75684248

**Comment by UnholyRanger** [comment]
To help with the investigation, as I'm having this issue as well, this appears to stem from the deprecated `Microsoft.AspNetCore.Mvc.ApiExplorer.IApiDescriptionGroupCollectionProvider.ApiDescriptionGroups` which already has the `FromQuery(Name = "")` applied to the `ApiParameterDescription`. We would need to investigate if moving to the new [Asp.Versioning.Mvc.ApiExplorer](https://www.nuget.org/packages/Asp.Versioning.Mvc.ApiExplorer) is possible and would resolve this issue.
