### ISSUE TITLE
OpenApi Version Update

### ISSUE THREAD

**Issue by tbaragao** [domaindrivendev/Swashbuckle.AspNetCore#2484]
I'm trying to update the openapi version exposed on swagger.json to 3.0.3 (at least).

Searched in a lot of places how to do that and didn't found a solution.

We already update the project to Swashbuckle.AspNetCore in the latest version (6.4.0) and still getting OpenApi 3.0.1 version.

**Comment by mauriciotalavera** [comment]
Agree we noticed the same issue and is causing troubles with the WAF configuration

**Comment by icnocop** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2349
