### ISSUE TITLE
Potential for localizing endpoint / metadata text

### ISSUE THREAD

**Issue by ronnyek** [domaindrivendev/Swashbuckle.AspNetCore#2485]
I'm not sure if this is a feature request, or just a question. I don't mind doing more research if I've got an idea if its possible, and get an idea of what I'm searching for.

I'm just curious if swashbuckle and swagger / openapi support providing information about endpoints and the requests/responses be localized so a customer isn't stuck viewing documentation in a fixed language.

The only documentation I found that seemed like it was a possibility was this github issue, which never got any responses:
#2161

**Comment by martincostello** [comment]
I don't think this would be possible without very heavy customisation using filters. You'd need to document everything just as resource keys, and then dynamically look up all the text at runtime on a per-request basis. This would then also play havoc with any caching we might do.

I don't think this is something we'd ever support out-of-the-box as to do so would probably be a huge piece of work.
