### ISSUE TITLE
Types being included in schema repository prior to ISchemaFilter running

### ISSUE THREAD

**Issue by johnwc** [domaindrivendev/Swashbuckle.AspNetCore#2486]
We are returning a Geometry type from NetTopologySuite using their GeoJson converter. They unfortunately do not have a custom schema generator for swashbuckle, so we are having to write our own. The issue is when we look in the generated schema, there is a bunch of NetTopologySuite types being included into the schema repository, even though we are handling the schema for the Geometry type in out ISchemaFilter.

It shouldn't be importing all of the geometry references types, since we are taking over the schema generation for it.

**Comment by johnwc** [comment]
Not stale, no response from dev team

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.

**Comment by johnwc** [comment]
Closing, as that was 2 years ago and nowhere near working in the same area to be able to quickly produce the example.
