### ISSUE TITLE
The swaggerendpoint cannot be set to a value other than "swagger"？

### ISSUE THREAD

**Issue by 835718973** [domaindrivendev/Swashbuckle.AspNetCore#2490]
I want to set the document page path to a custom value,but if the use "/swagger/v1/swagger.json",it works,otherwise "/swagger1/v1/swagger.json",it does not work.

**Comment by fschick** [comment]
It's possible.

Example UI:
https://demo.timetracking.schick-software.de/openapi/index.html

Example code:
https://github.com/fschick/TimeTracking/blob/main/FS.TimeTracking/FS.TimeTracking.Api.REST/Startup/OpenApi.cs
Search in code for constant `OPEN_API_UI_ROUTE`
