### ISSUE TITLE
swagger ui and uuid

### ISSUE THREAD

**Issue by Looooooka** [domaindrivendev/Swashbuckle.AspNetCore#2492]
I notices that swashbuckle's swaggerui interface relies on the swaggerui javascript code which unfortunately always assigns the same
 guide value to uuid strings:
 (source: https://github.com/swagger-api/swagger-ui/blob/b825e440770d9328996a116784cb77b05ab24c6c/src/core/plugins/samples/fn.js)
 
  "string_uuid": () => "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  
  is there any way to override the client UI to randomize this everytime the "execute" button is called, specifically with net 6's minimal API configuration?

**Comment by esbenbach** [comment]
Seems like this would be a question better asked in the Swagger-UI repo?

If its possible to configure it in the ui you should be able to do it with the custom index feature: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-indexhtml
