### ISSUE TITLE
SwaggerUI XSS vulnerability

### ISSUE THREAD

**Issue by hbahrini** [domaindrivendev/Swashbuckle.AspNetCore#2494]
Hi,

Do you have any plan to fix the XSS vulnerability in the SwaggerUI ?
https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers/

I tried the latest version (Swashbuckle.AspNetCore 6.4.0) but it seems to be vulnerable too.

Reproduce steps:
1-Open the SwaggerAPI link: http://localhost:xxxxx/swagger/index.html
2-Add the request parameter: ?configUrl=https://jumpy-floor.surge.sh/test.json

**Comment by hbahrini** [comment]
Please ignore this issue, it was a cache problem (old JS files from an old vulnerable version was being used after updating to a  clean version) so I tried to clear the browser cache. After testing, the versions 6.3.0 and 6.4.0 seems to be clean (no XSS vulnerability and no malicious API can be inserted into the Swagger API page)

**Comment by Duzlawi** [comment]
<img src=1 onerror=alert(1)>
