### ISSUE TITLE
Swagger json ver 3 does not included produces, and UI does not have Response Content Type Selection

### ISSUE THREAD

**Issue by jerchap** [domaindrivendev/Swashbuckle.AspNetCore#2496]
By default the swagger output is version 3.0.1, and it doesn't include the "produces" array in the json output.  Instead, it includes the possible response content-types in the responses/content property.  However the swagger UI seems to require the "produces" array to display and populate the "Response Content Type" selector so that I can specify, via the UI, what content-type I want the response to be.  Is this intended behavior, because it seems like I need to revert back to V2 using the SerializeAsV2 option to get that functionality back.

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
