### ISSUE TITLE
When you switch groups, authorization information is lost

### ISSUE THREAD

**Issue by linege** [domaindrivendev/Swashbuckle.AspNetCore#2497]
I'm using the latest version of VS2022, and when I created the net6 webapi project, I grouped the interfaces, but when I switched the groupings, the authorization information was lost.

**program.cs**
 
![image](https://user-images.githubusercontent.com/26296687/189537924-3e5def24-b8d9-4dbd-bc87-715f5c66fb79.png)

**my controller**
 
![image](https://user-images.githubusercontent.com/26296687/189537937-bb39ce86-3a26-48b8-a666-689c43b55b1a.png)

**Comment by linege** [comment]
Hi ~ this is my first time submitting issues, there is something wrong please forgive me.

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
