### ISSUE TITLE
NSwag.AspNetCore not working as documented (getting 404 errors) in Microsoft.AspNetCore.OData service fabric project project

### ISSUE THREAD

**Issue by daverozee** [domaindrivendev/Swashbuckle.AspNetCore#2498]
Service fabric project
kestrel web server
Visual studio 2022
NSwag.AspNetCore 13.6.1
Microsoft.ServiceFabric.AspNetCore.Kestrel 3.2.187

Added documented sections:

As per documentation:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-6.0&tabs=visual-studio

// Register the Swagger generator and the Swagger UI middlewares
app.UseOpenApi();
app.UseSwaggerUi3();

services.AddSwaggerDocument();

Launch the app. Navigate to:
http://localhost:<port>/swagger to view the Swagger UI.
http://localhost:<port>/swagger/v1/swagger.json to view the Swagger specification.

Get 404 errors for all swagger endpoints

**Comment by icnocop** [comment]
Are you missing a call to `AddSwaggerGen()`?

See https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio
