### ISSUE TITLE
Ahoy not generating endpoints when targeting dnx451 in Asp.Net Core

### ISSUE THREAD

**Issue by pdushkin** [domaindrivendev/Swashbuckle.AspNetCore#250]
I am using Asp.Net Core and have updated to Ahoy. However, my project is using Entity Framework 6.1.3, which requires the full framework. Accordingly, due to the [limitations of this requirement](https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6), I have the following in my project.json accross all projects:

```
"frameworks": {
    "dnx451": {}
  },

```
Now, this seems to impact Ahoy as it appears to need the deps.json file generated by the netcoreapp1.0 framework to paint the Rest UI. However, including netcoreapp1.0 creates all sorts of conflict errors as Entity Framework 6.1.3 doesn't play well with it.  

So, how do I do this? If I revert to version 5.5.3 I am no longer able to hook into the Swashbuckle Startup.cs services pipeline.   

I'd appreciate some direction (particularly project examples) regarding how to use Swashbuckle in an "Asp.Net Core" project exclusively targeting framework dnx451.

Thanks in advance.

**Comment by tillig** [comment]
The article you linked shows `net452` not `dnx451`. The dnx target framework monikers were deprecated when .NET Core was released.
