### ISSUE TITLE
Update swagger-ui 4.12.0 due to vulnerability

### ISSUE THREAD

**Issue by alex-kri** [domaindrivendev/Swashbuckle.AspNetCore#2501]
swagger-ui dependency should be updated to later version as the currently used one contains a known vulnerability.
https://github.com/swagger-api/swagger-ui/security/advisories/GHSA-qrmm-w75w-3wpx

**Comment by icnocop** [comment]
swagger-ui was updated to 4.14.0 as part of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2491
