### ISSUE TITLE
Make a component property required and nullable

### ISSUE THREAD

**Issue by Jacob-Roberts** [domaindrivendev/Swashbuckle.AspNetCore#2510]
I'm not seeing any documentation or method to make a property both required and nullable. 

When I annotate a property like this:

```cs
public class Something {
    [Required]
    public string? Note { get; init; }
}
```

I would expect to have a resulting openapi doc of the following:

```json
{
  "Something": {
    "required": ["note"],
    "type": "object",
    "properties": {
      "note": {
        "minLength": 1,
        "type": "string",
        "nullable": true
      }
    },
    "additionalProperties": false
  }
}
```

However, the `"nullable": true` is not there. But then when I remove the required attribute, nullable appears, but the property is no longer in the "required" array. 

How can I get both of these at the same time?

**Comment by Havunen** [comment]
If it is required it cannot be null even the dotnet API does not accept such request?

**Comment by martincostello** [comment]
I guess the nuance here is that you want the property to be explicitly specified, but you want to allow the value given to still be `null`.
