### ISSUE TITLE
Certain DataAnnotations do not appear to be support   [Display(Name = "")] for example

### ISSUE THREAD

**Issue by flauckner** [domaindrivendev/Swashbuckle.AspNetCore#252]
We have a call with a Swagger response defined with a type.
 [SwaggerResponse(System.Net.HttpStatusCode.OK, Type = typeof(SearchAssignStandardPUTReturn))]

In that class, we have property defined with some annotations defined.

        [StringLength(50)]
        [Display(Name = "Search Party Prefix")]
        [DataMember(Name = "SearchPartyPrefix")]
        [JsonProperty(PropertyName = "SearchPartyPrefix")]
        public String SearchPartyPrefix { get; set; }

Currently, only the string length and JsonProperty are included in the swagger.json file.

How can we get the [Display(Name'"...   annotation to be included in the swagger.json ?

**Comment by spacedsweden** [comment]
[Display(Name = "Search Party Prefix")] is not a dataanotation right, its a ASP.net attribute for ui, should that really be in a swagger doc`? I am conflicted :D

**Comment by domaindrivendev** [comment]
@flaukner - specifically which Swagger Schema field would you expect to see this mapped to? The one that makes most sense to me is _title_ but it looks like this is ignored by the [swagger-ui](https://github.com/swagger-api/swagger-ui). So, I could go ahead and make this change but, to set expectations, I don't think your UI will be rendered any differently.

**Comment by flauckner** [comment]
We have found a workaround.  Thank you for your response

**Comment by qub1n** [comment]
> We have found a workaround. Thank you for your response

What kind of workaround?

**Comment by qub1n** [comment]
> @flaukner - specifically which Swagger Schema field would you expect to see this mapped to? The one that makes most sense to me is _title_ but it looks like this is ignored by the [swagger-ui](https://github.com/swagger-api/swagger-ui). So, I could go ahead and make this change but, to set expectations, I don't think your UI will be rendered any differently.

So is there a way, how I can propagate description of the property from C# code to swagger documentation?
