### ISSUE TITLE
Root tags object not showing

### ISSUE THREAD

**Issue by greg-signi** [domaindrivendev/Swashbuckle.AspNetCore#2530]
I set the attribute [Tags("...")] in the Controler and despite having my openapi.json object with tags under the designated methods, eg:

`"paths": {
    "/sessions": {
      "post": {
        "tags": [
          "Authentication Session"
        ],
        "summary": "Create a session",`
        
The root object tags is not created. Any idea what's missing ?

**Comment by domaindrivendev** [comment]
I'm not familiar with the `TagsAttribute` you're referring to. Could you please provide more info (sample code, expected output etc.).

**Comment by greg-signi** [comment]
Hello, either the [Tags("User")] from Microsoft.AspNetCore.Http or `[SwaggerOperation(Tags = new[] { "User" }] from Swashbuckle.Swagger.Annotations`

And they work in some instance since they are able to get appended to the method information `"paths": { "/sessions": { "post": { "**tags**": [ "Authentication Session" ], "summary": "Create a session",` 

But the array "tags" at the root level object, remains empty. I did a workaround where I create a `IDocumentFilter` and fill the array `swaggerDoc.Tags` by hand.. But I shouldn't have to do this right ?

**Comment by yingxinj** [comment]
Hello, please see the linked PR https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2565 that adds support for the `TagsAttribute` - let me know if this would be helpful for resolving your issue, or if you had a different approach to implementing a workaround @greg-signi?

**Comment by personball** [comment]
Hi, any update for ” the array tags at the root level object, that encompasses all the tags available in the api, remains empty“ ？

**Comment by martincostello** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2565#issuecomment-2053577323
