### ISSUE TITLE
Comment summary and example do not work for Enum properties

### ISSUE THREAD

**Issue by JoepGeevers** [domaindrivendev/Swashbuckle.AspNetCore#2534]
I create documentation through comments (which works great!) like:

```
/// <summary>
/// Required. May be smaller than cents
/// </summary>
/// <example>1.1979</example>
[Required]
public decimal Amount { get; set; } = default!;
```

becomes

```
"amount": {
  "type": "number",
  "description": "Required. May be smaller than cents",
  "format": "double",
  "example": 1.1979
},
```

Perfect!

Except for Enum properties. Any summary or example that I put it, seems to be completely ignored, doesn't show up in the json, doesn't show up in the UI, and the example is not copied to the example request body.

```
/// <summary>
/// Optional. Specifies the method used to round tax amount
/// </summary>
/// <example>ToEven</example>
public Rounding Rounding { get; set; } = Rounding.None;
```

becomes

```
"rounding": {
  "$ref": "#/components/schemas/Rounding"
}
```

Using Swashbuckle.AspNetCore v6.4.0

**Comment by domaindrivendev** [comment]
Dup/same root cause as #2378. Long story short - you need to apply the `UseAllOfToExtendReferenceSchemas` setting

**Comment by JoepGeevers** [comment]
That solves it, thanks! That effect was a bit surprising to me.
