### ISSUE TITLE
6.3.0 (V2 Spec) - Remove 'Body' parameter from GET request definition 

### ISSUE THREAD

**Issue by Encodian** [domaindrivendev/Swashbuckle.AspNetCore#2537]
Package(s): Swashbuckle.AspNetCore.* 
Version: 6.3.0
Forcing Swagger to render as V2:  c.SerializeAsV2 = true;

Consider this example controller action:
 // GET api/v1/mgmt/
 /// <param name="operationId">Retrieve the operation status for the Operation ID provided.</param>
 /// <returns>Response object, refer to schema definition: DtoBaseMgmtResponse</returns>
 /// <response code="200">Success</response>
 /// <response code="202">Accepted</response>
 /// <response code="400">Bad request</response>
 [HttpGet(Name = "GetOperationStatus")]
 [SwaggerConsumes("application/json")]
 [ProducesResponseType(typeof(DtoBaseMgmtResponse), 200)]
 [ProducesResponseType(typeof(DtoBaseMgmtResponse), 202)]
 [ProducesResponseType(typeof(DtoBaseMgmtResponse), 400)]
 [Metadata("Get an Operation Status", "Get the operation status of for the operation ID provided.", VisibilityType.Internal)]
 public async Task<IActionResult> GetOperationStatus(string operationId)

This generates the following definition: 
    "/api/v1/Mgmt/GetOperationStatus": {
      "get": {
        "tags": [
          "Mgmt"
        ],
        "operationId": "GetOperationStatus",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "operationId",
            "description": "Retrieve the operation status for the Operation ID provided.",
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "schema": { }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/DtoBaseMgmtResponse"
            }
          },
          "202": {
            "description": "Accepted",
            "schema": {
              "$ref": "#/definitions/DtoBaseMgmtResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/DtoBaseMgmtResponse"
            }
          }
        },
        "x-ms-visibility": "internal",
        "summary": "Get an Operation Status",
        "description": "Get the operation status of for the operation ID provided."
      }
    },

Note the parameters section:

"parameters": [
          {
            "in": "query",
            "name": "operationId",
            "description": "Retrieve the operation status for the Operation ID provided.",
            "type": "string"
          },
          **{
            "in": "body",
            "name": "body",
            "schema": { }
          }**
        ],

How do we ensure the second 'body' parameter is not added to the defintion? This is get request and would not contain a body and we do not want it within the swagger definition.

**Comment by domaindrivendev** [comment]
This should not be happening and I'm unable to repro it. However, the `SwaggerConsumesAttribute` is not part of Swashbuckle (is this a custom attribue you implemented?) and I wonder if it might be doing something behind the scenes to cause this 🤔. As this is a `GET` request with no body, it seems strange to be specifying that the operation "consumes" application/json.

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.

**Comment by NotAsea** [comment]
@martincostello hi it appear this problem start showing up again, all Get request get a strange `void` body in Asp.Net Core 8 minimal api project

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/88715515/822c6a71-e658-46fd-a428-8ae3d0850d3f)

you can see the route get strange body add in, while all parameter get infer correct, also all Map verb with no body (Get, Delete) get a strange void body add in
## Code

- In the rout defenition
 ```cs
public static class DadJokeRoute
{
    public static void HandleDadJokeRoute(this IEndpointRouteBuilder route)
    {
        route.MapGet("/", GetDadJoke);
        // -- snip----//
    }

    private static async Task<Results<Ok<DadJokeModel>, Ok<string>, BadRequest<string>>> GetDadJoke(
        [AsParameters] DadJokeParam param,
        string? term,
        bool asString
    )
    {
        var (service, logger) = param;
        try
        {
            return asString
                ? TypedResults.Ok(await service.GetDadJokeAsString(term).ConfigureAwait(true))
                : TypedResults.Ok(await service.GetDadJoke(term).ConfigureAwait(true));
        }
        catch (Exception ex)
        {
            var reason = ex.GetBaseException().Message;
            logger.CallApiFail(reason, ex.StackTrace!);
            return TypedResults.BadRequest(reason);
        }
    }
   // --- snip ---
}
```
the only reason i suspect, is SwashBuckle not recognise AsParameters Attribute and try serialise the `MapGet` call, this is not happened with v6.5.0 

- My setup code 

```cs
 builder.Services.AddEndpointsApiExplorer().AddHttpContextAccessor();
 builder.Services.AddSwaggerGen(c =>
        {
            c.AddSecurityDefinition(
                "bearerAuth",
                new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.Http,
                    Scheme = "bearer",
                    BearerFormat = "JWT",
                    Description = "JWT Authorization header using the Bearer scheme."
                }
            );
            c.AddSecurityRequirement(
                new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "bearerAuth"
                            }
                        },
                        Array.Empty<string>()
                    }
                }
            );
        });
```
- verrsion: washbuckle.AspNetCore / 6.6.2
