### ISSUE TITLE
Values of OneOf assigned within an ISchemaFilter have no output

### ISSUE THREAD

**Issue by ryno1234** [domaindrivendev/Swashbuckle.AspNetCore#2538]
I have an ISchemaFilter where I manually generate some addition schemas from some types and then add those returned schemas to the `OneOf` property. This generated .json output does not contain any reference to `oneOf`. I would think I would see my generated schemas listed there.

*Note: I realize Swashbuckle comes with support for Polymorphic models out of the box, try not to get hung up on my example below. :)*

Version: 6.4.0

    public class SwaggerPolymorphicSchemaFilter : ISchemaFilter
    {
        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            // Setup this model as having a discriminator 
            schema.Discriminator = new OpenApiDiscriminator()
            {
                PropertyName = "AnimalType";
            };

            OpenApiSchema dogSchema = context.SchemaGenerator.GenerateSchema(typeof(MyNamespace.DogModel), context.SchemaRepository);
            OpenApiSchema catSchema = context.SchemaGenerator.GenerateSchema(typeof(MyNamespace.CatModel), context.SchemaRepository);

            schema.OneOf.Add(dogSchema);
            schema.OneOf.Add(catSchema);
        }
    }

**Comment by domaindrivendev** [comment]
@ryno1234 I just applied your filter above in a test project and can confirm it's working as expected (see screenshot below). Please create a sample project that repro's your issue and post to github so I can pull down and troubleshoot.

<img width="391" alt="Screenshot 2022-11-15 at 20 59 24" src="https://user-images.githubusercontent.com/1434343/202024575-3cc2cc77-bf35-4fd1-8c76-375a6c4c02bd.png">

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
