### ISSUE TITLE
Run "dotnet swagger tofile" with .NET 7 SDK

### ISSUE THREAD

**Issue by ramondeklein** [domaindrivendev/Swashbuckle.AspNetCore#2539]
The current `dotnet swagger` tool cannot run with .NET 7. It shows:
```
You must install or update .NET to run this application.
App: /root/.nuget/packages/swashbuckle.aspnetcore.cli/6.4.0/tools/net6.0/any/dotnet-swagger.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0-rc.2.21480.5' (x64)
.NET location: /usr/share/dotnet/
The following frameworks were found:
  7.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0-rc.2.21480.5&arch=x64&rid=ubuntu.22.04-x64
```
It would be great to run this tool inside the `dotnet/sdk:7.0-jammy`, because that is also the container that is run to build the .NET 7 application. Looking at https://www.nuget.org/packages/Swashbuckle.AspNetCore.Cli, it doesn't support net7 yet.

**Comment by htuomola** [comment]
I think #2542 will resolve this when merged?

**Comment by ramondeklein** [comment]
@domaindrivendev I ran `dotnet tool install swashbuckle.aspnetcore.cli --version 7.0.0-preview-2114 --add-source https://www.myget.org/F/domaindrivendev/api/v3/index.json` in a `mcr.microsoft.com/dotnet/sdk:7.0-jammy` container and it seems to run fine. Running the 6.4.0 version shows the missing runtime message, so I guess this is fixed.

**Comment by ramondeklein** [comment]
@domaindrivendev Is there an ETA for a release that works for .NET 7?

**Comment by wsugarman** [comment]
@domaindrivendev - Any update on the .NET 7 release would be great

**Comment by MarianSWA** [comment]
@domaindrivendev Version 7.0.0-preview-2114 seems to have been removed from myget and this crashes our build. We were relying on it, temporarily, until the official .net 7 version is out. Can it be added back?

**Comment by htuomola** [comment]
@MarianSWA for what it's worth, if you install both .net 6 and 7 on build agent, you should still be able to use the CLI. Or that's what I'm doing. In Azure Pipelines it's just a matter of two UseDotNet-task calls.

**Comment by MarianSWA** [comment]
Thanks @htuomola, good point! For now we've switched to 6.5.0-preview-2124 from myget which seems to have .net 7 support as well. This leads me to belive that the next version, 6.5.0 will be released soon. Hopefully the preview will not be removed from myget until then.

**Comment by udlose** [comment]
any updates on releasing a version compatible with .NET 7 that doesn't require both .NET 6 and .NET 7 to be installed on the build agent?

**Comment by poimis** [comment]
> @MarianSWA for what it's worth, if you install both .net 6 and 7 on build agent, you should still be able to use the CLI. Or that's what I'm doing. In Azure Pipelines it's just a matter of two UseDotNet-task calls.

Thanks @htuomola, saved my day...or night :)

**Comment by angieleba** [comment]
@htuomola Hi, I receive an error when trying to execute the command: Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-swagger does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
  
I added it to the pipeline, changing the .net version. Any ideas?

**Comment by htuomola** [comment]
@angieleba are you executing dotnet tool install or dotnet tool restore to install swagger-cli? And it installs it without errors? There shouldn't be more to it.
