### ISSUE TITLE
Mimal Api TypedResults method no exist HttpContext

### ISSUE THREAD

**Issue by YataoFeng** [domaindrivendev/Swashbuckle.AspNetCore#2541]
Fix it. Thank you very much. 😊😊😊 love you hahaha
版本：.NET7
框架：Minimal Api
描述：https://github.com/dotnet/aspnetcore/issues/44970

**Comment by domaindrivendev** [comment]
It's not clear to me why this is an issue with Swashbuckle and from the upstream thread it sounds like it's not. Closing for now unless you can provide more information.
