### ISSUE TITLE
DeepCopy is missing InferSecuritySchemes

### ISSUE THREAD

**Issue by davidfowl** [domaindrivendev/Swashbuckle.AspNetCore#2545]
I spent some time debugging trying to figure out why calling `InferSecuritySchemes` on SwaggerGenOptions doesn't seem to work and it look like DeepCopy isn't setting `InferSecuritySchemes`.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/4a28652059c93dc95146d962df645bff8953e39f/src/Swashbuckle.As
pNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs#L55-L71

This explains why:

This does not work

```C#
builder.Services.AddSwaggerGen(c => c.InferSecuritySchemes());
```

This works

```C#
builder.Services.Configure<SwaggerGeneratorOptions>(opts =>
{
    opts.InferSecuritySchemes = true;
});
```

cc @captainsafia

**Comment by davidfowl** [comment]
Linking the right comment https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/e98e4aa651ef244ad123f82c0bd05a3c6d70c3f0

Also @domaindrivendev would be possible to put this in a patch release?

**Comment by westfin** [comment]
Hi everyone, seems we have the same issue for `SecuritySchemesSelector`.
