### ISSUE TITLE
XML documentation files are missing in RC1 packages

### ISSUE THREAD

**Issue by xperiandri** [domaindrivendev/Swashbuckle.AspNetCore#255]

**Comment by tillig** [comment]
The code itself has little to no XML API documentation [apparently intentionally](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/236/files/63c5a8f62896dce813f9ea4a524955b2b85a2ea2#r89422196) so it doesn't really matter if they'd be included or not since it'd all be empty.

**Comment by domaindrivendev** [comment]
@tillig - OK OK, I'll get over my personal issue with comments in general and add XML comments to the classes that make up Swasbuckle's public config. interface. Expect it in the stable release

**Comment by xperiandri** [comment]
Thanks!

**Comment by domaindrivendev** [comment]
See 82dd0e696e7ac2c5ef218d06a1ce9e4a2c8ffc8d
