### ISSUE TITLE
How can I not specify httppost in each method?

### ISSUE THREAD

**Issue by bbhxwl** [domaindrivendev/Swashbuckle.AspNetCore#2551]
How can I not specify httppost in each method?
I have written 100 methods, each of which requires a name. In fact, I use the method name. This is a lot of repetitive work.
![image](https://user-images.githubusercontent.com/26525599/202418376-fd225f14-83e7-4cd4-abdc-59a3945f2185.png)
![image](https://user-images.githubusercontent.com/26525599/202418396-db1b442a-ecd8-4dfd-b394-33729af980b2.png)

**Comment by Havunen** [comment]
Without declaring http method in the method, what http method are you expecting the client side to call when sending network request?

**Comment by martincostello** [comment]
This is how ASP.NET Core works, it's nothing to do with Swashbuckle.
