### ISSUE TITLE
I must specify the httpMethod and write the name? In this way, I also need to write the method name. It is troublesome to write the same method name twice.

### ISSUE THREAD

**Issue by bbhxwl** [domaindrivendev/Swashbuckle.AspNetCore#2552]
I must specify the httpMethod and write the name? In this way, I also need to write the method name. It is troublesome to write the same method name twice.

Can't I use the method name by default?

**Comment by domaindrivendev** [comment]
See option 2) in the following readme section:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#assign-explicit-operationids

**Comment by bbhxwl** [comment]
> See option 2) in the following readme section: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#assign-explicit-operationids

It seems not possible.


![image](https://user-images.githubusercontent.com/26525599/202599640-a7c2eb26-13a8-4748-8c80-7484a60e0395.png)
