### ISSUE TITLE
Add support for C# 11 'required' modifier.

### ISSUE THREAD

**Issue by joel1st** [domaindrivendev/Swashbuckle.AspNetCore#2555]
Now that C# has inbuilt language support for required properties, it might be worth discussing how we can take advantage of this with SwashBuckle to provide more accurate, streamlined API documentation.

I think the below comment covers my thoughts on this well:
[Since nullablility and required/not are different things where one does not necessarily imply the other, I think SwashBuckle should use the C# property nullability for swagger property nullable, and C# property required/not for the swagger property required.](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2036#issuecomment-1293304351)

**Comment by flostellbrink** [comment]
This did the trick for me:

```c#
using System;
using System.Linq;
using System.Runtime.CompilerServices;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

class SwaggerRequiredMemberFilter : ISchemaFilter
{
	public void Apply(OpenApiSchema schema, SchemaFilterContext context)
	{
		var requiredProperties = context.Type.GetProperties().Where(p => p.HasAttribute<RequiredMemberAttribute>());
		var schemaPropertyNames = schema.Properties.Keys.Where(
			sp => requiredProperties.Any(rp => string.Equals(sp, rp.Name, StringComparison.InvariantCultureIgnoreCase))
		);

		foreach (var property in schemaPropertyNames)
		{
			schema.Required.Add(property);
		}
	}
}
```

From a quick glance it looks like a proper implementation might get away with adding `RequiredMemberAttribute` here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/73610b90d65772b0648a5bc1846e5af54e7bad4f/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs#L15

**Comment by 30drie** [comment]
I used the solution from @flostellbrink, but found one flaw. I found that not all properties where marked required and when I looked at the code I saw that this only works as long as the name of the property is the same as the json name, but if you use JsonPropertyName to use snakecase for the API while your C# property has PascalCase naming convention, this code does not work.

So I changed the code slightly, basically do the foreach on the Properties of the class instead of Properties of the schema.
This code should work in all cases.

`
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

public class RequiredMemberFilter : ISchemaFilter
{
	public void Apply(OpenApiSchema schema, SchemaFilterContext context)
	{
		var nullabilityContext = new NullabilityInfoContext();
		var properties = context.Type.GetProperties();

		foreach(var property in properties)
		{
			if (property.HasAttribute<JsonIgnoreAttribute>() || !property.HasAttribute<RequiredMemberAttribute>()) continue;

			var jsonName = property.Name;
			if (property.HasAttribute<JsonPropertyNameAttribute>())
			{
				jsonName = property.GetCustomAttribute<JsonPropertyNameAttribute>()!.Name;
			}

			var jsonKey = schema.Properties.Keys.SingleOrDefault(key =>
				string.Equals(key, jsonName, StringComparison.OrdinalIgnoreCase));

			if (string.IsNullOrWhiteSpace(jsonKey)) continue;

			// Check nullability of non primitive types
			var primitive = schema.Properties[jsonKey].Type != null;
			if (!primitive)
			{
				// Do not mark nullableref types.
				// Ref types cannot be marked as nullable, so this would lead to them being non nullable.
				var nullabilityInfo = nullabilityContext.Create(property);
				if (nullabilityInfo.ReadState == NullabilityState.Nullable) continue;
			}

			schema.Required.Add(jsonKey);
		}
	}

}
`

**Comment by onionhammer** [comment]
This isnt a C# 11 issue, it's a discrepancy between the ASP.NET validator treatment of non-nullable properties and swashbuckle's. 

https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-7.0#non-nullable-reference-types-and-required-attribute

**Comment by onionhammer** [comment]
Any movement on this issue? AFAICT this discrepancy still exists

**Comment by Havunen** [comment]
FYI this should work in DotSwashbuckle

**Comment by mattiasnordqvist** [comment]
Is this related? 
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2810

I think the `required` keyword has been incorrectly interpreted as `not nullable`

**Comment by martincostello** [comment]
That has already been fixed for the next release: #2879

**Comment by cremor** [comment]
I think this can be closed as resolved?

**Comment by jgarciadelanoceda** [comment]
@martincostello this is a candidate to close
