### ISSUE TITLE
Visibility of sensitive data

### ISSUE THREAD

**Issue by a-a-k** [domaindrivendev/Swashbuckle.AspNetCore#2556]
Not sure if it's a bug, but I suspect this is something weird at least.
As you can see on the picture below, both the `ClientId` and  `ClientSecret` are disclosed in the request payload, which is kindly provided by browser console. Simultaneously, `ClientId` is carefully hided from us under asterisks on the Authorization dialog panel.

![image](https://user-images.githubusercontent.com/5455861/203535922-09145ba5-dd34-4aef-9cf3-65086faa82b7.png)

**Comment by domaindrivendev** [comment]
Please post this to the swagger-ui repo, which is leveraged but not maintained by Swashbuckle authors

**Comment by a-a-k** [comment]
can I somehow transfer this issue there to prevent doubling?

**Comment by domaindrivendev** [comment]
It shouldn’t be here so please recreate in the other repo and reference this one from there
