### ISSUE TITLE
SwaggerDoc Info description is not showing non-html href

### ISSUE THREAD

**Issue by masterjs** [domaindrivendev/Swashbuckle.AspNetCore#256]
Hello,
I just upgraded from the 6.0.0-beta902 to the Swashbuckle.AspNetCore 1.0.0-rc1. All is fine, except for the information I was putting in the Description of the Info object in the SwaggerDoc. I use to have a simple text with some html markups and one of them was a reference to Slack using their deep-linking URI. So it was something like 
`Description = "Bla bla bla.. <a href='slack://channel?team=TEAMX&id=CHANNELY'>Slack</a>.. bla bla ble";`

Now with the new version, when the **href** is not a "http", it just removes it when rendering the swagger documentation. Is there a know work-around for this?

thank you,
JS

**Comment by masterjs** [comment]
Hello again,
I now have a workaround for my issue. I recently learned that MarkDown is also supported. So I instead use the following and it works!
`Description = "Bla bla bla.. [Slak](slack://channel?team=TEAMX&id=CHANNELY).. bla bla bla";`

So in a summary, the HTML is not working for non-html references, but it will at least work in MarkDown.

I'll leave the issue open since there's still the HTML issue.

thank you,
JS

**Comment by domaindrivendev** [comment]
This sounds more like a UI issue that a Swagger generation issue. Can you check the raw Swagger JSON (i.e. at /swagger/v1/swagger.json) and ensure that the Description fields still contain the correct HTML?

If you've confirmed this, then this is really a UI issue and should instead be reported to the [swagger](https://github.com/swagger-api/swagger-ui) guys.
