### ISSUE TITLE
Create GitHub Security Advisory for server side request forgery in SwaggerUI dependency

### ISSUE THREAD

**Issue by pshelton-skype** [domaindrivendev/Swashbuckle.AspNetCore#2560]
Swashbuckle repackages the `swagger-ui-dist` npm package and thus inherits a server side request forgery vulnerability outlined in https://github.com/advisories/GHSA-qrmm-w75w-3wpx. 

This was fixed in Swagger version 4.1.3 and released in Swashbuckle version 6.4 per  https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/401c7cb81e5efe835ceb8aae23e82057d57c7d29. 

Per discussion in https://github.com/github/advisory-database/pull/900, the ideal security workflow is that the maintainers of the Swashbuckle library should [create a separate GitHub Security Advisory](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/creating-a-repository-security-advisory) in order to alert consumers to the vulnerability and describe any recommended mitigation or upgrade steps. 

Per the [best practices](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/best-practices-for-writing-repository-security-advisories), I would recommend the advisory contain the following information:
______

**Title:** Server side request forgery in Swashbuckle.AspNetCore
**Ecosystem:** Nuget
**Package Name:** Swashbuckle.AspNetCore.SwaggerUI
**Affected versions:** < 6.4
**Patched versions:** 6.4
**Description:** 

SwaggerUI supports displaying remote OpenAPI definitions through the `?url` parameter. This enables robust demonstration capabilities on sites like `editor.swagger.io` where users often want to see what their OpenAPI definitions would look like rendered.

However, this functionality may pose a risk for users who host their own SwaggerUI instances. In particular, including remote OpenAPI definitions opens a vector for phishing attacks by abusing the trusted names/domains of self-hosted instances.

**Resolution:**
Upgrade to Swashbuckle.AspNetCore.SwaggerUI 6.4, which includes a change in the core SwaggerUI library to [disable query parameters ](https://github.com/swagger-api/swagger-ui/issues/4872). 

Alternatively, review the provided workaround in https://github.com/advisories/GHSA-qrmm-w75w-3wpx to disable the use of the `?url` parameter.

**Comment by pshelton-skype** [comment]
@domaindrivendev, can you assist?

**Comment by pshelton-skype** [comment]
@domaindrivendev, please assist in notifying consumers of a security vulnerability.

**Comment by Havunen** [comment]
Fixed in DotSwashbuckle

**Comment by martincostello** [comment]
I don't have access to create the advisory, only @domaindrivendev can do so.
