### ISSUE TITLE
Support `ParameterFilter` and `RequestBodyFilter` on `OpenApiOperation` from metadata

### ISSUE THREAD

**Issue by captainsafia** [domaindrivendev/Swashbuckle.AspNetCore#2561]
@marcominerva reported an issue in https://github.com/dotnet/aspnetcore/issues/45307 wherein parameter filters are not applied to parameters in `OpenApiOperation`s sourced from metadata.

I believe this happens for `ParameterFilter`s (and like `RequestBodyFilter`s) because these filter types are invoked closer to the creation of those generators where as `DocumentFilter`s and `OperationFilter`s run after the OpenApiOperation has been plucked from metadata.

Is there a strategy we can use to run these filter types across both scenarios without much duplication?

**Comment by artyom-p** [comment]
Any progress here?

**Comment by warappa** [comment]
Still having this problem on .NET 8.0.1

**Comment by jgarciadelanoceda** [comment]
It's supported with #3059
