### ISSUE TITLE
Does'nt support Extension and ExtensionProperty, like java ?

### ISSUE THREAD

**Issue by wangzhi005578** [domaindrivendev/Swashbuckle.AspNetCore#2567]
like this:
**@ApiOperation(value = "user", 
            extensions = { 
            @Extension(name = "custom parameter", properties = { 
                    @ExtensionProperty(name = "userEmail", value = "user email") } ) })**
public ServerResponse<User> login(User user){
    // do something...
}

**Comment by martincostello** [comment]
Please explain your use case in more detail so we can help.
