### ISSUE TITLE
What if From atrribute is not applicable?

### ISSUE THREAD

**Issue by xperiandri** [domaindrivendev/Swashbuckle.AspNetCore#257]
What if I have a method like this where input parameter comes from some middleware
``` C#
        public async Task<IActionResult> Logout(OpenIdConnectRequest request)
        {
            // Ask ASP.NET Core Identity to delete the local and external cookies created
            // when the user agent is redirected from the external identity provider
            // after a successful authentication flow (e.g Google or Facebook).
            await signInManager.SignOutAsync();

            // Returning a SignOutResult will ask OpenIddict to redirect the user agent
            // to the post_logout_redirect_uri specified by the client application.
            return SignOut(OpenIdConnectServerDefaults.AuthenticationScheme);
        }

```
How to produce Swagger that ommits this parameter?

**Comment by xperiandri** [comment]
Is `[FromServices]` attribute is right thing to use?

**Comment by domaindrivendev** [comment]
If it's not from the request, I would have expected it to be ignored by virtue of the following line:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs#L132

In your case, not sure exactly how the middleware injects the parameter and how it sets "IsFromRequest" on the BindingSource. Need to investigate further ...

**Comment by xperiandri** [comment]
But it is not ignored.
I use [OpenIddict](https://github.com/openiddict/openiddict-core)
The methods I use in AuthorizeController have the same signatures as in samples of that repository.
And request is preprocessed by [ASOS](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server)

**Comment by TsengSR** [comment]
Is `OpenIdConnectRequest` a service registered in the ASP.NET Core DI? If so, [FromService] is the correct way to inject these services into the action method. It is useful when you don't want to inject it via constructor, i.e. there is only a single method which use it and you don't want to pollute the constructor with it. 

If that's the case and swagger fails with `[FromService]`, you can move it to the constructor as workaround. The generator should ignore FromService (if not already the case).

**Comment by PinpointTownes** [comment]
> Is OpenIdConnectRequest a service registered in the ASP.NET Core DI?

Actually, it's not: it's instantiated, populated and stored by ASOS in an HTTP feature named `OpenIdConnectServerFeature`.

It can be later retrieved using `HttpContext.Features.Get<OpenIdConnectServerFeature>()?.Request` or `HttpContext.GetOpenIdConnectRequest()`, but OpenIddict also comes with a MVC model binder that allows using `OpenIdConnectRequest` as an action parameter.

https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Mvc/OpenIddictModelBinder.cs
https://github.com/openiddict/openiddict-core/blob/dev/test/OpenIddict.Mvc.Tests/OpenIddictModelBinderTests.cs

> In your case, not sure exactly how the middleware injects the parameter and how it sets "IsFromRequest" on the BindingSource. Need to investigate further ...

TBH, I'm not familiar with MVC's API description stack, but what's sure is that we never explicitly set the `BindingSource`, so it should be left to `null` and `IsFromRequest` should be `false` in this case.

@xperiandri out of curiosity, why do you want to include this endpoint - [defined by the OIDC session spec](http://openid.net/specs/openid-connect-session-1_0.html#RPLogout) - in your API docs?

**Comment by xperiandri** [comment]
Now it is used from Java on Android. And there is no good OIDC library, and not OIDC library that supports Resource Owner Password Credential Grant

**Comment by xperiandri** [comment]
@TsengSR, `FromServices` works as a workaround for Swagger error elimination, but the value comes from the request outline

**Comment by sandorfr** [comment]
I think `FromServices` should indeed be trimmed but just because it is a DI injected parameter. Maybe there should be a `SwaggerIgnore` kind of attribute which may be used when we want or need to drop a parameter.

As it is very specific, I think a quick workaround to this issue would be to set `[ApiExplorerSettings(IgnoreApi = true)]`flag on the action and write this action specs using a document filter.

**Comment by PinpointTownes** [comment]
> Now it is used from Java on Android. And there is no good OIDC library, and not OIDC library that supports Resource Owner Password Credential Grant 

Then I'm not sure to understand why you'd use the logout/end session endpoint, as it's only useful for redirection-based OAuth2/OIDC flows like code, hybrid or implicit. In your case, there's really no point using it :sweat_smile:

**Comment by xperiandri** [comment]
I just posted it because it was shorter that `Exchanged`.
Do you mean if I use ROPC, I don't need `Logout`? As it only makes sense for interactive flows.

**Comment by PinpointTownes** [comment]
> Do you mean if I use ROPC, I don't need Logout? As it only makes sense for interactive flows.

Yup, that's why I mean.

**Comment by domaindrivendev** [comment]
@xperiandri - can I close this at this point?

**Comment by xperiandri** [comment]
Well the solution with `[FromServices]` works but is it correct one?
