### ISSUE TITLE
Expose the swagger generation route(s) in the swagger.json

### ISSUE THREAD

**Issue by orty** [domaindrivendev/Swashbuckle.AspNetCore#2570]
I am trying to expose the routes which give back the `swagger.json` documents for an ASP.Net 6 web api, in the generated `swagger.json` itself. I just need to see the swagger generation route used to generate the JSON document, alongside the other endpoints of my API.

I tried both `app.UseSwagger` and `app.MapSwagger` but the route template (containing the `{documentName}` token) never make its way to the Operations parsed by Swashbuckle.

How can I achieve this goal ?

Thx !

**Comment by Havunen** [comment]
Just use the Swagger middleware add the UI copy paste the route urls and remove UI middleware
