### ISSUE TITLE
System.Text.JSON polymorphic behaviour not supported

### ISSUE THREAD

**Issue by Stepami** [domaindrivendev/Swashbuckle.AspNetCore#2571]
Beginning with .NET 7, System.Text.Json supports polymorphic type hierarchy serialization and deserialization with attribute annotations.

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism

But if we configure swagger to use polymorphism it does not add information about derived type to docs.

As I think, the problem is that [JsonDerivedType] adds implicit discriminator property which can be seen in json string only. 

So, it is interesting to know the plans for support of this feature in library.

**Comment by Tungsten78** [comment]
Ideally, Swashbuckle would be able to infer what it needs from the new attributes. 

Currently, there's a need to duplicate
```
  [JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
  [SwaggerDiscriminator("type")] //the need to duplicate may one day be removed, see https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2571
  [JsonDerivedType(typeof(AnyCriteria), "Any")]
  [SwaggerSubType(typeof(AnyCriteria), DiscriminatorValue = "Any")]
  [JsonDerivedType(typeof(EqualCriteria), "Equal")]
  [SwaggerSubType(typeof(EqualCriteria), DiscriminatorValue = "Equal")]
  [JsonDerivedType(typeof(GreaterThanCriteria), "GreaterThan")]
  [SwaggerSubType(typeof(GreaterThanCriteria), DiscriminatorValue = "GreaterThan")]
  [JsonDerivedType(typeof(LessThanCriteria), "LessThan")]
  [SwaggerSubType(typeof(LessThanCriteria), DiscriminatorValue = "LessThan")]
  [JsonDerivedType(typeof(BetweenCriteria), "Between")]
  [SwaggerSubType(typeof(BetweenCriteria), DiscriminatorValue = "Between")]
  public abstract record Criteria;

  public record AnyCriteria : Criteria;

  public record EqualCriteria : Criteria;

  public record GreaterThanCriteria(bool OrEqual, decimal Value) : Criteria;

  public record LessThanCriteria(bool OrEqual, decimal Value) : Criteria;

  public record BetweenCriteria(bool OrEqual, decimal From, decimal To) : Criteria;

**Comment by Stepami** [comment]
Eventually, i've made the NuGet package that solves my problem.
It works due to the following algorithm:

1. Scan predefined through `appsettings.json` file assemblies for classes marked with `[JsonDerivedType]`. Those types are the roots of hierarchies.
2. Those roots are being transformed to hierarchies thanks to attribute metadata and cached into the singleton repository.
3. Custom `ISchemaFilter` implementation enriches documentation with additional discriminator info using consumed data before.

Obviously, the solution is not perfect as it requires knowledge about assemblies containing polymorphic contracts and obligates a developer to build hierarchy according to certain limitations.

More information provided in repository of package:
https://github.com/Stepami/swagger-discriminator-setup

**Comment by benlongo** [comment]
It's relatively straightforward to use `SelectSubTypesUsing`, `SelectDiscriminatorNameUsing` and `SelectDiscriminatorValueUsing` to make this work I think

**Comment by Stepami** [comment]
@benlongo not really. We cannot specify the type of discriminator and map it to allowed values in some kind of enum with corresponding defaults.

**Comment by schnerring** [comment]
> @benlongo not really. We cannot specify the type of discriminator and map it to allowed values in some kind of enum with corresponding defaults.

Well, STJ deserialization doesn't actually put the discriminator value into a property, so enum-valued type discriminators would be a thing of the past.

[The docs on customizing the type discriminator name also state](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0#customize-the-type-discriminator-name):

> Avoid using a [JsonPolymorphicAttribute.TypeDiscriminatorPropertyName](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpolymorphicattribute.typediscriminatorpropertyname#system-text-json-serialization-jsonpolymorphicattribute-typediscriminatorpropertyname) that conflicts with a property in your type hierarchy.

See also: https://github.com/dotnet/runtime/issues/72170

**Comment by Havunen** [comment]
FYI This should work in DotSwashbuckle

**Comment by martincostello** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2671#issuecomment-2053575845

**Comment by martincostello** [comment]
#3170

**Comment by DavidPx** [comment]
Just in case anyone is having trouble getting this working...  you have to add the `Swacshbuckle.AspNetCore.Annotations` package.  See [this documentation](https://github.com/domaindrivendev/Swashbuckle.AspNetCore?tab=readme-ov-file#enrich-polymorphic-base-classes-with-discriminator-metadata) for how to set it up.  It's [linked from the main readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore?tab=readme-ov-file#describing-discriminators) here, too.
