### ISSUE TITLE
No service for type 'Microsoft.AspNetCore.Authentication.IAuthenticationService

### ISSUE THREAD

**Issue by bklooste** [domaindrivendev/Swashbuckle.AspNetCore#2573]
When return ForbidResult without IAuthenticationService then the following is produced from Swagger middleware "No service for type 'Microsoft.AspNetCore.Authentication.IAuthenticationService".  And no we dont use  IAuthenticationService our security is done in anotther layer but sometimes we return Forbid 

![image](https://user-images.githubusercontent.com/261344/207231048-77b840b8-6259-46c6-bdb5-0d028ddf2f07.png)

Version 6.4
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />

**Comment by martincostello** [comment]
This doesn't appear that it's being thrown by Swashbuckle, our middleware is just in the pipeline and `RequestDelegateFactory` is invoking a user-provider endpoint which uses `ForbidResult`.
