### ISSUE TITLE
Release v6.5.0 on NuGet

### ISSUE THREAD

**Issue by captainsafia** [domaindrivendev/Swashbuckle.AspNetCore#2576]
It looks like 6.5.0 has been versioned in the repo but is not yet available on NuGet. Can this be published on NuGet so apps can pickup the `InferSecuritySchemes` bug fix?

**Comment by Meligy** [comment]
That'd also be potentially solve https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2539?

**Comment by udlose** [comment]
I'm waiting on this for the ability to run it with .NET 7

**Comment by dawsonbooth** [comment]
Also eager for this release as it includes the `DateOnly` format fix addressed in #2480

**Comment by kcadduk** [comment]
Also waiting. Just stood up a new application to find that it can't work without .net 6 SDK

**Comment by Krusty93** [comment]
Same problem here

**Comment by MarcoBlamauer** [comment]
Same here. What is taking so long? .NET 7 was release almost 2 months ago...

**Comment by domaindrivendev** [comment]
Just released `6.5.0` to Nuget

**Comment by domaindrivendev** [comment]
Just released `6.5.0` to Nuget
