### ISSUE TITLE
<see href="link">text</see> is not converted to correct Markdown link

### ISSUE THREAD

**Issue by mburumaxwell** [domaindrivendev/Swashbuckle.AspNetCore#2577]
`<see href="link">text</see>` tags are currently not converted to Markdown which is the expected format for descriptions in OpenAPI/Swagger. Redoc does not generate a link for `<see href="link">text</see>` but instead displays the inner text as-is.

**Comment by martincostello** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2392#issuecomment-2053579399
