### ISSUE TITLE
Using JsonAPI is not reflected in Swagger docs

### ISSUE THREAD

**Issue by BryanCrotaz** [domaindrivendev/Swashbuckle.AspNetCore#2586]
I'm using [JsonApiSerializer](https://github.com/codecutout/JsonApiSerializer/) to format responses and POSTed models as Json:API.

Feature Request: Is there a way that the documentation generated here can reflect this in the schemas?

**Comment by martincostello** [comment]
I don't think we're going to take on support for a third JSON serializer.

If it's not possible to use the current extensibility model to allow someone to write their own support for an arbitrary JSON serializer, then we'd consider making changes to allow someone to do that, depending on their size of the changes required to do so.
