### ISSUE TITLE
 HTML injection in Swashbuckle swagger UI

### ISSUE THREAD

**Issue by Zen-Rahul** [domaindrivendev/Swashbuckle.AspNetCore#2594]
I found HTML injection can be possible in Swashbuckle swagger UI, please find the below steps to reproduce the issue:

1. Open any swagger UI, eg. https://petstore.swagger.io/
2. And then add configUrl query parameter eg. ?configUrl=https://jumpy-floor.surge.sh/test.json

For example open https://petstore.swagger.io/ and then add ?configUrl=https://jumpy-floor.surge.sh/test.json query in Url. You will find entire swagger definition will change. I know this feature is provided by https://swagger.io/ but is there any way to disable this in Swashbuckle ?
[HTML Injection.docx](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/10473913/HTML.Injection.docx)

**Comment by Baertie** [comment]
Why closed? I have the same issue

**Comment by Zen-Rahul** [comment]
Try updating the package to the latest one.

**Comment by Baertie** [comment]
i am on 6.5.0 and still have the issue
