### ISSUE TITLE
Parameters not displayed for sub class

### ISSUE THREAD

**Issue by LarsSkovK** [domaindrivendev/Swashbuckle.AspNetCore#2598]
When an argument is defined as a sub class Swagger is not displaying the properties that is defined in the type.
Happens after upgrading from 5.6.3 to 6.4

Controller method
```
[HttpPost("getAllData")]
public async Task<ActionResult<IEnumerable<string>>> GetAll(GetData.Query query)
{            
    return Ok();
}
```

Argument type with sub class Query
```
public class GetData
{
    public class Query
    {
        public int MyParameter { get; set; }
    }
    ...
}
```
Swagger UI just shows argument
"string"

If argument type is changed so GetDataQuery is placed outside GetData class
```
public class GetDataQuery
{
    public int MyParameter { get; set; }
}

public class GetData
{
    ...
}
```

Swagger UI shows parameter as expected
{
  "myParameter": 0
}

swagger.json shows myParameter in both cases.

Schema is either
GEPARD.Screening.Application.Features.Subscription.Queries.GetData+Query
or
GEPARD.Screening.Application.Features.Subscription.Queries.GetDataQuery

**Comment by Havunen** [comment]
This seems to work in DotSwashbuckle as expected: 

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/2021355/903b6bd2-46a6-4b61-a186-99dec04e35a3)
