### ISSUE TITLE
"openapi" field in generated yaml depends on OS culture settings

### ISSUE THREAD

**Issue by DK8ALREC** [domaindrivendev/Swashbuckle.AspNetCore#2602]
When I generate OpenAPI yaml spec with Swashbuckle.AspNetCore.Cli the "openapi" field in the generated spec containing the OpenAPI version gets generated differently depending on the culture settings in the OS.

Repro steps:
1. On windows 11 go to "Time & language" > "Language & region" under settings and set "Regional format" to "English (United States)".
2. Generate an OpenAPI spec as yaml with Swashbuckle.AspNetCore.Cli
3. The generated file will look like:
```
openapi: 3.0.1
...
```
4.  Go to "Time & language" > "Language & region" under settings and set "Regional format" to "English (Denmark)".
5. Generate an OpenAPI spec as yaml with Swashbuckle.AspNetCore.Cli
6. The generated file will look like:
```
openapi: '3.0.1'
...
```

This is most likely related to the fact that some cultures use "." as decimal separator while other cultures use ",".

It would be great if the generated spec would be identical regardless of the users culture settings 🙂

**Comment by DK8ALREC** [comment]
It seems like this has been fixed in https://github.com/microsoft/OpenAPI.NET/commit/a389eb6cdae8c250d767eec02b84933209cecc84

[Swashbuckle.AspNetCore.Swagger.csproj](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj) is using version "1.2.3" of "Microsoft.OpenApi", and the above fix was released in version "1.4.4" (latest is "1.6.0").

**Comment by martincostello** [comment]
Tracked by #2606.
