### ISSUE TITLE
Swagger don't understand seperated files

### ISSUE THREAD

**Issue by petrkasnal** [domaindrivendev/Swashbuckle.AspNetCore#2603]
Hello,

i create web api swagger doc with my own open api spec. I have it in seperated files and i use $ref for it. And swagger sometimes don't understand it and i dont know what to do. I use static files

`        app.UseStaticFiles(new StaticFileOptions
        {
            FileProvider = new PhysicalFileProvider(Path.Combine(builder.Environment.ContentRootPath, $"Swaggers/v1")),
            RequestPath = $"/Swagger/v1",
            ServeUnknownFileTypes = true
        });`
        
        
![image](https://user-images.githubusercontent.com/90285874/216631591-e40af102-245a-4f77-a3af-730ccddcffab.png)

![image](https://user-images.githubusercontent.com/90285874/216631730-659a71e6-1ed1-43fb-91f7-79827d179b93.png)

For example for schema its working but for example no. 

`    default:
      description: 'Other codes'
      content:
        application/json:
          schema:
            allOf:
              - $ref: '../BaseSchemas/ApiResult.yml'
          example: 
            $ref: '../BaseExamples/UnexceptedExample.yml'`
            
Thank you for help

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
