### ISSUE TITLE
Add support for models binded through TryParse

### ISSUE THREAD

**Issue by Kairarara** [domaindrivendev/Swashbuckle.AspNetCore#2605]
With ASP.NET Core 7 it's now possible to bind a string to a class by implementing on of the following static methods:
`public static bool TryParse(string value, T out result);`
`public static bool TryParse(string value, IFormatProvider provider, T out result);`

At the moment the generated documentation will treat such classes the same as all others, while the actual value expected by the server will be a string.

**Comment by Havunen** [comment]
Hi, 

Are you referring to IParseable interface? If so then how would the generator know which target type to select for the schema because there could be multiple types supported same time. As well as the object format. 
I think it is better to use Annotation attributes in this case.

**Comment by martincostello** [comment]
This is too open-ended as noted above for us to reliably support. Annotations and providing hints is going to be the more reliable solution here I think, as noted above.
