### ISSUE TITLE
Feature Request: Upgrade To Requiring Microsoft.OpenApi Version 1.6.0

### ISSUE THREAD

**Issue by EmperorArthur** [domaindrivendev/Swashbuckle.AspNetCore#2606]
# Feature Request

Please set the NuGet dependency to at least Microsoft.OpenApi Version 1.6.0.

# Rationale

Until, https://github.com/NuGet/Home/issues/5553 is resolved, bumping the minimum version is the only way to ensure all users have access to new features from dependencies.  The only other way for users to gain access to new features is to install the transitive dependencies, negating all the benefits of PackageReference.

In this case, the largest change with the new version is Microsoft.OpenApi dropped support for .NET Framework.

# Personal Reasons

I am making several calls to `SwaggerGenOptions.SwaggerDoc(...)`, and found that most of `Microsoft.OpenApi.Models.OpenApiInfo` does not change.  Unfortunately, the version Swashbuckle currently relies on (v.12.3) is over two years old, and does not have a copy constructor.  The new version [does](https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi/Models/OpenApiInfo.cs).  This meant I had to either install a transitive dependency, or re-implement library functionality.

**Comment by martincostello** [comment]
Looks like this will resolve #2602.
