### ISSUE TITLE
Swagger UI - 'Accept' header parameter not send correctly in request

### ISSUE THREAD

**Issue by g19d71s9a6nhs-b4eam** [domaindrivendev/Swashbuckle.AspNetCore#2612]
Dear Dev-Team,

I try to create an web api endpoint that returns an image in a format that can be defined in the 'Accept-Header' field of the request. I'm using Swashbuckle NugGet Package (Swashbuckle.AspNetCore, Version 6.5.0) and the UI shows the parameter correctly: see 
![Swashbuckle Header Issue](https://user-images.githubusercontent.com/70902649/219085064-9268b217-24e2-47c3-b6bd-8f71eb7fa9e0.png)
As you can see there too, the curl parameter -H 'accept: text/plain' is wrong and should be 'image/jpeg'.

The openAPI definition is specified with an IOperationFilter that removes Action parameter of a certain type and inserts the Header parameter instead (see code below).
[EaImageFormatFilter.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/10745068/EaImageFormatFilter.txt)

**Comment by martincostello** [comment]
The rendering of the curl section is a SwaggerUI feature.

**Comment by peirens-bart** [comment]
Can this be reopened, I have a similar issue, it seems like the accept header can't be changed. Any other name is working.

```
 <ItemGroup>
   <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11" />
   <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
   <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.2.0" />
 </ItemGroup>
```


```
public class AcceptHeaderOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        operation.Parameters ??= [];

        operation.Parameters.Add(new OpenApiParameter
        {
            Name = HeaderNames.Accept,
            In = ParameterLocation.Header,
            Required = true,
            Schema = new OpenApiSchema
            {
                Type =  "string",
                Enum = [
                    new OpenApiString(MediaTypeNames.Application.Json),
                    new OpenApiString(MediaTypeNames.Text.Html),
                    new OpenApiString("application/linkset+json")
                    ],
                Default = new OpenApiString(MediaTypeNames.Application.Json)
            }
        });
    }
}
```

![image](https://github.com/user-attachments/assets/171e12d0-476f-49d1-b2ea-4b569c016b68)

**Comment by martincostello** [comment]
If your OpenAPI document looks correct, then it's a SwaggerUI constraint and not something we can do anything about.
