### ISSUE TITLE
Swagger UI page is blank

### ISSUE THREAD

**Issue by TehWardy** [domaindrivendev/Swashbuckle.AspNetCore#2616]
Hey guys, 

I've seen this ...
   https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1756

... The suggested fix there didn't solve my problem.
My solution is being built with dotnet 7 so I wondered if this is a new issue to dotnet 7 or something.

My project references ...
```xml
  <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.5.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.5.0" />
        ...
  </ItemGroup>
```

Here's my full setup code ...

```cs
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v7", new OpenApiInfo() { Title = "V7 API", Version = "v7" });
    c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());
    c.AddSecurityDefinition("bearer", new OpenApiSecurityScheme
    {
        Description = @"Authorization header using the Bearer scheme. \r\n\r\n 
        Enter 'Bearer' [space] and then your token in the text input below.
        \r\n\r\nExample: 'bearer 12345abcdef'",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "bearer"
    });


});

var app = builder.Build();

app.UseStaticFiles();
app
    .UseSwagger()
    .UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v7/swagger.json", "V7 API definition");
    });
```

The json doc seems to generate fine but when I go to "swagger/index.html" I get this ...

![image](https://user-images.githubusercontent.com/6891030/223694589-7af906f7-072d-4850-ba96-ba93cd3ee84d.png)

I'm assuming i've missed something silly somewhere and that swagger is fine?
Any ideas?

**Comment by hell-racer** [comment]
Hi! Does your web app change `System.Text.Json` default serializer settings (specifically `DefaultIgnoreCondition` and/or `WriteIndented`)?

**Comment by snakarmi** [comment]
@TehWardy,

Did you ever fixed the issue. I have the same issue.

Thanks.
Sarendra

**Comment by peeveen** [comment]
I found that if you have routes in your service like this:

```
app.MapGet("/{param1}/{param2}", () => { ... do stuff ... });
```

... then the Swagger requests (e.g. `/swagger/swagger-ui.css` etc) will map to these endpoints, breaking the Swagger UI.

You can get around this by adding a "static" part to the route:

```
app.MapGet("/myservicename/{param1}/{param2}", () => { ... do stuff ... });
```

or if you really need to use the first URL pattern, perhaps add a regex to match everything except "swagger":

```
app.MapGet("/{param1:regex(^(?!swagger$).*$)}/{param2}", () => "Hello World!");
```

or if you want to keep it so that "swagger" could be a valid parameter during production:

```
var swaggerMatcher = app.Environment.IsDevelopment() ? ":regex(^(?!swagger$).*$)" : string.Empty;
app.MapGet($"/{{param1{swaggerMatcher}}}/{{param2}}", () => "Hello World!");
```

**Comment by burnchar** [comment]
> You can get around this by adding a "static" part to the route:

I will never know how much time and hair this saved me. Thank you for taking the time to post and help the community.

**Comment by TehWardy** [comment]
Hi All, 

It's been a while I totally forgot about this ticket ... but if I recall the problem was order of events.
You have to add the MVC stuff before you make the swagger calls.

I think there's some oddities around certain middleware.
It's gotten to be a bit of a maze for me because of all the different features I use from the aspnetcore toolchain plus the stuff i've built on top of it.
