### ISSUE TITLE
Downloading file from Swagger-UI removes BOM preamble

### ISSUE THREAD

**Issue by MatrixRonny** [domaindrivendev/Swashbuckle.AspNetCore#2617]
I don't know if this is a Swashbuckle or Swagger-UI problem. I decided to create the issue here since it is the top most layer.

### Bug context:
 - OS: Windows 10 Business - 20H2
 - Browser Version: Firefox 110.0.1 / Edge 110.0.1587.69
 - Method of installation: NuGet / C#
 - Swagger-UI version: 4.10.3 (Swashbuckle.AspNetCore 6.2.3)
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Configuration:
`builder.Services.AddSwaggerGen();`

### Problem description:
API returning file works if called directly, but not when using Swagger-UI. The problem consists of Swagger-UI removing BOM bytes.
https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-with-bom

### Code context (C#):
``` C#
[HttpGet]
public IActionResult GetResult()
{
    MemoryStream memStream = new MemoryStream();
    memStream.Write(Encoding.UTF8.GetPreamble());  //UTF-8 BOM
    memStream.Write(Encoding.UTF8.GetBytes("Bună!"));
    memStream.Seek(0, SeekOrigin.Begin);

    return File(memStream, "text/csv", "file.csv");
}
```

### Actual result:
Downloads a file named "file.csv" with UTF-8 encoding containing "Bună!". This is displayed in Excel as "BunÄƒ!".

### Expected result:
To download a file named "file.csv" with UTF-8 BOM encoding containing "Bună!". This is properly displayed in Excel as "Bună!".

### Note:
If API is called directly, the downloaded file has appropriate encoding and contains the BOM preamble.

**Comment by martincostello** [comment]
Looks like this would be an issue with SwaggerUI to me.
