### ISSUE TITLE
SwaggerSchemaAttribute Title and Description have no effect

### ISSUE THREAD

**Issue by kodeo** [domaindrivendev/Swashbuckle.AspNetCore#2620]
I'm using Swashbuckle.AspNetCore 6.5.0 with Swashbuckle.AspNetCore.Annotations 6.5.0 and have added a SwaggerSchemaAttribute to a response class thus:

    [SwaggerSchema(Title = "MyTitle", Description = "MyDescription")]
    public class MyResponse
    {
        public string Id { get; set; }
    }
 
The project docs say I can use this to "to enrich the corresponding Schema metadata that's generated by Swashbuckle", but the generated swagger.json doesn't contain "MyTitle" or "MyDescription" at all, only:

      "MyResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }

**Comment by captainsafia** [comment]
@kodeo Have you verified that you have support for annotations enabled in your Swagger generator options ?

```csharp
builder.Services.AddSwaggerGen(c => c.EnableAnnotations());
```

**Comment by kreditkenny** [comment]
@captainsafia this worked for me! thank you!
