### ISSUE TITLE
Incorrect schema generation for IFormFile parameters in Minimal API projects when using WithOpenApi extension method

### ISSUE THREAD

**Issue by marcominerva** [domaindrivendev/Swashbuckle.AspNetCore#2625]
I'm using .NET 7.0.4 and Swashbuckle.AspNetCore 6.5.0.

Consider the following endpoints:

    app.MapPost("/api/upload", (IFormFile file) =>
    {
        return TypedResults.Ok(file.FileName);
    });
    
    app.MapPost("/api/upload_with_openapi", (IFormFile file) =>
    {
        return TypedResults.Ok(file.FileName);
    })
    .WithOpenApi();

The first one generates the following schema:

    schema": {
      "required": [
        "file"
      ],
      "type": "object",
      "properties": {
        "file": {
          "type": "string",
          "format": "binary"
        }
      }
    },

While the second, using `WithOpenApi`, produces this:

    "schema": {
      "type": "string",
      "format": "binary"
    },

This causes an exception when calling the `/api/upload_with_openapi` endpoint:

```
Microsoft.AspNetCore.Http.BadHttpRequestException: Required parameter "IFormFile file" was not provided from form file.
       at lambda_method3(Closure, Object, HttpContext, Object)
       at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass92_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
    --- End of stack trace from previous location ---
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
       at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
       at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

You can find a minimal repro here: https://github.com/marcominerva/FileUploadIssue

_Original issue posted at https://github.com/dotnet/aspnetcore/issues/47526_

**Comment by marcominerva** [comment]
I have published the **MinimalHelpers.OpenApi** library to solve this issue (and others similar). Take a look at https://github.com/marcominerva/MinimalHelpers#minimalhelpersopenapi.

**Comment by artl93** [comment]
I'm hitting this too.

**Comment by mr-davidc** [comment]
I am also running into this issue..

**Comment by thepwrtank18** [comment]
Still an issue.

**Comment by Havunen** [comment]
Fixed in DotSwashbuckle

**Comment by jgarciadelanoceda** [comment]
I am starting to implement this issue in Swasbuckle

**Comment by jgarciadelanoceda** [comment]
@marcominerva can you please test if your library does not conflict with this change?
Just in case, I showed that it has 30K downloads so there could be an impact

**Comment by marcominerva** [comment]
@martincostello, @jgarciadelanoceda I see a different (and I think incorrect) `swagger.json` that is generated using **Swashbuckle 6.7.0-preview.545**:

```json
{
    "openapi": "3.0.1",
    "info": {
        "title": "WebApplication4",
        "version": "1.0"
    },
    "paths": {
        "/upload": {
            "post": {
                "tags": [
                    "WebApplication4"
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "components": {}
}
```

This leads to the following UI and the corresponding error if I click **Execute** without selecting a file (note that I have Nullable Reference Types enabled):

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/3522534/38abdb7f-0412-4750-b266-bf0da5ade728)

If, instead, I revert to **Swashbuckle 6.6.2** and use my library, I get the following `swagger.json`:

```json
{
    "openapi": "3.0.1",
    "info": {
        "title": "WebApplication4",
        "version": "1.0"
    },
    "paths": {
        "/upload": {
            "post": {
                "tags": [
                    "WebApplication4"
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "file"
                                ],
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            },
                            "encoding": {
                                "file": {
                                    "style": "form"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "components": {}
}
```

In particular, you can see this (I have extracted just the different parts):

```json
"multipart/form-data": {
    "schema": {
        "required": [
            "file"
        ],
        // ...
    },
    "encoding": {
        "file": {
            "style": "form"
       // ...
```

With this declaration, I get the following UI:

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/3522534/9d19d7c3-d2ef-4737-b571-f29b1e628b85)

In which I cannot send an empty value, as expected.

**Comment by jgarciadelanoceda** [comment]
@marcominerva, I do not know what the encoding part does do you know about it?

**Comment by jgarciadelanoceda** [comment]
@marcominerva, I do not know what the encoding part does do you know about it?

**Comment by marcominerva** [comment]
The `encoding` section is used to describe how fields in the request are encoded when there is a multipart content like `multipart/form-data`. In this case, it means that the `file` field must be encoded using the `form` style (i.e., it is sent as `FromForm`) .

In other words, the `encoding` parameter specifies that the file must be sent using the encoding of HTML forms, that is the standard way to upload file s.

**Comment by marcominerva** [comment]
Hi @jgarciadelanoceda @martincostello, I can confirm that now the `swagger.json` is generated correctly. 

Moreover, I have verified and there isn't conflicts with my library. In any case, as soon as **Swashbuckle 6.7.0** is published, I will update **MinimalHelpers.OpenApi** to reference the new version and I will transform the `AddFormFile` method as No-op with a warning saying that is no longer necessary.

**Comment by jgarciadelanoceda** [comment]
I hope that with the addition of #2980 the library will no longer be needed :)
