### ISSUE TITLE
Mismatch behavior between RegexRouteConstraint and produced OpenApi document

### ISSUE THREAD

**Issue by StasPerekrestov** [domaindrivendev/Swashbuckle.AspNetCore#2626]
When a regex-based constraint is defined,
for instance
```c#
endpoints.MapGet("/{username:alpha}", async (string username, CancellationToken cancellationToken) =>
{
```
AlphaRouteConstraint is applied. The constraint inherits RegexRouteConstraint which is case insensitive.
The issue is that `RegexRouteConstraint.Constraint & RegexOptions.IgnoreCase` isn't taken into account.

```json
"users/{username}": {
      "get": {
        "tags": [
          "demo"
        ],
        "parameters": [
          {
            "name": "username",
            "in": "path",
            "required": true,
            "schema": {
              "pattern": "^[a-z]*$",
              "type": "string"
            }
          }
        ],
```
In a nutshell,
the behavior of `^[a-z]*$` is different in the OpenApi document and in AlphaRouteConstraint because the first one is case sensitive and the other one is case insensitive.

```c#
public class AlphaRouteConstraint : RegexRouteConstraint
{
    /// <summary>
    /// Initializes a new instance of the <see cref="AlphaRouteConstraint" /> class.
    /// </summary>
    public AlphaRouteConstraint() : base(@"^[a-z]*$") <--------------------
    {
    }
}
```

This behavior can be observed in Swagger UI when it doesn't allow to execute an HTTP request due to a failed validation:
For instance, "Jack" cannot pass the provided regex constraint.

https://swagger.io/docs/specification/data-models/data-types/
_The pattern keyword lets you define a regular expression template for the string value. Only the values that match this template will be accepted. The regular expression syntax used is from JavaScript (more specifically, [ECMA 262](https://www.ecma-international.org/ecma-262/5.1/#sec-15.10.1)). Regular expressions are case-sensitive, that is, [a-z] and [A-Z] are different expressions._

**Comment by Havunen** [comment]
This seems to work in DotSwashbuckle

**Comment by jgarciadelanoceda** [comment]
@StasPerekrestov or @SDOsmany. I have just tested using MyGet nuget and it seems to be working.
Can you please specify which version of Swashbuckle are you using?

**Comment by StasPerekrestov** [comment]
@jgarciadelanoceda 
I've checked the asp.net core code and found out that the issue is fixed in .NET 8
[.NET 6](https://github.com/dotnet/aspnetcore/blob/v6.0.31/src/Http/Routing/src/Constraints/AlphaRouteConstraint.cs)
[.NET 7](https://github.com/dotnet/aspnetcore/blob/v7.0.20/src/Http/Routing/src/Constraints/AlphaRouteConstraint.cs)
[.NET 8](https://github.com/dotnet/aspnetcore/blob/v8.0.6/src/Http/Routing/src/Constraints/AlphaRouteConstraint.cs)

I suppose the issue can be closed.
Thank you for looking into it.
