### ISSUE TITLE
OpenApiFloat is formatted with local culture decimal separator

### ISSUE THREAD

**Issue by Palpie** [domaindrivendev/Swashbuckle.AspNetCore#2627]
I'm using IncludeXmlComments in version 6.5.0. I have this comment:

![image](https://user-images.githubusercontent.com/6249536/230046682-8de219b4-4edb-47d5-bb58-8554a53dd05b.png)

Which looks liks this in the XML:

![image](https://user-images.githubusercontent.com/6249536/230047037-c96dcba3-dff1-4f4f-b2c4-7108273fb6a4.png)

And like this in the OpenApiExample:

![image](https://user-images.githubusercontent.com/6249536/230047184-22f05743-17c6-4949-80b5-7738938eefdc.png)

But in swagger.json it gets the wrong decimal separator:

![image](https://user-images.githubusercontent.com/6249536/230047634-e0967c31-e092-497a-afb2-3909c771f1d0.png)

My best guess is that it uses my local culture (sv-SE) to format the float, but it should always be a `.`.

**Comment by fradzano** [comment]
i faced the same issue while generating the openapi.json during `PostBuild` events and was able to work around it by forcing invariant culture through the `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` environment variable.

```
<Target Name="OpenApiGeneration" AfterTargets="PostBuildEvent">
  <Exec Command="dotnet tool restore" />
  <Exec EnvironmentVariables="ASPNETCORE_ENVIRONMENT=local;DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1" Command="dotnet tool run swagger tofile --output openapi.json --serializeasv2 $(OutputPath)$(AssemblyName).dll v1" />
</Target>
```

**Comment by Palpie** [comment]
`DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` worked. Thanks!

**Comment by woeterman94** [comment]
Any way to solve this in code? Rather than having to restore our entire solution on build?

**Comment by ferenc-a** [comment]
Could this issue be reopened?
I'm glad there's a workaround, but it shouldn't generate broken JSON by default.

Something similar was raised earlier: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1367
(And it was supposedly fixed.)
