### ISSUE TITLE
Nullable enum does not populate nullable

### ISSUE THREAD

**Issue by fairking** [domaindrivendev/Swashbuckle.AspNetCore#2633]
The following class:
``` c#
public class BookingQueryForm
{
    public BookingStatusEnum? Status { get; set; }
}
```

populates the following schema:
``` json
"BookingQueryForm": {
        "required": [
        ],
        "type": "object",
        "properties": {
          "status": {
            "$ref": "#/components/schemas/BookingStatusEnum"
          }
        },
        "additionalProperties": false
      },
      "BookingStatusEnum": {
        "enum": [
          "Booked",
          "Waiting",
          "Cancelled"
        ],
        "type": "string"
      },
```

Please note that the `status` property is not nullable while it should be:
``` json
 "properties": {
          "status": {
            "$ref": "#/components/schemas/BookingStatusEnum",
            "nullable": true
          }
        },
```

Related issue: https://github.com/RicoSuter/NSwag/issues/4397

**Comment by kjkrum** [comment]
I noticed this while digging into a different problem with enum properties. It *may* have something to do with how enum nullability is defined in the OpenAPI spec. In languages like C#, nullability is a property of the reference. In OpenAPI, nullability of an enum is a matter of `null` being a *member* of the enum. You can use an `ISchemaFilter` to set `Nullable` and add `OpenApiNull` to the `Enum` property of enum schemas. I tried this and it didn't solve my other problem, but I haven't tried generating an NSwag client against the resulting schema.

**Comment by martincostello** [comment]
To make issue tracking a bit less overwhelming for the new maintainers (see #2778), I've created a new tracking issue to roll-up various nullability issues here: #2793.

We'll refer back to this issue from there and include it as part of resolving that issue, but I'm going to close this one to help prune the backlog.
