### ISSUE TITLE
Generating format attribute for definition schemas

### ISSUE THREAD

**Issue by karygauss03** [domaindrivendev/Swashbuckle.AspNetCore#2634]
I am facing an issue while trying to add a format attribute to each definition schema in my code using Swagger using Swashbuckle annotation `[SwaggerSchema(Format = nameof(...))]`. The value of the format attribute should be the name of the schema itself. Here's what I have tried:

```
[SwaggerSchema(Format = nameof(User))]
public class User {
// implementation
}
```
This works fine and results in the following schema output:
```
"User": {
  "format": "User",
  "type": "object",
  ...
}
```
However, I encountered a problem when working with classes that have generic parameters, such as `ResponseList<T>` which represents a list of response type. With the previous implementation, all schemas of `ResponseList<...>` have the same format name, which is "ResponseList", as shown below:
```
"ResponseList<User>: {
  "format": "ResponseList",
  ...
}

"ResponseList<Product>: {
  "format": "ResponseList",
  ...
}
```

But my desired goal is to have schemas like this:

````
"ResponseList<User>: {
  "format": "ResponseListUser",
  ...
}

"ResponseList<Product>: {
  "format": "ResponseListProduct",
  ...
}
```
Is there any way to achieve this? Any help would be appreciated.

**Comment by jgarciadelanoceda** [comment]
You can achieve it with constant interpolated strings $"{nameOf(class)}{nameof(otherclass)}.
If you specify a OperationFilter you can also do it automatically though I do not know the real purpose of the format property in the OpenApi spec
