### ISSUE TITLE
API Key Header not sent from SwaggerUI to API

### ISSUE THREAD

**Issue by Montago** [domaindrivendev/Swashbuckle.AspNetCore#2636]
I've added the SecurityDefinition as well as SecurityRequirements as described here : https://stackoverflow.com/questions/57227912/swaggerui-not-adding-apikey-to-header-with-swashbuckle-5-x

```
services.AddSwaggerGen(c =>
			{
				c.AddSecurityDefinition("Api Key in Header", new OpenApiSecurityScheme()
				{
					Name = "x-api-key",
					In = ParameterLocation.Header,
					Type = SecuritySchemeType.ApiKey,
					Description = "Authorization by x-api-key inside request's header",
				});

				var key = new OpenApiSecurityScheme()
				{
					Reference = new OpenApiReference
					{
						Type = ReferenceType.SecurityScheme,
						Id = "x-api-key"
					},
					In = ParameterLocation.Header,
					Type = SecuritySchemeType.ApiKey
				};
				
				var requirement = new OpenApiSecurityRequirement
				{
				   { key, new List<string>() }
				};

				c.AddSecurityRequirement(requirement);
			});
```

which result in the Authorize option pops up in UI:
![image](https://user-images.githubusercontent.com/456040/233617759-99cc93a3-2cb6-4750-a480-1e3997f5ee8a.png)

![image](https://user-images.githubusercontent.com/456040/233617810-195fa58a-0679-4e2f-9024-bb27fb6db4e2.png)

**However** The API Key isn't sent from SwaggerUI to the Endpoint: 
![image](https://user-images.githubusercontent.com/456040/233617983-9510a051-ec1f-4bcf-aef3-6321a06612d9.png)

The header is missing 

This is also the case if i inspect the Request.Headers object in the backend. 

Am i missing something ?

**Comment by Havunen** [comment]
Hi @Montago 

here is working configuration ( I tested it using it DotSwashbuckle but it should work in Swashbuckle too ):

```cs
  c.AddSecurityDefinition("ApiKeyHeader", new OpenApiSecurityScheme()
  {
      Name = "x-api-key",
      In = ParameterLocation.Header,
      Type = SecuritySchemeType.ApiKey,
      Description = "Authorization by x-api-key inside request's header",
  });
  c.AddSecurityRequirement(new OpenApiSecurityRequirement{
      {
          new OpenApiSecurityScheme
          {
              Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "ApiKeyHeader" }
          },
          new string[] {}
      }
  });
```
The security definition needs to be associated with the security requirement

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/2021355/dff82c3f-03c5-413a-9ad8-c5b183a0aaa1)

**Comment by 2br-2b** [comment]
Any chance we could get an updated version of this code? In the most recent version, there's an error that Reference isn't defined

**Comment by ghost** [comment]
This is working for me @2br-2b 
```
 c.AddSecurityDefinition("ApiKeyHeader", new OpenApiSecurityScheme
 {
     Description = "API Key needed to access the endpoints. X-API-Key: {your-api-key}",
     In = ParameterLocation.Header,
     Name = "X-API-Key",
     Type = SecuritySchemeType.ApiKey
 });

 c.AddSecurityRequirement(doc => new OpenApiSecurityRequirement
 {
     { new OpenApiSecuritySchemeReference("ApiKeyHeader", doc), [] },
 });
```
