### ISSUE TITLE
Swagger Authorization using IdentityServer returns Invalid redirect_uri

### ISSUE THREAD

**Issue by LPiotr** [domaindrivendev/Swashbuckle.AspNetCore#2638]
Hi!
I want to raise vulnerability issue connected to using redirections in Swagger. It is connected to security issue described here:
https://owasp.org/Top10/A01_2021-Broken_Access_Control/

here it is conceivable way to resolve:
https://stackoverflow.com/questions/54242118/swagger-ui-authorization-using-identityserver4-returns-invalid-redirect-uri

Also, Contrast is giving medium warning with this on project:
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__5.MoveNext()

**Comment by martincostello** [comment]
Duplicate of #2721
