### ISSUE TITLE
Aligning your net and netstandard version by downgrading netstandard to 1.2

### ISSUE THREAD

**Issue by klettier** [domaindrivendev/Swashbuckle.AspNetCore#264]
Hello,

You are providing both  **net451** and **netstandard1.6** lib for Swashbuckle but **netstandard** version aligned with **.NET Framework 4.5.1** is the **1.2**

By aligning your versions more people and projects will be able to use your lib.

Thanks

**Comment by domaindrivendev** [comment]
Swashbuckle depends on Microsoft.AspNetCore.Mvc.Core which in turn supports netstandard1.6 and above. So, SB simply won't work on anything below 1.6.
