### ISSUE TITLE
not consistent paths in IDocumentFilter

### ISSUE THREAD

**Issue by CzBuCHi** [domaindrivendev/Swashbuckle.AspNetCore#2645]
i have declared this single mapping: `app.MapPost("/User/Update/{userId:int}", (int userId) => Results.Ok());`

now in document filter class:
```
class Filter : IDocumentFilter {
    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context) {
        var description in context.ApiDescriptions.First();

        var path = description.RelativePath;
        var key = swaggerDoc.Paths.Keys.First();

    }
}
```
- `path` variable will be resolved as `/User/Update/{userId:int}`
- `key` variable as `/User/Update/{userId}`

so i cannot simply compare these two and need to do regex magic to get rid of `:int` part from `path` ...

**Comment by Havunen** [comment]
Yes this is expected behavior because `swaggerDoc.Paths` will be actual Url path and description.relativePath is the API explorer template URI.
