### ISSUE TITLE
SwaggerCLI output not the same as SwaggerUI

### ISSUE THREAD

**Issue by talmroth** [domaindrivendev/Swashbuckle.AspNetCore#2646]
For the application I'm working on we wanted to auto build the swagger.json so it can be used for Azure APIM.  From the web UI if we download the swagger.json it looks like we want.  But when use the the CLI the output that is generated is not the same, it's using fully qualified names in tags and for the open api title.  Our swagger setup is built into a framework but it should behave the same regardless of host so I am not sure why the output would be different.

This is on version 6.3.  I tried moving up to 6.5 but for some reason we are getting an error "Could not load file or assembly 'System.Runtime, Version=7.0.0.0" on systems with .net7 installed.  The application in question is .net6.0

**Comment by talmroth** [comment]
I know there is another issue opened for the 7.0.0.0 issue.  We added a global.json and that seemed to fix the problem but after a recent local update that issue has returned.

**Comment by Havunen** [comment]
Have you tested with DotSwashbuckle it is for .Net8 only but it shouldnt have any difference between the generated schemas from CLI or web api

**Comment by martincostello** [comment]
I'm going to close this in favour of #2792, as going through triaging the open issues I'm spotting a common theme and it's easier to manage one issue. Please track that issue for further updates.

If this issue isn't resolved once we have added support for `net8.0`, please open a new issue.
