### ISSUE TITLE
GeneratePolymorphicSchemas to exclude abstract types

### ISSUE THREAD

**Issue by SimonSimCity** [domaindrivendev/Swashbuckle.AspNetCore#2648]
I'm not all to familiar with using this plugin, but as of what I discovered, the "GeneratePolymorphicSchemas" feature includes abstract classes, which IMO should not be in a `oneOf` list in my generated swagger file.

E.g. when I have the following classes:
```C#
abstract class IDocument {}
abstract class IDocumentWithYear : IDocument {}
class Album : IDocument {}
class Track : IDocumentWithYear {}
```

When generating a swagger, it will include `IDocumentWithYear` in the list of `oneOf` for a type `IDocument` even though its abstract and can never directly be a type.

Hope this was short enough but understandable 😅

**Comment by SimonSimCity** [comment]
Fixed it now for my project by adding ` && !type.IsAbstract` to the default subtype selector found here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGeneratorOptions.cs#L55-L58

My code:

```C#
c.SelectSubTypesUsing(baseType =>
{
    return baseType.Assembly.GetTypes().Where(type => type.IsSubclassOf(baseType) && !type.IsAbstract);
});
```

Would be nice to have a re-evaluation if abstract types should be allowed by default.

**Comment by Havunen** [comment]
Can you explain why this is an issue? Those JSON schemas are not meant to be used as is, but as reference to build concrete schema for a given path

**Comment by lhargil** [comment]
> Fixed it now for my project by adding ` && !type.IsAbstract` to the default subtype selector found here:
> 
> [Swashbuckle.AspNetCore/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGeneratorOptions.cs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGeneratorOptions.cs#L55-L58)
> 
> Lines 55 to 58 in [8f363f7](/domaindrivendev/Swashbuckle.AspNetCore/commit/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3)
> 
>  private IEnumerable<Type> DefaultSubTypesSelector(Type baseType) 
>  { 
>      return baseType.Assembly.GetTypes().Where(type => type.IsSubclassOf(baseType)); 
>  } 
> My code:
> 
> c.SelectSubTypesUsing(baseType =>
> {
>     return baseType.Assembly.GetTypes().Where(type => type.IsSubclassOf(baseType) && !type.IsAbstract);
> });
> Would be nice to have a re-evaluation if abstract types should be allowed by default.

I'm aware that this is closed and not planned. Want to say thanks, this workaround fixed it for our use case too.
