### ISSUE TITLE
[BUG?] UseSwaggerUI bug when working with different environments

### ISSUE THREAD

**Issue by ghost** [domaindrivendev/Swashbuckle.AspNetCore#2649]
Hello,

I am building a .NET 6 WEB API which I hosted on IIS.
I am hosting the API in base site, not in a subdirectory.

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/5992169/58c969f6-645c-490f-8b1b-70d049d71af1)

Now, here's what's interesting:

**line 68:**

IF I set options.RoutePrefix to "routePrefix" variable, I see in logs that options.RoutePrefix is empty in Test environment, BUT when I open the base address, it redirects to index.html and gives me a 404 error.

IF I set options.RoutePrefix to "string.Empty" (ignoring the IF clause in lines 59-62), I see in logs that options.RoutePrefix is empty in Test environment, BUT if I open the base address, it redirects to index.html and shows Swagger UI.

It looks to me as if Swagger ignores the dynamically set "routePrefix"?

**Comment by Havunen** [comment]
Can you create a sample application and zip it or upload it to Github and I can then have a look. Also if you are using .Net8 you can test if DotSwashbuckle resolves your issue

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
