### ISSUE TITLE
Doesn't generate summary doc when the controller class has overload methods.

### ISSUE THREAD

**Issue by codelovercc** [domaindrivendev/Swashbuckle.AspNetCore#2655]
Swashbuckle.AspNetCore 6.5.0
.net 7.0

Project.csproj
```
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
```

Controller class:

```csharp
[ApiController]
[Route("api/[controller]")]
public class MyController : MyBaseController<MyModel>
{
    public MyController(MyBuzService service):base(service){}
   
    /// <summary>
    /// Find by single id
    /// </summary>
    /// <param name="id">ID</param>
    /// <returns></returns>
    [HttpGet]
    [Route("Find/{id}")]
   public async Task<IActionResult> Find([FromRoute] string id) => await Find(new[] { id });

    /// <summary>
    /// Find by multi id
    /// </summary>
    /// <param name="id">ID</param>
    /// <returns></returns>
    [HttpPost]
    [Route("Find")]
   public async Task<IActionResult> Find([FromQuery] [FromBody] string[] id)
   {
        return Ok(await Service.GetModelAsync(id));
   }
}

public abstract class MyBaseController<TModel>
{
    private MyBuzService Service;
    public MyController(MyBuzService service)
   {
        Service = service;
   }
   

    /// <summary>
    /// Add some models
    /// </summary>
    /// <param name="models">Models to add</param>
    /// <returns></returns>
   [HttpPost]
    [Route("AddRange")]
   public async Task<IActionResult> AddRange([FromBody] TModel[] models)
   {
       return Ok(await Service.AddRange(models));
   }
}
```

I've checked the generated XML documentation file, it's generated correctly. 
But summary document are missing in the swagger.json.
I've created a class that implements `IOperationFilter` interface, when I'm debugging, I found `OpenApiOperation.Summary` property with value `null`.

update issue:
The method `public async Task<IActionResult> AddRange([FromBody] TModel[] models)`  takes one parameter of TModel[] type which is array type doesn't generate summary doc too!.

**Comment by Naxaliav** [comment]
@codelovercc have you configured to read .xml file? :) 
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/33034058/2f6bff61-519f-4443-88e2-1b32611e9440)

**Comment by codelovercc** [comment]
> @codelovercc have you configured to read .xml file? :) ![image](https://user-images.githubusercontent.com/33034058/241531824-2f6bff61-519f-4443-88e2-1b32611e9440.jpeg)

Hi Naxaliav, 
It's configured.
```csharp
 options.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory,
                $"{typeof(SwaggerExtensions).Assembly.GetName().Name}.xml"));
            var entryAssembly = Assembly.GetEntryAssembly();
            if (entryAssembly != null)
            {
                options.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory,
                    $"{entryAssembly.GetName().Name}.xml"));
            }
```

**Comment by Naxaliav** [comment]
Your find method has 2 http attributes: post and get. There should be only one.

**Comment by codelovercc** [comment]
> Your find method has 2 http attributes: post and get. There should be only one. However I think its just a typo in example :). Why can't you rename the methods to FindById and FindByIds, in that case it would work :)

Hi, [Naxaliav](https://github.com/Naxaliav)
Rename the methods will work, but the overloaded method is a language feature of the C# standard, and I think it is necessary for Swashbuckle.AspNetCore.SwaggerGen to support it.

**Comment by Havunen** [comment]
FYI. This is supported in DotSwashbuckle 
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/2021355/be03705e-1f35-4ead-ae6a-1146aabb20f4)

**Comment by codelovercc** [comment]
@Havunen Thank you for your work.
There still is a problem with overloaded method in this case:

```C#

public abstract class BaseModelController<TKey, TModel> : Controller
{
     /// <summary>
    /// Delete by Id
    /// </summary>
    /// <param name="id">deleting Id</param>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    /// <response code="200">Deleted</response>
    /// <response code="404">Failed</response>
    [HttpDelete($"{nameof(Delete)}/{{{nameof(id)}}}")]
    [ProducesResponseType(typeof(SuccessResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(NotFoundResponse), StatusCodes.Status404NotFound)]
    public virtual async Task<IActionResult> Delete([Required, FromRoute] TKey id, CancellationToken cancellationToken)
    {
        return Ok();
    }
   
    
     /// <summary>
    /// Delete by Ids
    /// </summary>
    /// <param name="id">deleting Ids</param>
    /// <param name="cancellationToken"></param>
    /// <returns></returns>
    /// <response code="200">Deleted</response>
    /// <response code="404">Failed</response>
    [HttpDelete($"{nameof(Delete)}/{{{nameof(id)}}}")]
    [ProducesResponseType(typeof(SuccessResponse<int>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(NotFoundResponse), StatusCodes.Status404NotFound)]
    public virtual async Task<IActionResult> Delete([Required, FromRoute] TKey id, CancellationToken cancellationToken)
    {
        return Ok(new SuccessResponse<int>(10));
    }
 
     /// <summary>
    /// List all of <typeparamref name="TModel" />
    /// </summary>
    public virtual async Task<IActionResult> List()
    {
        return Ok();
    }
}

[ApiController]
[Route("[controller]")]
public ArticleController : BaseModelController<Guid, Article>
{
    
}
```

XML documents file generated will. Method `List` with full documented in swagger, but method `Delete([Required, FromRoute] TKey id, CancellationToken cancellationToken)` and `Delete([Required, FromRoute] TKey id, CancellationToken cancellationToken)` lost all of xml comment docs in swagger.

**Comment by Havunen** [comment]
Thanks, I will check

**Comment by codelovercc** [comment]
> Thanks, I will check

Hi, thanks for you work. The overload methods doc generation may be work well in your fork repo, I recently checked this, `TKey[]` is an array type that cause Swashbuckle can't get the xml summary and remark doc, it's an issue in Swashbuckle.

Let me be clear:
1. Swashbuckle does not generate doc for overload methods. (checked)
2. Swashbuckle does not generate doc if there's any array parameter in controller action method. (checked)
3. DotSwashbuckle will generate doc for overload methods well. (unchecked)

@martincostello Hi, do I need to open an issue about 'Array type parameter in controller action can't generate summary and description doc' ?

**Comment by martincostello** [comment]
This existing issue can track both cases.

**Comment by jgarciadelanoceda** [comment]
I am reviewing this issue :)

**Comment by codelovercc** [comment]
@jgarciadelanoceda 
Sure, I will test it as soon as possible. Thank you for your work :)

**Comment by jgarciadelanoceda** [comment]
You can test it now with 6.7.1 package

**Comment by codelovercc** [comment]
Thank you, this worked!
