### ISSUE TITLE
Add Server default with schema/host

### ISSUE THREAD

**Issue by timheuer** [domaindrivendev/Swashbuckle.AspNetCore#2656]
The swagger.[json|yaml] should emit a `servers` object in the OpenAPI specification using the running server scheme/host by default.  This helps complete the default configuration with little overrides quickly.

It saves from writing the code of `AddServer()` when the default host of the API should be at least one of the servers.  Or give an opt-out way.

**Comment by martincostello** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2663#issuecomment-2053575975
