### ISSUE TITLE
Debug _tofile in Visual Studio

### ISSUE THREAD

**Issue by dpomerantz-jci** [domaindrivendev/Swashbuckle.AspNetCore#2657]
I am running Visual Studio 2022, and working with the latest .NET 6.0 build from the Swashbuckle Repo which was cloned today.  I am trying to step through the code of swashbuckle CLI _tofile, and I am not able to do so.  Adding Debugger.Launch() to that code path does not appear to do anything, and I can't figure out how to run that config with setting the equivalent of depspath and and runtimeconfig in such a way that it can be run that way inside of .Net.  Would I have to change a buildtarget?

How does the team step through this code?  Any help would be appreciated.

(Often I find the answer after finally asking for help, so I apologize in advance if that happens)

Thank you,

dmp

**Comment by Havunen** [comment]
There are multiple ways to do that, for example you could just enable debugger to go to the system types by disabling "just my code" in visual studio and then just debug through. Or you could bring your project into the Swashbuckle repository or vice versa and debug it.
