### ISSUE TITLE
Swagger UI failed to read JSConfig beacause of different cases

### ISSUE THREAD

**Issue by sm-g** [domaindrivendev/Swashbuckle.AspNetCore#266]
I have `"Swashbuckle.AspNetCore": "1.0.0-rc1"`. `/swagger/v1/swagger.json` is generated fine. But `/swagger/index.html` failed, because js in case sensitive and html contains:

    window.JSConfig = JSON.parse('{"swaggerEndpoints":[{"url":"/swagger/v1/swagger.json","description":"API v1"}],"

but later there is

      window.swaggerUi = new SwaggerUi({
        url: JSConfig.SwaggerEndpoints[0].Url,

and more of them, trying to get properties in pascalcase.

I also noticed when there is just `app.UseSwaggerUi)` instead of `app.UseSwaggerUi(x => x.SwaggerEndpoint("/swagger/v1/swagger.json", "API v1"));`, `"swaggerEndpoints":[]` is empty array (but `/swagger/v1/swagger.json` is still generated of course). Docs says it will be default value when there is

    services.AddSwaggerGen(o =>
    {
                o.SwaggerDoc("v1", new Info { Title = "API", Version = "v1" });
    }

**Comment by sandorfr** [comment]
Hi, 

I think this is a [duplicated issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/258) which has been addressed by this [PR](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/259).

I think your code or one of your dependencies is settings some global JsonConvert Serialization settings. Which is as bad as relying on those global settings in terms of practices.

I hope the patched code will be released soon, but meanwhile you should remove `JsonConvert.DefaultSettings` and pass appropriate serialization settings instead when using `Serialize` or `Deserialize`.

**Comment by sm-g** [comment]
Very likely. Do you know when this pr will be on nuget?

**Comment by sandorfr** [comment]
As I'm just an occasional contributor, I have no idea.
