### ISSUE TITLE
Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware fails script injection

### ISSUE THREAD

**Issue by ldeluigi** [domaindrivendev/Swashbuckle.AspNetCore#2664]
## Issue
Whenever the Swagger Ui generated page is loaded, this warning pops out in the logs:
```
warn: Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware[3]
      Unable to configure browser refresh script injection on the response. Consider manually adding '<script src="/_framework/aspnetcore-browser-refresh.js"></script>' to the body of the page.
```

This is related to Visual Studio Debug mode which, in order to support the Hot Reload feature, injects a page refresh script through a middleware.

## Swashbuckle version
```xml
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.5.0" />
```

**Comment by ZedZipDev** [comment]
Did you find any solutions? I have the same issue in VS2022, NET7+Swagger project

**Comment by ldeluigi** [comment]
> Did you find any solutions? I have the same issue in VS2022, NET7+Swagger project

Nope. I'm ignoring the warning.

**Comment by coendewit** [comment]
As the docs suggest: <img width="654" alt="image" src="https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/3438857/8a6ca0f6-141c-4dbc-b88f-db41c373060a">

**Comment by sinanaltaii** [comment]
I am having the same issue. I enabled hot reload in launchSettings.json and ran dotnet watch on my project and I can confirm I am getting the same issue. Not sure if this might help, but, in my case its an optimizely 12 cms project.

**Comment by martincostello** [comment]
I've seen this before on other static pages, and IIRC for when I saw it, it was caused by the use of compression. This is caused by Visual Studio hot reload.
