### ISSUE TITLE
Add a parameter to create the output folder with Swashbuckle.AspNetCore.Cli

### ISSUE THREAD

**Issue by mcraiha** [domaindrivendev/Swashbuckle.AspNetCore#2667]
When Swashbuckle.AspNetCore.Cli is used, it will fail if the output folder does not exist (e.g. tofile is **$(Build.ArtifactStagingDirectory)/documents/api.yaml** and we currently only have **$(Build.ArtifactStagingDirectory)**). It would nice to have a parameter that allows to create the full path if it does not yet exist (like **-p** with **mkdir**).

**Comment by Havunen** [comment]
The con is that if the path is incorrect, which often happens with relative paths, then it creates that folder and puts the data into some weird folder location, I dont see this as important feature as it can be achieved with single liner terminal /cmd command

**Comment by martincostello** [comment]
If we did anything here, I think it would be better to not have an option but just have the code do it:

```csharp
var directoryName = Path.GetDirectoryName(fileName);
if (!Directory.Exists(directoryName))
{
    Directory.Create(directoryName);
}
```

The above wouldn't handle recursive creation of subdirectories, but it would help.

**Comment by martincostello** [comment]
Duplicate of #2352
