### ISSUE TITLE
SwaggerResponseAttributeFilter overwrites Description, even if it is not set in the SwaggerResponseAttribute

### ISSUE THREAD

**Issue by michael-x** [domaindrivendev/Swashbuckle.AspNetCore#267]
I don't want to re-open the discussion on whether using the `ProducesResponseTypeAttribute`, the `SwaggerResponseAttribute` or the extended XML comment `response` element is best practice. I just noticed some strange behaviour.

When putting a description into the XML comment `response` e.g. for a code 204, the `SwaggerResponseAttributeFilter` will remove the description, even if `SwaggerResponseAttribute.Description` is not set. For the `SwaggerResponseAttribute.Type` it does check, whether it is set and only overwrites the Schema, if it is.

Even without an XML comment it will remove the default description and it would probably also remove the description for any other filter that is applied before the `SwaggerResponseAttributeFilter`.

I know that without the `Description` I could also use the `ProducesResponseTypeAttribute`, and that is what I'm doing now, but other folks might get the same problem. I'm also using the `SwaggerOperationAttribute` to assign an `OperationId` to my operations and it seems to be more consistent to then also use the `SwaggerResponseAttribute` instead of the `ProducesResponseTypeAttribute`, especially since one derives from the other.

**Comment by domaindrivendev** [comment]
Fixed with 358b83feb2693a71f6fc7e48699d7698e7db7d5a
