### ISSUE TITLE
requesting AllowAnonymous api does not carry Authorization header

### ISSUE THREAD

**Issue by ShadowNearby** [domaindrivendev/Swashbuckle.AspNetCore#2678]
some requests to api that allows allow anoymous still need Authorization header to distinguish the anoymous user and the authorized user

**Comment by Havunen** [comment]
Can you provide more details what is the issue you are facing and what is the expected result? Are you referring to schema generation or something else, swagger ui ?

**Comment by ShadowNearby** [comment]
Thanks for your reply!
When I'm using Swagger UI for interface testing, some interfaces don't necessarily require an Authorization header; they allow anonymous users. However, if an Authorization header is provided, personalized services are provided based on the user information obtained from the Authorization. I should configure it to allow anonymous users, but doing so means I won't receive the information from the Authorization header. Therefore, I'm wondering if it's possible to include the Authorization header in the request when the interface allows anonymous users.

**Comment by Havunen** [comment]
This sounds like swagger - UI question. Maybe better to request a feature there. https://github.com/swagger-api/swagger-ui/issues

**Comment by ShadowNearby** [comment]
Fine, thanks again.

**Comment by Havunen** [comment]
@ShadowNearby 
I encountered similar issue recently where authorization header security restrictions were incorrectly defined, maybe this can help you: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2636
