### ISSUE TITLE
Swagger UI fails when using multiple [FromRoute] parameters in GET route

### ISSUE THREAD

**Issue by osleyhc** [domaindrivendev/Swashbuckle.AspNetCore#2684]
I am using the following packages in my ASP.NET Core project:

Swashbuckle.AspNetCore version 6.5.0
Swashbuckle.AspNetCore.Annotations version 6.5.0
Swashbuckle.AspNetCore.Newtonsoft version 6.5.0
When I define a GET route without a resourceName and with more than one parameter, Swagger UI fails to display the route correctly. The issue occurs when I use a simple route template like [HttpGet("{id}/{name}", Name = "Get")], and Swagger UI fails to generate the correct documentation for the route.
error of type https://tools.ietf.org/html/rfc7231#section-6.5.1 
   The 400 (Bad Request) status code indicates that the server cannot or
   will not process the request due to something that is perceived to be
   a client error (e.g., malformed request syntax, invalid request
   message framing, or deceptive request routing).

Expected Behavior:
I expect the Swagger UI to correctly display the GET route with multiple parameters and generate the appropriate documentation for the route.

Additional Information:

I have checked my Swagger configuration and have followed the recommended setup for Swashbuckle.
The issue occurs only when using multiple parameters in the route template. When I use a route with only one parameter (e.g., [HttpGet("{id}", Name = "Get")]), Swagger UI works fine. Or when I use [HttpGet("resourceName/{id}/{name}", Name = "Get")] it also works like a charm.

It also fails if I used this way: 
[Route("{id}/{name}")]
[HttpGet(Name = "Get")]
public async Task<IActionResult> Get([FromRoute] int id, [FromRoute] string name) => Ok();
I have tried restarting the application, but the issue persists.

Environment:
.NET Core version: [e.g., 6.0.0]
ASP.NET Core version: [e.g., 6.0.0]

**Comment by Havunen** [comment]
I am not sure if we want to do anything for this, because one would need to check which routes are actually callable by the .NET API if you define the route that way. Instead, you should define the route using HttpGet or HttpPost etc.

working example:
```cs
[HttpGet("{id}/{name}", Name = "FromRouteTwice")]
public async Task Get([FromRoute] int id, [FromRoute] string name) => Ok();
```

This adds one route with http method GET and path "id/name" 



```
[Route("{id}/{name}")] <-- adds one route? 
[HttpGet(Name = "Get")] <-- adds another route ?
public async Task Get([FromRoute] int id, [FromRoute] string name) => Ok();
```
