### ISSUE TITLE
JsonRequired property from STJ not marked as required in generated OpenApi Schema

### ISSUE THREAD

**Issue by aygalinc** [domaindrivendev/Swashbuckle.AspNetCore#2686]
Hello,

I try to use swashbuckle in one of my project and I notice when I mark some property with property: JsonRequired in my record, the corresponding specification does not marke the property as required. Is this the expected behavior or a bug ? 

A reproducer : 

public sealed record OrganizationCustomExchangeRatesDto(
    [property: JsonRequired] TemporalHeaderDto ColumnDates,
   [property: JsonRequired] FrequencyDto Frequency,
    [property: JsonRequired] List<OrganizationCurrencyPairRowDto> CurrenciesRates
);

Generates : 

"OrganizationCustomExchangeRatesDto": {
        "type": "object",
        "properties": {
          "columnDates": {
            "$ref": "#/components/schemas/TemporalHeaderDto"
          },
          "frequency": {
            "$ref": "#/components/schemas/FrequencyDto"
          },
          "currenciesRates": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/OrganizationCurrencyPairRowDto"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      },

CurrenciesRates is also mark as nullable despite of my Json required annotation.

**Comment by Havunen** [comment]
This will be fixed in DotSwashbuckle 3.0.3+
https://github.com/Havunen/DotSwashbuckle
https://www.nuget.org/packages/DotSwashbuckle.AspNetCore
