### ISSUE TITLE
how to "skip" exceptions using Swashbuckle.AspNetCore.CLI

### ISSUE THREAD

**Issue by Nothing-Works** [domaindrivendev/Swashbuckle.AspNetCore#2689]
I am using `dotnet swagger tofile --output [output] [startupassembly] [swaggerdoc]` this command to generate swagger docs, and it works fine locally.

But when it's in the CI/CD, as far as I know, it needs to start the app, but the app will not start in CI/CD due to some dependencies problems. So the app will throw exceptions inside `Program.Main` when it's run on CI/CD.

my question is, what's the recommended solution there? is there a way to skip exceptions? or even do not start the app? or should I configure what dependency to load in `Main`?

  [1]: https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by vdekercd** [comment]
Hi @Nothing-Works,

You don't need to start the app. You just need to build it,

**Comment by Nothing-Works** [comment]
@vdekercd I do not want to start the app either, but the cli tool starts the apps under the hood.

**Comment by vdekercd** [comment]
@Nothing-Works 
My bad, you've right! :)

**Comment by Baertie** [comment]
I have the same issue!

**Comment by Havunen** [comment]
This might be fixed in DotSwashbuckle, can you test using it please.
https://github.com/Havunen/DotSwashbuckle
https://www.nuget.org/packages/DotSwashbuckle.AspNetCore
