### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by mschatt** [domaindrivendev/Swashbuckle.AspNetCore#2691]
Hello
We use the latest Version 6.5.0

While scanning our solution, we found a security issue, the package has a dependency on System.Text.Regularexpressions.4.3.0 which has a security issue:
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/106265156/a60f4f04-3529-4f8f-9df5-9c2dc77605e9)
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/106265156/07ef9710-5a16-4792-ad6e-4342c0bdef29)
Can you please update your dependencies

**Comment by aldoulate** [comment]
Same here, security issues one dependencies, 8 months without a new release!

**Comment by mschatt** [comment]
Will this issue be resolved?

**Comment by Havunen** [comment]
This issue is fixed in my fork called DotSwashbuckle

**Comment by martincostello** [comment]
This only affects the `netstandard2.0` target, and can be resolved by you adding an explicit package reference to override the dependency version.
