### ISSUE TITLE
Swagger 支持api搜索吗？

### ISSUE THREAD

**Issue by hnpvqve** [domaindrivendev/Swashbuckle.AspNetCore#2699]
Swagger 支持api搜索吗？
因为有时候api接口太多了，需要对文档进行搜索查找接口地址。

**Comment by vdekercd** [comment]
Hi there, would it be possible for you to communicate in English? This would help us steer clear of using potentially inaccurate translation tools. Additionally, could you provide a more specific example of the type of behavior you're looking for?

**Comment by codelovercc** [comment]
@hnpvqve 您好，[Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore)是一个用于支持Swagger文档的库，内置了SwaggerUI，SwaggerUI不支持API接口搜索。您可以使用Swashbuckle.AspNetCore.ReDoc包来启用[redoc](https://github.com/Redocly/redoc)的UI支持，Redoc是另一个Swagger的UI开源项目，其支持对API接口的搜索但不支持对API的测试。具体使用方法见：[Swashbuckle.AspNetCore.ReDoc](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcoreredoc)

Hi, @hnpvqve , [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) is a package that support Swagger documentation for .net, it uses SwaggerUI by default, API searching feature is not supported by SwaggerUI. You could use package Swashbuckle.AspNetCore.ReDoc to enable [redoc](https://github.com/Redocly/redoc) UI, Redoc is another open source project of swagger UI, it dose support API searching but doesn't support "try it out" for API test. Usage doc: [Swashbuckle.AspNetCore.ReDoc](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcoreredoc)

**Comment by martincostello** [comment]
Please open a new issue in English so that the maintainers are able to look into your problem.
