### ISSUE TITLE
Warnings while using Swashbuckle on AspNet.Core

### ISSUE THREAD

**Issue by galvesribeiro** [domaindrivendev/Swashbuckle.AspNetCore#270]
I added `Swashbuckle 6.0.0-beta902` and the following warnings are throwing at build time:

```
5>Startup.cs(86,17,86,31): warning CS1701: Assuming assembly reference 'Microsoft.AspNetCore.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' used by 'Swashbuckle.Swagger' matches identity 'Microsoft.AspNetCore.Http.Abstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' of 'Microsoft.AspNetCore.Http.Abstractions', you may need to supply runtime policy
5>Startup.cs(87,17,87,33): warning CS1701: Assuming assembly reference 'Microsoft.AspNetCore.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' used by 'Swashbuckle.SwaggerUi' matches identity 'Microsoft.AspNetCore.Http.Abstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' of 'Microsoft.AspNetCore.Http.Abstractions', you may need to supply runtime policy
```

I assume it is because the dependency on aspnet assemblies are old. Can it be updated?

Thanks

**Comment by sandorfr** [comment]
This package is obsolete, It has moved to `Swashbuckle.AspNetCore` https://www.nuget.org/packages/Swashbuckle.AspNetCore/1.0.0-rc1 .

I was wondering the same a few days ago. I guess this should be advertised in a more visible way on the homepage as I guess, a lot of early adopter might be wondering the same. Maybe the description of deprecated packages could be updated it as well to mention the new repo

**Comment by galvesribeiro** [comment]
@sandorfr Multiple people in CoreCLR community are mentioning the `.AspNetCore` package is going to be merged back to the main package :(

I don't know which one now is true :(

**Comment by sandorfr** [comment]
I don't know about maintainer plans about this, but I don't really see it working well.

They are really two different versions of swashbuckle targeting two very different stack sharing almost nothing but a base name (aspnet core and apsnet). I don't know how one would select the right assemblies if it was to be merged together. To me this would be unclear and tricky hence this is very unlikely.

**Comment by domaindrivendev** [comment]
See the announcement at the top of the [readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore).

Swashuckle.6.0.0-beta* packages are obsolete. The new name is Swashbuckle.AspNetCore.1.0.0-*. The plan is to maintain two separate projects, the original Swashbuckle for ASP.NET / WebApi and Swashbuckle.AspNetCore for ASP.NET Core, that can live on with their respective frameworks

**Comment by galvesribeiro** [comment]
@domaindrivendev ok, good. Now a clear statement from someone who did that :)

What about the annoying warnings?
