### ISSUE TITLE
TargetFrameworks cause compile error

### ISSUE THREAD

**Issue by ben-page** [domaindrivendev/Swashbuckle.AspNetCore#2706]
Libraries that reference `Swashbuckle.AspNetCore` and target multiple framework versions (`<TargetFrameworks>net6.0;net7.0</TargetFrameworks>`) fail to compile with the following error.

`MSB3073`
`The command "dotnet "C:\Users\ben.page\.nuget\packages\microsoft.extensions.apidescription.server\6.0.5\build\../tools/dotnet-getdocument.dll" --assembly "C:\repos\SwashbuckleMultiTargetError\SwashbuckleMultiTarget\bin\Debug\net6.0\SwashbuckleMultiTarget.dll" --file-list "obj\SwashbuckleMultiTarget.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v6.0" --output "obj" --project "SwashbuckleMultiTarget" --assets-file "C:\repos\SwashbuckleMultiTargetError\SwashbuckleMultiTarget\obj\project.assets.json" --platform "AnyCPU" " exited with code 3.`

Replacing `<TargetFrameworks>net6.0;net7.0</TargetFrameworks>` with `<TargetFramework>net7.0</TargetFramework>` allows the code to compile.

Example Repo:  https://github.com/ben-page/SwashbuckleMultiTargetError

**Comment by ben-page** [comment]
This is the same issue reported on #1511. But that was closed because is was missing an example repo.

**Comment by jeremia** [comment]
This seem similar to the old aspnetcore issue 14370. This comment says that the scenario with using Swashbuckle in a library project isn't supported: https://github.com/dotnet/aspnetcore/issues/14370#issuecomment-917290020.
It's obviously a use case for several people including me.
It just sounds like it's not supported because they didn't thought of that scenario.

**Comment by rianjs** [comment]
This is definitely still and issue, and the workaround still works.

Workaround: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1511#issuecomment-696682962
