### ISSUE TITLE
Oauth2 authorizations,  endpoints padlock button doesn't show scopes

### ISSUE THREAD

**Issue by muhammetsk** [domaindrivendev/Swashbuckle.AspNetCore#2711]
I am upgrading my swashbuckle from 6.4.0 to 6.5.0. But endpoints padlock button modal different. I mean Authorize button not broken but when I click padlock button right of the each endpoint. Scopes are not showing in 6.5.0.
This is 6.4.0 swashbuckle
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/22572902/cd420f28-61c3-42e4-a62a-7a8ccb9721e6)
6.5.0
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/22572902/9c466bd5-630f-4db7-b2a7-88a7fda6096c)
I have following lines in Startup.cs

              services.AddSwaggerGen(c => {
                c.SwaggerDoc("v1", new OpenApiInfo {Title = "Petstore", Version = "v1"});
                var basePath = AppContext.BaseDirectory;
                var xmlPath = Path.Combine(basePath, "petstore.xml");
                c.IncludeXmlComments(xmlPath);
                c.OperationFilter<AddHeaderParamFilter>();
                c.OperationFilter<EventUploadOperationFilter>();
                c.OperationFilter<ResponseOperationFilter>();
                c.OperationFilter<EventMultipartUploadOperationFilter>();
                c.DescribeAllParametersInCamelCase();

              
                c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "oauth2"
                            }
                        },
                        new[] {"readAccess", "writeAccess"}
                    }
                });
            });

            services.ConfigureSwaggerGen(options =>
            {
                var authorizationUrl =
                    string.Format("{0}/connect/authorize", Configuration["IdentityServer:Authority"]);
                var tokenUrl = string.Format("{0}/connect/token", Configuration["IdentityServer:Authority"]);

                options.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.OAuth2,
                    Flows = new OpenApiOAuthFlows
                    {
                        Implicit = new OpenApiOAuthFlow
                        {
                            AuthorizationUrl = new Uri(authorizationUrl, UriKind.Absolute),
                            Scopes = new Dictionary<string, string>
                            {
                                {"Petstore", "Access to Petstore"},
                                {"Petstore2", "Access to Petstore2"}
                            }
                        }
                    }
                });
            });

**Comment by pliszka-FP** [comment]
Hello I encountered the same problem. Please check if scopes have that the same names in ConfigureSwaggerGen and in AddSecurityRequirement. In your example, you should probably change "readAccess" and "writeAccess" to "Petstore" and "Petstore2". Good luck!

**Comment by muhammetsk** [comment]
Hi @pliszka-FP thank you very much it solved my problem :)
