### ISSUE TITLE
CLI is running all registered IHostedService

### ISSUE THREAD

**Issue by desjoerd** [domaindrivendev/Swashbuckle.AspNetCore#2712]
Currently the CLI is running all registered Hosted Services (`IHostedService`). I see that it's needed to start the application because otherwise the `app.Use*`/`app.Map*` configuration is not run. Because it's starting the application (with a NoopServer) it is running all registered HostedServices.

Because the CLI is almost always run in the context of a build it would be nice to not run those registered hosted services. This would also solve instances of for example HangFire or other things which start an IHostedService.

I've got a fix which I would like to discuss. It's a bit dirty but it works in my tests.

**Comment by 0xced** [comment]
Related: [dotnet-getdocument issues in .NET7](https://github.com/dotnet/aspnetcore/issues/45025#issuecomment-1320526859) on the ASP.NET Core repository.

The workaround I describe there requires modifying the application code so your pull request is probably a much better approach!

I'm just a bit worried that this project looks currently inactive. Last commit and last comment from @domaindrivendev dates back to January, 11. In the meantime, issues and pull requests are piling on. 😕 I hope this is only temporary. 🤞

**Comment by martincostello** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2713#issuecomment-2053583005

**Comment by martincostello** [comment]
Thanks for your help with this - the fix is available in [Swashbuckle.AspNetCore 6.6.2](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v6.6.2).
