### ISSUE TITLE
XmlCommentsDocumentFilter incorrect comment controller tags names.

### ISSUE THREAD

**Issue by MerickOWA** [domaindrivendev/Swashbuckle.AspNetCore#2717]
In Swashbuckle.AspNetCore.SwaggerGen v6.5.0

There appears to be a bug in [XmlCommentsDocumentFilter.cs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsDocumentFilter.cs#L28)

Simple reproduction steps are to create an [ApiController] and set a [ControllerName(...)] attribute on it which overrides the controller's name to something else, example:

```csharp
// simple setup with including xml comments
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
    c.IncludeXmlComments(..., includeControllerXmlComments: true);
});

/// <summary>
/// My test controller to prove bugs
/// </summary>
[ApiController]
[Route("api/test")]
[ControllerName("Test")]
public class MyTestController : ControllerBase
{
    /// <summary>
    /// Returns something else
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public IActionResult Index()
    {
        return Ok(new { Something = "Hello", Else = "World" });
    }
}
```

The default SwaggerGeneratorOptions.TagsSelector uses the RouteValues["controller"] as the tag it puts on actions, but the XmlCommentsDocumentFilter.cs will create the tag using ControllerName which is the original/raw name (minus the Controller suffix if it exists).

This leads to ReDoc and Swagger UI to show an extra section with the raw controller name and the comment, and a separate section with the action actions.

Expected behavior would be that controller comments properly show up under the "Test" section.

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/185721/23ea97c9-bf62-4969-978c-9906ed4703b2)

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/185721/aaf2388d-d8dd-449b-832f-b2a990614b69)

**Comment by martincostello** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2718#issuecomment-2053572519
