### ISSUE TITLE
[AsParameter] attribute generates a string query parameter when it should generate a decimal

### ISSUE THREAD

**Issue by LloydNicholson** [domaindrivendev/Swashbuckle.AspNetCore#2733]
**Issue**
The `[AsParameters]` attribute is not generating the correct type of `decimal` when using Swashbuckle to generate a WebApi. It generates a `string`.

When a decimal type is used on the object that is annotated with the `[AsParameters]` attribute the type generated is always a `string` rather than a decimal.

**Reproduction**
I have attached a zip file with a net7.0 solution with a basic replication of the problem. It contains a net7 minimal web API and you need to run it to see the type generated on the `/swagger` URL page is a string, not a decimal as expected.

[TestWebApp.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/13265006/TestWebApp.zip)

**Expected Behaviour**
Generate a decimal when the client runs the build step.

**Comment by Havunen** [comment]
I tested this using DotSwashbuckle and .NET 8 and it seems to work.
https://github.com/Havunen/DotSwashbuckle
https://www.nuget.org/packages/DotSwashbuckle.AspNetCore

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/2021355/27163fe0-b666-4d24-bb96-7c23378d12f7)

**Comment by Liandrel** [comment]
I've run into simmilar issue with enum type 
endpoint registered like that
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/109763767/6b1e46c9-93b0-4047-833c-fbf9fa554cbd)
As parameters object
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/109763767/0be39261-e400-4e3a-bd44-6c8b950f0f7d)
swagger endpoint
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/109763767/533d12f3-540c-4ff0-8009-3e745d14136d)
swagger json
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/109763767/fb1b1171-235e-44fd-a4d9-abe8c859571d)

I can provide some more context if it will be needed

**Comment by martincostello** [comment]
More information would be good if you can.

**Comment by Liandrel** [comment]
To make sure it's not any external or domain dependency I've created  sample project that shows the issue

https://github.com/Liandrel/Swashbuckle-AsParameters-sample

.NET 8 minimal api with no additional nugget packages except of pattern ones

one endpoint:
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/109763767/99dbc759-edd3-4b57-b1ca-ce78c0fe8ef1)

RequestModel:
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/109763767/8b4717d5-6526-49f9-a82b-ae7826f144f1)

Swagger Page: 
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/109763767/ea208de4-dd0b-48f1-b4f2-866ab3d7f57b)

Swagger.json
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/109763767/d46b15c1-5874-41d8-a8b1-66bda2377edc)

**Comment by Havunen** [comment]
It seems the ApiExplorer provides the value for enum as string... using metadata driven approach works tho...




```cs
// Works
                endpoints.MapGet("/asparameter/openapi/enum", ([FromQuery] ConditionState? ConditionStateFromQuery,
                    [AsParameters] RequestModel model) =>
                {
                    return $"{ConditionStateFromQuery}, {model.ConditionStateAsParameters}";
                }).WithOpenApi();

// Does not work
                endpoints.MapGet("/asparameter/openapi/enum2", ([FromQuery] ConditionState? ConditionStateFromQuery,
                    [AsParameters] RequestModel model) =>
                {
                    return $"{ConditionStateFromQuery}, {model.ConditionStateAsParameters}";
                });
```

**Comment by Liandrel** [comment]
I tried it and for me it still renders as string field in swagger, did u changed anything else then adding `.WithOpenApi()` extension ?
