### ISSUE TITLE
Not Able to generate the Schema after upgrading from 5.4.1 to 6.5.0 

### ISSUE THREAD

**Issue by Eknath-Sable** [domaindrivendev/Swashbuckle.AspNetCore#2734]
Thanks for contributing to Swashbuckle.AspNetCore! As per the [contributing guidelines](CONTRIBUTING.md), please adhere to An unhandled exception occurred while processing the request.

ArgumentException: Invalid type owner for DynamicMethod.
System.Reflection.Emit.DynamicMethod.Init(string name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, bool skipVisibility, bool transparentMethod)

SwaggerGeneratorException: Failed to generate schema for type - Solidatus.Api.Dtos.v1.Responses.ListResponse`1[Solidatus.Entities.CommentTimelineEntry]. See inner exception
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)

SwaggerGeneratorException: Failed to generate Operation for action - Solidatus.Web.Controllers.Api.v1.Models.IssuesController.GetComments (Solidatus.Web). See inner exception
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)

Stack Query Cookies Headers Routing
ArgumentException: Invalid type owner for DynamicMethod.
System.Reflection.Emit.DynamicMethod.Init(string name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, bool skipVisibility, bool transparentMethod)
System.Reflection.Emit.DynamicMethod..ctor(string name, Type returnType, Type[] parameterTypes, Type owner, bool skipVisibility)

Swagger.cs 

using System;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.OpenApi.Models;
using Solidatus.Common.SwaggerUtils;
using Solidatus.Web.AppStartup.Filters.Swagger;
using Solidatus.Common.Configuration;
using Solidatus.Web.Utils;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Solidatus.Web.AppStartup;

public static class Swagger
{
    public static void Setup(IServiceCollection services, SwaggerConfiguration swaggerConfig)
    {
        services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "Solidatus API", Version = "1" });
                c.SwaggerDoc("vBeta", new OpenApiInfo { Title = "Solidatus API", Version = "Beta" });

                c.DocumentFilter<IncludeLiveUpdateEventsFilter>();
                c.DocumentFilter<IncludesFilter>();

                c.MapType<DateOnly>(() => new OpenApiSchema
                {
                    Type = "string",
                    Format = "date"
                });

                var webDocsFilePath = Path.Combine(AppContext.BaseDirectory,
                    "Solidatus.Web.xml");
                c.IncludeXmlComments(webDocsFilePath);

                var apiDocsFilePath = Path.Combine(AppContext.BaseDirectory,
                    "Solidatus.Api.xml");
                c.IncludeXmlComments(apiDocsFilePath);

                var apiDtosDocsFilePath = Path.Combine(AppContext.BaseDirectory,
                    "Solidatus.Api.Dtos.xml");
                c.IncludeXmlComments(apiDtosDocsFilePath);

                var entitiesDocsFilePath = Path.Combine(AppContext.BaseDirectory, "Solidatus.Entities.xml");
                c.IncludeXmlComments(entitiesDocsFilePath);

#pragma warning disable 618
                // Still a fix - tracked by https://solidatus.myjetbrains.com/youtrack/issue/SOL-2361
                //c.DescribeAllEnumsAsStrings();
#pragma warning restore 618

                // Fixes error where variables in the url path are camelCase and they are matched to ones in the
                // parameters list that come from a 'request' object and are in PascalCase
                c.DescribeAllParametersInCamelCase();

                c.GeneratePolymorphicSchemas();

                // Add both schemes, ApiKey used for UI of docs to allow entry of token and for it to appear in request
                // Bearer used by client
                c.AddSecurityDefinition("ApiKey", new OpenApiSecurityScheme
                {
                    Description =
                        "Authorization header using the Bearer scheme. Example: \"Bearer {token}\"",
                    Name = "Authorization",
                    In = ParameterLocation.Header,
                    Type = SecuritySchemeType.ApiKey
                });

                c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme, Id = "ApiKey"
                            }
                        },
                        new string[] { }
                    }
                });

                // The Swagger environment is active when using the Swashbuckle CLI to get the full JSON in order to build the TypeScript API client,
                // so we don't want to filter out anything
                var isClientGen = swaggerConfig.BuildEnvironment is BuildEnvironment.Swagger;

                if (!isClientGen)
                {
                    // Suppress admin content from unauthenticated/unauthorized users
                    c.DocumentFilter<SuppressAdminContentDocumentFilter>();

                    // Removes properties marked with the SwaggerExcludeAttribute
                    c.SchemaFilter<ExcludeAttributeSchemaFilter>();

                    // Removes actions marked with the SwaggerExcludeAttribute
                    c.DocInclusionPredicate((docName, apiDesc) =>
                    {
                        return DefaultDocInclusionPredicate(docName, apiDesc) && !apiDesc.CustomAttributes().OfType<SwaggerExcludeAttribute>().Any();
                    });
                }

                // Corrects the inheritance of generated schemas
                c.SchemaFilter<CorrectInheritanceSchemaFilter>();

                // Corrects the polymorphism of generated schemas
                c.SchemaFilter<CorrectPolymorphismSchemaFilter>();

                // Adds the default content-type to the encoding part of "multipart/form-data" request bodies as
                // openapi-generator does not respkt defaults... (fails validation with
                // .requestBody.content.encoding.contentType is missing)
                // https://github.com/OpenAPITools/openapi-generator/issues/5902
                c.OperationFilter<ExplicitDefaultEncodingContentTypeOperationFilter>();

                c.OperationFilter<SolidatusMethodNameOperationFilter>();

                c.OperationFilter<IncludeFileUploadOperationFilter>();

                // Add a custom generation of schema Ids. This turns names caused by types such as
                // "List<Product>" to not come out as "List[Product]" but rather "ProductList".
                // Fixes error: "ref values must be RFC3986-compliant percent-encoded URIs"
                // Code from https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/752#issuecomment-467817189
                c.CustomSchemaIds(modelType =>
                {
                    if (!modelType.IsConstructedGenericType)
                    {
                        return modelType.Name;
                    }

                    var prefix = modelType.GetGenericArguments()
                        .Select(genericArg => genericArg.Name)
                        .Aggregate((previous, current) => previous + current);

                    return prefix + modelType.Name.Split('`').First();
                });
            })
            .AddSwaggerGenNewtonsoftSupport();
    }

    public static void Configure(IApplicationBuilder app)
    {
        app.UseSwagger(c => { c.RouteTemplate = "api-docs/{documentName}/docs.json"; });
        //Temporary CVE patch for SwaggerUI mentioned.
        //The 5.7.1 release will contain the necessary fixes.
        app.UseSwaggerUI(c =>
         {
             c.RoutePrefix = "api-docs";
             c.DocumentTitle = "Solidatus API Docs";
             c.SwaggerEndpoint("/api-docs/v1/docs.json", "Solidatus API V1");
             // c.SwaggerEndpoint("/api-docs/vBeta/docs.json", "Solidatus API Beta");
         });
    }

    // Default Swashbuckle implementation
    // from https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGeneratorOptions.cs
    private static bool DefaultDocInclusionPredicate(string documentName, ApiDescription apiDescription)
    {
        return apiDescription.GroupName == null || apiDescription.GroupName == documentName;
    }
}

CommentTimelineEntry
public class CommentTimelineEntry : TimelineEntry
{
    public CommentTimelineEntry()
    {
        this.Type = "Comment";
    }

    public string Comment { get; set; }

    public DateTime? LastEdit { get; set; }

    [BsonIgnore]
    public bool IsEdited => this.LastEdit != null;
}

public abstract class TimelineEntry : BaseDbEntry
{
    [BsonRepresentation(BsonType.ObjectId)]
    public string EntityId { get; set; }

    [BsonRepresentation(BsonType.String)]
    public EntityType EntityType { get; set; }

    [BsonRepresentation(BsonType.ObjectId)]
    public string UserId { get; set; }

    public string UserName { get; set; }

    public string UserDisplayName { get; set; }

    public bool IsDeleted { get; set; }

    [BsonIgnore]
    public string Type { get; set; }

    /// <summary>
    /// List of different types of Id, they are used for filtering purposes
    /// </summary>
    [BsonRepresentation(BsonType.ObjectId)]
    [BsonIgnoreIfNull]
    public IEnumerable<string> RelatedIds { get; set; } = new List<string>();

    [BsonRepresentation(BsonType.ObjectId)]
    [BsonIgnoreIfNull]
    public IEnumerable<string> ReadBy { get; set; } = new List<string>();
}

**Comment by Havunen** [comment]
This might be fixed in DotSwashbuckle, can you test using it please.
https://github.com/Havunen/DotSwashbuckle
https://www.nuget.org/packages/DotSwashbuckle.AspNetCore

**Comment by martincostello** [comment]
I'm going to close this as it's just a copy-paste of an exception message and some code that won't compile in isolation. Please open a new issue with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) if you're still experiencing this issue and would like us to look into it.
