### ISSUE TITLE
SwaggerGeneratorOptions.SchemaComparer isn't calling the configured Comparer

### ISSUE THREAD

**Issue by dlstucki** [domaindrivendev/Swashbuckle.AspNetCore#2741]
I'm trying to custom sort my schemas and SwaggerGeneratorOptions.SchemaComparer doesn't seem to have any effect.
 
Could the problem be that SchemaComparer getting skipped in this DeepCopy?

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs#L55-L65

Using Swashbuckle.AspNetCore.SwaggerGen.6.5.0.0

**Comment by Havunen** [comment]
fixed in DotSwashbuckle
