### ISSUE TITLE
Could we provide an example of Migrating a .NET7.0 app to .NET8.0?

### ISSUE THREAD

**Issue by FreddyJohn** [domaindrivendev/Swashbuckle.AspNetCore#2744]
1.) Open a .NET7.0 project
2.) follow the migration outlined here https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio

After this, swagger opens with `ERR_EMPTY_RESPONSE`

**Comment by codelovercc** [comment]
I've upgraded my project from .NET7 to .NET8 recently. Lucky for me, It's running with out any problems. I don't know why you have got `ERR_EMPTY_RESPONSE` problem. Could you please comment the exception stacks or log informations?

**Comment by jonsagara** [comment]
According to the docs, Swashbuckle is not supported in .NET 8 and later:

https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle

**Comment by fuzzzerd** [comment]
> According to the docs, Swashbuckle is not supported in .NET 8 and later:
> 
> https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle

That was updated very recently. It now says that runtime generation is supported, but build-time is no longer supported. I have a .NET 8 app using build-time generation, since before that doc update, and it seems to be working.

**Comment by Havunen** [comment]
This should be fixed in DotSwashbuckle

**Comment by FreddyJohn** [comment]
I fixed this issue months ago, very busy so haven't seen responses. If you are having issues just deeply review all your configuration
