### ISSUE TITLE
System.InvalidOperationException for XmlCommentsParameterFilter

### ISSUE THREAD

**Issue by sgoldberg16** [domaindrivendev/Swashbuckle.AspNetCore#2747]
I am having the following exception throw after upgrading to .Net8:
System.InvalidOperationException: A suitable constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsParameterFilter' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.

Any initial thoughts or suggested fixes would be appreciated!
Using Swashbuckle.AspNetCore 6.5.0
Using Swashbuckle.AspNetCore.SwaggerUI 6.5.0
Using Swashbuckle.AspNetCore.SwaggerGen 6.5.0
Using Swashbuckle.AspNetCore.Swagger 6.5.0

**Comment by KothariDhrumil** [comment]
I am also facing the same when I am publishing this on IIS. in local its working fine.

**Comment by KothariDhrumil** [comment]
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/69053211/72dba82d-296a-4124-ae72-d1b4ece6be25)

**Comment by Havunen** [comment]
Have you tested with https://github.com/Havunen/DotSwashbuckle https://www.nuget.org/packages/DotSwashbuckle.AspNetCore

**Comment by martincostello** [comment]
It's not obvious to me at first glance why this wouldn't be working.

The activation call come from here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/830c5a6f7468bce6b716d84c034a258dbbcbfe98/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/ConfigureSwaggerGeneratorOptions.cs#L76-L77

The constructor receives a single `XPathDocument`:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/830c5a6f7468bce6b716d84c034a258dbbcbfe98/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsParameterFilter.cs#L11

Which is provided as the argument here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/830c5a6f7468bce6b716d84c034a258dbbcbfe98/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs#L433

It might be related to [this breaking change in .NET 8](https://learn.microsoft.com/dotnet/core/compatibility/extensions/8.0/activatorutilities-createinstance-behavior).

**Comment by martincostello** [comment]
Having updated Swashbuckle to target `net8.0`, I can't replicate this with our test suite.

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
