### ISSUE TITLE
I maked custom service to controller convention

### ISSUE THREAD

**Issue by wisamidris7** [domaindrivendev/Swashbuckle.AspNetCore#2751]
I did custom service to controller convention like abp.io but problem is swagger not working to generate all services
cause there are not controllers

so give me way to make it and tell swagger to add custom classes

and thanks

**Comment by Havunen** [comment]
can you provide an example what you did and what is the expected result please

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem you're encountering. This issue is not actionable in its current state.
