### ISSUE TITLE
Microsoft.OpenApi.Any.OpenApiString   Automatically convert to int

### ISSUE THREAD

**Issue by Tony-Liang** [domaindrivendev/Swashbuckle.AspNetCore#2752]
schema.Example = new Microsoft.OpenApi.Any.OpenApiString("2", true);
![QQ图片20231229102446](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/2556784/ede62448-ead9-4501-ac93-b66f23992307)

schema.Example = new Microsoft.OpenApi.Any.OpenApiString("-u2", true);
![QQ图片20231229102450](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/2556784/7bc0cf37-8b4e-4b88-9fb6-877075f10ef9)

String is not quoted with double quotes

**Comment by darrelmiller** [comment]
@Tony-Liang  Past attempts to try and guess the datatypes of examples and other things like extensions has been a major problem for OpenAPI.NET users.  We are working on a major new version with OpenAPI 3.1 support that will stop trying to do this.   I'm hoping we have an early preview of the update in a couple of months.
