### ISSUE TITLE
How to bind documentation only to the required assembly

### ISSUE THREAD

**Issue by matyashovandrey** [domaindrivendev/Swashbuckle.AspNetCore#2753]
Hello, I am interested in the question of how to link documentation to a specific assembly.

As an C# example
There are two assemblies
Project.Web.dll
Project.Web.Api.dll

Assembly Project.Web.dll connects assembly Project.Web.Api.dll
and in this situation it is necessary to document only the assembly Project.Web.Api.dll.

Thanks in advance for your answers.

**Comment by Havunen** [comment]
One option is to declare your Assembly1 controllers with  API explorer settings attribute: 

> [ApiExplorerSettings(GroupName= "name1")]

and assembly 2 controllers with another attribute API Explorer settings attribute with different name.

Then you can generate swagger documents per the attribute group:

```cs

services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("doc-v1", new OpenApiInfo { Title = "name1", Version = "v1" });
    c.SwaggerDoc("doc-v2", new OpenApiInfo { Title = "name2", Version = "v1" });
}
```

optionally add swagger ui for one or all of them:

```cs
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/doc-v1/swagger.json", "name1");
    c.SwaggerEndpoint("/swagger/doc-v2/swagger.json", "name2");
}
```


you can also ignore the whole type by using: `[ApiExplorerSettings(IgnoreApi = true)]`

**Comment by martincostello** [comment]
You could also consider hiding things with a [schema filter](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/ISchemaFilter.cs).
