### ISSUE TITLE
[Length] Attribute isn't supported

### ISSUE THREAD

**Issue by satma0745** [domaindrivendev/Swashbuckle.AspNetCore#2756]
This issue is a feature request for a support of the `[Length]` attribute. Judging by the example in the [Contribution guide](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/CONTRIBUTING.md?plain=1#L16), this issue falls into the **Feature Requests** category.

The `System.ComponentModel.DataAnnotations` namespace has 3 (actually even more, but it is not within the scope of this Issue) Attributes responsible for the string length validation:
1. `[MinLength(length)]` - [MS Docs](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.minlengthattribute)
2. `[MaxLength(length)]` - [MS Docs](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.maxlengthattribute)
3. `[Length(minimumLength, maximumLength)]` - [MS Docs](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.lengthattribute)

And while the first two are supported, the latter isn't.
Suppose, we have the following DTO definition:
```csharp
class Dto
{
    [MinLength(2), MaxLength(10)]
    public string Prop1 { get; set; }

    [Length(2, 10)]
    public string Prop2 { get; set; }
}
```
Having such model SwaggerGen produces the following `OpenApi` specification:
```json
"Dto": {
  "type": "object",
  "properties": {
    "prop1": {
      "maxLength": 10,  
      "minLength": 2,
      "type": "string",
      "nullable": true
    },
    "prop2": {
      "type": "string",
      "nullable": true
    }
  },
  "additionalProperties": false
}
```
Where the `prop1` field has both `maxLength` and `minLength` values specified, but the `prop2` field doesn't have them at all.

**Comment by satma0745** [comment]
I'll also provide a PR that solves this issue, but it'll take some time (first time I opened the source-code of this library).

**Comment by satma0745** [comment]
It turns out that the Project has not been updated for a year (at this point in time). This means that the current version for the project is .Net 7.0, while the `[Length]` attribute [was introduced in .Net 8.0](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.lengthattribute#applies-to). It's impossible to add support for this attribute at the moment.

**Comment by satma0745** [comment]
If You stumbled upon this Issue and the Project hasn't yet migrated to .Net 8, then you can make use of the following SchemaFilter in Your Solution:
```csharp
internal sealed class LengthAttributeSupportSchemaFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        if (context.MemberInfo is null)
        {
            return;
        }

        var lengthAttributes = context.MemberInfo.GetInlineAndMetadataAttributes().OfType<LengthAttribute>();
        foreach (var lengthAttribute in lengthAttributes)
        {
            ApplyLengthAttribute(schema, lengthAttribute);
        }
    }

    private void ApplyLengthAttribute(OpenApiSchema schema, LengthAttribute lengthAttribute)
    {
        if (schema.Type == "array")
        {
            schema.MinItems = schema.MinItems is null 
                ? lengthAttribute.MinimumLength 
                : Math.Max(schema.MinItems.Value, lengthAttribute.MinimumLength);

            schema.MaxItems = schema.MaxItems is null
                ? lengthAttribute.MaximumLength
                : Math.Min(schema.MaxItems.Value, lengthAttribute.MaximumLength);
        }
        else
        {
            schema.MinLength = schema.MinLength is null 
                ? lengthAttribute.MinimumLength 
                : Math.Max(schema.MinLength.Value, lengthAttribute.MinimumLength);

            schema.MaxLength = schema.MaxLength is null
                ? lengthAttribute.MaximumLength
                : Math.Min(schema.MaxLength.Value, lengthAttribute.MaximumLength);
        }
    }
}
```

**Comment by satma0745** [comment]
I'm not closing this Issue, since the solution I've provided is temporary. I hope that the Project'll migrate to the .Net 8 eventually and we'll be able to add support for the `[Length]` attribute on the Project's source-code side.

**Comment by soroshsabz** [comment]
ITNOA

I need this feature too.

**Comment by dnperfors** [comment]
I wanted to help you out by implementing this, but I need .NET 8 support for this... Guess I will start with reviewing the .NET 8 PR instead :)

**Comment by soroshsabz** [comment]
@satma0745 @dnperfors As you can see, .NET 8 added in PR #2799 and merge it.

So do you can start implementing this feature?

thanks

**Comment by satma0745** [comment]
Yeah, I'll start working on it

**Comment by satma0745** [comment]
@soroshsabz
Yeah, I'll start working on it

**Comment by satma0745** [comment]
@soroshsabz Opened a PR: #2882
