### ISSUE TITLE
indexed description formatted in frontend has display error

### ISSUE THREAD

**Issue by yu0A** [domaindrivendev/Swashbuckle.AspNetCore#2757]
Version 6.2.3
I write description below:
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/111437058/951121ed-4c5e-4ef8-a43a-5573cc654a6d)
The frontend shows description below:
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/111437058/71f97d39-8952-44d1-a637-8a013c5b6f97)

**Comment by Havunen** [comment]
That is swagger ui bug, you can report it there https://github.com/swagger-api/swagger-ui

**Comment by yu0A** [comment]
> That is swagger ui bug, you can report it there https://github.com/swagger-api/swagger-ui

OK, please leave this issue archived, so [this bug](https://github.com/swagger-api/swagger-ui/issues/9656) can find my screenshots.
