### ISSUE TITLE
[Question] schema definition attribute for swagger gen

### ISSUE THREAD

**Issue by jmurphzyo** [domaindrivendev/Swashbuckle.AspNetCore#276]
Is there an existing attribute included in this lib to define the [Swagger spec schema object](http://swagger.io/specification/#schemaObject) ? If not is there a way to create a custom one? Thanks for all the work you guys have put into this project!

**Comment by domaindrivendev** [comment]
Please check out the following sections of the readme and let me know if they answer your questions:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#override-schema-for-specific-types
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#schema-filters

**Comment by jmurphzyo** [comment]
Not so much I was looking at adding the title and description properties to the actual properties of a class. I ended up creating a custom attribute and a custom schema filter to achieve what I was looking for.
