### ISSUE TITLE
Support the required keyword in the same way as RequiredAttribute

### ISSUE THREAD

**Issue by AntiGuideAkquinet** [domaindrivendev/Swashbuckle.AspNetCore#2764]
When using .NETs required keyword, the properties that it is used on do not get marked as required in SwaggerGen. I set up a project to reproduce the issue. When adding the RequiredAttribute to the property, the result changes to the expected behavior.

I assume that [this](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs#L393C36-L394C51) line could fix the problem if it checked for `RequiredMemberAttribute` too.

Thank you for investigating!

Version: 6.5.0
C# 11/.NET 7 and up
[SwashbuckleReproduction.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/14139486/SwashbuckleReproduction.zip)

**Comment by KRSogaard** [comment]
+1 this is causing a lot of problem in API communication with frontend team members

**Comment by Havunen** [comment]
This functionality has been implemented in DotSwashbuckle v3.0.1 
https://github.com/Havunen/DotSwashbuckle/commit/2871109cf24ff1643bcefc0f2f32a5eaebb66d79
https://www.nuget.org/packages/DotSwashbuckle.AspNetCore

**Comment by mattiasnordqvist** [comment]
Why did you do this? Required-keyword in C# has nothing to do with nullability. It is there to enforce initialization of properties in constructor or constructor-initializers. It is perfectly fine in C# to declare a property as a required nullable int like this: `required int?`

**Comment by martincostello** [comment]
See #2879.
