### ISSUE TITLE
Change field name swagger documentation

### ISSUE THREAD

**Issue by stone89son** [domaindrivendev/Swashbuckle.AspNetCore#2766]
is it possible to change property names in Swagger documentation(https://localhost:7126/swagger/v1/swagger.json)?
I'm using .NET 8 and Swashbuckle.AspNetCore 6.4. I've tried search on google but nothing has changed. Help!

My model:
```
    {
        public int MyProperty1 { get; set; }
        public int MyProperty2 { get; set; }
        public int MyProperty3 { get; set; }
    }
```
and swagger.json which was generated for it in POST method:

```
 "components": {
    "schemas": {
      "TestModel": {
        "type": "object",
        "properties": {
          "myProperty1": {
            "type": "integer",
            "format": "int32"
          },
          "myProperty2": {
            "type": "integer",
            "format": "int32"
          },
          "myProperty3": {
            "type": "integer",
            "format": "int32"
          }
        }
      }
    }
  }

```
How to change it to:

```
 "components": {
    "schemas": {
      "TestModel": {
        "type": "object",
        "properties": {
          "MyProperty1": {
            "type": "integer",
            "format": "int32"
          },
          "MyProperty2": {
            "type": "integer",
            "format": "int32"
          },
          "MyProperty3": {
            "type": "integer",
            "format": "int32"
          }
        }
      }
    }
  }
```

**Comment by Havunen** [comment]
Are you using Pascal naming convention or why do you want to serialize them that way?

By default Swashbuckle serializes the contract using the same serialization settings what you have defined for you web api. If you are using Newtonsoft serialization for API you need to enable Swashbuckle.AspNetCore.Newtonsoft  https://github.com/domaindrivendev/Swashbuckle.AspNetCore?tab=readme-ov-file#systemtextjson-stj-vs-newtonsoft

If you are using system.text.json serializer then you can define the Web API serialization settings in your Startup.cs file.

```cs
services
    .AddControllers()
    .AddJsonOptions(
        (c) => c.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.KebabCaseLower
    );
```

There is no option for PascalCase naming policy in STJ, I believe it is so uncommon so it is not implemented by default, but you could always implement it yourself or use some Nuget package. 

Btw. There is newer version of Swashbuckle called DotSwashbuckle which is for .NET 8 and later. It has bunch of bugs fixes.
https://github.com/Havunen/DotSwashbuckle?tab=readme-ov-file
https://www.nuget.org/packages/DotSwashbuckle.AspNetCore

**Comment by stone89son** [comment]
Thank you for your support, but that's not what I'm configuring.
I'm configuring to make changes in the components section of the file at https://localhost:7126/swagger/v1/swagger.json.
However, I don't know how to configure it and also don't see any instructions in the documentation.

**Comment by stone89son** [comment]
thank for support
not same.
![giaodien1](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/6795515/1c3c95a7-2362-421c-ba34-49aa4cad8eb2)
![giaodien2](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/6795515/b21d53fb-a99a-468a-80ca-b43afa28dac1)

**Comment by stone89son** [comment]
I have fixed it.
Add .AddJsonOptions(opt => opt.JsonSerializerOptions.PropertyNamingPolicy = null);
to keep the property names intact like in C#.
Thank you for taking the time to help.

**Comment by Liamhhhhh** [comment]
Generate API documentation. Perhaps you can try [Apidog](https://apidog.com/), which can meet your needs.

**Comment by martincostello** [comment]
Closing as resolved - arbitrary changes to the generated schemas can be made with [schema filters](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/ISchemaFilter.cs) ([example](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/Basic/Swagger/ExamplesSchemaFilter.cs)).
