### ISSUE TITLE
DisableValidator()

### ISSUE THREAD

**Issue by JoelAdamWeiss** [domaindrivendev/Swashbuckle.AspNetCore#277]
Spent most of the afternoon looking for an answer for this one.  According to the documentation

app.UseSwaggerUi(c =>
{
    c.EnabledValidator();
    c.BooleanValues(new object[] { 0, 1 });
    c.DocExpansion("full");
    c.InjectOnCompleteJavaScript("/swagger-ui/on-complete.js");
    c.InjectOnFailureJavaScript("/swagger-ui/on-failure.js");
    c.SupportedSubmitMethods(new[] { "get", "post", "put", "patch" });
    c.ShowRequestHeaders();
    c.ShowJsonEditor();
});

should be how you can call DisableValidator() or enable validator, but currently that function UseSwaggerUi only takes two strings, so I am getting a compilation error here.

I did ask some folks smarter than me to take a look at it, and they couldn't help.

The reason I care is that our site isn't public and I want to turn off the Validator to get rid of the error on the swagger page.

I did verify I have v6.0.0-beta902 installed.

Any info, even it's not ready yet would be great.  I have a hard head, but this wall is thick.

**Comment by domaindrivendev** [comment]
It's not immediately clear from the docs (will get something added ASAP) but the ASP.NET Core version of Swashbuckle now has its own dedicated package - Swashbuckle.AspNetCore. So, the docs aren't compatible with the old Swashbuckle 6 package you're using. You'll need to replace it with the new Core specific package

**Comment by JoelAdamWeiss** [comment]
Thanks for the quick answer.  Got this working.
