### ISSUE TITLE
Project continuation 

### ISSUE THREAD

**Issue by kant2002** [domaindrivendev/Swashbuckle.AspNetCore#2773]
Thank you for your work on this project. 

Given recent announcements is there a way that you start cooperate with community (at least me) on the project transition. 

I understand that you maybe cautious give project to strangers or have other concerns. 

If you have process in your mind which is best suited to you, please tell us.

if you want speak privately I think I have my email/Twitter/Mastodon in my profile.

**Comment by pinkfloydx33** [comment]
As someone who has spent an inordinate amount of time customizing swashbuckle for work and personal projects, I would be devasted to see this project go unmaintained. I too would be willing to help keep it alive as a maintainer

**Comment by skellyapi** [comment]
The developer, @domaindrivendev , is actively searching for someone to take over ownership and if that falls through, he'll actively seek maintainers from the community ([reference])(https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2759#issuecomment-1936136992). @Havunen has created a [fork](https://github.com/Havunen/DotSwashbuckle) which has included many commits related to issues reported on this repo. 

The time saved by this project is major and I sincerely hope the dev understands how much we all appreciate his efforts over the years. Ideally Microsoft steps up to sponsor or even fork it to maintain as their own; in my eyes it has saved us hundreds of hours and switching to a solution like NSwag will take time and investment given we've standardized usage within our APIs.  

Unfortunately, it looks like [Microsoft will be pulling Swashbuckle from it's WebAPI template moving forward with .NET 9](https://github.com/dotnet/aspnetcore/issues/54599#issue-2192441560). I hope it means that they will offer mechanisms further extending OpenAPI and Swagger such that if swashbuckle ceases maintenance completely, we have easy mechanisms to replace with what is support by Microsoft.

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/discussions/2778
