### ISSUE TITLE
can't using this package

### ISSUE THREAD

**Issue by arielcloud** [domaindrivendev/Swashbuckle.AspNetCore#278]
tried upgrade from 6.0.0-beta902 to this package.

doing exactly what is documented in the get started page, no swagger.json file created, and can't run the swagger-ui.

what additional data can I add, or how can I debug the problem?

I'm working on asp.net core 1.1

**Comment by domaindrivendev** [comment]
I need more info - what are u observing - 404 not found, blank page, JavaScript errors? Did you navigate directly to the swagger JSON endpoint? What are you observing there?

**Comment by arielcloud** [comment]
found my problem. it's now on swagger/index.html and not swagger/ui/index.html.

sorry. 10x. closing
