### ISSUE TITLE
Use Regex source generator

### ISSUE THREAD

**Issue by martincostello** [domaindrivendev/Swashbuckle.AspNetCore#2794]
For `net7.0` and later we can look to leverage the [Regex source generator]() to improve performance.

For example:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/830c5a6f7468bce6b716d84c034a258dbbcbfe98/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsTextHelper.cs#L10-L13

**Comment by martincostello** [comment]
Turns out those are the only static occurences in the whole code base. All the others are based on dynamic inputs.

**Comment by Saibamen** [comment]
How much perf boost?

**Comment by martincostello** [comment]
I didn't measure.
