### ISSUE TITLE
Drop support for out-of-support .NET versions

### ISSUE THREAD

**Issue by martincostello** [domaindrivendev/Swashbuckle.AspNetCore#2798]
The published binaries and code are starting to get bloated with adding support for .NET 8 for #2792, so we should look to remove support for target frameworks that are now _completely unsupported_ by Microsoft.

- `netcoreapp2.2`
- `netcoreapp3.0`
- `netcoreapp3.1`
- `net5.0`
- `net6.0` (from November 2024)
- `net7.0` (from May 2024)

This should be done as a major version bump.

We could either drop them all at once some time after November 2024, or do it in a phased approach:

1. Drop everything not supported today (.NET < 6.0 + 7.0);
2. Drop .NET 6 at a future date.

**Comment by martincostello** [comment]
As part of any breaking changes made when we do this, we should also consider removing any constructor overloads we've added over time to preserve binary compatibility which also ties into #2805.

**Comment by martincostello** [comment]
Will be resolved by #3007.

**Comment by cremor** [comment]
> We could either drop them all at once some time after November 2024, or do it in a phased approach:
>
> 1. Drop everything not supported today (.NET < 6.0 + 7.0);
> 2. Drop .NET 6 at a future date.

Seems like you chose the phased approach based on that #3007 still contains .NET 6.0?

**Comment by martincostello** [comment]
Yes - see #3087.
