### ISSUE TITLE
Consider making more types internal

### ISSUE THREAD

**Issue by martincostello** [domaindrivendev/Swashbuckle.AspNetCore#2805]
Review the public API and see if there's any types that are public that don't need to be, such as `SwaggerMiddleware`. That gives us more agility to change implementation details, like adding new constructor overloads (see #2801).

It may be that some types don't need to be public and are only done so through oversight or to be accessible to unit tests. In the case of tests, it might be too tricky to do with the way that some assemblies are strong named and others aren't, as `[InternalsVisibleTo]` requires IVT'd assemblies to also be strong named, and all dependencies of a project need to be strong named for it to be, which creates issues where a test project depends on one project that is signed and another that isn't.

Context: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2418#discussion_r1566514729

**Comment by ahoke-cr** [comment]
You can also specify InternalsVisibleTo inside the .csproj file which doesn't require any funny business with assemblies:

```xml
<ItemGroup>
     <InternalsVisibleTo Include='Swashbuckle.AspNetCore.SomeTestProject' />
</ItemGroup
```

**Comment by martincostello** [comment]
Good point, we do that here already:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/28128ebb4e6d809686036d1e4e45b6cd08e5d6ba/src/Swashbuckle.AspNetCore.SwaggerGen/Swashbuckle.AspNetCore.SwaggerGen.csproj#L14-L17
