### ISSUE TITLE
Pickup only from Area or namespace

### ISSUE THREAD

**Issue by seriouz** [domaindrivendev/Swashbuckle.AspNetCore#281]
How is it possible to restrict the lookup of Swashbuckle only to a certain `Area` or `namespace`?
I don't want that it looks up all of my controllers and actions. Just the namespace `BlogMaster.Areas.Api` or area `Api` would be perfect. I have a lot of other controllers which methods should not show up in the swagger!
```csharp
namespace BlogMaster.Areas.Api
{
    [Area("Api")]
    [AllowAnonymous]
    public class PostsController : Controller
    {
        [HttpGet]
        public List<string> GetAll()
        {
            ....
        }
    }
}

**Comment by domaindrivendev** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#omit-actions-by-convention

Based on the above, it should be fairly trivial to create a controller OR action "convention" that sets _ApiExplorer.IsVisible_ accordingly by inspecting the namespace or _AreaAttribute_.
