### ISSUE TITLE
Snapshot testing

### ISSUE THREAD

**Issue by martincostello** [domaindrivendev/Swashbuckle.AspNetCore#2811]
Consider adding tooling such as https://github.com/VerifyTests/Verify to create snapshot tests of generated schemas to provide a more comprehensive regression test suite.

**Comment by SimonCropp** [comment]
when u r using Verify, what would be the type of the instance you would pass in?

**Comment by SimonCropp** [comment]
and the extension to Verify, do u want it under this org or the Verify org?

**Comment by martincostello** [comment]
> when u r using Verify, what would be the type of the instance you would pass in? 

I don't know, I haven't looked into it. At a high-level I was thinking of just comparing rendered JSON/YAML schemas.

**Comment by martincostello** [comment]
> and the extension to Verify, do u want it under this org or the Verify org? 

What extension? Also this repo isn't in an org.
