### ISSUE TITLE
Manipulate opertationId

### ISSUE THREAD

**Issue by piniSolomon** [domaindrivendev/Swashbuckle.AspNetCore#282]
Hey,
I tried to make the swagger file create the operationId with the following pattern {ControllerName}_{ActionName} (the underscore is for the autorest to create cleaner API with separated clients)
I managed to do so only with the operationFilter.
`public void Apply(Operation operation, OperationFilterContext context)
{
            var actionAttrib = context.ApiDescription.GroupName;//.ApiDescription.GetActionAttributes();
            ControllerActionDescriptor actionDesc = (ControllerActionDescriptor)context.ApiDescription.ActionDescriptor;
            operation.OperationId = $"{context.ApiDescription.GroupName}_{actionDesc.ActionName}";
        }` 
What I would like to know is there another way to do so, maybe with attribue on the controller or action?

**Comment by domaindrivendev** [comment]
If you want to do it with an attribute - check out _SwaggerOperationAttribute_

**Comment by piniSolomon** [comment]
Hey,
Thanks for the response , I tried the _SwaggerOperationAttribute_ and it didn't work for me.
Here is the controller which I used with the attribue
`[HttpGet("{missionId}")]
[SwaggerOperation("GetMission")]
        //[SwaggerResponse(System.Net.HttpStatusCode.OK,Type =typeof(Mission))]
        //[SwaggerResponse(System.Net.HttpStatusCode.NotFound)]
        [ProducesResponseType(typeof(Mission), (int)System.Net.HttpStatusCode.OK)]
        [ProducesResponseType(typeof(string), (int)System.Net.HttpStatusCode.NotFound)]
        public IActionResult GetSpecificMission(int missionId, [FromQuery] string missionName)`
and here is the swagger genereted for that:

` "/api/Missions/{missionId}": {
      "get": {
        "tags": [
          "Missions"
        ],
        "operationId": "ApiMissionsByMissionIdGet",
        "consumes": [
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "missionId",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "missionName",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Mission"
            }
          },
          "404": {
            "description": "Client Error",
            "schema": {
              "type": "string"
            }
          }
        },
        "deprecated": false
      }
    },`

so I couldn't get this attribute to work, am I doing somthing wrong?

**Comment by domaindrivendev** [comment]
@piniSolomon - I'm unable to repro your issue. I'm doing exactly what you're trying to do in one of the sample sites in this repo:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/Basic/Controllers/SwaggerAnnotationsController.cs#L9

And it works as expected. So, you're going to have to dig a bit deeper yourself as I really can't help if I can't repro.

**Comment by domaindrivendev** [comment]
Closing - can't repro
