### ISSUE TITLE
`new` properties not respected for interfaces

### ISSUE THREAD

**Issue by angelaki** [domaindrivendev/Swashbuckle.AspNetCore#2821]
Hiding properties doesn't seam to work for interfaces (but was working with Newtonsoft-Generator) while it is working for classes:

```
public class First
{ public string? Value { get; } }

public class Second : First
{ public new int Value { get; } }

public class IFirst
{ public string? Value { get; } }

public class ISecond : IFirst
{ public new int Value { get; } }
```

```
  "First": {
	"type": "object",
	"properties": {
	  "value": {
		"type": "string",
		"nullable": true,
		"readOnly": true
	  }
	},
	"additionalProperties": false
  },
  "Second": {
	"type": "object",
	"properties": {
	  "value": {
		"type": "integer",
		"format": "int32",
		"readOnly": true
	  }
	},
	"additionalProperties": false
  }
  "IFirst": {
	"type": "object",
	"properties": {
	  "value": {
		"type": "string",
		"nullable": true,
		"readOnly": true
	  }
	},
	"additionalProperties": false
  },
  "ISecond": {
	"type": "object",
	"properties": {
	  "value": {
		"type": "string",
		"nullable": true,
		"readOnly": true
	  }
	},
	"additionalProperties": false
  },
```

`ISecond` gets a property of type "string", what isn't true / not the serializers behavior.

**Comment by martincostello** [comment]
Please share the code for the endpoints where you consume these types, which will be what causes them to be referenced in the schema.

**Comment by angelaki** [comment]
Yeah, sure ... easy as that:

```
public class First { public string? Value { get; } }
public class Second : First { public new int Value { get; } }
public interface IFirst { public string? Value { get; } }
public interface ISecond : IFirst { public new int Value { get; } }

[HttpGet("GetFirst")] public First? GetFirst() => null;
[HttpGet("GetSecond")] public Second? GetSecond() => null;
[HttpGet("GetIFirst")] public IFirst? GetIFirst() => null;
[HttpGet("GetISecond")] public ISecond? GetISecond() => null;
```

**Comment by martincostello** [comment]
If the returned types are the most-derived type, then I would have thought reflection would find the `new` override.

If this is a bug in Swashbuckle it would need to be investigated.

**Comment by angelaki** [comment]
Reflection / inheritance works pretty different for interfaces. So I guess Swashbuckle doesn't respect the order here.

**Comment by angelaki** [comment]
I could sure support here with a PR :) Can you give me a hint where to start?

**Comment by martincostello** [comment]
I don't know specifically where - I guess the changes would need to be in the SwaggerGen project and would be wherever we'd doing reflection on types getting properties.

**Comment by angelaki** [comment]
Possible, that this is already fixed in the latest version? Just created this test on the master branch and it works?

```
public interface IInterfaceWithNewPropertyBase { public int Property { get; } }
public interface IInterfaceWithNewProperty : IInterfaceWithNewPropertyBase { public new string Property { get; } }

public void GetSwagger_GeneratesSwaggerDocument_ForInterfaceWithNewProperty()
{
    var metadata1 = ModelMetadataFactory.CreateForType(typeof(IInterfaceWithNewPropertyBase));
    var metadata2 = ModelMetadataFactory.CreateForType(typeof(IInterfaceWithNewProperty));

    Assert.Equal(typeof(int), metadata1.Properties[0].ModelType);
    Assert.Equal(typeof(string), metadata2.Properties[0].ModelType);
}
```

Or maybe you can tell me what the easiest way is to reproduce my issue?

**Comment by martincostello** [comment]
If you consume the latest version from [our MyGet feed](https://www.myget.org/gallery/domaindrivendev) and you think it's fixed, then we can close this issue.

If we don't have an explicit test for it already, then a PR to codify the behaviour would be welcome.

**Comment by angelaki** [comment]
Nope, issue still exists with this version. Seams to be some kind of _constellation_, the `ModelMetadataFactory.CreateForType` doesn't seam to cause this issue. So a test wouldn't help, too.

If you were so kind to add a failing test to some branch based on my code here (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2821#issuecomment-2072017872) I would try to fix it :)

**Comment by martincostello** [comment]
I won't have the time to do that soon (and if I did I'd probably find the fix while doing it anyway).

If you're too busy too, that's fine, but I don't have enough time to investigate all the issues we currently have open, which is why there's lots of help-wanted issues.

**Comment by angelaki** [comment]
My fault... GetInterfaces() already gets all the interfaces (not first the first leven / .Net doesn't differentiate here). So the fix was quite easy, here we go :)
