### ISSUE TITLE
Duplicate parameters for [FromQuery] query parameters

### ISSUE THREAD

**Issue by rhegner** [domaindrivendev/Swashbuckle.AspNetCore#283]
I have an action like this:

    [HttpGet("{id}/{sourceDeviceId:bool?}")]
    public async Task<IActionResult> Get([FromRoute] string id, [FromQuery] bool sourceDeviceId)
    {
        // ...
    }

and in the generated swagger.json the `sourceDeviceId` appears twice:

	"parameters": [{
			"name": "id",
			"in": "path",
			"required": true,
			"type": "string"
		}, {
			"name": "sourceDeviceId",
			"in": "query",
			"required": false,
			"type": "boolean"
		}, {
			"name": "sourceDeviceId",
			"in": "path",
			"required": true,
			"type": "string"
		}
	],

Am I doing something wrong or is this a bug? A parameter labelled as `[FromQuery]` I would assume to only show up as a query parameter in swagger.

I'm using the Swashbuckle.AspNetCore 1.0.0-rc1 NuGet package.

**Comment by domaindrivendev** [comment]
When you use Http("{id}/{sourceDeviceId:bool?") you're specifying that sourceDeviceId is a "path" parameter (or a "route" parameter in ASP.NET speak) not a "query" parameter. However, in your action signature you're decorating it with _FromQuery_ and this means it should be a "query" parameter.

So, your current code is ambiguous and you need to decide, from an API contract perspective, which you want it to be "path" or "query". If you're not sure what the difference is, path parameters come before the "?" in a URI and a query parameters comes after it as a list of key-value pairs.

**Comment by rhegner** [comment]
Ok when doing this everything works as expected:

    [HttpGet("{id}")]
    public async Task<IActionResult> Get([FromRoute] string id, [FromQuery] bool sourceDeviceId)
    {
        // ...
    }

Thanks for your help!
