### ISSUE TITLE
Example request bodies not seen in json output

### ISSUE THREAD

**Issue by nsg1000** [domaindrivendev/Swashbuckle.AspNetCore#2832]
Swashbuckle cli 6.5.0

Implementing request examples as:

IExamplesProvider<MyRequest> from Swashbuckle.AspNetCore.Filters

Expect json to have an _example:_ section as per the following: https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters?tab=readme-ov-file#request-example

My swagger page json works correctly, the json file generated by the cli does not.

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
