### ISSUE TITLE
Incompatibility with Microsoft.AspNetCore.Mvc.Core 1.1.1

### ISSUE THREAD

**Issue by withinfocus** [domaindrivendev/Swashbuckle.AspNetCore#284]
MS recently put out a security advisory:

https://github.com/aspnet/Announcements/issues/216

Looks like Swashbuckle has a hard dependency on 1.1.0 and the latest 1.1.1 of the MVC Core causes runtime errors.

**Comment by domaindrivendev** [comment]
Swashbuckle doesn't have a hard dependency on 1.1.0. It specifies a minimum version of _1.0.0_. If my understanding is correct, this means it should be compatible with any version of Mvc Core >= _1.0.0_.  As described here https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions ...

_"Best practice:
Developers most commonly specify a minimum version, which is a version number without adornmants as shown above, like 6.1.0. This allows NuGet to install that version or later."_

With that said, I am (unexpectedly) getting a runtime error when explicitly referencing 1.1.1 from the application's project.json:

```
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.1.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Swashbuckle.AspNetCore": "1.0.0-rc1"
  },
```

 _Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference_

This is a little puzzling to me based on my reading of the docs referenced above. @rynowak - would really love to get your input here. Shouldn't the package restore process resolve a version of Mvc.Core that's compatible with all references (both direct and transitive) - i.e. Microsoft.AspNetCore.Mvc.Core 1.1.1. Am I missing something here?

**Comment by rynowak** [comment]
Did you clean after updating the version to 1.1.1? That's my understanding as well that it should resolve 1.1.1 of all of the MVC packages.

**Comment by domaindrivendev** [comment]
@rynowak - good call, cleaned out old bins and it worked as expected.

@withinfocus - as per comments above, I was able to run Swashbuckle.AspNetCore.1.0.0-rc1 in an application that referenced version 1.1.1 of Mvc Core. See dependencies config. above. Just remember to clean out old bins after upgrading Mvc Core to 1.1.1.

**Comment by withinfocus** [comment]
This was a dirty build on my part. Had to do some manual cleanup and then everything was fine. No issue. Sorry for the confusion!
