### ISSUE TITLE
System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly

### ISSUE THREAD

**Issue by SmutnyJan** [domaindrivendev/Swashbuckle.AspNetCore#2844]
I am trying to publish ASP.NET Core Web API to Azure with GitHub CI/CD. I am using completely default and generated WeatherForecast in .net 8.0. My problem is that GitHub actions fail everytime with following error:
[![github actions error][1]][1]

I also tried to update Swashbuckle.AspNetCore package, but the error persists.

Here is my repo with testing project: https://github.com/SmutnyJan/backend-testing
The workflow is generated by VS but there were still errors, so I had to change couple of things:
First error I encountered was that one:
[![release error][2]][2]
I thought this is caused by .gitignore file, so I started commiting <a href="https://github.com/SmutnyJan/backend-testing/commit/b8486e34adae69dfdb2c3a07d945347fa951553c">release folder</a> yet the problem still persisted. Then I realised it is searching for the dll file in wrong directory which is specified in yaml file. <a href="https://github.com/SmutnyJan/backend-testing/commit/10e8ccd76784fabfae1dd33578547d363a6604c4">So I made some adjustments aswell</a>. After that this problem with dll was fixed, but I got the error mentioned in title.
I hope it clarifies everything!

  [1]: https://i.sstatic.net/H5GxSIOy.png
  [2]: https://i.sstatic.net/H3lQJFHO.png

**Comment by martincostello** [comment]
I think this issue is related to the fact that your actions workflow is using different versions of .NET and Swashbuckle compared to your code:

https://github.com/SmutnyJan/backend-testing/blob/de3dd77407b647ef509ab9af95420de3a66b4fd2/.github/workflows/WebApplication120240430032308.yml#L14-L15

It seems you're trying to build a .NET 8 application with the .NET Core 3.1 SDK, which is not going to work.

**Comment by SmutnyJan** [comment]
Hm... that makes sense to me! But I still don't understand, where did I make mistake? I used "publish" in VS2022 and it generated everything for me... I am so sorry for my lack of knowledge. It's my first time publishing stuff on Azure.

**Comment by martincostello** [comment]
Sorry, what Visual Studio might be generating for you automatically and anything being published to Azure (and however that deployment is configured, App Service, AKS, a VM...) is outside the scope of our repo.

I suggest you ensure that your workflow and publishing use consistent .NET and package versions and try again.
