### ISSUE TITLE
IApplicationBuilder.UseSwaggerUi does not expose lambda-based config as documentation suggests

### ISSUE THREAD

**Issue by jholovacs** [domaindrivendev/Swashbuckle.AspNetCore#285]
Documentation says you can do this:
```
app.UseSwaggerUi(c =>
{
    ...
    c.InjectStylesheet("/swagger-ui/custom.css");
}
```
...but when trying this out:

![image](https://cloud.githubusercontent.com/assets/1767540/22399942/308a4944-e576-11e6-9c78-f84c53a788bd.png)

I'm using v6.0.0-beta902.

**Comment by withinfocus** [comment]
You'll want to move to the latest:

https://www.nuget.org/packages/Swashbuckle.AspNetCore/1.0.0-rc1

They broke the versioning so you won't automatically receive this.

**Comment by jholovacs** [comment]
Never would have guessed that.  Thanks!
