### ISSUE TITLE
[SwaggerGen] Asp.Versioning.ApiExplorer instead of [deprecated]Microsoft.AspNetCore.Mvc.ApiExplorer

### ISSUE THREAD

**Issue by charliex3** [domaindrivendev/Swashbuckle.AspNetCore#2854]
Looking at the master and 6.5.0 both still use Microsoft.AspNetCore.Mvc.ApiExplorer which got deprecated.
Would be nice if someone updated the repo to use Asp.Versioning library till the next version.

To be more specific, I'm using IOperationFilter from SwaggerGen and there's model ApiDescription from the deprecated library.

**Comment by martincostello** [comment]
This NuGet package is only referenced if you're [using the `netstandard2.0` version](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8cc68704b85fe5e534224ddb98c47763828bbf15/src/Swashbuckle.AspNetCore.SwaggerGen/Swashbuckle.AspNetCore.SwaggerGen.csproj#L22-L26) of the library, which is for .NET Framework users to use, which depends on Microsoft.AspNetCore.Mvc.ApiExplorer 2.1.0, [which is not obsolete](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.ApiExplorer/2.1.0).

ASP.NET Core 3.0 and later get access to ApiExplorer [through a FrameworkReference](https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore).
