### ISSUE TITLE
Update ASP.NET Core documentation for 6.6.1 release

### ISSUE THREAD

**Issue by martincostello** [domaindrivendev/Swashbuckle.AspNetCore#2857]
Raise a pull request to edit [getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-swashbuckle.md) once Swashbuckle.AspNetCore [6.6.1](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/19) is released to:

1. Remove the banner stating that .NET 8 is not supported.
2. Remove the reference to #1920.

See https://github.com/dotnet/AspNetCore.Docs/issues/32477#issuecomment-2099910191.

**Comment by captainsafia** [comment]
@martincostello Thoughts on updating the templates in 8.0 as well?

**Comment by martincostello** [comment]
@captainsafia Do you mean the versions referenced by the templates in dotnet/aspnetcore? If so I'm happy to do that if that meets the backport bar.

**Comment by captainsafia** [comment]
> @captainsafia Do you mean the versions referenced by the templates in dotnet/aspnetcore? If so I'm happy to do that if that meets the backport bar.

Yep, that's what I meant.  I think we can make the case for it given that .NET 8 is LTS and the lack of support for net8.0 in 6.5.0 is a blocker for build-time doc gen.

**Comment by martincostello** [comment]
OK cool - I'll do a PR for that tomorrow 👍

**Comment by cremor** [comment]
Maybe wait with the template update until 6.6.2 is released? Or even a bit longer to give people the chance to test the new version and report bugs.

**Comment by captainsafia** [comment]
> Maybe wait with the template update until 6.6.2 is released? Or even a bit longer to give people the chance to test the new version and report bugs.

Good point! Given the volume of changes that were merged over the past few weeks, it might be good to give things more bake time.

**Comment by cremor** [comment]
> Thoughts on updating the templates in 8.0 as well?

Is this actually feasible? I've just learned that no template changes for existing major .NET versions can be shipped without a "patching request" path and adding features/bumping versions would not meet the bar of value vs risk. Source: https://github.com/dotnet/test-templates/issues/388#issuecomment-2117461282

And .NET 9 templates will not include Swashbuckle at all (see dotnet/aspnetcore#54599).

**Comment by martincostello** [comment]
I'll give [6.6.2](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v6.6.2) a few days to bed-in, then if we don't get any big new issues from 6.6x I'll do the PR to the release/8.0 branch.

**Comment by cremor** [comment]
6.6.2 looks good and the documentation has already been updated. Will the templates be updated to 6.6.2 or do you want to wait for 6.7.0?

**Comment by martincostello** [comment]
Thanks for the reminder, I'd forgotten about this.

@captainsafia Looking [at the release/8.0 branch](https://github.com/dotnet/aspnetcore/blob/ba94792835910ce8d4ac066f051cc9b50cb3bca9/eng/Dependencies.props#L220) it seems like the templates are configured to always pull the latest version, so I don't think we actually need to do anything?

**Comment by cremor** [comment]
Isn't [this](https://github.com/dotnet/aspnetcore/blob/release/8.0/src/ProjectTemplates/Web.ProjectTemplates/WebApi-CSharp.csproj.in) the actual template file? That sets a version, and I think it gets it from [here](https://github.com/dotnet/aspnetcore/blob/release/8.0/eng/Versions.props#L324).
See also https://github.com/dotnet/aspnetcore/pull/47861

**Comment by martincostello** [comment]
Ah yes - clearly my Visual Studio Code search didn't find that.

**Comment by martincostello** [comment]
https://github.com/dotnet/aspnetcore/pull/56266.

**Comment by martincostello** [comment]
Closing this out as this is now only waiting on the linked external PR.
