### ISSUE TITLE
ConfigureOAuth2 requiers client secret (implicit flow)

### ISSUE THREAD

**Issue by ozonni** [domaindrivendev/Swashbuckle.AspNetCore#286]
I'm trying to integrate swagger ui with OAuth implicit flow which doesn't require client secret and seems like it's not even used if it's configured.

The question is, why is this setting is not optional?

**Comment by domaindrivendev** [comment]
Mainly because I want to have the server-side C# configuration match the swagger-ui JavaScript configuration semantics as much as possible. Just provide null if it's not required.
