### ISSUE TITLE
[cli] add option that would return api versions available

### ISSUE THREAD

**Issue by mieliespoor** [domaindrivendev/Swashbuckle.AspNetCore#2861]
When generating OAS docs using the cli, you need to pass in the api version (`swaggerdoc`)

```
swagger tofile --output [output] [startupassembly] [swaggerdoc]
```
In CI systems, the possible values for `swaggerdoc` mightn't be know unless this is passed in using a variable into the CI pipeline. It would be helpful if the cli could provide an option that would return all the available swaggerdoc values in a string array which could then be used by subsequent cli calls to generate the OAS docs.

**Comment by martincostello** [comment]
What's the use case here? Is it because you want to generate "one of each"?

If a v4 was suddenly added, would you want to unconditionally generate a file with it when you upgraded to that version?

**Comment by mieliespoor** [comment]
We have to submit every OAS to 42Crunch for security scans. At this moment, we have a variable in the CI pipeline where the dev team would specify all the documents that exist so that we could generate these OAS's and submit to 42Crunch. 

The idea is that if the cli here could tell us what documents are available, we could simply call that and generate what we want/need.

**Comment by martincostello** [comment]
The documents available are the ones you generate - you don't have to generate everything that's possible to do so.
