### ISSUE TITLE
[Feature request]: Add descriptions for more HTTP status codes

### ISSUE THREAD

**Issue by cremor** [domaindrivendev/Swashbuckle.AspNetCore#2871]
### Is your feature request related to a specific problem? Or an existing feature?

I've noticed that the HTTP status code 422 has the description "Client Error" by default. I'd expect it to be "Unprocessable Entity".
Seems like "Client Error" is the default description for all 4xx HTTP status codes that don't have a better description.

### Describe the solution you'd like

Please update the default HTTP status code description list. A good source seems to be https://github.com/dotnet/aspnetcore/blob/main/src/Http/WebUtilities/src/ReasonPhrases.cs

**Comment by cremor** [comment]
Thanks. I could create a PR. Should I take all status codes from https://github.com/dotnet/aspnetcore/blob/main/src/Http/WebUtilities/src/ReasonPhrases.cs or do you want a shorter list?

**Comment by martincostello** [comment]
Let's just add any that are missing which are [in the HTTP Semantics RFC](https://www.rfc-editor.org/rfc/rfc9110.html#name-status-codes) (so, for example, not 418 or 499).

If there's any you think are sensible to add even though they aren't in the RFC (for example 429 isn't), then we can add those too.
