### ISSUE TITLE
Could not load file or assembly 'Swashbuckle.AspNetCore.Swagger'

### ISSUE THREAD

**Issue by FlorianLabranche** [domaindrivendev/Swashbuckle.AspNetCore#2878]
### Describe the bug

Using version 6.6.1, I have an exception when I run the following command in an Azure pipeline.

### Command:
```
dotnet swagger tofile --output $(System.DefaultWorkingDirectory)/apim/artifacts/apis/dms-api/specification_v1.json bin/Release/net6.0/MyAPI.dll v1
```

### Expected behavior

Should run fine like in version 6.5.0

### Actual behavior

Throw exception

### Steps to reproduce

Run command 
```
dotnet swagger tofile --output <path> MyAPI.dll v1
```

### Exception(s) (if any)

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Swashbuckle.AspNetCore.Swagger, Version=6.6.1.0, Culture=neutral, PublicKeyToken=62657d7474907593'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Swashbuckle.AspNetCore.Swagger, Version=6.6.1.0, Culture=neutral, PublicKeyToken=62657d7474907593'
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in /_/src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in /_/src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in /_/src/Swashbuckle.AspNetCore.Cli/Program.cs:line 141
```

### Swashbuckle.AspNetCore version

6.6.1

### .NET Version

.Net 6

**Comment by martincostello** [comment]
Any chance you could provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue? It would make it easier/faster for us to investigate and fix.

**Comment by martincostello** [comment]
Also, does this help? https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2651#issuecomment-1882968072

**Comment by martincostello** [comment]
I can't see any obvious differences in the package contents between [6.5.0](https://nuget.info/packages/Swashbuckle.AspNetCore.Cli/6.5.0) and [6.6.1](https://nuget.info/packages/Swashbuckle.AspNetCore.Cli/6.6.1).

Does your project consistently use v6.6.1 everywhere, so for example, isn't picking up references to a different version in your application's output directory?

**Comment by incongruousm** [comment]
> Does your project consistently use v6.6.1 everywhere, so for example, isn't picking up references to a different version in your application's output directory?

I had this problem, and a dependency elsewhere on 6.5.0 was the cause. Adding the 6.6.1 package directly to my project resolved the issue.

**Comment by FlorianLabranche** [comment]
Thanks for the hint !
Indeed, pipeline was using latest cli version but code still had dependency over older swashbuckle versions.

**Comment by rwb196884** [comment]
This is causing 6.7.3 to fail. Have to use 6.6.1 instead.
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Swashbuckle.AspNetCore.Swagger, Version=6.7.3.0, Culture=neutral, PublicKeyToken=62657d7474907593'. The system cannot find the file specified.
File name: 'Swashbuckle.AspNetCore.Swagger, Version=6.7.3.0, Culture=neutral, PublicKeyToken=62657d7474907593'
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in /_/src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in /_/src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in /_/src/Swashbuckle.AspNetCore.Cli/Program.cs:line 159
```

**Comment by martincostello** [comment]
Ensure that all your references, including transient ones, are using the same version of Swashbuckle.
