### ISSUE TITLE
byte type is recognized as string

### ISSUE THREAD

**Issue by xperiandri** [domaindrivendev/Swashbuckle.AspNetCore#289]
I have `[FromForm, Required] byte licenseZone` parameter
And it's recognized as string
![image](https://cloud.githubusercontent.com/assets/2365592/22448385/bb3b0528-e761-11e6-9277-c7329d5670bf.png)

**Comment by erendrake** [comment]
Please check out the swagger spec for standard types http://swagger.io/specification/.  byte is serialized as a string with a 'format' of byte. What are you seeing in your swagger.json? 

I dont think json even has a byte value for swagger to use other than big64

**Comment by domaindrivendev** [comment]
This seems correct to me. You're describing a JSON API and JSON does not have a type "byte". As per JSONSchema, a field can be of type null, string, boolean, number, array or object.

**Comment by xperiandri** [comment]
Thanks, @erendrake. That is interesting decision.
OK, @domaindrivendev, is there a mechanism to override a time? Or IOperationFilter is my choice for this task, isn't it?

**Comment by domaindrivendev** [comment]
I'm closing this issue as, according to the Swagger spec., bytes should be described as type=string and format=byte which is exactly what SB is doing.
