### ISSUE TITLE
Should options.IncludeXmlComments(xmlFile) throw an exception if xml file is not found?

### ISSUE THREAD

**Issue by ericvb** [domaindrivendev/Swashbuckle.AspNetCore#290]
It is not really an issue, more an open question.

In the current version, if you use Swagger and for some reason the xml file is not found, you get an Internal Server Error in case of a webapp. That's because Swagger throws an exception if the file is not found.

I had some integration tests running using the TestServer from Microsoft (https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing#integration-testing).
After the implementation of Swagger, these tests did stop running giving me some strange error complaining about some data not found in the TestFixture.
Finally I found that in the Integration test project, there was no XML file present, causing the strange error.
So I adapted the code in the Startup.cs file to test first if the xml file is present, and only if it exists, adding it.

```
            services.AddSwaggerGen();

            services.ConfigureSwaggerGen(options =>
            {
                // add check if xml file exist, otherwise swagger will throw an exception and block everything
                string xmlFilePath = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath,PlatformServices.Default.Application.ApplicationName + ".xml");
                if (File.Exists(xmlFilePath))
                {
                    options.IncludeXmlComments(xmlFilePath);
                }
            });
```
So the question that comes up, why Swagger throws an exception?
In my opinion it should silently continue, adding maybe a log entry as warning, but not block the app.
Swagger is an usefull addon, but not a critical block of code that has the right of blocking completely your app in case of a missing xml file.
Or is it me, that is missing something in the whole story :-) ?

**Comment by Igmat** [comment]
Sometimes human-readable descriptions in swagger are required (e.g. some API that has no other documentation and would be used by external developers). In that case silent fail wouldn't be an option.
Also, `IncludeXmlComments` describes developers intention very clearly and missing of xml comments in generated docs will be surprising.
But, I agree that often they are unnecessary. Your snippet looks good for that case and doesn't contain a lot of code, so it could be used as is.
@domaindrivendev, IMO it make sense to add `TryIncludeXmlComments` method for handling such situations even clearly then with snippet above. What do you think?

**Comment by domaindrivendev** [comment]
@ericvb - we'll have to agree to disagree. I'm philosophically opposed to defensive programming, especially trapping errors that are "unexpected" - regardless of being part of an add-on or core functionality. If a developer has included the call to _IncludeXmlComments_ but hasn't thought about whether the specified file is present in various environments then IMO that's a bug and is better surfaced so it can be fixed.

**Comment by ericvb** [comment]
I agree that trapping "unexpected" errors is not a good programming philosophy, but the proposed `TryIncludeXmlComments` let's the using programmer the choice, in my eyes a better solution.
But for me this was just an open question, not a critical point :-)
