### ISSUE TITLE
[Bug]: C#9 positional Record with xmldoc containing param-tag without example property, generates unexpected 'example=""' for types with "string" json type

### ISSUE THREAD

**Issue by stb-co** [domaindrivendev/Swashbuckle.AspNetCore#2900]
### Describe the bug

We recently tried updating from 6.5.1 to 6.6.1 but had to put it off because we started seeing a bunch of these warnings in the OpenApiDiagnostics object being returned when generating the swagger doc
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/93922970/51666681-96dc-40fa-abd6-291c97e7b403)

The problematic part of the schema was reported to be the generated 'examples' taken from the xmldoc of the start|end property of the record:
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/93922970/dae61e95-cf5f-4ad2-8b5c-685dae678579)

We could see that it happened for Records using positional syntax with **DateTime** fields and an xmldoc with a **param** tag _without_ the **example** property, like so:
```c#
/// <summary>
/// Some Request DTO
/// </summary>
/// <param name="IncludeSomething">Include a thing</param>
/// <param name="UserIds">Ids of users</param>
/// <param name="Start">Start date of something</param>
/// <param name="End">End date of something</param>
public sealed record SomeRequestDto(
    bool IncludeSomething,
    List<string> UserIds,
    DateTime Start,
    DateTime End);
```

The same behaviour is present for `Bool`, `Guid` and `string`.

### Expected behavior

The swagger doc should not contain empty schema 'examples' when the source records contains param tags without an example property.

### Actual behavior

The swagger doc contains empty schema 'examples' even though the source records do not contain the example property in their param tags.

### Steps to reproduce

Add an endpoint accepting a Record like this:

```c#
/// <summary>
/// Some Request DTO
/// </summary>
/// <param name="IncludeSomething">Include a thing</param>
/// <param name="UserIds">Ids of users</param>
/// <param name="Start">Start date of something</param>
/// <param name="End">End date of something</param>
public sealed record SomeRequestDto(
    bool IncludeSomething,
    List<string> UserIds,
    DateTime Start,
    DateTime End);
```

Call the Swagger endpoint and check the Warnings in the OpenApiDiagnostics of the result.
Check the generated Schema and observe there being empty examples.

### Swashbuckle.AspNetCore version

6.6.1

### .NET Version

net8.0

### Anything else?

I've tracked the issue down to [this line](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/828b7df2ac697d4b3b513d42a17cad152ad9f2e6/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs#L52) which is using [this method](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xpath.xpathnavigator.getattribute?view=net-8.0#returns).
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/93922970/4a27d5b6-ad34-474a-95d7-582a49a78de2) It returns `string.Empty` when the example propery isn't found, which causes the [`TrySetExample`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/828b7df2ac697d4b3b513d42a17cad152ad9f2e6/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs#L67-L73) method to set the empty string as the example.

I can't think of a situation where it is ever desired for this method to allow an empty string anyway, so it should be easily fixed by replacing the `example == null` check with `string.IsNullOrEmpty(example)`

I can push a fix along with a test covering the problem, if desired :)

**Comment by martincostello** [comment]
@stb-co A PR to fix would be welcome if you can do it today, otherwise I'll look at it so it can be included in our next release which we're looking to do ASAP.

**Comment by martincostello** [comment]
I think it would be safer (as in, not changing existing behaviour for non-records) to put the check before calling `TrySetExample()` on line 53, rather than changing the behaviour for everything.

**Comment by stb-co** [comment]
@martincostello Alright, that makes sense. I'll make a PR with the fix immediately :)

**Comment by martincostello** [comment]
Thanks for reporting this issue - the fix is available in [Swashbuckle.AspNetCore 6.6.2](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v6.6.2).
