### ISSUE TITLE
SwaggerUi name not following naming conventions

### ISSUE THREAD

**Issue by epsitec** [domaindrivendev/Swashbuckle.AspNetCore#291]
The name `SwaggerUi` should be written `SwaggerUI` in order to follow the _least surprise principle_ for .NET developers, since [two letter acronyms should be writen in uppercase](https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx) as explained in the [Capitalization Conventions](https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx).

I understand it is a breaking change, but it might still be early enough in the life of the project to make these changes now. This will serve all future users of `Swaschbuckle`.

**Comment by domaindrivendev** [comment]
I'm all for adhering to conventions but in this case, I'm inclined to say we just live with it. It will be a breaking change that will likely frustrate many of the early adopters. Furthermore, changing the case in the package name could lead to undesired behavior throughout the Nuget ecosystem - http://adamralph.com/2015/03/04/nuget-gallery-casing-woes.

Principles & practices are great and they add massive value to the software community. But, I've been at this long enough to also view them pragmatically, keep sight of the "WHY" and understand the trade-offs in every situation.

When you say "This will serve all future users of Swashbuckle", I'd like to understand some specific scenarios where this change would actually help a developer incorporate Swashbuckle into their application. To be honest, I can't think of too many concrete examples and therefore, IMO, the cons currently outweigh the pros.

But then again, I can always be swayed with the right argument :)

**Comment by xperiandri** [comment]
As ASP.NET Core package is still in RC it is not a big deal to do that in my opinion

**Comment by epsitec** [comment]
What I meant by _this will serve all future users of Swashbuckle_ is that the principle of least
surprise (or reducing WTFs/minute) is important for a library.

**Comment by epsitec** [comment]
I feel that we can live with the unchanged (and only partially consistent) package name, as file name casing is something (usually) handled by the tools. And Visual Studio is not case sensitive when searching for a NuGet package.

**Comment by domaindrivendev** [comment]
@epsitec - you sowed the seed and it started to niggle at me :) In the end, I made the change but not without some case-sensitive file rename gotchas. What should have been 1 commit became 4 ...

4bbf5cacd6ad0817b9015d699c559fd5c1cedf0d
b1c718f70305c8c657e11009472c507aa1a9fa70
b8334b1098bdf05ca1cea5d7dcebee105dffd439
0cd8487fd80e262b41c37040f2d52195569fcd4b

Before the next official release, I would really appreciate if you could upgrade to the preview version that's available on MyGet and make sure everything works as expected:

Swashbuckle.AspNetCore 1.0.0-preview-0109

Let me know

**Comment by domaindrivendev** [comment]
Just released https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/1.0.0-rc2

**Comment by epsitec** [comment]
Thank you very much. I love the new names :-) they make me very happy every time I see them!
