### ISSUE TITLE
[Bug]: "InvalidOperationException: Sequence contains more than one matching element" in Swagger when using multiple [FromForm] parameters in Minimal API

### ISSUE THREAD

**Issue by marcominerva** [domaindrivendev/Swashbuckle.AspNetCore#2912]
### Describe the bug

I have originally posted the issue in the ASP.NET Core repo: https://github.com/dotnet/aspnetcore/issues/53831. See in particular this comment: https://github.com/dotnet/aspnetcore/issues/53831#issuecomment-1930720704

### Expected behavior

Swagger should not throw an exception.

### Actual behavior

An `InvalidOperationException` is thrown.

### Steps to reproduce

Minimal repro here: https://github.com/marcominerva/FromFormBindingIssue

### Exception(s) (if any)

InvalidOperationException: Sequence contains more than one matching element
System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
System.Linq.Enumerable.TryGetSingle(IEnumerable source, Func<TSource, bool> predicate, out bool found)
System.Linq.Enumerable.SingleOrDefault(IEnumerable source, Func<TSource, bool> predicate)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOpenApiOperationFromMetadata(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### Swashbuckle.AspNetCore version

6.6.1

### .NET Version

8.0.5

**Comment by jgarciadelanoceda** [comment]
Reviewing this item it seems to be due to this PR. #2441. For MinimalApis the Schema is being generated:
```javascript
"multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Person"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/Person"
              }
            }
``` 
This code block (The ref is not build for controllers because the controllers do not have the OpenApiOperation attribute)

I am right now working on a fix to make the FromForm request with several of them work again

**Comment by jgarciadelanoceda** [comment]
@martincostello you can close this issue
