### ISSUE TITLE
[Bug]: FromRoute parameter only binds directly on method signature, not when nested in request record

### ISSUE THREAD

**Issue by RasmusEdvardsen** [domaindrivendev/Swashbuckle.AspNetCore#2921]
### Describe the bug

I am capturing a request data from query and route in a request object, but it seems the string interpolation messes up, as it just sends the string template further, and not the actual value. 

Code that doesn't work (id is bound inside request record):

```
[HttpGet("{id}")]
public async Task<ActionResult<GetDocumentResponse>> GetDocument(GetDocumentRequest request)
```

Code that works:
```
[HttpGet("{id}")]
public async Task<ActionResult<GetDocumentResponse>> GetDocument(string id)
```

Thanks!

### Expected behavior

Route parameters are interpreted as interpolatable by swagger, and will, when using the UI or code generated API, fill in the value in the interpolated part of the string

### Actual behavior

Nothing is put into the interpolated template of the string, and something like "entities/{id}/file-url" is sent instead of "entities/actual-id-123/file-url".

### Swashbuckle.AspNetCore version

6.6.2

### .NET Version

net8.0

**Comment by RasmusEdvardsen** [comment]
On further examination, this actually works if the [FromRoute] decorator within the request record has a Name attribute specified, like so:

`[FromRoute(Name = "id")]`

I was under the impression that this would be inferred somehow - or is this indeed the intended behavior?

**Comment by jgarciadelanoceda** [comment]
@RasmusEdvardsen. The issue that you are describing here should be fixed just by adding [FromRoute] on the object property.
But if you do that, you have to specify the Route as Id instead of id( It's case sensitive)

**Comment by RasmusEdvardsen** [comment]
@jgarciadelanoceda Ah I see, that might be what I'm referring to in my latest comment. If you ask me my personal preference, I'd just want it to work the same way it does as if it was specified directly on the controller parameter. If it already does, I apologize for taking time out of your schedule. Thanks for a good project, btw.

**Comment by jgarciadelanoceda** [comment]
I'll look at this feature, because it seems to be a issue of the library although with dotnet 8 you will have the issue 
dotnet/aspnetcore#54212. It's a nice to have case insensitive on the Route parameters

**Comment by RasmusEdvardsen** [comment]
Agreed - and yea, it does seem like the issue you linked pertains to this issue. I went around it the dirty way - suppressing the warning.

**Comment by jgarciadelanoceda** [comment]
@RasmusEdvardsen. The issue that you are describing here should be fixed just by adding [FromRoute] on the object property.
But if you do that, you have to specify the Route as Id instead of id( It's case sensitive).

I think that when this issue is solved, we could handle swagger-api/swagger-ui#8143

**Comment by RasmusEdvardsen** [comment]
Alright, sounds good, thanks. I'll close this, and let's hope the linked issue will be fixed soon 👍

**Comment by RasmusEdvardsen** [comment]
@jgarciadelanoceda do you want me to close this for now? I realised I should've asked you first, as you have linked this one in [https://github.com/swagger-api/swagger-ui/issues/8143](https://github.com/swagger-api/swagger-ui/issues/8143)

**Comment by jgarciadelanoceda** [comment]
As you please, I showed that it has linked a PR that has been active for 3 years, but I hope they merge it

**Comment by RasmusEdvardsen** [comment]
Okay, I'll close it. Thanks
