### ISSUE TITLE
[Bug]: Swagger Page response Json result error

### ISSUE THREAD

**Issue by China-Mr-zhong** [domaindrivendev/Swashbuckle.AspNetCore#2923]
### Describe the bug

![111](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/46012747/bfa2da9b-1f08-4590-8a40-1ebcf3a82b79)
[api_res.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/15479795/api_res.txt)
[swaggar_res.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/15479796/swaggar_res.txt)

### Expected behavior

Consistent with the interface response

### Actual behavior

Inconsistent results

### Swashbuckle.AspNetCore version

6.6.2

### .NET Version

net8.0

**Comment by martincostello** [comment]
This looks like an upstream issue in ASP.NET Core: https://github.com/dotnet/aspnetcore/issues/52393

If it isn't and is an issue in Swashbuckle, we'll need a reproducible sample of code that generates these responses.

**Comment by China-Mr-zhong** [comment]
This is because the Json serialization long type precision loss problem, implement custom conversion to string type, has been solved, this is not a bug, please close it. Sorry
