### ISSUE TITLE
Swagger ui configuration

### ISSUE THREAD

**Issue by piniSolomon** [domaindrivendev/Swashbuckle.AspNetCore#293]
Hey,
I want to config the swagger ui to work with authentication, I tried to follow the example from Oauth flow
`app.UseSwaggerUi(c =>
{
    ...
    // Provide client ID, client ID, realm and application name
    c.ConfigureOAuth2("swagger-ui", "swagger-ui-secret", "swagger-ui-realm", "Swagger UI");
}`
The thing is I don't have an overload that takes action only two strings
baseRoute, SwaggerURL

**Comment by erendrake** [comment]
What version of the Swashbuckle.AspNetCore package are you using? i had the same problem yesterday and I had to update to 1.0.0-rc1 to get the overload

**Comment by domaindrivendev** [comment]
The readme now corresponds to Swashbuckle.AspNetCore.1.0.0-rc1
