### ISSUE TITLE
[Bug]: 6.6.2 doesn't accept Assembly in the param in IncludeXmlComments

### ISSUE THREAD

**Issue by janzenz** [domaindrivendev/Swashbuckle.AspNetCore#2935]
### Describe the bug

According to the documentation here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore?tab=readme-ov-file#include-descriptions-from-xml-comments

`IncludeXmlComments` should accept Assembly as a parameter but in the latest version 6.6.2 as of this writing isn't exposing this new method.

### Expected behavior

IncludeXmlComments should accept Assembly as param as mentioned in the instructions.

### Actual behavior

It doesn't accept Assembly and the IDE complains that this method doesn't have this override.

### Steps to reproduce

- Download 6.6.2
- Follow the instructions mentioned here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore?tab=readme-ov-file#include-descriptions-from-xml-comments
- IDE complains that this method doesn't accept the Assembly param

### Swashbuckle.AspNetCore version

6.6.2

### .NET Version

8.0

**Comment by martincostello** [comment]
@leotsarev Could you do a PR to tweak the README to note that this feature is available from v6,7.0 please?

**Comment by leotsarev** [comment]
I'm sorry for inconvenience. Missed bug. I think now that 6.7 have been released, it's no point to add this information.

**Comment by martincostello** [comment]
Is it _fixed_ in 6.7.0? If not, the information is still useful.

**Comment by leotsarev** [comment]
The problem is that README recommends method that was added only in 6.7.0

**Comment by martincostello** [comment]
That's not a problem - 6.7.0 is the latest released version and that's what we recommend people use.

If 6.7.0 resolved the ask, we can close this issue. If it didn't, then we need more information to action it.

**Comment by leotsarev** [comment]
should be closed
