### ISSUE TITLE
ASP.Net API Versioning injection

### ISSUE THREAD

**Issue by markgould** [domaindrivendev/Swashbuckle.AspNetCore#294]
When using ASP.Net Api Versioning and specifying a route parameter shown below, Swashbuckle generates the Swagger json requiring a version parameter to be specified. Is it possible for Swashbuckle to understand this and write the version into the URL? 

**Controller:**
`[ApiVersion("1")]`
`[Route("api/v{version:apiVersion}/[controller]")]`

**Outputted json:**
`"paths":{"/api/v{version}/ControllerName"`

**Comment by domaindrivendev** [comment]
This is pretty much a dup of #244. Also check out the multiple versions example site - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/MultipleVersions/Startup.cs which does exactly what you're looking for
