### ISSUE TITLE
Intercept SwaggerGenerator.GetSwagger() to override paths

### ISSUE THREAD

**Issue by rh072005** [domaindrivendev/Swashbuckle.AspNetCore#295]
I've been following Issue #244 and am trying to work with ```MapToApiVersion```. I've noticed that ```CreatePathItem``` within ```SwaggerGenerator``` throws an error because duplicate paths with the same method can exist. 
Using the [example from the documentation](https://github.com/Microsoft/aspnet-api-versioning/wiki/Versioning-via-the-URL-Path#aspnet-core) this appears to be because the templates are still in the paths e.g. api/v{version}/helloworld. 
Is there any way I can modify the paths object in the API descriptions so that I can replace the templates prior to calling ```CreatePathItem``` and consequently not throw the overloaded method error or failing that another way to work around the issue.

**Comment by domaindrivendev** [comment]
Did you define multiple Swagger documents (i.e. one per API version) and wire up the _DocInclusionPredicate_ to only include the relevant actions for each version ... pretty much as described here  https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/244#issuecomment-276595734

I believe you're getting the error because multiple actions with the same path, but for a different version, are being selected for a single Swagger document.

**Comment by rh072005** [comment]
Yeah I've defined multiple documents using that code example.
Is the problem that the mapped methods are effectively being added to the wrong Swagger document?
i.e. HelloWorld2Controller.Get and HelloWorld2Controller.GetV3 are both being added to the V2.0 document instead of Get to V2.0 and GetV3 to V3.0?

If that's the case I'm guessing I can remove methods based on ```MapToApiVersionAttribute``` rather than have to modify the paths as part of the pipeline.

I'll give that a try

**Comment by rh072005** [comment]
That seems to work. I'm now returning false from the Doc Inclusion Predicate if the controller and action versions intersect.

```csharp
swaggerOptions.DocInclusionPredicate((version, apiDescription) =>
{
    var actionVersions = apiDescription.ActionAttributes().OfType<MapToApiVersionAttribute>().SelectMany(attr => attr.Versions).ToList();
    var controllerVersions = apiDescription.ControllerAttributes().OfType<ApiVersionAttribute>().SelectMany(attr => attr.Versions).ToList();
    var controllerAndActionVersionsOverlap = controllerVersions.Intersect(actionVersions).Any();
    if(controllerAndActionVersionsOverlap)
    {
        return false;
    }
    return controllerVersions.Any(v => $"v{v.ToString()}" == version);
});
```
