### ISSUE TITLE
[Question]: How to enumerate values a string can take on?

### ISSUE THREAD

**Issue by RPGillespie6** [domaindrivendev/Swashbuckle.AspNetCore#2961]
### What are you wanting to achieve?

I have a string property on a POST body that can take on the values "cGy", "Gy", "%", or "cc"

I can't figure out a way to get swashbuckle to generate docs for that.

### What code or approach do you have so far?

The closest I've come is using an enum and enabling enum strings setting:
```
    public enum ConstraintUnit
    {
        Gy,
        cGy,
        Percent,
        cc,
    }
```
However, that required me to spell out "Percent" instead of using "%".

Is there a way I can just do:
```
[SwaggerEnum(["cGy", "Gy", "%", "cc"])]
public string unit {get; set}
```

or something like this?

**Comment by martincostello** [comment]
Which serializer are you using?

For example with Newtonsoft.JSON you can do something like this: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/f6c1e312b892138e3691f3ca24e24c2eab1510a1/test/Swashbuckle.AspNetCore.Newtonsoft.Test/Fixtures/JsonConverterAnnotatedEnum.cs#L12

**Comment by RPGillespie6** [comment]
Yes, brilliant, this is _exactly_ what I was looking for, just was having a hard time find it. Thank you very much!
