### ISSUE TITLE
[Bug]: attributes are moved to allOf instead of in the root of an object after updating from 6.5.0 to 6.6.2

### ISSUE THREAD

**Issue by DerGary** [domaindrivendev/Swashbuckle.AspNetCore#2964]
### Describe the bug

The left side is generated through swagger cli with version 6.5.0 of the library, and the right sight is generated after updating to 6.6.2:
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/4302467/e67dc8b1-6217-4f42-b2c6-5f8e6178ea15)
When this is now used to generate a client from it it contains the following properties:
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/4302467/77153f8d-37d2-4606-a485-9d6768dc51ce)

### Expected behavior

Left Side

### Actual behavior

Right Side

### Steps to reproduce

Create an empty type that inherits from a base class. We are using `UseOneOfForPolymorphism` as well as:

```
[SwaggerDiscriminator(ConnectionType.TypeDiscriminatorPropertyName)]
[SwaggerSubType(typeof(HttpConnectionConfigDto), DiscriminatorValue = ConnectionType.Http)]
```

### Swashbuckle.AspNetCore version

6.6.2

### .NET Version

net8.0

**Comment by martincostello** [comment]
We don't explicitly write out the JSON, we delegate it to [Microsoft.OpenApi](https://github.com/microsoft/OpenAPI.NET). That dependency was updated to the latest release (1.6.14) as part of the 6.6.x release (#2795), so I would have thought that if this is a bug, it should be logged there.

**Comment by DerGary** [comment]
Okay, is there anything that I need to do?

**Comment by martincostello** [comment]
I would suggest opening an issue in [their repo](https://github.com/microsoft/OpenAPI.NET/issues/new/choose).

**Comment by serhiiz** [comment]
Turns out it's now the expected behavior: #2268
