### ISSUE TITLE
[Question]: How to tell SwaggerUI using "Standard Query Parameters" instead of "JSON-encoded Query Parameters" with GET method?

### ISSUE THREAD

**Issue by nighttiger1990** [domaindrivendev/Swashbuckle.AspNetCore#2970]
### What are you wanting to achieve?

I have an endpoint like this:
```C#
public async Task GetExaminationRegisterPayments([FromQuery] List<FilterItem> filterModel){
  //do something
}
```

```C#
public class FilterItem
{
    public string Field { get; set; }
    public string Value { get; set; }
    public string Operator { get; set; }
}
```

That endpoint work successfully with this Url (Chat GPT tell this mean `Standard Query Parameters` )
```
https://localhost:5000/api/test?filterModel[0].field=refId&filterModel[0].value=123&filterModel[0].operator===
```

But when I used SwaggerUI
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/21042933/984f5e84-76d4-4cb0-9d27-8bd2bc8526a6)
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/21042933/71fe30b8-2d13-4c33-bf08-ee4d81a7c339)

That endpoint work but value of filterModel always is Empty with this Url (ChatGPT tell this mean `JSON-encoded Query Parameters`)
```
https://localhost:5000/api/test?filterModel=%7B%0A%20%20%22field%22%3A%20%22refId%22%2C%0A%20%20%22value%22%3A%20%22123%22%2C%0A%20%20%22operator%22%3A%20%22%3D%3D%22%0A%7D
```

How to tell SwaggerUI using "Standard Query Parameters" instead of "JSON-encoded Query Parameters"?

### What code or approach do you have so far?

```C#
public async Task GetExaminationRegisterPayments([FromQuery] List<FilterItem> filterModel){
  //do something
}
```

```C#
public class FilterItem
{
    public string Field { get; set; }
    public string Value { get; set; }
    public string Operator { get; set; }
}
```

```
https://localhost:5000/api/test?filterModel[0].field=refId&filterModel[0].value=123&filterModel[0].operator===
```

```
https://localhost:5000/api/test?filterModel=%7B%0A%20%20%22field%22%3A%20%22refId%22%2C%0A%20%20%22value%22%3A%20%22123%22%2C%0A%20%20%22operator%22%3A%20%22%3D%3D%22%0A%7D
```

**Comment by jgarciadelanoceda** [comment]
I do not know really and I have tried several ways.

- Put the style "form"
- Put the style "form" and explode true (This is not supported in OpenApi.Net but I tricked it with app.MapGet exposing the OpenApi document with the properties I wanted)
- Put the style "deepObject"
- Put the style "deepObject" and explode true
- Put the Content as multipartFromData and the schema inside the item
I do not know what's the correct way to expose this Query parameter so Swagger-Ui formats them in the way you expected, so I suggest you open a Issue on that repo
