### ISSUE TITLE
[Bug]: CSS related operationId name is breaking line

### ISSUE THREAD

**Issue by WKnak** [domaindrivendev/Swashbuckle.AspNetCore#2978]
### Describe the bug

It was detected on version 6.6.1 and 6.6.2 that operationId description is now presented breaking the line as you can see in the screenshot below. The version 6.5.0 is working find, I did a Ctrl+F5 after downgrading to refresh the CSS and it works. 

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/5892364/918dc103-f56e-401f-b7a5-a8749338a745)

### Expected behavior

Do not break line of have space to display operationId on the right.

### Actual behavior

The operationId name is breaking into the next line.

### Exception(s) (if any)

// add customOperationIds with AddSwaggerGen

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
    options.CustomOperationIds(selector =>
    {
        var httpVerb = selector.HttpMethod?.ToSentenceCase();
        var controllerName = ((ControllerActionDescriptor)selector.ActionDescriptor).ControllerName;
        var actionSuffix = GetActionSuffix(selector);
        return $"{httpVerb}{controllerName}{actionSuffix}";
    })
);

### Swashbuckle.AspNetCore version

6.6.2

### .NET Version

8.0.202

**Comment by martincostello** [comment]
The CSS comes from swagger-ui which we redistribute.

The difference between the versions of Swashbuckle is which version was included.

This is either a bug in swagger-ui, which you should report to them and we will pick up at some point when fixed, or it's an implementation detail you depended on which had no guarantees of stability and you will need to work around with custom CSS of your own.
