### ISSUE TITLE
Supporting 'N' Number of Dynamic Query Parameters

### ISSUE THREAD

**Issue by RehanSaeed** [domaindrivendev/Swashbuckle.AspNetCore#298]
I have the following scenario where the following action can accept 'N' number of query parameters with a non-predetermined name and value i.e. I have no idea what query parameters someone might pass in.

```
[HttpGet("foo")]
public Task<IActionResult> Foo([FromQuery] string firstParameter)
{
    var firstParameterSplit = firstParameter == null ? null : firstParameter.Split(',');
    var remainingDynamicParameters = 
        this.Request.Query.ToDictionary(x => x.Key, x => x.Value.ToString());
    
    // Do Something
}
```

Right now, Swashbuckle only lists `firstParam` and has no way of knowing about the other dynamic query parameters. The ideal scenario would be a button that lets my dynamically add text boxes to enter extra query parameters. Failing that, a single text box that lets me add a raw query string e.g. `foo=bar&baz=mar`. How can this be achieved?

There is no model binding to support this scenario in ASP.NET Core, so I raise issue https://github.com/aspnet/Mvc/issues/5770.

**Comment by domaindrivendev** [comment]
As SB is 100% driven by the [Swagger Specification](http://swagger.io/specification/), you'll need to figure out how this scenario would be described in Swagger. I'm not sure so you'll need to research that yourself. Once you know that, I may be able to help in getting SB to generate that Swagger.

**Comment by RehanSaeed** [comment]
Here are the links to an issue and PR that implement this feature:

Issue: https://github.com/OAI/OpenAPI-Specification/issues/349
PR: https://github.com/OAI/OpenAPI-Specification/pull/804

**Comment by erendrake** [comment]
I don't think implementing any OSI features makes sense until they have an official release. I would love to add hypermedia features and all kinds of others neat stuff but until there is a stable target the risk is quite high. Just my $0.02

**Comment by RehanSaeed** [comment]
Thats perfectly reasonable. How long is the review process until 3.0 comes out?

**Comment by erendrake** [comment]
the latest blog post shows a 'first Implementer Draft' that is scheduled for February 28, 2017.

https://www.openapis.org/blog/2017/01/24/a-new-year-a-new-specification

that being said i am not in charge of anything either in OpenApi or Swashbuckle so dont take anything I say as an official schedule

**Comment by darrelmiller** [comment]
@erendrake Implementer's Draft is ready.  You can now describe freeform query parameters by setting `style` to `form` and `explode` to 'true' and setting the parameter value to an object or map.

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#style-examples

**Comment by erendrake** [comment]
@darrelmiller like I said @domaindrivendev is the swashbuckle maintainer so they will set the pace on adoption of the new standard. I am excited to see that the spec is ready to start implementing!

**Comment by domaindrivendev** [comment]
Closing in favor of #419
