### ISSUE TITLE
[Bug]: Record nullable property (reference type) not marked as nullable in generated open api specification

### ISSUE THREAD

**Issue by panky98** [domaindrivendev/Swashbuckle.AspNetCore#2987]
### Describe the bug

I have a record which have nullable reference type property:
![image](https://github.com/user-attachments/assets/d39de473-cba8-42dd-866c-f837069cd039)

In generated open api specification that property is not marked as nullable:
![image](https://github.com/user-attachments/assets/8b0b50d6-b9e7-4d87-b154-3d488c7dff3e)

### Expected behavior

Property to have nullable: true

### Actual behavior

Property is not marked as nullable.

### Swashbuckle.AspNetCore version

6.2.3

### .NET Version

7.0

### Anything else?

/

**Comment by martincostello** [comment]
Please update to the latest release of Swashbuckle.AspNetCore, [6.6.2](https://www.nuget.org/packages/Swashbuckle.AspNetCore/6.6.2), and see if this is still an issue or not.

**Comment by panky98** [comment]
Hi @martincostello, thanks for suggestion. I have already tried that, still the same thing unfortunately

**Comment by panky98** [comment]
Thanks @jgarciadelanoceda! I have wrote a _ISchemaFilter_ as a workaround doing the same thing.. but not necessary apparently
