### ISSUE TITLE
[Question]: Ensuring the Correct Order of Operation and Schema Filters in Swashbuckle.AspNetCore

### ISSUE THREAD

**Issue by gokayokutucu** [domaindrivendev/Swashbuckle.AspNetCore#2993]
### What are you wanting to achieve?

I want to provide the correct execution order of OperationFilter and SchemaFilter in Swashbuckle.AspNetCore when generating Swagger documents. In particular, I want my OperationFilter to first work to cache certain header names, then I want my SchemaFilter to ignore those cached header names. Despite specifying the order in my configuration, SchemaFilter runs before OperationFilter.

### What code or approach do you have so far?

Here is a minimalistic code snippet demonstrating the issue:

```
public class CacheHeaderNamesOperationFilter : IOperationFilter
{
    public static List<string> CachedHeaderNames = new();
    
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        // Caching header names logic
        CachedHeaderNames.Add("ExampleHeaderName");
    }
}

public class IgnoreCachedHeaderNamesSchemaFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        // Logic to ignore cached header names
        foreach (var header in CacheHeaderNamesOperationFilter.CachedHeaderNames)
        {
            schema.Properties.Remove(header);
        }
    }
}

services.AddSwaggerGen(c =>
{
    c.OperationFilter<CacheHeaderNamesOperationFilter>(); // First, cache the header names
    c.SchemaFilter<IgnoreCachedHeaderNamesSchemaFilter>(); // Then, ignore the cached header names
});
```

Despite this order, IgnoreCachedHeaderNamesSchemaFilter runs before CacheHeaderNamesOperationFilter.

**What is the expected outcome?**

The expected outcome is that CacheHeaderNamesOperationFilter should run before IgnoreCachedHeaderNamesSchemaFilter, ensuring that the cached header names are available for the schema filter to process and ignore. This way, the Swagger documentation accurately reflects the intended API design.

**Comment by martincostello** [comment]
Schemas are created as part of the process of enumerating the operations found in the document, which is why different types of filters run in a certain order.

For your specific scenario, to get the behaviour your want you probably need to use a document filter and remove the schemas you wish to ignore from the almost-final document before it is serialized after your operation processors have run.

**Comment by gokayokutucu** [comment]
Thank you, your response. In particular, what steps should I follow to get the correct order and how can I use the document filter correctly?

**Comment by martincostello** [comment]
- Schema filters run when a schema is created: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/85fefe4257f718ae669b67f0b562177ce25f7934/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs#L37

**Comment by gokayokutucu** [comment]
Thank you very much for your response. It really helped me a lot.
