### ISSUE TITLE
Swagger UI not showing the auth textbox and explore button

### ISSUE THREAD

**Issue by Tochemey** [domaindrivendev/Swashbuckle.AspNetCore#300]
I added the Swashbuckle.Core to my NetCore web api. However the default authentication input and explore button are not showing. I followed the tutorial on MSDN site.

Please assist.

**Comment by domaindrivendev** [comment]
Have you followed the readme instructions for adding security definitions - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#add-security-definitions-and-requirements

**Comment by Tochemey** [comment]
I will recheck that portion and revert back to you.
Thank you

**Comment by Tochemey** [comment]
It is working smoothly. Thanks
