### ISSUE TITLE
[Bug]: Swashbuckle.AspNetCore.Cli v.6.7.0 doesn't generate format of the property

### ISSUE THREAD

**Issue by AndriiBlandov** [domaindrivendev/Swashbuckle.AspNetCore#3005]
### Describe the bug

In generated swagger.jwon property description object doesn't contain "format" 

### Expected behavior

"components": {
"schemas": {
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "**format": "date-time"**
          },

### Actual behavior

"components": {
"schemas": {
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            ~~"format": "date-time"~~
          },

### Steps to reproduce

Generate swagger.json for ASP.NET Core Web Api using class with DateTime property

### Swashbuckle.AspNetCore version

6.7.0

### .NET Version

8.0.303

### Anything else?

With version 6.6.2 everything works as expected

**Comment by martincostello** [comment]
Without a repro to go off, looking at the diff since 6.6.2 my guesses for where a regression could have been introduced are #2803, #2941 or #2980.

**Comment by AndriiBlandov** [comment]
False alarme, I am sorry, there was a problem with dependencies in that used Swachbackle as well but was not updated to latest version.

**Comment by Dave-EMIS** [comment]
In my case this is because I had a mismatch of Swashbuckle versions:
```
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.1" />
<PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="6.5.0" />
```
