### ISSUE TITLE
Setting SerializerSettings.ContractResolver to DefaultContractResolver, fails to load swagger UI

### ISSUE THREAD

**Issue by abhisek-sinha** [domaindrivendev/Swashbuckle.AspNetCore#301]
Following the [announcement](https://github.com/aspnet/Announcements/issues/194) for breaking change in ASP.Net JSON serialization behavior, I updated my startup.cs to use -
```
 services
        .AddMvc()
        .AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());
```
After this change, the swagger UI fails(at /swagger endpoint) to load in the browser. If I revert back the above change, the swagger UI is displayed properly.
What is the correct way to let swagger know that we want to use DefaultContractResolver, and not camel case one?
My project.json is using - ```"Swashbuckle.AspNetCore": "1.0.0-rc1"```

**Comment by domaindrivendev** [comment]
@abhisek-sinha - this doesn't repro with any of my sample applications. There must be something specific to your setup. Can you enable the dev. exception page (i.e. _UseDeveloperExceptionPage_) and then navigate directly to the Swagger JSON at /swagger/v1/swagger.json. This should provide details of the server-side exception and might help troubleshoot.

With just the limited info you've given above and without a repro, there's really not much else I can do to assist without the additional exception info.

**Comment by abhisek-sinha** [comment]
Thanks for your reply. I did not try to see what happened at server, but in browser, IIRC, I think the swagger endpoint array was empty, and so it couldn't load the UI.
But I'll enable the exception page, and provide you details on what happens there.

**Comment by abhisek-sinha** [comment]
I am disappointed that I couldn't get the problem to show up again. There had been some other changes to the project, so I am not sure, if there is anything else that's affecting the behavior. And I wasn't able to restore the project to the date when it was showing this problem. 
I think it is OK to close this issue now. I would revert back if the problem shows up again.
