### ISSUE TITLE
[Bug]: A nullable struct property results in an invalid generated schema.

### ISSUE THREAD

**Issue by igor-korolyov** [domaindrivendev/Swashbuckle.AspNetCore#3013]
### Describe the bug

Invalid schema has been generated in cases where a type has a nullable property of a custom struct.

Version 6.2.2 behaves in the expected way.

### Expected behavior

A valid schema should be generated.

### Actual behavior

An invalid (and recursive) schema has been generated.
![image](https://github.com/user-attachments/assets/303237fb-b132-4e82-a1b5-c8e384c9c0f2)

### Steps to reproduce

```
public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        // Add services to the container.

        builder.Services.AddControllers();
        // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
        builder.Services.AddEndpointsApiExplorer();
        builder.Services.AddSwaggerGen();

        var app = builder.Build();

        // Configure the HTTP request pipeline.
        if (app.Environment.IsDevelopment())
        {
            app.UseSwagger();
            app.UseSwaggerUI();
        }

        app.UseAuthorization();


        app.MapControllers();

        app.Run();
    }
}

[ApiController]
[Route("[controller]/[action]")]
public class TestController : ControllerBase
{
    [HttpGet]
    public TestResponse Get()
    {
        return new()
        {
            Foo = new(1, 2),
        };
    }
}

public record TestResponse
{
    public TestStruct? Foo { get; init; }
}

public record struct TestStruct(int A, int B);
```

### Swashbuckle.AspNetCore version

6.7.0

### .NET Version

net8.0

**Comment by shihabmridha** [comment]
We are having the same issue.
+1

**Comment by martincostello** [comment]
Looks like this was broken by #2941.

**Comment by jgarciadelanoceda** [comment]
Sorry for the inconvenience!

**Comment by ahoke-cr** [comment]
This is doubly bad because object types as references that are properties of an object or request are not allowed to have descriptions. This makes 6.7.0 unusable for us as it results in most of our API docs being unusable with unhelpful descriptions of object properties/request parameters being the description of the schema itself (empty in the case of these "NullableInt32" etc. types).

**Comment by martincostello** [comment]
[Version 6.7.1](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v6.7.1) is now available from NuGet.org which resolves this issue.
