### ISSUE TITLE
[Bug]: The annotation of the field parameter using FromForm in the interface is not displayed 

### ISSUE THREAD

**Issue by qcjxberin** [domaindrivendev/Swashbuckle.AspNetCore#3018]
### What are you wanting to achieve?

The annotation of the field parameter using FromForm in the interface is not displayed 

![image](https://github.com/user-attachments/assets/572a5586-d97f-420d-a254-5773305586fa)

### What code or approach do you have so far?

no

**Comment by martincostello** [comment]
Sorry, I don't understand what you're trying to explain is broken here.

**Comment by qcjxberin** [comment]
/// <summary>
/// 修改密码
/// </summary>
/// <param name="OldPassword">旧密码</param>
/// <param name="NewPassword">新密码</param>
/// <param name="ComfimPassword">确认密码</param>
/// <returns></returns>
[HttpPost("ChangePassword")]
[ApiSignature]
public IActionResult ChangePassword([FromForm)] string OldPassword, [FromForm] string NewPassword, [FromForm] string ComfimPassword)
![image](https://github.com/user-attachments/assets/58c30d21-7610-4a8a-a8f7-1a0892786fa9)

![image](https://github.com/user-attachments/assets/9ac1cd0a-a025-4bec-b278-d1eda3201c81)

@martincostello

**Comment by martincostello** [comment]
So you're expecting the XML documentation for those parameters to be present as the `description` on the parameters in the OpenAPI specification?

How are you configuring XML documents to be added to the OpenAPI document? Do they appear in other places you'd expect them to be?

**Comment by martincostello** [comment]
> The old version was OK, but not after the upgrade.

From which version to which version?

**Comment by qcjxberin** [comment]
[ApiDemo.zip](https://github.com/user-attachments/files/16568618/ApiDemo.zip)
I just created a new project casually, and then tested it and found the same problem, you can take a look.
@martincostello

**Comment by qcjxberin** [comment]
![image](https://github.com/user-attachments/assets/a4549b1c-b170-4d2e-97c1-78e109ed90f6)
![image](https://github.com/user-attachments/assets/dbb71e89-ec01-49fb-a9d5-f50adc5792de)

**Comment by qcjxberin** [comment]
![image](https://github.com/user-attachments/assets/b7a87c1c-d192-4a7a-82de-3b27bd3b4be3)
The data content of returns is also not displayed

**Comment by qcjxberin** [comment]
![image](https://github.com/user-attachments/assets/7408de5b-6b7f-4c7e-bd5c-ac5faa16b62a)
![image](https://github.com/user-attachments/assets/36c45c67-c549-4c40-b4bf-1ae98d896e8b)
So far, the test has found that there should be no comment on the requestBody.

**Comment by qcjxberin** [comment]
@martincostello Can you Help me?

**Comment by martincostello** [comment]
This is a bug - it has never worked.

**Comment by martincostello** [comment]
Also, FWIW, your repo is using Swashbuckle.AspNetCore 6.4.0 which is 2 years old. If you experience an issue, please try the latest version before reporting an issue in case it has since been fixed.

**Comment by qcjxberin** [comment]
There is the same problem, and it should be possible to use versions before 6.
![image](https://github.com/user-attachments/assets/7411f9d0-5126-432b-b3a2-abebf6c1ea42)

**Comment by qcjxberin** [comment]
When will 6.7.1 be released, we want to use it as soon as possible

**Comment by martincostello** [comment]
I don't know exactly when. It depends on when other contributors review and approve the PRs open against [that milestone](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/24).

**Comment by qcjxberin** [comment]
Okay, thank you so much for your support

**Comment by martincostello** [comment]
Re-opening it as it's an active issue (that others can find more easily) until the fix is shipped.

**Comment by martincostello** [comment]
[Version 6.7.1](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v6.7.1) is now available from NuGet.org which resolves this issue.

**Comment by qcjxberin** [comment]
@martincostello So far, only the first parameter has been described, but the others are not

**Comment by qcjxberin** [comment]
![image](https://github.com/user-attachments/assets/7162acbc-e048-416b-8d16-a3abef7b596a)

**Comment by martincostello** [comment]
That is a different issue: #2062

The first form parameter is being used to describe the request body _as a whole_ (which on reflection is probably incorrect if there are multiple properties, which is another issue caused by the fix for this issue).

Separately, the members of the request are not being documented at all, which is the issue above.
