### ISSUE TITLE
What kind of IParameter for Operation?

### ISSUE THREAD

**Issue by cryo75** [domaindrivendev/Swashbuckle.AspNetCore#303]
I'm migrating to AspNetCore, and I encountered a problem. What is the concrete class that implements IParameter for OpeationFilter?

As in:

    operation.Parameters.Insert(0, new IParameter
    {
        name = "token",,
        @in = "header",
        required = true,
        type = "string"
    });`

**Comment by domaindrivendev** [comment]
This is OSS. Don't be afraid to peak at the code :)

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Swagger/Model/SwaggerDocument.cs#L192

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Swagger/Model/SwaggerDocument.cs#L214
