### ISSUE TITLE
[Bug]: Topbar wrapper changed from img to svg

### ISSUE THREAD

**Issue by pawan-atl** [domaindrivendev/Swashbuckle.AspNetCore#3033]
### Describe the bug

In v6.5.0, I was able to change the logo of the swagger index document by having a custom css as below (as the wrapper contained img element:- 

.topbar-wrapper > a img {
  content: url("logo-secure.png");
  height: 65px;
}

In updated version 6.7.1, its all changed to svg and now my logo doesnt work!

Please help.

**Comment by martincostello** [comment]
The version of [swagger-ui](https://github.com/swagger-api/swagger-ui) between 6.5.0 and 6.7.1 was upgraded from [4.15.5](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerUI/package.json#L6) to [5.17.14](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/f4ca2cda8b4844091d4cba1b91178d73b4b8afa0/src/Swashbuckle.AspNetCore.SwaggerUI/package.json#L6).

The design of the user interface's HTML elements and how they interact with swagger-ui's JavaScript is not something we control.

You will need to update your code's CSS customisation for the topbar in swagger-ui v5 to achieve the desired effect.
