### ISSUE TITLE
[Question]: How to use markNonNullableTypeAsRequired

### ISSUE THREAD

**Issue by lunatiqqc** [domaindrivendev/Swashbuckle.AspNetCore#3034]
### What are you wanting to achieve?

I am trying to mark non nullable properties as marked

### What code or approach do you have so far?

builder.Services.AddSwaggerGen(o =>
{
    ...
    o.NonNullableReferenceTypesAsRequired();

});

### Additional context

It doesn't seem to mark properties as required in the spec

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.
