### ISSUE TITLE
[Question]:  WithOpenApi and ParameterFilters

### ISSUE THREAD

**Issue by jgarciadelanoceda** [domaindrivendev/Swashbuckle.AspNetCore#3037]
### What are you wanting to achieve?

I have just changed the SwaggerAnnotationsEndpoints of the WebApi project and realized that the ParameterFilters are not being called when you insert the WithOpenApi extension method.

I do not know if this is by design but the change of this is pretty simple.

Previously : https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/7a7230dd54be847ac82982010e00497d9fe5f2cf/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L406-L415

Now (If it's not by design), I have also to integrate ParameterAsyncFilters:

```c#
var apiParameter = apiDescription.ParameterDescriptions.SingleOrDefault(desc => desc.Name == parameter.Name && !desc.IsFromBody() && !desc.IsFromForm() && !desc.IsIllegalHeaderParameter());
if (apiParameter is not null)
{
    var (parameterAndContext, filterContext) = GenerateParameterAndContext(apiParameter, schemaRepository);
    parameter.Schema = parameterAndContext.Schema;
    foreach (var filter in _options.ParameterFilters)
    {
        filter.Apply(parameter, filterContext);
    }
}
``` 

I label this as Question because I am not sure if the WithOpenApi should apply the ParameterFilters

### What code or approach do you have so far?

I want that the ParameterFilters run also when the WithOpenApi extension method is called

**Comment by martincostello** [comment]
Could you be a bit more specific - we don't have a method called `WithOpenApi()`, so I'm not sure what you're adding that's causing the issue?

**Comment by martincostello** [comment]
Weird - it doesn't appear [in code search](https://github.com/search?q=repo%3Adomaindrivendev%2FSwashbuckle.AspNetCore%20WithOpenApi&type=code) for me.

**Comment by jgarciadelanoceda** [comment]
In the first result has 8 more results, there are several endpoints that have WithOpenApi extension method

**Comment by jgarciadelanoceda** [comment]
In the first file has 8 more results, there are several endpoints that have WithOpenApi extension method

**Comment by martincostello** [comment]
I would have thought it should work. There'd have to be a good reason for it to not work intentionally.

**Comment by jgarciadelanoceda** [comment]
I would investigate if the rest of the filters work ( I think that they do), and if all of them (Schema, Operation and Document) do I will create a PR to fix it

**Comment by jgarciadelanoceda** [comment]
I have just checked and when you insert WithOpenApi, the Parameters filters are skipped and also the RequestBodyFilters, but the OperationFilter, SchemaFilter and DocumentFilter are executed.
I think that both filters should be executed (Both for Body and for Parameters). I will summit the PR as soon as #3030 gets merged
