### ISSUE TITLE
additionalQueryStringParameters not provided for OAuth2Scheme of Flow = application

### ISSUE THREAD

**Issue by ckittel** [domaindrivendev/Swashbuckle.AspNetCore#304]
Version: `Swashbuckle.AspNetCore` (1.0.0-rc1) via NuGet

In my `Startup.cs` `Configure` method, I have the following for swagger:
```csharp
app.UseSwagger();

app.UseSwaggerUi(c =>
{
    c.ConfigureOAuth2("MyClientID", "MyClientSecret",  string.Empty, "Swagger UI", 
            additionalQueryStringParameters: new Dictionary<string, string>
            {
                {"audience", "MyAudienceValue"}
            });
}
```
and in `ConfigureServices` I have:
```csharp            
services.AddSwaggerGen(c =>
{
    c.AddSecurityDefinition("oauth2", new OAuth2Scheme
    {
        Type = "oauth2",
        Flow = "application",
        TokenUrl = "https://myauthservice.com/oauth/token"
    });
});
```

However, in the UI when it goes to make the HTTP POST off to the `TokenUrl`, the values in `additionalQueryStringPrameters` are not included in the body.
```
client_id=MyClientId&client_secret=MyClientSecret&scope=&grant_type=client_credentials
```
I was expecting the HTTP POST body to look like
```
client_id=MyClientId&client_secret=MyClientSecret&scope=&grant_type=client_credentials&audience=MyAudienceValue
```
Am I doing something wrong, or is this parameter not working with `Flow = "application"`?  Is there a reasonable workaround?

**Comment by domaindrivendev** [comment]
These are additional "query string" parameters so you're not going to see them in the request "body". But, they should be visible at the very end of your token URL. Just confirmed this and appears to working correctly.

**Comment by ckittel** [comment]
They are not in the request url either as it is an HTTP POST to the token
URL (not a GET). The token URL, in my case Auth0, demands another www form
encoded parameter in the body.

**Comment by domaindrivendev** [comment]
OK gotcha, I missed that this was specific to the "application" flow.

At this point, I'm going to have to refer you to the swagger-ui project (https://github.com/swagger-api/swagger-ui) as this is the component that's bundled with Swashbuckle to provide the slick UI.

That's where the OAuth interactions and "additionalQueryStringParameters" option is implemented:

https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L64

**Comment by ckittel** [comment]
Sounds good. I posted there originally, so I'll just unclose my post there
with additional information as provided in this thread. Thanks!

**Comment by RehanSaeed** [comment]
To get the Swagger 'Authorize' button to work, which flow did you end up using `implicit`, `application` or `client_credentials`. I'm trying to get Azure Active Directory to work https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/332. It makes sense to me that I use the `implicit` flow, due to the client being JavaScript, however, I'm not sure.

**Comment by ckittel** [comment]
I didn't get the button to work, because I'm waiting for my PR to get merged in upstream. I'm using the `application` flow, with Auth0.

**Comment by RehanSaeed** [comment]
Auth0 is a similar service, so is `application` the way to go and will it not work until your PR is released? Is there a description of what the `application` flow is and when to use each flow with Swagger?

**Comment by ckittel** [comment]
My topology fits into the OAuth2 application flow model, but yours may not.
The swagger-ui team has great documentation on this topic you might want to
check out.

On Tue, Mar 7, 2017, 6:13 AM Muhammad Rehan Saeed <notifications@github.com>
wrote:

Auth0 is a similar service, so is application the way to go and will it not
work until your PR is released? Is there a description of what the
application flow is and when to use each flow with Swagger?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/304#issuecomment-284705253>,
or mute the thread
