### ISSUE TITLE
Swagger UI: JSConfig bootstrapping serialization error

### ISSUE THREAD

**Issue by ArashMotamedi** [domaindrivendev/Swashbuckle.AspNetCore#305]
Swagger UI's window.JSConfig bootstrapping is affected by JsonConvert's Default Settings, and this can cause runtime javascript errors. Here's my application setup:

At the top of `ConfigureServices`, I modify JsonConvert default settings for my application purposes:
```C#
// Serialization settings
var jsonSettings = new JsonSerializerSettings(); 
jsonSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
JsonConvert.DefaultSettings = () => jsonSettings;
```

As a result of `camelCase` settings above, the generated window.JSConfig line will become:
```javascript
window.JSConfig = JSON.parse('{"swaggerEndpoints":[{"url":"/swagger/v1/swagger.json"}')...
```

**Note the camelCased `swaggerEndpoints` and `url`, etc.**

As a result, **JSConfig.SwaggerEndpoints[0].Url** throws an exception and an empty window is shown.

JSConfig must be serialized reliably regardless of any JsonConvert default settings that the user might have chosen. 

![image](https://cloud.githubusercontent.com/assets/9794140/23141039/aa4f4ea0-f769-11e6-91ea-1fc0175180f4.png)

**Comment by domaindrivendev** [comment]
Fixed with 8377c006378a7db46186a425f082b798d63c35e9
