### ISSUE TITLE
[Bug]: RegEx example data includes characters that are not allowed.

### ISSUE THREAD

**Issue by richard-collette-precisely** [domaindrivendev/Swashbuckle.AspNetCore#3057]
### Describe the bug

Given a regular expression validator applied to body object property like:

```c#
public class SanitizedNameAttribute() : RegularExpressionAttribute(@"^[\p{L}\p{M}\p{Zs}\p{N}'-\.]+$")
{
    public override string FormatErrorMessage(string name)
    {
        return "Only alphanumeric characters, printable whitespace, and the symbolic characters ' . and - are allowed.";
    }
}
```

The example data that is generated for that property looks like:

```json
  "firstName": "{LsLM{p{sZps-pZ's{}}}}NpN'p'psZ-ssNNMp-'MNL{L'sZp'",
```

### Expected behavior

The delimiters \p{ followed by } should be treated as a character class instead of seeing { as a character literal to match.

### Actual behavior

{  and } characters are rendered in the example data when they should not be.

### Swashbuckle.AspNetCore version

6.7.3

### .NET Version

8.0.401

**Comment by martincostello** [comment]
How/where are you setting the examples? As far as I'm aware Swashbuckle only sets them from XML documentation - anything else is for the app to implement.

Can you provide a self-contained example of how you get this behaviour?

**Comment by richard-collette-precisely** [comment]
Actually, I apologize.  This is a swagger UI issue.   I had pasted the JSON in the swagger editor and falsely assumed that the example values were in the JSON files, but that is not the case.  It must be swagger UI that is generating the incorrect values.

I'm closing this out.
