### ISSUE TITLE
[Feature request]: index.js in 6.7.3 cannot be replaced as index.html. 

### ISSUE THREAD

**Issue by dlevesque1980** [domaindrivendev/Swashbuckle.AspNetCore#3060]
### Is your feature request related to a specific problem? Or an existing feature?

I am trying to add a plugins for swaggerUI, but I cannot add it wihtout replacing the index.js files and this file is not replaceable officially. The only choice we have is to put a different source of the same file or to put the javascript code inline like before. 

### Describe the solution you'd like

It would be ideal if we can replace index.js just like we are able to replace index.html or having a way to add the plugins in the configuration. 
The plugin I use for example is a script I must include in the index file and use a global a variable make available for that script 

### Additional context

Have a look here
https://github.com/dlevesque1980/swagger-ui-json-folding-plugin

**Comment by martincostello** [comment]
I'm not _quite_ sure I'm following.

index.js should be replaceable (like any of the files we serve) by replacing it with a file with the same path in your `wwwroot` folder. If that isn't working, then that's a bug.

If you want the ability to add plugins _without_ needing to override index.js, then that was recently added by #3056, which will be available in the next release.

**Comment by dlevesque1980** [comment]
yes that is what is required. Thank you.

**Comment by AkselKP** [comment]
@martincostello Is replacing files, such as index.js, documented somewhere? I can't seem to figure it out.

**Comment by martincostello** [comment]
I can't see an obvious mention of it in the README, no.

**Comment by AkselKP** [comment]
Alright thanks anyway. Is there a planned release date for v6.8.0?

**Comment by martincostello** [comment]
Not yet - best I can say at the moment is "soon".

If you're super-desperate to use the latest changes, you can consume pre-release packages from our MyGet feed.

**Comment by AkselKP** [comment]
Alright, thank you.
