### ISSUE TITLE
[Bug]: Optional route parameter gets rendered as required

### ISSUE THREAD

**Issue by sommmen** [domaindrivendev/Swashbuckle.AspNetCore#3078]
### Describe the bug

The following endpoint:

``` csharp
    [HttpGet("packing-dashboard")]
    [HttpGet("packing-dashboard/{partner?}")]
    public async Task<IActionResult> GetDashboard([FromRoute] string? partner = default, CancellationToken cancellationToken = default)
```

Makes the partner value required in the UI:

![image](https://github.com/user-attachments/assets/e43e7451-1ee0-4735-ac61-8d6bc9bac949)

Ditto for the document:
![image](https://github.com/user-attachments/assets/b3fd3e29-7c91-4903-9d34-218edd10a8c0)

### Expected behavior

The partner variable should be optional.

### Actual behavior

Its required.

### Steps to reproduce

Paste the sample code above in a controller.

### Swashbuckle.AspNetCore version

Latest (6.8.0)

### .NET Version

net8.0

**Comment by martincostello** [comment]
> Latest

To confirm, is this with 6.8.0?

**Comment by sommmen** [comment]
> > Latest
> 
> To confirm, is this with 6.8.0?

Did not expect the 2hrs ago release - i will recheck if this issue persists on that version.

**Comment by sommmen** [comment]
> > Latest
> 
> To confirm, is this with 6.8.0?

Unfortunately the issue remains with 6.8.0.

**Comment by jgarciadelanoceda** [comment]
This seems to be the expected behaviour: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/9f4dacda759dfa38e0fc989a4d006a0f0af68174/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs#L34-L39

**Comment by sommmen** [comment]
> This seems to be the expected behaviour:
> 
> https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/9f4dacda759dfa38e0fc989a4d006a0f0af68174/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs#L34-L39
> 
> Last PR against this: #2183

Welp if the spec say so this is intended behaviour - but then how would i define an endpoint like;

```
/package (lists all packages)
/package/123 (gets a package by id).

```
For the same method in asp net core?
```
[HttpGet("package/{id?}"]
GetPackage(int? id = default) {...
```

**Comment by cremor** [comment]
I wouldn't implement those two things in the same method.

- They should have different return types (one a list of objects, one a single object) and the Swagger UI should show this.
- They should have different error results (e.g. the single get could return 404, the list all should never return 404) and the Swagger UI should show this.
- They could have different authorization requirements (e.g. a user could only be allowed to select specific objects, but not all).
