### ISSUE TITLE
Add inline route constraints to path parameters

### ISSUE THREAD

**Issue by Dresel** [domaindrivendev/Swashbuckle.AspNetCore#308]
You are adding [validation properties](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/1b8e109cdb2e21b57584ef4596a0d1a13af8b7eb/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs#L193) to the schema objects.

Are you eager to also support this kind of functionality for path parameters? I'm sure you have already heard of the ASP.NET Core [inline route constraints](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?highlight=routing#route-constraint-reference), which are propagated into `ApiDescription. ParameterDescriptions.RouteInfo.Constraints`. It's not a problem for me to add this kind of functionality as an OperationFilter for myself but a built in solution might be of interest for others. For example I added something like this for Regex constraints:

	public class ApplyRegexRouteConstraintsOperationFilter : IOperationFilter
	{
		public void Apply(Operation operation, OperationFilterContext context)
		{
			foreach (ApiParameterDescription parameterDescription in context.ApiDescription.ParameterDescriptions.Where(x => x.Source == BindingSource.Path))
			{
				NonBodyParameter parameter =
					operation.Parameters.OfType<NonBodyParameter>().SingleOrDefault(x => x.Name == parameterDescription.Name);

				foreach (IRouteConstraint routeConstraint in parameterDescription.RouteInfo.Constraints)
				{
					RegexRouteConstraint regexRouteConstraint = routeConstraint as RegexRouteConstraint;

					if (regexRouteConstraint != null)
					{
						parameter.Pattern = regexRouteConstraint.Constraint.ToString();
					}
				}
			}
		}
	}

What do you think?

**Comment by rynowak** [comment]
I'm not answering for the swashbuckle maintainers, but please keep in mind that route constraints in MVC are not validation. URL input that doesn't match the constraint will result in a 404 rather than a 400 with a validation error message.

Constraints are still useful for cases where you want to disambiguate between routes (constraints raise the precedence of a route).

**Comment by Dresel** [comment]
Ok thanks for the clarification - but it would still make sense to use the Swagger path properties like Pattern to somehow show this information or not?

**Comment by xperiandri** [comment]
I think it is the matter of Swagger support of different methods at the same route
