### ISSUE TITLE
[Bug]: 6.8.0 Method options.IncludeXmlComments creates FilterDescriptor w/o supplying Arguments, breakes other lib

### ISSUE THREAD

**Issue by alser** [domaindrivendev/Swashbuckle.AspNetCore#3081]
### Describe the bug

I have an app with `Swashbuckle.AspNetCore` plus `Unchase.Swashbuckle.AspNetCore.Extensions` to handle `<inheridoc/>` tags.

Version `Swashbuckle.AspNetCore 6.8.0` introduced breaking change, not present in 6.7.3.

I'm wondering whether it's intended and this other lib should do something different, or if it's a bug.

---

In the following code a call to `IncludeXmlCommentsFromInheritDocs` (from Unchase package) fails with the attached exception.

```cs
// xml comments file generated by c# compiler, no matter the contents (with or w/o inheritdocs)
const string xmlFilePath = "path/to/MyAssembly.xml";

services.AddSwaggerGen(options =>
{
    options.IncludeXmlComments(xmlFilePath);
    options.IncludeXmlCommentsFromInheritDocs();
});
```

Same behavior if supplied `XPathDocument`:

```cs
options.IncludeXmlComments(() => new XPathDocument(new StringReader(File.ReadAllText(xmlFilePath))));
```

---

In this repo sources method `IncludeXmlComments` results in calling to:

```cs
swaggerGenOptions.AddSchemaFilterInstance(new XmlCommentsSchemaFilter(xmlDocMembers));
```

which in turn does this:

```cs
swaggerGenOptions.SchemaFilterDescriptors.Add(new FilterDescriptor
{
    Type = typeof(TFilter),
    FilterInstance = filterInstance
});
```

therefore creating `FilterDescriptor` with `Arguments = null`.

Method `IncludeXmlCommentsFromInheritDocs` (in Unchase lib) starts with:

```cs
var documents = swaggerGenOptions.SchemaFilterDescriptors.Where(x => x.Type == typeof(XmlCommentsSchemaFilter))
    .Select(x => x.Arguments.Single())
    .Cast<XPathDocument>()
    .ToList();
```

expecting to see single argument of type `XPathDocument`, but throwing ANE.

`Swashbuckle.AspNetCore 6.7.3` had `FilterDescriptor.Arguments` as an array with single `XPathDocument`.

---

created similar issue in Unchase lib's repo: https://github.com/unchase/Unchase.Swashbuckle.AspNetCore.Extensions/issues/38

### Expected behavior

Calling `SwaggerGenOptions.IncludeXmlComments(string)` adds to `SwaggerGenOptions.SchemaFilterDescriptors` an object `FilterDescriptor` with property `Arguments = new[] { xpathDocument }`.

### Actual behavior

`SwaggerGenOptions.SchemaFilterDescriptors` has filter descriptors with `Arguments = null`

### Exception(s) (if any)

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Unchase.Swashbuckle.AspNetCore.Extensions.Extensions.SwaggerGenOptionsExtensions.<>c.<IncludeXmlCommentsFromInheritDocs>b__7_1(FilterDescriptor x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Unchase.Swashbuckle.AspNetCore.Extensions.Extensions.SwaggerGenOptionsExtensions.IncludeXmlCommentsFromInheritDocs(SwaggerGenOptions swaggerGenOptions, Boolean includeRemarks, Type[] excludedTypes)
```

### Swashbuckle.AspNetCore version

6.8.0

### .NET Version

8.0

**Comment by martincostello** [comment]
This was a breaking change in the context that _it broke you_, but it isn't a breaking change as far as SemVer and [.NET library guidelines](https://learn.microsoft.com/en-us/dotnet/core/compatibility/library-change-rules#members) are concerned:

> ✔️ ALLOWED: Adding a constructor to a class

The issue here is with Unchase.AspNetCore.Extensions - it shouldn't make hard assumptions about the public members that exist on Swashbuckle.AspNetCore's types. The code should be refactored to not rely on `Single()` so that it can find the constructor that it expects and ignore others.

Had we _removed_ the constructor it relied on, that would be our fault. We have analysers in place to protect against making such breaking changes unintentionally: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2801

**Comment by martincostello** [comment]
Also, it's still the case we only have one public constructor - we added a new internal one:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/17981d9626ce04cc48932aa7443f909653d5fcdd/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsSchemaFilter.cs#L12-L19

**Comment by martincostello** [comment]
The bit being tripped over is likely [this part of the change](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/90f302d9bf0e1285a7f4c3cc2bab32fddc777fbb#diff-57500675bcb9e227ce26b531b4c87fd75c92f0a24385edda93d14b431636585a), where we refactored the internals to use the new constructor to improve performance:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/90f302d9bf0e1285a7f4c3cc2bab32fddc777fbb/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs#L712

**Comment by alser** [comment]
Thanks for a quick and throrough response! That code in Unchase lib definitely assumpts too much. I'll think what can be fixed from its end then.
