### ISSUE TITLE
Override default swagger-ui index.html template?

### ISSUE THREAD

**Issue by Fizzleban** [domaindrivendev/Swashbuckle.AspNetCore#310]
Is there anyway to override the default swagger-ui index.html template?  This was possible using custom assets before, but I am not sure if this is possible for the .NET core version?  

I tried adding an "index.html" file to "wwwroot/api-explorer" (I changed the path from "swagger" to "api-explorer"), and it did override the index.html file that was auto-generated, but when I try to swap in the index.html from the templates directory, the %(StylesheetsHtml) and JSON.parse('%(JSConfig)'); are throwing errors.

**Comment by cartwrightp** [comment]
Can confirm I get the same even when using wwwrooot/Swagger and putting the index.html file in there. The page renders ok and I see all the API actions, but the header area is broken and console shows JSConfig as undefined, exactly same as fizzleban.

**Comment by CumpsD** [comment]
I would also love to simply provide a way to override `Swashbuckle.AspNetCore.SwaggerUI/Template/index.html` instead of having to host a static index.html which has the parameters hardcoded.

**Comment by vytautas-pranskunas-** [comment]
I was not able to do this at all because no matter what i do i got original files rendered, however if i navigate to ..host/api-docs/images/test.png i got it right, if replace original swagger logo and ..host/api-docs/images/logo_small.png i got original anyway.

Any ideas how to get swapped files served or any progress on this task at all?

Thanks

**Comment by jsears** [comment]
Plus One for this feature being sorely needed.  Cheers.

**Comment by domaindrivendev** [comment]
Fixed by #205. Nuget will be released shortly
