### ISSUE TITLE
[Feature request]: Support `oneOf` *per operation*

### ISSUE THREAD

**Issue by angelaki** [domaindrivendev/Swashbuckle.AspNetCore#3109]
### Is your feature request related to a specific problem? Or an existing feature?

Guess I have a pretty _edgy case_ here: I've written a custom polymorphic serializer that let's me choose weather a contract should get serialized respecting polymorphic definitions or not. E.g. a method `GetShapes()` could actually just return an array of `Shape` while `GetShape()` returns the actual type - hope that's understandable?

I'm quite sure that, right now, theirs no way to solve this, right? What would you think about a PR where `SelectSubTypesUsing` offers an overload with the operation passed, so it could be decided depending on the operation? Would you accept such a PR? Or is there already a solution for this right now?

### Describe the solution you'd like

Something like an overload

```
public static void SelectSubTypesUsing(
    this SwaggerGenOptions swaggerGenOptions,
    Func<Type, **ApiDescription**, IEnumerable<Type>> customSelector)
```

**Comment by martincostello** [comment]
Unfortunately the change isn't as simple as adding an overload, as the method just maps to setting a delegate property on a public property:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/6995d8a914c1c32090908a415002c6ce354c2a61/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGeneratorOptions.cs#L32

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/6995d8a914c1c32090908a415002c6ce354c2a61/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptionsExtensions.cs#L263

We couldn't update that property without making a binary-breaking change, and to avoid that we'd need to have two similar but different properties and choose between them. Then we'd have to do all the internal refactoring to push the API description through, etc. and I imagine it would end up being quite a big change.

Have you looked into seeing if you can get the desired effect using a [schema/operation filter](https://github.com/domaindrivendev/Swashbuckle.AspNetCore?tab=readme-ov-file#extend-generator-with-operation-schema--document-filters)?

**Comment by angelaki** [comment]
Actually expected it to become a bit harder. I'll give the operation filter a chance and come back with some news. Thank you for that suggestion!

Guess my use-case **is** to edgy for a proper support, right?

**Comment by angelaki** [comment]
@martincostello thank you for your hint! Yeah, a custom `IOperationFilter` can totally do the job. Would love to see it work out of the box - but guess my use-case is pretty rare, right? And at least it can be achieved this way. So you're free to close if you don't want to see a build in solution.

**Comment by martincostello** [comment]
I can't really speak for an objective opinion on whether your use case is an edge-case or not. I can make an _assumption_ it is based on the fact this is the first time I'm aware it's come up though. 😃

If filters solve the job for you, then I'll close this on the basis that introducing it at this stage would otherwise be a big change with little user demand. We could always look at it again in the future if it does turn out to be an in-demand feature.
