### ISSUE TITLE
[Bug]: Incorrect swagger.json generation in Minimal API when using FromForm parameters without the WithOpenApi extension method

### ISSUE THREAD

**Issue by marcominerva** [domaindrivendev/Swashbuckle.AspNetCore#3126]
### Describe the bug

I have the following endpoints:

```
app.MapPost("/api/products", ([FromForm] Product product) =>
{
    return TypedResults.NoContent();
})
.DisableAntiforgery();

app.MapPost("/api/products-with-openapi", ([FromForm] Product product) =>
{
    return TypedResults.NoContent();
})
.DisableAntiforgery()
.WithOpenApi();

public record class Product(string Name, double Price);
```

These endpoints differ only for the `WithOpenApi` extension method, but the `swagger.json` definition is quite different:

```
"/api/products": {
  "post": {
    "tags": [
      "FromFormIssue"
    ],
    "requestBody": {
      "content": {
        "multipart/form-data": {
          "schema": {
            "required": [
              "product"
            ],
            "type": "object",
            "properties": {
              "product": {
                "$ref": "#/components/schemas/Product"
              }
            }
          },
          "encoding": {
            "product": {
              "style": "form"
            }
          }
        },
        "application/x-www-form-urlencoded": {
          "schema": {
            "required": [
              "product"
            ],
            "type": "object",
            "properties": {
              "product": {
                "$ref": "#/components/schemas/Product"
              }
            }
          },
          "encoding": {
            "product": {
              "style": "form"
            }
          }
        }
      }
    },
    "responses": {
      "204": {
        "description": "No Content"
      }
    }
  }
}


"/api/products-with-openapi": {
  "post": {
    "tags": [
      "FromFormIssue"
    ],
    "requestBody": {
      "content": {
        "multipart/form-data": {
          "schema": {
            "$ref": "#/components/schemas/Product"
          }
        },
        "application/x-www-form-urlencoded": {
          "schema": {
            "$ref": "#/components/schemas/Product"
          }
        }
      },
      "required": true
    },
    "responses": {
      "204": {
        "description": "No Content"
      }
    }
  }
}
```

So, in Swagger I get the following result:

WRONG
![image](https://github.com/user-attachments/assets/ed8d13e3-44ec-43df-877b-b71f46c59051)

CORRECT
![image](https://github.com/user-attachments/assets/d4f7817c-9eee-40ce-a47a-7d4e4979331c)

### Expected behavior

Both the endpoints should produce the same `swagger.json` definition that defines the parameters from `Form`.

### Steps to reproduce

Minimal repro here: https://github.com/marcominerva/FromFormIssue

### Swashbuckle.AspNetCore version

6.9.0

### .NET Version

8.0.403

**Comment by jgarciadelanoceda** [comment]
I am going to take a look at these ( the controllers reports every Property of an object in the description, but MinimalApi seems to just report the type)

**Comment by jgarciadelanoceda** [comment]
Almost there! I am thinking about make the OpenApi almost equal for WithOpenApi/MinimalApi/Controllers.

The only difference that exists right now is that controllers put each property of the object in the ApiDescription and Minimal doesn't.

There is a small issue when there are 2 or more properties ( for example strings in a Form).. The WithOpenApi extension method puts AllOf whereas MinimalApi just writes two properties ( Both options are correct)
