### ISSUE TITLE
Request: please update nuget packages

### ISSUE THREAD

**Issue by freerkjelsma** [domaindrivendev/Swashbuckle.AspNetCore#314]
Hi,

When will you create a new (prerelease) nuget package?
The Swashbuckle.AspNetCore 1.0.0-rc1 has a two (blocking) issues for us that are already fixed in master:

1. commit https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/7fce261892fcd25d1dfee7b688c1bcd3125a7acb
(issue https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/266)

2. commit https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/0e45a32d2f33c01877332f6da1516eb54a042c0a
(issue https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/302)

Thanks

**Comment by domaindrivendev** [comment]
Just released https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/1.0.0-rc2
