### ISSUE TITLE
Exception caused by null ModelMetadata in XmlCommentsOperationFilter.cs

### ISSUE THREAD

**Issue by dopare** [domaindrivendev/Swashbuckle.AspNetCore#316]
I am using ASP.NET MVC API Versioning package and it is adding version parameter to operation's parameters list with null ModelMetadata which throws null exception in XmlCommentsOperationFilter.cs.

Created PR #315

**Comment by dopare** [comment]
@domaindrivendev please publish this commit on nuget.

**Comment by freerkjelsma** [comment]
+1 on updating the nuget package

**Comment by wertzui** [comment]
+1 on a NuGet release, I'm having the exact same problem and really need a fix.

**Comment by SteveDunlap13** [comment]
+1 on this fix please.  Can't continue or use Swashbuckle without.

**Comment by richardscholten73** [comment]
+ for the new NuGet release

**Comment by mgernand** [comment]
+1 for the package release.

**Comment by frankvl76** [comment]
+1 for package release!

**Comment by westonpace** [comment]
FYI, this was released in 1.0.0.
