### ISSUE TITLE
[Bug]: When submitting `multipart/form-data` request, nullable `int` and `Array` values are sent incorrectly

### ISSUE THREAD

**Issue by FlameWolf** [domaindrivendev/Swashbuckle.AspNetCore#3160]
### Describe the bug

When submitting `multipart/form-data` request, nullable `int` and `Array` values are sent incorrectly.

### Expected behavior

# Case 1:

Leave `IntProp` as blank.

## Expected behaviour:

Data parsed correctly and `IntProp` will be null.

# Case 2:

Specify some values for `IntArrProp` (example: 1, 2, 3).

## Expected behaviour:

Data parsed correctly and `IntArrProp` should be populated with the values `int[] { 1, 2, 3}`.

### Actual behavior

# Case 1:

## Actual behaviour:

Error: Microsoft.AspNetCore.Http.BadHttpRequestException: The value '' is not valid for 'IntProp'.

# Case 2:

## Actual behaviour:

Error: Microsoft.AspNetCore.Http.BadHttpRequestException: The value '1,2,3' is not valid for 'IntArrProp'.

### Steps to reproduce

Repo: [https://github.com/FlameWolf/DotNet9WebApi](https://github.com/FlameWolf/DotNet9WebApi)

Model:

```C#
public class PostBody
{
	public string Content { set; get; }
	public PollBody? Poll { set; get; }
	public IFormFile? Media { set; get; }
	public int? IntProp { set; get; }
	public int[]? IntArrProp { set; get; }
}
```

Endpoint:

```C#
group.MapPost("/post", ([FromForm] PostBody post) =>
{
	var guid = Guid.NewGuid();
	return Results.Ok(new
	{
		post.Content,
		post.Poll,
		Guid = guid
	});
})
.DisableAntiforgery();
```

### Swashbuckle.AspNetCore version

7

### .NET Version

9

### Anything else?

# Case 1:

## Reason:

Since `IntProp` is nullable, Swagger should not send it when blank, but it sends an empty string instead.

```bash
curl -k -X 'POST' \
  'https://localhost:7272/WeatherForecast/post' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'content=string' \
  -F 'poll={"option1":"string","option2":"string"}' \
  -F 'media=' \
  -F 'intProp=' \
  -F 'intArrProp=0'
```

# Case 2:

## Reason:

Since `IntArrProp` is an array, Swagger should send it as multiple form parts with the same name, but instead sends it as a single part with the values as a comma-separated list.

```bash
curl -k -X 'POST' \
  'https://localhost:7272/WeatherForecast/post' \
  -H 'accept: */*' \
  -H 'Content-Type: multipart/form-data' \
  -F 'content=string' \
  -F 'poll={"option1":"string","option2":"string"}' \
  -F 'media=' \
  -F 'intProp=' \
  -F 'intArrProp=1,2,3'
```

**Comment by martincostello** [comment]
Does the OpenAPI document describe the API requests in the format you'd expect? If so, then the issue is with Swagger UI's interpretation of the document, rather than our generation of it.

**Comment by FlameWolf** [comment]
Yes -- here is the relevant section of the generated `swagger.json`:


```JSON
"components": {
    "schemas": {
        "PollBody": {
            "type": "object",
            "properties": {
                "option1": {
                    "type": "string",
                    "nullable": true
                },
                "option2": {
                    "type": "string",
                    "nullable": true
                }
            },
            "additionalProperties": false
        },
        "PostBody": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "nullable": true
                },
                "poll": {
                    "$ref": "#/components/schemas/PollBody"
                },
                "media": {
                    "type": "string",
                    "format": "binary",
                    "nullable": true
                },
                "intProp": {
                    "type": "integer",
                    "format": "int32",
                    "nullable": true
                },
                "intArrProp": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "nullable": true
                }
            },
            "additionalProperties": false
        }
    },
    "securitySchemes": {
        "bearerAuth": {
            "type": "http",
            "description": "Enter your bearer token",
            "scheme": "Bearer",
            "bearerFormat": "JWT"
        }
    }
}
```

**Comment by martincostello** [comment]
If the OpenAPI document is correct, then this is a SwaggerUI issue not a Swashbuckle issue.

**Comment by FlameWolf** [comment]
Closing because this is not a Swashbuckle issue.
