### ISSUE TITLE
[Bug]: SwaggerUI post error route call

### ISSUE THREAD

**Issue by brotherhorse** [domaindrivendev/Swashbuckle.AspNetCore#3180]
### Describe the bug

When there is a method with the same name in two controls, calls made through the UI on one controller will point to the other controller:
`    [Route("v1/values")]
    public class ValuesController : ControllerBase
    {

        [HttpPost]
        [Route("action2")]
        public int Action2()
        {
            return 2;
        }

        [HttpPost]
        [Route("action")]
        public int Action()
        {
            return 1;
        }
    }`

` [Route("v1/VV")]
 public class VVController : ControllerBase
 {

     [HttpPost]
     [Route("action")]

     public int Action()
     {
         return 3;
     }

 }`

Call VVController .Action by SwaggerUI

### Expected behavior

return 3

### Actual behavior

return 2

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.

**Comment by brotherhorse** [comment]
Program.cs:
`using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.IO;
using System.Threading.Tasks;
namespace TestServiceApp
{
    public class Program
    {    
        public static Task Main(params string[] args)
        {
            var builder = WebApplication.CreateBuilder(new WebApplicationOptions
            {
                Args = args,
                ContentRootPath = Directory.GetCurrentDirectory(),
                EnvironmentName = Environments.Production,
            });
            var services = builder.Services;
            services.AddSwaggerGen(c =>
            {
                c.CustomOperationIds(apiDesc => apiDesc.TryGetMethodInfo(out var methodInfo) ? methodInfo.Name : null);
            });
            var mvc = services.AddMvcCore().AddApiExplorer();
            var app = builder.Build();
            app.UseRouting();
            app.UseSwagger();
            app.UseSwaggerUI();
            app.MapControllers();
            app.UseEndpoints((endpoints) => { });
            return app.RunAsync();
        }
    }
}`

VVController.cs:
`using Microsoft.AspNetCore.Mvc;
namespace TestServiceApp.Controllers
{
    [Route("v1/[controller]")]
    public class VVController : ControllerBase
    { 
        [HttpPost]
        [Route("action")]       
        public int Action()
        {
            return 3;
        }
    }
}`

ValuesController.cs:
`using Microsoft.AspNetCore.Mvc;
namespace TestServiceApp.Controllers
{
    [Route("v1/[controller]")]
    public class ValuesController : ControllerBase
    {  
        [HttpPost]
        [Route("action2")]
        public int Action2()
        {
            return 2;
        }
        [HttpPost]
        [Route("action")]
        public int Action()
        {
            return 1;
        }
    }
}`

**Comment by brotherhorse** [comment]
I use c.DisplayOperationId() to display the C# method's name.

**Comment by martincostello** [comment]
That's probably enough for someone to repro, but a GitHub project is much preferred so someone can just clone it and start debugging. For example, you've not provided your `.csproj` content, so someone will need to guess at what's needed.

The easier you make a problem to debug, the more likely someone will be to give up their free time to look into it.

**Comment by brotherhorse** [comment]
I have found the err:
    DisplayOperationId must be unique, but method's cannot guarantee uniqueness.

Thanks.
