### ISSUE TITLE
Operation filters inclusion order must be preserved

### ISSUE THREAD

**Issue by xperiandri** [domaindrivendev/Swashbuckle.AspNetCore#320]
Related to #261

My `FormFileOperationFilter` is added after `XmlCommentsOperationFilter` nevertheless it is included earlier.
In this case `XmlCommentsOperationFilter` reads incorrect parameters and `file` parameters do not have descriptions in Swagger.

**Comment by xperiandri** [comment]
Maybe adding `XmlCommentsOperationFilter` to the end of operation filters list will be enough?

**Comment by xperiandri** [comment]
In that case it works as expected.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/82dd0e696e7ac2c5ef218d06a1ce9e4a2c8ffc8d/src/Swashbuckle.AspNetCore.SwaggerGen/Application/SwaggerGenOptions.cs#L240
``` C#
swaggerGeneratorSettings.OperationFilters.Add(new XmlCommentsOperationFilter(xmlDoc));
```
instead of 
``` C#
swaggerGeneratorSettings.OperationFilters.Insert(0, new XmlCommentsOperationFilter(xmlDoc));
```

**Comment by domaindrivendev** [comment]
This seems like a chicken and egg problem. For your specific case, I completely understand why you would want to have the FormFileOperationFilter execute BEFORE the Xml comments filter. However, there may be other cases where you might want a custom filter to execute AFTER the Xml comments filter. For example, if you wanted to apply additional markdown formatting to the inserted descriptions.

I don't want to second guess peoples intentions. All of the built-in filters (including Xml comments) could just have easily been incorporated directly into the _SwaggerGenerator_. But, using filters allowed me to separate concerns a little better. But, I really consider those built-in filters to be part of the core SB behavior and so feel it's best to ensure they execute BEFORE any custom filters that have been wired up.

I want to stick with this rule of thumb. However, I would certainly consider incorporating the FormFileOperationFilter that you created into the Swashbuckle code. This way, it will just be another built-in filter which we could explicitly wire-up before the XML filter.

**Comment by xperiandri** [comment]
It is a good option.
However maybe just introduce ability to add filters before and after embedded?
