### ISSUE TITLE
[Question]: Migrate .Net Core WebApi project from Version 2.1 to 8.0

### ISSUE THREAD

**Issue by sibinthomask** [domaindrivendev/Swashbuckle.AspNetCore#3204]
### What are you wanting to achieve?

Hi all, I am trying to migrate .Net Core WebApi project from Version 2.1 to 8.0.

For last 2 days I am getting an Error - TypeLoadException: Could not load type 'Swashbuckle.AspNetCore.Swagger.Info' from assembly 'Swashbuckle.AspNetCore.Swagger, Version=7.2.0.0, Culture=neutral, PublicKeyToken=62657d7474907593'.

As we do usually, I installed packages from NuGet - Swashbuckle, Swashbuckle.AspNetCore, Swashbuckle.AspNetCore.SwaggerGen, Swashbuckle.AspNetCore.SwaggerUI, Swashbuckle.AspNetCore.Filters
But these are not working-out.

Please share your ideas to solve this error. If you can't comment here, please mail your ideas/answers to sibinthomask@gmail.com. That will be helpful for me.

### What code or approach do you have so far?

I installed packages from NuGet

**Comment by martincostello** [comment]
#3204
