### ISSUE TITLE
SingleApiVersion Deprecated?

### ISSUE THREAD

**Issue by cecilphillip** [domaindrivendev/Swashbuckle.AspNetCore#324]
I'm upgrading some old samples from Swashbuckle 6.0.0-beta901 to Swashbuckle.AspNetCore 1.0.0-rc3. The follow code no longer compiles. Is there a different way to do this now ?

``` csharp
 services.AddSwaggerGen(c =>
            {
                c.SingleApiVersion(new Info
                {
                    Version = "v1",
                    Title = "Simple API",
                    Description = "A demo API "
                });
            });
```

**Comment by domaindrivendev** [comment]
Read "Getting Started" in the readme. Essentially you use c.SwaggerDoc instead
