### ISSUE TITLE
Swashbuckle.AspNetCore.SwaggerGen and Swashbuckle.AspNetCore.SwaggerUi RC1 to RC3 update

### ISSUE THREAD

**Issue by AngelVHS** [domaindrivendev/Swashbuckle.AspNetCore#328]
After updating this 2 packages from version 1.0.0-rc1 to version 1.0.0-rc3 I noticed that the UseSwaggerUi extension method has been renamed to UseSwaggerUI. After changing the code the swagger endpoint stopped working and the following exception is now being shown: "Object reference not set to an instance of an object.". The HTTP error code is 500. The actual configuration line is "app.UseSwaggerUi(options => { options.SwaggerEndpoint("/swagger/v1/swagger.json", "V1 Docs"); });".
Is there some other changes that I should be implementing to accomplish the update?

Thanks in advance!

**Comment by xperiandri** [comment]
Try deleting `project.lock.json`

**Comment by AngelVHS** [comment]
Thank you, I will be looking forward for an updated package then.
