### ISSUE TITLE
Multiple ProducesResponseType For 200

### ISSUE THREAD

**Issue by louislewis2** [domaindrivendev/Swashbuckle.AspNetCore#329]
Hi,

I have a question. In one of the project I am working on, we have action methods
that can return different types based on a header value. while this might seems crazy
to some, we wanted customers to have for example a dedicated endpoint where they
can for example load a customer object. For example a call to api/customers/1 would return a 
customer lite object, containing a subset of the actual record. If they then want to load 
a more detailed object, they can for example add in a header called transform, with a value such as 
lite, detailed or expanded.

We felt it was better than adding multiple endpoints such as:
api/customer/1
api/customer/1/detailed
api/customer/1/expanded

Due to the amount of exposed types in the system, going with the route that we have chosen, we have spared almost 300 extra endpoints that would have been required to implement it in the url fashion.

Based on this, is there a way in which we can make use of this package and support such scenarios?

**Comment by erendrake** [comment]
To start off i want to say that this is an API design i see from time to time and its a natural impulse to not oversubscribe when you are fetching data from a service. It is very much against the spirt of REST. That being said I work in two teams right now and one of them continues to think its important to have this 'flexibility' so you are not alone. you could save the same number of endpoints by only exposing the largest type and implementing caching if it proves to be too slow.

The question is not if you can use Swashbuckle. its the swagger spec and client generation you are going to have trouble with. There is not a great way to describe this header interaction in swagger 2.0. This means generated clients will have a hard time discovering your API.

each operation has one definition per status code. so when you have multiple definitions that are actually available based on header you can either:

* **list the broadest definition as the response type**: this only works when this broadest definition is a proper superset of all of the other definitions. 
* **Make a custom filter**: you could build a custom filter that make a single endpoint appear as multiple endpoints, with a definition for each. This would be a little complicated and would still have a discoverability problem 
* **Use non-standard HTTP status codes** normally only one code _200_ is 'OK'. you could always list other codes as these other definitions. Its messy and client generation might not work but all of the definitions will show up in the output.

**Comment by louislewis2** [comment]
@erendrake Thank you for your quick and detailed response.
I should have written my specific use case which perhaps would have helped a bit.
We build and ship clients for our endpoints built directly from source, so the intention with 
Swashbuckle is not to enable automatic client generation.

Our clients would merely find it great to be able to use the ui that it generates to get an overview
of the endpoints and to be able to "play" around with it before heading straight for the code.

Our reasons behind this api design, was to minimize data across the wire by default, thus all our endpoints by default return the smallest useful form of the type in question. This is true for getting single values as well as paged results. The caller has to opt in to get a larger data object to work with. With the system. The defaults work well with the more common tasks, such as drop downs, lists etc. When a specific record is sought after they can then add the appropriate header  and get the results they are after. We found this very useful in an attempt to manage what some might call big data.

I will experiment with your ideas a bit and see which could work best before considering a forked version to play with.

Thanks again.

**Comment by domaindrivendev** [comment]
As per @erendrake's comments, the constraint here is going to be the Swagger specification and not Swashbuckle. So, I'm going to close this issue.

My two cents on the API design, I would always favor explicit URL's over overloaded ones. The closer you can tie a resource / URI to a specific use-case, the better as it allows you
