### ISSUE TITLE
ReadOnly Properties

### ISSUE THREAD

**Issue by louislewis2** [domaindrivendev/Swashbuckle.AspNetCore#330]
Hi,

I saw there was a issue created about potentially adding an attribute that could
prevent this package from exposing a certain property, this was turned down because 
simply making the property internal would fix this.

In my use case, we have a readonly public property, implemented as

```
public string CoolProperty => "Some Cool Property";
```

I cannot work out why this property would show up on the generated ui?
This property cannot be made internal, as it is from an external library;

**Comment by domaindrivendev** [comment]
If you look at the generated Swagger (e.g. /swagger/v1/swagger.json), you should see that the corresponding Schema property has the "readOnly" flag set. Unfortunately though, the [swagger-ui](https://github.com/swagger-api/swagger-ui) doesn't render these properties any differently. It's really a limitation with that tool and so you should post your issue in their repo.

**Comment by enemyofthedawn** [comment]
I made a filter for this that adds support for `ReadOnlyAttribute`: https://github.com/domaindrivendev/Swashbuckle/issues/138
