### ISSUE TITLE
Move to new project setup

### ISSUE THREAD

**Issue by ruant** [domaindrivendev/Swashbuckle.AspNetCore#335]
Since VS2017 is out now, is it time to move everything over to the new .csproj setup?

**Comment by ruant** [comment]
csproj changes: https://github.com/ruant/Swashbuckle.AspNetCore/commit/5bcbcf859c189ba0656a76d3790d95589321a8f8

I also updated everything to asp.net core 1.1 and the dependencies to the latest version: https://github.com/ruant/Swashbuckle.AspNetCore/commit/9ac44438dc1b6258d40ab12d1ade398649ddd1b4

For me it builds and runs fine, so if you want me to create a pull request let me know.

The only thing I noticed was that one of the test projects complained about a constructor, but that must have been there from the start?

Also, I've never migrated a project like this before, so if there something that should be changed let me know 😃

**Comment by domaindrivendev** [comment]
Have it done on a local branch and now trying to resolve some build warnings

**Comment by xperiandri** [comment]
Cool!

**Comment by ruant** [comment]
@domaindrivendev Awesome, let us know if you need help with anything 😃

**Comment by timotyweis** [comment]
@domaindrivendev any ideas of a new deadline for the `v1.0.0` release?
