### ISSUE TITLE
Error when using preferred Attribute Routing api versioning in .net core 1.1

### ISSUE THREAD

**Issue by drbergeron** [domaindrivendev/Swashbuckle.AspNetCore#340]
I created a new api controller containing 2 namespaces with the following route attribute on it:
```c#
namespace Apps.Api.Core.Controllers
{
    [ApiVersion("2.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    public class FooController : Controller
    {
         [HttpGet]
        public IActionResult Get()
        {
            return Ok(testset);
        }
    }
}

namespace Apps.Api.Core.Controllers.Deprecated
{
    [ApiVersion("1.0", Deprecated = true)]
    [Route("api/v{version:apiVersion}/[controller]")]
    public class FooController : Controller
    {

       [HttpGet]
        public IActionResult GetLegacy()
        {
            return Ok(testset);
        }
  }
}
```

In my startup.cs i have the following code to define versioning:
```C#
services.AddApiVersioning(o => {
                o.ReportApiVersions = true;
                o.AssumeDefaultVersionWhenUnspecified = true;
                o.DefaultApiVersion = new ApiVersion(2, 0);
            });
```

This works correctly and I am able to hit both of these endpoints via postman at:
http://localhost:28293/api/v2/Foo
and
http://localhost:28293/api/v1/Foo

However, I am getting the following error when generating swagger:
>NotSupportedException: HTTP method "GET" & path "api/v{version}/Foo" overloaded by actions - Apps.Api.Core.Controllers.FooController.Get (Apps.Api.Core),Apps.Api.Core.Controllers.Deprecated.FooController.GetLegacy (Apps.Api.Core). Actions require unique method/path combination for Swagger

Commenting out the legacy namespace does resolve this issue.

According to the article you call out on similar issues here:
http://blogs.msdn.com/b/webdev/archive/2014/08/22/customizing-web-api-controller-selector.aspx

attribute routing is the preferred method of doing this.

**Comment by domaindrivendev** [comment]
Have you configured SB to split each API version into a separate Swagger document as described here - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#generate-multiple-swagger-documents?

NOTE: You should read through that whole section and pay special attention to the sub-section entitled "Customize the Action Selection Process" as that provides a hint around specifically doing this with ApiVersion attributes.

**Comment by drbergeron** [comment]
Ah thanks, was reading much further down in the doc about Listing multiple swagger docs and not generating multiple swagger docs. Confirmed working now.
