### ISSUE TITLE
Empty document generated - WHY?!

### ISSUE THREAD

**Issue by floyd-may** [domaindrivendev/Swashbuckle.AspNetCore#341]
I had a not-so-great experience wiring SwaggerGen into my existing ASP.Net Core project, and I'm putting the details here so that you can hopefully add some things to Swashbuckle to save others in my situation the same headache I had. I followed the tutorial, yet the document that SwaggerGen created was empty.

In the process of debugging I wired up an `IApplicationModelConvention` implementation to verify that the `ApplicationModel` passed to the `Apply(...)` method does, in fact, contain references to all of my controllers. Digging further (including some code-surfing into the Swashbuckle.AspNetCore source [yay, GitHub]) I discovered that it was (long story short) due to using conventional routing instead of attribute-based routing in my site. Conventional routing, is, as you already know, incompatible with ApiExplorer, and by extension, conventional routing is incompatible with SwaggerGen.

So, my issue is this: 
**I had to spend a lot of time debugging and researching to learn that SwaggerGen and conventional routing were incompatible.** To address this, I would ask you to consider these two things:

1. Add something to the `IApplicationModelConvention` implementation at `Swashbuckle.AspNetCore.SwaggerGen.SwaggerApplicationConvention` that throws an exception when conventional routing is being used. Of course, that would throw on sites that use mixed routing, so you'll need a config option to ignore (rather than throw) when conventional routing is discovered. This would be a breaking change, and I do understand the disruption that such a change would cause. However, the value of the time saved for people in my situation would be **huge**.
2. Make it **absolutely clear** in the documentation that API endpoints using conventional routing will not be discovered. An FAQ item entitled something like "Why is my swagger document empty?" could save a lot of headache.

**Comment by domaindrivendev** [comment]
Thanks for the feedback. This is a free and open-source project - in that spirit, perhaps you could create a PR to update the readme?

**Comment by floyd-may** [comment]
> perhaps you could create a PR to update the readme?

Well that would just make too much sense! 😜
