### ISSUE TITLE
RC3, ConfigureOAuth2 results in Uncaught ReferenceError: log is not defined

### ISSUE THREAD

**Issue by ryangpts** [domaindrivendev/Swashbuckle.AspNetCore#342]
I am trying to get oauth2 with auth0 integrated but I get the following error in the chrome console. This error is in the console on first load of the page before the Authorize button is clicked.

Console Error: 

    Uncaught ReferenceError: log is not defined
        at initOAuth (swagger-oauth.js:1)
        at Object.onComplete (localhost/:56)
        at C.n.render (swagger-ui.min.js:13)
        at t.exports.options.success (swagger-ui.min.js:13)
        at t.exports.g.buildFromSpec (swagger-ui.min.js:7)
        at t.exports.l.finish (swagger-ui.min.js:8)
        at t.exports.l.resolve (swagger-ui.min.js:8)
        at response (swagger-ui.min.js:7)
        at h (swagger-ui.min.js:7)
        at t.on.response (swagger-ui.min.js:7)

ConfigureServices: 

     //Swagger API documentation functionality
     services.AddSwaggerGen(c =>
     {
          c.SwaggerDoc("v1", new Info { Title = "API", Version = "v1" });
          c.AddSecurityDefinition("oauth2", new OAuth2Scheme
          {
              Type = "oauth2",
              Flow = "implicit",
              AuthorizationUrl = Configuration["auth0:AuthorizationUrl"],
              Scopes = new Dictionary<string, string>
              {
                  { "openid", "openid" },
                  { "name", "name" },
                  { "email", "email" },
                  { "nickname", "nickname" }
              }
        });
    });

Configure:

    //Swagger
    app.UseSwagger();

    app.UseSwaggerUI(o =>
    {
        o.ShowJsonEditor();
        o.ShowRequestHeaders();
        o.SwaggerEndpoint("/swagger/v1/swagger.json", "SHPO API V1");
        o.ConfigureOAuth2(Configuration["auth0:ClientId"], null, null, "Swagger");
    });

**Comment by domaindrivendev** [comment]
This is really an issue for the [swagger-ui](https://github.com/swagger-api/swagger-ui) folks. It requires a non-null value for all the fields regardless of them being applicable for the flow in question.

That said, I just pushed the following commit - 82e336, to at least allow SB consumers to pass null for those optional fields. Before that's available, just pass "na" instead of null.

**Comment by ryangpts** [comment]
The error occurs regardless of what is passed to ConfigureOAuth2. I only have null in the example because it was the last thing I tried. But I also suspected this was a swagger-ui issue...

**Comment by domaindrivendev** [comment]
@ryangpts - hmmm, for me ... no error when I pass "na" instead of nulls

**Comment by ryangpts** [comment]
I am mistaken, passing dummy values does remove the error.
