### ISSUE TITLE
Installing Nuget package in VS 2017

### ISSUE THREAD

**Issue by Riaanvdw** [domaindrivendev/Swashbuckle.AspNetCore#343]
When trying to install nuget package in Visual Studio 2017 for ASP.Net core 1.1.
Get error Unable to load package 'Swashbuckle.AspNetCore.SwaggerUI'.

More info...
Failed to download package 'Swashbuckle.AspNetCore.Swagger.1.0.0-rc3' from 'https://www.myget.org/F/domaindrivendev/api/v3/flatcontainer/swashbuckle.aspnetcore.swagger/1.0.0-rc3/swashbuckle.aspnetcore.swagger.1.0.0-rc3.nupkg'.
An error occurred while sending the request.
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  The remote certificate is invalid according to the validation procedure.

**Comment by erendrake** [comment]
I was able to install it from the nuget.org feed just fine a few seconds ago. and as of right now the myget ssl looks ok to me. you should try it again or switch to the nuget.org feed

**Comment by domaindrivendev** [comment]
I'm also unable to repro this issue. I'm going to close for now but please feel free to re-open if you have more details and can provide a consistent set of repro steps
