### ISSUE TITLE
Http Header Based Versioning

### ISSUE THREAD

**Issue by briziomusic** [domaindrivendev/Swashbuckle.AspNetCore#346]
Hi,
I'm starting a new project with Swashbuckle.AspNetCore. I created one method with version 1 and 2.
Everything is working fine.
Methods

```
[HttpGet("PublicMethodWithVersion")]
[ApiExplorerSettings(GroupName = "v1")]
public string PublicMethodV1([FromHeader(Name = "x-api-version")]string version)
{
    return "You are hitting V1 method!";
}

[HttpGet("PublicMethodWithVersion"), MapToApiVersion("2.0")]
[ApiExplorerSettings(GroupName = "v2")]
public string PublicMethodV2([FromHeader(Name = "x-api-version")]string version)
{
    return "You are hitting V2 method!";
}
```
I can see the x-api-version in the parameters section for these apis.
Is it possibile to show the x-api-version parameter globally in Swagger (for all apis) without use FromHeader attribute in the signature???

I would like also set the 'x-api-version' automatically, based on the selected api/document version (dropdown on top). Is it possibile?
Thanks

![swa](https://cloud.githubusercontent.com/assets/3625306/24048741/12590558-0b2a-11e7-8dcc-2eca90f4a2a2.png)

**Comment by domaindrivendev** [comment]
This isn't as straightforward as it could be but still ... with a little bit of customization you can achieve the right result. You can automatically add the parameter, and default it's value to the current document version, by wiring up a Document Filter (see readme) that automatically adds the param to all operation descriptions:

```csharp
// AddGlobalVersionHeader.cs
public class AddGlobalVersionHeader : IDocumentFilter
{
    public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
    {
        var version = swaggerDoc.Info.Version;

        foreach (var pathItem in swaggerDoc.Paths.Values)
        {
            TryAddVersionParamTo(pathItem.Get, version);
            TryAddVersionParamTo(pathItem.Post, version);
            TryAddVersionParamTo(pathItem.Put, version);
            TryAddVersionParamTo(pathItem.Delete, version);
        }
    }

    private void TryAddVersionParamTo(Operation operation, string version)
    {
        if (operation == null) return;

        if (operation.Parameters == null)
            operation.Parameters = new List<IParameter>();

        operation.Parameters.Add(new NonBodyParameter
        {
            Name = "x-api-version",
            In = "header",
            Type = "string",
            Default = version
        });
    }
}

// Startup.cs
services.AddSwaggerGen(c =>
{
    ...
    c.DocumentFilter<AddGobalVersionHeader>();
};
```

This gets you mostly there. The only additional step you may want to take would be to hide this parameter in the UI as it's already defaulted to the required value. To do this, you should checkout the readme section on injecting custom CSS - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#inject-custom-css. Seems like a simple CSS rule would round things off nicely!

**Comment by briziomusic** [comment]
Thank you really much @domaindrivendev !
Very helpfull
