### ISSUE TITLE
oauth2 does not pass authorization once authenticated

### ISSUE THREAD

**Issue by mjnorman** [domaindrivendev/Swashbuckle.AspNetCore#347]
Using the following config--

```services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Swashbuckle.AspNetCore.Swagger.Info { Title = "ScheduleCallback", Version = "v1" });
                c.AddSecurityDefinition("oauth2", new OAuth2Scheme
                {
                    Type = "oauth2",
                    Flow = "application", 
                    TokenUrl = "http://localhost:5000/connect/token",
                    AuthorizationUrl = "http://localhost:5000",
                    Scopes = new Dictionary<string, string>
                    {
                        { "Callbacks", "Access read operations" }
                    }
                });
                c.OperationFilter<SecurityRequirementsOperationFilter>();
            });
```
with the sample IOperationFilter class given in the oauth2 documentation, I cannot seem to get swagger to pass in the Authorization.  I see the authorize button and the red ! on each operation.  When you click it and enter request_body, with given client_id and password, I can see that Identity4 passes out the token, but it is not delivered on the swagger post, and thus results in a 401.

At first my controller was decorated with [Authorize] only, however it would not pass the IOperationFilter configuration until I added a policy and changed the tag to [Authorize("Callbacks")].

Also using RC3.

Any advice?  Thanks for the awesome tool!

**Comment by xperiandri** [comment]
I experience the same thing.
`Authorization` header is not passed even though authentication to OpenIddict happens successfully.
@domaindrivendev is it **Swagger UI** issue?

**Comment by xperiandri** [comment]
The issue was related to absent CORS configuration on authentication server

**Comment by mnarz** [comment]
@xperiandri I seem to experience the same issue, but my client has the cors allowed in identity4. Can you tell me what you meant with your post exactly? Maybe some src-code?

**Comment by xperiandri** [comment]
``` C#
options.AddSecurityDefinition("OpenId Connect", new OAuth2Scheme {
    Type = "oauth2",
    Flow = "password",
    TokenUrl = "https://localhost:44396/connect/token",
    Scopes = new Dictionary<string, string>
    {
        { Auth.Scopes.KnowledgeBase, "Knowledge Base API" }
    }
});
```

No OpenId Connect scopes in declaration
Type: Request Body
Client credentials as configured

![image](https://user-images.githubusercontent.com/2365592/29285778-5bc7323a-8138-11e7-929e-cc8912127aeb.png)

**Comment by mnarz** [comment]
@xperiandri Thanks for your answer, but I think we misunderstood each other... I configured the swagger correctly: I even see the token generation process from IS4 but this token is not transferred to the swagger-SPA... hitting F12 in firefox shows me an error concerning CORS policy, but I don't know how or where to configure allowed CORS as my client (in IS4's ClientStore) already has two allowed CORS (including swagger-spa).
I think the InMemory-Extenions of the ISBuilder do some stuff that normal store-extensions don't do.

**Comment by mnarz** [comment]
@xperiandri Found my bug... As we implemented Stores ourselves we forgot to implement an own CorspolicyService. That's why our origins were not checked... Thank you for your help.

**Comment by xperiandri** [comment]
@mjnorman, have you solved your issue?

**Comment by mjnorman** [comment]
No I have not re approached this since I reported it.

**Comment by mnarz** [comment]
@mjnorman For our implementation there is no need for any IOperationFilter implementation. Our AddSecurityDefinition call looks quite the same as @xperiandri posted above. That's it.

**Comment by mnarz** [comment]
@mjnorman For our implementation there is no need for any IOperationFilter implementation. Our AddSecurityDefinition call looks quite the same as @xperiandri posted above. That's it.
