### ISSUE TITLE
Any plans on updating to latest swagger ui 3.x

### ISSUE THREAD

**Issue by fhelje** [domaindrivendev/Swashbuckle.AspNetCore#349]
Is there any plans to upgrade the ui to latest swagger ui?

**Comment by erendrake** [comment]
3.0.2 has been out for 2 days! give @domaindrivendev some time :)

im sure they would also take a pull request if you wanted it that bad

**Comment by fhelje** [comment]
It was more a question on if and if so when and is there a plan. Which would make it easier to see if I could help out.

**Comment by gingters** [comment]
This is related to #179, as the issue is solved in swagger-ui 3.x . So upgrading to swagger-ui 3.x should also solve #179 automagically ;-)

**Comment by coderangerdan** [comment]
Is there a plan for this on the non-aspnetcore repo as well?

**Comment by IGx89** [comment]
PR #453 is out there for upgrading to Swagger UI 3.0.x but sadly seems to have stalled. The 3.0 upgrade will solve a lot of issues in this issue tracker it seems.
