### ISSUE TITLE
.NetCore V1.1

### ISSUE THREAD

**Issue by gforceg** [domaindrivendev/Swashbuckle.AspNetCore#353]
Hello,

I'm trying to use Swashbuckle in .NetCore V1.1. When I run:
```
dotnet add package Swashbuckle.AspNetCore
```

I get:
```
error: Unable to resolve 'Swashbuckle.AspNetCore' for '.NETCoreApp,Version=v1.1'.
```

I don't know a lot about this project but I think #335 fixed this issue. So I cloned this repo and built the solution. I was able to get the build to complete w/o issue after creating an environmental variable called APPVEYOR_BUILD_FOLDER but I don't know what to do with the resulting .nupkgs package. (I'm not usually a .Net developer)

Are there steps I can take to use these local .nupkgs in my project until the above command works in the future?

Thanks!

**Comment by domaindrivendev** [comment]
Swashbuckle for AspNetCore is still in pre-release (stable release overdue) and you have to tell Nuget explicitly if you want to download pre-release versions of a package. The following should do it:

    dotnet add package Swashbuckle.AspNetCore -v 1.0.0-*

**Comment by xperiandri** [comment]
@gforceg, you can import packages from file system folder by adding elements like this
`<add key="Local" value="C:\Users\Андрій\Dev\NuGet\packages" />`
into **NuGet.config** placed in a root folder of your solution.

**Comment by gforceg** [comment]
nice! that's good to know. I haven't had a chance to try either of the above yet. . . deadlines. :balance_scale:
