### ISSUE TITLE
XML comments NullReferenceException

### ISSUE THREAD

**Issue by fabiomaulo** [domaindrivendev/Swashbuckle.AspNetCore#355]
First of all, sorry to not send a PR with its test.. I hope you can sniff the problem quickly than I clone the repo and so on.

There is just one method with XML comments.

**NullReferenceException: Object reference not set to an instance of an object.**
Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter ApplyPropertiesXmlToPropertyParameters 
ApiParameterDescription 

The API has 2 versions, and all others methods, so far, has no comments.
The whole XML is something like this (I just blurs something)

[Company.Feature.Api.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/869608/Company.Feature.Api.txt)

**Comment by commonsensesoftware** [comment]
I'm also facing this, but it seems to have been fixed in #315. Unfortunately, that change is apparently not in RC3.

**Comment by WeihanLi** [comment]
I also met this problem and I'm using the version `1.0.0-rc3` ,error is as follows:
```
NullReferenceException: Object reference not set to an instance of an object.
Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter+<>c.<ApplyPropertiesXmlToPropertyParameters>b__11_0(ApiParameterDescription p)
```

**Comment by commonsensesoftware** [comment]
Until the fix is included in a published package, the following should workaround the issue by defaulting any unset model metadata to be the `string` model.

```c#
public class SwaggerApiDescriptionProvider : IApiDescriptionProvider
{
    readonly ModelMetadata @string;

    public SwaggerApiDescriptionProvider( IModelMetadataProvider metadadataProvider ) =>
        @string = metadadataProvider.GetMetadataForType( typeof( string ) );

    public int Order => 0;

    public void OnProvidersExecuted( ApiDescriptionProviderContext context )
    {
        foreach ( var result in context.Results )
        {
            foreach ( var parameter in result.ParameterDescriptions )
            {
                if ( parameter.ModelMetadata == null )
                {
                    parameter.ModelMetadata = @string;
                }
            }
        }
    }

    public void OnProvidersExecuting( ApiDescriptionProviderContext context ) { }
}
```
To wire this up in your application, just use:

```c#
builder.Services.TryAddEnumerable(
  ServiceDescriptor.Transient<IApiDescriptionProvider, SwaggerApiDescriptionProvider>() );
```

The new API description provider will be run in addition to the built-in provider and fix-up null model metadata before Swagger does it's thing.

I hope that helps.

**Comment by professorjoshua** [comment]
When will a new release be available so we don't have to use the work around?

**Comment by professorjoshua** [comment]
@commonsensesoftware I receive an error when I put your code into my application.  In the SwaggerApiDescriptionProvider class I get an error on the constructor:  "must declare a body because it is not marked abstract, extern, or partial".

Any suggestions?

**Comment by commonsensesoftware** [comment]
Sounds like a compiler error. If I had to guess, you aren't using C# 7.0 [but should be ;)]. Just change the code from an _expression body_ to an actual body.

**Comment by professorjoshua** [comment]
@commonsensesoftware I had figured out the I needed to change the code to an actual body.  I have one other issue, no definition of Services within the IConfigurationBuilder (builder).  Is this because I'm still using VS2015?  Is there another solution for an earlier version of C#?

**Comment by professorjoshua** [comment]
@commonsensesoftware I added:

services.TryAddEnumerable(ServiceDescriptor.Transient<IApiDescriptionProvider, SwaggerApiDescriptionProvider>());

to the ConfigureServices method.  I know see my comments!!!

But I still have an issue because the link to Swagger still fails.

**Comment by sm-g** [comment]
Got same issue after updating from rc1 to rc3.

**Comment by domaindrivendev** [comment]
I believe this was fixed some time ago so going to close it. If you're still experiencing this with the latest version (2.5.0 as of writing), feel free to re-open the issue (with clear repro steps)
