### ISSUE TITLE
No JSON object returned when including comments

### ISSUE THREAD

**Issue by professorjoshua** [domaindrivendev/Swashbuckle.AspNetCore#359]
I am able to see the JSON object when I do not include the API comments.  

services.AddSwaggerGen(c => {
   c.SwaggerDoc("v1", new Swashbuckle.AspNetCore.Swagger.Info { Title = "MM2.0 API", Version = "v1" });   
});

However, if I include the XML comments nothing gets returned.

services.AddSwaggerGen(c => {
   var filePath = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "MenuManager.API.xml");
  c.IncludeXmlComments(filePath);
  c.SwaggerDoc("v1", new Swashbuckle.AspNetCore.Swagger.Info { Title = "MM2.0 API", Version = "v1" });
 });

**Comment by helgejfo** [comment]
Same here, both for 1.0.0-rc2 and 1.0.0-rc3, works in 1.0.0-rc1. 

ASP.NET Core version, netcoreapp1.1 and Microsoft.AspNetCore 1.1.1. Project created using V2017.

**Comment by domaindrivendev** [comment]
Can you navigate directly to the Swagger JSON endpoint (swagger/v1/swagger.json) to get more details about the error? NOTE: you may need to enable the developer exceptions middleware:

```csharp
app.UseDeveloperExceptionPage()
```

**Comment by professorjoshua** [comment]
IApplicatonBuilder does not contain a definition for 'UseDeveloperExceptionPage.

**Comment by helgejfo** [comment]
Included the stack trace. Same exception for both rc2 and rc3.

[stack.txt](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/881299/stack.txt)

**Comment by euang** [comment]
Isn't this a duplicate of #355 ?

**Comment by professorjoshua** [comment]
It could be a duplicate of #355.  When will the new release be available?

**Comment by professorjoshua** [comment]
@helgejfo @domaindrivendev @euang I was able to work around the problem following the workaround in #355.  The JSON object now comes up with the comments.  The swagger site still fails but at least I know have the comments in the JSON object!
