### ISSUE TITLE
support for Microsoft.AspNetCore.StaticFiles (1.0.2)

### ISSUE THREAD

**Issue by patricknolan** [domaindrivendev/Swashbuckle.AspNetCore#360]
Hi,

I need to reference Microsoft.AspNetCore.StaticFiles (1.0.2) and am also wanting to use the latest release of SwashBuckle.Swagger.

When I call Microsoft.AspNetCore.Builder.SwaggerUiBuilderExtensions.UseSwaggerUi i get the following error

System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.AspNetCore.StaticFiles, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.'

Is there anything I can do to get around this error?

**Comment by domaindrivendev** [comment]
There must be something specific to your setup as I can't repro this issue. I have the following dependencies and it all works fine:

![screen](https://cloud.githubusercontent.com/assets/1434343/24464626/40bb51d8-145f-11e7-8904-4407a99cf0d1.png)

You should try clearing out your bin folders to ensure and old DLL isn't lying around

**Comment by patricknolan** [comment]
Thanks for your reply.

Below is the fusion log for the bind error. As you can see it is clearly searching for Microsoft.AspNetCore.StaticFiles, Version=1.0.0.0 and failing because it finds Microsoft.AspNetCore.StaticFiles, Version=1.0.2.0

Would you have any other ideas?

![image](https://cloud.githubusercontent.com/assets/21054590/24480231/88bc314c-1526-11e7-959d-d19842e2dff1.png)

**Comment by patricknolan** [comment]
I'm also getting this error for Microsoft.AspNetCore.Mvc.Core

System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.'

Using Telerik JustDecompile I can see that in fact Swashbuckle.AspNetCore.SwaggerGen was compiled using Microsoft.AspNetCore.Mvc.Core, Version=1.0.0.0 (see screenshot attached)

Would it be possible to update Swashbuckle.AspNetCore.Swagger, Swashbuckle.AspNetCore.SwaggerGen and Swashbuckle.AspNetCore.SwaggerUI to use the latest AspNetCore assemblies? i.e. 1.1.2

![image](https://cloud.githubusercontent.com/assets/21054590/24739121/bae98f7c-1add-11e7-996f-f889cf477a5d.png)

**Comment by xperiandri** [comment]
At least PATCH version of the referenced package must be maximal to avoid issues and vulnerabilities

**Comment by domaindrivendev** [comment]
Let me know if this issue is still persisting with the latest version of Swashbuckle?
