### ISSUE TITLE
When adding Extension on Parameter, it does not populate in the schema

### ISSUE THREAD

**Issue by Alegrowin** [domaindrivendev/Swashbuckle.AspNetCore#368]
Let's say I have a controller like this:

```csharp
public class HomeController : Controller
{
    [Route("")]
    [HttpGet]
    [AllowAnonymous]
    public HomeResponse Get([FromQuery]Go soso)
    {
        return new HomeResponse
        {
            Result = "Welcome to the API"
        };
    }
}
```
Where Go is:
```csharp
public enum Go
{
    Asdf,
    Asdfge,
    Asdfasdva,
    Asdcvawce
}
```

If I add the following Schema Filter:
```csharp
public class EnumTypeSchemaFilter : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaFilterContext context)
        {
            var typeInfo = context.SystemType.GetTypeInfo();

            if (typeInfo.IsEnum)
            {
                schema.Extensions.Add(
                    "x-ms-enum",
                    new
                    {
                        name = typeInfo.Name,
                        modelAsString = false
                    });
            }
        }
    }
```

I would expect something like (working with Autorest 1.0.1-20170331-1605-preview):
```json
 "paths": {
    "/": {
      "get": {
        "consumes": [],
        "operationId": "Get",
        "parameters": [
          {
            "enum": [
              "Asdf",
              "Asdfge",
              "Asdfasdva",
              "Asdcvawce"
            ],
            "in": "query",
            "name": "soso",
            "required": false,
            "type": "string",
            "x-ms-enum": {
              "modelAsString": false,
              "name": "Go"
            }
          }
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/HomeResponse"
            }
          }
        },
        "tags": [
          "Home"
        ]
      }
    },
```

But I get this instead:
```json
 "paths": {
    "/": {
      "get": {
        "consumes": [],
        "operationId": "Get",
        "parameters": [
          {
            "enum": [
              "Asdf",
              "Asdfge",
              "Asdfasdva",
              "Asdcvawce"
            ],
            "in": "query",
            "name": "soso",
            "required": false,
            "type": "string"
          }
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/HomeResponse"
            }
          }
        },
        "tags": [
          "Home"
        ]
      }
    },
```

I've put a breakpoint and the schema filter works for the Enum, so adding the Extension is working. But there must be a sanitize after and it removes my extension or the Extensions are not passed as ref so they are not saved.

Any clues?

**Comment by Alegrowin** [comment]
I've traced back an issue in Swashbuckle where someone tried to use a complex type (json) as a query parameter. [https://github.com/domaindrivendev/Swashbuckle/issues/277](https://github.com/domaindrivendev/Swashbuckle/issues/277) 

@domaindrivendev said: For query parameters, you are limited to the following types - "string", "number", "integer", "boolean", "array" or "file".

Does that mean the json gets sanitized because swagger specification does not support Enum as query parameter?

Thanks

**Comment by domaindrivendev** [comment]
Just tried this in the latest version (1.2.0) and it appears to work correctly, so no repro at this point. Feel free to re-open if you still can't get it to work with the latest version.

**Comment by jhtodd** [comment]
I'm experiencing the same problem in 1.2.0 as well as 2.4.0, using the `x-ms-enum` sample code copied from the README.md.

**Comment by gabeluci** [comment]
I'm seeing this in 2.4.0 as well. `x-ms-enum` is added to properties of classes, but not to parameters.

**Comment by gabeluci** [comment]
[SwashbuckleEnumTest.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/1933076/SwashbuckleEnumTest.zip)

I've attached a minimal test project. It's a single controller with a single action:

    [HttpGet]
    public Color Get(Color color) {
        return color;
    }

I included the generated swagger.json file in the zip file. You'll see that it includes `x-ms-enum` with the return type, but not for the parameter.

    "parameters":[
       {
          "name":"color",
          "in":"query",
          "required":false,
          "type":"string",
          "enum":[
             "Red",
             "Green",
             "Blue"
          ]
       }
    ],
    "responses":{
       "200":{
          "description":"Success",
          "schema":{
             "enum":[
                "Red",
                "Green",
                "Blue"
             ],
             "type":"string",
             "x-ms-enum":{
                "name":"Color",
                "modelAsString":false
             }
          }
       }
    }

**Comment by gabeluci** [comment]
Does anyone get notifications on closed issues? I can't reopen. Maybe I should just open a new issue.

**Comment by OzBob** [comment]
My version of Swashbuckle 5.6.0 doesn't filter to Enum types, so I needed to add

                 c.ApplyFiltersToAllSchemas();
