### ISSUE TITLE
My custom index.html file no longer works

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [domaindrivendev/Swashbuckle.AspNetCore#369]
With the previous beta version of swashbuckle, we created a custom index.html file with a custom css file.  Following these directions:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger

And using the section "customising the ui".

I have upgraded to vs 2017, and am now using the latest RC build of swashbuckle.
My custom stylesheet is no longer being used and I only see the original styles.

Is there a different way to do this now?

**Comment by ThinkAboutGitHub** [comment]
It seems like the issue may be that i'm using a custom path to my index file, how is this achieved?

**Comment by kraihn** [comment]
For me the, the Swagger UI path changed from /swagger/ui/index.html to /swagger/index.html. Moving the files fixed it for me.

**Comment by ThinkAboutGitHub** [comment]
Thanks for the reply, I had noticed that the ui folder was no longer in use.  However due to our project's modular structure, we are using an entirely different folder structure at the top.

Previously though this worked by us doing the following:
app.UseStaticFiles(new StaticFileOptions()
            {
                FileProvider = new PhysicalFileProvider(
                    Path.Combine(Directory.GetCurrentDirectory(), @"DifferentFolder\wwwroot\Swagger")),
                    RequestPath = new PathString("/Swagger")
            });

This no longer seems to be the case.

**Comment by ThinkAboutGitHub** [comment]
Ok I got around this issue partly, by playing with the directory structure a bit.  However there is still a problem, in that previously we had html images defined in the xml comments. 
These images are now being displayed as text html, rather than displaying the icons that were working previously.
Is there something different in the way that this works now or is this a bug?

**Comment by ThinkAboutGitHub** [comment]
Ok I fixed this by playing with the directory structure a bit more.
