### ISSUE TITLE
DateTime Format is not according to swaggers expectations

### ISSUE THREAD

**Issue by senj** [domaindrivendev/Swashbuckle.AspNetCore#375]
Hey guys,

I have a problem with the C# DateTime object.
I want to provie a Schema Example of an object that has a DateTime.
Problem is that the Json Serializer on default will write the value as ```0001-01-01T00:00:00``` but the Swagger Spec expects ```0001-01-01T00:00:00Z```.
I can't do a ToString("...") on the DateTime because I dont want to have a string in my object definition but DateTime.

Does anyone know an easy answer or do I have to change the serialization to take this into account?

Thanks

**Comment by chrisoverzero** [comment]
Are you giving it the value `new DateTime()` (or `default(DateTime)`), or is the all-zeroes representation in your example only an example? A default `DateTime` has its `DateTimeKind` set to `Unspecified`, which will omit the time zone.

```csharp
JsonConvert.SerializeObject(default(DateTime)); //=> "0001-01-01T00:00:00"
JsonConvert.SerializeObject(DateTime.Now); //=> "2017-05-16T12:08:20.6771719-04:00"
```

The default value of `DateTimeOffset` will always show a time zone offset, natch.

```csharp
JsonConvert.SerializeObject(default(DateTimeOffset)); //=> "0001-01-01T00:00:00+00:00"
JsonConvert.SerializeObject(DateTimeOffset.Now) //=> "2017-05-16T12:12:23.0031721-04:00"
```

I think you should either provide an actual example value or switch to `DateTimeOffset`.

**Comment by senj** [comment]
Wow thats interesting, thanks for the Info.
