### ISSUE TITLE
SwaggerDoc missing for net core 1.1.0

### ISSUE THREAD

**Issue by nukec** [domaindrivendev/Swashbuckle.AspNetCore#376]
SwaggerDoc is not recognized.

[http://imgur.com/a/05OYy](http://imgur.com/a/05OYy)

**Comment by shotor** [comment]
I haven't been able to get `Swagger` working on `dot net core 1.1.0`

If I try the `ConfigureSwaggerGen` I get an exception when browsing to the `/swagger` route.

When I use `AddSwaggerGen` instead, the exception is gone. But then I get a 404:

```
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });

                // add stuff
//                c.IncludeXmlComments("/");
//                c.DescribeAllEnumsAsStrings();
            });
```

I'm curious how you got `service.AddSwaggerGen` to work without a parameter. I had to do this to get it through the compiler:
```
            services.AddSwaggerGen(opt =>
            {

            });
```

I'll keep digging but it appears that Swashbuckle is not compatible with 1.1, at least not with the instructions in the readme.

**Comment by hanssens** [comment]
What works for me is something like:


```
    services.AddSwaggerGen(swagger =>
    {
        swagger.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
        swagger.IncludeXmlComments(Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "MyApi.xml"));
    });
```

**Comment by nukec** [comment]
I was using wrong version, correct version is Install-Package Swashbuckle.AspNetCore -Pre. I was using something else.
