### ISSUE TITLE
Apply new theme

### ISSUE THREAD

**Issue by Jonatthu** [domaindrivendev/Swashbuckle.AspNetCore#377]
How can I apply this theme?
https://github.com/legendecas/material-swagger-ui
Or another theme with this kind of changes?

**Comment by michaelsogos** [comment]
I have the same question.
Swagger UI default theme is very ugly in my opinion; i look around and i found a lot of different an coolest themes; like [this one ](https://github.com/jensoleg/swagger-ui) inspired by SLATE.

There are options to adopt a different theme?

**Comment by tillig** [comment]
Take a look at the [CustomIndexHtml example in the repo](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/CustomIndexHtml/Startup.cs) to see how to swap in your own HTML and CSS. It's not much harder than just dropping your own stuff into wwwroot/swagger.

**Comment by jsears** [comment]
The latest version from nuget (tag 1.1.0) does not contain the example code.  Please advise where to pull this code from?

**Comment by domaindrivendev** [comment]
The library you've referenced above isn't really a theme, it's an _alternative_ to the swagger-ui. That is, it's a completely different front-end application.

Swashbuckle ships with two different UI libraries - the swagger-ui and ReDoc. Furthermore, you can customize both of them by injecting a custom `index.html` file as shown in the following example:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v2.5.0/test/WebSites/CustomUIIndex/Startup.cs#L29

However, if you want to use a completely different front-end library like the one you've referenced above, then you'll need to do the heavy lifting yourself. They are just static assets, so this could be done with a simple webserver (IIS, NGINX etc.) or if you want to do it through middleware in your ASP.NET Core app then you can create a project that's very similar to the `SwaggerUI` or `ReDoc` projects in Swashbuckle:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/v2.5.0/src/Swashbuckle.AspNetCore.SwaggerGen

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/v2.5.0/src/Swashbuckle.AspNetCore.ReDoc

**Comment by quetzalcoatl** [comment]
@domaindrivendev I suppose you mean SwaggerUI instead of SwaggerGen?
