### ISSUE TITLE
ProducesResponseType with ModelStateDictionary

### ISSUE THREAD

**Issue by totht91** [domaindrivendev/Swashbuckle.AspNetCore#379]
I'm trying to use multiple `ProducesResponseTypeAttribute` on my action, but if I use built in types like `ModelStateDictionary` the swagger page doesn't contain this class' model. If I use custom type it works like charm.

**Not working:**
```C#
[HttpGet("{id}")]
[ProducesResponseType(typeof(Product), (int)HttpStatusCode.OK)]
[ProducesResponseType(typeof(ModelStateDictionary), (int)HttpStatusCode.BadRequest)]
public IActionResult Get(int id)
{
    return Ok(_mapper.Map<Product>(_productService.GetProduct(id)));
}
```

![image](https://cloud.githubusercontent.com/assets/8333960/25176288/f4c23bb6-24fd-11e7-8744-fe3916e9a7d3.png)

**Working but I don't want this:**
```C#
[HttpGet("{id}")]
[ProducesResponseType(typeof(Product), (int)HttpStatusCode.OK)]
[ProducesResponseType(typeof(Order), (int)HttpStatusCode.BadRequest)]
public IActionResult Get(int id)
{
    return Ok(_mapper.Map<Product>(_productService.GetProduct(id)));
}
```

![image](https://cloud.githubusercontent.com/assets/8333960/25176354/2409dc80-24fe-11e7-9cc4-2fd2b4ac8e65.png)

**Comment by totht91** [comment]
ping

**Comment by totht91** [comment]
Okay I dig into this a little bit and I found that the asp.net core pipeline does not use `ModelStateDictionary` as a return value for `BadRequest` rather than a [`SerializableError` class](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/SerializableError.cs). This is formally a `Dictionary<string, object>` but technically a `Dictionary<string, string[]>` [see](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/SerializableError.cs#L49-L55).

So we need to use `[ProduceResponseType(typeof(Dictionary<string, string[]>)]` attribute to achive the same functionality as the MVC pipeline works. However after this the swagger ui still cannot visualize the response's model, because the `Dictionary<string, whatever>` is a simple json object with unspecified property names. Besides that in the swagger schema is correct so the client side code generation should work.
![image](https://user-images.githubusercontent.com/8333960/34069532-f6416278-e253-11e7-8508-e4cab8c68a5f.png)

Could we find out some way to visualize this model in the swagger UI?

**Comment by domaindrivendev** [comment]
Essentially a dup of #337
