### ISSUE TITLE
Respect Properties Casing on Schemas

### ISSUE THREAD

**Issue by AliBazzi** [domaindrivendev/Swashbuckle.AspNetCore#383]
Hi,

I have a model that is returned by a Get Call, this model contains PascalCase named Properties like the following:

```
public Class CustomModel
{
    public string Value1 {get;set;}
    public int Value2 {get;set;}
}
```

the swagger document contains the schema description as camelCase, i.e. : value1, value2.
with that it overrides the casing that is specified on the Model,

any way to configure the library to respect the casing on the model ? 
thanks.

**Comment by wgasparin** [comment]
Same problem here. 
We could add an attribute, for example, [JsonProperty("Value1")] to force to show as it is on swagger.

**Comment by domaindrivendev** [comment]
Swashbuckle uses the casing that your JsonSerializer is configured to use for serializing objects to JSON. Which is clearly more appropriate than the casing used in code.

So, you should configure your serializer to use PascalCase (I believe camel is now the default) and then Swadhbuckle will just follow suit. I took the liberty of googling how to do this and the following post came up:

https://codeopinion.com/asp-net-core-mvc-json-output-camelcase-pascalcase/

**Comment by PeterAnaniaHC** [comment]
Thank you so much for developing a tool that tells us how we should code, but I wondering if instead you could give us a tool that we can configure to work as we want it to?

The URL you gave us suggests we add AddMVC to our configured services. What if I'm not using that? What if I'm building an API using AddControllers? It would be simpler (just my opinion as a person who builds solutions for users who prefer to be allowed to define their own processes) if the Swagger UI didn't modify our data by default and instead allowed us to configure it to use whatever case we wanted IF we wanted it to.

Just a suggestion.

**Comment by twinter-patriot** [comment]
> What if I'm building an API using AddControllers?

Then go ahead and do that. That's what we do in our APIs. Works just fine with Swagger/Swashbuckle.

>  It would be simpler ... if the Swagger UI didn't modify our data

It doesn't. The Swagger UI shows your data as it actually comes out of the API. The original poster was incorrect in thinking their JSON would have names like `Value1`. Without the serializer changes that @domaindrivendev suggests, it will actually come out of the API as `value1.` Swagger/Swashbuckle is just reflecting that reality.

**Comment by PeterAnaniaHC** [comment]
Sorry for the response delay, I was away.

I’m not certain we are speaking of the same thing here.

In our API Startup,cs file, we had the below.

                services.AddNewtonsoftJson(options =>
                {
                    options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                    options.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
                });

This changed the casing of the output from its native representation of Pascal case to Camel case.

I changed it to this

                services.AddControllers().AddJsonOptions(jsonOptions =>
                {
                    jsonOptions.JsonSerializerOptions.PropertyNamingPolicy = null;
                    jsonOptions.JsonSerializerOptions.IgnoreNullValues = true;
                });

Which stopped that, but it also caused other issues (specifically with the JSON ignore decorator in nested classes).

We eventually landed on this
                services.AddControllers().AddNewtonsoftJson(options =>
                {
                    options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                    options.SerializerSettings.Formatting = Formatting.None;
                    options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                    options.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
                });

Which stopped the auto-formatting of our output and properly handled the JSON ignore decorator in nested classes correctly.

But the point is, all of this work had to be done because Newtonsoft auto-formatted our output to Camel case instead of leaving it as is.

These Newtonsoft options were added because of our Swagger implementation using the .Net Core 3.0 library.

So I can see you taking the position that this is a Newtonsoft issue and not a Swagger issue, but the point is the default should be ‘no formatting’ and if we wanted formatting we should have to implement it.

Not the other way around.

Peter

**Comment by TLYoz** [comment]
I am also getting this issue. There does appear some confusion here. I am already using serializer settings 

```
 .AddNewtonsoftJson(opts =>
                {
                    opts.SerializerSettings.ContractResolver = new DefaultContractResolver();
                })
```

but the swagger schema is not Pascal cased.

```
"schemas": {
      "Address": {
        "type": "object",
        "properties": {
          "line1": {
            "type": "string",
            "nullable": true
          },
         ....
          "postCode": {
            "type": "string",
            "nullable": true
          },
          "countryCode": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
```

So swagger does not seem to be using the serialiser settings at all. Can you look at this again as it feels either there is a regression between 2018 and version 6.1.4 or we are at cross purposes

**Comment by TLYoz** [comment]
I think the missing things for me is to add nuget `Swashbuckle.AspNetCore.Newtonsoft`
and call `services.AddSwaggerGenNewtonsoftSupport(); ` from `ConfigureServices`
