### ISSUE TITLE
Set ;charset=utf-8 to response header for swagger.json

### ISSUE THREAD

**Issue by EvgeniyZ** [domaindrivendev/Swashbuckle.AspNetCore#384]
Swagger UI correctly view my commentaries for fields or properties in my native language, but in swagger.json I see some values like
Р’РµСЂРЅСѓС‚СЊ РІСЃРµ РІРѕР·РјРѕР¶РЅС‹Рµ С‚ in "summary" or "description" key values.
Xml documentation, generated by VS, has UTF-8 encoding, I assume that problem with generation swagger.json.

Need to add ;charset=utf-8 to Content-Type:application/json for better browser supporting.

Actually, need to fix in Swagger.SwaggerMiddleware.cs line 73
response.ContentType = "application/json;charset=utf-8";

**Comment by michielpost** [comment]
Yes, I also noticed these characters in the json format since version 1.0.0. Swagger UI displays then correctly. In RC3 this wasn't a problem.

**Comment by Adriien-M** [comment]
+1

**Comment by musicaddicted** [comment]
+1 
waiting for solving it
