### ISSUE TITLE
Q: Is there a way to make Swagger look at a specific Route prefix?

### ISSUE THREAD

**Issue by Allann** [domaindrivendev/Swashbuckle.AspNetCore#387]
I have combined the api and mvc parts in the same controller and this works well and makes it simpler to manage code.  I stumbled onto Swagger through a blog post and thought this would be another great way to document/test the api.  Hence, this question is posed by a complete novice with regard to swagger. 
When I run the web site and go to path http://localhost:8088/swagger/v1/swagger.json I get the following exception:

> NotSupportedException: Ambiguous HTTP method for action - Jbssa.MasterData.Web.Controllers.AnimalBreedsController.Put (Jbssa.MasterData.Web). Actions require an explicit HttpMethod binding for Swagger
> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable<ApiDescription> apiDescriptions, ISchemaRegistry schemaRegistry)

Whilst I understand why I get the exception, I don't know how to limit swagger to just the api/* route.

I have many HttpPost methods used by the Views when the forms submit back to the controller, but only one that is used by the api.  For example:
```
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AnimalBreedCreateViewModel viewModel)
        {
```

```
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, AnimalBreedEditViewModel viewModel)
        {
```
Api
```
        [HttpPost]
        [Route("api/[controller]")]
        public async Task<IActionResult> Post([FromBody]AnimalBreedModel model)
        {
```

Any help would be appreciated.

**Comment by Allann** [comment]
Any news on this?  We would love to use this product without having to split our WebAPI Controller from the MVC Controller.

**Comment by scorbin** [comment]
have the same problem

**Comment by domaindrivendev** [comment]
Take a look at the section in the readme that describes how to omit arbitrary operations by convention:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#omit-actions-by-convention

You should have enough info in the ActionModel metadata to filter out operations where the route is not prefixed by "api/"
