### ISSUE TITLE
When returning longs, the least significant 8 bits seem to be changed.

### ISSUE THREAD

**Issue by johnathan-walker** [domaindrivendev/Swashbuckle.AspNetCore#392]
When returning longs to the Swashbuckle UI, it seems that the long's aren't returned correct. When using Postman, the returned longs are correct. There doesn't seem to be the same issue when returning any other numeric type.

Example repo: https://github.com/johnathan-walker/SwaggerUILongBug

**Comment by bryjshed** [comment]
Any news or fix about this? We are also facing this issue.

**Comment by domaindrivendev** [comment]
This sounds like a swagger-ui issue - you'll have better luck posting to that repo

**Comment by johnathan-walker** [comment]
Thank you @domaindrivendev

For those that care: https://github.com/swagger-api/swagger-ui/issues/3141

**Comment by domaindrivendev** [comment]
Sounds like this is a JavaScript limitiation - so going to close as there really isn't much that can be done on the Swashbuckle side.
