### ISSUE TITLE
Collection of enum leads to enum renaming to "Anonymous"

### ISSUE THREAD

**Issue by nero777x** [domaindrivendev/Swashbuckle.AspNetCore#396]
Creating an array (or list, etc) of an enum property on a class model leads to the enum being renamed to "Anonymous."

    public enum SomeEnum { Thing1, Thing2 }

    public class SomeClass
    {
        public SomeEnum[] SomeEnums { get; set; }
    }

The above sample code translates to following within the spec leading to the creation of these "Anonymous" enums.

    "definitions":{
	  ...
	  "SomeClass":{  
		 "type":"object",
		 "properties":{  
			"someEnums":{  
			   "type":"array",
			   "items":{  
				  "enum":[  
					 "Thing1",
					 "Thing2"
				  ],
				  "type":"string"
			   }
			}
		 }
	  },
	  ...
    }

Additionally, every time you reuse the same enum as an array in any other location, an "Anonymous" enum type is created for each instance.  In my case I used 3 of these arrays and ended up with "Anonymous1" to 3.  The desired behavior when generating the spec would be to create the enum as a reference and then use that as the type for the array.

**Comment by gatimus** [comment]
The underlying issue seems to be related to issue [358](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/358)

**Comment by domaindrivendev** [comment]
Closing as #358 captures the underlying issue
