### ISSUE TITLE
AddSwaggerGen: when defining SwaggerDoc it need version number to be in lower case

### ISSUE THREAD

**Issue by aKabirKhan** [domaindrivendev/Swashbuckle.AspNetCore#397]
Hi all, 

I was setting up swagger for .net core 1.1 Api sln VS 2017 Enterpirse, during this I was having issue with setting up with swagger which throw me off the loop for half a day, The error I kept seeing was that the swagger document was unknown, here is the exact error "UnknownSwaggerDocument: Unknown Swagger document - v1"
I finally figured out what the issue was, when I was setting up the AddSweggerGen and customizing the swaggerDoc inside, I was using "V1" as oppose to "v1", see below 

This does not work
`services.AddSwaggerGen(customize => 
{
          
          // Does not work
          customize.SwaggerDoc($"{SwaggerApiDocInformation.Version}", new Info { Title = "My API", Version = "V1" 

          // Works
          customize.SwaggerDoc($"{SwaggerApiDocInformation.Version.toLower()}", new Info { Title = "My API", Version = "V1" 
});
});`
Not sure this is by design, if so it is a bad one, and if it is not please fix it.

**Comment by domaindrivendev** [comment]
As described in the docs, the "version" is used to "uniquely" identify a given Swagger document.

And, as a unique identifier, I believe it should absolutely be case-sensitive. Furthermore, as per [RFC 7230](http://tools.ietf.org/html/rfc7230#section-2.7.3), the specification for HTTP URLs "requires" the path to be case sensitive. So, this behavior is not only representing my own opinion around what constitutes a "unique identifier" but it is also just using the web correctly.

If it really bothers you though, I would recommend using the Rewrite middleware for ASP.NET Core to easily workaround:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting

**Comment by aKabirKhan** [comment]
Hi @domaindrivendev 

Thanks for the response, and explanation. It does not make sense to me still because the domains are case insensitive where else the following URL segments are according to [6.2.2.1](https://tools.ietf.org/html/rfc3986#section-6.2.2.1)
. But I will accept it for what it is. And thanks for the recommendation of the work around.

**Comment by rajqaiser** [comment]
I am using .netcore 1.0. Initially i used swagger and face some issue then i found an alternative and i used Swashbuckle 3.0.0 and its working fine for me.
I used this link step by step.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio.
 If someone using .netcore 1.0 then use Swashbuckle 3.0.0.
