### ISSUE TITLE
Unable to resolve service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider'

### ISSUE THREAD

**Issue by waratah** [domaindrivendev/Swashbuckle.AspNetCore#398]
An error occurred while starting the application.
InvalidOperationException: Unable to resolve service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider' while attempting to activate 'Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware'.

Microsoft.Extensions.Internal.ActivatorUtilities+ConstructorMatcher.CreateInstance(IServiceProvider provider)

    InvalidOperationException: Unable to resolve service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider' while attempting to activate 'Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware'.
        Microsoft.Extensions.Internal.ActivatorUtilities+ConstructorMatcher.CreateInstance(IServiceProvider provider)
        Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
        Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next)
        Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
        Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

I am mixing in autofac resolution into the middle of this logic and I am probably having a conflict with this...

        // This method gets called by the runtime. Use this method to add services to the container.
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            // Enable cross site browsing.
            services.AddCors();

            // Add framework services.
            services.AddMvc();

            Register(services);

            // Register the Swagger generator, defining one or more Swagger documents
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "Scouts API", Version = "v1" });
            });

            return new AutofacServiceProvider(this.ApplicationContainer);
        }

**Comment by AlexBokhankovich** [comment]
I have the same issue. Is there any way to fix this?

**Comment by chen-qing** [comment]
Assume your Register(services) is actually doing the autofac container building, then this would be due to the fact that AddSwaggerGen is configured after container has been initialized, i.e. Register(services).

**Comment by waratah** [comment]
@chen-qing    This was exactly the issue.   Move register below creating the swagger interface and it works perfectly.
