### ISSUE TITLE
.Net Core can't see ApiContoller in XmlDocumentation

### ISSUE THREAD

**Issue by TonyCasey** [domaindrivendev/Swashbuckle.AspNetCore#400]
In a .net core api project, using the xml documents, Swagger does not see "ApiControllers", only basic "Controllers".

The controllers are listed in the xml doc, see below the "Packages" ApiController. 
It does not see it but does see the "Values" Controller.

If I change the ApiController to a Controller, it works, it sees it.

`<?xml version="1.0"?>
<doc>
    <assembly>
        <name>esw.Shipping.Api</name>
    </assembly>
    <members>
        <member name="T:esw.Shipping.Api.Controllers.PackagesController">
            <summary>
            Packages controller
            </summary>
        </member>
        <member name="M:esw.Shipping.Api.Controllers.PackagesController.Get">
            <summary>
            returns a collection of Packages
            </summary>
            <response code="200">collection of Packages</response>
        </member>
        <member name="M:esw.Shipping.Api.Controllers.PackagesController.Get(System.Int32)">
            <summary>
            returns a specific Packages with the specified id
            </summary>
            <param name="id">id of Packages to return</param>
            <returns>a single Packages</returns>
            <response code="200">Packages found - body contains data</response>
            <response code="404">Packages does not exist</response>
        </member>              
        <member name="M:esw.Shipping.Api.Controllers.ValuesController.Get">
            <summary>
            returns a collection of values
            </summary>
            <response code="200">collection of values</response>
        </member>
        <member name="M:esw.Shipping.Api.Controllers.ValuesController.Get(System.Int32)">
            <summary>
            returns a specific value with the specified id
            </summary>
            <param name="id">id of value to return</param>
            <returns>a single value</returns>
            <response code="200">record found - body contains data</response>
            <response code="404">record does not exist</response>
        </member>
        <member name="M:esw.Shipping.Api.Controllers.ValuesController.Post(esw.Shipping.Api.Models.Record)">
            <summary>
            adds a record type to the system
            </summary>
            <param name="value">new record to add</param>
            <response code="201">resource created</response>
            <response code="400">Request is not valid</response>
        </member>
        <member name="M:esw.Shipping.Api.Controllers.ValuesController.Put(System.Int32,esw.Shipping.Api.Models.Record)">
            <summary>
            modifies the existing resource
            </summary>
            <param name="id">id of resouce</param>
            <param name="value">Data to change</param>
            <returns></returns>
            <response code="204">resource modified</response>
            <response code="403">not allowed to modify the resource</response>
            <response code="404">resource does not exist</response>
        </member>
        <member name="M:esw.Shipping.Api.Controllers.ValuesController.Delete(System.Int32)">
            <summary>
            removes a record from the system
            </summary>
            <param name="id">id of resource to remove</param>
            <response code="204">resource removed</response>
            <response code="403">not allowed to remove the resource</response>
            <response code="404">resource does not exist</response>
        </member>
            <summary>
            Customers date of birth
            </summary>
        </member>
    </members>
</doc>
`

**Comment by PaddoSwam** [comment]
In .NET Core, assuming a ASP.NET Web API project here, you no longer have a specific `ApiController` class, it's unified in the `Controller` 😉 

You could go down into the code and maybe derive your own `ApiController` class from `ControllerBase` check it out here on [github.com/aspnet/Mvc](https://github.com/aspnet/Mvc/blob/9aff0a67c189fe25d48379f94f6180e577d55d5c/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs)

**Comment by TonyCasey** [comment]
Fab thanks
