### ISSUE TITLE
OrderActionsBy doesn't work correctly

### ISSUE THREAD

**Issue by janih78** [domaindrivendev/Swashbuckle.AspNetCore#401]
Cannot get OrderActionsBy working correctly. I need to order actions based on HTTP methods used so that GET methods come first (then POST, PUT, DELETE etc.). I have a few API controllers with some actions (using different HTTP methods). So I tried something very simple as shown below.

This is not working (order doesn't change at all):
```
config.OrderActionsBy(apiDesc =>
{
    return apiDesc.HttpMethod == "GET" ? "1" : "2";
});
```

This is working (but obviously it doesn't order actions as I want):
```
config.OrderActionsBy(apiDesc =>
{
    return apiDesc.HttpMethod;
});
```

Am I doing something wrong or misunderstood something or is this a bug in Swashbuckle?

**Comment by domaindrivendev** [comment]
Swagger, the community-driven spec that powers Swashbuckle, does not list operations in a flat list. It dictates that operations MUST be grouped by path. So, the ordering is only applied within those groups.

Perhaps, __TagActionsBy__ is what you need as the UI supports arbitrary grouping of operations based on a tag. The default is controller name but you could change to HTTP method.

**Comment by janih78** [comment]
I understand your point, but what I want is to **order actions within a group based on HTTP methods** (GETs first and so on). I don't want to group actions by HTTP methods. Now actions seem to be ordered by paths? Actually, I also tried TagActionsBy and it worked as you mentioned, but that's not what I want.

So, is it possible to order actions within a group based on HTTP methods?

Anyway, I really like Swashbuckle and have used it earlier with WebAPI 2 and now trying to adopt this Core version.

**Comment by domaindrivendev** [comment]
Hmmm - so in that case OrderActionsBy really should be working as you expect. There's tests around that so I'm reluctant to concede it's a big. Let me try reproduce and I'll get back to you

**Comment by aboo** [comment]
Any update on this? 

I've used the following code:

```csharp
c.OrderActionsBy(description => description.HttpMethod);
```

Expected:
```
DELETE /competitors/{id}
GET /competitors/{id}
GET /competitors
GET /competitors/search/{keyword}
POST /competitors
PUT /competitors
```

Actual:
``` 
DELETE /competitors/{id}
GET /competitors/{id}
GET /competitors
POST /competitors
PUT /competitors
GET /competitors/search/{keyword}`
```

**Comment by domaindrivendev** [comment]
@aboo - as per my comments above, the Swagger document structure dictates that operations are always grouped by path and therefore sorting can only be applied within the scope of each path. Therefore, the actual behavior you've described is correct. That is, operations for the "/competitors/{id}" path are displayed first, and sorted by HTTP method and are then followed by operations for the "/competitors" path, also sorted by HTTP method.

**Comment by efirdman** [comment]
I do not think its working

Trying to set in the following order within the same Controller

GET - POST - PUT - DELETE

                // Define order of the Actions on the page
                Func<ApiDescription, string> sortKeySelector = (x =>
                {
                    return
                        x.HttpMethod.Equals("GET", StringComparison.InvariantCultureIgnoreCase)
                        ? "0"
                            : x.HttpMethod.Equals("POST", StringComparison.InvariantCultureIgnoreCase)
                            ? "1"
                                : x.HttpMethod.Equals("PUT", StringComparison.InvariantCultureIgnoreCase)
                                ? "2"
                                    : x.HttpMethod.Equals("DELETE", StringComparison.InvariantCultureIgnoreCase)
                                    ? "3"
                                    : "4";
                });
                options.OrderActionsBy(sortKeySelector);

**Comment by HunteRoi** [comment]
Hey there! 

Sorry to bring this closed issue up again but I'm currently trying to get the exact result @janih78 was wanting : a way to **sort operations by their http methods within a group**.

Do you have any update or snippet which is making the job for this?

**Comment by ktownsend-cbre** [comment]
If there is some requirement that paths be sorted within a group and the OrderActionsBy sorting override can't change that, I wish that fact was more discoverable in the intellisense for the method in Visual Studio. It would have saved me many hours trying to figure out why sorting was broken. 

Frankly, a sorting override like this should truly override the sorting. Setting a sort override only to have it changed by internal sorting is confusing and unexpected.

**Comment by akhachaturyan** [comment]
Unfortunately, the sorting override doesn't work within the grouping items, which is really confusing and unexpected.
The way it works is withing the logical grouping (GroupName), it orders items by sub-groups (1st controller items order, then 2nd then 3rd, etc.)
The code below proves that.

`
     var actionsSortingOrder = new Dictionary<string, int>
        {
            { "GET", 0 },
            { "POST", 1 },
            { "PUT", 2 },
            { "DELETE", 3 },
        };
     var actionsDefaultOrder = _actionsSortingOrder.Max(m => m.Value) + 1; 
     var actionOrderCollector = new Dictionary<string, int>();

     options.OrderActionsBy((oa =>
                {
                    var method = oa.HttpMethod.ToUpperInvariant();
                    string res;

                    if (actionsSortingOrder.ContainsKey(method))
                    {
                        if (!actionOrderCollector.ContainsKey(method))
                        {
                            actionOrderCollector[method] = 0;
                        }

                        res = $"{actionsSortingOrder[method]}.{actionOrderCollector[method]++}";
                    }
                    else
                    {
                        res = actionsDefaultOrder.ToString();
                    }

                    return res;
                }));
`

**Comment by ShaunWhite2018** [comment]
Yeah... I've just spent half a day on this myself! Seeing if I could override sorting via OrderActionsBy...
Would be **really** nice in a future release to enable a **true** sorting override using this method!
No ifs... No buts!
Surely this wouldn't constitute a major code change!?

**Comment by ShaunWhite2018** [comment]
Well... If you want something done...?

I knocked up this Vanilla JavaScript hack which sorts Swagger end-points by HTTP method (GET, POST, PUT etc) and then by alphabetical order.

This works via the **InjectJavascript** extension for Swashbuckle.AspNetCore.SwaggerUI version 6.2.3 and I've tested it using a Core WebAPI project running under .NET6 (although it should also work for .NET5):

**swagger-custom.js:**
`
"use strict";

(function () {
    const SwaggerEndPointClass = ".opblock";
    const SwaggerEndPointsToggleClass = ".opblock-tag-section";

    const SwaggerEndPoints = "operation-tag-content";
    const SwaggerEndPointsClass = `.${SwaggerEndPoints}`;
    const SwaggerEndPointsContainer = `${SwaggerEndPointsClass} > span`;

    const SwaggerHttpMethods = Object.freeze([
        "head",
        "options",
        "get",
        "post",
        "put",
        "patch",
        "delete"
    ]);

    let swaggerEndPointsSorted = false;
    let swaggerEndPointsToggleClickHandlersAssigned = false;

    function GetSwaggerEndPointIDHttpMethodIndex(swaggerEndPointID) {
        for (let i = 0; i < SwaggerHttpMethods.length; i++)
            if (swaggerEndPointID.includes(`-${SwaggerHttpMethods[i]}_`))
                return i;
    }

    function SortSwaggerEndPointIDs(swaggerEndPointIDX, swaggerEndPointIDY) {

        let swaggerEndPointIDHttpMethodIndeX = GetSwaggerEndPointIDHttpMethodIndex(swaggerEndPointIDX);
        let swaggerEndPointIDHttpMethodIndeY = GetSwaggerEndPointIDHttpMethodIndex(swaggerEndPointIDY);

        if (swaggerEndPointIDHttpMethodIndeX < swaggerEndPointIDHttpMethodIndeY)
            return -1;

        if (swaggerEndPointIDHttpMethodIndeX > swaggerEndPointIDHttpMethodIndeY)
            return 1;

        return 0;
    }

    function GetSwaggerEndPointIDsByHttpMethods(swaggerEndPointsContainers) {
        let swaggerEndPointIDs = [];

        swaggerEndPointsContainers.forEach(x => swaggerEndPointIDs.push(x.querySelector(SwaggerEndPointClass).id));
        swaggerEndPointIDs.sort();
        swaggerEndPointIDs.sort(SortSwaggerEndPointIDs);

        return swaggerEndPointIDs;
    }

    function SwaggerEndPointsSort() {
        let swaggerEndPointsContainers = document.querySelectorAll(SwaggerEndPointsContainer);

        if (swaggerEndPointsContainers.length < 1)
            return;

        let swaggerEndPointsContainerNew = document.createElement("div");
        let swaggerEndPointsContainerOld = document.querySelector(SwaggerEndPointsClass);
        let swaggerEndPointIDsByHttpMethods = GetSwaggerEndPointIDsByHttpMethods(swaggerEndPointsContainers);

        swaggerEndPointIDsByHttpMethods.forEach(x => swaggerEndPointsContainerNew.appendChild(document.getElementById(x)));

        swaggerEndPointsContainerNew
            .classList
            .add(SwaggerEndPoints);

        swaggerEndPointsContainerOld
            .parentNode
            .replaceChild(swaggerEndPointsContainerNew, swaggerEndPointsContainerOld);

        swaggerEndPointsSorted = true;
    }

    window.addEventListener("DOMNodeInserted", () => {
        if (!swaggerEndPointsSorted)
            SwaggerEndPointsSort();

        let swaggerEndPointsToggles = document.querySelectorAll(SwaggerEndPointsToggleClass);

        if (!swaggerEndPointsToggleClickHandlersAssigned)
            if (swaggerEndPointsToggles.length > 0) {
                swaggerEndPointsToggles.forEach(x => x.addEventListener("click", _ => swaggerEndPointsSorted = false));
                swaggerEndPointsToggleClickHandlersAssigned = true;
            }
    });
})();
`

As I said it's a hack but should hopefully sort your needs until they decide to make the **OrderActionsBy** TRULY override the end-point order... Irrespective of arbitrary grouping!

Hope this helps!
