### ISSUE TITLE
Please support empty RoutePrefix in SwaggerUIOptions

### ISSUE THREAD

**Issue by Tanhe** [domaindrivendev/Swashbuckle.AspNetCore#404]
Currently the FileServerOptions RequestPath property is set to

`$"/{options.RoutePrefix}"`

The RequestPath must not end with a "/" but it can be blank. This allows the swagger documentation to be served from the route which is what we do internally for our individual microservices for simplicity.

Current workaround is to use the following in lieu of app.UseSwaggerUi():

```
var indexSettings = new IndexSettings();
indexSettings.JSConfig.SwaggerEndpoints.Add(new EndpointDescriptor()
{
     Url = "/swagger/v1/swagger.json",
     Description = "Some API Name"
});

var fileServerOptions = new FileServerOptions()
{
    FileProvider = new SwaggerUIFileProvider(indexSettings.ToTemplateParameters()),
    EnableDefaultFiles = true
};

fileServerOptions.StaticFileOptions.ContentTypeProvider = new FileExtensionContentTypeProvider();

app.UseFileServer(fileServerOptions);
```

**Comment by juho-hanhimaki** [comment]
+1 for this.
