### ISSUE TITLE
Swashbuckle no longer works with latest VS 2017  version 15.2 (26430.12)

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [domaindrivendev/Swashbuckle.AspNetCore#407]
I just updated my VS 2017 to the latest version, to fix some tooling issues, and now the Swagger UI fails to generate.  The code has not changed at all.

Using Swashbuckle.AspNetCore 1.0.0
and
Swashbuckle.Core 5.5.3

**Comment by tillig** [comment]
Have you tried deleting your `.vs` folder and any `bin` and `obj` folders from your code tree? Tooling updates sometimes fail to update cached items.

**Comment by ThinkAboutGitHub** [comment]
Yes I had deleted all bin and obj directories, as well as the .vs directory.  Did a full rebuild of the entire source and I am still presented with Swagger UI failed to generate.

I see 500 : http://localhost:5000/swagger/v1/swagger.json

And in the console it just says Unable to Load SwaggerUI.

The API itself is still working and can be queried, but the swashbuckler implementation no longer seems to work.

**Comment by tillig** [comment]
Any logs or exception messages in Debug output?

**Comment by ThinkAboutGitHub** [comment]
Yes i'll paste the errors below:

Exception was thrown at line 2, column 27536 in http://localhost:5000/swagger/lib/jquery-1.8.0.min.js
0x800a139e - JavaScript runtime error: SyntaxError
Exception was thrown at line 2, column 19502 in http://localhost:5000/swagger/lib/lodash.min.js
0x800a01b6 - JavaScript runtime error: Object doesn't support this property or method
Exception was thrown at line 2, column 27207 in http://localhost:5000/swagger/swagger-ui.min.js
0x800a1396 - JavaScript runtime error: Array.prototype.sort: argument is not a JavaScript object
Exception was thrown at line 2, column 27288 in http://localhost:5000/swagger/swagger-ui.min.js
0x800a1396 - JavaScript runtime error: Array.prototype.sort: argument is not a JavaScript object
Exception was thrown at line 12, column 2586 in http://localhost:5000/swagger/swagger-ui.min.js
0x800a01b6 - JavaScript runtime error: Object doesn't support this property or method
Exception was thrown at line 7, column 9089 in http://localhost:5000/swagger/swagger-ui.min.js
0x800a139e - JavaScript runtime error: Cannot find module 'buffer'
Exception was thrown at line 7, column 9089 in http://localhost:5000/swagger/swagger-ui.min.js
0x800a139e - JavaScript runtime error: Cannot find module 'esprima'
Exception was thrown at line 12, column 21049 in http://localhost:5000/swagger/swagger-ui.min.js
0x80004005 - JavaScript runtime error: unknown exception
Exception was thrown at line 12, column 16072 in http://localhost:5000/swagger/swagger-ui.min.js
0x80004005 - JavaScript runtime error: unknown exception
Exception was thrown at line 12, column 16072 in http://localhost:5000/swagger/swagger-ui.min.js
0x80004005 - JavaScript runtime error: unknown exception

**Comment by tillig** [comment]
This is all JS/swagger-ui stuff. If you got the JSON endpoint directly do you see any .NET errors? The thing we need to figure out is the cause of the 500. The .NET errors will tell us that.

If the JSON loads without error, there's something else going on.

**Comment by ThinkAboutGitHub** [comment]
Do you mean the swagger json endpoint?  
As in http://localhost:5000/swagger/v1/swagger.json

Because that is giving me a 500 error in the browser, I can't see any .net errors once I browse to it.

**Comment by ThinkAboutGitHub** [comment]
I have found my issue (namely me) so I will close this, so sorry for wasting your time.
