### ISSUE TITLE
Operation level schema example is not getting rendered in the UI

### ISSUE THREAD

**Issue by kvvnbabu** [domaindrivendev/Swashbuckle.AspNetCore#411]
Hi,

I have one Error class which will be returned in case of error. I need to define example to for at each operation. 
Initially I have used ISchemaFilter to achieve this. But for all actions it is giving same example.
Then I am using IOperationFilter and setting the example different for different action. When I see the JSON, it has different example for different action. But in UI it is not rendering that specific examples.
![image](https://user-images.githubusercontent.com/29245862/26865586-05b2480a-4b7b-11e7-9c47-0047cf89fc28.png)

**Comment by domaindrivendev** [comment]
To apply operation-level response examples, you'll need to create an Operation Filter that assigns examples conditionally for each operation. See below - also note the structure of the examples - as per the Swagger spec, you need to provide an example per mime type:

```csharp
// ExamplesOperationFilter.cs
public class ExamplesOperationFilter : IOperationFilter
{
    public void Apply(Operation operation, OperationFilterContext context)
    {
        var methodAndPath = $"{context.ApiDescription.HttpMethod} {context.ApiDescription.RelativePath}";

        switch (methodAndPath)
        {
            case "POST api/products":
                {
                    operation.Responses["400"].Examples = new Dictionary<string, object>
                    {
                        {
                            "application/json",
                            new
                            {
                                Error = "Invalid product",
                                ErrorDescription = "foobar"
                            }
                        }
                    };
                }
                break;
        }
    }
}

// Startup.cs
c.AddSwaggerGen(c =>
{
    ...

    c.OperationFilter<ExamplesOperationFilter>();
}
```
