### ISSUE TITLE
Swagger .NETCORE can't read json

### ISSUE THREAD

**Issue by leilasoriano** [domaindrivendev/Swashbuckle.AspNetCore#416]
I'm having a trouble with swagger in .netcore. I've tried everything and nothing. I saw another similar questions, but nothing works for me. Running my webapi app with swagger, always returns "Can't read swagger JSON from http://localhost:5000/api/swagger/v1/swagger.json".

My codes:

```
public void ConfigureServices(IServiceCollection services)
    {
        // Add framework services.
        services.AddApplicationInsightsTelemetry(Configuration);
        services.AddCors(options => options.AddPolicy("AllowAll", p => p.AllowAnyOrigin()
                                                                  .AllowAnyMethod()
                                                                   .AllowAnyHeader()));
        services.AddMvc();
        services.AddSwaggerGen();

        services.ConfigureSwaggerGen(options =>
        {
            var info = new Info
            {
                Version = "v1",
                Title = "Web API Multiprodutos",
                Description = "Web API Multiprodutos",
                Contact = new Contact { Name = "Marcos Monte", Url = "www.arrowbus.com.br" }
            };

            options.SingleApiVersion(info);

            string caminhoAplicacao = AppContext.BaseDirectory;
            string nomeAplicacao =
                PlatformServices.Default.Application.ApplicationName;
            string caminhoXmlDoc =
                Path.Combine(caminhoAplicacao, $"{nomeAplicacao}.xml");

            options.IncludeXmlComments(caminhoXmlDoc);
            options.IgnoreObsoleteProperties();
            options.IgnoreObsoleteActions();
            options.DescribeAllEnumsAsStrings();
        });

        services.AddTransient<IServicoSimulacao, ServicoSimulacao>();

        services.AddTransient<IAplicacaoLocalidade, AplicacaoEndereco>();
    }

  public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseApplicationInsightsRequestTelemetry();
            app.UseApplicationInsightsExceptionTelemetry();

            app.UseCors(builder =>
            {
                builder.AllowAnyOrigin();
                builder.AllowAnyMethod();
                builder.AllowAnyHeader();
            });

            app.UseCors("AllowAll");

            app.UseMvc();
            app.UseMvcWithDefaultRoute();

            app.UseSwagger((httpRequest, swaggerDoc) =>
            {
                swaggerDoc.Host = httpRequest.Host.Value;
            });

            app.UseSwaggerUi(swaggerUrl: Configuration["AppSettings:VirtualDirectory"] + "/swagger/v1/swagger.json", baseRoute: "swagger/ui");
        }

```

Project.json

```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Aplicacao.Multiprodutos": "1.0.0-*",
    "Dominio.MultiProdutos": "1.0.0-*",
    "Swashbuckle": "6.0.0-beta902",
    "Swashbuckle.AspNetCore": "1.0.0",
    "Swashbuckle.SwaggerGen": "6.0.0-beta902",
    "Swashbuckle.SwaggerUi": "6.0.0-beta902",
    "Infra.Repositorio.MultiProdutos": "1.0.0-*"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "xmlDoc": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

Please, help me.Thanks in advance.

**Comment by hydanjan** [comment]
what does VirtualDirectory return?
Configuration["AppSettings:VirtualDirectory"]

**Comment by leilasoriano** [comment]
Returns "/api"

**Comment by hydanjan** [comment]
If you want to customize the URL it has to be done in two middlewares like below.
Change the code accordingly and try accessing the json.
app.UseSwagger(c =>
            {
                c.RouteTemplate = "api/swagger/{documentName}/swagger.json";
            });
            app.UseSwaggerUI(c =>
            {
                
                c.SwaggerEndpoint("/api/swagger/v1/swagger.json", "Some API");
                c.RoutePrefix = "api/swagger";

            });

**Comment by leilasoriano** [comment]
I've changed and got "Additional information: Unable to resolve service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider' while attempting to activate 'Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware'."

**Comment by hydanjan** [comment]
Sorry i gave an answer related to the Swashbuckle.AspNetCore but looks like you are not using that. 
I think someone else would jump in to resolve it.

**Comment by leilasoriano** [comment]
I'm using  Swashbuckle.AspNetCore.

**Comment by leilasoriano** [comment]
I realized the error occurs in Program.cs

```
public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }
```

**Comment by kvvnbabu** [comment]
Try this
` app.UseSwagger(c =>
        {
            c.RouteTemplate = "api/swagger/{documentName}/swagger.json";
        });
        app.UseSwaggerUI(c =>
        {
            
            c.SwaggerEndpoint("v1/swagger.json", "Some API");
            c.RoutePrefix = "api/swagger";

        });`

**Comment by leilasoriano** [comment]
Throws the same exception:  Unable to resolve service for type 'Swashbuckle.AspNetCore.Swagger.ISwaggerProvider' while attempting to activate 'Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware'.

**Comment by tillig** [comment]
@leilasoriano Looking at your `project.json` it appears you have some odd packages.

For example, I see you've got the correct latest `Swashbuckle.AspNetCore` package (1.0.0) but you also have the original `Swashbuckle` package (not used in the ASP.NET Core scenario); and you also have the `6.0.0-beta*` packages for `Swashbuckle.SwaggerGen` and `Swashbuckle.SwaggerUi` (also not used in ASP.NET Core).

Have you tried removing all Swashbuckle package references _except for_ the `Swashbuckle.AspNetCore` package?

Note it also looks like you haven't actually moved to the final .NET Core build/app tooling, which could affect your ability to reach success. [.NET Core and the dotnet CLI moved away from project.json at release time](https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj).

**Comment by tillig** [comment]
[The README on this repo](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md) also has a relevant note:

---

| :mega: Attention early adopters - please note the package rename to Swashbuckle.AspNetCore |
| ------------- |
| If you've been using Swashbuckle for ASP.NET Core since it's inception, you may be referencing "Swashbuckle.6.0.0-beta\*" packages. These are no longer valid. The original intention had been to move the [Swashbuckle project](https://github.com/domaindrivendev/Swashbuckle) from ASP.NET WebApi onto the ASP.NET Core stack in a major version bump. However, now that Microsoft plans to support WebApi for at least 4 more years, I felt it was more appropriate to split into separate projects, allowing both to live on with their respective frameworks. Although, I personally will be devoting most of my time to this version. |

**Comment by pavankumargooty** [comment]
Did it got fixed for you. I am also facing similar issue

**Comment by domaindrivendev** [comment]
For anyone experiencing this issue, please ensure you have the latest version of Swashbuckle.AspNetCore - v2.5.0 at the time of writing. If you've pulled that down and still experience this issue, let me know and I'll re-open the ticket.
