### ISSUE TITLE
Is there support for XmlSerializer based XML with XmlAttribute etc. obeyed

### ISSUE THREAD

**Issue by pierslawson** [domaindrivendev/Swashbuckle.AspNetCore#417]
A general question... the XML examples seem to assume the serialised XML will be all element based, is that because it is assuming the DataContractSerializer will be used by the API? Is there a way to indicate that the XmlSerializer is being used and have attributes such as the XmlAttribute obeyed?

**Comment by pierslawson** [comment]
Looked at the code and can see this is not supported. I have created pull request https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/420 to suggest how the support could be added fairly simply.

**Comment by domaindrivendev** [comment]
Will track as part of #1050
