### ISSUE TITLE
Bare project crashing Azure App Service - API

### ISSUE THREAD

**Issue by stsomewheredesign** [domaindrivendev/Swashbuckle.AspNetCore#426]
I'm having an issue with publishing a bare-bones API app up to Azure using v1.0.0. The application will not start successfully, yet runs just fine when developing locally. This is basically the template provided by Visual Studio 2017, targeting Core 1.1, with nothing more than the demo controller/endpoint in place.

Of course, the error message coming back from Azure is less than helpful simply saying "An error occurred while starting the application."

Code posted below since I can't attach the .cs file directly.

Thanks,
Ric

`
using System.IO;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.PlatformAbstractions;
using Swashbuckle.AspNetCore.Swagger;

namespace myApi
{
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info
                {
                    Title = "myApi",
                    Version = "v1",
                    Contact = new Contact
                    {
                        Name = "My Company Name",
                        Email = "a@b.com",
                        Url = "companyUrl"
                    }
                });

                var basePath = PlatformServices.Default.Application.ApplicationBasePath;
                var xmlPath = Path.Combine(basePath, "myApi.xml");
                c.IncludeXmlComments(xmlPath);
            });

            // Add framework services.
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "my API V1");
            });

            app.UseMvc();
        }
    }
}

`

**Comment by stsomewheredesign** [comment]
I may have located the source for my problem - the XmlComments, well, more importantly - the path to the XmlComments.

I'm publishing through Visual Studio 2017 to an Azure App Service and even though I've moved the .xml file into the Controllers folder, it was not getting published properly. No idea why, and don't have the time to investigate past what I've done to get this working, but, adding the XmlComments to the wwwroot folder does result in the file being published properly.

`
                const  string xmlPath = "wwwroot/PromiseZoneApi2.xml";
                c.IncludeXmlComments(xmlPath);
`

Granted, there's nothing dynamic or flexible about this whatsoever, but it does work.

**Comment by bryanloeper** [comment]
Thanks for finding that - I tried the #21 solution proposed by @RehanSaeed but no dice even after updating the IApplicationEnvironment references.
