### ISSUE TITLE
Bearer Token

### ISSUE THREAD

**Issue by mjabian** [domaindrivendev/Swashbuckle.AspNetCore#428]
I have this configuration:

```
            services.ConfigureSwaggerGen(x =>
            {
                //x.DocumentFilter
                x.SingleApiVersion(new Info
                {
                    Version = "v1",
                    Title = "API",
                    Description = "API templates for app.",
                    TermsOfService = "None",
                    Contact = new Contact()
                    {
                        Email = "email@d.com",
                        Name = "vendor",
                        Url = "website",
                    },
                    License = new License()
                    {
                        Name = "dd",
                        Url = "https://ddd/support/license"
                    },
                });
                x.IncludeXmlComments(AppContext.BaseDirectory + @"/app.xml");
                x.IgnoreObsoleteProperties();
                x.IgnoreObsoleteActions();
                x.DescribeAllEnumsAsStrings();
                x.AddSecurityDefinition("Bearer", new ApiKeyScheme()
                {
                    Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                    Name = "Authorization",
                    In = "header",
                    Type = "apiKey"
                });
            });
```

There is no provision in UI for input of Bearer token?

![image](https://user-images.githubusercontent.com/5665607/27243652-80399f64-5315-11e7-9650-a87abe24e188.png)

**Comment by domaindrivendev** [comment]
As per the Swagger spec, a "security definition" is not enough, you also need to assign applicable operations to the defined scheme. All described in the Swashbuckle readme

**Comment by goforgold** [comment]
@mjabian were you able to achieve this? I need tom implement exactly this.

@domaindrivendev can you please suggest how to do this in ASP.NET Core? any link?

**Comment by goforgold** [comment]
@mjabian 

I tried your solution, fortunately it worked for me with a minor change (not in your code). I used below part of your code

```
x.AddSecurityDefinition("Bearer", new ApiKeyScheme()
{
    Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
    Name = "Authorization",
    In = "header",
    Type = "apiKey"
});
```

It creates an `Authorize` button in Swagger UI like below for me

![image](https://user-images.githubusercontent.com/1727061/27266732-eadb9536-54d5-11e7-80dc-4d6cc875e685.png)

When I click this button, it opens up a popup where I was able to put JWT value. **It didn't work.**

I observed the request using F12 tools and found that the required header was being added but suffix `bearer` was not added. So, I just put this manually in token value like `bearer <token-here>`. And, yo, **It worked!!**.

Thanks a lot to you.

**Comment by ross2411** [comment]
@goforgold @mjabian Thanks guys.  worked for me!

**Comment by Behnam-Emamian** [comment]
This feature is working just for version 1.X not 2.X, so I have downgrade to v1.2 and it is sending the token.

**Comment by ajbeaven** [comment]
I agree, this is not working in 2.X. I also had to downgrade.

**Comment by Behnam-Emamian** [comment]
I can see there is a new UI, so this feature has been broken.

**Comment by domaindrivendev** [comment]
@ajbeaven @Behnam-Emamian - to get this to work in 2.x, you need to accompany your scheme _definition_ with a corresponding _requirement_ to indicate that the scheme is applicable to all operations in your API:

```csharp
c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
{
    { "Bearer", new string[] { } }
});
```

__NOTE__: it turns out that the old UI worked without this despite being an incomplete set of security metadata as per the Swagger 2.0 spec. The new swagger-ui _correctly_ requires this

**Comment by erikcheatham** [comment]
YAS!  Thank You @domaindrivendev!!

**Comment by replaysMike** [comment]
Did anyone else figure out why swagger-ui doesn't include the Bearer prefix to the auth token? Or is it expected we provide it on input?

**Comment by gakees** [comment]
Hi @replaysMike, it is expected (to my understanding) that the user supplies the "Bearer " prefix along with the JWT Token when pasting it via the Swagger UI.

**Comment by jlnpinheiro** [comment]
```csharp
services.AddSwaggerGen(options =>
{
    options.AddSecurityDefinition("Bearer", new ApiKeyScheme
    {
        Name = "Authorization",
        In = "header"
    });

    options.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
    {
        { "Bearer", new string[] { } }
    });
});
```
This did not work for me in **version 2.5.0**. Has anyone else found a solution to this problem?

**Comment by jlnpinheiro** [comment]
Thanks for the help my friend, @keycad! Problem resolved!

**Comment by MichelZ** [comment]
Isn't there a way to always prepend bearer to user supplied tokens?

**Comment by keycad** [comment]
I tried and didn't find one... but I'll be pleased if you know how
