### ISSUE TITLE
MyGet feed does not have Daily builds after 1.0.0

### ISSUE THREAD

**Issue by cfeilen** [domaindrivendev/Swashbuckle.AspNetCore#431]
Not sure if it was intentional to have only the previews up till 1.0.0 on myget, or not.

**XY problem**: I'm looking for nightlies, or more recent builds on Nuget/Myget in order to utilize some of the awesome features that have come in in the last few weeks.

**Comment by dennismaxjung** [comment]
You can try to download them from https://ci.appveyor.com/project/domaindrivendev/ahoy/build/artifacts. To download the NuGet-Packages click "Artifacts". 
(The current one, does't build, so the last successfull I found was this one: https://ci.appveyor.com/project/domaindrivendev/ahoy/build/1.0.0-build188/artifacts )
