### ISSUE TITLE
Upload Multiply files

### ISSUE THREAD

**Issue by sergeu90** [domaindrivendev/Swashbuckle.AspNetCore#433]
Hellow All. I have a question.Can I upload multiple files IList<IFormFile>? I search workaround but I didn't find anything

**Comment by theCuriousOne** [comment]
Try this

https://gist.github.com/theCuriousOne/39b79e40e3e7194b7bdb66cc910ee1b4

(just made it, haven't tested everything)

**Comment by crashsol** [comment]
waiting for too

**Comment by domaindrivendev** [comment]
Going to close this in favor of duplicate report #1029
