### ISSUE TITLE
Configure Timeout for XmlHttpRequest to prevent 504 Gateway Timeout

### ISSUE THREAD

**Issue by goforgold** [domaindrivendev/Swashbuckle.AspNetCore#434]
Some of APIs requires longer time to run (can reach upto 3 minutes). In Swagger UI, it times out the request while server is still processing the request and completes it.

Is there a way to configure timeout for API calls before swagger shows 504 timeout issue?

**Comment by goforgold** [comment]
Is this project still being maintained?

**Comment by tillig** [comment]
It's absolutely being maintained but it's also done for free by volunteers. There's no SLA on responses and most of the work is peoples' free time. The best way to get help is to try helping yourself - submit a PR with the changes required for your request.

**Comment by domaindrivendev** [comment]
This is a UI concern. Swashbuckle leverages the swagger-ui but doesn't maintain it. So, if this is still causing issues for you, I recommend you submit an issue to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui).

Alternatively, you could consider breaking down your documentation into multiple Swagger documents that can be navigated via a drop down in the swagger-ui. See the following readme sections for more details:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#generate-multiple-swagger-documents

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#list-multiple-swagger-documents

**Comment by Cloudmersive** [comment]
This was never fixed by the way - can we please reopen it

**Comment by domaindrivendev** [comment]
Read the above comment
