### ISSUE TITLE
SnakeCase with OpenIdConnectRequest

### ISSUE THREAD

**Issue by tinchoz49** [domaindrivendev/Swashbuckle.AspNetCore#439]
Hi everyone!

I'm working with the `OpenIdConnectRequest` to generate a valid jwt token. 
```c#
[HttpPost("~/connect/token"), Produces("application/json")]
public async Task<IActionResult> Exchange(OpenIdConnectRequest request)
{
...
```
Something that I noticed was that OpenIdConnectRequest has SnakeCase properties but the Swagger generator is creating a documentation with the parameters using PascalCase.

I know that there is a `DescribeAllParametersInCamelCase` option to convert all the parameters to CamelCase maybe we can add an option for SnakeCase too.

What do you think? or maybe there is another solution..

Thanks!

**Comment by kt81** [comment]
+1
If we could change the resolver of property names, It's not useful only for OpenId but also general usage.

**Comment by domaindrivendev** [comment]
Swashbuckle bases it's descriptions on the configured `SerializerSettings` for your application. So, if your application is configured to serialize objects in camelCase, SB will describe them in camelCase. If your application is configured to serialize objects in snake_case, SB will describe them in snake_case and so on.

For example, you can configure snake_case at the application level as follows:

```csharp
// Startup.cs
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddMvc()
        .AddJsonOptions(options =>
        {
            options.SerializerSettings.ContractResolver = new DefaultContractResolver
            {
                NamingStrategy = new SnakeCaseNamingStrategy()
            };
        });

    ...
}
```

If you do this, then sure enough, Swashbuckle will follow suit when documenting your API.

**Comment by kt81** [comment]
@domaindrivendev 
Thank you for the information.

I finally realized why my API properties are always converted as camelCase.
I'm using alternative JSON Resolver ([UTF8Json](https://github.com/neuecc/Utf8Json)) and it does not affect Swashbucke's name resolving behavior.
So I solved this issue by changing the naming rules to camelCase...(´・ω・｀)

**Comment by tinchoz49** [comment]
Hi everyone! I'm not working anymore on .net but if @kt81 says that he could solved the issue, maybe we can close it.

Thanks for the help @domaindrivendev @kt81
