### ISSUE TITLE
Add support to set BaseURL

### ISSUE THREAD

**Issue by jluqueba** [domaindrivendev/Swashbuckle.AspNetCore#441]
Plase add support in EnableSwagger() to can be able to set BaseUrl in order to change URL use by Try It Out Button.

**Comment by kierenj** [comment]
Dupe of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/427 ?

**Comment by vebaspect** [comment]
+1

**Comment by JDL440** [comment]
I was able to make this work by seeting the basePath like this:
.UseSwagger(c =>
{
c.PreSerializeFilters.Add((swaggerDoc, httpReq) => swaggerDoc.BasePath = "/MyServiceApp/MyService");
})

**Comment by wswind** [comment]
> I was able to make this work by seeting the basePath like this:
> .UseSwagger(c =>
> {
> c.PreSerializeFilters.Add((swaggerDoc, httpReq) => swaggerDoc.BasePath = "/MyServiceApp/MyService");
> })

swaggerDoc.BasePath is not working with  swashbuckle.aspnetcore version 5.3.3. How to fix this now?
