### ISSUE TITLE
Out of memory issue when Swagger UI is generating

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [domaindrivendev/Swashbuckle.AspNetCore#442]
Hi there

We are currently using SwashBuckle.AspNetCore 1.0.0.

We have noticed that the UI is quite slow to load.  When we include one of our new controllers, then browser now throws an Out of Memory error.
I have attached a file.

The Model being retrieved by this controller, does have nested properties, however they don't go any deeper than about three levels.

Would this be possibly causing the out of memory issue? Since moving to the AspNetCore version the ui is significantly slower to load.

![error](https://user-images.githubusercontent.com/18153399/27891901-dc90af94-623f-11e7-8ac6-baf24067f39b.png)

**Comment by tillig** [comment]
You attached a screen shot but that doesn't help. Just like on StackOverflow, you really need to include a _minimal_ repro, a full stack trace, and info on what you've already done yourself to troubleshoot it. Folks want to help, but there's not enough to go on here.

**Comment by tillig** [comment]
Also, this looks like a client error, which is a different project. Swashbuckle generates the JSON but SwaggerUI generates the UI and owns the JavaScript.

**Comment by ThinkAboutGitHub** [comment]
My apologies, I will attempt to simplify my solution to create a repro and then report back here.
