### ISSUE TITLE
How to add custom decorations for complex objects members?

### ISSUE THREAD

**Issue by albator1932** [domaindrivendev/Swashbuckle.AspNetCore#446]
Hi there,

I have implemented an IOperationFilter that search for a custom decoration on the action parameters and it works great. However those parameters are usually complex objects and I would like to do the same kind of thing for their members.
I would like to know if there's a way to implement some kind of decoration that I could use to mark the members in my objects because obviously an IOperationFilter does not go on the objects, only actions.

**Comment by albator1932** [comment]
I thought adding [Required] would have been enough but apparently it simply does nothing so I'm wondering if it could be a bug (or a missing feature) in Swashbuckle.
It can be done with a IDocumentFilter like this:

```
         internal class AddComplexObjectRequiredParameter : IDocumentFilter
         {
             public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
             {
                 if (swaggerDoc.Definitions != null)
                 {
                     swaggerDoc.Definitions["ComplexObject"].Required = new List<string>()
                     {
                         "Property1",
                         "Property2"
                     };
                 }
             }
```

However this is not the best approach because in case you have a lot of objects (like I do) with a lot of properties, it gets very tedious to list them that's why a decoration would be much cleaner.

**Comment by domaindrivendev** [comment]
See #599
