### ISSUE TITLE
NodaTime MapType to string but showing up as expanded parameters

### ISSUE THREAD

**Issue by zocdoc-tuan-huynh** [domaindrivendev/Swashbuckle.AspNetCore#456]
I'm having issues with Swagger generating the wrong api doc when I use NodaTime objects.

For example, I mapped NodaTime LocalDate to a string like this
`c.MapType<LocalDate>(() => new Schema { Type = "string" });`

And I have this test endpoint:
```
[HttpGet("Test")]
public async Task<ActionResult> GetAvailabilityTest([FromQuery] LocalDate test)
{
    return Ok(test);
}
```
The endpoint has expanded parameters on SwaggerUI even though I was expecting just a string because of the mapping. (I've also confirmed that swagger.json has these extra parameters):
![screen shot 2017-08-01 at 2 35 44 pm](https://user-images.githubusercontent.com/13220344/28840988-c1bebd64-76c6-11e7-9cfd-67cfb9198c52.png)

The `curl` in the screenshot is obviously wrong and the response is wrong. Going to this in the browser`http://localhost:<random_port>/availability/v1/Test?test=2015-02-17` gives me the response I was expecting, which is just an echo of the date passed in.

To provide more information, in the `ConfigureServices` method of `Startup.cs`, I've set up Swagger like this:
```
using NodaTime;
using NodaTime.Serialization.JsonNet;

public IServiceProvider ConfigureServices(IServiceCollection services)
{
        // setup NodaTime's time zone provider
        var nodaZoneProvider = DateTimeZoneProviders.Tzdb;
        services.AddSingleton(nodaZoneProvider);

        // configure MVC
        services
            .AddMvc()
            //configures Json model binder to play with NodaTime
            .AddJsonOptions(
                jo =>
                {
                    jo.SerializerSettings.ConfigureForNodaTime(nodaZoneProvider);
                })
            .AddMvcOptions(
                opts =>
                {
                    //tells MVC how to parse NodaTime values from querystring & form values
                    opts.ModelBinderProviders.Insert(0, new NodaTimeModelBinderProvider());
                });
}
```

Any ideas what I'm doing wrong or if there's a bug? Thanks!

**Comment by Tanhe** [comment]
I'm having the same problem. Looks like MapType works fine for LocalDate if it's a property of a request object on a POST, or if it's in the return model. Only query parameters seem to have this problem. I haven't found a workaround yet.

**Comment by akrobet** [comment]
+1

**Comment by domaindrivendev** [comment]
This is a dup of #309. The root cause is that `ApiExplorer`, ASP.NET Core's built-in metadata provider, expands non-body (i.e. not decorated with `FromBody`), complex parameters into individual API parameters, regardless of any model binders in play. 

The solution is to use a `TypeConverter` rather than a custom model binder. In fact, this is what's recommended in the [ASP.NET Core docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.1#model-binding-review), when you have simple string -> SomeType conversions:

> We recommended you create a type converter if you have a simple string -> SomeType mapping that doesn't require external resources

Luckily, `ApiExplorer` does honor these and as a result Swagger will describe the parameter correctly:

```csharp
// LocalDateTypeConverter.cs
public class LocalDateTypeConverter : TypeConverter
{
    public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
    {
        return (sourceType == typeof(string));
    }

    public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
    {
        return LocalDatePattern.Iso.Parse(value.ToString()).Value;
    }
}

// Startup.cs
public void ConfigureServices(IServiceCollection services)
{
    ...

    // Assign TypeConverter to LocalDate so it can be deserialized from a string
    TypeDescriptor.AddAttributes(typeof(LocalDate), new TypeConverterAttribute(typeof(LocalDateTypeConverter)));
}
```
