### ISSUE TITLE
Multiple parameter types

### ISSUE THREAD

**Issue by pksorensen** [domaindrivendev/Swashbuckle.AspNetCore#459]
I outlines what i was playing with at SO https://stackoverflow.com/questions/45506169/how-to-have-multiple-data-types-for-form-body-with-swagger-in-aspnet-core-mvc

I also attempted to create a converter and maybe manipulate the written json.

  ```
public class IParameterConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return typeof(IParameter).IsAssignableFrom(objectType);
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }

        public override bool CanRead => false;

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
           
        }
    }
```

and 

```
 .AddJsonOptions(options =>
            {
                options.SerializerSettings.Formatting = Formatting.Indented;
                options.SerializerSettings.Converters.Add(new IParameterConverter());
            }); ;
```

but its never called for any of the swagger objects. 

Is there any way to work around this? End goal is to be able to change between different content types for the request in the UI

**Comment by domaindrivendev** [comment]
As Swashbuckle.AspNetCore 5.0.0-beta now supports Swagger/OAI V3, it _is_ possible to describe an operation that accepts an object OR a file depending on the provided `Content-Type`.

While Swashbuckle doesn't support this out-of-the-box, there are a couple of workarounds to get the desired behavior. See #1040 for details around this exact use-case
