### ISSUE TITLE
Missing HttpStatusCode versions of attribute constructors

### ISSUE THREAD

**Issue by izzycoding** [domaindrivendev/Swashbuckle.AspNetCore#461]
This is more of an annoyance than a bug. But can we please get HttpStatusCode versions of Attributes?
It would save me having to manually cast them to int everywhere.

**Comment by VisualBean** [comment]
There.. created a pull request, lets see if it gets added :)

**Comment by xperiandri** [comment]
You just have to use another type for this
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/StatusCodes.cs

**Comment by thmhoag** [comment]
@xperiandri Makes sense, but is there any reason not to have an override allowing the `System.Net.HttpStatusCode` type in an overload? Seems like it might be nice to have either way.

@VisualBean Came across this and your PR (#465) after creating my own attribute for a similar overload. Not sure what happened with the CI build as it seems to have failed, but I'd also love to see this implemented to have the option of using the System.Net type (unless there is a compelling reason not to support it in addition to the `Microsoft.AspNetCore.Http.StatusCodes`)

**Comment by VisualBean** [comment]
Yeah I dunno why this PR failed - cant figure out which "check" failed

**Comment by domaindrivendev** [comment]
Microsoft.AspNetCore.Http.Abstractions/StatusCodes appears to be the "Core" way of dealing with status codes. So going to keep SB consistent with the Core and close issue
