### ISSUE TITLE
Datetime? not correct display

### ISSUE THREAD

**Issue by sergeu90** [domaindrivendev/Swashbuckle.AspNetCore#462]
Hi.I have a problem
I have action 
[HttpGet]
        public IActionResult Get(DateTime? datetime)
Swagger generated 
![image](https://user-images.githubusercontent.com/7217517/29211132-e73f6274-7e9f-11e7-9c4f-445849211836.png)
Can you help me ?

**Comment by VisualBean** [comment]
Datetime basically gets translated into strings.

BUT
you could go down the following road https://github.com/domaindrivendev/Swashbuckle/issues/741

**Comment by sergeu90** [comment]
@VisualBean  Thanks

**Comment by domaindrivendev** [comment]
Don't know when this was fixed but appears to be resolved in the current version (2.5.0 as of writing this).
