### ISSUE TITLE
Swagger.json not generated

### ISSUE THREAD

**Issue by mind0n** [domaindrivendev/Swashbuckle.AspNetCore#470]
Refer to the screenshot below, I have AspNetCore controllers located in a separated .net standard 2.0 project.  

The AspNetCore mvc and swagger is setup within the Startup project (also .net standard 2.0 with Swaggerbuckle.AspNetCore dependency)

When I launch the startup project, I can access the Index method from HomeController with url https://localhost/ or https://localhost/home/index

But when I try to visit: https://localhost/swagger/v1/swagger.json
I got 404 and I cannot find any swagger.json within my disk.

![image](https://user-images.githubusercontent.com/1991295/29548140-615f0b7a-86b3-11e7-961c-638f27eeb040.png)

Expected Result:
Swagger should be able to work correctly.

**Comment by tillig** [comment]
Swagger.json is all in memory. You'll never see a fire.

It appears you're missing `app.UseSwagger();` in Configure. You added the UI but not the Swagger.json part. See the README on the repo.

**Comment by mind0n** [comment]
Thanks for the response, it worked.
Actually it is the word **Optional** within the Readme.md that caused me removed the UseSwagger and left only the UseSwaggerUI.  My mistake.

> Optionally insert the swagger-ui middleware if you want to expose interactive documentation, specifying the Swagger JSON endpoint(s) to power it from.
