### ISSUE TITLE
Transfer simple type parameter in body.

### ISSUE THREAD

**Issue by PMExtra** [domaindrivendev/Swashbuckle.AspNetCore#476]
I have some API like this: `PUT /SomeThing/Running` to switch the running status of SomeThing.
I want to transfer a bool value in the body, but the SwaggerGen always generate the simple type (like bool) parameters to x-www-form-urlencoded body. In default, the AspNetCore does not allow this content type.
So what should I do for that? I want to specified the content type be application/json in there.

**Comment by domaindrivendev** [comment]
Can you please post your action signature for the operation?

**Comment by PMExtra** [comment]
My question is similar to #50 .
I'm finding a way to define the supported `Content-Type`.

**Comment by domaindrivendev** [comment]
`Consumes` and `Produces` attributes are now fully supported so you can use those to specify explicit media types for your operations.
