### ISSUE TITLE
GET method with complex type not displaying any description

### ISSUE THREAD

**Issue by josemaia** [domaindrivendev/Swashbuckle.AspNetCore#477]
I have a GET method that returns a list. It receives a Paging object as its only parameter, composed of the current page and the amount of results to return.

If I describe the paging object in the get method, that description is not exposed to swagger / swagger UI. Instead, the two parameters that compose it are shown. However, their description is not brought to the UI.

This issue seems similar to what is described in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/66, but that issue is closed. Am I missing something?

Method:

    /// <summary>
    /// Returns a list of all the agents in the modeler.
    /// </summary>
    /// <param name="paging">(Optional) Information on paging for the returned results.</param>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Get(Paging paging)
    {
        var agents = await _agentsService.Get(paging.Page, paging.PageSize);

        return Ok(agents);
    }

Relevant part of the paging class:

    public class Paging
    {
        /// <summary>
        /// Page number (starts at 1).
        /// </summary>
        [FromQuery(Name = "page")]
        public int Page { get; set; }

        /// <summary>
        /// Number of results per page.
        /// </summary>
        [FromQuery(Name = "pageSize")]
        public int PageSize { get; set; }
        (...)
    }

**Comment by fabich** [comment]
did you make any progress on this?

**Comment by josemaia** [comment]
Have not gotten back to working on documentation, but from what I can see, everything's the same in our most recent published build.

**Comment by fabich** [comment]
I just found my mistake today.
My class was in another project and the XML documentation generated by this project wasn't included in Swagger :)
After fixing that it works as expected.
Might be the same for you?

**Comment by josemaia** [comment]
That was exactly it! Thanks @fabich!
