### ISSUE TITLE
Unable to setting query parameters to be required

### ISSUE THREAD

**Issue by cpirie** [domaindrivendev/Swashbuckle.AspNetCore#480]
I'm trying to set query parameter on a HttpGet to be required but am unable to do so. Even integers will not be required by default when the swagger.json is created.

```
[HttpGet]
[Produces("application/json", Type = typeof(IEnumerable<string>))]
[SwaggerOperation(operationId: "ListStuff")]
[ProducesResponseType(typeof(string), (int)HttpStatusCode.BadRequest)]
public IActionResult ListStuff(int id, [Required]string auditId)
{
    ...
}
```

In the above scenario, both id and auditId will be flagged as not required:

```
"parameters": [{
	"name": "id",
	"in": "query",
	"required": false,
	"type": "integer"
},
{
	"name": "auditId",
	"in": "query",
	"required": false,
	"type": "string"
}]
```

Not sure if this is a bug (swear I read somewhere that required is the default), or if I'm doing something wrong?

**Comment by thabet084** [comment]
I faced the same issue I cannot set query parameters as required .
Any advice !

**Comment by edjacob25** [comment]
+1
I got something like
```CSharp
/// <summary>
/// Returns all items in the FV Inventory
/// </summary>
[HttpGet]
public IEnumerable<FvInventory> Get([FromQuery][Required] int projectId, [FromQuery]int? moduleId, [FromQuery] int? fvType, [FromQuery] int? statusId)
```
And I got something like 
```Json
"parameters": [{
                "name": "projectId",
                "in": "query",
                "required": false,
                "type": "integer",
                "format": "int32"
            }, {
                "name": "moduleId",
                "in": "query",
                "required": false,
                "type": "integer",
                "format": "int32"
            }, {
                "name": "fvType",
                "in": "query",
                "required": false,
                "type": "integer",
                "format": "int32"
            }, {
                "name": "statusId",
                "in": "query",
                "required": false,
                "type": "integer",
                "format": "int32"
            }]
```

**Comment by ThisNoName** [comment]
Same here.  [Required] on primitive parameter not show up.  [Required] on object parameter works fine.

**Comment by santo2** [comment]
what is the alternative?

**Comment by akrohn** [comment]
+1

**Comment by alexandra142** [comment]
Hi, first solution is to use parameter in Path, but becouse of convensions that filtration should be in query I have written OperationFilter. I said to myself, lets add to OperationID _{number}{number} to say there is required parameter and his order. For Example  method Get(int a, int b) and I want a parameter a to be required I will use annotation  [SwaggerOperation("ApiControllerGet_0")]. In OperationFilter, I find out all required parameters, and change OperationId back.
![obrazek](https://user-images.githubusercontent.com/17181592/35939107-7125b310-0c4b-11e8-9d55-6e2f002f537a.png)
![obrazek](https://user-images.githubusercontent.com/17181592/35939132-8675856a-0c4b-11e8-9f40-f573c9b0e3c9.png)
![obrazek](https://user-images.githubusercontent.com/17181592/35939177-a5a51bb2-0c4b-11e8-8a1f-50cd27df80ea.png)

**Comment by alexandra142** [comment]
Hi. I set up to add _{parameterOrderNumber}{parameterOrderNumber}... to OperationId , use this information in OperationFilter and set OperationId back. For Example for a method Get(string a, string b) and I want a parameter a to be required I will use an annotation [SwaggerOperation("ApiControllerGet_0")]. My code example is for query parameters.

![obrazek](https://user-images.githubusercontent.com/17181592/35941807-d3d68fd6-0c53-11e8-9493-7fdb3160433d.png)

![obrazek](https://user-images.githubusercontent.com/17181592/35941870-0f5a9606-0c54-11e8-8ef8-cb59c5f48cb8.png)
![obrazek](https://user-images.githubusercontent.com/17181592/35941878-18cb5ac2-0c54-11e8-8457-52d3b813dd72.png)

**Comment by domaindrivendev** [comment]
See #599
