### ISSUE TITLE
Respect ShouldSerialize*

### ISSUE THREAD

**Issue by CUCO-Ultimate** [domaindrivendev/Swashbuckle.AspNetCore#481]
I have serval classes that serialize depending on these ShouldSerialize* functions.

Since my classes all have a default which let all ShouldSerialize functions return false, the UI does not respect them. All classes will generate full JSON with not respecting ShouldSerialize functions

**Comment by domaindrivendev** [comment]
Swashbuckle generates API descriptions according to the static constructs within your code - attributes, type definitions etc. Your asking for it to go a step further and somehow execute runtime logic (i.e. the code within `ShouldSerialize`), and incorporate the result of that into the descriptions it generates.

This is a step to far for Swashbuckle as it introduces all kinds of complexities in implementation, not to mention the security implications of executing your runtime logic.

Furthermore, the purpose of `ShouldSerialize` is to serialize based on some conditional logic for any given instance of a model. So, how exactly should it encode the behavior for the general case - i.e. in your API docs?
