### ISSUE TITLE
Ignore property on model

### ISSUE THREAD

**Issue by lucgauthier** [domaindrivendev/Swashbuckle.AspNetCore#482]
Hello,

I want to ignore some properties. The code found here doesn't work in Swashbuckle.AspNetCore:
https://stackoverflow.com/a/41006116/1704198

Is it implemented in Swashbuckle.AspNetCore 1.0.0 ?

Thanks,
Luc

**Comment by domaindrivendev** [comment]
The fundamental goal of Swashbuckle is to describe "actual" API behavior as opposed to "intended" behavior.

So, with that in mind, does your API allow the properties in question to be accepted and deserialized into your model object? If so, why not describe them?

On the flip side, if they just happen to be part of the C# type you're using, but really shouldn't be part of the API contract then be explicit and make that the "actual" behavior via the JsonIgnore attribute. Then, you'll remove the security risk in letting unwanted data into your app and SB won't describe it either.

**Comment by lucgauthier** [comment]
Thank you for the thoughtful answer.
Unfortunatly, the model comes from another system. I can't add the json ignore attribute. The model property is systematically replaced with a specific value in the MVC controller - no security risk here.

In this scenario, it would be helpful to mask this api property.

Thanks,
Luc

**Comment by domaindrivendev** [comment]
If you're unable to change the access level and/or annotate the property, then I would recommend a Schema Filter:

```csharp
// IgnorePropertiesSchemaFilter.cs
public class IgnorePropertiesSchemaFilter : ISchemaFilter
{
    public void Apply(Schema schema, SchemaFilterContext context)
    {
        if (schema.Properties == null) return;

        schema.Properties = schema.Properties
            .Where(entry =>
            {
                return !(  *** put your specific exclusion criteria here *** );
            })
            .ToDictionary(entry => entry.Key, entry => entry.Value);
    }
}

// Startup.cs
c.AddSwaggerGen(c =>
{
    ...

    c.SchemaFilter<IgnorePropertiesSchemaFilter>();
}
```

**Comment by lonix1** [comment]
The idea is to ignore a specific property on a specific model. But this example runs for all models.

Is there a way to identity the model? Because during debugging I noticed that all of `schema` properties are null, except for `schema.Properties`. So how do we pick out a specific model?

**Comment by wizofaus** [comment]
FWIW, [Obsolete] works. And the property can still be serialized to/from,
