### ISSUE TITLE
Swagger UI not reflecting changes in YAML file

### ISSUE THREAD

**Issue by dipo7** [domaindrivendev/Swashbuckle.AspNetCore#485]
I just edited my YAML file using the online editor.

While my editing is already done, the UI on the right side does not reflect my changes.

This is happening on Chrome. 

I have cleared my cache in order to start afresh but my current screen keeps coming back and the UI still wont reflect those changes.

I tried with Firefox and it worked.

**Comment by domaindrivendev** [comment]
Wrong project
