### ISSUE TITLE
Complex [FromRoute] params not handled correctly

### ISSUE THREAD

**Issue by domaindrivendev** [domaindrivendev/Swashbuckle.AspNetCore#488]
__ASP.NET Core Version:__ 2.0
__Swashbuckle.AspNetCore Version:__ 1.0.0

Generated docs for the following action includes parameters for each property within the complex object when there should just be a single parameter named "searchParams", of type "string"

```csharp
[HttpGet("search/{searchParams}")]
public IEnumerable<Product> Search([FromRoute]SearchParams searchParams)
{
    ...
}
```

![screenshot](https://user-images.githubusercontent.com/1434343/30444855-2e32ee22-9939-11e7-94a2-35eac8f69776.png)

**Comment by rcvink** [comment]
I am also experiencing this issue in ASP.NET Core 2.1 and Swashbuckle.AspNetCore 2.5.0.

**Comment by jotatoledo** [comment]
Hey there,
any suggestions for workarounds for this issue?

**Comment by domaindrivendev** [comment]
This is a dup of #456. In that case the parameter binding is `[FromQuery]` instead of `[FromRoute]` but the root cause and workaround is the same. That is, a) use `MapType` to tell SB that the parameter should be described as a string and b) wire-up a `TypeConverter` to tell ASP.NET Core that the parameter should in fact be serialized from a string.
