### ISSUE TITLE
Failed with ASP.NET Core 2.0 app targeting full .NET 

### ISSUE THREAD

**Issue by VeselovAndrey** [domaindrivendev/Swashbuckle.AspNetCore#489]
Adding Swashbuckle.AspNetCore to ASP.NET Core 2.0 API App (default template).
But when I trying to open swagger UI I got

> MissingMethodException: Method not found: 'Void Microsoft.Net.Http.Headers.EntityTagHeaderValue..ctor(System.String)'.
> Microsoft.AspNetCore.StaticFiles.StaticFileContext.LookupFileInfo()
> Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
> Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddleware.Invoke(HttpContext context)
> Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware+<Invoke>d__6.MoveNext()
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

PS: With .NET Core app all works well.

**Comment by Chris-ZA** [comment]
Is this not the same as #438? 

If it is, the solution for me was to install the _Microsoft.AspNetCore.StaticFiles_ Nuget package suggested by Aetherix.

**Comment by VeselovAndrey** [comment]
Yes. Looks like that.

**Comment by VeselovAndrey** [comment]
Thanks @Chris-ZA

**Comment by TanielianVB** [comment]
```PowerShell
PM> Install-Package Microsoft.AspNetCore.StaticFiles
```
Solved the issue for me...

**Comment by domaindrivendev** [comment]
Hmmm ... this workaround is a poor dev experience. Ideas for addressing this are welcome

**Comment by collinbarrett** [comment]
I'm still struggling with [this issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/483#issuecomment-340315304), any other ideas? Thanks.

**Comment by MelbourneDeveloper** [comment]
Microsoft.AspNetCore.StaticFiles solved it for me.

**Comment by dmineau** [comment]
To those still struggling. If you still have this error after installing Microsoft.AspNetCore.StaticFiles, check the version of the git package for compatibility with the ASP.NET Core.
