### ISSUE TITLE
[Question] OpenId Connect

### ISSUE THREAD

**Issue by ashtonkj** [domaindrivendev/Swashbuckle.AspNetCore#490]
Hi,

The documentation mentions setting up OAuth2 support. Is there a way to set it up for OpenId Connect as well? (Including the discovery document, etc) as per the Swagger spec where it speaks of the openIdConnectUrl? (See: https://swagger.io/specification/#securitySchemeObject). And is there a way to get this working through Swagger UI so that the secured calls can also be tested?

Kevin

**Comment by ashtonkj** [comment]
More info: I have it working with the OAuth2 version, but it would be nice to be able to just specify the discovery document rather than the token and authorize endpoints.

**Comment by tdesmet** [comment]
The documentation you are linking to is for openapi 3, and this project only supports openapi 2.

See: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/419

**Comment by domaindrivendev** [comment]
Swashbuckle.AspNetCore 5.0.0 (now available as a beta package) supports Swagger/OAI and so it should be possible to define an OpenId Connect scheme and requirement via the `AddSecurityDefinition` and `AddSecurityRequirement` config methods.
