### ISSUE TITLE
Visual studio 2017 crashes when i try to load the source solution file.

### ISSUE THREAD

**Issue by smetronic** [domaindrivendev/Swashbuckle.AspNetCore#491]
Hi, I want to build this project from source but when i open the solution file in visual studio 2017 it crashes.
-Thanks

**Comment by domaindrivendev** [comment]
You'll have t do a little more digging/debugging yourself. Given that I'm actively developing the solution with Visual 2017 and don't have any problems, I would have absolutely no idea where to begin troubleshooting.

**Comment by smetronic** [comment]
Can you please share your source code with me so i can compare the solution with my current one and see why VS 2017 is crashing.

**Comment by domaindrivendev** [comment]
Ehhh - this repo is the source code

**Comment by smetronic** [comment]
I don't get it then why VS 2017 is crashing whenever i open up the solution or project files of this source code. Do i need to configure something.

**Comment by tillig** [comment]
http://blog.masterdevs.com/debugging-a-visual-studio-crash/

**Comment by tillig** [comment]
For reference, I've noticed a similar weird crash with other OSS projects I've worked on recently. Logs have told me it's something in the Visual Studio Project System causing the issue. I can't pinpoint what, but with VS 2017 releasing versions constantly it well could be something in the version of VS you're using.

**Comment by tillig** [comment]
After a lot of trial and error on a different OSS project where I saw this, I figured out it was the GhostDoc for VS 2017 add-in causing my trouble. After disabling it and restarting VS I was able to open that other project without issues. If you can use `/safemode` to start VS as outlined in that above article and things work, then it's one of your add-ins. Start disabling them and restarting VS until you figure out which one was causing the crash.

**Comment by smetronic** [comment]
Yeah, I just saw your message, i did checked the error log when my visual studio crashed and i found out there was some package that was causing the problem, so after that i disable Resharper but that didn't solve the issue then i thought maybe disabling GhostDoc will solve this but i didn't disable it because i thought it was for documenting the code but after seeing your message i disable it and my solution file opened with any problems.
