### ISSUE TITLE
asp.net team wants to add swagger generation to mvc

### ISSUE THREAD

**Issue by Ermesx** [domaindrivendev/Swashbuckle.AspNetCore#496]
This is great project used by thousands of people and a lot of good code created with experience.
I would be great if it will be contributed with collaboration with asp.net team. 

It could simplify many areas and allow to exchange knowledge and experience to build the better product.

issues: 
https://github.com/aspnet/Mvc/issues/6787
https://github.com/aspnet/Mvc/issues/6877

**Comment by rynowak** [comment]
Hi, MVC dev here.

We're looking at what gaps we can fill in the current experience by providing more or better information through the `ApiDescription` set of APIs. We have to plans to replace the existing 3rd party swagger libraries with our own.
