### ISSUE TITLE
No XML description for public data properties

### ISSUE THREAD

**Issue by PaulDotNet** [domaindrivendev/Swashbuckle.AspNetCore#499]
Swagger spec generated by swashbuckle contains descriptions of classes from dependent assembly but all properties have no descriptions. 

## VERSION: ##
1.0.0 for .Net Core. Project is .Net Core 2.0 console application referencing .Net Standard 2.0 DLLs.

## STEPS TO REPRODUCE: ##
Here is the code that adds swagger generator and specifies Data.XML file with XML documentation for the objects.
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info
                {
                    Version = "v1",
                    Title = "API"
                });
                c.IncludeXmlComments(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Data.xml"));
            });

## EXPECTED RESULT: ##
Swagger JSON file should contain descriptions of classes and their properties.
Swagger UI should contain descriptions of classes and their properties.

## ACTUAL RESULT: ##
Swagger JSON file contains descriptions for classes but no descriptions of any properties.
Swagger UI has no descriptions of classes and their properties.

**Comment by PaulDotNet** [comment]
I think I found the problem. Newtonsoft.JsonObjectContract takes into account both data fields and properties.  Swashbuckle only looks at properties and ignores all data fields. No data fields - no comments in swagger. 

Solution is quite simple but it requires modification of the library source code. PropertyInfo everywhere should be replaced with MemberInfo which is base class for both properties and data members.

**Comment by PaulDotNet** [comment]
Created pull request #500

**Comment by domaindrivendev** [comment]
Just merged #500. Preview package should be available on myget.org. Official release coming soon
