### ISSUE TITLE
Generate document tags from controller class comments

### ISSUE THREAD

**Issue by bragma** [domaindrivendev/Swashbuckle.AspNetCore#503]
Hi,
Thanks for this great project! I've seen from the docs that it's possible to generate a description for a tag using an IDocumentFilter implementation. Is it possible to do it directly from xml docs/attributes? My use case is the default one creating a tag for each controller. I'd like to add some descriptions in the UI for the tag, but I've not found any other way than listing them a document filter. I'd like to do that in the file containing the controller class instead. Any suggestion?
Thanks!

**Comment by RainingNight** [comment]
+1

**Comment by bed007** [comment]
+1
