### ISSUE TITLE
add headers to a response

### ISSUE THREAD

**Issue by will-beta** [domaindrivendev/Swashbuckle.AspNetCore#504]
I’m wondering if it’s possible to add customized headers to a response, for the support of pagination in RESTful APIs.

**Comment by SimonTouchtech** [comment]
The [`Response` class](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Swagger/Model/SwaggerDocument.cs#L345) has a [`Headers` property](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Swagger/Model/SwaggerDocument.cs#L351) but as far as I can see it's never set anywhere in the Swashbuckle code. You can set it yourself though, probably using an `OperationFilter` is the best approach.

**Comment by will-beta** [comment]
@SimonTouchtech Thanks! It works!

**Comment by freeranger** [comment]
@will-beta - care to share a code sample for the benefit of others?

Thanks

**Comment by will-beta** [comment]
@freeranger 

```c#
    /// <summary>
    /// custom attribute for API
    /// </summary>
    class ResponseHeaderAttribute : Attribute
    {
        public string HttpCode { get; set; }
        public string Name { get; set; }
        public Type Type { get; set; }
        public object Default { get; set; }
        public string Description { get; set; }
    }
```

```c#
        class ResponseHeaderOperationFilter : IOperationFilter
        {
            public void Apply(Operation operation, OperationFilterContext context)
            {
                context?.ApiDescription?.ActionAttributes()
                    ?.OfType<ResponseHeaderAttribute>()
                    ?.ToList()
                    ?.ForEach(a =>
                    {
                        var response = operation.Responses[a.HttpCode];
                        if (response != null)
                        {
                            response.Headers = response.Headers ?? new System.Collections.Generic.Dictionary<string, Header>();
                            response.Headers.Add(a.Name, new Header { Type = a.Type.Name, Default = a.Default, Description = a.Description });
                        }
                    });

            }
        }
```

**Comment by freeranger** [comment]
Thanks @will-beta

**Comment by minnocenti901** [comment]
Hello, I recently updated Swashbuckle.AspNetCore from version 8.1.4 to version 10.2.1. 

With this new version I cannot do  `response.Headers = response.Headers ?? new System.Collections.Generic.Dictionary<string, Header>();` anymore since the property Headers has no setter anymore and it is always null. How can I fix it?

Thanks.

**Comment by martincostello** [comment]
See the [migration guide linked to from the README](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/docs/migrating-to-v10.md).
