### ISSUE TITLE
Doesn't work with CSP

### ISSUE THREAD

**Issue by markblandford** [domaindrivendev/Swashbuckle.AspNetCore#505]
Unable to use this due to the inline script, when using a Content Security Policy without enabling unsafe-inline.

Can this be fixed please?

**Comment by domaindrivendev** [comment]
To reduce drift and ongoing maintenance, I want to avoid significant customization of the swagger-ui assets. I see there's an open issue for this in the swagger-ui library (https://github.com/swagger-api/swagger-ui/issues/3370) and as soon as they have an out-of-the-box solution, I'll be happy to incorporate that version into Swashbuckle.

In the meantime, Swashbuckle does allow you to inject your own version of the index.html (see readme for details) so you could implement the customization yourself without too much effort.

Moving to the backlog for now.

**Comment by evgenisokolov** [comment]
> To reduce drift and ongoing maintenance, I want to avoid significant customization of the swagger-ui assets. I see there's an open issue for this in the swagger-ui library ([swagger-api/swagger-ui#3370](https://github.com/swagger-api/swagger-ui/issues/3370)) and as soon as they have an out-of-the-box solution, I'll be happy to incorporate that version into Swashbuckle.
> 
> In the meantime, Swashbuckle does allow you to inject your own version of the index.html (see readme for details) so you could implement the customization yourself without too much effort.
> 
> Moving to the backlog for now.

Hi, @angularsen!
It seems that the bug you mentioned is resolved. Do you have any plans on updating a Swagger UI version?

**Comment by angularsen** [comment]
According to Microsoft's docs on OpenAPI, there are two community packages that offer Swagger UI:


> The two main OpenAPI implementations for .NET are [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) and [NSwag](https://github.com/RicoSuter/NSwag), see:
> 
> [Getting Started with Swashbuckle](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-8.0)
> [Getting Started with NSwag](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-8.0)


The other one seems actively maintained at least, but I haven't tried it:
https://github.com/RicoSuter/NSwag

**Comment by angularsen** [comment]
Okay, some more chatter here about the inactivity of this project:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2759

**Comment by martincostello** [comment]
This is something we're unlikely to tackle as per the original comment about the complexity it brings, as well as still depending on swagger-ui itself being CSP friendly.

If you have a need to use a strict Content Security Policy, I suggest you not use the SwaggerUI package at all and instead ship your own index.html file that you can customize to use CSP features such as specifying an `integrity` hash. Here's an example: [index.html](https://github.com/martincostello/adventofcode/blob/7deaa7bcd356702ddf1a5ce1cd8fa516b1f912c0/src/AdventOfCode.Site/wwwroot/swagger-ui/index.html).

I also maintain a GitHub Action that can update such files for you if you consume them from a CDN: [martincostello/update-static-assets](https://github.com/martincostello/update-static-assets)
