### ISSUE TITLE
Configuration via appsettings.json

### ISSUE THREAD

**Issue by MontyGvMC** [domaindrivendev/Swashbuckle.AspNetCore#506]
Well, it's not a issue, just a basic question.

My swashbuckle configuration keeps growing.

I moved everything to the appsettings.json.

But now in StartUp.cs I have a lot of code like:

`
  options.SwaggerDoc
  (
    Configuration["SwaggerConfig:DocSettings:Name"],
    new Swashbuckle.AspNetCore.Swagger.Info
    {
      Title = Configuration["SwaggerConfig:DocSettings:Info:Title"],
      Version = Configuration["SwaggerConfig:DocSettings:Info:Version"],
      Description = Configuration["SwaggerConfig:DocSettings:Info:Description"],
      TermsOfService = Configuration["SwaggerConfig:DocSettings:Info:TermsOfService"],

      Contact = new Swashbuckle.AspNetCore.Swagger.Contact()
      {
        Name = Configuration["SwaggerConfig:DocSettings:Info:Contact:Name"],
        Email = Configuration["SwaggerConfig:DocSettings:Info:Contact:Email"],
        Url = Configuration["SwaggerConfig:DocSettings:Info:Contact:Url"]
      }
    }
  );
`

Is there some more elegant / automatic way to configure swashbuckle via the appsettings.json?
The code above does not check if the values are in the settings file.

**Comment by ThisNoName** [comment]
You can create an AppSettings class with all the needed parameters, add a AppSetting section in appsetings.json, add this on ConfigServices

    services.AddSingleton(Configuration.GetSection("AppSettings").Get<AppSettings>());

Then you can use it anywhere in Startup, or use constructor injection to pass AppSettings to any controller or classes.

Although personally, I lean towards a global static config class (from database).  Not the most technically correct solution, but the saving in keystrokes well worth the trade off.

**Comment by RomanKernSW** [comment]
So there is no way to configure swashbuckle via Appsettings.json? I have moved all my serilog configs to the appsettings.json. It has a positiv value not checking in code on which staging it executed, because the appsettings.json has separate config for each statings and it save time to read all this

**Comment by nalla** [comment]
@domaindrivendev could you provide a simple example?

**Comment by Salengo-com** [comment]
In case somesome wants to use appsettings.json to inject Openinfo directly, simply use : 

`services.AddSwaggerGen(options => options.SwaggerDoc("v1", configuration.GetSection("Swagger").Get<OpenApiInfo>()));`

**Comment by DeepakkSHAW** [comment]
The only addition is to fetch the IConfiguration instance before AddSwaggerGet

        var provider = services.BuildServiceProvider();
        var configuration = provider.GetRequiredService<IConfiguration>();
