### ISSUE TITLE
SwaggerResponse : Add overloaded constructor to ease migration

### ISSUE THREAD

**Issue by FrMalan** [domaindrivendev/Swashbuckle.AspNetCore#508]
Is it possible to add an overloaded constructor to the SwaggerResponseAttribute? 
This will make it possible to migrate large code bases that used the previous versions without editing every single SwaggerResponse attribute.

`
public SwaggerResponseAttribute(HttpStatusCode statusCode, string description = null, Type type = null)
    : base(type == null ? typeof(void) : type, (int) statusCode)
{
    Description = description;
}
`

**Comment by davidsavagejr** [comment]
#781

**Comment by martincostello** [comment]
At this point I think the ship has sailed on this.
