### ISSUE TITLE
Unit testing/Intergration testing OperationFilter

### ISSUE THREAD

**Issue by napalm684** [domaindrivendev/Swashbuckle.AspNetCore#512]
I apologize if this is open anywhere but does anyone have an example they could point me towards on how one might unit test or integration test a custom operation filter?  I am looking to get coverage around a simple file import IOperationFilter.  I am having issues using the TestHost for AspNetCore as it's not even entering the configuration lambda in the ```AddSwaggerGen()``` extension method.

**Comment by domaindrivendev** [comment]
For a unit test example ... https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Annotations/SwaggerAttributesOperationFilterTests.cs

For an integration test example ...
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/Swashbuckle.AspNetCore.IntegrationTests/SwaggerGenIntegrationTests.cs
