### ISSUE TITLE
This one uses Swagger UI 2.. but I need Swagger UI 3!

### ISSUE THREAD

**Issue by ganeshmuthuvelu** [domaindrivendev/Swashbuckle.AspNetCore#515]
This one seems to be using Swagger 2.x. 

There's a bug/inconsistent behavior in Swagger UI 2.x  See link below.
https://github.com/swagger-api/swagger-ui/issues/3759#issuecomment-336556631

So, how do I make use of Swagger-UI 3.x ??

**Comment by Soarc** [comment]
You could use swagger ui directly. Just serve content of [swagger ui dist folder](https://github.com/swagger-api/swagger-ui/tree/master/dist) as static files and it will work. You might be required to edit index.html swagger ui initialization to point to your swagger document.

**Comment by webron** [comment]
@ganeshmuthuvelu following up here from the swagger-ui ticket, keep in mind that `supportedSubmitMethods` is not yet implemented in Swagger-UI 3.x.

**Comment by ganeshmuthuvelu** [comment]
Thanks..! I will use Swagger-UI 2.x for now.

**Comment by chinooo19** [comment]
@Soarc thank you so much for your post on Oct 16. You have resolved my problems about the upgrade of the version of Swagger
Regards

**Comment by domaindrivendev** [comment]
SwaggerUI3 is now available in beta - see #550 for details
