### ISSUE TITLE
Documenting custom attributes

### ISSUE THREAD

**Issue by lyptt** [domaindrivendev/Swashbuckle.AspNetCore#516]
We're using a custom binder / attribute combo on a method parameter for request verification. How would we go about translating this into generated documentation?

e.g.:

```csharp
[HttpPost]
public IActionResult DoSomething([OurAttribute] data) { ... }
```

The combination above sources data from a header, so ideally it would be nice to document this as something other than a query parameter. Is there any way to do this at present?

**Comment by niemyjski** [comment]
Yes, I also have this problem: https://github.com/exceptionless/Exceptionless/blob/feature/core/src/Exceptionless.Api/Controllers/EventController.cs#L698

`public async Task<IActionResult> GetSubmitEventAsync(string projectId = null, int version = 2, string type = null, [UserAgent] string userAgent = null, [QueryStringParameters] IDictionary<string, string[]> parameters = null) {`

I have a user agent and query string parameters attribute and I'd like to control what is outputted for these? Any ideas?

**Comment by domaindrivendev** [comment]
In the latest version (v2.5.0), you can use a Parameter Filter to control how parameters with a specific attribute are documented:

```csharp
// OurAttributeParameterFilter.cs
public class OurAttributeParameterFilter : IParameterFilter
{
    public void Apply(IParameter parameter, ParameterFilterContext context)
    {
        if (context.ControllerParameterDescriptor?.ParameterInfo == null) return;

        var hasAttribute = context.ControllerParameterDescriptor.ParameterInfo
            .GetCustomAttributes(true)
            .OfType<OurAttribute>()
            .Any();

        if (hasAttribute)
            parameter.In = "header";
    }
}

// Startup.cs
services.AddSwaggerGen(c =>
{
    ...

    c.ParameterFilter<OurAttributeParameterFilter>();
});
```
