### ISSUE TITLE
OrderActionsBy - ControllerName ? 

### ISSUE THREAD

**Issue by ganeshmuthuvelu** [domaindrivendev/Swashbuckle.AspNetCore#517]
`services.AddSwaggerGen(c =>
{
    ...
    c.OrderActionsBy((apiDesc) => $"{apiDesc.ControllerName()}_{apiDesc.HttpMethod}");
};`

ControllerName doesn't seem to be available ..?

**Comment by domaindrivendev** [comment]
Use the following instead:

```csharp
c.OrderActionsBy((apiDesc) => ${apiDesc.ActionDescriptor.RouteValues["controller"]}_{apiDesc.HttpMethod}");
```
