### ISSUE TITLE
Dynamic Route Name & Sorting

### ISSUE THREAD

**Issue by ganeshmuthuvelu** [domaindrivendev/Swashbuckle.AspNetCore#518]
I have a dynamic route name for the controller as shown below:
`[ApiExplorerSettings(GroupName = "LastController",IgnoreApi = false)]
    [Route("{HostName}/api/CustomerPortal")]
    public class MyController : Controller
    {`

Since the Route is dynamic, the UI lists the controller at the very beginning in the sorting. I therefore gave a GroupName as "LastController" as shown above.

When I did that, my controller totally disappeared from the documentation..??

**Comment by domaindrivendev** [comment]
As per the docs, GroupName is typically used to "group" operations into completely separate Swagger documents (different endpoints). You're looking to group within the same document. Swagger-ui uses tags for this which you can modify using _TagOperationsBy_. Also described in readme.

**Comment by ganeshmuthuvelu** [comment]
I do not see TagOperationsBy in the readme.. May be you meant to say something else?

**Comment by domaindrivendev** [comment]
My mistake its TagActionsBy

**Comment by domaindrivendev** [comment]
`TagActionsBy` _should_ help if I'm understanding the issue correctly. Let me know if that's not the case and I can re-open
