### ISSUE TITLE
How to customize the swagger-ui - javascript/css files and other custom settings

### ISSUE THREAD

**Issue by andyalm** [domaindrivendev/Swashbuckle.AspNetCore#52]
The previous WebAPI based Swashbuckle supported a method to add your own custom javascript and css files (as embedded resources) to the Swagger UI. How does one do that with the ASP.NET 5 version?

**Comment by domaindrivendev** [comment]
In this version, you customize the swagger-ui by providing a custom version of index.html. The easiest way to do this is by creating a copy at wwwroot/swagger/ui/index.html. If you need dynamic rendering, you can alternatively create a controller and view for the route - "swagger/ui/index.html". There's a sample under test/WebSites that you can use for reference.

**Comment by domaindrivendev** [comment]
You can place additional assets (CSS, JavaScript etc) in the wwwroot folder too and simply reference them in your customized index.html

**Comment by domaindrivendev** [comment]
I had originally intended scrapping the C# interface for customizing the embedded swagger-ui. The thinking being that a custom version of "index.html" (easily injected via wwwroot) would be the preferred approach anyway. However, it seems a lot of people like the additional layer of abstraction and feel the custom index.html approach is too brittle.

So, I'm considering adding this feature back in. But, it won't be for a couple of iterations - certainly not before beta3.

**Comment by andyalm** [comment]
Was this feature added back in? I would love to have a way to customize the UI without having to copy-paste the entire index.html contents.

**Comment by domaindrivendev** [comment]
I hope to add it back in the next milestone - beta10. PR's always welcome :)

@andyalm - are you writing your Angular back-ends in Rails? If so, you might want to check this out - https://github.com/domaindrivendev/swagger_rails.

**Comment by andyalm** [comment]
I've created a PR for this. Please see #166

**Comment by ThinkAboutGitHub** [comment]
Is there a way to do this yet?  I can get this working by putting an index.html and its css into my wwwroot directory of my api, but I was hoping there was a way to do this in code.

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"

**Comment by jcoutch** [comment]
It looks like the method was removed again.  I just finished adding it in my fork, and will submit a new issue and pull request (since I can't re-open this bug.)
