### ISSUE TITLE
Swagger seems NOT compatible with custom middleware at all.

### ISSUE THREAD

**Issue by davidsmithgf** [domaindrivendev/Swashbuckle.AspNetCore#520]
Swagger seems NOT compatible with custom middleware at all. see following code.

If write "app.Use(async (context, next)...);" before UseSwagger(), swagger page may return 500 and crashed.
If write "app.Use(async (context, next)...);" after UseSwagger(), the middleware do NOT working at all.

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.Use(async (context, next) =>
    {
        using (var buffer = new System.IO.MemoryStream())
        {
            var stream = context.Response.Body;
            context.Response.Body = buffer;
    
            await next.Invoke();
    
            buffer.Seek(0, System.IO.SeekOrigin.Begin);
            using (var reader = new System.IO.StreamReader(buffer))
            {
                string body = await reader.ReadToEndAsync();
                buffer.Seek(0, System.IO.SeekOrigin.Begin);
                await buffer.CopyToAsync(stream);
                context.Response.Body = stream;
                log4net.LogManager.GetLogger(Startup.Repository.Name, "Startup.Configure.[AnLog]Middleware").Info("ResponseBody:{" + body + "}");
            }
        }
    });
    //
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
    	c.RoutePrefix = "help";
    	c.SwaggerEndpoint("/swagger/v1/swagger.json", "Demo API ver 1.0");
    });
}

**Comment by domaindrivendev** [comment]
This _should_ be resolved with latest release (2.3.0). Please re-open the issue if you're still having issues with that version or later.
