### ISSUE TITLE
Add token to the end of every request

### ISSUE THREAD

**Issue by andrecarlucci** [domaindrivendev/Swashbuckle.AspNetCore#525]
Hi guys,

I'm using a security definition for my JWT secured services and it works great:
```cs
               options.AddSecurityDefinition("Bearer", new ApiKeyScheme {
                    Name = "Authorization",
                    In = "header",
                    Type = "apiKey"
                });
```

Now I have another service where I need a simple key=token appended to the end of every querystring. Is it possible to do it in a similar way?

Tks!

**Comment by domaindrivendev** [comment]
The following should do it:

```csharp
c.AddSecurityDefinition("token", new ApiKeyScheme
{
    Name = "token",
    In = "query"
});
```

__NOTE__: if you're using the latest version of SB, you will also need to explicitly indicate that this scheme should be applied to all operations as described [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements):

```csharp
c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
{
    { "token", new string[] { } }
});
```

**Comment by RainingNight** [comment]
@domaindrivendev I can't found `AddSecurityRequirement` method in v2.1.0.
