### ISSUE TITLE
How to use modified index.html instead of default on localhost/swagger/

### ISSUE THREAD

**Issue by Liuksas** [domaindrivendev/Swashbuckle.AspNetCore#527]
I managed to replace index.html and call it using url: localhost/swagger/index.html
But problem when calling  localhost/swagger/ - it uses default swagger index.html, not downloading my current one, how to force it to use current one ???

Index.html file stored by using UseStaticFiles and swaggerUIFilesPath="C:\\xyz"

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
                app.UseMvc();
                string swaggerUIFilesPath = Configuration.GetSwaggerUIFilesPath();
                if (!string.IsNullOrEmpty(swaggerUIFilesPath))
                {
                    app.UseStaticFiles(new StaticFileOptions
                    {
                        FileProvider = new PhysicalFileProvider(swaggerUIFilesPath),
                        RequestPath = new PathString("/swagger"),
                    });
                }
                app.UseSwagger();
                app.UseSwaggerUI(c =>
                {
                    c.SwaggerEndpoint("v1/swagger.json", "Api v1");
                });
         }

**Comment by domaindrivendev** [comment]
Hmmm - there’s an easier way that shouldn’t require any of the above. I thought it was documented but see it’s not :(

To inject a custom index file, create it at wwwroot/swagger/index.html in your project root. Then, it should be picked up at the standard route. See test/Websites/CustomIndexHtml in this repo for a concrete example

**Comment by Liuksas** [comment]
Working, thanks :)
