### ISSUE TITLE
I am not seeing RedirectHandler in this package

### ISSUE THREAD

**Issue by jaydeept** [domaindrivendev/Swashbuckle.AspNetCore#528]
The Swashbuckle.Core was containing the class called `RedirectHandler`.
I was using that class as below:

> private static void SetAliasesForDocumentationPage(HttpConfiguration config, params string[] aliasesForDoc)
        {
            foreach (var aliasForDoc in aliasesForDoc)
            {
                var redirect = new RedirectHandler(SwaggerDocsConfig.DefaultRootUrlResolver, "swagger/ui/index");
                config.Routes.MapHttpRoute($"docsShortcut{aliasForDoc}", aliasForDoc,
                    defaults: null, constraints: null, handler: redirect);
            }
        }

I am looking for redirect the route for .net core 2 web application.

**Comment by domaindrivendev** [comment]
There's a lot that's changed between the WebApi version and this version (i.e. specifically for ASP.NET Core). If you're trying to serve the UI at an alternate path, try the following: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#change-relative-path-to-the-ui
