### ISSUE TITLE
FR: Ignoring property only on Swagger, without using JsonIgnore

### ISSUE THREAD

**Issue by josemaia** [domaindrivendev/Swashbuckle.AspNetCore#532]
Hello.

I have the following scenario in my API:
- A data transfer object has a series of properties (i.e. Id, Code, Description...) that I want to return on HTTP GETs, and also want to send in HTTP POST/PUT/PATCH. However, there are also some properties that only make sense to return in GETs but shouldn't be part of any user interactions (CreationDate, UpdateDate...).
- I do not want to use JsonIgnore on these, as they must be returned in GETs.

Should this be possible with Swashbuckle, for example, with a custom filter?

[This url](https://stackoverflow.com/questions/41005730/how-to-configure-swashbuckle-to-ignore-property-on-model) has an example for non-core Swashbuckle. Is this still the recommended solution?

Thanks.

**Comment by VisualBean** [comment]
Yes custom schema would be the way to go, if you are keen on returning the exact same object

**Comment by VisualBean** [comment]
I would say that the return from a post should be the same as getting the newæy created object via Get

**Comment by domaindrivendev** [comment]
Have you tried restricting the C# access for the properties in question? For example, public get and internal set. Swashbuckle will honor these by setting the readOnly flag accordingly.

Please note though, I can’t recall what the UI does for properties that are marked readOnly. It might hide them which would be perfect but it may just provide a note. Try it out and let me know

**Comment by josemaia** [comment]
I ended up no longer requiring this, as per the consistency argument mentioned upthread. Thanks!
