### ISSUE TITLE
Unit tests should use generated XML documentation file

### ISSUE THREAD

**Issue by PaulDotNet** [domaindrivendev/Swashbuckle.AspNetCore#533]
Unit tests should use generated XML documentation file.
Current project uses some sort of manually created xml comment file. Some comments in the source code do not match ones in the file. For example one string in the source contains "parma1" and in xml file "param1".  There are some upper and lower case mismatches. 

As a part of pull request #500  I also added compiler option to generate XML file automatically and fixed strings so that all unit tests would pass. Much easier to add new test cases.

**Comment by domaindrivendev** [comment]
Already merged
