### ISSUE TITLE
How do you add Basic Authentication to your swagger documentation page?

### ISSUE THREAD

**Issue by milesdavis16** [domaindrivendev/Swashbuckle.AspNetCore#536]
version using: 1.1.0

With Swashbuckle, how do you add basic authentication to your swagger documentation page?
How do you update the ui to accept username and password? (like attached pic)

![swagger-basicauth](https://user-images.githubusercontent.com/9260164/32871978-2a646006-ca52-11e7-9782-45b6378bf7fc.png)

**Comment by wdspider** [comment]
I believe you follow the steps listed in the docs here: 
 https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcoreswaggergen but instead of using the OAuth2Scheme class, you would use the [BasicAuthScheme class](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Swagger/Model/BasicAuthScheme.cs)

**Comment by milesdavis16** [comment]
Thanks @wdspider!
For my particular needs I went with ApiKeyScheme:
            services.AddSwaggerGen(c =>
            {
                ...
                c.AddSecurityDefinition("Bearer", new ApiKeyScheme() { In = "header", Description = "Please insert JWT with Bearer into field", Name = "Authorization", Type = "apiKey" });
            });

![image](https://user-images.githubusercontent.com/9260164/36050723-a872efd4-0db5-11e8-8271-79d22ec5004f.png)

![image](https://user-images.githubusercontent.com/9260164/36050779-cf8a11a6-0db5-11e8-912b-6e5fabb32184.png)

**Comment by janmohammadi** [comment]
Hi
I have a little authorization tool for Swashbuckle and Bearer token.
[https://github.com/janmohammadi/swashbuckle-authorize](https://github.com/janmohammadi/swashbuckle-authorize)

![How it works](https://cdn.pbrd.co/images/Hg2NkLw.gif)

**Comment by alextof** [comment]
Thank you very much!

**Comment by priyankaj1910** [comment]
@janmohammadi @wdspider

**Comment by priyankaj1910** [comment]
> Hi
> I have a little authorization tool for Swashbuckle and Bearer token.
> https://github.com/janmohammadi/swashbuckle-authorize
> 
> ![How it works](https://camo.githubusercontent.com/5afcad565b8d4c24381a95f09630d1348abcf36eae9e72db118afa594dafb960/68747470733a2f2f63646e2e706272642e636f2f696d616765732f4867324e6b4c772e676966)

Not sure why this JS dint worked for me ..
