### ISSUE TITLE
DateTime and int are not required, but showed as required in UI

### ISSUE THREAD

**Issue by neman** [domaindrivendev/Swashbuckle.AspNetCore#537]
I'm using `Swashbuckle.AspNetCore (1.1.0)`

For the following class 
```c#
/// <summary>
/// Employee class
/// </summary>
public class Employee
{
    /// <summary>
    /// Employee constructor
    /// </summary>
    public Employee()
    {
        DateCreated = DateTime.UtcNow;
    }

    /// <summary>
    /// Employee id
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Employee first name
    /// </summary>
    public string PersonName { get; set; }

    /// <summary>
    /// Employee last name
    /// </summary>
    public string Surname { get; set; }

    /// <summary>
    /// Employee residence address
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// Date when employee object was created
    /// </summary>
    public DateTime DateCreated { get; private set; }
}
```
And related action
```c#
/// <summary>
/// Get details with employee query string
/// </summary>
/// <param name="employee">Employee</param>
/// <returns>Employee</returns>
/// <response code="200"></response>
[HttpGet(nameof(Details))]
public IActionResult Details(Employee employee)
{
    return Ok(employee);
}
```

I got following UI with two required fields, although I have not decorated those fields with `[Required]` attribute

![image](https://user-images.githubusercontent.com/350314/32988129-d278c144-ccfd-11e7-978f-2024e0e759eb.png)

Only when I set them to be nullable, they are not required. 
**Is this the correct behavior?**

**Comment by domaindrivendev** [comment]
Yes that's the correct behavior.

Request validation in ASP.NET Core (e.g. via ModelState.IsValid) is applied AFTER the request has been deserialized into a model object. At that point, Value types (such as decimal, int, float, DateTime) will always have a value regardless of one being explicitly provided in the request or not. So, you MUST leverage nullable vs non-nullable to perform meaningful validation of required vs optional fields.

In fact, if you read [the official tutorial on request validation in ASP.NET Core]( https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation), you'll see the following sentence a couple of paragraphs in:

_"Value types (such as decimal, int, float, DateTime) are inherently required and don't need the [Required] attribute"_
