### ISSUE TITLE
Getting Could not load file or assembly Microsoft.AspNetCore.StaticFiles, Version=1.0.4.0

### ISSUE THREAD

**Issue by itanev** [domaindrivendev/Swashbuckle.AspNetCore#539]
Hi,

I am trying to use Swashbuckle 1.1.0 with AspDotnetCore 2.0 but I am getting the below error.

'Could not load file or assembly 'Microsoft.AspNetCore.StaticFiles, Version=1.0.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.'

Why does it search for 1.0.4.0?

In the NuGet packages, I see that the SwaggerUI which depends on Microsoft.AspNetCore.StaticFiles uses version 2.0.0, but the error says it is looking for 1.0.4? 

Could someone shed some light on what am I missing?

**Comment by KrzysztofPajak** [comment]
Hi,
We have the same problem in our project. We use Microsoft.AspNetCore.StaticFiles in version 2.0
Best Regards
Krzysztof

**Comment by itanev** [comment]
Hi,

After a while, I am returning to Swagger.

I've realized (thanks to a decompiler) that the swagger packages are compiled with older versions of some assemblies including StaticFiles, so a binding redirect is required. 

In the new AspNetCore all binding redirects are being generated automatically, but because the project that uses swagger in our system is not referenced in the traditional way, but is loaded at runtime (along with its dependencies) the .NET does not know about its dependencies and no binding redirects are generated for them. 

Hope this will help someone. :)

**Comment by domaindrivendev** [comment]
@itanev - can I close this or do you still feel there's a change that can me made to SB here?

**Comment by itanev** [comment]
Close it. :)
