### ISSUE TITLE
[FromQuery] parameters have "required": true instead of "required": false in 1.1.0

### ISSUE THREAD

**Issue by jssignore1** [domaindrivendev/Swashbuckle.AspNetCore#540]
I've upgraded to 1.1.0 and I noticed that [FromQuery] parameters now are required whereas previously they were optional. This is a problem for me because many endpoints have [FromQuery] parameters with default values so I don't want to have to give them values in the UI.

Are [FromQuery] params supposed to be changed from "required": false to "required": true in the most recent release, and if so, how can I manually set them to "required": false?

Thanks!

**Comment by domaindrivendev** [comment]
Sorry about this. It’s a breaking change and therefore should have been a major version jump. I just missed this case.

The change was actually addressing other issues for folks that want the to be required, so now I’ve ended up in a wackamole situation. The whole required vs non-required scenario is confusing and needs better documentation and possibly more clarity through the code too.

In the meantime, you can make the parameters nullable to unset the required flag.

**Comment by ThisNoName** [comment]
Maybe adding an option for default nullable behavior?  Like c.DescribeAllEnumsAsStrings(); .  

I have similar issue on return model when int, bool, datetime become nullable in swagger.  I have to add my own filter so that autorest can generate client models that match the server's.

**Comment by twgraham** [comment]
@domaindrivendev I appreciate your predicament - can't please everyone. I suppose I'll throw my two cents here anyway. Many of my controller methods take query parameters for pagination. e.g.
```csharp
public virtual Task<IActionResult> DoSomething([FromRoute] string id, [FromQuery] int perPage = 10, [FromQuery] int page = 1)
{

}
```

Now if I make them nullable, that means that users could actually set those parameters to null in their request (correct me if I'm wrong). That would mean I have to set the `perPage` and `page` variables to their defaults in the body to be safe, which undermines the point of default values in the method. 

I suppose one solution would be I could write a filter or something similar to enforce correct values for pagination.

In the meantime, I'll probably just put up with swagger requiring values for these query parameters.

**Comment by whyleee** [comment]
We have the same issue with pagination query params. Non-nullable params being required is a good default, but if there are default values in the code like `GetItems(int page = 1)` - such params should be optional.

**Comment by whyleee** [comment]
Found an easy solution to fix default params based on [operation filter for old Swashbuckle](https://github.com/domaindrivendev/Swashbuckle/issues/69#issuecomment-336322537):
```
public class UpdateOptionalParamatersWithDefaultValues : IOperationFilter
{
    public void Apply(Operation operation, OperationFilterContext context)
    {
        if (operation.Parameters == null || !operation.Parameters.Any())
        {
            return;
        }

        var parameterValuePairs = context.ApiDescription.ActionDescriptor.Parameters
            .OfType<ControllerParameterDescriptor>()
            .Where(parameter => parameter.ParameterInfo.HasDefaultValue)
            .ToDictionary(parameter => parameter.Name, parameter => parameter.ParameterInfo.DefaultValue);

        foreach (var parameter in operation.Parameters)
        {
            if (parameterValuePairs.TryGetValue(parameter.Name, out var defaultValue))
            {
                parameter.Extensions.Add("default", defaultValue);
                parameter.Required = false;
            }
        }
    }
}
```

**Comment by twgraham** [comment]
@whyleee You're a legend, thanks for that. I figured something like this could be done with operation filters. I modified slightly because some of my parameters with default values are enums, of which I use a string value.

In your larger example, I replaced this:
```csharp
return parameterInfo.DefaultValue;
```
with this:
```csharp
return parameter.Type.IsEnum ? parameterInfo.DefaultValue.ToString().ToLower() : parameterInfo.DefaultValue;
```

**Comment by whyleee** [comment]
Thanks @twgraham 👍 I updated the full version with enums handling. It also takes MVC serializer settings into consideration whether to return numeric or string values, or string camel case values.

**Comment by domaindrivendev** [comment]
See #599
