### ISSUE TITLE
[Feature] Generate Swagger file at postbuild without running the app

### ISSUE THREAD

**Issue by poulad-rbc** [domaindrivendev/Swashbuckle.AspNetCore#541]
### Feature Request

It would be great to generate the Swagger file in CI without running the app. I am willing to build such a feature (either in this repo or create another tool). Using reflection, a small program could read all docs and generate the swagger file.

What are your comments about it?

**Comment by domaindrivendev** [comment]
@poulad-rbc - this is definitely a feature that's long overdue. I'm working on some significant refactors to   make the overall architecture more flexible and ultimately allow this feature to "plug-in" more seamlessly. So, you might want to hold off on your PR until then.

In the meantime you could certainly start spiking into what it would take to generate the Swagger outside of the running application from a command line tool. The tricky part will be getting the complete ApiExplorer infrastructure wired up as Swashbuckle is heavily dependent on it. Easiest thing might be an in memory/test server - you could look at the current IntegrationTests for some inspiration.

When you have a design in mind, it may be prudent to talk through it before you start knocking out the PR, just so we're on the same page. Thanks

**Comment by PaulDotNet** [comment]
I did a very small experiment to get swagger in test/WebSites/Basic project.  Here is the code in the main() function:

        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            // Trying to get swagger provider here
            var sw = (ISwaggerProvider) host.Services.GetService(typeof(ISwaggerProvider));
            // ... and document here. Which throws exception when it tries to add duplicate "x-purpose" in
            // the AssignOperationVendorExtensions.Apply()
            var doc = sw.GetSwagger("v1", null, "/");

            host.Run();
        }

As you can see from my comments this approach currently does not work. GetService() call breaks something and both sw.GetSwagger and host.Run() fails. If I remove GetSwagger() failure remains.  
Any ideas why is this happening?

**Comment by qmfrederik** [comment]
@PaulDotNet Your code actually works for me; and here's how I serialize the swagger documentation:

```csharp
// Serialize
var swaggerString = JsonConvert.SerializeObject(
    swaggerDoc,
    Formatting.Indented,
    new JsonSerializerSettings
    {
        NullValueHandling = NullValueHandling.Ignore,
        ContractResolver = new CamelCasePropertyNamesContractResolver()
    });

File.WriteAllText("swagger.json", swaggerString);
```

**Comment by qmfrederik** [comment]
Actually, the code fails on .NET Core SDK 2.1.3 and works with .NET Core SDK 2.1.4. So it looks you'd need .NET Core SDK 2.1.4 for this to work 😄 .

**Comment by rv-alove** [comment]
I came across this looking for a good way to generate Swagger docs during a build rather than only dynamically at runtime, and combining the ideas provided I ended up with this in my Main method. The code in the `if` should probably move to a separate method.

```
public static void Main(string[] args)
{
    if (args.Length > 0 && args[0] == "swagger")
    {
        Console.WriteLine(GenerateSwagger(args));
    }
    else
    {
        BuildWebHost(args).Run();
    }
}

private static string GenerateSwagger(string[] args)
{
    var host = BuildWebHost(args.Skip(2).ToArray()); // Skip the `swagger <doc-name>` arguments provided
    var sw = (ISwaggerProvider)host.Services.GetService(typeof(ISwaggerProvider));
    var doc = sw.GetSwagger(args[1], null, "/");
    return JsonConvert.SerializeObject(
        doc,
        Formatting.Indented,
        new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            ContractResolver = new SwaggerContractResolver(new JsonSerializerSettings())
        });
}
```

This lets me run the application normally using `dotnet run` or `dotnet <app-name>.dll` but run it as `dotnet run swagger v1` to generate the Swagger docs directly and output to the console. Now I can run that during a build process and redirect the doc wherever I want it to go.

**Comment by awarrenlove** [comment]
I came across this thread looking for a similar solution, specifically to write the doc statically during a build rather than only dynamically at runtime. I used the ideas here to update my Main method to this.

```
public static void Main(string[] args)
{
    if (args.Length > 0 && args[0] == "swagger")
    {
        Console.WriteLine(GenerateSwagger(args));
    }
    else
    {
        BuildWebHost(args).Run();
    }
}

private static string GenerateSwagger(string[] args)
{
    var host = BuildWebHost(args.Skip(2).ToArray()); // Skip the `swagger <doc-name>` arguments provided
    var sw = (ISwaggerProvider)host.Services.GetService(typeof(ISwaggerProvider));
    var doc = sw.GetSwagger(args[1], null, "/");
    return JsonConvert.SerializeObject(
        doc,
        Formatting.Indented,
        new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            ContractResolver = new SwaggerContractResolver(new JsonSerializerSettings())
        });
}
```

Now I can run `dotnet run` to execute the application normally or `dotnet run swagger v1` to generate the Swagger doc to standard out, letting me redirect that to wherever I want during the build.

**Comment by PaulDotNet** [comment]
```csharp
private static string GenerateSwagger(IWebHost host, string docName)
{
    var sw = (ISwaggerProvider)host.Services.GetService(typeof(ISwaggerProvider));
    var doc = sw.GetSwagger(docName, null, "/");
    return JsonConvert.SerializeObject(
        doc,
        Formatting.Indented,
        new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            ContractResolver = new SwaggerContractResolver(new JsonSerializerSettings())
        });
}

```
GenerateSwagger function after some cleanup. Just could not look at **args** parameter...

**Comment by domaindrivendev** [comment]
Preview of CLI tool is now available. See docs for more info - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#dotnet-swagger-cli-tool. Please try out and provide feedback here

**Comment by tillig** [comment]
It'd be nice if the tool dumped to Console.Out by default or allowed a `--` sort of output parameter to avoid writing the file. That would be friendlier to things like PowerShell pipelines where additional filtering or processing during a build might take place.

**Comment by adamskoye** [comment]
@domaindrivendev this is exactly what I want, thanks for your work on it - but could you please add a link to https://myget.org/feed/domaindrivendev/package/nuget/dotnet-swagger to make it easier to find?

**Comment by domaindrivendev** [comment]
Now available on Nuget - dotnet-swagger.1.2.0-beta1

**Comment by domaindrivendev** [comment]
@tillig - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/50067c00d982a7f51fb4dcf18bb1b470f403b24d#diff-40b7a31ddf6b8f31423fbff3dd0d5a8bR83

**Comment by ranouf** [comment]
> Error occurred while restoring NuGet packages: Value cannot be null.
> Parameter name: path
> NU1101: Unable to find package Swashbuckle.AspNetCore.Cli. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/601

**Comment by saxonww** [comment]
This is something I want to use, but right now I don't think it can work for me.

My use case is to generate a swagger document with some extensions required to deploy to/update an api gateway as part of a deployment pipeline. These extensions contain environment configuration details which I definitely do not want to expose to end users. I don't have to use swagger for this, but all of my other options are a lot more work.

I'm doing this today with Document and Operation filters. I toggle registration of the filters and provide the extra details via command line parameters; I could use appsettings/environment variables instead. My pipeline starts the application, downloads the swagger.json, then tears it down. Doing this with a cli tool would simplify my build and probably make it a little faster.

**Comment by domaindrivendev** [comment]
This tool still uses your `Startup.cs` file. So if you toggle values from within it via env variables or otherwise, they should still be picked. Can you elaborate, with examples, on why you don't think it will work for your use-case.

**Comment by domaindrivendev** [comment]
I assume PS has a way to pass environment variables to any command but you’ll have to Google the exact syntax. On Linux, you would do the following:

FOO=BAR dot net swagger

Re the exception, can you provide the stack trace?

**Comment by domaindrivendev** [comment]
Looks like you’re close - let me know how it goes?

**Comment by saxonww** [comment]
I updated my comment with the stack trace.

**Comment by saxonww** [comment]
What this boils down to is that CreateSwaggerProvider() is getting called twice, once during BuildWebHost() and again by GetRequiredService<T>() in the Cli tool. I'm not sure what the correct fix for this really is - I am not very experienced with these DI frameworks - but I will send a PR with a potential fix.

**Comment by x2764tech** [comment]
@domaindrivendev is this still the right place to report issues with the command line tools?

I have a space in my profile path ("C:\Users\David Kemp\") and I get the following error:

```
dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Users\David'"
```

I think this is from the [call to dotnet exec](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Cli/Program.cs#L41) not wrapping the file path in double-quotes.

I can verify this by running `dotnet exec` with the correct path to the cli assembly.

**Comment by twgraham** [comment]
Love your work @domaindrivendev, my plan is to use this tool in conjunction with [Atlassian's openapi-diff tool](https://bitbucket.org/atlassian/openapi-diff) as sort of sanity test. During CI builds, my frontend SPA can compare the current API with a pre-generated version it has - thus ensuring that there are no breaking changes that my frontend might not be handling.

As for feedback, the main issue I'm having right now is getting it to work with XML comments enabled. Regular Swashbuckle.AspNetCore running on the server with comments works fine.

Using 2.3.0-beta1, ASP NET Core 2.0, MacOSX
 
See below for stack-trace

```
File name: '/path/to/my/secret/project/SomeLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.xml'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass28_0.<IncludeXmlComments>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerProvider(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by twgraham** [comment]
Also, the command line tool doesn't exit after generating the JSON file.

**Comment by fiksen99** [comment]
We're using ASP.NET Core with .NET Framework runtime, is there a plan to make this tool compatible with projects targeting .NET Framework?

**Comment by x2764tech** [comment]
@fiksen99 if you look at the https://github.com/domaindrivendev/Swashbuckle project, it looks like Richard doesn't have the time to maintain both versions. 

I'm sure he'd appreciate a Pull Request for someone willing to port it though ;)

**Comment by fiksen99** [comment]
I'm actually using the Swashbuckle.AspNetCore project right now, which is
compatible with .Net Framework as it conforms to .Net standard. However
from what I can see currently there isn't an equivalent of the
DotNetCliReference tool in the net framework world.

I've tried to fork the current project, and add a net462 target framework
(with conditional compilation around the assembly loader), I have a
successful build, but alas it wasn't as easy as that and I'm unsure how to
actually run the net framework app correctly (if it's even possible!) to
output the swagger.

**Comment by fiksen99** [comment]
Looks like https://www.natemcmaster.com/blog/2017/11/11/build-tools-in-nuget/ may provide insight into how we can get it working as a .Net Framework build tool. Will see if I can figure anything out here

**Comment by fiksen99** [comment]
I received the following from a colleague, and got relatively close to getting this working myself, but couldn't quite complete it (yet?). Indicates that it is feasible to make this work for an ASP.NET Core web app targeting .Net Framework

> NuGet packages allow you to inject .targets files into the referencing projects.  See https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package
> 
> One option you have here is to wrap the Swashbuckle code in an MSBuild Task.  Then you can invoke that MSBuild task during your build.  You can even make it happen every time you build the project if you make your target say AfterTargets="Build".
> 
> I see that the main logic of the Swashbuckle code supports net451 (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj#L7) and the CLI tool is just a thin netcoreapp2.0 wrapper over this logic.  So it should be relatively easy to wrap this code in an MSBuild task that runs on .NET Framework.
>

**Comment by keycad** [comment]
I have a problem with the version field that the CLI tool generates.
I've set it all up on a AspNetCore WebApi project. Everything works fine, except that the swagger-ui generated json has the correct version number under info (1.8.14 and increasing), whereas the cli-tool generated json always has version number "2.1.0.0". I'd need to have the correct version number here, since I'm using it to generate clients and check if changes have been made to the Api

**Comment by marobet** [comment]
Hi @domaindrivendev , 

I'm using this tool to generate the swagger.json file, but in the Statup of my application I read settings from the launchSettings.json file using Environment.GetEnvironmentVariable("settingname"), and the values come back in null, so I'm getting exceptions when running the tool. 

I read your previous reply saying:

> This tool still uses your Startup.cs file. So if you toggle values from within it via env variables or otherwise, they should still be picked.

but cannot make it work with mine. Here is my code in my .csproj file. 

```
<PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
</PropertyGroup>
...
 <ItemGroup>
    <DotNetCliToolReference Include="Swashbuckle.AspNetCore.Cli" Version="2.1.0-beta1" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="dotnet swagger tofile --output wwwroot\api-docs\v1\swagger.json $(OutputPath)\$(AssemblyName).dll v1 " />
  </Target>
```
Any ideas?

Thank you

**Comment by YuriGuzun** [comment]
@marobet try putting '.\' before the output path and make sure path actually exists.
`    <Exec Command="dotnet swagger tofile --output .\wwwroot\api-docs\v1\swagger.json $(OutputPath)\$(AssemblyName).dll v1 " />
`

**Comment by eduherminio** [comment]
I've just found this issue after opening #794.
Any suggestions?

**Comment by saxonww** [comment]
I ended up putting code in my filters to check whether they had already
been applied, and return early if so.

I also submitted a PR (#629) for this, but my workaround was rejected. It
looks like someone else submitted a similar PR (#792) which was also
closed; both apparently addressed the symptom and not the cause.
@domaindrivendev said he knew the root cause and had a fix in mind, so
hopefully that will be committed soon.

**Comment by domaindrivendev** [comment]
@saxonww - please try 3.0.0?

**Comment by saxonww** [comment]
@domaindrivendev I don't have access to this project anymore, but @jrajax does and may be able to test this.

**Comment by ts46235** [comment]
I'm getting this error when I run the dotnet swagger command. Its looking for dotnet-swagger.xml file when it should be looking for my assembly's xml doc file, Novek.OrderProcess.xml. If I create a dotnet-swagger.xml file and add the contents from Novek.OrderProcess.xml it works without an error.

What is my problem?

```
PS C:\morov\OrderProces> dotnet swagger tofile --output swagger3.json C:\morov\OrderProces\bin\Debug\netcoreapp2.1\Novek.OrderProcess.dll v1

Unhandled Exception: Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ISwaggerProvider (DelegateActivator), Services
= [Swashbuckle.AspNetCore.Swagger.ISwaggerProvider], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> Could not find file 'C:\morov\OrderProces\bin\Debug\netcoreapp2.1\dotnet-swagger.xml'. (See inner exception for details.) ---> System.IO.FileNotFoundException: Could not find file 'C:\morov\OrderProces\bin\Debug\netcoreapp2.1\dotnet-swagger.xml'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass28_0.<IncludeXmlComments>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerProvider(IServiceProvider serviceProvider)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args)
```

**Comment by realfink** [comment]
I'm getting the same issue as @ts46235. I've come up with a workaround. Not ideal, but it does plaster over the issue. I add this to the csproj file:

```xml
<Target Name="SwaggerToFile" AfterTargets="AfterBuild">
    <Exec Command="copy $(OutputPath)$(AssemblyName).xml $(OutputPath)dotnet-swagger.xml" />
    <Exec Command="dotnet swagger tofile --output swagger.json $(OutputPath)$(AssemblyName).dll v1" />
</Target>
```

**Comment by sorvis** [comment]
Hello,

I'm testing out the CLI tool for a script that generates swagger files for an unknown number of swagger documents (named: v1, v2, v3, etc). Once it hits the end of the swagger documents and doesn't find the next one I'd like to see the command exit giving an error. It does exit giving an error:

```
Unhandled Exception: Swashbuckle.AspNetCore.Swagger.UnknownSwaggerDocument: Unknown Swagger document - v3
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args)
```

The issue is though it also throws this message:
![image](https://user-images.githubusercontent.com/1037467/48653487-9f9c6c00-e9d3-11e8-9eb6-098aa10e9a09.png)

I noticed the message is only thrown when I run it as _dotnet swagger_ versus running it as _dotnet /c/Users/sorvis/.nuget/packages/swashbuckle.aspnetcore.cli/4.0.1/lib/netcoreapp2.0/dotnet-swagger.dll_ which does not throw the windows error dialog. I think it just boils down to catching the exception in the application then exiting with the proper exit code so that it no longer is an un-handled exception?

**Comment by sorvis** [comment]
Another issue I'm seeing is when I enter an UnknownSwaggerDocument I have no idea to know what the available options really are. So I made a quick [PR ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/941)to add that to the error messages.

**Comment by bdyer64** [comment]
I am having a problem getting XML comments into the swagger generated by the CLI command. When I load the swagger via the HTTP endpoint it all works great but when I generate the swagger via the command line no annotations from the XML comments. I see a comment above that my Startup class gets called but I don't understand how that happens given how the builder is created but I am just learning .Net Core so my knowledge is limited. Any help would be appreciated.

**Comment by thomasvdb** [comment]
I'm having an issue when already reading a configuration section in the `ConfigureServices`.
Example:

```
var oAuthConfiguration = Configuration.GetSection("OAuthConfiguration").Get<OAuthConfiguration>();

services.AddAuthentication(options =>
{
     options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
     options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options =>
{
     options.Authority = oAuthConfiguration.Authority;
     options.Audience = oAuthConfiguration.Audience;
});
```

I get a `NullReferenceException` on `oAuthConfiguration`.
If I remove this section, the generation of the swagger.json succeeds.

Is this use-case supported or am I missing something?

**Comment by thomasvdb** [comment]
This also seems to work: `ASPNETCORE_ENVIRONMENT=Development dotnet swagger tofile ...`

**Comment by winstonhenke-work** [comment]
With version 4.0.1 of the tool I was not able to make the --basepath option work. It generated with the value of ApplicationPath from the appsettings.json file instead.

**Comment by KasperHoldum** [comment]
After upgrading from 5.0.0-beta to 5.0.0-RC2 we started getting the following error in jenkins:
 
>  Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> 
>      at System.Console.get_Out()
> 
>      at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args)
> 
>    error MSB3073: The command "dotnet swagger tofile --serializeasv2 --output "C:\jenkins\workspace\ices_abe\src\aaa\swagger.json" "C:\jenkins\workspace\ices_abe\src\aaa\bin\Release\netcoreapp2.2\aaa.dll" "v1"" exited with code 255.

If I revert back to the beta it starts working again.

**Comment by thomasvdb** [comment]
@KasperHoldum This issue is also logged here with some more details: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1103

**Comment by Indigo744** [comment]
Hello,

We are having issue when trying to generate swagger.json:

`> dotnet swagger tofile bin\Debug\net472\App.exe v1`
```
A JSON parsing exception occurred in [App\bin\Debug\net472\App.exe]: * Line 1, Column 2 Syntax error: Malformed token
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'App\bin\Debug\net472\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, specify the appropriate framework in App\bin\Debug\net472\App.json.
```

After some research, I think it's because our projet is targeting the .net Framework (`<TargetFramework>net472</TargetFramework>` in csproj) and not a core framework.

What are our options to be able to generate the swagger json file from command line? Is this possible?

Thanks a lot for your help.

**Comment by fiksen99** [comment]
@Indigo744 I can share our solution to this shortly

**Comment by Indigo744** [comment]
@fiksen99 We went with the route proposed by @PaulDotNet (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/541#issuecomment-359152090) and we simply call our generated Exe app with the relevant args to get the Swagger Json file.

However, I'm interested in hearing your solution.

**Comment by fiksen99** [comment]
Essentially exactly what we did. Separate codepath to output the swagger
when a specific arg was passed in to the exe. We also added an msbuild task
as we needed the swagger as part of our build output (to input to an arm
template), which I can share if interested?

**Comment by Indigo744** [comment]
Thanks a lot, but I think we are ok. It works, even though I would have preferred to use the CLI tool. Thanks anyway!

**Comment by woeterman94** [comment]
Does this work for .NET core 3.1? 

the CLI does not seem to be compatible

**Comment by chlsmith** [comment]
I'm finding the same.....errors every time with 3.1

**Comment by jkketts** [comment]
Ran into this issue this evening. Turns out I was only providing the assembly path and not the actual assembly name. To get the command to run, I just ran the following:
```
dotnet swagger tofile ./MyApp.dll v1
```

**Comment by Kavyeshs41** [comment]
I'm having an issue running CLI. The app reads some variables from either environment or the appsettings.json file. But it seems when running commands it doesn't read the appsettings.json file hence throwing a null reference error. **If I set those as env variables it works just fine**.

P.S. I've also tried setting ASPNETCORE_ENVIRONMENT=Development with having all settings stored in appsettings.Development.json file. but it also not working. 

Set of command I'm using.

```
dotnet restore src/myApp/myApp.csproj
dotnet publish src/myApp/myApp.csproj -o publish/ -c Release
dotnet new tool-manifest --force
dotnet tool install --local Swashbuckle.AspNetCore.Cli --version 6.1.4
dotnet swagger tofile --output swagger.json publish/myApp.dll v1
```

Thanks.

**Comment by woeterman94** [comment]
> Does this work for .NET core 3.1?
> 
> the CLI does not seem to be compatible

Okay I fixed it by using the correct versions of the packages.  (I wrote a detailed article [here ]). Should work with the Swashbuckle.AspNetCore.Cli package (https://medium.com/@woeterman_94/how-to-generate-a-swagger-json-file-on-build-in-net-core-fa74eec3df1)

**Comment by nikolay-dimitrov** [comment]
@Indigo744 or @fiksen99 can someone from you guys share the implemented solution - i have a task to generate swagger .json files from multiple projects all created on .net framework 4.8 and those jsons files to be merged in one swagger file used by .net core API which will behave as API Gateway

**Comment by fiksen99** [comment]
@nikolay-dimitrov unfortunately I don't have access to the source code any more(changed company). From what I recall, we basically introduced a separate argument which would output the swagger, then called that from an ms build task. Unfortunately I don't have much more info. Sounds like you'll need to do some post processing to get the swagger files merged also

**Comment by nikolay-dimitrov** [comment]
@fiksen99 tnx for you answer - im not sure how exactly to get the instance of the swagger, in the example that is mention by @Indigo744 the following code is modified somehow 

        private static string GenerateSwagger(IWebHost host, string docName)
        {
            var sw = (ISwaggerProvider)host.Services.GetService(typeof(ISwaggerProvider));
            var doc = sw.GetSwagger(docName, null, "/");
            return JsonConvert.SerializeObject(
                doc,
                Formatting.Indented,
                new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore,
                    ContractResolver = new SwaggerContractResolver(new JsonSerializerSettings())
                });
        }
but since im on .net framework 4.8 there is no IWebHost host (Swagger it self is been plugged as middleware in .NET Core) while in the normal framework when Swagger package is been installed then its magically called runtime - without any DI or something else. Any help is really appreciated

**Comment by Indigo744** [comment]
Hello,

Just to be sure I'm understanding correctly, you are using ASPNET Core on .Net Framework, right?

What we essentially do is:

```cs

public static class Program
{
    public static void Main(string[] args)
    {
        var webHost = CreateWebHostBuilder().Build();
        
        // If args, then it's for generating swagger and exit
        // otherwise run web server
        if (args.Length > 0)
        {
            Console.WriteLine(GenerateSwagger(webHost, args[0]));
            Environment.Exit(0);
        }
        
        webHost.Run();
    }
    
    private static IWebHostBuilder CreateWebHostBuilder()
    {
        IWebHostBuilder builder = WebHost
            .CreateDefaultBuilder()
            .UseConfiguration(...)
            .UseUrls(...)
            .UseStartup<Startup>()
            ....;
        
        return builder;
    }
    
    private static string GenerateSwagger(IWebHost host, string docName)
    {
        ISwaggerProvider sw = (ISwaggerProvider)host.Services.GetService(typeof(ISwaggerProvider));
        OpenApiDocument doc = sw.GetSwagger(docName);
        return doc.SerializeAsJson(OpenApiSpecVersion.OpenApi3_0);
    }
}
```

Hope it helps.

**Comment by nikolay-dimitrov** [comment]
@Indigo744 no its normal .net framework 4.8 web api

**Comment by Indigo744** [comment]
@nikolay-dimitrov you mean ASP.NET? I fear you're in the wrong repo then, as this is Swagger for ASP.NET Core... Maybe you should look into https://github.com/domaindrivendev/Swashbuckle.WebApi and open an issue there.

Anyway, we don't use ASP.Net so I can't help you further. Good luck!

**Comment by fiksen99** [comment]
@Indigo744 this looks very familiar and likely exactly what we did. However As @Indigo744 says - this issue (and this repo) is tracking Swashbuckle in ASP.NET Core (which you can use with .NET Framework). the ASP.NET Swashbuckle version is linked out, though I believe it is no longer maintained.

**Comment by Nothing-Works** [comment]
I am using `dotnet swagger tofile --output [output] [startupassembly] [swaggerdoc]` this command to generate swagger docs, and it works fine locally.

But when it's in the CI/CD, as far as I know, it needs to start the app, but the app will not start in CI/CD due to some dependencies problems. So the app will throw exceptions inside `Program.Main` when it's run on CI/CD.

my question is, what's the recommended solution there? is there a way to skip exceptions? or even do not start the app? or should I configure what dependency to load in `Main`?

  [1]: https://github.com/domaindrivendev/Swashbuckle.AspNetCore

**Comment by markwalsh-liverpool** [comment]
@awarrenlove Are you executing `dotnet run swagger` as part of a post-build script within the csproj; if so, how are you doing that?
