### ISSUE TITLE
Documentation is not generated for routes with generic parameters or return types.

### ISSUE THREAD

**Issue by gercobrandwijk** [domaindrivendev/Swashbuckle.AspNetCore#542]
On the Swashbuckle GitHub (so not the AspNetCore one) this issues was reported:
https://github.com/domaindrivendev/Swashbuckle/issues/749

I am having the same issue now with Swashbuckle.AspNetCore. Can this be fixed?

For reproducing this bug, you can simply follow the steps described at the issue at https://github.com/domaindrivendev/Swashbuckle/issues/749

**Comment by domaindrivendev** [comment]
See 12aee13da3e5f6d48033b3aa663655c9ba3ba788. Preview package available on myget.org and official Nuget (2.4.0) being published as we speak.
