### ISSUE TITLE
Adding Proxy-Authorization header in swagger - version 1.1.0

### ISSUE THREAD

**Issue by meanin** [domaindrivendev/Swashbuckle.AspNetCore#544]
I am using Swashbuckle.AspNetCore v. 1.1.0.  I want to add Proxy-Authorization header alongside with normal Authorization header. 

Currently I tried 2 ways to do that:
* implementing IOperationFilter for both authorization header and proxy-authorization header,
* adding security definition  for both authorization header and proxy-authorization header.

None of these ways work for me. I am wondering if there is something that I miss? When I am going first way, I am able to add authorization header alongside with any custom named header. For me it seems like any header with prefix `proxy-` is prohibited in this context.

Is it a bug? Am I doing something wrong? Please send me some more info. I cannot find anything on my own.

**Comment by meanin** [comment]
Created a demo which present this bug:
https://github.com/meanin/swashbuckle-proxy-authorization-header

**Comment by domaindrivendev** [comment]
Judging from your demo, it looks like you're using the original (WebApi) version of Swashbuckle. This repo is specifically for the ASP.NET Core implementation. So, you should post the issue to the following repo instead (although you should know it's getting very little love these days):

https://github.com/domaindrivendev/Swashbuckle

In case you decide to move your application to ASP.NET Core anytime soon, you can get your specific use-case working, in this version, with the following configuration in `Startup.cs`:

```csharp
services.AddSwaggerGen(c =>
{
    ...

    c.AddSecurityDefinition("basicAuth", new BasicAuthScheme());
    c.AddSecurityDefinition("proxyAuth", new ApiKeyScheme
    {
        In = "header",
        Name = "Proxy-Authorization"
    });

    c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
    {
        { "basicAuth", new string[]{ } },
        { "proxyAuth", new string[]{ } }
    });
});
```csharp
