### ISSUE TITLE
Actions require an explicit HttpMethod binding for Swagger

### ISSUE THREAD

**Issue by ShiWei-L** [domaindrivendev/Swashbuckle.AspNetCore#547]
I customize a ActionModelConvention Used to set the default HttpMethod, it works fine, but the swagger can not generate the document Because it can't get to the HttpMethod from ApiDescription

![](https://user-images.githubusercontent.com/16813853/33368847-c09bbfd4-d52d-11e7-8668-7648fa9e7f9a.png)

**Comment by 564064202** [comment]
please tell us how to do it ?

**Comment by liangshiw** [comment]
I rewrote the SwaggerGenerator to achieve my goal.
