### ISSUE TITLE
Anchor tags in UI not working

### ISSUE THREAD

**Issue by Sprot** [domaindrivendev/Swashbuckle.AspNetCore#548]
When using link http://myapi/virtDirectory/swagger/#!/method I expect UI to move to the method but currently it stays in top.

using Swashbuckle.AspNetCore 1.1.0 (same was with 1.0.0)

setup code:
```
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint(webServerSettings.Value.VirtualDir + "/swagger/v1/swagger.json", "My API");
            });
```

**Comment by domaindrivendev** [comment]
This issue might be obsolete with latest version, as it pulls in the new (3x) version of swagger-ui, which doesn't use URL fragments.

Either way, this is a swagger-ui specific issue and therefore should be posted to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui)
