### ISSUE TITLE
Generating query param instead of path param on nullable  params

### ISSUE THREAD

**Issue by zoinkydoink** [domaindrivendev/Swashbuckle.AspNetCore#549]
Thanks for contributing to Swashbuckle.AspNetCore! As per the [contributing guidelines](CONTRIBUTING.md), please adhere to the following rules of thumb before submitting your issue:

Using Swashbuckle.aspnetcore 1.1.0 (ASP.NET core 2.0.3)
I have the following code

`  [HttpGet]
        [ProducesResponseType(typeof(EventDto), 200)]
        [Route("events/{fromDate:datetime}/{toDate:datetime?}")]
        public IActionResult EventsByDateRange(DateTime fromDate, DateTime? toDate, List<int> categories)
`

When generated in the UI, it makes toDate a query parameter instead of path parameter, but the actually code when called is expecting a path parameter.
In the Request URL here is what is called by the swagger UI 

`http://localhost:53103/api/events/2017-05-05/{toDate}`

and here is a screenshot of how it looks https://imgur.com/pONd6TZ

I want the 2 date params to be path and the array to be query

**Comment by ThisNoName** [comment]
Path parameters are required by default, I think.  But honestly, two dates and a list of categories seems a better fit for query string parameters, or a model.

**Comment by domaindrivendev** [comment]
The [Swagger 2.0 spec](https://swagger.io/specification/#parameterObject) does not allow optional "path" parameters and therefore neither does SB.
