### ISSUE TITLE
Update to Swagger UI v3?

### ISSUE THREAD

**Issue by patnolan** [domaindrivendev/Swashbuckle.AspNetCore#550]
Hi,

Could you please confirm if and when Swashbuckle.AspNetCore will be updated to include Swagger UI Version 3.0?

**Comment by domaindrivendev** [comment]
This is now available as a preview on myget but as a separate package:

See `Swashbuckle.AspNetCore.SwaggerUI3` at `https://www.myget.org/feed/Packages/domaindrivendev`

If you pull that down as a dependency, you should be able to use as follows:

```csharp
c.UseSwaggerUI3(c =>
...
)
```

If a few of the folks on this thread can test and verify, I'll promote to Nuget

**Comment by gjsduarte** [comment]
Would love to test it but have no access to the myget feed

**Comment by bass3l** [comment]
Hello,

Did you change your packages at myget? because I can't find `Swashbuckle.AspNetCore.SwaggerUI3` anymore.

I did find `Swashbuckle.AspNetCore.SwaggerUI 3.1.0-preview-0583` at `myget.org` but adding the reference to `Nuget.Config` won't solve the problem. 
Thanks.
