### ISSUE TITLE
Primitive type is not marked as required

### ISSUE THREAD

**Issue by heapx** [domaindrivendev/Swashbuckle.AspNetCore#551]
With 

```csharp
[Route("setvolume")]
[HttpPost]
public void SetVolume([FromBody]SetVolumeRequest req)
{
}

public class SetVolumeRequest
{
    public int Volume { get; set; }
}
```

the following json definition is generated for the request model 

```json
"SetVolumeRequest":{"type":"object","properties":{"volume":{"format":"int32","type":"integer"}}}
```

It seems to me that, since value types are inherently required, "volume" should automatically be marked as required. It is easy enough to add a [Required] attribute, but thought I'd check whether this was intentional. :)

**Comment by domaindrivendev** [comment]
Hmmm what version of Swashbuckle are you using, thought this was fixed in latest

**Comment by heapx** [comment]
I'm on 1.1.0.

**Comment by ThisNoName** [comment]
I think for input model, you are [Required] to be explicit about validation annotations.  It doesn't work on query string parameters, but with a model and FromBody, everything seems fine.

Primitive type in return data is a different story.

**Comment by domaindrivendev** [comment]
See #599
