### ISSUE TITLE
Swashbuckle.AspNetCore Support to ASP.Net Web API Project

### ISSUE THREAD

**Issue by narendraaki** [domaindrivendev/Swashbuckle.AspNetCore#556]
Hi Team,

Does Swashbuckle.AspNetCore supports Web API project which was not developed using Asp.Net core ?
As Swashbuckle project is no longer maintained, Can some please suggest how should i proceed documenting my web api which was developed on .Netframework 4.5

Thanks
Narendra Aki

**Comment by domaindrivendev** [comment]
This repo is specifically for API's built on ASP.NET Core. The [original Swashbuckle project](https://github.com/domaindrivendev/Swashbuckle) is still the de facto Swagger implementation for Web API. It's still maintained, albeit at a much slower rate, as focus has now shifted to .NET Core.
