### ISSUE TITLE
config.MapType does not seem to work with open generics

### ISSUE THREAD

**Issue by senritsu** [domaindrivendev/Swashbuckle.AspNetCore#560]
When configuring a type override for swagger docs display, open generic types don't seem to work.

```
options.MapType(typeof(Id<>), () => new Schema {Type = "string", Description = "uuid"});
```

A parameter of type `Id<Foo>[]` is still displayed as a body of type `Array[Id[Foo] {}]` with an example value of
```
[
  {}
]
```

**Comment by domaindrivendev** [comment]
Not sure exactly when this was added but it's definitely available from `v5.6.0` onwards.
