### ISSUE TITLE
Missing controllers after applying ApiExplorerSettings attribute

### ISSUE THREAD

**Issue by tarurar** [domaindrivendev/Swashbuckle.AspNetCore#562]
Once `ApiExplorerSettings` attribute applied on controller or method level the appropriate controller methods or particular method doesn't appear anymore in swagger UI.

Using the following version of the package: https://www.nuget.org/packages/Swashbuckle.AspNetCore.SwaggerUI/1.1.0

**Comment by ballm** [comment]
Have just seen this too. Any update? Also using 1.1.0

**Comment by domaindrivendev** [comment]
As described [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#decorate-individual-actions), `ApiExplorerSettings.GroupName` is used to assign action descriptions to a specific Swagger JSON document. If the value is null (i.e. the default), then the action will be included in ALL Swagger documents. If you set it to a specific value, then the action will only be included if you request the corresponding Swagger document. For example, if you have the following action

```csharp
[ApiExplorerSettings(GroupName = "v3")]
public IActionResult Get()
{
   ...
}
```
 Then it will only be included with the following Swagger document:

`http://example.com/swagger/v3/swagger.json`
