### ISSUE TITLE
Support C# 7.2 feature....?

### ISSUE THREAD

**Issue by NMSLanX** [domaindrivendev/Swashbuckle.AspNetCore#565]
Code: public void Get(**in** int id);  
Show: Swashbuckle.AspNetCore can't show the method's comments.
Code: public void Get(int id);
Show; It's ok!

**Comment by loxsmoke** [comment]
XML documentation problem apparently. Creating names from reflection to search in XML doc file is quite tricky sometimes.  I even created LoxSmoke.DocXml Nuget package that retrieves XML documentation based on reflection but it is .net standard 2.0 which is not supported by Swashbuckle so I cannot even offer it as solution here. 
Maybe creating operation filters could somehow solve this problem?

**Comment by NMSLanX** [comment]
Thanks a lot. And the Asp.net-Core don't support the new feature. I'm sorry-what I rasied the issue was very thoughtless.

**Comment by domaindrivendev** [comment]
If you’re satisfied there’s nothing SB can do at this point, please close the issue. Thanks

**Comment by NMSLanX** [comment]
SB？What does this word mean?

**Comment by domaindrivendev** [comment]
Swashbuckle
