### ISSUE TITLE
the query parameter is required by default?

### ISSUE THREAD

**Issue by tianbiai** [domaindrivendev/Swashbuckle.AspNetCore#567]
[HttpGet("test")]
public async Task<IActionResult> Get(int start, int end,  int areatype)

when I use Swashbuckle 1.0.0 , the parameter start,end,areatype is not required.

I update to 1.1.0,the UI display the parameter start,end,areatype as required.

how to set the parameter as not required??

**Comment by domaindrivendev** [comment]
Try making them nullable

**Comment by domaindrivendev** [comment]
See #599
