### ISSUE TITLE
(IgnoreApi = true) is ignored for OData controller

### ISSUE THREAD

**Issue by Mithgroth** [domaindrivendev/Swashbuckle.AspNetCore#568]
Helloes.
My swagger is broken after I added a new Controller for OData purposes.

```
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MyDomain.Models;
using Microsoft.AspNet.OData;
using Microsoft.EntityFrameworkCore;

[ApiExplorerSettings(IgnoreApi` = true)]
[Route("odata/Events")]
public class EventsODataController : Controller
{
   private readonly DbContext _context;
   public EventsODataController(DbContext context)
   {
       _context = context;
   }

   [EnableQuery]
   public IActionResult Get()
   {
       return Ok(_context.Events.Include(e => e.Venue).AsQueryable());
   }
}
```

Although I've flagged this controller with `Microsoft.AspNetCore.Mvc.ApiExplorerSettingsAttribute(IgnoreApi = true)` and this works on all other ordinary controllers; Swagger returns me the exception below:

> InvalidOperationException: No media types found in &#x27;Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes&#x27;. Add at least one media type to the list of supported media types.

It should have been ignored like other controllers, right?

**Comment by domaindrivendev** [comment]
Can you provide a full stack trace?

**Comment by Mithgroth** [comment]
I'm using `Microsoft.AspNetCoreCore.OData(7.0.0-beta1)` package in case you want to reproduce.
The relevant part from Output window:

>MyProject> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
MyProject>       Request starting HTTP/1.1 GET http://localhost:64044/swagger/v1/swagger.json  
MyProject> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
MyProject>       An unhandled exception has occurred while executing the request
MyProject> System.InvalidOperationException: No media types found in 'Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.
MyProject>    at Microsoft.AspNetCore.Mvc.Formatters.OutputFormatter.GetSupportedContentTypes(String contentType, Type objectType)
MyProject>    at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.GetApiResponseTypes(IApiResponseMetadataProvider[] responseMetadataAttributes, Type type)
MyProject>    at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.CreateApiDescription(ControllerActionDescriptor action, String httpMethod, String groupName)
MyProject>    at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.OnProvidersExecuting(ApiDescriptionProviderContext context)
MyProject>    at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
MyProject>    at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
MyProject>    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
MyProject>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
MyProject> --- End of stack trace from previous location where exception was thrown ---
MyProject>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
MyProject>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MyProject>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
MyProject> --- End of stack trace from previous location where exception was thrown ---
MyProject>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
MyProject>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MyProject>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
MyProject> --- End of stack trace from previous location where exception was thrown ---
MyProject>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
MyProject>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MyProject>    at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
MyProject> --- End of stack trace from previous location where exception was thrown ---
MyProject>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
MyProject>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MyProject>    at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
MyProject> --- End of stack trace from previous location where exception was thrown ---
MyProject>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
MyProject>    at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
MyProject> --- End of stack trace from previous location where exception was thrown ---
MyProject>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
MyProject>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
MyProject>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
MyProject> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
MyProject>       Request starting HTTP/1.1 GET http://localhost:64044/swagger/images/favicon-16x16.png  
MyProject> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
MyProject>       Sending file. Request path: '/images/favicon-16x16.png'. Physical path: 'N/A'
MyProject> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
MyProject>       Request finished in 30.9959ms 200 image/png
MyProject> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
MyProject>       Request finished in 281.477ms 500 text/html; charset=utf-8

**Comment by Mithgroth** [comment]
@domaindrivendev Any updates?

**Comment by eloekset** [comment]
I'm having the same issue. Did you find a solution to it?
