### ISSUE TITLE
I'm trying to find the way to force authorization on documentation page.

### ISSUE THREAD

**Issue by msmolka** [domaindrivendev/Swashbuckle.AspNetCore#571]
I'm trying to secure api documentation with login/password 
it can be cookie or basic, doesn't matter. 
But I cannot find configuration option to force authorization for documentation page (NOT API itself)
but swagger endpoint.

**Comment by dataspun** [comment]
One option is to use IIS authentication settings.

**Comment by domaindrivendev** [comment]
Dup of #429
