### ISSUE TITLE
ControllerName() for sorting (ordering) is internal not public

### ISSUE THREAD

**Issue by msmolka** [domaindrivendev/Swashbuckle.AspNetCore#572]
In documentation there is a way to sort based on controller name and Http method.

But `ControllerName()` extension is not accessible (based on code it is internal property.

**Comment by VisualBean** [comment]
try looking at this https://github.com/domaindrivendev/Swashbuckle/issues/11

**Comment by domaindrivendev** [comment]
Addressed by 2a3a8a96f3f6ff807e13e34fa605845ec3dc341b.

Those extension methods are for internal use only and I don't want to expose them. So, I've updated the docs with an alternative.
