### ISSUE TITLE
OAuth2 login in third party ui swagger web site

### ISSUE THREAD

**Issue by chigivigi** [domaindrivendev/Swashbuckle.AspNetCore#576]
I am using a third party ui swagger web site to test my swagger.json in my web api and I haven't defined my own ui swagger in my web api. the third party swagger ui site is https://editor.swagger.io/. My oauth definition follows the example on this github page:

c.AddSecurityDefinition("oauth2", new OAuth2Scheme
    {
        Type = "oauth2",
        Flow = "implicit",
        AuthorizationUrl = "my authorize url",
        Scopes = new Dictionary<string, string>
        {
            { "readAccess", "Access read operations" },
            { "writeAccess", "Access write operations" }
        }
    });

I have defined my operation filter that is used with the security definition correctly and it works when I use apikey security definition. the current version that I use is 1.1.0.  When I try to authorize on the third party ui swagger web site passing my clientID it redirects me on the microsoft login site and tells me that my provider is not defined. How can I modify my security definition that the authorize request returns successfully ?

**Comment by domaindrivendev** [comment]
As per the [contributing guidelines](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/CONTRIBUTING.md), I want to restrict issues in these repo to bug reports and feature requests.

I think this is more of a general question around using SB, and in particular how to integrate with a third party tool, and therefore would encourage you to post on StackOverflow instead. Thanks
