### ISSUE TITLE
Add Assembly at Runtime

### ISSUE THREAD

**Issue by AceCoderLaura** [domaindrivendev/Swashbuckle.AspNetCore#580]
When I load an application part with a controller in it, Swashbuckle doesn't add the controller to the Swagger.

```
List<System.Reflection.Assembly> ExtraControllerAssemblies { get; set; }

public void ConfigureServices(IServiceCollection services)
{
  foreach (var assembly in ExtraControllerAssemblies)
  {
      services.AddMvc().AddApplicationPart(assembly);
  }
}
```

I can invoke actions on the runtime-loaded controller just fine, so it's clearly loaded properly, but Swashbuckle hasn't generated any Swagger for it.

**Comment by domaindrivendev** [comment]
You’ll need to take this up with the aspnet folks and specifically how ApiExplorer handles (or doesn’t handle) dynamically added controllers. SB basically takes the metadata surfaced by ApiExplorer and maps to a Swagger format

**Comment by domaindrivendev** [comment]
I’m going to close as a fix is outside the scope of SB so long as it continues to depend on ApiExplorer - something that I don’t plan on changing

**Comment by AceCoderLaura** [comment]
Okay, I'll take it up with them.
Can you point me to a repository or support forum by any chance?
Thanks for your response 👍

**Comment by chenyi1008** [comment]
@AceCoderLaura Hi, were you able to resolve this issue? I'm seeing the same issue with swagger to work with an assembly which contains controllers and is loaded by Applicationpart.

**Comment by goors** [comment]
Same here ...
