### ISSUE TITLE
Add Api Response Time to Response result #570

### ISSUE THREAD

**Issue by sagarkul** [domaindrivendev/Swashbuckle.AspNetCore#584]
Current Swagger page, When you hit try it out button.
It shows
Curl, Request URL, Response Body, Response Code and Response Headers

All I want to know is the response time taken by the API.

This will help to check the performance of the API response (time).
Currently, I can go to dev tool and check it on the network tab.
however, it will be convenient if we provide that information along with above results.

**Comment by domaindrivendev** [comment]
This is a UI issue and so should be posted to the Swagger-ui repo

**Comment by sagarkul** [comment]
I checked with swagger-ui. Look like there is option for [displayRequestDuration](https://github.com/swagger-api/swagger-ui/issues/4237) 

with 1.2.0 version there is setting which enables display request duration.

```
            app.UseSwaggerUI(c =>
            {
......
                c.DisplayRequestDuration();
            });
 
```

Thanks

**Comment by jawn** [comment]
For future reference, 
With Swagger UI 3 you can enable the setting like this:

```
app.UseSwaggerUi3(c => 
  c.AdditionalSettings.Add("displayRequestDuration", true))
);
```
