### ISSUE TITLE
Tags with spaces have the space replaced with "32"

### ISSUE THREAD

**Issue by freeranger** [domaindrivendev/Swashbuckle.AspNetCore#585]
Hi,

I was following this example: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/263#issuecomment-279125263
to put spaces in the tags so that in the ui I see
"Foo Bar" rather than "FooBar" for my "FooBarController"

This works fine but I notice that the link address to the tag is "#!/Foo32Bar".
I could understand "#!/Foo%32Bar" but this seems a bit odd as it stands.

Perhaps there is another way to get spaces showing which is not about changing the tag itself?

**Comment by domaindrivendev** [comment]
This is related to the swagger-ui which is leveraged but not maintained here. Please post to the swagger-uni repo.
