### ISSUE TITLE
new lines in examples

### ISSUE THREAD

**Issue by freeranger** [domaindrivendev/Swashbuckle.AspNetCore#588]
Hi,
I am trying to generate an example for an end point that returns only text/csv
I am setting the example:
```
Foo,Bar
foo1,bar2
```
but in swagger it all appears on one line
```
Foo,Bar\r\nfoo1,bar1
```
Swagger UI seem to have fixed this: https://github.com/swagger-api/swagger-ui/pull/3353
Is Swashbuckle on an earlier version?  If so, do you have any plans to update?  
Thanks

**Comment by acjh** [comment]
> SwaggerUI3 is now available in beta - see #550 for details

**Comment by freeranger** [comment]
Thanks @acjh but at the moment I need to stick with the standard release.
It may be this PR should have made it into the existing codebase and needs some config I am unaware of

**Comment by acjh** [comment]
That PR is in swagger-ui v3.0.19. Swashbuckle is not a fork of swagger-ui.

**Comment by freeranger** [comment]
Ah ok, thanks.
Is there any workaround in the meantime?

**Comment by domaindrivendev** [comment]
@freeranger - As of 2.0.0, SB now ships with the newer (3x) version of the swagger-ui. Can you verify if this is still an issue in the latest version? Other than upgrading the embedded swagger-ui, there's not much SB can do at this point.
