### ISSUE TITLE
Enums marked with alternate values using [EnumMember(Value="...")] are not supported

### ISSUE THREAD

**Issue by tstrass** [domaindrivendev/Swashbuckle.AspNetCore#589]
Below is copied from https://github.com/domaindrivendev/Swashbuckle/issues/562, because I am seeing the same issue in Swashbuckle.AspNetCore. It looks like someone attempted to fix this in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/414, but that PR is pretty out-of-date, and failing CI. That fix there appears to be replicating https://github.com/domaindrivendev/Swashbuckle/pull/563, but those changes are now out-of-date as well in Swashbuckle, as the enum schema is now generated using a [Type extension](https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Swagger/TypeExtensions.cs#L41).

> Forgive the contrived example, but given the following code:
> ```C#
> public class DefaultController : ApiController
> {
>     [ResponseType(typeof(TestResult))]
>     public IHttpActionResult Get(string id)
>     {
>         return this.Ok(new TestResult());
>     }
> }
> 
> [DataContract]
> public class TestResult
> {
>     [DataMember]
>     public TestEnum Type { get; set; }
> }
> 
> [DataContract]
> public enum TestEnum
> {
>     [EnumMember(Value = "roger")]
>     None = 0,
>     [EnumMember(Value = "blake")]
>     Something = 1,
>     [EnumMember(Value = "sarah")]
>     SomethingElse = 2
> }
> ```
> The API will return "roger", "blake" or "sarah" depending on the enum value. Swashbuckle does not pick up on the alternative names and reports that the potential options are "None", "Something" or "SomethingElse".

**Comment by PaulDotNet** [comment]
Quite frankly Swagger support for enums is pathetic. It is great when values are 0, 1, 2, 3... etc. but when they do not start from 0 or have gaps between values then generated swagger spec is useless. I converted my code to generate simple ints and added description of values to the comment. Clunky but it works.

**Comment by onionhammer** [comment]
@PaulDotNet I recently made a PR that nobody seems to have reviewed to help improve enum support... these custom members arent supported though

**Comment by rfrancisco** [comment]
Any updates regarding this issue?

**Comment by elize-vdr** [comment]
O gosh, 2021, and this problmem is still around, compeltely ignoring the [EnumMember] value and therefore showing users of the API the wrong value in the response. Not sure how I am goign to get a workaroudn for this.

**Comment by elize-vdr** [comment]
In case anybody needs a solution I solved it in the following way:
For this enum:
```
    public enum AssociationMultiplicity {
        [EnumMember(Value = "unknown")]
        Unknown,
        [EnumMember(Value = "zero-or-one")]
        ZeroOrOne,
        [EnumMember(Value = "one")]
        One,
        [EnumMember(Value = "many")]
        Many
    }
```

Create an extension for the enumerator to convert the value to the EnumMember attribute value, here it is:
```
    public static class AssociationMultiplicityExtension
    {
        public static string GetEnumMember(this AssociationMultiplicity value)
        {
            var type = value.GetType();
            var name = Enum.GetName(type, value);
            if (name == null)
                return null;
            var field = type.GetField(name);
            if (field is null || !Attribute.IsDefined(field, typeof(EnumMemberAttribute)))
                return null;
            if (Attribute.GetCustomAttribute(field, typeof(EnumMemberAttribute)) is EnumMemberAttribute attr)
            {
                return attr.Value;
            }
            return null;
        }
}
```

Then create a SchemaFilter class like this:
```
public class ProblemDetailsSchemaFilter : ISchemaFilter
{
    
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {        
        if (context.Type == typeof(AssociationMultiplicity))
        {
            schema.Enum.Clear();
            var valuesArray = Enum.GetValues(typeof(AssociationMultiplicity));

            foreach (AssociationMultiplicity val in valuesArray)
            {
                schema.Enum.Add(new OpenApiString(val.GetEnumMember()));
            }

        }
    }
}
```

And register this SchemaFilter in the ConfigureServices where the AddSwaggerGen is called:
```
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "WebContractsParsing API - V1", Version = "v1" });
    // For future versions an example, see here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments
    // c.SwaggerDoc("v2", new OpenApiInfo { Title = "WebContractsParsing API - V2", Version = "v2" });

    var filePath = Path.Combine(System.AppContext.BaseDirectory, "WebContractsParsingApi.xml");
    c.IncludeXmlComments(filePath);
    
    c.DescribeAllParametersInCamelCase();

    c.SchemaFilter<ProblemDetailsSchemaFilter>();
}
```

**Comment by domaindrivendev** [comment]
FYI this 100% should be working out-of-the-box without need for custom code. I’m assuming you have something configured incorrectly. Please create a minimal app (ie starting from blank project) that repro’s and post to GitHub so I can pull down and troubleshoot

**Comment by elize-vdr** [comment]
Hi Richard, I take your word that it should be working, then I may have a config issue. Adding a simple example here, I quickly created it with JetBrains Rider, hope it works on your end, you will find here the `AssociationMultiplicity` is not displaying in the swagger the `EnumMember` value. I tried to depict my configuration by adding the enum in a class in a library which is how I am using it. Thanks for taking a look. It does return the correct `zero-or-one` in the JSON response but in the swagger it is `ZeroOrOne`
[DemoWebAppEnums.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/7925523/DemoWebAppEnums.zip)
.

**Comment by elize-vdr** [comment]
BTW <example> also does not work, I add `/// <example>Some text</example>` above a member of a class being used in response or request, specifying the type in the attributes for response, for example `[ProducesResponseType(typeof(EntitySetCollection), StatusCodes.Status200OK)]` and they never show in the swagger, I have to add it to an ISchemaFilter class I created for all examples I want to show.

**Comment by xhafan** [comment]
@elize-vdr's solution does not work for me for 6.3.1, but it helped me to create a solution which works for me:
```
public class IgnoreEnumMemberValueSchemaFilter : ISchemaFilter
{
    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        if (context.Type == typeof(AssociationMultiplicity))
        {
            schema.Enum.Clear();
            var enumValues = Enum.GetValues(typeof(AssociationMultiplicity));

            foreach (var val in enumValues)
            {
                schema.Enum.Add(new OpenApiString(GetEnumConstantNameIgnoringEnumMemberValue(val)));
            }
        }
    }

    private string GetEnumConstantNameIgnoringEnumMemberValue<TEnum>(TEnum value)
    {
        var type = value.GetType();
        return Enum.GetName(type, value);
    }
}
```
It basically ignores `EnumMember` values, and uses enum constant names as if the `EnumMember` attribute is missing.

**Comment by jnv** [comment]
Note that `EnumMember` works only if you use `Newtonsoft.Json`-based serializer. Looks like this was not implemented for `System.Text.Json` – I reported a new issue for that: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/3328
