### ISSUE TITLE
Minimal setup example

### ISSUE THREAD

**Issue by rfcdejong** [domaindrivendev/Swashbuckle.AspNetCore#59]
Could you update the Readme with a simple example on how to setup? Maybe a pre-release NuGet package as well :+1: 

The best I found documentating this was http://devmeetsbi.ghost.io/help-and-test-page-for-asp-net-web-api-asp-net-5-and-mvc-6/

Not beta-6, but then the rc1-final https://www.nuget.org/packages/Swashbuckle/6.0.0-rc1-final

**Comment by styfle** [comment]
:+1:

**Comment by domaindrivendev** [comment]
See "Getting Started" in readme
