### ISSUE TITLE
Cannot find a way to get a cross origin json in swagger UI from Startup.cs

### ISSUE THREAD

**Issue by qrasmont** [domaindrivendev/Swashbuckle.AspNetCore#593]
Hi,
I have two ASP.NET Core projects. One is an API on which I generate a swagger.json to document my API.
On my other Core project I have implemented Swagger UI and I want to display the swagger.json.

I haven't found a way to specify a external host to get the json from.

To be clear :
* My json is generated at localhost:5000
* My swagger UI is at localhost:8000

I want to display my json on localhost:5000 to my UI on localhost:8000

in Startup.cs how can I specify this ?

`
app.UseSwaggerUI(c =>
            {
               //Some way to get json from localhost:5000
            });
`

Hope I was clear.
Thanks for your help !

PS: I have allowed CORS and I can display my json if I enter the url in the swaggerUI search bar.

**Comment by domaindrivendev** [comment]
Have you tried the following:

‘’’csharp
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint(“http://localhost:5000/Swagger/v1/Swagger.json”, “V1 Docs”);
});

**Comment by qrasmont** [comment]
Of course, it just generate the following url : http://localhost:8000/http://localhost:5000/Swagger/v1/Swagger.json

**Comment by domaindrivendev** [comment]
Hmmm - then we have a bug because that's certainly not the intended behavior. Will investigate

**Comment by domaindrivendev** [comment]
Which version are you using? I'm using 1.1.0 and it works fine for me ...

This is what I have in my `Startup.cs`:

```csharp
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("http://example.com/swagger/v1/swagger.json", "V1 Docs");
});
```

This is what I see in the UI:

![swagger](https://user-images.githubusercontent.com/1434343/36271918-d384912c-1234-11e8-8a54-0d8ee22120b7.png)

Are you by any chance using a custom version of index.html that's doing something weird with the URL?

**Comment by qrasmont** [comment]
Ok I'm sorry I apparently did something wrong , i tested this :
`app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("http://example.com/swagger/v1/swagger.json", "V1 Docs");
});
`
I got the expected behavior
so I tested again with localhost  :
`
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint(“http://localhost:5000/Swagger/v1/Swagger.json”, “V1 Docs”);
});
`
and everything works. I must have done something wrong previouly.

**Comment by kkblues** [comment]
https://stackoverflow.com/questions/48450262/asp-net-core-swashbuckle-not-creating-swagger-json-file/56129755#56129755
