### ISSUE TITLE
Required parameter with default value incorrectly marked as required in swagger docs

### ISSUE THREAD

**Issue by nphmuller** [domaindrivendev/Swashbuckle.AspNetCore#595]
I have the following controller and action:
``` c#
public class MyController : ControllerBase
{
    [HttpGet]
    public Task<PagedResult<MyClass>> SearchAsync(
        [FromQuery] string query,
        [FromQuery] uint page = 0, [FromQuery] uint? pageSize = null)
    {
        // ...
    }
}
```

In version 1.0 of Swashbuckle.AspNetCore the page parameter was not marked as required, but in version 1.1.0 it is. This PR introduced this behaviour: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/534/

I went ahead and tried to extend the `IsRequired` method in `ApiParameterDescriptionExtensions` with a check to see if the parameter has a default value. This is pretty straightforward in ASP.NET 2.0:
``` c#
public static bool IsRequired(this ApiParameterDescription parameterDescription)
{
    var modelMetadata = parameterDescription.ModelMetadata;
    var parameterDescriptor = parameterDescription.ParameterDescriptor as ControllerParameterDescriptor;
    return (modelMetadata == null) ? false : modelMetadata.IsRequired && parameterDescriptor?.ParameterInfo.HasDefaultValue != true;
}
```

The problem however is that the `ParameterDescriptor` property does not exist on `ApiParameterDescription` in ASP.NET Core 1.x, and I can't think of any easy way to obtain the ParameterInfo.

I will submit a PR to fix this, if I can get past this. But for now I'm stuck at this point.

**Comment by domaindrivendev** [comment]
See #599
