### ISSUE TITLE
Swashbuckle.AspNetCore.Cli Not found

### ISSUE THREAD

**Issue by ranouf** [domaindrivendev/Swashbuckle.AspNetCore#601]
Hi,

I m currently using this Url Rewriting configuration based on this article:
https://weblog.west-wind.com/posts/2017/Apr/27/IIS-and-ASPNET-Core-Rewrite-Rules-for-AspNetCoreModule

But It s not compatible with Swagger-Ui, I need to disable these handlers to make Swagger-Ui working:

```
    <handlers>
      <add name="StaticFileModuleHtml" path="*.htm*" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleSvg" path="*.svg" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleJs" path="*.js" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleCss" path="*.css" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleJpeg" path="*.jpeg" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleJpg" path="*.jpg" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModulePng" path="*.png" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      <add name="StaticFileModuleGif" path="*.gif" verb="*" modules="StaticFileModule" resourceType="File" requireAccess="Read" />
      [...]
    </handlers>
```
 
But when I m doing this, my angular WebSite is not working anymore :)

I saw on your git: https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcorecli
That is possible to extract all the content and make accessible directly from a folder.

But for :

`  <DotNetCliToolReference Include="Swashbuckle.AspNetCore.Cli" Version="2.0.0-beta1" />`

source: [Your git](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcorecli) 

OR 

`<DotNetCliToolReference Include="Swashbuckle.AspNetCore.Cli" Version="1.2.0-beta1" />`

source: [Your csProject source code](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/CliExample/CliExample.csproj) 

I have this error:

> Error occurred while restoring NuGet packages: Value cannot be null.
> Parameter name: path
> NU1101: Unable to find package Swashbuckle.AspNetCore.Cli. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

I try to use the Nugget Ui to find the package, 
![image](https://user-images.githubusercontent.com/1764519/36452394-513864b4-1662-11e8-8e86-3c942fbcf841.png)
![image](https://user-images.githubusercontent.com/1764519/36452405-5a0f3590-1662-11e8-9652-468be62cfcbe.png)

Do i need to add a nugget source? If yes, which one?

**Comment by ranouf** [comment]
I finally found a way to avoid to extract the Swagger Ui in a folder when the project build.
If someone is interested to see: https://stackoverflow.com/questions/48889816/iis-rewrite-exclude-folders-and-subfolders-swagger-case/48893301#48893301

But there is still an issue, the package is not available.

**Comment by domaindrivendev** [comment]
This is only available as a preview package from myget.org. Just updated the docs:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#swashbuckleaspnetcorecli
