### ISSUE TITLE
2.0.0 Authorization Token not being sent in Headers

### ISSUE THREAD

**Issue by jglisson** [domaindrivendev/Swashbuckle.AspNetCore#603]
In the new version, the Authorization token is not being passed in the request header.

Setup...
![image](https://user-images.githubusercontent.com/6360789/36558455-264c545e-17d9-11e8-8de6-356991aa44c0.png)

![image](https://user-images.githubusercontent.com/6360789/36558487-390bfd88-17d9-11e8-8263-492c7ea8cc86.png)

1. Call my Login method (POST) and retrieve JWT
2. Add "Bearer {JWT}" using the Authorize feature of Swagger UI.
3. Call a secured method (GET, POST, whatever) and receive 401 Unauthorized. The curl does not show the Authorization header has been added to the request at all. Confirmed the header is not there in the Chrome developer console.

I can uninstall Swashbuckle, and install 1.1.0 or 1.2.0 and it works. 2.0.0 does not work.

Thanks!

**Comment by jglisson** [comment]
Sounds similar. I don't hide based on authorization. But, I do have the "Authorize" attribute set on all methods other than my Login method (which is AllowAnonymous) . As such, all methods other than Login return a 401, even after adding the Bearer {token} to the Authorization section of the Swagger doc.

I like the new Swagger layout a lot better. In particular I like that it renders the models at the bottom of the document. However, it's a nonstarter if the Authorization doesn't work.

Thanks all!

**Comment by joakimhew** [comment]
Can confirm that the authorization header is not set. I can take a look at it and hopefully soon have a PR for a fix + tests.

**Comment by RehanSaeed** [comment]
Also have the same issue. It is setting a `WWW-Authenticate: Bearer` HTTP header though.

**Comment by domaindrivendev** [comment]
I’ll look into this. The OAuth example in this repo works without a hitch so I’m surprised that other auth methods aren’t working.

**Comment by RehanSaeed** [comment]
I'm using both OAuth and Basic in the same API. Just confirmed that Basic is not working for me either.

**Comment by maucodev** [comment]
I have the same problem. Meanwhile, I will be using version 1.2.0

**Comment by domaindrivendev** [comment]
As per the [Swagger spec](https://swagger.io/specification/#securityRequirementObject), defining the scheme alone is not sufficient. You also need to provide a `Security Requirement Object` at the document level or on individual operations to indicate which operations that scheme is applicable to.

If this was working in the previous version of the UI without the security requirement, then that's really a bug because it shouldn't have been according to the spec. The security semantics in Swagger 2.0 are fairly clunky IMO, but still, you should be able to get things working by wiring up the following DocumentFilter (see readme). I just verified locally and it works exactly as expected for Bearer and Basic.

```csharp
public class SecurityRequirementsDocumentFilter : IDocumentFilter
{
    public void Apply(SwaggerDocument document, DocumentFilterContext context)
    {
        document.Security = new List<IDictionary<string, IEnumerable<string>>>()
        {
            new Dictionary<string, IEnumerable<string>>()
            {
                { "Bearer", new string[]{ } },
                { "Basic", new string[]{ } },
            }
        };
    }
}
```

**Comment by jglisson** [comment]
Yep, that worked. Thanks @domaindrivendev

**Comment by RehanSaeed** [comment]
I got Basic auth working but OAuth2 is not. I can get as far as logging in as shown here:

![untitled](https://user-images.githubusercontent.com/2270364/36665042-5b141f70-1ade-11e8-86ed-8d94af55f405.png)

When hitting Execute on an operation, it's not adding an Authorization HTTP header to the request:

![untitled2](https://user-images.githubusercontent.com/2270364/36665084-892636fa-1ade-11e8-9c2f-fea57ee82312.png)

Here is the code I'm using for OAuth2:

### AddSwaggerGen
```
var scheme = new OAuth2Scheme()
{
    AuthorizationUrl = "https://login.microsoftonline.com/{Company Name}.onmicrosoft.com/oauth2/authorize",
    Description = "OAuth2 Authentication using Azure Active Directory.",
    Flow = "implicit",
    Type = "oauth2"
};
options.AddSecurityDefinition("oauth2", scheme);
options.OperationFilter<ClaimsOperationFilter>();
```

### ClaimsOperationFilter
```
public class ClaimsOperationFilter : IOperationFilter
{
    public void Apply(Operation operation, OperationFilterContext context)
    {
        var filterDescriptors = context.ApiDescription.ActionDescriptor.FilterDescriptors;
        var authorizationRequirements = filterDescriptors.GetPolicyRequirements();
        var claimTypes = authorizationRequirements
            .OfType<ClaimsAuthorizationRequirement>()
            .Select(x => x.ClaimType)
            .ToList();
        if (claimTypes.Any())
        {
            operation.Security = new List<IDictionary<string, IEnumerable<string>>>
            {
                new Dictionary<string, IEnumerable<string>>()
                {
                    { "basic", claimTypes },
                    { "oauth2", claimTypes }
                }
            };
        }
    }
}
```

### SwaggerUIOptions
```
options.OAuthAppName("My Application");
options.OAuthClientId("{Client ID GUID}");
options.OAuthAdditionalQueryStringParams(new { nonce = Guid.NewGuid().ToString() });
```

### swagger.json

```
{
    "swagger": "2.0",
    "info": {
        "version": "1.0",
        "title": "...Omitted",
        "description": "...Omitted"
    },
    "paths": {
        "/foo": {
            "get": {
                "tags": [
                    "...Omitted"
                ],
                "summary": "...Omitted",
                "operationId": "...Omitted",
                "consumes": [],
                "produces": [
                    "application/json",
                    "text/json"
                ],
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "...Omitted",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/...Omitted"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized - The user has not supplied the necessary credentials to access the resource."
                    },
                    "403": {
                        "description": "Forbidden - The user does not have the necessary permissions to access the resource."
                    }
                },
                "security": [
                    {
                        "basic": [
                            "roles"
                        ],
                        "oauth2": [
                            "roles"
                        ]
                    }
                ]
            }
        }
    },
    "definitions": {
        "...Omitted": {
        },
    },
    "securityDefinitions": {
        "basic": {
            "type": "basic",
            "description": "Basic HTTP Authentication using a username and password."
        },
        "oauth2": {
            "flow": "implicit",
            "authorizationUrl": "https://login.microsoftonline.com/{Company Name}.onmicrosoft.com/oauth2/authorize",
            "type": "oauth2",
            "description": "OAuth2 Authentication using Azure Active Directory."
        }
    }
}
```

**Comment by Razzeee** [comment]
I also thought oauth2 is not working. It started to work when I changed the example above to this:
```
public class SecurityRequirementsDocumentFilter : IDocumentFilter
{
    public void Apply(SwaggerDocument document, DocumentFilterContext context)
    {
        document.Security = new List<IDictionary<string, IEnumerable<string>>>()
        {
            new Dictionary<string, IEnumerable<string>>()
            {
                { "oauth2", new string[]{ "openid", "profile", "email" } },
            }
        };
    }
}
```

`oauth2` is the name of my security definition

```
options.AddSecurityDefinition("oauth2", new OAuth2Scheme
                    {
                            Description = "Client credentials needed.",
                            Type = "oauth2",
                            Flow = "implicit",
                            AuthorizationUrl  = "http://localhostandstuff/auth/realms/master/protocol/openid-connect/auth",
                            Scopes = new Dictionary<string, string>
                                {
                                    { "openid", "Standard openid scope" },
                                    { "profile", "Standard openid scope" },
                                    { "email", "Standard openid scope" },
                                }
                    });
```

**Comment by RehanSaeed** [comment]
@Razzeee That didn't seem to work for me. I still don't see the `Authorization` getting added to the request. I'm going to try and debug the JavaScript to see why that is the case.

**Comment by RehanSaeed** [comment]
I've worked it out, sadly Swagger UI has hard coded the name of the token to `access_token` and I'm using Azure Active Directory which uses an `id_token`. I had a workaround in Swagger v2 as described here https://github.com/swagger-api/swagger-ui/issues/1974 that no longer works with v3 because they've hard coded the token name in a few more places.

**Comment by RainingNight** [comment]
any 2.1.1 nuget package?

**Comment by domaindrivendev** [comment]
It’s published but unlisted because there seems to be other issues with it. Working on it

**Comment by IeuanWalker** [comment]
I'm having this bug with Bearer tokens. Here is my C#
```csharp
c.AddSecurityDefinition("Bearer", new ApiKeyScheme
{
    Name = "Authorization",
    In = "header",
    Description = "JWT Authorization header using the Bearer scheme. Example: \"Bearer {token}\"",
    Type = "apiKey"
});
```
![image](https://user-images.githubusercontent.com/6544051/36858189-6b342396-1d72-11e8-864a-4f56797dac64.png)

But when i try HttpDelete with [Authorise] Attribute added, this is the response - 
![image](https://user-images.githubusercontent.com/6544051/36858276-99dfcf42-1d72-11e8-94af-a49f44bd7c4c.png)
The same API tested in Postman works completely fine -
![image](https://user-images.githubusercontent.com/6544051/36858339-cf522fe4-1d72-11e8-94b3-7857a8f11e42.png)

**Comment by Razzeee** [comment]
Is your `SecurityRequirementsDocumentFilter` matching the one from this topic and referenced correctly?

**Comment by RainingNight** [comment]
I'm having too, and I add SecurityRequirementsDocumentFilter :
```csharp
c.AddSecurityDefinition("oauth2", new OAuth2Scheme
{
    Type = "oauth2",
    Flow = "password",
    TokenUrl = "/api/Token/Authenticate"
});
c.DocumentFilter<SecurityRequirementsDocumentFilter>();
```

I loggin in, but Authorization Token still not being sent in Headers.

**Comment by ristogod** [comment]
I've tried every option listed here and none of them work at all. Authorization worked fine prior to this update and now is totally broke.

Here is my code updated with suggested changes here:

``` c#
options.AddSecurityDefinition("Bearer",
                              new ApiKeyScheme
                              {
                                  Description = "Token Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                                  Name = "Authorization",
                                  In = "header",
                                  Type = "apiKey"
                              });

options.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
                               {
                                   { "Bearer", new string[] { } }
                               });
```

Doesn't work rendering swagger useless requiring outside tooling.

**Comment by tariknz** [comment]
This worked for me if you're using a bearer token.

```
c.AddSecurityDefinition("Bearer", new ApiKeyScheme
{
    In = "header",
    Description = "Please insert JWT with Bearer into field",
    Name = "Authorization",
    Type = "apiKey"
});

c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
{
    { "Bearer", new string[] { } }
});
```

**Comment by samart-chaiprasittikul** [comment]
@tariknz Thank you for setting authorize in swagger  v.2.2  It's work

**Comment by VinTheDean** [comment]
Just wanted to say that add that the info @tariknz and @RainingNight also worked for me.  I am using JWT token but I was able to use the oath2 configuration.  That way i can use the Authorization form provided by Swagger UI

`c.AddSecurityDefinition("oauth2", new OAuth2Scheme
                {
                    Type = "oauth2",
                    Flow = "password",
                    TokenUrl = "/api/token",
                });

                c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
                {
                    { "oauth2", new string[] { } }
                });`  


Swagger UI Login
![image](https://user-images.githubusercontent.com/23174737/37502604-06611990-28aa-11e8-95f7-8622b197d2ff.png)

Successfull Call
![image](https://user-images.githubusercontent.com/23174737/37502695-9b54bd68-28aa-11e8-81f7-9be899bf6b75.png)

**Comment by alaniemieckota** [comment]
For JWT 
```
c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
{
    { "Bearer", new string[] { } }
});
```

sovles the problem.

**Comment by ecleveland** [comment]
For Oauth2 using Azure AD integration.
```
c.AddSecurityDefinition("oauth2", new OAuth2Scheme()
{
    AuthorizationUrl = $"https://login.microsoftonline.com/{Configuration["AzureAd:TenantId"]}/oauth2/authorize",
        Flow = "implicit",
        TokenUrl = $"https://login.microsoftonline.com/{Configuration["AzureAd:TenantId"]}/oauth2/token",
        Scopes = new Dictionary<string, string> { { "Arch.NetCoreAPI", "Dotnet Core API" } }
});

c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
{
    { "oauth2", new string[] { } }
});
```

**Comment by Cular** [comment]
Hello. I have problem with getting token by client credentials grant type.
Swashbuckle.AspNetCore V 2.4.0

I've added config for services:
```
services.AddSwaggerGen(c =>
{
	var oauthScheme = new OAuth2Scheme
	{
		Description =
			"JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
		TokenUrl = "/token",
		Flow = "application"
	};

	c.SwaggerDoc("v1", new Info { Title = "Map Service API", Version = "v1" });
	c.AddSecurityDefinition("application", oauthScheme);

	IncludeComments(c);
	c.DescribeAllEnumsAsStrings();
});
```

Then added config for app:
```
app.UseSwaggerUI(c =>
{
	c.SwaggerEndpoint("/swagger/v1/swagger.json", "Map Service API V1");
	c.OAuthClientId("someclientid");
	c.OAuthClientSecret("somepass2app");
	c.OAuthRealm(string.Empty);
	c.OAuthAppName("SomeService");
});
```
On trying to send post request for getting token, i see that in form data i have only grant_type property. My clientCredentials converted to Base64 and putted into Authorization header.
![image](https://user-images.githubusercontent.com/26927442/39056668-07cb4d6e-44c0-11e8-91e2-e95491f41800.png)

Is exist solution for getting my `client_id` and `client_secret` from Form Data. Or should I get the values from encoding Authorization header?

P.S. For example with flow `flow: password` in form data I'm getting `username` and `password`.
P.S.S. I have some doubts that this question should be asked in swagger-ui proj. :)

**Comment by Cular** [comment]
@alaniemieckota , yeah, thanks i found it later.
But for me it works by another way:
```
services.AddSwaggerGen(c =>
{
	var oauthScheme = new OAuth2Scheme
	{
		Description =
			"JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
		TokenUrl = "/token",
		Flow = "application",
		Type = "oauth2"
	};

	c.SwaggerDoc("v1", new Info { Title = "My Service API", Version = "v1" });
	c.AddSecurityDefinition("oauth2", oauthScheme);
	c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>> { { "oauth2", new string[] { } } });
	c.DocumentFilter<SecurityRequirementsDocumentFilter>();
	IncludeComments(c);
	c.DescribeAllEnumsAsStrings();
});
```
And i did it by encoding Header with basic auth:
```
if (!context.Request.Headers.TryGetValue("Authorization", out var authorizationHeader) || authorizationHeader.Count < 1 || !authorizationHeader.First().StartsWith("Basic", StringComparison.OrdinalIgnoreCase))
{
	context.Response.StatusCode = 400;
	await context.Response.WriteAsync(JsonConvert.SerializeObject(new ValidationResultModel((int)BusinessExceptionCode.AuthenticationFalied, "Authorization header must contains: Basic {clientCredentials}")));
}

var convertedCredetials = authorizationHeader.First().Replace("Basic ", string.Empty);
var clientCredentials = Encoding.UTF8.GetString(Convert.FromBase64String(convertedCredetials));
var credentials = clientCredentials.Split(':');
var clientid = credentials[0];
var clientsecret = credentials[1];
```

**Comment by esofar** [comment]
This issue solved my problem,thanks.

**Comment by arlan85** [comment]
Awesome @Cular, this work for me !!! but I have an issue, how to put the response into the "Available authorizations" when it comes back from azure? How to create a response page to retrieve this info and put it on the needed place? 
Than you.

**Comment by Cular** [comment]
@arlan85, sorry for late response. I have no trouble with case, that you describe. My previous post was implemented with nuget version: 2.5.0. And I don't update my dependency on new version, maybe it helps to you. :)

**Comment by trefsahl** [comment]
Swashbuckle.AspNetCore 3.0.0

I think my swagger.json (short version) follows the spec, but I still cannot get SwaggerUI to attach the JWT token on requests. I have implemented a local proxy to login.microsoft.com to avoid CORS when logging in, and the "authorize" function in the UI works - A JWT token is returned and the object follows the spec https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/. 

```json{
  "swagger": "2.0",
  "paths": {
    "/api/crm/images": {
      "get": {
        "tags": [ "Crm" ],
        "operationId": "ApiCrmImagesGet",       
        "security": [ { "oauth2": [ "ImageAPI.Get" ] } ]
      }
    },
    "/api/security/oauth2/token": {
      "post": {
        "tags": [ "Security" ],
        "operationId": "ApiSecurityOauth2TokenPost",
        "consumes": [],
        "produces": [ "text/plain", "application/json", "text/json", "application/xml", "text/xml" ],
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": { "$ref": "#/definitions/AuthenticationResult" }
          }
        }
      }
    },
    "AuthenticationResult": {
      "type": "object",
      "properties": {
        "accessTokenType": { "type": "string" },
        "accessToken": { "type": "string" },
        "expiresOn": {
          "format": "date-time",
          "type": "string"
        }
    }
  },
  "securityDefinitions": {
    "oauth2": {
      "flow": "application",
      "tokenUrl": "/api/security/oauth2/token",
      "scopes": {
        "ImageAPI.Get": "Application can perform GET operations",
        "ImageAPI.Post": "Application can perform POST operations"
      },
      "type": "oauth2"
    }
  },
  "security": [
        { "oauth2": [
           "ImageAPI.Get", "ImageAPI.Post" ] 
        }
    ]
}`
Logging in:
![swagger-auth](https://user-images.githubusercontent.com/6596084/45672184-cd764900-bb27-11e8-8597-c6082f5af3d1.png)

logged in:
![swagger-loggedin](https://user-images.githubusercontent.com/6596084/45672191-d404c080-bb27-11e8-899b-411b8eab05a5.PNG)

Executing a request, but without the required Bearer token resulting in 401
![swagger-request](https://user-images.githubusercontent.com/6596084/45672325-2a71ff00-bb28-11e8-8daa-2b16e65d1699.png)

(It all works with both Postman and a C# console client)

**Comment by Grepsy** [comment]
I had to fiddle around a bit to get this to work for ApiKey auth. Here's what works for me (no need to include the filter mentioned above):

```csharp
c.AddSecurityDefinition("ApiKeyAuth", new ApiKeyScheme {
    Description = "Authorization by pre-shared API key.",
    In = "header",
    Type = "apiKey",
    Name = "X-API-KEY"
});

c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>> {
    { "ApiKeyAuth", new string[0] }
});
```

**Comment by erickkkt** [comment]
Should add Bearer before token string
![image](https://user-images.githubusercontent.com/21192515/54191454-85d5e600-44e8-11e9-9fe3-ac498be788bd.png)
It worked with me :)

**Comment by kambleaa007** [comment]
> .FilterDescriptors

.GetPolicyRequirements() Not works for me???
 Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IList<FilterDescriptor>' does not contain a definition for 'GetPolicyRequirements' and no accessible extension method 'GetPolicyRequirements' accepting a first argument of type 'IList<FilterDescriptor>' could be found (are you missing a using directive or an assembly reference?)	iModelAcquisitionService	D:\PS_Aquisition_Service\toPR\ps-acquisitionservice\Startup.cs	184	Active
