### ISSUE TITLE
2.0.0 Relative SwaggerEndpoint URL doesn't work

### ISSUE THREAD

**Issue by jglisson** [domaindrivendev/Swashbuckle.AspNetCore#604]
When using a relative path for the SwaggerEndpoint, the SwaggerUI shows an error:

![image](https://user-images.githubusercontent.com/6360789/36558690-d0a5cc32-17d9-11e8-87dd-e66ff75666f5.png)

{"schemaValidationMessages":[{"level":"error","message":"Can't read from file /swagger/v1/swagger.json"}]}

When I use an absolute path (includes the fully qualified host and folder location) it works.

Thanks!

**Comment by ltraus** [comment]
How do you happen to be hosting it? I'm having a similar issue but it's due to me using a RP and using a location mapping through nGinx.

**Comment by jglisson** [comment]
@ltraus this is in my local environment...not deployed anywhere yet (http://localhost:port/etc...)

**Comment by ltraus** [comment]
I'm going to assume you updated all the packages to 2.0, and tried.

```
   c=> Endpoint("/swagger/v1/swagger.json")
   c=> Endpoint("swagger/v1/swagger.json")
```
And have not modified the original route prefix?

**Comment by jglisson** [comment]
`c=> Endpoint("/swagger/v1/swagger.json")`

This is how I have it configured.

**Comment by jonthegiant** [comment]
Try removing the preceding /swagger/ route:

```
app.UseSwaggerUI(c => c.SwaggerEndpoint("v1/swagger.json"))
```

**Comment by jglisson** [comment]
Same thing...

`{"schemaValidationMessages":[{"level":"error","message":"Can't read from file v1/swagger.json"}]}`

**Comment by jonthegiant** [comment]
Hmm, can you post your full Startup.cs?

**Comment by jglisson** [comment]
Note: I am using appSettings.json to store some of the values. But, they match what you would expect the string values to be "/swagger/v1/swagger.json" for instance.

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using Swashbuckle.AspNetCore.Swagger;

namespace RCMOneWebApi
{
    public class Startup
    {
        public IConfiguration _config { get; }

        public Startup(IConfiguration configuration)
        {
            _config = configuration;
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc(_config["Swagger:Version"], new Info
                {
                    Title = _config["Swagger:Title"],
                    Version = _config["Swagger:Version"]
                });
                c.AddSecurityDefinition("Bearer", new ApiKeyScheme
                {
                    Description = "JWT Authorization header using the Bearer scheme. Example - Authorization: Bearer {token}",
                    Name = "Authorization",
                    In = "header",
                    Type = "apiKey"
                });
            });

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
            {
                options.TokenValidationParameters = new TokenValidationParameters()
                {
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidateLifetime = true,
                    ValidateIssuerSigningKey = true,
                    ValidIssuer = _config["Jwt:issuer"],
                    ValidAudience = _config["Jwt:issuer"],
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_config["Jwt:Key"]))
                };
            });

            services.AddCors();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint(_config["Swagger:Endpoint"], _config["Swagger:Title"]);
            });

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseAuthentication();
            app.UseMvc();
            app.UseCors(builder => builder.AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials());
        }
    }
}
`

**Comment by ltraus** [comment]
I'm not sure if this is it, but you're missing app.UseStaticFiles() that's the only difference in my code towards yours.

**Comment by domaindrivendev** [comment]
Firstly, it would be more appropriate to post this issue to the [swagger-ui project](https://github.com/swagger-api/swagger-ui) instead of Swashbuckle.

Secondly, it's worth noting that the validator badge makes a GET request to a remote validator passing your Swagger endpoint as a parameter so it can in turn retrieve your Swagger JSON and validate it.

`https://online.swagger.io/validator?url=/swagger/v1/swagger.json`

So, the `url` has to include the domain name and be accessible by the remote validator (e.g. localhost won't work).  For that reason, I would disable the validator badge in all private environments because it's always going to give you an error. To do this, set `ValidatorUrl(null)` as per the [readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#apply-swagger-ui-parameters). Furthermore, if you're going to enable it in production, you need to pass a the full url (e.g. www.example.com/api/swagger/v1/swagger.json") to the `SwaggerEndpoint` method.

**Comment by yosbeleg89** [comment]
I have the same issue after upgrading to 2.0.0, before the update it was working fine.

```C#
    /// <summary>
    /// Adds Swagger JSON endpoints. Can be fully-qualified or relative to the UI page
    /// </summary>
    /// <param name="options"></param>
    /// <param name="url">Can be fully qualified or relative to the current host</param>
    /// <param name="name">The description that appears in the document selector drop-down</param>
    public static void SwaggerEndpoint(this SwaggerUIOptions options, string url, string name)
    {
      options.ConfigObject.Value<JArray>((object) "urls").Add((JToken) JObject.FromObject((object) new
      {
        url = url,
        name = name
      }));
    }
```

According to the SwaggerEndpoint method documentation the url field `Can be fully qualified or relative to the current host`. So it should work as it worked in version 1.

**Comment by buvinghausen** [comment]
The call to the SwaggerEndpoint function is throwing a NullReferenceException for me.

```csharp
app.UseSwagger(o => o.RouteTemplate = "api/docs/{documentName}/swagger.json");
app.UseSwaggerUI(o => {
  o.RoutePrefix = "api/docs";
  o.SwaggerEndpoint("api/docs/v1/swagger.json", "API v1");
});
```

**Comment by fabiobraganet** [comment]
I have the same issue after upgrading to 2.0.0

**Comment by ltraus** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/559 for those with "after upgrade" issues, talks about clearing project files.

**Comment by yosbeleg89** [comment]
I cleared my project files, still not working, also it is not working for me in production.

**Comment by Tochemey** [comment]
Hello,

I am having the same issue. Even mine it points to http://petstore.swagger.io/v2/swagger.json which I do not understand.

**Comment by domaindrivendev** [comment]
I've already explained what's going here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/604#issuecomment-368092353. Please read my comments.

Now, it does look like the latest release enables the validator by default, and this explains why this is suddenly surfacing as an issue. For now, you can have parity with the previous version by disabling the validator:

```csharp
c.UseSwaggerUI(c =>
{
    c.ValidatorUrl(null);
}
```

In the meantime, I'm going to go ahead and push out another release (2.1.0) that disables it by default.

**Comment by domaindrivendev** [comment]
See efaf85ddcc6cdab9006c4b019b12a0ede27b79be. Will be disabled by default as of 2.1.0 (publishing as we speak)

**Comment by buvinghausen** [comment]
@domaindrivendev Even with the validatorurl set to null I still get an NRE.

![image](https://user-images.githubusercontent.com/1130210/36633361-30c07dcc-1962-11e8-9881-03293cb29ab4.png)

**Comment by domaindrivendev** [comment]
I can’t repro this so very difficult to troubleshoot with just the info you’re providing. Can you get a stack trace or better still, pull down SB and debug locally

**Comment by buvinghausen** [comment]
It must be something wonky in our repository. I just put together an example project to test out the NodaTime Swashbuckle settings with v2 and make sure they still work as expected.

[No Issues Here](https://github.com/buvinghausen/Swashbuckle.NodaTime.AspNetCore/tree/master/example/Web)

**Comment by alexxie** [comment]
app.UseSwaggerUI(c => c.SwaggerEndpoint("v1/swagger.json")) works for me via:

http://localhost:xxxx/swagger or 
http://localhost:xxx/appname/swagger

**Comment by bhavik-gandhi** [comment]
Was able to solve the problem by 
c.CustomSchemaIds(x => x.FullName);

**Comment by marekpetak** [comment]
Agree with @alexxie. Using only `app.UseSwaggerUI(c => c.SwaggerEndpoint("v1/swagger.json"))` seems to fix the problem even if deploying in VirtualDirectory on IIS, it look like this does not need to be set anymore ...
Using NET Core 2.1 and Swashbuckle.AspNetCore 3.0.0

**Comment by VictorioBerra** [comment]
@marekpetak I am using the same versions and I do not have a `SwaggerEndpoint` function that only takes a single argument like that.

**Comment by alexxie** [comment]
@marekpetak is right, SwaggerEndpoint needs the second parameter which is just a name.

**Comment by hack2root** [comment]
I disagree that relative SwaggerEndpoint paths does not work, this is correct way to use it:
`
	public static class Extensions
	{
		public static void UseSwaggerRoute(
			this IApplicationBuilder app,
			IApiVersionDescriptionProvider provider,
			string clientId = null,
			string clientSecret = null)
		{
			app.UseSwagger();
			app.UseSwaggerUI(__options =>
			{
				foreach (var versionDescription in provider.ApiVersionDescriptions)
				{
					__options.SwaggerEndpoint($"../{__options.RoutePrefix}/{versionDescription.GroupName}/swagger.json", versionDescription.GroupName.ToUpperInvariant());
				}
				if (!string.IsNullOrEmpty(clientId) && !string.IsNullOrEmpty(clientSecret))
				{
					__options.OAuthClientId(clientId);
					__options.OAuthClientSecret(clientSecret);
				}
			});
		}
	}
`

**Comment by macoratti** [comment]
In ASP .NET 3.0 using the package Swashbuckle.AspNetCore 5.0.0-rc2 just add:

 c.AddSecurityDefinition("bearer", new OpenApiSecurityScheme
  {
                    In = ParameterLocation.Header,
                    Description = "Json Web Token (JWT) - \"Bearer {token}\"",
                    Name = "Authorization",
                    Type =  SecuritySchemeType.ApiKey
                });

And it's works fine.
