### ISSUE TITLE
Documentation for SwaggerSchemaFilter attribute?

### ISSUE THREAD

**Issue by VictorioBerra** [domaindrivendev/Swashbuckle.AspNetCore#606]
I noticed `SwaggerSchemaFilterAttribute` being used in a sample API online. When I tried to google for it I only found the code here on GitHub.

I ctrl+f the docs here and i saw info on  `ISchemaFilter` but nothing on passing your instance to `SwaggerSchemaFilter` like `[SwaggerSchemaFilter(typeof(SaveCarSchemaFilter))]`. This appears to live in `Swashbuckle.AspNetCore.SwaggerGen` so I am sure its just new.

Could we please add an example of this to the docs?

**Comment by domaindrivendev** [comment]
Sounds like you’re volunteering to create a PR :)
