### ISSUE TITLE
How to bypass Available authorizations screen?

### ISSUE THREAD

**Issue by patnolan** [domaindrivendev/Swashbuckle.AspNetCore#607]
When I click the Authorize Button I get the "Available authorizations" dialog for selecting the scope(s) as ecpected. The available scopes are defined in code via AddSecurityDefinition.

However, I would like to bypass this dialog and have the scopes automatically selected. If you have 8 or 10 scopes to check everytime you authorize it can become quite annoying in a dev environment. Could anyone advise how to do this or even provide the necessary code\config?

Thanks heaps!

**Comment by domaindrivendev** [comment]
Please post this to the [swagger-ui project](https://github.com/swagger-api/swagger-ui). Thanks
