### ISSUE TITLE
Auto discover RedirectUrl Hostname?

### ISSUE THREAD

**Issue by patnolan** [domaindrivendev/Swashbuckle.AspNetCore#610]
Hi,

I'm setting the RedirectUrl using OAuth2RedirectUrl via the UseSwaggerUI method.

`c.OAuth2RedirectUrl("http://hostname:12661/swagger/oauth2-redirect.html");`

If I don't do this it defaults to localhost:3200.

All the samples I've come across has the hostname and port hardcoded as above. However, for obvious reasons a hardcoded value is no good for a prod environment. I would also rather not get this value from a config file.

Can anyone offer any suggestions how I can auto discover the hostname and port?

**Comment by domaindrivendev** [comment]
The only approach I can think of right now would be to use a custom version of `index.html`, described in the [readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-indexhtml). There, you can use `window.location` to discover the full redirect url, and pass it to the swagger-ui component:

```javascript
<script>
  window.onload = function () {
    var configObject = JSON.parse('%(ConfigObject)');
    var oauthConfigObject = JSON.parse('%(OAuthConfigObject)');

    // Apply mandatory parameters
    configObject.dom_id = "#swagger-ui";
    configObject.presets = [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset];
    configObject.layout = "StandaloneLayout";

    // Discover and assign OAuth2 redirect URL
    configObject.oauth2RedirectUrl = window.location + "oauth2-redirect.html";

    // Build a system
    const ui = SwaggerUIBundle(configObject);

    // Apply OAuth config
    ui.initOAuth(oauthConfigObject);
  }
</script>
```

**Comment by mantasaudickas** [comment]
Any plans to fix this? 
It worked with 1.x version on multiple environments without any additional configuration.
And now to maintain custom index.html does not look like very good solution.

**Comment by Razzeee** [comment]
Just here to say @domaindrivendev suggestion works for me. But yes, it's not the a good solution.
One thing I read over at the swagger ui site is that you should be able to set the url and port in your swagger file. But that's also a nogo for me, as I have to deploy this on multiple devices without changing a config file and entering the server url.

**Comment by domaindrivendev** [comment]
@Razzeee - see 893aa299547207fc74455399ec4292bd8aa8902f. Adds the host-aware, built-in default, so you don't have to.

**Comment by patricknolan** [comment]
Hi @domaindrivendev does that mean if I upgrade to Swashbuckle.AspNetCore 2.1.0 it should work like 1.x and be auto host-aware?

I've updated and it still tries to redirect to "http://localhost:3200/oauth2-redirect.html"

**Comment by Razzeee** [comment]
I think that's targeting anything greater than 2.1.0 not 2.1.0 itself.

**Comment by patricknolan** [comment]
Hey @Razzeee 2.1.0 is the latest version of Swashbuckle.AspNetCore. I don't think there is anything newer. I'm assuming the fix included in changeset [893aa29](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/893aa299547207fc74455399ec4292bd8aa8902f) was deployed with nugget package 2.1.0?

**Comment by Razzeee** [comment]
@patnolan 
No, check the tag here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commits/v2.1.0
I would be surprised if that was included in the nugget package. Anyway the changeset itself also confused me with the 2.1.0-beta-X stuff.

**Comment by patricknolan** [comment]
Thanks @Razzeee 

I wonder if anyone knows when the change will be available? This is a pretty big issue for us as we're deploying Swagger to so many environments.

**Comment by domaindrivendev** [comment]
2.1.1 build is baking and we speak. Should be available on Nuget shortly ...

**Comment by patricknolan** [comment]
Hey @domaindrivendev I've upgraded to Swashbuckle.AspNetCore 2.1.1 and my API loads but nothing is displayed.

I created a simple test api with Swashbuckle and it has the same issue (see attached). If I revert the test project back to 2.1.0 it works.

Is there something we need to do after upgrading to 2.1.1 for swagger to display?

[SwaggerTest.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/1769859/SwaggerTest.zip

**Comment by patricknolan** [comment]
Hi @domaindrivendev are you able to confirm if release Swashbuckle.AspNetCore 2.1.1 is broken?

**Comment by domaindrivendev** [comment]
Please try 2.2.0

**Comment by patricknolan** [comment]
Hi @domaindrivendev I can confirm that's fixed the issue. 

Thanks heaps!

**Comment by kambleaa007** [comment]
> Hi @domaindrivendev I can confirm that's fixed the issue.
> 
> Thanks heaps!

How this solved, i cant see array of string which can take all dev qa prod local environments
