### ISSUE TITLE
 JWT Bearer Authorization error

### ISSUE THREAD

**Issue by lilinghui** [domaindrivendev/Swashbuckle.AspNetCore#611]
the version 2.0.0 can't add [JWT Bearer Authorization] , version 1.2.0 is fine.

**Comment by domaindrivendev** [comment]
Please provide more detail. The supported schemes in Swagger 2.0 are "oauth2", "apiKey" and "basic", and these are tested and working in SB 2.0.0. What exactly are you trying to do? Include example code

**Comment by domaindrivendev** [comment]
Also, see #603

**Comment by lilinghui** [comment]
yes same as #603
