### ISSUE TITLE
2.x release notes?

### ISSUE THREAD

**Issue by memark** [domaindrivendev/Swashbuckle.AspNetCore#612]
Both versions 2.0 and 2.1 seem to be released (without any prerelease tag).  There seems to be some breaking changes (since my code doesn't compile :)). Are there any release notes for these versions?

**Comment by domaindrivendev** [comment]
There shouldn't be breaking changes. Can you elaborate on your compilation errors?

**Comment by domaindrivendev** [comment]
Sorry I misinterpreted your question. There are breaking changes between 1.x and 2.0.0. I'll add some release notes.

**Comment by domaindrivendev** [comment]
Release notes added for 2.0.0 and 2.10. It's also worth noting that SB follows [semantic versioning](https://semver.org/) so you can typically expect breaking changes with any major upgrade.

**Comment by memark** [comment]
Thanks for your quick response @domaindrivendev!
