### ISSUE TITLE
Not passing authroization header with requests for client credential (application) flow

### ISSUE THREAD

**Issue by ajtowf** [domaindrivendev/Swashbuckle.AspNetCore#613]
For version 2 and up when configuring oauth2 client credientials flow the access_token isn't passed along with the requests as an authroization header.

Configured as follows: 

    services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "Some API", Version = "v1" });

                c.AddSecurityDefinition("OpenId Connect", new OAuth2Scheme
                {
                    Type = "oauth2",
                    Flow = "application",

                    TokenUrl = "http://localhost:5000/connect/token",
                    AuthorizationUrl = "http://localhost:5000/connect/authorize",

                    Scopes = new Dictionary<string, string>
                    {
                        { "some.api", "API Scope" }
                    }
                });
            });

UI manages to sign in, access_token is issued, UI says we're logged in, but all requests gets denied (401) since the access token isn't passed along.

Just downgrading the version to 1.2 makes it work as expected without any configuration changes.

Love the new look and feel guys, awesome work!

**Comment by domaindrivendev** [comment]
Please have a read through #603 as I think it may be related.

**Comment by ajtowf** [comment]
Thanks @domaindrivendev, adding a DocumentFilter did the trick, didn't know that was required and I've been using swagger for quite some time :-)
