### ISSUE TITLE
Token not added to request

### ISSUE THREAD

**Issue by statler** [domaindrivendev/Swashbuckle.AspNetCore#614]
According to all the info I have read, I should be able to get my token added to every request from the UI by doing something like this;

```
services.AddSwaggerGen(c =>
            {

                c.SwaggerDoc("v2", new Info
                {
                    Version = "v2",
                    Title = "Mobile API",
                });

                c.AddSecurityDefinition("Bearer", new ApiKeyScheme()
                { In = "header", Description = "Please insert JWT with Bearer into field", Name = "Authorization", Type = "apiKey" });
                
                // Set the comments path for the Swagger JSON and UI.
                var basePath = AppContext.BaseDirectory;
                var xmlPath = Path.Combine(basePath, "cpDataCore.xml");
                c.IncludeXmlComments(xmlPath);
            });
```

I get the authorize prompt and can enter the token into it no problems, but the token isn't added to any of the requests. What am I missing?

P.S I can add a parameter with the token manually using the OperationFilter without problems, so it isnt an issue with the tokens.

**Comment by joakimhew** [comment]
Duplicate of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/603
Have a look at domaindrivendev's comment regarding IDocuments in in that issue

**Comment by ajtowf** [comment]
Just wrote the same bug report yesterday https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/613 and solved it by looking at https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/603

But clearly it's not obvious that a DocumentFilter is needed, it feels a bit clunky imho, nevertheless it solves the problem. Maybe they should consider a re-design to simplify this?

**Comment by domaindrivendev** [comment]
@ajtowf - agreed that it's a little more clunky than it ought to be. But, I'll contend that it's partly due to the [Swagger Spec.](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityRequirementObject), and not Swashbuckle directly, because it requires you to a) define your security scheme and b) declare which operations each scheme is applicable to.

Essentially, that's exactly what #603 suggests. I don't want to create additional abstractions on top of the spec (that's not the goal of SB). But, I could certainly make the second step a little easier, perhaps providing an `AddSecurityRequirement` method for applying schemes globally, rather than requiring the use of a `DocumentFilter`

**Comment by statler** [comment]
Yes. That's the money shot.

```
                c.AddSecurityDefinition("Bearer", new ApiKeyScheme()
                { In = "header", Description = "Please insert JWT with Bearer into field", Name = "Authorization", Type = "apiKey" });
                c.DocumentFilter<SecurityRequirementsDocumentFilter>();
```

```
using Swashbuckle.AspNetCore.Swagger;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Collections.Generic;

namespace cpDataCore
{
    internal class SecurityRequirementsDocumentFilter : IDocumentFilter
    {
        public void Apply(SwaggerDocument document, DocumentFilterContext context)
        {
            document.Security = new List<IDictionary<string, IEnumerable<string>>>()
            {
                new Dictionary<string, IEnumerable<string>>()
                {
                    { "Bearer", new string[]{ } },
                    { "Basic", new string[]{ } },
                }
            };
        }
    }
}
```

Cheers

**Comment by domaindrivendev** [comment]
See #616 to simplify this a little more
