### ISSUE TITLE
Upgrade breaks apiKey inclusion in header (v1.2.0 -=> v2.1.0)

### ISSUE THREAD

**Issue by dudleycodes** [domaindrivendev/Swashbuckle.AspNetCore#617]
Using ApIKeyScheme for JWT works great in swashbuckle 1.2.0; here's my setup:

```
services.AddSwaggerGen(c =>
{
    // ....
    c.AddSecurityDefinition("apikey", 
        new ApiKeyScheme
        {
            Description = "JWT Authorization header using the Bearer scheme. Example: \"bearer {token}\"",
            Name = "Authorization",
            In = "header",
            Type = "apiKey"
        });
});
```

## Working (version 1.2.0)
Authorize button is added to the header

![header](https://user-images.githubusercontent.com/12804982/36735379-b009c4d6-1b9b-11e8-8862-b473e8e8119b.jpg)

Clicking authorize button brings up dialog to add bearer to header:

![auth](https://user-images.githubusercontent.com/12804982/36735464-e5b36826-1b9b-11e8-82b9-d928334d6220.jpg)

After authorizing header bearer token is included in all try requests as seen by the example curl statement:

![working curl](https://user-images.githubusercontent.com/12804982/36735559-1f5400b8-1b9c-11e8-9bbb-0804272efce9.jpg)

## Broken (Version 2.1.0)

After upgrading the authorize button is still there

![new auth](https://user-images.githubusercontent.com/12804982/36736043-37399ae8-1b9d-11e8-9503-323240bef3f8.jpg)

And it still pops up the dialog allowing us to add token to header

![new dialog](https://user-images.githubusercontent.com/12804982/36736130-63d0e73c-1b9d-11e8-98b8-cff2298ade49.jpg)

But header is not included on any try requests as seen by its absence from the example curl statements:

![untitled](https://user-images.githubusercontent.com/12804982/36736162-7f53eca2-1b9d-11e8-88df-0ed9875dfe1f.jpg)

Confirmed the issues also occurs with version 2.0.0

**Comment by domaindrivendev** [comment]
Dup of #603. In fact, the previous version was the one behaving incorrectly

**Comment by domaindrivendev** [comment]
Also, I would suggest reading through this (updated) section of the docs - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#add-security-definitions-and-requirements
