### ISSUE TITLE
Cannot access Swagger UI in test projects

### ISSUE THREAD

**Issue by LEsperanca** [domaindrivendev/Swashbuckle.AspNetCore#620]
When i run the test sites the swagger-ui does not show. It fails to load the resources.
Index.html loads to js scripts that are not bundled in dll.

`<script src="./swagger-ui-bundle.js"> </script> 
<script src="./swagger-ui-standalone-preset.js"> </script>`

**Comment by domaindrivendev** [comment]
Before building, you need to run “bower install” at the root of the SwaggerUI project to pull down and embed front end assets.

FWIW, I’ve found the use of bower in this case to be more hassle than it’s worth and am likely just going to revert to checking the assets directly into the repo
