### ISSUE TITLE
Regular expression for Guid parameters is failing

### ISSUE THREAD

**Issue by chriscichocki** [domaindrivendev/Swashbuckle.AspNetCore#623]
When the Swagger UI runs, it uses the javascript file "swagger-ui-bundle.js".  The script defines a function "validateguid" which uses the regular expression:

^[{(]?[0-9a-f]{8}-[0-9a-f]{4}-**[1-5][0-9a-f]{3}**-**[89ab][0-9a-f]{3}**-[0-9a-f]{12}[)}]?$

This mandates that the 3rd segment starts with the numbers 1-5, and the 4th segment begins with 8, 9, a or b.  However Microsoft doesn't have such a restriction when they create Guid values, which is resulting in what appears to be a false negative test on many of our Guid's.

Looking at the "original" swagger-api/swagger-ui repository, the regular expression test that they use is in their javascript file 'src/core/util.js' is as follows:

^[{(]?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[)}]?$

It seems the regular expression in Swashbuckle.AspNetCore was changed or added with the version 2 release.  Can this be changed to use the same regular expression test as swagger-ui?

We use Swashbuckle in all our API projects, so thank you for publishing your work.  It is greatly valued!

**Comment by chriscichocki** [comment]
I didn't realize you were including the 'redistributable' for swagger-ui.  They made the change v3.2.2 that added the validation check.  I'll request an update to their code base.

**Comment by chriscichocki** [comment]
I'm going to reopen the issue because I can't seem to identify where the 'swagger-ui-bundle.js' file is actually being loaded from at runtime.

I've downloaded the swagger-api/swagger-ui repository and looked at their 'swagger-ui-bundle.js' file which is in the 'swagger-ui-master/dist' folder.  It contains the correct regular expression for Guid's.  

In fact, I've downloaded this repository and looked at the 'Swashbuckle.AspNetCore.SwaggerUI' project, which has a 'node-modules/swagger-ui-dist' folder, and the 'swagger-ui-bundle.js' file ALSO has the correct regular expression for Guid's.  

That leaves me wondering, where does the regular expression that I'm seeing at runtime actually come from?

**Comment by chriscichocki** [comment]
After more digging, this definitely seems like a bug.

When I run the sample "Basic" website in the Swashbuckle.AspNetCore solution, it runs correctly.  The files Swagger-UI are loaded from the 'Swashbuckle.AspNetCore.SwaggerGen' assembly.  The name of the resource for the 'swagger-ui-bundle.js' file is: 

Swashbuckle.AspNetCore.SwaggerUI.node_modules.swagger_ui_dist.swagger-ui-bundle.js

..and it has the correct regular expression for validating Guid's.

However, when I run my own project using the latest NuGet package 2.1.0, the files are again loaded from the 'Swashbuckle.AspNetCore.SwaggerGen' assembly, but the name of the resource for the 'swagger-ui-bundle.js' file is:

Swashbuckle.AspNetCore.SwaggerUI.bower_components.swagger_ui.dist.swagger-ui-bundle.js

Unfortunately, that version of the file does not have the correct regular expression in it.

So my guess is there was a recent change from pulling the package for 'swagger-ui' from bower to npm, and the NuGet package that is being distributed is bundling in an older version of swagger-ui as a result.

**Comment by domaindrivendev** [comment]
Nuget releases are behind master. But, a 2.1.1 build, which I believe to have the changes you’re looking for, is baking as we speak. Should be available on Nuget shortly

**Comment by chriscichocki** [comment]
Awesome.  Thanks for the update!
