### ISSUE TITLE
Basic Auth : Breaking change between 1.2.0 and 2.0.0

### ISSUE THREAD

**Issue by DomZZ** [domaindrivendev/Swashbuckle.AspNetCore#626]
I have a working API that use version 1.1.0 and basic authentication, Authorize button set correctly the header.
Then I've upgraded to 2.0.0 (same on 2.1.0), and with the same setup, the authorize button doesn't set anything and then my basicauthentication middleware is not working at all.

Here is my startup class 
`        public virtual void ConfigureServices(IServiceCollection services)
        {
            services
                .AddCors()
                .AddMvc()
                .AddJsonOptions(options =>
                {
                    options.SerializerSettings.Converters.Add(new StringEnumConverter());
                    options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
                    options.SerializerSettings.Formatting = Formatting.Indented;
                });
            services.Configure<FormOptions>(options =>
            {
                options.ValueLengthLimit = int.MaxValue;
                options.MultipartBodyLengthLimit = int.MaxValue; // In case of multipart
            });

            services.Configure<StartupConfig>(Configuration);

            // Register the Swagger generator, defining one or more Swagger documents
            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new Info { Title = "APM API" });

                //options.IncludeXmlComments(swaggerCommentXmlPath); //Includes XML comment file
                options.OperationFilter<FileOperation>();
                options.DescribeAllEnumsAsStrings();
                options.AddSecurityDefinition("basic", new BasicAuthScheme { Type = "basic" });
            });

            OnConfigureServices(services);
        }

        public virtual void OnConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMiddleware<ExceptionHandlerMiddleware>();

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            app.UseCors(options => options.AllowAnyOrigin().AllowAnyMethod());

            // Enable middleware to serve swagger-ui (HTML, JS, CSS etc.), specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                //c.RootUrl(req => req.RequestUri.GetLeftPart(UriPartial.Authority) + VirtualPathUtility.ToAbsolute("~/").TrimEnd('/'));
                c.RoutePrefix = "Help";
                c.DisplayRequestDuration();
                c.DocumentTitle = "APM Api";
                c.SwaggerEndpoint("../swagger/v1/swagger.json", "APM API");
            });
            
            app.UseMiddleware<BasicAuthenticationMiddleware>();

            app.UseMvc();
        }
    }`

And my basic auth middleware
`
    public class BasicAuthenticationMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly IAuthenticationService _authentication;

        public BasicAuthenticationMiddleware(RequestDelegate next, IAuthenticationService authentication)
        {
            _next = next;
            _authentication = authentication;
        }

        public async Task Invoke(HttpContext context)
        {
            if (context.Request.Path.ToString().Contains("/ClientDownload") ||
                context.Request.Path.ToString().Contains("/Help") ||
                _authentication.IsAuthenticationHeaderValid(context, out var username, out var password))
                await _next(context);
            else
            {
                var apiEx = new ApiException().Error(Interface.ErrorCode.AuthenticationFailed).AddMessage($"Authentication failed with following credentials (login [{username}], password [{password}])!");
                apiEx.ErrorCode = 401;

                throw apiEx;
            }
        }
    }
`
`        public bool IsAuthenticationHeaderValid(HttpContext context, out string login, out string pwd)
        {
            var basicAuthenticationHeader = **context.Request.Headers["Authorization"]**
                .FirstOrDefault(header => header.StartsWith("Basic", StringComparison.OrdinalIgnoreCase));

            (string username, string password) = _basicHeader.TryDecodeHeaderValue(basicAuthenticationHeader);
            login = username;
            pwd = password;

            if (!string.IsNullOrWhiteSpace(username) && !string.IsNullOrWhiteSpace(password))
            {
                var hashPassword = _hashPassword.EncodePassword(password);

                var account = _platform.Accounts.FirstOrDefault(_ => _.Username == username);
                if (account != null && account.Password.Equals(hashPassword) && (account.IsPlatformAdmin ?? false))
                    return true;
            }

            return false;
        }`

The problem is that context.Request.Headers["Authorization"] is empty.

**Comment by RainingNight** [comment]
+1

**Comment by domaindrivendev** [comment]
Dup of #603
