### ISSUE TITLE
2.0.0 RelativeURL "Try it now button" (Question)

### ISSUE THREAD

**Issue by ltraus** [domaindrivendev/Swashbuckle.AspNetCore#630]
I got a change out recently that made it so i can use a relative URL through nginx, but the issue i'm having is the "try it now" button.

![image](https://user-images.githubusercontent.com/5386554/36911189-01c10346-1e00-11e8-9105-a68ff83e53e4.png)

But the top URL is.

![image](https://user-images.githubusercontent.com/5386554/36911256-352cc72e-1e00-11e8-80eb-c6cb4524fcb9.png)

The application is routed in by /_api/auth/, so is there a magic incantation for the try it now button to get the relative properly as well? I thought i found it in the spec for swagger ui; but its' not working so much.

https://github.com/swagger-api/swagger-js/issues/532

Is the swagger feature that they talk about a while ago.

**Comment by domaindrivendev** [comment]
It's not clear to me what your exact issue is. Can you just describe the exact behavior you're looking for using example URLs?

**Comment by ltraus** [comment]
https://URL/_api/auth/swagger/

Created by:

   location /_api/auth/ {
            proxy_redirect off;
            proxy_pass http://authorization/;
            proxy_set_header Host $host;
        }

When i access the swagger; I hit try it now on the first endpoint.

Current: curl -X GET "https://URL/v1/features" -H "accept: application/json"
Expected: curl -X GET "https://URL/_api/auth/v1/features" -H "accept: application/json"

**Comment by domaindrivendev** [comment]
You need to set `SwaggerDocument.BasePath` to "api". You can do this with a simple Document Filter. See [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#document-filters) for the low down.
