### ISSUE TITLE
Non Json request bodies are not detected in version 2.2.0

### ISSUE THREAD

**Issue by clawrenceks** [domaindrivendev/Swashbuckle.AspNetCore#633]
In version 2.2.0 of Swashbuckle the 'Parameter Content Type' dropdown box only contains 'application/json' regardless of what is set using the Consumes attribute for the action. The swagger.json file however does contain the correct values in consumes[].

This would appear to be due to a swagger-ui regression detailed [here](https://github.com/swagger-api/swagger-ui/issues/4257) that has now been fixed in Swagger UI version 3.12.0

It looks like version 2.2.0 of Swashbuckle is using Swagger UI version 3.11.0, as when I downgrade to version 2.1.0 of Swashbuckle, which according to the release notes is using 3.10.0 of Swashbuckle, the issue does not occur.

I realise this is a Swagger-UI issue, logging here simply to raise awareness and also for tracking purposes.

**Comment by domaindrivendev** [comment]
Updated to 3.12.0 with the following commit - cc968d2a40835a3f9aef76a40e2cce75fddee211. You can try it out now by pulling the latest preview package from [myget.org](https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore). I'll be publishing an official release to nuget.org in the next week or so.

**Comment by renanmt** [comment]
any chances of seeing this in nuget?
