### ISSUE TITLE
Resfresh the page raise an unhandled exception with a custom index.html(2.2.2)

### ISSUE THREAD

**Issue by abosquet** [domaindrivendev/Swashbuckle.AspNetCore#636]
Error:
An unhandled exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.dll
Stream was not readable

Repro steps
1. Add an index.html page in the project.
2. Add app.UseSwaggerUI(c =>
{
    c.IndexStream = () => GetType().GetTypeInfo().Assembly
        .GetManifestResourceStream("{namespace}.index.html");
});
3. Start the project
4. The new layout work as expected and I can navigate with no problem
5. Refresh the page from the browser
6. The web application crash

**Comment by domaindrivendev** [comment]
I can't repro making it almost impossible to troubleshoot. To assist, could you create a fresh project and try repro from scratch?

**Comment by abosquet** [comment]
[Repro.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/1818904/Repro.zip)
Sorry for the delay. I attached a small Repro Project.

Repro steps:
1. Start the Project
2. Refresh the swagger page from the browser

Here is the full stack:
ArgumentException: Stream was not readable.
System.IO.StreamReader..ctor(Stream stream, Encoding encoding, bool detectEncodingFromByteOrderMarks, int bufferSize, bool leaveOpen)
System.IO.StreamReader..ctor(Stream stream)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware+<RespondWithIndexHtml>d__5.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware+<Invoke>d__3.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

Thanks for your support!
And by the way you did a fantastic job! Swashbuckle is awesome!

**Comment by domaindrivendev** [comment]
Replace the following lines:

```csharp
var stream = GetType().GetTypeInfo().Assembly.GetManifestResourceStream("CoreWebApi.index.html");
c.IndexStream = () => stream;
```

with ...

```csharp
c.IndexStream = () => GetType().GetTypeInfo().Assembly.GetManifestResourceStream("CoreWebApi.index.html");
```

By creating the stream outside of the lambda, you're creating a long lived stream that's instantiated once and used for every request. This isn't going to work - it needs to be recreated every time the page is requested
