### ISSUE TITLE
Authorize Button shows for non-auth WebApi

### ISSUE THREAD

**Issue by nzain** [domaindrivendev/Swashbuckle.AspNetCore#637]
First off, I'm not sure if this is a bug in the Swashbuckle configuration made through this repo or if it is somewhere in swagger-UI's javascript (appologies, if this is the case). The only information I could find about my issue is "the auth button should not show, if no security definitions are specified". Any directions are welcome!

**Reproduce**
In Visual Studio create a new empty WebApi project.
Add the nuget package `Swashbuckle.AspNetCore` (version 2.2.0 at the time of writing).
Add the basic swagger doc generator to the services and enable swagger in the Configure callback. The full code example is shown below.

**Expected Behavior**
The swagger-UI does not show the Authorize button.

**Actual Behavior**
The Authorize button is shown, click opens an empty list.

**Sample Code**

    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info {Version = "v1", Title = "some title"}); 
                c.DescribeAllEnumsAsStrings();
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Some API V1");
                c.RoutePrefix = "api"; // http://localhost:5000/api/
                c.SupportedSubmitMethods(); // none: disable the "Try it out" buttons
            });

            app.UseMvc();

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }

**Comment by nzain** [comment]
related, but doesn't have much information: https://github.com/swagger-api/swagger-ui/issues/3816

**Comment by domaindrivendev** [comment]
This should be resolved by the following commit - 5acec5f7b16ca48e29076dfcbecf744cba47eb81. You can try it out now by pulling the latest preview package from [myget.org](https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore). I'll be publishing an official release to nuget.org in the next week or so.

**Comment by nzain** [comment]
Great, problem resolved. Thanks for your quick help!
