### ISSUE TITLE
Setting default JsonSerializerSettings Formatting.Indented stops UI from loading

### ISSUE THREAD

**Issue by lkurth** [domaindrivendev/Swashbuckle.AspNetCore#639]
Using ASP.NET Core 2. If the JsonConvert.DefaultSettings included Formatting.Indented, the Swagger UI will not load. Simply remove that setting and it work correctly. This is new behavior with Swashbuckle 2.2.0 (maybe any 2.x.x). I had a project that was working correctly using 1.1.0. I upgraded to 2.2.0 and it stopped working.

It took a while to track down the issue. But once found, I was able to create a clean project that exhibits the incorrect behavior. It is attached. I create a new Core Web API project and then added Swashbuckle. The only changes I made were to the Startup class, and I changed the launch path in the project properties.

As is, the attached project will exhibit the bug behavior. Comment out line 37 in Startup and it will work correctly.
[SwashbuckleTest.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/1786045/SwashbuckleTest.zip)

**Comment by domaindrivendev** [comment]
I think #618 will resolve this. Just waiting to tie up some lose ends around implementation. Will push it forward ASAP as this is a glaring bug

**Comment by lkurth** [comment]
Thanks @domaindrivendev!!

I probably should have found #618 and not logged a new bug. I did a search but came up empty. Just not quite the right search terms. It definitely appears to be the same issue.

**Comment by domaindrivendev** [comment]
This should be resolved by the following commit - 21deb49cfa133fdc051df91ad6d12d03d626145a. You can try it out now by pulling the latest preview package from [myget.org](https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore). I'll be publishing an official release to nuget.org in the next week or so.

**Comment by lkurth** [comment]
Tested. It's fixed! Thanks for the update!
