### ISSUE TITLE
1.1.0 to 2.2.0  - IDocumentFilter after authentication

### ISSUE THREAD

**Issue by Janidbest** [domaindrivendev/Swashbuckle.AspNetCore#641]
It may be a bug or implementation may have to change dependending on the design changes.

**In short - IDocumentFilter apply after authentication ( which is not kicking at the moment, because the response stays back in the popup without hitting the server)**

We have IDocumentFilter which hides the unauthorized enpoints, if user authenticates ( oauth - OAuth2SecurityRequirement - IOperationFilter), the call to IDocumentFilter is now not working. 

It may be due to the fact the login in 2.2.0 is async and the page load is not triggering so IDocumentFilter Apply.

The same was different with 1.1.0. So we were able to hide/show the methods that we want to on the swagger document.

IDocumentFilter implementation is 

`public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
        {
            // Prevent IE caching of Swagger.json file
            _httpContext.HttpContext.Response.Headers.Append("Cache-Control", new string[] { "no-store" });
           var authenticated = _httpContext.HttpContext.User.Identity.IsAuthenticated;
            //TODO context user is null, need to fix the authentication
            if (!authenticated)
            {
                foreach (var values in swaggerDoc.Paths.Values)
                {
                    var nullifyThese = new List<Operation>();
                    foreach (var operation in values.EnumerateOperations())
                    {
                        if (operation != null && operation.Security?.Count > 0)
                            nullifyThese.Add(operation);
                    }
                    values.NullifyOperations(nullifyThese);
                }
            }
        }`

Also the IsAuthenticated is always false !!. Swagger document always showing "Authorize" button. I assume once authorized that should disappear or transform into Logout. 

having said that, the authorize is been satisfied on tryout by passing the bearer. However IDocumentFilter and UI is thinking its not authenticated.

**Comment by domaindrivendev** [comment]
The following article describes the best approach that I'm aware of, to protect access the swagger JSON/swagger-ui:

https://stackoverflow.com/questions/46775629/asp-net-core-2-0-authenticate-a-route-without-a-controller
