### ISSUE TITLE
NotSupportedException: Ambiguous HTTP method for action - SednaCloud.API.Controllers.ArticoliCalibriController.GetByCodice (SednaCloud). Actions require an explicit HttpMethod binding for Swagger 2.0

### ISSUE THREAD

**Issue by brux88** [domaindrivendev/Swashbuckle.AspNetCore#643]
hi, i tried this package, but shoe me this error:

`An unhandled exception occurred while processing the request.
NotSupportedException: Ambiguous HTTP method for action - SednaCloud.API.Controllers.ArticoliCalibriController.GetByCodice (SednaCloud). Actions require an explicit HttpMethod binding for Swagger 2.0
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable<ApiDescription> apiDescriptions, ISchemaRegistry schemaRegistry)

Stack Query Cookies Headers
NotSupportedException: Ambiguous HTTP method for action - SednaCloud.API.Controllers.ArticoliCalibriController.GetByCodice (SednaCloud). Actions require an explicit HttpMethod binding for Swagger 2.0
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable<ApiDescription> apiDescriptions, ISchemaRegistry schemaRegistry)
System.Linq.Enumerable.ToDictionary<TSource, TKey, TElement>(IEnumerable<TSource> source, Func<TSource, TKey> keySelector, Func<TSource, TElement> elementSelector, IEqualityComparer<TKey> comparer)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(string documentName, string host, string basePath, String[] schemes)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`

this is my method:
`[Authorize(Policy = "CanAccessTenant")]
        [Route("getByCodice/{codice}")]
        [HttpGet(Name = "getByCodiceArticoliCalibri")]
        public ActionResult GetByCodice(string codice)
        {
            try
            {
                _logger.LogInformation("Ricerca");
                var result = _repo.GetByCodice(codice);
                if (result != null)
                {
                    return Ok(result);
                }
                _logger.LogWarning("Non posso salvare ArticoliCalibri  nel db");
                return NotFound(ValidationError.RitornoValore(nameof(ArticoliCalibri) + _sharedLocalizer[$"NON_TROVATO"] + $": {codice}"));
            }
            catch (Exception ex)
            {
                _logger.LogError($"Errore Interno : {ex}");
            }

            return BadRequest(ValidationError.RitornoValore(_sharedLocalizer["ERRORE_INSERIMENTO"]));
        }
`

if i replace [HttpGet(Name = "getByCodiceArticoliCalibri")] with [HttpGet] work, but i need  [HttpGet(Name = "getByCodiceArticoliCalibri")]

**Comment by domaindrivendev** [comment]
Swashbuckle leverages the `ApiDescriptions` that are surfaced by ASP.NET Core's built-in API metadata layer to drive the Swagger generation. I'm not sure why, but the combination you've shown results in an `ApiDescription` with `HttpMethod = null`.

With that said, if you just combine your route declaration into a single HttpGetAttribute that includes the template (see below), you won't have this issue. Plus the code looks cleaner!

```csharp
[Authorize(Policy = "CanAccessTenant")]
[HttpGet("getByCodice/{codice}", Name = "getByCodiceArticoliCalibri")]
public ActionResult GetByCodice(string codice)
```

**Comment by brux88** [comment]
thank, you have a right, but now i have another error. if i run: http://localhost:6000/swagger/v1/swagger.json i see the json and work, but if i run http://localhost:6000/swagger/  i see this error:
![2018-03-10_1217](https://user-images.githubusercontent.com/3495339/37241655-1697271a-245d-11e8-93fd-f5c4f802061b.png)
