### ISSUE TITLE
Issue with HybridAndClientCredentials grant type.

### ISSUE THREAD

**Issue by enriketrujillo** [domaindrivendev/Swashbuckle.AspNetCore#645]
Hi Im using IdentityServer 4 with the HybridAndClientCredentials grant type. In swagger the clientCredentials flow is working fine but authorizationCode isn't because id_token is missing in the response_type. Is there a way to solve that issue?
Thanks

**Comment by domaindrivendev** [comment]
SB leverages the swagger-ui but doesn’t maintain it. As per the contribution guidelines, this should be posted to that repo instead

**Comment by vanillajonathan** [comment]
When using the `ClientCredentials` grant type ("client_credentials"), the `response_type` query parameter is not passed. Which results in an invalid request.
