### ISSUE TITLE
SwaggerGen emits enum [FromQuery] parameter value list as 'null', 'null' if [EnumMember] is set

### ISSUE THREAD

**Issue by daerhiel** [domaindrivendev/Swashbuckle.AspNetCore#646]
Hi all, seems there's a bug in v2.2.0 SwaggerGen.

I have the following API definition:
```
[HttpPost("{scope}/{name}")]
public async Task<Agent> Create([FromRoute]string scope, [FromRoute]string name, [FromQuery]AgentState? state = null)
```
where AgentState is
```
    [DataContract]
    public enum AgentState
    {
        [EnumMember]
        Inactive,

        [EnumMember]
        Active
    }
```

and it causes to generate swagger.json having nulls as enum value names
```
/api/Agents/{scope}/{name}
operationId:"ApiAgentsByScopeByNamePost"
  parameters: [{name: "scope", in: "path",…}, {name: "name", in: "path",…}, {name: "state", in: "query",…}]
    0: {name: "scope", in: "path",…}
    1: {name: "name", in: "path",…}
    2: {name: "state", in: "query",…}
      description:"The agent state to set after the agent definition is created."
      enum:[null, null]
      in:"query"
      name:"state"
      required:false
      type:"string"
```
Which appears in UI as:
![image](https://user-images.githubusercontent.com/485120/37251256-dedcf0c0-2560-11e8-8c33-36d6535edfcc.png)

When I remove all the data contract annotations from the enum, everything gets back to normal:
    public enum AgentState
    {
        Inactive,
        Active
    }
![image](https://user-images.githubusercontent.com/485120/37251276-2ea7e254-2561-11e8-9bee-83c169373566.png)

**Comment by domaindrivendev** [comment]
Thanks for pointing this out. It should be fixed with the following commit - 896f3371d54faa56579432785d7a24f703569e17. Will release official Nuget in the next week or so. In the meantime you can pull the preview (built from master) from myget.org.
