### ISSUE TITLE
Missing Bearer token in request header

### ISSUE THREAD

**Issue by hzinchenko** [domaindrivendev/Swashbuckle.AspNetCore#647]
I'm using Swashbuckle.AspNetCore on my project. Recently I updated package from 1.1.0 version to 2.2.0.
After that, I noticed that with the same set of actions that I did before, bearer token is no more sent in the request header.
I use the next configuration:
`                services.AddSwaggerGen(c =>
                {
                    c.SwaggerDoc("v1", new Info { Title = "MyCoolApp API", Version = "v1" });
                    c.AddSecurityDefinition("Bearer", new ApiKeyScheme()
                    {
                        Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                        Name = "Authorization",
                        In = "header",
                        Type = "apiKey"
                    });
                });`

Did something change in the new version configuration?

**Comment by ogix** [comment]
Same problem here

**Comment by domaindrivendev** [comment]
This is a dup of #603. Please take the time to search existing issues instead of creating new ones.
