### ISSUE TITLE
Issue when upgrading to ASP.Net Core 2.0.2

### ISSUE THREAD

**Issue by TonyValenti** [domaindrivendev/Swashbuckle.AspNetCore#652]
Hi All,
I've recently upgraded to ASP.NET Core 2.0.0 and now I'm getting the following error:

System.MissingMethodException: 'Method not found: 'Void Microsoft.Net.Http.Headers.EntityTagHeaderValue..ctor(System.String)'.'

Decompiling the method, it looks like its constructor's signature changed and is now:
public EntityTagHeaderValue(StringSegment tag)

**Comment by domaindrivendev** [comment]
Dup of #408
