### ISSUE TITLE
JWT, Bearer token, Authorization header stopped working

### ISSUE THREAD

**Issue by alaniemieckota** [domaindrivendev/Swashbuckle.AspNetCore#653]
Since very beginning I was using something like this:
```
services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new Info { Title = "My Title", Version = "v1" });
    options.AddSecurityDefinition("Bearer", new Swashbuckle.AspNetCore.Swagger.ApiKeyScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\", provide value: \"Bearer {token}\"",
        Name = "Authorization",
        In = "header",
        Type = "apiKey"
    });
});
```
It was giving me a possibility to have "Authorize" button where after clicking it I was able to provide a value which was attached to each request in header like:

Authorization: Bearer the_token_here

since version 2.0.0 of Swaschbuckle.AspNetCore this stopped working.
I mean the Authorization button is still there, after clicking it I am still able to provide a value but, the provided value is not being attached to requests any more.

**Comment by domaindrivendev** [comment]
Dup of #603.

**Comment by fileman** [comment]
If you intended to get access_token from querystring after login redirect and append to execute action as "Authentication: Bearer ey0123...", starting from default [oauth2 implicit](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-indexhtml) config, you need a [custom index.html](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-indexhtml) with this settings:
```
<script>
        window.onload = function () {
            var queryDict = {};
            location.href.substr(1).split("&").forEach(function (item) { queryDict[item.split("=")[0]] = item.split("=")[1] })

            var authToken = queryDict["access_token"];

            var configObject = JSON.parse('%(ConfigObject)');
            var oauthConfigObject = JSON.parse('%(OAuthConfigObject)');

            // Apply mandatory parameters
            configObject.dom_id = "#swagger-ui";
            configObject.presets = [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset];
            configObject.layout = "StandaloneLayout";

            if (!configObject.hasOwnProperty("oauth2RedirectUrl"))
                configObject.oauth2RedirectUrl = window.location + "oauth2-redirect.html"; // use the built-in default


            // Build a system
            const ui = SwaggerUIBundle({
                url: configObject.oauth2RedirectUrl.replace("/swagger", "") + configObject.urls[0].url,
                dom_id: configObject.dom_id,
                configs: {
                    preFetch: function (req) {
                        if (authToken) {
                            req.headers["Authorization"] = "Bearer " + authToken;
                        }
                        return req;
                    }
                },
                tagsSorter: configObject.tagsSorter,
                docExpansion: configObject.docExpansion,
                deepLinking: configObject.deepLinking,
                validatorUrl: configObject.validatorUrl,
                presets: configObject.presets,
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: configObject.layout
            })


            // Apply OAuth config
            ui.initOAuth(oauthConfigObject);
        }
</script>
```
I'm not a javascript expert, I don't know if there is a better method to configure configs.prefetch to configObject ... but this work without break startup.cs settings.

**Comment by vanillajonathan** [comment]
@fileman Do not pass the token in the query string as it is less secure. Query strings may be cached and logged by proxies. It is best pass them in the `Authorization` header.

**Comment by fileman** [comment]
@vanillajonathan sure the access_token was sended in header to the api.

I'm using Azure B2C and after login's callback it open a new swagger windows with the access token in querystring, so I extract from it and set into header.

**Comment by arlan85** [comment]
Hi all, 
@vanillajonathan I'm using the same providr as @fileman and it comes on the query-string the token content and specs, but I try to add it with no luck to a cookie or to any swagger configuration on client. 
Any clues?
