### ISSUE TITLE
Operation.Consumes contains sometimes duplicate MediaTypes

### ISSUE THREAD

**Issue by wouterdirks** [domaindrivendev/Swashbuckle.AspNetCore#655]
Tested on version 2.3.0 and 1.1.0

In the Operation.Consumes there are sometimes duplicate MediaTypes.  This is caused by the fact that there provided as duplicates in apiDescription.SupportedRequestFormats.

Error from swagger.io:

> Schema error at paths['/{label}/v1/activities/{id}'].put.consumes
> should NOT have duplicate items (items ## 6 and 9 are identical)
> i: 9
> j: 6

> consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
        - application/xml
        - text/xml
        - application/*+xml
        - application/xml
        - text/xml
        - application/*+xml

Solution:
Add .Distinct() just as is done in SupportedResponseMediaTypes.

`internal static IEnumerable<string> SupportedRequestMediaTypes(this ApiDescription apiDescription)
        {
            return apiDescription.SupportedRequestFormats
                .Select(requestFormat => requestFormat.MediaType)
                .Distinct();
        }`

**Comment by domaindrivendev** [comment]
See 513fb2102a5a7184ba8222926fab60841874d226
