### ISSUE TITLE
Invalid Swagger generated when mapping url arguments to an object

### ISSUE THREAD

**Issue by jcoplonsdc** [domaindrivendev/Swashbuckle.AspNetCore#656]
I'm using Swashbuckle.AspNetCore v2.2.0. I'm mapping a route that looks like the following:

```csharp
[HttpGet("{foo}/{bar}/{blah}")]
public async Task<IActionResult> Get(Foobar foo) 
{
}

public class Foobar
{
        [JsonProperty(PropertyName ="foo")]
        public string Foo { get; set; }

        [JsonProperty(PropertyName ="bar")]
        public decimal Bar { get; set; }

        [JsonProperty(PropertyName ="blah")]
        public short Blah { get; set; }
}
```
Resulting Swagger:

``` json
{  
   "swagger":"2.0",
   "info":{  
      "version":"v1",
      "title":"Foobar Service"
   },
   "paths":{  
      "/foobar/{foo}/{bar}/{blah}":{  
         "get":{  
            "tags":[  
               "Foobar"
            ],
            "consumes":[  

            ],
            "produces":[  

            ],
            "parameters":[  
               {  
                  "name":"Foo",
                  "in":"path",
                  "required":true,
                  "type":"string"
               },
               {  
                  "name":"Bar",
                  "in":"path",
                  "required":true,
                  "type":"number",
                  "format":"double"
               },
               {  
                  "name":"Blah",
                  "in":"path",
                  "required":true,
                  "type":"integer",
                  "format":"int32"
               }
            ],
            "responses":{  
               "200":{  
                  "description":"Success"
               }
            }
         }
      }
   },
   "definitions":{  
      
   },
   "securityDefinitions":{  

   },
   "security":[  

   ]
}
```

The resulting Swagger generated utilizes the path defined correctly in lower case however the names of the parameters are upper case matching the model's property name causing the resulting swagger to look like there is a discrepancy. This breaks a few of our tools that we'd like to leverage. Is there a way to have the model names for url sourced models map to the defined JsonProperty name?

**Comment by domaindrivendev** [comment]
`JsonProperty` has no effect on properties that are bound to non-body parameters from the HTTP request. It's only applicable when serializing/deserializing objects to/from response & request payloads.

Try replacing the use of `JsonProperty` above with `BindProperty`.

It's also worth noting, you can remove these annotations altogether and instruct SB to always generate camelCase names for parameters, regardless of the casing used in the property name as follows:

```csharp
c.DescribeAllParametersInCamelCase()
```

Either of these approaches should work for you
