### ISSUE TITLE
Upgrade version 1.0 to 2.0, the bearer authentication doesn't work. Why?

### ISSUE THREAD

**Issue by NhatDuy1407** [domaindrivendev/Swashbuckle.AspNetCore#657]
Hello everyone,

Using **Swashbuckle.AspNetCore v1.0.0**, I configured as below:

` services.AddSwaggerGen(c =>`
`{`
         ` c.SwaggerDoc("v1", new Info { Title = ".NET API", Version = "v1" });`
               ` c.AddSecurityDefinition("Bearer", new ApiKeyScheme`
              `  {`
                  `  Description = "Example: \"Authorization: Bearer {token}\"",`
                   ` Name = "Authorization",`
                    `In = "header",`
                   ` Type = "apiKey"`
             `   });`
`});`

**It worked fine.**
After that, I upgrade the latest version **Swashbuckle.AspNetCore v2.3.0**, no change the code and try to run swagger, but it doesn't work, I check the request header, missing the bearer authentication header.
See the picture:

![noheaderauthentication](https://user-images.githubusercontent.com/5676740/37700255-5af0a5c6-2d1d-11e8-823d-46306230cf85.JPG)

Please tell me why? How to fix it?
Thanks in advance.

**Comment by wertzui** [comment]
Add this after your code:
```
c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
{
     { "oauth2", new string[] { } },
});
```

**Comment by domaindrivendev** [comment]
Above guidance is correct. Also, this is a dup of #603
