### ISSUE TITLE
Authorization header not present in request

### ISSUE THREAD

**Issue by brunoavpinheiro** [domaindrivendev/Swashbuckle.AspNetCore#658]
After upgrade the version from 1.2.0 to 2.3.0 the Authorization header was not sent anymore in the request from the Swagger UI.

I am using ApiKey Authorization.

**Comment by domaindrivendev** [comment]
Dup of #608. For future reference, please search the existing issues before creating new ones. Thanks.

**Comment by domaindrivendev** [comment]
Doh - that should be #603
