### ISSUE TITLE
XML comments from generic base controller are not found

### ISSUE THREAD

**Issue by wertzui** [domaindrivendev/Swashbuckle.AspNetCore#659]
I have a base controller that looks like this:

    public abstract class RestController<TDto, TEditDto, TListDto, TDetailDto> : Controller

It has a `GET` Method:

    public async Task<IActionResult> Get([FromRoute, Required] IReadOnlyCollection<long> ids, [FromQuery]PagingRequestDto<TDetailDto> paging)

And a Controller that derives from it:

    public class InventoryController : RestController<InventoryDto, InventoryEditDto, InventoryListDto, InventoryDetailDto>

Inside of the InventoryController there is no override of the `Get` method, it just defines the generic type arguments of the `RestController` class.

The Problem is that in the xml comment file, the member name is this:

    M:AspNetCore.Common.Controllers.RestController`4.Get(System.Collections.Generic.IReadOnlyCollection{System.Int64},Common.Dtos.PagingRequestDto{`3})

But `XmlCommentsIdHelper.GetCommentIdForMethod(controllerActionDescriptor.MethodInfo)` will expand the generic type argument `TDetailDto` to `InventoryDetailDto`.
So the generated name is

    M:AspNetCore.Common.Controllers.RestController`4.Get(System.Collections.Generic.IReadOnlyCollection{System.Int64},Common.Dtos.PagingRequestDto{InventoryDetailDto})

What I would expect is that it should identify the method as a generic method that uses the 3rd type argument from the containing class resulting in a correct commentId.

**Comment by domaindrivendev** [comment]
Dup of #165
