### ISSUE TITLE
How to authorize Swagger with [FromBody] request?

### ISSUE THREAD

**Issue by Advitalitum** [domaindrivendev/Swashbuckle.AspNetCore#663]
I have AuthController.cs that has this metod:
```csharp
[HttpPost("~/auth/token")]
[AllowAnonymous]
public async Task<IActionResult> GenerateToken([FromBody] LoginModel model)
```
I use security definition:
```csharp
c.AddSecurityDefinition("Bearer", new OAuth2Scheme()
{
    AuthorizationUrl = "/auth/token",
    TokenUrl = "/auth/token",
    Flow = "password",
    Description = "Please authorize to access API",
    Type = "oauth2",
});
```
If i try to authorize on swagger page i get 415 (Unsupported Media Type) response status.
How to configure security definition to send auth parameters in the body of the request?

**Comment by domaindrivendev** [comment]
What media type does your token endpoint expect. I believe the OAuth2 protocol allows credentials to be sent via query parameters or form data (application/x-www-form-urlencoded), but not JSON.

I just tried out the password flow with a local project and confirmed the Swashbuckle/swagger-ui integration all works well if the token endpoint support accepts form data.
