### ISSUE TITLE
SwaggerResponseAttribute exists with no SwaggerResponseRemoveDefaultsAttribute

### ISSUE THREAD

**Issue by richmcd** [domaindrivendev/Swashbuckle.AspNetCore#664]
If I use the Produces attribute SB always specifies a 200 Success response even when there is no return path that generates a status code of 200.  I can use the ProducesResponseType attribute instead to specify both the type and default response code, but it seems kind of confusing to have the SwaggerReponseAttribute back to account for other response codes and not include the SwaggerResponseRemoveDefaultsAttribute.

I can create a SwaggerResponseRemoveDefaults Attribute and Filter easily enough and register the Filter as an OperationFilter, but that requires me to re-register or duplicate the SwaggerResponseAttributeFilter code or I just lose all response codes.  It seems like the remove defaults behavior really does belong back in the SwaggerResponseAttributeFilter or at least the SwaggerResponseAttribute should allow for an optional Remove flag so we can selectively remove status codes from the defaults.

I realize now that this request may not fit with the desire to reuse MVC attributes, but it makes more sense from a code migration perspective.

**Comment by domaindrivendev** [comment]
As of ASP.NET Core 2.2, `ApiExplorer` will only surface a default (i.e. 200) response if the action has no `ProducesResponseType` attributes. In other words, as soon as you decorate an action with one or more explicit response types - defaults will be removed implicitly.

**Comment by lonix1** [comment]
@domaindrivendev The `/// <response....` syntax is now available and preferred, but Swashbuckle still adds a default 200 even though it's unwanted.

We can still suppress that by using an attribute, but that defeats the purpose of using xml comments.

Is there a workaround?
