### ISSUE TITLE
IServiceCollection do not contain AddSwaggerGen's definition 

### ISSUE THREAD

**Issue by WillLeeBebi** [domaindrivendev/Swashbuckle.AspNetCore#667]

**Comment by domaindrivendev** [comment]
I can't repro this, and the latest build and tests (see https://ci.appveyor.com/project/domaindrivendev/ahoy/branch/master) completed successfully. So, at this point, I'm not sure how I can help.

Perhaps, you could provide clear repro steps, starting with a blank project that follows the "Getting Started" steps?

**Comment by WillLeeBebi** [comment]
Failed to load API definition.
Internal Server Error /swagger/v1/swagger.json

**Comment by WillLeeBebi** [comment]
An unhandled exception occurred while processing the request.
NotSupportedException: Ambiguous HTTP method for action - QuanDuan.Love.WebApi.Controllers.MemberController.Auth (QuanDuan.Love.WebApi). Actions require an explicit HttpMethod binding for Swagger 2.0
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable<ApiDescription> apiDescriptions, ISchemaRegistry schemaRegistry)
