### ISSUE TITLE
Customize class property names

### ISSUE THREAD

**Issue by adamkjonesmesh** [domaindrivendev/Swashbuckle.AspNetCore#669]
Hello,

Suppose I have class in a C# asp.net core app as below:

```
public class MyClass
{
    public string MyString { get; set; }
    public int MyInteger { get; set; }
    public DateTime TimeStamp { get; set; }
}
```

I use this class in my controller for one of my actions (e.g. below).

```
public IActionResult Post ([FromBody]MyClass request)
{
    ...
}
```

When I generate the swagger documentation and view it in the swagger ui, MyClass properties are outputted as MyString, MyInteger, and TimeStamp.  What I would like to do is have them output as myString, myInteger, and timestamp.  Notice timestamp isn't camelCase but is all lower case.  Is there a way we can customize property names and how they are outputted in swagger ui?

Thanks.

**Comment by domaindrivendev** [comment]
Swashbuckle generates API descriptions from the behavior it infers from code. So really, you need to customize your "actual" API behavior, specifically around JSON serialization, and then Swashbuckle will automatically adjust it's descriptions accordingly:

```csharp
// Startup.cs
services.Configure<MvcJsonOptions>(c =>
{
    // Serialize all properties to camelCase by default
    c.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
});

// MyClass.cs
public class MyClass
{
    public string MyString { get; set; }

    public int MyInteger { get; set; }

    [JsonProperty("timestamp")] // set JSON name explicitly for this one as it's a special case
    public DateTime TimeStamp { get; set; }
}
```

**Comment by adamkjonesmesh** [comment]
Yeah, I've tried that but it doesn't work.  It works fine for POST actions but NOT GET.  I'm sorry, I posted my question with a POST action, but I just recently (today) found out this does not work for GET actions; however, it does work for POST actions.  For example, if I have a GET action as such:

```
public IActionResult Get(MyClass request)
{
    ...
}
```

When I start the app and go to the swagger endpoint, the swagger UI displays the properties on MyClass as Pascal case and ignores the JsonProperty attributes.  Is this expected behavior?

**Comment by domaindrivendev** [comment]
So, when you use a class to represent query parameters, the JsonSerializer isn’t involved. Instead, MVC model binding is used to assign values directly from the request into the instance properties.

So, if you want to be explicit about required casing for this behavior, and hence the generated description, you need to customize the model binding behavior too. I’m not at my laptop now but off the top of my head, I think you can annotate properties with “FromQuery” and set the bind name that way.

**Comment by adamkjonesmesh** [comment]
Perfect!  Thanks so much.  This works beautifully.

**Comment by chinaniit** [comment]
Thanks for you help. @domaindrivendev 
This is POST method:
```csharp
[HttpPost]
public xx PostByName([FromBody]PostModel model)
{
    // TODO:
}
...
public class PostModel
{
     [JsonProperty("name")]
     public string Name{get;set;}
}
```
This is GET method:
```csharp
[HttpGet]
public xx GetByName([FromQuery]GetModel model)
{
    // TODO:
}
...
public class GetModel
{
     [FromQuery(Name = "name")]
     public string Name{get;set;}
}
```
