### ISSUE TITLE
Add support for OpenAPI v3

### ISSUE THREAD

**Issue by darrelmiller** [domaindrivendev/Swashbuckle.AspNetCore#671]
I'm opening this issue to judge interest/openness to me submitting a PR for adding support for OpenAPI V3.  

The OpenAPI V3 model library we have been working on [here](https://github.com/microsoft/openapi.net) is getting very close to a 1.0 release and from my initial investigations around the Swashbuckle code base it appears like it would be fairly straightforward to replace the existing SwaggerDocument class with the model from the OpenAPI.NET library.  Even though it is a V3 model, it can still export V2 documents in both JSON and YAML format, so we should be able to add the functionality in a non-breaking way.

Thoughts? Interest?

**Comment by domaindrivendev** [comment]
Generally speaking, I think this would likely be a good move for Swashbuckle and it's consumers.

With that said, I'm always a little hesitant to take on external dependencies. In doing so, I want to be sure there's a strong case in terms of both value-add and long-term dependability.

@darrelmiller - would you be open to syncing up and discussing your longer-term vision for OpenApi.NET?

**Comment by darrelmiller** [comment]
@domaindrivendev Happy to chat at your convenience.  I can tell you that this library will be used by Azure API Management and Azure Logic Apps.  It is will soon be used to as part of the MSFT docs generation process.  There are also a number of other internal Microsoft projects that are using it.
The model project itself has no external dependencies, so there is no concern about mismatched versions on third party libraries.

The team working on the project is spread across multiple divisions and so there is no single org that can choose to shutter it if their focus changes :-)

**Comment by domaindrivendev** [comment]
@darrelmiller - based on your response and some further research, I'm happy to go down this route. Let me know if there's any way I can help?

**Comment by darrelmiller** [comment]
@domaindrivendev That's excellent.  I have a long flight tomorrow to Seattle.  I'll see what I can get done.

@onionhammer I'm not aware of anyone who has yet produced a code generator that takes advantage of the V3 stuff.  Hopefully soon!

**Comment by domaindrivendev** [comment]
@darrelmiller - have you had a chance to look at this yet? Let me know if there's any way I can help

**Comment by darrelmiller** [comment]
@domaindrivendev  I did look and realized that there are few approaches with varying degrees of benefit and work.  I could embed the OpenApiDocument inside the existing SwaggerDocument and output V3 versions of OpenAPI.  It would be very little work but it would not enable taking advantage of any of the V3 features.  So it would be very much a short term solution, but it would be non-breaking.

The other approach would be to add a new project Swashbuckle.AspNetCore.OpenApiGen.  This would require re-implementing/duplicating quite a bit of infrastructure.  But then the two models would live side by side and would be non-breaking.

The final approach which I had originally considered would be to just replace the SwaggerDocument with OpenApiDocument and make the adjustments where code interacts with the OpenApiDocument.  This would be breaking for any other library that takes a dependency on Swashbuckle.  When I was looking that this I had decided that making breaking changes was going to be a non-starter, but now thinking about it again, perhaps Swashbuckle is more self-contained than most libraries and maybe it isn't a major problem to make this breaking change?

**Comment by domaindrivendev** [comment]
I'm happy with the third approach. It would definitely go out as a major version increment (of Swashbuckle) and I would accompany with docs & communication for upgrading. You mentioned that OpenApi.NET can serialize to v3 or v2 versions (of OAI) so we could have Swashbuckle expose both. That way, API authors that consume Swashbuckle can provide backwards compatibility to consumers of their Swagger/OAI JSON. Does that make sense?

**Comment by SimonTouchtech** [comment]
See also https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/419

**Comment by esbenbach** [comment]
@domaindrivendev Is this being worked on actively? The netstandard 2.0 branch has not been updated in a while. Might be there is some way we can contribute if we knew where/what you want help with.

**Comment by darrelmiller** [comment]
@esbenbach Yes, I am actively working on the V3 support over [here](https://github.com/darrelmiller/Swashbuckle.AspNetCore/tree/dm/openapiv3).  I ran into a bit of a roadblock with the migration due to a missing capability in the OpenAPI.Net library.  That work has now been [done](https://github.com/Microsoft/OpenAPI.NET/pull/258) and so I should be able to continue on this work very shortly.

**Comment by gaui** [comment]
Wow awesome to hear @darrelmiller your work is really appreciated!

**Comment by domaindrivendev** [comment]
@darrelmiller - how are things going? Is there anything I can help with to get this over the line?

**Comment by darrelmiller** [comment]
@domaindrivendev Find someone to do my day job? ;-)  But seriously I ran into a bit of a deadline at work and it has diverted my attention.

**Comment by RaulRG** [comment]
I was going to ask for Open API v3 support and saw this issue. As we are going to use it for Logic Apps as well, it would be a great move!!!

**Comment by domaindrivendev** [comment]
@darrelmiller - can you provide a quick assessment of the remaining work for this? Can we enlist some more help to get it over the line?

**Comment by darrelmiller** [comment]
@domaindrivendev My guess is there is 3-4 hours of work left.  I have a flight on Friday.  I'll try and do it then.

**Comment by bmwatson214** [comment]
@darrelmiller , Is there any update on the eta for v3 support? Super excited about this update!

**Comment by KrzysztofBranicki** [comment]
@darrelmiller Does your work include also support for OAS 3 features like oneOf, anyOf, allOf and appropriate swagger generation for cases when you use abstractions in models that are passed to controller actions?

**Comment by darrelmiller** [comment]
@KrzysztofBranicki The model we are using does support those schema constructs.  However, I have not made any attempt to translate types to use those constructs.  I need to get the basic stuff working first.

Sadly because it took me so long to get this work done, merging master is very painful.  I tried doing it in one shot and resolving the conflicts was impossible.  So now I have started merging a chunk at a time.  So far I'm have successfully merged v2.5 stuff.  Still a ways to go.

**Comment by mpetito** [comment]
@domaindrivendev @darrelmiller was the merge with master completed?  Are you looking for assistance at this point?

**Comment by domaindrivendev** [comment]
@darrelmiller - I haven't received a PR yet. Is there much left to do?

I have several breaking changes (albeit enhancements) now in master queued up for the next major release and I wanted to include this change also to reduce the number of releases with breaking changes. This is the last open feature out of that batch -  https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/6

If you're short on cycles - I can take a look. I've been working with the OpenAPI.Net object model on a separate project and have become familiar enough with it that I could probably incorporate it into SB relatively quickly.

**Comment by VictorioBerra** [comment]
Let's get this shipped boys. You would think with the ASPNET Core 3.0 pushing API conventions and analyzers so much there would be a little bit of extra pull from their side on this.

https://blogs.msdn.microsoft.com/webdev/2018/10/29/a-first-look-at-changes-coming-in-asp-net-core-3-0/

**Comment by domaindrivendev** [comment]
Beta version now available, leveraging OpenAPI.NET object model, with full support for OpenAPI 3.0 specification …

https://www.nuget.org/packages/Swashbuckle.AspNetCore/5.0.0-beta

**Comment by esbenbach** [comment]
Awesome work @darrelmiller and @domaindrivendev

**Comment by RKVitaly** [comment]
> Beta version now available, leveraging OpenAPI.NET object model, with full support for OpenAPI 3.0 specification …
> 
> https://www.nuget.org/packages/Swashbuckle.AspNetCore/5.0.0-beta

Hello. Thank you for beta.
What about anyof/oneof?

**Comment by RKVitaly** [comment]
Why you closed the issue?
Please answer for this: 
What about anyof/oneof?

**Comment by esbenbach** [comment]
Probably because support anyof/oneof requires a different set of changes, so it should probably a separate feature request/issue. I suggest you create an issue for it, then there is at least some chance someone will work on it :)

**Comment by domaindrivendev** [comment]
Exactly - I'm not going to track every single additional feature that _could_ be supported with OpenAPI 3.0 in a single issue. Please create a separate issue incl. a full description (including code samples) of the problem you're hoping to solve with the addition of anyof/oneof support

**Comment by RKVitaly** [comment]
> Exactly - I'm not going to track every single additional feature that _could_ be supported with OpenAPI 3.0 in a single issue. Please create a separate issue incl. a full description (including code samples) of the problem you're hoping to solve with the addition of anyof/oneof support

Thank you
#955
