### ISSUE TITLE
Error while using with  services.AddProgressiveWebApp()

### ISSUE THREAD

**Issue by skvsree** [domaindrivendev/Swashbuckle.AspNetCore#676]
When we use Swashbuckle along with  `services.AddProgressiveWebApp()` as per  instructions in below link.
[Building Progressive Web apps with ASP.NET Core](https://dotnetthoughts.net/progressive-web-apps-on-aspnet-core/)

receiving below error.
`Ambiguous HTTP method for action - WebEssentials.AspNetCore.Pwa.PwaController.ServiceWorkerAsync (WebEssentials.AspNetCore.Pwa). Actions require an explicit HttpMethod binding for Swagger`

Is there a way we can exclude these methods from Swagger?

**Comment by domaindrivendev** [comment]
I'm not familiar with the Progressive Web apps functionality but if you're looking to omit certain actions/controllers based on some arbitrary metadata, take a look at the following section of the SB  readme:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#omit-arbitrary-operations
