### ISSUE TITLE
How to enable JsonEditor ?

### ISSUE THREAD

**Issue by abentabet** [domaindrivendev/Swashbuckle.AspNetCore#677]
Hi Everyone,

I've upgraded to the latest version of  Swashbuckle.AspNetCore, I'm using a custom html (to implement XSRF token), but i can't enable json editor by configObject.jsonEditor = true as the option on UseSwaggerUI is no longer available !

Does anyone know how to enable json editor ? 
Thanks in advance !

**Comment by domaindrivendev** [comment]
This feature is no longer supported in the 3x versions of swagger-ui, which is a completely separate project that's bundled into Swashbuckle. For more info, check the following issue in the swagger-ui repo - https://github.com/swagger-api/swagger-ui/issues/2911
