### ISSUE TITLE
aspnet core 2.1.0 preview 2

### ISSUE THREAD

**Issue by grahamehorner** [domaindrivendev/Swashbuckle.AspNetCore#679]
create a aspnet core web api using the default template aspnet core 2.1 preview 2, add the swashbuckle package and configure it as you would do with aspnet core 2.0 template, run the web api then navigate to the /swagger uri this results in a server exception 500

console windows shown issues with the middleware pipeline

**Comment by domaindrivendev** [comment]
I can't repro this - please provide a stack trace of the errors you're seeing

**Comment by domaindrivendev** [comment]
No response - closing as I can't repro with current information.
