### ISSUE TITLE
Swagger UI always return json response

### ISSUE THREAD

**Issue by michelwin** [domaindrivendev/Swashbuckle.AspNetCore#680]
I am using Swashbuckle.AspNetCore version 1.2.0.

The problem that I can't pass the accept parameter with application/xml that's why the application always return json response.

Thanks,

**Comment by domaindrivendev** [comment]
Swashbuckle bases it's description on the "actual" API behavior it can derive from your ASP.NET Core configuration and code. Can you confirm that the "actual" behavior you're trying to describe works. That is, can you successfully retrieve XML from your API independently of Swashbuckle (e.g. curl, postman etc.)?

**Comment by michelwin** [comment]
Exactly, the application the work's with aboth XML and json.
The problem happen only when I use swagger. As I said the swagger don't have option to change the response type to XML.

**Comment by domaindrivendev** [comment]
Ok can you provide your Startup.cs and one of the your action methods?

**Comment by michaelestermann** [comment]
In our project, we created an operation filter (IOperationFilter), which adds the response types to the swagger configuration. You can get it from here: https://github.com/michaelestermann/SwashbuckleCasing/blob/master/SwashbuckleCasing/ResponseContentTypeFilter.cs

**Comment by domaindrivendev** [comment]
Will track as part of #1050
