### ISSUE TITLE
Map byte and sbyte to integer instead of string

### ISSUE THREAD

**Issue by roman-honzak** [domaindrivendev/Swashbuckle.AspNetCore#682]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/d40c731b87524276df6393ebf97db284b95c683b/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs#L252

Hi,

please correct mapping of primitive numeric types byte and sbyte to numeric type, not to string.

`{ typeof(byte), () => new Schema { Type = "integer", Format = "int32" } }`
`{ typeof(sbyte), () => new Schema { Type = "integer", Format = "int32" } }`

Thank you.

**Comment by domaindrivendev** [comment]
Fixed by bf3589901f12805432af81f2dff85809ce74af09. Preview package available on myget.org.
