### ISSUE TITLE
Type of Array parameter is not generated, unless parameter is specified as  FromBody

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [domaindrivendev/Swashbuckle.AspNetCore#684]
When I have a method 
```
      [HttpPost][Route("{id}")]
        public SwashbuckleTestProfile Post(Guid id, List<SwashbuckleTestProfile> companies)

```
in swagger.json companies are described as array, not as array of SwashbuckleTestProfile. 

As a workaround, specifying [FromBody]  fixes the issue, but  I didn't know this until I was [advised on SO](https://stackoverflow.com/questions/49746268/swashbuckle-swagger-how-to-show-type-of-array-of-models-parameter/49758618#49758618) 
The example to reproduce the issue can be loaded from https://github.com/MNF/Samples/tree/master/SwashbuckleExample .

I am using latest 2.4 version.

**Comment by domaindrivendev** [comment]
From the readme ...

"_NOTE: If you omit the explicit parameter bindings, the generator will describe them as "query" params by default._"

I'm assuming you want this parameter to be passed in the request body and not the query string. So, you need to be explicit about that if you want Swashbuckle to describe it accurately. It's also worth noting that, independently of Swashbuckle, by omitting the 'FromBody` binding your API will actually accept the parameter via query or body.

**Comment by MNF** [comment]
I’ve read, that in asp.net core 2.1 it will be [Automatic inferring of parameter binding strategies](https://www.strathweb.com/2018/02/exploring-the-apicontrollerattribute-and-its-features-for-asp-net-core-mvc-2-1/).  
Will Swashbuckle be able to determine the most appropriate binding strategy without explicit FromBody attribute?
You correctly guessed

> I'm assuming you want this parameter to be passed in the request body and not the query string

Could Swashbuckle assume the same? At least, if it made some assumptions, could it log a warning describing which options it had and what was chosen?

Also, as far as I know ( correct me if I am wrong) it’s possible to[ send complex object-in-query-string](https://stackoverflow.com/questions/47931625/pass-a-list-of-complex-object-in-query-string-to-web-api).
So the type of parameter should be correctly shown regardless is it in body or query string.
