### ISSUE TITLE
Hide the client secret?

### ISSUE THREAD

**Issue by garymacpherson** [domaindrivendev/Swashbuckle.AspNetCore#695]
In an older version of the SwaggerUI when you did the OAuth2 flow to provide authentication, the screen where you selected your scopes was different and didn't show the client ID or (more importantly) client secret.

I have upgraded the version of the package I am using and now the client secret is shown in plain text... how can I hide that?

**Comment by domaindrivendev** [comment]
As per the point 2) in the [issue template](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/ISSUE_TEMPLATE.md), this is a question for the [swagger-ui](https://github.com/swagger-api/swagger-ui) folks and not for Swashbuckle.
