### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': Invalid name

### ISSUE THREAD

**Issue by ngohungphuc** [domaindrivendev/Swashbuckle.AspNetCore#704]
I get this error when set Authorization header. 
Here is my setup 
```cs
services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info
                {
                    Version = "v1",
                    Title = "Awesome CMS Core API",
                    Contact = new Contact { Name = "Tony Hudson", Email = "", Url = "https://github.com/ngohungphuc" }
                });

                c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
                {
                    { "Bearer", new string[] { } }
                });

                c.AddSecurityDefinition("Bearer", new ApiKeyScheme
                {
                    Name = "Authorization: Bearer",

                    In = "header",

                    Type = "apiKey",

                    Description = ""
                });

            });
```
![chrome_2018-04-25_23-13-23](https://user-images.githubusercontent.com/13591213/39258498-4b3b2c1e-48de-11e8-80f0-8e20ea96ae6c.png)

**Comment by domaindrivendev** [comment]
For Bearer auth, the format is typically `Authorization: Bearer <token>`. So, in your example, the key name needs to be `Authorization` and then the value that's provided (i.e. through the SwaggerUI) needs to be of the format `Bearer <token>`

**Comment by jayrajmishra** [comment]
Autorization Token = Bearer xyx-something-example, put this access token in Swagger, but i am getting the error. 

public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(options =>
            {
                options.Authority = "https://auth0.todayworld.com/";
                options.Audience = "todayworld";
            });

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info
                {
                    Title = "API",
                    Version = "v1",
                    Description = "Today World",
                    TermsOfService = "http://todayworld.com"
                });
                c.AddSecurityDefinition("Bearer",
                    new ApiKeyScheme
                    {
                        In = "header",
                        Name = "Authorization",
                        Type = "apiKey"
                    });
                c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>() { { "Bearer", new string[] { } } });

            });

        }

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "CPS Staging API-v1");
            });       
        }

When authorizing, the Access Token, I am getting this error - 

TypeError: Failed to execute 'fetch' on 'Window': Invalid name
--
