### ISSUE TITLE
valid values in xml comments

### ISSUE THREAD

**Issue by adnan-kamili** [domaindrivendev/Swashbuckle.AspNetCore#710]
I was trying to add valid values for a class property using following:

        /// <summary>
        /// The strategy to determine the xxx.
        /// </summary>
        /// <remarks>Valid values: "now", "delayed"</remarks>
        [Contains(new string[] { StrategyType.Now, StrategyType.Delayed })]
        public string Strategy { get; set; }

The remarks section seems to be ignored in this case. I am not using an enum, so I need to mention allowed values in the comments.

**Comment by domaindrivendev** [comment]
The `Schema` object in [Swagger 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) only has one field for a textual description and that is populated from the `<summary>` tag. So, you need to append valid values to the summary instead of using the `<remarks>` tag
