### ISSUE TITLE
nuget icon?

### ISSUE THREAD

**Issue by SimonCropp** [domaindrivendev/Swashbuckle.AspNetCore#714]
May i suggest https://thenounproject.com/search/?q=pirate

**Comment by domaindrivendev** [comment]
Awesome - are they free? One of the in between two braces would be great

**Comment by SimonCropp** [comment]
most use the model of dual license. so creative commons with attribution or paid with no attribution. so i usually attribute in the readme. https://github.com/NServiceBusExtensions/NServiceBus.Attachments#icon

but they are only around 2$ US to buy
