### ISSUE TITLE
Updating UI html to allow proper CSP headers

### ISSUE THREAD

**Issue by garymacpherson** [domaindrivendev/Swashbuckle.AspNetCore#716]
Is there any desire within the maintainers to update `Swashbuckle.AspNetCore/src/Swashbuckle.AspNetCore.SwaggerUI/index.html` to bundle remote fonts, change inline styles to external files etc. to allow full use of proper CSP headers as it can be a security requirement for some consumers.

I can raise a PR to do so, if it is inline with your direction.

Thanks,

**Comment by domaindrivendev** [comment]
Dup of #505
