### ISSUE TITLE
Add option for "dotnet swagger tofile" CLI command to produce formatted output.

### ISSUE THREAD

**Issue by mcattle** [domaindrivendev/Swashbuckle.AspNetCore#718]
I'd like to request a feature to add a switch to the **dotnet swagger tofile** command to allow the output to be "pretty" formatted with whitespace and line breaks.

Use case: As a post-compile task, I'm looking at auto-generating the swagger JSON to a file to be stored in our service's code repository, so that any changes to the controller actions will be reflected in the document and included in the commit (for later client code generation).  Without the formatting, this could raise messy merge issues if multiple developers modify the interface of the service.  With the formatting, the merge tool should have no issue merging multiple changes.

A workaround would be to run the output of the command through a JSON formatter, but as we have both Windows and Linux development workstations, the formatter would need to be supported on both platforms, ideally without having to install anything outside of npm.

**Comment by domaindrivendev** [comment]
Makes sense - interested in submitting a PR?

**Comment by mcattle** [comment]
I'll see what I can come up with this weekend.

**Comment by mcattle** [comment]
Submitted Pull Request #722

**Comment by mcattle** [comment]
Thanks for merging the PR, closing issue.
