### ISSUE TITLE
Problem with [FromQuery] and IDictionary<>

### ISSUE THREAD

**Issue by gaui** [domaindrivendev/Swashbuckle.AspNetCore#720]
We are using Swashbuckle.AspNetCore 2.4.0. We have the following function in our controller:

```
[HttpPost("{company}/{system}/{type}")]
[ProducesResponseType(typeof(IEnumerable<DocumentDTO>), 200)]
[ProducesResponseType(typeof(void), 400)]
[ProducesResponseType(typeof(void), 500)]
public async Task<IActionResult> CreateDocument(string company, string system, string type, [FromQuery] IDictionary<string, string> query, [FromBody] IFormFile file)
```

Which produces the following Swagger Spec:

```
  '/Documents/{company}/{system}/{type}':
    post:
      tags:
        - Documents
      operationId: DocumentsByCompanyBySystemByTypePost
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: company
          in: path
          required: true
          type: string
        - name: system
          in: path
          required: true
          type: string
        - name: type
          in: path
          required: true
          type: string
        - name: query
          in: query
          required: false
          type: object
        - name: file
          in: body
          required: false
          schema:
            $ref: '#/definitions/IFormFile'
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/DocumentDTO'
        '400':
          description: Bad Request
        '500':
          description: Server Error
```

`[FromQuery]` works correctly, it produces the `in: query` but because of the `IDictionary<>` type, it returns `type: object` but that results in a invalid Swagger Spec:

```
Errors

Schema error at paths['/Documents/{company}/{system}/{type}'].post.parameters[3]
should NOT have additional properties
additionalProperty: type, name, in, required
Jump to line 171

Schema error at paths['/Documents/{company}/{system}/{type}'].post.parameters[3].required
should be equal to one of the allowed values
allowedValues: true
Jump to line 171

Schema error at paths['/Documents/{company}/{system}/{type}'].post.parameters[3].in
should be equal to one of the allowed values
allowedValues: body, header, formData, path
Jump to line 172

Schema error at paths['/Documents/{company}/{system}/{type}'].post.parameters[3].type
should be equal to one of the allowed values
allowedValues: string, number, boolean, integer, array, file
Jump to line 174
```

When I change `type: object` to `type: string` it works correctly and the Swagger Spec is valid.

Is this a bug or can I somehow override this behavior?

**Comment by domaindrivendev** [comment]
Do you expect the dictionary of strings to be represented in the query string as a single key value pair? If so, what is the expected format of the value?

Although SB clearly doesn’t handle this well, I also think the Swagger spec doesn’t support query string values of type dictionary

**Comment by gaui** [comment]
No of course I don't expect that. I'm not sure, the spec allows array - maybe that's more appropriate? I monkey patched this by creating an OperationFilter implementation that changes "object" to "string" and that makes the schema valid on editor.swagger.io

**Comment by domaindrivendev** [comment]
Could you provide an example request to demonstrate how the dictionary might be populated on the server-side - it will help me understand your use case a little better because it's still not clear to me

**Comment by gaui** [comment]
The parameter declaration is the following: `[FromQuery] IDictionary<string, string> queryString`
Sample input into the API: `?key1=val1&key2=val2&key3=val3`

Which creates a dictionary like the following:

```
{
  "key1": "val1",
  "key2": "val2",
  "key3": "val3"
}
```

**Comment by domaindrivendev** [comment]
Now that I understand what you're trying to do a little better, I believe this is a dup of #298. In a nutshell, Swagger 2.0 (the version currently used by Swashbuckle) _does not_ provide a way to describe dynamic query parameters.

I believe this is supported in the latest version which SB doesn't yet support - that's being tracked n #671

**Comment by caryttd** [comment]
While using the latest version of Swashbuckle (
Swashbuckle.AspNetCore 6.1.2, 
Swashbuckle.AspNetCore.Swagger 6.1.2, 
Swashbuckle.Core 5.6.0,
Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting 4.2.0),

I believe I have encountered the same problem when using [fromQuery] on a Dictionary parameter.

E.g.

`[HttpGet]
public JsonResult Index([FromQuery(Name="properties")] IDictionary<string, string> properties)`
will be ignored.

`[HttpGet]
public JsonResult Index(IDictionary<string, string> properties)`
will be detected and shown on Swagger.

Do you know if there is any workaround or if any current work is being done to resolve this problem?
