### ISSUE TITLE
Custom dictionary properties are not present in generated schema

### ISSUE THREAD

**Issue by dmitriyett** [domaindrivendev/Swashbuckle.AspNetCore#723]
Hi,

As mentioned in swagger [spec](https://swagger.io/docs/specification/data-models/dictionaries/#fixed-keys) it is possible to add fixed keys to map-like objects by marking such fields as `Required`. My naive attempt was:

    [Route("/api/[controller]")]
    public class TestController : Controller
    {
        [HttpPost]
        [Consumes("application/json")]
        [Produces("application/json")]
        [ProducesResponseType(200)]
        public IActionResult Demo([FromBody] Model model)
        {
            throw new NotImplementedException();
        }
    }

    public class Model : Dictionary<string, string>
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Test { get; set; }
    }

and generated schema looks like this:

          {
            "name": "model",
            "in": "body",
            "required": false,
            "schema": {
              "type": "object",
              "additionalProperties": { "type": "string" }
            }
          }

All required properties are missing and therefore are not present in Swagger UI:

![image](https://user-images.githubusercontent.com/8244145/39701444-cf85e372-5209-11e8-8742-074ff5ea1861.png)

Correct schema, as I understand, should be:

          {
            "name": "model",
            "in": "body",
            "required": false,
            "schema": {
              "type": "object",
              "required": [ "name", "test" ],
              "properties": {
                "id": {
                  "format": "int32",
                  "type": "integer"
                },
                "name": { "type": "string" },
                "test": { "type": "string" }
              },
              "additionalProperties": { "type": "string" }
            }
          }

My env:
Visual Studio 2017 15.6.7
ASP.NET Core: 2.0.7
Swashbuckle.AspNetCore: 2.4.0
Also here is a repository to reproduce the issue: https://github.com/dmitriyett/SwaggerFixedKeysIssue

Hope that helps :)
Thanks in advance.

PS: I'm currently looking for a workaround, I'll post it here if I'll find any.

**Comment by domaindrivendev** [comment]
Ultimately I would say this is a dup of #675.

Independently of Swashbuckle, I don't believe you should subclass `Dictionary` to bind this type of object. In your example, if you submit a payload that contains the "fixed" properties, the values will be added as dictionary items but won't be assigned to their corresponding properties in the `Model` object.

Instead, I would suggest you update your `Model` to use the `JsonExtensionDataAttribute` which is exactly for this type of request/model binding:

```csharp
public class Model
{
    [Required]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Test { get; set; }

    [JsonExtensionData]
    public IDictionary<string, object> DynamicProperties { get; set; }
}
```

If you do this, your API will behave exactly as you've described above and Swashbuckle will describe it exactly as you've described above.

**Comment by dmitriyett** [comment]
@domaindrivendev thanks a lot, that works
