### ISSUE TITLE
Issue with hyphens '-' in request path

### ISSUE THREAD

**Issue by plachor** [domaindrivendev/Swashbuckle.AspNetCore#727]
Hi @domaindrivendev,

my issue is related to swagger-ui ;/ still I have checked it against latest dist of swagger-ui and it's working there correctly.  

When I `expand` any operation block that has **hyphen** in request path (example '/api/tes-t') it is collapsing immediately for the first time being clicked. This does not occur if no hyphen is in path. For any subsequent try of expending and collapsing of same operation it is working correctly than. 

I have attached a simple reproduction project. Just start and check your self. 
Execute `dotnet run` from within `netcore-reproduction` folder and navigate to `http://localhost:10363/swagger/`. 

Expand `get `or any other method from `Test` operations block. 

If you open `index.html` form `swaggeui-dist` folder with `http://localhost:10363/swagger/v1/swagger.json` you will see that is working correctly. The `swaggeui-dist` folder was taken from latest `master` branch of swagger-ui repository.

Here you have reproduction project: [test-sample.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/1994289/test-sample.zip)

**Comment by plachor** [comment]
I done some local tests and updating "swagger-ui-dist": "3.13.2" => "3.14.1" did resolve the issue. When do  you plan to update this package (`Swashbuckle.AspNetCore.SwaggerUI`) ?

**Comment by plachor** [comment]
Hi again, any update on this issue? Can you share at least rough estimation like this week, next month or Q4.2019 :)

**Comment by domaindrivendev** [comment]
This is now fixed and available as of v2.5.0
