### ISSUE TITLE
Allow for [FromQuery]IDictionary<string,string> to be flagged as collectionFormat multi

### ISSUE THREAD

**Issue by Tarig0** [domaindrivendev/Swashbuckle.AspNetCore#733]
## VERSION: ##
2.4.0

## STEPS TO REPRODUCE: ##
1. Start empty
2. Add swashbuckle
3. Add a function with the following sig 
```c#
public IActionResult Test([FromQuery]IDictionary<string, string> test)
```
## EXPECTED RESULT: ##
This should be documented as a multi param

## ACTUAL RESULT: ##
Examine that the json generated does not set the multi flag

passed that it's up to the UI to actually allow me to pass ?a=b&c=d to be bound to test

## ADDITIONAL DETAILS ##

> https://swagger.io/docs/specification/2-0/describing-parameters/

multi | Multiple parameter instances rather than multiple values. This is only supported for the in: query and in: formData parameters. | foo=value&foo=another_value
-- | -- | --

**Comment by domaindrivendev** [comment]
Multi is for collections not dictionaries - i.e. it's a _collectionFormat_. Try changing the parameter type in your action to `IEnumerable<string>` and it should be described correctly.

**Comment by Tarig0** [comment]
you are correct I saw foo=value&foo2=value instead of reality.

I'm not sure what the correct documentation is for.

?*=* ....

**Comment by Tarig0** [comment]
looks like I'm looking for #671 specifically #720

**Comment by domaindrivendev** [comment]
Yep I suspected that might be the case. Going to close this as they’re the ones to track
