### ISSUE TITLE
Added Deep Link support 

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle.AspNetCore#737]
It appears that after the upgrade to swagger 3.0 we lost all deep linking support: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/deep-linking.md

**Comment by domaindrivendev** [comment]
I guess it's disabled by default in swagger-ui 3x. You should be able to explicitly enable it with the following:

```csharp
app.UseSwaggerUI(c =>
{
    ...
    c.EnableDeepLinking();
});
```
