### ISSUE TITLE
Respect the LowercaseUrls Routing Setting

### ISSUE THREAD

**Issue by RehanSaeed** [domaindrivendev/Swashbuckle.AspNetCore#74]
When using lower case URL's in conjunction with the special `[controller]` string in the route like so:

```
services.ConfigureRouting(
    options =>
    {
        options.LowercaseUrls = true;
    });

[Route("bar/[controller]")]
public class FooController : Controller {}
```

The generated URL's that Swagger displays has an upper-case controller name:

> bar/Foo

**Comment by irontoby** [comment]
Wasn't sure whether to comment here or open a new ticket... considering the (default for ASP.NET Core)[https://github.com/aspnet/Announcements/issues/194] is now camel case, shouldn't camel-case controller names now be the default?

I even explicitly have

            services.AddMvc()
                .AddJsonOptions(opt =>
                {
                    opt.SerializerSettings.ContractResolver =
                        new CamelCasePropertyNamesContractResolver();
                });

in my `Startup.cs` yet I'm getting PascalCased controller names in Swagger (though property names are indeed camelCase).

Is there currently a way to get camelCase controller names and still use the generalized `[Route("api/[controller]")]` on my controllers?

**Comment by andre-artus** [comment]
What is the status on this? I'm still getting Pascal case.

**Comment by jonsa** [comment]
I too wished that the document generator followed the routing configuration.

As a workaround I use the suggested [fix](https://gist.github.com/rafalkasa/01d5e3b265e5aa075678e0adfd54e23f) in https://github.com/domaindrivendev/Swashbuckle/issues/834 (it just needs some `using` tweaks)

**Comment by dataspun** [comment]
I found the UI will output api/foo given:

```
[Route("api/[controller]")]
public class fooController : Controller
```

**Comment by wickdninja** [comment]
I was running into the same issue using dotnetcore 2.1, and hacked this solution together.
 
I wouldn't doubt that there is a better way, but this worked for me.

```
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger(c =>
            {
                c.PreSerializeFilters.Add((document, request) =>
                {
                    var paths = new Dictionary<string, PathItem>();
                    foreach (var item in document.Paths)
                    {
                        var key = item.Key.ToLowerInvariant();
                        var value = item.Value;
                        paths.Add(key, value);
                    }
                    document.Paths.Clear();
                    foreach (var pathItem in paths)
                    {
                        document.Paths.Add(pathItem.Key,pathItem.Value);
                    }
                });
            });
         }
```

... Also probably would be a little "cleaner" if `Concat` was used to repopulate `document.Paths` instead of a foreach loop.

**Comment by FDUdannychen** [comment]
+1 to @wickdninja the code snippet can be simpler
            app.UseSwagger(o =>
            {
                o.PreSerializeFilters.Add((document, request) =>
                {
                    document.Paths = document.Paths
                        .ToDictionary(p => p.Key.ToLowerInvariant(), p => p.Value);
                });
            });

**Comment by domaindrivendev** [comment]
On further reflection, I'm not convinced `ApiExplorer` _ought_ to honor the `RouteOptions.LowercaseUrls` flag. From my understanding, that flag is used to indicate the casing of _generated_ URL's - i.e. when using `UrlHelper.RouteUrl` in razor pages etc. but doesn't have any baring on the routing of incoming requests to actions. Even with this flag set, the framework will ignore casing for incoming requests.

If you still want to _advertise_ them in lowercase, then I think the workarounds suggested above are sufficient options.

**Comment by SimonTouchtech** [comment]
This was apparently changed/fixed in `ApiExplorer` in https://github.com/aspnet/Mvc/issues/8006
