### ISSUE TITLE
Cannot include nicely formatted XML in comments

### ISSUE THREAD

**Issue by Mattacks** [domaindrivendev/Swashbuckle.AspNetCore#745]
(Some of) our APIs take strings containing XML.
The only way to express these in C# XML comments is to replace < with &lt; (etc.)
These are then displayed in the Swagger UI as &lt; (etc.) making it incomprehensible (and incorrect).

We need a way to have such characters displayed 'normally' in the UI.
It also makes it impossible to include the XML declaration which is part of the XML-in-the-string payload.
Characters include < > " \

**Comment by esbenbach** [comment]
I might speak out of turn, but this sound more like an swagger-ui issue than a swashbuckle issue (not 100% certain of course).

Typically when encountering this type of problem i resort to CDATA, have you tried that, it should allow you to write < > " \ etc without encoding it.

**Comment by Mattacks** [comment]
@esbenbach 
Yes, I had tried CDATA - it's the same.
I wasn't sure which repo to raise the issue in, and I didn't want to spam them, all - happy for someone to suggest a better one.
Matt

**Comment by domaindrivendev** [comment]
I'm using latest version (v2.5.0) and CDATA as suggested, and am not seeing an issue:

![screenshot](https://user-images.githubusercontent.com/1434343/41010749-400539fe-68ee-11e8-9a92-8bd39618fb07.png)

Here's the code:
```csharp
/// <summary>
/// Create a new Product
/// </summary>
/// <remarks>
/// Example: <![CDATA[ <foo></foo> ]]> 
/// </remarks>
/// <param name="product"></param>
/// <returns></returns>
[HttpPost("api/products")]
[ProducesResponseType(201)]
public ActionResult<Product> Create([FromBody, Required]Product product)
{
    ...
}
```
