### ISSUE TITLE
HTTP 200 should be OK, not SUCCESS

### ISSUE THREAD

**Issue by dariusdamalakas** [domaindrivendev/Swashbuckle.AspNetCore#755]
Hi,

HTTP 200 response status code is `OK`, and not `SUCCESS` according to [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)

There are unit tests in repository which assert that HTTP 200 is `SUCCESS`.  Not sure if this is swashbuckle or AspNetCore to be blamed for this.

[{ "200", new Response { Description = "Success", Schema = new Schema { Ref = "#/definitions/foo" } } },](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/12aee13da3e5f6d48033b3aa663655c9ba3ba788/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Annotations/XmlCommentsOperationFilterTests.cs#L72)

**Comment by domaindrivendev** [comment]
I think you're misinterpreting the meaning of the `description` field the Swagger Response object. It's just an arbitrary description of the response. It could be anything from "the Cart was successfully created", to "Success" to "OK". Swashbuckle provides a generic value based on the class of response code (i.e. 1xx, 2xx. 3xx etc.). As it's just a textual description that would ideally be customized to individual operations, there is no specific value that it ought to be.

**Comment by dariusdamalakas** [comment]
@domaindrivendev thanks for explanation.    so any `1xx` response would be `Informational response`, and any `3xx` would be `Redirection`?

**Comment by domaindrivendev** [comment]
That's correct. Like I said, it's just a textual description for humans and Swashbuckle takes a basic pass at filling it in. See the following code to see exactly how it does this:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v2.5.0/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs#L312

NOTE: If you need to apply more detailed descriptions for any given operation, you can do so via XML comments (via the `<response>` tag).
