### ISSUE TITLE
README.md includes deprecated code example

### ISSUE THREAD

**Issue by nlaveck** [domaindrivendev/Swashbuckle.AspNetCore#757]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#customize-the-action-selection-process.

I'm working with code that uses the example in this section to use API versioning:

```
c.DocInclusionPredicate((docName, apiDesc) =>
{
    var versions = apiDesc.ControllerAttributes()
        .OfType<ApiVersionAttribute>()
        .SelectMany(attr => attr.Versions);

    return versions.Any(v => $"v{v.ToString()}" == docName);
});
```
ApiDescriptionExtensions.ControllerAttributes is now deprecated.  The deprecation message seems to apply specifically to filters so I am unsure of what I should change this to in the `DocInclusionPredicate` function.

**Comment by gtaylor1981** [comment]
I had this problem too, however I noticed the `Obsolete` attribute mentions the alternative "_Use OperationFilterContext.ControllerActionDescriptor_", available using a bit of casting:

    c.DocInclusionPredicate((docName, apiDesc) =>
    {
        var controllerActionDescriptor = apiDesc.ActionDescriptor as ControllerActionDescriptor;
        var attributes = controllerActionDescriptor?.GetControllerAndActionAttributes(true)
                         ?? Enumerable.Empty<object>();

        var versions = attributes.OfType<ApiVersionAttribute>().SelectMany(attr => attr.Versions);

        return versions.Any(v => $"v{v.ToString()}" == docName);
    });

**Comment by domaindrivendev** [comment]
Docs updated - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-the-action-selection-process

**Comment by Johanneshn** [comment]
@Monte-Christo try this:

`var test = methodInfo.DeclaringType.GetTypeInfo().GetCustomAttributes(true);`
