### ISSUE TITLE
Content-Type value is not correct

### ISSUE THREAD

**Issue by heyixiaoran** [domaindrivendev/Swashbuckle.AspNetCore#760]
Hi . I get a wrong Content-Type value. 

When I post a request . Curl is like "curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' ...." in Swashbuckle.AspNetCore 2.4 & 2.5

But If I use Swashbuckle.AspNetCore 1.1.0 . Curl is like “curl -X POST --header 'Content-Type: undefind' ....”
I heard this value is set in swagger-ui . So I want to need some help. Thanks.

`  

        [HttpPost("Login")]   
        public async Task<IActionResult> Login([FromForm] LoginUser user)    
        {  
                .....  
        }
`

I asked this in swagger-ui  [https://github.com/swagger-api/swagger-ui/issues/4621#issuecomment-395918513](url)
But it seem probably is Swashbuckle .

**Comment by domaindrivendev** [comment]
This is a dup of #213. Support for form requests (e.g. file uploads etc.) is somewhat lacking and is def a priority to improve. In the meantime though, if you read through the referenced issue, you should see some relatively trivial workarounds.
