### ISSUE TITLE
Can let Swashbuckle.AspNetCore.Cli be .NET Core tool?

### ISSUE THREAD

**Issue by seanmars** [domaindrivendev/Swashbuckle.AspNetCore#761]
.NET Core 2.1 add the tool for cli,  would we get the tool version of Swashbuckle.AspNetCore.Cli?

**Comment by domaindrivendev** [comment]
I don't understand your request - please elaborate with an example.

**Comment by seanmars** [comment]
Just want to know the `Swashbuckle.AspNetCore.Cli` will go to [.Net Core global tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)?

**Comment by PRIMETSS** [comment]
Had same issue if installed via NuGet UI Manager, but if installed via PM Console

Package Manager : Install-Package Swashbuckle.AspNetCore

worked. Same version got installed 2.5.0

**Comment by richardgavel** [comment]
The Swashbuckle.AspNetCore.Cli is not a true .Net Core global tool, one that can be installed globally via "dotnet tool install". If you try, you get the following error. It's a tool that can only be used as a DotNetTool reference in csproj file.

`error NU1212: Invalid project-package combination for Swashbuckle.AspNetCore.Cli 4.0.1. DotnetToolReference project style can only contain references of the DotnetTool type
The tool package could not be restored.`

**Comment by domaindrivendev** [comment]
I think this issue is clear at this point - any takers on this thread interested in submitting a PR?

**Comment by kant2002** [comment]
@domaindrivendev could you take a look at PR ?
