### ISSUE TITLE
Cannot determine if attribute is applied to controller or action

### ISSUE THREAD

**Issue by rcollette** [domaindrivendev/Swashbuckle.AspNetCore#764]
SwaggerGen 2.5

Previous Code
```
var authorization = context.ApiDescription.ActionAttributes()
                                    .OfType<AuthorizeAttribute>().SingleOrDefault() ??
                                    context.ApiDescription
                                    .ControllerAttributes()
                                    .OfType<AuthorizeAttribute>().SingleOrDefault();

```
CurrentCode required due to obsoletion
```
            var authorization1 = context.ControllerActionDescriptor.GetControllerAndActionAttributes(true)
                .OfType<AuthorizeAttribute>();
```

In the current release I am unable to prioritize attributes that are applied to methods over attributes that are applied to the controller because there is no way, that I can discern, to determine what the attributes returned from `GetControllerAndActionAttributes` are applied to.

**Comment by pierslawson** [comment]
Related to this, the help around operation filters needs updating to not use the obsolete functionality: 
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#operation-filters

**Comment by domaindrivendev** [comment]
See updated docs https://github.com/domaindrivendev/Swashbuckle.AspNetCore#operation-filters. As of v3.0.0, the canonical way of accessing action or controller attributes in a filter is via `context.MethodInfo`.

**Comment by rcollette** [comment]
Excellent. This seems a bit closer to the standard .NET Core methods.

**Comment by dandohotaru** [comment]
in situations where all levels of a particular attribute (say `ProducesAttribute` ) need to be looked up, i ended up with something along these lines

```
var globalAttributes = context.ApiDescription.ActionDescriptor.FilterDescriptors.Select(p => p.Filter);
var controlerAttributes = context.MethodInfo?.DeclaringType?.GetCustomAttributes(true);
var methodAttributes = context.MethodInfo?.GetCustomAttributes(true);
var produceAttributes = globalAttributes
	.Union(controlerAttributes)
	.Union(methodAttributes)
	.OfType<ProducesAttribute>();
```
