### ISSUE TITLE
Use DisplayNameAttribute and DescriptionAttribute to set schema properties - Enhancement

### ISSUE THREAD

**Issue by jonmeyerson** [domaindrivendev/Swashbuckle.AspNetCore#765]
It would be a good enhancement if DisplayNameAttribute and DescriptionAttribute were used to fill out a Schema Title and Description properties respectively. Currently it is not possible to fully implement this using a ISchemaFilter beyond JsonObjectContract because the other types require knowing the class the Primitive/List/Dictionary is defined in. If the defining type were available in SchemeFilterContext then it would be possible to read the metadata. 

PS: I tried using IDocumentFilter to read these attributes and set the scheme but this runs into the problem of processing over the same objects multiple times due to apis reusing the same schema elements, also there is  the problem of when looking into collections of running into an infinite loop. 
See https://stackoverflow.com/a/50828780/4893516

**Comment by domaindrivendev** [comment]
Seems reasonable - I'll add it to the backlog for now. Might be quick if you submit a PR though 😉

**Comment by SmegheadSev** [comment]
It's been a while since this was touched on but I'd like to second this enhancement. I have complex parameter types that I would love to be able to use attribute descriptions on the properties.
