### ISSUE TITLE
[FeatureRequest] RangeAttribute DataAnnotation only supports Int32 but not double

### ISSUE THREAD

**Issue by C0unt23r0** [domaindrivendev/Swashbuckle.AspNetCore#771]
.NET Core 2.1
Swashbuckle.AspNetCore 2.5.0

The RangeAttribute also supports initialising a new instance by using the specified minimum and maximum as double values. Swashbuckle ignores values wich exceeds the minimum and maximum of the Int32 Datatype. I've checked the JSON Schema and JSON Schema Validation specification but i've seen no such limitations. 

For my understanding changes has to be made in the following files:

Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaExtensions.cs (SwaggerGen.SchemaExtension)
Swashbuckle.AspNetCore.Swagger/Model/SwaggerDocument.cs (Swagger.Schema)

Thx
Jan

**Comment by mrtristan** [comment]
perhaps while in this realm we could have support for one-sided limits. i'm currently trying to figure out how to have something like `[MinimumAttribute(1)]` without explicitly specifying a maximum. (use case is a parameter for `pageIndex` in pagination... doesn't make sense to go below 1, and not thinking it makes sense to explicitly specify a maximum.

**Comment by domaindrivendev** [comment]
Added this with 7493a079ba25ce6ad9eb6bee83b9483bf8a46a96. Will be generally available with the upcoming 4.0.0 release (exact date TBD). In the meantime, you can try out the preview package from myget.org:

7493a079ba25ce6ad9eb6bee83b9483bf8a46a96
