### ISSUE TITLE
Custom endpoint without the final slash has a bad redirect

### ISSUE THREAD

**Issue by AnthonyMastrean** [domaindrivendev/Swashbuckle.AspNetCore#774]
> Migrated from https://github.com/swagger-api/swagger-ui/issues/4662

### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 67
 - Method of installation: [NuGet](https://www.nuget.org/packages/Swashbuckle.AspNetCore/)
 - Swagger-UI version: 3.12.2
 - Swagger/OpenAPI version: 2.0

### Content & configuration

I'm using a custom [route template](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#change-the-path-for-swagger-json-endpoints) and [route prefix](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#change-relative-path-to-the-ui) per the documentation.

```csharp
app.UseSwagger(options =>
{
    options.RouteTemplate = "nvdm-vrf/api-docs/{documentName}/swagger.json";
});

app.UseSwaggerUI(options =>
{
    options.RoutePrefix = "nvdm-vrf/api-docs";
    options.SwaggerEndpoint("/nvdm-vrf/api-docs/v1/swagger.json", "NVDM VRF API v1");
});
```

### Describe the bug you're encountering

When I navigate to a custom Swagger endpoint, without a final forward-slash (`/`), I am redirected to an incorrect endpoint. Part of the custom route prefix is duplicated.

For example:

```
http://localhost/nvdm-vrf/api-docs
```

Redirects to:

```
http://localhost/nvdm-vrf/nvdm-vrf/api-docs/
```

### To reproduce...

1. Create an ASP.NET Core web api or web application project
2. Install Swashbuckle.AspNetCore via the normal NuGet.org instructions
3. Configure a custom route prefix (changing the options per the linked documentation)
4. Navigate to the Swagger UI endpoint _without_ the final slash (so you hit the built-in redirect)

### Expected behavior

The normal built-in redirect to the endpoint including the final slash should occur.

### Screenshots

![swagger-redirect](https://user-images.githubusercontent.com/217842/41601960-b62cabee-73a7-11e8-9acd-3a982aebab49.gif)

### Additional context or thoughts

I checked and the redirect works as expected with the default endpoint.

```csharp
app.UseSwagger();
app.UseSwaggerUI(options =>
{
    options.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});
```

The endpoint:

```
http://localhost/swagger
```

Redirects to:

```
http://localhost/swagger/
```

**Comment by domaindrivendev** [comment]
Which version of Swashbuckle are you using - I believe this was fixed recently

**Comment by AnthonyMastrean** [comment]
I'm on 2.4.0. I see 2.5.0 out there, but I don't see any release notes.

**Comment by AnthonyMastrean** [comment]
Fixed in 2.5.0

**Comment by domaindrivendev** [comment]
Your browser may be caching the old bogus redirect. Try incognito

**Comment by AnthonyMastrean** [comment]
Yep, it was a stale cache!
