### ISSUE TITLE
parameter serialisation 

### ISSUE THREAD

**Issue by szymonzmyslony** [domaindrivendev/Swashbuckle.AspNetCore#775]
Hello,
I need to be able not to expand query parameters to primitives but keep them as object so that I can generate type definitions on frontend. I know it a feature of Open Api 3.0 but it is yet to be implemented here, what would be the place to look at if I wanted to change that?

**Comment by domaindrivendev** [comment]
Please provide more information, including code examples. Otherwise, I'm not going to be able to help

**Comment by domaindrivendev** [comment]
Insufficient info and no response - closing for now
