### ISSUE TITLE
How do I keep track of compatibility?

### ISSUE THREAD

**Issue by AnthonyMastrean** [domaindrivendev/Swashbuckle.AspNetCore#776]
I'm tracking another issue directly in Swagger UI (https://github.com/swagger-api/swagger-ui/issues/4663#issuecomment-398941225) and they recommend

> can you try the latest version (3.17.1)?

But, I don't see this listed in the [compatibility matrix](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#compatibility) yet. How do I keep track of the roadmap and what's going to be supported next?

**Comment by domaindrivendev** [comment]
We don't have a formal roadmap. If people need a change that comes with the latest version, I can turn it around fairly quick. I'll get 3.17.1 out with the 3.0.0 release (coming soon)

**Comment by domaindrivendev** [comment]
See f540071b9d27c4eac92484aa3bffc1a6eac9e256. This will be generally available with the 3.0.0 release (coming soon). In the meantime, you can pull down the latest preview from myget.org to try it out.

**Comment by shockey** [comment]
Hey @domaindrivendev, any particular reason you're pinning Swagger UI versions in your releases?

Most projects that consume Swagger UI use a package manager to pull in the latest version within a defined range (for example, `3.*.*`).

**Comment by domaindrivendev** [comment]
@shockey - the swagger-ui assets are pulled and embedded into a nuget package at build-time. So, a given version of SB has to be tied to a given version of the SwaggerUI. I think the "most projects" you're referring to are not deployed and packaged as Nuget packages - but please correct me if I'm wrong

**Comment by shockey** [comment]
@domaindrivendev, definitely not, I know very little about Nuget, or .NET in general, so I'm not sure if there's any way to resolve the dependency at runtime 😄 thanks for the clarification!
