### ISSUE TITLE
[Feature request] OAuth with required/autoset scopes.

### ISSUE THREAD

**Issue by MelnikovIG** [domaindrivendev/Swashbuckle.AspNetCore#782]
Now we should manually set scope checkboxes, i assume it would be better if each defined scope have configuration to have default selection value. Also some scopes should be required, and it is no sense to edit them. So please provide configuration to mark scope as selected ✅  with edit possibility, or required without edit possibility.

**Comment by domaindrivendev** [comment]
This feature should be directed to the [swagger-ui project](https://github.com/swagger-api/swagger-ui), not Swashbuckle.
