### ISSUE TITLE
[Required] attribute on Query parameter input is not honoured

### ISSUE THREAD

**Issue by fiksen99** [domaindrivendev/Swashbuckle.AspNetCore#783]
Create a new web api project, using ASP.NET Core 2.0 and .NET Framework 4.6.2, targeting Swashbuckle.AspNetCore v2.2.0.

In your autogenerated controller, add a parameter to the default GET endpoint, mark it [FromQuery] and [Required].

Run the web app and browse to the generated swagger.

Observe that the query input parameter is marked as "required":false
![image](https://user-images.githubusercontent.com/2607336/42185923-8563263e-7dff-11e8-85a2-846063b30e83.png)

![image](https://user-images.githubusercontent.com/2607336/42185901-75a90074-7dff-11e8-8465-08a47a07be3c.png)

**Comment by domaindrivendev** [comment]
Support for this was merged with #749. It will be generally available in the 3.0.0 release (coming soon) and in the meantime you can pull down the preview package from myget.org.
