### ISSUE TITLE
Swagger page does not refresh to show operations after Authentication with Identity Server 4

### ISSUE THREAD

**Issue by kieronjadavies** [domaindrivendev/Swashbuckle.AspNetCore#786]
Hello.

I am using Swashbuckle 2.5 with Identity Server 4.  On the swagger page the operations are omitted until authorization, The authorization button successfully makes the call to ID4 and you can authorize through windows authentication successfully.  On the swagger page the following comes up - 

![image](https://user-images.githubusercontent.com/36955972/42226618-47fe7d42-7ed7-11e8-901d-8cf8cfdb37c6.png)

When I close this the Swagger page still does not show the operations.

I have added the following to my document filter - 

        swaggerDoc.Security = new List<IDictionary<string, IEnumerable<string>>>()
        {
            new Dictionary<string, IEnumerable<string>>()
            {
                { "oauth2", new string[]{ "********" } }
            }
        };

And I have added a security requirement to the SwaggerGen options - 

options.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
                                         {
                                              { "oauth", new string[] { "*******" } }
                                         });

I am wondering why the page is not updating automatically with the operations when it returns from Identity Server 4.   If I refresh the page manually then it loses the authentication (where is this stored?  In the session?)

With an earlier version of Swashbuckle (1.2) The page automatically refreshed and because it was authenticated the operations showed up.   

Any help would be much appreciated.

**Comment by domaindrivendev** [comment]
This is a swagger-ui issue which is being tracked [here](https://github.com/swagger-api/swagger-ui/issues/4734)

**Comment by martincostello** [comment]
Closing as external.
