### ISSUE TITLE
Orleans swagger document generation

### ISSUE THREAD

**Issue by aqa510415008** [domaindrivendev/Swashbuckle.AspNetCore#790]
It is recommended to leave Microsoft.AspNetCore.Mvc.ApiExplorer, which has the flexibility to extend the generated RPC interface documentation. Swashbuckle defines the required ApiDescription.

**Comment by domaindrivendev** [comment]
To be honest, the text above doesn’t make much sense to me. Could you please elaborate with an example?

**Comment by aqa510415008** [comment]
@domaindrivendev 
[Orleans.SwaggerGen](https://github.com/aqa510415008/Orleans.HttpGateway/blob/master/src/Orleans.SwaggerGen/SwaggerGenerator.cs#L37)

This is my Orleans based on Swashbuckle.AspNetCore
  The implementation of the Swagger document generation. You can understand it if you can look it up.


Because Orleans cannot get all the interfaces from IApiDescriptionGroupCollectionProvider. So I redefine ApiDescriptionCollectionProvider and ApiDescription

[ApiDescriptionCollectionProvider](https://github.com/aqa510415008/Orleans.HttpGateway/blob/master/src/Orleans.SwaggerGen/ApiDescriptionCollectionProvider.cs)

[ApiDescription](https://github.com/aqa510415008/Orleans.HttpGateway/blob/21b8256483f3037658f48b0a6a359ff8477a5ca7/src/Orleans.SwaggerGen/ApiDescription.cs)

**Comment by aqa510415008** [comment]
Orleans based on Swashbuckle survival Swagger document component [Swashbuckle.Orleans.SwaggerGen](https://github.com/aqa510415008/Swashbuckle.Orleans.SwaggerGen)
