### ISSUE TITLE
Generated Swagger doc is different between first load and subsequent loads

### ISSUE THREAD

**Issue by wpetrowski** [domaindrivendev/Swashbuckle.AspNetCore#793]
.NET Core 2.0
Swashbuckle.AspNetCore 2.5.0

### Issue

The first time I access `<host>/swagger/v1/swagger.json` after launching my API, I get the following swagger:

```
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Doc Reload"
  },
  "basePath": "/v1",
  "paths": {
    "/v1/api/Values": {
      "get": {
        "operationId": "V1ApiValuesGet",
        // ...
      }
    }
  },
  "definitions": {}
}
```

After the first load, any time I access that json, I get:

```
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Doc Reload"
  },
  "basePath": "/v1",
  "paths": {
    "/api/Values": {
      "get": {
        "operationId": "ApiValuesGet",
        // ...
      }
    }
  },
  "definitions": {}
}
```

(note the difference in the path and the `operationId`)

### Backstory

I've got an API that does versioning in the URL, like so: `https://example.com/v1/api/values`.  My goal is to get the generated Swagger doc to have the version segment in the `basePath` instead of in each route.  I've got an `IDocumentFilter` to do this... almost.  As noted above, it works except for the first time the swagger doc is accessed.

My (simplified) document filter looks like this:

```
public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
{
    var version = "v1";

    swaggerDoc.BasePath = "/" + version;

    foreach (var description in context.ApiDescriptions)
    {
        if (description.RelativePath.StartsWith(version))
        {
            var pathComponents = description.RelativePath.Split('/');
            description.RelativePath = string.Join("/", pathComponents.Skip(1));
        }
    }
}
```

I've also got a trimmed down repo that reproduces the issue over at: https://github.com/wpetrowski/DocReloadBug

P.S. If there's an easier/different way to accomplish what I'm trying to do, I'd be interested to hear it as well. 😄

**Comment by domaindrivendev** [comment]
Filters are for modifying the generated Swagger objects (`SwaggerDocument`, `Operation`, `Schema` etc.). The `ApiExplorer` objects, which are provided by ASP.NET Core framework, should only be used for inspection to drive filter logic. Although this fact is [alluded to in the docs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#operation-filters) I appreciate that it's not immediately obvious.

In any case, you can use the filter below in place of your one to get the result you're looking for:

```csharp
public class BasePathDocumentFilter : IDocumentFilter
{
    public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
    {
        // Set the base path
        swaggerDoc.BasePath = "/" + swaggerDoc.Info.Version;

        // Remove base path from individual paths
        swaggerDoc.Paths = swaggerDoc.Paths
            .ToDictionary(
                entry => entry.Key.Replace(swaggerDoc.BasePath, string.Empty),
                entry => entry.Value
            );
    }
}
```

**Comment by wpetrowski** [comment]
Makes perfect sense.  Thanks for the help!
