### ISSUE TITLE
double is not specified as required

### ISSUE THREAD

**Issue by tomkerkhove** [domaindrivendev/Swashbuckle.AspNetCore#795]
When using `double` it does not mark it as `required` when using `Required` attribute.

When using this complex type:
```csharp
[DataContract]
public class Car
{
   [DataMember]
   [Required]
   public double Speed { get; set; }
}
```

It will generate the following:
```json
"Car": {
  "type": "object",
  "properties": {
    "speed": {
      "format": "double",
      "type": "number"
    }
  }
}
```

### Version
2.5.0

**Comment by domaindrivendev** [comment]
Support for this was merged with #749. It will be generally available in the 3.0.0 release (coming soon) and in the meantime you can pull down the preview package from myget.org.
