### ISSUE TITLE
Can't find Swashbuckle.AspNetCore.Annotations on nuget.org

### ISSUE THREAD

**Issue by rai69** [domaindrivendev/Swashbuckle.AspNetCore#796]
I can't find the package Swashbuckle.AspNetCore.Annotations on nuget.org. Shouldn't it be there?

**Comment by domaindrivendev** [comment]
`master` and hence the repo readme is marginally ahead of the latest nuget release and the Annotations extraction hasn't been released to nuget yet. Working on it though so should be there by end of the day ...

**Comment by domaindrivendev** [comment]
https://www.nuget.org/packages/Swashbuckle.AspNetCore.Annotations/
