### ISSUE TITLE
Issue using locally generated Swashbuckle.AspNetCore.Cli package

### ISSUE THREAD

**Issue by eduherminio** [domaindrivendev/Swashbuckle.AspNetCore#801]
I'm trying to generate a local, test package of `Swashbuckle.AspNetCore.Cli`.
After creating the .nupkg with a new version (no code modifications yet) and correctly restoring it, I'm getting the following error when using it:
```
  Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Swashbuckle.AspNetCore.Swagger, Version=3.0.1.0, Culture=neutral, PublicKeyToken=62657d7474907593'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
     at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
     at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
     at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
     at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args)
```

Package generation commands tried (run at solution level):
`dotnet pack -c Release --include-symbols --include-source -o  C:\local-nuget-repo --version-suffix alpha`
`dotnet pack -c Release --include-symbols --include-source -o  C:\dev\prd\src\local-nuget-repo /p:Version=3.1.0-alpha`

**Comment by sorvis** [comment]
@eduherminio were you able to resolve your issue? I'm seeing a similar issue.

**Comment by eduherminio** [comment]
I did manage to solve it:
Try generating packages of all projects and using generated ones together with your version of `Swashbuckle.AspNetCore.Cli`.
Let me know if that works for you!
