### ISSUE TITLE
Support configuring SwaggerUIOptions and SwaggerOptions in IServiceCollection

### ISSUE THREAD

**Issue by AndreaCuneo** [domaindrivendev/Swashbuckle.AspNetCore#804]
I happened to stumble upon a case where configuring not just the Gen but also the UI and Swagger from the IServiceCollection would make possible to make business core library/templates far more modular.

I'd like to be able to configure SwaggerUIOptions and SwaggerOptions in the IServiceCollection like it's done with ConfigureSwaggerGen()

The main reason is that while the IApplicationBuilder pipeline is "ordered" ... it's a pipeline. So while I configure the pipeline (this before that) I do not care about the configurations. I found Mvc design in just having .UseMvc() clean.

For now I ended up using the extensions below but would be grand if UseSwagger() and UseSwaggerUI() would take the IOptions<> from the ApplicationServices themself.

```
        public static IServiceCollection ConfigureSwagger(this IServiceCollection services, Action<SwaggerOptions> setup)
        {
            return services.Configure(setup);
        }

        public static IServiceCollection ConfigureSwaggerUI(this IServiceCollection services, Action<SwaggerUIOptions> setup)
        {
            return services.Configure(setup);
        }

        public static IApplicationBuilder MyUseSwagger(this IApplicationBuilder app, Action<SwaggerOptions> setup = null)
        {
            return app.UseSwagger(c =>
            {
                foreach (var conf in app.ApplicationServices.GetServices<IConfigureOptions<SwaggerOptions>>())
                    conf.Configure(c);

                setup?.Invoke(c);
            });
        }

        public static IApplicationBuilder MyUseSwaggerUI(this IApplicationBuilder app, Action<SwaggerUIOptions> setup = null)
        {
            return app.UseSwaggerUI(c =>
            {
                foreach (var conf in app.ApplicationServices.GetServices<IConfigureOptions<SwaggerUIOptions>>())
                    conf.Configure(c);

                setup?.Invoke(c);
            });
        }
```

**Comment by twsouthwick** [comment]
This commit https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/594 seems to imply it should work. However, it only seems to work for `app.UseSwagger` and not `app.UseSwaggerUI` for me.
