### ISSUE TITLE
Why was SwaggerSchemaFilter removed in 3.0.0 and what do we use now?

### ISSUE THREAD

**Issue by VictorioBerra** [domaindrivendev/Swashbuckle.AspNetCore#805]
I updated today and my code broke, SwaggerSchemaFilter can no longer be found. Why did we remove this?

I realize we can use SwaggerGenOptions.SchemaFilter but I think the SwaggerSchemaFilterAttribute was easier.

**Comment by domaindrivendev** [comment]
See #799
