### ISSUE TITLE
Content-Type not inferred correctly

### ISSUE THREAD

**Issue by rhegner** [domaindrivendev/Swashbuckle.AspNetCore#809]
In my ASP.NET Core 2.1 application I have an action like this:

    [Route("api/[controller]")]
    [ApiController]
    public class AccountController : ControllerBase
    {
        [AllowAnonymous]
        [HttpPost("TokenLogin")]
        public async Task<ActionResult<LoginResponseModel>> TokenLogin([FromForm] string grant_type, [FromForm] string username, [FromForm] string password, [FromForm] string scope)
        {
            return Ok();
        }
    }

When I invoke this action using Swagger, all the parameters are `null`. Looking at the generated CURL call I see that `Content-Type` is undefined:

    curl -X POST "http://localhost:5000/api/Account/TokenLogin" -H "accept: text/plain" -H "Content-Type: undefined" -d "grant_type=password&username=user&password=pass"

If I run a CURL with the correct `Content-Type: application/x-www-form-urlencoded`, then I get the expected values.

So to me this looks like Swashbuckle does not correctly set the `Content-Type` in this case. 
As a workaround, is there a way to set the `Content-Type` for this specific action explicitly?

I'm using Swashbuckle.AspNetCore 3.0.0 but I experienced the same behavior with version 2.5.0. I've been using Swashbuckle in older applications (ASP.NET Core 1.1) as well, and that does not seem to be a problem with these older applications.

**Comment by AidanRRR** [comment]
Having the same problems.

![image](https://user-images.githubusercontent.com/19323152/42931570-52ae36e0-8b40-11e8-8c1f-99428126027f.png)

![image](https://user-images.githubusercontent.com/19323152/42931610-7453c74c-8b40-11e8-9423-81ed71de2525.png)

Call from js application works well though.

**Comment by domaindrivendev** [comment]
See 5d7d73e63e4b8af685f1b91d8a25b204f5f11449. It includes two changes that should resolve this issue:

1. If there's no `SupportedRequestFormats` surfaced through `ApiExplorer` (ASP.NET Core's built-in metadata provider) AND the request contains `FromForm` parameters, default to `application/x-www-form-urlencoded`
2. If explicit media types are specified through `Consumes` and `Produces` attributes, use those values in the generated Swagger JSON.

These changes will be generally available in the upcoming 4.0.0 release. Exact date still TBD but in the meantime you can use the preview packages that are being pushed to myget.org:

https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore

**Comment by mmikirtumov** [comment]
Hi @domaindrivendev ,

How can we get the version 4.0.0?
When are you going to release the mentioned version?

Thanks

**Comment by domaindrivendev** [comment]
Apologies for the delay here. I have several enhancements queued up in master that will break the public/config API and so would like to release them all together rather than having a series of major version releases in quick succession with breaking changes. As you can see from the [4.0.0 milestone](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/6), there's 1 feature that's holding things up. I'm trying to get that resolved ASAP. If I can't get that resolved soon, I may have to resort to separate releases, each with breaking changes :(

So, stay tuned and thanks for your patience.

**Comment by xrain0610** [comment]
if use 3.0 , can use this to fix：

create a OperationHeader：
```
public class AddHeaderParameter : IOperationFilter
    {
        public void Apply(Operation operation, OperationFilterContext context)
        {
           operation.Consumes.Add("application/x-www-form-urlencoded");
        }
    }
```

**Comment by kgrosvenor** [comment]
> if use 3.0 , can use this to fix：
> 
> create a OperationHeader：
> 
> ```
> public class AddHeaderParameter : IOperationFilter
>     {
>         public void Apply(Operation operation, OperationFilterContext context)
>         {
>            operation.Consumes.Add("application/x-www-form-urlencoded");
>         }
>     }
> ```

How do you use that?

**Comment by exiach** [comment]
> > if use 3.0 , can use this to fix：
> > create a OperationHeader：
> > ```
> > public class AddHeaderParameter : IOperationFilter
> >     {
> >         public void Apply(Operation operation, OperationFilterContext context)
> >         {
> >            operation.Consumes.Add("application/x-www-form-urlencoded");
> >         }
> >     }
> > ```
> 
> How do you use that?

Hi @kgrosvenor  here there a example how to use a IOperationFIlter in [stackoverflow](https://stackoverflow.com/questions/41141137/how-can-i-tell-swashbuckle-that-the-body-content-is-required)

**Comment by PokeyTheCat** [comment]
I'm using the 4.0.1 _Swashbuckle.AspNetCore_ and _Swashbuckle.AspNetCore.Annotations_ packages from nuget. I'm also on asp.net core 2.1. I was able to get my endpoint working correctly in swagger with the following annotations (SwaggerOperation being the one that makes it work I think):

>[Consumes("application/x-www-form-urlencoded")]
>[SwaggerOperation(Consumes = new string[] { "application/x-www-form-urlencoded" })]

Using this method I dont think you'd need to deal with the IOperationFilter.
