### ISSUE TITLE
Parameter type issue when binding from form data

### ISSUE THREAD

**Issue by JimmyHannon** [domaindrivendev/Swashbuckle.AspNetCore#81]
When binding parameter data from the form data using the FromForm attribute the generated parameter type is "form" instead of "formData". If i am right this value is not supported in the swagger spec. This causes the try it out to make a request without the parameters.

Is there a solution in the make or can i contribute?

**Comment by domaindrivendev** [comment]
Sounds like a bug - absolutely please feel free to contribute

**Comment by RemyArmstro** [comment]
We were running into the same issue.  Created pull request with possible fix: [https://github.com/domaindrivendev/Ahoy/pull/95](PR)

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"
