### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by preese13** [domaindrivendev/Swashbuckle.AspNetCore#810]
Trying to update the readme to include the security requirement definition for an API-key scheme.  It wasn't in there and I lost a lot of time figuring it out. Keep getting a 403

**Comment by domaindrivendev** [comment]
I think the docs are pretty clear ...
> NOTE: In addition to defining a scheme, you also need to indicate which operations that scheme is applicable to. You can apply schemes globally (i.e. to ALL operations) through the AddSecurityRequirement method. The example below indicates that the scheme called "oauth2" should be applied to all operations, and that the "readAccess" and "writeAccess" scopes are required. When applying schemes of type other than "oauth2", the array of scopes MUST be empty.

With that said, if you think there's a better way to describe it then please go ahead and submit a PR to update the docs. This is open source software provided to the community at the expense of countless personal hours for __FREE__. Don't complain, just make it better by contributing.
