### ISSUE TITLE
SwaggerOperation 

### ISSUE THREAD

**Issue by male110** [domaindrivendev/Swashbuckle.AspNetCore#812]
[Route("api/[controller]")]
    public class ProductController : Controller
    {

        [HttpGet("list")]
        [SwaggerOperation(Tags = new[] { "111" })]
        [ProducesResponseType(typeof(ApiResult<IList<Product>>), 200)]
        public ApiResult<IList<Product>> List()

      I have used SwaggerOperation and the tag is "111"
In the version 2.5,    it's ok.In the version 3.0,It's not work
    http://chuantu.biz/t6/341/1531452819x-1404781126.png

**Comment by domaindrivendev** [comment]
Did you explicitly enable annotations (i.e. c.EnableAnnotations) in Startup.cs as per the docs?

**Comment by Mhirji** [comment]
You should find how to enable annotations here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#swashbuckleaspnetcoreannotations
