### ISSUE TITLE
Link to Json Spec file not working when using relative path

### ISSUE THREAD

**Issue by BerdyPango** [domaindrivendev/Swashbuckle.AspNetCore#814]
I don't know if it is a bug, but when I use relative path the link generated for the json spec file in the Swagger UI page seems not correct. here's the codes I have in my project:

``` csharp
public IServiceProvider ConfigureServices(IServiceCollection services){
    ...
    services.AddMvcCore().AddApiExplorer();
    services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "my api", Version = "v1" });
            });
    ...
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("v1/swagger.json", "v1");
            });
}
```
I tried to set a relative path of the json file, it works well for the ui page and Try it out, but when I click the link of the json file at the top left, it opens me another blank page. I checked the href of the "a" tag. I get this:
``` html
<a target="_blank" href="about:blank">
<span class="url">
<!-- react-text: 65 -->
 <!-- /react-text -->
<!-- react-text: 66 -->v1/swagger.json<!-- /react-text -->
<!-- react-text: 67 --> 
<!-- /react-text -->
</span>
</a>
```
The HTML that works looks like below:
``` html
<a target="_blank" href="/swagger/v1/swagger.json">
<span class="url">
<!-- react-text: 65 -->
 <!-- /react-text -->
<!-- react-text: 66 -->/swagger/v1/swagger.json<!-- /react-text -->
<!-- react-text: 67 --> 
<!-- /react-text -->
</span>
</a>
```
I don't know what happened during the process of generating the html when I use a relative path. But I don't want to use an absolute path to the spec file because I would probably set the base path later when the Api is running behind a reverse proxy server. Is there any quick fix to this specific case?

**Comment by domaindrivendev** [comment]
I believe this is actually a swagger-ui issue, which is a separate project independent from Swashbuckle. In fact, there appears to be a [related issue](https://github.com/swagger-api/swagger-ui/issues/4107) already posted to that project that you should probably checkout.

**Comment by BerdyPango** [comment]
Thanks, I fix the problem currently by using a absolute path.
