### ISSUE TITLE
[SwaggerResponse] Description does not show up.

### ISSUE THREAD

**Issue by VictorioBerra** [domaindrivendev/Swashbuckle.AspNetCore#816]
Code:

```csharp
        /// <summary>
        /// Gets all products.
        /// </summary>
        /// <param name="dataTableRequest">The requested product identifier.</param>
        /// <param>A jQuery DataTable server-side processing request. https://datatables.net/manual/server-side </param>
        /// <returns>All products.</returns>
        [HttpPost("DataTable", Name = ProductControllerRoute.GetProductPage)]
        [SwaggerResponse(StatusCodes.Status200OK, Description = "Existing products were successfully retrieved.")]
        public DataTableResponseViewModel<ProductViewModel> GetDataTable([FromBody]DataTablesAjaxPostViewModel dataTableRequest)
        => _productApplicationService.GetDataTable(dataTableRequest);
```

UI:

![image](https://user-images.githubusercontent.com/2934507/42788249-11dd374c-8924-11e8-8c3e-e7119a6086fd.png)

I have enabled XML comments, if that matters.

**Comment by VictorioBerra** [comment]
Also, [SwaggerTag] does nothing. I put it over my Products controller and cant find the text anywhere on the UI.

**Comment by domaindrivendev** [comment]
Have you explicitly enabled `Annotations` (now an add-on package) as described [in the readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcoreannotations)?

**Comment by domaindrivendev** [comment]
Seeing as you're already using XML comments for the operation and parameter descriptions, you should consider ditching the `SwaggerResponse` annotation and using XML comments for the response description too:

```csharp
/// <summary>
/// Gets all products.
/// </summary>
/// <param name="dataTableRequest">The requested product identifier.</param>
/// <param>A jQuery DataTable server-side processing request. https://datatables.net/manual/server-side </param>
/// <response code="200">Existing products were successfully retrieved</response>
/// <returns>All products.</returns>
[HttpPost("DataTable", Name = ProductControllerRoute.GetProductPage)]
public DataTableResponseViewModel<ProductViewModel> GetDataTable([FromBody]DataTablesAjaxPostViewModel dataTableRequest)
```

**Comment by VictorioBerra** [comment]
Which is preferred? Is there benefits to going full in on one vs the other?

**Comment by domaindrivendev** [comment]
It depends. All-in on XML comments is probably the current “de facto” as it’s a little cleaner looking, particularly when you start using multi-line, paragraphs etc. However, you still need to combine with ASP.NET Core’s ProducesResponseType attributes when you want to document additional status codes.

Also, some people prefer to reserve xml comments for code authors (intended audience) as opposed to API consumers. This would be another reason to use the Swagger specific annotations

So, it’s up to you

**Comment by VictorioBerra** [comment]
Thanks a lot.

**Comment by VictorioBerra** [comment]
Also I feel like there's additional vendor lock-in with the swagger attributes as well.

**Comment by domaindrivendev** [comment]
Agreed
