### ISSUE TITLE
work with FluentValidation.AspNetCore

### ISSUE THREAD

**Issue by huanent** [domaindrivendev/Swashbuckle.AspNetCore#821]
Hi ,  do you have plan to support swagger work with  FluentValidation.AspNetCore?
this is repository url https://github.com/JeremySkinner/FluentValidation
because  FluentValidation.AspNetCore widely used for asp.net core . asp.net core mvc native model validator very well,but FluentValidation better than , I hope swagger can support FluentValidation.AspNetCore.Thanks for you work!

**Comment by domaindrivendev** [comment]
I have no plans to support Fluent validations at present. But, it would be a great addition if you're interested in submitting a PR?

**Comment by huanent** [comment]
Sorry, I am not ability,but I find a implement lib https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation

**Comment by domaindrivendev** [comment]
Awesome - I’ll add a reference to that lib in my readme, then close this issue.

**Comment by domaindrivendev** [comment]
OK - I've added a link in the readme to the MicroElements project:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#community-packages
