### ISSUE TITLE
Xml comments are being ignored

### ISSUE THREAD

**Issue by alexeyzimarev** [domaindrivendev/Swashbuckle.AspNetCore#822]
I am using `Swashbuckle.AspNetCore` version 3.0.0 and ASP.NET Core 2.1 on Linux.

My request DTO looks like this:
https://github.com/alexeyzimarev/ddd-book/blob/master/Marketplace/Contracts/ClassifiedAds.cs

And the controller looks like this:
https://github.com/alexeyzimarev/ddd-book/blob/master/Marketplace/Api/ClassifiedAdsCommandsApi.cs

Now, the startup code is:
https://github.com/alexeyzimarev/ddd-book/blob/master/Marketplace/Startup.cs

When I check the JSON file, it has no content from XML comments. Instead, it just contains the details that are generated by reflections:
https://gist.github.com/alexeyzimarev/c48a96dbaa120f51e7c2327e77b21b73

I remember when I used 2.3 and .NET Core 2, it all worked.

My XML file is:
https://gist.github.com/alexeyzimarev/c9fc7919578200e5e059360a87b68a59

The issue is easy to reproduce by cloning this repo https://github.com/alexeyzimarev/ddd-book and running the application.

**Comment by ldybyz** [comment]
You should add route attribute on each controller action.I have the same problem.

**Comment by domaindrivendev** [comment]
Looking at your `Startup.cs` file, I see you haven't configured Swashbuckle to include XML comments. This is a required step as you need to tell it which XML file(s) to use. See the following section in the readme for more details:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments
