### ISSUE TITLE
Add Built in attributes to control parameters and body.

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle.AspNetCore#823]
I have a post method that takes a single parameter and then reads the body using Request.Body. However the generated docs doesn't have a body. Can something like this be built in (https://stackoverflow.com/questions/41141137/how-can-i-tell-swashbuckle-that-the-body-content-is-required perhaps with the consumes attribute??)

Also, I have other parameters of type IQueryCollection with a custom model binder to set it to all the query string parameters. In this case I get a body when there shouldn't be one and no params.

**Comment by domaindrivendev** [comment]
Again, please provide more detail when submitting issues? Example code clearly indicating expected behavior vs what you're observing would be extremely helpful.
