### ISSUE TITLE
Descriptions from XML - .Net Core 2.0 Webapi published to AWS Lambda

### ISSUE THREAD

**Issue by stevegroner** [domaindrivendev/Swashbuckle.AspNetCore#825]
Hello:

I have a .NET Core 2.0 Webapi, that I am trying to use this tool for.  Everything works fine when you run it locally on your box or on a server.  However, when you enable the features for XML documentation found in https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments when you publish he API to an AWS lambda/API Gateway it returns an internal error.
I believe it has something to do with not finding the .xml file defined in the properties of the project.  

I am not sure this is a bug or not so I thought I would post it here first.  Do you have any hints on how to make this work with an AWS Lambda function.  The module works as long as you do not turn on the descriptions from xml feature.   But, I would really like to add a little additional information inline in the code so it appears in the swagger doc.

I am using Swashbuckle 3.0.0

Thank you in advance,

**Comment by strofimo** [comment]
Hi,

You are right, it looks like xml file are not included into lambda package. 
The thing is that publish action do not copy xml file so you need to do it by your own. 

This is how I do it through proj file:

`  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <ItemGroup>
      <DocFile Include="bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\$(TargetName).xml" />
    </ItemGroup>
    <Copy SourceFiles="@(DocFile)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="false" />
/>
  </Target>`

**Comment by domaindrivendev** [comment]
To render the descriptions, SB _requires_ access to the XML file, and you tell it where to find via the `IncludeXmlComments` file. So, it's not a bug but is just something you need to figure out in your deployment process - which, AWS Lambda or otherwise, I can't really speak to.
