### ISSUE TITLE
Attributes do not work (standard XML formatter)

### ISSUE THREAD

**Issue by dmitriy-shleht** [domaindrivendev/Swashbuckle.AspNetCore#831]
Hello.
I'm using asp net core version 2.1
Swashbuckle.AspNetCore 3.0.0

### There is a model:

```cs
public class Document
{
    [XmlElement("MT101")]
    public MT101 MT101 { get; set; }

    public XmlDocument Signature { get; set; }
}

public class MT101
{
    [XmlAttribute("id")]
    [RegularExpression("signed")]
    public string Id { get; set; }
    public string F1 { get; set; }
    public string F2 { get; set; }
}
```
### Generated example:
![1](https://user-images.githubusercontent.com/13961834/43321105-85dfe90e-91b3-11e8-9978-05a821f06a61.JPG)

### It should be:
```xml
<Document>
  <MT101 id="signed">
    <F1></F1>
    <F2></F2>
  </MT101>
  <Signature></Signature>
</Document>
```

> Also, please note that the item name register matters. In this case there should be PascalCase

**Comment by blurhkh** [comment]
I find a solution for XmlElementAttribute,but still don‘t know how to make the XmlRootAttribute work.
Maybe the follwing code can help you.
`public class SchemaFilter : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaFilterContext context)
        {
            if (schema.Properties == null) return;

            if (context.SystemType.GetCustomAttribute(typeof(XmlRootAttribute))
                is XmlRootAttribute xmlRoot)
            {
                var map = context.SystemType.GetProperties().Select(prop => new
                {
                    PropertyName = prop.Name.ToCamelCase(),
                    (prop.GetCustomAttribute(typeof(XmlElementAttribute)) as XmlElementAttribute)?.ElementName
                }).Where(x => x.ElementName != null).ToDictionary(x => x.PropertyName, x => x.ElementName);

                schema.Properties = schema.Properties
                    .ToDictionary(kv => map.TryGetValue(kv.Key, out var key) ? key : kv.Key,
                        kv => kv.Value);
            }
        }
    }`

**Comment by dmitriy-shleht** [comment]
Thanks, it helped

**Comment by domaindrivendev** [comment]
Will track as part of #1050
