### ISSUE TITLE
Description from inherited SwaggerResponse hides one from child class

### ISSUE THREAD

**Issue by sm-g** [domaindrivendev/Swashbuckle.AspNetCore#833]
I have base controller class with `SwaggerResponse`.

```
[AuthorizerAttribute]
[SwaggerResponse((int)HttpStatusCode.Forbidden, Description = "User not matched user id from request")]
public abstract class AuthorizedControllerBase : ApiControllerBase
{
}
```

Child classes also can use same status code:

```
public class SettingsController : AuthorizedControllerBase
{
   [SwaggerResponse((int)HttpStatusCode.Forbidden, Description = "Another reason")]
   public IActionResult Get() {
     //
   }
}
```

In generated json there is only description of base class:
```
"403": {
            "description": "User not matched user id from request"
          },
```

On version 1.0.0 there was no description at all in such case.

Current behavior is bad, because it hides some of important reasons of status code from API users. Maybe configurable description merge function should be used to produce i.e. "User not matched user id from request OR Another reason".

**Comment by sm-g** [comment]
My "solution" for this - not use attributes on parent controller, use operation filter (registered after `EnableAnnotations`):

```
o.EnableAnnotations();
o.OperationFilter<AddResponsesForAuthorized>();

public class AddResponsesForAuthorized : IOperationFilter
{
	private static readonly (string statusCode, string description)[] ResponsesToAdd = new[] {
		("401", "No CurrentUser set (login first)"),
		("403", "CurrentUser not matched user id from request")
	};

	public const string Divider = " OR ";

	public void Apply(Operation operation, OperationFilterContext context)
	{
		var authFilter = context.ApiDescription.ActionDescriptor.FilterDescriptors
			.Select(x => x.Filter)
			.OfType<AuthorizedAttribute>()
			.FirstOrDefault();

		if (authFilter != null)
		{
			foreach (var (statusCode, description) in ResponsesToAdd)
			{
				if (operation.Responses.ContainsKey(statusCode))
				{
					var existingResponse = operation.Responses[statusCode];
					existingResponse.Description += Divider + description;
				}
				else
				{
					operation.Responses[statusCode] = new Response { Description = description };
				}
			}
		}
	}
}
```

**Comment by domaindrivendev** [comment]
Swashbuckle invokes `GetCustomAttributes(true)` on controllers to retrieve the list of `SwaggerResponse` attributes. By passing the flag, it will include attributes that have been inherited but AFAICT there is no guarantee around the ordering of attributes returned - e.g. whether they've come from the base class or not. So, there's no easy way for me to support the semantics you're looking for.
