### ISSUE TITLE
Swagger UI, Swagger endpoint : quote not supported

### ISSUE THREAD

**Issue by deka** [domaindrivendev/Swashbuckle.AspNetCore#838]
Hi,
An error with quote in swagger endpoint  
To reproduce : 
`
...
.UseSwaggerUI(c => {
      c.SwaggerEndpoint("v1/swagger.json", "Something' with' a' quote");
})
...
`
Regards

**Comment by domaindrivendev** [comment]
Fixed by 8c9449c6cd51d35f4e7d9f4ba416aa62e1c93ebb
