### ISSUE TITLE
multiple parameter post not support

### ISSUE THREAD

**Issue by grissomlau** [domaindrivendev/Swashbuckle.AspNetCore#840]
two or more object parameter in post, it just post the last parameter.
 

![swagger_bug_1](https://user-images.githubusercontent.com/4479670/43623622-c2c48184-9714-11e8-80e8-c386d44ec69f.png)
![swagger_bug_2](https://user-images.githubusercontent.com/4479670/43623624-c7bea6d8-9714-11e8-8973-a44494bb4924.png)

**Comment by domaindrivendev** [comment]
It doesn't make any sense to have two separate body parameters - in HTTP there can only be one body.

This is reflected in the aspnecore docs - https://docs.microsoft.com/en-us/aspnet/web-api/overview/formats-and-model-binding/parameter-binding-in-aspnet-web-api#using-frombody

> At most one parameter is allowed to read from the message body. So this will not work:
public HttpResponseMessage Post([FromBody] int id, [FromBody] string name)

And also in the Swagger specification - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object

>The payload that's appended to the HTTP request. Since there can only be one payload, there can only be one body parameter
