### ISSUE TITLE
Extensions for parameter's items?

### ISSUE THREAD

**Issue by coiscir** [domaindrivendev/Swashbuckle.AspNetCore#841]
AFAICT, SwaggerGen doesn't currently allow adding extensions to a parameter's items.

```csharp
public void Apply(IParameter parameter, ParameterFilterContext context)
{
    if (parameter is PartialSchema parameterSchema)
    {
        parameterSchema.Items.Extensions /* nope */ .Add(...);
    }
}
```

Have I overlooked an option that permits this in v3.0.0 or is it a reasonable request to add in a future version?

One API includes a query-string parameter that's an enum array. I'd like to include [autorest's `x-ms-enum` extension](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-enum) so it remains `enum[]` rather than becoming `string[]` in the client. And, autorest only accepts the extension on the same schema object as `"enum": []`, including items.

```json
"parameters": [
  {
    "name": "foos",
    "...": "...",
    "type": "array",
    "items": {
      "type": "string",
      "enum": [ "Bar", "Baz" ],
      "x-ms-enum": { "name": "Foo" }
    }
  }
]
```

```csharp
public enum Foo { Bar, Baz }
public IActionResult Get([FromQuery] Foo[] foos)
```

**Comment by domaindrivendev** [comment]
See 76f7b3e14e53c19cfc2ff4021cc7f169916199b2. Will be generally available with the upcoming 4.0.0 release (still some other issues to fix that will be part of that). In the meantime you can download the preview version from myget.org:

https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore
