### ISSUE TITLE
Endpoint path does not include Base URL

### ISSUE THREAD

**Issue by AnthonyMastrean** [domaindrivendev/Swashbuckle.AspNetCore#844]
We're running our app behind a reverse-proxy that inserts a prefix on all routes: `/api/`. We've got that wired up correctly using a preserialize filter and a custom X-Forwarded header.

```csharp
app.UseSwagger(options =>
{
    options.RouteTemplate = "nvdm/api-docs/{documentName}/swagger.json";
    options.PreSerializeFilters.Add((doc, request) => doc.BasePath = request.Headers["X-Forwarded-Path"]);
});
```

You can see Base URL under the first highlight on the screenshot. But, it's missing from the endpoint path under the second highlight. Although, it does appear properly in the Curl example!

![image](https://user-images.githubusercontent.com/217842/43794103-57e11ac8-9a4b-11e8-9d7e-3e7bea636742.png)

I assume Swashbuckle creates this `swagger.json` and you can see the "paths" appear absolute and are _missing_ the base path.

```
{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "NVDM API"
    },
    "basePath": "/api/",
    "paths": {
        "/nvdm/healthcheck": {
            "get": {
                "tags": [
                    "Healthcheck"
                ],
                "summary": "Get the health of this service",
...
```

I don't see anything in the Swagger document model in the preserialize filters that I can set. Should Swashbuckle use the BasePath when constructing those paths?

**Comment by domaindrivendev** [comment]
If I’m understanding your issue correctly - this is by design. The display of paths for each operation is intended to be relative to the global basePath.

**Comment by AnthonyMastrean** [comment]
The path displayed is an absolute path (it starts with a forward-slash). If I've got my terminology correct, that's absolute to the host part of the URI. So, `/nvdm/healthcheck` is absolute with regards to `https://localhost`... so, `https://localhost/nvdm/healthcheck` (incorrect!).

A relative path might be more appropriate if we answered "relative to what?". You could say relative to the host + any possible base path. So, `nvdm/healthcheck` would be relative to `https://localhost` + `/api/`..., so `https://localhost/api/nvdm/healthcheck` (correct!).

Maybe you're saying it's just a design choice?

**Comment by domaindrivendev** [comment]
Youre terminology is correct from a pure HTTP perspective - i.e `/foobar` is relative to the host whereas `foobar` would be relative to the current resource. However, for your issue we're really just talking about the way in which API documentation, specifically [Swagger-based](https://swagger.io/) documentation, is structured. And, in this case the semantics are subtly different. For more info, you should check out the relevant section of the Swagger 2.0 spec:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#paths-object

>Path: A relative path to an individual endpoint. The field name MUST begin with a slash. The path is appended to the basePath in order to construct the full URL. Path templating is allowed.

**Comment by darrelmiller** [comment]
The use of a leading slash in paths is an unfortunate historical artifact.  You can't use relative reference resolution with `paths`.  We attempted to be clear about this in the V3 spec.

> 
A relative path to an individual endpoint. The field name MUST begin with a slash. The path is appended (no relative URL resolution) to the expanded URL from the Server Object's url field in order to construct the full URL. 

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#patterned-fields

However other relative references in the spec do behave properly.
 https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#relativeReferences

**Comment by AnthonyMastrean** [comment]
That is an interesting historical artifact and a very specific point-of-view (a spec implementor or, at least, reader).

I'm concerned about the use of the Swagger UI by regular users of my application! I expect them to practice in Swagger UI and turn around to do some very lite scripting or console `curl`ing without having to read the spec in order to construct the correct URL!

@darrelmiller if there were a place to file a "complaint" or request to change this, would it be on the openapi-specification project?

**Comment by darrelmiller** [comment]
@AnthonyMastrean You can raise the issue on https://github.com/oai/openapi-specification .  However, changing this would be a significant breaking change and therefore would not likely happen until V4, which is a long way off.

You can also raise the issue on the Swagger-UI repo.  The lead for that project is one of the OpenAPI Technical Steering committee members.

**Comment by domaindrivendev** [comment]
@AnthonyMastrean - if you feel the use of `basePath` in the docs is unintuitive to readers, you can leave it blank and expand out all of the individual paths instead. This way, the path that's displayed for operations would be a full path, relative to the host:

```csharp
app.UseSwagger(c =>
{
    c.PreSerializeFilters.Add((swagger, httpReq) =>
    {
        swagger.Paths = swagger.Paths.ToDictionary(
            (kvp) => request.Headers["X-Forwarded-Path"] + kvp.Key,
            (kvp) => kvp.Value
        );
    });
});
```

**Comment by darrelmiller** [comment]
@gortok I think the original intent was considering paths as absolute to the "api" and the basePath was to indication the location of the "api".  It is true that it doesn't match RFC 3986 but then neither does the concept of HTTP "api".  ASP.NET does something similar by inventing the non-standard `~/` nomenclature.
