### ISSUE TITLE
Exclude model from Models list

### ISSUE THREAD

**Issue by m-demydiuk** [domaindrivendev/Swashbuckle.AspNetCore#846]
# Content & configuration
Swagger/OpenAPI definition:
I use Swashbuckle.AspNetCore v3.0.0 / Swagger-Ui v3.17.1

# Is your feature request related to a problem?
I need to exlude (i.e. do not show) model in Models list. As our partners do not use AspNet.Core, they don't need to know anything about IFormFile interface which is specific to AspNet.Core.

# Describe the solution you'd like
It will be very useful for us, to decorate the method parameter with some attribute to exclude IFormFile from rendering.

public async Task<IActionResult> Post(**[IgnoreModel]**IFormFile document)

# Additional context
![image](https://user-images.githubusercontent.com/2910327/43834220-034bbaba-9b16-11e8-989f-22ba61dae00f.png)

**Comment by domaindrivendev** [comment]
For the specific example you gave, there's a broader issue for handling `IFormFile` parameters better on the backlog - #193

For the general case, you should just create a Document Filter (see readme) that removes the unwanted models from the `Definitions` dictionary:

```csharp
// Startup.cs
services.AddSwaggerGen(c =>
{
    ...

    c.DocumentFilter<RemoveBogusDefinitionsDocumentFilter>();
}

// RemoveBogusDefinitionsDocumentFilter.cs
public class RemoveBogusDefinitionsDocumentFilter : IDocumentFilter
{
    public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
    {
        swaggerDoc.Definitions.Remove("IFormFile");
    }
}
```

**Comment by m-demydiuk** [comment]
Thanks, it helped. Just curious why Swashbuckle do not have an option for this?

**Comment by DanielCaspers** [comment]
For others looking for a solution that is more dynamic or generic, like the OP was originally hoping for, I've written a document filter which can access a custom attribute you can write using reflection and then remove the definitions which are a match (based on type name).

https://github.com/domaindrivendev/Swashbuckle/issues/178#issuecomment-546161898

**Comment by Nathalino** [comment]
And how do I remove only the model, without impacting the actions of the controler. I observe the withdrawal of attributes from the model a lot, but if you want to remove the model from the documentation.

technology employed:
I use Swashbuckle.AspNetCore v3.0.0 / Swagger-Ui v3.17.1

Thank you very much in advance
