### ISSUE TITLE
Javascript error with apostrophe in SwaggerEndpoint

### ISSUE THREAD

**Issue by Iridio** [domaindrivendev/Swashbuckle.AspNetCore#847]
With version 3.0 and NET Core 2.1 the swagger UI show an empty page if in the Swagger endpoint is used an apostrophe

in startup.cs -> Configure use this line:
`app.UseSwaggerUI(c => { c.SwaggerEndpoint("/swagger/v1/swagger.json", "Alex's API v1"); });`

When runnig http:/localhost/swagger an empty page with a javascript error on line 83 as per image attached.

![cattura](https://user-images.githubusercontent.com/1730278/43851575-54714994-9b3b-11e8-94d8-59d630c18aeb.JPG)

I guess the strings are not escaped

**Comment by domaindrivendev** [comment]
Dup of #838
