### ISSUE TITLE
Expose IdentityServer4 endpoints

### ISSUE THREAD

**Issue by m-demydiuk** [domaindrivendev/Swashbuckle.AspNetCore#850]
Hi, I have setup IdentityServer4 and now I need to add UI for it. As we already use `Swashbuckle.AspNetCore` for all our APIs, it would be great to use it for IdServer as well. But swagger ui does not expose IdServer endpoints, because, actually, IdServer does not have MVC Controller/Actions. It has some route filter that executes internal services matched to the route. And for now, the only option that I can imagine is to manually describe these endpoints in `swagger.json`, but I can't find the way how to do it.

Please advice, thanks!

**Comment by domaindrivendev** [comment]
You can use a `DocumentFilter` for this (see readme) - this allows you to enrich the generated `SwaggerDocument` as you see fit. In your case, you'll need to add additional items to the `Paths` dictionary. Before you start, I would highly recommend having a read through the Swagger 2.0 docs, in particular the `PathItem` structure:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathsObject
