### ISSUE TITLE
Info.Description "\_" will be replaced by "_"

### ISSUE THREAD

**Issue by aureole82** [domaindrivendev/Swashbuckle.AspNetCore#853]
Hi, inside my QA System I'd like to display the logging folder:

    var path = "C:\\inetpub\\logs\\_dev\\";
    options.SwaggerDoc("v1",
        new Info
        {
            Title = "Test WebApi",
            Version = "v1",
            Description = $"LoggingPath: {path}"
        });

But the index.html will display the following :-(

### Test WebApi (v1)
_/swagger/v1/swagger.json_
LoggingPath: C:\inetpub\logs_dev\

**Comment by domaindrivendev** [comment]
That's a weird one alright! However, it looks to me like it might be a [swagger-ui](https://github.com/swagger-api/swagger-ui) issue as opposed to a Swashbuckle issue. If you look at the Swagger JSON being returned by Swashbuckle - it looks correct, so the issue appears to be isolated to the UI rendering.

So, I would suggest you post an issue to that repo instead.
