### ISSUE TITLE
Xml Comment <example> tag is not included in Swagger UI

### ISSUE THREAD

**Issue by wojciechrak** [domaindrivendev/Swashbuckle.AspNetCore#859]
In the project's readme, in section Include Descriptions from XML Comments (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/v3.0.0#include-descriptions-from-xml-comments) there is this piece:

> You can also annotate types with summary and example tags:
> ```csharp
> public class Product
> {
>    /// <summary>
>    /// The name of the product
>    /// </summary>
>    /// <example>Men's basketball shoes</example>
>    public string Name { get; set; }
>
>    /// <summary>
>    /// Quantity left in stock
>    /// </summary>
>    /// <example>10</example>
>    public int AvailableStock { get; set; }
> }
> ```

But I can't see how it is reflected in the UI.

**Comment by domaindrivendev** [comment]
Switch from "Example value" to the "Model" view and expand ...

<img width="443" alt="screen shot 2018-08-24 at 3 02 41 pm" src="https://user-images.githubusercontent.com/1434343/44609961-d2590e80-a7ae-11e8-9dad-6f7938b1afe1.png">

**Comment by garygaryzhang** [comment]
> Switch from "Example value" to the "Model" view and expand ...
> 
> <img alt="screen shot 2018-08-24 at 3 02 41 pm" width="443" src="https://user-images.githubusercontent.com/1434343/44609961-d2590e80-a7ae-11e8-9dad-6f7938b1afe1.png">

How do I make the example in the Example Value like what they have in Swagger example then?
![image](https://user-images.githubusercontent.com/15327928/90841376-20fbfd80-e322-11ea-9355-9b92aa81d2e4.png)
