### ISSUE TITLE
Annotating array types with example tag not working

### ISSUE THREAD

**Issue by pascalpfeil** [domaindrivendev/Swashbuckle.AspNetCore#866]
**Version:** v3.0.0

**Bug:** When trying to annotate an array data type with the example tag it gets interpreted as string

**Steps to reproduce:**

Create following model in C#:
```csharp
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ns
{
    public class Model
    {
        /// <summary>
        /// summary
        /// </summary>
        /// <example>
        /// ["entry1", "entry2", "entry3"]
        /// </example>
        [Required]
        public ISet<string> Stuff{ get; set; }
    }
}
```

This will generate the following "Example Value" for the model:
```json
{
  "stuff": "[\"entry1\", \"entry2\", \"entry3\"]"
}
```

instead of
```json
{
  "stuff": [
    "entry1", 
    "entry2",
    "entry3
  ]
}
```

**Comment by domaindrivendev** [comment]
This is not supported - you can only use XML comments to specify simple string examples. If you need to provide examples for more complex types, you should use an Operation Filter.

See the following blog post for some inspiration:
https://mattfrear.com/2015/04/21/generating-swagger-example-responses-with-swashbuckle/

**Comment by pascalpfeil** [comment]
Thank you very much for your response.
I would suggest adding this to https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments

**Comment by pascalpfeil** [comment]
For anyone having the same problem: Meanwhile someone published a well-working solution:
https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters

**Comment by nicostubi** [comment]
Hi @pascalpfeil 

Could you please elaborate a bit more on what helped you with the package 

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters

Indeed, I've tried to install it added

`c.ExampleFilters();`

and

`services.AddSwaggerExamplesFromAssemblyOf<MyType>();`

but when using:

`/// <example>["CHF"]</example>`
`public string[] Currencies { get; set; }`

I still get "string", like this:

![image](https://user-images.githubusercontent.com/47106274/96736822-49a18180-13bd-11eb-8830-fe87631e5ad4.png)

Best,
Nico

**Comment by pascalpfeil** [comment]
Hi @nicostubi, unfortuantely, that was a long time ago and I do not remember. Best of luck!
