### ISSUE TITLE
Failed to load API definition Failed to fetch

### ISSUE THREAD

**Issue by WeihanLi** [domaindrivendev/Swashbuckle.AspNetCore#867]
Asp.Net Core version:

> .netcoreapp2.0

Swagger version:

> Swashbuckle.AspNetCore 3.0.0

Error description:

I can access the swagger.json file directly and got 200,but when I access the swagger index,
I met the error as follows:

![image](https://user-images.githubusercontent.com/7604648/44781927-349f7e00-abb8-11e8-86d9-99ea5ee3c27c.png)
![image](https://user-images.githubusercontent.com/7604648/44781941-45e88a80-abb8-11e8-8f86-77002979c441.png)

**Comment by WeihanLi** [comment]
I've checked every method in controller and there's no method without httpVerboses(`HttpGet`,`HttpPost`..) attribute

**Comment by WeihanLi** [comment]
It was my chrome ad block plugin caused...

**Comment by memoryfraction** [comment]
I ran into the same issue, can I know what you did to solve it?

**Comment by q00Dree** [comment]
Im in guys

**Comment by santoshnayak** [comment]
> I ran into the same issue, can I know what you did to solve it?

Did you solved this?

**Comment by q00Dree** [comment]
> > I ran into the same issue, can I know what you did to solve it?
> 
> Did you solved this?

In my case it was wrong configuration in Startup.

code in ConfigureServices was

 ```csharp
services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Version = "v1"
                });
            var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                c.IncludeXmlComments(xmlPath);
            }
 ```

and code in Configure method was 

 ```csharp
                app.UseSwaggerUI(c =>
                {
                    c.SwaggerEndpoint("/swagger/v2/swagger.json", "v2");
                });
 ```

Problem was: I made middleware with root  swagger/v2 json, but defined swagger/v1 above. 
Maybe you do the same?
