### ISSUE TITLE
How to replace the Api path in the swagger.json file with the API gateway?

### ISSUE THREAD

**Issue by zengqinglei** [domaindrivendev/Swashbuckle.AspNetCore#870]
# Instructions
## I created two services: UserService, ProductService
* The routing template of the UserService is: api/users/{id}
* The routing template of the ProductService is: api/products/{id}
### Then I created an Ocelot gateway service: ApiGateway
**It is such a proxy for these two services:**
* /userService/swagger/{url}          -->   /swagger/{url}
* /userService/{url}                         -->    /api/{url}
* /productService/swagger/{url}    -->   /swagger/{url}
* /productService/{url}                   -->    /api/{url}

**An example is shown below:**
![image](https://user-images.githubusercontent.com/7374317/44800606-67ae3580-abe9-11e8-8784-67c4bffeafd0.png)

**The ui display is normal, but the obtained swagger.json file because of the road strength is: /api/users/{id}, which makes it impossible to use the test function provided by ui. How can I replace the api road force in swagger.json with What about gateway routing?**

**_Thank you!_**

**Comment by WeihanLi** [comment]
I also need this.

**Comment by domaindrivendev** [comment]
@zengqinglei I don't understand this description. What does "road strength" and "road force" mean?

> The ui display is normal, but the obtained swagger.json file because of the road strength is: /api/users/{id}, which makes it impossible to use the test function provided by ui. How can I replace the api road force in swagger.json with What about gateway routing?

**Comment by WeihanLi** [comment]
what @zengqinglei  means maybe the follows:

> When you access the api via gateway,the url may be `http://gateway/api/users/123`, but the swagger ui requests may request `http://userService/api/users/123`, can I config any option or do something else to proxy the swagger ui request forware to the gateway ?

**Comment by zengqinglei** [comment]
@domaindrivendev Yes, as @WeihanLi  said !
When you access the api via gateway,the url may be **http://gateway/userService/users/123**, api gateway will forward the request to: **http://192.168.0.102/api/users/123**, but the swagger ui requests may request http://gateway/api/users/123, can I config any option or do something else to proxy the swagger ui request forware to the gateway ?

**Comment by SunGram** [comment]
app.UseSwagger(c =>
            {
                c.PreSerializeFilters.Add((swagger, httpReq) => swagger.Host = httpReq.Host.Value);
            })

**Comment by bstringer-reward** [comment]
Also facing this issue.

**Comment by Mortana89** [comment]
There might be a better way, but this is how we solved it:
```
app.UseSwagger(c => c.PreSerializeFilters.Add((swagger, httpReq) => {
                var oldPaths = swagger.Paths.ToDictionary(entry => entry.Key,
                                               entry => entry.Value);
                foreach(var path in oldPaths)
                {
                    swagger.Paths.Remove(path.Key);
                    swagger.Paths.Add(path.Key.Replace("api", "api/me"), path.Value);
                }
            }));
```

This will replace the 'api' strings with the api/me string, which is the configured downstream path in Ocelot for this specific microservice. But you get the idea!
