### ISSUE TITLE
ArgumentNullException when trying to register type with generic argument

### ISSUE THREAD

**Issue by TheSimpleZ** [domaindrivendev/Swashbuckle.AspNetCore#871]
Hello!

I have the following type:
```
public interface IQuery<TDto> { }

public interface a
    {
        int Number { get; set; }
    }

public class PostCars1<T> : IQuery<object> where T : a
    {
        public T Car { get; set; }
    }
```

Which i'm trying to register in the schema registry using `SchemaRegistry.GetOrRegister(type);`.
When i run my code i get the following exception:
```

System.ArgumentNullException: Value cannot be null. Parameter name: key
    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
    at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
    at Swashbuckle.AspNetCore.SwaggerGen.SchemaRegistry.GetOrRegister(Type type)
```

Why does this error appear only when i have a generic parameter? Is this type of functionality not supported or is it a bug?

**Comment by domaindrivendev** [comment]
Please provide a concise set of repro steps - starting from an empty project.

**Comment by TheSimpleZ** [comment]
Thanks for your time, but we chose to take a different approach and skip generics. I don't have the time to put together a project which you can test, but you will most likely get the same error as me if you simply call `SchemaRegistry.GetOrRegister(typeof(PostCars1<>));`

**Comment by domaindrivendev** [comment]
OK going to close for now - if you (or anyone else) has time to put together a repro, I’ll re-open
