### ISSUE TITLE
CLI: Allow setting environment at runtime

### ISSUE THREAD

**Issue by nascosto** [domaindrivendev/Swashbuckle.AspNetCore#872]
I would like the ability to specify the environment of the API when running the CLI to control which appsettings files get used. Currently, it defaults to Production, but our production values are tucked away into secrets and loaded outside the appsettings file. I'd like to point it to Development.

dotnet run has the ability to set environment via --environment <envvalue> and has the ability to set environment variables in general using <envname>=<envvalue>.  It also can pull the ASPNETCORE_ENVIRONMENT from the launchSettings.json

I can still set ASPNETCORE_ENVIRONMENT at the user/system level, but I'd prefer the flexibility of one of these other options.

**Comment by domaindrivendev** [comment]
I don't see --environment as an option for `dotnet run`:

<img width="516" alt="screen shot 2018-09-04 at 10 53 04 pm" src="https://user-images.githubusercontent.com/1434343/45073777-9dde3000-b095-11e8-9fad-6d2e81658ee1.png">

Also, I don't understand how the introduction of such a parameter would provide any more flexibility over passing ASPNETCORE_ENVIRONMENT as an environment variable to the command as follows:

```
> ASPNETCORE_ENVIRONMENT=development dotnet swagger tofile --output wwwroot/api-docs/v1/swagger.json bin/Debug/netcoreapp2.0/MyAPI.dll v1
```

**Comment by nascosto** [comment]
So it turns out the dotnet run call just takes in additional arguments which are then added to the app configuration object. You can see this option here
![image](https://user-images.githubusercontent.com/2653283/45124439-9e270b80-b127-11e8-9d45-bb12dbf0a478.png)

ASPNETCORE_ENVIRONMENT just happens to be translated to the environment configuration option. So by using --environment Development or environment=Development at the end of the dotnet run command, you are setting the environment configuration. Adding --foo bar or foo=bar would set foo to bar in the configuration usable during startup.

The additional flexibility comes from trying to use the command inside the csproj file like so
`` 
<Target Name="SwaggerToFile" AfterTargets="AfterBuild">
    <Exec Command="dotnet swagger tofile --output $(OutputPath)swagger.json $(OutputPath)$(AssemblyName).dll v1" />
  </Target>
``
For whatever reason, I can't have two commands (e.g. set <var>=<val> && dotnet swagger tofile) in the same command which means I can't set the environment variable this way, hence why I'd like it as part of the actual tofile command.

It is a niche case, but I figured I'd ask.

**Comment by persalmi** [comment]
Just ran into this missing option to set environment. Seems to be needed when using the Manage User Secrets feature of VS, then without the environment = Development setting, the "dotnet swagger tofile..." command embedded in a .csproj fails if you use config properties for oauth2 setup in the Startup.cs.

**Comment by donald93** [comment]
I have a similar use case where we wish to use the CLI to create contract diffs during PRs. Unfortunately we access secrets in our Startup.cs file that are not available at build time and are only available when we deploy. This causes a particular piece of our Startup to error because it's attempting to use a configuration variable that's `null`. 

Being able to specify configuration options similar to the Environment would allow us to use the CLI without making code changes.

**Comment by curbol** [comment]
I have the same use case as persalmi. I'm using Manage User Secrets with a script in the .csproj file

```xml
<Target Name="SwaggerToFile" AfterTargets="AfterBuild">
    <Exec Command="dotnet swagger tofile --output swagger.json $(TargetPath) v1" />
  </Target>
```

**Comment by andrew-vdb** [comment]
I finally able to make it work

Set env variable like this
![image](https://user-images.githubusercontent.com/12871379/75436058-3afcea80-5954-11ea-9751-fe0f9e413c5f.png)

Notice there is **NO** && ^ between setting env variable and calling dotnet swagger

Within the project, dont forget to put the appsettings.Development.json

![image](https://user-images.githubusercontent.com/12871379/75436103-4bad6080-5954-11ea-8f6a-83554afc6a67.png)

**Comment by joaopgrassi** [comment]
If using the CLI as part of you build pipelines on Azure DevOps, you can do it like this:
```
- task: CmdLine@2
  displayName: 'Generating swagger json'
  inputs:
    script: |
      set ASPNETCORE_ENVIRONMENT=Development
      swagger tofile --serializeasv2 --output swagger.json MyService.Dll 1.0
    workingDirectory: <your dotnet publish directory>
```

**Comment by domaindrivendev** [comment]
@nascosto  - it seems there's very reasonable solutions here, can this be closed?

**Comment by nascosto** [comment]
Yeah. Let's close this for now. Thanks.

**Comment by DanielHabenicht** [comment]
Just if anybody still looks for a solution to make it work in `.csproj`: 
```xml
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="dotnet tool restore" />
    <Exec Command="dotnet swagger tofile --output swagger.json $(OutputPath)$(AssemblyName).dll v1" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" />
</Target>
```

**Comment by ilcos91** [comment]
> Just if anybody still looks for a solution to make it work in `.csproj`:
> 
> ```
> <Target Name="PostBuild" AfterTargets="PostBuildEvent">
>     <Exec Command="dotnet tool restore" />
>     <Exec Command="dotnet swagger tofile --output swagger.json $(OutputPath)$(AssemblyName).dll v1" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=$(Configuration)" />
> </Target>
> ```

With this instruction I'm getting "Debug" and not the Environment Variable, how is this supposed to work?

**Comment by DanielHabenicht** [comment]
> > Just if anybody still looks for a solution to make it work in `.csproj`:
> > 
> > ```
> > <Target Name="PostBuild" AfterTargets="PostBuildEvent">
> >     <Exec Command="dotnet tool restore" />
> >     <Exec Command="dotnet swagger tofile --output swagger.json $(OutputPath)$(AssemblyName).dll v1" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=$(Configuration)" />
> > </Target>
> > ```
> 
> With this instruction I'm getting "Debug" and not the Environment Variable, how is this supposed to work?

What are you trying to do?
The environment variable is set according to the targeted configuration.

**Comment by ilcos91** [comment]
I'm trying to compile the project and I need the environment to be able to connect to the correct key vault.
This means that I have to create a new configuration and call it "Development"? And when I run my pipeline I should create also a configuration to define the environment

> > > Just if anybody still looks for a solution to make it work in `.csproj`:
> > > ```
> > > <Target Name="PostBuild" AfterTargets="PostBuildEvent">
> > >     <Exec Command="dotnet tool restore" />
> > >     <Exec Command="dotnet swagger tofile --output swagger.json $(OutputPath)$(AssemblyName).dll v1" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=$(Configuration)" />
> > > </Target>
> > > ```
> > 
> > 
> > With this instruction I'm getting "Debug" and not the Environment Variable, how is this supposed to work?
> 
> What are you trying to do? The environment variable is set according to the targeted configuration.

**Comment by DanielHabenicht** [comment]
Well then simply use the variable: https://stackoverflow.com/questions/48618357/how-to-get-environment-variable-in-csproj-file

**Comment by greg-signi** [comment]
Trying to do this using gitlab pipelines without much success:

`- dotnet tool install --tool-path tools Swashbuckle.AspNetCore.Cli --version 6.4.0 && set myvar=https://example.com
 - ./tools/swagger tofile --output swagger.json MyProject.dll v1`
    
    Tried many variations without success
    
    `- dotnet tool install --tool-path tools Swashbuckle.AspNetCore.Cli --version 6.4.0
    - set myvar=https://example.com && ./tools/swagger tofile --output swagger.json MyProject.dll v1`
    
    `- dotnet tool install --tool-path tools Swashbuckle.AspNetCore.Cli --version 6.4.0
    - set myvar=https://example.com
    - ./tools/swagger tofile --output swagger.json MyProject.dll v1`

**Comment by mehmetaltuntas** [comment]
passing environment variables working?

> Trying to do this using gitlab pipelines without much success:
> 
> ```
> - dotnet tool install --tool-path tools Swashbuckle.AspNetCore.Cli --version 6.4.0 && set myvar=https://example.com
> - ./tools/swagger tofile --output swagger.json MyProject.dll v1
> ```
> 
> Tried many variations without success:
> 
> ```
> - dotnet tool install --tool-path tools Swashbuckle.AspNetCore.Cli --version 6.4.0
> - set myvar=https://example.com && ./tools/swagger tofile --output swagger.json MyProject.dll v1
> 
> - dotnet tool install --tool-path tools Swashbuckle.AspNetCore.Cli --version 6.4.0
> - set myvar=https://example.com
> - ./tools/swagger tofile --output swagger.json MyProject.dll v1
> ```

is this working or any other options above?
