### ISSUE TITLE
Fetch error FABRIC_E_TIMEOUT for SwaggerUI/swagger.json

### ISSUE THREAD

**Issue by starklord07** [domaindrivendev/Swashbuckle.AspNetCore#873]
I am developing an Azure Service Fabric Service, in which I have used Swashbuckle.AspNetCore to build API List. I am using the following code in my Startup.cs file

In ConfigureServices(IServiceCollection services)

            `            services.AddSwaggerGen(c =>
                         {
                              c.SwaggerDoc("Backend", new Info { Title = "My Backend", Version = "v1.0" });
                         });`

And in Configure(IApplicationBuilder app, IHostingEnvironment env)

`           app.UseSwagger(c => c.PreSerializeFilters
                .Add((swagger, httpReq) => swagger.Host = httpReq.Host.Value));

            app.UseSwaggerUI(c => c.SwaggerEndpoint("/MyApp.Fabric/MyApp.Backend/swagger/Backend/swagger.json",
                "Backend"));`

Here, because I am developing SF service, I have used reverse proxy with swagger endpoint configuration. Now the same thing is working with my other services except one. I have the same code and same version of Swashbuckle.AspNetCore nuget used in all of my services that is 3.0.0 

When I try to access the SwaggerUI for this service, I am getting the following error 
![image](https://user-images.githubusercontent.com/18307876/44943695-6eef6200-ade8-11e8-83d3-a291635131ba.png)

Can anyone please help me on this ? I have been trying but could not get any suitable solution..

**Comment by domaindrivendev** [comment]
As per the [contributing guidelines](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/CONTRIBUTING.md), this issue tracker should only be used for clear and reproducible bug reports, or feature requests. As there's not enough information here to suggest this is a bug with Swashbuckle, I would suggest you post to stackoverflow instead.
