### ISSUE TITLE
The value larger than 16 digits in response is rounded in UI display

### ISSUE THREAD

**Issue by aratomo-arazon** [domaindrivendev/Swashbuckle.AspNetCore#875]
Hi,

I want to return the value of Int64 or UInt64.
But wrong value has been displayed in Swagger UI.

Controller:
`[HttpGet] public IActionResult GetValue() { return Ok(Int64.MaxValue); }`
Int64.MaxValue = 9223372036854775807

Response body (in Swagger UI):
`9223372036854776000`
Why is it rounded up?

Other tools (e.g.Postman) showed the correct value.
`9223372036854775807`

**Comment by domaindrivendev** [comment]
The UI is constrained by JavaScripts max int:
https://github.com/swagger-api/swagger-ui/issues/299

**Comment by aratomo-arazon** [comment]
Thank you for answering.
Sorry, I did not know that it was a known matter.
