### ISSUE TITLE
Property description not showing for some classes

### ISSUE THREAD

**Issue by SiddiquiImran** [domaindrivendev/Swashbuckle.AspNetCore#883]
Hi ,

Have added swagger in one of my recent ASP.NET core Web API  project , there I am facing a wired issue.
I have some domain classes for which I have created a separate class library project and have added reference in API project.
`public class Expense
    {
        [JsonProperty("tenantId")]
        [JsonRequired]
        [Description("Id of the tenant.")]
        public Guid TenantId { get; set; }

        [JsonProperty("id")]
        [JsonRequired]
        [Description("Internal ID of the Expense.")]
        public Guid Id { get; set; }

        [JsonProperty("number")]
        [JsonRequired]
        [Description("Internal number of the Expense.")]
        public string Number { get; set; }

        [JsonProperty("date")]
        [JsonRequired]
        [Description("date of the Expense.")]
        public DateTime Date { get; set; }

        [JsonProperty("type")]
        [JsonRequired]
        [Description("type of the Expense.")]
        public string Type { get; set; }

        [JsonProperty("lockDate")]
        [Description("date of the invoice when it Expense.")]
        public DateTime? LockDate { get; set; }

        [JsonProperty("supplier")]
        [Description("Detail of the supplier.")]
        [JsonRequired]
        public Supplier Supplier { get; set; }

        [JsonProperty("positions")]
        [Description("Expense positions.")]
        public List<ExpensesPosition> Positions { get; set; }

        [JsonProperty("payments")]
        [Description("Expense payments.")]
        public List<ExpensePayment> Payments { get; set; }

        [JsonProperty("state")]
        [Description("state of the invoice. Enum: [ open, paid]")]
        //[JsonRequired]
        public string State { get; set; }

        [JsonProperty("totalNet")]
        [JsonRequired]
        [Description("Total net of Expense.")]
        public decimal TotalNet { get; set; }

        [JsonProperty("vat")]
        [Description("vat applied on Expense.")]
        public Dictionary<string, decimal> Vat { get; set; }

        [JsonProperty("totalGross")]
        [JsonRequired]
        [Description("Total gross of Expense.")]
        public decimal TotalGross { get; set; }

        [JsonProperty("paymentDueDate")]
        [Description("Last date to pay due.")]
        public Nullable<DateTime> PaymentDueDate { get; set; } = DateTime.Now;

        [JsonProperty("discountDays")]
        [Description("no of days discount will be applicable in Expense.")]
        public Nullable<long> DiscountDays { get; set; } = 0;

        [JsonProperty("discountPercent")]
        [Description("Discount Percent applied in the Expense.")]
        public Nullable<decimal> DiscountPercent { get; set; } = 0.0M;

        [JsonProperty("paymentOpenAmount")]
        [Description("Amount which is still need to pay for the Expense.")]
        public decimal PaymentOpenAmount { get; set; }
    }`
This class showing up properly in swagger document with descpription as well but other class in same dll is not showing description of properties:

`public class Accounts
    {
        [JsonProperty("id")]
        [Description("Internal ID of the account.")]
        public Guid Id { get; set; }

        [JsonProperty("contactId")]
        [Description("ContactID to which this account belongs.")]
        public Guid ContactId { get; set; }

        [JsonProperty("accountName")]
        [Description("Name of the account.")]
        public string AccountName { get; set; }

        [JsonProperty("accountCurrency")]
        [Description("Currency of the account.")]
        public string AccountCurrency { get; set; }

        [JsonProperty("accountHolder")]
        [Description("Account holder name.")]
        public string AccountHolder { get; set; }

        [JsonProperty("accountBalance")]
        [Description("Bank balance.")]
        public Decimal AccountBalance { get; set; }

        [JsonProperty("accountBalanceDate")]
        [Description("Timestamp of the Bank balance.")]
        public DateTime AccountBalanceDate { get; set; }

        [JsonProperty("accountIban")]
        [Description("IBAN of the target account.")]
        public string AccountIban { get; set; }

        [JsonProperty("accountType")]
        [Description("Type of account.")]
        public int AccountType { get; set; }

        [JsonProperty("accountActive")]
        [Description("Account status. Indicates whether the account was activated during the contact setup.")]
        public bool AccountActive { get; set; }

        [JsonProperty("orderId")]
        [Description("Orderid of account.")]
        public int OrderId { get; set; }
    }`

Have also tried to create separate xml comment xml file for this dll but there I got another issue like how to load both xml .

**Comment by domaindrivendev** [comment]
Swashbuckle does not currently support the `DescriptionAttribute`. You need to use XML comments to add human readable descriptions - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments. Is this what you're doing? Multiple calls to `IncludeXmlComments` (i.e. with difference files) should work just fine

**Comment by Logikoz** [comment]
> Swashbuckle does not currently support the `DescriptionAttribute`. You need to use XML comments to add human readable descriptions - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#include-descriptions-from-xml-comments. Is this what you're doing? Multiple calls to `IncludeXmlComments` (i.e. with different files) should work just fine

this works for me, ty
