### ISSUE TITLE
Expose controller type in `ActionDescriptor`

### ISSUE THREAD

**Issue by RobThree** [domaindrivendev/Swashbuckle.AspNetCore#885]
See https://github.com/domaindrivendev/Swashbuckle/issues/1262

I want to be able to override ("manually set") in which order my controllers are documented.

I would like to get to the actual controller in `OrderActionsBy` so I can get to it's attributes etc. However, this is not possible. The closest I can get is the `ActionDescriptor` which doesn't contain the information I want/need. I did notice the `ActionDescriptor` has a `ControllerTypeInfo`; if that could be exposed I think I can use that and some reflection to get to the controller's attributes. (Sidenode: `ControllerTypeInfo` should probably be named `ControllerType`, assuming it is of type `Type`).

Edit: thinking about it... the `OrderActionsBy` accepts a `Func<ApiDescriptor, string>` which means only ordering by strings is possible (but as a user I can't know/see what kind of ordering is used (case sensitive, which culture, which sorting rules?). This is pretty limiting IMHO. Should I want to implement the same trick I did in the mentioned link I'd have to, somehow, turn the values of the attributes into a string which will, in turn, cause all sorts of problems because when sorted as strings this results in the sequence `1, 11, 2, 20, 3`. I could work around _that_ by turning the values in some 'creative' strings that would result in correct ordering but that would be a huge mess. What is, again IMHO, actually needed is at least an override that accepts `Func<ApiDescriptor, int>` (and the above suggestion to expose the controller's Type). That would make it a whole lot more flexible.

**Comment by challamzinniagroup** [comment]
I'm not sure where you are trying to get the controller information, it sounds like the ` OrderActionsBy ` method - but I've used a workaround for pulling attributes off the controller in many places of the SwaggerGen DI injection.

As an example, try something like this (this is in the ` TagActionsBy ` method but should translate the same):
```
services.AddSwaggerGen(opts =>
{
	// set custom Tag grouping
	opts.TagActionsBy(api =>
	{
		var controllerActionDescriptor = (ControllerActionDescriptor) api.ActionDescriptor;
		return ((DocTagAttribute)controllerActionDescriptor.MethodInfo.GetCustomAttribute(
				typeof(DocTagAttribute)))?.Tag ?? "UNKNOWN";
	});
});
```
By simply casting the ` api.ActionDescriptor` as a ` ControllerActionDescriptor ` you are then able to see all things controller related.

An examination of the ` controllerActionDescriptor ` during a breakpoint should give you all the details you are looking for:

  | Name | Value | Type
-- | -- | -- | --
◢ | controllerActionDescriptor | "{*removed value*}" | Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor
  | ▶ ActionConstraints | Count = 1 | System.Collections.Generic.IList<Microsoft.AspNetCore.Mvc.ActionConstraints.IActionConstraintMetadata> {System.Collections.Generic.List<Microsoft.AspNetCore.Mvc.ActionConstraints.IActionConstraintMetadata>}
  | ActionName | "{*removed value*}" | string
  | ▶ AttributeRouteInfo | {Microsoft.AspNetCore.Mvc.Routing.AttributeRouteInfo} | Microsoft.AspNetCore.Mvc.Routing.AttributeRouteInfo
  | ▶ BoundProperties | Count = 0 | System.Collections.Generic.IList<Microsoft.AspNetCore.Mvc.Abstractions.ParameterDescriptor> {System.Collections.Generic.List<Microsoft.AspNetCore.Mvc.Abstractions.ParameterDescriptor>}
  | ControllerName | "{*removed value*}" | string
  | ▶ ControllerTypeInfo | {*removed value*} | System.Reflection.TypeInfo {System.RuntimeType}
  | DisplayName | "{*removed value*}" | string
  | ▶ FilterDescriptors | Count = 7 | System.Collections.Generic.IList<Microsoft.AspNetCore.Mvc.Filters.FilterDescriptor> {System.Collections.Generic.List<Microsoft.AspNetCore.Mvc.Filters.FilterDescriptor>}
  | Id | "87b460b9-918c-469b-9d0b-f41d28053940" | string
  | ▶ MethodInfo | {System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] {*removed value*}(System.Nullable`1[System.Guid])} | System.Reflection.MethodInfo {System.Reflection.RuntimeMethodInfo}
  | ▶ Parameters | Count = 1 | System.Collections.Generic.IList<Microsoft.AspNetCore.Mvc.Abstractions.ParameterDescriptor> {System.Collections.Generic.List<Microsoft.AspNetCore.Mvc.Abstractions.ParameterDescriptor>}
  | ▶ Properties | Count = 2 | System.Collections.Generic.IDictionary<object, object> {System.Collections.Generic.Dictionary<object, object>}
  | ▶ RouteValues | Count = 2 | System.Collections.Generic.IDictionary<string, string> {System.Collections.Generic.Dictionary<string, string>}

**Comment by domaindrivendev** [comment]
@RobThree can this be closed?

**Comment by RobThree** [comment]
Uhm, if you want to but quite honestly I still think a better method to 'force' some ordering would be at the very least a 'nice to have'.

**Comment by dungtri** [comment]
In my case, I need to just order controllers ordering in Swagger.

On asp.net core 2.2, by using the workaround I forced the ordering succesfully with **OrderActionsBy** method.

SwaggerControllerOrderAttribute can be optionally inserted on controller I need to see at the top of the list.



```
config.TagActionsBy(api => api.GroupName);
config.OrderActionsBy(api =>
{
    var controllerActionDescriptor = (ControllerActionDescriptor)api.ActionDescriptor;
    var attribute = (SwaggerControllerOrderAttribute)controllerActionDescriptor.ControllerTypeInfo.GetCustomAttribute(typeof(SwaggerControllerOrderAttribute));
                    return attribute != null ? attribute.Order : api.GroupName;
                });
```
