### ISSUE TITLE
BindRequired not honored in Model

### ISSUE THREAD

**Issue by Eneuman** [domaindrivendev/Swashbuckle.AspNetCore#893]
I am using the lastes version Swashbuckle and .Net Core 2.1.

My controller has the
`  [ApiController]`
attribute set to it.

I have the following method in my controller:
```
    [HttpPost()]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [SwaggerOperation(OperationId = "CreateFile")]
    public async Task<ActionResult<int>> CreateFileAsyncV1(CreateFileCommandV1 command, [FromHeader(Name = "x-requestid"), BindRequired] Guid requestId)
    {
      if (await _requestManager.ExistAsync(requestId))
        return StatusCode(StatusCodes.Status409Conflict);

      var id = await _mediator.Send(command);
      await _requestManager.CreateRequestForCommandAsync<CreateFileCommandV1>(requestId);

      return CreatedAtAction(nameof(GetFileAsyncV1), new { id = id }, id);
    }
```

and the model:

```
  public class CreateFileCommandV1 : MediatR.IRequest<int>
  {
    [BindRequired]
    public int PrislistaId { get; set; }

    [BindRequired]
    public DateTime PeriodStart { get; set; }

    [BindRequired]
    public DateTime PeriodStop { get; set; }
  }
```

According to the documentation

> In addition to parameters, Swashbuckle will also honor the RequiredAttribute when used in a model that's bound to the request body. In this case, the decorated properties will be flagged as "required" properties in the body description:

I though that the generated swagger file would have "Required" set to the PeriodStart and PeriodStop properties but it doesn't. Is this the correct behaviour?

Swagger generated model:
`"CreateFileCommandV1":{"type":"object","properties":{"prislistaId":{"format":"int32","type":"integer"},"periodStart":{"format":"date-time","type":"string"},"periodStop":{"format":"date-time","type":"string"}}}`

Using [BindRequired, Required] instead of [BindRequired] solves the problem, but that doesnt seem right?

**Comment by domaindrivendev** [comment]
Use the RequiredAttribute instead of BindRequiredAttribute. In ASP.NET Core, the latter is only applicable for “non body” parameters
