### ISSUE TITLE
Oauth2: Why does Swagger make the client id something that can be edited?

### ISSUE THREAD

**Issue by VictorioBerra** [domaindrivendev/Swashbuckle.AspNetCore#895]
![image](https://user-images.githubusercontent.com/2934507/46156217-99450b80-c23e-11e8-9213-31b2fedeb79d.png)

With implicit auth flow, the client Id and the return url are strongly tied together.

A user is never given a client id, it always belongs to the app. So why do they show it as an editable text entry on the Swagger UI? Can we make this read only?

**Comment by VictorioBerra** [comment]
I am assuming this is because if you use clientCredentials low, you can edit this so maybe its using the same template? I haven't dug into the codebase i dont have time to ramp up on this codebase.

**Comment by arlan85** [comment]
Hi @VictorioBerra Did you find an answer to this? Thank you.

**Comment by VictorioBerra** [comment]
I have not.

**Comment by arlan85** [comment]
You can try use another auth flow: 
implicit - Implicit
password - resource owner password credentials
application - client credentials
accessCode - authorization code

**Comment by domaindrivendev** [comment]
This looks like a question for the [swagger-ui project](https://github.com/swagger-api/swagger-ui) and not Swashbuckle
