### ISSUE TITLE
Using IFormFile does not generate type in swagger json and fails validation

### ISSUE THREAD

**Issue by adamkjonesmesh** [domaindrivendev/Swashbuckle.AspNetCore#896]
I have an endpoint with the following signature:
```
public async Task<IActionResult> UploadFile(IFormFile file, ObjectStorageFileUploadRequest fileUploadRequest)
```
The above endpoint is part of a asp.netcore API.  I deploy this API to an azure web service.  Everything works fine; however, I then grab the swagger json URL and import it into editor. swagger.ui (or attempt to import into azure api gateway) and the following error occurs:

```
Schema error at paths['/api/v1.0/storage/object/files/upload'].post.parameters[0].in
should be equal to one of the allowed values
allowedValues: body
Jump to line 207
```
First, let me note that the error is misleading.  The actual error is that the "type" property is missing in the generated swagger json.  The generated schema looks like this:
```
parameters:
        - name: file
          in: query
          description: File to upload
          required: false
```
Notice in the above schema, the "type" property is missing.  The type should be file.  This is a serious problem.  Is there a workaround or some way to get the generated json to issue the correct type when using IFormFile?

**Comment by maximebousquet** [comment]
Adding to this, shouldn't the "in" property be "form"? Since you're using an `IFormFile` ? Are you using the `[ApiController]` attribute on your controller? Asking those questions because I get a similar problem:

![image](https://user-images.githubusercontent.com/5472559/47027751-08bf6400-d136-11e8-9678-e12b692597eb.png)

However, mine is that the type is present but that it is object, but object should not be allowed in a "query" according to this: 

![image](https://user-images.githubusercontent.com/5472559/47028156-c5b1c080-d136-11e8-8abd-2952e3f0c713.png)

Under **Parameter Object** [here](https://swagger.io/specification/v2/).

**Comment by mswilson4040** [comment]
@domaindrivendev This seems to be an issue in v5.3.1 Is there any open issue for this or is this known?

**Comment by Danielku15** [comment]
I can also confirm that this is still an issue. But if I see it correctly it might already an issue in the ApiExplorer. If you have an `IFormFile` parameter, the API explorer already rewrites it to a list of flat properties of the IFormFile:
![image](https://user-images.githubusercontent.com/674916/84233468-aed19600-aaf2-11ea-8075-378417dc1f63.png)

At least that's what I see if I inspect the `context.ApiDescription` in my `IOperationFilter`. Unless Swashbuckle does a rewrite there to flatten the IFormFile properties in a preprocessing step we might need to get a fix in ApiExplorer or SwashBuckle needs to dig deeper on the mapping of properties. The `ApiParameterDescription.ParameterDescriptor` seems to contain the original IFormFile parameter which would allow handling it.

**Comment by ophirKatz** [comment]
> In ASP.Net Core “IFormFile” and “FromForm” are different concepts and should not be used together. There’s no need to decorate the param with “FromForm” and in fact, it’s technically incorrect to do so

I can't understand why that is (and where is it documented). IFormFile is an abstract to receive a binary file over http. FromForm simple tells the framework where in the request to take the content from - either from the request body or the request form. So if I want to pass files as FormData i.e. in the request form, then I'll use the FromForm binder, and the type of the data will be IFormFile. Where am I getting this wrong?
By the way, I'm encountering an issue similar to the described in this issue - I have a request model the is marked with the FromForm binder in the controller, the model has an IFormFile property. In this case the model type is not generated to the openapi document. The operation is shown in the swagger ui, but with the model's properties as parameters instead.
Any idea why? I think I described it well enough but If you'd like to see a code example for repro I'll open a new issue (Just wanted to put things in context)

**Comment by Kevin-Andrew** [comment]
@ophirKatz 

>> In ASP.Net Core “IFormFile” and “FromForm” are different concepts and should not be used together. There’s no need to decorate the param with “FromForm” and in fact, it’s technically incorrect to do so

> I can't understand why that is (and where is it documented).

The documentation is at:
https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.0#binding-source-parameter-inference
where it states the following:
> [FromForm] is inferred for action parameters of type [IFormFile](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iformfile) and [IFormFileCollection](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.iformfilecollection). It's not inferred for any simple or user-defined types.

Note that domaindrivendev only said, "...it's _technically_ incorrect...", he did not say it flat out couldn't be done. But it is unnecessary to explicitly specify `[FromForm]` on a parameter of type `IFormFile`.

Also note that, at least for us, to support a file upload from an HTML <form>, as what I believe you're describing, we also had to add a `[Consumes("multipart/form-data")]` attribute to our API controller end point method. So as a complete example, here is one of our API methods that supports file upload. The caller is able to make the request one of two ways, using Ajax and setting the `data` property of the request to the HTML file input control (you should be able to find numerous examples of that on the Internet), or by posting a plain HTML form that contains a file input element and `enctype` attribute set to `multipart/form-data`.
```
[HttpPost("Upload")]
[Consumes(HttpHeaderValues.ApplicationOctetStream, "multipart/form-data"), DisableRequestSizeLimit] // While the Swagger UI does work if only ApplicationOctetStream is specified with the IFromFile parameter, including the multipart/form-data allows for plain browser/HTML form based support and being able to properly document the parameter.
[ProducesResponseType(StatusCodes.Status201Created, Type = typeof(Backup))]
[ProducesResponseType(StatusCodes.Status403Forbidden)]
public async Task<IActionResult> UploadBackupAsync(/* This enables file upload in swagger */ IFormFile fileData, CancellationToken cancellationToken)
{
        cancellationToken.Register(async () => await CancelBackupAsync());
        var result = await _logic.SaveFileFromStreamAsync(fileData?.OpenReadStream() ?? Request.Body);

        return CreatedAtRoute("upload/file");
    }
}
```
