### ISSUE TITLE
Ambiguous HTTP method for action for non-API routes using IDocumentFilter

### ISSUE THREAD

**Issue by clayiam** [domaindrivendev/Swashbuckle.AspNetCore#899]
Hi,

I recently upgraded my project from ASP.NET Core 2.0.7 / Swashbuckle 2.4.0 to the following details

ASP.NET Core 2.1.1
Swashbuckle.AspNetCore 3.0.0

In my startup.cs, I was using this quite happily before to generate the Swagger doc for only API specific controllers and models.

` c.DocumentFilter<ApiOnlyFilter>();`

The Filter
```
    public class ApiOnlyFilter : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
        {
            swaggerDoc.Paths = swaggerDoc.Paths.Where(m => m.Key.StartsWith("/api"))
                .ToDictionary(entry => entry.Key, entry => entry.Value);

            var dict = new Dictionary<string, Schema>();
            foreach (var definition in swaggerDoc.Definitions)
            {
 
                if (type != null)
                {
                    dict.Add(definition.Key, definition.Value);
                }
            }

            swaggerDoc.Definitions = dict;
        }
    }
```
It would just throw this error:

```
NotSupportedException: Ambiguous HTTP method for action - WebEssentials.AspNetCore.Pwa.PwaController.ServiceWorkerAsync (WebEssentials.AspNetCore.Pwa). Actions require an explicit HttpMethod binding for Swagger 2.0
```
After disabling Pwa ServiceWorker, it would still throw the same error

Eventually I came across this issue: #676 and saw your suggestion about the IActionModelConvention.

I implemented the following convention to only apply to actions with the [SwaggerOperationAttribute] as my API controllers are generated by https://github.com/OpenAPITools/openapi-generator

```
public class ApiExplorerConvention : IActionModelConvention
{
    public void Apply(ActionModel action) => action.ApiExplorer.IsVisible = action.Attributes.OfType<SwaggerOperationAttribute>().Any();
}
```
And implemented it like this:
```
services.AddMvc(options =>
{
    options.Conventions.Add(new ApiExplorerConvention());
});
```

**Comment by RugerSR9** [comment]
Quick update for anyone experiencing this issue in 2019.

The `SwaggerOperationAttribute` attribute was moved to a new Nuget Package called `Swashbuckle.AspNetCore.Annotations` which will need to be added to your project.

**Comment by cesguto** [comment]
I solved my problem by including the `[NonAction]` signature in the header of functions that were not endpoints

Example

    ```
[ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]
    public class RequestController : ControllerBase {

        [NonAction]
        public ObjectResult SetError( Exception e)
        {
            return StatusCode(500, e.Message);
        }
    }
```
