### ISSUE TITLE
Please release packages targeting netstandard2.0

### ISSUE THREAD

**Issue by bherila** [domaindrivendev/Swashbuckle.AspNetCore#912]
Blocking #901

**Comment by bherila** [comment]
Here are sample packages: https://github.com/bherila/Swashbuckle.AspNetCore/releases/tag/4.0.0

**Comment by domaindrivendev** [comment]
The master branch in this repo already targets netstandard2.0. The official nuget release is still pending another feature but you can download packages that are built from latest master from myget.org. So sample packages are available

**Comment by bherila** [comment]
> you can download packages that are built from latest master from myget.org

This is helpful, thank you!

**Comment by domaindrivendev** [comment]
No worries. Although it does look like they’re changing things up a bit, possibly pushing for more paying users, so finding the download page may be difficult. Use the following list no and you should be good:

https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore
