### ISSUE TITLE
Meaningless 500 Internal Server Error

### ISSUE THREAD

**Issue by Deilan** [domaindrivendev/Swashbuckle.AspNetCore#916]
Right now if we have some 500 Internal Server Error as a result of something went wrong with `Swashbuckle.AspNetCore`, it gives us no clue about what's exactly wrong: both json and UI are silent about it. Stack trace in logs also not very helpful. It's very painful to troubleshoot the problems and it prevents from integrating swagger into existing projects.

I propose to provide some contextual information along with just stating there's some error. It should be configurable in a similar fashion we can configure provision of exception details in different environments in vanilla ASP.NET Core at `Startup#ConfigureServices`:
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    // ...
    if (env.IsDevelopment())
        app.UseDeveloperExceptionPage();
    else
        app.UseExceptionHandlerMiddleware();
    // ...
}
```
So that internal details not leak to production environment, but present in a development environment.

It should be also considered to throw exception right in-place on configuring `Swashbuckle.AspNetCore`. As an example you can take a look at Automapper's `Mapper.Configuration.AssertConfigurationIsValid();` ([docs](http://docs.automapper.org/en/stable/Configuration-validation.html)).

**Comment by domaindrivendev** [comment]
By enabling the standard DeveloperExceptionPage as you’ve shown above - all exceptions thrown by SB should be surfaced. Are you not observing this behavior?

**Comment by Deilan** [comment]
I have messed up with the order of middleware units: Swagger was before Developer exception page. Sorry about that. :) After fixing the order, the exception page with description appeared.
