### ISSUE TITLE
Tags out of order with includeControllerXmlComments

### ISSUE THREAD

**Issue by JustGentle** [domaindrivendev/Swashbuckle.AspNetCore#918]
Using `AspNetCore 2.1.1` and `Swashbuckle.AspNetCore 3.0.0`
When I use 'SwaggerGenOptions.IncludeXmlComments' without parameter `includeControllerXmlComments`, the API order by tag name, everything work perfect.
```
options.IncludeXmlComments(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Test.Web.Host.XML"));
options.IncludeXmlComments(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Test.Application.XML"));
```
![01](https://user-images.githubusercontent.com/25601771/47201211-abcce380-d3ab-11e8-9d9d-ea0ba5562f77.png)
then i use it and API list got out of order:
```
options.IncludeXmlComments(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Test.Web.Host.XML"), true);
options.IncludeXmlComments(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Test.Application.XML"), true);
```
![02](https://user-images.githubusercontent.com/25601771/47201212-ac657a00-d3ab-11e8-98f9-829413bb7ce1.png)
So i try to add OrderActionsBy but nothing happen:
```
options.OrderActionsBy(a =>
{
    return $"{a.ActionDescriptor.RouteValues["controller"]}";
});
```
By the way, my  XmlComments is Chinese, like this:
```
    /// <summary>
    /// 公共模块
    /// </summary>

    public class CommonController : BaseController<ICommonService>
    {
    }
```
did i made any mistake?

**Comment by domaindrivendev** [comment]
So, the addition of the group description (via `includeControllerXmlComments`) actually adds a global `tags` section (see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object) to the generated Swagger JSON. When present, this tag section and the order of tag metadata within it dictates the order of operation groups in the [swagger-ui](https://github.com/swagger-api/swagger-ui).

**Comment by domaindrivendev** [comment]
I believe the following commit should resolve this - e2f30e04f412b821a5a989338a186e422c776cc4

But, you'll need to wait for and upgrade to v5.0.0 to avail of it. In the meantime, you can workaround with the following document filter:


```csharp
// TagReOrderDocumentFilter.cs
public class TagReOrderDocumentFilter : IDocumentFilter
{
    public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
    {
        swaggerDoc.Tags = swaggerDoc.Tags
            .OrderBy(tag => tag.Name)
            .ToList();
    }
}

// Startup.cs
options.IncludeXmlComments(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Test.Web.Host.XML"), true);
options.IncludeXmlComments(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Test.Application.XML"), true);
options.DocumentFilter<TagReOrderDocumentFilter>();
```

**Comment by kuntalbose** [comment]
Hi I use bellow packages of v5.0.0

 ```
<PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="5.6.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="6.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="5.6.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.ReDoc" Version="5.6.3" />
```
and facing same ordering issue ,fix after using above code.
