### ISSUE TITLE
Define Explicit Model

### ISSUE THREAD

**Issue by kashif-imagyn** [domaindrivendev/Swashbuckle.AspNetCore#920]
I have a requirement to define explicit Model for each request same as we can define in Response
i have a generic Model for every function which is encrypted string ,after decryption i am casting it in original model and then validating model swagger is picking the encrypted model as parameter but i want to define the original model in documentation.

Thanks for contributing to Swashbuckle.AspNetCore! As per the [contributing guidelines](CONTRIBUTING.md), please adhere to the following rules of thumb before submitting your issue:

1. If it's not a bug report, feature request or PR, don't submit it here. Post to Stackoverflow instead.
2. If your issue is specifically a UI concern, don't submit it here. Post to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui).
3. For bug reports, specify the version your using and provide clear repro steps.

**Comment by domaindrivendev** [comment]
There's nothing out-of-the-box to support your specific use-case. However, SB exposes a number of extensibility points that might help. Have you looked at the following readme sections?

- https://github.com/domaindrivendev/Swashbuckle.AspNetCore#override-schema-for-specific-types
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore#extend-generator-with-operation-schema--document-filters

To give you a little inspiration, I think something along the following lines might work for you:

```csharp
// Create a custom attribute for specifying explicit request body type
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
public class RequestBodyTypeAttribute : Attribute
{
    public RequestBodyTypeAttribute(Type type)
    {
        Type = type;
    }

    public Type Type { get; set; }
}

// Create a filter that detects the attribute and updates the request body schema(s) accordingly
public class RequestBodyTypeFilter : IRequestBodyFilter
{
    public void Apply(OpenApiRequestBody requestBody, RequestBodyFilterContext context)
    {
        var parameterInfo = context.BodyParameterDescription?.ParameterInfo();

        var attribute = parameterInfo?.GetCustomAttributes(false)
            .OfType<RequestBodyTypeAttribute>()
            .FirstOrDefault();

        if (attribute == null) return;

        var schema = context.SchemaGenerator.GenerateSchema(
            type: attribute.Type,
            schemaRepository: context.SchemaRepository,
            parameterInfo: parameterInfo);

        foreach (var mediaType in requestBody.Content.Values)
        {
            mediaType.Schema = schema;
        }
    }
}
```

```csharp
// Startup.cs - wire up the filter
c.AddSwaggerGen(c =>
{
    ...
    
    c.RequestBodyFilter<RequestBodyTypeFilter>();
}
```
