### ISSUE TITLE
(minor issue) 3.0.0 Swashbuckle.AspNetCore.SwaggerUI dll size

### ISSUE THREAD

**Issue by MichaCo** [domaindrivendev/Swashbuckle.AspNetCore#922]
Hi,
After upgrading some of our services to use 3.0.0, we found that the size of our artifacts increased by a bunch.
And it is because the `Swashbuckle.AspNetCore.SwaggerUI.dll` is now 11MB big, from ~2MB previously.

Is there any reason to include the `.map` files as a resource within the dll?

![image](https://user-images.githubusercontent.com/5837539/47518019-21dcb900-d88a-11e8-9fbe-8184e9d4ba15.png)

Thanks!

**Comment by domaindrivendev** [comment]
See 45d88beb2c2ab17dd5a6745cb02a4659324cdffc

**Comment by MichaCo** [comment]
@domaindrivendev nice, thanks!
