### ISSUE TITLE
Enum No't Annotated Display

### ISSUE THREAD

**Issue by wangliqiang1026** [domaindrivendev/Swashbuckle.AspNetCore#923]
I didn't see any comments for the enumeration, just int or string, and I didn't know what to do, and I looked at the instructions earlier, and I didn't find the right way for it to show up.

**Comment by erendrake** [comment]
@wangliqiang1026 swagger 2.0 doesnt have a specification for description on individual enum values.
https://swagger.io/docs/specification/2-0/enums/ 

there is an open request for this in the OAI repo https://github.com/OAI/OpenAPI-Specification/issues/348

**Comment by domaindrivendev** [comment]
As it's not currently supported by the Swagger/OpenAPI specification, it's not currently supported by SB.
