### ISSUE TITLE
Hi!, I am wondering if you support .NET Standard 2.0?

### ISSUE THREAD

**Issue by learnersm** [domaindrivendev/Swashbuckle.AspNetCore#927]

**Comment by tohidazizi** [comment]
I am not sure if this is the right place to ask such a question, but according to the NuGet page [(https://www.nuget.org/packages/Swashbuckle.AspNetCore/)](https://www.nuget.org/packages/Swashbuckle.AspNetCore/), Swashbuckle.AspNetCore has .NETStandard 1.6 dependency, which means YES, .NETStandard 2.0 would be OK with the latest version of Swashbuckle.AspNetCore.

**Comment by learnersm** [comment]
Thanks, sorry for the lack of clarity!
