### ISSUE TITLE
ReDoc's SupressWarnings doesn't work 

### ISSUE THREAD

**Issue by Leon99** [domaindrivendev/Swashbuckle.AspNetCore#929]
Despite setting `...ConfigObject.SupressWarnings = true`, ReDoc still shows warnings at the top of the page.

**Comment by domaindrivendev** [comment]
Can you provide a set of repro steps - specifically I want to know what constitutes a _warning_ and how do I trigger one to test out the flag?

**Comment by Leon99** [comment]
Here's what I get once I add `options.ExampleFilters();` inside `services.AddSwaggerGen`:

![image](https://user-images.githubusercontent.com/6840381/48239644-c8e15900-e423-11e8-9e02-ea2d19111ddc.png)
Not sure yet what exactly in my examples triggers it.

**Comment by Leon99** [comment]
OK I found a reason of those warnings, it's a problem with Swashbuckle.AspNetCore.Filters. It generates an incorrest JSON for a request example, so should be easy for you to reproduce.

**Comment by Leon99** [comment]
Looks like I found the reason for those warnings. It's a problem with Swashbuckle.AspNetCore.Filters. It generates an incorrest JSON for a parameter example, so should be easy for you to reproduce.

**Comment by OpenWindow** [comment]
Property `SupressWarnings` in `ConfigObject` is misspelled. It should be `SuppressWarnings`. The fix is in a [PR 1001](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1001) along with other changes. Not sure when that will be merged.

**Comment by OpenWindow** [comment]
@Leon99 , not sure if you still want suppressWarnings to work. PR 1001 is approved but not deployed nuget to use it. Mean while, there is an alternate to make it work with Version="4.0.1". Instead of using `SupressWarnings `use `AdditionalItems `property in `ConfigObject`. The below code worked for me.

``` csharp
      app.UseReDoc(c =>
            {
                c.SpecUrl = "../swagger/v1/swagger.json";                
                c.ConfigObject = new Swashbuckle.AspNetCore.ReDoc.ConfigObject() {
                    AdditionalItems = { { "suppressWarnings", true } }
                    
                };
            });
```

**Comment by domaindrivendev** [comment]
Fixed as part of https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1001
