### ISSUE TITLE
In a project that has odata and api controller only odata controller that appear in swagger

### ISSUE THREAD

**Issue by saktya** [domaindrivendev/Swashbuckle.AspNetCore#933]
I have a project that has OData Controller and Api controller inside it and I would like to show the doc in Swagger UI.
I implement following config in my startup.cs

     public void ConfigureServices( IServiceCollection services )
        {
            services.AddMvc();
            services.AddApiVersioning( options => options.ReportApiVersions = true );
            services.AddOData().EnableApiVersioning();
            services.AddODataApiExplorer(
                options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                } );
            services.AddSwaggerGen(
                options =>
                {
                    var provider = services.BuildServiceProvider().GetRequiredService<IApiVersionDescriptionProvider>();
                    
                    foreach ( var description in provider.ApiVersionDescriptions )
                    {
                        options.SwaggerDoc( description.GroupName, CreateInfoForApiVersion( description ) );
                    }
                } );
        }

and this

    public void Configure( IApplicationBuilder app, IHostingEnvironment env, VersionedODataModelBuilder modelBuilder, IApiVersionDescriptionProvider provider )
        {
            app.UseMvc( routeBuilder => routeBuilder.MapVersionedODataRoutes( "odata", "api", modelBuilder.GetEdmModels() ) );
            app.UseSwagger();
            app.UseSwaggerUI(
                options =>
                {
                    // build a swagger endpoint for each discovered API version
                    foreach ( var description in provider.ApiVersionDescriptions )
                    {
                        options.SwaggerEndpoint( $"/swagger/{description.GroupName}/swagger.json", description.GroupName.ToUpperInvariant() );
                    }
                } );
        }

the result is all my odata controller and method appear in Swagger UI, but my API Controller not appear at all.

Is there something that I miss?

**Comment by dviry** [comment]
I think you are missing the XML comments, otherwise .AddSwaggerGen() will not know from where to get all the details... (add this inside .AddSwaggerGen())
```c#
//Set the comments path for the swagger json and ui.
var basePath = PlatformServices.Default.Application.ApplicationBasePath;
var xmlPath = Path.Combine(basePath, "<your project name>.xml");
options.IncludeXmlComments(xmlPath);
```

**Comment by domaindrivendev** [comment]
Dup of #581
