### ISSUE TITLE
Missing the method OperationFilter

### ISSUE THREAD

**Issue by barabasishe** [domaindrivendev/Swashbuckle.AspNetCore#935]
After updating to 4.0.1, I get the exception 

> "Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.OperationFilter(System.Object[])'."

in the following code:
```c#
services.AddSwaggerGen(c => 
{
    ...
    c.ExampleFilters(); // <---- exception is here
    ...
}
```

Some investigation showed me that probably you forgot add corresponding namespace `Microsoft.Extensions.DependencyInjection` (which now contains this method definition) in the file `SwaggerGenOptionsExtensions` (where the definition of method `ExampleFilters` is situated) of `Swashbuckle.AspNetCore.Filters` library

**Comment by domaindrivendev** [comment]
Swashbuckle.AspNetCore.Filters is a [separate project](https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters) that's maintained by someone else. You should post this issue there instead.

The relevant extension methods were moved to the `Microsoft.Extensions.DependencyInjection` namespace to optimize for the most common case - where the generator service is configured in `Startup.cs`. That is, when the `SwaggerGen` package is referenced - you will have immediate intellisense access to the `AddSwaggerGen` method on `IServicesCollection` _AND_ the configuration API on the options that are passed into that method, without having to add a `using` statement to the top of that file.

**Comment by barabasishe** [comment]
Yes, I've noticed that this method was moved to the this namespace.
Sorry for my inattention.

**Comment by mattfrear** [comment]
> The relevant extension methods were moved to the Microsoft.Extensions.DependencyInjection namespace to optimize for the most common case...

Ah, I wondered why they'd moved.

**Comment by Leon99** [comment]
Wow, I couldn't even imagine VS still doesn't include methods from non-imported namespaces in the autocomplete. They clearly don't want to (really) compete with JetBrains...
