### ISSUE TITLE
QUESTION: Do you have plans to support ReDoc version 2?

### ISSUE THREAD

**Issue by freeranger** [domaindrivendev/Swashbuckle.AspNetCore#936]
Hi,

I am very interested in support for inheritance, which swagger supports but swagger-ui does not.
ReDoc supports this in version 2 so I was wondering if you have any plans to support ReDoc 2 and timescales for same?

thanks

**Comment by domaindrivendev** [comment]
As a general rule, I'll only take on official releases of dependencies. As far as I can tell, ReDoc 2.0 is still in pre-release phase. Once it's released proper, I'll certainly look at upgrading the version that ships with SB. Or, if you like to submit a PR ...
