### ISSUE TITLE
Issue with swagger.json and abstract classes

### ISSUE THREAD

**Issue by arlan85** [domaindrivendev/Swashbuckle.AspNetCore#939]
Hi, I'm facing issues getting specific implementations of abstract classes on swagger.json. Also I used [this feature](https://stackoverflow.com/a/49009485/4347363) but when I generate my SDK on [swagger editor](https://editor.swagger.io/) and use it, all api responses get the base abstract class. 
Can someone tell me what happens?

**Comment by domaindrivendev** [comment]
This boils down to limited support for polymorphic API types. While you can add definitions for the known sub-types using the workaround you referenced, there's no link between the types in the outputted Swagger. I'm going to close this issue as it's essentially a dup of #2.

With OpenAPI v3 support now added (see #952), we're in a better position to improve the support for polymorphic types. So, I'll be looking at this as a priority. Stay tuned ...
