### ISSUE TITLE
SwaggerGen produces duplicate consume entries

### ISSUE THREAD

**Issue by kieseld** [domaindrivendev/Swashbuckle.AspNetCore#942]
"consumes": [
          "application/json;odata.metadata=minimal;odata.streaming=true",
          "application/json;odata.metadata=minimal;odata.streaming=false",
          "application/json;odata.metadata=minimal",
          "application/json;odata.metadata=full;odata.streaming=true",
          "application/json;odata.metadata=full;odata.streaming=false",
          "application/json;odata.metadata=full",
          "application/json;odata.metadata=none;odata.streaming=true",
          "application/json;odata.metadata=none;odata.streaming=false",
          "application/json;odata.metadata=none",
          "application/json;odata.streaming=true",
          "application/json;odata.streaming=false",
          "application/json",
          "application/xml",
          "application/prs.odatatestxx-odata",
          "application/json-patch+json",
          "application/json",
          "text/json",
          "application/*+json",
          "application/xml",
          "text/xml",
          "application/*+xml"
        ],

**Comment by aaronclong** [comment]
Is there anyway that we could get this fixed pushed out in a minor version @kieseld?

It would really be a lifesaver. I made an issue as about this #995.

**Comment by kieseld** [comment]
@aaronclong I am not on the team, just a contributor. @domaindrivendev would have to release it.

**Comment by arslanaybars** [comment]
@aaronclong probably, you already solve your issue but I also matched with the same case and I would like to share my solution for future needers. (until new release) 😋 👌

write a operation filter.
```
public class SwaggerPreventDuplicateConsumeFilter : IOperationFilter
{
    public void Apply(Operation operation, OperationFilterContext context)
    {
        operation.Consumes = operation.Consumes.Distinct().ToList();
    }
}
```

then add to operation filter at ConfigureServices;
```
services.AddSwaggerGen(c =>
{
    // ...codes...
    c.OperationFilter<SwaggerPreventDuplicateConsumeFilter>();
    // ...codes...
});
```
