### ISSUE TITLE
Cant find a way to get 'consumes' to work 

### ISSUE THREAD

**Issue by kgrosvenor** [domaindrivendev/Swashbuckle.AspNetCore#944]
Is it possible to include docs on this subject, or rather then leaving it up to developers to implement as a custom filter, why cant we create annotations for this that work like the others do?

**Comment by domaindrivendev** [comment]
What specifically are you having trouble with? As of v4.0.0, the following should work just fine:

```csharp
[HttpPost("/api/products")]
[Consumes("application/vnd.api+json")]
public IActionResult CreateProduct([FromBody]Product product)
{
    ...
}
```

**Comment by kgrosvenor** [comment]
All good I found a way  👍
