### ISSUE TITLE
File upload not working in 4.0

### ISSUE THREAD

**Issue by MelGrubb** [domaindrivendev/Swashbuckle.AspNetCore#953]
I had a file upload which was working before I updated to v4, but throws javascript console errors now, specifically this one:

Error: Required parameter file is not provided
    at index.js:1
    at Array.forEach (<anonymous>)
    at Object.o [as buildRequest] (index.js:1)
    at actions.js:402
    at utils.js:121
    at bindActionCreators.js:3
    at wrap-actions.js:30
    at Object.r (system.js:174)
    at Object.executeRequest (system.js:461)
    at actions.js:442

Rolling back to version 3 makes the upload work again.

**Comment by MelGrubb** [comment]
That is how it's marked up. That's how it was marked up in v3 as well. The only thing that changed was that I updated from v3 to v4, and the upload stopped working. The call doesn't even leave the browser. I think something is broken either in SwaggerUI, or in Swashbuckle's copy of it.

Here is my controller method
```
        [HttpPost("{companyId}/products/upload", Name = "Company_Products_Upload"), SwaggerOperation(Tags = new[] { swaggerTag })]
        [AddSwaggerFileUploadButton]
        [DisableRequestSizeLimit]
        [ProducesResponseType((int)HttpStatusCode.OK)]
        public async Task<ActionResult> UploadAsync(int companyId, IFormFile file)
        {
            var results = await _companyProductService.ImportAsync(CurrentUserId, companyId, file);

            return Ok();
        }
```

**Comment by domaindrivendev** [comment]
What does the `AddSwaggerFileUploadButtonAttribute` do. I'm guessing it's doing something that works around the _lack of file upload support in v3_. This shouldn't be necessary in v4 as file upload is supported out-of-the-box. Try removing it

**Comment by MelGrubb** [comment]
It came from here: https://mattfrear.com/2018/01/02/add-an-upload-button-to-your-swagger-page/
and without it, I didn't get any kind of Upload button at all.

I've made another attempt at upgrading to v4, removed the attribute AND the operation filter from the article, and it seems to be working again. It looks like this can probably be closed, but maybe a mention in the release notes would be helpful for anyone else following the same upgrade path.

**Comment by domaindrivendev** [comment]
It is mentioned in the release notes. Your welcome for the help!

**Comment by MelGrubb** [comment]
Thank you very much. I saw the notes about IFormFile support. I'm thinking more of a note to the effect of "If you used this particular workaround in 3.0, make sure to remove both the attribute and the operation filter or they will interfere with the new mechanism."

**Comment by domaindrivendev** [comment]
Just added the additional note …

> The other notable change with this release is out-of-the-box support for parameters of type IFormFile. That is, the generator will automatically detect these and generate the correct Swagger to describe parameters that are passed in formData. If you have a workaround in place (e.g. using Operation Filters), you should remove it as part of the upgrade.

**Comment by MelGrubb** [comment]
I missed that somehow despite staring directly at it, I swear. Thanks.
