### ISSUE TITLE
Can no longer set operation's summary in an IOperationFilter

### ISSUE THREAD

**Issue by mattfrear** [domaindrivendev/Swashbuckle.AspNetCore#956]
Hi,

A long time ago I wrote an IOperationFilter which appends Authorization information to an operation's summary, as per this screenshot:
![authorization](https://user-images.githubusercontent.com/169179/36599686-1d939bcc-18a8-11e8-8f81-d8706f1f0dc1.JPG)

The full source code for this filter lives here:
https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/blob/master/src/Swashbuckle.AspNetCore.Filters/AppendAuthorizeToSummary/AppendAuthorizeToSummaryOperationFilterT.cs

The gist of it is:
`operation.Summary += "(Auth)";`

I think when I wrote it it was against Swashbuckle.AspNetCore 1.2.0 and it worked fine.
It seems to work fine with Swashbuckle 3.0 if ASP.NET Core 1.1 is targeted. 

But with Swashbuckle 3.0 & ASP.NET Core 2.0 (and of course with Swashbuckle 4.0) it doesn't work _if the operation also has an XML summary_, as per this screenshot:
![ss](https://user-images.githubusercontent.com/43034297/48902017-8a9e5d80-ee57-11e8-9e4f-83e118cfbc72.png)

What I see when I debug with ASP.NET Core 1.1 is that the operation.Summary already has the XML description in it so the `+=` of "Auth" works.
But when I debug with ASP.NET Core 2.0 the operation.Summary is null, so the `+=` of "Auth" happens, but then later on the XML description must be overwriting it.

Parent issue: https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/74

**Comment by domaindrivendev** [comment]
Under the hood, the XML comments functionality is implemented as a set of filters. And, as with all filters - the order in which they’re added matters. You could resolve your issue by ensuring your filter is added _after_ the call to IncludeXmlComments
