### ISSUE TITLE
When I click on one of them, both are open

### ISSUE THREAD

**Issue by quan01994** [domaindrivendev/Swashbuckle.AspNetCore#957]
![image](https://user-images.githubusercontent.com/20533465/49355799-28214900-f704-11e8-920c-8870cebf11f0.png)

When I click on one of them, both are open

Swashbuckle.AspNetCore 4.0.1
Microsoft.NETCore.App 2.1

I use this config to Generate xml.
````xml
 <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <noWarn>1591</noWarn>
  </PropertyGroup>
````

**Comment by boppbo** [comment]
Make sure the methods on your controller have unique names (no overloading). That could fix the issue

**Comment by domaindrivendev** [comment]
This is a dup of #904. See thread there for more details
