### ISSUE TITLE
Dependencies for .NET 4.6.1 (traditional ASP.NET) won't work

### ISSUE THREAD

**Issue by neoaisac** [domaindrivendev/Swashbuckle.AspNetCore#96]
I don't know if the intention will be to keep two branches of development of Swashbuckle in the end, but so you know, the .NET package (NuGet) has dependencies that aren't compatible with 4.6.1 projects, therefore, even though the package is created to target 4.6.1 too, it won't install in projects like that.

It may all go OK once the "prerelease" tag goes away, though, but early awareness of incompatibilities is good.

**Comment by isaacllopisaracil** [comment]
In particular I get:

> Could not install package 'runtime.native.System 4.0.0-rc2-24027'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

for dependency (apparently) of [runtime.native.System 4.0.0-rc2-24027](https://www.nuget.org/packages/runtime.native.System/4.0.0-rc2-24027)

**Comment by TsengSR** [comment]
The Ahoy repository (Swashbuckle.SwaggerGen and Swashbuckle.SwaggerUI) is for ASP.NET Core (formly know as ASP.NET 5 or ASP.NET vNext). 

Use the "Swashbuckle" package for legacy ASP.NET

**Comment by BillDines** [comment]
Hi Guys,

I am using Asp.Net Core but targeting .Net 4.6.1.  The nuget packages up to 6.0.0-beta902 have supported this, but 6.0.0-rc1-final does not.  The error is:

Could not install package 'Swashbuckle.SwaggerUi 6.0.0-rc1-final'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

There are a lot of reasons why you might want to target .Net 4.6.1 in your Asp.Net Core projects, e.g. .Net Core 1.0 is still quite limited and the VS2015 tooling is still immature and prerelease making it hard (for us at least) to integrate into our production build process.  

I hope the intention is to be able to support ASP.Net Core projects that target the full .NET framework in the final released version??

**Comment by TsengSR** [comment]
@BillDines: Ehm... the latest version **is** beta-902. Please read the release dates on https://www.nuget.org/packages/Swashbuckle.SwaggerUi/6.0.0-rc1-final !!!! It's from 7th December **2015**.  The beta-902 is from 14th August 2016!

The rc1-final is a version which was made/compiled against ASP.NET Core RC 1 final  (hence the name), which is a very old version of ASP.NET Core before all the packages got renamed and the last version to use DNX which is obsolete now. 

Use the beta-902 and it will work fine.

**Comment by BillDines** [comment]
@TsengSR Thanks for clearing that up.  In Visual Studio's nuget package manager 6.0.0-rc1-final looks as though it is the latest version and is listed as un update from beta-902.  I must remember not to trust this in the future and check myself before trying to update!

**Comment by TsengSR** [comment]
Well nuget version scheme considers rc to be newer as beta and no surfix to be newer as  rc, which is normally correct. It's just a bit unlucky naming of the Swagger versions to go from the rc1 back to beta w/o a version bump, but that will be sorted out once it gets a stable version

**Comment by domaindrivendev** [comment]
Yep naming is a bit messed up until I get a stable release together ... working on it

**Comment by domaindrivendev** [comment]
Available with latest pre-release. Note the package rename to "Swashbuckle.AspNetCore.1.0.0-rc1"
