### ISSUE TITLE
SerializeAsV2 not available in ASP.NET Core 2.1

### ISSUE THREAD

**Issue by nkalfov** [domaindrivendev/Swashbuckle.AspNetCore#963]
The [readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md) file has to be edited in section [Serialize Swagger in the 2.0 format](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#serialize-swagger-in-the-20-format). There you have stated that the swagger version could be changed from version 3.0 to version 2.0 with the following code:
```cs
app.UseSwagger(c =>
{
    c.SerializeAsV2 = true;
});
```
However, the property `SerializeAsV2 ` cannot be found by Visual Studio IntelliSense. Is the property removed? 

I have installed packages `Swashbuckle.AspNetCore` and `Swashbuckle.AspNetCore.Annotations`. If a package is missing, please, add it to the readme file. If this is available only to specific package version, please, add it to the readme file.

**Comment by domaindrivendev** [comment]
Dup of #961. In summary, the readme was reflecting master as opposed to latest stable version. The long term solution is to move docs over to readthedocs.com. In the meantime, I've updated master branch to maintain README for the latest stable version.
