### ISSUE TITLE
Change in behavior since upgrading to ASP.NET Core 2.2

### ISSUE THREAD

**Issue by SkinnySackboy** [domaindrivendev/Swashbuckle.AspNetCore#965]
Hi,

We have just upgraded our web services to ASP.NET Core 2.2 (previously 2.1) and we have just noticed a slight change in behavior of Swashbuckle.AspNetCore 

Previously, we had plenty of controller API methods attributed with ProducesResponseTypeAttribute. By and large, this has continued to work exactly as it always used to, with one exception since upgrading to netcoreapp2.2

On several of our methods, we use the use the following attribute:
`[ProducesResponseType((int)HttpStatusCode.NotFound)]`

Previously, this used to generate the following:
`"responses": {
          ... ,
          "404": {
            "description": "Not Found"
          }}`

Since having upgraded from ASP.NET Core 2.1 to 2.2 this now generates the following:
`"responses": {
          ... ,
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ProblemDetails"
            }
          }
        }`

I'm not sure why this happens against netcoreapp2.2 but not netcoreapp2.1

To cut a long story short, this is causing an issue further downstream with autorest, because if it detects multiple schema/$ref definitions with differing response types, the C# APIs it generates are no longer the correct type but of type object. This is understandable because object is the only type that ProblemDetails and our own DTO response types actually have in common. Interestingly, specifying the attribute for non-404 status codes without a physical type associated, as in NoContent, has carried on working without issues, e.g. `[ProducesResponseType((int)HttpStatusCode.NoContent)]`

used to and still returns simply:
`"responses": {
          "204": {
            "description": "Success"
          }
        }`

The questions I've got are:

1. Do you know why previously attributing a method with `[ProducesResponseType((int)HttpStatusCode.NotFound)]` wasn't generating ProblemDetails but now is, simply by having switched the compilation target from netcoreapp2.1 to netcoreapp2.2?

2. Is there any way to turn off this behavior/feature?

Thanks in advance.

**Comment by domaindrivendev** [comment]
It looks as if `ApiExplorer`, the ASP.NET Core component that surfaces API metadata, is telling Swashbuckle that the operation will return a model of type [ProblemDetails](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails?view=aspnetcore-2.1) in the event of a 404 response.

I know later version of ASP.NET Core are introducing more API features by convention and it's possible that the endpoint does actually return a serialized `ProblemDetails` in the response body, in which case the docs would be correct. Have you checked if the response does contain anything in the event of a 404?

**Comment by domaindrivendev** [comment]
See the section on entitled "Problem Details support" here - https://blogs.msdn.microsoft.com/webdev/2018/09/12/asp-net-core-2-2-0-preview2-now-available/

**Comment by SkinnySackboy** [comment]
Thank you very much, that explains exactly why this is now happening! Thanks again @domaindrivendev much appreciated.
