### ISSUE TITLE
Authorization Bearer token with version 3.0.0

### ISSUE THREAD

**Issue by tlorton** [domaindrivendev/Swashbuckle.AspNetCore#971]
Hello. Trying get JWT Authorization Bearer token to work for version 3.0.0

It worked in versions 2.*.* before by putting this in the Startup.cs:

           `services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info
                {
                    Title = "API",
                    Description = "API Swagger Documentation"
                });

                c.AddSecurityDefinition("Bearer", new ApiKeyScheme
                {
                    Description = "JWT Authorization header. Example: \"Authorization: Bearer {token}\"",
                    Name = "Authorization",
                    In = "header",
                    Type = "apiKey"
                });

                c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
                {
                    {
                        "Bearer", Enumerable.Empty<string>()
                    }
                });
            });` 

But now it keeps telling me that the "Authorization header is missing". 
I understand that there were some changes to SwaggerGen moving to the Annotations namespace in version 3.0.0. Maybe this caused it? Not sure.

Any help would be greatly appreciated. Thank you.

**Comment by willthiswork89** [comment]
Same issue thats why i came her to see if this has been resolved...looks like it has not been. Same exact setup as you.

**Comment by tlorton** [comment]
FWIW, I guess upgrading to v4.0.* fixed it for us. Not sure why.

**Comment by ronaldhoek** [comment]
Same problem with 5.1.0 and 5.2.1 using the following code:

```C#
public static void AddSwagger(this IServiceCollection services)
{
    services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("v1", new OpenApiInfo
        {
            Version = "V1",
            Title = "Check Api",
            Description = "Api voor Check"
        });
        c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme()
        {
            Description =
                "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
            Name = "Authorization",
            Type = SecuritySchemeType.ApiKey,
            In = ParameterLocation.Header
        });

        var oar = new OpenApiSecurityRequirement();
        oar.Add(new OpenApiSecurityScheme() { BearerFormat = "Bearer" }, new List<string>());
        c.AddSecurityRequirement(oar);
    });
}
```

**Comment by ronaldhoek** [comment]
When you can upgrade to 5.1.x or 5.2.x you can use the following code to get JWT/bearer tokens to work in the SwaggerUI:

```C#
public static void AddSwagger(this IServiceCollection services)
{
    services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("v1", new OpenApiInfo
        {
            Version = "V1",
            Title = "Check Api",
            Description = "Api voor Check"
        });

        c.AddSecurityDefinition("bearerAuth", new OpenApiSecurityScheme()
        {
            Description =
                "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
            Name = "Authorization",
            Type = SecuritySchemeType.ApiKey,
            In = ParameterLocation.Header,
            Scheme = "Bearer"
        });

        var oar = new OpenApiSecurityRequirement();
        oar.Add(
            new OpenApiSecurityScheme
            { 
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "bearerAuth"
                }  
            }, new List<string>());
        c.AddSecurityRequirement(oar);
    });
}

```

Note the fact the `OpenApiSecurityRequirement` uses a reference to the created `OpenApiSecurityScheme` based on the `name`/`Id` applied to it when adding it using `AddSecurityDefinition("bearerAuth",...)`.

Based on examples shown in issue #1022

**Comment by wendellestradairely** [comment]
@ronaldhoek How do you exclude the endpoint that is used to get the bearer token?

**Comment by ronaldhoek** [comment]
> @ronaldhoek How do you exclude the endpoint that is used to get the bearer token?

Remove the `[Authorize]` attribute from the endpoint or add the attribute `[AllowAnonymous]`to specific methods of the endpoint!

BTW this has nothing to do with swagger btw!

**Comment by yekanchi** [comment]
@ronaldhoek is it possible to add a hardcoded bearer token?

**Comment by ronaldhoek** [comment]
Sorry, don't know - never tried that, I was just able to make it functional again....
