### ISSUE TITLE
Issue documenting a paged list object without violating swagger spec

### ISSUE THREAD

**Issue by kgrosvenor** [domaindrivendev/Swashbuckle.AspNetCore#973]
I annotate my controller with the following:
`[ProducesResponseType(200, Type = typeof(PagedList<Item>))]`

The schema ref produces PagedList[Item] and this is invalid to the swagger spec, i haven't tried using the generated code yet, but because of the square brackets I couldn't see it working.

Would it be possible by default to create "PagedListItem", I.E replace both "[" and "]" from all model generation with "" / empty string?

It could be possible to add annotations onto classes to name the ref on the SwaggerOperation directive, this would very useful for generic types and left empty it could use the default class documented as its schema the way it already does

**Comment by domaindrivendev** [comment]
An old issue here that was fixed some time ago. If you try the latest version (`5.6.3` at time of writing), the constructed generic from your example would have the following schema Id by default:

`ItemPagedList`

Furthermore, if you want to provide your own custom strategy (e.g. one that leverages a custom attribute), you can do so as follows:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-schema-ids
