### ISSUE TITLE
When will 5.0.0 officially published?

### ISSUE THREAD

**Issue by bravobobo** [domaindrivendev/Swashbuckle.AspNetCore#975]
Hi Guys!

Very happy to see new Swashbuckle now supports OpenApi 3.0 now!

Quick question: does anyone know when the official 5.0.0 will release instead of beta?

Let me know, thanks!

**Comment by bravobobo** [comment]
cc @domaindrivendev 👍 🥇

**Comment by mattfrear** [comment]
I would like to know an approximate release date @domaindrivendev , as I am trying to update my Swashbuckle.AspNetCore.Filters NuGet package to be 5.0 compatible. 

Since I don't have much spare time and it's a lot of work, hopefully the 5.0 release is a long way away 😁

**Comment by emiliovmq** [comment]
Any news on this? Any tentative date?

**Comment by christophla** [comment]
Would it be possible to publish more beta versions to nuget? The current one is stuck on an old version of redoc that doesn't like OpenAPI 3.0.

**Comment by myshon** [comment]
Is there any migration guide to 5.0.0?

**Comment by mattfrear** [comment]
I notice the code has a few `#if NETCOREAPP3_0`, so I wonder if @domaindrivendev is going to wait until .NET Core 3.0 is no longer in preview? Just speculating...

**Comment by tomkerkhove** [comment]
Any update on this @domaindrivendev? Waiting for .NET Core 3.0 is fine, would be ideal to get an *estimate*.
