### ISSUE TITLE
How to generate an array type? Such as [1,2] instead of "[1,2]"?

### ISSUE THREAD

**Issue by gaoconggit** [domaindrivendev/Swashbuckle.AspNetCore#977]
```
        /// <summary>
        /// kv info
        /// </summary>
        /// <example>[{"key":4,"value":11}]</example>
        public List<KV> skuInfo { get; set; }
```
![image](https://user-images.githubusercontent.com/10905068/50262570-f1119e00-044c-11e9-81d1-c918357973ad.png)

**Comment by domaindrivendev** [comment]
With the latest master code, you can do the following:

```csharp
/// <example>[1,2]</example>
public int[] ArrayProperty { get; set; }
```

This will be available with the upcoming `6.0.0` release, but in the meantime you can pull down the latest perview build from [myget.org](https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) to try it out.
