### ISSUE TITLE
Debug Symbols for releases

### ISSUE THREAD

**Issue by zihotki** [domaindrivendev/Swashbuckle.AspNetCore#978]
I'm reporting the issue for v5-beta but I suppose it's also applicable for other versions. There are no debug symbols for releases which makes it harder to debug. It'd be great to have symbols given that [it's very easy](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) to create and publish them nowadays.

**Comment by CumpsD** [comment]
That would be nice! I had to download the specific tag now, and reference the code in my project to be able to debug

**Comment by martincostello** [comment]
This was done as part of #2775.
