### ISSUE TITLE
Documentation for Web API with conventional routing

### ISSUE THREAD

**Issue by mbpnet** [domaindrivendev/Swashbuckle.AspNetCore#980]
I just tried to use Swagger with an ASP.Net Core Web API project, but it did not find any of my controllers / actions. It turns out to be limitation with swagger, it does not respect conventional/traditional routing.  

Is there any alternate for it? If not, is it prioritized in the list to support in near future.

**Comment by RodrigoRodriguesX10** [comment]
I have the same problem here, I just can't ignore conventional routing (which in .net framework used to work) and changes all controllers to use ApiExplorer and routing attributes. So...
I would like if Swashbuckle has a method that manually add a custom path and settings. Maybe something in app.UseSwagger() that can be easily used to manually add endpoints. So we could iterate the routes generated by conventional rounting and pull it to swagger doc.

**Comment by chsakell** [comment]
I have created [Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting](https://github.com/chsakell/Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting) which adds support for conventional routes. It supports ASP.NET Core **2.2** & ASP.NET Core **3.X** applications.

**Comment by zHaytam** [comment]
Any news on this?

**Comment by domaindrivendev** [comment]
This is not supported nor are there ny plans to do so.
