### ISSUE TITLE
Unable to override model attribute in responses

### ISSUE THREAD

**Issue by jaydeept** [domaindrivendev/Swashbuckle.AspNetCore#981]
I am trying to override Model description in response for my operation using,

```
public void Apply(Schema schema, SchemaFilterContext context)
{
     schema.Properties = new Dictionary<string, Schema>.....
}
```

And I am adding that in object of `SwaggerGenOptions` using `SchemaFilter`. While opening the swagger page, I am getting an error that "Failed to load API definition". This used to work with .Net Framework, is it kind of regression or restriction in .net core?

**Comment by domaindrivendev** [comment]
If SB generates properties, then it's almost certain that your API accepts/emits them so I'm not really sure why you would want to do this.

In any case, I tried a filter similar to your example with the latest version (`5.6.3`) and it works without any issue so I don't think there's a repro of this issue anymore.
