### ISSUE TITLE
Actions require an explicit HttpMethod binding for Swagger 2.0

### ISSUE THREAD

**Issue by HanJunJun** [domaindrivendev/Swashbuckle.AspNetCore#982]
System.NotSupportedException: Ambiguous HTTP method for action - Blog.Core.Controllers.v1.ApbController.Get (Blog.Core). Actions require an explicit HttpMethod binding for Swagger 2.0\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)\r\n   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItems(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Jom.WebApi.Config.ErrorHandlingMiddleware.Invoke(HttpContext context) in

**Comment by HanJunJun** [comment]
![image](https://user-images.githubusercontent.com/16394348/50372412-fd425a80-0608-11e9-92e6-b0b99498fe16.png)

**Comment by HanJunJun** [comment]
![image](https://user-images.githubusercontent.com/16394348/50372422-1ea34680-0609-11e9-89d0-eea90e4e516a.png)

**Comment by HanJunJun** [comment]
I can't call it after [CustomRoute(ApiVersions.v1, "fone")].

**Comment by tahazayed** [comment]
1-remove parameters from HttpGet and let it [HttpGet]
2-add [Route] attribute and add routing parameters to it and it should work

**Comment by devlife** [comment]
@tahazayed's suggestion fxed it for me.
