### ISSUE TITLE
How to turn off models, don't let him show it

### ISSUE THREAD

**Issue by HanJunJun** [domaindrivendev/Swashbuckle.AspNetCore#984]
![image](https://user-images.githubusercontent.com/16394348/50384932-4f69a580-0707-11e9-8bdc-5a7ffadffd12.png)

**Comment by fjzfdsk** [comment]
> 我也在寻找这个选项。我相信问题[＃981](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/981)也可以用这个来解决。可能由于这个模型的东西，我无法覆盖它作为回应。

The author did not reply, I am also looking for a solution

**Comment by HanJunJun** [comment]
> I am also looking for this option. I believe the issue #981 can also be resolved with this. Probably due to this Model stuff, I am unable to override it in response.

I found a way to hide the model and hope to help you.

![image](https://user-images.githubusercontent.com/16394348/50629136-5352be80-0f76-11e9-968f-6a5308d58b09.png)

**Comment by HanJunJun** [comment]
This method was found in the swagger demo.

**Comment by jaydeept** [comment]
Thanks @HanJunJun , This solution is working perfectly.
