### ISSUE TITLE
Inherited Class XML comments does not get pulled through.

### ISSUE THREAD

**Issue by sjnorval** [domaindrivendev/Swashbuckle.AspNetCore#99]
This is more a request than an issue.

I have the following scenario

```
    public class TestSuper : TestBase
    {
        /// <summary>
        /// TEST from super only
        /// </summary>
        public int propSuperOnlyTest { get; set; }

        /// <summary>
        /// TEST from base virtual
        /// </summary>
        public override int propBaseTest { get; set; }
    }
```

```
    public class TestBase
    {
        /// <summary>
        /// TEST from base virtual
        /// </summary>
        public virtual int propBaseTest { get; set; }

        /// <summary>
        /// TEST from base only
        /// </summary>
        public int propBaseOnlyTest { get; set; }
    }
```

TestSuper's propBaseTest  which it overrides from the base class does not inherit the xml comments present in the TestBase. This would be super convenient as it will prevent the xml from needing to be maintained in more than one place. This improvement would also require a check to override the comments if the overridden property also has a comment present. Would this be possible? If it is possible then how do I achieve the desired result.

In a previous version this was touched upon: [https://github.com/domaindrivendev/Swashbuckle/issues/50](url)

**Comment by domaindrivendev** [comment]
I don't have plans to support this functionality - I think it's an edge case and would introduce too much additional complexity to the codebase, in addition to possible performance impacts. The tradeoff doesn't feel right at the moment.
