### ISSUE TITLE
[ApiExplorerSettings(GroupName = "customer,business")]  ?

### ISSUE THREAD

**Issue by gaoconggit** [domaindrivendev/Swashbuckle.AspNetCore#993]
[ApiExplorerSettings(GroupName = "customer,business")]   ?

How to achieve this function?

**Comment by domaindrivendev** [comment]
You'll need to [customize the action selection process](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-the-action-selection-process). The predicate accepts the name of the document being generated and the `ApiDescription` for the action in question, and returns true if it should be included, false if not. You should provide a custom predicate that inspects the `ApiDescription.GroupName` and returns true if the current `docName` is include in the comma separated list.
