### ISSUE TITLE
Unable to inject the custom JavaScript in .Net Core 2.2 

### ISSUE THREAD

**Issue by jaydeept** [domaindrivendev/Swashbuckle.AspNetCore#994]
I have written a `JavaScript` which I would like to inject in `swagger` with **.Net Core 2.2**. I would like to highlight that **wwwroot** folder wasn't created by default when I created web project with .Net Core 2.2. I then created wwwroot folder manually and added my JavaScript file inside that. When I am launching swagger, I am getting an error that file couldn't be loaded. I tried to create a folder inside wwwroot and place a file there but that too didn't work.
Here is my sample code:
```
SwaggerUIOptions uiConfig;
uiConfig.InjectJavascript("mycustomfile.js");
```

Also I would like to highlight what I am trying to achieve here. I got a drop-down in my header for a database provided i.e. `Oracle/MSSQL` etc. Now based on the selection, I wan to change value of another header i.e. connection string. I have written a JavaScript for this purpose but let me know if that can be achieved in some other and simplistic was as well with .Net Core along with `Swashbuckle`.

**Comment by jaydeept** [comment]
I did try to create swagger folder inside wwwroot and placed my JavaScript file there but still no helps.

**Comment by HanJunJun** [comment]
> I have written a `JavaScript` which I would like to inject in `swagger` with **.Net Core 2.2**. I would like to highlight that **wwwroot** folder wasn't created by default when I created web project with .Net Core 2.2. I then created wwwroot folder manually and added my JavaScript file inside that. When I am launching swagger, I am getting an error that file couldn't be loaded. I tried to create a folder inside wwwroot and place a file there but that too didn't work.
> Here is my sample code:
> 
> ```
> SwaggerUIOptions uiConfig;
> uiConfig.InjectJavascript("mycustomfile.js");
> ```
> Also I would like to highlight what I am trying to achieve here. I got a drop-down in my header for a database provided i.e. `Oracle/MSSQL` etc. Now based on the selection, I wan to change value of another header i.e. connection string. I have written a JavaScript for this purpose but let me know if that can be achieved in some other and simplistic was as well with .Net Core along with `Swashbuckle`.

Obviously your path is wrong.
If it is in wwwroot, it should be written like this:
c.InjectJavascript("/swagger-lang.js");

**Comment by jaydeept** [comment]
Hi @HanJunJun , 
I tried that too but still getting an error that failed to load resource. In .Net Framework, we used to provide the assembly and resource file. Something similar is possible here?

**Comment by emilssonn** [comment]
Are you getting an exception or a 404 on the swagger page?
Have you enabled static files?
`public void Configure(IApplicationBuilder app)
{
    app.UseStaticFiles();
}`

**Comment by jaydeept** [comment]
I am facing one more issue though, I got `jQuery` code inside my `JavaScript` file. I am getting below error in console:

> ReferenceError: $ is not defined

I tried to add `<script>` but then I was facing a syntax error for "<".
Amy idea what's going wrong?

**Comment by emilssonn** [comment]
I think that is because Swashbuckle injects the javascript at end of the `<head>` tag, before swagger-ui has been loaded.

**Comment by jaydeept** [comment]
@emilssonn , Ok I see. Is there any way to make it working?

**Comment by emilssonn** [comment]
@jaydeept, I think the only way is to somehow defer the use of jquery until the swagger-ui js is loaded. Maybe some of the answers in https://stackoverflow.com/questions/7486309/how-to-make-script-execution-wait-until-jquery-is-loaded can help?

**Comment by jaydeept** [comment]
@emilssonn , I tried to defer it using options provided in mentioned [page](https://stackoverflow.com/questions/7486309/how-to-make-script-execution-wait-until-jquery-is-loaded) but that too didn't work. Seems like this is a genuine issue.

**Comment by HanJunJun** [comment]
You F12 see if your js is loaded on the head or at the bottom of the page.

**Comment by jaydeept** [comment]
I was able to resolve by adding below lines in my custom JavaScript file:

```
var script = document.createElement("SCRIPT");
script.src = 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js';
script.type = 'text/javascript';
document.getElementsByTagName("head")[0].appendChild(script);
```

However I still believe that this issue should be fixed from Swashbuckle side.

**Comment by domaindrivendev** [comment]
You're using a configuration that gives you full control over the index.html file - so I'm not really sure how your jquery issue can be resolved on the SB side. But, if you have an idea, feel free to submit a PR.
