### ISSUE TITLE
Push out pr #493's changes

### ISSUE THREAD

**Issue by aaronclong** [domaindrivendev/Swashbuckle.AspNetCore#995]
The pr #943 fixes an issue with duplicate produces and consumes types being returned. It was merged over a month ago. I was wonder if you guys could do me a solid and push out a minor version. I know you have already started working on version 5, but I don't think I can wait for that version to be finalized.

**Comment by aaronclong** [comment]
@domaindrivendev If you could give input on this I would really appreciate it.

**Comment by domaindrivendev** [comment]
As a general rule - I don't release hot fixes to old versions. I can barely keep up with milestones of the latest version, let alone worrying about hot fixes against older versions. However, it seems you could solve this for yourself with a very simple Operation Filter.
