### ISSUE TITLE
x-www-form-urlencoded body parameters descriptions are not generated

### ISSUE THREAD

**Issue by Erikvdv** [domaindrivendev/Swashbuckle.AspNetCore#998]
Using AspNetCore 5.0.0-beta:
Descriptions of x-www-form-urlencoded body parameters are not displayed.
Example:
```C#
[HttpPost("api/test")]
[Consumes("application/x-www-form-urlencoded")]
public async Task<IActionResult> Test([FromForm] TestRequest testRequest) {}

public class TestRequest
{
        /// <summary>
        /// this should be the description
        /// </summary>
        public string TestValue { get; set; }
}
```
This works fine when I use the TestRequest class in the query. All other renderings like type and required go fine.

**Comment by pfaustinopt** [comment]
I've found another bug related to this, if instead of [Required] we use [JsonProperty(Required = Required.Always)] it also doesn't work.

**Comment by domaindrivendev** [comment]
@Erikvdv - I believe this works just fine in the latest version - `v5.6.3`.
